### ISSUE TITLE
Uninstalling @angular/cli failes due to an error

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [npm/npm#17107] opened 2017-06-09 06:34 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Uninstalling @angular/cli is producing an error in node v8.1.0.

#### How can the CLI team reproduce the problem?
`npm install -g @angular/cli`
`npm uninstall -g @angular/cli`

Error message:
`$ npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got null strip-json-comments@~2.0.1 fetched in 21ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)`

Gist: https://gist.github.com/StefanNieuwenhuis/0533ad48bdf071ad1f9abec90bc259d8

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X/macOS
 - Network issues:
   - Geographic location where npm was run: The Netherlands
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-06-09 20:40
Does this occur with the latest canary (`npm i -g npmc@latest`)?

**Comment by kkeri** [comment] 2017-06-09 21:55
The same here when trying to uninstall global installation of typescript v2.2.2.
Also with npmc@5.0.3-canary.12.
Windows 10, node v6.3.1
~~~
D:\project\mm\mm-build>npmc uninstall -g typescript
npm notice CANARY npmc is experimental software. If you find an issue, please file it in the main npm repository, and call out that you were using npmc.
Unhandled rejection Error: Argument #2: Expected string but got null09a42734fddd
    at addDependency (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Kalman\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!
~~~

~~~
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Kalman\\AppData\\Roaming\\npm\\node_modules\\npmc\\bin\\npm-cli.js',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@5.0.3-canary.12
3 info using node@v6.3.1
4 notice CANARY npmc is experimental software. If you find an issue, please file it in the main npm repository, and call out that you were using npmc.
5 verbose npm-session beddc061dc2ff240
6 silly install loadCurrentTree
7 silly install readGlobalPackageData
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly uninstall loadAllDepsIntoIdealTree
12 silly install loadAllDepsIntoIdealTree
13 error cb() never called!
14 error This is an error with npm itself. Please report this error at:
15 error <https://github.com/npm/npm/issues>
~~~

**Comment by kenany** [comment] 2017-06-11 23:28
Duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-11 23:28 UTC
Labels: npm5
