### ISSUE TITLE
Error Jade :SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by NGENDAKURIYOLionel** [npm/npm#12257] opened 2016-04-07 11:57 UTC
Hello evryBody, I am tryiing to install jade module but it gives me a an error 
as SyntaxError: Unexpected token 
Here is my debug : 

```
npm http GET https://registry.npmjs.org/express/2.5.8
npm http GET https://registry.npmjs.org/jade
npm http 200 https://registry.npmjs.org/jade
npm http 200 https://registry.npmjs.org/express/2.5.8
npm http GET https://registry.npmjs.org/express/-/express-2.5.8.tgz
npm http 200 https://registry.npmjs.org/express/-/express-2.5.8.tgz
npm WARN engine express@2.5.8: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/mime/1.2.4
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/character-parser/1.2.1
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/clean-css
npm http GET https://registry.npmjs.org/constantinople
npm http GET https://registry.npmjs.org/jstransformer/0.0.2
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/transformers/2.1.0
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/void-elements
npm http GET https://registry.npmjs.org/with
npm http 200 https://registry.npmjs.org/mime/1.2.4
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.4.tgz
npm http 200 https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.0.tgz
npm http 304 https://registry.npmjs.org/clean-css
npm http 200 https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/qs/-/qs-0.4.2.tgz
npm http 304 https://registry.npmjs.org/character-parser/1.2.1
npm http 200 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/constantinople
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/uglify-js
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.0.tgz
npm http 304 https://registry.npmjs.org/jstransformer/0.0.2
npm http 200 https://registry.npmjs.org/connect
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.4.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-1.9.2.tgz
npm http 304 https://registry.npmjs.org/transformers/2.1.0
npm http 200 https://registry.npmjs.org/qs/-/qs-0.4.2.tgz
npm http 304 https://registry.npmjs.org/with
npm http 200 https://registry.npmjs.org/connect/-/connect-1.9.2.tgz
npm http 304 https://registry.npmjs.org/void-elements
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/acorn-globals
npm http GET https://registry.npmjs.org/is-promise
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/css
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http GET https://registry.npmjs.org/yargs
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/acorn-globals
npm http 304 https://registry.npmjs.org/is-promise
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/css
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/css-parse/1.0.4
npm http GET https://registry.npmjs.org/css-stringify/1.0.5
npm http GET https://registry.npmjs.org/asap
npm http GET https://registry.npmjs.org/graceful-readlink
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http 200 https://registry.npmjs.org/yargs
npm http 200 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/formidable
npm http 304 https://registry.npmjs.org/css-parse/1.0.4
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/cliui
npm http GET https://registry.npmjs.org/window-size/0.1.0
npm http GET https://registry.npmjs.org/decamelize
npm http 304 https://registry.npmjs.org/css-stringify/1.0.5
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/window-size/0.1.0
npm http 200 https://registry.npmjs.org/decamelize
npm http 200 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/camelcase
npm http 200 https://registry.npmjs.org/formidable
npm http GET https://registry.npmjs.org/formidable/-/formidable-1.0.17.tgz
npm http 200 https://registry.npmjs.org/cliui
npm http GET https://registry.npmjs.org/wordwrap/0.0.2
npm http GET https://registry.npmjs.org/center-align
npm http GET https://registry.npmjs.org/right-align
npm http 304 https://registry.npmjs.org/asap
npm http 200 https://registry.npmjs.org/formidable/-/formidable-1.0.17.tgz
npm http 200 https://registry.npmjs.org/wordwrap/0.0.2
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/center-align
npm http 200 https://registry.npmjs.org/right-align
npm ERR! SyntaxError: Unexpected token 
�h~LBm<%����Sm@�MDH5>�i�V�$���B"���X�=9�Se<�3 ���*wbř���v*�Թ��i
npm ERR! ��J^�6�]	��-�F�t��c�e�Z��R�*-��_=���t�ˊ?Wo�{�[�Z��ųgW�*�R䣰F��G�(Z��⶛�@>�.��Gv����7Q���'�y��o��}����9�;��ۣS�Dq��XlTE�G�����<�2�a4.������g�4J�SԎtb�qys���i�!X�����^�Dۘ��8<��G<ث~��5.��������s
       ?� �%:����/y6EV�&i+�&�oF�;�T1�3���]
�-�1���|y���/5f                       U�z�Zm�r1��\d���\.敐�Y%�5	���-(�K�������܉Cޫ�����d:�m�W�<���/,���
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/innoveos/Dropbox/Mean_Projects/MeanMVC
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! 
```

Please help me !!
I don't see the problem since i install with no problem other modules

**Comment by sribiere** [comment] 2016-04-07 12:04
You seem to have the same issue as us

`npm install -g npm@1.4.5`

This solved our problem for today (fortunately it allowed us to deliver this week)

**Comment by NGENDAKURIYOLionel** [comment] 2016-04-07 12:16
Hello , I have just made a reboot .
It worked !
Thank you

**Comment by othiym23** [comment] 2016-04-07 16:22
Closing as duplicate of #12196. See that issue for details and current status. Thanks for your patience!

**Closed by othiym23** 2016-04-07 16:22 UTC
Labels: registry, support
