### ISSUE TITLE
when generating MEAN, error occurred

### ISSUE THREAD

**Issue by johnnychusa** [npm/npm#10735] opened 2015-12-08 02:04 UTC
```
Error: Command failed: /bin/sh -c cd mean && npm install
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.1

npm ERR! shasum check failed for /var/folders/rv/h_wtgn5j7klf0ghh_smc9vn00000gn/T/npm-12348-d42a94b5/registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz
npm ERR! Expected: f9ce19bf1909608ceb15d97721e23bfdd1e7cf65
npm ERR! Actual:   d116d9ef4bc5fbd8b25797691996ebfe906976c8
npm ERR! From:     https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz
npm ERR!

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

[npm-debug.log.zip](https://github.com/npm/npm/files/54829/npm-debug.log.zip)

**Comment by zkat** [comment] 2016-12-09 00:50
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:50 UTC
Labels: support
