### ISSUE TITLE
Error when trying to update npm version in nodejs

### ISSUE THREAD

**Issue by doberkofler** [npm/npm#7584] opened 2015-03-10 09:38 UTC
I have been trying to update the local version of npm (as suggested as Option 3 in https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) but do get an error message as follows:

```
C:\Program Files\nodejs>npm install npm
npm ERR! not a package C:\Program Files\nodejs\npm
npm ERR! addLocal Could not install C:\Program Files\nodejs\npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
```

Content of npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'npm', null ]
6 verbose cache add spec npm
7 silly cache add parsed spec { raw: 'npm',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'npm',
7 silly cache add   spec: 'C:\\Program Files\\nodejs\\npm',
7 silly cache add   type: 'local' }
8 silly addLocalTarball shasum (computed) 0fa532e896cc4d8c877453527df2796487f40399
9 verbose addTmpTarball C:\Program Files\nodejs\npm not in flight; adding
10 verbose addTmpTarball validating metadata from C:\Program Files\nodejs\npm
11 verbose tar unpack C:\Program Files\nodejs\npm
12 verbose tar unpacking to C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1
13 verbose gentlyRm vacuuming C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1
14 silly gunzTarPerm modes [ '777', '666' ]
15 error not a package C:\Program Files\nodejs\npm
16 error addLocal Could not install C:\Program Files\nodejs\npm
17 verbose stack Error: ENOENT, open 'C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1\package.json'
17 verbose stack     at Error (native)
18 verbose cwd C:\Program Files\nodejs
19 error Windows_NT 6.1.7601
20 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm"
21 error node v0.12.0
22 error npm  v2.5.1
23 error path C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1\package.json
24 error code ENOENT
25 error errno -4058
26 error enoent ENOENT, open 'C:\Users\DOBERK~1.LBI\AppData\Local\Temp\npm-60452-55b7e2be\unpack-8d2bdeaa63f1\package.json'
26 error enoent This is most likely not a problem with npm itself
26 error enoent and is related to npm not being able to find a file.
27 verbose exit [ -4058, true ]
```

**Comment by smikes** [comment] 2015-03-20 01:23
I think the problem is that `npm` is interpreting the package name argument as a directory, instead of as a package name.  Try

```
> npm install npm@latest
```

That will unambiguously specify a version from the `npm` repository.

**Comment by doberkofler** [comment] 2015-03-20 10:23
@smikes thank you. this worked but i would say this is generally a bug in npm

**Comment by smikes** [comment] 2015-03-20 12:49
At the very minimum this is a bug in the documentation (which I have now changed to say `npm install npm@latest`).

I believe the problem comes because `npm` allows you to specify a package to install in a number of ways, including as a name (from the registry), as a tarball, as a git repository, and as directory.  On Windows, `npm` is installed by the `node` installer under `C:\Program Files\nodejs\npm\` , and so the sequence of commands

```
> cd C:\Program Files\nodejs
> npm install npm
```

is ambiguous between the meanings `npm install npm@latest` (the package from the registry) and `npm install .\npm` (the subdirectory of the current directory).

So with all of that said, what can be done to fix the bug?  I am kind of leaning towards requiring a path to contain either the character `.` or a path separator (`/` on Unix, `\` or `/` on Windows), but that would be a break in backwards-compatibility.

**Comment by doberkofler** [comment] 2015-03-20 16:26
@smikes Changing the documentation is for sure helpful. Given the fact that by for installation will probably be done from the registry, I find your solution quite reasonable. Eventually this could also be restricted to the npm package.

**Comment by iarna** [comment] 2015-04-12 18:26
Closing as resolved.

**Closed by iarna** 2015-04-12 18:26 UTC
Labels: support, windows
