### ISSUE TITLE
Cannot install ionic

### ISSUE THREAD

**Issue by olamieUsman** [npm/npm#12869] opened 2016-05-27 09:33 UTC
Here is the issue I am having here

![npm](https://cloud.githubusercontent.com/assets/11750102/15604128/64bb123a-23f6-11e6-882b-6df3a951cef0.PNG)

**Comment by KenanY** [comment] 2016-05-27 18:04
@olamieUsman Have you tried running `npm cache clean`?

**Comment by olamieUsman** [comment] 2016-05-29 18:03
Yes, I did that several times. @KenanY

**Comment by zkat** [comment] 2016-12-09 00:57
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:57 UTC
Labels: shasum, support, windows
