### ISSUE TITLE
npm install --save git+https://* add wrong entry to package.json

### ISSUE THREAD

**Issue by Moeriki** [npm/npm#9873] opened 2015-10-07 09:31 UTC
`npm --version`

3.3.5

STEPS

``` bash
npm install --save git+https://myrepo.com/stash/scm/myproject/my-project.git
```

EXPECTED `package.json`

``` json
{
  "dependencies": {
    "my-project": "git+https://myrepo.com/stash/scm/myproject/my-project.git"
  }
}
```

ACTUAL `package.json`

``` json
{
  "dependencies": {
    "my-project": "https://myrepo.com/stash/scm/myproject/my-project.git"
  }
}
```

Could this possibly a bug?

I noticed ACTUAL when I ran `npm install`afterwards again for some other reason, and it failed contacting this repo.

**Comment by KenanY** [comment] 2015-10-07 15:04
Might be a dupe of https://github.com/npm/npm/issues/9679, https://github.com/npm/npm/issues/9732 (`git+` being removed).

**Closed** 2017-06-19 10:33 UTC
Labels: bot-closed, bug, git
