### ISSUE TITLE
npm 5.0.1 removing github dependencies from package-lock.json during install

### ISSUE THREAD

**Issue by jakepusateri** [npm/npm#16887] opened 2017-06-01 19:10 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm is not installing git dependencies correctly from a package-lock.json file.

#### How can the CLI team reproduce the problem?
`npm install braintree-web`
Then copy over package.json and package-lock.json into a new directory (mimicking what a build machine git clone might do).
`npm install`

The modules `browser-detection`, `iframer`, and `wrap-promise` will be missing from the install.
Additionally, the package-lock.json will have been modified to remove these dependencies.

https://gist.github.com/jakepusateri/87288f835d7cc5443928951bc1edbbde

### supporting information:

 - `npm -v` prints:
5.0.1
 - `node -v` prints:
v8.0.0
 - `npm config get registry` prints:
http://znpm.in.zillow.net:31050/ (internal npme)
 - Windows, OS X/macOS, or Linux?:
linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mikemaccana** [comment] 2017-06-01 19:33
I have a similar issue with npm 5.0.1 removing required, already-installed `private: true` packages.

**Comment by schmod** [comment] 2017-06-01 19:39
Likely a duplicate of #16839.

**Comment by zkat** [comment] 2017-06-01 21:35
Closing as a dupe of #16839 -- there's a few others with "missing dependency" reports but I'll triage those out on another pass.

**Closed as completed by zkat** 2017-06-01 21:35 UTC
Labels: installer, npm5
