### ISSUE TITLE
Error while installing ionic through npm

### ISSUE THREAD

**Issue by chaitanyaphanikumar** [npm/npm#16467] opened 2017-04-28 15:06 UTC
I've the below error while installing ionic through npm. Any suggestions are really appreciated..

C:>npm install -g ionic cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic" "cordova"
npm ERR! node v7.9.0
npm ERR! npm v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\JMP829\AppData\Roaming\npm-cache_logs\2017-04-28T14_38_13
_697Z-debug.log

**Comment by legodude17** [comment] 2017-04-28 16:27
Duplicate of #10686.

**Comment by KenanY** [comment] 2017-04-29 03:16
@chaitanyaphanikumar Could you upload the full debug log file to <https://gist.github.com/> and post the link to the gist here?

**Comment by KenanY** [comment] 2017-05-30 17:11
Closing due to no reply after a month.

**Closed by KenanY** 2017-05-30 17:11 UTC
Labels: support
