### ISSUE TITLE
Feature Request: add ability for arrays of scripts.

### ISSUE THREAD

**Issue by nkt** [npm/npm#8943] opened 2015-07-14 22:38 UTC
npm-scripts is very powerful tool, but not friendly for the sequence of commands. I suggest to concatenate array of commands into sequence:
```json
"scripts": {
  "prepublish": [
    "npm test",
    "rm -rf build",
    "npm run build"
  ]
}

```
For this config npm should run `npm test && rm -rf build && npm run build` before publish.

**Comment by othiym23** [comment] 2015-07-14 23:57
My feeling is that this complicates what should be a pretty simple feature, and recently we've been trying to convert fields in `package.json` that can be multiple different types to only accept a single type. So, I'm weakly -1 on this proposal as-is. The current best practice about doing more complicated run-scripts is to break them down into multiple pieces and then string them together: `"npm test && npm run clean && npm run build"`, which shouldn't ever get too complicated.

**Comment by KenanY** [comment] 2015-07-15 02:52
Duplicate of https://github.com/npm/npm/issues/6943?

**Comment by othiym23** [comment] 2015-07-15 03:34
> Duplicate of #6943?

Yes, thanks for noticing. Closing as duplicate!

**Closed by othiym23** 2015-07-15 03:34 UTC
Labels: feature-request
