### ISSUE TITLE
`npm ls` fails on shrink-wrapped packages that have nested subdependencies whose versions are set to "" (empty string).

### ISSUE THREAD

**Issue by lxe** [npm/npm#11493] opened 2016-02-10 22:35 UTC
Tough one to explain but easy to reproduce:
#### Description

Some packages are published with some of their dependency versions set to `""` (empty string). For example `follow-redirects@0.0.3`, who sets 'underscore' dependency to `""`:

```
$ npm info follow-redirects@0.0.3 dependencies
{ underscore: '' }
```

If we shrinkwrap a package whose dependency chain contain such modules, and then run npm install on it (after removing / with no previously existing `node_modules` tree), `npm ls` command will fail with `invalid`.
#### Procedure

Let's create a shrink-wrap with npm v2 (deep dependencies) or just force deep tree with another version of underscore at the top of our tree:

**package.json**

```
{
  "name": "shrinkwrap-fail",
  "version": "1.0.0",
  "dependencies": {
    "follow-redirects": "0.0.3",
    "underscore": "1.0.3"
  }
}
```

Let's run `npm install`, followed by `npm ls`:

```
$ npm install
...
shrinkwrap-fail@1.0.0 /Users/aleksey/shrinkwrap-fail
├─┬ follow-redirects@0.0.3
│ └── underscore@1.8.3
└── underscore@1.0.3

$ npm ls
shrinkwrap-fail@1.0.0 /Users/aleksey/shrinkwrap-fail
├─┬ follow-redirects@0.0.3
│ └── underscore@1.8.3
└── underscore@1.0.3
```

Everything looks good!

For further debugging purpose, let's examine the generated `package.json` of `underscore@1.8.3` :

```
$ head -n10 node_modules/follow-redirects/node_modules/underscore/package.json
{
  "_args": [
    [
      "underscore@",
      "/Users/aleksey/shrinkwrap-fail/node_modules/follow-redirects"
    ]
  ],
  "_from": "underscore@latest",
  "_id": "underscore@1.8.3",
  "_inCache": true,
```

Let's now create a `npm-shrinkwrap.json`:

```
$ npm shrinkwrap
wrote npm-shrinkwrap.json
```

Now, blow away `node_modules`, and run `npm install` to regenerate the module tree from the shrinkwrap:

```
$ rm -rf node_modules
$ npm install
....
├─┬ follow-redirects@0.0.3
│ └── underscore@1.8.3
└── underscore@1.0.3
```

It succeeds, however, `npm ls` shows `underscore@1.8.3 invalid`:

```
$ npm ls
shrinkwrap-fail@1.0.0 /Users/aleksey/shrinkwrap-fail
├─┬ follow-redirects@0.0.3
│ └── underscore@1.8.3 invalid
└── underscore@1.0.3

npm ERR! invalid: underscore@1.8.3 /Users/aleksey/shrinkwrap-fail/node_modules/follow-redirects/node_modules/underscore
```

Let's examine the generated `package.json` of `underscore@1.8.3` again to compare:

```
$ head -n10 node_modules/follow-redirects/node_modules/underscore/package.json
{
  "_args": [
    [
      "underscore@https://registry.npmjs.org/underscore/-/underscore-1.8.3.tgz",
      "/Users/aleksey/shrinkwrap-fail/node_modules/follow-redirects"
    ]
  ],
  "_from": "underscore@latest",
  "_id": "underscore@1.8.3",
  "_inCache": true,
```

Looks like it's no longer using the `""` (empty string) version to create the package spec, which in turn probably causes npm ls to fail.

**Comment by tkornblit** [comment] 2016-04-25 04:08
Also experiencing a bug here. It seems that the "npm list" command is not syncing up with the npm-shrinkwrap.json file.

I think the solution here is that you need to have "npm list" command include the npm-shrinkwrap.json file in it's analysis.

**Comment by deepsweet** [comment] 2016-08-31 10:44
same here, it also fails to update `npm-shrinkwrap.json`:

```
$ npm shrinkwrap

...

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have commander@2.9.0 (expected: ) test/node_modules/cfb/node_modules/commander
npm ERR! extraneous: commander@2.9.0 test/node_modules/cfb/node_modules/commander
npm ERR! invalid: have commander@2.9.0 (expected: ) test/node_modules/codepage/node_modules/commander
npm ERR! extraneous: commander@2.9.0 test/node_modules/codepage/node_modules/commander
npm ERR! invalid: have commander@2.9.0 (expected: ) test/node_modules/xlsjs/node_modules/commander
npm ERR! extraneous: commander@2.9.0 test/node_modules/xlsjs/node_modules/commander
npm ERR! invalid: have commander@2.9.0 (expected: ) test/node_modules/xlsx/node_modules/commander
npm ERR! extraneous: commander@2.9.0 test/node_modules/xlsx/node_modules/commander
```

because one of sub-modules has `commander: ""` in its `package.json`

```
$ npm ls commander

...

├─┬ alasql@0.2.7
│ ├─┬ xlsjs@0.7.5
│ │ ├─┬ cfb@0.10.3
│ │ │ └── commander@2.9.0  invalid
│ │ ├─┬ codepage@1.3.8
│ │ │ └── commander@2.9.0  invalid
│ │ └── commander@2.9.0  invalid
│ └─┬ xlsx@0.8.0
│   └── commander@2.9.0  invalid
```

**Comment by nhtera** [comment] 2016-09-19 08:18
I've same issue with xlsx package. Has anyone found a solution for this issue?

**Comment by joshkel** [comment] 2016-09-23 18:30
I'm seeing the same problem when I install [ascli](https://github.com/dcodeIO/ascli), which depends on "colour@latest" and "optjs@latest". As I understand it, "" is equivalent to "latest", so this is another symptom of the same bug.

**Comment by JordanBelford** [comment] 2016-11-14 19:48
Has anyone seen this bug with npm 4? I am not always able to reproduce this one, but I didn't see it when running npm 4.0.2. Not sure if it was fixed or if it was just chance.

**Comment by legodude17** [comment] 2016-11-14 21:08
My best guess is that somewhere in `npm`, a check is like `if (pkg.dependencies[name])` and then `""` is falsy. That wouldn't explain your issue @joshk.

**Comment by mifi** [comment] 2017-01-11 10:03
I updated npm to latest 3 version (3.10.10), and that seems to have solved the issue for me. So maybe it has been fixed by an unknown commit and now all these issues can be closed?

**Closed** 2017-06-19 10:09 UTC
Labels: bot-closed, bug, shrinkwrap
