### ISSUE TITLE
Unable to do npm install: Registry returned 401 for GET 

### ISSUE THREAD

**Issue by tangledfruit** [npm/npm#12758] opened 2016-05-18 21:55 UTC
Trying to install a (public) module of mine in another project yields an unexpected error:

npm-debug.log contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/tangledfruit/.nvm/versions/node/v6.1.0/bin/node',
1 verbose cli   '/Users/tangledfruit/.nvm/versions/node/v6.1.0/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData rxjs
20 silly mapToRegistry name rxjs
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'rxjs',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   name: 'rxjs',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/rxjs
25 silly fetchNamedPackageData rxjs-fetch
26 silly mapToRegistry name rxjs-fetch
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'rxjs-fetch',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   name: 'rxjs-fetch',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/rxjs-fetch
31 verbose request uri https://registry.npmjs.org/rxjs
32 verbose request always-auth set; sending authorization
33 info attempt registry request try #1 at 2:49:12 PM
34 verbose request id f8bf0816d5d03123
35 http request GET https://registry.npmjs.org/rxjs
36 verbose request uri https://registry.npmjs.org/rxjs-fetch
37 verbose request always-auth set; sending authorization
38 info attempt registry request try #1 at 2:49:12 PM
39 http request GET https://registry.npmjs.org/rxjs-fetch
40 http 401 https://registry.npmjs.org/rxjs-fetch
41 verbose headers { 'content-type': 'application/json',
41 verbose headers   'cache-control': 'max-age=300',
41 verbose headers   'content-length': '2',
41 verbose headers   'accept-ranges': 'bytes',
41 verbose headers   date: 'Wed, 18 May 2016 21:49:12 GMT',
41 verbose headers   via: '1.1 varnish',
41 verbose headers   connection: 'keep-alive',
41 verbose headers   'x-served-by': 'cache-dfw1830-DFW',
41 verbose headers   'x-cache': 'MISS',
41 verbose headers   'x-cache-hits': '0',
41 verbose headers   'x-timer': 'S1463608152.935029,VS0,VE58',
41 verbose headers   vary: 'Accept-Encoding' }
42 silly get cb [ 401,
42 silly get   { 'content-type': 'application/json',
42 silly get     'cache-control': 'max-age=300',
42 silly get     'content-length': '2',
42 silly get     'accept-ranges': 'bytes',
42 silly get     date: 'Wed, 18 May 2016 21:49:12 GMT',
42 silly get     via: '1.1 varnish',
42 silly get     connection: 'keep-alive',
42 silly get     'x-served-by': 'cache-dfw1830-DFW',
42 silly get     'x-cache': 'MISS',
42 silly get     'x-cache-hits': '0',
42 silly get     'x-timer': 'S1463608152.935029,VS0,VE58',
42 silly get     vary: 'Accept-Encoding' } ]
43 silly fetchPackageMetaData Error: Registry returned 401 for GET on https://registry.npmjs.org/rxjs-fetch
43 silly fetchPackageMetaData     at makeError (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
43 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
43 silly fetchPackageMetaData     at Request._callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
43 silly fetchPackageMetaData     at Request.self.callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
43 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
43 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
43 silly fetchPackageMetaData     at Request.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
43 silly fetchPackageMetaData     at emitOne (events.js:101:20)
43 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
43 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:963:12)
43 silly fetchPackageMetaData  error for rxjs-fetch@^2.1.0 { Error: Registry returned 401 for GET on https://registry.npmjs.org/rxjs-fetch
43 silly fetchPackageMetaData     at makeError (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
43 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
43 silly fetchPackageMetaData     at Request._callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
43 silly fetchPackageMetaData     at Request.self.callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
43 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
43 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
43 silly fetchPackageMetaData     at Request.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
43 silly fetchPackageMetaData     at emitOne (events.js:101:20)
43 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
43 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:963:12) pkgid: 'rxjs-fetch', statusCode: 401, code: 'E401' }
44 http 401 https://registry.npmjs.org/rxjs
45 verbose headers { 'content-type': 'application/json',
45 verbose headers   'cache-control': 'max-age=300',
45 verbose headers   'content-length': '2',
45 verbose headers   'accept-ranges': 'bytes',
45 verbose headers   date: 'Wed, 18 May 2016 21:49:13 GMT',
45 verbose headers   via: '1.1 varnish',
45 verbose headers   connection: 'keep-alive',
45 verbose headers   'x-served-by': 'cache-dfw1832-DFW',
45 verbose headers   'x-cache': 'MISS',
45 verbose headers   'x-cache-hits': '0',
45 verbose headers   'x-timer': 'S1463608153.460550,VS0,VE55',
45 verbose headers   vary: 'Accept-Encoding' }
46 silly get cb [ 401,
46 silly get   { 'content-type': 'application/json',
46 silly get     'cache-control': 'max-age=300',
46 silly get     'content-length': '2',
46 silly get     'accept-ranges': 'bytes',
46 silly get     date: 'Wed, 18 May 2016 21:49:13 GMT',
46 silly get     via: '1.1 varnish',
46 silly get     connection: 'keep-alive',
46 silly get     'x-served-by': 'cache-dfw1832-DFW',
46 silly get     'x-cache': 'MISS',
46 silly get     'x-cache-hits': '0',
46 silly get     'x-timer': 'S1463608153.460550,VS0,VE55',
46 silly get     vary: 'Accept-Encoding' } ]
47 silly fetchPackageMetaData Error: Registry returned 401 for GET on https://registry.npmjs.org/rxjs
47 silly fetchPackageMetaData     at makeError (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
47 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
47 silly fetchPackageMetaData     at Request._callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
47 silly fetchPackageMetaData     at Request.self.callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
47 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
47 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
47 silly fetchPackageMetaData     at Request.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
47 silly fetchPackageMetaData     at emitOne (events.js:101:20)
47 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
47 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:963:12)
47 silly fetchPackageMetaData  error for rxjs@>=5.0.0-beta.6 { Error: Registry returned 401 for GET on https://registry.npmjs.org/rxjs
47 silly fetchPackageMetaData     at makeError (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
47 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
47 silly fetchPackageMetaData     at Request._callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
47 silly fetchPackageMetaData     at Request.self.callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
47 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
47 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
47 silly fetchPackageMetaData     at Request.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
47 silly fetchPackageMetaData     at emitOne (events.js:101:20)
47 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
47 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:963:12) pkgid: 'rxjs', statusCode: 401, code: 'E401' }
48 silly rollbackFailedOptional Starting
49 silly rollbackFailedOptional Finishing
50 silly runTopLevelLifecycles Starting
51 silly runTopLevelLifecycles Finishing
52 silly install printInstalled
53 verbose stack Error: Registry returned 401 for GET on https://registry.npmjs.org/rxjs-fetch
53 verbose stack     at makeError (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
53 verbose stack     at CachingRegistryClient.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
53 verbose stack     at Request._callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
53 verbose stack     at Request.self.callback (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
53 verbose stack     at emitTwo (events.js:106:13)
53 verbose stack     at Request.emit (events.js:191:7)
53 verbose stack     at Request.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
53 verbose stack     at emitOne (events.js:101:20)
53 verbose stack     at Request.emit (events.js:188:7)
53 verbose stack     at IncomingMessage.<anonymous> (/Users/tangledfruit/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/request/request.js:963:12)
54 verbose statusCode 401
55 verbose pkgid rxjs-fetch
56 verbose cwd /Users/tangledfruit/Projects/my-project
57 error Darwin 15.4.0
58 error argv "/Users/tangledfruit/.nvm/versions/node/v6.1.0/bin/node" "/Users/tangledfruit/.nvm/versions/node/v6.1.0/bin/npm" "install"
59 error node v6.1.0
60 error npm  v3.8.6
61 error code E401
62 error Registry returned 401 for GET on https://registry.npmjs.org/rxjs-fetch
63 error If you need help, you may report this error at:
63 error     <https://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]
```

**Comment by lxe** [comment] 2016-05-18 22:03
You have `always-auth` config set to true:

```
32 verbose request always-auth set; sending authorization
```

Remove it or set it to false in your `~/.npmrc`

**Comment by othiym23** [comment] 2016-05-18 22:37
I haven't been able to reproduce this, with `always-auth` set to `true`, and with the same versions of the CLI and Node.js. Are you accessing the registry via a proxy? That's inconsistent with the registry headers in your debug log, but I'm unsure what else could be causing this behavior (I've asked @npm/registry-team for their input, and pending their feedback, I may redirect you over to [`npm/registry`](https://github.com/npm/registry/issues)).

**Comment by scouten** [comment] 2016-05-18 22:47
Boom. That was it. I had an `~/.npmrc` file that pointed to a private npm registry (at my employer) and it did have `always-auth` set to `true`. I renamed the file to set it aside and the problem went away.

What's interesting is that that same `~/.npmrc` file has been there for almost a year and, as recently as yesterday, I had never had a problem with it. Anything change recently on registry.npmjs.org WRT enforcement of authorization?

**Comment by lxe** [comment] 2016-05-19 17:48
@othiym23 interesting:

```
$ npm info npm version --always-auth=true --loglevel=info --progress=false
npm info it worked if it ends with ok
npm info using npm@3.9.2
npm info using node@v0.10.42
npm info attempt registry request try #1 at 10:45:53
npm info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
```

However, if npm caches it first by hitting the endpoint until it no longer makes http requests:

```
$ npm info npm version --always-auth=false --loglevel=info --progress=false
npm info it worked if it ends with ok
npm info using npm@3.9.2
npm info using node@v0.10.42
npm info attempt registry request try #1 at 10:46:23
npm http request GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
3.9.0
npm info ok

$ npm info npm version --always-auth=false --loglevel=info --progress=false
npm info it worked if it ends with ok
npm info using npm@3.9.2
npm info using node@v0.10.42
3.9.0
npm info ok
```

The next call with `always-auth=true` will succeed, since no http calls are made:

```
 $ npm info npm version --always-auth=true --loglevel=info --progress=false
npm info it worked if it ends with ok
npm info using npm@3.9.2
npm info using node@v0.10.42
3.9.0
npm info ok
```

**Comment by othiym23** [comment] 2016-05-19 18:20
@lxe that latter behavior (info succeeding because the metadata is cached) is known, and sort of a "lol distributed systems / cache invalidation" problem that we may or may not get around to addressing during the cache rewrite (it's sort of a footgun for users of private packages who are surprised / alarmed when they can still see packages they think they shouldn't be after they change access to their packages or dev teams).

Here's the script I was using:

```bash
mkdir test-rxjs-lol
cd test-rxjs-lol/
npm init -y
~/bin/nave use 6.1.0 npm i -g npm@3.8.6
~/bin/nave use 6.1.0 npm install rxjs-fetch --always-auth
# no problems
rm package.json
rm -r node_modules/
npm init -y
~/bin/nave use 6.1.0 npm cache clean rxjs-fetch
# being thorough, because `cache clean` doesn't remove the header metadata:
rm -r ~/.npm/registry.npmjs.org/rxjs-fetch/
~/bin/nave use 6.1.0 npm config set always-auth true
~/bin/nave use 6.1.0 npm install -S rxjs-fetch
# still no problems
```

It could be an `npm view` vs `npm install` situation, but @scouten's problem was happening at install time.

**Comment by othiym23** [comment] 2016-05-19 18:21
@scouten (are you the same user as @tangledfruit?) I've asked the registry team if they changed how this behavior worked, and it seems that they haven't. If I hear to the contrary, I'll let you know. Is this resolved to your satisfaction now?

**Comment by scouten** [comment] 2016-05-19 20:26
(Yes, daytime me vs after-hours me. 😉) I'm OK with closing this. Setting aside `~/.npmrc` resolved my issue for now. (I had forgotten about the auth info I had entered there many months ago.)

**Comment by othiym23** [comment] 2016-05-19 20:28
Closing as resolved.

**Closed by othiym23** 2016-05-19 20:28 UTC
Labels: proxy, registry, support
