### ISSUE TITLE
`npm -g outdated` and local/linked packages that aren't in the registry

### ISSUE THREAD

**Issue by halhenke** [npm/npm#10054] opened 2015-10-21 01:37 UTC
At the moment if you use `npm ln` to use a local package that you are working on and you then call outdated globally to look at the general state of global packages npm will stop and print something like

```
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/caper-activities
npm ERR! 404
npm ERR! 404 'caper-activities' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
 without providing any info on other packages. You can check packages individually to avoid this but this is obv a pain.

Would seem desirable to me that npm would note this (perhaps less verbosely) and continue to provide info on outdated packages. I'm not sure if there are future plans for `npm ln` or something else in terms of being the proper way to develop multiple packages locally (would love it if someone could point me in that direction if so) but at the moment it can be a bit painful IMO - though obv thats another discussion.

**Comment by KenanY** [comment] 2015-10-21 04:38
Possibly a duplicate of https://github.com/npm/npm/issues/8752.

**Comment by halhenke** [comment] 2015-10-21 04:50
Yeah pretty much - didnt realise this was a bug/used to work differently.

**Comment by othiym23** [comment] 2015-10-21 05:17
Closing as a duplicate of #8752. There's definitely more work to be done to smooth the rough edges of working with local and linked dependencies.

**Closed by othiym23** 2015-10-21 05:17 UTC

**Comment by halhenke** [comment] 2015-10-21 15:28
Re those questions - is there a gitter/slack channel for discussion of npm development?

**Comment by othiym23** [comment] 2015-10-22 14:47
There's #npm on Freenode IRC, where the npm CLI team will be paying attention during West Coast US hours.

**Comment by halhenke** [comment] 2015-10-23 05:56
Awesome thanks Forrest - very interested in the local/linked dependency thing and what might be done in the future...
