### ISSUE TITLE
allow `preversion` and `version` scripts to add files to the commit

### ISSUE THREAD

**Issue by jamestalmage** [npm/npm#8620] opened 2015-06-19 19:52 UTC
The `git version` command is useful if all you need to do is bump the value in package.json. If you try to generate/compile any files as part of your release process, then it complains:

```
npm ERR! Error: Git working directory not clean.
```

I think it should work (something) like this

  1. Check to make sure the git working directory is clean before running any scripts (scripts in future steps may add files to the commit without throwing an error).
  2. Run the `preversion` script. These scripts have access to the old `version` in package.json. Any files you want added to the commit should be explicitly added using `git add`.
  3. Bump `version` in `package.json`. 
  4. Run the `version` script. Scripts here have access to the new `version` in package.json (so they can incorporate it into file headers in generated files for example). Again, scripts should explicitly add files using `git add`.
  5. Commit and tag
  6. Run the `postversion` script.

The most important part is being able to easily incorporate generated files as part of the commit that will be tagged, and easy access to what that version number was / will be.

**Comment by othiym23** [comment] 2015-06-24 21:25
This sounds like a great idea, with exactly this spec. If you wanted to turn this into a PR, it would be extremely welcome. :+1:

**Comment by thejameskyle** [comment] 2015-06-24 22:27
I was just about to ask for the same thing. I've implemented it for now like this:

https://github.com/thejameskyle/a-damn-nice-test-repo/blob/master/package.json#L8

```json
"preversion": "[[ -z $(git status --porcelain) ]] && npm run build && git add -A dist && git commit -m 'Build lib'"
```

It would be nice if I could just do:

```json
"preversion": "npm run build && git add -A dist"
```

**Comment by jasonkarns** [comment] 2015-06-25 14:14
Is it necessary that the working directory actually be clean before proceeding? As a user, if I didn't have any `preversion` or `version` scripts, I wouldn't feel it necessary to ensure a clean working directory just to bump my package version. Instead of checking for clean working directory, perhaps all that should be checked is the index? Since modified files won't be committed unless explicitly added by scripts, I would think that a clean index is all that should be ensured prior to running `version`.

**Comment by jamestalmage** [comment] 2015-06-25 14:25
Even without any scripts, the `version` command already adds, commits, and tags the `package.json` file after it modifies it. It's fairly common practice that "publish v0.0.0" commits contain only modification to package.json and auto-generated files (files which you **only** update when committing a new release).

If there are existing edits, that means you are (possibly) modifying existing behavior in the same commit. By common practice that really should be two commits.

Perhaps it would be worthwhile to add some sort of flag for skipping that step. My ideas are: `--force` / `--skip-check` / `--skip-git-check`.

**Comment by jasonkarns** [comment] 2015-06-25 14:30
> If there are existing edits, that means you are (possibly) modifying existing behavior in the same commit.

This doesn't make sense if the edits are excluded from the commit. Which is precisely what I'm describing. I'm assuming that this PR only commits files that are explicitly added to the index. (We aren't doing `git commit -a` in this PR are we?)

So if the only files that get committed (along with the bumped package.version) are files that are explicitly added to the index as part of preversion/version scripts, then there is no chance that a non-staged edit gets included in the commit. Hence, no reason to ensure clean working dir (only a clean index).

**Comment by rlidwka** [comment] 2015-06-25 14:30
I think npm should exclude `git add`'ed files in "not clean" check and commit them when user runs `npm version`.

So the workflow for the release would be:

```sh
$ vim ChangeLog.md
$ git add ChangeLog.md
$ npm version
```

And the resulting commit would look like that: https://github.com/rlidwka/sinopia/commit/93245c0179524874fea574db1da48d1c68e6d0a2 (yes, I'm using this workflow for a year now).

This would only require a change in `lib/version.js`, something like [this](https://github.com/rlidwka/yapm/blob/d2f85d7ee27be37c248ddd110ee77d5d6682ce88/lib/version.js#L129-L138).

**Comment by jasonkarns** [comment] 2015-06-25 14:32
I do like the `--force` flag, however, to override whatever git checking does finally remain. (whether it's clean working dir guard or clean index guard)

**Comment by jamestalmage** [comment] 2015-06-25 14:46
> So if the only files that get committed (along with the bumped package.version) are files that are explicitly added to the index as part of preversion/version scripts, then there is no chance that a non-staged edit gets included in the commit. Hence, no reason to ensure clean working dir (only a clean index).

Take `"version" : "npm run build && git add -A dist"`, and some file `lib/fancy-module.js`, that contribute to the generated files in `dist/`. If you've modified `lib/fancy-module.js` but excluded it from the commit, those changes will be reflected in the generated files for the commit (and be part of your distribution for that release), but the actual changes to the source will get committed after the tag. That's almost certainly not what you want. If you've got some changes you don't want to be part of the release, the proper thing to do is shelve them before cutting the release.

**Comment by jasonkarns** [comment] 2015-06-25 14:49
Note that in my original comment I said:

> As a user, if I didn't have any preversion or version scripts

So given the exact same edited files as you described: `lib/fancy-module.js`, without a custom `version` script, then `npm version` would complain for no reason.

**Comment by jamestalmage** [comment] 2015-06-25 14:52
@othiym23 
Happy to add `--force` tag (or whatever) to this PR if you wish.

**Comment by jamestalmage** [comment] 2015-06-25 14:59
@jasonkarns 
Fair enough. I still think it's worth having the default behavior be as described, with an option to force it. It's pretty rare that I want to bump a version while I've got pending source changes. Failing by default makes ensures I double check what I'm doing.

**Comment by jasonkarns** [comment] 2015-06-25 15:02
So it seems that the only scenario where a clean working directory is important is iff additional files will be included in the commit.

Perhaps we should define 'clean_working_directory` to mean only modified-unstaged files. And then
perhaps we should check if the working directory is clean and save the result. And then only bail at the `version` step if `working_directory_dirty && files_in_index_other_than_package_json`.

This way:
- staged edits can be committed (like changelog, etc)
- a dirty working copy is fine if no extra files (aside from package.json) are to be committed.
- clean working copy (defined as no unstaged edits) is ensured if extra files are to be committed.

I believe this covers all the desired scenarios?

**Comment by jamestalmage** [comment] 2015-06-25 17:34
> staged edits can be committed (like changelog, etc)

I am not sure about this. I think guarding against changes being accidentally committed is worthwhile (and has minimal downside for your use case if we incorporate a force tag).

> a dirty working copy is fine if no extra files (aside from package.json) are to be committed

I am least opposed to this idea, though it still seams like shelving changes or using `--force` is the way to go here. What scenario is this for? All I can think of is: "Hey I just patched that bug in the last commit, and started working on something I just realized is a new feature. I should release that previous work as a `patch` release, and this current work as a `minor` one". If that's what you are thinking - it's basically the text book scenario for gits shelve changes feature.

> clean working copy (defined as no unstaged edits) is ensured if extra files are to be committed.

That's what we've already go... So I agree. :grin:

**Comment by jamestalmage** [comment] 2015-06-25 17:34
> staged edits can be committed (like changelog, etc)

I am not sure about this. I think guarding against changes being accidentally committed is worthwhile (and has minimal downside for your use case if we incorporate a force tag).

> a dirty working copy is fine if no extra files (aside from package.json) are to be committed

I am least opposed to this idea, though it still seams like shelving changes or using `--force` is the way to go here. What scenario is this for? All I can think of is: "Hey I just patched that bug in the last commit, and started working on something I just realized is a new feature. I should release that previous work as a `patch` release, and this current work as a `minor` one". If that's what you are thinking - it's basically the text book scenario for gits shelve changes feature.

> clean working copy (defined as no unstaged edits) is ensured if extra files are to be committed.

That's what we've already go... So I agree. :grin:

**Comment by jamestalmage** [comment] 2015-06-25 17:51
How about this, allow additional arguments to the version command

    npm version [<newversion> | <semver-arg>] [options] [files]

allowing for
  
    npm version patch -m "releasing %m" Changelog.md dist/

This way we are explicitly saying which files are OK to be dirty going into the process. I think this this especially useful for changelogs - where you may want to manually edit them and inserting that in a build script would be difficult. I see no reason we couldn't automatically `git add` those files for you either.

Perhaps there could also be a `release-files` property of `package.json` so you could set some default values for this.

    {"release-files": ["Changelog.md", "dist/"]}

**Comment by jasonkarns** [comment] 2015-06-25 19:44
explicitly listing files in the command is intriguing, as is having a release-files property in package.json.

My main rationale for suggesting we do the extra work is to ensure that, by default, without any flags or configuration or extra args, it does the right thing with the least amount of thought.

Having unstaged edits in the working copy has zero effect on the release if the only file committed is package.json. Agree? Whether or not it's recommended isn't really relevant because it has no technical impact one way or the other.

With my proposal, the least amount of effort is required of the user. If they wish to bump with a dirty working copy, that's fine. It can't hurt. We'll already be guarding against the case where they patch a bug, generate a build in a `preversion` script, and assume the patch is included in the release. (Which is the only case where having a dirty working copy is harmful.)

I find this a much nicer user experience because this reduces the requirements on the user when executing the command.

So a modified version of my proposal:

- complete successfully if there are no *staged* edits (either manual or result of preversion/version script)
- error out if there are unstaged edits **and** staged edits (either manual or result of script)
- `--force` flag (or similar) overrides this guard
- staged edits (and potentially unstaged if we decide to `git add` automatically) will be committed without `--force` flag only if they are listed explicitly on the command line or in `releaseFiles` array in package.json

This proposal does all the things we want. No file gets into the repo accidentally, and it doesn't put any extra burden on the user to have some special working copy state just to bump the version.

**Comment by jamestalmage** [comment] 2015-06-25 20:26
The "fail on unclean" behavior goes back at least two years. I don't see why we would introduce a breaking change when `--force` solves the problem so easily.

**Comment by jasonkarns** [comment] 2015-06-25 20:51
Breaking change is debateable. It's a relaxing change, not a hardening change. And the functional result of the change is 0. (no files would be committed)

Again, the use case for `--force` is clear. And is still necessary in my proposal. However, my proposal makes possible the easiest use of the command with the fewest requirements on the user (which IMO is a more friendly API).

Simply require `--force` at all times actually leads to an *increased* chance of an invalid state commit because it would be required *any time* there are local modifications, even if those local modifications aren't intended to be committed.

**Comment by jamestalmage** [comment] 2015-06-25 21:07
The docs have promised it will fail with an error since at least 2013.

`--force` would not be required if you do not have a dirty tree. Ignored and untracked files don't count as "dirty". Explicitly listing the "allowed dirty" files will avoid the trap of always requiring `--force` if you want to commit manually edited changelogs, etc.

**Comment by rlidwka** [comment] 2015-06-25 22:26
Is there any reason not to commit staged files and error out instead? You can't accidentally stage something, can you?

Because to me it looks like npm doesn't differentiate between staged and unstaged only because implementation is buggy, and we ought to fix that.

**Comment by jamestalmage** [comment] 2015-06-25 23:05
> You can't accidentally stage something, can you?

WebStorm will do it to you.

**Comment by othiym23** [comment] 2015-06-26 01:34
> Is it necessary that the working directory actually be clean before proceeding?

Yes, for the sake of simplicity and not violating the principle of least surprise: If you have a dirty working directory, what should npm do? Should it add untracked files? Should it commit staged changes? Should it add and commit unstaged changes? @jasonkarns, your proposal is well laid out, and it makes sense in context, but it's not necessarily the behavior a lot of users would intuit. Erroring out with an informative error message is friendlier, IMO, than forcing people to read the docs to understand what's happening and why. Requiring the directory to be clean before allowing lifecycle scripts to dirty it up again is a simple, consistent, easy-to-understand model, even if it is less convenient.

I'm fine with allowing `--force` to override the behavior, inasmuch as the docs already make very clear that `--force` is basically a footgun with a hair trigger.

**Comment by jamestalmage** [comment] 2015-06-26 02:07
@othiym23 
Thoughts on exempting files via the command line or `package.json`?
(See my comment 8 or 9 comments above this one)

I do see some value in having a way to tell it to let  (for example) `Changes.md` past the check.

**Comment by othiym23** [comment] 2015-06-26 02:14
> Thoughts on exempting files via the command line

That's complicated.

> or `package.json`.

See above.

As originally stated, this is a useful refinement, and complicating it with configuration and command-line options would take that and turn it into a complicated niche feature. Please keep it simple, and if it turns out it's infeasibly inflexible, it will be easier to relax the rules later than to try to make them stricter.

**Comment by jasonkarns** [comment] 2015-06-26 13:33
@othiym23 

> Should it add untracked files? Should it commit staged changes? Should it add and commit unstaged changes? [...] Requiring the directory to be clean before allowing lifecycle scripts to dirty it up again is a simple, consistent, easy-to-understand model, even if it is less convenient.

This makes me think my suggestion isn't clear. Because the *only* time that I propose `--force` not be required is when *no additional files* will be committed. So the use for `--force` is unnecessary because the resulting commit would be identical as if I had done `git clean -df && npm version`.

To reiterate, I'm only suggesting the `--force` flag be optional when there are unstaged edits *and* no scripts add any additional files to the commit. So in the case where scripts add files to the index, we would still error out with the unclean message. I fail to see why that would require any reading of the docs. It's the exact same resulting commit as if I had a clean working directory in the first place.

I'm fine calling the discussion closed, however, and letting the first implementation go. My change is only a minor relaxation on the `--force` requirement and could be added later if we find enough momentum to do so. (Apparently I'm the only one on this thread that's already super annoyed every time I do an `npm version` and get the "unclean" error message.)

**Closed** 2015-07-01 10:00 UTC
Labels: feature-request, next-minor, patch-welcome

**Comment by oncletom** [comment] 2015-07-02 16:40
That's an excellent idea :-) amazing to generate CHANGELOG as part of the release under the appropriate tag. ACE :+1:

**Comment by tkissing** [comment] 2015-07-18 04:14
Love this feature. Is it (going to be) in v2 as well as v3?
I am personally on 3.1.2 but most of the team (and CI) are still on 2.x

**Comment by othiym23** [comment] 2015-07-18 04:15
It was landed in `npm@2` first, I believe. So yes, it's there.

**Comment by tkissing** [comment] 2015-07-18 05:04
Thanks, confirmed with 2.13.1! This is awesome!

**Comment by UltCombo** [comment] 2015-07-26 01:58
Awesome work guys!

Can we have some clarification in the docs as to what happens when files are created during the `preversion` and `version` scripts but not `git add`ed?

Also, what happens if we edit the `package.json` as part of the `preversion` script? A common use case would be:

```js
"scripts": {
  "preversion": "npm update --save some-dependency"
}
```

Will this fail the `npm version` command if we do not `git add package.json`? I'm not sure what is the expected/current behavior here.

**Comment by ryexley** [comment] 2015-07-26 02:20
So, this is the only thread I've found that seems relevant to what I'm trying to accomplish. I'm currently using npm 2.13.2 (just upgraded to it to see if it would fix my problem but it doesn't seem to have).

I have the following scripts in my `package.json` file:

```json
{
  ...
  "scripts": {
    "build": "gulp build",
    "test": "./node_modules/mocha/bin/mocha spec/some-module.spec.js",
    "preversion": "npm test",
    "version": "npm run build",
    "postversion": "git push && git push --tags && npm publish"
  }
  ...
}
```

My expectation (and desire) here is that when I run `npm version patch -m "v%s"`, `gulp build` will run webpack and generate two new UMD modules to the `dist/` folder (one uncompressed and one minified) and stamp each one with a banner that includes the updated version number, etc. Once that is complete, I _was hoping_ that the commit that the `version` task performs would _include_ these changes, and push and publish the updated module version.

However, in reality, everything _but_ committing the updates to those two files in `dist/` is happening, so a new module is getting published with non-updated modules. Am I misunderstanding how this can/should work? Is there any way I can get around this and include those files in the commit?

Any clarification or guidance would be greatly appreciated. Thank you.

**Comment by UltCombo** [comment] 2015-07-26 02:26
@ryexley You should explicitly `git add` the generated files that you want to be committed, as extensively mentioned in this issue and the [docs](https://docs.npmjs.com/cli/version). E.g.:

```json
""version": "npm run build && git add -A dist"
```

**Comment by ryexley** [comment] 2015-07-26 02:30
Yeah, I should have been more clear. Those generated files don't get _created_ as part of the build, they get _modified_, so adding them does nothing more than stage them. I tried that initially, but they still didn't get included in the commit (I'm guessing because they're not new files getting created, but rather are already versioned files just getting modified). Hope that helps.

**Comment by UltCombo** [comment] 2015-07-26 02:32
Oh that's odd. My interpretation of the docs is that all staged changes (`git add`ed) made in the `preversion`/`version` scripts would be committed as part of the version commit.

**Comment by ryexley** [comment] 2015-07-26 02:38
I agree, but nothing I try seems to actually work, which is why I'm asking the question. The result is always that the two files in `dist/` get modified by the `build` task called in `version` but do _not_ get included in the commit, and remain marked as "modified" by git after successful completion of the task.

**Comment by dreyescat** [comment] 2015-07-26 10:01
@ryexley I have a similar procedure to generate a *lib* folder with both compressed and uncompressed versions of my UMD library. The `version` script in my [package.json](https://github.com/dreyescat/react-rating/blob/master/package.json) works fine. The added changes are properly committed along with the version bump all in the same commit.

```json
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "webpack-dev-server --progress --colors --port 8080",
    "build": "webpack --progress && webpack -p --output-filename react-rating.min.js --progress",
    "version": "npm run build && git add -A lib",
    "postversion": "git push && git push --tags"
  },
```

As @UltCombo suggested, make sure you `git add -A dist` your new/modified files in the `version` script.

Make sure you are using npm >=[2.13.0](https://github.com/npm/npm/releases/tag/v2.13.0), as this `version` functionality was introduced in [version: allow scripts to add files to the commit](https://github.com/npm/npm/commit/582f170).

**Comment by ryexley** [comment] 2015-07-26 15:35
@dreyescat you are absolutely right. I hadn't tried using `git add -A dist/` _after_ I upgraded to version `2.13.2`. I went back and tried it again, and now it works and is doing what I expected it would. Thanks for reminding me of that.

**Comment by oncletom** [comment] 2015-07-27 06:09
@ryexley also, consider adding the dist files at `prepublish` to have them in the npm package but not in git.

**Comment by JaKXz** [comment] 2015-07-29 21:20
@ryexley @dreyescat I'm having a similar problem with modified rather than created files, where the modified files and my `package.json` is not being committed and the tag is not being created like the docs say they will be in step 5. My `version` and `postversion` scripts look just like yours @dreyescat, and I'm using `npm@2.13.2` with this config:

```bash
$ npm config ls -l | grep git
git-tag-version = true
sign-git-tag = false
git = "git"
```

and `git version 2.5.0`. I'm using the command: `npm version minor -m "upgrade to %s for reasons"`

What ends up happening is when `git push && git push --tags` is called, since a commit hasn't been created, git responds with `Everything up-to-date` which is correct as far as git is concerned, since my modified files are only staged:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   index.html
	modified:   package.json
```
