### ISSUE TITLE
"Update available" message shown while updating npm

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [npm/npm#18444] opened 2017-09-07 17:26 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm told me a new update was available, so I did `npm i -g npm`, however in the same command it printed the same update available message after npm had been updated

![screen shot 2017-09-07 at 1 23 56 pm](https://user-images.githubusercontent.com/25586630/30176301-f52f2b36-93cf-11e7-9d0e-0555647e9907.png)

#### How can the CLI team reproduce the problem?
install npm 5.4.0 and try to upgrade to 5.4.1

### supporting information:
macOS latest stable
node 8.3.0
npm 5.4.0

**Comment by kenany** [comment] 2017-09-07 17:44
Duplicate of #18443 (admittedly, by only a few minutes 😄 )

**Closed as completed by kenany** 2017-09-07 17:44 UTC
