### ISSUE TITLE
npm install Error: Missing Required Argument #2

### ISSUE THREAD

**Issue by afflicto** [npm/npm#10271] opened 2015-11-05 09:07 UTC
When I run "npm install" I get an error.

Here's the npm-debug.log

	0 info it worked if it ends with ok
	1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
	2 info using npm@3.3.6
	3 info using node@v5.0.0
	4 silly loadCurrentTree Starting
	5 silly install loadCurrentTree
	6 silly install readLocalPackageData
	7 silly install normalizeTree
	8 verbose stack Error: Missing required argument #2
	8 verbose stack     at exports.findRequirement (/usr/lib/node_modules/npm/lib/install/deps.js:475:3)
	8 verbose stack     at /usr/lib/node_modules/npm/lib/install/deps.js:90:19
	8 verbose stack     at zalgoSafe (/usr/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:20:10)
	8 verbose stack     at finalize (/usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:37:5)
	8 verbose stack     at /usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:22:20
	8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
	9 verbose cwd /home/petter/dev/www/friluft
	10 error Linux 3.19.0-31-generic
	11 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
	12 error node v5.0.0
	13 error npm  v3.3.6
	14 error code EMISSINGARG
	15 error typeerror Error: Missing required argument #2
	15 error typeerror     at exports.findRequirement (/usr/lib/node_modules/npm/lib/install/deps.js:475:3)
	15 error typeerror     at /usr/lib/node_modules/npm/lib/install/deps.js:90:19
	15 error typeerror     at zalgoSafe (/usr/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:20:10)
	15 error typeerror     at finalize (/usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:37:5)
	15 error typeerror     at /usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:22:20
	15 error typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
	15 error typeerror This is an error with npm itself. Please report this error at:
	15 error typeerror     <http://github.com/npm/npm/issues>
	16 verbose exit [ 1, true ]

This is my package.json:

    {
      "private": true,
      "devDependencies": {
        "coffee-script": "^1.9.2",
        "event-stream": "^3.3.0",
        "gulp": "^3.8.8",
        "gulp-autoprefixer": "^2.3.1",
        "gulp-coffee": "^2.3.1",
        "gulp-concat": "^2.5.2",
        "gulp-order": "^1.1.1",
        "gulp-sass": "^1.3.3",
        "gulp-util": "^3.0.4",
        "laravel-elixir": "*"
      },
      "dependencies": {
        "afflicto/gentlestyle": "^2.4.11",
        "jquery": "^2.1.4"
      }
    }

Ubuntu 14.04 LTS x64. Installed from instructions at https://github.com/nodesource/distributions#debinstall

**Comment by othiym23** [comment] 2015-11-06 19:29
Closing as duplicate of #9270. Thanks for the report!

**Comment by othiym23** [comment] 2015-11-06 19:30
Whoops! Unrelated issue!

**Comment by othiym23** [comment] 2015-11-06 19:31
_Actually_ this is a duplicate of #9669, and is fixed by upgrading to a newer version of npm using `npm update -g npm@latest`.

**Closed by othiym23** 2015-11-06 19:31 UTC

**Comment by TheVoidSeeker** [comment] 2015-11-11 12:02
I still have the problem with relative paths after updating to npm@latest.

e.g. "../bm-common": "1.0.0" results in Error: Missing required argument #2
