### ISSUE TITLE
windows user error

### ISSUE THREAD

**Issue by Mafmudin** [npm/npm#14668] opened 2016-11-19 04:36 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/ionic
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 11:06:56
24 verbose request id 535d484744baa94d
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 11:06:57
29 http request GET https://registry.npmjs.org/ionic
30 http 200 https://registry.npmjs.org/ionic
31 verbose headers { server: 'nginx/1.10.1',
31 verbose headers   'content-type': 'application/json',
31 verbose headers   'last-modified': 'Thu, 17 Nov 2016 20:16:03 GMT',
31 verbose headers   etag: 'W/"582e1003-c489d"',
31 verbose headers   'content-encoding': 'gzip',
31 verbose headers   'cache-control': 'max-age=300',
31 verbose headers   'content-length': '45015',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Sat, 19 Nov 2016 04:07:00 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   age: '191',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-hkg6820-HKG',
31 verbose headers   'x-cache': 'HIT',
31 verbose headers   'x-cache-hits': '18',
31 verbose headers   'x-timer': 'S1479528420.612551,VS0,VE0',
31 verbose headers   vary: 'Accept-Encoding' }
32 silly get cb [ 200,
32 silly get   { server: 'nginx/1.10.1',
32 silly get     'content-type': 'application/json',
32 silly get     'last-modified': 'Thu, 17 Nov 2016 20:16:03 GMT',
32 silly get     etag: 'W/"582e1003-c489d"',
32 silly get     'content-encoding': 'gzip',
32 silly get     'cache-control': 'max-age=300',
32 silly get     'content-length': '45015',
32 silly get     'accept-ranges': 'bytes',
32 silly get     date: 'Sat, 19 Nov 2016 04:07:00 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     age: '191',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-hkg6820-HKG',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '18',
32 silly get     'x-timer': 'S1479528420.612551,VS0,VE0',
32 silly get     vary: 'Accept-Encoding' } ]
33 verbose get saving ionic to C:\Users\9\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
34 verbose correctMkdir C:\Users\9\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
35 verbose makeDirectory C:\Users\9\AppData\Roaming\npm-cache creation not in flight; initializing
36 verbose makeCacheDir UID & GID are irrelevant on win32
37 http 200 https://registry.npmjs.org/cordova
38 verbose headers { server: 'nginx/1.10.1',
38 verbose headers   'content-type': 'application/json',
38 verbose headers   'last-modified': 'Sat, 19 Nov 2016 02:53:50 GMT',
38 verbose headers   etag: 'W/"582fbebe-f1033"',
38 verbose headers   'content-encoding': 'gzip',
38 verbose headers   'cache-control': 'max-age=300',
38 verbose headers   'content-length': '37399',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   date: 'Sat, 19 Nov 2016 04:07:00 GMT',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   age: '0',
38 verbose headers   connection: 'keep-alive',
38 verbose headers   'x-served-by': 'cache-hkg6823-HKG',
38 verbose headers   'x-cache': 'HIT',
38 verbose headers   'x-cache-hits': '1',
38 verbose headers   'x-timer': 'S1479528420.603526,VS0,VE174',
38 verbose headers   vary: 'Accept-Encoding' }
39 silly get cb [ 200,
39 silly get   { server: 'nginx/1.10.1',
39 silly get     'content-type': 'application/json',
39 silly get     'last-modified': 'Sat, 19 Nov 2016 02:53:50 GMT',
39 silly get     etag: 'W/"582fbebe-f1033"',
39 silly get     'content-encoding': 'gzip',
39 silly get     'cache-control': 'max-age=300',
39 silly get     'content-length': '37399',
39 silly get     'accept-ranges': 'bytes',
39 silly get     date: 'Sat, 19 Nov 2016 04:07:00 GMT',
39 silly get     via: '1.1 varnish',
39 silly get     age: '0',
39 silly get     connection: 'keep-alive',
39 silly get     'x-served-by': 'cache-hkg6823-HKG',
39 silly get     'x-cache': 'HIT',
39 silly get     'x-cache-hits': '1',
39 silly get     'x-timer': 'S1479528420.603526,VS0,VE174',
39 silly get     vary: 'Accept-Encoding' } ]
40 verbose get saving cordova to C:\Users\9\AppData\Roaming\npm-cache\registry.npmjs.org\cordova\.cache.json
41 verbose correctMkdir C:\Users\9\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
42 silly install normalizeTree
43 silly loadCurrentTree Finishing
44 silly loadIdealTree Starting
45 silly install loadIdealTree
46 silly cloneCurrentTree Starting
47 silly install cloneCurrentTreeToIdealTree
48 silly cloneCurrentTree Finishing
49 silly loadShrinkwrap Starting
50 silly install loadShrinkwrap
51 silly loadShrinkwrap Finishing
52 silly loadAllDepsIntoIdealTree Starting
53 silly install loadAllDepsIntoIdealTree
54 silly resolveWithNewModule ionic@2.1.12 checking installable status
55 silly cache add args [ 'ionic', null ]
56 verbose cache add spec ionic
57 silly resolveWithNewModule cordova@6.4.0 checking installable status
58 silly cache add args [ 'cordova', null ]
59 verbose cache add spec cordova
60 silly cache add parsed spec Result {
60 silly cache add   raw: 'ionic',
60 silly cache add   scope: null,
60 silly cache add   escapedName: 'ionic',
60 silly cache add   name: 'ionic',
60 silly cache add   rawSpec: '',
60 silly cache add   spec: 'latest',
60 silly cache add   type: 'tag' }
61 silly addNamed ionic@latest
62 verbose addNamed "latest" is being treated as a dist-tag for ionic
63 info addNameTag [ 'ionic', 'latest' ]
64 silly mapToRegistry name ionic
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry https://registry.npmjs.org/
67 silly mapToRegistry data Result {
67 silly mapToRegistry   raw: 'ionic',
67 silly mapToRegistry   scope: null,
67 silly mapToRegistry   escapedName: 'ionic',
67 silly mapToRegistry   name: 'ionic',
67 silly mapToRegistry   rawSpec: '',
67 silly mapToRegistry   spec: 'latest',
67 silly mapToRegistry   type: 'tag' }
68 silly mapToRegistry uri https://registry.npmjs.org/ionic
69 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
70 silly cache add parsed spec Result {
70 silly cache add   raw: 'cordova',
70 silly cache add   scope: null,
70 silly cache add   escapedName: 'cordova',
70 silly cache add   name: 'cordova',
70 silly cache add   rawSpec: '',
70 silly cache add   spec: 'latest',
70 silly cache add   type: 'tag' }
71 silly addNamed cordova@latest
72 verbose addNamed "latest" is being treated as a dist-tag for cordova
73 info addNameTag [ 'cordova', 'latest' ]
74 silly mapToRegistry name cordova
75 silly mapToRegistry using default registry
76 silly mapToRegistry registry https://registry.npmjs.org/
77 silly mapToRegistry data Result {
77 silly mapToRegistry   raw: 'cordova',
77 silly mapToRegistry   scope: null,
77 silly mapToRegistry   escapedName: 'cordova',
77 silly mapToRegistry   name: 'cordova',
77 silly mapToRegistry   rawSpec: '',
77 silly mapToRegistry   spec: 'latest',
77 silly mapToRegistry   type: 'tag' }
78 silly mapToRegistry uri https://registry.npmjs.org/cordova
79 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
80 verbose get https://registry.npmjs.org/ionic not expired, no request
81 silly addNameTag next cb for ionic with tag latest
82 silly addNamed ionic@2.1.12
83 verbose addNamed "2.1.12" is a plain semver version for ionic
84 verbose get https://registry.npmjs.org/cordova not expired, no request
85 silly addNameTag next cb for cordova with tag latest
86 silly addNamed cordova@6.4.0
87 verbose addNamed "6.4.0" is a plain semver version for cordova
88 silly mapToRegistry name ionic
89 silly mapToRegistry using default registry
90 silly mapToRegistry registry https://registry.npmjs.org/
91 silly mapToRegistry data Result {
91 silly mapToRegistry   raw: 'ionic',
91 silly mapToRegistry   scope: null,
91 silly mapToRegistry   escapedName: 'ionic',
91 silly mapToRegistry   name: 'ionic',
91 silly mapToRegistry   rawSpec: '',
91 silly mapToRegistry   spec: 'latest',
91 silly mapToRegistry   type: 'tag' }
92 silly mapToRegistry uri https://registry.npmjs.org/ionic
93 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz not in flight; adding
94 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz',
94 verbose addRemoteTarball   'e0102b764d589a09e9cbd432c338d9c539feeebe' ]
95 silly mapToRegistry name cordova
96 silly mapToRegistry using default registry
97 silly mapToRegistry registry https://registry.npmjs.org/
98 silly mapToRegistry data Result {
98 silly mapToRegistry   raw: 'cordova',
98 silly mapToRegistry   scope: null,
98 silly mapToRegistry   escapedName: 'cordova',
98 silly mapToRegistry   name: 'cordova',
98 silly mapToRegistry   rawSpec: '',
98 silly mapToRegistry   spec: 'latest',
98 silly mapToRegistry   type: 'tag' }
99 silly mapToRegistry uri https://registry.npmjs.org/cordova
100 verbose addRemoteTarball https://registry.npmjs.org/cordova/-/cordova-6.4.0.tgz not in flight; adding
101 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-6.4.0.tgz',
101 verbose addRemoteTarball   '3fd9e8b9ad77a6a93ec76947704de21ac2991776' ]
102 info retry fetch attempt 1 at 11:06:59
103 info attempt registry request try #1 at 11:06:59
104 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
105 info retry fetch attempt 1 at 11:06:59
106 info attempt registry request try #1 at 11:06:59
107 http fetch GET https://registry.npmjs.org/cordova/-/cordova-6.4.0.tgz
108 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
109 http fetch 200 https://registry.npmjs.org/cordova/-/cordova-6.4.0.tgz
110 silly fetchAndShaCheck shasum 3fd9e8b9ad77a6a93ec76947704de21ac2991776
111 verbose addTmpTarball C:\Users\9\AppData\Local\Temp\npm-6112-b8c7a16d\registry.npmjs.org\cordova\-\cordova-6.4.0.tgz not in flight; adding
112 verbose addTmpTarball already have metadata; skipping unpack for cordova@6.4.0
113 verbose correctMkdir C:\Users\9\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
114 silly cache afterAdd cordova@6.4.0
115 verbose afterAdd C:\Users\9\AppData\Roaming\npm-cache\cordova\6.4.0\package\package.json not in flight; writing
116 verbose correctMkdir C:\Users\9\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
117 verbose afterAdd C:\Users\9\AppData\Roaming\npm-cache\cordova\6.4.0\package\package.json written
118 info retry will retry, error on last attempt: Error: read ECONNRESET
119 silly fetchAndShaCheck shasum e0102b764d589a09e9cbd432c338d9c539feeebe
120 silly rollbackFailedOptional Starting
121 silly rollbackFailedOptional Finishing
122 silly runTopLevelLifecycles Finishing
123 silly install printInstalled
124 verbose stack Error: shasum check failed for C:\Users\9\AppData\Local\Temp\npm-6112-b8c7a16d\registry.npmjs.org\ionic\-\ionic-2.1.12.tgz
124 verbose stack Expected: e0102b764d589a09e9cbd432c338d9c539feeebe
124 verbose stack Actual:   dae1a832b286021297deea94e40e7b43b5a52615
124 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
124 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
124 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
124 verbose stack     at emitNone (events.js:91:20)
124 verbose stack     at ReadStream.emit (events.js:185:7)
124 verbose stack     at endReadableNT (_stream_readable.js:974:12)
124 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
124 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
125 verbose cwd C:\Users\9
126 error Windows_NT 10.0.10240
127 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
128 error node v6.9.1
129 error npm  v3.10.8
130 error shasum check failed for C:\Users\9\AppData\Local\Temp\npm-6112-b8c7a16d\registry.npmjs.org\ionic\-\ionic-2.1.12.tgz
130 error Expected: e0102b764d589a09e9cbd432c338d9c539feeebe
130 error Actual:   dae1a832b286021297deea94e40e7b43b5a52615
130 error From:     https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
131 error If you need help, you may report this error at:
131 error     <https://github.com/npm/npm/issues>
132 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2016-11-29 01:28
Please check your internet connection. Then try running `npm cache clean ionic`.

**Comment by zkat** [comment] 2016-12-02 04:46
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:46 UTC
Labels: network, shasum, support
