### ISSUE TITLE
NPM 3 moves duplicate dependencies when installing from local file system

### ISSUE THREAD

**Issue by briansokol** [npm/npm#10383] opened 2015-11-13 19:50 UTC
The error occurs when you have a saved dependency that exists on your local file system and you try to reinstall it again from local. This will cause any dependencies that the two modules share in common to be removed entirely. I've set up a repo as an example.

https://github.com/briansokol/npm-install-error

I've seen this behavior in npm since at least 3.3.9, probably earlier. Currently running npm 3.4.0 and node 5.0.0 on El Capitan.

To test, first install dependencies for *test-project-1*:

    cd test-project-1
    npm install
    npm ls
  
You'll see all the dependencies have been installed correctly:

    npm-install-error/test-project-1
    ├── js-cookie@2.0.4
    ├── lodash@3.10.1
    ├── object-assign@4.0.1
    └─┬ react@0.14.2
      ├─┬ envify@3.4.0
      │ ├─┬ jstransform@10.1.0
      │ │ ├── base62@0.1.1
      │ │ ├── esprima-fb@13001.1001.0-dev-harmony-fb
      │ │ └─┬ source-map@0.1.31
      │ │   └── amdefine@1.0.0
      │ └── through@2.3.8
      └─┬ fbjs@0.3.2
        ├── core-js@1.2.6
        ├─┬ loose-envify@1.1.0
        │ └── js-tokens@1.0.2
        ├─┬ promise@7.0.4
        │ └── asap@2.0.3
        ├── ua-parser-js@0.7.9
        └── whatwg-fetch@0.9.0
    
Next, install *test-project-2* into *test-project-1*, saving it as a dependency:

    npm install ../test-project-2 --save
    npm ls
    
You'll see that *test-project-2* was correctly installed:

    npm-install-error/test-project-1
    ├── js-cookie@2.0.4
    ├── lodash@3.10.1
    ├── object-assign@4.0.1
    ├─┬ react@0.14.2
    │ ├─┬ envify@3.4.0
    │ │ ├─┬ jstransform@10.1.0
    │ │ │ ├── base62@0.1.1
    │ │ │ ├── esprima-fb@13001.1001.0-dev-harmony-fb
    │ │ │ └─┬ source-map@0.1.31
    │ │ │   └── amdefine@1.0.0
    │ │ └── through@2.3.8
    │ └─┬ fbjs@0.3.2
    │   ├── core-js@1.2.6
    │   ├─┬ loose-envify@1.1.0
    │   │ └── js-tokens@1.0.2
    │   ├─┬ promise@7.0.4
    │   │ └── asap@2.0.3
    │   ├── ua-parser-js@0.7.9
    │   └── whatwg-fetch@0.9.0
    └─┬ test-project-2@1.0.0
      ├── classnames@2.2.0
      └── underscore@1.8.3
    
Now, install *test-project-2* again:

    npm install ../test-project-2
    npm ls
    
You'll see that the dependencies these two modules share in common have been removed.

    npm-install-error/test-project-1
    ├── UNMET DEPENDENCY js-cookie@^2.0.4
    ├── lodash@3.10.1
    ├── UNMET DEPENDENCY object-assign@^4.0.1
    ├── UNMET DEPENDENCY react@^0.14.2
    └── test-project-2@1.0.0

    npm ERR! missing: js-cookie@^2.0.4, required by test-project-1@1.0.0
    npm ERR! missing: object-assign@^4.0.1, required by test-project-1@1.0.0
    npm ERR! missing: react@^0.14.2, required by test-project-1@1.0.0

**EDIT**: I confirmed that missing dependencies are not entirely removed, but have been moved from the root node_modules directory (in test-project-1) into the node_modules of the package that was installed (test-project-2). This makes them inaccessible to test-project-1.

**Comment by KenanY** [comment] 2015-11-13 20:06
This might be a duplicate of https://github.com/npm/npm/issues/10258 but I haven't completely looked into it.

**Comment by briansokol** [comment] 2015-11-13 20:14
Yes, that's it, or very close to it. So, contrary to what I originally stated, the dependencies aren't removed entirely. They're just moved into *test-project-2*'s node_modules. That makes them unavailable to *test-project-1*.

**Comment by baelter** [comment] 2015-11-16 09:08
+1

**Comment by briansokol** [comment] 2015-11-21 03:12
Issue was resolved with release of nom 3.4.1.

**Closed** 2015-11-21 03:12 UTC
