### ISSUE TITLE
shasum check failed for angular2-2.0.0-beta.3.tgz

### ISSUE THREAD

**Issue by erwin16** [npm/npm#11462] opened 2016-02-07 14:39 UTC
[npm-debug.log.zip](https://github.com/npm/npm/files/120727/npm-debug.log.zip)
[npm-debug-Log.zip](https://github.com/npm/npm/files/120728/npm-debug-Log.zip)

```
npm install
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/kc/k_tvbzbd7js1svtf5rz7gdfh0000gn/T/npm-4336-2004d989/registry.npmjs.org/angular2/-/angular2-2.0.0-beta.3.tgz
npm ERR! Expected: 30b791052b092af48b2508b4f409701a8c47fd72
npm ERR! Actual:   1ab98b09b272aaead71d9efc2c637c5f529a4e91
npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

FROM THE DEBUG LOG

```
253 verbose stack Expected: 30b791052b092af48b2508b4f409701a8c47fd72
253 verbose stack Actual:   1ab98b09b272aaead71d9efc2c637c5f529a4e91
253 verbose stack From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.3.tgz
253 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:25:8
253 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:72:7)
253 verbose stack     at emitNone (events.js:72:20)
253 verbose stack     at ReadStream.emit (events.js:166:7)
253 verbose stack     at endReadableNT (_stream_readable.js:905:12)
253 verbose stack     at nextTickCallbackWith2Args (node.js:455:9)
253 verbose stack     at process._tickCallback (node.js:369:17)
254 verbose cwd /Users/yves/Developments/MEAN-Stack/ANGULAR/ng2-play
255 error Darwin 15.2.0
256 error argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
257 error node v5.3.0
258 error npm  v3.3.12
259 error shasum check failed for /var/folders/kc/k_tvbzbd7js1svtf5rz7gdfh0000gn/T/npm-4336-2004d989/registry.npmjs.org/angular2/-/angular2-2.0.0-beta.3.tgz
```

**Comment by achreftlili** [comment] 2016-02-07 19:07
i got the same error too

**Comment by erwin16** [comment] 2016-02-08 13:36
so it's seems impossible to install Angular 2 beta now ...
I am moving to Aurelia , at least their beta is running fine ...

**Comment by achreftlili** [comment] 2016-02-09 15:38
No, but I tested in the office and I got no error I think it because of the low connection speed...

**Comment by giacomocerquone** [comment] 2016-03-11 11:56
I've got this error too while I was heavily downloading stuff on another computer!

`
OS: Windows 10
Node: v5.7.0
Npm:  v3.6.0
`

npm-debug.log

`
276 error Windows_NT 10.0.10586
277 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
278 error node v5.7.0
279 error npm  v3.6.0
280 error shasum check failed for ...AppData\Local\Temp\npm-6268-af804ab7\registry.npmjs.org\angular2\-\angular2-2.0.0-beta.9.tgz
280 error Expected: 2936007518be13e7997c2f43b9cc09a21ad665e7
280 error Actual:   345f004d6a29db0d6e4bffc08dc5318d52ab049e
280 error From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.9.tgz
281 error If you need help, you may report this error at:
281 error     <https://github.com/npm/npm/issues>
`

And I solved just disconnecting the other computer that was downloading.

**Comment by zkat** [comment] 2016-12-09 00:46
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:46 UTC
Labels: shasum, support
