### ISSUE TITLE
npm-debug.log could be written to /tmp or similar

### ISSUE THREAD

**Issue by kapouer** [npm/npm#1548] opened 2011-10-13 08:55 UTC
Hi,
npm-debug.log sometimes get written in strange places (i even found one in /usr/bin).

It could be very nice to write it to a temp directory, like /tmp on linux, or env[TEMP] on windows,
and of course tell to the user where it is.

A second idea is to timestamp the file name, so that crashes are logged separately.

**Comment by joshuabc** [comment] 2015-01-02 19:17
Big +1 on adding a configuration option to disable this.

**Comment by kloplop321** [comment] 2015-01-05 03:08
I keep finding this in all the weirdest places too, and no one on my team remembers how the heck it is getting into places like /etc/php5/fpm/pool.d and such.

**Comment by DavidSouther** [comment] 2015-01-05 03:13
@kloplop321 that's a really weird place! Presumably, it'll only show up in places that `npm` has executed and encountered an issue. Perhaps there's an automated tool that sometimes works in that part of  your directory structure?

**Comment by kloplop321** [comment] 2015-01-05 03:15
Well, no one remembers executing it there, and we don't have much automated besides crash detection. Same for our app directories, which are not node based. Though we do have a node-based bot that handles callback URLs for git pushes and such.

**Comment by jaythomas** [comment] 2015-02-03 17:16
@LeviSchuck, npm creates the debug log in your current working directory, not where you executed it. The problem is your current working directory is not specific to the shell instance you ran npm in. So if you are using, say, a terminal multiplexer like gnu-screen/tmux... or even running a terminal emulator with multiple tabs of bash/zsh open, npm will be open in one screen but writing logs to your current working directory in another screen (ie you could be in "/etc/php5/fpm/pool.d" in your other screen.)

**Comment by faiq** [comment] 2015-02-03 17:21
npm-debug.log should also never be made when something is wrong with the package, and it clearly isn't npm's fault

**Comment by monolithed** [comment] 2015-02-03 17:25
`npm-debug.log` is a log file like `httpd.log`, `nginx.log` etc, and the location should be configurable (`npm_modules` as well)!

**Comment by DavidSouther** [comment] 2015-02-03 17:36
@monolithed I hesitantly disagree - `httpd.log` and `nginx.log` are for long-running daemon processes, which I use to either gather metrics or triage an error. `npm-debug.log` is only generated when the most recent NPM command has encountered a failure, and is highly contextually dependent on where it happened.

Perhaps a hybrid solution would be to delete npm-debug.log on the next successful NPM command?

I still think those of you mentioning logs in random places have more pernicious issues with poorly written node scripts, that happen to tangentially fail when using NPM, and seeing `npm-debug.log` in those places should be a real indicator you should look inside the log file to find out which command was being executed, when and by whom, and take steps to triage bad code in your environment.

**Comment by inf3rno** [comment] 2015-03-05 23:55
+1 I think too it should be disableable.

**Comment by bitdivine** [comment] 2015-06-03 14:06
If the name of the file is configurable it can be made /dev/null and there won't be a need for explicit disabling.  For myself, I want to keep the code directory completely immutable for security reasons, so no files can be written to there by npm at all.  That's why I'd love to be able to run with NPM_DEBUG_LOGFILE=/var/log/spunk/npm-debug.log  HERE'S A BIG +1 :-)

**Comment by bitdivine** [comment] 2015-06-03 14:16
I should say that parsing package.json, extracting the run command and running it directly is perfectly feasible, doesn't involve npm and doesn't write npm-debug.log files.  I'm just always on a hunt to strip out as many steps as possible.  In this case you could accuse me of trying to pass the buck, and rightly so!

**Comment by gyss** [comment] 2015-06-21 15:12
+1

**Comment by tcurdt** [comment] 2015-10-28 22:47
+1

**Comment by rxaviers** [comment] 2015-11-10 20:21
+1 for a way to disable its creation.

I was wondering if there was a config I could use on `~/.npmrc` to disable its creation.

**Comment by justinhoward** [comment] 2015-12-17 21:48
+1 for disabling. I have yet to use an `npm-debug.log` file for anything useful. It just gets in the way.

**Comment by durkiewicz** [comment] 2016-01-18 06:08
+1

**Comment by monolithed** [comment] 2016-01-18 11:15
It's hard to believe that five years we can not resolve this issue

**Comment by ratson** [comment] 2016-03-28 12:15
Has this been implemented in some form?
There are seems some attempts solving this, but doesn't go through.

**Comment by jaythomas** [comment] 2016-03-28 13:35
My workaround was just to make an `~/.npmrc` and set `loglevel=silent` in it. Though it's not very helpful for those that really do want an npm-debug.log printout instead of using stdout to debug errors.

**Comment by iarna** [comment] 2016-04-15 20:56
Related to #11439

**Comment by just-boris** [comment] 2016-09-23 08:44
This is very very weird behavior.
`npm-debug.log` is getting out of control. Every time when I run npm wrong or by mistake, I end up with `npm-debug.log` in any random place.

The most common example is that I forgot to change folder before running `npm install`. Then I am getting `npm-debug.log` in the folder where I was before.

Imagine that git had the same behavior and gave you `git-debug.log` file every time when you tried to checkout to non-existing branch or got rejected push. That would be probably annoying, isn't it?

Actually now I afraid to run `npm`. I prefer to think twice before running because I am risking to have one more `npm-debug.log` somewhere in my file system.

I think that behavior should be different. Here should be either an option to switch this file off and enable it only when you need to provide the log for bug report maybe, or it should be placed in some other not visible for me folder.

From all tools that I have to deal with at my work on the regular basis, only `npm` behaves like this. And I am really wondering why.

**Comment by isiahmeadows** [comment] 2016-11-09 04:13
#11439 looks very interesting. hopefully that gets merged. :pray: 

@just-boris Easiest workaround ever: add `npm-debug.log` to each projects' `.gitignore`.

I agree it's annoying, but that at least guards against accidental commits. `npm` deletes the file on success, anyways.

**Comment by just-boris** [comment] 2016-11-09 09:20
@isiahmeadows 

> The most common example is that I forgot to change folder before running npm install. Then I am getting npm-debug.log in the folder where I was before.

Gitignore will not work in my case. If I run `npm` in the folder, that doesn't belong to any project (like my user home folder), the log file will pollute my home folder without any useful information.

**Comment by legodude17** [comment] 2016-11-09 18:46
The log file only appears if there is an error. When that happens you should troubleshoot it, and then delete the `npm-debug.log`.

**Comment by just-boris** [comment] 2016-11-09 19:27
@legodude17 
My error is very simple: I didn't have `package.json` in current folder. There is nothing to troubleshoot.
If npm would not have created `npm-debug.log` file such kind of error as well as it doesn't create log for misspelled command like `npm intall`, that will solve my problem.

Should I create a new issue/feature-requrest about that?

**Comment by monolithed** [comment] 2016-11-09 19:29
> The log file only appears if there is an error. When that happens you should troubleshoot it, and then delete the npm-debug.log.

I like stdout, why not? As you see `npm-debug.log` is unexpected file for many people, that's why it should be configurable.

**Comment by legodude17** [comment] 2016-11-09 19:39
@just-boris, what did you run? It is only an error if it needs the `package.json`, then just delete `npm-debug.log.

@monolithed, the `npm-debug.log` is very important when I am trying to troubleshoot other people's issues. It should be configurable, but I don't think that there should be an option to suppress it entirely.

**Comment by SamHH** [comment] 2016-11-14 11:47
@legodude17 Why not an option to suppress it entirely that is defaulted to off? As in, everyone has the logs created until they explicitly choose not to.

**Comment by legodude17** [comment] 2016-11-14 18:07
@SamHH, why would you need that? The biggest use case I have found is for automated build servers.

**Comment by SamHH** [comment] 2016-11-15 12:32
@legodude17 

I personally find the file to be a nuisance. I always find the issue by just looking at the console so each time anything related to npm errors I have to run `rm npm-debug.log`. That's a waste of time and adds further cognitive load.

Yarn takes a different approach in a simple use case. You try to install something that doesn't exist. Yarn acknowledges (I guess) that if you're installing it from the CLI, you only need to see the error in the CLI. npm on the other hand creates a worthless log file that I now have to remember to delete.

**Comment by legodude17** [comment] 2016-11-17 21:21
@SamHH, I agree that you may think it is a nuisance, but I find it helpful when trying to find a problem, like what if the console only says `143 == 0`? What then? I agree it should be able to be turned off, but the docs should warn against it for new users.

**Comment by SamHH** [comment] 2016-11-17 23:52
@legodude17 Yeah, I'm okay with having it enabled by default as a compromise. I think everyone here would be happy with that.

**Comment by rxaviers** [comment] 2016-11-18 00:31
Reading #6744 and other issues, it seems like npm team has agreed on moving `npm-debug.log` file to the cache directory (instead of cwd). There's a partial implementation made by @isaacs, but it has stalled and the PR has been closed.

**Closed** 2017-01-26 12:50 UTC
Labels: already-looked-at, feature-request, patch-welcome, supportability

**Comment by lichenhao** [comment] 2017-08-30 09:33
this is happened again...so sad .....

**Comment by mcblum** [comment] 2017-12-02 19:23
We're seeing a ton of these files created when using CircleCI. I don't exactly understand why and I can certainly place a command in the deploy script to clean them up, but it would be great to actually solve this.
