### ISSUE TITLE
npm pack with unexistant files

### ISSUE THREAD

**Issue by radare** [npm/npm#8791] opened 2015-07-01 13:08 UTC
The `package.json` "files" entry can contain files that does not exist in the filesystem. The `npm pack` does not shows any warning or error when constructing the tarball.

**Comment by KenanY** [comment] 2015-07-02 19:39
https://github.com/npm/npm/issues/6582?

**Comment by zkat** [comment] 2016-03-17 06:15
I've been poking at this (and other related issues), and there's some classes of problems that seem to be really hard/not-possible to implement without a significant amount of refactoring of the various modules involved in the process of adding/ignoring files.

In the case of this one, it turns out [specific information about what specific file was being required is obfuscated from the time the ignore file is read](https://github.com/npm/fstream-npm/blob/master/fstream-npm.js#L234-L238).

Reading further, we find that [all ignore rules are applied, as a batch, on a per-file basis](https://github.com/npm/fstream-ignore/blob/master/ignore.js#L214-L250).

Kinda a fundamental thing, which affects not just this, but #11669, is that the `files` array is treated as an "inverted" ignore file, as a flat set of (negated) globs, and the only place in the code that is able to make decisions about this sort of warning is also [completely unaware of `package.json` as a concept](https://github.com/npm/fstream-npm/blob/master/fstream-npm.js#L202-L204).

Yes, there's ways around this, which involve continuing to do more of the [copypasting](https://github.com/npm/npm/blob/master/lib/utils/tar.js#L64-L136) and [overriding](https://github.com/npm/fstream-npm/blob/master/fstream-npm.js#L91-L183) that has gotten us fairly deep in the hole by now and is already causing major maintainability/readability problems. The more I crawl through this code though, the more I'm convinced that the only way to get stuff like this working without making *everything* worse is to just reevaluate the way we're dealing with the fstream family of libraries.

I'm going to remove the `bug` label from this, because I really don't consider a value-added warning to be a bug, as nice as I agree this particular feature would be.

**Comment by zkat** [comment] 2016-04-12 22:07
(Update: #12191 addresses this 🎉 -- it took some changes related to other stuff to make this reasonably possible)

**Comment by radare** [comment] 2016-04-12 23:22
Cool!

**Comment by iamstarkov** [comment] 2016-06-15 09:26
@zkat is there any chance that this will be merged and deployed with next npm release?

**Comment by zkat** [comment] 2016-06-21 20:52
So, because of #5082, there was recently a lot of work and attention on fstream and company, and I wanted to lay off additional features like these.

That said, in order to merge #12191, npm/fstream-npm#21 needs to be updated to *exclude* the change related to how ignores/files are prioritized, because that would be a breaking change that we aren't doing for a while (if ever! Because of reasons!) It also needs tests. Once that's in place, I can get the PR in.

Unfortunately, I'm not gonna have time allocated to do this for a while, so I'm unassigning myself, but if anyone wants to start from what's there and help bring them over the finish line, I can take a bit of time to point them in the right direction.

**Comment by zkat** [comment] 2016-09-22 21:24
Closing as a duplicate of #6582.

**Closed by zkat** 2016-09-22 21:24 UTC
Labels: already-looked-at, feature-request, patch-welcome
