### ISSUE TITLE
install a project use 'npm install'

### ISSUE THREAD

**Issue by cindyzhangmj** [npm/npm#16624] opened 2017-05-15 02:21 UTC
#### I'm opening this issue because:

D:\element-starter-master>npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\THINK\AppData\Local\Temp\npm-1304-9279
b158\registry.npmjs.org\element-ui\-\element-ui-1.3.3.tgz
npm ERR! Expected: 070e730497ec288a6a435e32065757fdb9e97515
npm ERR! Actual:   79b0136227da180f1b2297f7356582d58b13cdaf
npm ERR! From:     https://registry.npmjs.org/element-ui/-/element-ui-1.3.3.tgz
npm ERR!

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-05-16 19:21
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:52 UTC
Labels: bot-closed, shasum, support
