### ISSUE TITLE
Npm i, always installs in user directory when using "open command prompt here" from context menu

### ISSUE THREAD

**Issue by Astrydax** [npm/npm#16250] opened 2017-04-05 05:56 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Npm install , always installs in USER directory when using "open command prompt here" from context menu, no matter what directory you are currently in.  Tested on windows 7
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2017-04-05 11:43
@Astrydax What versions of Node and `npm` are you using? Could you provide a list of steps to follow if I want to reproduce this?

**Comment by KenanY** [comment] 2017-05-30 17:23
Closing due to no reply.

**Closed by KenanY** 2017-05-30 17:23 UTC
Labels: support

**Comment by Astrydax** [comment] 2017-07-09 20:01
Sorry, it was the newest version of node and npm at the time. Did a fresh install when troubleshooting bug
