### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by gilangpr** [npm/npm#12436] opened 2016-04-22 02:58 UTC
i got this error while installing ionic-cli beta

```
npm ERR! shasum check failed for /tmp/npm-21772-5c33cd35/registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
npm ERR! Expected: 0184b9f610b8c52e72bfa287eebcdde08a1443be
npm ERR! Actual:   bb6e60232fe70caaa7dd0c937ec704a6255c59da
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment] 2016-04-22 03:04
@gilangpr Have you tried `npm cache clean`?

**Comment by gilangpr** [comment] 2016-04-22 03:46
@KenanY already did `npm cache clean` but still got same errors

npm http request GET https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/ionic
npm http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
npm http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic@beta"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! shasum check failed for /tmp/npm-28082-691dff24/registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
npm ERR! Expected: 0184b9f610b8c52e72bfa287eebcdde08a1443be
npm ERR! Actual:   856803bf0c5c97e6f8277cf9dfffd1630ccd665b
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/myindodev/npm-debug.log

**Comment by framerate** [comment] 2016-05-06 00:09
I'm getting an error like this when trying to npm an electron project inside Bash on Win10 (the technical preview)

**Comment by ballPointPenguin** [comment] 2016-05-12 01:42
similar issue here on Windows 10 Insider build 14342 using Ubuntu Bash for Windows
npm installed via https://github.com/nodesource/distributions
error occurs when running
```
$ sudo npm -g i npm
```

**Comment by ballPointPenguin** [comment] 2016-05-12 01:48
I wonder if the checksum is truly failing because of Windows weird filesystem or line endings in the pseudo-ubuntu world that is Ubuntu Bash for Windows

**Comment by simonbuchan** [comment] 2016-05-27 03:29
Fixed in WSL/Ubuntu on Windows in Preview Build 14352

**Comment by zkat** [comment] 2016-12-09 00:42
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:42 UTC
Labels: proxy, support
