### ISSUE TITLE
Common location needed for downloaded libraries

### ISSUE THREAD

**Issue by dhakehurst** [npm/npm#19390] opened 2017-12-13 08:11 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x ] Other (_see below for feature requests_):

#### What's going wrong?

node_modules contains duplicates for each separate project.

see comment in closed issue #918 (it should not be closed, it is a real issue), repeated here.

> "These are both much less "cluttered" options than "dump all my deps for everything in one place". 
&
> I can't speak to the experience on Maven, having never used it.

Having use maven lots (and gradle), these are far better approaches than the node/npm.
I agree with the original author, the node/npm way is 'broken', or 'not optimal' at any rate.

When I have more than one project that depends on the same third-party library at the same version,
why oh why oh why does npm download it separately for each project.
The published version of the library will not change.
there should be a '.node' folder in my home directory that stores all libs (at different versions)
(like the maven .m2 folder).

Then they are only downloaded once.

It is really messy and cluttered and time consuming and disk space consuming to have each lib installed separately in node_modules for each project.

It is an obvious thing to to, to have a common location. maven/gradle gets this right, node/npm does not.

> What happens when you want to update project A, but it breaks project B?"
this does not happen, because both projects define which libs at which version they want to use.

**Comment by kenany** [comment] 2017-12-13 14:15
Duplicate of https://github.com/npm/npm/issues/18068.

**Closed as completed by kenany** 2017-12-13 14:15 UTC
