### ISSUE TITLE
global library installations on windows are completely insecure

### ISSUE THREAD

**Issue by clshortfuse** [npm/npm#9078] opened 2015-07-27 18:45 UTC
On Windows systems, global modules are installed into %APPDATA%

The problem is, any application can write to %APPDATA%

Compare this with a linux environment where npm packages are installed to /usr/local/bin but requires elevated permissions to write to it. 

Any app can write over AppData bower/grunt-cli/etc installations and steal/inject data without the need for administrative rights. 

I can't think of any other secure place rather than %programfiles% since you need administrative rights to write to it.

Currently I'm using:

    npm config set prefix "%programfiles%\npm"
    npm config set cache "%programfiles%\npm\cache"

as a workaround (and then changing the environment paths)

**Comment by othiym23** [comment] 2015-07-29 05:36
Thanks for putting this together! I'm a little confused as to what it is you're asking for here – are you suggesting that the default cache and global prefix be changed on Windows? If so, you should probably take a look at #4564, where it's pretty clear that there's not a consensus about where npm should install things. What consensus there is in that issue is that there are probably more situations where writing to the roaming profile folder is a problem than writing to the local, but I don't see a lot of energy in favor of `%programfiles%` there.

I wouldn't describe your current solution as a workaround, since it gives you the level of control you feel is appropriate. In general, it's not really npm's place to have an opinion about users' operational environments. The current defaults were chosen in consultation with folks at Microsoft, and make sense to me for reasons I'll get into below. I personally don't think it makes much sense to require Administrator privileges to write to the cache, especially because practically no Unix or OS X users have their caches set up that way.

My own work laptop is set up so that `/usr/local` is owned and writable by my account (which is typical for Homebrew users like me). This makes a lot of sense for developer environments, which I think probably accounts for the vast majority of npm users on Windows. The Windows installer treats the bundled npm installation as part of the Node install, which is why it gets written into the same directory as Node. I can tell you that the requirement that users run with Administrator privileges to upgrade the bundled version of npm is confusing to a very large number of users, and is an ongoing support cost for the CLI team, to the point that it's [a frequently referred-to point in our Troubleshooting FAQ](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows).

Either way, we probably are going to change at least the global prefix at some point in the medium term, but since the discussion around that has mostly happened on #4564, I'm closing this issue as a duplicate of that one. We haven't made any decisions yet, so if after reading the discussion there, you think there's a case to be made for `%programfiles%`, feel free to weigh in!

**Closed by othiym23** 2015-07-29 05:36 UTC
Labels: documentation, feature-request

**Comment by clshortfuse** [comment] 2015-07-29 13:09
@othiym23 Thanks for taking a read. I'll weight in on the other thread.
