### ISSUE TITLE
npm doesn't see it's debug file

### ISSUE THREAD

**Issue by sam20908** [npm/npm#13822] opened 2016-08-31 06:08 UTC
I'm trying to run
npm install

but i got error saying

"Please include npm-debug.log with any support/request"

**Comment by KenanY** [comment] 2016-08-31 11:40
@sam20908 Could you please expand on what the issue is here?

**Comment by KenanY** [comment] 2016-09-08 05:45
Closing as abandoned.

**Closed by KenanY** 2016-09-08 05:45 UTC
