### ISSUE TITLE
Cannot read property 'path' of null on an offline server 

### ISSUE THREAD

**Issue by LabaniBanerjee** [npm/npm#16140] opened 2017-03-24 05:09 UTC
**I'm opening this issue because:**

1. npm is producing an incorrect install.
2. npm is doing something I don't understand.

**What's going wrong?**

Not very sure - but it seems like  app data folder of current logged in user is not getting correct config information 

**How can the CLI team reproduce the problem?**

Please use Windows server 2008 R2 or Windows server 2012 R2 any offline machine [no internet connection] where Node.js is never installed .Install the MSI .When Node.js command prompt is available , browse to the path "C:\Progarm Files\Nodejs\ and execute the command

 _**npm install node-jsmeter -g offline-npm**_

_The issue doesn't occur when the server is connected to internet ._

My observation says if the command is executed with net connection and then Internet is is disconnected , the installation command works perfectly fine .I think it also stores some configuration values in current logged in user app data \roaming folder ->

C:\Users\<current user>\AppData\Roaming\npm
C:\Users\<current user>\AppData\Roaming\npm-cache

and the values get removed / not even fetched during offlie installation for the very first time.

C:\Program Files\nodejs>npm install node-jsmeter -g offline-npm
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-jsmeter" "-g" "offline-npm"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2

npm ERR! ****Cannot read property 'path' of null****
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Supporting information:**

 - `npm config get registry` prints:

1. npm config get registry -> -http://registry.npmjs.org/
2. npm config get http-proxy  -> always comes undefined even after setting to null 
3. npm config get https-proxy -> null

 - Windows, OS X/macOS, or Linux?:

1. Windows Server 2008 R2
2. Windows Server 2012 R2

 - Network issues:
   - Geographic location where npm was run:  

1. India , South-East Asia 
2.   No internet connection - on a stand alone SharePoint server 

**Debug log** 

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'node-jsmeter',
1 verbose cli   '-g',
1 verbose cli   'offline-npm' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData node-jsmeter
8 silly fetchPackageMetaData offline-npm
9 silly fetchNamedPackageData node-jsmeter
10 silly mapToRegistry name node-jsmeter
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'node-jsmeter',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'node-jsmeter',
13 silly mapToRegistry   name: 'node-jsmeter',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/node-jsmeter
15 silly fetchNamedPackageData offline-npm
16 silly mapToRegistry name offline-npm
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'offline-npm',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'offline-npm',
19 silly mapToRegistry   name: 'offline-npm',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/offline-npm
21 verbose request uri https://registry.npmjs.org/offline-npm
22 verbose request no auth needed
23 info attempt registry request try #1 at 8:59:47 PM
24 verbose request id 01dafdc906e155a3
25 http request GET https://registry.npmjs.org/offline-npm
26 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
27 verbose request uri https://registry.npmjs.org/node-jsmeter
28 verbose request no auth needed
29 info attempt registry request try #1 at 8:59:47 PM
30 verbose etag W/"503636c5-e5a"
31 verbose lastModified Thu, 23 Aug 2012 13:57:25 GMT
32 http request GET https://registry.npmjs.org/node-jsmeter
33 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
34 info attempt registry request try #2 at 8:59:57 PM
35 http request GET https://registry.npmjs.org/offline-npm
36 info attempt registry request try #2 at 8:59:57 PM
37 verbose etag W/"503636c5-e5a"
38 verbose lastModified Thu, 23 Aug 2012 13:57:25 GMT
39 http request GET https://registry.npmjs.org/node-jsmeter
40 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
41 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
42 info attempt registry request try #3 at 9:00:57 PM
43 http request GET https://registry.npmjs.org/offline-npm
44 info attempt registry request try #3 at 9:00:57 PM
45 verbose etag W/"503636c5-e5a"
46 verbose lastModified Thu, 23 Aug 2012 13:57:25 GMT
47 http request GET https://registry.npmjs.org/node-jsmeter
48 silly fetchPackageMetaData Error: getaddrinfo ENOENT registry.npmjs.org:443
48 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1034:11)
48 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
48 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
48 silly fetchPackageMetaData  error for offline-npm { Error: getaddrinfo ENOENT registry.npmjs.org:443
48 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1034:11)
48 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
48 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
48 silly fetchPackageMetaData   code: 'ENOENT',
48 silly fetchPackageMetaData   errno: 'ENOENT',
48 silly fetchPackageMetaData   syscall: 'getaddrinfo',
48 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
48 silly fetchPackageMetaData   host: 'registry.npmjs.org',
48 silly fetchPackageMetaData   port: 443 }
49 silly get cb [ 304, undefined ]
50 verbose etag https://registry.npmjs.org/node-jsmeter from cache
51 verbose get saving node-jsmeter to C:\Users\spfarm\AppData\Roaming\npm-cache\registry.npmjs.org\node-jsmeter\.cache.json
52 verbose correctMkdir C:\Users\spfarm\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
53 silly rollbackFailedOptional Starting
54 verbose stack TypeError: Cannot read property 'path' of null
54 verbose stack     at Installer.rollbackFailedOptional (c:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
54 verbose stack     at Array.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
54 verbose stack     at LOOP (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
54 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
54 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
54 verbose stack     at Array.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
54 verbose stack     at LOOP (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
54 verbose stack     at chain (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
54 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
54 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
55 verbose cwd c:\Program Files\nodejs
56 error Windows_NT 6.2.9200
57 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-jsmeter" "-g" "offline-npm"
58 error node v7.7.4
59 error npm  v4.1.2
60 error Cannot read property 'path' of null
61 error If you need help, you may report this error at:
61 error     <https://github.com/npm/npm/issues>
62 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-03-24 15:49
Duplicate of #10686. Try checking you internet connection and proxy.

**Comment by LabaniBanerjee** [comment] 2017-03-24 15:53
Hi . I want to install it in an offline server . It doesn't have any internet connection.

**Comment by legodude17** [comment] 2017-03-24 18:50
You need internet to install with `npm`.

**Closed** 2017-06-17 03:39 UTC
Labels: bot-closed
