### ISSUE TITLE
Silent login

### ISSUE THREAD

**Issue by asaf** [npm/npm#12817] opened 2016-05-24 12:30 UTC
Hey,

Silent login is critical for automation,
There are multiple issues opened about how to login silently to private repos, most of the solutions are complicated / doesn't work, since during build, TTY/STDIN is not available for interaction,

See: #2907, #7014

I would like to add --user <username> --password <pass> to the 'adduser' command,

Will you accept a PR for this?

Unless there is a better approach,
There is a function called `npm.config.getCredentialsByURI(npm.config.get('registry'))` that can retrieve credentials from URL but i'm not sure how it works,

Thanks,

Asaf.

**Comment by KenanY** [comment] 2016-05-24 16:23
https://github.com/npm/npm/issues/12111#issuecomment-202497588

**Comment by asaf** [comment] 2016-05-24 20:44
@KenanY 

Do tokens have any expiration time?
Is it safe to set a token created month ago to `.npmrc` directly?

Otherwise I don't see how the suggested approach can be used persistently,

Thanks

**Comment by KenanY** [comment] 2016-06-02 14:58
@asaf Anecdotally I can say that I usually use the same token for several months at a time.

**Comment by KenanY** [comment] 2016-06-28 21:07
Closing as a duplicate of https://github.com/npm/npm/issues/12111.

**Closed by KenanY** 2016-06-28 21:07 UTC
Labels: feature-request
