### ISSUE TITLE
Error while npm install node-rfc

### ISSUE THREAD

**Issue by masiddiqui91** [npm/npm#15062] opened 2016-11-29 16:26 UTC
![capture](https://cloud.githubusercontent.com/assets/1316542/20718328/59cdc9ce-b67e-11e6-9d75-fb0eae775a7b.JPG)
------------------------------------------------------------------------------------------------------
I am trying to install node-rfc but its giving me some error which I dont understand. Experts please help.

Please find the npm debug log below ::
-------------------------------------------------------------------------------------------------------
<details>
<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\msm2365\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'node-rfc' ]
2 info using npm@3.9.5
3 info using node@v4.4.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData node-rfc
8 silly fetchNamedPackageData node-rfc
9 silly mapToRegistry name node-rfc
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'node-rfc',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'node-rfc',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/node-rfc
14 verbose request uri https://registry.npmjs.org/node-rfc
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:53:12 PM
17 verbose request id 5eb23ff27ef875a7
18 verbose etag W/"53e376f0-225"
19 verbose lastModified Thu, 07 Aug 2014 12:54:08 GMT
20 http request GET https://registry.npmjs.org/node-rfc
21 http 304 https://registry.npmjs.org/node-rfc
22 verbose headers { date: 'Tue, 29 Nov 2016 16:23:13 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"53e376f0-225"',
22 verbose headers   age: '267',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-sin6921-SIN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1480436593.390939,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 29 Nov 2016 16:23:13 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"53e376f0-225"',
23 silly get     age: '267',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin6921-SIN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1480436593.390939,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/node-rfc from cache
25 verbose get saving node-rfc to C:\Users\msm2365\AppData\Roaming\npm-cache\registry.npmjs.org\node-rfc\.cache.json
26 verbose correctMkdir C:\Users\msm2365\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 verbose stack TypeError: Cannot convert undefined or null to object
27 verbose stack     at Function.keys (native)
27 verbose stack     at pickVersionFromRegistryDocument (C:\Users\msm2365\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:125:29)
27 verbose stack     at C:\Users\msm2365\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
27 verbose stack     at C:\Users\msm2365\AppData\Roaming\npm\node_modules\npm\lib\utils\pulse-till-done.js:19:8
27 verbose stack     at saved (C:\Users\msm2365\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:174:7)
27 verbose stack     at C:\Users\msm2365\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
27 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
28 verbose cwd C:\storm\microsql
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\msm2365\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-rfc"
31 error node v4.4.5
32 error npm  v3.9.5
33 error Cannot convert undefined or null to object
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
</pre>
</detail>

**Comment by legodude17** [comment] 2016-11-29 17:30
Ref #9896. I believe this is a duplicate of that one.

**Comment by othiym23** [comment] 2016-11-29 21:56
Closing as duplicate of #9896.

**Closed by othiym23** 2016-11-29 21:56 UTC
Labels: big-bug, bug
