### ISSUE TITLE
NPM 3.7.1 issue while installing babel-cli

### ISSUE THREAD

**Issue by JigneshRaval** [npm/npm#11397] opened 2016-02-03 10:26 UTC
Hi, could you please guide me on the following error I got everytime when I try to install babel-cli using command "npm install --save-dev babel-cli". 

However it installs "express" properly.

Node Version : 5.3.0
NPM Version : 3.7.1
Error:
---------------
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\<userName>\AppData\Roaming\npm-cache\trim-newlines\1.0.0\package.tgz.3558189468' -> 'C:\Users\<userName>\AppData\Roaming\npm-cache\trim-newlines\1.0.0\package.tgz'

This is random error for different packages like here in above code it is for "trim-newline". If I will repeat npm install command again then it will throw error for another sub-module.

I have also attached npm-debug.log file

------------------------------------------
[npm-debug.txt](https://github.com/npm/npm/files/115459/npm-debug.txt)

**Comment by uriee** [comment] 2016-03-15 11:25
Hello.
I think the babel-cli need to be install only globaly (npm install -g babel-cli)

**Comment by busches** [comment] 2016-08-18 20:14
@JigneshRaval is this still occurring with the latest `npm`?

**Comment by othiym23** [comment] 2016-08-19 21:55
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:55 UTC
Labels: windows
