### ISSUE TITLE
npm search without search-parameter runs infinitely. 

### ISSUE THREAD

**Issue by iSchlicht** [npm/npm#6173] opened 2014-09-12 13:13 UTC
is this an error or need npm search for a mandatory search parameters?

using 1.4.25 (OSX or Windows 8.1 x64)
... try "npm cache clean -force" will not help!

**Comment by smikes** [comment] 2015-02-22 17:53
@netgamer7 do you still see this behavior with the current regsitry implementation?  I often have problems with stock `npm search` but others seem to have success (possibly they have > 8GB RAM, but hey).

The full download - parse - calculate - display cycle for `npm search` with no arguments will take a long time, because `npm search` will first build a result set containing all the packages, then determine the appropriate column widths by inspecting every record, and only then write them out.

Could you please try

```
npm search npm > /dev/null
```

Which will force the search database to be downloaded and processed, but will not require an enormous search-results data structure to be created.  That will help isolate whether the problem is coming from the download or the processing.

**Comment by netgamer7** [comment] 2015-02-23 16:26
phobos:~ iridium$ npm search
npm WARN Building the local index for the first time, please be patient
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
phobos:~ iridium$ 

this is running nodejs 0.12.0 and npm 2.5.0 on OS X 10.10.2, node installed through macports.

**Comment by netgamer7** [comment] 2015-02-23 16:27
@smikes meant to add in my previous message that the machine as 16gb of ram - it was higher than 8GB which you said some people had success with.

**Comment by smikes** [comment] 2015-02-23 16:34
Hmm you might need to try it in two steps

npm search jshint >/dev/null
npm search

That worked for me yesterday, but it was slow. I'd also invite you to try 'npm-kludge-search'

**Comment by danielbayley** [comment] 2015-02-23 17:10
Just FYI, I also have 16GB of RAM so it doesn't seem to help.

**Comment by smikes** [comment] 2015-02-23 20:18
I am definitely looking for beta testers for `npm-kludge-search`.  It works for name, full-text search, and completion; the only thing it doesn't support yet is regexp search.

`npm i -g npm-kludge-search` ; install takes 3-4 minutes because it has to pull down and build the index (in production, we'll build these centrally and distribute via CDN but it's still fairly big, 16MB).

**Comment by othiym23** [comment] 2015-02-26 02:28
I'm closing this in favor of / as a duplicate of #6016 – it's a known issue that `npm search` is extremely slow and memory-intensive, and we intend to address the problem. We haven't gotten that onto the roadmap yet, though, so in the meantime, alternatives like `npm-kludge-search` will be an important way to see what works and what doesn't (and, not incidentally, allow you all to continue to search for things).

**Closed by othiym23** 2015-02-26 02:28 UTC
Labels: bug, registry
