### ISSUE TITLE
npm install -g appium fails for 1.6.1, 1.6.2, 1.6.3

### ISSUE THREAD

**Issue by magleahy** [npm/npm#15210] opened 2016-12-13 17:08 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I try to install all versions of appium globally from 1.6.1 to 1.6.3 - all fail. 

#### How can the CLI team reproduce the problem?

magleahy@ip-10-99-16-56 ~/D/p/c/App> npm uninstall -g appium
magleahy@ip-10-99-16-56 ~/D/p/c/App> npm cache clean
magleahy@ip-10-99-16-56 ~/D/p/c/App> npm install -g appium
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

***Upgraded npm***

magleahy@ip-10-99-16-56 ~/D/p/c/App> npm install -g appium
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

***Appium 1.6.0: this version is NOT the one I need***

magleahy@ip-10-99-16-56 ~/D/p/c/App> npm install -g appium@1.6.0
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@2.9.2 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:2431) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
info Chromedriver Install Writing binary content to /var/folders/c7/1kkz38rn2l96p5fjv141dwsc0000gn/T/20161113-2431-wqyq1r.dciz77gb9/chromedriver_mac32.zip...
info Chromedriver Install Extracting /var/folders/c7/1kkz38rn2l96p5fjv141dwsc0000gn/T/20161113-2431-wqyq1r.dciz77gb9/chromedriver_mac32.zip to /var/folders/c7/1kkz38rn2l96p5fjv141dwsc0000gn/T/20161113-2431-wqyq1r.dciz77gb9/chromedriver_mac32
info Chromedriver Install Creating /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac...
info Chromedriver Install Copying unzipped binary, reading from /var/folders/c7/1kkz38rn2l96p5fjv141dwsc0000gn/T/20161113-2431-wqyq1r.dciz77gb9/chromedriver_mac32/chromedriver...
info Chromedriver Install Writing to /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver...
info Chromedriver Install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver successfully put in place

> appium-selendroid-driver@1.4.3 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
(node:2433) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info AndroidDriver Java version is: 1.8.0_112
info Selendroid Ensuring /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from http://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download/selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d82.jar
info Selendroid Writing binary content to /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download/selendroid-server.jar.tmp
info Selendroid Selendroid standalone server downloaded
info Selendroid Determining AndroidManifest location
info Selendroid Determining server apk location
info Selendroid Extracting manifest and apk to /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download
info Selendroid Copying manifest and apk to /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid
info Selendroid Cleaning up temp files
info Selendroid Fixing AndroidManifest icon bug

> appium-uiautomator2-driver@0.0.4 install /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
(node:2439) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info AndroidDriver Java version is: 1.8.0_112
info UiAutomator2 downloading UiAutomator2 Server APKs 
WARN UiAutomator2 UiAutomator2 Server APKs downloaded, but MD5 hash did not match, please be careful
WARN UiAutomator2 fs.md5(UI2_SERVER_APK_PATH):80db0e40c100d73fa4d9ab6543d82b22
WARN UiAutomator2 fs.md5(UI2_TEST_APK_PATH):e1a161b4f2e0c874e2f75a8d7a74d7b1

> appium-windows-driver@0.2.0 install /usr/local/lib/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

Not installing WinAppDriver since did not detect a Windows system
/usr/local/lib
└─┬ appium@1.6.0 
  ├── accepts@1.3.3 
  ├── acorn@1.2.2 
  ├─┬ adbkit@2.6.0 
  │ ├── bluebird@2.9.34 
  │ ├── debug@2.1.3 
  │ └── ms@0.7.0 
  ├── adbkit-logcat@1.1.0 
  ├─┬ adbkit-monkey@1.0.1 
  │ └── async@0.2.10 
  ├── adm-zip@0.4.7 
  ├── align-text@0.1.4 
  ├── alter@0.2.0 
  ├── amdefine@1.0.0 
  ├── ansi@0.3.1 
  ├── ansi-regex@2.0.0 
  ├── ansi-styles@2.2.1 
  ├─┬ appium-adb@2.6.17 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-android-bootstrap@2.7.5 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-android-driver@1.10.27 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├── appium-android-ime@2.0.0 
  ├── appium-atoms@0.1.0 
  ├─┬ appium-base-driver@2.0.19 
  │ └─┬ request-promise@4.1.1 
  │   └── bluebird@3.4.6 
  ├─┬ appium-chromedriver@2.9.2 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-cookies@1.1.0 
  │ ├── babel-runtime@5.8.20 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-fake-driver@0.1.10 
  │ ├── bluebird@3.4.6 
  │ └── lodash@3.10.1 
  ├─┬ appium-instruments@3.8.5 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-ios-driver@1.12.27 
  │ └── xpath@0.0.22 
  ├─┬ appium-ios-log@1.2.1 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├── appium-ios-simulator@1.7.10 
  ├─┬ appium-logger@2.1.0 
  │ └── source-map-support@0.3.3 
  ├── appium-remote-debugger@3.1.7 
  ├─┬ appium-selendroid-driver@1.4.3 
  │ ├── bluebird@3.4.6 
  │ ├── lodash@3.10.1 
  │ ├── request-promise@4.1.1 
  │ └── source-map-support@0.3.3 
  ├── appium-support@2.3.3 
  ├─┬ appium-uiauto@2.3.3 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-uiautomator@1.1.0 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-uiautomator2-driver@0.0.4 
  │ ├── lodash@3.10.1 
  │ ├─┬ request-promise@4.1.1 
  │ │ └── bluebird@3.4.6 
  │ └── source-map-support@0.3.3 
  ├── appium-uiautomator2-server@0.0.1 
  ├── appium-unlock@0.1.1 
  ├─┬ appium-windows-driver@0.2.0 
  │ ├── punycode@2.0.0 
  │ ├─┬ request-promise@3.0.0 
  │ │ └── bluebird@3.4.6 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-xcode@3.1.1 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├─┬ appium-xcuitest-driver@2.0.26 
  │ └── bluebird@3.4.6 
  ├── appium-youiengine-driver@1.0.6 
  ├── are-we-there-yet@1.1.2 
  ├── argparse@1.0.9 
  ├── array-filter@0.0.1 
  ├── array-flatten@1.1.1 
  ├── array-map@0.0.0 
  ├── array-reduce@0.0.0 
  ├── asn1@0.2.3 
  ├── assert-plus@0.2.0 
  ├── assertion-error@1.0.2 
  ├── ast-traverse@0.1.1 
  ├── ast-types@0.8.5 
  ├── async@1.5.2 
  ├── async-listener@0.6.3 
  ├─┬ asyncbox@2.3.1 
  │ ├── babel-runtime@5.5.5 
  │ ├── chai@3.5.0 
  │ ├── chai-as-promised@5.3.0 
  │ ├── core-js@0.9.18 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├── asynckit@0.4.0 
  ├── aws-sign2@0.6.0 
  ├── aws4@1.4.1 
  ├─┬ babel-core@5.8.24 
  │ ├── lodash@3.10.1 
  │ ├── minimatch@2.0.10 
  │ ├── source-map@0.4.4 
  │ └─┬ source-map-support@0.2.10 
  │   └── source-map@0.1.32 
  ├── babel-plugin-constant-folding@1.0.1 
  ├── babel-plugin-dead-code-elimination@1.0.2 
  ├── babel-plugin-eval@1.0.1 
  ├── babel-plugin-inline-environment-variables@1.0.1 
  ├── babel-plugin-jscript@1.0.4 
  ├── babel-plugin-member-expression-literals@1.0.1 
  ├── babel-plugin-property-literals@1.0.1 
  ├─┬ babel-plugin-proto-to-assign@1.0.4 
  │ └── lodash@3.10.1 
  ├── babel-plugin-react-constant-elements@1.0.3 
  ├── babel-plugin-react-display-name@1.0.3 
  ├── babel-plugin-remove-console@1.0.1 
  ├── babel-plugin-remove-debugger@1.0.1 
  ├── babel-plugin-runtime@1.0.7 
  ├── babel-plugin-undeclared-variables-check@1.0.2 
  ├── babel-plugin-undefined-to-void@1.1.6 
  ├── babel-runtime@5.8.24 
  ├── babylon@5.8.38 
  ├── balanced-match@0.4.2 
  ├── base64-js@0.0.8 
  ├── basic-auth@1.0.4 
  ├── bcrypt-pbkdf@1.0.0 
  ├── big-integer@1.6.16 
  ├── bignumber.js@2.4.0 
  ├─┬ bl@1.1.2 
  │ └── readable-stream@2.0.6 
  ├── bluebird@2.11.0 
  ├── bmp-js@0.0.1 
  ├── body-parser@1.15.2 
  ├── boom@2.10.1 
  ├── bplist-creator@0.0.6 
  ├── bplist-parser@0.1.1 
  ├── brace-expansion@1.1.6 
  ├── breakable@1.0.0 
  ├── buffer-equal@0.0.1 
  ├── buffer-shims@1.0.0 
  ├── bufferpack@0.0.6 
  ├── bytes@2.4.0 
  ├── camelcase@2.1.1 
  ├── caseless@0.11.0 
  ├── center-align@0.1.3 
  ├── chalk@1.1.3 
  ├── cliui@3.2.0 
  ├─┬ cls-bluebird@1.1.3 
  │ └── shimmer@1.1.0 
  ├── code-point-at@1.0.1 
  ├── colors@1.1.2 
  ├── combined-stream@1.0.5 
  ├── commander@2.9.0 
  ├─┬ commoner@0.10.4 
  │ └── glob@5.0.15 
  ├── concat-map@0.0.1 
  ├── connected-domain@1.0.0 
  ├── content-disposition@0.5.1 
  ├── content-type@1.0.2 
  ├── continuation-local-storage@3.2.0 
  ├── convert-source-map@1.3.0 
  ├── cookie@0.3.1 
  ├── cookie-signature@1.0.6 
  ├── core-js@1.2.7 
  ├── core-util-is@1.0.2 
  ├── cryptiles@2.0.5 
  ├── cycle@1.0.3 
  ├─┬ dashdash@1.14.0 
  │ └── assert-plus@1.0.0 
  ├── date-utils@1.2.21 
  ├── debug@2.2.0 
  ├── decamelize@1.2.0 
  ├─┬ deep-eql@0.1.3 
  │ └── type-detect@0.1.1 
  ├── defined@1.0.0 
  ├─┬ defs@1.1.1 
  │ ├── camelcase@1.2.1 
  │ ├── cliui@2.1.0 
  │ ├── esprima-fb@15001.1001.0-dev-harmony-fb 
  │ └── yargs@3.27.0 
  ├── delayed-stream@1.0.0 
  ├── delegates@1.0.0 
  ├── depd@1.1.0 
  ├── destroy@1.0.4 
  ├─┬ detect-indent@3.0.1 
  │ └── minimist@1.2.0 
  ├── detective@4.3.1 
  ├── dom-walk@0.1.1 
  ├── ecc-jsbn@0.1.1 
  ├── ee-first@1.1.1 
  ├── emitter-listener@1.0.1 
  ├── encodeurl@1.0.1 
  ├── es6-error@2.1.1 
  ├── es6-mapify@1.0.0 
  ├── es6-promise@3.3.1 
  ├── escape-html@1.0.3 
  ├── escape-string-regexp@1.0.5 
  ├── esprima-fb@15001.1.0-dev-harmony-fb 
  ├── esutils@2.0.2 
  ├── etag@1.7.0 
  ├── exif-parser@0.1.9 
  ├── express@4.14.0 
  ├── extend@3.0.0 
  ├── extsprintf@1.0.2 
  ├── eyes@0.1.8 
  ├── file-type@3.8.0 
  ├── finalhandler@0.5.0 
  ├── for-each@0.3.2 
  ├── forever-agent@0.6.1 
  ├── form-data@2.0.0 
  ├── forwarded@0.1.0 
  ├── fresh@0.3.0 
  ├── fs-readdir-recursive@0.1.2 
  ├── fs.realpath@1.0.0 
  ├── gauge@1.2.7 
  ├── generate-function@2.0.0 
  ├── generate-object-property@1.2.0 
  ├── get-stdin@4.0.1 
  ├─┬ getpass@0.1.6 
  │ └── assert-plus@1.0.0 
  ├── glob@6.0.4 
  ├── global@4.3.1 
  ├── globals@6.4.1 
  ├── graceful-fs@4.1.9 
  ├── graceful-readlink@1.0.1 
  ├── har-validator@2.0.6 
  ├── has-ansi@2.0.0 
  ├── has-unicode@2.0.1 
  ├── hawk@3.1.3 
  ├── hoek@2.16.3 
  ├── home-or-tmp@1.0.0 
  ├─┬ http-errors@1.5.0 
  │ └── inherits@2.0.1 
  ├── http-signature@1.1.1 
  ├── iconv-lite@0.4.13 
  ├── inflight@1.0.5 
  ├── inherits@2.0.3 
  ├── invert-kv@1.0.0 
  ├── io.appium.settings@2.1.0 
  ├─┬ ios-app-utils@1.1.0 
  │ ├── lodash@3.10.1 
  │ └── source-map-support@0.3.3 
  ├── ip-regex@1.0.3 
  ├── ipaddr.js@1.1.1 
  ├── is-bluebird@1.0.2 
  ├── is-buffer@1.1.4 
  ├── is-finite@1.0.2 
  ├── is-fullwidth-code-point@1.0.0 
  ├── is-function@1.0.1 
  ├── is-integer@1.0.6 
  ├── is-my-json-valid@2.15.0 
  ├── is-os@1.0.0 
  ├── is-property@1.0.2 
  ├── is-typedarray@1.0.0 
  ├── isarray@1.0.0 
  ├── isexe@1.1.2 
  ├── isstream@0.1.2 
  ├── jimp@0.2.27 
  ├── jodid25519@1.0.2 
  ├── jpeg-js@0.2.0 
  ├── js-tokens@1.0.1 
  ├── js2xmlparser2@0.2.0 
  ├── jsbn@0.1.0 
  ├── jsesc@0.5.0 
  ├── json-schema@0.2.3 
  ├── json-stringify-safe@5.0.1 
  ├── json5@0.4.0 
  ├── jsonify@0.0.0 
  ├── jsonpointer@4.0.0 
  ├── jsprim@1.3.1 
  ├── kind-of@3.0.4 
  ├── lazy-cache@1.0.4 
  ├── lcid@1.0.0 
  ├── left-pad@0.0.3 
  ├── leven@1.0.2 
  ├── line-numbers@0.2.0 
  ├── load-bmfont@1.2.3 
  ├── lodash@4.16.4 
  ├── lodash.pad@4.5.1 
  ├── lodash.padend@4.6.1 
  ├── lodash.padstart@4.6.1 
  ├── longest@1.0.1 
  ├── md5-file@2.0.7 
  ├── media-typer@0.3.0 
  ├── merge-descriptors@1.0.1 
  ├── method-override@2.3.6 
  ├── methods@1.1.2 
  ├── mime@1.3.4 
  ├── mime-db@1.24.0 
  ├── mime-types@2.1.12 
  ├── min-document@2.19.0 
  ├── minimatch@3.0.3 
  ├── minimist@0.0.8 
  ├── mkdirp@0.5.1 
  ├── morgan@1.7.0 
  ├── ms@0.7.1 
  ├─┬ mv@2.1.1 
  │ └── rimraf@2.4.5 
  ├── nan@2.4.0 
  ├── ncp@2.0.0 
  ├── negotiator@0.6.1 
  ├── net@1.0.2 
  ├── node-forge@0.6.43 
  ├── node-idevice@0.1.6 
  ├── node-simctl@3.4.4 
  ├── node-uuid@1.4.7 
  ├── npmlog@2.0.4 
  ├── number-is-nan@1.0.1 
  ├── oauth-sign@0.8.2 
  ├── object-assign@4.1.0 
  ├── on-finished@2.3.0 
  ├── on-headers@1.0.1 
  ├── once@1.4.0 
  ├── options@0.0.6 
  ├── os-locale@1.4.0 
  ├── os-tmpdir@1.0.2 
  ├── output-file-sync@1.1.2 
  ├── parse-bmfont-ascii@1.0.6 
  ├── parse-bmfont-binary@1.0.6 
  ├── parse-bmfont-xml@1.1.3 
  ├── parse-headers@2.0.1 
  ├── parseurl@1.3.1 
  ├─┬ path@0.12.7 
  │ └── process@0.11.9 
  ├── path-exists@1.0.0 
  ├── path-is-absolute@1.0.1 
  ├── path-to-regexp@0.1.7 
  ├── pinkie@2.0.4 
  ├── pinkie-promise@2.0.1 
  ├── pixelmatch@4.0.2 
  ├── pkginfo@0.3.1 
  ├── plist@1.2.0 
  ├── pngjs@3.0.0 
  ├── portfinder@1.0.7 
  ├── private@0.1.6 
  ├── process@0.5.2 
  ├── process-nextick-args@1.0.7 
  ├── proxy-addr@1.1.2 
  ├── ps-node@0.0.5 
  ├── punycode@1.3.2 
  ├── q@1.4.1 
  ├── qs@6.2.0 
  ├── querystring@0.2.0 
  ├── range-parser@1.2.0 
  ├── raw-body@2.1.7 
  ├── read-chunk@1.0.1 
  ├── readable-stream@2.1.5 
  ├─┬ recast@0.10.24 
  │ └── source-map@0.4.4 
  ├── regenerate@1.3.1 
  ├── regenerator@0.8.35 
  ├─┬ regexpu@1.3.0 
  │ └── esprima@2.7.3 
  ├── regjsgen@0.2.0 
  ├── regjsparser@0.1.5 
  ├── repeat-string@1.5.4 
  ├── repeating@1.1.3 
  ├── request@2.75.0 
  ├─┬ request-promise@1.0.2 
  │ └── lodash@3.10.1 
  ├── request-promise-core@1.1.1 
  ├── resolve@1.1.7 
  ├── right-align@0.1.3 
  ├─┬ rimraf@2.5.4 
  │ └── glob@7.1.1 
  ├── rsvp@3.3.3 
  ├── safari-launcher@2.0.5 
  ├── sax@1.2.1 
  ├── semver@4.3.6 
  ├── semver-compare@1.0.0 
  ├── send@0.14.1 
  ├── serve-favicon@2.3.0 
  ├── serve-static@1.11.1 
  ├── setprototypeof@1.0.1 
  ├── shebang-regex@1.0.0 
  ├── shell-quote@1.6.1 
  ├── shimmer@1.0.0 
  ├── simple-fmt@0.1.0 
  ├── simple-is@0.2.0 
  ├── slash@1.0.0 
  ├── sntp@1.0.9 
  ├── source-map@0.1.32 
  ├─┬ source-map-support@0.4.3 
  │ └── source-map@0.5.6 
  ├── split@0.3.3 
  ├── sprintf-js@1.0.3 
  ├─┬ sshpk@1.10.1 
  │ └── assert-plus@1.0.0 
  ├── stable@0.1.5 
  ├── stack-trace@0.0.9 
  ├── statuses@1.3.0 
  ├── stealthy-require@1.0.0 
  ├── stream-buffers@2.2.0 
  ├── stream-to@0.2.2 
  ├── stream-to-buffer@0.1.0 
  ├── string-width@1.0.2 
  ├── string_decoder@0.10.31 
  ├── stringmap@0.2.2 
  ├── stringset@0.2.1 
  ├── stringstream@0.0.5 
  ├── strip-ansi@3.0.1 
  ├── supports-color@2.0.0 
  ├── table-parser@0.1.1 
  ├─┬ teen_process@1.7.1 
  │ └── source-map-support@0.2.10 
  ├─┬ temp@0.8.3 
  │ └── rimraf@2.2.8 
  ├── through@2.3.8 
  ├── tinycolor2@1.4.1 
  ├── to-fast-properties@1.0.2 
  ├── tough-cookie@2.3.1 
  ├─┬ traceur@0.0.111 
  │ ├── glob@5.0.15 
  │ └── source-map-support@0.2.10 
  ├── trim@0.0.1 
  ├── trim-right@1.0.1 
  ├── try-resolve@1.0.1 
  ├── tryor@0.1.2 
  ├── tunnel-agent@0.4.3 
  ├── tweetnacl@0.14.3 
  ├── type-detect@1.0.0 
  ├── type-is@1.6.13 
  ├── ultron@1.0.2 
  ├── unpipe@1.0.0 
  ├── url@0.11.0 
  ├── url-regex@3.2.0 
  ├── user-home@1.1.1 
  ├─┬ utf7@1.0.2 
  │ └── semver@5.3.0 
  ├─┬ util@0.10.3 
  │ └── inherits@2.0.1 
  ├── util-deprecate@1.0.2 
  ├── utils-merge@1.0.0 
  ├── uuid-js@0.7.5 
  ├── validate.js@0.9.0 
  ├── vary@1.1.0 
  ├── verror@1.3.6 
  ├── which@1.2.11 
  ├── window-size@0.1.4 
  ├─┬ winston@2.2.0 
  │ ├── async@1.0.0 
  │ └── colors@1.0.3 
  ├── wordwrap@0.0.2 
  ├── wrap-ansi@2.0.0 
  ├── wrappy@1.0.2 
  ├── ws@1.1.1 
  ├── xhr@2.2.2 
  ├── xml-parse-from-string@1.0.0 
  ├─┬ xml2js@0.4.17 
  │ └── xmlbuilder@4.2.1 
  ├─┬ xmlbuilder@4.0.0 
  │ └── lodash@3.10.1 
  ├── xmldom@0.1.22 
  ├── xpath@0.0.9 
  ├── xtend@4.0.1 
  ├── y18n@3.2.1 
  └── yargs@3.32.0 

***Appium 1.6.1***

magleahy@ip-10-99-16-56 ~/D/p/c/App> npm install -g appium@1.6.1
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.1"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.1"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/magleahy/Desktop/projects/client/App/npm-debug.log

***Appium 1.6.2***

magleahy@ip-10-99-16-56 ~/D/p/c/App> npm install -g appium@1.6.2
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.2"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.2"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/magleahy/Desktop/projects/client/App/npm-debug.log

***Appium: 1.6.3***

magleahy@ip-10-99-16-56 ~/D/p/c/App> npm install -g appium@1.6.3
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.3"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.3"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/magleahy/Desktop/projects/client/App/npm-debug.log

### supporting information:

 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS Sierra 10.12

See appium bug also raised as I am not sure where the problem lies: https://github.com/appium/appium/issues/7525

**Comment by jlipps** [comment] 2016-12-13 17:15
If you specifically install npm@4.0.5 it should work

**Comment by magleahy** [comment] 2016-12-13 17:22
Thanks @jlipps! 

Also ```npm install -g appium@1.6.3 --no-shrinkwrap``` works - found at the end of your 1.6.0 release page. Is this a bad way to install appium?

How could I be more autonomous about knowing to upgrade to npm@4.0.5? Is it documented? 

Cheers bro.

**Comment by magleahy** [comment] 2016-12-13 17:37
As you can see above - npm 4.0.2 and 4.0.3 exhibit the issue of installing appium via npm.

**Comment by jlipps** [comment] 2016-12-13 19:38
@magleahy installing without shrinkwrap is pretty dangerous because it means that you can get any valid version of a dependency, which for appium means completely different versions of the various drivers.

in terms of knowing about 4.0.5, i didn't :-) i googled for the error message that i saw in the npm log, found an npm issue, and saw that there was an npm bug for which upgrading to 4.0.5 was the resolution. that worked for me!

**Comment by zkat** [comment] 2016-12-15 05:33
@magleahy heya! Thanks for the super-detailed report with all the comparisons. This is almost certainly a duplicate of https://github.com/npm/npm/issues/14427, which was caused by a small oversight when using `bundledDependencies` when no `devDependencies` were defined (likely in one of the dependencies for `appium`.

So, in this case, upgrading to `npm@4.0.5` would definitely fix it (and that's becoming `latest` tomorrow). I'm going to close this as a duplicate, but please ping this thread again if that upgrade doesn't fix it for you, as we may have missed another spot. This was a particularly rude error that was incredibly hard to reproduce for us. :)

**Closed by zkat** 2016-12-15 05:33 UTC

**Comment by magleahy** [comment] 2016-12-15 14:44
Nice work @jlipps and @zkat!
