### ISSUE TITLE
npm run-script pollutes $PATH

### ISSUE THREAD

**Issue by sciyoshi** [npm/npm#12318] opened 2016-04-12 14:13 UTC
@iarna @segrey the fix from #11175 caused a regression which causes a different executable to be run from inside an npm script than from outside. See #5876 for a description of the original issue. This causes problems when trying to run scripts that depend on the PATH variable, like when using rvm or virtualenv.

**Comment by addaleax** [comment] 2016-04-12 17:13
Btw, the same patch also was quite a bit of trouble for @bcoe’s `nyc` (bcoe/nyc#190)… everything should be fixed there, but it meant having to give `npm` commands some special treatment.
#11175 makes sense and I wouldn’t want it to be reverted, but maybe having some opt-out mechanism for this behaviour would be nice? Would a patch for that be accepted?

**Comment by othiym23** [comment] 2016-04-12 17:55
> #11175 makes sense and I wouldn’t want it to be reverted, but maybe having some opt-out mechanism for this behaviour would be nice? Would a patch for that be accepted?

Probably not, because it would create a new set of edge cases to deal with, and likely cause a new set of regressions for people who are doing tricky things but aren't aware of the changed behavior. If you follow the discussion from #5876 to 021770b9cb07451509f0a44afff6c106311d8cf6, you can see some suggestion of using environment variables, but as I say there, to keep this from being a game of whack-a-mole, we need to enumerate the complete set of use cases that people have, and come up with a solution that we're confident addresses all of them.

**Comment by addaleax** [comment] 2016-04-12 19:01
Nah, okay then. I’d still like to write a bit for the `npm run` docs because this behaviour can definitely be surprising.

**Comment by StefanDywersant** [comment] 2016-04-26 21:24
The fix #11175 caused use of node 4.x impossible on some older systems. E.g. RHEL 6 is bundled with gcc 4.4.6 which doesn't understand v8's C++11 syntax. The solution was to use software collections (scl enable devtoolset-3 -- npm install). That scl script sets some env variables and what is most important modifies PATH to search in different place for gcc/g++. After #11175 '/usr/bin' (on most systems where node is installed from package) is added before scl's path elements and that causes node-gyp to be using standard compilers, then fail.

If you run into similar trouble you can downgrade npm temporarily to 2.14.20 which is last working version:
`npm install -g --verbose npm@2.14.20`

**Comment by bnoordhuis** [comment] 2016-05-25 16:57
FWIW, I've received several bug reports in the last few days where (in hindsight - I didn't realize it at the time) building add-ons under devtoolset fails because of this change.

I appreciate it fixes an issue but if it swaps one bug for another, then perhaps it's better to reconsider.

**Comment by akx** [comment] 2016-05-26 17:21
Yup, this is a problem for Pythonistas too (quoting #12859):

> Just bumped into an issue trying to run `python` commands in a `run-script` script with a [Python virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/) active.
> 
> npm 3.7.0+ prepends `/usr/bin` to the `PATH` in the environment where the runscript commands are run, on systems where `/usr/bin/python` is a thing, _and_ `node` lives in `/usr/bin` too (which means pretty much all of them) the user will never be able to use their virtualenv's Python interpreter in runscripts.
>
> My particular use case is to run `python manage.py makemessages` for a Django project; the symptom is, naturally, `ImportError: No module named django.core.management`, as the system-wide Python interpreter does not have the Django package.

**Closed** 2016-07-08 00:16 UTC
Labels: bug, needs-discussion

**Comment by evantorrie** [comment] 2016-07-18 21:07
This is also a problem for anyone who may have a `node` wrapper script which exists in a directory separate to where the node binary is installed.  Now it wants to run the node binary directly, rather than set up whatever may have been intended to set up via the wrapper script.

**Comment by addaleax** [comment] 2016-07-18 21:12
@evantorrie Would a solution like #13409 work in your case, i.e. an explicit opt-out of npm’s PATH modification using an configuration option?

**Comment by evantorrie** [comment] 2016-07-18 21:22
Yes, this would work for us.  Although we need it backported to the 2.x line as well.

**Comment by kadishmal** [comment] 2016-11-08 02:52
Downgrading to `npm install -g --verbose npm@2.14.20` with Node `4.6.1` didn't work on CentOS `6.5`. Previous version of Node `4.4.7` worked fine.
