### ISSUE TITLE
npm@5.8.0-next.0 ci shows progress bar

### ISSUE THREAD

**Issue by Ashot-KR** [npm/npm#20036] opened 2018-03-13 07:52 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
npm@5.8.0-next.0
`npm ci` command shows progress bar on installation process (`npm ci` on 5.7.1 runs without progress bar). Looks like regression.

#### How can the CLI team reproduce the problem?
In any project folder with `package.json`:
```bash
rm -rf node_modules #if folder exists
npm ci
```
You will see progress bar.

### supporting information:

 - `npm -v` prints: 5.8.0-next.0
 - `node -v` prints: v9.7.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS 10.13.2 (17C88)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment] 2018-03-13 18:43
I cannot reproduce this issue with `prgress=false` in `.npmrc`. Could you check your config file?

Refs: https://docs.npmjs.com/misc/config#progress

**Comment by Ashot-KR** [comment] 2018-03-14 07:37
here is my config
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.8.0-next.0 node/v9.7.1 darwin x64"

; builtin config undefined
prefix = "/usr/local"
python = "/usr/bin/python"

; node bin location = /usr/local/Cellar/node/9.7.1_1/bin/node
; cwd = /Users/Ashot/Projects/github-gql
; HOME = /Users/Ashot
; "npm config ls -l" to show all defaults.
```
I know about `progress` config. When `progress` set to `false` `npm ci` runs without progress bar.

`npm ci` on npm@5.7.1 runs without progress bar by default. If `progress` set to `true` in config there is also no progress bar.

**Comment by watilde** [comment] 2018-03-14 09:25
Thank you for the additional detail! I just confirmed this regression. Since `ci` command is supposed to be used in CI, the progress bar might not be necessary, but I'm also curious this was bug-fix or just a regression.

As a workaround, it is possible to add `npm config set progress false` in .travis.yaml.

**Comment by zkat** [comment] 2018-03-14 16:52
This is intentional

**Comment by zkat** [comment] 2018-03-14 20:50
anyway, now that I'm actually at a computer: `npm@5.7.1` does, indeed, have a progress bar. It's had one ever since it was first integrated with npm. The difference between `5.7.1` and `5.8.0-next.0` is that the progress bar _fills_ now, as opposed to sitting there, not moving, until it was done.

So, I don't consider this either a feature or a regression: it's a bugfix for a progress bar that was left static before, and you should be able to remove it the same way as usual by using the command @watilde mentioned.

THAT SAID, you should not need to do this on Travis: we disable the progress bar on Travis by default already, so if you don't have any particular setting, we'll do that. It _would_ be nice if we had a patch that checked additional CI environments (which we already do in `pacote`, for example), but that's orthogonal to this issue.

Since this is working as intended and is neither a regression nor a new feature that can actually change much, I'm gonna close this. Cheers!

**Closed as completed by zkat** 2018-03-14 20:50 UTC
Labels: npm5
