### ISSUE TITLE
npm install -g @angular/cli - Skips isexe dependency

### ISSUE THREAD

**Issue by rubencordoba** [npm/npm#16384] opened 2017-04-19 10:06 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I try to install @angular/cli everything seems to be OK, but it's skipping the isexe dependency because fsevents. Tried with different versions of npm but the error persists.

#### How can the CLI team reproduce the problem?

npm install -g @angular/cli

### Supporting information:

 - `npm -v` prints:

![image](https://cloud.githubusercontent.com/assets/6088529/25174537/f4d4476c-24f7-11e7-95f3-c15d9ef341c3.png)

- Report when I create a new Angular project via Angular CLI on WebStorm:

![image](https://cloud.githubusercontent.com/assets/6088529/25174703/81535d36-24f8-11e7-869d-2e147cd566e8.png)

 - Windows, OS X/macOS, or Linux?: Windows 8 x64
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by legodude17** [comment] 2017-04-19 16:03
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

Also, the first part is not what `npm -v` should print. What command did you run?

**Closed** 2017-06-17 03:26 UTC
Labels: bot-closed
