### ISSUE TITLE
Edge case relating to node_modules path location

### ISSUE THREAD

**Issue by foxx** [npm/npm#9479] opened 2015-09-03 11:49 UTC
There was already a discussion about this in #775, and was subsequently marked as wontfix by @isaacs, then locked by @othiym23 to prevent bikeshedding. I've taken time to read all the comments, and would like to re-open discussion due to a specific edge case.

### The problem

This involves shared folders with Vagrant (or even without) in which `node_modules` being placed on the shared folder causes `npm` errors which cannot be reproduced if installed into a directory which is not on the shared folder. Further more, the performance impact from it being stored on a shared folder (or even via NFS), has a significant impact and noticeable lag.

### Workarounds

There are several workarounds, each with their own side effects;

A) Run `node_modules` on the shared folder. This requires symlink [fixes][1] but still results in errors thrown by `npm` for some packages.
B) Symlink `node_modules` to an `mktemp`. This causes the same issues as A
C) Create a bind mount to an `mktemp`, as a `preinstall` scripts hook. This does work, but requires root access and a lot of messy bootstrapping code.
D) Globally install the packages. This can be achieved without root by using `nvm`, however you cannot create multiple environments for the same node version, which can cause issues for repos with multiple `project.json` files (e.g. client/server in the same repo)

### Alternative solutions

I've been thinking of some ways this could be made easier. Allowing `node_modules` to be redirected using an ENV var isn't perfect, because it would require `npm` to be prefixed on every command. Having an option inside `package.json` could work, but it would require a fixed location and thus unable to use `mktemp`.

### Conclusion

As such, I'm not entirely sure that allowing `node_modules` to be moved is the correct way forward. Instead, I'm thinking that the better option would be to ask `nvm` maintainers if they can add support for multiple environments of the same version.

Before I submit this request to `nvm`, I would any/all appreciate feedback on the above. Any alternative approaches/ideas?

Thanks in advance

[1]: https://github.com/mitchellh/vagrant/issues/6188

**Comment by foxx** [comment] 2015-09-10 11:47
Further update, it would seem that installing globally isn't a complete fix as because some packages require modules to be installed locally rather than globally, for example [grunt](http://stackoverflow.com/questions/13925916/fatal-error-unable-to-find-local-grunt).

Another fix is to use a FUSE layer to automatically redirect `node_modules` to an `mktemp -d`, but this seems like an awful lot of overheads.

**Comment by foxx** [comment] 2015-10-08 11:59
Shamelessly bumping after running into this problem again today. If there are any core devs that have spare time to look at this, it would be much appreciated.

**Comment by foxx** [comment] 2015-10-08 12:15
After a bit of searching, another user discovered that changing the symlink destination dirname to `node_modules` allows symlinks to work without breaking packages, and thus fixes this problem.

As stated by that other (see above), I would concur that this is very strange behaviour, and as such would mark as a bug. Should I open a new ticket for this?

**Comment by iarna** [comment] 2015-11-10 22:57
What errors, specifically, do you get when you use the latter type of link?

**Comment by Perni1984** [comment] 2016-01-13 18:59
Just for other users that might run into these problems on windows hosts - the moving out node_modules directory and symlinking to it are perfectly possible with Vagrant and a Linux Guest OS.

Using a guest OS with linux kernel > 3.18 (e.g. ubuntu/vivid64):

config.vm.synced_folder "/projectfolder/www", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]

Symlinks are then supported in the guest OS, aswell as smb3 (improved performance for shared folders). I am successfully running npm inside my linux guest flawlessly. I was running into a lot of problems before.

**Comment by othiym23** [comment] 2016-01-21 23:13
npm should support having `node_modules` be a symlink to somewhere else. That's the best support that I think we can reasonably offer for this class of vm-based use cases, because there are a bunch of virtualized environments out there and they all have slightly different constraints, making it very difficult to put together a general solution. As far as the team knows, symlinking `node_modules` currently works, so we're going to close this issue.

If you do run into issues with symlinked installs (@iarna wasn't able to reproduce the issue @foxx mentioned above), then it's entirely appropriate to file issues, because those are bugs. Thanks for your time, and thanks for the thorough rundown of the problem and workaround!

**Closed by othiym23** 2016-01-21 23:13 UTC
Labels: bug, feature-request, needs-bikeshedding

**Comment by foxx** [comment] 2016-01-22 00:24
@othiym23 @iarna The bug is easily reproducible, and this is certainly still a valid issue. If I get a chance, I'll submit the `npm-debug.log` along with a small project that demonstrates the problem

**Comment by jacobat** [comment] 2016-01-22 08:26
FWIW, I have this issue as well. And I'm just putting `node_modules` in a different spot on disk for caching purposes. That is we have `app/node_modules` as a symlink to `/var/cache/node_modules-${CACHE_KEY}` and this breaks our `npm run` for webpack with the error mentioned in https://github.com/webpack/webpack/issues/1134 that is:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'webpack/lib/ConcatSource'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/cache/node_modules-edba3300028807464b214123f07a8e2b/extract-text-webpack-plugin/index.js:5:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 3.13.0-62-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "prod"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
```

**Comment by foxx** [comment] 2016-05-16 16:34
Not sure why @othiym23 closed this issue, I provided a way to reproduce the problem and others are also reporting the same issues. Can we please get this re-opened?
