### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tonyhogben** [npm/npm#8696] opened 2015-06-26 09:14 UTC
verbose stack Error: No compatible version found: weinre@'*'
    verbose stack Valid install targets:
    verbose stack ["2.0.0-pre-H0WTHDO5-incubating","2.0.0-pre-H1GCS73N-incubating","2.0.0-pre-H3FWTQKQ-incubating","2.0.0-pre-H41DGW8S-incubating","2.0.0-pre-H8EOSCLN-incubating","2.0.0-pre-H9PU2WST-incubating","2.0.0-pre-HA5N9T49","2.0.0-pre-HG9PLCRF","2.0.0-pre-HH0SN197","2.0.0-pre-HYFXM3QM","2.0.0-pre-HZ79PDUK","2.0.0-pre-HZO3BMNG","2.0.0-pre-I0Z7U9OV"]
    verbose stack
    verbose stack     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-named.js:274:12)
    verbose stack     at next (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-named.js:253:17)
    verbose stack     at setData (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-named.js:230:5)
    verbose stack     at RES (C:\Program Files\nodejs\node_modules\npm\node_modules\inflight\inflight.js:23:14)
    verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
    verbose stack     at fixName (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-named.js:29:5)
    verbose stack     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:173:7)
    verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
    verbose cwd C:\
    error Windows_NT 6.1.7601
    error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "weinre"
    error node v0.12.5
    error npm  v2.11.2
    error code ETARGET
    error notarget No compatible version found: weinre@'*'
    error notarget Valid install targets:
    error notarget ["2.0.0-pre-H0WTHDO5-incubating","2.0.0-pre-H1GCS73N-incubating","2.0.0-pre-H3FWTQKQ-incubating","2.0.0-pre-H41DGW8S-incubating","2.0.0-pre-H8EOSCLN-incubating","2.0.0-pre-H9PU2WST-incubating","2.0.0-pre-HA5N9T49","2.0.0-pre-HG9PLCRF","2.0.0-pre-HH0SN197","2.0.0-pre-HYFXM3QM","2.0.0-pre-HZ79PDUK","2.0.0-pre-HZO3BMNG","2.0.0-pre-I0Z7U9OV"]
    error notarget
    error notarget This is most likely not a problem with npm itself.
    error notarget In most cases you or one of your dependencies are requesting
    error notarget a package version that doesn't exist.

**Comment by rosen-vladimirov** [comment] 2015-06-30 13:07
Hi,
Is this expected behavior? It looks like we are unable to install any npm package, which has dash in its name. I'm able to install only packages with strict versions (1.0.0, 1.0.1, etc.), but versions like 1.0.0-211 is not installed and ETARGET error is raised. I've tried npm 2.11.2, 2.11.3, 2.12.0 and each of them is failing to install packages with dash in the name.  I've also tried 2.11.0 and 2.11.1 and all of the packages are installed correctly. 
Can someone confirm what and why had been changed?

**Comment by getify** [comment] 2015-07-06 04:27
I think it's possible this bug is also affecting my package, too. Just had this reported to me:

https://github.com/getify/You-Dont-Know-JS/issues/480

**Comment by KenanY** [comment] 2015-07-06 05:43
`git bisect` tells me that https://github.com/npm/npm/commit/ef6be38ea056418f251a3c6368a4f0b0583c2b26 introduced this

```
ef6be38ea056418f251a3c6368a4f0b0583c2b26 is the first bad commit
commit ef6be38ea056418f251a3c6368a4f0b0583c2b26
Author: Forrest L Norvell <forrest@npmjs.com>
Date:   Sun May 31 21:12:28 2015 -0700

    semver@4.3.5
    
    Improved testing, with coverage.

:040000 040000 f60302a18a2df1df6cb38fbdacc48546327d12ff 96ad1e737d0fabcb1103da93273fa3c5cb26d940 M	node_modules
:100644 100644 2bf7700dc8e7195d3b08c9787f2d4eccd1e055ba 9fb57f4eb21ecd46b3e5738f0933a27f2fca04d8 M	package.json
```

**Comment by iarna** [comment] 2015-07-06 07:50
semver@4.3.5 made this change intentionally:

https://github.com/npm/node-semver/commit/93a870665bba0f4be5c4edc19d6f94ff39ad60e8
https://github.com/npm/node-semver/issues/123

To my mind it would make sense for npm, if `*` fails to match anything, to fallback to using the `latest` tag instead.

**Comment by getify** [comment] 2015-07-06 12:29
> semver@4.3.5 made this change intentionally:

That's a pretty big breaking change that was introduced in a patch level update to npm. :(

In every single package I maintain, I use the `-xxx` level differently than strict semver when I'm in 0.x world. Essentially, I shift the octets by one place, so that it's 0.major.minor-patch instead of major.minor.patch-tag.

I was also under the impression that semver rules weren't supposed to apply to 0.x versioned packages, so it seems wrong for semver/npm to start intentionally applying this new rule to 0.x versions.

**Comment by iarna** [comment] 2015-07-06 18:46
Bug fixes are breaking if you depend on the bug, yes? I dunno though, we'll have to talk about this more.

**Comment by getify** [comment] 2015-07-06 18:54
> Bug fixes are breaking if you depend on the bug, yes?

Did I miss that semver now applies to 0.x as well? Or did I miss that npm says that even though semver doesn't apply to 0.x, npm is going to apply semver rules to 0.x? I was certainly under the impression that for the most part I could do whatever I wanted while under the 0.x umbrella. It appears not.

> We'll keep you informed!

Thanks!

**Comment by iarna** [comment] 2015-07-06 19:08
0.x still has semver applied to it if people use `^`. You can see that behavior described here: https://www.npmjs.com/package/semver#caret-ranges-1-2-3-0-2-5-0-0-4

**Comment by getify** [comment] 2015-07-06 21:47
I was aware of that and that's what I meant by "...for the most part..." The ^ vs ~ has rarely been an issue in practice for those who use my packages.

**Comment by iarna** [comment] 2015-07-06 22:34
Sorry, I was replying to "Did I miss that semver now applies to 0.x as well?"  That link is where it talks about semver applying to 0.x as well.

**Comment by iarna** [comment] 2015-07-08 05:31
I've opened a new issue to make modules w/o any non-prerelease versions installable here: https://github.com/npm/npm/issues/8855

I'm going to close this issue in preference to that one, but please feel free to open a new issue if you feel that doesn't address your problem.

**Closed by iarna** 2015-07-08 05:31 UTC
Labels: support
