### ISSUE TITLE
install asn1 fails for unclear reason

### ISSUE THREAD

**Issue by iliakan** [npm/npm#9886] opened 2015-10-07 20:04 UTC
Try `npm i asn1` with the latest npm@3.

That's the error:
```
npm ERR! Cannot read property 'localeCompare' of undefined
```

That's the log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i', 'asn1' ]
2 info using npm@3.3.5
3 info using node@v4.1.2
4 verbose config Skipping project config: /Users/iliakan/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData asn1
9 silly fetchNamedPackageData asn1
10 silly mapToRegistry name asn1
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/asn1
14 verbose request uri https://registry.npmjs.org/asn1
15 verbose request no auth needed
16 info attempt registry request try #1 at 23:03:15
17 verbose request id 9431018c6d2f435e
18 verbose etag "DDLF9L8HF721MHU45QBXII2UU"
19 http request GET https://registry.npmjs.org/asn1
20 http 304 https://registry.npmjs.org/asn1
21 verbose headers { date: 'Wed, 07 Oct 2015 20:03:15 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=60',
21 verbose headers   etag: '"DDLF9L8HF721MHU45QBXII2UU"',
21 verbose headers   age: '34',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-fra1229-FRA',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '2',
21 verbose headers   'x-timer': 'S1444248195.453653,VS0,VE0',
21 verbose headers   vary: 'Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Wed, 07 Oct 2015 20:03:15 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=60',
22 silly get     etag: '"DDLF9L8HF721MHU45QBXII2UU"',
22 silly get     age: '34',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-fra1229-FRA',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '2',
22 silly get     'x-timer': 'S1444248195.453653,VS0,VE0',
22 silly get     vary: 'Accept' } ]
23 verbose etag https://registry.npmjs.org/asn1 from cache
24 verbose get saving asn1 to /Users/iliakan/.npm/registry.npmjs.org/asn1/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule asn1@0.2.3 checking installable status
38 silly cache add args [ 'asn1', null ]
39 verbose cache add spec asn1
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'asn1',
40 silly cache add   scope: null,
40 silly cache add   name: 'asn1',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: '*',
40 silly cache add   type: 'range' }
41 silly addNamed asn1@*
42 verbose addNamed "*" is a valid semver range for asn1
43 silly addNameRange { name: 'asn1', range: '*', hasData: false }
44 silly mapToRegistry name asn1
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/asn1
48 verbose addNameRange registry:https://registry.npmjs.org/asn1 not in flight; fetching
49 verbose get https://registry.npmjs.org/asn1 not expired, no request
50 silly addNameRange number 2 { name: 'asn1', range: '*', hasData: true }
51 silly addNameRange versions [ 'asn1',
51 silly addNameRange   [ '0.1.0',
51 silly addNameRange     '0.1.1',
51 silly addNameRange     '0.1.2',
51 silly addNameRange     '0.1.3',
51 silly addNameRange     '0.1.4',
51 silly addNameRange     '0.1.5',
51 silly addNameRange     '0.1.6',
51 silly addNameRange     '0.1.7',
51 silly addNameRange     '0.1.8',
51 silly addNameRange     '0.1.9',
51 silly addNameRange     '0.1.10',
51 silly addNameRange     '0.1.11',
51 silly addNameRange     '0.2.0',
51 silly addNameRange     '0.2.1',
51 silly addNameRange     '0.2.2',
51 silly addNameRange     '0.2.3' ] ]
52 silly addNamed asn1@0.2.3
53 verbose addNamed "0.2.3" is a plain semver version for asn1
54 silly mapToRegistry name asn1
55 silly mapToRegistry using default registry
56 silly mapToRegistry registry https://registry.npmjs.org/
57 silly mapToRegistry uri https://registry.npmjs.org/asn1
58 verbose addRemoteTarball https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz',
59 verbose addRemoteTarball   'dac8787713c9966849fc8180777ebe9c1ddf3b86' ]
60 info retry fetch attempt 1 at 23:03:22
61 info attempt registry request try #1 at 23:03:22
62 http fetch GET https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz
63 http fetch 200 https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz
64 silly fetchAndShaCheck shasum dac8787713c9966849fc8180777ebe9c1ddf3b86
65 verbose addTmpTarball /tmp/npm-15652-25c13f45/registry.npmjs.org/asn1/-/asn1-0.2.3.tgz not in flight; adding
66 verbose addTmpTarball already have metadata; skipping unpack for asn1@0.2.3
67 silly cache afterAdd asn1@0.2.3
68 verbose afterAdd /Users/iliakan/.npm/asn1/0.2.3/package/package.json not in flight; writing
69 verbose afterAdd /Users/iliakan/.npm/asn1/0.2.3/package/package.json written
70 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
70 verbose stack     at installOrder (/usr/local/lib/node_modules/npm/lib/install/deps.js:241:32)
70 verbose stack     at Array.sort (native)
70 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:240:27
70 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
70 verbose stack     at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:377:3)
70 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:347:5
70 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
70 verbose stack     at Array.forEach (native)
70 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
70 verbose stack     at Array.forEach (native)
71 verbose cwd /Users/iliakan
72 error Darwin 14.5.0
73 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "asn1"
74 error node v4.1.2
75 error npm  v3.3.5
76 error Cannot read property 'localeCompare' of undefined
77 error If you need help, you may report this error at:
77 error     <https://github.com/npm/npm/issues>
78 verbose exit [ 1, true ]
```

**Comment by iliakan** [comment] 2015-10-07 20:05
P.S. There is an issue https://github.com/npm/npm/issues/9766, maybe somehow related?

**Comment by KenanY** [comment] 2015-10-07 20:24
@iliakan This is probably a duplicate of that issue.

**Comment by iliakan** [comment] 2015-10-07 20:55
I thought so too, but https://github.com/npm/npm/issues/9766#issuecomment-145644794 says something about an incorrect package.json, and in asn1 it's valid.

**Comment by iarna** [comment] 2015-10-08 23:04
#9766 has comments about a few different causes of very much the same error message. I'm going to close this as a duplicate, but that's mostly because I'm about to land a patch that will resolve all of these related issues.

**Closed by iarna** 2015-10-08 23:04 UTC

**Comment by iliakan** [comment] 2015-10-09 06:37
@iarna thanks, great to hear!
