### ISSUE TITLE
Installing Gulp into my Laravel project fails

### ISSUE THREAD

**Issue by larsl** [npm/npm#5934] opened 2014-08-13 12:44 UTC
I'm trying to install gulp for a Laravel Project (using their Homestead VM). I've tried the recommended fixes of updating NPM, or clearing the cache. This is the error I see when trying it:

```
npm WARN package.json @ No repository field.
npm ERR! error rolling back Error: ETXTBSY, unlink '/home/vagrant/Code/Territory/node_modules/gulp/node_modules/liftoff/artwork/liftoff-icon.eps'
npm ERR! error rolling back  gulp@3.8.7 { [Error: ETXTBSY, unlink '/home/vagrant/Code/Territory/node_modules/gulp/node_modules/liftoff/artwork/liftoff-icon.eps']
npm ERR! error rolling back   errno: 62,
npm ERR! error rolling back   code: 'ETXTBSY',
npm ERR! error rolling back   path: '/home/vagrant/Code/Territory/node_modules/gulp/node_modules/liftoff/artwork/liftoff-icon.eps' }
npm ERR! Error: UNKNOWN, symlink '../supports-color/cli.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-30-generic
npm ERR! command "node" "/usr/bin/npm" "install" "gulp" "--save-dev"
npm ERR! cwd /home/vagrant/Code/Territory
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.23
npm ERR! path ../supports-color/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! Error: ENOENT, lstat '/home/vagrant/Code/Territory/node_modules/gulp/node_modules/semver/test/index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-30-generic
npm ERR! command "node" "/usr/bin/npm" "install" "gulp" "--save-dev"
npm ERR! cwd /home/vagrant/Code/Territory
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.23
npm ERR! path /home/vagrant/Code/Territory/node_modules/gulp/node_modules/semver/test/index.js
npm ERR! fstream_path /home/vagrant/Code/Territory/node_modules/gulp/node_modules/semver/test/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/Code/Territory/npm-debug.log
npm ERR! not ok code 0

```

**Comment by smikes** [comment] 2015-01-06 13:15
@larsl , Is this still a problem for you?

You state above that you couldn't reproduce it anymore; I wonder if this could have been an unusual presentation of the race conditions that were present in < `npm@2.1`

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.23. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-01-15 22:39
Closing as abandoned.

**Closed by othiym23** 2015-01-15 22:39 UTC
Labels: support

**Comment by pavel-ms** [comment] 2015-04-17 07:02
Hello! 
Sorry for late answer, but I was able to reproduce the issue. 
But I think it is not npm problem, but VM issue. When your VM directory is mounted to your local windows direcroty it seems the npm can't create symlink in .bin directory. 
You need just run virtual machine as windows-admin user to fix the problem.

**Comment by bompi88** [comment] 2016-05-13 13:39
@pavelmics This was the case or me as well 👍 had to run as `sudo`
