### ISSUE TITLE
unable to install npm 

### ISSUE THREAD

**Issue by gauravsuk** [npm/npm#16152] opened 2017-03-25 10:25 UTC
[npm-debug.log.txt](https://github.com/npm/npm/files/869921/npm-debug.log.txt)
ERR! Linux 4.4.0-67-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2

npm ERR! shasum check failed for /tmp/npm-28685-ac61c808/registry.npmjs.org/browser-sync-ui/-/browser-sync-ui-0.6.3.tgz
npm ERR! Expected: 640a537c180689303d5be92bc476b9ebc441c0bc
npm ERR! Actual:   152f66fd9099f17f2b5bb47c27b2c6ec660eaaf9
npm ERR! From:     https://registry.npmjs.org/browser-sync-ui/-/browser-sync-ui-0.6.3.tgz

**Comment by legodude17** [comment] 2017-03-27 16:06
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:56 UTC
Labels: bot-closed, support
