### ISSUE TITLE
running npm scripts directly from node_modules/.bin seems to be broken in windows

### ISSUE THREAD

**Issue by SoonDead** [npm/npm#10413] opened 2015-11-16 14:12 UTC
For example in a scenario where I have gulp installed as a devDependency but not as global:

    > npm install gulp --save-dev
    > npm run gulp

This throws the error `missing script "gulp"`.

But if I define a dummy script

    scripts: {
        "gulpdummy": "npm run gulp"
    }

I can run gulp properly:

    > npm run gulpdummy

Why does npm run gulp fail? gulp.cmd is present in `node_modules/.bin`. If I remember correctly this worked before.

Or am I assuming something incorrect?

**Comment by KenanY** [comment] 2015-11-16 15:49
@SoonDead Are you sure you don't want to do this?:

``` json
{
  "scripts": {
    "gulp": "gulp"
  }
}
```

**Comment by SoonDead** [comment] 2015-11-16 16:10
@KenanY I'm able, to but shouldn't npm run gulp run without it if `node_modules/.bin/gulp.cmd` is present?

**Comment by KenanY** [comment] 2015-11-16 16:24
@SoonDead Erm, no. `npm run` runs npm scripts, not binaries in `node_modules/.bin`. I think you're looking for `npm-exec` (https://github.com/npm/npm/issues/6053), which does not exist yet in `npm` but there are modules in userland you can check out I think.

**Comment by MoOx** [comment] 2016-03-08 07:03
@KenanY npm run automatically add node_modules/.bin in PATH, so it can call any bin in this place.

**Comment by KenanY** [comment] 2016-07-05 17:16
Closing since this is expected behavior. `npm run gulp` does not run `node_modules/.bin/gulp`; it runs the `"gulp"` script from your `package.json`. This behavior is unlikely to change, rather a new command (i.e. `npm exec`) would need to be added, and there are open issues for this already.

**Closed by KenanY** 2016-07-05 17:16 UTC
