### ISSUE TITLE
Support for custom shorthand URL prefix

### ISSUE THREAD

**Issue by ovmjm** [npm/npm#3943] opened 2013-09-27 09:47 UTC
Please allow me to redirect you to the following issue I opened last week in the [normalize-package-data](https://github.com/meryn/normalize-package-data) repository

https://github.com/meryn/normalize-package-data/issues/35

This concerns adding an option to override the default git://github.com/ prefix that is used with repository shorthand URLs.

The idea comes from the _shorthand-resolver_ config option, a template string, from the [bower](https://github.com/bower/bower) project, which is defined in this [document](https://docs.google.com/document/d/1APq7oA9tNao1UYWyOm8dKqlRP2blVkROYLZ2fLIjtWc/edit).

I can see it to be very useful to easily refer to in-house projects without hard-coding the full repo URL. Also very handy when it comes to hand-over the code-base to the customer or another agency.

Do you think such an option has its place in npm ?

**Comment by zeke** [comment] 2015-02-03 06:32
+1

**Comment by nicksrandall** [comment] 2015-12-01 00:12
+1

**Comment by slang800** [comment] 2016-04-16 08:10
sounds like a dupe of: https://github.com/npm/npm/issues/11749

**Comment by othiym23** [comment] 2016-05-20 21:12
The npm CLI team isn't going to add this, for the reasons I describe in #11749. People I've talked to about this are pretty consistent that custom resolvers were a bad choice for Bower, and they'd be a bad choice for npm. However, if there are specific Git providers you'd like to see added to the set recognized by npm, you can send a pull request to [`hosted-git-info`](http://github.com/npm/hosted-git-info), and we'll work with you to see if / how it can be merged. (Fun fact: `bitbucket:`, `gitlab:` and `gist:` are already included.) Thanks for your time!

**Closed by othiym23** 2016-05-20 21:12 UTC
Labels: feature-request

**Comment by moravcik** [comment] 2016-08-31 23:41
In Bower, I'm using shordhand resolver to access Github private repos with personal access token stored in env variable `GITHUB_TOKEN` :

    "shorthand_resolver": "https://${GITHUB_TOKEN}@github.com/{{owner}}/{{package}}.git"

Now I am trying to migrate to NPM, but I haven't found an alternative to use `GITHUB_TOKEN` env variable to access private repos. Is there any preferred way other than `ssh+git`? I don't like `git+ssh` solution much as I need to expose my private SSH key into the build environment (Heroku).
