### ISSUE TITLE
npm5 fails with combination of bundledDependencies and shrinkwrap

### ISSUE THREAD

**Issue by rmg** [npm/npm#17002] opened 2017-06-06 00:44 UTC
Scenario is a top-level package with an `npm-shrinkwrap.json` with some dependencies having _their_ dependencies bundled.

This is reproducibly broken with this publicly accessible combination:
 - npm@5.0.2
 - apiconnect@2.6.50

Under npm@4, `npm i -g apiconnect` works as expected, but with npm@5, it gets tripped up trying to re-resolve a (deeply nested) bundled version of `minimist@0.0.8` which happened to have originally been installed from an internal registry before publishing as a bundled dep of `appmetrics@2.0.1`.

It seems tricky to explain in prose, so here's a (heavily) pruned and annotated snippet of the troublesome tree that I hope will make it more clear:
```
apiconnect@2.6.50                   <-- npm-shrinkwrap.json at this level
└─┬ apiconnect-cli-pm@2.4.2
  └─┬ strong-pm@6.0.1
    └─┬ strong-runner@7.0.0
      └─┬ strong-supervisor@6.1.1
        └─┬ appmetrics-dash@3.1.0
          └─┬ appmetrics@2.0.1      <-- lists 'tar' in bundledDependencies
            └─┬ tar@2.2.1           <-- tar and deps installed from internal registry
              └─┬ fstream@1.0.10        before appmetrics was published
                └─┬ mkdirp@0.5.1
                  └── minimist@0.0.8   <-- hangs trying to fetch tarball from _resolved
                                           prop in bundled minimist's package.json
```

By "hangs" I mean `npm` prints an error message about a 404 and then appears to just sit and spin.

**Comment by rmg** [comment] 2017-06-08 01:11
@zkat could I trade 15 minutes of your time pointing me in the right direction here in exchange for me taking a stab at a PR to fix it?

**Comment by zkat** [comment] 2017-06-08 07:04
@rmg hi! Ok so with this one, it turns out I have an idea! The shrinkwrap you generated doesn't mark the bundled dependencies as such, which is why npm5 is trying to go out and fetch them.

Unfortunately, there's no way right now of recovering that bundle information from legacy shrinkwrap (apparently. I thought there was, but obviously not). My main recommendation here, if you're able, is that you remove node_modules, remove npm-shrinkwrap.json, and just do a full install + shrinkwrap using npm5. That will retain bundle dep information and you should stop seeing this error.

If that isn't possible or you're strongly opposed to that, you need to manually edit your shrinkwrap and add `bundled: true` to every entry in it that you know is bundled, and remove its `integrity` field. Otherwise, npm will try and replace it right now, because it insists on reproducing the shrinkwrap as described -- and that includes deciding that those deps aren't coming from a bundle.

As far as patches go, one thing that we maybe could be improved and is maaaaybe not incredibly hard to do is patch npm such that _when it runs into these legacy shrinkwraps_, it identifies any extracted bundleDeps that match entries in the shrinkwrap, and then markes those deps as bundled in the ideal tree. This feels like it might be a bit tricky to do, and /cc @iarna on it, but it might improve the upgrade path for folks who already had these shrinkwraps.

I've been working on improving the upgrade path for legacy shrinkwraps, too: the latest `npmc` has some of that work, so more folks who used shrinkwrap pre-5 will now transparently move to `lockfileVersion=1`. But this bundle stuff seems like it's gonna take a bit of work.

If you're curious, I think the part of the code that would need to figure out these bits of the tree and update it are over at https://github.com/npm/npm/blob/release-next/lib/install/action/extract.js#L65-L98. But that's just my initial thought, and I'm not sure exactly what or could be done here to reconstruct bundle information from whatever is available. And in the case of bundleDeps, it would even depend on what version that bundleDep was bundled _with_.

**Comment by rmg** [comment] 2017-06-08 17:48
Hm. Well the problem is this is a CLI tool, so people aren't "upgrading" so much as just installing the latest and greatest `node` which comes with the latest and greatest `npm` which fails to install the latest and greatest `apiconnect`, even though all of these "latest and greatest" releases are less than a week old.

And of course then there are previous releases for those that require compatibility with other things, but I personally don't consider that a particularly strong argument.

In any case, I'm sure you can see why I was hoping to be able to fix this in npm.

If the shrinkwrap was regenerated with npm5, would npm2 still be able to install it properly?

**Comment by rmg** [comment] 2017-06-08 19:00
For the workaround, it turns out that manually adding `"bundled": true` to the troublesome items in `npm-shrinkwrap.json` is sufficient. It sounds tedious, but it's a lot _less_ tedious that reviewing a diff of a completely re-generated shrinkwrap.

**Comment by zkat** [comment] 2017-06-08 21:58
@rmg the conclusion @iarna and I reached seems to basically be that folks who were previously using `npm-shrinkwrap.json` will have to regenerate it. It's too unlikely for us to have enough information to construct a new-style shrinkwrap from legacy ones, when it comes to bundles, and shrinkwraps and bundles are both things people used pretty rarely. Enough that it's probably fine to say "welp".

Glad this worked out, I guess. I'm just gonna close this now. :)

**Closed as completed by zkat** 2017-06-08 21:58 UTC
Labels: bug, shrinkwrap, npm5
