### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by mosnet99** [npm/npm#8604] opened 2015-06-18 17:31 UTC
![git](https://cloud.githubusercontent.com/assets/12955763/8237544/142fdc02-15be-11e5-9634-c53fce35e7c9.JPG)

I'm new to using Get Bash, I'm trying to install bower and I got this error. I'm not sure if I was supposed to assign a directory or give permissions or what. Any help would be nice.

**Comment by tjwebb** [comment] 2015-06-19 01:28
Try clearing your npm cache folder by deleting that `npm-15284...` folder and trying again.

**Comment by zkat** [comment] 2016-12-09 00:57
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:57 UTC
Labels: shasum, support
