### ISSUE TITLE
npm 3: install fails on Windows with node 0.10

### ISSUE THREAD

**Issue by mantoni** [npm/npm#8750] opened 2015-06-29 09:34 UTC
Installing anything on a Windows workstation fails with `Error: EACCES, access '{project-dir}'`.

The error happens on this line: https://github.com/npm/npm/blob/master/lib/install/check-permissions.js#L77

It works fine when switching to Node 0.12 and it also works on Unix with Node 0.10.
I checked with the Windows `cmd` and also through cygwin.

@iarna @othiym23 Please advise if there is any temporary hack that we could put in locally to work around the issue.

**Comment by lukeapage** [comment] 2015-06-30 09:50
+1 this exact error is happening to me with node 0.10.30

**Comment by lukeapage** [comment] 2015-06-30 09:54
duplicate of : https://github.com/npm/npm/issues/8701

**Comment by lukeapage** [comment] 2015-06-30 10:40
temporary hack explained here: https://github.com/npm/npm/issues/8701#issuecomment-117118250

**Comment by iarna** [comment] 2015-07-01 07:33
Yeah, I'm closing this as a dup of #8701. I'm going to start by disabling this check on windows this week and then I'll come back to figuring out how to do this right later on.

**Closed by iarna** 2015-07-01 07:33 UTC
