### ISSUE TITLE
shasum mismatch installing appium

### ISSUE THREAD

**Issue by amritha2** [npm/npm#12119] opened 2016-03-29 07:40 UTC
The following is the log for the error . Kindly provide the necessary  support!

```
22728 verbose stack Error: shasum check failed for /var/folders/j8/ctr_ybtx37xgws4_9bqc05mw0000gn/T/npm-64659-3a0437ae/registry.npmjs.org/appium-selendroid-driver/-/appium-selendroid-driver-1.2.2.tgz
22728 verbose stack Expected: 78e5f671451fe989f3f00400490e2dcccb11f0aa
22728 verbose stack Actual:   e1af6cef8ea44de3296b54e63c4819e0081ee484
22728 verbose stack From:     https://registry.npmjs.org/appium-selendroid-driver/-/appium-selendroid-driver-1.2.2.tgz
22728 verbose stack     at /Users/apple/local/lib/node_modules/npm/node_modules/sha/index.js:25:8
22728 verbose stack     at ReadStream.<anonymous> (/Users/apple/local/lib/node_modules/npm/node_modules/sha/index.js:72:7)
22728 verbose stack     at emitNone (events.js:85:20)
22728 verbose stack     at ReadStream.emit (events.js:179:7)
22728 verbose stack     at endReadableNT (_stream_readable.js:913:12)
22728 verbose stack     at _combinedTickCallback (node.js:383:13)
22728 verbose stack     at process._tickCallback (node.js:407:11)
22729 verbose cwd /Users/apple/node-latest-install
22730 error Darwin 15.2.0
22731 error argv "/Users/apple/local/bin/node" "/Users/apple/local/bin/npm" "install" "-g" "appium"
22732 error node v5.9.1
22733 error npm  v3.8.3
22734 error shasum check failed for /var/folders/j8/ctr_ybtx37xgws4_9bqc05mw0000gn/T/npm-64659-3a0437ae/registry.npmjs.org/appium-selendroid-driver/-/appium-selendroid-driver-1.2.2.tgz
22734 error Expected: 78e5f671451fe989f3f00400490e2dcccb11f0aa
22734 error Actual:   e1af6cef8ea44de3296b54e63c4819e0081ee484
22734 error From:     https://registry.npmjs.org/appium-selendroid-driver/-/appium-selendroid-driver-1.2.2.tgz
```

https://gist.github.com/othiym23/730c42fbe9b9baf51bbd8e91f9add77b

**Comment by zkat** [comment] 2016-12-09 00:28
Closing as a duplicate of https://github.com/npm/npm/issues/14626.

**Closed by zkat** 2016-12-09 00:28 UTC
Labels: network, shasum, support
