### ISSUE TITLE
npm update -g no longer working

### ISSUE THREAD

**Issue by ffxsam** [npm/npm#13210] opened 2016-06-29 00:11 UTC
### I'm opening this issue because:
- [ ] npm is crashing
- [ ] npm is producing an incorrect install
- [X] npm is doing something I don't understand
- [ ] other (_see below for feature requests_)
#### Node version:

v6.2.2
#### npm version:

3.10.2
#### How did you install Node and npm?

nvm install v6.2.2
#### Operating system version and distribution:

Darwin Vader.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
#### Containerization or virtualization environment:

N/A
#### Are you using [a proxy](https://docs.npmjs.com/misc/config#proxy)?

No
#### What problem are you seeing?

`npm update -g` does nothing, despite several packages being out of date. `npm ls -g --depth 0` shows:

```
/Users/samh/.nvm/versions/node/v6.2.2/lib
├── babel-cli@6.7.7
├── doctoc@1.0.0
├── generator-react-cdk@1.1.0
├── grunt-cli@1.2.0
├── meteor-mongo-sync@0.7.2
├── npm@3.10.2
├── npm-check-updates@2.6.7
├── react-native-cli@1.0.0
├── webpack@1.13.1
└── yo@1.8.3
```

`babel-cli` is at 6.10.1, `doctoc` is at 1.2.0, etc.
#### How can the problem be reproduced?
1. `npm update -g`

**Comment by scottohara** [comment] 2016-06-29 01:30
This may be a duplicate of #10590 ?

Try running `npm update -g babel-cli --loglevel verbose`

See it reports something like:
`npm verb outdated not updating babel-cli because it's currently at the maximum version that matches its specified semver range`

**Comment by ffxsam** [comment] 2016-06-29 01:32
Yep!

```
npm verb outdated not updating babel-cli because it's currently at the maximum version that matches its specified semver range
```

**Closed** 2017-06-18 11:21 UTC
Labels: bot-closed
