### ISSUE TITLE
I can not update appium 1.6.1

### ISSUE THREAD

**Issue by Archer456** [npm/npm#15043] opened 2016-11-28 00:38 UTC
#### I'm opening this issue because:

I can not  install appium 1.6.1

#### What's going wrong?
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\Users\cmd>npm cache clean

C:\Users\cmd>npm-check -u -g
? Choose which packages to update. appium@1.6.1

$ npm install --global appium@1.6.1 --color=always
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "npm "install" "--global" "appium@1.6.1" "--color=always""
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node-global\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "appium@1.6.1" "--color=always"
npm ERR! node v4.4.7
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node-global\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "appium@1.6.1" "--color=always"
npm ERR! node v4.4.7
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\node-global\node_modules\npm-debug.log

For more detail, add `--debug` to the command

C:\Users\cmd>node -v
v4.4.7

C:\Users\cmd>npm -v
4.0.2

**Comment by legodude17** [comment] 2016-11-28 21:37
Try fully reinstalling `npm`, this is a problem caused by the `nodejs` installer sometimes.

**Comment by cervenyprofiq** [comment] 2016-11-29 09:58
I have same problem on Linux.
node v7.2.0
npm  v4.0.2

I tried reinstall npm, and it doesn't solve it.

**Comment by legodude17** [comment] 2016-11-29 15:41
@cervenyprofiq same answer. 😄

**Comment by KenanY** [comment] 2016-11-29 16:03
Looks like a duplicate of https://github.com/npm/npm/issues/14427.

**Closed by KenanY** 2016-11-29 16:03 UTC
