### ISSUE TITLE
`npm install` succeeds but `npm list` shows missing/invalid deps

### ISSUE THREAD

**Issue by jandet** [npm/npm#8241] opened 2015-05-12 20:37 UTC
my npm is v2.9.1

I run npm install which succeeds but upon npm list shows:

```
npm ERR! missing: github@^0.2.3, required by bower@1.4.1
npm ERR! invalid: debug@2.2.0 /Users/jdet/workspace/vine-web/www/vine-ember/node_modules/ember-cli/node_modules/debug
```

Here is my `package.json`:

``` json
{
  "name": "vine-ember",
  "version": "2.0.0",
  "description": "Website for vine.co",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "bower": "^1.4.1",
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.3",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-autoprefixer": "^0.3.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.10",
    "ember-cli-stylus": "1.0.4",
    "ember-cli-uglify": "1.0.1",
    "ember-export-application-global": "^1.0.2",
    "grunt": "^0.4.5",
    "grunt-aws-s3": "^0.13.0",
    "grunt-broccoli": "^0.4.0",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-env": "^0.4.4",
    "grunt-eslint": "^11.0.0",
    "grunt-exec": "^0.4.6",
    "grunt-revdir": "^1.0.4",
    "grunt-text-replace": "^0.4.0",
    "load-grunt-tasks": "^3.1.0",
    "request": "^2.55.0"
  },
  "ember-addon": {
    "paths": [
      "lib/livereload"
    ]
  }
}
```

Wondering if this is a bug on npm's side or on the side of the packages that are listed as having invalid/missing deps i.e. bower or ember-cli??

**Comment by indirect** [comment] 2015-05-12 22:06
I'm seeing the exact same problem, immediately after `rm -rf node_modules; npm cache clean; npm install`.

**Comment by indirect** [comment] 2015-05-12 22:10
I should elaborate: ember-cli depends on debug `^2.1.3` in its package.json. Running `npm install` installs debug `2.2.0`, and prints these warnings:

```
npm WARN unmet dependency ember-cli/node_modules/express requires debug@'~2.1.3' but will load
npm WARN unmet dependency ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency ember-cli/node_modules/morgan requires debug@'~2.1.3' but will load
npm WARN unmet dependency ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency ember-cli/node_modules/broccoli/node_modules/connect requires debug@'~2.1.3' but will load
npm WARN unmet dependency ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency ember-cli/node_modules/broccoli/node_modules/connect/node_modules/finalhandler requires debug@'~2.1.3' but will load
npm WARN unmet dependency ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency ember-cli/node_modules/express/node_modules/finalhandler requires debug@'~2.1.3' but will load
npm WARN unmet dependency ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency ember-cli/node_modules/express/node_modules/send requires debug@'~2.1.3' but will load
npm WARN unmet dependency ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
```

And then running `npm ls` prints this error message:

```
npm ERR! invalid: debug@2.2.0 /Users/andre/src/plos/lemur-collections/vendor/collections-commons/node_modules/ember-cli/node_modules/debug
```

**Comment by othiym23** [comment] 2015-05-20 05:03
@jandet This seems to be an issue with the packaging of `ember-cli@0.2.3` – when I used the `package.json` file you included up above, I was able to reproduce the exact same failure you saw. I'd say to take this up with @stefanpenner, but when I installed `ember@0.2.5`, the problem went away, so it seems he already got to it. Is that an acceptable solution for you?

There are a couple other issues here (it's hard to figure out that the problematic version of `bower` is actually inside `ember-cli`, and not at the top level, npm really shouldn't let you publish a package with `bundledDependencies` when the tree is in a bad state), and I'll file those separately, but I think upgrading `ember-cli` should take care of this.

ps hi janessa

**Comment by stefanpenner** [comment] 2015-05-20 05:44
> @jandet This seems to be an issue with the packaging of ember-cli@0.2.3

this is actually a bug in npm, reported here: https://github.com/npm/npm/issues/7887

We worked-around the issue  by promoting `github` from a devDep to a prod dep – see: https://github.com/marcioj/ember-cli/commit/0225153ea48217c439ce7b8deac2e4cba5f878cb 

This particular issue comes up every month or so, when one of our `bundledDependencies` starts using one of our devDependencies as a prod Dependency. Our current strategy is to play wack-a-mole :S

**Comment by othiym23** [comment] 2015-05-20 05:48
Thanks for chiming in, @stefanpenner. It wasn't immediately obvious to me how the two might be related, but I've added a note to #8315 pointing out the connection. In other news, work on resolving #7774 proceed apace.

**Comment by stefanpenner** [comment] 2015-05-20 05:52
> It wasn't immediately obvious to me how the two might be related

np

**Comment by jandet** [comment] 2015-05-20 05:54
Aha thanks for identifying the root bugs and glad to hear there is a workaround for now.  As expressed by a few others the main difficulty this was causing was inability to shrinkwrap without doing some wonky steps.  Will look out for the fix to land later then and will in the meantime keep my ember-cli to date.

Thanks so much!!

Also hi guys! :)

**Closed** 2017-06-17 02:57 UTC
Labels: bot-closed, support
