### ISSUE TITLE
npm uninstall -g not working

### ISSUE THREAD

**Issue by ganorberg** [npm/npm#17121] opened 2017-06-09 22:24 UTC
#### I'm opening this issue because:

npm is crashing.
 
#### What's going wrong?

can't globally uninstall bower

#### How can the CLI team reproduce the problem?
I called npm uninstall -g bower in the command line and got an error "Unhandled rejection Error: Argument #2: Expected string but got null". Here is the log:

Unhandled rejection Error: Argument #2: Expected string but got null
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

Used locally on my early 2015 macbook pro OS X. Bash.

**Comment by sheriffderek** [comment] 2017-06-11 15:42
I get the same errors for `npm uninstall -g ember-cli`

npm --version
5.0.0

**Comment by kenany** [comment] 2017-06-11 23:27
Duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-11 23:27 UTC
Labels: npm5
