### ISSUE TITLE
ionic install version 2.1.12

### ISSUE THREAD

**Issue by balamscint** [npm/npm#15839] opened 2017-02-23 08:44 UTC
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic@2.1.12"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for C:\Users\balam\AppData\Local\Temp\npm-10780-7b3bca36\registry.npmjs.org\ionic\-\ionic-2.1.12.tgz
npm ERR! Expected: e0102b764d589a09e9cbd432c338d9c539feeebe
npm ERR! Actual:   55e83b254cc3bf5f97eae25460b92d1841e64894
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
[npm-debug.txt](https://github.com/npm/npm/files/795926/npm-debug.txt)

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\balam\npm-debug.log

**Comment by legodude17** [comment] 2017-02-23 17:15
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-02-24 05:41 UTC
