### ISSUE TITLE
Unhandled rejection Error: Argument #2: Expected string but got null on `npm remove`

### ISSUE THREAD

**Issue by jatins** [npm/npm#17424] opened 2017-06-25 08:39 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I ran into this issue https://github.com/webpack/webpack/issues/2131. So, I tried running 
`npm remove webpack -g` as suggested in that. Doing that results in this error: `Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree`

<details>
<summary>Stack Trace</summary>

```
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/Users/jasn/.npm-packages/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/jasn/.npm-packages/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/jasn/.npm-packages/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/jasn/.npm-packages/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/jasn/.npm-packages/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jasn/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
```
</details>

<details> 
<summary>Debug Log </summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/jasn/.npm-packages/bin/npm',
1 verbose cli   'remove',
1 verbose cli   'webpack',
1 verbose cli   '-g' ]
2 info using npm@5.0.3
3 info using node@v7.3.0
4 verbose npm-session 05cb9c242287459c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

</details>

#### How can the CLI team reproduce the problem?
Umm, try removing webpack.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v7.3.0
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by hauntingEcho** [comment] 2017-06-30 18:14
possibly related to #17497? I'm receiving the same error with `npm uninstall -g`

**Comment by kenany** [comment] 2017-06-30 18:19
Looks like a duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-30 18:19 UTC
Labels: npm5
