### ISSUE TITLE
`npm uninstall` fails to remove some directories from node_modules resulting in ENOENT errors

### ISSUE THREAD

**Issue by lxe** [npm/npm#10887] opened 2015-12-18 20:41 UTC
Steps to reproduce:

top-level package.json:
```
{
  "dependencies": {
    "pkg-that-just-requires-gulp": "^1.0.0",
    "gulp": "^3.9.0"
  }
}
```

`pkg-that-just-requires-gulp` is a test package that just requires `gulp` as its only dependency.

Install the dependency tree:

```
$ npm install
```

Now, let's uninstall `gulp`:

```
$ npm uninstall --save gulp
```

We now **expect** `npm ls` to return this:
```
├─┬ dep-2@2.0.0
│ └── UNMET DEPENDENCY gulp@^3.9.0

npm ERR! missing: gulp@^3.9.0, required by pkg-that-just-requires-gulp@1.0.0
```

However, this is what we **actually** see:

```
$ npm ls
├─┬ pkg-that-just-requires-gulp@1.0.0
│ └── UNMET DEPENDENCY gulp@^3.9.0
└──  extraneous error: ENOENT, open '/Users/aleksey/my-project/node_modules/vinyl-fs/package.json

npm ERR! extraneous: vinyl-fs /Users/aleksey/my-project/node_modules/vinyl-fs
npm ERR! error in /Users/aleksey/my-project//node_modules/vinyl-fs: ENOENT, open '/Users/aleksey/my-project/node_modules/vinyl-fs/package.json'
npm ERR! missing: gulp@^3.9.0, required by pkg-that-just-requires-gulp@1.0.0
```

Examining the tree reveals that an `vinyl-fs` directory, containing nothing but `node_modules` is retained in `node_modules` even if it's been uninstalled along with gulp:

```
1$ tree node_modules/vinyl-fs
node_modules/vinyl-fs
└── node_modules

1 directory, 0 files
```

That's what causes the erroneous `ENOENT` error and the extraneous message.

`npm install`ing gulp again, does not fix the modules tree.

**Comment by ganemone** [comment] 2016-01-07 21:33
+1 - I am seeing issues with this more an more.

**Comment by cduruk** [comment] 2016-01-07 21:34
+1 Experiencing this issue as well. The workaround is removing those directories by hand.

**Comment by rajeshsegu** [comment] 2016-01-07 21:41
+1 hard deleting directories work but this needs to be fixed

**Comment by othiym23** [comment] 2016-01-07 22:23
Confirmed and marked as a big bug, also confirmed that it's reliably `vinyl-fs` that leaves behind an empty directory for some reason.

**Comment by chrisirhc** [comment] 2016-01-16 20:26
Quick update while debugging this, in case I don't get to creating a PR in time. This might be helpful for somebody else looking into this.

Minimal example at https://github.com/chrisirhc/npm-uninstall-not-clean-mwe

This seems to be caused by .bin directories in a nested node_modules (`node_modules/*/node_modules/.bin`). It could be caused by two packages with the same bin declaration, or due to npm being unable to flatten the module hierarchy due to incompatible dependencies.

In the above example, the tree looks like:
```
├─┬ gulp@3.9.0
│ ├── archy@1.0.0
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── escape-string-regexp@1.0.4
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.0
│ │ └── supports-color@2.0.0
│ ├── deprecated@0.0.1
│ ├─┬ gulp-util@3.0.7
│ │ ├── array-differ@1.0.0
│ │ ├── array-uniq@1.0.2
│ │ ├── beeper@1.1.0
│ │ ├─┬ dateformat@1.0.12
│ │ │ ├── get-stdin@4.0.1
│ │ │ └─┬ meow@3.7.0
│ │ │   ├─┬ camelcase-keys@2.0.0
│ │ │   │ └── camelcase@2.0.1
│ │ │   ├── decamelize@1.1.2
│ │ │   ├─┬ loud-rejection@1.2.0
│ │ │   │ └── signal-exit@2.1.2
│ │ │   ├── map-obj@1.0.1
│ │ │   ├─┬ normalize-package-data@2.3.5
│ │ │   │ ├── hosted-git-info@2.1.4
│ │ │   │ ├─┬ is-builtin-module@1.0.0
│ │ │   │ │ └── builtin-modules@1.1.1
│ │ │   │ └─┬ validate-npm-package-license@3.0.1
│ │ │   │   ├─┬ spdx-correct@1.0.2
│ │ │   │   │ └── spdx-license-ids@1.2.0
│ │ │   │   └─┬ spdx-expression-parse@1.0.2
│ │ │   │     └── spdx-exceptions@1.0.4
│ │ │   ├── object-assign@4.0.1
│ │ │   ├─┬ read-pkg-up@1.0.1
│ │ │   │ ├─┬ find-up@1.1.0
│ │ │   │ │ ├── path-exists@2.1.0
│ │ │   │ │ └─┬ pinkie-promise@2.0.0
│ │ │   │ │   └── pinkie@2.0.1
│ │ │   │ └─┬ read-pkg@1.1.0
│ │ │   │   ├─┬ load-json-file@1.1.0
│ │ │   │   │ ├── graceful-fs@4.1.2
│ │ │   │   │ ├─┬ parse-json@2.2.0
│ │ │   │   │ │ └─┬ error-ex@1.3.0
│ │ │   │   │ │   └── is-arrayish@0.2.1
│ │ │   │   │ ├── pify@2.3.0
│ │ │   │   │ └── strip-bom@2.0.0
│ │ │   │   └── path-type@1.1.0
│ │ │   ├─┬ redent@1.0.0
│ │ │   │ ├─┬ indent-string@2.1.0
│ │ │   │ │ └─┬ repeating@2.0.0
│ │ │   │ │   └─┬ is-finite@1.0.1
│ │ │   │ │     └── number-is-nan@1.0.0
│ │ │   │ └── strip-indent@1.0.1
│ │ │   └── trim-newlines@1.0.0
│ │ ├── fancy-log@1.1.0
│ │ ├─┬ gulplog@1.0.0
│ │ │ └── glogg@1.0.0
│ │ ├─┬ has-gulplog@0.1.0
│ │ │ └── sparkles@1.0.0
│ │ ├── lodash._reescape@3.0.0
│ │ ├── lodash._reevaluate@3.0.0
│ │ ├── lodash._reinterpolate@3.0.0
│ │ ├─┬ lodash.template@3.6.2
│ │ │ ├── lodash._basecopy@3.0.1
│ │ │ ├── lodash._basetostring@3.0.1
│ │ │ ├── lodash._basevalues@3.0.0
│ │ │ ├── lodash._isiterateecall@3.0.9
│ │ │ ├── lodash.escape@3.1.0
│ │ │ ├─┬ lodash.keys@3.1.2
│ │ │ │ ├── lodash._getnative@3.9.1
│ │ │ │ ├── lodash.isarguments@3.0.5
│ │ │ │ └── lodash.isarray@3.0.4
│ │ │ ├── lodash.restparam@3.6.1
│ │ │ └── lodash.templatesettings@3.1.1
│ │ ├─┬ multipipe@0.1.2
│ │ │ └─┬ duplexer2@0.0.2
│ │ │   └── readable-stream@1.1.13
│ │ ├── object-assign@3.0.0
│ │ ├── replace-ext@0.0.1
│ │ ├─┬ through2@2.0.0
│ │ │ ├─┬ readable-stream@2.0.5
│ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ ├── process-nextick-args@1.0.6
│ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ └── util-deprecate@1.0.2
│ │ │ └── xtend@4.0.1
│ │ └─┬ vinyl@0.5.3
│ │   ├── clone@1.0.2
│ │   └── clone-stats@0.0.1
│ ├── interpret@0.6.6
│ ├─┬ liftoff@2.2.0
│ │ ├── extend@2.0.1
│ │ ├─┬ findup-sync@0.3.0
│ │ │ └─┬ glob@5.0.15
│ │ │   ├── inflight@1.0.4
│ │ │   ├── minimatch@3.0.0
│ │ │   └── path-is-absolute@1.0.0
│ │ ├── flagged-respawn@0.3.1
│ │ ├── rechoir@0.6.2
│ │ └── resolve@1.1.6
│ ├── minimist@1.2.0
│ ├─┬ orchestrator@0.3.7
│ │ ├─┬ end-of-stream@0.1.5
│ │ │ └─┬ once@1.3.3
│ │ │   └── wrappy@1.0.1
│ │ ├── sequencify@0.0.7
│ │ └── stream-consume@0.1.0
│ ├── pretty-hrtime@1.0.1
│ ├── semver@4.3.6
│ ├─┬ tildify@1.1.2
│ │ └── os-homedir@1.0.1
│ ├─┬ v8flags@2.0.11
│ │ └── user-home@1.1.1
│ └─┬ vinyl-fs@0.3.14
│   ├── defaults@1.0.3
│   ├─┬ glob-stream@3.1.18
│   │ ├── glob@4.5.3
│   │ ├─┬ glob2base@0.0.12
│   │ │ └── find-index@0.1.1
│   │ ├─┬ minimatch@2.0.10
│   │ │ └─┬ brace-expansion@1.1.2
│   │ │   ├── balanced-match@0.3.0
│   │ │   └── concat-map@0.0.1
│   │ ├── ordered-read-streams@0.1.0
│   │ ├─┬ through2@0.6.5
│   │ │ └── readable-stream@1.0.33
│   │ └── unique-stream@1.0.0
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     ├─┬ glob@3.1.21
│   │     │ ├── graceful-fs@1.2.3
│   │     │ └── inherits@1.0.2
│   │     ├── lodash@1.0.2
│   │     └─┬ minimatch@0.2.14
│   │       ├── lru-cache@2.7.3
│   │       └── sigmund@1.0.1
│   ├── graceful-fs@3.0.8
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├─┬ strip-bom@1.0.0
│   │ ├── first-chunk-stream@1.0.0
│   │ └── is-utf8@0.2.1
│   ├─┬ through2@0.6.5
│   │ └── readable-stream@1.0.33
│   └─┬ vinyl@0.4.6
│     └── clone@0.2.0
└── pkg-that-just-requires-gulp@1.0.0
```

Notice that `strip-bom` is included twice. `strip-bom@1.0.0` declares a `bin` field of `"strip-bom": "cli.js"`, so that creates a nested `.bin` in `vinyl-fs` (`node_modules/vinyl-fs/node_modules/.bin`).

**Closed** 2016-01-21 22:53 UTC
Labels: big-bug, bug
