### ISSUE TITLE
more descripriptive deprecated warnings

### ISSUE THREAD

**Issue by iamstarkov** [npm/npm#12679] opened 2016-05-12 15:17 UTC
right now if you are doing `npm install` you are getting `deprecated` messages caused by you own or even nested dependencies. its quite hard to find out which packages are causing deprecated warnings, for example:

```
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
```

while i having 22 dependencies and a lot more nested ones, i dont know how to help to those maintainers to update their deps, but if warning message will change their format it would be pretty easy:

```
// old one
npm WARN deprecated {deprecated-pkg}@{version}: {message}

// new one
npm WARN deprecated {deprecated-pkg}@{version} in {node_modules-path-to-pkg-with-outdated-deps}: {message}

// real world example
npm WARN deprecated has-color@0.1.7 in `node_modules/ava/node_modules/example-pkg`: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
```

Last example clearly shows that i need to propose pull-request to one of ava's dep and one more to ava itself. What do you think about this enhancement? if its cool, i can try to implement it

**Comment by KenanY** [comment] 2016-05-12 15:24
ref. https://github.com/npm/npm/issues/10438, https://github.com/npm/npm/issues/11901

**Comment by iamstarkov** [comment] 2016-05-12 20:26
then i guess it is a duplicate

**Comment by othiym23** [comment] 2016-05-16 21:12
Closing as duplicate of #11901.

**Closed by othiym23** 2016-05-16 21:12 UTC

**Comment by bsed** [comment] 2016-11-12 01:38
```bash
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
/home/kelvin/.nvm/versions/node/v6.6.0/bin/yarnpkg -> /home/kelvin/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/bin/yarn.js
/home/kelvin/.nvm/versions/node/v6.6.0/bin/yarn -> /home/kelvin/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/bin/yarn.js
/home/kelvin/.nvm/versions/node/v6.6.0/lib
```
