### ISSUE TITLE
I am Getting Following Error While trying to Install C:\Smart Sense>npm install -g ionic cordova npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\CECH008\AppData\Local\Temp\npm-13844-92e6b060\registry.npmjs.org\q\-\q-1.0.1.tgz.2937630988' -> 'C:\Users\CECH008\AppData\Local\Temp\npm-13844-92e6b060\registry.npmjs.org\q\-\q-1.0.1.tgz' npm ERR! Windows_NT 10.0.10586 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova" npm ERR! node v7.6.0 npm ERR! npm  v4.1.2 npm ERR! tarball.destroy is not a function

### ISSUE THREAD

**Issue by ImmanuelCE** [npm/npm#15843] opened 2017-02-23 13:49 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ImmanuelCE** [comment] 2017-02-23 14:42
I am trying to install Ionic 2 , using the command.
npm install -g ionic cordova

I am getting following errors.

npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\CECH008\AppData\Local\Temp\npm-12112-7c99fa53\registry.npmjs.org\typedarray\-\typedarray-0.0.6.tgz.328925666' -> 'C:\Users\CECH008\AppData\Local\Temp\npm-12112-7c99fa53\registry.npmjs.org\typedarray\-\typedarray-0.0.6.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment] 2017-02-23 17:25
Duplicate of #15674.

**Closed** 2017-06-17 04:05 UTC
Labels: bot-closed
