### ISSUE TITLE
Cannot install packages

### ISSUE THREAD

**Issue by roblyn** [npm/npm#13054] opened 2016-06-14 16:23 UTC
[npm-debug.txt](https://github.com/npm/npm/files/314414/npm-debug.txt)

**Comment by KenanY** [comment] 2016-06-14 16:27
@roblyn Duplicate of https://github.com/npm/npm/issues/13052?

**Comment by roblyn** [comment] 2016-06-14 16:29
This is the last error that I got

**Comment by legodude17** [comment] 2016-06-14 18:05
This is the same error as #13052.

**Comment by roblyn** [comment] 2016-06-16 10:49
Yes

**Comment by KenanY** [comment] 2016-06-28 19:37
Closing as a duplicate of https://github.com/npm/npm/issues/13052.

**Closed by KenanY** 2016-06-28 19:37 UTC
Labels: support
