### ISSUE TITLE
cache-min & unknown version

### ISSUE THREAD

**Issue by timoxley** [npm/npm#8581] opened 2015-06-16 09:10 UTC
Currently, if npm is trying to install a package not yet in the npm cache, it will reach out to the registry and grab the package, even with `cache-min=Infinity`. This is desirable.

This allows high values for cache-min to work well, but a problem occurs in the following scenario: 

1. package A in cache, knows all versions up to v1.0.0.
2. package A releases version 1.1.0
3. package B not in cache, gets downloaded
4. package B requests package A ^1.1.0.
5. `npm install --cache-min=Infinity`
6. npm errors with a "no matching version found" error, listing all versions up to 1.0.0.

To resolve this, one has to update the cache's version info e.g. `npm info packagename` or lower the `cache-min` setting. This makes use of high `cache-min` values particularly error prone, especially on first installs.

It would be good if unknown versions were treated the same as unknown package names, i.e. npm should fall back to checking the remote registry before reporting "no compatible version found".

**Comment by timoxley** [comment] 2015-06-27 10:24
@othiym23 what are your reservations about this?

**Comment by timoxley** [comment] 2015-08-08 22:44
bump

**Comment by JamesMGreene** [comment] 2015-08-27 15:34
Arrrrrgh, I keep running into this. :+1:

**Comment by iarna** [comment] 2016-02-19 22:13
We chatted more about this internally and reservations are withdrawn– We would welcome a patch that, if a dependency version lookup failed with a cached version of the package's metdata, tried again with a fresh version. (This may be a bit tricky due to the architecture around the config being a painfully global object, but with sufficient surgery it's plausible.) However, it's not on our timeline for the coming year to add it ourselves.

As such, @othiym23 has marked this patch-welcome, and I'm going to close this issue.

**Closed** 2016-02-19 22:14 UTC
Labels: feature-request, patch-welcome

**Comment by timoxley** [comment] 2016-04-18 08:17
For the record, I disagree that this issue should be closed, and I disagree with labelling it as a "feature request". It's a race condition bug that *sometimes* causes a completely valid `npm install` to fail.

**Comment by quarterto** [comment] 2016-08-05 12:34
Also for the record: this issue was fixed by #12084 which was released in npm 3.9. `--cache-min=Infinity` to your heart's content.

**Comment by gumallett** [comment] 2016-11-10 20:29
Has there been a regression? We are currently using 3.10.8 and this logic is no longer working.  we have cache-min=Infinity and after publishing a new version of a dependency (e.g 1.0.7), running npm install dep@1.0.7 gives an error ETARGET.

**Comment by legodude17** [comment] 2016-11-10 20:43
That could be it.
Pinging @timoxley, as well as @iarna and @othiym23.

**Comment by alienlike** [comment] 2017-02-16 18:35
I'm still experiencing this at v4.1.2, with `npm update`.

```
$ call npm update --cache-min=Infinity
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gitlab-runner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "--cache-min=Infinity"
npm ERR! node v6.2.0
npm ERR! npm  v4.1.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: postcss-loader@'>=1.3.0 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\GitLab-Runner\builds\bf2143f7\0\xplan\Find-A-Ride\src\FindARide\npm-debug.log
```
