### ISSUE TITLE
Dependencies specified via local paths should be okay to publish to npm

### ISSUE THREAD

**Issue by gaye** [npm/npm#8422] opened 2015-06-01 12:07 UTC
Suppose I have some package `a` that looks like

```
# package.json
{
  "name": "a",
  "version": "0.0.1",

  "dependencies": {
    "b": "file:./b"
  }
}
```

and a package `b` that looks like

```
# b/package.json
{
  "name": "b",
  "version": "3.14"
}
```

I would like `npm publish` to magically replace `"file:./b"` with `"3.14"` in `package.json`. This enables me to have a code tree with multiple npm packages which

(1) use the in-tree versions for development within my tree
(2) can be independently published to npm

Thoughts? Arguments for or against?

**Comment by gaye** [comment] 2015-06-04 13:11
Maybe a better way to seed this discussion is to describe a use case rather than a potential solution.

I work on a *gigantic* codebase. Many different webapps, libraries, binaries, and test suites live in various parts of my git tree. A single package may rely on many different packages within the tree. I would like to be able to publish (independently) a single package within the tree that relies on other, in-tree packages. 

It's also important for my use case that packages which depend on packages in other parts of the git tree use the in-tree versions. Ideally, I could make changes to one package in the tree and those changes would be automagically propagated through the dependency tree. This model is closer to _push_ or perhaps _building from head_ than the traditional npm model where you _pull_ different dependencies by specifying a version of the dependency in the consumer.

The biggest thing that keeps a model like this from working with npm currently is that if packages within my tree specify their dependencies with local paths (ie `file:./path/from/one/to/other`) then they cannot be published to npm. One idea for how to solve this problem is for `npm publish` to replace local path dependencies with the version of the dependent package. Another idea for how to solve this problem is for `npm publish` to gather all of the `file:` dependencies of the package being published at publish time and publish them (perhaps as part of the package being published).

**Comment by gaye** [comment] 2015-06-06 13:09
I wrote a small library to cover some npm client deficiencies related to local modules. It implements install with the semantics I suggested here https://github.com/gaye/npmr.

**Comment by zkat** [comment] 2016-02-25 21:41
Closing this as a duplicate of #8480

**Comment by gaye** [comment] 2016-03-20 23:01
@zkat These are different issues but I doubt the open/closed status will affect the work anyone does here, so feel free to keep closed :)

**Comment by zkat** [comment] 2016-03-21 18:32
Sorry! I misread it, too. Reopening. :)

**Comment by othiym23** [comment] 2016-03-22 20:52
Whenever I see the word “magic” or “magical”, I stop and look at the larger context of an issue, because CLI tools doing magical things is generally a sign that there’s some kind of confusion or conflation of concerns going on. In this case, I think that’s definitely true. Were npm to start substituting one kind of dependency for another automatically on publish, there would be two immediate consequences:

1. It would be harder for developers to understand the scope of the publishing command.
2. It would blur the lines between kinds of dependencies.

For that reason, I’m not a fan of making this a part of npm’s behavior, and am going to close this feature request. That said, there’s still a lot more the CLI could do to handle monorepos like the ones you describe above, and I think one of the best ways to improve npm there is through producing plug-in tooling that can be used e.g. with package scripts. There’s [`linklocal`](http://npm.im/linklocal), which is used to simplify the process of linking together many packages that are under simultaneous active development, and I think that something that looked like that for local dependencies might ease monorepo-based development quite a bit, especially if it were built to be plugged into npm scripts. I encourage people to play around with those kinds of solutions and to draw our attention to them when they’re useful, because when tools like that find traction, it makes a lot of sense to incorporate them directly into the npm CLI. Thanks for your time and the clear statement of the problem, and good luck getting this problem sorted out!

**Closed by othiym23** 2016-03-22 20:52 UTC
Labels: feature-request
