### ISSUE TITLE
RangeError: Maximum call stack size exceeded while publishing

### ISSUE THREAD

**Issue by aredridel** [npm/npm#8709] opened 2015-06-26 19:41 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@3.0.0
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/Users/ariastewart/Projects/copy-browser-modules',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /Users/ariastewart/.npm/copy-browser-modules/1.1.0/package.tgz not in flight; packing
10 info prepublish copy-browser-modules@1.1.0
11 verbose tar pack [ '/Users/ariastewart/.npm/copy-browser-modules/1.1.0/package.tgz',
11 verbose tar pack   '/Users/ariastewart/Projects/copy-browser-modules' ]
12 verbose tarball /Users/ariastewart/.npm/copy-browser-modules/1.1.0/package.tgz
13 verbose folder /Users/ariastewart/Projects/copy-browser-modules
14 verbose stack RangeError: Maximum call stack size exceeded
14 verbose stack     at String.split (native)
14 verbose stack     at encodeField (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:149:15)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:139:32
14 verbose stack     at Array.forEach (native)
14 verbose stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
14 verbose stack     at Array.forEach (native)
14 verbose stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
14 verbose stack     at Array.forEach (native)
15 verbose cwd /Users/ariastewart/Projects/copy-browser-modules
16 error Darwin 14.4.0
17 error argv "node" "/usr/local/bin/npm" "publish"
18 error node v0.12.4
19 error npm  v3.0.0
20 error Maximum call stack size exceeded
21 error If you need help, you may report this error at:
21 error     <https://github.com/npm/npm/issues>
22 verbose exit [ 1, true ]

```

**Comment by aredridel** [comment] 2015-07-07 13:24
Still happens with 3.1.0.

**Comment by iarna** [comment] 2015-07-07 18:00
I would expect this.

**Comment by zpao** [comment] 2015-07-13 18:32
I just hit this running node@0.10.40, npm#3.1.1, publishing [jstransform](https://github.com/facebook/jstransform) (hopefully that's reproducible). Let me know if there's anything I can do to help!

**Comment by iarna** [comment] 2015-07-20 21:58
Closing as a duplicate of #8706

**Closed by iarna** 2015-07-20 21:58 UTC
Labels: bug
