### ISSUE TITLE
Issue while installing grunt-cli

### ISSUE THREAD

**Issue by ANKUR1983** [npm/npm#10522] opened 2015-11-23 09:35 UTC
Hi
I have been getting the following error while installing grunt-cli.

When I run npm install grunt, it installs successfully.
But then when I run npm install -g grunt-cli, I get the following error:

```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\AnkurSharma\AppData\Roaming\npm\node_modules\grunt-cli\bin\officeclicktorun.exe_c2ruidll(20151118141917780).log
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall unlink

npm ERR! EBUSY: resource busy or locked, unlink 'C:\Users\AnkurSharma\AppData\Roaming\npm\node_modules\grunt-cli\bin\officeclicktorun.exe_c2ruidll(20151118141917780).log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, unlink 'C:\Users\AnkurSharma\AppData\Roaming\npm\node_modules\grunt-cli\bin\CENTRUM-ALEX-20151118-1419.log'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, unlink 'C:\Users\AnkurSharma\AppData\Roaming\npm\node_modules\grunt-cli\bin\CENTRUM-ALEX-20151118-1419.log']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: 'C:\\Users\\AnkurSharma\\AppData\\Roaming\\npm\\node_modules\\grunt-cli\\bin\\CENTRUM-ALEX-20151118-1419.log' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\AnkurSharma\DownerSnow-Cordova-Light-App\npm-debug.log
```

**Comment by OmgImAlexis** [comment] 2015-12-01 04:52
Looks like an issue with `officeclicktorun.exe`, have you tried closing/killing Microsoft Office and trying again?

**Comment by othiym23** [comment] 2016-08-19 21:53
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:53 UTC
Labels: support, windows
