### ISSUE TITLE
How to support proprietary licenses in package.json without triggering an NPM warning?

### ISSUE THREAD

**Issue by mwawrusch** [npm/npm#8795] opened 2015-07-01 16:13 UTC
Using the private registry we can chose between having no license field (not good) resulting in an NPM warning that license is missing; or having a license field with our proprietary license name, which results in a not a valid SPDX expression warning. 

How can we specify our proprietary license (or none at all, the code is not licensed to anybody) and have no warnings?

**Comment by bryancallahan** [comment] 2015-07-08 23:43
Here are some helpful links that have worked for me.
https://spdx.org/about-spdx/faqs
http://programmers.stackexchange.com/questions/285885/which-spdx-license-is-equivalent-to-all-rights-reserved

In summary, use `"license": "LicenseRef-LICENSE"` and then create a LICENSE file next to package.json with something as little as: "(c) Copyright 2015 person or company, all rights reserved.".

**Comment by mwawrusch** [comment] 2015-07-08 23:44
awesome, thx.

**Comment by iarna** [comment] 2015-07-09 01:01
You can also put `UNLICENSED` as the license and npm won't complain any more.

Anyway, I'm going to close this as resolved. 😄

**Closed by iarna** 2015-07-09 01:01 UTC
Labels: support

**Comment by Sergey80** [comment] 2016-05-08 16:49
"license": "LicenseRef-LICENSE" has not worked for me

**Comment by AgentME** [comment] 2016-07-05 20:40
When using `npm init`, npm refuses to allow "LicenseRef-LICENSE". Instead, it suggests `"SEE LICENSE IN <filename>"`:

```
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

...
license: (ISC) All Rights Reserved
Sorry, license should be a valid SPDX license expression (without "LicenseRef"), "UNLICENSED", or "SEE LICENSE IN <filename>".
license: (ISC) LicenseRef-LICENSE
Sorry, license should be a valid SPDX license expression (without "LicenseRef"), "UNLICENSED", or "SEE LICENSE IN <filename>".
license: (ISC) SEE LICENSE IN LICENSE.txt
About to write to .../package.json:
```

**Comment by macagua** [comment] 2016-08-04 15:15
"license": "UNLICENSED", work fine for me! 

Thanks guys!

**Comment by brunocassol** [comment] 2016-08-05 17:16
You can also use:

`"private": true,`

And it will stop complaining about missing license and repository fields.

**Comment by mocheng** [comment] 2016-11-21 05:03
`"private": true,` makes package unpublishable.

**Comment by DanHakimi** [comment] 2017-02-13 04:52
Why are you trying to publish a package if you don't want to give people permission to use it?

If you put your shit NPM, *some* people are going to just assume it's open source. If you don't want them to treat it as open source, I recommend not putting it on NPM.

**Comment by Sergey80** [comment] 2017-02-13 23:21
The licence is licence whether it is shit or not. One may sell his code,
use it as resume-references, etc. To read code and copy paste-code is
different thing.

**Comment by Sergey80** [comment] 2017-02-13 23:25
And one may not want to publish anything anywhere but use his private repo.

**Comment by DanHakimi** [comment] 2017-02-14 00:06
Do you need your code on NPM to sell it or use it on his resume? My worry is that people find poprietary code on NPM, use it by accident, and end up having to remove it when legal points out that they messed up. Is there any need for NPM to host proprietary code at all?

**Comment by AgentME** [comment] 2017-02-14 00:12
You don't need proprietary code for licenses to be important. If you use GPL code pulled off of npm without respecting its license and assuming it's MIT, then you're going to have a bad time.

**Comment by Sergey80** [comment] 2017-02-14 21:01
I guess you drifted away from original question.

**Comment by mividtim** [comment] 2017-03-30 14:51
The original question is still pertinent, and open to me.  To make the issue clear: we use a private NPM repository, and are publishing proprietary packages to it.  If we set `"private": true`, we are prevented from publishing to our private repository.  If we don't set a valid SPDX license (which we definitely should not), we get a license warning.  My opinion is that there should be a valid way (no warnings) to handle this case, as we have no good options.  `UNLICENSED`, `LicenseRef-LICENSE`, and `SEE LICENSE IN` no longer suppress the warning.

Frankly, I feel I should be able to put anything I want in there and not get a warning from the `npm` command itself.  If the public `npmjs.org` repository wishes to enfore specific licenses on publish, that's that repository's business.  Someone should be free, for instance, to create a GPL-only public repository, and folks should be free to use the same `npm` tool to publish to it.  The license warning built into the `npm` itself seems to be unwarrantedly burdensome.

**Comment by snewell92** [comment] 2017-05-03 19:44
I agree with @mividtim 

I am creating a new node application and it's always good to start with `npm init`, so I did and now I have to choose a license. I opted for `UNLICENSED` and `"private": true`, however I do want to be able to make a private registry at some point so our team can easily break code up into clearly defined modules and use them **across projects**. Then we could `npm install` these reusable parts. Right now we just copy-pasta a lot of stuff. I'd rather npm do that for me since these things are dependencies.

These modules would be company scoped, and our company's scope will have a setting a la a global `.npmrc` file to set the registry url to be some internal server ip or wherever we want our registry.

I *think* this would, legally, necessitate more than an `UNLICENSED` property. I would, ideally, want `PROPRIETARY` as the license property in package.json with a `LICENSE.md` file which contains a blurb about all rights reserved/copyright blah blah. Something to be 'legally correct' and more succinct than putting something at the top of every source file, which I've seen done in other companies (and I'm sure some places still do), but we don't do currently (but probably should - we aren't lawyers, so we actually don't know, just trying to cover our butts).

I'd actually be interested to hear a lawyer's perspective on this.

**Comment by richRemer** [comment] 2017-08-16 01:06
IANAL, but legally all works are automatically copyrighted (in the United States, at least, and we sort of push our intellectual property laws upon most of the world).  Publishing your work as proof of when you created it is sufficient to win in court.  While it's not bad practice to "all rights reserved" your code, it is not strictly necessary; no rights are implicitly granted, so no rights need to be reserved.  In this context "UNLICENSED" is clearly proprietary if you haven't acquired a license through another channel.

http://www.nolo.com/legal-encyclopedia/copyright-automatic.html

**Comment by BillyWM** [comment] 2017-10-14 21:14
> Frankly, I feel I should be able to put anything I want in there and not get a warning from the npm command itself. If the public npmjs.org repository wishes to enfore specific licenses on publish, that's that repository's business. Someone should be free, for instance, to create a GPL-only public repository, and folks should be free to use the same npm tool to publish to it. The license warning built into the npm itself seems to be unwarrantedly burdensome.

Wouldn't it then need to fetch some kind of policy file from these alternative public registries? e.g.
`{ supportedLicenses: ["GPL-3.0", .......`

This seems more of a matter of principle than something with practical use. I mean, there aren't even enough people mad enough about this for Yarn to add it.

I don't see a good reason for NPM to become the Linux PPA system. What is the use-case for GPL'd code that you don't want to put on NPM and you don't want to include via NPM's ability to install from arbitrary git:// URLs? Seems like it would largely be for political, not technical, reasons.

Requiring a recognized FOSS license is a sane default that enforces a modicum of quality and I hope they never remove it. Anything goes as the default is bad for the community. By pigeonholing you into an accepted choice, that's one less minefield the less of us have to navigate - and now I just have to worry about someone deleting left-pad.

I don't see a point in encouraging senseless fracturing with me-too public registries. God knows more fracturing is the last thing the Javascript ecosystem needs.

**Comment by mividtim** [comment] 2017-12-06 14:21
No.  I think it's not the tool's job to validate a thing - that should be done when publishing, by the server.

**Comment by mividtim** [comment] 2017-12-06 14:23
My use case isn't to enforce GPL on my registry - that was just an example use case.  My use case is to host proprietary code on a private registry.  The tool should not be enforcing npmjs.org policy, since the tool can be used on other registries.  The tool should not throw warnings about npmjs.org policy (i.e. license requirements) every time you run the command - the publish should simply be rejected by the server.

**Comment by mividtim** [comment] 2017-12-06 14:27
@BillyWM, you're conflating what's good for the npmjs.org community (enforcing sane licensing) with the behavior of a tool that should be completely agnostic to that community - it is used by thousands of developers on internal registries.  We all have to ignore this warning every time we run the command, because it would be dangerous to appease the tool by putting a FOSS license in the license field, in case the package is shared outside the organization.  package.json's license field should allow ANY license whatsoever.  It's the _registry_ that should be enforcing license policy, not the tool.

**Comment by Knagis** [comment] 2018-01-02 17:28
I just want to point out that using "Unlicensed" (as suggested multiple times in this thread) might imply the opposite as was intended: see http://unlicense.org/

**Comment by mividtim** [comment] 2018-02-02 01:27
UNLICENSED isn't even supported anymore. Nothing but a "valid" FOSS license is accepted, or a warning is kicked out. The supposed "solution" is to set `"private": true`, which will disallow publishing to a private registry, not just the public registry - the tool itself refuses the publication without even checking the registry. Again, the tool should be agnostic to licensing. If a given registry wishes to care about the content of the license field, that's their business.

**Comment by dreki** [comment] 2018-02-02 03:23
@AgentME's works for me

**Comment by shanehughes3** [comment] 2018-03-08 16:30
@Knagis The [npm docs](https://docs.npmjs.com/files/package.json#license) imply a difference between "Unlicense" (as found in the [SPDX List](https://spdx.org/licenses/)) and "UNLICENSED": 

> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
> `{ "license": "UNLICENSED" }`

**Comment by ohager** [comment] 2018-03-19 23:34
It's a pity that the [DBAD](https://www.dbad-license.org/) License is not a valid SPDX License...

SCNR

**Comment by Fuco1** [comment] 2018-04-13 09:57
`Unlicense` is **NOT** what you want.

This is the start of the text of the `Unlicense` lincense:

> This is free and unencumbered software released into the public domain.

> Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

Putting this on your proprietary code will get you kicked out of your job.

**Comment by Ore4444** [comment] 2018-04-19 10:41
Sounds like it makes sense to allow `"private": true` packages to be published to private registries. It could be made a requirement that such packages have a custom URL in their `publishConfig.registry`.

**Comment by mividtim** [comment] 2018-04-19 13:58
^^ @Ore4444 PLEASE

**Comment by jimmykane** [comment] 2018-05-14 12:10
What @Fuco1  said. BIG WARNING HERE about Unlicense

**Comment by jimmykane** [comment] 2018-05-14 12:18
What helped is was: 

- Create a LICENSE.md containing any custom license you might want 
- Add `"license": "SEE LICENSE IN LICENSE.md",`

**Comment by DJDaveMark** [comment] 2018-05-22 09:58
I can't help but think the simplest form would've been:

    see file <filename>

which would allow other fields in the future to externalize their content using the same pattern.
