### ISSUE TITLE
Problem installing npm browser-sync on the sytem

### ISSUE THREAD

**Issue by pardhivas** [npm/npm#12886] opened 2016-05-28 15:44 UTC
```console
>npm install -g browser-sync
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\S525273\AppData\Local\Temp\npm-11860-8aff1942\registry
.npmjs.org\read-pkg\-\read-pkg-1.1.0.tgz.967844103' -> 'C:\Users\S525273\AppData
\Local\Temp\npm-11860-8aff1942\registry.npmjs.org\read-pkg\-\read-pkg-1.1.0.tgz'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
C:\Users\S525273\AppData\Roaming\npm\browser-sync -> C:\Users\S525273\AppData\Ro
aming\npm\node_modules\browser-sync\bin\browser-sync.js
browser-sync@2.12.10 C:\Users\S525273\AppData\Roaming\npm\node_modules\browser-s
ync
├── emitter-steward@1.0.0
├── qs@6.2.0
├── dev-ip@1.0.1
├── ua-parser-js@0.7.10
├── immutable@3.8.1
├── opn@3.0.3 (object-assign@4.1.0)
├── browser-sync-client@2.4.2 (fresh@0.3.0, etag@1.7.0)
├── http-proxy@1.13.3 (eventemitter3@1.2.0, requires-port@1.0.0)
├── portscanner@1.0.0 (async@0.1.15)
├── connect@3.4.1 (utils-merge@1.0.0, parseurl@1.3.1, debug@2.2.0, finalhandler@
0.4.1)
├── serve-static@1.10.2 (escape-html@1.0.3, parseurl@1.3.1, send@0.13.1)
├── resp-modifier@6.0.1 (debug@2.2.0, minimatch@2.0.10)
├── micromatch@2.3.7 (filename-regex@2.0.0, is-glob@2.0.1, is-extglob@1.0.0, ext
glob@0.3.2, normalize-path@2.0.1, array-unique@0.2.1, expand-brackets@0.1.5, reg
ex-cache@0.4.3, arr-diff@2.0.0, kind-of@3.0.3, parse-glob@3.0.4, object.omit@2.0
.0, braces@1.8.5)
├── chokidar@1.5.1 (inherits@2.0.1, path-is-absolute@1.0.0, glob-parent@2.0.0, a
sync-each@1.0.0, is-glob@2.0.1, anymatch@1.3.0, is-binary-path@1.0.1, readdirp@2
.0.0)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.2.0, jsonfile@2.3.1, gracefu
l-fs@4.1.4, rimraf@2.5.2)
├── socket.io@1.4.6 (has-binary@0.1.7, debug@2.2.0, socket.io-parser@2.2.6, sock
et.io-adapter@0.4.0, engine.io@1.6.9, socket.io-client@1.4.6)
├── serve-index@1.7.3 (escape-html@1.0.3, parseurl@1.3.1, batch@0.5.3, mime-type
s@2.1.11, http-errors@1.3.1, debug@2.2.0, accepts@1.2.13)
├── localtunnel@1.8.1 (openurl@1.1.0, debug@2.2.0, yargs@3.29.0, request@2.65.0)

├── bs-recipes@1.2.2
├── yargs@4.7.1 (decamelize@1.2.0, camelcase@3.0.0, y18n@3.2.1, set-blocking@1.0
.0, require-main-filename@1.0.1, window-size@0.2.0, lodash.assign@4.0.9, yargs-p
arser@2.4.0, cliui@3.2.0, string-width@1.0.1, os-locale@1.4.0, pkg-conf@1.1.3, r
ead-pkg-up@1.0.1)
├── easy-extender@2.3.2 (lodash@3.10.1)
├── eazy-logger@2.1.3 (lodash.clonedeep@4.3.1, tfunk@3.0.2, opt-merger@1.1.1)
└── browser-sync-ui@0.5.19 (async-each-series@0.1.1, connect-history-api-fallbac
k@1.2.0, stream-throttle@0.1.3, weinre@2.0.0-pre-I0Z7U9OV)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\S525273\npm-debug.log
```

[npm-debug.txt](https://github.com/npm/npm/files/287782/npm-debug.txt)

**Comment by qaqeqe0** [comment] 2016-07-05 01:52
Help!!!!

**Comment by othiym23** [comment] 2016-08-19 22:02
```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\S525273\AppData\Local\Temp\npm-11860-8aff1942\registry.npmjs.org\read-pkg\-\read-pkg-1.1.0.tgz.967844103' -> 'C:\Users\S525273\AppData\Local\Temp\npm-11860-8aff1942\registry.npmjs.org\read-pkg\-\read-pkg-1.1.0.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:02 UTC
Labels: support, windows
