### ISSUE TITLE
npm install --save --save-exact react-native

### ISSUE THREAD

**Issue by daoxingwudao** [npm/npm#15387] opened 2017-01-04 09:16 UTC
{ Error: Command failed: npm install --save --save-exact react-native
    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:294:5)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
  error: null,
  cmd: 'npm install --save --save-exact react-native',
  file: '/bin/sh',
  args: 
   [ '/bin/sh',
     '-c',
     'npm install --save --save-exact react-native' ],
  options: 
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     file: '/bin/sh',
     args: 
      [ '/bin/sh',
        '-c',
        'npm install --save --save-exact react-native' ],
     envPairs: 
      [ 'TERM_PROGRAM=Apple_Terminal',
        'SHELL=/bin/bash',
        'TERM=xterm-256color',
        'TMPDIR=/var/folders/kg/tfghpm9s5qj2c744sbn639mc0000gn/T/',
        'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.shnVQOJtci/Render',
        'TERM_PROGRAM_VERSION=388',
        'TERM_SESSION_ID=F2EF30B7-4C98-4307-B1F1-05395DBC5B3F',
        'USER=mac',
        'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Z4LJlIvHwc/Listeners',
        '__CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34',
        'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
        'PWD=/Users/mac/Desktop/ReatNativePro',
        'LANG=zh_CN.UTF-8',
        'XPC_FLAGS=0x0',
        'XPC_SERVICE_NAME=0',
        'SHLVL=1',
        'HOME=/Users/mac',
        'LOGNAME=mac',
        'SECURITYSESSIONID=186a7',
        '_=/usr/local/bin/react-native',
        'OLDPWD=/Users/mac' ] },
  envPairs: 
   [ 'TERM_PROGRAM=Apple_Terminal',
     'SHELL=/bin/bash',
     'TERM=xterm-256color',
     'TMPDIR=/var/folders/kg/tfghpm9s5qj2c744sbn639mc0000gn/T/',
     'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.shnVQOJtci/Render',
     'TERM_PROGRAM_VERSION=388',
     'TERM_SESSION_ID=F2EF30B7-4C98-4307-B1F1-05395DBC5B3F',
     'USER=mac',
     'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Z4LJlIvHwc/Listeners',
     '__CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34',
     'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
     'PWD=/Users/mac/Desktop/ReatNativePro',
     'LANG=zh_CN.UTF-8',
     'XPC_FLAGS=0x0',
     'XPC_SERVICE_NAME=0',
     'SHLVL=1',
     'HOME=/Users/mac',
     'LOGNAME=mac',
     'SECURITYSESSIONID=186a7',
     '_=/usr/local/bin/react-native',
     'OLDPWD=/Users/mac' ],
  stderr: null,
  stdout: null,
  pid: 14146,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
Command `npm install --save --save-exact react-native` failed.
macdeMacBook-Air:ReatNativePro mac$ react-native init First
This will walk you through creating a new React Native project in /Users/mac/Desktop/ReatNativePro/First
Installing react-native...
Consider installing yarn to make this faster: https://yarnpkg.com
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/kg/tfghpm9s5qj2c744sbn639mc0000gn/T/npm-14438-90990a2c/registry.npmjs.org/react-native/-/react-native-0.39.2.tgz
npm ERR! Expected: c73ed67ff25ea8e31643ac6ef2d60a88f26d12c1
npm ERR! Actual:   ad3c813da4ccfa65cfa36de5c088560e5bb449ef
npm ERR! From:     https://registry.npmjs.org/react-native/-/react-native-0.39.2.tgz

**Comment by Charlotteis** [comment] 2017-01-05 10:27
This is a duplicate of https://github.com/npm/npm/issues/14626

Please upgrade your npm, `npm install -g npm@latest`

🌸

**Comment by KenanY** [comment] 2017-02-03 13:11
Closing as abandoned.

**Closed by KenanY** 2017-02-03 13:11 UTC
