### ISSUE TITLE
Trouble installing polymer cli

### ISSUE THREAD

**Issue by jeyzur** [npm/npm#14178] opened 2016-10-04 21:07 UTC
#### I'm opening this issue because:
- [ ] npm is throwing errors
#### What's going wrong?

I'm trying to install the polymer CLI

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/joeycruz/.nvm/versions/node/v6.2.2/bin/node" "/Users/joeycruz/.nvm/versions/node/v6.2.2/bin/npm" "i" "-g" "polymer-cli"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for /var/folders/91/c2nx2js14n571kr8c1054w9545h_qm/T/npm-42449-7f596784/registry.npmjs.org/accessibility-developer-tools/-/accessibility-developer-tools-2.11.0.tgz
npm ERR! Expected: 2b669c802671672aed5c61c42a782082a2fc7d2c
npm ERR! Actual:   657c7968432e110f60999bbf2f6c3aa61839d542
npm ERR! From:     http://registry.npmjs.org/accessibility-developer-tools/-/accessibility-developer-tools-2.11.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
#### What's the feature?

polymer

-->

**Comment by mbarqawi** [comment] 2016-10-16 08:31
any update ? I have the same thing

**Comment by mateodelnorte** [comment] 2016-11-29 20:15
+1

Same. Problem is with [accessibility-developer-tools](https://github.com/GoogleChrome/accessibility-developer-tools)

**Comment by Charlotteis** [comment] 2016-11-29 20:32
Does the problem persist after updating to latest version of `npm`?

**Comment by mateodelnorte** [comment] 2016-11-29 21:24
Yes. And after `npm cache clean`.

**Comment by zkat** [comment] 2016-12-09 00:36
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:36 UTC
Labels: network, shasum, support
