### ISSUE TITLE
npm uninstall reports 1 package removed but there wasn't any package

### ISSUE THREAD

**Issue by Cuel** [npm/npm#17341] opened 2017-06-20 13:36 UTC
#### I'm opening this issue because:
  - [x] npm is producing an incorrect result.

#### What's going wrong?
Npm suggests that it removed one package but that's a lie

#### How can the CLI team reproduce the problem?

```
$ npm uninstall -g blablabla-i-do-not-exist
removed 1 package in 0.056s
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.0.0

**Comment by kenany** [comment] 2017-06-20 17:51
Duplicate of https://github.com/npm/npm/issues/16956.

**Closed as completed by kenany** 2017-06-20 17:51 UTC
