### ISSUE TITLE
i am facing a same problem at the time of installation on windows machine

### ISSUE THREAD

**Issue by Dhan-An-Jay** [npm/npm#16485] opened 2017-05-01 07:09 UTC
C:\Users\Think Different>node -v
v6.10.2

C:\Users\Think Different>npm -v
3.10.10

C:\Users\Think Different>npm install -g bower
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "-g" "bower"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\THINKD~1\AppData\Local\Temp\npm-6056-1
2810462\registry.npmjs.org\bower\-\bower-1.8.0.tgz
npm ERR! Expected: 55dbebef0ad9155382d9e9d3e497c1372345b44a
npm ERR! Actual:   502b60e38ecc5de62fa3bcbc3104d03268981530
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Think Different\npm-debug.log

C:\Users\Think Different>c

**Comment by legodude17** [comment] 2017-05-01 16:44
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:54 UTC
Labels: bot-closed, shasum, support
