### ISSUE TITLE
for protractor installation command npm install -g protractor, below error(log) is coming

### ISSUE THREAD

**Issue by yogendralondhe** [npm/npm#15343] opened 2016-12-29 11:52 UTC
#### I'm opening this issue because:

after mentioned command in console message coming -npm ERR! shasum check failed for "windows path"

#### What's going wrong?
protractor is not installing

### supporting information:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData protractor
8 silly fetchNamedPackageData protractor
9 silly mapToRegistry name protractor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'protractor',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'protractor',
12 silly mapToRegistry   name: 'protractor',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/protractor
14 verbose request uri http://registry.npmjs.org/protractor
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:12:04 PM
17 verbose request id a84ce698851da174
18 verbose etag W/"5859e1c4-244f2"
19 verbose lastModified Wed, 21 Dec 2016 01:58:28 GMT
20 http request GET http://registry.npmjs.org/protractor
21 http 304 http://registry.npmjs.org/protractor
22 verbose headers { date: 'Thu, 29 Dec 2016 11:42:04 GMT',
22 verbose headers   via: '1.1 varnish, 1.1 Arlwcg02.igatecorp.com',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"5859e1c4-244f2"',
22 verbose headers   age: '234',
22 verbose headers   'x-served-by': 'cache-sin6922-SIN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '5',
22 verbose headers   'x-timer': 'S1483011724.849842,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding',
22 verbose headers   connection: 'close' }
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 29 Dec 2016 11:42:04 GMT',
23 silly get     via: '1.1 varnish, 1.1 Arlwcg02.igatecorp.com',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"5859e1c4-244f2"',
23 silly get     age: '234',
23 silly get     'x-served-by': 'cache-sin6922-SIN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '5',
23 silly get     'x-timer': 'S1483011724.849842,VS0,VE0',
23 silly get     vary: 'Accept-Encoding',
23 silly get     connection: 'close' } ]
24 verbose etag http://registry.npmjs.org/protractor from cache
25 verbose get saving protractor to C:\Users\ylondhe\AppData\Roaming\npm-cache\registry.npmjs.org\protractor\.cache.json
26 verbose correctMkdir C:\Users\ylondhe\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule protractor@4.0.14 checking installable status
40 silly cache add args [ 'protractor', null ]
41 verbose cache add spec protractor
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'protractor',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'protractor',
42 silly cache add   name: 'protractor',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed protractor@latest
44 verbose addNamed "latest" is being treated as a dist-tag for protractor
45 info addNameTag [ 'protractor', 'latest' ]
46 silly mapToRegistry name protractor
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry http://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'protractor',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'protractor',
49 silly mapToRegistry   name: 'protractor',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri http://registry.npmjs.org/protractor
51 verbose addNameTag registry:http://registry.npmjs.org/protractor not in flight; fetching
52 verbose get http://registry.npmjs.org/protractor not expired, no request
53 silly addNameTag next cb for protractor with tag latest
54 silly addNamed protractor@4.0.14
55 verbose addNamed "4.0.14" is a plain semver version for protractor
56 silly mapToRegistry name protractor
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry http://registry.npmjs.org/
59 silly mapToRegistry data Result {
59 silly mapToRegistry   raw: 'protractor',
59 silly mapToRegistry   scope: null,
59 silly mapToRegistry   escapedName: 'protractor',
59 silly mapToRegistry   name: 'protractor',
59 silly mapToRegistry   rawSpec: '',
59 silly mapToRegistry   spec: 'latest',
59 silly mapToRegistry   type: 'tag' }
60 silly mapToRegistry uri http://registry.npmjs.org/protractor
61 verbose addRemoteTarball http://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz not in flight; adding
62 verbose addRemoteTarball [ 'http://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz',
62 verbose addRemoteTarball   'efc4a877fac3a182a9dded26cd5869f4762fd172' ]
63 info retry fetch attempt 1 at 5:12:05 PM
64 info attempt registry request try #1 at 5:12:05 PM
65 http fetch GET http://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz
66 http fetch 200 http://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz
67 silly fetchAndShaCheck shasum efc4a877fac3a182a9dded26cd5869f4762fd172
68 silly rollbackFailedOptional Starting
69 silly rollbackFailedOptional Finishing
70 silly runTopLevelLifecycles Finishing
71 silly install printInstalled
72 verbose stack Error: shasum check failed for C:\Users\ylondhe\AppData\Local\Temp\npm-2792-d3350124\registry.npmjs.org\protractor\-\protractor-4.0.14.tgz
72 verbose stack Expected: efc4a877fac3a182a9dded26cd5869f4762fd172
72 verbose stack Actual:   939a7c0b0a0d9f707a479045ff01b144d82814aa
72 verbose stack From:     http://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz
72 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
72 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
72 verbose stack     at emitNone (events.js:91:20)
72 verbose stack     at ReadStream.emit (events.js:185:7)
72 verbose stack     at endReadableNT (_stream_readable.js:974:12)
72 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
72 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
73 verbose cwd C:\Users\ylondhe
74 error Windows_NT 6.1.7601
75 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
76 error node v6.9.2
77 error npm  v3.10.9
78 error shasum check failed for C:\Users\ylondhe\AppData\Local\Temp\npm-2792-d3350124\registry.npmjs.org\protractor\-\protractor-4.0.14.tgz
78 error Expected: efc4a877fac3a182a9dded26cd5869f4762fd172
78 error Actual:   939a7c0b0a0d9f707a479045ff01b144d82814aa
78 error From:     http://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz
79 error If you need help, you may report this error at:
79 error     <https://github.com/npm/npm/issues>
80 verbose exit [ 1, true ]

-->

**Comment by Charlotteis** [comment] 2016-12-29 12:16
Duplicate of #14626, please see https://github.com/npm/npm/issues/14626#issuecomment-267701302 :)

**Comment by KenanY** [comment] 2017-02-03 13:11
Closing as a duplicate.

**Closed by KenanY** 2017-02-03 13:11 UTC
