### ISSUE TITLE
NPM install - 'uid must be an unsigned int' - macOS Sierra

### ISSUE THREAD

**Issue by frousselet** [npm/npm#14068] opened 2016-09-24 16:12 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Can't install components

#### How can the CLI team reproduce the problem?

`npm install -g yo`

`npm install -g less`

`npm config get user` prints `0`

`npm config get uid` prints `undefined`

[Log file](https://gist.github.com/frousselet/ceba531e08e34ab29ac8186be4313df0)

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v4.4.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: macOS Sierra Build 16A323
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-09-24 16:20
See https://github.com/npm/npm/issues/14047#issuecomment-249099655. Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-24 16:20 UTC
