### ISSUE TITLE
npm 5.0.3 behaves badly if package-lock.json is read-only

### ISSUE THREAD

**Issue by radcapitalist** [npm/npm#17177] opened 2017-06-13 15:25 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Perhaps related to https://github.com/npm/npm/issues/17173, which was about package.json.

My source control (Perforce) leaves sync'd files in a read-only state unless checked out.  It seems this scenario was not contemplated in the design of package-lock.json.  If I check package-lock.json into source control, causing it to be read-only, and then sync it to a machine that has out-of-date packages, and run npm install, npm install creates bad installs. Ultimately, in order to fix it, I have to delete node_modules and package-lock.json and run npm install over again.

#### How can the CLI team reproduce the problem
Check in package-lock.json generated on one machine.  Go to another machine that has out-of-date packages, sync the repository, make sure package-lock.json is read-only, and run npm install.  Then, run npm ls.  I see lots of errors.  Sorry, I don't have a clean, step-by-step repro.

### supporting information:

 - `npm -v` prints:  5.0.3
 - `node -v` prints:  v8.1.0
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:  Windows

**Comment by zkat** [comment] 2017-06-29 04:17
Closing this as a duplicate of #17173 because all of this is handled by `save`, which is what should be dealing with this.

**Closed as completed by zkat** 2017-06-29 04:17 UTC
