### ISSUE TITLE
"npm ERR! code E400" when unpublishing

### ISSUE THREAD

**Issue by scorpiongu** [npm/npm#12315] opened 2016-04-12 10:37 UTC
![capturefromcmd](https://cloud.githubusercontent.com/assets/18379697/14457407/e3493f74-00dc-11e6-928f-0e65c4b442ba.PNG)

npm-debug.log shows like that:

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'unpublish',
1 verbose cli   'censorify_20160411',
1 verbose cli   '--force' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] censorify_20160411
6 silly unpublish thing Result {
6 silly unpublish   raw: 'censorify_20160411',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'censorify_20160411',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized censorify_20160411
9 silly gentlyRm D:\Program Files\nodejs\node_cache\censorify_20160411 is being purged
10 verbose gentlyRm don't care about contents; nuking D:\Program Files\nodejs\node_cache\censorify_20160411
11 silly mapToRegistry name censorify_20160411
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/censorify_20160411
15 verbose get GET as part of write; not caching result
16 verbose request uri https://registry.npmjs.org/censorify_20160411?write=true
17 verbose request no auth needed
18 info attempt registry request try #1 at 18:34:06
19 verbose request using bearer token for auth
20 verbose request id 6f678effb6883d9f
21 http request GET https://registry.npmjs.org/censorify_20160411?write=true
22 http 200 https://registry.npmjs.org/censorify_20160411?write=true
23 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 verbose headers   etag: '"BCS7NCDDVCL7ZHASIL19PB29H"',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   'content-encoding': 'gzip',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'transfer-encoding': 'chunked',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Tue, 12 Apr 2016 10:34:04 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-sjc3645-SJC',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1460457244.744438,VS0,VE108',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"BCS7NCDDVCL7ZHASIL19PB29H"',
24 silly get     'content-type': 'application/json',
24 silly get     'content-encoding': 'gzip',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'transfer-encoding': 'chunked',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Tue, 12 Apr 2016 10:34:04 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sjc3645-SJC',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1460457244.744438,VS0,VE108',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose get saving censorify_20160411 to D:\Program Files\nodejs\node_cache\registry.npmjs.org\censorify_20160411_3Fwrite_3Dtrue\.cache.json
26 verbose correctMkdir D:\Program Files\nodejs\node_cache correctMkdir not in flight; initializing
27 info unpublish No version specified, removing all
28 verbose request uri https://registry.npmjs.org/censorify_20160411/-rev/1-e66bf69e77d8713468d50b0b67d2970f
29 verbose request sending authorization for write operation
30 info attempt registry request try #1 at 18:34:07
31 verbose request using bearer token for auth
32 http request DELETE https://registry.npmjs.org/censorify_20160411/-rev/1-e66bf69e77d8713468d50b0b67d2970f
33 http 400 https://registry.npmjs.org/censorify_20160411/-rev/1-e66bf69e77d8713468d50b0b67d2970f
34 verbose headers { 'content-type': 'application/json',
34 verbose headers   'cache-control': 'max-age=300',
34 verbose headers   'content-length': '17',
34 verbose headers   'accept-ranges': 'bytes',
34 verbose headers   date: 'Tue, 12 Apr 2016 10:34:05 GMT',
34 verbose headers   via: '1.1 varnish',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-served-by': 'cache-sjc3621-SJC',
34 verbose headers   'x-cache': 'MISS',
34 verbose headers   'x-cache-hits': '0',
34 verbose headers   'x-timer': 'S1460457245.690879,VS0,VE152',
34 verbose headers   vary: 'Accept-Encoding' }
35 verbose request invalidating D:\Program Files\nodejs\node_cache\registry.npmjs.org\censorify_20160411 on DELETE
36 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/censorify_20160411/-rev/1-e66bf69e77d8713468d50b0b67d2970f
36 verbose stack     at makeError (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
36 verbose stack     at CachingRegistryClient.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
36 verbose stack     at Request._callback (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
36 verbose stack     at Request.self.callback (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:199:22)
36 verbose stack     at emitTwo (events.js:100:13)
36 verbose stack     at Request.emit (events.js:185:7)
36 verbose stack     at Request.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1036:10)
36 verbose stack     at emitOne (events.js:95:20)
36 verbose stack     at Request.emit (events.js:182:7)
36 verbose stack     at IncomingMessage.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:963:12)
37 verbose statusCode 400
38 verbose pkgid censorify_20160411
39 verbose cwd D:\Documents\nodetest\censorify
40 error Windows_NT 6.3.9600
41 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "censorify_20160411" "--force"
42 error node v5.9.0
43 error npm  v3.7.3
44 error code E400
45 error Registry returned 400 for DELETE on https://registry.npmjs.org/censorify_20160411/-rev/1-e66bf69e77d8713468d50b0b67d2970f
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment] 2016-04-12 17:44
npm, Inc. recently [made some changes to how unpublishing works](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) on the primary registry. If you believe that you've hit this problem in error, you'll want to take it over to the [issue tracker the npm registry team recently opened](https://github.com/npm/registry/issues/new) and discuss it with them. Since the CLI is working as designed, I'm going to close this issue. Thanks for your time!

**Closed by othiym23** 2016-04-12 17:44 UTC
Labels: registry, support
