### ISSUE TITLE
unable to install reac-tools

### ISSUE THREAD

**Issue by hexideciml** [npm/npm#5449] opened 2014-06-09 21:54 UTC
I am unable to install react-tools.  please help.  log below

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'react-tools' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'react-tools', null ]
6 verbose cache add name=undefined spec="react-tools" args=["react-tools",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'react-tools',
7 verbose parsed url   path: 'react-tools',
7 verbose parsed url   href: 'react-tools' }
8 silly lockFile 0f761efe-react-tools react-tools
9 verbose lock react-tools C:\Users\tli\AppData\Roaming\npm-cache\0f761efe-react-tools.lock
10 silly lockFile 0f761efe-react-tools react-tools
11 silly lockFile 0f761efe-react-tools react-tools
12 verbose addNamed [ 'react-tools', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 47fcd5e0-react-tools react-tools@
15 verbose lock react-tools@ C:\Users\tli\AppData\Roaming\npm-cache\47fcd5e0-react-tools.lock
16 silly addNameRange { name: 'react-tools', range: '*', hasData: false }
17 verbose url raw react-tools
18 verbose url resolving [ 'http://registry.npmjs.org/', './react-tools' ]
19 verbose url resolved http://registry.npmjs.org/react-tools
20 info trying registry request attempt 1 at 14:47:47
21 http GET http://registry.npmjs.org/react-tools
22 info retry will retry, error on last attempt: Error: Invalid protocol
23 info trying registry request attempt 2 at 14:47:57
24 http GET http://registry.npmjs.org/react-tools
25 info retry will retry, error on last attempt: Error: Invalid protocol
26 info trying registry request attempt 3 at 14:48:57
27 http GET http://registry.npmjs.org/react-tools
28 silly lockFile 47fcd5e0-react-tools react-tools@
29 silly lockFile 47fcd5e0-react-tools react-tools@
30 error Error: Invalid protocol
30 error     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:335:51)
30 error     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:99:8)
30 error     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:11)
30 error     at RegClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:189:13)
30 error     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:102:17)
30 error     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
30 error     at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 6.1.7601
33 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-tools"
34 error cwd C:\Users\tli
35 error node -v v0.10.28
36 error npm -v 1.4.9
37 verbose exit [ 1, true ]
```

**Comment by smikes** [comment] 2015-01-28 20:46
I believe this is a duplicate of #5609 , and can be closed.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-01-31 22:10
Closing as duplicate of #5609, and also as resolved.

**Closed by othiym23** 2015-01-31 22:10 UTC
Labels: registry, support
