### ISSUE TITLE
npm ERR! Cannot read property 'path' of null

### ISSUE THREAD

**Issue by jadeye** [npm/npm#15348] opened 2016-12-29 21:00 UTC
I'm opening this issue because:
  - npm is producing an incorrect install.
  - npm is doing something I don't understand.

What's going wrong?

How can the CLI team reproduce the problem?
Cant tell

```
$ sudo npm install -g bean-sdk
sudo: npm: command not found
$ npm install -g bean-sdk
npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/bin/npm" "install" "-g" "bean-sdk"
npm ERR! node v4.4.5
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jadeye/npm-debug.log


npm-debug.log
https://gist.github.com/jadeye/10f79dbb72a57eef9aef304794bbb94c

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v4.4.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by legodude17** [comment] 2016-12-29 23:09
How is your internet connection?
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by jadeye** [comment] 2016-12-30 07:13
1. `https://registry.npmjs.org/`
2. `undefined`
3. `null`

**Comment by jadeye** [comment] 2016-12-30 07:18
@legodude17 FYI: I have this issue with 2 versions of `npm` installed...couldn't get `npm` to upgrade so this is what I did: [Understanding & updating npm on ubuntu 14.04](http://stackoverflow.com/questions/41350760/understanding-updating-npm-on-ubuntu-14-04/41378212#41378212)

**Comment by m-a-ge** [comment] 2017-01-09 10:12
if you are behind proxy server (common thing in corporate environment) you should set http-proxy setting accordingly:
```
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```

**Comment by jadeye** [comment] 2017-01-09 10:45
Am not behind proxy...thanx anywayz

**Comment by talk2ajay** [comment] 2017-01-09 15:51
@jadeye 

Were you able to resolve this issue? I'm facing the same issue when I'm running the below command

npm install -g webdriver_update

**Comment by jadeye** [comment] 2017-01-09 18:48
@talk2ajay nope.....still a stand still

**Comment by pchaganti** [comment] 2017-01-10 14:41
Same issue running on Amazon linux.

**Comment by Meeeeow** [comment] 2017-01-10 16:30
Same issue on ArchLinux, with Node 7.4.0 & NPM 4.0.5

**Comment by legodude17** [comment] 2017-01-10 17:16
@Meeeeow good point, this seems to be inadequate checking for 404's.

**Comment by jamesdixon** [comment] 2017-01-10 23:04
I can verify that this is due to the package not existing. macOS 10.12

**Comment by iqmal852** [comment] 2017-01-11 02:36
im getting same error when installing ironic framework

**Comment by watilde** [comment] 2017-01-12 11:05
I think it's duplicated with https://github.com/npm/npm/issues/15227

**Comment by AlexTes** [comment] 2017-01-13 09:28
From what I see this issue is about an unclear error message. I experienced the same. Also, I feel "npm is producing an incorrect install." is not the case at all. That in addition to the description of the issue is a bit prohibitive to voting.

We could either:
1. Encourage people to vote on this and say it's about an unclear error message when trying to install packages that don't exist globally.
2. (Close this and) I can open a new issue that clearly describes the problem.

I'll also see about submitting a PR 🤔  Seems straightforward!

**Comment by legodude17** [comment] 2017-01-13 18:49
@watilde I don't think this is a duplicate because it that case the person ran just `npm i -g` with no package name.

@AlexTes A PR would be very appreciated! 😄

**Comment by amelnikoff** [comment] 2017-01-19 08:23
In my case that problem was on macOS with enabled Kaspersky Internet Security. It blocked some connection because of not valid SSL certificate chain.

From npm-debug.log

```
15 verbose request uri https://registry.npmjs.org/bower
16 verbose request no auth needed
17 info attempt registry request try #1 at 11:04:29 AM
18 verbose request id 03038a161c1660c9
19 http request GET https://registry.npmjs.org/bower
20 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
21 info attempt registry request try #2 at 11:04:39 AM
22 http request GET https://registry.npmjs.org/bower
23 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
24 info attempt registry request try #3 at 11:05:40 AM
```

With disabled antivirus everything installed successfully.

**Comment by amelnikoff** [comment] 2017-01-19 08:45
In my case the problem appeared on macOS with enabled protection of Kaspersky Internet Security.
Kaspersky blocks some connection because not valid ssl certificate found in chain.

from npm-debug.log
```
15 verbose request uri https://registry.npmjs.org/bower
16 verbose request no auth needed
17 info attempt registry request try #1 at 11:04:29 AM
18 verbose request id 03038a161c1660c9
19 http request GET https://registry.npmjs.org/bower
20 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
21 info attempt registry request try #2 at 11:04:39 AM
22 http request GET https://registry.npmjs.org/bower
23 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
24 info attempt registry request try #3 at 11:05:40 AM
```

With disabled anitivirus everything installed successfully.

**Comment by jadeye** [comment] 2017-01-20 13:04
I don't know but it seems that the issue is persistent.
I have completely removed all `npm` & `node` installations.
Reinstalled them so versions are different.
Here's what this produces:
```
$ npm -v
3.10.10
$ node -v
v6.9.4
$ npm config get registry
https://registry.npmjs.org/
$ npm install -g bean-sdk
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/bean-sdk/node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bean-sdk"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/bin/lib/node_modules/lib/node_modules/bean-sdk/node_modules/.bin
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir

npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/bin/lib/node_modules/lib/node_modules/bean-sdk/node_modules/.bin'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, rmdir '/usr/local/bin/lib/node_modules/lib/node_modules/bean-sdk/node_modules/.bin'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/bin/lib/node_modules/lib/node_modules/bean-sdk/node_modules/.bin' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jadeye/npm-debug.log
$ sudo npm install -g bean-sdk
[sudo] password: 
/usr/local/bin/lib/node_modules/bin/bean -> /usr/local/bin/lib/node_modules/lib/node_modules/bean-sdk/build/cli/entry.js
/usr/local/bin/lib/node_modules/lib
└── bean-sdk@0.6.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/bean-sdk/node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
As far as `bean-sdk` goes, it exists but dependencies seem not to...

**Comment by legodude17** [comment] 2017-01-20 15:52
That seems like a different issue. Do you have write permission to
/usr/local/bin/lib/node_modules?

**Comment by jadeye** [comment] 2017-01-21 17:35
yes I do...all 3 subfolders `bin` `etc` `lib` are under my user.
Though:
```
$ ls -l /usr/local/bin/lib/node_modules/bin/
total 0
lrwxrwxrwx 1 root root 47 Jan 20 11:44 bean -> ../lib/node_modules/bean-sdk/build/cli/entry.js
```
And (this one's strange)
```
$ ls -l /usr/local/bin/lib/node_modules/lib/node_modules/
total 4
drwxr-xr-x 7 nobody jadeye 4096 Jan 20 11:44 bean-sdk
```
And this one...
```
$ ls -l /usr/local/bin/lib/node_modules/lib/node_modules/bean-sdk/
total 48
-rwxr-xr-x  1 nobody jadeye   52 Sep 15 08:20 bean.sh
drwxr-xr-x  6 nobody jadeye 4096 Jan 20 11:44 build
-rw-r--r--  1 nobody jadeye 3442 Nov 27 23:19 CHANGELOG.md
-rw-r--r--  1 nobody jadeye  124 Aug 30 19:15 circle.yml
drwxr-xr-x  2 nobody jadeye 4096 Nov 27 03:38 examples
-rw-r--r--  1 nobody jadeye 1460 Nov 22 00:42 HACKING.md
-rw-r--r--  1 nobody jadeye 1087 Aug 17 21:32 LICENSE
drwxr-xr-x 43 root   root   4096 Jan 20 11:44 node_modules
-rw-r--r--  1 nobody jadeye 2859 Jan 20 11:44 package.json
-rw-r--r--  1 nobody jadeye  995 Nov 27 03:38 README.md
drwxr-xr-x  2 nobody jadeye 4096 Nov 27 23:22 scripts
drwxr-xr-x  6 nobody jadeye 4096 Jan 20 11:44 src
```
I don't understand why it would install under `nobody`...
Any ideas on this??

**Comment by Fuhunter** [comment] 2017-01-23 15:19
@amelnikoff

Confirm your solution......gonna remove av at all...only problems with it

**Comment by darkn3rd** [comment] 2017-01-24 18:31
I get this error as well from installing a package that does not exist.  It is not a very user friendly to show feedback that the package does not exist:

```
$ npm -g install package_that_doesnt_exist
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/jmenchaca/.nvm/versions/node/v4.6.2/bin/node" "/Users/jmenchaca/.nvm/versions/node/v4.6.2/bin/npm" "-g" "install" "package_that_doesnt_exist"
npm ERR! node v4.6.2
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jmenchaca/projarea/wordpress-exp/provision/cloudformation/npm-debug.log
```

**Comment by legodude17** [comment] 2017-01-24 19:13
@darkn3rd that is not related and also a duplicate.

@jadeye there are some issues with it installing under nobody, but not his recent.

/cc @othiym23

**Comment by othiym23** [comment] 2017-01-24 19:27
@legodude17 As I'm no longer affiliated with either npm, Inc. or the npm CLI project, I'd appreciate it if you would no longer tag me into npm issue threads. Thank you!

**Comment by maclein** [comment] 2017-02-19 08:00
@amelnikoff's [reply](https://github.com/npm/npm/issues/15348#issuecomment-273709969) helped me fix this issue. I have Kaspersky Internet Security installed on my system which was causing this error`npm ERR! Cannot read property 'path' of null`. Disabled Kaspersky protection temporarily before running this command and it worked perfectly.

**Comment by xiaomalover** [comment] 2017-02-22 10:31
npm install -g cnpm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cnpm"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\wwwroot\humhub\npm-debug.log

**Comment by AlexTes** [comment] 2017-02-22 12:36
@xiaomalover works fine for me. In other words there's probably a problem reaching the npm registry from the network you're on. Check if your settings are the issue. You can see the first few comments for pointers. For reference:
```
❯ npm get registry
https://registry.npmjs.org/

❯ npm get http-proxy
undefined

❯ npm get https-proxy
null
```

**Comment by xiaomalover** [comment] 2017-02-24 02:41
@AlexTes Thanks, this problem has been solved now.I set it like this:
npm config set proxy null
npm config set https-proxy null
npm config set strict-ssl false

**Comment by GH-rajasekharReddy** [comment] 2017-02-27 12:50
I had faced the same issue on Windows 10 platform, but its not SSL related. So I have turned off my windows defender and re-run the command and it executed fine. 

Thought useful for someone.

**Comment by MuthuAliasKumar** [comment] 2017-02-28 13:28
Registry is empty when i checked using "npm config get" command. I tried npm config set registry=http://registry.npmjs.org/ and it worked for me.

node: 6.3.1
npm: 4.2.0

**Comment by arealdeadone** [comment] 2017-03-01 20:44
Well in my case I was trying it behind a proxy,
even with  ***proxy*** and ***https-proxy*** set
So I just changed the registry from
https://registry.npmjs.org to http://registry.npmjs.org 
and It worked!

**Comment by fastzhong** [comment] 2017-03-02 09:27
Yes, confirmed, if behind proxy, have to change https://registry.npmjs.org to http://registry.npmjs.org.

**Comment by ant5** [comment] 2017-03-10 12:36
I have no proxy. I  confirm the following solution:
 npm config set strict-ssl false

**Comment by ChampIsMe** [comment] 2017-03-13 17:08
Use this npm --https-proxy http://XX.AA.AA.BB:8080 install cordova-plugins

**Comment by bardez** [comment] 2017-04-03 12:25
@xiaomalover works for me ... thanks

**Comment by clq716** [comment] 2017-04-08 08:03
I had the same problem today and spent the whole day to resolve it by all the way above and failed. Finally I found the reason is that I made a spelling error, mistook "http-server" for "http-sever".......

**Comment by sumant30** [comment] 2017-04-16 06:11
I am facing the same issue when I tried 

npm install -g karma-cli@1.0.18

**Comment by legodude17** [comment] 2017-04-17 16:22
That is because the version `1.0.18` of `karma-cli` doesn't exist. Try just `npm install -g karma-cli`.

**Comment by sumant30** [comment] 2017-04-17 17:13
Thanks @legodude17.

**Comment by Shadowvail** [comment] 2017-05-02 18:12
In order to resolve this issue in my particular case, I had to run the cmd window I was executing the command from as administrator. I did not have permission to write to this directory without it.

**Comment by ajfarkas** [comment] 2017-05-08 18:14
I also vote for this as inadequate messaging.
Thanks for all your work!

**Comment by stevenaldinger** [comment] 2017-05-14 07:55
I had this issue trying to npm install a private package (which is essentially non-existent package in some sense) without having a .npmrc in place.
+1 for inadequate messaging. Honestly would've found the cause quicker if it had erred silently.

**Closed** 2017-06-18 10:37 UTC
Labels: bot-closed

**Comment by puneetdewan** [comment] 2017-07-20 05:42
none of the package is installing on my pc. It is giving this error.

`
C:\Users\puneet.dewan>npm install -g babel
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\puneet.dewan\npm-debug.log`

**Comment by puneetdewan** [comment] 2017-07-20 05:44
npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'babel' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData babel
8 silly fetchNamedPackageData babel
9 silly mapToRegistry name babel
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://infygit.ad.infosys.com:4873/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'babel',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'babel',
12 silly mapToRegistry   name: 'babel',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://infygit.ad.infosys.com:4873/babel
14 verbose request uri http://infygit.ad.infosys.com:4873/babel
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:09:01 AM
17 verbose request id 5bf009b7c2626ac7
18 http request GET http://infygit.ad.infosys.com:4873/babel
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.67.4.132:4873
20 info attempt registry request try #2 at 11:09:32 AM
21 http request GET http://infygit.ad.infosys.com:4873/babel
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.67.4.132:4873
23 info attempt registry request try #3 at 11:10:53 AM
24 http request GET http://infygit.ad.infosys.com:4873/babel
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 10.67.4.132:4873
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData  error for babel { Error: connect ETIMEDOUT 10.67.4.132:4873
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '10.67.4.132',
25 silly fetchPackageMetaData   port: 4873 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:505:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:331:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:288:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\puneet.dewan
29 error Windows_NT 10.0.14393
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel"
31 error node v7.4.0
32 error npm  v4.0.5
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
`

**Comment by thomazottoni** [comment] 2017-07-26 11:48
I had this issue and I solve this with the reinstall of npm:
$ npm install npm@latest -g

**Comment by notafox** [comment] 2017-07-31 22:26
I had the same error. @clq716 's post led me to double check my command. 
sudo npm install -g ionic@latest  --> I was having a space before @:
                               ionic @latest

**Comment by stevinus73** [comment] 2018-02-22 01:29
Which distribution are you using in Linux? Ubuntu?

**Comment by iqmal852** [comment] 2018-02-22 01:47
Can we close this issue? bcoz this issue alrdy solve and its from 2016, which is already obsolete

**Comment by stevinus73** [comment] 2018-02-26 02:06
@iqmal852 Label this as duplicate. This is already closed.
