### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by cloned2k16** [npm/npm#12741] opened 2016-05-18 05:48 UTC
>npm search command

<--- Last few GCs --->

   28640 ms: Mark-sweep 802.7 (1151.1) -> 776.1 (1129.0) MB, 750.1 / 0 ms [allocation failure] [GC in old space requested].
   29388 ms: Mark-sweep 776.1 (1129.0) -> 775.6 (1136.0) MB, 747.9 / 0 ms [allocation failure] [GC in old space requested].
   30150 ms: Mark-sweep 775.6 (1136.0) -> 775.6 (1129.0) MB, 761.7 / 0 ms [last resort gc].
   30879 ms: Mark-sweep 775.6 (1129.0) -> 775.5 (1122.0) MB, 729.4 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002FA33EC9FC9 <JS Object>
    1: fromString(aka fromString) [buffer.js:234] [pc=000001992D11572B] (this=000002FA33E04189 <undefined>,string=000002108C0EC4D1 <Very long string[170581519]>,encoding=000002FA33ED6521 <String[4]: utf8>)
    2: from [buffer.js:131] [pc=000001992D159EB6] (this=000000A3A0BAADE1 <JS Function Buffer (SharedFunctionInfo 0000020EAF3F6609)>,value=000002108C0EC4D1 <Very long string[170581519]>,enco...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by guiwp** [comment] 2016-05-25 13:01
Same here:
```
$ npm search beautify
npm WARN Building the local index for the first time, please be patient
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```

**Comment by edi9999** [comment] 2016-06-08 15:04
Same here : 

```
npm search imports-loader

<--- Last few GCs --->

    9052 ms: Mark-sweep 826.6 (1213.3) -> 824.9 (1218.3) MB, 340.3 / 0 ms (+ 103.9 ms in 592 steps since start of marking, biggest step 5.7 ms) [allocation failure] [GC in old space requested].
    9594 ms: Mark-sweep 824.9 (1218.3) -> 799.4 (1191.0) MB, 541.9 / 0 ms [allocation failure] [GC in old space requested].
   10190 ms: Mark-sweep 799.4 (1191.0) -> 799.4 (1185.0) MB, 596.0 / 0 ms [last resort gc].
   10729 ms: Mark-sweep 799.4 (1185.0) -> 799.3 (1179.0) MB, 539.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x112344ac9e59 <JS Object>
    1: fromString(aka fromString) [buffer.js:234] [pc=0x192920030569] (this=0x112344a04189 <undefined>,string=0x46286c0c759 <Very long string[176125621]>,encoding=0x112344ad7aa9 <String[4]: utf8>)
    2: from [buffer.js:131] [pc=0x192920030196] (this=0x4f5a44d7d39 <JS Function Buffer (SharedFunctionInfo 0xee0451f2671)>,value=0x46286c0c759 <Very long string[176125621]>,encodingOrOffset=0x112344a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted (core dumped)
```

Could you investigate a bit ?

**Comment by rkakrik** [comment] 2016-06-15 10:24
Same problem:
```
<--- Last few GCs --->

  740181 ms: Mark-sweep 848.5 (1226.3) -> 847.7 (1233.3) MB, 983.1 / 0 ms (+ 361.6 ms in 1069 steps since start of marking, biggest step 22.1 ms) [allocation failure] [GC in old space requested].
  741783 ms: Mark-sweep 847.7 (1233.3) -> 822.8 (1212.1) MB, 1602.6 / 0 ms [allocation failure] [GC in old space requested].
  743417 ms: Mark-sweep 822.8 (1212.1) -> 822.8 (1206.1) MB, 1634.2 / 0 ms [last resort gc].
  745044 ms: Mark-sweep 822.8 (1206.1) -> 822.8 (1200.1) MB, 1626.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x21975e8c9e59 <JS Object>
    1: fromString(aka fromString) [buffer.js:234] [pc=0x276d4abe7229] (this=0x21975e804189 <undefined>,string=0x165aca15c281 <Very long string[176048233]>,encoding=0x21975e8d7aa9 <String[4]: utf8>)
    2: from [buffer.js:131] [pc=0x276d4ab5de16] (this=0x641836e0821 <JS Function Buffer (SharedFunctionInfo 0x33e363af2601)>,value=0x165aca15c281 <Very long string[176048233]>,encodingOrOffset=0x2197...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
```
krik@exotab ~ % node -v
v6.2.1
krik@exotab ~ % npm -v
3.9.5
```

**Comment by myme** [comment] 2016-06-15 12:30
The same things happened to me as well. Seems to be related to building the initial index. I installed `npm -g i npm@3.4.x` and ran `npm search` which then seemed to properly build the local cache at least. I then reinstalled `npm -g i npm@latest` and search worked again. I tried working my way backwards through npm minor versions until this first step worked. Not much help, but neither is posting more of these `heap out of memory` traces I suppose...

**Comment by Overtonesinger** [comment] 2016-06-16 17:26
Same here.  Debian 8.5 x64, kernel ver.: **3.16.0-4-amd64**

**node v6.2.1**  (switchable using **n**  .... + **npm repaired** to work again using **this** script "curl -0 -L http://npmjs.org/install.sh | sudo sh") ;
------------------------------

```
<--- Last few GCs --->

  103247 ms: Mark-sweep 849.9 (1211.3) -> 849.3 (1219.3) MB, 21274.6 / 0 ms (+ 695.4 ms in 638 steps since start of marking, biggest step 61.5 ms) [allocation failure] [GC in old space requested].
  106317 ms: Mark-sweep 849.3 (1219.3) -> 824.4 (1197.1) MB, 3065.2 / 0 ms [allocation failure] [GC in old space requested].
  108208 ms: Mark-sweep 824.4 (1197.1) -> 824.3 (1190.1) MB, 1891.4 / 0 ms [last resort gc].
  110092 ms: Mark-sweep 824.3 (1190.1) -> 824.3 (1183.1) MB, 1883.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1529445c9e59 <JS Object>
    1: fromString(aka fromString) [buffer.js:234] [pc=0x25cbd0c5e49] (this=0x152944504189 <undefined>,string=0x1b8a8157d119 <Very long string[176424623]>,encoding=0x1529445d7aa9 <String[4]: utf8>)
    2: from [buffer.js:131] [pc=0x25cbd0543d6] (this=0x268ca2fdb249 <JS Function Buffer (SharedFunctionInfo 0x37dbddf2659)>,value=0x1b8a8157d119 <Very long string[176424623]>,encodingOrOffset=0x152944...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted
```

**Comment by Overtonesinger** [comment] 2016-06-16 18:11
needs labels: #search command ,  #search

**Comment by macedigital** [comment] 2016-06-23 15:40
This one has bugging me for a while now, and, as far as I can see, there are a lot of tickets regarding it already https://github.com/npm/npm/issues/12619#issuecomment-220176074, https://github.com/Microsoft/BashOnWindows/issues/411, https://github.com/npm/npm/pull/10615, etc.

In case it is helpful to anyone, this procedure worked for me:
````bash
npm -g i npm@3.8
npm search [any-package]
# Building the local index for the first time, please be patient - does it's thing - and lists search results
npm -g i npm@3.9
npm search [any-package]
# Doesn't have to build local index and finds packages ...
````

**Comment by adam66** [comment] 2016-06-28 15:57
Seeing this on 3.10.2 - work-around didn't work, still received the out-of-memory error on 3.8

**Comment by othiym23** [comment] 2016-06-28 16:04
Closing as duplicate of #12619.

**Closed by othiym23** 2016-06-28 16:04 UTC
Labels: big-bug, bug, search, support

**Comment by drewlamur** [comment] 2016-07-30 11:37
Hoping this is the right spot for this. There are quite a few of these threads open / closed. 

I received a similar error and JS stack processing a large data set.

Error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory.

Increasing the allocated memory did fix the issue. I started out with `--max-old-space-size=4096`. This didn't resolve the issue so I increased the memory limit to `--max-old-space-size=8192` and haven't seen the error again.

**Comment by Deepak275** [comment] 2016-08-22 11:26
hi everyone, i am using a npm package full-text-search-light package for implementing full text search. On instantiating it, it is taking a index parmeter. I am facing the same error Error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. when i am using index_amount 12. when i am bringing it down to the 6 or less, it is good to go. node version is
v6.3.1. Please help me

**Comment by pauldotknopf** [comment] 2016-08-28 03:20
Same issue here as well.

```
npm search hyperterm
npm WARN Building the local index for the first time, please be patient
⸨░░░░░░░░░░░░░░░░░░⸩ ⠋ : WARN Building the local index for the first
<--- Last few GCs --->

   26297 ms: Mark-sweep 929.4 (1242.8) -> 928.8 (1249.8) MB, 488.8 / 0 ms (+ 260.3 ms in 1299 steps since start of marking, biggest step 10.1 ms) [allocation failure] [GC in old space requested].
   27182 ms: Mark-sweep 928.8 (1249.8) -> 903.5 (1226.1) MB, 884.8 / 0 ms [allocation failure] [GC in old space requested].
   28112 ms: Mark-sweep 903.5 (1226.1) -> 903.5 (1221.1) MB, 930.7 / 0 ms [last resort gc].
   29025 ms: Mark-sweep 903.5 (1221.1) -> 903.3 (1215.1) MB, 912.8 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2b15ab7c9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x3c443a5df750] (this=0x2b15ab704189 <undefined>,string=0x3a3d5795c989 <Very long string[194702988]>,encoding=0x2b15ab7d7a41 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x3c443a53caf6] (this=0x1e3eeb2abb61 <JS Function Buffer (SharedFunctionInfo 0x2b15ab7e3319)>,value=0x3a3d5795c989 <Very long string[194702988]>,encodingOrOffset=0x2b15...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
12: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x3c4439f0961b
Abort trap: 6
```

**Comment by bogomips** [comment] 2016-09-01 17:47
same here

**Comment by Overtonesinger** [comment] 2016-09-01 18:12
Consider this possibility, please:
**npm** is **NOT** just an ordinary package for node.js ; It is **THE** Package Manager!

Yeah, I know: No one could have _known_ that one day it will have to create index with 0.9 million packages!

But it has happened.

I understand that You don't want it to depend on **any** external lib or executable.
But still, consider making this small exception:  Only when it **does** indeed detect that there is _no index_  and that it needs to do the "_creating index for the first time... please be patient_" procedure,

maybe it could **simply** run an external linux-command written in **pure C** (probably using "jsmn" lib for perf.&memory reasons)  to handle the index creation (parsing the **HUGE** JSON file in RAM _in-place_  with zero-copy principle).

Wouldn't this be a nice and logical solution?

**Comment by rasarab** [comment] 2016-09-15 20:15
Same issue  

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8c83816 [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [node]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [node]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned int, node::encoding) [node]
 9: void node::Buffer::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
11: 0x85b5471 [node]
12: 0x85b5a40 [node]
13: 0x4290a7fe
14: 0xa86a78f3
15: 0x4290bc36
16: 0x54d0f6be
17: 0x4290bc36
18: 0xa8662bf1
19: 0xa8662a72
20: 0xa86fdbe4
21: 0x54d32b59
22: 0xb28733e5
23: 0x429327fe
24: 0x429218c3
25: v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [node]
26: v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [node]
27: v8::Function::Call(v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [node]
28: node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [node]
29: node::ZCtx::After(uv_work_s*, int) [node]
30: 0x8f03eee [node]
31: 0x8f05d44 [node]
32: 0x8f05e14 [node]
33: 0x8f16853 [node]
34: uv_run [node]
35: node::Start(int, char**) [node]
36: main [node]
37: __libc_start_main [/lib/i386-linux-gnu/libc.so.6]
Aborted (core dumped)

**Comment by max-devjs** [comment] 2016-09-21 02:42
Is search working for some mere mortal?

**Comment by Bjeaurn** [comment] 2016-09-21 06:15
Guys, this issue was closed because it is a duplicate of #12619, everybody posting here should check out that topic first.

**Comment by laxmisuresh** [comment] 2016-09-28 16:19
I have faced this issue and tried for couple of days to figure it out.

npm install -g ionic  

causing out of memory. The root cause is there is no memory in the C: drive. if you see 
> npm config edit
It will open the text file. There if you see prefix property point to c:\Program files\npm. Since there is no
space in the C: drive, we used to get this issue.

I have installed using the below command

> npm install ionic -g --prefix d:\<install_folder>

ionic installed properly.

You need to do after installation

1. > npm config set prefix  d:\<install_folder> -g
2. put this d:\<install_folder> in path

It will solve your problem

**Comment by wahengchang** [comment] 2016-10-06 07:33
same here, in building VUE project

**Comment by Relanda** [comment] 2016-10-10 02:32
## same here. 
======================
npm -v
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
 2.15.9
======================
## 
and whatever I use npm install everything . it's all get this err.

===========================================
npm install express
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

  115240 ms: Scavenge 1401.2 (1457.9) -> 1401.2 (1457.9) MB, 18.4 / 0 ms (+ 0.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  117336 ms: Mark-sweep 1401.2 (1457.9) -> 1401.2 (1457.9) MB, 2095.5 / 0 ms (+ 1.0 ms in 2 steps since start of marking, biggest step 1.0 ms) [last resort gc].
  119305 ms: Mark-sweep 1401.2 (1457.9) -> 1401.2 (1457.9) MB, 1968.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000028DF32B4639 <JS Object>
    1: ToPropertyDescriptor(aka ToPropertyDescriptor) [native v8natives.js:~234] [pc=000002F516E2B988] (this=0000028DF32041B9 <undefined>,J=000000455F7E09D1 <an Object with map 0000038505793D61>)
    2: defineProperty(aka defineProperty) [native v8natives.js:775] [pc=000002F516C46934] (this=0000028DF32041B9 <undefined>,J=000000455F7E0A89 <an Error with map 000001A34D508931>,V=0000028DF32350A9...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
===========================================

what's happened ? Is somebody can help me ?

**Comment by jianwu** [comment] 2016-10-29 18:41
Same problem here, in Mac, tried uninstall and reinstall the latest version. deleted .mpn. Nothing helps.

**Comment by dmitriid** [comment] 2016-11-08 19:34
Chill out folks. 

To quote:

> *This is a known issue*, and has to do with the underlying *implementation of search* in the CLI being *pretty terrible* for anything more than a couple thousand packages. Replacing the search code with something that queries an online endpoint is something the various engineering teams at npm would like to do, but it *hasn't been addressed until now because it's never quite risen to the top of the priority list*, and because it's something that to fix properly requires coördinated effort between multiple teams at npm, Inc.

https://github.com/npm/npm/issues/12619#issuecomment-220176074

This is not going to be fixed

**Comment by othiym23** [comment] 2016-11-08 19:38
As I just mentioned to you on Twitter, there's an entirely new (streaming) search implementation in `npm@4`. `npm -g install npm@next` to check it out. Not only did we always intend to fix it, but it has, in fact, been fixed.

**Comment by dmitriid** [comment] 2016-11-11 09:41
@othiym23 Then perhaps, just perhaps, this and and a few other tickets can be closed with a mention of this?

**Comment by legodude17** [comment] 2016-11-14 21:55
This one already is closed, and so are most of the other ones about the broken search.

**Comment by maciejkowalski** [comment] 2017-01-27 18:37
Working solution (OSX)

```
$ npm cache clean
$ node --max_old_space_size=4096 --optimize_for_size --max_executable_size=4096 --stack_size=4096 /usr/local/bin/npm search PACKAGE_NAME
```

So simple and easy! I love node!

**Comment by max-devjs** [comment] 2017-01-29 16:56
@othiym23 with

```
node v7.4.0
npm 4.0.5
```

search is a delight now!

**Comment by shivamshreychawla** [comment] 2017-02-03 04:58
Please update to the latest version of npm, where search is now fixed.

npm install -g npm@latest

**Comment by owlstack** [comment] 2017-02-10 14:51
What is this supposed to be? "/usr/local/bin/npm search PACKAGE_NAME" @maciejkowalski

**Comment by maciejkowalski** [comment] 2017-02-10 18:29
@owlstack 
This is command in terminal that allows you to search npm packages.
If I type `npm search PACKAGE_NAME` then I have heap out of memory ERROR.

So I run node, then add some params (use more RAM), then I point my npm (absolute path) and search.

**Comment by AarushiSinghal** [comment] 2017-04-08 13:26
<--- Last few GCs --->

   31263 ms: Scavenge 306.7 (898.4) -> 306.7 (898.4) MB, 1.4 / 0 ms (+ 1.5 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   31318 ms: Mark-sweep 306.7 (1172.6) -> 305.2 (1168.6) MB, 54.3 / 0 ms (+ 1.8 ms in 2 steps since start of marking, biggest step 1.5 ms) [last resort gc].
   31349 ms: Mark-sweep 305.2 (1168.6) -> 303.7 (1168.6) MB, 31.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1d2d68cb4629 <JS Object>
    1: update [/root/DigitalBadge/node_modules/js-sha3/src/sha3.js:~111] [pc=0x320118e95edd] (this=0x2d85f545a8f1 <a Keccak with map 0x267d87222f51>,message=0x2d85f545a8c9 <Very long string[143718354]>)
    2: /* anonymous */(aka /* anonymous */) [/root/DigitalBadge/node_modules/js-sha3/src/sha3.js:~34] [pc=0x320118e96f01] (this=0x1d2d68c041b9 <undefined>,message=0x2d85f545a8c9 <Very long strin...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)



my node and npm version -
root@shivam:~/DigitalBadge# node -v
v4.4.2
root@shivam:~/DigitalBadge# npm -v
4.4.4

**Comment by majorcool** [comment] 2017-06-13 06:22
I also faced this issue, found this npm package helpful [increase-memory-limit](https://www.npmjs.com/package/increase-memory-limit)

**Comment by deju** [comment] 2017-07-04 07:56
@Exin It help me too. 👍

**Comment by ramania** [comment] 2018-02-01 10:53
Running the command in terminal of Ubuntu 14.04
newman run postman-collection.json -e environment.json -r -r cli,html --reporter-html-export report.html

with newman version 3.9.3 throws below error:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x121a2cc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0xe1c4cc [node]
 7: 0xe306b5 [node]
 8: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [node]
 9: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [node]
10: v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [node]
11: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [node]
12: v8::internal::Runtime_KeyedStoreIC_Slow(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0x29630400463d

Please someone suggest any solution to that
