### ISSUE TITLE
Absolute filepaths in the npm package json in the registry

### ISSUE THREAD

**Issue by f3lang** [npm/npm#19841] opened 2018-02-16 15:06 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
Hey, i just noticed in the package json of the npm in the registry, there are absolute paths in the "man" property: [https://registry.npmjs.org/npm/latest](https://registry.npmjs.org/npm/latest)
The absolute paths are pointing to "/Users/zkat/Documents/code/npm/man/man1/". I don't know if this is desired that way, but it don't think so :)

**Comment by kenany** [comment] 2018-02-16 15:25
Duplicate of https://github.com/npm/npm/issues/14293, https://github.com/npm/npm/issues/14541, https://github.com/npm/npm/issues/17138, etc.

**Closed as completed by kenany** 2018-02-16 15:25 UTC
