### ISSUE TITLE
`files` not being picked.

### ISSUE THREAD

**Issue by hemanth** [npm/npm#9419] opened 2015-08-26 16:15 UTC
For : 

```
npm i -g -g sanskrit-dict
```

All we see is:

![](http://i.imgur.com/F5OX3XG.png)

npm ERR! enoent ENOENT: no such file or directory for `cli.js` at [L#22](https://github.com/hemanth/sanskrit-dict/blob/master/package.json#L22) not sure what I'm missing.

**Comment by joepie91** [comment] 2015-08-26 16:17
For clarification, that screenshot is of the contents of the actual tarball being installed. No clear reason why it'd look like that, so there's the *possibility* of this being an npm bug (either on the publishing side or the registry side).

**Comment by hemanth** [comment] 2015-08-26 16:18
```
$ npm pack
```

```
$ tar -tf sanskrit-dict-1.0.2.tgz 
package/package.json
package/.npmignore
package/test.js
package/license
package/readme.md
```

**Comment by othiym23** [comment] 2015-08-26 16:30
```
bauchelain% h clone hemanth/sanskrit-dict
Cloning into 'sanskrit-dict'...
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 33 (delta 10), reused 29 (delta 6), pack-reused 0
Receiving objects: 100% (33/33), 133.88 KiB | 0 bytes/s, done.
Resolving deltas: 100% (10/10), done.
Checking connectivity... done.
bauchelain% pwd
/Users/ogd/Documents/projects/test-sanskrit-dict
bauchelain% cd sanskrit-dict
bauchelain% n i
mocha@2.2.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── debug@2.0.0 (ms@0.6.2)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
bauchelain% npm -ddd pack
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', '-ddd', 'pack' ]
npm info using npm@2.14.1
npm info using node@v2.5.0
npm sill cache add args [ '.', null ]
npm verb cache add spec .
npm sill cache add parsed spec { raw: '.',
npm sill cache add   scope: null,
npm sill cache add   name: null,
npm sill cache add   rawSpec: '.',
npm sill cache add   spec: '/Users/ogd/Documents/projects/test-sanskrit-dict/sanskrit-dict',
npm sill cache add   type: 'directory' }
npm verb addLocalDirectory /Users/ogd/.npm/sanskrit-dict/1.0.2/package.tgz not in flight; packing
npm verb tar pack [ '/Users/ogd/.npm/sanskrit-dict/1.0.2/package.tgz',
npm verb tar pack   '/Users/ogd/Documents/projects/test-sanskrit-dict/sanskrit-dict' ]
npm verb tarball /Users/ogd/.npm/sanskrit-dict/1.0.2/package.tgz
npm verb folder /Users/ogd/Documents/projects/test-sanskrit-dict/sanskrit-dict
npm info prepublish sanskrit-dict@1.0.2
npm verb addLocalTarball adding from inside cache /Users/ogd/.npm/sanskrit-dict/1.0.2/package.tgz
npm sill cache afterAdd sanskrit-dict@1.0.2
npm verb afterAdd /Users/ogd/.npm/sanskrit-dict/1.0.2/package/package.json not in flight; writing
npm verb afterAdd /Users/ogd/.npm/sanskrit-dict/1.0.2/package/package.json written
sanskrit-dict-1.0.2.tgz
npm verb exit [ 0, true ]
npm info ok
bauchelain% tar tfz sanskrit-dict-1.0.2.tgz
package/package.json
package/index.js
package/cli.js
package/license
package/readme.md
bauchelain% npm -v
2.14.1
```

What version of npm are you using to pack / publish `sanskrit-dict`?

**Comment by hemanth** [comment] 2015-08-26 16:32
Sorry forgot to mention that:

```sh
$ node -v
v2.5.0

$ npm -v
2.13.2

```

**Comment by othiym23** [comment] 2015-08-26 16:37
Can you try upgrading to `npm@latest`, and if that doesn't work, `npm@next`? I'm also running io 2.5.0, and I can't reproduce the issue you're seeing.

**Comment by hemanth** [comment] 2015-08-26 17:07
Thanks `npm@latest` worked. 

But, still how come that strange bug in the previous version?

**Comment by othiym23** [comment] 2015-08-26 17:27
It's hard to say -- the code changes between `npm@2.13.2` and `npm@2.14.0` are pretty small, and it doesn't look like any of the dependency changes should have directly affected packing. Is it possible that something unusual had happened to your install of npm during a previous upgrade?

Either way, I'm going to close this as resolved, since the upgrade fixes it. If you decide to dig deeper or run into this issue again, file a new issue and the team can take a deeper look.

**Closed by othiym23** 2015-08-26 17:27 UTC
Labels: support

**Comment by hemanth** [comment] 2015-08-27 04:25
Nothing unusual, will try to track it. :+1:
