### ISSUE TITLE
npm 3.10.8 now fails an npm install on a Linux box when shrinkwrap was done on Mac due to optionalDependency

### ISSUE THREAD

**Issue by khoomeister** [npm/npm#14411] opened 2016-10-25 19:31 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm 3.10.8 now fails an npm install on a Linux box when shrinkwrap was done on Mac due to optionalDependency

#### How can the CLI team reproduce the problem?

Shrinkwrap anything with [chokidar](https://github.com/paulmillr/chokidar/blob/dc783754bdd5b61b66dafbfbf6b1b83268eb0f4f/package.json#L43) on a Mac box and `npm install` on a Linux box.  fsevents will fail with this error:

```
npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Comment by watilde** [comment] 2016-10-25 21:15
Hi! Thanks for reporting this issue. It may be duplicated issue to #14042

**Comment by zkat** [comment] 2016-10-25 22:04
Closing as duplicate of #14042, thank for pointing that out, @watilde!

**Closed by zkat** 2016-10-25 22:04 UTC
