### ISSUE TITLE
not working any command of grunt bower etc

### ISSUE THREAD

**Issue by justVilla** [npm/npm#9831] opened 2015-10-02 20:09 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt',
1 verbose cli   '--save-dev' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of D:\Projects\myApp\package.json
5 warn package.json myapp@1.0.0 No repository field.
6 warn package.json myapp@1.0.0 No README data
7 warn package.json myapp@1.0.0 No license field.
8 verbose readDependencies loading dependencies from D:\Projects\myApp\package.json
9 silly cache add args [ 'grunt', null ]
10 verbose cache add spec grunt
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'grunt',
11 silly cache add   scope: null,
11 silly cache add   name: 'grunt',
11 silly cache add   rawSpec: '',
11 silly cache add   spec: '*',
11 silly cache add   type: 'range' }
12 silly addNamed grunt@*
13 verbose addNamed "*" is a valid semver range for grunt
14 silly addNameRange { name: 'grunt', range: '*', hasData: false }
15 silly mapToRegistry name grunt
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/grunt
19 verbose addNameRange registry:https://registry.npmjs.org/grunt not in flight; fetching
20 verbose request uri https://registry.npmjs.org/grunt
21 verbose request no auth needed
22 info attempt registry request try #1 at 1:36:59 AM
23 verbose request id 84a450f035ed0494
24 verbose etag "CMK0E6FT3J4J5C3I0Z1QN9JSN"
25 http request GET https://registry.npmjs.org/grunt
26 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
26 verbose stack     at Error (native)
26 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
26 verbose stack     at Object.exports.connect (_tls_wrap.js:955:21)
26 verbose stack     at Agent.createConnection (https.js:73:22)
26 verbose stack     at Agent.createSocket (_http_agent.js:174:16)
26 verbose stack     at Agent.addRequest (_http_agent.js:143:23)
26 verbose stack     at new ClientRequest (_http_client.js:133:16)
26 verbose stack     at Object.exports.request (http.js:31:10)
26 verbose stack     at Object.exports.request (https.js:163:15)
26 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:803:30)
27 verbose cwd D:\Projects\myApp
28 error Windows_NT 6.1.7600
29 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"
30 error node v4.1.1
31 error npm  v2.14.4
32 error error:0906D06C:PEM routines:PEM_read_bio:no start line
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment] 2015-10-05 19:48
Closing as duplicate of #9829.

**Closed by othiym23** 2015-10-05 19:48 UTC
Labels: proxy, support
