### ISSUE TITLE
Bash completion changes the COMP_WORDBREAKS, breaking global completion behaviour

### ISSUE THREAD

**Issue by rparree** [npm/npm#5820] opened 2014-07-29 07:48 UTC
Hi,

I found out the the npm completion script i had in my bash_completion.d directory broke the way bash completion works with equal sign globally. 

It turns out the completion script i have installed modifies the `COMP_WORDBREAKS` variable, which influences the behaviour of other scripts.

See my stackoverflow answer with a listing of the completion script See http://stackoverflow.com/a/25010080/103605. 

See also http://stackoverflow.com/a/12495480/103605

**Comment by jasonkarns** [comment] 2015-03-23 14:33
I ran into this bug recently. Without the equal sign, git completion breaks for any option containing an equal sign.

`git log --date=<TAB>`,  `git commit --reuse-message=<TAB>`, `git branch --set-upstream-to=<TAB>` are all broken because of npm's modification of `COMP_WORDBREAKS`.

**Comment by jasonkarns** [comment] 2015-03-23 14:34
Looks like this is a duplicate of #4530. moving my comment. this one should probably be closed.

**Comment by othiym23** [comment] 2015-08-07 04:05
Closing this as a duplicate of #4530, but at the same time, this is resolved by d7271b8226712479cdd339bf85faf7e394923e0d, which will be in the next `npm@2` release. Now all we have to do is get the completion script replaced in everyone's `bash_completion.d`...

**Closed by othiym23** 2015-08-07 04:05 UTC
Labels: bug
