### ISSUE TITLE
Error installing ionic

### ISSUE THREAD

**Issue by XcOdeTanzania** [npm/npm#11777] opened 2016-03-05 11:00 UTC
C:\Windows\System32>npm install -g ionic
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for C:\Users\Robbyn\AppData\Local\Temp\npm-8628-7a684d87\registry.npmjs.org\ionic-\ionic-1.7.14.tgz
npm ERR! Expected: af493d5df4688d917d778b0934d1739b9be6efe6
npm ERR! Actual:   0779d53c2519610bdb43e902d94b4bb36d4f66a5
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log

**Comment by KenanY** [comment] 2016-03-05 21:46
@XcOdeTanzania Can you try running:

```
npm cache clean
npm config set registry https://registry.npmjs.org
```

**Comment by jackieli123723** [comment] 2016-03-09 07:05
it doesn't work,@KenanY

**Comment by zkat** [comment] 2016-12-09 00:45
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:45 UTC
Labels: shasum, support, windows
