### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by NuBreed004** [npm/npm#15463] opened 2017-01-12 14:00 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
error in the installing process
#### How can the CLI team reproduce the problem?
typing npm i in terminal and got an error after installation

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2017-01-12 15:37
Please provide a `npm-debug.log` file. You can upload it to <https://gist.github.com/> and link it here.

**Comment by NuBreed004** [comment] 2017-01-12 16:56
https://gist.github.com/NuBreed004/048c622eb742f2e3262123936e2e80b5

**Comment by Charlotteis** [comment] 2017-01-13 10:11
This is a duplicate of #14670 and should be solved by updating your version of npm.

```
npm install -g npm@latest
```

**Comment by KenanY** [comment] 2017-02-03 13:04
Closing as a duplicate.

**Closed by KenanY** 2017-02-03 13:04 UTC
