### ISSUE TITLE
npm ERR! shasum check failed

### ISSUE THREAD

**Issue by georgeajin** [npm/npm#12783] opened 2016-05-20 13:24 UTC
Hi,
      i was not able to install zetta module using npm command. Attaching the debug log corresponding to the error.

Regards,
  Ajin
[npm-debug.txt](https://github.com/npm/npm/files/274644/npm-debug.txt)

**Comment by LeonidasJP** [comment] 2016-05-20 14:17
Same problem here. Semver v4.3.6 seems having shasum check errors in Bash on Ubuntu on Windows (Windows 10 build 14342), blocking installation of Gulp.
[npm-debug.log.txt](https://github.com/npm/npm/files/274739/npm-debug.log.txt)

**Comment by johncrisostomo** [comment] 2016-05-22 12:11
I am having the same problem on Ubuntu for Windows (Windows 10 build 14342). I installed Node 6 using the process described here: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

I am having these error messages:

`npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "browserify"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for /tmp/npm-5552-3589ab02/registry.npmjs.org/stream-http/-/stream-http-2.3.0.tgz
npm ERR! Expected: d77de76f6211072119f8d2a49a118717b8feeaa3
npm ERR! Actual:   c075486a0740d190a6fd71ae465c8a19e794d179
npm ERR! From:     https://registry.npmjs.org/stream-http/-/stream-http-2.3.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/johncrisostomo/npm-debug.log`

**Comment by dcunited08** [comment] 2016-05-23 14:20
Having the same issue.

npm ERR! shasum check failed for /tmp/npm-118-c9a1bd01/registry.npmjs.org/npm/-/npm-3.9.2.tgz
npm ERR! Expected: ae9b3dab82590a1866b2ba685c4406c4ba634407
npm ERR! Actual:   744ae4df122af3b9ac400b9c39cd3fc68badfe1e
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-3.9.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/dcook/npm-debug.log
dcook:dcook/ $

**Comment by zkat** [comment] 2016-12-09 00:40
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:40 UTC
