### ISSUE TITLE
npm 3 in https://nodejs.org/dist

### ISSUE THREAD

**Issue by shobhitg** [npm/npm#12930] opened 2016-06-02 02:30 UTC
Hi,

Not sure which project is the correct owner for this.

I am using [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) to install nodejs and npm in my build system. I wish to start using the latest and greatest versions of both.

frontend-maven-plugin downloads whatever is configured from this place: https://nodejs.org/dist

For nodejs, we have the latest versions (v6.2.0). But I can't seem to find npm 3.x.x anywhere. I really wish to move on to npm 3 because most parts of the grunt module's ecosystem requires it now.

Does npm/npm why is npm 3 not available there? Or if the responsibility lies elsewhere, please point me in the right direction.

-Shobhit

**Comment by KenanY** [comment] 2016-06-02 02:41
Duplicate of https://github.com/npm/npm/issues/10346?

**Comment by shobhitg** [comment] 2016-06-02 03:26
@KenanY Thanks for referencing.
Yes it seems duplicate.

But I would like to continue the discussion around this. I disagree with the resolution of that issue.
As of now, binaries are not being made available at any place. Making the npm binaries unavailable isn't going to make it easy for other ecosystems to adapt to npm.

Does anyone know which project maintains https://nodejs.org/dist ? I am trying to find at which repo I have the highest chance to make this happen.

**Comment by othiym23** [comment] 2016-06-02 04:07
> As of now, binaries are not being made available at any place.

All versions of the npm binaries are available from <https://registry.npmjs.org/npm>. The supported-by-npm way to access them is to use the version of npm bundled with the version of node you're using to run `npm -g install npm@<version>`.

> I am using [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) to install nodejs and npm in my build system.

That plugin is out of date. <https://nodejs.org/dist> hasn't had any new versions of npm uploaded to it since shortly after @isaacs left Joyent to form npm, Inc. in early 2014. The current maintainers of the Node.js web site are the members of [`nodejs/nodejs.org`](https://github.com/nodejs/nodejs.org), the Node.js web site working group. That's who you should lobby to see those files updated, but I would be prepared to meet some resistance to the idea of having npm builds in two places.

Because this isn't something that the CLI team is responsible for, I'm going to close this issue. Thanks for your time!

**Closed by othiym23** 2016-06-02 04:07 UTC
Labels: node-bug, support
