### ISSUE TITLE
EREADFILE error installing grunt for apprtc

### ISSUE THREAD

**Issue by cabeggar** [npm/npm#10184] opened 2015-10-30 18:41 UTC
I'm trying to build apprtc on my laptop and while I'm doing npm install on grunt I got the following error:

```
npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v3.3.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/cabeggar/.npm/grunt-htmlhint/0.9.9/package.tgz archive: ENOENT, open '/home/cabeggar/.npm/grunt-htmlhint/0.9.9/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cabeggar/apprtc/npm-debug.log
```

Any idea on solving this problem?

**Comment by KenanY** [comment] 2015-11-02 00:42
@cabeggar Maybe try `npm cache clean`?

**Comment by cabeggar** [comment] 2015-11-02 19:26
@KenanY still the same error after ```npm cache clean```

**Comment by iarna** [comment] 2015-11-06 19:15
This is a known issue, and is a duplicate of #10057.

**Closed by iarna** 2015-11-06 19:15 UTC
