### ISSUE TITLE
npm install --save-dev is removing installed dependencies

### ISSUE THREAD

**Issue by petetnt** [npm/npm#16794] opened 2017-05-30 14:30 UTC
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

We are using a similar script to that in [`eslint-config-airbnb`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) which we use to correctly install the peerDependent versions of our `eslint` config that builds on top of various other configs and libraries and to automatically configure it with a postinstall hook.

With **`npm@4`** everything works as it should: everything installed via the script end up in `devDependencies`, all the folders remain, `postinstall` hooks happen successfully and the app functions as it should

However with **`npm@5`** running the script
- adds the devDependencies to `package.json`
- keeps the dependencies in `package.json`
- postinstall hooks occur normally
- ... but `npm@5` proceeds to **delete** everything installed as `dependencies`, keeping only devDependencies and empty folders of dependencies containing a empty `node_modules` folder.

#### How can the CLI team reproduce the problem?

On MacOS / Linux systems run the following commands

``` bash
# create a CRA project to install some dependencies / create scaffolding to test on
npx create-react-app npm-test && cd npm-test

# (optional: run 'ls node_modules/react' to see that it already contains every needed)

# run the installer script
(
  export PKG=eslint-config-motley
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)

# See the following message in the end
> npm notice created a lockfile as package-lock.json. You should commit this file.
> added 42 packages, removed 877 packages and updated 219 packages in 35.977s

# optional: run 'ls node_modules/react' to see that it only contains an empty node_modules folder

```

Output after the first optional step:
![image](https://cloud.githubusercontent.com/assets/7641760/26587944/88e2bb26-455c-11e7-8bdd-96810b17be24.png)

Output after the second optional step:

![image](https://cloud.githubusercontent.com/assets/7641760/26588017/b63d4d16-455c-11e7-96d1-7589527f7e9d.png)

### supporting information:

 - `npm -v` prints: ` 5.0.0`
 - `node -v` prints: `v7.9.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `macOS`

**Comment by nahtnam** [comment] 2017-05-30 15:16
I think I'm having a similar problem where if I install any package with `npm install packagename`, every single other dependency is completely removed. I end up having to run `npm install packagename` then `rm -rf node_modules` then `npm install` for it to work.

**Comment by petetnt** [comment] 2017-05-30 17:16
I think @nahtnam might be right that this might be non-exclusive to `--save-dev` but applies to every other `npm install` with any package name too. Cannot test it right now, but I seem to recall that happening to me too couple of hours before reporting this one which I could reproduce.

**Comment by nahtnam** [comment] 2017-05-30 18:31
Temporary workaround: Use yarn to add the package, and do whatever you need to do. Then when you are ready to commit your stuff. Remove `yarn.lock`, `package-lock.json`, and `node_modules`, and run `npm install`. Note that this will reset the lock so your package versions might change. Then commit and push.

**Comment by nahtnam** [comment] 2017-05-31 07:13
I've also noticed that this happens to only one of my projects. In the project, I have several packages linked. I don't know if that is a cause or not but I am posting it here just in case.

**Comment by EasonWang01** [comment] 2017-06-14 03:53
Why npm5 will remove all package before install new one?

```
removed 1204 packages and updated 13 packages in 28.292s
```

**Comment by jaromero** [comment] 2017-06-22 00:01
As a data point I want to add that I'm seeing this issue only when I've installed dependencies with `yarn`. I suspect this is because by installing with `npm` the local packages have extra metadata added which `npm` looks for later on, which doesn't seem to happen with `yarn`. (I notice that OP is using `create-react-app`, which uses `yarn` to install deps)

In other words, for a clean project (i.e. freshly cloned, or after deleting `node_modules`), if deps are installed with `npm install` then subsequent `npm install` commands work fine.

However, if at any point `yarn` is used to install or uninstall anything, `npm install` then freaks the hell out and starts removing things.

So I suppose another workaround is to pick between `yarn` or `npm` and stick with it and never use the other one to install/uninstall deps.

**Comment by ljharb** [comment] 2017-06-22 00:51
@EasonWang01 #16853

**Comment by Qix-** [comment] 2017-06-22 08:23
Could this be related to the weird "feature" where `--save` is now implicit?

**Comment by zkat** [comment] 2017-07-01 03:48
Hey y'all, just checking in.

Gonna be looking into this, but tbh less worried about it 'cause it's literally just because npm is getting confused that yarn installed these packages and for some reason isn't putting them back after removing them.

For the time being, just run _a single_ `npm i` immediately after `create-react-app` and everything should be ok. That `npm i` shouldn't break anything either -- and you'll get a package lock.

**Comment by nahtnam** [comment] 2017-07-01 03:54
It is quite annoying because some of my projects use yarn and I just do `npm install` out of habit which creates this whole issue. I usually remove the package-lock because I always check the diffs before committing, so that isnt an issue.

**Comment by Qix-** [comment] 2017-07-01 07:22
I'm seeing this without yarn @zkat. I've never used yarn in my life.

**Comment by zkat** [comment] 2017-07-01 16:33
@Qix- the OP is describing an issue with `create-react-app`, which uses yarn.

There was a _separate_ issue with deps being removed that should be fixed with the latest canary (and will be included in next week's release). If you can still repro the missing deps thing without yarn, using the latest canary of npm (`npm i -g npmc@latest`), then please open a new issue and ping me so we can fix that asap, too.

**Comment by jehy** [comment] 2017-07-10 08:24
Same for me - peerDependencies are just removed with npm 5.1.0

**Comment by pselden** [comment] 2017-07-10 15:48
Hah! I'm working around a yarn bug https://github.com/yarnpkg/yarn/issues/3801 -- and added a postinstall script to do "npm install watch". Now when it runs on a system with npm@5 after the postinstall runs it deletes everything!

**Comment by EasonWang01** [comment] 2017-07-10 23:45
Another way is back to old npm version.

```
npm install npm@4.6.1 -g
```

**Comment by bjornhanson** [comment] 2017-08-10 19:00
I'm trying to update a big project from `node 4.4.3/npm 2.15.1` to `node 8.2.1/npm 5.3.0` and am running into this problem. If I install a new dev dependency (with npm 5.3.0) it removes some of the existing dev dependencies. It also seems to add many others. I don't understand what's going on yet.

**Comment by Calvo94** [comment] 2017-08-14 12:50
So is there any solution to this problem please ?

**Comment by nahtnam** [comment] 2017-08-14 15:37
I haven't seen this happening in the newer versions of npm.

**Comment by PewQuadrat** [comment] 2017-09-05 07:24
It also happen in version 5.4.0

**Comment by Phillippe43** [comment] 2017-09-11 15:54
Same problem. I was on 5.3 then upgraded to 5.4.1 and problem persisted. After copying the package.json file I deleted it, recreated it, and then pasted the old info in to it. Did a restore from within Visual Studio and no more problems with it removing other packages, however, I am now unable to do anything from the command line in the project. I keep getting the operation not permitted error which many people have already commented on here #18380 

EDIT:
Downgraded to 5.3 per npm suggestion, also deleted node_modules from project and did npm install and everything is working normally.

**Comment by Srounsroun** [comment] 2017-09-29 09:32
I'm on version 5.3 and is having the same problem.

My visual studio is running npm restore when saving package.json, so this is deleting my node_modules on file saving.

**Comment by elclanrs** [comment] 2017-11-01 21:02
This is still happening in 5.5.1.

My simple test case is creating a package that has some `bin` scripts, and a `postinstall` script that uses the bin scripts and installs extra packages.

When I install my package with `npm install file:../my-package` it runs the postinstall script, which in turn installs more packages. After that, the postinstall script fails because the bin script that it's supposed to run after installing the extra packages cannot be found because `my-package` is deleted from `node_modules`.

This breaks our entire posinstall workflow.

**Comment by stewartduffy** [comment] 2017-11-09 01:13
Any updates? Still getting this
```
$ npm --v
5.5.1
```
```
$ npm i formik --save
npm WARN less-loader@4.0.5 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN stylus-loader@3.0.1 requires a peer of stylus@>=0.52.4 but none is installed. You must install peer dependencies yourself.
npm WARN @paymark/ui-react-common@1.0.11 No repository field.

+ formik@0.10.3
removed 22 packages and updated 1 package in 9.919s
```

**Comment by sujitpk-perennial** [comment] 2017-11-09 09:50
@EasonWang01  how I come to know for which version I need to degrade the npm version?

**Comment by rally25rs** [comment] 2017-11-14 14:45
Not sure if this is exactly the same as the initial bug report, but the conversation turned to yarn + npm... It looks like npm@5 deletes any packages that it didn't install:

```
~/Projects/yarn-test : yarn
yarn install v1.3.2
warning package.json: License should be a valid SPDX license expression
warning test@0.0.1: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 0.87s.

~/Projects/yarn-test : ls node_modules/browserify
LICENSE            changelog.markdown example            lib                package.json       test
bin                code-of-conduct.md index.js           node_modules       readme.markdown

~/Projects/yarn-test : npm install left-pad
npm WARN test@0.0.1 license should be a valid SPDX license expression

+ left-pad@1.1.3
added 1 package, removed 133 packages and updated 1 package in 1.359s

~/Projects/yarn-test : ls node_modules/browserify
node_modules
```

This wouldn't be much of an issue, except that a lot of packages have `preinstall, install, postinstall` scripts that run a `yarn` or `npm` command, so if you happen to use Yarn and isntall a package that has a postinstall script that does an `npm install` then it ends up deleting all your yarn installed packages. There isn't much you can do about it as the consumer of these packages other than fork someone else's code and change the script to use whichever command you use (yarn or npm).

**Comment by iarna** [comment] 2017-11-16 19:44
The root cause here is that yarn and npm can't really be used in the same project. yarn will completely replace npm's node_modules, for example, and that's probably what npm should do here. It _certainly_ shouldn't be printing a partial package-lock (that's not a thing that we should ever do). This will likely be addressed by some structural changes due to land soon.

The reason the two can't use one another's node modules comes down to lockfiles. yarn can't use _anything_ in your node_modules w/o a lockfile. npm _can_ but it requires that the package.json on disk have the shasum of the installed pacakge in it, so it can verify that it matches what the registry has. npm (including older versions of npm) write this, yarn does not write this.

**Comment by iarna** [comment] 2017-11-16 19:45
Closing this as a duplicate of #17379

**Closed by iarna** 2017-11-16 19:45 UTC
Labels: npm5

**Comment by petetnt** [comment] 2017-11-16 19:50
FWIW I would be all in for nuking the whole `node_modules` during `npm install` if they have been previously installed with `yarn`. Thanks @iarna

**Comment by philou2024** [comment] 2017-12-05 16:40
I have the same problem without yarn. 
Version 5.5.1 remove modules silently.

**Comment by gavinmcfarland** [comment] 2017-12-20 00:57
I'm having a similar problem with a fresh install of npm version 5.6.0.

Each module I install using `--save` removes every other module. Is that the expected behaviour?

**Comment by 7c** [comment] 2017-12-20 04:30
I am having same behaviour with 5.6.0

**Comment by mhzed** [comment] 2018-01-03 14:39
Same happened here, with 5.6.0.

**Comment by BeckZero** [comment] 2018-01-10 01:48
+1... 5.6.0

**Comment by jasedwards** [comment] 2018-01-10 18:54
I am also getting this issue still and have never used yarn.  so it is unrelated to yarn.  It is only one package removed for me though.  it's a package I install from bitbucket

**Comment by rainrivas** [comment] 2018-01-11 23:40
We were having the same issue on our projects too. Rolled NPM back to 3.10.10 on our Linux box as a workaround. Locally (Mac OS 10.12) running v5.5.1 has no issues

**Comment by sujitpk-perennial** [comment] 2018-01-12 05:31
This is frustrating me. Every time I need to check for removed dependencies. Thank god I have lot of backups.

**Comment by petetnt** [comment] 2018-01-12 08:19
@sujitpk-perennial the dependencies stay in the `package.json`, so if something goes awry you can always do `rm -rf node_modules && npm install` again.

**Comment by 7c** [comment] 2018-01-12 10:35
I am not sure if this is relevant but: i have observed that this usually happens on over-smb-mounted volumes to my mac. Just an indication.

**Comment by Qix-** [comment] 2018-01-12 12:42
Just need to accept the fact that NPM refuses to address or fix this. 🤷‍♂️

**Comment by skorunka** [comment] 2018-01-17 09:22
I'm having the similar issue: `npm i` removes any installed `peerDependencies` packages.
Maybe it is a feature ;)

**Comment by ljharb** [comment] 2018-01-17 20:24
@skorunka that should only happen if you’re incorrectly omitting your deps’ peerDeps from your own package.json - iow, anything that your deps list as a peer dep must also be listed in your packages deps or dev deps.

**Comment by skorunka** [comment] 2018-01-18 16:28
@ljharb here is my package.json

```json
{
	"dependencies": {
		"@angular/animations": "5.2.0",
		"@angular/common": "5.2.0",
		"@angular/compiler": "5.2.0",
		"@angular/core": "5.2.0",
		"@angular/forms": "5.2.0",
		"@angular/http": "5.2.0",
		"@angular/platform-browser": "5.2.0",
		"@angular/platform-browser-dynamic": "5.2.0",
		"@angular/router": "5.2.0",
		"@angular/service-worker": "5.2.0",
		"@ng-bootstrap/ng-bootstrap": "1.0.0-beta.9",
		"@ngx-translate/core": "9.1.1",
		"@progress/kendo-angular-treeview": "1.0.1",
		"@progress/kendo-theme-bootstrap": "2.10.0",
		"adal-angular": "1.0.16",
		"angular-l10n": "4.1.4",
		"bootstrap": "4.0.0-beta.2",
		"core-js": "2.5.3",
		"eyc-sdk-ng-host-typings": "0.0.52",
		"eyc-sol-ant-pln": "file:my-lib/",
		"font-awesome": "4.7.0",
		"lodash": "4.17.4",
		"ng2-adal-aot": "0.3.6",
		"npm-install-peers": "1.2.1",
		"rxjs": "5.5.6",
		"zone.js": "0.8.20"
	},
	"peerDependencies": {
		"@progress/kendo-angular-buttons": "^2.0.0",
		"@progress/kendo-angular-dateinputs": "^1.4.3",
		"@progress/kendo-angular-dropdowns": "^1.6.0",
		"@progress/kendo-angular-excel-export": "^1.0.5",
		"@progress/kendo-angular-grid": "^1.7.1",
		"@progress/kendo-angular-inputs": "^1.4.2",
		"@progress/kendo-angular-intl": "^1.3.0",
		"@progress/kendo-angular-l10n": "^1.0.5",
		"@progress/kendo-data-query": "^1.1.2",
		"@progress/kendo-drawing": "^1.4.1",
		"eyc.control.ng-schema-form": "0.0.5",
		"eyc.control.ng-grid-filter": "0.0.1"
	},
	"devDependencies": {
		"@angular/cli": "1.6.4",
		"@angular/compiler-cli": "5.2.0",
		"@angular/language-service": "5.2.0",
		"@angularclass/hmr": "2.1.3",
		"@biesbjerg/ngx-translate-extract": "2.3.4",
		"@ngx-rocket/scripts": "2.0.0",
		"@types/jasmine": "2.8.4",
		"@types/jasminewd2": "2.0.3",
		"@types/lodash": "4.14.92",
		"@types/node": "9.3.0",
		"codelyzer": "4.0.2",
		"hads": "1.6.0",
		"htmlhint": "0.9.13",
		"https-proxy-agent": "2.1.1",
		"jasmine-core": "2.8.0",
		"jasmine-spec-reporter": "4.2.1",
		"karma": "2.0.0",
		"karma-chrome-launcher": "2.2.0",
		"karma-cli": "1.0.1",
		"karma-coverage-istanbul-reporter": "1.3.3",
		"karma-jasmine": "1.1.1",
		"karma-junit-reporter": "1.2.0",
		"ng-packagr": "1.6.0",
		"protractor": "5.2.2",
		"puppeteer": "1.0.0",
		"stylelint": "8.4.0",
		"stylelint-config-recommended-scss": "3.0.0",
		"stylelint-config-standard": "18.0.0",
		"stylelint-scss": "2.2.0",
		"ts-node": "4.1.0",
		"tslint": "5.9.1",
		"typescript": "2.6.2"
	}
}
```

When I do `npm i` + [`npm-install-peers`](https://www.npmjs.com/package/npm-install-peers) everything get installed. When I then do `npm i eyc-sdk-ng-host-typings@latest` the `peerPackages` are removed so I have to do `npm-install-peers` again.

**Comment by ljharb** [comment] 2018-01-18 16:43
Right - anything npm-install-peers is adding for you needs to be added to package.json, such that npm-install-peers is a noop

**Comment by skorunka** [comment] 2018-01-19 11:07
Hi, `npm-install-peers` installs packages which are in `peerDependencies`, ti does not modify `package.json` file. What I'm saying is, that `npm i` deletes all the packages, which are not in the `dependencies` or in the `devDependencies`. In the example above, after `npm i` all the packages previously installed by `npm-install-peers` are deleted.

**Comment by ljharb** [comment] 2018-01-19 16:42
@skorunka right. I’m saying that peer deps that are not in your package.json file are an error on your part anyways, and if you fix it, your particular problem will be resolved (even though the underlying npm issue won’t be)

**Comment by skorunka** [comment] 2018-01-20 14:45
@ljharb I do have all peers deps in package.json. `npm i` just removes everything which is not in `dependencies` or `devDependencies`. It is what it is, that's just how `npm i` works. Although, I think it should not work like that, but it is different story.

**Comment by ljharb** [comment] 2018-01-20 19:26
@skorunka again; anything that is a peer dep of you, or any of your deps or dev deps, must also be explicitly listed as a dep or devDep in your own package.json. `npm-install-peers` should simply not be necessary.

**Comment by skorunka** [comment] 2018-01-20 20:49
@ljharb I understand. Wouldn't be better to have an option to tell `npm i` to do not delete packages which are in `peerDependencies`? Like `npm i --no-delete`

**Comment by ljharb** [comment] 2018-01-20 21:31
The best would be that npm install simply never removes packages, since that’s npm prune’s job.

**Comment by eladchen** [comment] 2018-01-31 11:47
@ljharb Wouldn't it be nice if this known issue is documented somewhere?

Is there even one at the moment?

**Comment by ljharb** [comment] 2018-01-31 16:29
@eladchen it’s documented here, and #16853 / #18921

**Comment by eladchen** [comment] 2018-02-01 13:13
@ljharb I was thinking about the readme file 😝

**Comment by BrianMinister** [comment] 2018-02-16 06:43
I just started to have this problem where everything was being uninstalled, but then I realized that this started when I installed webpack. 

Removed webpack, and the problem vanished.

What tripped me to this as a problem was when I saw that in the cli, I was getting fail paths that looked like node_modules\webpack\node_modules\some other module\node_modules\etc...

Really wish people would flatten their packs, and not stake dependencies like that. The file path gets so long that it inevitably fails.

**Comment by matomoo** [comment] 2018-02-17 13:54
hi all,

wanna know if this npm unintall another modules is already solved on npm5? 
do i have to fallback to npm4?

**Comment by aa6** [comment] 2018-03-08 04:07
They marked it as fixed in https://github.com/npm/npm/issues/17379 locked the conversation and npm just continues to do the `added 1 package and removed 3 packages` thing.
When it became that `install` means to delete something?

**Comment by sujitpk-perennial** [comment] 2018-03-08 04:28
Dont use `npm` to install packages. Use `yarn`.

**Comment by aa6** [comment] 2018-03-08 04:48
@sujitpk-perennial nah, I've just tried it. Yarn has another type of schizophrenia: they renamed `install` to `add` and banned `install` keyword from using. It isn't going to go any further than npm if it already has such "interesting" solutions. Because that indicates lack of understanding that CLI tools are meant to be used by humans.

**Comment by jbruni** [comment] 2018-03-11 23:37
@iarna and @zkat - Arrived here now... it says it has been closed as duplicate of https://github.com/npm/npm/issues/17379... the issue there has been **locked**, with a closing statement that `This is fixed as of npm@5.7.1`

Well... I'm using npm 5.7.1, and just faced this issue of `npm install --save-dev` removing installed dependencies.

**Comment by vasanthns** [comment] 2018-03-16 14:09
Same with me, npm@5.7.1 and it removes all installed modules with --save-dev

**Comment by shahinfir** [comment] 2018-04-05 22:13
I've had this very frustrating problem happen to me almost every time I npm i --save a new package. Workaround I use: 
1. commit your modules folder
2. install your new module
3. if other modules have been deleted, run git checkout -- .
4. Module deletions should be undone
5. git add and commit your new modules

Hope this works :D

**Comment by vasanthns** [comment] 2018-04-06 08:00
Hi @shahinfir thank you for your solution, it would certainly work the way as you suggested. Still checking in node_modules to Git will have lot of additional work when we upgrade the modules etc., ideally it should not remove the modules on --save-dev. Thanks!

**Comment by paulofmbarros** [comment] 2018-05-18 16:16
I already had the same issue
you only need to run in your console

npm install npm@4.6.1

after that you can install any package you want without any problems

**Comment by DJDaveMark** [comment] 2018-05-22 13:01
I have the same problem with `npm i <package>` removing `optionalDependencies` which are specified with `git+ssh` URLs for a branch or a semver range.

My workaround is: `npm i <package>; npm i` which I alias as `nip`:

`function nip { npm i $1; npm i; }`

```
node -v 10.0.0
npm -v 6.0.1
```

**Comment by DJDaveMark** [comment] 2018-05-25 09:37
I just upgraded to npm `6.1.0` and **the problem has gone away** (`optionalDependencies` are no longer removed upon `npm i <package>`).

After upgrading to `6.1.0`, I downgraded back to `6.0.1` to double check, and the problem came back.
