### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by lukaskollmer** [npm/npm#16876] opened 2017-06-01 16:11 UTC
#### I'm opening this issue because:

npm is crashing

#### What's going wrong?

I updated node to v8.0.0 via homebrew, which also updated npm.
Node works fine, but npm always crashes with the following stacktrace:

```bash
$ npm install         
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

### supporting information:

 - `npm -v` prints: Nothing, because it crashes
 - `node -v` prints: `v8.0.0`
 - `npm config get registry` prints: Nothing, because it crashes
 - macOS 10.12.5 (16F73)

**Comment by SimenB** [comment] 2017-06-01 16:14
Same error as #16807, interesting

**Comment by zkat** [comment] 2017-06-01 20:36
Closing as duplicate of #16807

**Closed as completed by zkat** 2017-06-01 20:36 UTC
Labels: npm5
