### ISSUE TITLE
npm update - not found

### ISSUE THREAD

**Issue by charlierudolph** [npm/npm#8522] opened 2015-06-10 15:47 UTC
This is assuming the default loglevel of warn.

When running "npm install" if the module cannot be found, it errors
When running "npm update" if the module cannot be found, it succeeds and outputs nothing.
I believe that needs to at least issues warnings messages if not error.

**Comment by othiym23** [comment] 2015-06-10 16:30
Closing as duplicate of #8521.

**Closed by othiym23** 2015-06-10 16:30 UTC
Labels: support
