### ISSUE TITLE
npm5: protocol 'https' not supported when installing 'dns' package

### ISSUE THREAD

**Issue by Charlotteis** [npm/npm#16613] opened 2017-05-12 13:17 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Hi team! I've been using npm5 without issue since it was released and it is super duper awesome, thank you. However, today I have an issue!

When installing `dns` I get a protocol error that doesn't happen when I install the same package with npm4.

Logs linked below.

#### How can the CLI team reproduce the problem?

- `npm5 i dns`
https://gist.github.com/Charlotteis/be794df41a3b5191431c3073c2424d6a

### supporting information:

 - `npm -v` prints:
    - npm4: `4.5.0`
    - npm5: `5.0.0-beta.44`
 - `node -v` prints: `v7.9.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `OS X`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by simonua** [comment] 2017-05-12 18:58
This is reproducible on my platform:

- npm 5.0.0-beta.49
- node v7.10.0
- Windows 7 64-bit

[https://gist.github.com/simonua/4bc145d19c5fbcd1792209f9c742bbe6](https://gist.github.com/simonua/4bc145d19c5fbcd1792209f9c742bbe6)

**Comment by simonua** [comment] 2017-05-12 19:08
@Charlotteis, looking through the log, I think we can narrow this a tad bit to this offending item:

`200 silly fetchPackageMetaData error for emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz Protocol "https:" not supported. Expected "http:"`

STRs:

`npm5 i emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz` - **fails**
`npm i emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz` - **succeeds**

I am using npm5@5.0.0-beta.49 and npm@4.6.1.

![image](https://cloud.githubusercontent.com/assets/8005145/26013072/c8af2550-3724-11e7-8e8b-d89517169af7.png)

**Comment by simonua** [comment] 2017-05-12 19:08
Speculation: so maybe this is specifically for installing from a non-registry source such as Github here?

**Comment by simonua** [comment] 2017-05-12 19:15
@Charlotteis I see a discrepancy to calling the install with _http_ here and the repo url property in [package.json](https://github.com/component/emitter/blob/master/package.json) being _https_.

Running `npm5 i emitter@https://github.com/component/emitter/archive/1.0.1.tar.gz` succeeds (notice http**s**).

I'm sorry, not offering any solutions, just details for forensics.

**Comment by simonua** [comment] 2017-05-12 19:24
Linking to the npm5 beta bug tracker: #16510

**Comment by zkat** [comment] 2017-05-12 22:48
I bet this is happening because of the github redirect to https messing with the agent. welp. Thanks, @Charlotteis! This helps a lot.

In the meantime, I assume you can work around it by using `https://github.com` instead

**Comment by simonua** [comment] 2017-05-12 23:09
Afk, but I wonder whether the package.json that references the Github location has the path hard-coded rather that the short-hand form. Would be a good PR for that package. If I'm not making any sense, just ignore me. 😁

**Comment by zkat** [comment] 2017-05-12 23:29
Sigh. Okay. This one's gonna be a pain to fix. The entire redirect logic needs to be moved into `make-fetch-happen` itself (which tbh I was already thinking of doing), so we can change the http agent if protocols change.

I'll.... put up a bug on m-f-h for this.

**Comment by zkat** [comment] 2017-05-12 23:37
Here's the issue on that repo: https://github.com/zkat/make-fetch-happen/issues/26

**Comment by zkat** [comment] 2017-05-12 23:58
I originally thought the other one was a proxy issue, but I'm gonna close this one as a duplicate of #16569.

Thanks! This issue definitely helped me grok wtf was going on.

**Closed by zkat** 2017-05-12 23:58 UTC
Labels: big-bug, npm5
