### ISSUE TITLE
Updating bower fails in node 4.2.1

### ISSUE THREAD

**Issue by keyhan** [npm/npm#10718] opened 2015-12-06 15:41 UTC
running the following command:
 ~/node/4.2.1/lib/node_modules/bower$ npm update
Fails with 

The following can be read in the log:

alTree │ └─┬ is-absolute@0.1.7
7338 silly idealTree │   └── is-relative@0.1.3
7338 silly idealTree ├── window-size@0.1.0
7338 silly idealTree ├── wordwrap@1.0.0
7338 silly idealTree ├── wrappy@1.0.1
7338 silly idealTree └── yargs@3.10.0
7339 silly generateActionsToTake Starting
7340 silly install generateActionsToTake
7341 verbose stack TypeError: Cannot read property 'target' of null
7341 verbose stack     at module.exports (/home/keyhan/node/4.2.1/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
7341 verbose stack     at Array.<anonymous> (/home/keyhan/node/4.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
7341 verbose stack     at LOOP (/home/keyhan/node/4.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:

**Comment by othiym23** [comment] 2015-12-07 16:48
Closing as duplicate of #10686 #10641, which has a fix under development in #10662 that needs a little more work and tests.

**Closed by othiym23** 2015-12-07 16:48 UTC
