### ISSUE TITLE
Allocation Error

### ISSUE THREAD

**Issue by norman-abramovitz** [npm/npm#14087] opened 2016-09-27 00:19 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Cannot run a npm search.
#### How can the CLI team reproduce the problem?
Not sure exactly but here is the output from the failed npm search command

$ npm search security
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "search" "security"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.8

npm ERR! Cannot read property '_updated' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

  144282 ms: Mark-sweep 1000.8 (1292.1) -> 975.1 (1274.1) MB, 804.6 / 0.0 ms [allocation failure] [GC in old space requested].
  145146 ms: Mark-sweep 975.1 (1274.1) -> 975.1 (1274.1) MB, 864.5 / 0.0 ms [allocation failure] [GC in old space requested].
  146077 ms: Mark-sweep 975.1 (1274.1) -> 975.0 (1237.1) MB, 930.6 / 0.0 ms [last resort gc].
  146928 ms: Mark-sweep 975.0 (1237.1) -> 975.0 (1230.1) MB, 851.6 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x26aa241cfb51 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x380a5abe04f0] (this=0x26aa24104381 <undefined>,string=0xf7b72dab8e1 <Very long string[202761985]>,encoding=0x26aa241dd329 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x380a5ab9ac31] (this=0x3696ccaa9c21 <JS Function Buffer (SharedFunctionInfo 0x28ed065f6a59)>,value=0xf7b72dab8e1 <Very long string[202761985]>,encodingOrOffset=0x26aa24...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
13: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>, v8::internal::Isolate*) [/usr/local/bin/node]
14: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x380a5a7092a7
16: 0x380a5abe04f0
17: 0x380a5ab9ac31
Abort trap: 6

### supporting information:
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - OS X:
 - Network issues:

 https://github.com/npm/npm/wiki/Troubleshooting

**Comment by KenanY** [comment] 2016-09-27 13:04
Looks like a duplicate of https://github.com/npm/npm/issues/12619.

**Closed by KenanY** 2016-09-27 13:04 UTC

**Comment by KenanY** [comment] 2016-11-08 20:08
[Fixed in `npm@4`](https://github.com/npm/npm/blob/4639b0eed8db92c8872011d4affd10c498b3b9db/CHANGELOG.md#search-rewrite-breaking)
