### ISSUE TITLE
Trying to install chai, always get shasum check failed

### ISSUE THREAD

**Issue by kennyyyb** [npm/npm#12807] opened 2016-05-23 13:34 UTC
When I perform the command, "sudo npm install chai --save" I get the following error. 

npm WARN package.json converter@1.0.0 No description
npm WARN package.json converter@1.0.0 No repository field.
npm WARN package.json converter@1.0.0 No README data
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "chai" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! shasum check failed for /tmp/npm-10322-d6b17d90/registry.npmjs.org/chai/-/chai-3.5.0.tgz
npm ERR! Expected: 4d02637b067fe958bdbfdd3a40ec56fef7373247
npm ERR! Actual:   96b2f5c75bc70a89023eb8d1158b6cbf17383661
npm ERR! From:     https://registry.npmjs.org/chai/-/chai-3.5.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/web/converter/npm-debug.log

[npm-debug.pdf](https://github.com/npm/npm/files/277565/npm-debug.pdf)

**Comment by kennyyyb** [comment] 2016-05-23 15:29
I'm using bash on Win10 and it appears this is probably the issue as per https://github.com/npm/npm/issues/12436

**Comment by LeonidasJP** [comment] 2016-05-24 06:59
Duplicate of #12783 as well

**Comment by zkat** [comment] 2016-12-09 00:40
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:40 UTC
