### ISSUE TITLE
uv_err_name: Assertion `0' failed during npm install

### ISSUE THREAD

**Issue by realshadow** [npm/npm#8880] opened 2015-07-09 15:17 UTC
Hey, I am trying to make npm install work in Vagrant (Ubuntu 14.04x64 guest on Windows 7 host), but I keep getting 

```
npm verb gentlyRm don't care about contents; nuking /var/www/html/***/*********-****/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan
npm verb write writing to /var/www/html/***/*********-****/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/package.json
../deps/uv/src/uv-common.c:143: uv_err_name: Assertion `0' failed.
Aborted
```

when I run `npm install gulp-util --no-bin-links --verbose`. So far I have noticed this to be the case on this particular package.

At first I thought it had something to do with Windows path limitation, because it works if I try to install it in parent folders and other places. But after applying this patch https://github.com/mitchellh/vagrant/issues/1953 the issue persists and the error message is a bit too cryptic for me

Node version 0.12.5
NPM version 2.11.2

Edit:

Here is gist of this strace `strace -F -f -s 1024 -o out.log npm install --no-bin-links --silly` 
https://gist.github.com/realshadow/179320fc9d60aac35dfe#file-npm_trace

Trace log file had 30MB so I copied last ~30k rows.

**Comment by realshadow** [comment] 2015-07-09 15:17
Moved to npm issues

**Comment by othiym23** [comment] 2015-07-15 05:22
So I have some bad news: anything that ends in a `SIGABRT` and has error output like

```
../deps/uv/src/uv-common.c:143: uv_err_name: Assertion `0' failed.
```

is a bug in Node itself that npm can't work around. Have you tried using the newest version of Node 0.12 or io.js? If those don't fix it, you should take your (useful) strace output over to either nodejs/node or nodejs/io.js and see what the Node core maintainers make of it.

Either way, as we can't do anything about issues in core, I'm going to close this out. I hope you get this sorted out!

**Closed by othiym23** 2015-07-15 05:22 UTC
Labels: node-bug

**Comment by harmic** [comment] 2017-03-02 06:29
Just in case someone else has this issue - I was having the same assertion failure when running npm install on Node 0.12.

I collected a core dump and looked at the backtrace - this line revealed the cause:

    #5  0x0000000000bf7b5e in node::UVException (isolate=<value optimized out>, errorno=-116, syscall=0x0, msg=0xf9b919 "stat", path=0x1e20e90 "/home/eharmic/.npm/registry.npmjs.org/xmldom/.cache.json") at ../src/node.cc:790

errno 116 = ESTALE (Stale NFS Handle). Which makes sense, since the home directory is an NFS share, and other VMs were performing installations at the same time. The solution is to set the npm cache to some other location.
