### ISSUE TITLE
[npm install -g] redundant EPACKAGEJSON warnings

### ISSUE THREAD

**Issue by williamboman** [npm/npm#8871] opened 2015-07-08 22:52 UTC
So, doing global installations on `npm@3` yields 4 `WARN` logs, like;

```sh
npm WARN EPACKAGEJSON /Users/william/.nvm/versions/node/v0.12.5/lib No description
npm WARN EPACKAGEJSON /Users/william/.nvm/versions/node/v0.12.5/lib No repository field.
npm WARN EPACKAGEJSON /Users/william/.nvm/versions/node/v0.12.5/lib No README data
npm WARN EPACKAGEJSON /Users/william/.nvm/versions/node/v0.12.5/lib No license field.
```

As the installation is global, these errors are redundant, if not invalid.

**Comment by csantanapr** [comment] 2015-07-19 14:40
could this be a nvm problem and not an npm problem?

**Comment by csantanapr** [comment] 2015-07-19 14:43
I'm guessing is npm, I think is a problem walking the tree up and not finding a package.json in /.nvm/versions/node/v0.12.5/lib

**Comment by jokeyrhyme** [comment] 2015-07-20 02:09
possible duplicate: #8887

**Comment by iarna** [comment] 2015-08-10 17:53
Released in 3.2.2

**Closed by iarna** 2015-08-10 17:53 UTC
Labels: bug, ready

**Comment by webfd** [comment] 2015-11-01 03:38
```
npm WARN ENOENT ENOENT: no such file or directory, open '/home/kelvin/workspace/web/package.json'
npm WARN EPACKAGEJSON /home/kelvin/workspace/web No description
npm WARN EPACKAGEJSON /home/kelvin/workspace/web No repository field.
npm WARN EPACKAGEJSON /home/kelvin/workspace/web No README data
npm WARN EPACKAGEJSON /home/kelvin/workspace/web No license field.
```
do you help me.

**Comment by webfd** [comment] 2015-11-01 03:44
How

This package takes advantage of onload-script npm config option.

    A node module to require() when npm loads. Useful for programmatic usage.
when onload-script executes before any work on npm command is done, so if we create package.json file here (and block while we do it) the problem is solved.
Install

`$ npm install -g npm-autoinit`

After that, add npm-autoinit/autoinit as npm onload script:

`$ npm config set onload-script npm-autoinit/autoinit`

see:[ https://www.npmjs.com/package/npm-autoinit](https://www.npmjs.com/package/npm-autoinit)
