### ISSUE TITLE
shasum check failed for ...

### ISSUE THREAD

**Issue by AndyGard** [npm/npm#10977] opened 2015-12-29 15:24 UTC
Hello, please help me.
What is my problem?

```
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /tmp/npm-8141-f9415816/registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
npm ERR! Expected: 894bbae414278da6f68229959ee72aff34a669b5
npm ERR! Actual:   23212ae5107f7b7b1c109f72a69cc554eb3b491e
npm ERR! From:     https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
```

thanks
[npm-debug.log.zip](https://github.com/npm/npm/files/74057/npm-debug.log.zip)

**Comment by zkat** [comment] 2016-12-09 00:49
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:49 UTC
Labels: shasum, support
