### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hannahhuck** [npm/npm#12339] opened 2016-04-13 15:01 UTC
I get the following error when trying to run

`sudo npm install -g post-css-split`

Cannot convert undefined or null to object

Any help with how to resolve this would be greatly appreciated. 

Thanks

[npm-debug.log.zip](https://github.com/npm/npm/files/217362/npm-debug.log.zip)

**Comment by atc-** [comment] 2016-05-04 11:21
I also get this issue when running `npm install` in a previously-working Node project:

	npm verb stack TypeError: Cannot convert undefined or null to object
	npm verb stack	 at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:121:29)
	npm verb stack	 at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
	npm verb stack	 at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:19:8
	npm verb stack	 at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:168:7)
	npm verb stack	 at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
	npm verb stack	 at FSReqWrap.oncomplete (fs.js:117:15)
	npm verb cwd <project folder path snipped>
	npm ERR! Windows_NT 6.1.7601
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--loglevel" "verbose"
	npm ERR! node v6.0.0
	npm ERR! npm  v3.8.6

	npm ERR! Cannot convert undefined or null to object
	npm ERR! 
	npm ERR! If you need help, you may report this error at:
	npm ERR!	 <https://github.com/npm/npm/issues>
	npm verb exit [ 1, true ]

Versions are:

	$ npm --version
	3.8.6

	$ node --version
	v6.0.0

Windows_NT 6.1.7601

This happened with 5.5.x Node (and 3.3.x) too.

**Comment by offero** [comment] 2017-01-12 18:34
https://github.com/npm/npm/issues/9896

**Comment by legodude17** [comment] 2017-01-13 19:00
@offero is right, this is a duplicate of #9896.

**Closed** 2017-06-18 12:02 UTC
Labels: bot-closed
