### ISSUE TITLE
Error when install plugin

### ISSUE THREAD

**Issue by ShaoYongChao** [npm/npm#9197] opened 2015-08-07 08:26 UTC
```
apm install atom-beautify
Installing atom-beautify to /Users/mrstar/.atom/packages ✗

npm ERR! registry error parsing json
npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mrstar/.atom/.apm/.apmrc" "--userconfig" "/Users/mrstar/.atom/.apmrc" "install" "/private/var/folders/dl/ym188ths73jfyx0wtrwps0zw0000gn/T/d-11577-3337-hinfvw/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /var/folders/dl/ym188ths73jfyx0wtrwps0zw0000gn/T/npm-3348-41490e14/registry.npmjs.org/prettydiff/-/prettydiff-1.12.18.tgz
npm ERR! Expected: 8a0cc6f3bbcfa6048022f512da65e5aad3896e8b
npm ERR! Actual:   ca89ed0265d9fcba92445cdc994b90928bf7fe41
npm ERR! From:     https://registry.npmjs.org/prettydiff/-/prettydiff-1.12.18.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/dl/ym188ths73jfyx0wtrwps0zw0000gn/T/apm-install-dir-11577-3337-1xvfwcu/npm-debug.log
```

**Comment by zkat** [comment] 2016-12-09 00:55
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:55 UTC
Labels: support
