### ISSUE TITLE
Bring "licenses" back

### ISSUE THREAD

**Issue by fredck** [npm/npm#7091] opened 2015-01-08 10:56 UTC
We license CKEditor in a triple OSS license model: GPL, LGPL and MPL. There is no "priority" on them, just pick the one that you want.

There is no way to include all license options in package.json.

I [read in an old comment](https://github.com/npm/npm/issues/4473#issuecomment-64406700) that the `licenses` option has been deprecated in package.json, with no clear reason.

What about reviving `licenses` or even making `license` accepting both a string for a single license or an array of strings for multiple?

**Comment by othiym23** [comment] 2015-01-08 16:25
That comment is on a feature request that's still outstanding. I'd love to see support for multiple licenses added (I commented supporting the feature before I even started working at npm, Inc.), but the list of things to do is long and the team working on npm is still relatively small. I'm going to close this issue as a duplicate of #4473, but a patch is as welcome as ever on that issue. Thanks!

**Closed by othiym23** 2015-01-08 16:25 UTC
Labels: feature-request

**Comment by fredck** [comment] 2015-01-09 10:16
I'm not sure making this a dup of #4473 is right. For instance, if a patch is provided there to introduce support for multiple licenses, it'll not satisfy that ticket fully, as that one is about enforcing the use of the license configuration.

It makes sense having a reference to this ticket there, but this one can live standalone as there is no cross-dependency between them.

**Comment by kemitchell** [comment] 2015-04-29 21:52
The newest version of SPDX includes a "release candidate" spec for a "license expression syntax". The syntax permits `AND` and `OR` operators for conjoining otherwise valid SPDX identifiers, in addition to ranges and `WITH` to identify various bolt-on license exceptions.

I have a very young, but so far pretty reliable validator here: http://github.com/kemitchell/spdx

**Comment by jcrben** [comment] 2015-07-12 22:45
I agree that this seems distinct from #4473 which is now closed anyway.

> the list of things to do is long and the team working on npm is still relatively small

What would a good multiple `licenses` option look like? I came here because I was looking at a long list of popular packages which a log was warning had no `license`, and it seems to be because they use the `licenses` array syntax.

**Comment by kemitchell** [comment] 2015-07-13 03:56
Since npm 2.10, npm accepts SPDX expressions like `(MIT OR BSD-2-Clause)` for `license` properties. `licenses` is deprecated. Packages that use that old, Ruby-esque property are [moving to the new syntax](https://npm1k.org). Many of the most popular packages already have valid `package.json` on GitHub, but are waiting for new substantive revisions to publish a new version.
