### ISSUE TITLE
ENOENT during npm install with npm v3.3.6/v3.3.12 and node v5.0.0

### ISSUE THREAD

**Issue by lencioni** [npm/npm#10260] opened 2015-11-04 17:01 UTC
When running `npm install` with the package.json and npm-shrinkwrap.json in [this gist](https://gist.github.com/lencioni/008ee5374b2af271353e) under npm v3.3.6 or v3.3.12 and node v5.0.0 I get some errors with the following output:

```
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/usr/local/nodejs-5.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! path /var/lib/jenkins/workspace/brigade-jasmine/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/ast-traverse
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/var/lib/jenkins/workspace/brigade-jasmine/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/ast-traverse' -> '/var/lib/jenkins/workspace/brigade-jasmine/node_modules/ast-traverse'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

This seems similar to:
- #10259
- #10236 
- #10229 
- #9633

**Comment by lencioni** [comment] 2015-11-04 17:02
Also, FWIW, I was unable to reproduce this on my Mac--I only see it in our CI jobs (Jenkins).

**Comment by DavidBarishev** [comment] 2015-11-04 18:09
Also , i think it's worth mentioning , its only happening in node 3.x, i was able to install the packages correctly with node 2

**Comment by artingei** [comment] 2015-11-04 18:22
similar problem for me:

937 error Linux 4.2.5-1-ARCH
938 error argv "/usr/bin/node" "/usr/bin/npm" "install"
939 error node v5.0.0
940 error npm  v3.3.10
941 error code EREADFILE
942 error Error extracting /root/.npm/grunt-csswring/1.1.0/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/grunt-csswring/1.1.0/package.tgz'

**Comment by baelter** [comment] 2015-11-05 10:03
+1

**Comment by baelter** [comment] 2015-11-05 10:29
Happens pretty much all the time now...

Workaround is to ```rm -rf node_modules``` and try again....

    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/dot-object/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/glob-parent/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/extend-shallow/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/htmlparser2/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/jade/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/lodash.values/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/mocha/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/randomatic/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/readdirp/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/socket.io-adapter/package.json'
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/anders/Projects/npdc/npdc-gulp/node_modules/streamqueue/package.json'
    npm ERR! Linux 4.2.5-1-MANJARO
    npm ERR! argv "/usr/bin/node" "/home/anders/.npm-packages/bin/npm" "install"
    npm ERR! node v5.0.0
    npm ERR! npm  v3.3.10
    npm ERR! path /home/anders/Projects/npdc/npdc-gulp/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall rename

    npm ERR! enoent ENOENT: no such file or directory, rename '/home/anders/Projects/npdc/npdc-gulp/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug' -> '/home/anders/Projects/npdc/npdc-gulp/node_modules/localtunnel/node_modules/debug'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/anders/Projects/npdc/npdc-gulp/npm-debug.log

**Comment by GerjanOnline** [comment] 2015-11-05 16:37
Did have the same problems today, multiple times. 

`rimraf node_modules` solved it most of the time

**Comment by othiym23** [comment] 2015-11-06 19:44
This is indeed a duplicate of #9633, so I'm going to close this as a dupe (and we're going to get this fixed :soon:).

**Closed by othiym23** 2015-11-06 19:44 UTC
