### ISSUE TITLE
npm3  is it support install like npm2  not dedupe   

### ISSUE THREAD

**Issue by zhoujianlin8** [npm/npm#10562] opened 2015-11-26 09:41 UTC
can i use --no-dedupe to ctr it   (请支持dedupe参数去控制是否进行扁平化处理)

is it support dedupePath (请支持指定模块扁平化处理的目录)

**Comment by XGHeaven** [comment] 2015-11-27 17:45
我能说我没看懂你这句话是说希望npm3支持扁平化还是什么😂

**Comment by zhoujianlin8** [comment] 2015-11-30 08:53
是希望扁平化的支持是可配置的   现在是如果我不需要扁平化如何用参数去除

不同的场景有不同的需求   

现在扁平化默认处理非常好   但是有些场景我们需要控制更多的过程

**Comment by XGHeaven** [comment] 2015-11-30 14:37
这个你可能需要跟作者说一下了，如果你不需要的话，可以尝试降级成2来进行。

**Comment by aredridel** [comment] 2015-11-30 16:42
What is the use-case for the non-flat tree? Why is it needed?

**Comment by martinheidegger** [comment] 2015-12-02 12:13
@aredridel Not sure why it is needed. But my use case is: in my editor it is not comfortable to look for a module if there are hundret(s?) of dependencies flat in one folder (scroll-scroll-grunt-scroll-scroll). 

In regards to others: I also remember that windows does not only have a limit on folder depth but also gets very slow if you have too many files/folders in one folder so I guess that could be an issue too.

**Comment by eddiemonge** [comment] 2015-12-02 23:30
@martinheidegger you shouldnt be scrolling if the list is that long. Your editor should have a search or a quick jump feature. If it doesn't perhaps its time for a better editor?

As for the windows too many things in a folder, what it the threshold for that as the system folders have  a lot of things in them

**Comment by martinheidegger** [comment] 2015-12-03 00:21
@eddiemonge So your answer to this is: we are okay with breaking the scroll-feature, get a tool that works without it?

**Comment by eddiemonge** [comment] 2015-12-03 00:31
No, I'm saying the "breaking the scroll-feature" is a non-issue. It doesn't matter if the structure is flattened, scrolling is a way of life and there are various ways around it. It isn't breaking it because you could list a million top level dependencies and still have to scroll through them. Most of time, you don't even need to look in the node_modules folder. Can you give a use case for it?

**Comment by othiym23** [comment] 2015-12-03 00:38
To answer the original poster's question, `npm@3` is designed to produce flatter, deduplicated install trees by default. This reduces the amount of disk space used by a typical install, as well as making it much less common that Windows users will run up against its well-known limitations with long paths (which, incidentally, is also helpful for users who are running Docker or Vagrant on Windows with shared directories).

@martinheidegger We've had an awful lot of requests from Windows users for the new, flatter installs, and as yet haven't gotten any complaints that the new install algorithm causes load times to be slower. In fact, we have evidence that in [some cases](http://goer.org/Journal/2015/11/npm-3s-flatter-module-tree-makes-babel-much-much-faster.html), flatter trees containing many packages actually _improve_ performance. There are a few people who've run into the issue you have, and while it's a bit inconvenient, I think that in all but extreme cases, the benefits outweigh the costs.

As this _is_ the intended behavior of `npm@3`, and we don't currently have any plans to go back to `npm@2`-style trees, I'm going to close this issue. Thanks for asking though, and thanks to those of you who pitched in to help in Chinese!

**Closed by othiym23** 2015-12-03 00:38 UTC
Labels: support

**Comment by martinheidegger** [comment] 2015-12-03 00:54
@othiym23 Just for clarification: I didn't mean that npm gets slow on windows with a lot of files. Windows Explorer & other browser of the file system do.

**Comment by othiym23** [comment] 2015-12-03 01:09
Sure, and my larger point still holds, I think – for the vast majority of Windows users, the new behavior is somewhere between a significant improvement and an absolute necessity to take npm and Node seriously as first-class citizens in the Windows world. There's been a lot of demand for this particular change, and it's been pretty impassioned.

**Comment by zhoujianlin8** [comment] 2015-12-07 07:12
now npm3  dedupePath is cwd/node_modules by default
 can you support dedupePath to ctrl 

I wrap npm to install modules in a dir  , but i don't install npm by default  , I use user npm to do it , so the problem  come out
