### ISSUE TITLE
I'm trying to install bower for Google Polymer but it's showing me error as follows.

### ISSUE THREAD

**Issue by iamrohitsawai** [npm/npm#13774] opened 2016-08-26 09:57 UTC
```
rohit@rohit-Lenovo-G500:~$ npm install -g bower polyserv
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/home/rohit/.nvm/versions/node/v6.4.0/bin/node" "/home/rohit/.nvm/versions/node/v6.4.0/bin/npm" "install" "-g" "bower" "polyserv"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rohit/npm-debug.log
```

and " /home/rohit/npm-debug.log " this file contains following result:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/rohit/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/home/rohit/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower',
1 verbose cli   'polyserv' ]
2 info using npm@3.10.6
3 info using node@v6.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchPackageMetaData polyserv
9 silly fetchNamedPackageData bower
10 silly mapToRegistry name bower
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'bower',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'bower',
13 silly mapToRegistry   name: 'bower',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/bower
15 silly fetchNamedPackageData polyserv
16 silly mapToRegistry name polyserv
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'polyserv',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'polyserv',
19 silly mapToRegistry   name: 'polyserv',
19 silly mapToRegistry   escapedName: 'polyserv',
19 silly mapToRegistry   name: 'polyserv',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/polyserv
21 verbose request uri https://registry.npmjs.org/polyserv
22 verbose request no auth needed
23 info attempt registry request try #1 at 3:24:24 PM
24 verbose request id 603b2df23d264223
25 http request GET https://registry.npmjs.org/polyserv
26 verbose request uri https://registry.npmjs.org/bower
27 verbose request no auth needed
28 info attempt registry request try #1 at 3:24:24 PM
29 verbose etag "9GZK6CH3XAF07WYBTW7NOMXN9"
30 http request GET https://registry.npmjs.org/bower
31 http 304 https://registry.npmjs.org/bower
32 verbose headers { date: 'Fri, 26 Aug 2016 09:54:30 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   'cache-control': 'max-age=300',
32 verbose headers   etag: '"9GZK6CH3XAF07WYBTW7NOMXN9"',
32 verbose headers   age: '213',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-sin6926-SIN',
32 verbose headers   'x-cache': 'HIT',
32 verbose headers   'x-cache-hits': '8',
32 verbose headers   'x-timer': 'S1472205270.814118,VS0,VE0',
32 verbose headers   vary: 'Accept-Encoding' }
33 silly get cb [ 304,
33 silly get   { date: 'Fri, 26 Aug 2016 09:54:30 GMT',
33 silly get     via: '1.1 varnish',
33 silly get     'cache-control': 'max-age=300',
33 silly get     etag: '"9GZK6CH3XAF07WYBTW7NOMXN9"',
33 silly get     age: '213',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-sin6926-SIN',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-sin6926-SIN',
33 silly get     'x-cache': 'HIT',
33 silly get     'x-cache-hits': '8',
33 silly get     'x-timer': 'S1472205270.814118,VS0,VE0',
33 silly get     vary: 'Accept-Encoding' } ]
34 verbose etag https://registry.npmjs.org/bower from cache
35 verbose get saving bower to /home/rohit/.npm/registry.npmjs.org/bower/.cache.json
36 verbose correctMkdir /home/rohit/.npm correctMkdir not in flight; initializing
37 http 404 https://registry.npmjs.org/polyserv
38 verbose headers { 'content-type': 'application/json',
38 verbose headers   'cache-control': 'max-age=0',
38 verbose headers   'content-length': '2',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   date: 'Fri, 26 Aug 2016 09:54:35 GMT',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   age: '0',
38 verbose headers   connection: 'keep-alive',
38 verbose headers   'x-served-by': 'cache-sin6923-SIN',
38 verbose headers   'x-cache': 'MISS',
38 verbose headers   'x-cache-hits': '0',
38 verbose headers   'x-timer': 'S1472205275.565632,VS0,VE248',
38 verbose headers   vary: 'Accept-Encoding' }
39 silly get cb [ 304, undefined ]
40 verbose get saving undefined to /home/rohit/.npm/registry.npmjs.org/polyserv/.cache.json
41 verbose correctMkdir /home/rohit/.npm correctMkdir not in flight; initializing
42 verbose stack TypeError: Cannot convert undefined or null to object
42 verbose stack     at pickVersionFromRegistryDocument (/home/rohit/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/fetch-package-metadata$
42 verbose stack     at /home/rohit/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
42 verbose stack     at /home/rohit/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
42 verbose stack     at saved (/home/rohit/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
42 verbose stack     at /home/rohit/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
42 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
43 verbose cwd /home/rohit
44 error Linux 4.2.0-35-generic
45 error argv "/home/rohit/.nvm/versions/node/v6.4.0/bin/node" "/home/rohit/.nvm/versions/node/v6.4.0/bin/npm" "install" "-g" "bower" "polyser$
44 error Linux 4.2.0-35-generic
45 error argv "/home/rohit/.nvm/versions/node/v6.4.0/bin/node" "/home/rohit/.nvm/versions/node/v6.4.0/bin/npm" "install" "-g" "bower" "polyser$
46 error node v6.4.0
47 error npm  v3.10.6
48 error Cannot convert undefined or null to object
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment] 2016-08-26 13:46
The problem is that `polyserv` is not a module. Did you mean `bower-polyserv` (One package name)?

**Comment by iamrohitsawai** [comment] 2016-08-28 13:30
Yes. bower-polyserve

**Comment by legodude17** [comment] 2016-08-28 13:32
Does `npm install bower-polyserv` work?

**Comment by iamrohitsawai** [comment] 2016-08-29 14:36
It's worked. Thanks.

**Comment by KenanY** [comment] 2016-08-29 14:38
Closing as resolved.

**Closed by KenanY** 2016-08-29 14:38 UTC

**Comment by iamrohitsawai** [comment] 2016-08-29 14:40
Yes. Yes, my problem is solved. 😊

**Comment by iamrohitsawai** [comment] 2016-10-04 19:45
Hey npm/npm,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Rohit Kiran

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ubQChTsk&invitationId=6189158020463812608&trk=eml-invite_guest-invite_guest-203-india_a&trkEmail=eml-invite_guest-invite_guest-203-india_a-null-0%7Eitvw9y3p%7Ewe



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-itvw9y3p-we&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQE6RCM_g2d-IwAAAVeROno4jGlQxT4owMILQ-EwXbe0Eww1SpKkTe1-Nn25PuT-LND6eLW06t0LhWDn9wtiIqbpJg4oZcZDHJF6RRE6DXkuNeEw7Yso2VHaVQ9aaGRDDwLKG-gj9BZZR1yQ67icARrW1Fqmjqu1hWybOKufbVSPzJw4B0KWA5i4w57-wlgat0zh&eid=0-itvw9y3p-we


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-itvw9y3p-we&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by iamrohitsawai** [comment] 2016-10-04 19:45
Hey npm/npm,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Rohit Kiran

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=5qdnvMK2&invitationId=6189158014273024001&trk=eml-invite_guest-invite_guest-203-india_a&trkEmail=eml-invite_guest-invite_guest-203-india_a-null-0%7Eitvwa1gz%7End



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-itvwa1gz-nd&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGYLerJ823lpwAAAVeROnkCAvWEFhklPPF6Z5fJF7PvL1TTw-ywHedDwlZNnCcawiDvGLKXeuhnU9W9YnKA4viiZWpjUsHNzlmcS0EQTMyMKgro92CAlmBllsOYg4CGhYzWwQJD0o5k2raE8PKZzMWGS-c0uJ1aD1NUlWRyb5xATF5UfsZHwabQ_TrNcoguDbPv&eid=0-itvwa1gz-nd


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-itvwa1gz-nd&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by iamrohitsawai** [comment] 2016-10-04 19:45
Hey npm/npm,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Rohit Kiran

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Ubq0Ql5h&invitationId=6189158013878759426&trk=eml-invite_guest-invite_guest-203-india_a&trkEmail=eml-invite_guest-invite_guest-203-india_a-null-0%7Eitvwae65%7Ed0



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-itvwae65-d0&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHWXbF-YsgdkgAAAVeROtI6S1hA2UmSOAnJfgfFokHXhpBtvQpZjEtn-ixZyqR0ZG1wiELNSb8aVxBKVk5v2gTFANrK_R3i7UH4dD-Ri7Engn76EsIwk5adAw9fPgNhkYPcQhwePLypv_oyL8ExAhfLU6cWPkzgtnePOBzpBCOUST8q8TYTtk7woTJWG8TVfdAv&eid=0-itvwae65-d0


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-itvwae65-d0&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by legodude17** [comment] 2016-10-04 23:49
What? What is that?
