### ISSUE TITLE
npm search doesn't work

### ISSUE THREAD

**Issue by yuriihabrusiev** [npm/npm#14051] opened 2016-09-23 09:32 UTC
#### I'm opening this issue because:

npm is crashing.

#### What's going wrong?

Running `npm search hyperterm` and getting this error:
```
❯ npm search hyperterm
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "search" "hyperterm"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7

npm ERR! Cannot read property '_updated' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

   56555 ms: Mark-sweep 997.5 (1314.0) -> 970.8 (1296.1) MB, 945.0 / 0.0 ms [allocation failure] [GC in old space requested].
   57545 ms: Mark-sweep 970.8 (1296.1) -> 970.8 (1300.1) MB, 990.6 / 0.0 ms [allocation failure] [GC in old space requested].
   58611 ms: Mark-sweep 970.8 (1300.1) -> 970.7 (1260.1) MB, 1066.0 / 0.0 ms [last resort gc].
   59669 ms: Mark-sweep 970.7 (1260.1) -> 970.6 (1254.1) MB, 1058.1 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1b45660cfb51 <JS Object>
    1: fromString(aka fromString) [buffer.js:195] [pc=0x2c1db64c9870] (this=0x1b4566004381 <undefined>,string=0x7f5b4eec6e9 <Very long string[201830218]>,encoding=0x1b45660dd329 <String[4]: utf8>)
    2: from [buffer.js:95] [pc=0x2c1db64477c2] (this=0x59f4eaa5d71 <JS Function Buffer (SharedFunctionInfo 0x3fa4764f61f9)>,value=0x7f5b4eec6e9 <Very long string[201830218]>,encodingOrOffset=0x1b45660...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
13: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>, v8::internal::Isolate*) [/usr/local/bin/node]
14: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x2c1db5f092a7
fish: 'npm search hyperterm' terminated by signal SIGABRT (Abort)
```

### supporting information:

 - `npm -v` prints: 3.10.7
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X 10.11.6
 - No network issues.
 - No container.

**Comment by KenanY** [comment] 2016-09-23 13:38
Closing as a duplicate of https://github.com/npm/npm/issues/12619.

**Closed by KenanY** 2016-09-23 13:38 UTC

**Comment by KenanY** [comment] 2016-11-08 20:08
[Fixed in `npm@4`](https://github.com/npm/npm/blob/4639b0eed8db92c8872011d4affd10c498b3b9db/CHANGELOG.md#search-rewrite-breaking)
