### ISSUE TITLE
Npm scripts set `TMPDIR` environment variable

### ISSUE THREAD

**Issue by kumavis** [npm/npm#4531] opened 2014-01-22 21:52 UTC
I found this bug while using [`os.tmpdir()`](https://github.com/joyent/node/blob/5fcd6e40385f45bc9091689337a7ab531861ba19/lib/os.js#L51-L54)

When executing as root on OSX, there is no explicit tmpdir provided from the environment variables. When using `os.tmpdir()`, node correctly falls back to '/tmp'. However when running scripts via npm, it seems that the environment variable `TMPDIR` is set to the cwd when undefined. This causes `os.tmpdir()` to incorrectly return the cwd as the tmp directory.

in my `package.json`
```json
"scripts": {
    "test": "echo $TMPDIR"
  },
```

```bash
npm test
#=> correct temp dir
sudo npm test
#=> current working directory (??)
node -e "console.log(process.env.TMPDIR)"
#=> correct temp dir
sudo node -e "console.log(process.env.TMPDIR)"
#=> undefined
```
another test, in my `package.json`
```json
"scripts": {
    "test": "node -e \"console.log(require('os').tmpdir())\""
  },
```
```bash
npm test
#=> correct temp dir
sudo npm test
#=> current working directory (??)
node -e "console.log(require('os').tmpdir())"
#=> correct temp dir
sudo node -e "console.log(require('os').tmpdir())"
#=> '/tmp'
```

my system (osx 10.9.1):
```
node -v
#=> v0.10.22
npm -v
#=> 1.3.14
```

**Comment by CatTail** [comment] 2015-03-24 08:14
Run into the same issue. It's wired to set current working directory as `TMPDIR`

**Comment by kumavis** [comment] 2015-03-24 20:12
woah blast from the past

**Comment by Starefossen** [comment] 2015-04-15 11:57
I got hit by this bug as well!

**Comment by nylen** [comment] 2015-05-27 19:54
@kumavis I don't believe this is a bug, or it is at least the intended behavior:

- [`lifecycle.js`#L55-57](https://github.com/npm/npm/blob/v2.11.0/lib/utils/lifecycle.js#L55-L57)
- introduced in [`d7dcace`](https://github.com/npm/npm/commit/d7dcacea6f17437fd88321987ca6aa8fe3c017d8#diff-8c44327c5a50975dee6ded9e9789e96eR26) and documented in [`1431a63`](https://github.com/npm/npm/commit/1431a6349b8f6424d2187b96e5716b75cb03e6a5#diff-8c44327c5a50975dee6ded9e9789e96eR33) (early 2011)
- refactored a little in [`56a6dd3`](https://github.com/npm/npm/commit/56a6dd3ad00e6efcc1b1dfb6b84eb21eca82352d#diff-8c44327c5a50975dee6ded9e9789e96eL40) (mid 2011)

**Comment by kumavis** [comment] 2015-05-27 22:09
interesting...
not sure what to recommend here.
this is not really an issue for me, so I don't mind if it gets closed.

**Comment by nylen** [comment] 2015-05-28 20:34
only you can <s>prevent forest fires</s> close out your own issue!

**Comment by othiym23** [comment] 2015-05-28 20:40
Or, you know, I can do it. Closing as behaving as intended. If this is causing problems for your build scripts, @kumavis, you can explicitly set `TMPDIR` in the environment in which the command is running. Hope this works well enough for you!

**Closed by othiym23** 2015-05-28 20:40 UTC
Labels: bug

**Comment by kumavis** [comment] 2015-05-28 22:38
forgot to mention: keep being awesome

**Comment by othiym23** [comment] 2015-05-28 22:47
Will do! :+1: Thank you!

**Comment by erykpiast** [comment] 2015-06-03 10:10
```
export TMPDIR="/tmp"
npm install something
```

And `process.env.TMPDIR` it's still `/input/node_modules/something`...

**Comment by coffenbacher** [comment] 2016-01-05 00:59
Wow, I'm seeing the same as @erykpiast - it actually blows away my environment's setting to replace the value with the CWD. Crazy.

**Comment by iameli** [comment] 2016-05-06 07:18
Just ran into this. Also in a docker container. Pretty confused.

**Comment by develar** [comment] 2016-05-19 16:38
> Pretty confused.

No words. I spend hours to make npm working. A lot of strange bugs. And all closed as intended or as won't fix. No words. But no way to get rid of npm :(

**Comment by develar** [comment] 2016-05-19 16:39
> you can explicitly set TMPDIR in the environment in which the command is running. 

It doesn't work. Doesn't work. NPM must work as node does, without any magic. Damn.

**Comment by sheerun** [comment] 2016-06-15 19:28
@othiym23 Please re-open. `require('os-tmpdir)()` returns current directory instead of `/tmp` when running with `sudo npm test`... (sudo clears TMP env variables and npm sets TMPDIR instead).

The scripts runs as intended if you run it with node itself.

**Comment by watilde** [comment] 2016-06-16 20:56
To not change the value of the environment variable `process.TMPDIR` and keep the current behavior, we can update the line in `lifecycle.js` to the following, doesn't it?
```diff
--    if (!npm.config.get('unsafe-perm')) env.TMPDIR = null
++    if (!npm.config.get('unsafe-perm')) npm.config.set('tmp', wd)
```

**Comment by whitecolor** [comment] 2017-01-09 14:14
this just npm =( use yarn.

**Comment by paulodiovani** [comment] 2017-01-13 19:17
Please, reopen.
For the ones using Docker this is a big issue.

**Comment by paulodiovani** [comment] 2017-01-13 19:32
For Docker, we can run with `npm start --unsafe-perm`

**Comment by develar** [comment] 2017-01-13 20:03
@paulodiovani Just set `npm config set unsafe-perm true` (example: https://github.com/electron-userland/electron-builder/blob/master/docker/7/Dockerfile)

**Comment by whitecolor** [comment] 2017-01-13 20:07
`npm config set unsafe-perm true` this will make `os.tmpdir()` come true?
