### ISSUE TITLE
Caught "TypeError: Cannot read property 'debug' of undefined" when II'm installing parsoid

### ISSUE THREAD

**Issue by tommypaopao** [npm/npm#14700] opened 2016-11-22 07:52 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I am installing parsoid on win7 virtualmachine, I have caught the error below:

56767 silly cache add parsed spec Result {
56767 silly cache add   raw: 'write-file-atomic@https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56767 silly cache add   scope: null,
56767 silly cache add   escapedName: 'write-file-atomic',
56767 silly cache add   name: 'write-file-atomic',
56767 silly cache add   rawSpec: 'https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56767 silly cache add   spec: 'https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56767 silly cache add   type: 'remote' }
56768 silly mapToRegistry name write-file-atomic@https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz
56769 silly mapToRegistry using default registry
56770 silly mapToRegistry registry https://registry.npmjs.org/
56771 silly mapToRegistry data Result {
56771 silly mapToRegistry   raw: 'write-file-atomic@https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56771 silly mapToRegistry   scope: null,
56771 silly mapToRegistry   escapedName: 'write-file-atomic',
56771 silly mapToRegistry   name: 'write-file-atomic',
56771 silly mapToRegistry   rawSpec: 'https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56771 silly mapToRegistry   spec: 'https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56771 silly mapToRegistry   type: 'remote' }
56772 silly mapToRegistry uri https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz
56773 verbose addRemoteTarball https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz not in flight; adding
56774 verbose addRemoteTarball [ 'https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz',
56774 verbose addRemoteTarball   null ]
56775 verbose stack TypeError: Cannot read property 'debug' of undefined
56775 verbose stack     at C:\Users\joe\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:35:40
56775 verbose stack     at Array.filter (native)
56775 verbose stack     at inflateShrinkwrap (C:\Users\joe\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:34:49)
56775 verbose stack     at C:\Users\joe\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:16
56775 verbose stack     at C:\Users\joe\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
56775 verbose stack     at zalgoSafe (C:\Users\joe\AppData\Roaming\npm\node_modules\npm\node_modules\dezalgo\dezalgo.js:20:10)
56775 verbose stack     at finalize (C:\Users\joe\AppData\Roaming\npm\node_modules\npm\node_modules\realize-package-specifier\index.js:39:5)
56775 verbose stack     at C:\Users\joe\AppData\Roaming\npm\node_modules\npm\node_modules\realize-package-specifier\index.js:22:20
56775 verbose stack     at C:\Users\joe\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:276:29
56775 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
56776 verbose cwd C:\Users\joe\parsoid\parsoid
56777 error Windows_NT 6.1.7600
56778 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\joe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
56779 error node v6.9.1
56780 error npm  v4.0.3
56781 error Cannot read property 'debug' of undefined
56782 error If you need help, you may report this error at:
56782 error     <https://github.com/npm/npm/issues>
56783 verbose exit [ 1, true ]

Could you please help to have a look at this issue?

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win7 VirtulMachine
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ x ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ x ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by tommypaopao** [comment] 2016-11-22 07:55
[npm-debug.log.txt](https://github.com/npm/npm/files/605769/npm-debug.log.txt)

**Comment by KenanY** [comment] 2016-11-22 14:42
I believe this is a duplicate of https://github.com/npm/npm/issues/14427. Fix should be out next Thursday, if I recall correctly.

**Closed by KenanY** 2016-11-22 14:42 UTC

**Comment by tommypaopao** [comment] 2016-11-23 06:09
Thanks Kenan, Is there any workaround for this issue? Or I have to wait for the fix?

**Comment by KenanY** [comment] 2016-11-23 16:14
@tommypaopao You can downgrade to `npm@3` for the time being.
