### ISSUE TITLE
How ignore this messgae "npm update check failed"? 😡😡😡 

### ISSUE THREAD

**Issue by retyui** [npm/npm#18566] opened 2017-09-18 13:22 UTC
Config property or other the method?
![image](https://user-images.githubusercontent.com/4661784/30543919-68476474-9c8d-11e7-8821-00754fe6b3e2.png)

**Comment by kenany** [comment] 2017-09-18 13:52
Perhaps this can be considered a duplicate of https://github.com/npm/npm/issues/17453?

**Closed as completed** 2018-02-26 14:04 UTC
