### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#13729] opened 2016-08-22 20:14 UTC
#### I'm opening this issue because:

npm is producing an incorrect install.
#### What's going wrong?

i can't install my app. npm install just hangs at the "fetch metadata" stage.
#### How can the CLI team reproduce the problem?

https://gist.github.com/jonathanong/bd88868a6582abb3bfe8e8d6d974b3cc

i ran `npm i -dd`
### supporting information:
- `npm -v` prints: `v3.10.6`
- `node -v` prints: - `v6.4.0`
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X
- Network issues:
  - Geographic location where npm was run: Santa Monica, CA
  - Frontier FiOS
  - No proxy or VPN
- Container: None

**Comment by jonathanong** [comment] 2016-08-22 20:29
actually seems to be happening with any of my projects. it will also look something like:

```bash
⸨    ░░░░░░░░░░░░░░⸩ ⠦ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/validator
```

**Comment by hughes** [comment] 2016-08-22 20:36
I've been getting a lot of 504s from https://www.npmjs.org/ today, maybe related? The registry subdomain seems unaffected though

**Comment by jonathanong** [comment] 2016-08-22 20:41
it seems to work if i install a single package at a time, ex. `npm i -g npm`

**Comment by jonathanong** [comment] 2016-08-22 20:48
tried strongloop's and nodejitsu's registries, but they don't work. surprisingly, http://registry.cnpmjs.org worked for me, but it was pretty slow.

**Comment by martinheidegger** [comment] 2016-08-23 03:08
@jonathanong It might help to see the output with `--verbose`

**Comment by jonathanong** [comment] 2016-08-23 03:13
@martinheidegger the gist contains a 4k log file

**Comment by jonathanong** [comment] 2016-08-23 03:14
waht's weird is that it works when i got home. maybe Frontier FiOS is throttling npm at work or something o.O

**Comment by ndrwhr** [comment] 2016-08-23 17:05
Had this issue yesterday, but it turned out it was because the connection to our internal npm repo was being blocked.

**Comment by toddw** [comment] 2016-08-24 17:23
I had this issue, turned out my `~/.npmrc` file was set to proxy through a private proxy from work and it didn't work when I was not on the VPN.

**Comment by jonathanong** [comment] 2016-08-24 17:30
i'm not seeing this anymore. no idea what caused it.

**Comment by tHBp** [comment] 2016-08-25 08:46
Having similar issue as with @jonathanong with a lot of npm packages. It is persisting still. Any alternative repositories that might work?

**Comment by varrant** [comment] 2016-09-08 16:09
Having similar issue as with @jonathanong with a lot of npm packages. It is persisting still. Your reply will be higly appreciated!

**Comment by gunar** [comment] 2016-09-08 18:25
Mine fixed by itself today. Before that, the hacky temporary solution I found was to use [npm-install-que](https://www.npmjs.com/package/npm-install-que). Hope it helps someone.

**Comment by powerpbx** [comment] 2017-01-07 18:35
Having this problem right now

**Comment by legodude17** [comment] 2017-01-09 23:11
Anyone still having this issue?

**Comment by holaneph** [comment] 2017-01-10 04:19
@legodude17 , me.
node -v: 7.4.0
npm -v : 4.0.5

any suggestions?

**Comment by legodude17** [comment] 2017-01-10 18:07
@holaneph do you have a proxy or VPN or spotty internet.

**Comment by holaneph** [comment] 2017-01-10 19:06
@legodude17 you're right. I disabled windows firewall and that fixed the problem.
Thanks!

**Comment by mlent** [comment] 2017-01-10 20:32
Having this problem. Internet is fine (someone sitting next to me on the same connection had no issues). No VPN. 

I started installing packages one-by-one by reading the package.json. I also tried to do them by name, like `npm install axios babel-polyfill`, but that also hung. After every other depedency, I'm still not able to install `google-cloud`. Console output:

```
[||||||||               ] / loadRequestDeps: sill install loadAllDepsIntoIdealTree
```

Was able to get around it by using `npm install @google-cloud/datastore` directly.

**Comment by legodude17** [comment] 2017-01-10 21:03
@mlent do you have a proxy?
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by mlent** [comment] 2017-01-10 21:07
❯   npm config get registry
https://registry.npmjs.org/

❯   npm config get http-proxy
undefined

❯   npm config get https-proxy
null

Working theory is that it actually hung because of trying to install `google-cloud`, which comprises several repositories. Once I replaced this in the package.json, I was able to run npm install successfully (after having installed each dependency one by one).

I will try to replicate this error/fix and let you know if that is in fact the case. Doesn't explain the root cause of course. But interesting that `npm install a b` doesn't work, just as `npm install google-cloud` doesn't work. Seems an issue with "trying" to install more than one thing at once?

Thanks for your help.

**Comment by legodude17** [comment] 2017-01-10 21:14
My first guess would be that it is overstressing your network with too many requests...

**Comment by mlent** [comment] 2017-01-10 21:45
By "my network" do you think this is on my local machine? As i mentioned, someone sitting next to me on the same network (but running a linux machine instead of mac os) had no issues at all.

I will try to start over tomorrow, as I have to reinstall everything for other reasons (permissions issues, unrelated to javascript dependencies). So I will let you know if I can replicate it before/after with the google-cloud adjustment.

**Comment by rubenmartin** [comment] 2017-01-12 14:50
@mlent please follow this fix: http://stackoverflow.com/a/41208021/4389370

I had the same issue and now It works for me.

I just 

`
sudo npm install -g yarn
yarn install
`
This 2 sentences fix your problem.

Now I can use npm install without any problem in my project again.

**Comment by faparikh** [comment] 2017-02-08 14:32
I tried all the possible solutions here but nothing work so took backup of .npm file and rerun npm install. 
It worked

**Comment by LXeightCo** [comment] 2017-02-25 03:56
I had to delete node.js and npm and install all over again. 
I was easier and faster.
*Worked
http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by pamontep** [comment] 2017-03-06 15:09
Pls try

`npm cache clean`
`npm install`

**Comment by vivekimsit** [comment] 2017-03-06 17:42
I confirm it, it hangs randomly while fetching any package.

**Comment by Choyhow** [comment] 2017-03-09 08:17
after try 
`npm cache clean
npm install ` it still hang.

npm -v print 3.10.10
node -v print v6.10.0

**Comment by hugows** [comment] 2017-03-09 15:38
For the record: my npm install command was hanging because the git protocol is blocked by the firewall. I had to workaround with something like:

git config --global url."https://".insteadOf git://

(http://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that)

**Comment by jebricker** [comment] 2017-03-14 18:11
I was having the problem running from Windows.  I had to run the cmd window as Admin and clean the cache before each install.

**Comment by rafialikhan** [comment] 2017-04-01 16:30
This is still an issue now most of the time, its a hit or miss like @jebricker said. Sometimes it proceeds but its damn slow, other times it doesn't and just hangs even after an hour of running. 

Tried - npm config set registry="http://registry.npmjs.org" but not convincing as before where npm installs just worked like a charm, now always seems like stuck at `fetchMetadata: sill mapToRegistry uri http://registry.npmjs.org/<some package>` 

```
NPM Version: 4.4.1
OS: Mac OS X El Capitan
Node Version: v6.10.0
```

So followed @rubenmartin and installed yarn which took sometime using`npm install -g yarn` but once installed, the `yarn install` really worked super fast. 

Is it time for node developers to move from npm to yarn for installations??

**Comment by sameer-awate** [comment] 2017-05-05 06:43
In my case it was wrong proxy configuration by default created in .npmrc file. I could figure it out using `npm config list` command. So, the solution was to remove those unwanted `proxy` and `https-proxy` settings from **.npmrc**. In fact, there was no other useful setting in there, hence I deleted the .npmrc file and the installation went ahead without any issues. Clearly, it has to do with your proxy settings, so you might want to confirm associated settings for you.

**Comment by kaizhu256** [comment] 2017-05-06 07:35
on my macbook air (using old maverick with node lts6), npm install always hangs when i try to install from github repo : /

$ npm -v 4.5.0

**Comment by oussamaABID** [comment] 2017-05-16 20:44
http://luxiyalu.com/how-to-remove-all-npm-proxy-settings/

**Comment by placha433** [comment] 2017-05-18 17:03
Have you tried to disable temporarily your antivirus and firewall ? In my case, it solved the problem.

**Comment by SoorajChandran** [comment] 2017-05-27 17:40
Facing this issue right now :/ Any fixes ? Tried all the above, but failed.

**Comment by legodude17** [comment] 2017-06-02 21:48
Have you updated to the latest version?

**Comment by SoorajChandran** [comment] 2017-06-14 10:51
Yes I'm already on the latest version

**Comment by SoorajChandran** [comment] 2017-06-14 11:09
After weeks of searching and researching this solved it for me finally:

`brew update && brew upgrade node && npm install -g npm` 

P.S: I'm pretty sure that I have updated it before too. But it seems like magic.

**Closed** 2017-06-19 03:42 UTC
Labels: bot-closed, support

**Comment by paynd** [comment] 2017-06-27 20:58
I've got the same issue. 
Using [nvm](https://github.com/creationix/nvm) solved this issue.

**Comment by samanshahmohamadi** [comment] 2017-07-22 21:41
Cleaning the .npm and .staging directories just solved my problem.
`yes|rm /root/.npm/* -R`
`yes|rm /path/to/node_modules/.staging/* -R`
`npm install`

**Comment by jpatel3** [comment] 2017-07-24 14:32
Tried above suggestions, It seems to be hanging on random packages every time I try to install it. Even --verbose doesn't really give any specific error. It gets stuck on a line `fetchMetadata: sill pacote range manifest for <pacakge name> fetched in <x>ms`

**Comment by jerradpatch** [comment] 2017-09-21 01:58
I got this thing to work. It was a git issue. I figured this out by going to another directory and performing the npm install, and it did hang on "npm Verb afterAdd' for some time (5 minutes). It did eventually install. Once installed, I noticed that after the verb it was hanging on was "git clone --template=/.......". This prompted me to delete my ./.git folder and ./.gitIgnore. (we are using SVN anyway, I know its awful).

In summery:
rm -rf /tmp/npm-* ~/.npm ./.git ./.gitignore
(I did not delete the node_modules folder)
npm cache clean
npm install -f --verbose git+https://........

hope it helps

**Comment by harsha499** [comment] 2017-10-13 17:00
Facing same issue, it was working earlier, but suddenly it got handled every time,
fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/zone.js

**Comment by hashmachine** [comment] 2017-10-14 20:37
Same issue.. Tried everything. Nothing Works..

**Comment by jerradpatch** [comment] 2017-10-14 22:16
In my experience, my issue was due to the auto merging feature of npm using git. Maybe try switching to a tmp folder then do an npm install with same package.json, or try removing packages you suspect to be using git via npm and see if the install completes. GL

**Comment by hashmachine** [comment] 2017-10-16 07:55
Switched to yarn.. No issues, whatsoever. Can't bang head whole day coz of NPM .

**Comment by kaizhu256** [comment] 2017-10-16 09:27
sorry for ranting, but how can npmjs.com be so **incompetent**?  unstable npm-install is a primary reason for javascript-fatigue, starting with v3's misguided flat dependency-resolution feature which never should have shipped (https://docs.npmjs.com/how-npm-works/npm3).

its bad enough now, most developers dread running npm-install on an existing web-project for fear of breaking it.

**Comment by judepereira** [comment] 2017-10-22 13:55
Yarn works.

**Comment by AleksandarSavic95** [comment] 2017-11-27 14:51
I had the same issue and the problem was that I didn't set the proxy correctly.
I was typing `npm set config proxy http://x.y:port` instead of `npm config set proxy http://x.y:port` (notice the order of "**set**" and "**config**" words).
After that, npm install ran OK.

**Comment by djmills** [comment] 2018-01-18 15:22
I had this issue after setting proxy, setting registry to http://registry.npmjs.org instead of https fixed it.

npm set registry http://registry.npmjs.org/

**Comment by gillettm** [comment] 2018-01-28 06:58
I am not very experienced with node.js and npm, but here are a few observations :

I have macOS highSierra OSX 10.13.2.

I never had these problems then all of a sudden I had this problem whenever I tried to install anything with multiple packages. It would hang for several seconds then I'd get some variation of :

pm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.5.2.tgz failed, reason: connect ETIMEDOUT 151.101.112.162:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

The only thing I can think of to cause this problem is I tried this: "npm config set prefix ~/npm" - nothing worked correctly afterwards, but it could be a coincidence, since the problem persisted after completely removing node and npm and installing nvm.

It took me over a week to fix it. Tried everything. After completely removing node and npm and installing nvm, I tried all the suggested config changes, although I have no proxy, registry was set correctly, etc.

This is what finally works:

npm set maxsockets 3

I also noticed that by changing maxsockets, it comments out : "maxsockets = 50" in the default config (wherever that is ?) and creates : ~/.nprmc containg only :

maxsockets = 3

A weird thing is I could set it back to 50, which is the default, and things which wouldn't install before,  now would install if they had around 60 packages or so, but yeoman with ~400 packages still failed at "maxsockets = 50", but worked at 3. I did not fine tune the number of sockets.

I found "npm config ls -l" was useful for kind of seeing what's going on.

**Comment by skozin** [comment] 2018-01-31 14:26
Seeing similar issue, reported to https://github.com/npm/npm/issues/18448#issuecomment-361945515.

**Comment by kimjanssens** [comment] 2018-02-21 09:33
My fetchMetadata also got stuck after running `npm i` and it started by printing out

> Enter passphrase for key '/Users/username/.ssh/id_rsa'

I thought this was an issue with my npm but in the end all I had to do was `ssh-add`

**Comment by rodrigodata** [comment] 2018-02-26 18:14
I don't know what the problem originally was, but I sorta fixed. It only took to me uninstall node from my machine e install the same version again. Then `npm i` and it worked. This already happened to me 3x times.

**Comment by PetKatt** [comment] 2018-03-12 00:18
For me `yarn install` fixed that problem

**Comment by wgebczyk** [comment] 2018-03-18 20:06
I'm experiencing this issue also.
OS: Windows 10 - up to date
npm info using npm@5.7.1
npm info using node@v9.8.0

Node JS reports timeout on fetching the data.
When processing of "npm i" command "hungs", I can observe:
- CPU for process node.exe is 0%
- Memory slowly increases with every second
- Sometimes it "un hung" and I'm getting:
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning ECONNRESET: request to http://registry.npmjs.org/acorn failed, reason: read ECONNRESET
npm WARN registry Using stale package data from http://registry.npmjs.org/ due to a request error during revalidation.
- Clearly node.exe is DOING SOMETHING. Sometimes it is able to finish this "thing" and it reports warning
- Sometimes it takes "too much???" and ends with (at end of comment)

I'm rather sure that there is bug in npm or node.
Any suggestion how to debug/diagnose what da heck this crap is doing during that time?
It takes a few minutes, so I can attach and see what is going on there?


npm http fetch GET 304 https://registry.npmjs.org/alphanum-sort 78ms (from cache)
npm verb type system
npm verb stack FetchError: request to https://registry.npmjs.org/amdefine failed, reason: read ECONNRESET
npm verb stack     at ClientRequest.req.on.err (<cut>\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm verb stack     at ClientRequest.emit (events.js:180:13)
npm verb stack     at TLSSocket.socketErrorListener (_http_client.js:394:9)
npm verb stack     at TLSSocket.emit (events.js:180:13)
npm verb stack     at emitErrorNT (internal/streams/destroy.js:64:8)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:114:19)
npm verb Windows_NT 10.0.16299
npm verb argv "C:\\Program Files\\nodejs\\node.exe" ... <cut irrelevant part>
npm verb node v9.8.0
npm verb npm  v5.7.1
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/amdefine failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]

**Comment by wgebczyk** [comment] 2018-03-18 20:08
When in "hung" it shows:
/ loadIdealTree:loadAllDepsIntoIdealTree: http fetch GET 200 http://registry.npmjs.org/assert 264875ms (from cache)
What exactly this number mean? 4.5 min to get from cache???

AND

entries around that line are:
npm http fetch GET 200 http://registry.npmjs.org/assert 264875ms (from cache) <-- the one from hung time
npm http fetch GET 200 http://registry.npmjs.org/async 127911ms (from cache)

AND

when it succeeds, the longest times for each "fetch" are weird and similar:
npm http fetch GET 200 http://registry.npmjs.org/acorn 127752ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/acorn 127769ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/async 127911ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/bn.js 127818ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/clone 127856ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/cssesc 127776ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/debug 127749ms (from cache)

npm http fetch GET 200 http://registry.npmjs.org/arrify 264881ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/assert 264875ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/chalk 264880ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/cliui 270897ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/color 264940ms (from cache)

Isn't the case where there is some strange multithreading when producer of some event emits faster notification than consumer is notified and consumer waits with timeout for notification?
Second set clearly waits twice as much as the first set.

**Comment by jandre3000** [comment] 2018-04-11 08:38
The only thing that works for me is waiting for `npm install` to fail, then looking at which package it failed on, and adding that package to the npm cache manually with `npm cache add [url of failed package]`. 

So if it fails with  
```
npm ERR! network request to https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.5.2.tgz failed, reason: connect ETIMEDOUT 
```
I then add that package to the npm cache manually with
```
npm cache add https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.5.2.tgz
```
and repeat a bunch of times until all the hanging packages have been added to the cache. Then it installs successfully.

**Comment by farhanaslamvbase** [comment] 2018-05-08 15:24
i changed my network connection (internet connection) it works for me through simple npm install.

**Comment by valgaze** [comment] 2018-05-08 22:01
Checklist for ssh dependencies using a "private" github organization (swap out *"secretgithub.yourfirm.com"* with your organization's private github URL if applicable):


- [ ] Dependency follows this syntax in package.json:
 
```json
"bongo": "git+ssh://git@secretgithub.yourfirm.com/CTAO-XD-SERVER/bongo.git
```

- [ ] Check your wifi/VPN

- [ ] Create a [new SSH Key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key) and [add it to your github account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)

- [ ] Run the following commands

```sh
ssh-keygen -R secretgithub.yourfirm.com

ssh-keyscan -t rsa secretgithub.yourfirm.com  >> ~/.ssh/known_hosts
```

**Comment by jsdevtom** [comment] 2018-05-19 06:44
Proxy is most likely the issue: https://stackoverflow.com/a/30373440/5950725. This solved my problem

**Comment by Amin52J** [comment] 2018-05-31 11:39
I was getting the same issue while using a VPN, disabling the VPN solved the issue.

**Comment by karljv** [comment] 2018-06-18 18:31
Btw, this happens, when your NPM version is old and node version is too new, like npm 3.4 vs node 10, it did not work for me.

What I did was install nvm, downgrade to node 6.0 and the problem dissappeared.

**Comment by lukepighetti** [comment] 2018-07-09 14:27
I had to allow the git port in my firewall settings.
