### ISSUE TITLE
publish Failed PUT 500

### ISSUE THREAD

**Issue by leizongmin** [npm/npm#8264] opened 2015-05-14 04:52 UTC
I try to publish a package but failed, here is the detail:

```
$ npm publish
npm ERR! publish Failed PUT 500
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.3
npm ERR! code E500

npm ERR! unexpected status code: 401 : lei-utils
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /user/xxx/lei-utils/npm-debug.log
lei-book:lei-utils glen$ npm publish
npm ERR! publish Failed PUT 500
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.3
npm ERR! code E500

npm ERR! unexpected status code: 401 : lei-utils
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /user/xxx/lei-utils/npm-debug.log
```

**Comment by spelufo** [comment] 2015-05-22 09:17
Same thing here.
```
npm ERR! publish Failed PUT 500
npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E500

npm ERR! unexpected status code: 401 : dager
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/santiago/prog/js/15/dager/npm-debug.log
```

npm-debug.log:
```
18 silly publish   _from: '.' }
19 silly mapToRegistry name dager
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/dager
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /home/santiago/.npm/cache/dager/1.0.1/package.tgz
25 verbose request uri https://registry.npmjs.org/dager
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 06:12:27
28 verbose request id bfafc7248a09a354
29 http request PUT https://registry.npmjs.org/dager
30 http 500 https://registry.npmjs.org/dager
31 info retry will retry, error on last attempt: Error: unexpected status code: 401 : dager
32 info attempt registry request try #2 at 06:12:38
33 http request PUT https://registry.npmjs.org/dager
34 http 500 https://registry.npmjs.org/dager
35 info retry will retry, error on last attempt: Error: unexpected status code: 401 : dager
36 info attempt registry request try #3 at 06:13:39
37 http request PUT https://registry.npmjs.org/dager
38 http 500 https://registry.npmjs.org/dager
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '39',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Fri, 22 May 2015 09:13:44 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-jfk1026-JFK',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1432286023.689498,VS0,VE554' }
40 verbose request invalidating /home/santiago/.npm/cache/registry.npmjs.org/dager on PUT
41 error publish Failed PUT 500
42 verbose stack Error: unexpected status code: 401 : dager
42 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
42 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
42 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:344:22)
42 verbose stack     at Request.emit (events.js:110:17)
42 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1239:14)
42 verbose stack     at Request.emit (events.js:129:20)
42 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1187:12)
42 verbose stack     at IncomingMessage.emit (events.js:129:20)
42 verbose stack     at _stream_readable.js:908:16
42 verbose stack     at process._tickCallback (node.js:355:11)
43 verbose statusCode 500
44 verbose pkgid dager
45 verbose cwd /home/santiago/prog/js/15/dager
46 error Linux 3.16.0-33-generic
47 error argv "/usr/bin/node" "/usr/bin/npm" "publish"
48 error node v0.12.2
49 error npm  v2.7.4
50 error code E500
51 error unexpected status code: 401 : dager
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

**Comment by spelufo** [comment] 2015-05-22 09:21
I think this is a duplicate of #7931. Try runing `npm login` before `npm publish`. It worked for me.

**Comment by leizongmin** [comment] 2015-05-24 02:07
I think the `npm` should print a more friendly message, such as `please run "npm login" before publishing a package`

**Comment by Volox** [comment] 2015-05-26 14:00
+1

**Closed** 2017-06-17 02:57 UTC
Labels: bot-closed, registry, support
