### ISSUE TITLE
Specify package.json

### ISSUE THREAD

**Issue by caffinatedmonkey** [npm/npm#5008] opened 2014-04-04 13:56 UTC
Add support to specify a json file to use as the `package.json` file with a flag. See this [StackOverflow question] for a possible use case.

[stackoverflow question]: http://stackoverflow.com/questions/22700317/npm-install-from-github-in-specific-environment

**Comment by othiym23** [comment] 2016-07-01 20:47
1. The npm control file is, and always will be, named `package.json`. This isn't going to change for a whole bunch of reasons, starting the design of the Node.js module loader, going through to the scale of the current npm ecosystem. I know the discussion moved on from this, but I wanted to be clear.
2. The problem with re-reading `package.json` after lifecycle scripts execute is that it's expensive, which means that adding this functionality would also mean slowing down the performance of the CLI (which could potentially be mitigated with some clever hacking, but it's still going to require significantly more filesystem activity than there is today). That said, either the CLI supports this or it doesn't – there's not a lot of room in-between, and it doesn't even feel like a feature. If enough people believe the CLI should do this, it's a bug, and not a feature request.
3. The discussion on this issue has left me in the dark about what, exactly, the problem is that y'all were trying to solve when asking for this behavior. I see a desire to run a bunch of packages' tests from the install of a single package, and some other _strategies_. What I'd like to see are some clearly enumerated problems to be solved.

Towards that end, I'm going to close this issue and suggest that those of you who still have a desire to get some of your problems solved open up new issues with specific descriptions of what you're trying to do and how npm gets in its way (without worrying too much about how to resolve the problems). Thanks to all for their time and their patience!

**Closed by othiym23** 2016-07-01 20:47 UTC
Labels: feature-request
