### ISSUE TITLE
npm doesn't install packages on Node.js 9.2.0

### ISSUE THREAD

**Issue by vladfrangu** [npm/npm#19193] opened 2017-11-18 10:07 UTC
#### I'm opening this issue because:
npm doesn't work nicely with Node.js 9.2.0
This could be an issue with Node itself, or with npm, I don't know as I am not experienced.

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm is unable to install packages, dependencies, or anything due to node.js 9.2.0. Note, this affects any packages, not just git ones.

![Image](https://i.kingdgrizzle.ml/2017/11/K4v6P4.png)

#### How can the CLI team reproduce the problem?
 - Upgrade to Node.js 9.2.0 from Node.js 8.6.0 on Windows (this is the version that affected me)
 - Launch a command prompt, and try installing a package
 - Watch as it errors
(No npm-debug log file is generated)

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v9.2.0
 - `npm config get registry` prints: ![Normal Registry from npm](https://i.kingdgrizzle.ml/2017/11/M3v6q9.png)
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by egoroof** [comment] 2017-11-18 20:48
Uninstall Node, go to `C:\Users\<your_user>\AppData\Roaming`, remove folders `npm` and `npm-cache` then install Node - it should work 🔨

**Comment by vladfrangu** [comment] 2017-11-18 22:10
Ok..?

- Uninstalled Node
- Renamed `%appdata%\npm` to `npm.old` (backup reasons) and deleted npm-cache
- Re-installed Node 9

Result: It worked!

But still. This seems like a very big bug for people who just expect upgrading to work..

**Comment by jamesplease** [comment] 2017-11-19 00:03
This also affects nvm installations.

**Comment by kenany** [comment] 2017-11-19 00:40
Duplicate of https://github.com/npm/npm/issues/19019.

**Closed as completed by kenany** 2017-11-19 00:40 UTC

**Comment by vitaly-t** [comment] 2017-11-20 11:33
We are using an NVM setup with many Node versions, so the solution about uninstalling Node is no good.

**Comment by aeroxy** [comment] 2017-11-21 09:13
Same issue here with ubuntu 17.04, somehow I removed Node 8 after installing 9 with nvm, and now I cannot switch back to 8 by using `nvm install 8` because it relies on npm...

**Comment by cagan** [comment] 2017-11-24 17:45
You can change your npm version.

Type `sudo su`

 Reinstall npm:  `curl -L https://www.npmjs.org/install.sh | sh`

And try to install packages via npm install

**Comment by jhonemillan** [comment] 2017-12-01 06:00
Same issue, Ubuntu 17.10, Node 9.2.0, NPM 5.5.1. Installing package fails.
Have you a workaround? or when will be fixed this??
