### ISSUE TITLE
npm ERR! uid must be an unsigned int

### ISSUE THREAD

**Issue by aeron11** [npm/npm#14047] opened 2016-09-23 03:18 UTC
myNamedeMacBook-Pro:FE myName$ sudo npm install -g bower
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myName/Development/sailsZumean/FE/npm-debug.log

**Comment by aeron11** [comment] 2016-09-23 03:20
I am using npm to install bower, or other package, it always throw above error when installing, I am just upgrade npm version to latest.

any idea? thanks!

**Comment by othiym23** [comment] 2016-09-23 04:22
Closing as duplicate of #13918 – either reinstalling Node and only using the distributed version of npm, downgrading to a Node.js LTS (which doesn't have this issue), or using npm no newer than `npm@3.10.7` should all fix it. See the linked issue for details. Thanks for your time!

**Closed by othiym23** 2016-09-23 04:22 UTC

**Comment by fayeyen** [comment] 2016-09-23 21:20
Please provide the proper way to uninstall node command reinstall node, or how to downgrade using npm no newer than npm@3.10.7.
I use the command try to downgrade but it show same error message
sudo npm install -g npm@3.10.7

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@3.10.7"
npm ERR! node v6.6.0
npm ERR! npm v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/admin/test/npm-debug.log

I also found this command at the site 

http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x
not sure does it work or not

lsbom -f -l -s -pf /var/db/receipts/org.nodejs.pkg.bom | while read f; do  sudo rm /usr/local/${f}; done

sudo rm -rf /usr/local/lib/node /usr/local/lib/node_modules /var/db/receipts/org.nodejs.*

**Comment by aurelienprevotMVP** [comment] 2016-09-24 09:35
Hello fayeyen,

I wrote a little blog post to explain how to deal with this problem. You'll find it in the second part of the blog post : https://rockwithazure.wordpress.com/2016/09/24/sp-framework-macos-sierra-troubles-and-resolution/

**Comment by emmafar** [comment] 2016-09-24 14:43
I have problem too

**Comment by nchirr** [comment] 2016-09-25 22:42
following the blog listed.. and the second option..  I still have an issue ..

with the "sudo n 6.2" command.. I am getting the following error.

  Error: invalid version 6.2

**Comment by manjurock** [comment] 2016-09-29 09:45
user these steps
1. Uninstall nmp.
2. Install  node.js      which install working version of npm also

**Comment by nchirr** [comment] 2016-09-29 12:51
Thanks very much @manjurock.
did exactly the same.. and it worked.

**Comment by natefikru** [comment] 2016-10-05 00:33
@aurelienprevotMVP thank you! your method worked for me.

**Comment by jonatasfreitasv** [comment] 2016-10-07 01:35
Use NodeJS v6.5.0

**Comment by shammelburg** [comment] 2016-12-14 09:34
I also uninstalled and now it works fine. Thanks guys
