### ISSUE TITLE
npm error while installing Ionic

### ISSUE THREAD

**Issue by SachinSingh20** [npm/npm#18552] opened 2017-09-17 06:23 UTC
I typed npm install -g cordova ionic 

i got this 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sachin Singh\npm-debug.log

**Comment by kenany** [comment] 2017-09-17 16:07
Closing as a duplicate of your previous issue, https://github.com/npm/npm/issues/18167.

**Closed as completed by kenany** 2017-09-17 16:07 UTC
Labels: support
