### ISSUE TITLE
Errors while trying to install less compiler on npm

### ISSUE THREAD

**Issue by jesmanto** [npm/npm#16631] opened 2017-05-15 20:36 UTC
#### I'm opening this issue because:
I tried installing LESS compiler and i get this error in return

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'less' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData less
8 silly fetchNamedPackageData less
9 silly mapToRegistry name less
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'less',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'less',
12 silly mapToRegistry   name: 'less',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/less
14 verbose request uri https://registry.npmjs.org/less
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:21:28 PM
17 verbose request id 250957ea24e355fd
18 verbose etag W/"591950c8-1fd9e"
19 verbose lastModified Mon, 15 May 2017 06:55:04 GMT
20 http request GET https://registry.npmjs.org/less
21 http 304 https://registry.npmjs.org/less
22 verbose headers { date: 'Mon, 15 May 2017 20:21:34 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"591950c8-1fd9e"',
22 verbose headers   age: '244',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-lhr6345-LHR',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1494879695.728386,VS0,VE1',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Mon, 15 May 2017 20:21:34 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"591950c8-1fd9e"',
23 silly get     age: '244',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lhr6345-LHR',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1494879695.728386,VS0,VE1',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/less from cache
25 verbose get saving less to C:\Users\JESSE .O\AppData\Roaming\npm-cache\registry.npmjs.org\less\.cache.json
26 verbose correctMkdir C:\Users\JESSE .O\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule less@2.7.2 checking installable status
40 silly cache add args [ 'less', null ]
41 verbose cache add spec less
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'less',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'less',
42 silly cache add   name: 'less',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed less@latest
44 verbose addNamed "latest" is being treated as a dist-tag for less
45 info addNameTag [ 'less', 'latest' ]
46 silly mapToRegistry name less
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'less',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'less',
49 silly mapToRegistry   name: 'less',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri https://registry.npmjs.org/less
51 verbose addNameTag registry:https://registry.npmjs.org/less not in flight; fetching
52 verbose get https://registry.npmjs.org/less not expired, no request
53 silly addNameTag next cb for less with tag latest
54 silly addNamed less@2.7.2
55 verbose addNamed "2.7.2" is a plain semver version for less
56 silly mapToRegistry name less
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry data Result {
59 silly mapToRegistry   raw: 'less',
59 silly mapToRegistry   scope: null,
59 silly mapToRegistry   escapedName: 'less',
59 silly mapToRegistry   name: 'less',
59 silly mapToRegistry   rawSpec: '',
59 silly mapToRegistry   spec: 'latest',
59 silly mapToRegistry   type: 'tag' }
60 silly mapToRegistry uri https://registry.npmjs.org/less
61 verbose addRemoteTarball https://registry.npmjs.org/less/-/less-2.7.2.tgz not in flight; adding
62 verbose addRemoteTarball [ 'https://registry.npmjs.org/less/-/less-2.7.2.tgz',
62 verbose addRemoteTarball   '368d6cc73e1fb03981183280918743c5dcf9b3df' ]
63 info retry fetch attempt 1 at 9:21:34 PM
64 info attempt registry request try #1 at 9:21:34 PM
65 http fetch GET https://registry.npmjs.org/less/-/less-2.7.2.tgz
66 http fetch 200 https://registry.npmjs.org/less/-/less-2.7.2.tgz
67 info retry will retry, error on last attempt: Error: read ECONNRESET
68 silly fetchAndShaCheck shasum 368d6cc73e1fb03981183280918743c5dcf9b3df
69 silly rollbackFailedOptional Starting
70 silly rollbackFailedOptional Finishing
71 silly runTopLevelLifecycles Finishing
72 silly install printInstalled
73 verbose stack Error: shasum check failed for C:\Users\JESSE~1.O\AppData\Local\Temp\npm-7100-4c20f651\registry.npmjs.org\less\-\less-2.7.2.tgz
73 verbose stack Expected: 368d6cc73e1fb03981183280918743c5dcf9b3df
73 verbose stack Actual:   8d2bd2edfc33b2f4f95b6724b2c5dec96b001d29
73 verbose stack From:     https://registry.npmjs.org/less/-/less-2.7.2.tgz
73 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
73 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
73 verbose stack     at emitNone (events.js:91:20)
73 verbose stack     at ReadStream.emit (events.js:185:7)
73 verbose stack     at endReadableNT (_stream_readable.js:974:12)
73 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
73 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
74 verbose cwd C:\Program Files\nodejs
75 error Windows_NT 6.2.9200
76 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "less"
77 error node v6.10.1
78 error npm  v3.10.10
79 error shasum check failed for C:\Users\JESSE~1.O\AppData\Local\Temp\npm-7100-4c20f651\registry.npmjs.org\less\-\less-2.7.2.tgz
79 error Expected: 368d6cc73e1fb03981183280918743c5dcf9b3df
79 error Actual:   8d2bd2edfc33b2f4f95b6724b2c5dec96b001d29
79 error From:     https://registry.npmjs.org/less/-/less-2.7.2.tgz
80 error If you need help, you may report this error at:
80 error     <https://github.com/npm/npm/issues>
81 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-05-16 18:33
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:52 UTC
Labels: bot-closed, shasum, support
