### ISSUE TITLE
Parsoid fail install

### ISSUE THREAD

**Issue by gmbr3** [npm/npm#14675] opened 2016-11-20 16:47 UTC
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install

#### What's going wrong?
[npm-debug.txt](https://github.com/npm/npm/files/602163/npm-debug.txt)

#### How can the CLI team reproduce the problem?
Run "npm install parsoid"

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: v7.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by othiym23** [comment] 2016-11-21 22:20
Closing as duplicate of #14427, which is fixed in the next release branch but won't be released until next Thursday. Thanks for your time!

**Closed by othiym23** 2016-11-21 22:20 UTC
Labels: support
