### ISSUE TITLE
"file name too long" on Windows 7

### ISSUE THREAD

**Issue by olegakbarov** [npm/npm#7768] opened 2015-03-27 08:38 UTC
probably a known issue but i stumbled upon this 

```
source-map/node_modules/source-map/build/suffix-source-map.jsm (Filename too long)
error: unable to create file lp/individual-investment-account/src/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/build/suffix-utils.jsm (Filename too long)

fatal: cannot create directory at 'lp/individual-investment-account/src/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map': Filename too long
```

**Comment by smikes** [comment] 2015-03-29 17:04
Yes, if this is about long filenames / paths on Windows, the canonical issue is: https://github.com/npm/npm/issues/3697

If that addresses your concerns, then this can be closed as a duplicate.

However sometimes the problem is with a third-party Windows tool that doesn't use the `\\?\` workaround to address longer-than-255-char paths at all, and you may be able to find a different workaround.  Can you tell me which program it was that generated the error messages you posted above?  If it was `npm`, can you attach the `npm-debug.log` file as a gist <https://gist.github.com>?

**Comment by DanielaPatrik** [comment] 2015-08-06 12:36
Hi There! I have had the same issue and I stumbled across "Long Path Tool" program. Give it a go! :)

**Comment by ehsalazar** [comment] 2015-08-12 02:43
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Closed by ehsalazar** 2015-08-12 02:43 UTC
Labels: support, windows

**Comment by yuliareea** [comment] 2015-10-21 19:16
I had this problem for a long time.
My friend recommended me Long Path Tool for fixing this.
I am skeptic with this king of tool but I was wrong.
This tool can do anything.

**Comment by gamicklisafisher** [comment] 2015-11-22 06:46
You should check out ‘Long Path Tool’ it will help you fix the issues. I had similar issue in past and this tool helped me to get it resolved.

**Comment by maximjo** [comment] 2015-12-17 10:04
I also have faced the same problem and “Long Path Tool” software sort out my problem easily.
Try it, It is easy and very much user friendly.

**Comment by markosillona** [comment] 2016-02-04 17:22
you need to use software " Long Path Tool " it will solve this problem

**Comment by cristopher100** [comment] 2016-03-09 02:44
i have also the same problem and i use long path tool to solve my problem and it works good for me.

**Comment by natasha544** [comment] 2016-06-10 15:41
Long path tool is very helpful

**Comment by ericdke** [comment] 2016-06-13 11:14
The link recommended by @natasha544, @yuliareea and @cristopher100 is an infamous malware/spam. You need to clean this page from spammers...

**Comment by magisch** [comment] 2016-06-13 11:17
**It must be noted that Long Path Tool is known malware and known spam. These accounts are all sockpuppets to spam the product. Please don't fall for this.**

**Comment by Samantha258** [comment] 2016-08-13 07:14
“Long Path Tool” is very helpful for this error !
You can use to solve this problem

**Comment by ericdke** [comment] 2016-08-13 09:47
@Samantha258 You're a spammer, go to hell. // @ehsalazar Please clean up this mess and ban these horrible people.
