### ISSUE TITLE
npm rm -g fails

### ISSUE THREAD

**Issue by dferber90** [npm/npm#17402] opened 2017-06-23 09:52 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

<details>
<summary>Console output</summary>

```
$ npm rm -g prettier
Unhandled rejection Error: Argument #2: Expected string but got nullcf8f172b3117
    at addDependency (/Users/nick/npm-global/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/nick/npm-global/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/nick/npm-global/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/nick/npm-global/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/nick/npm-global/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/nick/npm-global/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/nick/npm-global/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/nick/npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/nick/npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/nick/npm-global/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/nick/npm-global/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/nick/npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nick/npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/nick/npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick/.npm/_logs/2017-06-23T09_51_13_276Z-debug.log
```

</details>

<details>
<summary>npm debug log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/nick/npm-global/bin/npm',
1 verbose cli   'rm',
1 verbose cli   '-g',
1 verbose cli   'prettier' ]
2 info using npm@5.0.3
3 info using node@v6.10.2
4 verbose npm-session a8751b8d4aa03029
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

</details>

#### How can the CLI team reproduce the problem?

`npm rm -g prettier`
`npm rm prettier -g`

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOs
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-06-23 13:26
Dupe of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-23 13:26 UTC
Labels: npm5
