### ISSUE TITLE
Not able to install bower via npm

### ISSUE THREAD

**Issue by suriyanath** [npm/npm#15741] opened 2017-02-11 17:40 UTC
I got below error when trying to install bower via npm, not sure what is the problem. Any light on this issue is welcome.
I ran the below command from Ubuntu 16.04 LTS but fails

**npm install -g bower --verbose**

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'bower',
npm verb cli   '--verbose' ]
npm info using npm@3.5.2
npm info using node@v4.2.6
npm verb request uri https://registry.npmjs.org/bower
npm verb request no auth needed
npm info attempt registry request try #1 at 10:17:58 PM
npm verb request id a1ec336ca1904d10
npm verb etag W/"589a1b04-2ae08"
npm verb lastModified Tue, 07 Feb 2017 19:07:48 GMT
npm http request GET https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/bower
npm verb headers { date: 'Sat, 11 Feb 2017 16:48:00 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"589a1b04-2ae08"',
npm verb headers   age: '27',
npm verb headers   connection: 'close',
npm verb headers   'x-served-by': 'cache-dfw1827-DFW',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1486831680.245054,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/bower from cache
npm verb get saving bower to /home/vagrant/.npm/registry.npmjs.org/bower/.cache.json
npm verb cache add spec bower
npm verb addNamed "latest" is being treated as a dist-tag for bower
npm info addNameTag [ 'bower', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/bower not in flight; fetching
npm verb get https://registry.npmjs.org/bower not expired, no request
npm verb addNamed "1.8.0" is a plain semver version for bower
npm verb addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.8.0.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.8.0.tgz',
npm verb addRemoteTarball   '55dbebef0ad9155382d9e9d3e497c1372345b44a' ]
npm info retry fetch attempt 1 at 10:18:00 PM
npm info attempt registry request try #1 at 10:18:00 PM
npm http fetch GET https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm http fetch 200 https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm verb stack Error: shasum check failed for /tmp/npm-20551-007bfe52/registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm verb stack Expected: 55dbebef0ad9155382d9e9d3e497c1372345b44a
npm verb stack Actual:   34c6d64f41d0c44f5c399cd0fa5ec58f292b8565
npm verb stack From:     https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm verb stack     at /usr/share/npm/node_modules/sha/index.js:25:8
npm verb stack     at ReadStream.<anonymous> (/usr/share/npm/node_modules/sha/index.js:72:7)
npm verb stack     at emitNone (events.js:72:20)
npm verb stack     at ReadStream.emit (events.js:166:7)
npm verb stack     at endReadableNT (_stream_readable.js:905:12)
npm verb stack     at nextTickCallbackWith2Args (node.js:441:9)
npm verb stack     at process._tickCallback (node.js:355:17)
npm verb cwd /home/vagrant
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! shasum check failed for /tmp/npm-20551-007bfe52/registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR! Expected: 55dbebef0ad9155382d9e9d3e497c1372345b44a
npm ERR! Actual:   34c6d64f41d0c44f5c399cd0fa5ec58f292b8565
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
npm info attempt registry request try #2 at 10:23:21 PM
npm http fetch GET https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm http fetch 200 https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm info attempt registry request try #3 at 10:24:11 PM
npm http fetch GET https://registry.npmjs.org/bower/-/bower-1.8.0.tgz
npm http fetch 200 https://registry.npmjs.org/bower/-/bower-1.8.0.tgz

npm ERR! Please include the following file with any support request:

**Comment by amandeepmittal** [comment] 2017-03-02 10:33
@suriyanath did you try running the same command with `sudo`?

**Comment by legodude17** [comment] 2017-03-02 17:24
@amandeepmittal that won't help, but running the command again might.

Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by suriyanath** [comment] 2017-03-03 05:05
Hello,
        Thanks for your comments, I found the issue, it was problem with our proxy blocking https traffic partially, I changed registry to http i.e "http://registry.npmjs.org" and the problem is fixed

**Comment by amandeepmittal** [comment] 2017-03-04 03:03
@suriyanath if your problem is solved, you must close the issue.

**Closed** 2017-03-04 03:09 UTC
