### ISSUE TITLE
Error with "npm install" and update

### ISSUE THREAD

**Issue by farhatnawaz** [npm/npm#15145] opened 2016-12-05 20:52 UTC
Hi there. While trying to update the npm, I get this error. I was first trying to work with npm 3 install the dependency but that raised the similar problem.

<img width="571" alt="screen shot 2016-12-06 at 1 46 53 am" src="https://cloud.githubusercontent.com/assets/8686962/20901815/1ebcdaf0-bb56-11e6-8097-a3bbae46cd29.png">

Here are the contents of the log file: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@4.0.5' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:17:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
5 verbose cwd /Users/farhatnawaz/Freelancing/Projects/Sandjai/master
6 error Darwin 16.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@4.0.5"
8 error node v7.2.0
9 error npm  v3.10.9
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```
Does anyone have a fix?

**Comment by othiym23** [comment] 2016-12-05 22:26
Closing as duplicate of #14579, which is ultimately a consequence of how the Node installer works. See that issue for a description of how to fix this issue. Thanks for your time!

**Closed by othiym23** 2016-12-05 22:26 UTC
Labels: support
