### ISSUE TITLE
npm ERR! typeerror Error: Argument #1: Expected object but got string

### ISSUE THREAD

**Issue by raevilman** [npm/npm#8904] opened 2015-07-11 13:55 UTC
While running " sudo make install " 
I got following error

$ sudo make install
scripts/doc-build.sh doc/api/npm-view.md man/man3/npm-view.3
make[1]: Entering directory `/home/ec2-user/npm'
node cli.js install marked-man --no-global
npm ERR! Linux 3.14.35-28.38.amzn1.x86_64
npm ERR! argv "node" "/home/ec2-user/npm/cli.js" "install" "marked-man" "--no-global"
npm ERR! node v0.12.2
npm ERR! npm  v3.1.1
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected object but got string
npm ERR! typeerror     at resolveWithNewModule (/home/ec2-user/npm/lib/install/deps.js:375:3)
npm ERR! typeerror     at /home/ec2-user/npm/lib/install/deps.js:163:5
npm ERR! typeerror     at /home/ec2-user/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /home/ec2-user/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/home/ec2-user/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/home/ec2-user/npm/lib/install/deps.js:158:3)
npm ERR! typeerror     at Array.<anonymous> (/home/ec2-user/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/home/ec2-user/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/npm/npm-debug.log
make[1]: *** [node_modules/.bin/marked-man] Error 1
make[1]: Leaving directory `/home/ec2-user/npm'
make: *** [man/man3/npm-view.3] Error 2

**Comment by williamboman** [comment] 2015-07-12 11:01
dupe of #8893

**Comment by iarna** [comment] 2015-07-13 16:51
Closing as duplicate.

**Closed by iarna** 2015-07-13 16:51 UTC
Labels: bug
