### ISSUE TITLE
Discord.js error

### ISSUE THREAD

**Issue by potaha** [npm/npm#14482] opened 2016-11-01 07:14 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Новая папка\\Приложения\\nodejs\\node.exe',
1 verbose cli   'D:\\Новая папка\\Приложения\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.js' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData discord.js
8 silly fetchNamedPackageData discord.js
9 silly mapToRegistry name discord.js
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'discord.js',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'discord.js',
12 silly mapToRegistry   name: 'discord.js',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/discord.js
14 verbose request uri https://registry.npmjs.org/discord.js
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:12:46 PM
17 verbose request id 767c3c1e681cdcef
18 verbose etag "3AONFYJRWB9OIVSIUB2TIB4NV"
19 http request GET https://registry.npmjs.org/discord.js
20 http 304 https://registry.npmjs.org/discord.js
21 verbose headers { date: 'Tue, 01 Nov 2016 07:12:47 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"3AONFYJRWB9OIVSIUB2TIB4NV"',
21 verbose headers   age: '76',
21 verbose headers   connection: 'close',
21 verbose headers   'x-served-by': 'cache-bma7022-BMA',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1477984367.690004,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 01 Nov 2016 07:12:47 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"3AONFYJRWB9OIVSIUB2TIB4NV"',
22 silly get     age: '76',
22 silly get     connection: 'close',
22 silly get     'x-served-by': 'cache-bma7022-BMA',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1477984367.690004,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/discord.js from cache
24 verbose get saving discord.js to C:\Users\akmur_000\AppData\Roaming\npm-cache\registry.npmjs.org\discord.js\.cache.json
25 verbose correctMkdir C:\Users\akmur_000\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install discord.js as a dependency of itself
42 verbose stack     at checkSelf (D:\Новая папка\Приложения\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
42 verbose stack     at Array.<anonymous> (D:\Новая папка\Приложения\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
42 verbose stack     at LOOP (D:\Новая папка\Приложения\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
42 verbose stack     at chain (D:\Новая папка\Приложения\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
42 verbose stack     at D:\Новая папка\Приложения\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
42 verbose stack     at D:\Новая папка\Приложения\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at D:\Новая папка\Приложения\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (D:\Новая папка\Приложения\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
43 verbose cwd D:\Discord.js\discord.js-master\docs\custom\examples
44 error Windows_NT 10.0.14951
45 error argv "D:\\Новая папка\\Приложения\\nodejs\\node.exe" "D:\\Новая папка\\Приложения\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js"
46 error node v6.9.1
47 error npm  v3.10.8
48 error code ENOSELF
49 error Refusing to install discord.js as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by 7coder7** [comment] 2016-11-01 08:57
Looks like a duplicate of https://github.com/npm/npm/issues/9723

**Comment by KenanY** [comment] 2016-11-01 13:05
@potaha Make sure that the `"name"` property in your local `package.json` is not set to `"discord.js", make it more unique.

**Comment by KenanY** [comment] 2016-11-11 17:05
Closing due to no response

**Closed by KenanY** 2016-11-11 17:05 UTC
Labels: support
