### ISSUE TITLE
Getting "UID must be an unsigned int" prceeded by "deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue" warning.

### ISSUE THREAD

**Issue by nchirr** [npm/npm#14076] opened 2016-09-25 20:16 UTC
While trying to install Yeoman Yo, Bower, Grunt and other global node modules.. getting the error.

Surprisingly this is after I update the minimatch version to 3.10.8; and npm to the latest verion.

Here is the command and the log.
PHXC02R51YCFVH8:~ root# npm install -g yo bower grunt-cli jasmine-node karma yuidocjs forever less
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "jasmine-node" "karma" "yuidocjs" "forever" "less"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/root/npm-debug.log

**Comment by dansilcox** [comment] 2016-09-25 20:28
I'm getting the unsigned int issue too on node v4.2.2 / npm  v3.10.8 on OSX Darwin 15.6.0 (10.11.6 (15G1004) El Capitan)

**Comment by KenanY** [comment] 2016-09-25 20:48
See https://github.com/npm/npm/issues/14047#issuecomment-249099655. Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-25 20:48 UTC

**Comment by nchirr** [comment] 2016-09-25 22:44
My apologies.. following the suggestion as listed in the blogpost..  "https://rockwithazure.wordpress.com/2016/09/24/sp-framework-macos-sierra-troubles-and-resolution/"
and the second option..  I still have an issue ..

with the "sudo n 6.2" command.. I am getting the following error.
  Error: invalid version 6.2

**Comment by ercu** [comment] 2016-09-26 08:08
@nchirr Try 

`sudo n 6.2.0`
or you can see the list using 

`n list`

**Comment by nchirr** [comment] 2016-09-26 11:27
Thanks @ercu 
my "n list" is retuning blanks. does it mean I made a mistake with the n-master download?

Is uninstalling node (http://stackabuse.com/how-to-uninstall-node-js-from-mac-osx/) the only option? and install again? 

Really appreciate your help.

**Comment by zCHIP** [comment] 2016-09-30 01:04
I was getting the unsigned int error on node v6.7.0 and npm v3.10.8 on OSX 10.12 (Sierra)
Rollback to npm 3.10.7 did the trick.

**Comment by locoalien** [comment] 2016-10-11 12:54
I have the same problem with OS X Sierra. If anyone knows how to solve the compatibility problem I appreciate it.

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by fayeyen** [comment] 2016-10-11 14:15
npm v3.10.9 fit the problem

**Comment by fayeyen** [comment] 2016-10-11 14:21
sudo npm install npm@3.10.9 -g

**Comment by joelgrimberg** [comment] 2016-10-12 11:44
@fayeyen does not do the trick for me
having the same issue here (npm 3.10.8 - node 6.7.0)
