### ISSUE TITLE
prepublishOnly should run on `npm pack`

### ISSUE THREAD

**Issue by FezVrasta** [npm/npm#15363] opened 2017-01-01 12:24 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

The new `prepublishOnly` hook should be executed before `npm pack` in order to keep consistency with the previous behaviour. Otherwise, the resulting tarball generated by `pack` will be different from the files uploaded to the npm registry.

#### How can the CLI team reproduce the problem?

Create a `prepublishOnly` hook, run `npm pack`.

Consider this workflow:

```
npm pack
npm install my-module.tar.gz
```
This will be completely different from:

```
npm publish my-module
npm install my-module
```

Because in the first case, prepublish isn't executed.
In the second case, it's executed during the publish step.

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v7.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by KenanY** [comment] 2017-01-01 16:04
Isn't that what the `"prepare"` script is for? Running `"prepublish"` before anything but publishing is exactly the sort of behavior dozens of users complained about....

**Comment by FezVrasta** [comment] 2017-01-01 16:06
No, they complained about `prepublish` being ran on `install`.

But `prepublish` on `pack` is the expected behaviour, because `pack` is meant to return the exact same files that get published on npm registry.

**Comment by FezVrasta** [comment] 2017-01-01 16:08
Consider this workflow:

```
npm pack
npm install my-module.tar.gz
```

This will be completely different from:
```
npm publish my-module
npm install my-module
```

Because in the first case, `prepublish` isn't executed.
In the second case, it's executed during the `publish` step.

**Comment by shellscape** [comment] 2017-01-03 01:07
I'm in the same boat as @FezVrasta. I'm attempting to modify files before the packing takes place in order to add metadata. If we have to use `prepare` now instead of `prepublishOnly` then we're right back to where we started with `prepublish` and having to use the hacky (but wonderful) `in-publish` script again - since I only want that to take place before the module is packed and published. For folks in that scenario, having to use `prepare` effectively kills the benefit of `prepublishOnly`.

**Comment by shellscape** [comment] 2017-01-10 15:22
@othiym23 pretty serious limitation. pinging due to issue age and severity.

**Comment by FezVrasta** [comment] 2017-01-31 11:47
So there's not any commitment to fix this bug?

**Comment by xandris** [comment] 2017-02-06 23:43
Even the manual calls `npm pack` a dry run that does everything that `npm publish` does. This behavior was quite a surprise to me.

**Comment by FezVrasta** [comment] 2017-03-12 18:29
@KenanY can this issue get prioritized accordingly to the comments of this issue?

Thank you.

**Comment by KenanY** [comment] 2017-03-12 18:51
@FezVrasta It's up to the core team. I don't set any priorities.

**Comment by FezVrasta** [comment] 2017-03-12 19:01
Can you ping them then? It's pretty important, the npm API is broken right now.

**Comment by KenanY** [comment] 2017-03-12 19:24
@FezVrasta I really shouldn't :)

> PLEASE don't @ collaborators or npm employees on issues. The CLI team is small, and has many outstanding commitments to fulfill.

[source](https://github.com/npm/npm/blob/bc3f24bf95abe45a185848561c7c1edc90f60c5e/CONTRIBUTING.md#responsibilities)

**Comment by FezVrasta** [comment] 2017-03-12 19:56
Ok I guess we'll keep the apib broken then 🙂

**Comment by shellscape** [comment] 2017-03-12 20:52
I'm somewhat surprised that @iarna hasn't weighed in on this as yet. as the creator of `in-publish` and a CLI contributor this is in her wheelhouse.

**Comment by FezVrasta** [comment] 2017-04-22 11:59
I'm wondering, what if someone wants to contribute to npm and fix this issue? How can someone do this if nobody acknowledged the problem?

Is it possible that `npm` had the `pack` command broken for more than 4 months and nobody cares?

**Comment by legodude17** [comment] 2017-04-26 21:34
You could pretty easily write a PR for this if you want. Just be prepared that this might be expected behavior.

**Comment by KenanY** [comment] 2017-04-26 21:44
ref. https://github.com/npm/npm/issues/15454 (that issue seems to have garnered more traction than this one; might close this one in favor of that one eventually)

> I'm not opposed to moving `prepublishOnly` to prior to the `pack` step in publication. It's kind of borderline as to if that constitutes a breaking change, but `npm@5` is approaching quickly so if we did this, we'd probably just do it then to be conservative about our semver.

https://github.com/npm/npm/issues/15454#issuecomment-288606380

**Comment by FezVrasta** [comment] 2017-04-26 22:22
How can a bug become a breaking change?

**Comment by legodude17** [comment] 2017-04-27 16:22
@FezVrasta What if it is not a bug? This change will affect people who depend of that script not being run by `npm pack`.

**Comment by FezVrasta** [comment] 2017-04-27 16:24
How can it not be a bug? The whole idea behind `pack` is to being able to "pack" a package and install it from command line. If it can't properly "pack", how can someone use it?

**Comment by mplewis** [comment] 2017-05-25 22:15
>`prepublish` on `pack` is the expected behaviour, because `pack` is meant to return the exact same files that get published on npm registry.

This is exactly why I believe the current behavior of `pack` is confusing.

From the [npm docs](https://docs.npmjs.com/cli/pack):

> For anything that's installable (that is, a package folder, tarball, tarball url, name@tag, name@version, name, or scoped name), this command will fetch it to the cache, and then copy the tarball to the current working directory as <name>-<version>.tgz, and then write the filenames out to stdout.

I don't understand why `pack` requires the target to be installable and fetches it to the cache if it is not going to run the prepublish step.

**Comment by shellscape** [comment] 2017-05-25 22:28
What npm ought to do is set the standard cascade of events for events in a default config, and allow users to override that per package. Hell, that's what we all do when we're writing our own npm scripts. This whole one-size-fits-all lifecycle script thing clearly doesn't fit all.

**Closed** 2017-06-18 10:35 UTC
Labels: bot-closed
