### ISSUE TITLE
npm search hangs when not given search

### ISSUE THREAD

**Issue by KylePalko** [npm/npm#9251] opened 2015-08-12 13:38 UTC
npm search hangs if you don't give it a term to search for. I'm sure it's working as intended and hanging because it's trying to pull every package, but this can be confusing to some people.

**Comment by sinkingshriek** [comment] 2015-08-12 13:50
I think this has been addressed in npm@3+ already with the progress bar.

**Comment by KylePalko** [comment] 2015-08-12 14:16
That's great. Thanks. I would still think we would just want to disable the ability to search for all packages, but this is better than nothing I guess.

**Comment by marcbachmann** [comment] 2015-08-13 08:58
> I think this has been addressed in npm@3+ already with the progress bar.

Nope, there's no progress bar at the search command. And it still hangs if you don't pass a search term in npm v3.

**Comment by othiym23** [comment] 2016-03-21 17:49
Closing as a duplicate of #6016, but also see #11984, which addresses this specific situation by disallowing search with no parameters (in times of yore, this would return every package known to npm, which isn't useful with a registry containing 250,000 packages). Thanks for your time and patience!

**Closed by othiym23** 2016-03-21 17:49 UTC
Labels: bug, search
