### ISSUE TITLE
Sign version commit with "npm version"

### ISSUE THREAD

**Issue by hckhanh** [npm/npm#13561] opened 2016-08-03 15:32 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's the feature?

Sign version commit with `npm version`

#### What problem is the feature intended to solve?

When the `npm version` is executed. The tag and version commit will be created.

The command `npm version` will sign the **tag** if `sign-git-tag` is set `true`. But the **version commit** is not signed. So I think it would be nice if the **version commit** is signed as well.

#### Is the absence of this feature blocking you or your team? If so, how?

We cannot use `npm version` completely. Because the version commit is not signed. We need verify all tags and commits.

#### Is this feature similar to an existing feature in another tool?

No

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Of course.

**Comment by KenanY** [comment] 2016-08-03 20:24
Closing since this is a duplicate of https://github.com/npm/npm/issues/12288 and https://github.com/npm/npm/issues/12696, I believe.

**Closed by KenanY** 2016-08-03 20:24 UTC

**Comment by hckhanh** [comment] 2016-08-04 00:07
I think so, cheers :smile:
