### ISSUE TITLE
cannot install angular-cli

### ISSUE THREAD

**Issue by pappasa** [npm/npm#15649] opened 2017-02-02 10:20 UTC
#### I'm opening this issue because:
  - [x ] npm is crashing.

#### What's going wrong?
The following error messages are shown:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\temp\testangularcli\npm-debug.log

#### How can the CLI team reproduce the problem?
In a command window execute the following:
npm install -g angular-cli

[npm-debug.log.txt](https://github.com/npm/npm/files/747419/npm-debug.log.txt)

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [x ] I use a proxy to connect to the npm registry.

**Comment by doug-wade** [comment] 2017-02-04 20:30
This seems to be a duplicate of #15663

**Comment by KenanY** [comment] 2017-02-12 00:03
Closing as a duplicate.

**Closed by KenanY** 2017-02-12 00:03 UTC
