### ISSUE TITLE
Cannot find module 'internal/util/types' installing express

### ISSUE THREAD

**Issue by NataliaRG** [npm/npm#19158] opened 2017-11-14 18:02 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I write npm install express, there is npm Error: Cannot find module 'internal/util/types'
npm ERR! code MODULE_NOT_FOUND. I don't find the way to fix it
#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Natalia\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '-g' ]
2 info using npm@3.5.1
3 info using node@v8.9.1
4 verbose stack Error: Cannot find module 'internal/util/types'
4 verbose stack     at Function.Module._resolveFilename (module.js:536:15)
4 verbose stack     at Function.Module._load (module.js:466:25)
4 verbose stack     at Module.require (module.js:579:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at evalmachine.<anonymous>:31:26
4 verbose stack     at Object.<anonymous> (C:\Users\Natalia\AppData\Roaming\npm\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (module.js:635:30)
4 verbose stack     at Object.Module._extensions..js (module.js:646:10)
4 verbose stack     at Module.load (module.js:554:32)
4 verbose stack     at tryModuleLoad (module.js:497:12)
5 verbose cwd C:\Users\Natalia\Documents\prog
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Natalia\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "-g"
8 error node v8.9.1
9 error npm  v3.5.1
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/util/types'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:3.5.1
 - `node -v` prints:8.9.1
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-11-15 11:59
Duplicate of https://github.com/npm/npm/issues/19032.

**Closed as completed by kenany** 2017-11-15 11:59 UTC
Labels: support
