### ISSUE TITLE
Don't list dependencies after install (it's very spammy!)

### ISSUE THREAD

**Issue by stevage** [npm/npm#11121] opened 2016-01-12 06:31 UTC
(From [StackOverflow](http://stackoverflow.com/questions/34734035/dont-show-complete-npm-dependency-list-after-installation)) I recently upgrade from ancient to new NPM. After `npm install` completes in the package that I work on mostly, NPM spews out hundreds of lines of output, similar to the result of `npm list`.

![screenshot 2016-01-12 12 14 56](https://cloud.githubusercontent.com/assets/678344/12256578/5d6bdb5e-b952-11e5-8b83-afb9aaf7f055.png)

This seems unwarranted.  Output of that size isn't useful, and it hides the output of the `postinstall` phase, where I had hoped to include a user-friendly message.

Could this behaviour be changed, to skip the dependency listing? Or at least to make it optional somehow?

The package is [here](github.com/nicta/nationalmap).

The full output of `npm install` is [here](https://gist.github.com/stevage/9289124b8d9d935daf51) - it's 923 lines, of which ~900 are the dependency list.

**Comment by KenanY** [comment] 2016-01-12 15:44
@stevage Sounds like you want https://github.com/npm/npm/issues/10732.

**Comment by stevage** [comment] 2016-01-12 22:59
Thanks for that pointer. Thinking about this more, I think the current behaviour is simply broken, and adding options to turn broken behaviour into acceptable behaviour doesn't seem right.

Put it this way: in what situation is seeing 900 lines of package listing after installation desirable?

- New user: no, they just get overwhelmed
- Experienced user: no, their eyes will glaze over and they'll probably use some workaround to disable it
- Package developer: no way are they going to read 900 lines of output looking for something out of the ordinary

But agree with comments in #2040 that `npm install` should produce some output - and forcing the user to hide *all* output (including errors and warnings) with `--loglevel silent` would be wrong.

Could I suggest replacing all that output with:

>`900 packages installed. Run 'npm list' for details.`

**Comment by bazineta** [comment] 2016-01-13 20:12
I think @stevage hits it on the head here; there is no circumstance I can think of in which an amount of output that typically overflows the scroll buffer is actually helpful.  In general, we're now just running the install a few times to see if it took, frankly.

**Comment by zkat** [comment] 2016-01-13 23:31
This is a duplicate of #10732, so I'm closing this.

**Closed by zkat** 2016-01-13 23:31 UTC
