### ISSUE TITLE
Error while installing Apollo-Starter-kit 

### ISSUE THREAD

**Issue by Vinaya2101** [npm/npm#14702] opened 2016-11-22 10:14 UTC
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
 I am trying to install apollo-starter-kit but it is showing the following isuues
The debug file shows this 

<details><pre>
18811 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
18812 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
18813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
18813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
18813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
18813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
18814 verbose stack Error: shasum check failed for C:\Users\vdbhat\AppData\Local\Temp\npm-9752-cccd8367\registry.npmjs.org\acorn\-\acorn-4.0.3.tgz
18814 verbose stack Expected: 1a3e850b428e73ba6b09d1cc527f5aaad4d03ef1
18814 verbose stack Actual:   7a410b1cd51cde859eb9038c6b3996e7b5db574d
18814 verbose stack From:     https://registry.npmjs.org/acorn/-/acorn-4.0.3.tgz
18814 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
18814 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
18814 verbose stack     at emitNone (events.js:91:20)
18814 verbose stack     at ReadStream.emit (events.js:185:7)
18814 verbose stack     at endReadableNT (_stream_readable.js:974:12)
18814 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
18814 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
18815 verbose cwd C:\Users\vdbhat\Documents\GitHub\apollo-starter-kit
18816 error Windows_NT 6.1.7601
18817 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
18818 error node v7.1.0
18819 error npm  v3.10.9
18820 error shasum check failed for C:\Users\vdbhat\AppData\Local\Temp\npm-9752-cccd8367\registry.npmjs.org\acorn\-\acorn-4.0.3.tgz
18820 error Expected: 1a3e850b428e73ba6b09d1cc527f5aaad4d03ef1
18820 error Actual:   7a410b1cd51cde859eb9038c6b3996e7b5db574d
18820 error From:     https://registry.npmjs.org/acorn/-/acorn-4.0.3.tgz
18821 error If you need help, you may report this error at:
18821 error     <https://github.com/npm/npm/issues>
18822 verbose exit [ 1, true ]
</pre></details>

**Comment by legodude17** [comment] 2016-11-29 01:10
Try running `npm cache clean acorn`.

**Comment by zkat** [comment] 2016-12-02 04:44
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:44 UTC
Labels: network, shasum, support
