### ISSUE TITLE
shasum check failed for telegram-promise-1.0.0.tgz

### ISSUE THREAD

**Issue by mahnunchik** [npm/npm#11089] opened 2016-01-08 13:11 UTC
``` bash
$ npm install telegram-promise
npm info it worked if it ends with ok
npm info using npm@3.3.12
npm info using node@v5.4.0
npm info attempt registry request try #1 at 1:06:00 PM
npm http request GET https://registry.npmjs.org/telegram-promise
npm http 200 https://registry.npmjs.org/telegram-promise
npm info retry fetch attempt 1 at 1:06:07 PM
npm info attempt registry request try #1 at 1:06:07 PM
npm http fetch GET https://registry.npmjs.org/telegram-promise/-/telegram-promise-1.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/telegram-promise/-/telegram-promise-1.0.0.tgz
npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "telegram-promise"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /tmp/npm-5-a8645995/registry.npmjs.org/telegram-promise/-/telegram-promise-1.0.0.tgz
npm ERR! Expected: 0035da5f882c7108e0b0b1869f593c23c576d677
npm ERR! Actual:   cf436472e47b34649af351c00d6d2d3179ad8c46
npm ERR! From:     https://registry.npmjs.org/telegram-promise/-/telegram-promise-1.0.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

[npm-debug.txt](https://github.com/npm/npm/files/82710/npm-debug.txt)

**Comment by mahnunchik** [comment] 2016-01-08 13:20
Open issues related to the `shasum check failed for...`

* https://github.com/npm/npm/issues/11020
* https://github.com/npm/npm/issues/11009
* https://github.com/npm/npm/issues/11006
* https://github.com/npm/npm/issues/11000
* https://github.com/npm/npm/issues/10977
* https://github.com/npm/npm/issues/10943
* https://github.com/npm/npm/issues/10867
* https://github.com/npm/npm/issues/10854
* https://github.com/npm/npm/issues/10804
* https://github.com/npm/npm/issues/10801
* https://github.com/npm/npm/issues/10743
* https://github.com/npm/npm/issues/10738
* https://github.com/npm/npm/issues/10735
* https://github.com/npm/npm/issues/10722
* https://github.com/npm/npm/issues/10658
* https://github.com/npm/npm/issues/10560
* https://github.com/npm/npm/issues/10432

And more... [is:issue is:open shasum check failed for](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+shasum+check+failed+for)

What the hell?

**Comment by othiym23** [comment] 2016-01-08 18:02
@mahnunchik This is a common error because it's what happens when a package download is interrupted or otherwise fails. In almost all cases, the problem can be fixed by running `npm cache clear <package>` (or, if you're feeling paranoid, running `npm cache clear` and removing the entire cache) and then rerunning the install. As far as "what the hell" is concerned, there are tens of millions of downloads happening through the registry every day over a wide variety of network connections, and stuff happens. I would greatly prefer all downloads to succeed, but I'm actually pretty surprised people encounter this issue as rarely as they do.

Does clearing the cache fix the problem for you?

**Comment by mahnunchik** [comment] 2016-01-08 18:25
Hi @othiym23 

My investigation

The following variants have not solved the problem:
```bash
$ npm cache clear telegram-promise
$ npm cache clear
```
I've tried clear launch of node and npm inside Docker container but results are the same.

I've tried to download package in Thailand and Russia - the same error.

---
So I think that package archive is broken (invalid shasum) in the server or in one of servers.

`npm publish` was from travis `deploy` https://docs.travis-ci.com/user/deployment/npm

**Comment by mahnunchik** [comment] 2016-01-08 18:29
https://github.com/travis-ci/travis-ci/issues/5423

**Comment by priyajeet** [comment] 2016-01-08 19:02
Another

```
npm ERR! shasum check failed for /tmp/npm-8450-92cd866d/registry.npmjs.org/sha.js/-/sha.js-2.2.6.tgz
npm ERR! Expected: 17ddeddc5f722fb66501658895461977867315ba
npm ERR! Actual:   a53f8383a461d65d7084c04ace92ac16e0400e67
npm ERR! From:     https://registry.npmjs.org/sha.js/-/sha.js-2.2.6.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/jenkins/workspace/ContentExperience/Release/CutMinorRelease/npm-debug.log
```

**Comment by mahnunchik** [comment] 2016-01-09 07:53
Hi @othiym23 

Parallel publishing of module from travis make the broken packages in the npm repository. Shasum of this modules is incorrect.

I've created test repository to reproduce this error:
* GitHub repo https://github.com/mahnunchik/test-travis-npm-deploy-shasum-check-failed
* Travis build https://travis-ci.org/mahnunchik/test-travis-npm-deploy-shasum-check-failed/
* NPM package https://www.npmjs.com/package/test-travis-npm-deploy-shasum-check-failed

The build which produced package with incorrect shasum: https://travis-ci.org/mahnunchik/test-travis-npm-deploy-shasum-check-failed/builds/101228494

```bash
npm ERR! shasum check failed for /tmp/npm-2538-55d80a6e/registry.npmjs.org/test-travis-npm-deploy-shasum-check-failed/-/test-travis-npm-deploy-shasum-check-failed-1.0.3.tgz
npm ERR! Expected: 5bcd4ade3acef4f051cab4048a723004fe1fab62
npm ERR! Actual:   9aac2b6298da4c4d9978baa393905b91435f29d5
npm ERR! From:     https://registry.npmjs.org/test-travis-npm-deploy-shasum-check-failed/-/test-travis-npm-deploy-shasum-check-failed-1.0.3.tgz
```

**Comment by mahnunchik** [comment] 2016-01-09 14:03
Please look at comment: https://github.com/travis-ci/travis-ci/issues/5423#issuecomment-170237637

**Comment by mahnunchik** [comment] 2016-01-09 17:03
Similar problem: https://github.com/travis-ci/travis-ci/issues/4738

**Comment by aysham94** [comment] 2016-08-01 04:27
i created account in this web just to post this solution bcz all posted solution didnt work with me!
try the following commands sequentially

 npm i test-travis-npm-deploy-shasum-check-failed

npm cache clear

npm install -g ionic

hope it works with u guys

**Comment by aysham94** [comment] 2016-08-01 04:27
i created account in this web just to post this solution bcz all posted solution didnt work with me!
try the following commands sequentially

 npm i test-travis-npm-deploy-shasum-check-failed

npm cache clear

npm install -g ionic

**Comment by zkat** [comment] 2016-12-09 00:29
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:29 UTC
Labels: shasum, support
