### ISSUE TITLE
what SPDX license should I use for private modules?

### ISSUE THREAD

**Issue by mcollina** [npm/npm#8773] opened 2015-06-30 20:22 UTC
NPM now forbids the user to put non-spdx licenses in the license field during npm init, and complain thereafter if you have something weird in there. However, NPM is used also for private modules. What SPDX code should we put in? I do not want to reference ISC or MIT in closed-source modules.

Another solution is to ask "is this module private?" and do not prompt at all for a license, with the assumption that a private module does not require a license.

**Comment by sindresorhus** [comment] 2015-06-30 20:34
It's in the [docs](https://docs.npmjs.com/files/package.json#license):

> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:

> `{ "license": "UNLICENSED"}`

**Comment by iarna** [comment] 2015-07-01 02:32
I'm going to close this as answered.

**Closed by iarna** 2015-07-01 02:32 UTC
Labels: support

**Comment by mcollina** [comment] 2015-07-01 05:15
I got confused by UNLICENSED and Unlicense. Which means two completely
different things.

The user experience is kind of bad there, specially for newcomers, because
the information is not immediate to find (what is SPDX? google SPDX), as
UNLICENSED is not listed in https://spdx.org/licenses/, which is a place as
good as the NPM docs.
How about offering autocompletion or just a suggestion to use UNLICENSED
after a couple of tries.

BTW, the 'Is it private?' question still makes sense

Il giorno mer 1 lug 2015 alle 04:32 Rebecca Turner <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment] 2015-07-02 05:42
Sorry for bothering again, but I tried putting `UNLICENSED` in `npm init` and it didn't work:

```
$ npm -v
2.11.3
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (mymodule)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC) UNLICENSED
Sorry, license should be a valid SPDX license expression and license is similar to the valid expression "Unlicense".

**Comment by cappslock** [comment] 2015-07-23 21:08
Yeah, having the same problem.

**Comment by tianp** [comment] 2015-08-07 07:03
@mcollina @cappslock you might try to put ```"private": true``` in your package.json, it solved my problem.

**Comment by cchamberlain** [comment] 2015-08-07 15:11
@tianp - the private field should be set to true only if you don't want the package to be publishable.  The question here was what license should be used when you dont want to grant others license to use the code.

**Comment by jandrieu** [comment] 2015-08-30 02:22
This shouldn't be closed.

Btw, @tianp... the problem is you can't get past the prompt in npm init without setting a license. Adding private:true to the package.json is fine, but doesn't fix the brokenness that is npm init right now.

**Comment by robkorv** [comment] 2015-09-06 13:38
if you use `"private": true` the license isn't checked. So you can put in your own copyright notice at `license` if you will.

**Comment by alash3** [comment] 2015-10-13 12:15
This is a problem for me also. It makes `npm init` useless if one cannot state that the package one is building does not, and should not, have a license.

**Comment by faceleg** [comment] 2015-10-14 02:24
@robertkowalski @tianp what if I *do* want to publish the module, i.e. to a private NPM repository?

**Comment by drom** [comment] 2015-10-19 18:27
Private module, in a Private npm repository, under Private license.
Sound's like important feature to have.

**Comment by othiym23** [comment] 2015-10-19 20:40
In newer versions of npm, `UNLICENSED` is supported and is the correct license to include for private packages. Your code _always_ has some kind of license (depending on where you are), and having it be implicit rather than explicit is a potential source of problems for everyone who encounters your code outside your organization. Given the frequency with which today's private hack becomes tomorrow's published open source component, making sure this is taken care of makes it worth the inconvenience, IMO. `"private": true` has a distinct use and isn't going to be overloaded to override the need for a license declaration.

**Comment by alash3** [comment] 2015-10-19 20:58
That is great, what version(s) of npm support this?

**Comment by othiym23** [comment] 2015-10-19 21:36
[`npm@3.3.1`](https://github.com/npm/npm/commit/eb66030) and higher for `npm@3`, and [`npm@2.14.2`](https://github.com/npm/npm/commit/1502a28) and higher for `npm@2`.

**Comment by scriptjs** [comment] 2015-10-26 15:06
@othiym23, @iarna, @faceleg, @cappslock  Getting to something that satisfies licensed proprietary software as easy as open source is just as important. Obviously the SPDX list does not capture everything in its entirety. I think the overriding concern for modules is that a license is supplied.

The concern expressed in this issue is not being properly heard or understood. UNLICENSED does not work. A proprietary license does not equate to UNLICENSED software – its just a set of terms that are not the same as an open license.

ie. Does the Apple Software Licence make it unlicensed? – not. Further, it is legally ambiguous to provide a download and use proprietary software that is identified as UNLICENSED when it clearly meant for folks to use under the terms of an identified that is supplied with the software.

I hope NPM is listening feedback you are receiving and will determine an appropriate fix this. I would urge folks to leave their licenses as they are, warnings aside, until this is fixed.

Agreed that private does not have anything to do with licensing. It only identifies whether the package is permitted to be published to a registry. That does not necessarily mean to the npm repository exclusively either.

**Comment by iarna** [comment] 2015-10-26 15:52
@scriptjs Doesn't `SEE LICENSE IN <filename>` exactly meet the need you describe? _(Documented in the [package.json documentation](https://docs.npmjs.com/files/package.json#license)]).)_

**Comment by ergose** [comment] 2015-10-26 16:33
I understand that if I create something then I hold all rights. I understand the logic that UNLICENSED means no license is being provided. Since the default is that I hold all rights, then not providing a license implies that I am still holding all rights. Regardless, I still don't like the word. I'm not a lawyer, but it feels like it could be debated in court, at the very least, to cause confusion. I'd rather have ARR for a generic "All Rights Reserved" since that's been around since dirt and is extremely clear. I'd rather leave the file for "ARR with these exceptions to the rule."

**Comment by alash3** [comment] 2015-10-26 17:22
The fact that the latest versions of npm support UNLICENSED is fine for me and I now consider this issue closed. After one uses `npm init` and marks their work as UNLICENSED, they can put copyright notices in all their files saying whatever they want, including "All Rights Reserved.", as well as change the package.json to say something other than UNLICENSED.

**Comment by scriptjs** [comment] 2015-10-26 18:01
@iarna On what basis do you feel UNLICENSED would be an appropriate classification for LICENSED code that has been distributed for use under its terms? I am not understanding the tenacity to maintain a rigid system of classification if the manifest cannot allow for the scope of software licenses (open and proprietary) in the real world.

From my view, it is inappropriate to assume that all licensing is classified using SPDX. These are common but not definitive. The package.json as metadata is the source of truth users are searching and examining for their use of software in their projects.

Including an aside to speak of a  LICENSE when you were force to identify in a manifest as UNLICENSED to simply stop the emission of warnings is inappropriate.  Further, UNLICENSED in license metadata would be enough to turn off many developers from the software without further investigation.

Where this  goes wrong is that unless the license is one that exists in SPDX,  you assume no rights are being granting while the software may include a proprietary LICENSE that grants rights and has been distributed with the software to be used under those terms.

Licensing fall into one of three scenarios, not just two that are documented in the link you provided:

1. The license is one classified by SPDX (no warnings when one in SPDX)
2. The license (open or proprietary) is not one not classified by SPDX (currently emits warning: npm WARN EPACKAGEJSON license should be a valid SPDX license expression) UNLICENSED is inappropriate to use in this circumstance. Clearly the software is licensed.
3. The software is unlicensed. A case where UNLICENSED is appropriate. (no warnings > 3.3.1)

What exists currently is a issue for all licenses (proprietary or open) that fall of SPDX which only lists the most common open licenses.

One solution might be to include another manifest property that the license property from being validated against SPDX. ie 
```
spdx: false
```
The test would be for a license to be included, but bypass the test for SPDX validity.

@ergose, the rights imparted by a license are secondary to this discussion since it is up to the LICENSE itself to determine this. At the root of this issue is whether UNLICENSED is appropriate to  attached to code that has a proprietary LICENSE but not one identified by SPDX. UNLICENSED means something entirely different than licensed code.

**Comment by othiym23** [comment] 2015-10-27 01:43
This issue is becoming a magnet for off-topic discussion, and most of the discussion after the issue's resolution doesn't have anything to do with the original question, so I'm locking this issue. Further discussion about the ergonomics of `UNLICENSED` should either go in  #8918 or new issues (especially if you're running `npm@^2.14.8` or `npm@^3.3.9` and are running into issues where `UNLICENSED` isn't working).

That issue also includes explanations of which versions of npm contain support for `UNLICENSED` and `SEE LICENSE IN`, as well as a more general discussion of the rationale of the npm CLI team as to why those features are implemented the way they are.
