### ISSUE TITLE
npm5 unable to install with install.sh script

### ISSUE THREAD

**Issue by alistairjcbrown** [npm/npm#16736] opened 2017-05-26 15:42 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Unable to install npm5 using the hosted install script at https://www.npmjs.com/install.sh

#### How can the CLI team reproduce the problem?

```
export npm_install=5.0.0 && curl -L https://www.npmjs.com/install.sh | sh
```
Output of this command: https://gist.github.com/alistairjcbrown/22dfa12d0bbf9f4ccac49a28288f75ef

Note that running with `npm_install` set to `4.6.1` works as expected

### supporting information:

 - `npm -v` prints: `4.1.1` (though n/a)
 - `node -v` prints: `7.4.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rmg** [comment] 2017-05-26 19:26
Pretty sure this was caused by #12096 removing `cli.js`, which the shell script explicitly calls.

**Comment by rmg** [comment] 2017-05-26 19:28
More specifically, it seems the updated `scripts/install.sh` from that PR hasn't been deployed to `https://www.npmjs.com/install.sh`.

**Comment by zkat** [comment] 2017-05-27 03:46
Ah! Thanks for looking into it. I think this is because npm isn't on the `latest` tag yet, and I thiiiink this, like the docs, are only deployed once that happens. Gonna cc @bcoe and @iarna because they were the last to look at it.

**Comment by benmccann** [comment] 2017-05-29 15:24
What's the plan to update the `latest` tag to 5.0?

**Comment by zkat** [comment] 2017-05-29 17:37
@benmccann: it's going to go on `latest` tomorrow, to coincide with the release of node 8. The node PR already landed.

**Comment by benmccann** [comment] 2017-05-31 00:42
Cool. I see node 8 out. It doesn't look like npm latest is 5.0 yet, but I will keep a look out

**Comment by zkat** [comment] 2017-05-31 00:59
@benmccann should be `latest` now. There was some brief confusion today about coordination with node8, but if node8 is out, we may as well tag it :)

**Comment by zkat** [comment] 2017-05-31 04:01
This is working now. Cheers.

**Comment by aedensixty** [comment] 2017-05-31 04:29
I am still getting this problem?

**Comment by zkat** [comment] 2017-05-31 05:10
Oops I eat my word. It hasn't actually been fixed. Guess this might be a deeper problem :s

**Comment by zkat** [comment] 2017-05-31 05:16
No, it just hasn't been deployed on the site. I've let the website folks know. Cheers 👍

**Comment by zkat** [comment] 2017-05-31 23:14
ok ok. *now* it's published:

```
➜ curl -L https://www.npmjs.com/install.sh | grep cli.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6255  100  6255    0     0  25453      0 --:--:-- --:--:-- --:--:-- 25530
        "$node" bin/npm-cli.js rm npm -gf
        "$node" bin/npm-cli.js install -gf
```

**Closed by zkat** 2017-05-31 23:14 UTC
Labels: npm5, registry
