### ISSUE TITLE
React-Router-Component

### ISSUE THREAD

**Issue by imsger** [npm/npm#10057] opened 2015-10-21 04:41 UTC
Hi I am using react-router-component and am getting an error with installation, the following CLI command:

npm install react-router-component 

spits out this error message:

Error extracting /Users/kal/.npm/react-router-component/0.26.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/kal/.npm/react-router-component/0.26.0/package.tgz'

I went to the directory and the package was already opened already. Still getting an error message. How do I fix this?

Thanks

**Comment by KenanY** [comment] 2015-10-21 04:42
@imsger Is there a `npm-debug.log` file generated that you can upload as a [gist](https://gist.github.com/)?

**Comment by imsger** [comment] 2015-10-21 04:45
sure

since i couldnt upload it thru github here is a file uploader link- http://www.speedyshare.com/MNYd9/npm-debug.log

**Comment by imsger** [comment] 2015-10-21 04:54
I actually have another folder on my computer where i have this exact file in the node_modules package. could i simply copy and paste it into my node_modules package for my new project?

**Comment by othiym23** [comment] 2015-10-21 05:07
This is a 100% reproducible bug (with `npm@3.3.9` in my case), and seems to be related to how `npm@3` handles installing packages when `latest` is set to a prerelease version – from looking at the linked `npm-debug.log`, it appears that the caching code is downloading `react-router-component@0.27.2`, but the installer is trying to unpack and install `react-router-component@0.26.0`, which isn't in the cache, and therefore causes npm to blow up. @iarna will have to take a look at this and verify that my understanding is correct. Thanks for uploading the debug log!

**Comment by imsger** [comment] 2015-10-21 06:18
Ok makes sense. Thanks othiym23!

**Comment by ggrillone** [comment] 2015-10-27 01:00
I ran into the same exact error, using `npm@3.3.9` as well. By specifying the version it seems to have worked: `npm install react-router-component@0.27.2`. btw when trying `npm install react-router-component@0.26.0` it still installed `0.27.2` and threw the same error as mentioned above.

**Comment by fengmk2** [comment] 2015-10-27 05:44
`npm@3.3.6` has this bug too.

**Comment by othiym23** [comment] 2015-10-27 05:51
@iarna is working on a fix, and as it involves fixing what has grown into a fairly sgnificant architectural snarl, it may take a little while to land, so hang in there, everybody.

The issue is that for a long time `npm install package` has meant, in effect, `npm install package@*`, which is frequently, but not always, the same as `npm install package@latest`. One of the cases in which it _isn't_ the same is when `latest` is assigned to a prerelease version, as in this case. What turns this into a crasher is that two different pieces of npm have two different opinions about what happens at this point, and addressing that inconsistency is what's taking a little work to unravel.

**Comment by elvizcacho** [comment] 2015-11-08 21:59
same bug on npm@3.3.12

**Comment by leakingminds** [comment] 2015-12-15 14:10
any solutions so far?

**Comment by krainboltgreene** [comment] 2016-01-19 00:38
@leakingminds: One solution is to install the specific version of what you need. `npm install foo@1.2.3`, this "solved" the issue for me.

@othiym23 I appreciate the concise summary!

**Comment by leakingminds** [comment] 2016-01-19 07:45
@krainboltgreene

Thanks! Worked out :)

**Closed** 2017-06-19 10:32 UTC
Labels: bot-closed, bug
