### ISSUE TITLE
metadata includes developer’s home directory

### ISSUE THREAD

**Issue by Zearin** [npm/npm#14541] opened 2016-11-06 17:29 UTC
Small issue, but I figured I’d report it.  *shrug*

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

If I do `npm -g info npm@latest`, under the `man` key, all entries begin with `/Users/rebecca/code/release/`.

#### How can the CLI team reproduce the problem?

1. `npm -g info npm@latest man`
1. See developer’s paths of man pages

### Supporting Information:

 - **`npm -v` prints:** 3.10.9
 - **`node -v` prints:** v7.0.0
 - **`npm config get registry` prints:** https://registry.npmjs.org/
 - **Windows, OS X/macOS, or Linux?:** OS X/macOS “El Capitan” (10.11.6)

**Comment by KenanY** [comment] 2016-11-06 17:36
Maybe a duplicate of https://github.com/npm/npm/issues/14293.

**Comment by legodude17** [comment] 2016-11-07 01:50
Those are very similar but the problem in #14293 is that it fails to `man` `npm`, whereas this one is reporting the problem. As @zkat said, #14293 is most likely a problem with that user's `man` setup.

**Comment by helio-frota** [comment] 2016-11-24 18:37
When I run: `npm -g info npm@latest`
I see this:

```
 man: 
   [ '/Users/ogd/Documents/projects/npm/npm/man/man1/npm-access.1',
     '/Users/ogd/Documents/projects/npm/npm/man/man1/npm-adduser.1',
     '/Users/ogd/Documents/projects/npm/npm/man/man1/npm-bin.1',
```

```
npm -v
3.10.9
node -v
v7.2.0
```

**Comment by legodude17** [comment] 2016-11-27 21:48
Does `man npm`? Still work?

**Comment by helio-frota** [comment] 2016-11-28 01:34
Not found:
```
[hf@archT440 ~]$ man npm
No manual entry for npm
```

**Comment by legodude17** [comment] 2016-11-28 21:34
Then this is a duplicate of #14293. Which one should be closed?

**Closed** 2017-06-19 04:18 UTC
Labels: bot-closed, bug
