### ISSUE TITLE
installing polymer-cli on windows 10 pro 64-bit operating system

### ISSUE THREAD

**Issue by udyizhar** [npm/npm#14212] opened 2016-10-08 07:55 UTC
#### I'm opening this issue because:
- [x] npm is crashing.
- [x] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I try to install polymer-cli (npm install -g polymer-cli)
on windows 10 pro 64-bit operating system...
#### How can the CLI team reproduce the problem?

<details>

```
D:\dev>npm install -g polymer-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "polymer-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for C:\Users\udyizhar\AppData\Local\Temp\npm-5088-1d114781\registry.npmjs.org\sshpk\-\sshpk-1.10.1.tgz
npm ERR! Expected: 30e1a5d329244974a1af61511339d595af6638b0
npm ERR! Actual:   28198962127d351119746ea6677861a5f396ed63
npm ERR! From:     https://registry.npmjs.org/sshpk/-/sshpk-1.10.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\npm-debug.log
```

</details>

**Comment by legodude17** [comment] 2016-10-10 22:38
Try running `npm cache clean`.

**Comment by zkat** [comment] 2016-12-09 00:36
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:36 UTC
Labels: network, support
