### ISSUE TITLE
Installing NPM 5.0.2 on Node.JS Docker Image fails.

### ISSUE THREAD

**Issue by CyberiumShadow** [npm/npm#16974] opened 2017-06-05 00:09 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Attempts to run `npm -g install npm@latest` to update from npm 5.0.0 to npm 5.0.2 appears to succeed but actually fails as running npm -v produces
```js
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

#### How can the CLI team reproduce the problem?
Create a Docker Container using the official node image
Attach to the bash shell for the container and run `npm -v` (Should return 5.0.0)
Run `npm -g install npm@latest`
Run `npm -v` (should return 5.0.2 but doesn't)
Error occurs at above step.

### supporting information:

 - `npm -v` prints: (before install) 5.0.0    (after install): errors out
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:  Moldova
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kahwee** [comment] 2017-06-05 03:55
Sounds similar to #16807 and #16952

**Comment by zkat** [comment] 2017-06-05 16:56
Closing as duplicate of https://github.com/npm/npm/issues/16807

**Closed as completed by zkat** 2017-06-05 16:56 UTC
