### ISSUE TITLE
"npm install -g ionic" hangs on "unlock" step

### ISSUE THREAD

**Issue by anilmujagic** [npm/npm#9597] opened 2015-09-16 08:47 UTC
I tried to install ionic on Windows 7 machine as follows:

    npm install -g cordova

which went well, so I continued with this:

    npm install -g ionic

but it hangs. So I stopped it, removed it and tried again with **--verbose** flag to get more details and to try to trick it, but no success. Tried also **-ddd** flag, but still hangs. Step on which it hangs is:

    npm verb unlock done using C:\Users\myusername\AppData\Roaming\npm-cache\_locks\npm-7933e7d5b0e47ece.lock for C:\Users\myusername\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\npm

Any clues? I'm really out of ideas...

My environment:

    $ node -v
    v0.12.7

    $ npm -v
    2.11.3

**Comment by fabiosussetto** [comment] 2015-09-16 11:17
@anilmujagic I'm experiencing the same issue by installing other packages within a Docker container. Check this out: https://github.com/npm/npm/issues/7862

**Comment by othiym23** [comment] 2015-09-21 21:31
Closing as a duplicate of #7862.

**Closed by othiym23** 2015-09-21 21:31 UTC
