### ISSUE TITLE
scoped packages don't appear to be bundled

### ISSUE THREAD

**Issue by sam-github** [npm/npm#8341] opened 2015-05-23 05:50 UTC
See https://github.com/strongloop/strong-build/issues/27#issuecomment-104471598

excerpt:

```
{
  "name": "@ylopo/geocoder",
  "version": "0.2.0",
  "description": "Testing scoped dependencies.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node ."
  },
  "author": "Some Guy",
  "license": "None",
  "dependencies": {
    "@ylopo/service-logger": "^1.3.0",
    "MD5": "^1.2.1"
  },
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-jshint": "^0.10.0"
  },
  "bundleDependencies": [
    "@ylopo/service-logger",
    "MD5"
  ]
}
```

npm pack won't bundle `@ylopo/service-logger`

/cc @barwin

**Comment by julien-f** [comment] 2015-06-03 15:44
Same issue here.

**Comment by zkat** [comment] 2015-06-24 22:10
Dupe of #8614

**Closed by zkat** 2015-06-24 22:10 UTC
