### ISSUE TITLE
so many ERRs installing angular2-seed

### ISSUE THREAD

**Issue by Miss-Git** [npm/npm#13484] opened 2016-07-26 06:10 UTC
Im tryng to install the newst angular2 seed but I'm having the following problems when using npm start:

```
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@1.0.0 server: `webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 3000  --content-base src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@1.0.0 server script 'webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 3000  --content-base src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --colors --progress --display-error-details --display-cached --port 3000  --content-base src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myname\Desktop\Life\UI & UX\Codes\angular2-seed-master\npm-debug.log

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@1.0.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@1.0.0 start script 'npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myname\Desktop\Life\UI & UX\Codes\angular2-seed-master\npm-debug.log
```

Help Please! :((

**Comment by KenanY** [comment] 2016-07-26 14:38
@Miss-Git Should this be closed in favor of https://github.com/npm/npm/issues/13485?

**Comment by othiym23** [comment] 2016-07-27 23:17
Closing as duplicate of #13485.

**Closed by othiym23** 2016-07-27 23:17 UTC
Labels: support
