### ISSUE TITLE
npm install hangs on a private repository + branch

### ISSUE THREAD

**Issue by jonursenbach** [npm/npm#3889] opened 2013-09-12 16:58 UTC
So I'm working with some private repositories that I want to pull in via npm. This is my dependencies array:

    "dependencies": {
        "repo-name": "git+ssh://git@github.com:privateUsername/repo-name.git#develop"
    }

Running an ```npm install``` with this, npm just hangs indefinitely (I sat there for 10 minutes waiting for it to do something). Removing ```#develop```, it runs just fine.

Any ideas as to what's up?

**Comment by smikes** [comment] 2015-02-18 13:07
Is this still a problem for you?

The handling of git credentials has been improved a bit in current versions of `npm` -- can you update your `npm` to the latest version and check if the problem persists?

Have you looked into using a credential cache <http://git-scm.com/docs/git-credential-cache> to hold your `git` https credentials?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we may close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by mike-lang** [comment] 2015-02-19 02:33
I can't say if the original problem remains.  I switched over to SSH using `ssh-agent` and `ssh-add` together with a private key and haven't had any problems with it.

**Comment by othiym23** [comment] 2015-02-19 07:39
So the original issue should have been resolved a while ago (and also, thanks to the fallbacks in the GitHub caching code, you should be able to use GitHub shortcut syntax in `package.json` to depend on private repositories), I'm going to close this as resolved.

**Closed by othiym23** 2015-02-19 07:39 UTC
Labels: bug, support

**Comment by jonursenbach** [comment] 2015-02-19 17:04
I can confirm my original issue no longer exists.

**Comment by e-oz** [comment] 2016-03-01 22:24
Experiencing this issue, npm 3.6.0, node v5.5.0, OS X 10.11.2. If somebody knows workaround - fix - please let me know.

**Comment by ericmartinezr** [comment] 2016-03-02 02:05
Happening the same

Node 5.7.0
Npm 3.6.0

Running `npm install angular/angular#buid-js` hangs, same happens with `npm install git://github.com/angular/angular.git#build-js`

No log nor anything. Anyway to debug this?

**Comment by suluke** [comment] 2016-04-27 08:53
I am running `npm i --save-dev git+https://git@github.com:twbs/bootstrap.git#v4-dev` (also without `#v4-dev`) and get stuck at `normalizeTree -> fetchOth`. This also happened on the machines of 2 of my colleagues, we're all running Arch Linux with npm version 3.8.7 and node 5.11.0.

**Comment by suluke** [comment] 2016-04-27 08:55
@e-oz we currently work around this issue by using the github-provided tarballs, like e.g. `https://github.com/twbs/bootstrap/tarball/v4-dev`. Maybe your git hosting solution provides something similar?

**Comment by ericmartinezr** [comment] 2016-04-30 22:51
@othiym23 would you mind to re-open this issue? This is still happening (one year after the issue was closed).

@suluke your workaround works perfectly! Thank you so much!

**Comment by lajohnston** [comment] 2016-11-03 16:55
For me, the indefinite hanging was caused by git-credential-cache prompting for my credentials in the background. I don't require the credential cache so I resolved the issue by editing my git global config (git config --global --edit) and removing the [credential] settings

**Comment by ponelat** [comment] 2017-05-22 14:34
I had a similar issue ( npm appeared to hang ), but in my case. It was due to the size of a `https://github.com/xxx/xxx#aaa` dependency. npm _seemed_ to have cloned the entire repo, which took ages, and didn't have any indication. I fixed by using the tarball approach ( thanks @suluke ).
