### ISSUE TITLE
I get the following error when I do npm install on cmd .npm ERR! shasum check failed for C:\User\JULIET\Appdata\Local\Temp\npm-2440-ba288d18\registry.npmjs.org\hoek\-\hoek-2.16.3.tgz\ npm ERR! Expected: 20bb7403d3cea398e91dc4710a8ff1b827a25ed npm ERR! Actual:   00aee45b2a489aba9236e992af7bde926ee209da npm ERR! From:     https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz npm ERR! npm ERR! If you need help, you may report this error at: npm ERR!     <https://github.com/npm/npm/issues>  npm ERR! Please include the following file with any support request: npm ERR!   C:\Users\julietteEssence\MainApplicationFolder\Pracices\AngularCourse\npm-debug.log

### ISSUE THREAD

**Issue by juliettegodyere** [npm/npm#14611] opened 2016-11-13 00:43 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I get the following error when I do npm install on cmd .

```
npm ERR! shasum check failed for C:\User\JULIET\Appdata\Local\Temp\npm-2440-ba288d18\registry.npmjs.org\hoek\-\hoek-2.16.3.tgz\ 
npm ERR! Expected: 20bb7403d3cea398e91dc4710a8ff1b827a25ed 
npm ERR! Actual:   00aee45b2a489aba9236e992af7bde926ee209da 
npm ERR! From:     https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz 
npm ERR! 
npm ERR! If you need help, you may report this error at: 
npm ERR!     <https://github.com/npm/npm/issues>  
npm ERR! Please include the following file with any support request: 
npm ERR!   C:\Users\julietteEssence\MainApplicationFolder\Pracices\AngularCourse\npm-debug.log
```

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2016-11-14 21:43
Try running `npm cache clean`.

**Comment by zkat** [comment] 2016-12-09 00:33
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:33 UTC
Labels: shasum, support
