### ISSUE TITLE
Rename "prepublish" lifecycle script

### ISSUE THREAD

**Issue by isaacs** [npm/npm#6887] opened 2014-12-10 05:09 UTC
Original suggestion: https://github.com/npm/npm/issues/3059#issuecomment-60379536

People get confused because "prepublish" is badly named.  It looks like something that should only happen right before sending your code to npm.

However, really, what it means is, "do all the platform-independent tasks necessary to turn this package from its raw source code state into its actual use state".

That's why it's done on an arg-less `npm install` at the top level.  The deps in that case come from npm; they've already been "prepublished".  However, if there's some platform-independent setup that's required to use a module (eg, compile coffee-script), and you don't do that on initial checkout and setup, then contributors will be upset when all the tests fail.

If we rename it to "build", then we're going to run the risk of people adding stuff like `node-gyp build` for example, which *isn't* platform-agnostic.  Also, if we *don't* run `scripts.build` on install, people will be upset that their package isn't usable immediately after installation.

Some other terrible names: `devBuild`, `platformAgnosticBuild`, `toplevelBuild`

Candidate strategy for renaming it, should we decide to do that:

1. Add `scripts.whatever`, a duplicate of `scripts.prepublish`
2. Deprecate `scripts.prepublish`
3. Wait forever, or until `scripts.prepublish` no longer used, whichever comes first.
4. Remove `scripts.prepublish`

**Comment by balupton** [comment] 2015-04-05 04:06
Just encountered this today, expecting `prepublish` to run only before publish (rather than the silly local npm install nonsense - it really is nonsense, it makes no sense for something named `prepublish`).

Can we:

- FIX `prepublish` to only run before publish (say in npm v3)
- Add `prelocalinstall`, and `postlocalinstall` if anyone actually considers that use case important
- If someone wants a `prelocalinstall` and `prepublish` (the current `prepublish)` then they can call `prepublish` in the `prelocalinstall` script.

**Comment by dominictarr** [comment] 2015-07-01 18:38
I use `prepublish` to prevent myself pushing broken modules to the registry. My default prepublish script is `npm ls && npm test`. Of course, this does not need to run after `npm install .`

I think it's fine to use prepublish to compile your coffee script, but if you are do `npm install .` you are doing dev and it seems fine to allow them to manually run prepublish...

**Comment by Demurgos** [comment] 2016-05-08 11:28
Looks like this issue can be closed (duplicate of the newer #10074 ) ?

**Comment by othiym23** [comment] 2016-09-17 02:12
@demurgos Yeah, that's a good idea. Closing in favor of #10074, which has recent updates that are germane to the participants on this issue. Thanks to all for their contributions!

**Closed by othiym23** 2016-09-17 02:12 UTC
Labels: feature-request
