### ISSUE TITLE
npm ERR issues when I try to run the following command

### ISSUE THREAD

**Issue by kanajam** [npm/npm#13950] opened 2016-09-13 18:10 UTC
yo angular

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v3.10.7

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.nodejs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanajam/angular-project/npm-debug.log

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Please help me to get rid of this issue.
Struggling from last two days on windows platform as well as on mac.

Your help would be appreciated.

Regards,
Vijay Kanajam

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2016-09-13 23:47
This might be more of an issue with `generator-angular`, not npm. Have you filed a bug there?

**Comment by kanajam** [comment] 2016-09-14 07:13
I'm new to npm and as per document trying to setup yeoman with generator-angular as per the given url.

https://github.com/yeoman/generator-angular/
https://www.airpair.com/js/using-angularjs-yeoman
http://yeoman.io/codelab/

Could you please check and let me know if you have any ideas to resolve the issue.

I filled the bug over there as well just now.

**Comment by heijmans** [comment] 2016-09-14 20:12
This is a duplicate of #13957 . I would suggest that this issue should be closed. Please take a look at https://github.com/npm/npm/issues/13957#issuecomment-247134869 to see if it fixes your problem.

**Comment by KenanY** [comment] 2016-09-15 01:47
Alright, let's move this to https://github.com/npm/npm/issues/13957.

**Closed by KenanY** 2016-09-15 01:47 UTC
