### ISSUE TITLE
> (node-gyp rebuild 2> builderror.log) || (exit 0)

### ISSUE THREAD

**Issue by danfeng** [npm/npm#8675] opened 2015-06-25 23:39 UTC
```
npm ERR! Expected: 1dacc91458f2197c362d774d2cbf111680f86ec2
npm ERR! Actual:   b842f75b54dbd6479ae4f1fd1c7c65a2c1c75b7b
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "phonegap"
npm ERR! cwd /System/Library/Frameworks/Python.framework/Versions
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
```

**Comment by zkat** [comment] 2016-12-09 00:57
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:57 UTC
Labels: shasum, support
