### ISSUE TITLE
npm 2.7.4, bundledDependencies + devDep + dep === missing dep

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#7887] opened 2015-04-08 18:36 UTC
* ember-cli depends on bower
* ember-cli depDependends on github
* ember-cli bundles bower
* bower depends on github

after `npm package` `github` module appears to be missing

```
git clone https://github.com/ember-cli/ember-cli.git
cd ember-cli
git checkout v0.2.3
npm pack
tar ember-cli-0.2.3.tgz
cd package
npm ls github

ember-cli@0.2.3 /Users/stefanpenner/src/ember-cli/package
└── (empty)
```

various debugging checks
-----------------------------------

`bower` is a dependency and bundle dependency of `ember-cli`
```sh
 % cat package.json | jq '.bundledDependencies' | grep 'bower"' 
=> "bower"
 % cat package.json | jq '.dependencies' | grep 'bower"' 
=> "bower"
```

`github` is a devDependency of `ember-cli`

```sh
 % cat package.json | jq '.devDependencies' | grep 'github"'
=>  "github": "^0.2.3",
```

`github` is a dependency of `bower`

```sh
% cat node_modules/bower/package.json | jq '.dependencies' | grep 'github"'
=>    "github": "^0.2.3"
```

**Comment by stefanpenner** [comment] 2015-04-08 18:37
trying with `2.7.5` right now, just waiting for pack/install

**Comment by wagenet** [comment] 2015-04-08 18:38
This is extremely aggravating since it prevents `npm shrinkwrap` from working.

**Comment by stefanpenner** [comment] 2015-04-08 20:09
same issue on 2.7.5

**Comment by othiym23** [comment] 2015-04-08 20:18
I almost hate to ask, but have you tried with `npm@2.7.6`? There are a bunch of small tweaks to git handling in `npm@2.7.6` that might affect this, although this smells like a race condition, and I have no idea what could be causing it.

**Comment by wagenet** [comment] 2015-04-08 21:21
@othiym23 this isn't actually a git handling issue. It's the github package, but everything is via the npm repository.

**Comment by stefanpenner** [comment] 2015-04-08 21:40
> I almost hate to ask, but have you tried with npm@2.7.6?

I will try 2.7.6.

^^ also contains instructions if someone at NPM wants to dig into this.

**Comment by othiym23** [comment] 2015-04-08 21:43
I won't have time to get to this for a week or so (and it's also something that is probably fixed in `multi-stage` / `npm@3`). It looks like it's probably a race condition, and those are tremendously difficult to isolate and fix, even if you have a clear repro case. If you can figure out what's going on here and capture it in a minimal failing test, that will speed things up a lot, but as it is, I've just plain got a lot on my plate right now.

**Comment by stefanpenner** [comment] 2015-04-08 21:54
> is probably fixed in multi-stage / npm@3).

once https://github.com/npm/npm/issues/7816 is resolved, i can try with `multi-stage`

**Comment by stefanpenner** [comment] 2015-04-08 21:58
> I will try 2.7.6.

same issue

**Comment by othiym23** [comment] 2015-04-08 22:00
Thanks for checking! This will eventually get fixed in `npm@2`, just not right away.

**Comment by stefanpenner** [comment] 2015-04-08 22:11
i attempted a reduced cased, but was not successful. Maybe i'll have more time later this week

**Comment by othiym23** [comment] 2015-04-08 23:18
`bundledDependencies` is too clever for its own good. There are actually two issues here: 

1. The bundled dependency is erroneously being omitted from the package tarball because the packer has incomplete information about where the dependency is used – it doesn't notice that a subdependency of a regular dependency uses this module, which is installed at the top level because it's a `devDependency`. This is the root cause.
1. The installer should notice that the dependency is missing from the bundled list and install it. Fixing this will work around 1, and needs to be done anyway because basically every extant npm version has the problem in 1. Also it's probably a lot easier to fix.

Context (distilled down from a long conversation between @iarna and me, including a freakish amalgamation of our thoughts):

The problem is that you have a direct `devDependency` that's also a sub dependency (or sub-sub dependency or...) of a regular `dependency`. Because the `devDependency` doesn't get included in the bundle – even though it's also required by a non-`devDependency` – installing a bundle packed this way will yield an invalid tree. The packaged module is now missing a subdep, which will never be installed by npm@2. (It's more subtle in npm@3 as it'll fix up the missing dependency for you at install time.) So the root cause is a problem with packing, not installation.

Solution 2 doesn't look easy because the `npm@2` installer doesn't recurse into already installed modules, bundled deps are treated as already installed. That is, npm extracts the package, then goes through its deps. If it finds one in `node_modules` that matches the version, all's good and we leave it be. 

But this isn't that big a deal, because at install time, we use `read-installed` when bundledDeps are involved to figure out what's actually been included in the package. It wouldn't be that much additional trouble to validate that everything already installed matches what's in bundledDependencies. If npm tracks both the list of modules it believes to be bundled and modules it's already seen as part of the installation process, it can print a warning and install the modules that are in the former but not in the latter. And also whine piteously that somebody has confused it (where by "somebody has confused it" I mean "it has confused itself"). This helps unbreak broken bundled packs, which is the thing breaking `ember-cli`.

That said, this is still a lot easier said than done, given the complexity of `lib/install.js` with `npm@2` (which is the main reason the `multi-stage` branch exists). This needs to get fixed in `npm@2` for long-term support reasons, but as I said above, it will take me a little while to find the cycles to do it. If somebody else wants to take a whack at it, a patch would be very welcome.

**Comment by stefanpenner** [comment] 2015-04-08 23:57
Thanks for digging in.

**Comment by othiym23** [comment] 2015-08-31 22:32
I'm pretty sure that `npm@3` addresses this, but I'll let @stefanpenner and @iarna close the loop on this, and I'm pulling off the `next-patch` tag because we're not using those anymore.

**Comment by iarna** [comment] 2015-10-28 22:01
This was indeed explicitly addressed in `npm@3`. And now that `npm@2` is in LTS, we aren't planning to fix this there.

**Closed by iarna** 2015-10-28 22:01 UTC
Labels: bug, patch-welcome

**Comment by stefanpenner** [comment] 2015-10-28 22:26
:+1:
