### ISSUE TITLE
fsevents package on windows

### ISSUE THREAD

**Issue by mjasnikovs** [npm/npm#18453] opened 2017-09-08 04:23 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
fsevent package - it should not be installed on the windows. $%#@, last 3 years working with npm i always have problems with this package! Please do not install packages on OS where it will not even work. I don't need this packagde, it alweys come as some dempendency. 

#### How can the CLI team reproduce the problem?
```
1075 verbose unlock done using C:\Users\emja\AppData\Roaming\npm-cache\_locks\staging-bb83b07f7a5595fd.lock for c:\hub\aizkraukle-client\node_modules\.staging
1076 verbose stack Error: EPERM: operation not permitted, rmdir 'c:\hub\aizkraukle-client\node_modules\fsevents\node_modules'
1077 verbose cwd c:\hub\aizkraukle-client
1078 verbose Windows_NT 6.1.7601
1079 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1080 verbose node v8.3.0
1081 verbose npm  v5.3.0
1082 error path c:\hub\aizkraukle-client\node_modules\fsevents\node_modules
1083 error code EPERM
1084 error errno -4048
1085 error syscall rmdir
1086 error Error: EPERM: operation not permitted, rmdir 'c:\hub\aizkraukle-client\node_modules\fsevents\node_modules'
1086 error  { Error: EPERM: operation not permitted, rmdir 'c:\hub\aizkraukle-client\node_modules\fsevents\node_modules'
1086 error   stack: 'Error: EPERM: operation not permitted, rmdir \'c:\\hub\\aizkraukle-client\\node_modules\\fsevents\\node_modules\'',
1086 error   errno: -4048,
1086 error   code: 'EPERM',
1086 error   syscall: 'rmdir',
1086 error   path: 'c:\\hub\\aizkraukle-client\\node_modules\\fsevents\\node_modules' }
1087 error Please try running this command again as root/Administrator.
1088 verbose exit [ -4048, true ]
```
NPM trying to remove non existing directory. Sometimes it works, maybe race condition?

I fix this issue
 
```
npm install --no-optional
```

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kherona** [comment] 2017-09-08 08:27
I am facing this issue as well since upgrading npm.

When installing it gets stuck at postinstall, regardless of what I am trying to install, also each time it gets stuck at different node_modules path:
/ postinstall: info lifecycle timepicker@1.11.11~postinstall: timepicker@1.11.11

Then gives the following error:
npm ERR! path D:\Projects\VueApp\node_modules\fsevents\node_modules\assert-plus\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\Projects\VueApp\node_modules\fsevents\node_modules\assert-plus\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\Projects\VueApp\node_modules\fsevents\node_modules\assert-plus\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\Projects\\VueApp\\node_modules\\fsevents\\node_modules\\assert-plus\\package.json\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\Projects\\VueApp\\node_modules\\fsevents\\node_modules\\assert-plus\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Moham\AppData\Roaming\npm-cache\_logs\2017-09-08T08_26_21_009Z-debug.log

D:\Projects\VueApp>npm -v
5.4.0

D:\Projects\VueApp>node -v
v6.11.1

**Comment by martincostello** [comment] 2017-09-08 08:59
See #18287.

**Comment by marcins** [comment] 2017-09-08 13:12
This is probably a duplicate of #17671. I've made a lot of notes on that issue as I've worked to track down the cause.

**Comment by tomihawk** [comment] 2017-09-08 18:27
After updating npm to 5.4.1 I started having the same problem with npm update.  I didn't have a problem with fsevents before but now on "npm update firebase" it creates a new fsevents folder under node_modules with a load of node_modules of its own, all empty from what I can see and then fails when it tries to delete things in what looks like a post-install script.  Thankfully the --no-optional works for npm update as well, even though it's not documented on the command's page.

**Closed as completed** 2017-09-15 00:42 UTC
Labels: npm5
