### ISSUE TITLE
nyc cannot find npm-cli.js

### ISSUE THREAD

**Issue by smolyakoff** [npm/npm#15231] opened 2016-12-15 15:38 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

External utility (`nyc`) cannot find globally installed npm on Windows. It was able to find it until I upgraded npm to the latest version using `npm-windows-upgrade`. 

#### How can the CLI team reproduce the problem?

I have a `package.json` with a following npm script.
```json
{
  "scripts": {
    "test:unit": "mocha src/**/*.test.js",
    "coverage": "cross-env BABEL_ENV=test nyc npm run test:unit",
  }
}
```

When I run the script from a command line by typing `npm run coverage` I get the following error:
```
Error: Cannot find module 'D:\Projects\Work\project-name\node_modules\.bin\node_modules\npm\bin
\npm-cli.js'
at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Function.Module.runMain (module.js:604:10)
    at Function.runMain (C:\Users\C.Smolyakov\.node-spawn-wrap-83020-9425fd630a6a\node:40:10)
    at Object.<anonymous> (D:\Projects\Work\project-name\node_modules\nyc\bin\wrap.js:22:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

It used to work as expected when I had version 2.x. I don't remember the exact version which was installed. 

When I just run `npm run test:unit` it is working as expected.

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by legodude17** [comment] 2016-12-15 17:00
This appears to be a problem with `nyc`, and not with `npm`.

**Comment by zkat** [comment] 2016-12-15 21:51
Closing as dupe of https://github.com/tapjs/spawn-wrap/issues/41

**Closed by zkat** 2016-12-15 21:51 UTC

**Comment by markdemich** [comment] 2017-10-14 10:57
Has anyone found a workaround for this?
