### ISSUE TITLE
npm install express

### ISSUE THREAD

**Issue by wj704** [npm/npm#7809] opened 2015-03-31 14:41 UTC
hi ,all:
I am running npm install -g express, it will fail at the npm install step and output the following:
npm ERR! 
this is the npm-debug.log
```
29 error Windows_NT 6.1.7600
30 error argv "E:\\Program Files\\nodejs\\\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
31 error node v0.12.1
32 error npm  v2.5.1
33 error Unexpected end of input
33 error {"_id":"express",
```

**Comment by KenanY** [comment] 2015-03-31 14:43
Duplicate of https://github.com/npm/npm/issues/7808 ?

**Comment by iarna** [comment] 2015-04-11 01:40
Closing as duplicate.

**Closed by iarna** 2015-04-11 01:40 UTC
