### ISSUE TITLE
pacaur update

### ISSUE THREAD

**Issue by cws-khuntly** [npm/npm#9731] opened 2015-09-23 12:04 UTC
not sure if this has already been submitted -

:: Starting AUR upgrade...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1):

Name             Old Version  New Version

aur/atom-editor               1.0.15-1                  

:: Proceed with installation? [Y/n] y
:: Retrieving package(s)...

:: View atom-editor PKGBUILD? [Y/n] 
:: atom-editor PKGBUILD viewed
:: Checking atom-editor integrity...
==> Making package: atom-editor 1.0.15-1 (Wed Sep 23 07:55:57 EDT 2015)
==> Retrieving sources...
  -> Found v1.0.15.tar.gz
  -> Found atom-python.patch
==> Validating source files with sha256sums...
    v1.0.15.tar.gz ... Passed
    atom-python.patch ... Passed
:: Building atom-editor package(s)...
==> Making package: atom-editor 1.0.15-1 (Wed Sep 23 07:56:05 EDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v1.0.15.tar.gz
  -> Found atom-python.patch
==> Validating source files with sha256sums...
    v1.0.15.tar.gz ... Passed
    atom-python.patch ... Passed
==> Extracting sources...
  -> Extracting v1.0.15.tar.gz with bsdtar
==> Starting prepare()...
patching file atom.sh
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Node: v4.1.1
npm: v3.3.3
Installing build modules...
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/bin/npm" "--userconfig=/tmp/pacaurtmp-khuntly/atom-editor/src/atom-1.0.15/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.3
npm ERR! code EREADFILE

npm ERR! Error extracting /home/khuntly/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/khuntly/.atom/.npm/cson-safe/1.0.4/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/pacaurtmp-khuntly/atom-editor/src/atom-1.0.15/build/npm-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
:: atom-editor cleaning skipped
:: failed to build atom-editor package(s)

Here's the last few lines of the log (I don't see a way to actually attach it ?)

28343 silly addNamed cson-safe@1.0.5
28344 verbose addNamed "1.0.5" is a plain semver version for cson-safe
28345 silly cache afterAdd cson-safe@1.0.5
28346 verbose afterAdd /home/khuntly/.atom/.npm/cson-safe/1.0.5/package/package.json not in flight; writing
28347 verbose afterAdd /home/khuntly/.atom/.npm/cson-safe/1.0.5/package/package.json written
28348 silly rollbackFailedOptional Starting
28349 silly rollbackFailedOptional Finishing
28350 silly runTopLevelLifecycles Starting
28351 silly runTopLevelLifecycles Finishing
28352 silly install printInstalled
28353 verbose stack Error: Error extracting /home/khuntly/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/khuntly/.atom/.npm/cson-safe/1.0.4/package.tgz'
28353 verbose stack     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:276:10)
28353 verbose stack     at emitOne (events.js:77:13)
28353 verbose stack     at ReadStream.emit (events.js:169:7)
28353 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
28353 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
28353 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
28354 verbose cwd /tmp/pacaurtmp-khuntly/atom-editor/src/atom-1.0.15/build
28355 error Linux 4.1.6-1-ARCH
28356 error argv "/usr/bin/node" "/bin/npm" "--userconfig=/tmp/pacaurtmp-khuntly/atom-editor/src/atom-1.0.15/build/.npmrc" "install" "--loglevel" "error"
28357 error node v4.1.1
28358 error npm  v3.3.3
28359 error code EREADFILE
28360 error Error extracting /home/khuntly/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/khuntly/.atom/.npm/cson-safe/1.0.4/package.tgz'
28361 error If you need help, you may report this error at:
28361 error     <https://github.com/npm/npm/issues>
28362 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2015-09-23 20:34
Looks like a duplicate of https://github.com/npm/npm/issues/9725.

**Comment by snopeks** [comment] 2015-11-04 23:21
Hello @cws-khuntly, I'm closing as a duplicate of #9725 but if this turns out to be something else let us know, we'll be happy to reopen.

**Closed by snopeks** 2015-11-04 23:21 UTC
