### ISSUE TITLE
Not able to install cordova 

### ISSUE THREAD

**Issue by shashank080892** [npm/npm#15415] opened 2017-01-06 11:59 UTC
[npm-debug.txt](https://github.com/npm/npm/files/689817/npm-debug.txt)
#### I'm opening this issue because:

not able to install cordova was on open internet still i am facing issues .

getting error i dont understand . attaching log file.
[npm-debug.txt](https://github.com/npm/npm/files/689815/npm-debug.txt)

 npm ERR! shasum check failed for C:\Users\VIKAS1~1.KUM\AppData\Local\Temp\npm-88
56-fd17bad9\registry.npmjs.org\npm\-\npm-2.15.11.tgz
npm ERR! Expected: 350588fba9cd8d384cf9a6e8dc0fef0f94992b7c
npm ERR! Actual:   011fdfbad4d9098d7e77fcec26802d60d713ae8e
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.15.11.tgz
npm ERR!

**Comment by Ranga5115** [comment] 2017-01-06 15:27
Same issue with me

**Comment by Charlotteis** [comment] 2017-01-06 17:03
Duplicate of https://github.com/npm/npm/issues/14626

Please update your version of npm to the latest version:

```
npm install -g npm@latest
```

🌸

**Comment by KenanY** [comment] 2017-02-03 13:10
Closing as abandoned.

**Closed by KenanY** 2017-02-03 13:10 UTC
