### ISSUE TITLE
code ELIFECYCLE Exit status 1 at EventEmitter.<anonymous> 

### ISSUE THREAD

**Issue by sirsquall** [npm/npm#17936] opened 2017-07-26 09:00 UTC
#### I'm opening this issue because:

I'm using the boilerplate : https://github.com/vuejs-templates/pwa/tree/master/template
and when I run e2e to fire the tests on my mac everything is working fine, but not on my Jenkins, and I don't konw why

  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

```
 0 info it worked if it ends with ok
1 verbose cli [ '/jenkins/workspace/Xxx/vue/node/node',
1 verbose cli   '/var/lib/jenkins/workspace/Xxx/vue/node/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e' ]
2 info using npm@4.6.1
3 info using node@v7.10.1
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle xxx@1.0.0~pree2e: xxx@1.0.0
6 silly lifecycle xxx@1.0.0~pree2e: no script for pree2e, continuing
7 info lifecycle xxx@1.0.0~e2e: xxx@1.0.0
8 verbose lifecycle xxx@1.0.0~e2e: unsafe-perm in lifecycle true
9 verbose lifecycle xxx@1.0.0~e2e: PATH: /jenkins/workspace/Xxx/vue/node/node_modules/npm/bin/node-gyp-bin:/jenkins/workspace/Xxx/vue/node_modules/.bin:/var/lib/jenkins/wo
rkspace/Xxx/vue/node:/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/3.3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:
10 verbose lifecycle xxx@1.0.0~e2e: CWD: /jenkins/workspace/Xxx/vue
11 silly lifecycle xxx@1.0.0~e2e: Args: [ '-c', 'node test/e2e/runner.js' ]
12 silly lifecycle xxx@1.0.0~e2e: Returned: code: 1  signal: null
13 info lifecycle xxx@1.0.0~e2e: Failed to exec e2e script
14 verbose stack Error: xxx@1.0.0 e2e: `node test/e2e/runner.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/jenkins/workspace/Xxx/vue/node/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/jenkins/workspace/Xxx/vue/node/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid xxx@1.0.0
16 verbose cwd /jenkins/workspace/Xxx/vue
17 verbose Linux 3.13.0-105-generic
18 verbose argv "/jenkins/workspace/Xxx/vue/node/node" "/var/lib/jenkins/workspace/Xxx/vue/node/node_modules/npm/bin/npm-cli.js" "run" "e2e"
19 verbose node v7.10.1
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error xxx@1.0.0 e2e: `node test/e2e/runner.js`
23 error Exit status 1
24 error Failed at the xxx@1.0.0 e2e script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: v7.10.1
 - `node -v` prints: v4.6.1
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux OS name: "linux", version: "3.13.0-105-generic", arch: "amd64", family: "unix"

**Comment by kenany** [comment] 2017-07-26 14:07
All `npm` is doing here is letting you know that `node test/e2e/runner.js` returned an error code on your Jenkins machine. It's probably just something to do with the difference in environments, but since this is not caused by `npm` I'm gonna close this. Good luck!

**Closed as completed by kenany** 2017-07-26 14:07 UTC
Labels: support
