### ISSUE TITLE
Cannot Install angular-cli on Mac

### ISSUE THREAD

**Issue by romaroid** [npm/npm#14165] opened 2016-10-03 17:33 UTC
Cannot Install angular-cli on Mac

  - npm is crashing.

I get this error:

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

At first I had 4.6.0 version of node, then I updated to v6.7.0 but error still appears

 - node v6.7.0
 - npm  v3.10.8
 - OS X

**Comment by KenanY** [comment] 2016-10-03 17:44
Another duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-10-03 17:44 UTC
Labels: support
