### ISSUE TITLE
EPEERINVALID with shrinkwrap in npm 2

### ISSUE THREAD

**Issue by robrichard** [npm/npm#11070] opened 2016-01-07 16:16 UTC
We have a project that uses npm-shrinkwrap and depends on react, react-dom, react-bootstrap and several of the react-addons. Whenever there is a new react release we are unable to npm install from our shrinkwrap file because of peerinvalid errors. Our shrinkwrap file was using the 0.14.5 versions of react, react-dom, react-addons-*. It looks like react@0.14.6 is getting installed as a peerDependency and then conflicting with the shrinkwrapped versions that were also installed.

```
npm ERR! Linux 2.6.32-358.23.2.el6.x86_64
npm ERR! argv "/opt/rh/devtoolset-3/root/usr/bin/node" "/opt/rh/devtoolset-3/root/usr/bin/npm" "install" "--cache" "/home/jenkins//.npm/adminv2iomtstage"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-update@0.14.5 wants react@^0.14.5
npm ERR! peerinvalid Peer react-bootstrap@0.28.1 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-dom@0.14.5 wants react@^0.14.5
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.6 wants react@^0.14.6
```

[npm-debug.log](https://github.com/npm/npm/files/81358/npm-debug.log.txt)
[npm-ls.txt](https://github.com/npm/npm/files/81363/npm-ls.txt)

**Comment by mikesherov** [comment] 2016-01-08 03:13
Thanks for contributing! I think npm is doing the correct thing here in that it's correctly reporting that react@0.14.5 (which is what you specified in your shrinkwrap) does not satisfy react-addons-test-utils dependency on it (which is ^0.14.6).

Seems like the solution is to upgrade your shrinkwrap to include react@0.14.6, or you can upgrade to npm3 which warns but doesn't fail when peerDeps aren't able to be resolved.

**Comment by robrichard** [comment] 2016-01-08 13:30
Is it because dev dependencies are not in our shrinkwrap? react-addons-test-untils was automatically updated but react was not?

**Comment by mikesherov** [comment] 2016-01-08 15:13
It looks like your shrinkwrap has `react@0.14.5` in it and `react-addons-test-utils@0.14.6`. `react-addons-test-utils` has a peerDependency on `react@0.14.6`.

I *think* this is a dupe of https://github.com/npm/npm/issues/5135 and https://github.com/npm/npm/issues/6323

Note that since peerDependencies aren't automatically installed in npm3, this wouldn't be an issue if you upgrade your npm version.

**Comment by robrichard** [comment] 2016-01-08 15:21
`react-addons-test-utils` is not in the shrinkwrap file at all since it is a dev dependency.

**Comment by plusgut** [comment] 2016-01-12 12:10
Had the same issue, updating npm to 3.5.3 solved the issue

**Closed** 2017-06-19 10:17 UTC
Labels: bot-closed, bug, shrinkwrap
