### ISSUE TITLE
Add native support for git

### ISSUE THREAD

**Issue by piranna** [npm/npm#6290] opened 2014-09-24 11:29 UTC
Use a Javascript git library like [js-git](https://github.com/creationix/js-git) instead of depend on a system wide installed executable. This would fix issue #6229 and also help to use npm on [NodeOS](https://github.com/NodeOS/NodeOS/issues/67).

**Comment by Zoltu** [comment] 2015-04-02 04:36
:+1:

As a note to @othiym23 re: "improving npm's story on Windows", as a Windows developer I can say that one such problem with the story right now is dependency on globally installed git if you want to pull packages from git.  Also, from what I can tell windows users can't use git+ssh pull which causes problems with private repos.

While git as a VCS is pervasive in the Windows world, command line git usage is not.  There are a number of GUI tools on windows that do not require git in the path (or the user even knowing where git.exe is installed) and Visual Studio's git implementation is backed by libgit2, so for users using that there is no git.exe on the system.

While I am sure there are bigger issues to tackle with the Windows NPM story, I believe that removing the git dependency is part of this story.

I bring this up because git not being in my path (Windows developer) is what ultimately brought me to this issue.

**Comment by piranna** [comment] 2015-04-02 04:47
[Nodegit](http://www.nodegit.org/) are some native bindings of libgit2 for Node.js and it's sponsored by GitHub between others, I think it could be a good candidate to add native git support for npm...

**Comment by othiym23** [comment] 2015-04-02 05:13
@piranna `nodegit` is not a good fit for npm _because_ of its native bindings. npm needs to be ready to go at install time, and because it is the thing that comes with `node-gyp` to build native modules, it can't include any native modules itself without vastly complicating its deployment. Not to say anything about the difficulty of supporting such a thing.

I personally haven't encountered the problems that @Zoltu describes with `git+ssh:` clones on Windows (I've run Windows for working on npm 2 months so far this year), but do agree that expecting git to be set up on the default `%PATH%` is a bit of a stretch for typical Windows developers. However, helping them get up to speed with a Git installation is far easier than trying to develop platform-native installers for npm for all the platforms it supports, to say nothing of the issues in getting npm to accurately and robustly upgrade itself with such a setup. 

Any replacement for the git CLI in npm must satisfy two requirements:

1. It must be 100% pure JavaScript or depend on a CLI that is installed completely independently of npm and Node.
2. It must support all of the cloning methods and protocols offered by the git CLI. Packages use all of them them, and enterprise ops teams rely on being able to choose between `git:`, `git+https:`, and `git+ssh:` as suits their company policies. Same goes for `.insteadOf.` and all of the proxying support Git has built in.

I've made some changes to how npm uses git recently to clean up some inconsistencies in GitHub repo handling, and seemingly trivial changes have caused installs to start failing for some users. Like it or not, git is a very important part of many npm users' workflows, and we have to use great care when changing how npm uses it.

**Comment by piranna** [comment] 2015-04-02 05:21
> @piranna nodegit is not a good fit for npm because of its native bindings. npm needs to be ready to go at install time, and because it is the thing that comes with node-gyp to build native modules, it can't include any native modules itself without vastly complicating its deployment. Not to say anything about the difficulty of supporting such a thing.

What a shame, since npm include node-gyp, I though it would be possible, sorry... :-(

**Comment by othiym23** [comment] 2016-09-07 21:01
I’ve been following the conversation over on NodeOS/NodeOS#67 over the last couple years, and things seem to be gradually converging on the idea of using a drop-in compatible Git CLI written in JS that takes the commands and options used by npm and uses that in place of the default Git distribution. This seems like a solid approach for the purposes of NodeOS, and once it gets to the point where it’s robust and feature-complete, could be recommended to end users as an alternative to installing Git, especially on Windows.

Another benefit of pursuing that approach is that it removes the need to make invasive changes to the npm CLI, including adding an additional large set of dependencies by default. I’m going to close this issue, because the problem is being solved elsewhere. Thanks to all for their time and attention, and good luck getting this worked out for NodeOS!

**Closed by othiym23** 2016-09-07 21:01 UTC
Labels: feature-request, git

**Comment by piranna** [comment] 2016-09-08 08:06
The drop-in git client written in Javascript for NodeOS was always intended as a minor milestone before getting git support to be integrated on npm itself. It's ok to left it as a recomended method to use it instead of the integration, but I would consider it again in the future (maybe when the git client gets stable enough?).
