### ISSUE TITLE
EPERM, chowning '/home/%username%/.npm/_git-remotes/%package%'

### ISSUE THREAD

**Issue by sudodoki** [npm/npm#6905] opened 2014-12-11 23:51 UTC
Here's npm-debug, some npm i --verbose output & rights set for .npm https://gist.github.com/sudodoki/212dabadcdaf9ae4c7f7.
Tried chowning .npm recursevily to my user. npm is ran under same user, right?

**Comment by othiym23** [comment] 2015-01-15 23:20
Sure! I'll go ahead and close it out now. It bugs me that I still don't know what was causing this problem for you, though.

**Closed by othiym23** 2015-01-15 23:20 UTC
Labels: support

**Comment by NinjaTux** [comment] 2015-03-24 16:28
I have experienced the same error on Amazon Linux latest release.

```bash
npm ERR! Linux 3.14.20-20.44.amzn1.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.10
npm ERR! path /home/nodejs/.npm/_git-remotes/%git-package%
npm ERR! code EPERM
npm ERR! errno 50

npm ERR! Error: EPERM, chown '/home/nodejs/.npm/_git-remotes/%git-package%'
npm ERR!  { [Error: EPERM, chown '/home/nodejs/.npm/_git-remotes/%git-package%]
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/home/nodejs/.npm/_git-remotes/%git-package%,
npm ERR!   parent: 'application }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/nodejs/applications/releases/20150324160125/npm-debug.log
```

It happens just with one package specified with a git remote. Not sure way...

**Comment by othiym23** [comment] 2015-03-25 05:24
@NinjaTux update to the newest version of npm. There have been some fixes made in recent versions to how the git commands deal with setting permissions within the cache that will prevent the problem you're seeing (which is caused by sometimes running npm as root, and sometimes as an unprivileged user -- which should work, to be clear).
