### ISSUE TITLE
npm crash "npm -g remove eslint"

### ISSUE THREAD

**Issue by lll000111** [npm/npm#17170] opened 2017-06-13 13:42 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

npm crashes when I do

     npm -g remove eslint

NOTE (on the side): `npm -g update` does not always update, that is why I have to resort to "remove/install". I have had a ticket open about this issue somewhere for ages, nobody cared, despite other people having the exact same issue.

#### How can the CLI team reproduce the problem?

```
$ npm -g remove eslint
Unhandled rejection Error: Argument #2: Expected string but got null is-path-inside@^1.0.0 fetched in 126ms
    at addDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:463:5
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Program Files\nodejs\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Michael\AppData\Roaming\npm-cache\_logs\2017-06-13T13_37_15_151Z-debug.log
```

Attached:

[2017-06-13T13_37_15_151Z-debug.zip](https://github.com/npm/npm/files/1071545/2017-06-13T13_37_15_151Z-debug.zip)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: none

**Comment by kenany** [comment] 2017-06-13 15:13
Duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-13 15:13 UTC
Labels: npm5
