### ISSUE TITLE
Wrong dependency version installed

### ISSUE THREAD

**Issue by zhanzhenzhen** [npm/npm#14694] opened 2016-11-22 02:16 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

In some cases, the dependency's version is incorrectly installed.

#### How can the CLI team reproduce the problem?

To reproduce this issue, use the following package.json and then install:

```json
{
    "dependencies": {
        "site": "2.21.1"
    },
    "devDependencies": {
        "lodash": "4.6.1",
        "babel": "5.x"
    }
}
```

Then you'll find Babel's dependency "Lodash 3.x" is missing. Only Lodash 4 is installed. You can type `node_modules/.bin/babel --version` to test. It will produce an error.

If you exclude the "site" dependency in package.json, then everything will be fine. There will be a directory "node_modules/babel/node_modules/lodash" for Lodash 3.x. But if it includes "site", then Lodash 3.x will be missing.

**Comment by othiym23** [comment] 2016-11-23 22:05
What version of the npm CLI are you running? (`npm -v`) At least one incarnation of this issue has been fixed over the last few months. You can run `npm -g install npm@latest` to try out a newer version and see if it addresses the problem.

**Comment by zhanzhenzhen** [comment] 2016-11-23 22:08
My npm version is `4.0.2`. I don't believe it's fixed months ago. It exists in both 4.x and 3.x. Can you try my steps to reproduce it?

**Comment by zhanzhenzhen** [comment] 2016-11-23 22:53
Now the only workaround for me is to use `--global-style`. If I don't use `--global-style`, the `lodash` dependency inside `babel` will be missing.

**Comment by benurb** [comment] 2016-11-30 17:17
I can confirm that this problem exists with npm 3.10.8 and 4.0.2.
Another minified test case is:

```json
{
  "name": "npm_bug",
  "version": "1.0.0",
  "dependencies": {
    "chalk": "^1.1.3"
  },
  "devDependencies": {
    "ansi-styles": "^1.0.0"
  }
}
```

Output of `npm ls ansi-styles` after npm install is:

```
npm_bug@1.0.0
├── ansi-styles@1.1.0
└─┬ chalk@1.1.3
  └── UNMET DEPENDENCY ansi-styles@^2.2.1

npm ERR! missing: ansi-styles@^2.2.1, required by chalk@1.1.3
```

This seems critical to me 😕

**Comment by zhanzhenzhen** [comment] 2016-12-02 00:25
@othiym23 Could you check if this is a bug? Still the "support" label?

**Comment by benurb** [comment] 2016-12-05 13:40
Maybe @zkat or @iarna can take a look. The support label is very misleading here.

**Comment by zkat** [comment] 2016-12-05 19:15
@zhanzhenzhen I believe this is a duplicate of https://github.com/npm/npm/issues/11043, which was [fixed in `npm@4.0.5`](https://github.com/npm/npm/pull/12811). You should be able to upgrade and have the issue resolved. I'll close it once you confirm.

As far as labels though: The way we use labels is such that we apply `support` when we need more details to determine whether something's a bug. I guess that's a bit confusing sometimes ;)

**Comment by benurb** [comment] 2016-12-05 19:31
Hi @zkat. Thanks for the clarification about labels. Ye, it's a bit misleading, but I guess I can understand that 😄 

I can confirm that @zhanzhenzhen and my problem is fixed with npm 4.0.5. May I ask you if this fix gets backported to npm 3 for node LTS?

**Comment by zhanzhenzhen** [comment] 2016-12-05 19:45
@zkat Yes I confirm this is fixed. Thanks!

**Comment by zkat** [comment] 2016-12-05 19:53
@zhanzhenzhen good to hear! I'll close this now.

**Closed by zkat** 2016-12-05 19:53 UTC
Labels: bug
