### ISSUE TITLE
npm install error when following Angular2 5 min quickstart

### ISSUE THREAD

**Issue by jakkan** [npm/npm#11069] opened 2016-01-07 14:42 UTC
I get an error when following the Angular2 5 min quick start. How can I get past it?

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/angular2-tutorial$ sudo npm install   angular2-quickstart@1.0.0 /vagrant/angular2-tutorial
└── foxy@11.1.4  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.2
npm ERR! path /vagrant/angular2-tutorial/node_modules/.staging/lodash-496d43d7
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename '/vagrant/angular2-tutorial/node_modules/.staging/lodash-496d43d7' -> '/vagrant/angular2-tutorial/node_modules/browser-sync/node_modules/lodash'
npm ERR!     at destStatted (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename '/vagrant/angular2-tutorial/node_modules/.staging/lodash-496d43d7' -> '/vagrant/angular2-tutorial/node_modules/browser-sync/node_modules/lodash'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename '/vagrant/angular2-tutorial/node_modules/.staging/lodash-496d43d7' -> '/vagrant/angular2-tutorial/node_modules/browser-sync/node_modules/lodash'] parent: 'browser-sync' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.727051537
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.727051537' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/angular2-tutorial/npm-debug.log
```

Here is the error log: https://www.dropbox.com/s/xr6ha3z4re0npvi/npm-debug.log.727051537?dl=0

**Comment by mikesherov** [comment] 2016-01-08 03:16
Thanks for contributing! This seems like a duplicate of https://github.com/npm/npm/issues/10768 Is it?

**Comment by jakkan** [comment] 2016-01-08 08:15
Is it a bug or is it something that I can fix? I tried reinstaling npm using the first option from this list: https://gist.github.com/isaacs/579814 but that didn't help

**Comment by mikesherov** [comment] 2016-01-08 15:17
Seems like it's not a permissions issue which is what that gist fixes. If it's a dupe, best you can do is close bug, and your output to #10768, and find an exact repro case. Thanks again!

**Closed** 2017-06-16 23:37 UTC
Labels: bot-closed, support
