### ISSUE TITLE
Sanity checks on `npm publish`.

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#8617] opened 2015-06-19 18:29 UTC
Is it acceptable to block `npm publish` when something is technically fine, but suspicious?
Is it acceptable print non-blocking warnings on `npm publish` for the same reason?

Is `npm publish` supposed to be used in scripts without extra flags? If yes, then it's probably not fine to block it.

An example of blocking would be to ask the user «{something is suspicious}. Are you sure that you want to publish the package? Y/n». If that is inacceptable, is it ok to introduce non-blocking warnings (the package is published, but the user receives a notice in the process).

Some reasons when the warning would be desirable: when the package size is too big (that's a common mistake to include something that should not be included, see #8339 for details), when the package dependencies are not nice (see #8619 for details), etc.

**Comment by ChALkeR** [comment] 2015-06-19 18:55
It would be cool if this went into npm 3 release. Because if this would be made blocking, than probably there needs to be a flag to suppress that behaviour (in the case if someone uses `npm package` from scripts), and that would be (strictly speaking) a breaking change.

**Comment by othiym23** [comment] 2015-06-19 19:27
> Is it acceptable to block npm publish when something is technically fine, but suspicious?

It's perfectly acceptable to emit a warning. It's also fine to error and halt on validation failures before publishing, and to make that overridable with `--force`. Because npm is used as tooling, it only errors instead of blocking for confirmation for every command except `npm init`, which is interactive by design.

> Is it acceptable print non-blocking warnings on `npm publish` for the same reason?

Possibly, although this would be more useful in the context of the `npm pack` plumbing command, so people can check whether their package is in good shape before publishing it. (For what it's worth, I try to avoid using "sane" or "sanity checks" in these situations because they don't have a lot to do with mental health. If you wanted to retitle this issue "add linting to `npm publish`", I'd appreciate it, but it's your call.)

It sounds like what you want is to have some more package lint checks, and to move those into npm itself. I think this would be a useful affordance for a lot of developers, and I also think a great way to figure out what to check would be to put the checks in an external package linter, at least until we have a good idea of what's useful and what's not.

> It would be cool if this went into npm 3 release.

`npm@3` is as locked down as a release can be at this point. @iarna and I have a few last things to do, but it was feature-frozen months ago and there are no critical blockers remaining on it. That's fine, though, because I don't think adding lint checks into npm proper needs to be breaking (i.e. semver-major changes).

**Comment by othiym23** [comment] 2016-02-19 21:50
> It sounds like what you want is to have some more package lint checks, and to move those into npm itself. I think this would be a useful affordance for a lot of developers, and I also think a great way to figure out what to check would be to put the checks in an external package linter, at least until we have a good idea of what's useful and what's not.

I still feel that this is the best way to start adding quality and appropriateness checks to the CLI. Build a linter, get some real-world experience with it, allow people to play around with it, and at that point, it could make sense to integrate it directly into the CLI. Given the other things on the CLI team's list of things to do, we're not going to have the resources necessary to deal with this, so I'm going to close it, but that doesn't mean that I don't want linting in the CLI. Please, give it a shot!

Thanks for the proposal, and thanks for your time!

**Closed by othiym23** 2016-02-19 21:50 UTC
Labels: feature-request

**Comment by ChALkeR** [comment] 2016-02-19 21:53
@othiym23 Makes sense, thanks!
