### ISSUE TITLE
Error during npm install - ECONNRESET

### ISSUE THREAD

**Issue by mdrozdo** [npm/npm#9418] opened 2015-08-26 14:15 UTC
Hi, today I started getting ECONNRESET errors from npm on our build server. As far as I know there were no network changes to it recently and so far this was never an issue.

It seems that after these errors the packages actually get installed and I can use them. As a matter of fact, running npm install again afterwards doesn't update anything - issue happens only on a clean install. 

Every once in a while the operation actually goes through, but fails most of the time. I tried restarting the server and clearing npm cache but it didn't help. I'm running the latest npm version (2.14).

This what I get in the console. I uploaded the full console out and debug.log to https://gist.github.com/mdrozdo/594a152f8f8020dcb68c 
```
Done. Phantomjs binary available at C:\workspace\c\EMD_GradleBuild\rolling\npm_client\node_modules\grunt-contrib-jasmine
\node_modules\grunt-lib-phantomjs\node_modules\phantomjs\lib\phantom\phantomjs.exe
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[[SNIP]]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\c\EMD_GradleBuild\rolling\npm_client\npm-debug.log
```

**Comment by mjesun** [comment] 2015-08-27 08:33
+1. We are experiencing the same issue.

**Comment by grrobinson** [comment] 2015-08-27 13:21
+1 Same issue for my team

**Comment by hunterloftis** [comment] 2015-08-27 19:28
Seeing a few of these with customers on Heroku as well. Generally using a recent version of npm (2.7.x).

**Comment by josephgardner** [comment] 2015-09-03 21:23
+1

**Comment by hunterloftis** [comment] 2015-09-28 17:36
Still seeing these periodically with versions as recent as `2.11.3`. I'm looking into possible network issues since it's intermittent, but it's curious that there's also reports of this on jenkins.

**Comment by jlmitch5** [comment] 2015-10-05 17:07
+1 for our team.

**Comment by rochdev** [comment] 2015-10-15 19:27
+1 on Codeship intermittently (v2.11.3)

**Comment by Tinha4Sale** [comment] 2015-10-21 20:46
We had the same issue in our environment running on Node v0.12.4 and NPM v2.10.1 with the exact same error message; we are not using any proxy at all.  Jenkin (Mercurial too) occasionally reported they cannot publish; yet if the user manually re-do the publish action, it gets through.  There are no network changes as far I can see.  Not sure whether this is a bug in the Node / NPM or mis-configuration on our end.

**Comment by goliatone** [comment] 2015-10-28 21:29
Seeing the same behavior on Travis

```
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
```

**Comment by samtsai** [comment] 2015-11-02 17:11
Curious, does anyone have the `engineStrict` flag set to `true`?

**Comment by erquhart** [comment] 2015-11-14 19:39
+1 (only because there's no communication or apparent movement on status for this)

**Comment by tiwarisnehal** [comment] 2015-11-16 04:48
+1 win 10 64bit
keep on getting this error intermittently.
Have to try npm install a few times till it completes successfully.
Very frustrating and should be resolved.

**Comment by maartenba** [comment] 2015-12-03 15:02
Same with:

```
{ npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.1.0',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

It is only on https, but sometimes on http too.

**Comment by Tinha4Sale** [comment] 2015-12-16 21:16
Is anyone using STUD as the reverse proxy?  In my environment, the person who setup the Sinopia environment is using STUD as the reverse proxy.  As a test, I've replaced STUD with Nginx as the reverse proxy on my test box, and since then I am not seeing any error while accessing Sinopia through the web browser.  I am just awaiting confirmation from our Dev see if they can do a "npm publish" and see if they still having this connection issue.

**Comment by bolddp** [comment] 2016-01-03 20:06
+1 on my Jenkins. Appr. 5 out of 6 tries fail. Always on npm calls, never on github.

**Comment by zetlen** [comment] 2016-01-04 22:31
+1 on Appveyor. Node 5.0.0, NPM 3.5.2.

**Comment by swagatblog** [comment] 2016-01-09 14:39
I used to get same error. But could resolve by updating npm registry. It worked!!

>npm config set registry http://registry.npmjs.org/

Just changed https to http.

**Comment by gdennie** [comment] 2016-01-29 02:25
Works on retry for some reason

**Comment by eppsilon** [comment] 2016-02-11 16:34
I'm seeing this too, with Node 4.3.0 and NPM 3.7.1.

**Comment by sharkoman** [comment] 2016-03-19 18:12
the same here i can't install any package

**Comment by gdennie** [comment] 2016-03-19 18:18
Try @swagatblog suggestions to reconfigure connection for http instead of https (the default)

**Comment by thesmart** [comment] 2016-04-29 00:48
+1, we're getting this maybe 1/6 times Node v0.12 and npm 2.11.3

Disabling HTTPS to fix this seems like a bad idea.

**Comment by othiym23** [comment] 2016-04-29 01:09
Closing as duplicate of #12484. This is a network issue that occurs somewhere between the CLI and the CDN, and may or may not be due to the large number of simultaneous HTTPS connections initiated by the CLI. If it's the latter, than updating to the newest versions of `npm@2` or `npm@3` might mitigate the problem somewhat, due to the fact that they now limit the number of sockets open simultaneously. Either way the `ECONNRESET`s aren't, as far as we can tell, originating at npm's CDN. See #12484 or npm/registry#10 for further details. Thanks to all for your time and patience!

**Closed by othiym23** 2016-04-29 01:09 UTC
Labels: registry, support

**Comment by waterstar** [comment] 2016-05-05 06:42
Just like to share the problem could be solved by using node 5.
```
/** package.json **/
  "engines": {
    "node": "5.0.0",
    "npm": "3.5.0"
  },

```

**Comment by maciej-gurban** [comment] 2016-08-24 09:57
I've been having the same issue on `node 5.0.0` and `npm 3.3.6`. The errors are thrown only in automated builds. Scheduling a build manually doesn't seem to ever cause any problems.

**Comment by atungare** [comment] 2016-10-06 21:16
We are seeing a bunch of these ECONNRESETs recently on Travis, with e.g. node 5.8.0 and npm 3.7.3 (but other versions of node & npm are also experiencing errors).

**Comment by cusspvz** [comment] 2016-10-31 11:53
@atungare same here

**Comment by frankie-loves-jesus** [comment] 2017-02-03 21:24
I'm getting these too, abrupt npm ECONNRESET errors on Ubuntu Server 16.04.1/VirtualBox 5.1.4:

https://gist.github.com/anonymous/99c76033b96d819be6199bf927fc248c

**Comment by pnunn** [comment] 2017-02-09 23:52
I too am getting this. I'm stuck on node 0.10.40 and am not user how far I can push npm to match (its currently 1.4.28). This was all working fine two days ago and now it doesn't matter if I use http or https I'm getting the connection resets.

**Comment by jboler** [comment] 2017-03-09 06:37
About 50% of our builds on our paid Travis-CI account fail with this error. node 4.1.2, npm 2.15.11.

**Comment by cusspvz** [comment] 2017-03-16 10:11
@jboler that's probably a connectivity issue on travis's virtual instance.

**Comment by discordianfish** [comment] 2017-07-04 18:18
Have the same issues on circleci too.

**Comment by jboler** [comment] 2017-07-04 18:20
This issue went away for me when I upgraded to node 7 / npm 4/5.

**Comment by cusspvz** [comment] 2017-08-01 19:38
Most of the times this occurred with me, it was a network fault (either on my computer or on cloud providers). Gonna unsubscribe from this issue.

**Comment by jcollum-cambia** [comment] 2017-08-02 23:37
I'm seeing this issue on Node 6 / npm 5 

```
$ node --version; npm --version; npm config get proxy;  npm config get https-proxy;
v6.11.0
5.3.0
http://proxy.abcxyz.com:8080/
https://hvw-proxy.abcxyz.com:2831/
```

Windows 10. Tried in powershell and git-bash. 

I'll try upping to Node 8 but I doubt it'll do anything. edit: it didn't. 

Error text: 

```
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz failed, reason: socket hang up

npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/array-map/-/array-map-0.0.0.tgz failed, reason: socket hang up
```

**Final edit:** this apparently was a problem with our corporate proxy. I got on the guest wireless network and it went away. I'm going to leave this here in case it helps someone else.
