### ISSUE TITLE
Improve how build errors are reported to the user for optional native dependencies

### ISSUE THREAD

**Issue by glennblock** [npm/npm#3715] opened 2013-07-27 17:04 UTC
If a build failure occurs on windows due to trying to build an optional native dependency npm returns the build output including the error to the user. This is misleading to new users, in particular on windows where you get a bright red error like below if the right pre-reqs to build the native modules are not present (i.e. VS express).

![socketio](https://f.cloud.github.com/assets/141124/867206/669d4f84-f6de-11e2-8adf-07b1cf9e89e9.jpg)

It would be great if these sorts of warnings have the detailed output suppressed / piped to a file and then display a simple warning like "Warning: Optional dependency WS was not built, for details see here:"

Also having a message at the bottom like "modules successfully installed" would reinforce to the user that it's "ok, no need to panic"

**Comment by othiym23** [comment] 2016-05-06 20:47
Closing as a duplicate of #9567, which is on the CLI team's roadmap of things to address within the next year (or so). Thanks for your time and patience!

**Closed by othiym23** 2016-05-06 20:47 UTC
Labels: error-handling, feature-request
