### ISSUE TITLE
npm owner add fails with Gateway Timeout

### ISSUE THREAD

**Issue by ashleydw** [npm/npm#12521] opened 2016-04-29 06:51 UTC
`npm owner add` fails with a gateway timeout, but the npmjs.com website shows collaborator as added: https://www.npmjs.com/package/react-native-numberpicker

However, user `patrickomeara` cannot publish.

```
npm owner add patrickomeara react-native-numberpicker
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! owner mutate Failed to update package metadata
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "owner" "add" "patrickomeara" "react-native-numberpicker"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9

npm ERR! Unexpected token <
npm ERR! <html><body><h1>504 Gateway Time-out</h1>
npm ERR! The server didn't respond in time.
npm ERR! </body></html>
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ashleydw/Sites/react-native-numberpicker/npm-debug.log
```

The log doesn't get written.

```
npm publish .
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/bin/npm" "publish" "."
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code E403

npm ERR! you do not have permission to publish "react-native-numberpicker". Are you logged in as the correct user? : react-native-numberpicker
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pat/Mobile/react-native-numberpicker/npm-debug.log
``

**Comment by pawelfus** [comment] 2016-04-29 09:38
Nice timing, I have the same issue here: https://www.npmjs.com/package/highcharts-multicolor-series

**Comment by ashleydw** [comment] 2016-05-06 08:01
Same error a week later.

**Comment by levrik** [comment] 2016-05-06 13:05
I have the same problem. The user gets added but I can't remove the old user because npm says the package only has one owner added.

**Comment by xdumaine** [comment] 2016-05-06 18:46
We're seeing this, too.

**Comment by othiym23** [comment] 2016-05-07 00:47
Closing as a duplicate of #12610. Please see that issue for details and a suggested escalation path. Thanks for your time!

**Closed by othiym23** 2016-05-07 00:47 UTC
Labels: network, registry, support
