### ISSUE TITLE
Unable to download atom-html-preview

### ISSUE THREAD

**Issue by Manikumar1998** [npm/npm#13671] opened 2016-08-15 13:50 UTC
While trying to download the html-preview the following error is seen. How can I resolve this issue.

```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Manikumar\AppData\Local\atom\app-1.9.1\resources\app\apm\bin\node.exe" "C:\Users\Manikumar\AppData\Local\atom\app-1.9.1\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Manikumar\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Manikumar\.atom\.apmrc" "install" "C:\Users\MANIKU~1\AppData\Local\Temp\d-116715-2512-1t4qc5y\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm v2.13.3
npm ERR! path C:\Users\MANIKU~1\AppData\Local\Temp\apm-install-dir-116715-2512-13jnu9y\node_modules\atom-html-preview\package.json.3e34f3c8df1b976f5c2d8af52649d2c2
npm ERR! code EBUSY
npm ERR! errno 10

npm ERR! EBUSY, rename 'C:\Users\MANIKU~1\AppData\Local\Temp\apm-install-dir-116715-2512-13jnu9y\node_modules\atom-html-preview\package.json.3e34f3c8df1b976f5c2d8af52649d2c2'
npm ERR!
```

**Comment by KenanY** [comment] 2016-08-15 14:36
@Manikumar1998 Does this also occur after a reboot?

**Comment by othiym23** [comment] 2016-08-19 22:39
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 22:39 UTC
Labels: support, windows
