### ISSUE TITLE
Unable to install packages on Windows 10 Insider(Build:14367.rs1_release.160613-1700

### ISSUE THREAD

**Issue by CubeIX** [npm/npm#13133] opened 2016-06-21 20:02 UTC
npm version: 3.9.5(for the "npm -v" the npm throw a similar error, but print the version)
Node.Js version: v6.2.2
```
npm install chanchejs -verbose
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:672:19)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
 npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'chanchejs',
npm verb cli   '-verbose' ]
npm info using npm@3.9.5
npm info using node@v6.2.2
npm verb config Skipping project config: C:\Users\x640/.npmrc. (matches userconfig)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:672:19)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)```

**Comment by fernandogomesdf** [comment] 2016-06-25 16:18
+1

**Comment by KenanY** [comment] 2016-06-26 13:53
Duplicate of https://github.com/npm/npm/issues/12887.

**Comment by KenanY** [comment] 2016-06-29 01:53
Closing as a duplicate. If I am mistaken, I will gladly reopen.

**Closed by KenanY** 2016-06-29 01:53 UTC
Labels: support, windows
