### ISSUE TITLE
npm install causing issues showing garbage value

### ISSUE THREAD

**Issue by ansham22** [npm/npm#12251] opened 2016-04-07 09:40 UTC
tried with npm version 1.3.21

2688 silly gunzTarPerm extractEntry CONTRIBUTING.md
2689 silly gunzTarPerm extractEntry CHANGELOG.md
2690 error SyntaxError: Unexpected token ^_
2690 error ^_^@^@^@^@^@^D^C�R�n�0^P����bBh^�r��C{k{����^EL^@[�IJ��{w^S^Rql{@�����X+^Z`  ^C�     ^CA雚=0�G��W�Ż�������e^B�W^�C�^A��^B">�^QV��^_���%�^C!^V^G�ΫZ��m��@+�'9�^_X#^T  )�~���3�^Xݢ^Z^B��^La�>�;|�yF6^KF;�������^F,�G����_zo\^R�X+���Vx�^KG��Ԅ�iW\���^]*�:�^P   J݀^Q^E���6��)�^M#?��r�Ŕ�u^M��U$f�^E^H^Y��"^��l5_fy^Z��x:�A<_�y>EV/l*��^Zp^K^V
2690 error ��=oMS9�m1�A^X�O��^A��7��˭&uNf��c���G������K^LQ�U�k}^T}Vv{�^@�>�����(QA^CR   �       Ҡhx��^Zc�/�-FNY�0^QC��?H�we�^B^@^@
2690 error     at Object.parse (native)
2690 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:23)
2690 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
2690 error     at Request.EventEmitter.emit (events.js:98:17)
2690 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:894:14)
2690 error     at Request.EventEmitter.emit (events.js:117:20)
2690 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
2690 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
2690 error     at _stream_readable.js:920:16
2690 error     at process._tickCallback (node.js:415:13)
2691 error If you need help, you may report this *entire* log,
2691 error including the npm and node versions, at:
2691 error     <http://github.com/isaacs/npm/issues>
2692 error System Linux 3.13.0-48-generic
2693 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2694 error cwd /var/www/market-refund/releases/source
2695 error node -v v0.10.24
2696 error npm -v 1.3.21
2697 error type unexpected_token
2698 verbose exit [ 1, true ]

**Comment by jogendrajangid1** [comment] 2016-04-07 10:13
#12196

**Comment by othiym23** [comment] 2016-04-07 16:06
Closing as duplicate of #12196. See that issue for details and current status. Thanks for your patience!

**Closed by othiym23** 2016-04-07 16:06 UTC
