### ISSUE TITLE
unable to reinstall grunt after uninstall

### ISSUE THREAD

**Issue by fayeyen** [npm/npm#14038] opened 2016-09-22 12:57 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I uninstall the grunt and grunt-cli then I try to reinstall it 
sudo npm install -g grunt-cli
sudo npm install -g grunt
both shown me the error like below it keep repeating the same error for few times

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: MAC OS X EI Capitan 10.11.6
all latest version
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
Mac terminal admin to run the command
[npm-debug.pdf](https://github.com/npm/npm/files/487290/npm-debug.pdf)
[npm-debug.pdf](https://github.com/npm/npm/files/487293/npm-debug.pdf)

 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gortok** [comment] 2016-09-22 19:23
This is also present in issue #13918, #8515, and I'm currently having this issue when I try to install cordova globally.

The listed option to change the file system permissions does not work for me:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

It may work for you. Option 1:

> `npm config get prefix`
if the result is /usr/local, then:

> `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

Otherwise you can use Option 2 on that listed page.

**Comment by gortok** [comment] 2016-09-22 22:31
I resolved this issue by uninstalling node via brew (where it was installed) and installed the version on the website for Node4 (Node 4.5, and NPM version 2.5.19)

**Comment by fayeyen** [comment] 2016-09-23 13:24
I after I did change system permissions I got this error again
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

repeat many times
but the npm-debug.pdf is sorter.
[npm-debug.pdf](https://github.com/npm/npm/files/489743/npm-debug.pdf)

**Comment by fayeyen** [comment] 2016-09-23 13:25
I seem like uid must be an unsigned int 
is the key error, but I don't know what does it mean?

**Comment by KenanY** [comment] 2016-09-23 13:42
See https://github.com/npm/npm/issues/14047#issuecomment-249099655. Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-23 13:42 UTC

**Comment by fayeyen** [comment] 2016-09-23 14:04
I seem like new to downgrade npm to 3.10.7
So I used this command 
sudo npm install -g npm@3.10.7
Same problem
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@3.10.7"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/test/npm-debug.log

How should I delete npm in proper command and reinstall command?

**Comment by fayeyen** [comment] 2016-09-24 00:32
OK I sort it out by uninstall node.js and npm then reinstall it.
