### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by oliversalzburg** [npm/npm#15368] opened 2017-01-02 11:06 UTC
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
It exits unexpectedly when I run `npm prune`

```
231 verbose correctMkdir C:\Users\OliverSalzburg\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
232 verbose lock using C:\Users\OliverSalzburg\AppData\Roaming\npm-cache\_locks\staging-fd8d2a4ed67174a4.lock for C:\Users\OliverSalzburg\FairManager Projects\core-aws\node_modules\.staging
233 silly doParallel extract 0
234 silly doParallel preinstall 0
235 silly doReverseSerial remove 0
236 silly doSerial move 33
237 silly move node_modules\buffer node_modules\buffer
238 info lifecycle undefined~preuninstall: undefined
239 silly lifecycle undefined~preuninstall: no script for preuninstall, continuing
240 info lifecycle undefined~uninstall: undefined
241 silly lifecycle undefined~uninstall: no script for uninstall, continuing
242 verbose stack TypeError: Cannot read property '0' of undefined
242 verbose stack     at rmStuff (C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\lib\unbuild.js:61:24)
242 verbose stack     at Array.<anonymous> (C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
242 verbose stack     at LOOP (C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
242 verbose stack     at C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
242 verbose stack     at done (C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:132:5)
242 verbose stack     at LOOP (C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
242 verbose stack     at C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
242 verbose stack     at C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:318:20
242 verbose stack     at C:\Users\OliverSalzburg\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
242 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
243 verbose cwd C:\Users\OliverSalzburg\FairManager Projects\core-aws
244 error Windows_NT 10.0.14393
245 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\OliverSalzburg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "prune"
246 error node v6.9.2
247 error npm  v4.1.1
248 error Cannot read property '0' of undefined
249 error If you need help, you may report this error at:
249 error     <https://github.com/npm/npm/issues>
250 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?
I don't know if they can, as I noticed this behavior in a specific project that isn't publicly available.

### supporting information:

 - `npm -v` prints: 4.1.1
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

**Comment by legodude17** [comment] 2017-01-13 21:31
Duplicate of #13422.

**Closed** 2017-06-18 10:34 UTC
Labels: bot-closed
