### ISSUE TITLE
npm not working and not updating 

### ISSUE THREAD

**Issue by coreilabs** [npm/npm#6826] opened 2014-12-02 13:35 UTC
Someone can help? 

```
corei@coreia:~$ sudo npm -g install npm@latest
npm ERR! Linux 3.16.0-24-generic
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "npm@latest"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.6

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-24-generic
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "npm@latest"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.6

npm ERR! shasum check failed for /tmp/npm-15246-aab523c5/registry.npmjs.org/npm/-/npm-2.1.10.tgz
npm ERR! Expected: a571ae408ac1b5e515f6c34c033503a7bb828cb4
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.1.10.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by othiym23** [comment] 2015-01-08 18:34
I believe this is actually, at root, tied to the same cause as #7070, so I'm closing this issue as a duplicate of that one. Keep an eye on that issue for a resolution.

**Closed by othiym23** 2015-01-08 18:34 UTC
Labels: support
