### ISSUE TITLE
guideline to run the sample code from the Nock website

### ISSUE THREAD

**Issue by bettyzhenya** [npm/npm#15409] opened 2017-01-05 21:20 UTC
how can I write a test file with the following codes and how can ran with it, thanks
var nock = require('nock');

var couchdb = nock('http://myapp.iriscouch.com')
                .get('/users/1')
                .reply(200, {
                  _id: '123ABC',
                  _rev: '946B7D1C',
                  username: 'pgte',
                  email: 'pedro.teixeira@gmail.com'
                 });

**Comment by KenanY** [comment] 2017-01-05 23:52
You should be able to just run that code with `node`. Closing since this is not a bug or feature request for `npm`. StackOverflow or <https://github.com/nodejs/help> are more appropriate forums for this kind of support. Good luck! :)

**Closed by KenanY** 2017-01-05 23:52 UTC

**Comment by bettyzhenya** [comment] 2017-01-06 00:48
Ok thanks

**Comment by bettyzhenya** [comment] 2017-01-06 15:50
Hi Kenan
When I ran npm test command, how do I know which file I am going to run, is it listed on Package.json?

Thanks
