### ISSUE TITLE
Not working with node v9

### ISSUE THREAD

**Issue by arguiot** [npm/npm#19065] opened 2017-11-05 11:29 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Doesn't support Node v9
#### How can the CLI team reproduce the problem?
Just install node v9, and try to install something, npm will crash and will not install the packages

### supporting information:

 - `npm -v` prints:
```
5.5.1
```
 - `node -v` prints:
```
v9.0.0
```
 - `npm config get registry` prints:
```
https://registry.npmjs.org/
```
 - Windows, OS X/macOS, or Linux?:
Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by arguiot** [comment] 2017-11-05 11:32
Here are the logs:
```bash
npm WARN npm npm does not support Node.js v9.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
/home/travis/.nvm/versions/node/v9.0.0/bin/node[3072]: ../src/node_zlib.cc:430:static void node::{anonymous}::ZCtx::Init(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [npm]
 2: node::Assert(char const* const (*) [4]) [npm]
 3: 0x1251ea1 [npm]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
 5: 0xb74c3c [npm]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
 7: 0x31a1756842fd
/home/travis/.travis/job_stages: line 57:  3072 Aborted                 (core dumped) npm install
```

**Comment by kenany** [comment] 2017-11-05 14:06
Duplicate of https://github.com/npm/npm/issues/19019.

**Closed as completed by kenany** 2017-11-05 14:06 UTC
