### ISSUE TITLE
Could not install Gulp

### ISSUE THREAD

**Issue by prashmi9** [npm/npm#14202] opened 2016-10-06 19:45 UTC
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
I am getting following Error:
uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "gulp-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

Here is the npm-debug.log file.
[npm-debug.docx](https://github.com/npm/npm/files/514659/npm-debug.docx)

### supporting information:

uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "gulp-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

**Comment by addaleax** [comment] 2016-10-06 20:05
Try reinstalling Node from https://nodejs.org/ (or anything else that would downgrade your `npm` installation to a version that’s not `3.10.8`).

This is a known bug, see https://github.com/npm/npm/issues/13918 :)

**Comment by othiym23** [comment] 2016-10-06 20:14
Closing as a duplicate of #13918; thanks for catching this one, @addaleax!

**Closed by othiym23** 2016-10-06 20:14 UTC
Labels: support
