### ISSUE TITLE
npm5 save-dev doesn't install other dependencies or generate accurate lockfile

### ISSUE THREAD

**Issue by brentvatne** [npm/npm#16893] opened 2017-06-01 22:25 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other

#### What's going wrong?

If you have a `package.json` with some dependencies, you have not run `npm install`, and you don't have a lockfile, when you run `npm install any-package-name-here --save-dev` it installs only that dependency and creates a lockfile with only that dependency. This is behavior different from older versions of npm and likely also unintentional.

#### How can the CLI team reproduce the problem?

Create a new directory with the following package.json:

```
{
  "name": "save-dev-example",
  "dependencies": {
    "left-pad": "1.1.3"
  }
}
```

Go into the directory and run `npm install --save-dev lodash` (happens with any package, but I like lodash). Notice that `package-lock.json` includes only `lodash` and not `left-pad`. Running `npm install` again doesn't help with the problem because the lockfile already exists.

### supporting information:

 - `npm -v` prints: 5.0.0 and 5.0.1
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Vancouver, Canada
   - (none of the network issues listed apply, removed for brevity)

**Comment by cr101** [comment] 2017-06-02 00:04
Potentially a duplicate of #[16839](https://github.com/npm/npm/issues/16839)

**Comment by brentvatne** [comment] 2017-06-02 19:48
@cr101 - there does appear to be some overlap but the flows for reaching the state described in the other issue is different.

**Comment by relu-xz** [comment] 2017-10-02 14:34
@brentvatne I'm new to React Native and Expo and tried to reproduce the error without success. npm seems working fine. This is the `package-lock.json` generated:

```javascript
{
  "name": "save-dev-example",
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "left-pad": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/left-pad/-/left-pad-1.1.3.tgz",
      "integrity": "sha1-YS9hwDPzqeCOk58crr7qQbbzGZo="
    },
    "lodash": {
      "version": "4.17.4",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz",
      "integrity": "sha1-eCA6TRwyiuHYbcpkYONptX9AVa4=",
      "dev": true
    }
  }
}
```

SO: Windows 8.1 x64
Node: v8.6.0 x64
npm: v5.3.0

**Comment by brentvatne** [comment] 2017-10-04 23:41
@zorobabel - perhaps it is resolved on npm 5.3.0!

**Comment by deadcoder0904** [comment] 2017-10-05 18:56
So @brentvatne can we use `npm` now ❓& plz change CRNA docs then 😜

**Comment by brentvatne** [comment] 2017-10-06 18:14
@deadcoder0904 - I would still not recommend it (npm v5, npm v4 works fine!), as I encountered other problems last time I tested it a few weeks ago. But if you try it and it works then go for it!

**Comment by deadcoder0904** [comment] 2017-10-06 18:33
Cool enough 👍

**Comment by treyp** [comment] 2018-02-28 18:46
as of npm 5.6.0, the `npm install` command when run after the `--save-dev` command does end up installing the additional package.

```
12:41:54 dev $ mkdir save-dev-example
12:41:59 dev $ cd save-dev-example/
12:42:02 save-dev-example $ nano package.json
12:42:37 save-dev-example $ cat package.json 
{
  "name": "save-dev-example",
  "dependencies": {
    "left-pad": "1.1.3"
  }
}

12:42:42 save-dev-example $ ls
total 8
drwxr-xr-x   3    102B Feb 28 12:42 ./
drwxr-xr-x  43    1.4K Feb 28 12:41 ../
-rw-r--r--   1     83B Feb 28 12:42 package.json
12:42:56 save-dev-example $ npm install --save-dev lodash
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN save-dev-example@ No description
npm WARN save-dev-example@ No repository field.
npm WARN save-dev-example@ No license field.

+ lodash@4.17.5
added 1 package in 1.07s
12:43:12 save-dev-example $ cat package-lock.json 
{
  "name": "save-dev-example",
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "lodash": {
      "version": "4.17.5",
      "resolved": "https://[obfuscated]/artifactory/api/npm/npm/lodash/-/lodash-4.17.5.tgz",
      "integrity": "sha1-maktZcAnLevoyWtgV7yPv6O+1RE=",
      "dev": true
    }
  }
}
12:43:22 save-dev-example $ ls
total 16
drwxr-xr-x   5    170B Feb 28 12:43 ./
drwxr-xr-x  43    1.4K Feb 28 12:41 ../
drwxr-xr-x   3    102B Feb 28 12:43 node_modules/
-rw-r--r--   1    334B Feb 28 12:43 package-lock.json
-rw-r--r--   1    134B Feb 28 12:43 package.json
12:43:29 save-dev-example $ npm install
npm WARN save-dev-example@ No description
npm WARN save-dev-example@ No repository field.
npm WARN save-dev-example@ No license field.

added 1 package in 0.691s
12:43:40 save-dev-example $ cat package-lock.json 
{
  "name": "save-dev-example",
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "left-pad": {
      "version": "1.1.3",
      "resolved": "https://[obfuscated]/artifactory/api/npm/npm/left-pad/-/left-pad-1.1.3.tgz",
      "integrity": "sha1-YS9hwDPzqeCOk58crr7qQbbzGZo="
    },
    "lodash": {
      "version": "4.17.5",
      "resolved": "https://[obfuscated]/artifactory/api/npm/npm/lodash/-/lodash-4.17.5.tgz",
      "integrity": "sha1-maktZcAnLevoyWtgV7yPv6O+1RE=",
      "dev": true
    }
  }
}
```

**Comment by iarna** [comment] 2018-03-08 22:49
This was a problem specifically with npm@5 working with yarn produced (and only yarn produced) trees). As of npm@5.7.1 it should deal with these yarn produced trees more gracefully, despite the fact that they lack sufficient metadata to verify their validity.

The problem came out of an interesting intersection of features: Wanting `npm install foo` to only install `foo`, even you have other deps that aren't installed yet. Wanting to only write valid modules to your package-lock. And finally, always syncing your package-lock to your node-modules.

The validity checks were removing all of the yarn packages from its tree, as it couldn't verify their origin. Then the new package was added, but the remaining dependencies weren't added back in (because of the first feature) and so when it went to sync with your node_modules it removed all the yarn packages as they didn't fulfill any of npm's requirements.

**Closed as completed** 2018-03-08 22:49 UTC
Labels: bug, shrinkwrap, installer, npm5
