### ISSUE TITLE
Npm runs prepublish hook for local dependencies before installing devDependencies

### ISSUE THREAD

**Issue by sheerun** [npm/npm#9707] opened 2015-09-22 10:49 UTC
Hey,

My local dependency uses `babel` to compile, and lists `build` script in `prepublish` task, as so:

```
{
  "name": "package",
  "scripts": {
    "build": "babel src/ -d lib/",
    "prepublish": "npm run build",
  },
  "devDependencies": {
    "babel": "^5.8.21"
  }
}
```

When installing local module that lists this package as dependency, I get an error:

```
> package@1.0.0 prepublish /Users/sheerun/Source/package
> npm run build


> package@1.0.0 build /Users/sheerun/Source/package
> babel src/ -d lib/

sh: babel: command not found

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/sheerun/.nvm/versions/io.js/v2.2.1/bin/iojs" "/Users/sheerun/.nvm/versions/io.js/v2.2.1/bin/npm" "run" "build"
npm ERR! node v2.2.1
npm ERR! npm  v3.3.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! package@1.0.0 build: `babel src/ -d lib/`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the package@1.0.0 build script 'babel src/ -d lib/'.
```

It's because npm doesn't install devDependencies of "package" package, before running prepublish command. Prepublish script is meant to "[do all the platform-independent tasks necessary to turn this package from its raw source code state into its actual use state](https://github.com/npm/npm/issues/6887)", so I'd expect devDependencies of package are installed before prepublish script is executed.

Thanks

**Comment by KenanY** [comment] 2015-09-23 20:56
Hmm, I wonder if this is a dupe of https://github.com/npm/npm/issues/7040 (note: `npm@2`) and/or fixed by https://github.com/npm/npm/pull/8725.

**Comment by benmosher** [comment] 2015-12-22 16:13
Count me in on this. Any decent workarounds? I was thinking of doing a manual `npm install` first, but this runs `prepublish` twice.

**Comment by benmosher** [comment] 2015-12-22 16:23
Prepending `prepublish` with `npm i --only=dev --ignore-scripts && ` under `npm@3` seems to yield the desired outcome (dev deps are updated without recursing infinitely).

This is actually generally helpful in that `npm pack` will always run with up-to-date `devDependencies`, but still feels like a local FS install should handle this?

**Closed** 2017-06-18 22:55 UTC
Labels: bot-closed
