### ISSUE TITLE
Problem in Modules installation

### ISSUE THREAD

**Issue by fellowhacker** [npm/npm#17443] opened 2017-06-26 17:55 UTC
#### I'm opening this issue because:

I'm unable to install some npm modules.

#### Description : 
I'm able to install some modules example:- lodash but I'm unable to install modules like morgan
Thanks in advance.

**Comment by kenany** [comment] 2017-06-26 18:51
Is this a duplicate of your previous ticket, https://github.com/npm/npm/issues/17442?

**Comment by fellowhacker** [comment] 2017-06-26 18:52
Both are different

**Closed as completed** 2017-06-27 17:23 UTC
Labels: support
