### ISSUE TITLE
`npm update -g strongloop` fails with "typeerror Error: Missing required argument #1"

### ISSUE THREAD

**Issue by Sequoia** [npm/npm#10693] opened 2015-12-04 14:56 UTC
## context
```
$ node --version
v5.0.0

$ npm --version
3.3.6

$ which slc
/Users/sequoia/.npm-packages/bin//slc

$ slc --version
strongloop v5.0.1 (node v5.0.0)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.2.1 (50fcfa5)
│ └── strong-agent@2.0.1 (8554cb3)
├── generator-loopback@1.12.0 (01a38d5)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

## command
`npm update -g strongloop`

## expected
Updates strongloop or tells me it's already at latest

## actual
`npm ERR! typeerror Error: Missing required argument #1`

## debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sequoia/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/Users/sequoia/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'update',
1 verbose cli   'strongloop',
1 verbose cli   '-g' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:11:3)
4 verbose stack     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:77:5
4 verbose stack     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:61:20
4 verbose stack     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at fs.js:1657:23
5 verbose cwd /Users/sequoia/strongloop/coffee-time
6 error Darwin 15.0.0
7 error argv "/Users/sequoia/.nvm/versions/node/v5.0.0/bin/node" "/Users/sequoia/.nvm/versions/node/v5.0.0/bin/npm" "update" "strongloop" "-g"
8 error node v5.0.0
9 error npm  v3.3.6
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:11:3)
11 error typeerror     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:77:5
11 error typeerror     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:61:20
11 error typeerror     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /Users/sequoia/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at fs.js:1657:23
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by Sequoia** [comment] 2015-12-04 14:57
also tried `npm update -g strongloop`

**Comment by othiym23** [comment] 2015-12-04 17:32
Closing as duplicate of #9720, which probably also needs a bump in importance to `big-bug`. Thanks for the detailed description!

**Closed by othiym23** 2015-12-04 17:32 UTC
