### ISSUE TITLE
ionic not install

### ISSUE THREAD

**Issue by subediramji** [npm/npm#12166] opened 2016-04-01 11:12 UTC
```
C:\Users\Ramji>npm install -g ionic
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\Ramji\AppData\Local\Temp\npm-1160-b3d5f521\registry.npmjs.org\ionic\-\ionic-1.7.14.tgz
npm ERR! Expected: af493d5df4688d917d778b0934d1739b9be6efe6
npm ERR! Actual:   9db73f4bd48b33c44c44d43999e82ff5e2812c9e
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ramji\npm-debug.log
```

**Comment by zkat** [comment] 2016-12-09 00:44
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:44 UTC
Labels: shasum, support
