### ISSUE TITLE
I am trying to install Ionic 2 , using the command.  npm install -g ionic cordova

### ISSUE THREAD

**Issue by ImmanuelCE** [npm/npm#15846] opened 2017-02-23 15:23 UTC
I am trying to install Ionic 2 , using the command.
 npm install -g ionic cordova

I am getting following errors.

npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\CECH008\AppData\Local\Temp\npm-12112-7c99fa53\registry.npmjs.org\typedarray-\typedarray-0.0.6.tgz.328925666' -> 'C:\Users\CECH008\AppData\Local\Temp\npm-12112-7c99fa53\registry.npmjs.org\typedarray-\typedarray-0.0.6.tgz'
 npm ERR! Windows_NT 10.0.10586
 npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "ionic" "cordova"
 npm ERR! node v7.6.0
 npm ERR! npm v4.1.2

npm ERR! tarball.destroy is not a function
 npm ERR!
 npm ERR! If you need help, you may report this error at:
 npm ERR! https://github.com/npm/npm/issues

**Comment by legodude17** [comment] 2017-02-23 17:32
Duplicate of #15674.

**Closed** 2017-06-17 04:05 UTC
Labels: bot-closed
