### ISSUE TITLE
npm update replacing linked modules?

### ISSUE THREAD

**Issue by craigyk** [npm/npm#3157] opened 2013-02-13 18:52 UTC
Is npm update supposed to replace linked modules with ones from the repository, even if the linked module has a higher version number?  This is happening to me whenever I npm update and it's getting annoying.  Am I doing it wrong?

**Comment by smikes** [comment] 2015-02-09 04:17
/cc @othiym23 is this really a bug, or more like a feature request?  I am not sure what change this issue represents:

1. change `npm update` to ignore linked directories (luk-'s suggestion)

2. change `npm update` to check package.json of linked dependencies, and apply `semver` to the version in its `package.json`, the versions available from the registry, and the version range specified as a {dev,}dependency of the package being updated (@domenic's suggestion)

@craigyk , do you have an opinion about which is a better approach to this?

**Comment by othiym23** [comment] 2015-02-09 23:20
Implicitly deciding whether to replace or keep a linked module based on semver seems overly clever. Either npm should always replace the link with a module (which is what I believe it does now), or it should always leave the link alone. You have to explicitly opt in to using a linked module, and I believe that it makes sense to have to explicitly opt out, but the current behavior doesn't seem to surprise too many people. @iarna, do you have any thoughts on this? How does `multi-stage` handle this?

**Comment by jakub-g** [comment] 2015-10-16 13:19
I opened #10001 which is actually duplicate of this.
For me `npm update` replacing the linked module was rather surprising.
Should we document it as a feature, or fix it as a bug? (or perhaps document current behavior, and add a flag to `npm update` to prevent this from happening?)

**Comment by jakub-g** [comment] 2015-10-23 19:41
The issue is actually gone in npm3 via this commit

https://github.com/npm/npm/commit/bfe37e01a1e470eb2f076d1f9e6199fdd32ef43f#diff-b94b9e0be7f39c507f925fed87e016c6

(but still reproducible in npm2, see #10001 for details)

Do you think we should try to backport the fix to npm2 or document the behavior on https://docs.npmjs.com/cli/link ?

**Closed** 2017-06-19 11:31 UTC
Labels: bot-closed, bug
