### ISSUE TITLE
Can't install cordova

### ISSUE THREAD

**Issue by alfatta** [npm/npm#8626] opened 2015-06-21 02:57 UTC
I have some problem while i started to install cordova
I use windows 7
I run npm install -g cordova in administrator mode

---------- here's my cmd looks
C:\>npm install -g cordova
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v0.12.4
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
/
npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

---------- here's my npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.12.0
3 info using node@v0.12.4
4 verbose install initial load of D:\Program Files\nodejs\package.json
5 verbose readDependencies loading dependencies from D:\Program Files\nodejs\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec { raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cordova@*
10 verbose addNamed "*" is a valid semver range for cordova
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cordova
16 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 9:43:04 AM
20 verbose request using bearer token for auth
21 verbose request id c6bf8a9c2e6ba528
22 verbose etag "CHTP6Z7IEZ5MQODAPIGSTCZPS"
23 http request GET https://registry.npmjs.org/cordova
24 http 304 https://registry.npmjs.org/cordova
25 silly get cb [ 304,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"CHTP6Z7IEZ5MQODAPIGSTCZPS"',
25 silly get     'cache-control': 'max-age=60',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Sun, 21 Jun 2015 02:43:05 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-sin6921-SIN',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1434854584.873831,VS0,VE268' } ]
26 verbose etag https://registry.npmjs.org/cordova from cache
27 verbose get saving cordova to C:\Users\Alfatta\AppData\Roaming\npm-cache\registry.npmjs.org\cordova\.cache.json
28 verbose stack TypeError: undefined is not a function
28 verbose stack     at calculateOwner (D:\Program Files\nodejs\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
28 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\utils\correct-mkdir.js:23:22
28 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
29 verbose cwd C:\
30 error Windows_NT 6.1.7600
31 error argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
32 error node v0.12.4
33 error npm  v2.12.0
34 error undefined is not a function
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2015-06-21 15:44
Line in question: https://github.com/npm/npm/blob/v2.12.0/lib/utils/correct-mkdir.js#L37

@othiym23 I wonder if this is because `process.getuid()` is [not available on Windows](https://nodejs.org/api/process.html#process_process_getuid)?

**Comment by watilde** [comment] 2015-06-21 17:19
That's true, but `calculateOwner` shouldn't executed if `process.getuid` is not available: https://github.com/npm/npm/blob/v2.12.0/lib/utils/correct-mkdir.js#L59

**Comment by alfatta** [comment] 2015-06-21 22:05
please help me.....

**Comment by KenanY** [comment] 2015-06-21 22:24
@watilde Ah, good catch, but stack trace says `calculateOwner` is executed [here](https://github.com/npm/npm/blob/v2.12.0/lib/utils/correct-mkdir.js#L23)?

**Comment by othiym23** [comment] 2015-06-26 17:20
This is fixed in `npm@2.12.1` (via 7e5da238ee869201fdb9027c27b79b0f76b440a8), but unfortunately, to upgrade to it (it's `npm@next` right now) on Windows, you might have to downgrade. The fastest and easiest way to do this is using one of the official Node.js or io.js installers to reinstall both Node and npm. Thanks for filing this issue, because it's what alerted me that there was a problem here. And sorry for introducing the regression in the first place! This kind of change is very hard to test, but that's not an excuse.

**Closed by othiym23** 2015-06-26 17:20 UTC
Labels: support

**Comment by baileyburritt** [comment] 2015-06-27 18:33
I was having the exact same issue as the user above. I tried updating to the latest npm (running v2.12.0) but received the exact same error. 

C:\Users\My Computer>npm install -g npm@latest
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\My Computer\\AppData\\Roaming\\npm\\node_module
s\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
\
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\My Computer\npm-debug.log

C:\Users\My Computer>

**Comment by ldez** [comment] 2015-06-28 13:04
Try to do:
```shell
npm uninstall -g npm
npm install -g npm@2.12.1
```

**Comment by axtens** [comment] 2015-06-28 13:30
That did not work wonderfully. Having uninstalled npm, how can I now use it to install npm? 

Its seems as though you've told me to shoot myself in the foot. It worked. Now I'm crippled.

**Comment by ldez** [comment] 2015-06-28 13:37
I do myself.

NPM is installed into 2 places:
  - `C:\Users\[your username]\AppData\Roaming\npm`
  - `C:\Programs files\nodejs\node_modules\npm`

When your do `npm uninstall -g npm` this uninstall `C:\Users\[your username]\AppData\Roaming\npm` but not  `C:\Programs files\nodejs\node_modules\npm`

**Comment by roseanngabon** [comment] 2015-12-15 11:36
It didn't work for me
<code>npm uninstall -g npm</code>
<code>npm install -g npm@2.12.1</code>
------------------------------------------------
I've just solved now this issue. This is what I did
My OS: Windows 8.1

1. Go to Control Panel > System and Security > System > Environment Variables. 
2. Add to PATH this: %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\; 
3. I installed all required modules. (You will see the error when you type <code>cordova -v</code>)
(Here are the modules prompted that i've installed)
4. <code>npm install --save path-is-absolute</code>
5. <code>npm install --g path-is-absolute</code>
6. <code>npm install --g inflight</code>
7. <code>npm install --g once</code>
8. Check if you still see errors when you type in <code>cordova -v</code>

Note: I use to install this required module for ionic setup
