### ISSUE TITLE
Error when updating specific npm version to newest one

### ISSUE THREAD

**Issue by scf2k** [npm/npm#4459] opened 2014-01-10 08:59 UTC
```
$ npm --version
1.2.30
$ npm -g install npm
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-1.3.23.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-1.3.23.tgz
npm WARN package.json github-url-from-git@1.1.1 No repository field.
/home/travis/.nvm/v0.8.26/bin/npm -> /home/travis/.nvm/v0.8.26/lib/node_modules/npm/bin/npm-cli.js
npm ERR! EEXIST, symlink '../../../lib/node_modules/npm/man/man1/repo.1'
File exists: ../../../lib/node_modules/npm/man/man1/repo.1
Move it away, and try again. 
npm ERR! System Linux 2.6.32-042stab079.5
npm ERR! command "/home/travis/.nvm/v0.8.26/bin/node" "/home/travis/.nvm/v0.8.26/bin/npm" "-g" "install" "npm"
npm ERR! cwd /home/travis/build/bem/bem-tools
npm ERR! node -v v0.8.26
npm ERR! npm -v 1.2.30
npm ERR! path ../../../lib/node_modules/npm/man/man1/repo.1
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/bem/bem-tools/npm-debug.log
npm ERR! not ok code 0
The command "npm -g install npm" failed and exited with 47 during before_install.
```
Reproducing only with -g and with specific version. Doesn't happen when some older 1.3.x version is installed.

**Comment by smikes** [comment] 2015-02-02 16:33
Is this still a problem for you?

At this point, since current `node` is 0.10.36 (or io.js 1.0.4), and current `npm` is 2.4.1, I think even if there is a reproducible problem in 1.2 or 1.3 regarding this upgrade, it will probably never be fixed.

If you are still running node version 0.8, please upgrade to a newer version.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Closed** 2015-02-02 16:51 UTC
Labels: support
