### ISSUE TITLE
.npmignore not recognizing pattern correctly

### ISSUE THREAD

**Issue by unional** [npm/npm#13356] opened 2016-07-12 18:07 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have this `.npmignore` file:

```
**/*.spec.*
```

It should exclude the test files.
But the test files remain in the distribution.

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: 4.4.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X

**Comment by unional** [comment] 2016-07-12 23:16
Is it possible that `.npmignore` doesn't work with `package.json/files`?

**Comment by Turbo87** [comment] 2016-09-17 16:42
@unional unfortunately, yes: https://github.com/npm/npm/issues/4479

**Comment by busches** [comment] 2016-10-03 12:59
@KenanY based on @unional's comment, appears to be a duplicate of #4479

**Closed** 2016-10-03 13:00 UTC
