### ISSUE TITLE
Error attempting to uninstall the cookie-parser package

### ISSUE THREAD

**Issue by jpierson** [npm/npm#10517] opened 2015-11-23 02:14 UTC
Error attempting to run `npm uninstall --save cookie-parser`.

>
C:\MYDIR [dev ↑ +6 ~1 -0 !]> npm uninstall --save cookie-parser
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "uninstall" "--save" "cookie-parser"
npm ERR! node v4.2.1
npm ERR! npm  v3.4.1
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:426:3)
npm ERR! typeerror     at C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:235:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:231:8)
npm ERR! typeerror     at Array.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm ERR! typeerror     at chain (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (C:\Users\me\AppData\Roaming\npm\node_modules\npm\lib\uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\MYDIR\npm-debug.log

[npm-debug.log.txt](https://github.com/npm/npm/files/41253/npm-debug.log.txt)

**Comment by jpierson** [comment] 2015-11-23 02:18
Rerunning `npm install cookie-parser --save` followed by `npm uninstall --save cookie-parser` again seems to have done the trick. The problem I ran into seems to come from issuing an `npm uninstall cookie-parser` command first without the _--save_ option and then attempting to run the command again with the _--save_ command attempting to get npm to clean up my project.json file for me.

**Comment by othiym23** [comment] 2015-12-04 17:34
Closing as duplicate of #10571.

**Closed by othiym23** 2015-12-04 17:34 UTC
Labels: bug
