### ISSUE TITLE
npm doesn't respect .gitignore if ignored folder has an index.js in it.

### ISSUE THREAD

**Issue by jdalton** [npm/npm#3968] opened 2013-10-04 04:44 UTC
I noticed this behavior.
If my `.gitignore` looks like:
```text
.DS_Store
legacy
node_modules
mobile
```

and I run `npm pack`

the package will contain the folders `mobile` and `legacy` if there is an `index.js` file in them. If I remove the `index.js` file it will ignore them.

The workaround atm is to include `mobile` and `legacy` in the `.npmignore` file as well.

**Comment by peter-mouland** [comment] 2016-04-08 09:59
old issue, but as it's still open, i'll try to help close it.

What you describe is now the desired behaviour as mentioned in the docs, [keeping-files-out-of-your-package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):
```
If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.
```

**Comment by jdalton** [comment] 2016-04-08 14:01
@peter-mouland This is the opposite of that. These files should be ignored by npm as per the .gitignore file but are not.

**Comment by jdalton** [comment] 2016-04-12 21:32
\cc @zkat

**Comment by zkat** [comment] 2016-04-12 21:37
@jdalton Added to the milestone! Thanks a *ton* for the ping :)

**Comment by zkat** [comment] 2016-04-13 17:55
@jdalton Hey so, I looked at this a little closer. I can't reproduce the behavior you described, for a couple of expected reasons:

* [`.npmignore` _completely overrides_ `.gitignore`](https://github.com/npm/npm/blob/master/test/tap/files-and-ignores.js#L249). There is no merging involved.
* I assume when you say "it'll ignore `mobile`", you mean that there's files in there other than `index.js`. [Empty directories are not included](https://github.com/npm/npm/blob/master/test/tap/files-and-ignores.js#L569).
* It's possible that `mobile` was still going to be ignored if there were non-`index.js` contents, sometime in the past, but I can't see that being a problem with the way `npm pack` works now. I'll note you opened the issue back in 2013 originally, so I wouldn't be surprised :)

Based on that, and unless I'm misunderstanding your report, this seems to be working as intended. Is that the case?

**Comment by jdalton** [comment] 2016-04-13 18:00
I'll sanity check it asap.

**Comment by jdalton** [comment] 2016-04-13 20:56
>  .npmignore completely overrides .gitignore. There is no merging involved.

That would explain why an empty .npmignore lets things through that .gitignore is ignoring.

**Comment by jdalton** [comment] 2016-04-13 20:56
If that's the case, and it's by design, then this issue can be closed.

**Comment by zkat** [comment] 2016-04-13 22:35
Indeed. I think you already know about it, but [there's a nice wiki page](https://github.com/npm/npm/wiki/Files-and-Ignores) now that goes into detail about how this stuff works.

Since things seem to be working as expected, I'm closing this. There's a couple of issues/PRs that might affect this behavior, too, if you want to keep an eye on them or put in your 2c, specifically #12331 and #11669.

Cheers :dancer:

**Closed by zkat** 2016-04-13 22:35 UTC
Labels: bug

**Comment by jdalton** [comment] 2016-04-13 22:40
Thanks!
