### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601(getting this error while installing protractor)

### ISSUE THREAD

**Issue by suresh444** [npm/npm#15812] opened 2017-02-21 10:02 UTC
npm ERR! argv "D:pro\\soft\\nodejs\\node.exe" "D:\\pro\\soft\\node
js\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pro\soft\nodejs\npm-debug.log

**Comment by MohsinGhani** [comment] 2017-02-23 19:25
i also have this error :(

**Comment by legodude17** [comment] 2017-02-24 17:49
This might be some sort of network issue.

Duplicate of #15849.

**Closed** 2017-06-17 04:07 UTC
Labels: bot-closed
