### ISSUE TITLE
Getting Error when downloading the npm https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz

### ISSUE THREAD

**Issue by weilingsu** [npm/npm#12239] opened 2016-04-06 17:32 UTC

**Comment by othiym23** [comment] 2016-04-06 17:36
Closing as a duplicate of #12196. See that issue for details and context – the npm registry team is working on resolving this issue on npm's end. A quick way to work around the problem for you would be to update Jenkins to use a newer build of both Node and npm, which is a good idea anyway given that Node 0.10 is approaching the end of maintenance (and `npm@1.3` has been unsupported by the npm CLI team for several years now). Thanks for your time!

**Closed by othiym23** 2016-04-06 17:36 UTC
Labels: registry, support
