### ISSUE TITLE
uninstall bootstrap@4.0.0-alpha.2 error

### ISSUE THREAD

**Issue by smerth** [npm/npm#11184] opened 2016-01-17 08:00 UTC
I installed bootstrap 4: npm install --save-dev bootstrap@4.0.0-alpha.2
I uninstalled: npm uninstall --save-dev bootstrap@4.0.0-alpha.2

This resulted in a lot of errors at the end of which I got: npm ERR! typeerror This is an error with npm itself.

So here is the nam-debug.log:

[npm-debug.txt](https://github.com/npm/npm/files/93248/npm-debug.txt)

**Comment by othiym23** [comment] 2016-01-18 03:48
This is a duplicate of #11014, and so I'm closing it as such. It's on our list of big bugs, so it should be addressed in the reasonably near term.

**Closed by othiym23** 2016-01-18 03:48 UTC
Labels: bug

**Comment by smerth** [comment] 2016-01-18 07:58
Sorry I should have checked the issue queue more closely.
