### ISSUE TITLE
failed to install few packages with Error 503.

### ISSUE THREAD

**Issue by amolgawai** [npm/npm#6948] opened 2014-12-16 16:37 UTC
I am behind a corporate proxy and have appropriate proxy settings. I am able to install some packages without problem (e.g. gulp, bower etc.). But the npm install fails for packages like browserify, yo. I get fetch failed errors for pako and tar packages. I googled and tried a variety of suggestions, nothing is working. I am trying this for two days now and checked weather npm registry is down.

Following is a sample output.
 npm install -g browserify
npm ERR! fetch failed http://registry.npmjs.org/pako/-/pako-0.2.5.tgz
npm ERR! fetch failed http://registry.npmjs.org/pako/-/pako-0.2.5.tgz
npm ERR! fetch failed http://registry.npmjs.org/pako/-/pako-0.2.5.tgz
npm ERR! Error: 503 Service Unavailable
npm ERR!     at WriteStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\fetch.js
:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1609:14
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102
:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "-g" "browserify"
npm ERR! cwd C:\Users\gawaiam
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28

detailed config
λ npm config list                                                                                      
; cli configs                                                                                          
registry = "http://registry.npmjs.org/"                                                                
user-agent = "npm/1.4.28 node/v0.10.33 win32 x64"                                                      
                                                                                                       
; userconfig C:\Users\gawaiam\.npmrc                                                                   
https-proxy = EDITED TO HIDE CONTENT                    
proxy = EDITED TO HIDE CONTENT
registry = "http://registry.npmjs.org/"                                                                
strict-ssl = false                                                                                     
user = EDITED TO HIDE CONTENT                                                                                       
                                                                                                       
; builtin config undefined                                                                             
prefix = "C:\\Users\\gawaiam\\AppData\\Roaming\\npm"                                                   
                                                                                                       
; node bin location = C:\Program Files\nodejs\\node.exe                                                
; cwd = C:\Users\gawaiam                                                                               
; HOME = C:\Users\gawaiam                                                                              
; 'npm config ls -l' to show all defaults.

**Comment by amolgawai** [comment] 2015-01-12 17:03
I installed the problematic packages (pako & tar) by downloading their sources and using `node install -g <path-to-local-source-directory>`. Then browserify and yeoman could be installed properly.
Also I noted that when I tried to visit pako at npmjs.com, I got ssl errors (not able to reproduce right now to give the correct error).

**Comment by amolgawai** [comment] 2015-01-15 09:21
Following errors occur for tar and pako when I try to visit their pages on npmjs.org

>Network Error (ssl_domain_invalid)  
>The name on the HTTPS-certificate did not match the domain requested.   
>This is typically caused by a configuration error of the requested Web Site.

**Comment by smikes** [comment] 2015-03-20 14:34
Is this still a problem for you?

Is it possible that you are using a proxy that intercepts ssl connections?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by amolgawai** [comment] 2015-03-20 15:27
Yes. This is still a problem for me although I have found a workaround as described in my comment of Jan 12. I still get errors for pako and tar packages.

**Comment by smikes** [comment] 2015-03-20 15:55
Can you try updating your version of `npm`?  If you are still using `npm@1.4.28`, it's known to have some race conditions and bugs that affect installation on Windows.

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

> Option 3: navigate to  C:\Program Files (x86)\nodejs with cmd.exe and then run the installation without -g:

```
> cd  C:\Program Files (x86)\nodejs
> npm install npm@latest
```

**Comment by amolgawai** [comment] 2015-03-20 16:16
I did upgrade npm to 2.1.12 and still had problems. Right now I am using npm 2.1.18 and still have those problems.

**Comment by smikes** [comment] 2015-03-20 17:38
Sorry, I missed that. The current version is now 2.7.2 and substantial fixes to the Git support on windows went in pretty recently (>2.5). I am not at a windows machine now but I will be on Monday, so I will see if I can reproduce the problem and narrow down the cause.

**Comment by smikes** [comment] 2015-03-31 15:53
Just a ping to let you know I can follow up to this now.

**Comment by smikes** [comment] 2015-04-29 16:30
Is this still a problem for you?  I have not been able to reproduce it on my Windows machine, probably because I do not use a proxy on that network.

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- including better windows support and git dependency handling -- since 2.1.12. Can you try, once again, updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment] 2015-08-11 20:54
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Closed by ehsalazar** 2015-08-11 20:54 UTC
Labels: registry, support
