### ISSUE TITLE
npm ERR! invalid: readable-stream and string_decoder

### ISSUE THREAD

**Issue by muhasturk** [npm/npm#7139] opened 2015-01-14 18:16 UTC
Running `npm list -g`returns;

```

npm ERR! invalid: readable-stream@1.0.27-1 /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/node_modules/readable-stream
npm ERR! invalid: string_decoder@0.10.25-1 /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/string_decoder
```

What is the problem?

**Comment by smikes** [comment] 2015-01-15 14:07
It might be that you have run `npm update -g` at some point in the past, which tends to break things.

You may be able to fix it with `npm-check`:

```
npm install -g npm-check
npm-check -g
```

Can you tell us more about your `npm` version and what you're trying to do?

**Comment by muhasturk** [comment] 2015-01-15 14:26
I just want to see installed global packages.

```
☁  /tmp  npm --version
2.1.18
☁  /tmp  node --version
v0.10.35
```

**Comment by smikes** [comment] 2015-01-15 14:43
npm ls -g 

Should show you global packages. Are you seeing only the ERR: lines, or packages as well?

**Comment by muhasturk** [comment] 2015-01-15 14:48
as you already may know ls and list are same effect. I can see installed global packages. Hoewer there are two lines error at he bottom of output.

Full output when I run `npm list -g`or `npm ls -g``
http://hastebin.com/okoxafuwaj.pl

**Comment by smikes** [comment] 2015-01-15 17:05
You can either ignore the warning or try removing and reinstalling cordova :

npm rm -g cordova
npm i -g cordova@latest

If the warning persists after that, you should try following up with the Cordova development team. npm seems to be working as intended.

**Comment by othiym23** [comment] 2015-01-17 07:18
Closing as resolved.

**Closed by othiym23** 2015-01-17 07:18 UTC
Labels: support
