### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by mayurtank** [npm/npm#12653] opened 2016-05-10 19:11 UTC
Error: This is most likely not a problem with npm itself
error network and is related to network connectivity.
error network In most cases you are behind a proxy or have bad network settings.

When I try to install npm in windows.

Thanks for the help in advance :)

**Comment by KenanY** [comment] 2016-05-10 23:10
@mayurtank As the error message states, this is an issue with your internet connection, probably caused by a proxy or firewall messing with `npm`'s connection to the registry. Ensure that you have configured `npm` to use your proxy, or allowed it to make connections past your firewall. For some other users here the issue was in their router somehow, so you could take a look there as well.

**Comment by KenanY** [comment] 2016-05-17 14:30
@mayurtank Just following up a week later: are you still seeing this issue?

**Comment by KenanY** [comment] 2016-06-28 20:47
Closing as abandoned.

**Closed by KenanY** 2016-06-28 20:47 UTC
Labels: proxy, support, windows
