### ISSUE TITLE
Installing Angular-cli in windows 10 pro

### ISSUE THREAD

**Issue by Metwalli** [npm/npm#14385] opened 2016-10-22 17:24 UTC
I tried to install Angular-cli , I have the error message as below:

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Metwalli\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for C:\Users\Metwalli\AppData\Local\Temp\npm-8644-a94bead7\registry.npmjs.org\mout-\mout-1.0.0.tgz
npm ERR! Expected: 9bdf1d4af57d66d47cb353a6335a3281098e1501
npm ERR! Actual:   bf10a82f029a4f90eb14a524a0cac32ea6d422b1
npm ERR! From:     https://registry.npmjs.org/mout/-/mout-1.0.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Dev\Angular\material\material-app\npm-debug.log
```

**Comment by zkat** [comment] 2016-12-09 00:35
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:35 UTC
Labels: shasum, support
