### ISSUE TITLE
Save disk space by creating symlinks instead of making copies in node_modules

### ISSUE THREAD

**Issue by KSXGitHub** [npm/npm#19663] opened 2018-01-22 07:53 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

Instead of making copy of the same packages every time user run `npm install`, npm should download packages (that don't have a `postinstall` script) to a shared directory (e.g. `~/.npm/packages`) and create symlinks (or "junction" in Windows) inside `node_modules`.

#### What problem is the feature intended to solve?

* Eliminate package duplication, save disk usage.

* Enable a potential "strict mode" feature which disallows programmers to `require` things that aren't in `package.json`.

#### How it works?

How shared packages directory would look like:

```
--~/.npm/packages
  |--foo
  |  |--1.0.0
  |  |  |--node_modules (contains symlinks to other packages)
  |  |--2.0.0
  |  |  |--node_modules
  |--bar
  |  |--1.2.3
  |  |  |--node_modules

  ...
```

How `node_modules` should look like:

```
--node_modules
  |--foo → ~/.npm/packages/foo/1.0.0
  |--bar → ~/.npm/packages/bar/2.0.0
```

#### Caveats

Native Node.js modules (C++ add-ons) may not work this way so it's OK to install them directly into `node_modules` folder.

#### Is the absence of this feature blocking you or your team? If so, how?

My disk space is limited.

**Comment by kenany** [comment] 2018-01-22 15:54
Duplicate of https://github.com/npm/npm/issues/18068?

**Comment by KSXGitHub** [comment] 2018-01-22 16:00
@KenanY Yep, definitely a duplication, let's focus on the other one!

**Closed as completed** 2018-01-22 16:01 UTC
