### ISSUE TITLE
npm doctor fails against a Nexus 3 NPM repository

### ISSUE THREAD

**Issue by danshome** [npm/npm#15306] opened 2016-12-24 01:07 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Beside npm doctor everything else seems to work fine. I can both install and publish to Nexus3 just fine, it's only the npm doctor command that fails. 

npm doctor fails against a Nexus 3 NPM repository

npm doctor
npm ERR! registry error parsing json
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/Dan/workspace/cris-trunk/node/node" "/Users/Dan/workspace/cris-trunk/node/node_modules/npm/bin/npm-cli.js" "doctor"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.1

npm ERR! Unexpected token < in JSON at position 1
npm ERR! 
npm ERR! <!DOCTYPE html>
npm ERR! <html>
npm ERR! <head>
npm ERR!   <title>400 - Nexus Repository Manager</title>
npm ERR!   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
npm ERR! 
npm ERR! 
...

#### How can the CLI team reproduce the problem?

Configure you registry to point to a Nexus3 NPM repository, then run npm doctor. 

### supporting information:

 - `npm -v` prints: 4.1.1

 - `node -v` prints: 7.3.0

 - `npm config get registry` prints:

https://myinternalrepo.mydomain.local/nexus3/repository/myinternal-npm-group/

 - Windows, OS X/macOS, or Linux?:
 OS X

 - Network issues:

Nexus3 is configured behind an Apache 2.4 reverse proxy as documented in the Nexus 3 documentation.

**Comment by danshome** [comment] 2016-12-24 01:08
After further investigation the problem may be the npm ping command that's the issue. 

npm ping
npm ERR! registry error parsing json
undefined
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/Dan/workspace/cris-trunk/node/node" "/Users/Dan/workspace/cris-trunk/node/node_modules/npm/bin/npm-cli.js" "ping"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.1

npm ERR! Unexpected token < in JSON at position 1
npm ERR!

**Comment by legodude17** [comment] 2016-12-26 21:09
This is probably a result of Nexus3 implementing the `ping` endpoint incorrectly.

**Comment by othiym23** [comment] 2017-01-04 01:12
I doubt that any registries other than the primary npm registry support the `/whoami` endpoint used by ping. This is a situation where `npm doctor` should be prepared for failure, so it should probably guard against parsing failure and indicate that in the command output. @watilde, 1. happy new year! (:tada:), and 2. is this something you'd be willing to take a look at?

**Comment by watilde** [comment] 2017-01-04 01:57
@othiym23 Happy new year all! I guess this error is caused by `npm.registry.ping` and endpoint should be `/ping`. Then I will investigate more.

@danshome It would be helpful if you can give us your `npm-debug.log` file if it's possible. Thanks!

**Comment by othiym23** [comment] 2017-01-04 03:27
We're probably thinking the same thoughts here, but just to make sure, let me write down some pseudocode.

For the purposes of `npm doctor`, after the ping command gets a response:

- an HTTP status code of 301 or 302 should be followed (which I think `npm-registry-client` already does by default, so you're unlikely to see this)
- an HTTP status code of 404 means that the pinged registry doesn't support pinging, which, if we're distinguishing between warnings and errors, counts as a warning
- an HTTP status code of 401 means that you either need to log in or to put an auth token where npm can find it
- an HTTP status code of 407 probably means proxy configuration is either missing or incorrect
- any other 4xx status code should be assumed to mean the ping command isn't supported (which is, again, a warning)
- an HTTP status code of 50x is an error, and the status code should be reported
- an HTTP status of 200 should proceed, with:
  - a failure to parse the response body as JSON marked as a 404 in disguise (i.e. the ping endpoint isn't supported, or, as in the case of Nexus, the registry's application container doesn't know to return JSON for unmatched request paths) – flag as a warning
  - a JSON response body missing the expected payload (`{}`), counts as an error
  - everything making it to this point being A-OK

If you want to continue to roll everything up into `ok` or `notOk`, that's totally fine, but if you want to get fancy, the above will give users the most actionable feedback. Given that most users can't be expected to know the ins and outs of the registry API, we shouldn't alarm them about the fact that an endpoint isn't available if it's something over which they have no control.

Thanks for picking this up! And, once again, thanks for taking the initiative to make `npm doctor` a thing!

**Comment by watilde** [comment] 2017-04-24 18:26
We can close this issue :)

**Comment by KenanY** [comment] 2017-04-25 18:43
Roger that!

**Closed by KenanY** 2017-04-25 18:43 UTC
Labels: bug, supportability
