### ISSUE TITLE
How can I install socket.io

### ISSUE THREAD

**Issue by Anjan-Chowdhury** [npm/npm#11052] opened 2016-01-06 11:45 UTC
when I install npm install socket.io --save have some error :-1: 

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install" "socket.io" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ChatApp\npm-debug.log
```

Now what i will do  please help me to solve the error.

**Comment by KenanY** [comment] 2016-01-06 12:42
@Anjan-Chowdhury Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) `npm`.

**Comment by KenanY** [comment] 2016-01-06 12:43
Dupe of https://github.com/npm/npm/issues/11051 by same user (but this one has error log).

**Comment by KenanY** [comment] 2016-01-06 12:44
(and https://github.com/npm/npm/issues/11049)

**Comment by Anjan-Chowdhury** [comment] 2016-01-06 13:31
Thanks
Now I upgrade my npm version and and install socket.io package.

**Comment by Anjan-Chowdhury** [comment] 2016-01-06 13:34
but now have a problem in socket.io package when i run my app

C:\ChatApp\node_modules\socket.io\lib\static.js:100
    client.builder(transports, {
           ^

TypeError: client.builder is not a function
    at build (C:\ChatApp\node_modules\socket.io\lib\static.js:100:12)
    at Static.<anonymous> (C:\ChatApp\node_modules\socket.io\lib\static.js:121:5
)
    at Static.write (C:\ChatApp\node_modules\socket.io\lib\static.js:388:24)
    at Manager.handleRequest (C:\ChatApp\node_modules\socket.io\lib\manager.js:5
96:19)
    at Server.<anonymous> (C:\ChatApp\node_modules\socket.io\lib\manager.js:119:
10)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:527:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

C:\ChatApp>

**Comment by KenanY** [comment] 2016-01-06 13:36
@Anjan-Chowdhury That does not look like an error that is coming from `npm`. I think it would be best if you showed that to other socket.io users; they will know a lot more about what your problem might be.

**Comment by Anjan-Chowdhury** [comment] 2016-01-06 13:45
ok sir

**Comment by KenanY** [comment] 2016-06-28 21:28
Closing as resolved.

**Closed by KenanY** 2016-06-28 21:28 UTC
Labels: support
