### ISSUE TITLE
NPM install gives this error

### ISSUE THREAD

**Issue by bksoumya** [npm/npm#12243] opened 2016-04-06 21:38 UTC
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m SyntaxError: Unexpected token 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m ��T�n�0�Bg[�-%��@�)��� ���D"�r���>Z�#�@�� �Ù�fy|�(XD�J��YP�F�Nj�!7�\C�x�ю�cR1�,9�+F��=GDؑ��w��\�M�~<��Պ��+�QհS�e��6�Z�-d�>��q0��8ׯ��O�a�����4��wg�k=�-���1�:�7d�7�Z���X�����\#U�WG���Y�JA��꼿�C��({�����TK_�g��������DRѹ��\���zR%)!	�p��|�q�W�i�p��0
�n�l���@��gx�������ç�����9B3QP��瞻q(��I`]������ü%�`�����B��}�İ���%m;] #G�T�F�)N�ݿ�;�wD_1��ZҪ�b
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m ����Y�th��% �$�X�R�E�\Ty���/�U���E�'E�W"^.��C}����Ik�	�
���?�/�Y����iZ6'
mm����V�ȓ$ˋ�SZ-�8Ͳ�Eʓ��H��0�I������A��U�}�Hs��O�_,M��e���J��r�^Ğ�o"U��$~R��SB�ګ�����Wq���V/����������1T#n ��ކ�<�7���<?�&t�/��R�F9�"^�R\
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at Object.parse (native)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at Request.EventEmitter.emit (events.js:98:17)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at Request.EventEmitter.emit (events.js:117:20)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at IncomingMessage.EventEmitter.emit (events.js:117:20)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at _stream_readable.js:920:16
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     at process._tickCallback (node.js:415:13)
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m If you need help, you may report this log at:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     <http://github.com/isaacs/npm/issues>
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m or email it to:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     <npm-@googlegroups.com>
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mSystem[0m Linux 3.16.0-30-generic
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mcommand[0m "/usr/bin/nodejs" "/usr/bin/npm" "install" "--registry" "http://registry.npmjs.org/"

**Comment by othiym23** [comment] 2016-04-06 21:42
Closing as duplicate of #12196. See that issue for context and current status towards resolution.

**Closed by othiym23** 2016-04-06 21:43 UTC
