### ISSUE TITLE
Failed to install nodetime

### ISSUE THREAD

**Issue by ayanamist** [npm/npm#3955] opened 2013-09-30 11:50 UTC
```
npm http GET https://registry.npmjs.org/nodetime
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at Agent.request (_http_agent.js:278:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:51:22)
npm ERR!     at TunnelingAgent.createSocket (/home/ayanamist/.nvm/v0.11.7/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/home/ayanamist/.nvm/v0.11.7/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (/home/ayanamist/.nvm/v0.11.7/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:122:16)
npm ERR!     at Agent.request (_http_agent.js:293:10)
npm ERR!     at Object.exports.request (https.js:129:22)
npm ERR!     at Request.start (/home/ayanamist/.nvm/v0.11.7/lib/node_modules/npm/node_modules/request/index.js:604:30)
npm ERR!     at Request.end (/home/ayanamist/.nvm/v0.11.7/lib/node_modules/npm/node_modules/request/index.js:1211:28)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.8.0-31-generic
npm ERR! command "/home/ayanamist/.nvm/v0.11.7/bin/node" "/home/ayanamist/.nvm/v0.11.7/bin/npm" "install" "nodetime"
npm ERR! cwd /home/ayanamist/WebstormProjects/hr
npm ERR! node -v v0.11.7
npm ERR! npm -v 1.3.8
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ayanamist/WebstormProjects/hr/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment] 2015-02-03 21:03
Is this still a problem for you?

I note that I am unable to install nodetime today, but the error I am seeing is different:
```
> nodetime-native@0.1.0 install /Users/smikes/src/github/baz/node_modules/nodetime/node_modules/nodetime-native
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
```

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue as a support issue.  If you feel this is a bug that needs to be addressed, please let us know and we won't close it.

(In any case, don't worry -- you can always come back again and open a new issue.)

Thanks!

**Comment by othiym23** [comment] 2015-02-12 02:19
Closing as resolved / abandoned. I'm pretty sure `nodetime` has since been supplanted by AppDynamics's new node APM product, `appdynamics`. RIP, `nodetime`!

**Closed by othiym23** 2015-02-12 02:19 UTC
Labels: registry, support

**Comment by miellaby** [comment] 2015-04-10 12:30
I've got this bug when apache cordova CLI uses libnpm to install a module for itself. Also to reproduce the bug, you have to use npm behind a corporate proxy with authent credentials in the url (npm config https-proxy http://login:password@proxy:port) . Also npm must fetch a https:// registry URL.

I don't know exactly what I do, but I managed to patch the code of "tunnel-agent" so to fix the bug for now.

tunnel-agent\index.js line 73:
++  if (typeof host == typeof {}) {
++  	// throw Error("should not be an object" + JSON.stringify(host));
++  	port = host.uri.port;
++  	host = host.uri.host;
++  }

**Comment by smikes** [comment] 2015-04-10 13:26
@miellaby , this is quite an old case (from 2013 - 18 months ago!)  Could you please create a new case if you have a new bug report or support request?
