### ISSUE TITLE
npm ERR! tarball.destroy() is not a function

### ISSUE THREAD

**Issue by ningappa** [npm/npm#12489] opened 2016-04-27 05:51 UTC
Hi I'm having issue while installing react-dom module.

I'm able install other modules like react express modules, on windows 10. 64 bit machine, even i have free disk space.

```
npm install react-dom
npm WARN package.json -panel-client@1.0.0 No description
npm WARN package.json -panel-client@1.0.0 No repository field.
npm WARN package.json -panel-client@1.0.0 No README data
npm WARN package.json -panel-client@1.0.0 No license field.
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz.2090210803' -> 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-dom"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz.2000813013' -> 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz'
```

**Comment by busches** [comment] 2016-09-10 10:53
Duplicate of https://github.com/npm/npm/issues/8564 @KenanY

**Comment by KenanY** [comment] 2016-09-10 14:38
Alright, closing.

**Closed by KenanY** 2016-09-10 14:38 UTC
Labels: support, windows

**Comment by SwathiAbhi** [comment] 2017-03-01 21:29
HI ,
I'm able install other modules like react express modules, on windows 10. 64 bit machine, even i have free disk space.
please let me know if any suggestions to overcome this issue.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename
