### ISSUE TITLE
I am trying to update the already pulished npm module. But getting an error.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [npm/npm#9363] opened 2015-08-21 07:29 UTC
```
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/rajeshwar/.nvm/versions/node/v0.12.4/bin/npm" "publish"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.4

npm ERR! Arguments to path.resolve must be strings
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/rajeshwar/.nvm/versions/node/v0.12.4/bin/npm" "publish"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.4

npm ERR! Arguments to path.resolve must be strings
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rajeshwar/workspace/others/ionic-timepicker/npm-debug.log
```

**The log in npm-debug.log** is 

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/rajeshwar/.nvm/versions/node/v0.12.4/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.13.4
3 info using node@v0.12.4
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/rajeshwar/workspace/others/ionic-timepicker',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/rajeshwar/.npm/ionic-timepicker/0.3.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/rajeshwar/.npm/ionic-timepicker/0.3.0/package.tgz',
9 verbose tar pack   '/Users/rajeshwar/workspace/others/ionic-timepicker' ]
10 verbose tarball /Users/rajeshwar/.npm/ionic-timepicker/0.3.0/package.tgz
11 verbose folder /Users/rajeshwar/workspace/others/ionic-timepicker
12 info prepublish ionic-timepicker@0.3.0
13 verbose stack TypeError: Arguments to path.resolve must be strings
13 verbose stack     at Object.posix.resolve (path.js:439:13)
13 verbose stack     at Packer.applyIgnores (/Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:109:59)
13 verbose stack     at Packer.<anonymous> (/Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:181:17)
13 verbose stack     at Array.filter (native)
13 verbose stack     at Packer.IgnoreReader.filterEntries (/Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:179:31)
13 verbose stack     at Packer.<anonymous> (/Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:92:12)
13 verbose stack     at Packer.<anonymous> (/Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:134:5)
13 verbose stack     at /Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
13 verbose stack     at fs.js:334:14
13 verbose stack     at /Users/rajeshwar/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:42:10
14 verbose cwd /Users/rajeshwar/workspace/others/ionic-timepicker
15 error Darwin 14.0.0
16 error argv "node" "/Users/rajeshwar/.nvm/versions/node/v0.12.4/bin/npm" "publish"
17 error node v0.12.4
18 error npm  v2.13.4
19 error Arguments to path.resolve must be strings
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]
```

Please help me on this.

**Comment by pducks32** [comment] 2015-08-22 03:01
Having the exact same problem and have no clue what is up.

**Comment by snopeks** [comment] 2015-09-30 21:44
Hi @rajeshwarpatlolla, it looks like you're running into a bug that was fixed recently. If you upgrade your version of npm it should solve the problem :)

**Comment by rajeshwarpatlolla** [comment] 2015-10-01 04:05
I will check it and will get back to you if there is any other issue.

**Comment by snopeks** [comment] 2015-11-12 00:02
@rajeshwarpatlolla closing since it seems the issue is resolved now, yay :)  Let me know if this is still a problem.

**Closed by snopeks** 2015-11-12 00:02 UTC
Labels: support
