### ISSUE TITLE
Error updating multiple packages

### ISSUE THREAD

**Issue by aredridel** [npm/npm#9805] opened 2015-10-01 05:54 UTC
```
:; npm update lab sinon request boom bluebird
extend@3.0.0 node_modules/request/node_modules/extend -> node_modules/extend
estraverse@4.1.0 node_modules/eslint/node_modules/estraverse -> node_modules/lab/node_modules/estraverse
esprima@2.2.0 node_modules/eslint/node_modules/js-yaml/node_modules/esprima -> node_modules/lab/node_modules/js-yaml/node_modules/esprima
minimatch@2.0.10 node_modules/eslint/node_modules/minimatch -> node_modules/lab/node_modules/minimatch
object-assign@2.1.1 node_modules/eslint/node_modules/object-assign -> node_modules/lab/node_modules/object-assign
- qs@4.0.0 node_modules/request/node_modules/qs
minimist@0.0.8 node_modules/eslint/node_modules/minimist -> node_modules/write/node_modules/minimist
- eslint@1.0.0 node_modules/eslint
- espree@2.2.3 node_modules/eslint/node_modules/espree
- js-yaml@3.3.1 node_modules/eslint/node_modules/js-yaml
- mkdirp@0.5.1 node_modules/eslint/node_modules/mkdirp
- lolex@1.1.0 node_modules/lolex
newww@3.0.5 /Users/aredridel/Projects/npm/newww
├── @soldair/marky-markdown@6.0.0
├── bluebird@2.10.1
├── boom@2.9.0
├── browserify@5.13.1
├── eslint-config-hapi@2.0.1  extraneous
├── favicons@3.1.3
├── file-entry-cache@1.2.4  extraneous
├── gulp@3.9.0
├── gulp-concat@2.6.0
├── gulp-nodemon@1.0.5
├── gulp-uglify@0.3.2
├── handlebars@2.0.0
├── imagemin-pngcrush@1.0.0
├── is-resolvable@1.0.0  extraneous
├── mustache-mailer@2.1.2
├── nock@1.9.0
├── npm-explicit-installs@2.0.0
├── request@2.64.0
├── run-async@0.1.0  extraneous
├── rx-lite@2.5.2  extraneous
├── sinon@1.17.1
├── to-double-quotes@1.0.1  extraneous
└── to-single-quotes@1.0.3  extraneous

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/iojs/3.0.0/bin/iojs" "/Users/aredridel/bin/npm" "update" "lab" "sinon" "request" "boom" "bluebird"
npm ERR! node v3.0.0
npm ERR! npm  v3.3.5
npm ERR! path /Users/aredridel/Projects/npm/newww/node_modules/eslint/node_modules/estraverse
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/aredridel/Projects/npm/newww/node_modules/eslint/node_modules/estraverse' -> '/Users/aredridel/Projects/npm/newww/node_modules/lab/node_modules/estraverse'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aredridel/Projects/npm/newww/npm-debug.log
```

[`npm-debug.log`](https://gist.github.com/aredridel/55a94d907e9b6f502240)

**Comment by aredridel** [comment] 2015-10-01 05:55
This is is with version 9e378693f8112dd53a202bb5e54dfa035246a0b1, not plain 3.3.5

**Comment by iarna** [comment] 2015-11-06 19:49
Closing this as a duplicate of #9633

**Closed by iarna** 2015-11-06 19:49 UTC
