### ISSUE TITLE
npm cache node-gyp compiles for future packages

### ISSUE THREAD

**Issue by VespaGirl** [npm/npm#9546] opened 2015-09-10 17:57 UTC
Can we get this? Let me learn more about node and I will start contributing pull requests ^_^

**Comment by KenanY** [comment] 2015-09-10 19:20
I use [`ccache`](https://ccache.samba.org/) for this.

**Comment by KenanY** [comment] 2015-09-18 15:43
Duplicate of https://github.com/npm/npm/issues/3388 perhaps.

**Comment by othiym23** [comment] 2015-11-10 22:46
This is indeed a duplicate of #3388, so closing it as such (and we'll figure out how #3388 fits on the road map in a bit). Thanks, @KenanY! Thanks for volunteering to help out, @VespaGirl!

**Closed by othiym23** 2015-11-10 22:46 UTC
Labels: feature-request
