### ISSUE TITLE
issue on ubuntu 12.04.05 for installing some package

### ISSUE THREAD

**Issue by cnbarfish** [npm/npm#12181] opened 2016-04-04 08:49 UTC
I got some issue as below, anybody have idea or clue to solve the issue?

```
npm ERR! Linux 3.2.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.5

npm ERR! shasum check failed for /tmp/npm-16542-f3b37e89/registry.npmjs.org/jscs/-/jscs-2.11.0.tgz
npm ERR! Expected: 6e11ef0caaa07731f9dcc2b2b27d8ecee1ddbcb6
npm ERR! Actual:   a1327d2745555eb33d96ecd39e94dacd94b50e00
npm ERR! From:     https://registry.npmjs.org/jscs/-/jscs-2.11.0.tgz
```

**Comment by zkat** [comment] 2016-12-09 00:44
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:44 UTC
Labels: shasum, support
