### ISSUE TITLE
Error in installing cordova and ionic

### ISSUE THREAD

**Issue by ycheng18** [npm/npm#9062] opened 2015-07-25 15:06 UTC
```
APPLEdeMacBook-Pro-2:~ apple$ sudo npm install -g cordova ionic
npm ERR! tar.unpack untar error /tmp/npm-651-c8374bb5/registry.npmjs.org/npm/-/npm-2.1.3.tgz
npm ERR! Darwin 13.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! shasum check failed for /tmp/npm-651-c8374bb5/registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm ERR! Expected: 1dacc91458f2197c362d774d2cbf111680f86ec2
npm ERR! Actual:   463062dd660c050a81c0a33706554cef7bcc095a
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log
```

Have tried Run brew doctor remove all symbolic links etc using brew prune Run brew install node.

**Comment by KenanY** [comment] 2015-07-25 15:11
@ycheng18 Try running `npm cache clean`

**Comment by ycheng18** [comment] 2015-07-25 15:23
Have tried npm cache clean,but the question had still not solved.

**Comment by zkat** [comment] 2016-12-09 00:55
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:55 UTC
Labels: support
