### ISSUE TITLE
$ sudo npm install --- npm ERR! fetch failed with status code 502

### ISSUE THREAD

**Issue by altreact** [npm/npm#13293] opened 2016-07-06 12:54 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm-debug.log available at https://gist.github.com/altreact/00d84e47a7e1c024751484ad5c0d77ac and is also attached here: [npm-debug.log.zip](https://github.com/npm/npm/files/349693/npm-debug.log.zip)

xubuntu@xubuntu:/var/www/html/React-Redux-Boilerplate-master$ sudo npm install
npm ERR! fetch failed https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! fetch failed with status code 502
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/React-Redux-Boilerplate-master/npm-debug.log

after trying to visit https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz in a web browser, this is displayed:

502 Bad Gateway

The server returned an invalid or incomplete response.

#### How can the CLI team reproduce the problem?

0) install xubuntu 16.10, nodejs, npm
1) download .zip at https://github.com/buckyroberts/React-Redux-Boilerplate
2) extract .zip file
3) change into the newly extracted directory
4) npm install || sudo npm install

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux - $ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by t3chguy** [comment] 2016-07-06 12:58
https://github.com/npm/npm/issues/13284

**Comment by othiym23** [comment] 2016-07-06 14:53
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:53 UTC
Labels: big-bug, bug, registry
