### ISSUE TITLE
connect EINVAL

### ISSUE THREAD

**Issue by donatog** [npm/npm#7578] opened 2015-03-09 08:18 UTC
Please,
someone could tell me how to fix the error as reported in the file log below?
```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'http-server',
1 verbose cli   '-g' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'http-server', null ]
5 verbose cache add spec http-server
6 silly cache add parsed spec { raw: 'http-server',
6 silly cache add   scope: null,
6 silly cache add   name: 'http-server',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed http-server@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'http-server', range: '*', hasData: false }
11 silly mapToRegistry name http-server
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/http-server
15 verbose addNameRange registry:https://registry.npmjs.org/http-server not in flight; fetching
16 verbose request uri https://registry.npmjs.org/http-server
17 verbose request no auth needed
18 info attempt registry request try #1 at 08:57:42
19 verbose request id 0354b81af7e5771f
20 http request GET https://registry.npmjs.org/http-server
21 info retry will retry, error on last attempt: Error: connect EINVAL
22 info attempt registry request try #2 at 08:57:53
23 http request GET https://registry.npmjs.org/http-server
24 info retry will retry, error on last attempt: Error: connect EINVAL
25 info attempt registry request try #3 at 08:58:53
26 http request GET https://registry.npmjs.org/http-server
27 verbose stack Error: connect EINVAL
27 verbose stack     at exports._errnoException (util.js:746:11)
27 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
28 verbose cwd C:\Users\Donato
29 error Windows_NT 6.1.7601
30 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "http-server" "-g"
31 error node v0.12.0
32 error npm  v2.5.1
33 error code EINVAL
34 error errno EINVAL
35 error syscall connect
36 error connect EINVAL
37 error If you need help, you may report this error at:
37 error     <http://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```
Many Thanks.

**Comment by smikes** [comment] 2015-03-20 18:38
Thanks for reporting this.  When node @ 0.12.1 is released (soon) can you try using that to see if the problem was resolved?  Alternatively, could you try downgrading to node @ 0.10 and see if the problem is still present?

Thanks!

**Comment by smikes** [comment] 2015-04-29 18:19
Is this still a problem for you?

If so, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-05-20 03:23
Closing as resolved / abandoned.

**Closed by othiym23** 2015-05-20 03:23 UTC
Labels: support, windows
