### ISSUE TITLE
NPM 3 is very slow

### ISSUE THREAD

**Issue by gajus** [npm/npm#9632] opened 2015-09-17 13:00 UTC
I have been using NPM version 3 the last 24 hours and all the benefits aside I cannot but ignore how slow it is.

Here is a simple benchmark of installing https://github.com/gajus/react-css-modules.

Here is my Internet connection speed test (https://www.npmjs.com/package/speed-test).

```
Ping  85 ms
Download  3.2 Mbps
Upload  4.9 Mbps
```

NPM version:

```sh
$ npm -v
3.3.2
```

First test is using clean state:

```sh
$ rm -fr ./node_modules/
$ npm cache clean
$ date; npm install; date

Thu 17 Sep 2015 13:02:31 BST
[..]
Thu 17 Sep 2015 13:04:37 BST
```

It took 2.06 minutes.

Second test is using existing NPM cache:

```sh
$ rm -fr ./node_modules/
$ npm install
Thu 17 Sep 2015 13:05:20 BST
[..]
Thu 17 Sep 2015 13:06:20 BST
```

It took 1 minute using cache.

Now NPM 2:

```sh
$ npm -v
2.14.3

$ rm -fr ./node_modules/
$ npm cache clean
$ date; npm install; date

Thu 17 Sep 2015 13:12:07 BST
[..]
Thu 17 Sep 2015 13:13:12 BST
# 1 minute 5 seconds

$ rm -fr ./node_modules/
$ npm install
Thu 17 Sep 2015 13:14:24 BST
[..]
Thu 17 Sep 2015 13:14:50 BST
# 26 seconds
```

Here is my system info (gathered using https://www.npmjs.com/package/systeminfo):

```sh
$ systeminfo
Hostname:  curiosity
Platform:  darwin x64
Release:   14.5.0
Uptime:    219:19
Total RAM: 16.00 GB
CPU Model: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
CPU Clock: 2600 MHZ
CPU Cores: 8 cores
```

**Comment by gajus** [comment] 2015-09-17 13:00
A variation of this has been originally posted on https://www.reddit.com/r/javascript/comments/3laloz/npm_3_is_very_slow/.

**Comment by jucrouzet** [comment] 2015-09-17 13:20
Could you make a gist of the output of npm --verbose install ?

**Comment by gajus** [comment] 2015-09-17 14:01
https://gist.githubusercontent.com/gajus/83a4708ce11344c38419/raw/ef99bfcb8a3da76d5642368ee96ea36fa6beab1d/gistfile1.txt

**Comment by gajus** [comment] 2015-09-17 14:01
Took 20+ minutes to install this time.

**Comment by othiym23** [comment] 2015-09-17 16:58
Thanks for the numbers! There's a bit of a bootstrapping problem here -- it's been necessary for @iarna to concentrate on getting all of the blocking crashers in `npm@3` fixed so we can get it into wider release, which has kept her from putting time into the work necessary to improve its performance (which is a known issue – see #8826). `npm@3` just does a bunch more work than `npm@2`, so a certain amount of slowdown is inevitable, but we definitely want to eliminate any unnecessary file system and network activity, which is probably where @iarna is going to start. In any case, we're releasing `npm@3.3.3` as `latest` this week, so Rebecca will be shifting gears a bit to concentrate on this.

Closing as duplicate of #8826.

**Closed by othiym23** 2015-09-17 16:58 UTC

**Comment by sarkiroka** [comment] 2016-09-22 12:35
still slow

**Comment by pannous** [comment] 2016-09-23 12:49
very slow again after upgrade

**Comment by jimmont** [comment] 2016-10-18 20:04
also slow:
```
$ time npm -v
3.10.8

real	0m6.250s
user	0m5.920s
sys	0m0.310s


$ time npm --verbose install
npm info it worked if it ends with ok
npm verb cli [ '/opt/node-v6.8.1-linux-armv6l/bin/node',
npm verb cli   '/opt/nodejs/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'install' ]
npm info using npm@3.10.8
npm info using node@v6.8.1
npm verb config Skipping project config: /home/me/.npmrc. (matches userconfig)
npm info lifecycle undefined~preinstall: undefined
npm verb correctMkdir /home/me/.npm/_locks correctMkdir not in flight; initializing
npm verb makeDirectory /home/me/.npm/_locks creation not in flight; initializing
npm verb lock using /home/me/.npm/_locks/staging-e46d4459d78f71d3.lock for /home/me/node_modules/.staging
npm verb unlock done using /home/me/.npm/_locks/staging-e46d4459d78f71d3.lock for /home/me/node_modules/.staging
npm info linkStuff !invalid#1
npm verb linkBins !invalid#1
npm verb linkMans !invalid#1
npm info lifecycle undefined~install: undefined
npm info lifecycle undefined~postinstall: undefined
npm info lifecycle undefined~prepublish: undefined
npm WARN enoent ENOENT: no such file or directory, open '/home/me/package.json'
npm verb enoent ENOENT: no such file or directory, open '/home/me/package.json'
npm verb enoent This is most likely not a problem with npm itself
npm verb enoent and is related to npm not being able to find a file.
npm verb enoent
npm WARN me No description
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN me No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN me No README data
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN me No license field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb exit [ 0, true ]
npm info ok

real	0m18.655s
user	0m17.460s
sys	0m0.860s

$ cat /proc/version
Linux version 4.4.23+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #913 Tue Oct 4 13:56:56 BST 2016

$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 000e
Serial		: 00000000bff8eb74

```

**Comment by tinybug** [comment] 2016-11-21 08:48
try https://yarnpkg.com/

**Comment by sarkiroka** [comment] 2016-11-21 17:44
Of course, I can use yarn, or own proxy with cache, and any hack/patch. But
the new (v3) npm is still slow :(
If npm speedup then these softwares are not needed.
2016. nov. 21. de. 9:48 ezt írta ("tinybug" <notifications@github.com>):

**Comment by dud3** [comment] 2016-12-29 10:19
Horribly slow.

**Comment by Charlotteis** [comment] 2016-12-29 12:24
If you're experiencing slowness with npm 3 I'd recommend you upgrade to the latest version of npm 

```
npm install -g npm@latest
```

We're now on version 4 :)

If that doesn't work, please open an issue so we can help debug your problem.
Thanks!

**Comment by sarkiroka** [comment] 2016-12-29 13:16
okay, let's do it!
here is my package.json relevant part:
`  
"dependencies": {
    "express": "4.14.0",
    "path": "0.12.7",
    "pug": "^2.0.0-beta6"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-loader": "6.2.5",
    "webpack": "^1.14.0"
  }
`

and the result:
`
$ npm --version
4.0.5
$ time npm i
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
progbot@0.0.0 /home/sarkiroka/work/progbot
├── babel@6.5.2 
├─┬ babel-cli@6.18.0 
│ ├─┬ babel-polyfill@6.20.0 
│ │ ├── core-js@2.4.1 
│ │ └── regenerator-runtime@0.10.1 
│ ├─┬ babel-register@6.18.0 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ ├── os-homedir@1.0.2 
│ │ │ └── os-tmpdir@1.0.2 
│ │ └─┬ source-map-support@0.4.8 
│ │   └── source-map@0.5.6 
│ ├── babel-runtime@6.20.0 
│ ├─┬ chokidar@1.6.1 
│ │ ├─┬ anymatch@1.3.0 
│ │ │ ├── arrify@1.0.1 
│ │ │ └─┬ micromatch@2.3.11 
│ │ │   ├─┬ arr-diff@2.0.0 
│ │ │   │ └── arr-flatten@1.0.1 
│ │ │   ├── array-unique@0.2.1 
│ │ │   ├─┬ braces@1.8.5 
│ │ │   │ ├─┬ expand-range@1.8.2 
│ │ │   │ │ └─┬ fill-range@2.2.3 
│ │ │   │ │   ├── is-number@2.1.0 
│ │ │   │ │   ├── isobject@2.1.0 
│ │ │   │ │   └── randomatic@1.1.6 
│ │ │   │ ├── preserve@0.2.0 
│ │ │   │ └── repeat-element@1.1.2 
│ │ │   ├─┬ expand-brackets@0.1.5 
│ │ │   │ └── is-posix-bracket@0.1.1 
│ │ │   ├── extglob@0.3.2 
│ │ │   ├── filename-regex@2.0.0 
│ │ │   ├─┬ kind-of@3.1.0 
│ │ │   │ └── is-buffer@1.1.4 
│ │ │   ├── normalize-path@2.0.1 
│ │ │   ├─┬ object.omit@2.0.1 
│ │ │   │ ├─┬ for-own@0.1.4 
│ │ │   │ │ └── for-in@0.1.6 
│ │ │   │ └── is-extendable@0.1.1 
│ │ │   ├─┬ parse-glob@3.0.4 
│ │ │   │ ├── glob-base@0.3.0 
│ │ │   │ └── is-dotfile@1.0.2 
│ │ │   └─┬ regex-cache@0.4.3 
│ │ │     ├── is-equal-shallow@0.1.3 
│ │ │     └── is-primitive@2.0.0 
│ │ ├── async-each@1.0.1 
│ │ ├── glob-parent@2.0.0 
│ │ ├── inherits@2.0.3 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.8.0 
│ │ ├─┬ is-glob@2.0.1 
│ │ │ └── is-extglob@1.0.0 
│ │ └─┬ readdirp@2.1.0 
│ │   └── set-immediate-shim@1.0.1 
│ ├─┬ commander@2.8.1 
│ │ └── graceful-readlink@1.0.1 
│ ├── convert-source-map@1.3.0 
│ ├── fs-readdir-recursive@1.0.0 
│ ├─┬ glob@5.0.15 
│ │ ├─┬ inflight@1.0.6 
│ │ │ └── wrappy@1.0.2 
│ │ └── once@1.4.0 
│ ├── lodash@4.17.3 
│ ├─┬ output-file-sync@1.1.2 
│ │ └── graceful-fs@4.1.11 
│ ├── path-is-absolute@1.0.1 
│ ├── slash@1.0.0 
│ ├── source-map@0.5.6 
│ └─┬ v8flags@2.0.11 
│   └── user-home@1.1.1 
├─┬ babel-core@6.21.0 
│ ├─┬ babel-code-frame@6.20.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.0.0 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@2.0.0 
│ ├─┬ babel-generator@6.21.0 
│ │ ├─┬ detect-indent@4.0.0 
│ │ │ └─┬ repeating@2.0.1 
│ │ │   └─┬ is-finite@1.0.2 
│ │ │     └── number-is-nan@1.0.1 
│ │ ├── jsesc@1.3.0 
│ │ └── source-map@0.5.6 
│ ├── babel-helpers@6.16.0 
│ ├── babel-messages@6.8.0 
│ ├── babel-template@6.16.0 
│ ├─┬ babel-traverse@6.21.0 
│ │ ├── globals@9.14.0 
│ │ └─┬ invariant@2.2.2 
│ │   └── loose-envify@1.3.0 
│ ├─┬ babel-types@6.21.0 
│ │ └── to-fast-properties@1.0.2 
│ ├── babylon@6.14.1 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── json5@0.5.1 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├── private@0.1.6 
│ └── source-map@0.5.6 
├─┬ babel-loader@6.2.5 
│ ├─┬ loader-utils@0.2.16 
│ │ ├── big.js@3.1.3 
│ │ └── emojis-list@2.1.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ └── object-assign@4.1.0 
├─┬ babel-preset-es2015@6.18.0 
│ ├── babel-plugin-check-es2015-constants@6.8.0 
│ ├── babel-plugin-transform-es2015-arrow-functions@6.8.0 
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0 
│ ├── babel-plugin-transform-es2015-block-scoping@6.21.0 
│ ├─┬ babel-plugin-transform-es2015-classes@6.18.0 
│ │ ├── babel-helper-define-map@6.18.0 
│ │ ├── babel-helper-function-name@6.18.0 
│ │ ├── babel-helper-optimise-call-expression@6.18.0 
│ │ └── babel-helper-replace-supers@6.18.0 
│ ├── babel-plugin-transform-es2015-computed-properties@6.8.0 
│ ├── babel-plugin-transform-es2015-destructuring@6.19.0 
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.8.0 
│ ├── babel-plugin-transform-es2015-for-of@6.18.0 
│ ├── babel-plugin-transform-es2015-function-name@6.9.0 
│ ├── babel-plugin-transform-es2015-literals@6.8.0 
│ ├── babel-plugin-transform-es2015-modules-amd@6.18.0 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.18.0 
│ │ └── babel-plugin-transform-strict-mode@6.18.0 
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.19.0 
│ │ └── babel-helper-hoist-variables@6.18.0 
│ ├── babel-plugin-transform-es2015-modules-umd@6.18.0 
│ ├── babel-plugin-transform-es2015-object-super@6.8.0 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.21.0 
│ │ ├── babel-helper-call-delegate@6.18.0 
│ │ └── babel-helper-get-function-arity@6.18.0 
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.18.0 
│ ├── babel-plugin-transform-es2015-spread@6.8.0 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.8.0 
│ │ └── babel-helper-regex@6.18.0 
│ ├── babel-plugin-transform-es2015-template-literals@6.8.0 
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.18.0 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.11.0 
│ │ └─┬ regexpu-core@2.0.0 
│ │   ├── regenerate@1.3.2 
│ │   ├── regjsgen@0.2.0 
│ │   └─┬ regjsparser@0.1.5 
│ │     └── jsesc@0.5.0 
│ └─┬ babel-plugin-transform-regenerator@6.21.0 
│   └── regenerator-transform@0.9.8 
├─┬ express@4.14.0 
│ ├─┬ accepts@1.3.3 
│ │ ├─┬ mime-types@2.1.13 
│ │ │ └── mime-db@1.25.0 
│ │ └── negotiator@0.6.1 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.1 
│ ├── content-type@1.0.2 
│ ├── cookie@0.3.1 
│ ├── cookie-signature@1.0.6 
│ ├── depd@1.1.0 
│ ├── encodeurl@1.0.1 
│ ├── escape-html@1.0.3 
│ ├── etag@1.7.0 
│ ├─┬ finalhandler@0.5.0 
│ │ ├── statuses@1.3.1 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.1.2 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.1.1 
│ ├── qs@6.2.0 
│ ├── range-parser@1.2.0 
│ ├─┬ send@0.14.1 
│ │ ├── destroy@1.0.4 
│ │ ├─┬ http-errors@1.5.1 
│ │ │ └── setprototypeof@1.0.2 
│ │ └── mime@1.3.4 
│ ├── serve-static@1.11.1 
│ ├─┬ type-is@1.6.14 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.0 
│ └── vary@1.1.0 
├─┬ path@0.12.7 
│ ├── process@0.11.9 
│ └─┬ util@0.10.3 
│   └── inherits@2.0.1 
├─┬ pug@2.0.0-beta6 
│ ├─┬ pug-code-gen@1.1.0 
│ │ ├─┬ constantinople@3.1.0 
│ │ │ └── is-expression@2.1.0 
│ │ ├── doctypes@1.1.0 
│ │ ├── js-stringify@1.0.2 
│ │ ├── pug-attrs@2.0.1 
│ │ ├── pug-error@1.3.1 
│ │ ├── void-elements@2.0.1 
│ │ └─┬ with@5.1.1 
│ │   └── acorn-globals@3.0.0 
│ ├─┬ pug-filters@1.2.4 
│ │ ├── clean-css@3.4.23 
│ │ ├─┬ jstransformer@1.0.0 
│ │ │ ├── is-promise@2.1.0 
│ │ │ └─┬ promise@7.1.1 
│ │ │   └── asap@2.0.5 
│ │ ├── pug-walk@1.0.0 
│ │ └── resolve@1.2.0 
│ ├─┬ pug-lexer@2.3.0 
│ │ ├─┬ character-parser@2.2.0 
│ │ │ └── is-regex@1.0.3 
│ │ └─┬ is-expression@3.0.0 
│ │   └── acorn@4.0.4 
│ ├── pug-linker@1.0.1 
│ ├── pug-load@2.0.3 
│ ├─┬ pug-parser@2.0.1 
│ │ └── token-stream@0.0.1 
│ ├── pug-runtime@2.0.2 
│ └── pug-strip-comments@1.0.1 
└─┬ webpack@1.14.0 
  ├── acorn@3.3.0 
  ├── async@1.5.2 
  ├── clone@1.0.2 
  ├─┬ enhanced-resolve@0.9.1 
  │ └── memory-fs@0.2.0 
  ├── interpret@0.6.6 
  ├─┬ memory-fs@0.3.0 
  │ ├─┬ errno@0.1.4 
  │ │ └── prr@0.0.0 
  │ └─┬ readable-stream@2.2.2 
  │   ├── buffer-shims@1.0.0 
  │   ├── core-util-is@1.0.2 
  │   ├── isarray@1.0.0 
  │   ├── process-nextick-args@1.0.7 
  │   └── util-deprecate@1.0.2 
  ├─┬ node-libs-browser@0.7.0 
  │ ├── assert@1.4.1 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.9 
  │ ├─┬ buffer@4.9.1 
  │ │ ├── base64-js@1.2.0 
  │ │ └── ieee754@1.1.8 
  │ ├─┬ console-browserify@1.1.0 
  │ │ └── date-now@0.1.4 
  │ ├── constants-browserify@1.0.0 
  │ ├─┬ crypto-browserify@3.3.0 
  │ │ ├── browserify-aes@0.4.0 
  │ │ ├── pbkdf2-compat@2.0.1 
  │ │ ├── ripemd160@0.2.0 
  │ │ └── sha.js@2.2.6 
  │ ├── domain-browser@1.1.7 
  │ ├── events@1.1.1 
  │ ├── https-browserify@0.0.1 
  │ ├── os-browserify@0.2.1 
  │ ├── path-browserify@0.0.0 
  │ ├── punycode@1.4.1 
  │ ├── querystring-es3@0.2.1 
  │ ├── stream-browserify@2.0.1 
  │ ├─┬ stream-http@2.5.0 
  │ │ ├── builtin-status-codes@2.0.0 
  │ │ ├── to-arraybuffer@1.0.1 
  │ │ └── xtend@4.0.1 
  │ ├── string_decoder@0.10.31 
  │ ├─┬ timers-browserify@2.0.2 
  │ │ └── setimmediate@1.0.5 
  │ ├── tty-browserify@0.0.0 
  │ ├─┬ url@0.11.0 
  │ │ ├── punycode@1.3.2 
  │ │ └── querystring@0.2.0 
  │ └─┬ vm-browserify@0.0.4 
  │   └── indexof@0.0.1 
  ├─┬ optimist@0.6.1 
  │ └── wordwrap@0.0.2 
  ├─┬ supports-color@3.1.2 
  │ └── has-flag@1.0.0 
  ├── tapable@0.1.10 
  ├─┬ uglify-js@2.7.5 
  │ ├── async@0.2.10 
  │ ├── source-map@0.5.6 
  │ ├── uglify-to-browserify@1.0.2 
  │ └─┬ yargs@3.10.0 
  │   ├── camelcase@1.2.1 
  │   ├─┬ cliui@2.1.0 
  │   │ ├─┬ center-align@0.1.3 
  │   │ │ ├─┬ align-text@0.1.4 
  │   │ │ │ ├── longest@1.0.1 
  │   │ │ │ └── repeat-string@1.6.1 
  │   │ │ └── lazy-cache@1.0.4 
  │   │ └── right-align@0.1.3 
  │   ├── decamelize@1.2.0 
  │   └── window-size@0.1.0 
  ├─┬ watchpack@0.2.9 
  │ └── async@0.9.2 
  └─┬ webpack-core@0.6.9 
    ├── source-list-map@0.1.7 
    └─┬ source-map@0.4.4 
      └── amdefine@1.0.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

real	2m7.589s
user	0m15.864s
sys	0m1.584s

`

more than 2 minutes is horribly slow :-(

**Comment by dud3** [comment] 2016-12-29 14:28
There's most likely something fundamentally wrong here.

Throwing computing power to solve problems like this sounds slightly rubbish/stupid.

**Comment by Charlotteis** [comment] 2016-12-29 15:00
> please open an issue so we can help debug your problem.

As this has been around since 2015 and is closed, please can we open a fresh issue folks? as kenan says, any slowness is likely very unrelated to this issue that has since been closed, so can we start a nice fresh conversation?

**Comment by sarkiroka** [comment] 2016-12-31 22:10
you are right, i opened a new issue: https://github.com/npm/npm/issues/15361

**Comment by fastzhong** [comment] 2017-03-02 11:31
it is 2017, soooo slow even the latest npm and node. I have no problem with other applications.

**Comment by pannous** [comment] 2017-03-02 11:33
to push reaction times under a minute get rid of the global node_modules folder
` mv /usr/local/lib/node_modules/ /usr/local/lib/node_modules.WTF `
