### ISSUE TITLE
Problem with npm search

### ISSUE THREAD

**Issue by MasterDmi** [npm/npm#15113] opened 2016-12-02 03:25 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I can,t search modules, cos of this:
![image](https://cloud.githubusercontent.com/assets/24296504/20821965/d27af3b0-b881-11e6-9767-2e46f51a0e80.png)

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 7.2.0
 - Windows,

**Comment by zkat** [comment] 2016-12-02 03:32
Closing as a duplicate of https://github.com/npm/npm/issues/15112

**Closed by zkat** 2016-12-02 03:32 UTC

**Comment by MasterDmi** [comment] 2016-12-02 03:41
Why U closed that issue? U don't sold it.
