### ISSUE TITLE
npm doesn't care if a checksum check fails

### ISSUE THREAD

**Issue by OlliV** [npm/npm#8237] opened 2015-05-12 12:07 UTC
```
% npm install csv-parse
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/home/eollvan/repos/dashboard/nodes/current/bin/npm" "install" "csv-parse"
npm ERR! node v0.10.29
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /tmp/npm-23757-21327171/registry.npmjs.org/csv-parse/-/csv-parse-0.1.1.tgz
npm ERR! Expected: d18b6e97d65fdb709bb09a4e7eb6071142e79574
npm ERR! Actual:   a9656f975bba2688075a97b479adf53ad4edbddd
npm ERR! From:     http://registry.npmjs.org/csv-parse/-/csv-parse-0.1.1.tgz
```

but the package was still installed normally. Nothing else was printed (but just instructions to report the issue) but unfortunately I lose the generated log file. So even if npm redownloaded the package there is nothing indicating it happened, so I'm expecting it just happily installed the broken one.

**Comment by busches** [comment] 2016-08-22 19:02
Is this still an issue with npm3?

**Comment by OlliV** [comment] 2016-08-22 20:23
No idea. I haven't seen shasum errors after that.

**Comment by zkat** [comment] 2016-12-09 00:56
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:56 UTC
Labels: support
