### ISSUE TITLE
npm install error  error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by thuyennv** [npm/npm#16116] opened 2017-03-21 10:20 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

npm ERR! fetch failed https://registry.npmjs.org/jquery/-/jquery-2.2.4.tgz
npm WARN retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! fetch failed https://registry.npmjs.org/jquery/-/jquery-2.2.4.tgz
npm WARN retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! fetch failed https://registry.npmjs.org/jquery/-/jquery-2.2.4.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NguyenVanThuyen\Desktop\template\learnplus-v2.0.0\npm-debug.log

**Comment by xpepermint** [comment] 2017-03-21 18:38
Also seeing this on Ubuntu 16.04 - I cannot install packages anymore. Critical!

**Comment by legodude17** [comment] 2017-03-23 16:43
Hello! This is a duplicate of #10897. Please try `npm config set registry http://registry.npmjs.org`.

**Comment by xpepermint** [comment] 2017-03-23 16:57
@legodude17 It seems that it was a network problem. It simply started working again next day.

**Comment by legodude17** [comment] 2017-03-23 17:18
@xpepermint that is good.

**Comment by xpepermint** [comment] 2017-03-23 17:19
Yeah... bit its impossible to know that from the error message :).

**Comment by legodude17** [comment] 2017-03-23 17:54
Yeah, the error message is a little misleading. `npm@4` has a better handler for that.

**Closed** 2017-06-17 03:42 UTC
Labels: bot-closed
