### ISSUE TITLE
npm install --save-dev gulp-sass 

### ISSUE THREAD

**Issue by reekrd** [npm/npm#10696] opened 2015-12-04 17:27 UTC
System Info:
OS X El Capitan v10.11.1 
Node 5.1.0 (installed with homebrew) 
Npm v 3.5.1

Running *npm install --save-dev gulp-sass* gives me 209 folders in node_modules which feels a bit bloated. Below is the output from terminal.

(Running the same command on another computer that has OS X Yosemite 10.10.5, Node v0.12.7, Npm 2.12.1 I get the expected of result of only gulp-sass inside node_modules)

```
boxfaces-MacBook-Pro:test boxface$ npm install --save-dev gulp-sass
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

> node-sass@3.4.2 install /Users/boxface/Sites/_localhost/vaporizerblog/wwwroot/wp-content/themes/test/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/boxface/Sites/_localhost/vaporizerblog/wwwroot/wp-content/themes/test/node_modules/node-sass/vendor/darwin-x64-47/binding.node

> spawn-sync@1.0.13 postinstall /Users/boxface/Sites/_localhost/vaporizerblog/wwwroot/wp-content/themes/test/node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall /Users/boxface/Sites/_localhost/vaporizerblog/wwwroot/wp-content/themes/test/node_modules/node-sass
> node scripts/build.js

` /Users/boxface/Sites/_localhost/vaporizerblog/wwwroot/wp-content/themes/test/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
test@1.0.0 /Users/boxface/Sites/_localhost/vaporizerblog/wwwroot/wp-content/themes/test
└─┬ gulp-sass@2.1.0 
  ├─┬ gulp-util@3.0.7 
  │ ├── array-differ@1.0.0 
  │ ├── array-uniq@1.0.2 
  │ ├── beeper@1.1.0 
  │ ├─┬ chalk@1.1.1 
  │ │ ├── ansi-styles@2.1.0 
  │ │ ├── escape-string-regexp@1.0.3 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ ├── strip-ansi@3.0.0 
  │ │ └── supports-color@2.0.0 
  │ ├── dateformat@1.0.12 
  │ ├── fancy-log@1.1.0 
  │ ├─┬ gulplog@1.0.0 
  │ │ └── glogg@1.0.0 
  │ ├─┬ has-gulplog@0.1.0 
  │ │ └── sparkles@1.0.0 
  │ ├── lodash._reescape@3.0.0 
  │ ├── lodash._reevaluate@3.0.0 
  │ ├── lodash._reinterpolate@3.0.0 
  │ ├─┬ lodash.template@3.6.2 
  │ │ ├── lodash._basecopy@3.0.1 
  │ │ ├── lodash._basetostring@3.0.1 
  │ │ ├── lodash._basevalues@3.0.0 
  │ │ ├── lodash._isiterateecall@3.0.9 
  │ │ ├── lodash.escape@3.0.0 
  │ │ ├─┬ lodash.keys@3.1.2 
  │ │ │ ├── lodash._getnative@3.9.1 
  │ │ │ ├── lodash.isarguments@3.0.4 
  │ │ │ └── lodash.isarray@3.0.4 
  │ │ ├── lodash.restparam@3.6.1 
  │ │ └── lodash.templatesettings@3.1.0 
  │ ├── minimist@1.2.0 
  │ ├─┬ multipipe@0.1.2 
  │ │ └─┬ duplexer2@0.0.2 
  │ │   └── readable-stream@1.1.13 
  │ ├── object-assign@3.0.0 
  │ ├── replace-ext@0.0.1 
  │ └─┬ vinyl@0.5.3 
  │   ├── clone@1.0.2 
  │   └── clone-stats@0.0.1 
  ├─┬ node-sass@3.4.2 
  │ ├── async-foreach@0.1.3 
  │ ├─┬ cross-spawn@2.0.1 
  │ │ ├─┬ cross-spawn-async@2.0.1 
  │ │ │ └─┬ lru-cache@3.2.0 
  │ │ │   └── pseudomap@1.0.1 
  │ │ └─┬ spawn-sync@1.0.13 
  │ │   ├─┬ concat-stream@1.5.1 
  │ │   │ ├── readable-stream@2.0.4 
  │ │   │ └── typedarray@0.0.6 
  │ │   └── os-shim@0.1.3 
  │ ├─┬ gaze@0.5.2 
  │ │ └─┬ globule@0.1.0 
  │ │   ├─┬ glob@3.1.21 
  │ │   │ ├── graceful-fs@1.2.3 
  │ │   │ └── inherits@1.0.2 
  │ │   ├── lodash@1.0.2 
  │ │   └─┬ minimatch@0.2.14 
  │ │     └── lru-cache@2.7.3 
  │ ├── get-stdin@4.0.1 
  │ ├─┬ glob@5.0.15 
  │ │ ├─┬ inflight@1.0.4 
  │ │ │ └── wrappy@1.0.1 
  │ │ ├── inherits@2.0.1 
  │ │ ├─┬ minimatch@3.0.0 
  │ │ │ └─┬ brace-expansion@1.1.2 
  │ │ │   ├── balanced-match@0.3.0 
  │ │ │   └── concat-map@0.0.1 
  │ │ ├── once@1.3.3 
  │ │ └── path-is-absolute@1.0.0 
  │ ├─┬ meow@3.6.0 
  │ │ ├─┬ camelcase-keys@2.0.0 
  │ │ │ ├── camelcase@2.0.1 
  │ │ │ └── map-obj@1.0.1 
  │ │ ├─┬ loud-rejection@1.2.0 
  │ │ │ └── signal-exit@2.1.2 
  │ │ ├─┬ normalize-package-data@2.3.5 
  │ │ │ ├── hosted-git-info@2.1.4 
  │ │ │ ├─┬ is-builtin-module@1.0.0 
  │ │ │ │ └── builtin-modules@1.1.0 
  │ │ │ └─┬ validate-npm-package-license@3.0.1 
  │ │ │   ├─┬ spdx-correct@1.0.2 
  │ │ │   │ └── spdx-license-ids@1.1.0 
  │ │ │   └─┬ spdx-expression-parse@1.0.2 
  │ │ │     └── spdx-exceptions@1.0.4 
  │ │ ├─┬ read-pkg-up@1.0.1 
  │ │ │ ├─┬ find-up@1.1.0 
  │ │ │ │ └── path-exists@2.1.0 
  │ │ │ └─┬ read-pkg@1.1.0 
  │ │ │   ├─┬ load-json-file@1.1.0 
  │ │ │   │ ├─┬ parse-json@2.2.0 
  │ │ │   │ │ └─┬ error-ex@1.3.0 
  │ │ │   │ │   └── is-arrayish@0.2.1 
  │ │ │   │ ├── pify@2.3.0 
  │ │ │   │ └─┬ strip-bom@2.0.0 
  │ │ │   │   └── is-utf8@0.2.0 
  │ │ │   └── path-type@1.1.0 
  │ │ ├─┬ redent@1.0.0 
  │ │ │ ├─┬ indent-string@2.1.0 
  │ │ │ │ └─┬ repeating@2.0.0 
  │ │ │ │   └── is-finite@1.0.1 
  │ │ │ └── strip-indent@1.0.1 
  │ │ └── trim-newlines@1.0.0 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├── nan@2.1.0 
  │ ├─┬ node-gyp@3.2.1 
  │ │ ├── fstream@1.0.8 
  │ │ ├─┬ glob@4.5.3 
  │ │ │ └── minimatch@2.0.10 
  │ │ ├── graceful-fs@4.1.2 
  │ │ ├─┬ minimatch@1.0.0 
  │ │ │ ├── lru-cache@2.7.3 
  │ │ │ └── sigmund@1.0.1 
  │ │ ├─┬ nopt@3.0.6 
  │ │ │ └── abbrev@1.0.7 
  │ │ ├─┬ npmlog@1.2.1 
  │ │ │ ├── ansi@0.3.0 
  │ │ │ ├─┬ are-we-there-yet@1.0.4 
  │ │ │ │ └── delegates@0.1.0 
  │ │ │ └─┬ gauge@1.2.2 
  │ │ │   ├── has-unicode@1.0.1 
  │ │ │   ├─┬ lodash.pad@3.1.1 
  │ │ │   │ └─┬ lodash._createpadding@3.6.1 
  │ │ │   │   └── lodash.repeat@3.0.1 
  │ │ │   ├── lodash.padleft@3.1.1 
  │ │ │   └── lodash.padright@3.1.1 
  │ │ ├─┬ osenv@0.1.3 
  │ │ │ ├── os-homedir@1.0.1 
  │ │ │ └── os-tmpdir@1.0.1 
  │ │ ├─┬ path-array@1.0.0 
  │ │ │ └─┬ array-index@0.1.1 
  │ │ │   └─┬ debug@2.2.0 
  │ │ │     └── ms@0.7.1 
  │ │ ├── rimraf@2.4.4 
  │ │ ├── semver@5.1.0 
  │ │ ├─┬ tar@2.2.1 
  │ │ │ └── block-stream@0.0.8 
  │ │ └─┬ which@1.2.0 
  │ │   └─┬ is-absolute@0.1.7 
  │ │     └── is-relative@0.1.3 
  │ ├─┬ npmconf@2.1.2 
  │ │ ├─┬ config-chain@1.1.9 
  │ │ │ └── proto-list@1.2.4 
  │ │ ├── ini@1.3.4 
  │ │ ├── semver@4.3.6 
  │ │ └── uid-number@0.0.5 
  │ ├─┬ request@2.67.0 
  │ │ ├── aws-sign2@0.6.0 
  │ │ ├─┬ bl@1.0.0 
  │ │ │ └── readable-stream@2.0.4 
  │ │ ├── caseless@0.11.0 
  │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── extend@3.0.0 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├─┬ form-data@1.0.0-rc3 
  │ │ │ └── async@1.5.0 
  │ │ ├─┬ har-validator@2.0.3 
  │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ ├─┬ is-my-json-valid@2.12.3 
  │ │ │ │ ├── generate-function@2.0.0 
  │ │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ │ └── is-property@1.0.2 
  │ │ │ │ └── jsonpointer@2.0.0 
  │ │ │ └─┬ pinkie-promise@2.0.0 
  │ │ │   └── pinkie@2.0.1 
  │ │ ├─┬ hawk@3.1.2 
  │ │ │ ├── boom@2.10.1 
  │ │ │ ├── cryptiles@2.0.5 
  │ │ │ ├── hoek@2.16.3 
  │ │ │ └── sntp@1.0.9 
  │ │ ├─┬ http-signature@1.1.0 
  │ │ │ ├── assert-plus@0.1.5 
  │ │ │ ├─┬ jsprim@1.2.2 
  │ │ │ │ ├── extsprintf@1.0.2 
  │ │ │ │ ├── json-schema@0.2.2 
  │ │ │ │ └── verror@1.3.6 
  │ │ │ └─┬ sshpk@1.7.1 
  │ │ │   ├── asn1@0.2.3 
  │ │ │   ├── assert-plus@0.2.0 
  │ │ │   ├── dashdash@1.10.1 
  │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │   ├── jodid25519@1.0.2 
  │ │ │   ├── jsbn@0.1.0 
  │ │ │   └── tweetnacl@0.13.2 
  │ │ ├── is-typedarray@1.0.0 
  │ │ ├── isstream@0.1.2 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├─┬ mime-types@2.1.8 
  │ │ │ └── mime-db@1.20.0 
  │ │ ├── node-uuid@1.4.7 
  │ │ ├── oauth-sign@0.8.0 
  │ │ ├── qs@5.2.0 
  │ │ ├── stringstream@0.0.5 
  │ │ ├── tough-cookie@2.2.1 
  │ │ └── tunnel-agent@0.4.1 
  │ └─┬ sass-graph@2.0.1 
  │   ├── lodash@3.10.1 
  │   └─┬ yargs@3.31.0 
  │     ├─┬ cliui@3.1.0 
  │     │ └── wrap-ansi@1.0.0 
  │     ├── decamelize@1.1.1 
  │     ├─┬ os-locale@1.4.0 
  │     │ └─┬ lcid@1.0.0 
  │     │   └── invert-kv@1.0.0 
  │     ├─┬ string-width@1.0.1 
  │     │ ├─┬ code-point-at@1.0.0 
  │     │ │ └── number-is-nan@1.0.0 
  │     │ └── is-fullwidth-code-point@1.0.0 
  │     ├── window-size@0.1.4 
  │     └── y18n@3.2.0 
  ├── object-assign@4.0.1 
  ├─┬ through2@2.0.0 
  │ ├─┬ readable-stream@2.0.4 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── isarray@0.0.1 
  │ │ ├── process-nextick-args@1.0.6 
  │ │ ├── string_decoder@0.10.31 
  │ │ └── util-deprecate@1.0.2 
  │ └── xtend@4.0.1 
  └─┬ vinyl-sourcemaps-apply@0.2.0 
    └── source-map@0.5.3 

npm WARN test@1.0.0 No repository field.
```

**Comment by KenanY** [comment] 2015-12-04 19:05
@reekrd That is intentional. `npm@3` flattens dependencies as much as possible so many end in that root `node_modules/` directory. Here's [the relevant section](https://github.com/npm/npm/blob/v3.0.0/CHANGELOG.md#flat-flat-flat) of the changelog.

**Comment by othiym23** [comment] 2015-12-04 19:09
As @KenanY explained, this is how `npm@3` works by design, so I'm closing this issue as resolved.

**Closed by othiym23** 2015-12-04 19:09 UTC
Labels: support
