### ISSUE TITLE
unable to uninstall globla pm2

### ISSUE THREAD

**Issue by talktothelaw** [npm/npm#17561] opened 2017-07-01 16:59 UTC
#### I'm opening this issue because:
  -  [**true** ]  npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

i tried to remove pm2 from global installation but i got this error
  root@africa-nextgen:~/.npm/_logs# cat _logs/2017-07-01T16_48_08_276Z-debug.log  cat: _logs/2017-07-01T16_48_08_276Z-debug.log: No such file or directory
root@africa-nextgen:~/.npm/_logs# cat 2017-07-01T16_48_08_276Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'uninstall', 'pm2', '-g' ]
2 info using npm@5.0.4
3 info using node@v8.0.0
4 verbose npm-session 51ec340a50f4d5ff
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>

**Comment by kenany** [comment] 2017-07-01 17:01
dupe of https://github.com/npm/npm/issues/16738

**Closed as completed by kenany** 2017-07-01 17:01 UTC
Labels: npm5
