### ISSUE TITLE
Not able to install angular2

### ISSUE THREAD

**Issue by karanbisht** [npm/npm#13812] opened 2016-08-30 17:43 UTC
Showing this error-:

M:\Angular2\angular-cli-master\angular-cli-master>npm install
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\samsung\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6

npm ERR! shasum check failed for C:\Users\samsung\AppData\Local\Temp\npm-1868-bab0dcd8\registry.npmjs.org\npm-\npm-3.10.2.tgz
npm ERR! Expected: 4a1b56bd33b1971803436edbbc4563412f92a434
npm ERR! Actual:   6eeaedd688e72756e8c0efaa26ace4f6c554c03b
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-3.10.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by KenanY** [comment] 2016-08-30 18:25
@karanbisht Have you tried running `npm cache clean`?

**Comment by karanbisht** [comment] 2016-08-30 19:16
@KenanY thanks for replying , yes i tried  npm cache clean , but still getting same error.

**Comment by KenanY** [comment] 2016-09-16 15:21
@karanbisht Not sure what else I could suggest, unfortunately :/

**Comment by zkat** [comment] 2016-12-09 00:38
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:38 UTC
