### ISSUE TITLE
npm, npm package size

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#5436] opened 2014-06-08 17:08 UTC
@isaacs recommend bundling our dependencies for ember-cli see: https://github.com/stefanpenner/ember-cli/issues/931

Doing so does leave us with a large file, which is clearly not ideal for npm itself.

While auditing our node_modules for size I noticed NPM itself is about 6MB, while walking the node_modules it seems many of the size0able assets are not needed for general module usage as they are usually tests/fixtures/images/examples etc.

This pattern seems to repeated for any other large NPM dependency, I wonder if a set of best practices should be established?

**Comment by othiym23** [comment] 2016-07-19 21:02
The CLI team spent some time discussing this request, because there are a bunch of things in here, and at least one of us (me) was a little confused about what the underlying problem to be solved was. (This is important if the desired outcome is to promulgate a set of best practices, because it’s only kind of implicit in the discussion what those best practices might be.) As near as we could tease out, the problem is that there are many (popular) packages that are too large, and contain too many irrelevant or unused files. I think there’s a partial consensus within the ecosystem that this is a significant problem with npm in general, but if you see the discussion on #5264, it’s not a super broad consensus, and wading into it is not something that the CLI team is incredibly eager to do, given our central place within the ecosystem and the contentiousness of the topic.

However! There are several other smaller requests that spin off from this that seem generally useful, and those are definitely things the CLI team would like to see happen:

1. Better documentation that codifies how to use the features provided by npm (like `.npmignore` and `”files”` in `package.json`) to slim down your packages. These are the “best practices” that @stefanpenner alludes to (I think), and this seems in line with a lot of the other documentation that @ashleygwilliams has been working on recently. The CLI team itself tries to stay out of best practices debates within npm’s bundled help, but I think this is something that would be useful to have as a guide on docs.npmjs.com.
2. A display of how big a package is at publish / publish dry-run time, either of the package’s installed size on disk or the size of the packaged tarball (or both!).
3. Some way of confirming that files are intended to be part of a package, instead of passively filtered out. This is tricky, because many npm packages are significantly more complex than, say, the average Ruby gem or Python egg, so coming up with a way of doing this interactively would require careful design to not produce something extremely tedious. In the meantime, evangelizing the use of `”files”` (which supports globs) is a good place to start.

These are actually three separate requests, and as such that makes this issue a bit unwieldy. So I’m going to close it! That doesn’t mean that I don’t think the three things above aren’t worthwhile – they are! At the same time, it seems unlikely to me that the CLI team is going to have time to get to this within the next year or so, and so I request that you file those as new, individual feature request, or (please!) send us pull requests implementing any / all of the above (noting that docs changes should go to the [docs repo](https://github.com/npm/docs/issues) and not the CLI). Thanks to all for the time and discussion!

**Closed by othiym23** 2016-07-19 21:02 UTC
Labels: documentation, feature-request
