### ISSUE TITLE
Cannot install npm module (deepify) using node v5.0.0

### ISSUE THREAD

**Issue by eistrati** [npm/npm#10342] opened 2015-11-11 17:05 UTC
Here below is the dump-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'deepify',
1 verbose cli   '-g' ]
2 info using npm@3.3.9
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData deepify
8 silly fetchNamedPackageData deepify
9 silly mapToRegistry name deepify
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/deepify
13 verbose request uri https://registry.npmjs.org/deepify
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:18:46 AM
16 verbose request using bearer token for auth
17 verbose request id 5532f528089e5c00
18 verbose etag "29GRIACOAABIPTKCW9XWIR3W1"
19 http request GET https://registry.npmjs.org/deepify
20 http 304 https://registry.npmjs.org/deepify
21 verbose headers { 'cache-control': 'max-age=60',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Wed, 11 Nov 2015 16:18:46 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-jfk1033-JFK',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1447258726.618901,VS0,VE18' }
22 silly get cb [ 304,
22 silly get   { 'cache-control': 'max-age=60',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Wed, 11 Nov 2015 16:18:46 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-jfk1033-JFK',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1447258726.618901,VS0,VE18' } ]
23 verbose etag https://registry.npmjs.org/deepify from cache
24 verbose get saving deepify to /Volumes/Data/Users/eugene/.npm/registry.npmjs.org/deepify/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 verbose stack TypeError: Cannot read property 'forEach' of undefined
31 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:12)
31 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
31 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/copy-tree.js:22:18
31 verbose stack     at Array.forEach (native)
31 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:13)
31 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
31 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/copy-tree.js:22:18
31 verbose stack     at Array.forEach (native)
31 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:13)
31 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
32 verbose cwd /Volumes/Data/Users/eugene
33 error Darwin 15.0.0
34 error argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "deepify" "-g"
35 error node v5.0.0
36 error npm  v3.3.9
37 error Cannot read property 'forEach' of undefined
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

Please help.

**Comment by othiym23** [comment] 2015-11-11 22:49
We can't reproduce this ourselves, and the stack trace in the debug log (thanks for including it) is pretty weird. I was able to run that command successfully with `npm@3.3.9` and Node 5.0.0 and OS X El Capitan (just like you, it appears). Did you already have `deepify` installed before you reran the install? If you run `npm cache clean`, does this problem persist?

**Comment by eistrati** [comment] 2015-11-12 00:49
I have originally reported this problem here: https://github.com/nodejs/node/issues/3775 . It looks that @cjihrig was able to reproduce it as well.

`deepify` was already installed on my computer and I tried to install the newer version. Even `npm uninstall deepify -g` was generating the same exact issue. When I downgraded to v.4.2.2, it worked fine.

**Comment by eistrati** [comment] 2015-11-12 00:55
```
MitocGroup:~ eugene$ npm uninstall deepify -g
npm info it worked if it ends with ok
npm info using npm@3.3.9
npm info using node@v5.0.0
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "uninstall" "deepify" "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9

npm ERR! Cannot read property 'forEach' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Data/Users/eugene/npm-debug.log

MitocGroup:~ eugene$ cat /Volumes/Data/Users/eugene/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   'deepify',
1 verbose cli   '-g' ]
2 info using npm@3.3.9
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 verbose stack TypeError: Cannot read property 'forEach' of undefined
13 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:12)
13 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
13 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/copy-tree.js:22:18
13 verbose stack     at Array.forEach (native)
13 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:13)
13 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
13 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/copy-tree.js:22:18
13 verbose stack     at Array.forEach (native)
13 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:13)
13 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:15:3)
14 verbose cwd /Volumes/Data/Users/eugene
15 error Darwin 15.0.0
16 error argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "uninstall" "deepify" "-g"
17 error node v5.0.0
18 error npm  v3.3.9
19 error Cannot read property 'forEach' of undefined
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment] 2015-11-12 01:25
Do you know what version of `deepify` you had / have installed when you started? There's something about its tree that's causing npm to blow up when it tries to read the package tree. In our experiments with `deepify`, we discovered that it was creating symbolic links that point to themselves, which exposed a bug in npm (#10350 / #10351), and it's possible that there's something related going on with the version you have installed that's causing npm to choke.

Do you know whether you were running `npm@2` or `npm@3` when you originally installed `deepify`?

**Comment by AlexanderC** [comment] 2015-11-12 14:26
Deepify is working well with `npm@2` and seems like we figured out the root cause of this issue. Thank you @othiym23 for pointing out to the problem. We're moving it to our issues.

**Closed** 2015-11-12 14:34 UTC
Labels: big-bug, bug, needs-repro
