### ISSUE TITLE
Create a grunt project in a different directory

### ISSUE THREAD

**Issue by ashebby** [npm/npm#14455] opened 2016-10-28 13:12 UTC
#### What's going wrong?
trying to create a grunt project in a differect dir, I input npm install grunt into the dir of choice and get this error:

npm WARN enoent ENOENT: no such file or directory, open '/Users/macuser/package.json'
npm WARN macuser No description
npm WARN macuser No repository field.
npm WARN macuser No README data
npm WARN macuser No license field.

**Comment by KenanY** [comment] 2016-10-28 13:53
@ashebby That is just a warning, and should not interrupt the installation. If you would like to get rid of the warning, then you can create a `package.json` file with [`npm init`](https://docs.npmjs.com/cli/init). Closing since this is not a bug with `npm`.

**Closed by KenanY** 2016-10-28 13:53 UTC
