### ISSUE TITLE
npm5 package-lock.json uses resolved URL for version property of existing node_modules

### ISSUE THREAD

**Issue by sgtcoolguy** [npm/npm#16926] opened 2017-06-02 17:19 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

After looking into mapbox/node-pre-gyp#298 I found a behavior change in the package.json files.

The generated `package.json` file for dependencies inside node_modules sometimes uses an URL string value for `version` rather than a version string.

This happens if there is no `package-lock.json` in the repo, but there is an existing set of dependencies in a `node_modules` folder. The generated `package-lock.json` will set `version` to the resolved URL of the packages that already exist in `node_modules` (and will not set a `resolved` property for them). This bad value then works it's way into the `package.json` files of those dependencies.

#### How can the CLI team reproduce the problem?

```shell
git clone git@github.com:appcelerator/titanium_mobile.git --depth 1
npm install
# At this point we have a broken package-lock.json generated
rm -rf node_modules
npm install
# We now have a broken package-lock.json, and the bad version values have propagated into the modules' package.json files.
```

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by sgtcoolguy** [comment] 2017-06-02 18:19
Looks to me like this is the root cause of the error: https://github.com/npm/npm/blob/latest/lib/shrinkwrap.js#L114

My existing node_modules don't have a `_requested.registry` value because they were installed via the "standard"/default npm registry. So the new version value for the lock file gets assigned the `_resolved` value from the existing `package.json`.

I don't know enough history of the code to really know why the move from copying the version value to checking for these specific cases where the version takes the _resolved value. cc @zkat @iarna

**Comment by jokeyrhyme** [comment] 2017-06-04 11:43
I'm having the same problem

Here's another set of steps to reproduce the issue:

```sh
npm install --global npm@4`

mkdir test; cd test`
npm init -y
npm install --save-dev flow-bin

npm install --global npm # i.e. latest / 5.x
npm install
```

For a project that previously had a node_modules installed by `npm` 4.x, the following package-lock.json is created by `npm` 5.x:

```json
{
  "name": "test",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "dependencies": {
    "flow-bin": {
      "version": "https://registry.npmjs.org/flow-bin/-/flow-bin-0.47.0.tgz",
      "integrity": "sha1-oqCKs+DR8ctX0X4nswsRi2L9o2c=",
      "dev": true
    }
  }
}
```

This causes the following errors in Travis CI: https://travis-ci.org/jokeyrhyme/node-init.js/jobs/239279370
> Invalid version: "https://registry.npmjs.org/ava/-/ava-0.19.1.tgz"

**Comment by zkat** [comment] 2017-06-05 15:58
Closing as dupe of https://github.com/npm/npm/issues/16728

**Closed as completed by zkat** 2017-06-05 15:58 UTC
Labels: npm5
