### ISSUE TITLE
Slow search

### ISSUE THREAD

**Issue by jnordberg** [npm/npm#11010] opened 2016-01-02 16:55 UTC
I'm using npm programatically for a plugin system and was tracing down why the searches was so slow (around 5 minutes on my machine with node v5.2.0) and found it to be JSON.decode that was stuck processing a 160mb file (the entire npm registry i assume).

Is there some workaround for this?

**Comment by smikes** [comment] 2016-01-05 13:18
Unfortunately no, there is no official workaround.

Manually, you can use the npmjs.org website's search box.  But I don't believe that there is an API that would allow you to run searches against the npm website.

You can also try npm-kludge-search (https://www.npmjs.com/package/npm-kludge-search), a module that I wrote to address some of the problems around old-style npm search.

**Comment by jnordberg** [comment] 2016-01-05 20:41
Okay, that's a pity. I see that you plan to remove the search functionality. Why not use something like json-stream to parse the registry incrementally? I think it would be possible to get acceptable performance using this

**Comment by torvalamo** [comment] 2016-03-16 02:21
Just as a thought, would it not make more sense to store the local registry in an sqlite file instead of as json? I mean, its purpose is lookup, so adapt it to that purpose...

**Comment by othiym23** [comment] 2016-03-21 17:47
Closing as a duplicate of #6016. See also #10615, which will partially address the issue by making updating the search index _much_ more memory-efficient, although it's going to take more work to make the searching process itself faster and not use all available memory. This is a project that will probably span teams at npm, Inc., and therefore may take a while. Thanks for your time and patience!

**Closed by othiym23** 2016-03-21 17:47 UTC
Labels: bug, search
