### ISSUE TITLE
run-script loglevel too high

### ISSUE THREAD

**Issue by denis-sokolov** [npm/npm#5809] opened 2014-07-27 20:08 UTC
Here's in my `package.json`: `"test": "mocha test test/functional && npm run lint"`.
Here's the output of `npm test`:

```
> <package-name>@<package-version> test <working-dir>
> mocha test test/functional && npm run lint
```

These log messages are logged with a high verbosity. Only `npm --loglevel=silent test` seems to hide them. Shouldn't this be `info` or even `verbose`?
It seems to me that with default options these messages should not appear, rather, only the output of my actual command should. After all, people are running `npm test` (and other `npm run-script`) all the time with the default settings of npm and expect to see useful outputs of the test itself.

I feel like this is a step to imprvoving UI, just like #3295 eventually got there with `npm install`.

**Comment by olizilla** [comment] 2015-03-04 10:34
+1

**Comment by olizilla** [comment] 2015-03-04 10:52
I'm using `npm run -s mocha some/test/over/here` to reduce the noise for arbitrary run scripts. 
`npm test` seems to be less noisy than `npm run foo` by default.

**Comment by jedrichards** [comment] 2015-05-14 22:47
+1. I feel like there should be a loglevel between `silent` and `error`. I'd like **some** indication that `npm run` exited in an error state (maybe a 1 line summary), but ~20 lines of cruft that `loglevel=error` spits out at the moment is pretty distracting.

**Comment by ChrisPearce** [comment] 2015-08-24 17:33
+1

**Comment by jedrichards** [comment] 2015-08-24 18:20
Npm scripts are poised to take over from tools like Grunt and Gulp in the frontend tooling world. It'll be a great thing for the quality of the frontend tooling ecosystem on npm since a whole swathe of sporadically updated Grunt/Gulp plugins can be forgotten about, build processes can get less complex and more unix-y and the quality of tool CLIs will increase too. I few tweaks to the npm scripts DX could really help the process.

**Comment by othiym23** [comment] 2016-08-09 21:31
Closing as a duplicate of #8821 (which came after this issue, but which has more discussion and pointers at a possible resolution, what you gonna do). Thanks to all for raising this and the additional discussion!

**Closed by othiym23** 2016-08-09 21:31 UTC
Labels: feature-request
