### ISSUE TITLE
Running npm uninstall <package> --save-dev causing "npm ERR! code EMISSINGARG Error: Missing required argument #3"

### ISSUE THREAD

**Issue by sanderblue** [npm/npm#10378] opened 2015-11-13 15:21 UTC
While attempting to run an uninstall command ( `npm uninstall gulp-livereload --save-dev` ) I received this output.
[npm-debug.txt](https://github.com/npm/npm/files/34060/npm-debug.txt)

```
npm ERR! Linux 2.6.32-279.5.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rm" "gulp-livereload" "--save-dev"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:427:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:236:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:232:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

```

**Comment by marcoms** [comment] 2015-11-13 20:18
Just got this message a few minutes ago for the first time... Weird.

**Comment by marcoms** [comment] 2015-11-13 21:15
Also the error occurs with any one of `--save-dev`, `--save`, and `--save-optional`

**Comment by marcoms** [comment] 2015-11-13 21:30
Sorry to pollute the issue and everyone's inboxes, but it looks like it only occurs when the package does not exist in `node_modules/`. However this means that it is impossible to remove a dependency from `package.json` using npm if for example you forgot the `-S`/`-D` flag the first time removing it.

**Comment by bradstewart** [comment] 2015-11-13 21:37
I'm seeing the same error on OSX as well.

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/brstewar/.node/bin/npm" "uninstall" "babel"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/Users/brstewar/.node/lib/node_modules/npm/lib/install/deps.js:427:3)
npm ERR! typeerror     at /Users/brstewar/.node/lib/node_modules/npm/lib/install/deps.js:236:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/Users/brstewar/.node/lib/node_modules/npm/lib/install/deps.js:232:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/brstewar/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/brstewar/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/brstewar/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/Users/brstewar/.node/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/Users/brstewar/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/brstewar/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by smartmouse** [comment] 2015-11-14 04:13
There is no error for npm v2.14.7  or npm v3.3.6 on windows for me. 

For npm v3.x , if the node-modules is empty,  (i.e. I did a npm uninstall <xxxx> first )
npm uninstall <xxx> --save  does not remove the node modules <xxx> from dependencies in package.json, 

For npm v2.14.7, the same scenario will remove <xxx> from dependencies package.json.

**Comment by ArsSirek** [comment] 2015-11-29 22:31
Hi everyone, my case fits @marcoms explanation, I forgot -D first time and then it caused the error.
I just installed some packages via command line, including "angular-google-maps", unsupported "lodash-node" (as dev dependence) and lodash (as main dependence) , and then uninstalled them with the following commands:
1)npm uninstall angular-google-maps -D
2)npm uninstall angular-simple-logger -D
3)npm uninstall lodash -D 
4)npm uninstall lodash
5)npm uninstall lodash-node
6)npm uninstall lodash-node -D
So, the last command caused an error
[npm-debug.log.txt](https://github.com/npm/npm/files/46772/npm-debug.log.txt)

npm --version 3.3.12
node --version v5.1.0
ubuntu - 14.04

P.S. As this is not causing any problems for me, I reported only because of the line "This is an error with npm itself. Please report this error at:"
 Can, someone advise me, is it preferable to always report errors with this sort of message? or does it just polite way to point where error should be reported if I need help? )
Thanks.

**Comment by feross** [comment] 2015-12-01 00:07
Confirmed on npm 3.3.12. This is a recent error because this command used to work for me.

I like to use `npm rm package-name -S` to remove dependencies from `package.json`. The package isn't necessarily installed when I run this command.

**Comment by dougwilson** [comment] 2015-12-01 04:07
I just got caught on this issue as well in Travis CI. I use `npm rm --save-dev` to conditionally remove things from the package before `npm install` is run.

**Comment by othiym23** [comment] 2015-12-04 17:35
Closing as duplicate of #10571.

**Closed by othiym23** 2015-12-04 17:35 UTC
