### ISSUE TITLE
i can't install week-toolkit

### ISSUE THREAD

**Issue by highway33** [npm/npm#15125] opened 2016-12-03 03:08 UTC
<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ '/Users/haidong/.nvm/versions/node/v5.9.1/bin/node',
1 verbose cli   '/Users/haidong/.nvm/versions/node/v5.9.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'weex-toolkit' ]
2 info using npm@4.0.3
3 info using node@v5.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData weex-toolkit
8 silly fetchNamedPackageData weex-toolkit
9 silly mapToRegistry name weex-toolkit
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'weex-toolkit',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'weex-toolkit',
12 silly mapToRegistry   name: 'weex-toolkit',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/weex-toolkit
14 verbose request uri https://registry.npmjs.org/weex-toolkit
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:37:36
17 verbose request id bf954c298d6a61a5
18 http request GET https://registry.npmjs.org/weex-toolkit
19 http 200 https://registry.npmjs.org/weex-toolkit
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Fri, 25 Nov 2016 02:09:09 GMT',
20 verbose headers   etag: 'W/"58379d45-1ddfd"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '10638',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 03 Dec 2016 02:37:37 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-itm7420-ITM',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1480732657.550769,VS0,VE156',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Fri, 25 Nov 2016 02:09:09 GMT',
21 silly get     etag: 'W/"58379d45-1ddfd"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '10638',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 03 Dec 2016 02:37:37 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-itm7420-ITM',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1480732657.550769,VS0,VE156',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving weex-toolkit to /Users/haidong/.npm/registry.npmjs.org/weex-toolkit/.cache.json
23 verbose correctMkdir /Users/haidong/.npm correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule weex-toolkit@0.6.2 checking installable status
37 silly cache add args [ 'weex-toolkit', null ]
38 verbose cache add spec weex-toolkit
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'weex-toolkit',
39 silly cache add   scope: null,
39 silly cache add   escapedName: 'weex-toolkit',
39 silly cache add   name: 'weex-toolkit',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: 'latest',
39 silly cache add   type: 'tag' }
40 silly addNamed weex-toolkit@latest
41 verbose addNamed "latest" is being treated as a dist-tag for weex-toolkit
42 info addNameTag [ 'weex-toolkit', 'latest' ]
43 silly mapToRegistry name weex-toolkit
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry data Result {
46 silly mapToRegistry   raw: 'weex-toolkit',
46 silly mapToRegistry   scope: null,
46 silly mapToRegistry   escapedName: 'weex-toolkit',
46 silly mapToRegistry   name: 'weex-toolkit',
46 silly mapToRegistry   rawSpec: '',
46 silly mapToRegistry   spec: 'latest',
46 silly mapToRegistry   type: 'tag' }
47 silly mapToRegistry uri https://registry.npmjs.org/weex-toolkit
48 verbose addNameTag registry:https://registry.npmjs.org/weex-toolkit not in flight; fetching
49 verbose get https://registry.npmjs.org/weex-toolkit not expired, no request
50 silly addNameTag next cb for weex-toolkit with tag latest
51 silly addNamed weex-toolkit@0.6.2
52 verbose addNamed "0.6.2" is a plain semver version for weex-toolkit
53 silly mapToRegistry name weex-toolkit
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry data Result {
56 silly mapToRegistry   raw: 'weex-toolkit',
56 silly mapToRegistry   scope: null,
56 silly mapToRegistry   escapedName: 'weex-toolkit',
56 silly mapToRegistry   name: 'weex-toolkit',
56 silly mapToRegistry   rawSpec: '',
56 silly mapToRegistry   spec: 'latest',
56 silly mapToRegistry   type: 'tag' }
57 silly mapToRegistry uri https://registry.npmjs.org/weex-toolkit
58 verbose addRemoteTarball https://registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz',
59 verbose addRemoteTarball   '373d16608471c66064f1d47375a04f3c2c872717' ]
60 info retry fetch attempt 1 at 10:37:37
61 info attempt registry request try #1 at 10:37:37
62 http fetch GET https://registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz
63 http fetch 200 https://registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz
64 info retry will retry, error on last attempt: Error: read ECONNRESET
65 silly fetchAndShaCheck shasum 373d16608471c66064f1d47375a04f3c2c872717
66 silly rollbackFailedOptional Starting
67 silly rollbackFailedOptional Finishing
68 silly runTopLevelLifecycles Finishing
69 silly install printInstalled
70 verbose stack Error: shasum check failed for /var/folders/rl/2n0b7pz51_db9xsd4yjl54ww0000gn/T/npm-88409-f65bd35f/registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz
70 verbose stack Expected: 373d16608471c66064f1d47375a04f3c2c872717
70 verbose stack Actual:   49315487de212fa29e86cdb4100faf6ebf1f3943
70 verbose stack From:     https://registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz
70 verbose stack     at /Users/haidong/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/sha/index.js:25:8
70 verbose stack     at ReadStream.<anonymous> (/Users/haidong/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/sha/index.js:72:7)
70 verbose stack     at emitNone (events.js:85:20)
70 verbose stack     at ReadStream.emit (events.js:179:7)
70 verbose stack     at endReadableNT (_stream_readable.js:913:12)
70 verbose stack     at _combinedTickCallback (node.js:383:13)
70 verbose stack     at process._tickCallback (node.js:407:11)
71 verbose cwd /Users/haidong/Downloads
72 error Darwin 15.6.0
73 error argv "/Users/haidong/.nvm/versions/node/v5.9.1/bin/node" "/Users/haidong/.nvm/versions/node/v5.9.1/bin/npm" "install" "-g" "weex-toolkit"
74 error node v5.9.1
75 error npm  v4.0.3
76 error shasum check failed for /var/folders/rl/2n0b7pz51_db9xsd4yjl54ww0000gn/T/npm-88409-f65bd35f/registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz
76 error Expected: 373d16608471c66064f1d47375a04f3c2c872717
76 error Actual:   49315487de212fa29e86cdb4100faf6ebf1f3943
76 error From:     https://registry.npmjs.org/weex-toolkit/-/weex-toolkit-0.6.2.tgz
77 error If you need help, you may report this error at:
77 error     <https://github.com/npm/npm/issues>
78 verbose exit [ 1, true ]
 </pre></details>

**Comment by zkat** [comment] 2016-12-05 22:41
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-05 22:41 UTC
