### ISSUE TITLE
npm run dist in windows with error

### ISSUE THREAD

**Issue by zhuxindaba** [npm/npm#11902] opened 2016-03-15 03:51 UTC
**when i input 'npm run dist' in windows**

> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wangzhiwei\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run"
>  "dist"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code ELIFECYCLE
> npm ERR! gitblog@1.0.0 dist: `NODE_ENV=production webpack --progress --colors`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the gitblog@1.0.0 dist script 'NODE_ENV=production webpack --progress --colors'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the gitblog package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     NODE_ENV=production webpack --progress --colors
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs gitblog
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls gitblog
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:

**Comment by zhuxindaba** [comment] 2016-03-15 03:53
my package.json
```
{
  "name": "gitblog",
  "version": "1.0.0",
  "description": "my github pages",
  "main": "index.js",
  "scripts": {
    "build": "webpack --progress --colors --watch",
    "watch": "webpack-dev-server --hot --progress --colors",
    "dist": "NODE_ENV=production webpack --progress --colors"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zhuxindaba/zhuxindaba.github.io.git"
  },
  "author": "zhuxin",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/zhuxindaba/zhuxindaba.github.io/issues"
  },
  "homepage": "https://github.com/zhuxindaba/zhuxindaba.github.io#readme",
  "dependencies": {
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.10.0",
    "jquery": "^2.2.1",
    "node-sass": "^3.4.2",
    "react": "^0.14.7",
    "sass-loader": "^3.2.0",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1",
    "yarjs": "^1.0.4"
  }
}
```

**Comment by othiym23** [comment] 2016-03-15 04:42
The `dist` script isn't going to work as written on Windows – because scripts are run with `cmd.exe` on Windows the `NODE_ENV=production` part will be interpreted as a command, rather than setting an environment variable. There isn't a really good workaround this for the moment, aside from writing a Node script to invoke webpack as a child process after setting `process.env.NODE_ENV = 'production'`. The CLI team does have some plans to simplify writing package scripts to work the same on both UNIX and Windows, but it may be a while until that happens. Until then, package scripts will need to stay pretty simple to work on both platforms.

As this is the current intended behavior of npm, I'm going to close this issue. Thanks for your time, and I hope this explanation was useful!

**Closed by othiym23** 2016-03-15 04:42 UTC
Labels: support, windows
