### ISSUE TITLE
Hubot Installation error

### ISSUE THREAD

**Issue by lvyingde51** [npm/npm#12248] opened 2016-04-07 09:24 UTC
Have some problems,If you know how to solve it,Please help me..Thank you..

```
root@ip-172-31-35-251:/opt/hubot# npm ls
npm WARN unmet dependency /opt/hubot/node_modules/hubot-mock-adapter/node_modules/hubot requires express@'^3.21.2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
hubot@2.18.0 /opt/hubot
├── async@0.9.2
├─┬ chai@2.1.2
│ ├── assertion-error@1.0.0
│ └─┬ deep-eql@0.1.3
│   └── type-detect@0.1.1
├─┬ chalk@1.1.3
│ ├── ansi-styles@2.2.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ has-ansi@2.0.0
│ │ └── ansi-regex@2.0.0
│ ├─┬ strip-ansi@3.0.1
│ │ └── ansi-regex@2.0.0
│ └── supports-color@2.0.0
├── cline@0.8.2
├── coffee-errors@0.8.6
├── coffee-script@1.6.3
├─┬ connect-multiparty@1.2.5
│ ├─┬ multiparty@3.3.2
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── stream-counter@0.2.0
│ ├─┬ on-finished@2.1.1
│ │ └── ee-first@1.1.0
│ ├── qs@2.2.5
│ └─┬ type-is@1.5.7
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.0.14
│     └── mime-db@1.12.0
├── UNMET DEPENDENCY express ^3.21.2
├─┬ hubot-mock-adapter@1.0.0
│ ├─┬ hubot@2.18.0
│ │ └── UNMET DEPENDENCY express ^3.21.2
│ └── lodash@1.3.1
├── log@1.4.0
├── mockery@1.4.1
├── optparse@1.0.4
├── scoped-http-client@0.11.0
├─┬ sinon@1.17.3
│ ├── formatio@1.1.1
│ ├── lolex@1.3.2
│ ├── samsam@1.1.2
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
└── sinon-chai@2.8.0

npm ERR! missing: express@^3.21.2, required by hubot@2.18.0
npm ERR! missing: express@^3.21.2, required by hubot@2.18.0
npm ERR! not ok code 0
```

**Comment by othiym23** [comment] 2016-04-07 16:43
When #12247 / #12196 is resolved, this issue will also be resolved (although you'll probably need to `rm -rf node_modules` and do a complete reinstall). If you can, now would be a good time to upgrade [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-linux) and [npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). Because this is caused by another issue (that's itself a duplicate), I'm going to close this issue. Thanks for your time!

**Closed by othiym23** 2016-04-07 16:43 UTC
Labels: support
