### ISSUE TITLE
Packages cannot be installed directly from Git repos

### ISSUE THREAD

**Issue by alexgig** [npm/npm#18791] opened 2017-10-11 15:10 UTC
#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?

A package referenced with a git url cannot be installed.

#### How can the CLI team reproduce the problem?

Installing the following package fails:

```bash
$ npm install git+https://github.com/elm-node/core.git#semver:^2.2.1
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexandre/.npm/_logs/2017-10-11T15_07_34_154Z-debug.log
```

[2017-10-11T15_07_34_154Z-debug.log](https://github.com/npm/npm/files/1376096/2017-10-11T15_07_34_154Z-debug.log)

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v8.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by EvgenyOrekhov** [comment] 2017-10-16 09:55
This is a duplicate of https://github.com/npm/npm/issues/18434.

**Closed as completed** 2017-10-17 14:05 UTC
Labels: git, npm5
