### ISSUE TITLE
Add support for `npm install --no-build`

### ISSUE THREAD

**Issue by bevacqua** [npm/npm#6529] opened 2014-10-21 03:38 UTC
It'd be great to have this as part of the npm CLI. See ["npm clean modules"][1] on SO.

Use case would be I want to `rsync` my app into another environment and then run `npm rebuild` on it, without having to go through `npm install`. This is particularly useful when the remote environment runs on a different platform (e.g: OSX vs Ubuntu), and also when the local environment tweaks `node_modules` using `npm prune` or `npm dedupe`. I'm sure there are similar use cases related to this

Thoughts?

[1]: http://stackoverflow.com/q/11351784/389745

**Comment by cesarandreu** [comment] 2015-01-04 22:03
Just to check up, is there any update on this?

**Comment by qubyte** [comment] 2015-04-06 12:35
I'm doing a little work that this would be really handy for. The sequence goes something like

 - A build server listens for tag events on a repo on github with a webhook.
 - Upon a new tag, it checks out that tag and installs (with --no-build or equivalent).
 - tars and zips the result.
 - Creates a release from the tag with the github releases API.
 - Uploads the zip file as a release asset.
 - A fleet of various production servers grab the asset and run rebuild.

There's no reason not to do this now of course, but it seems less wasteful to build when it's just adding bulk to the asset and time to the process.

**Comment by othiym23** [comment] 2015-08-04 22:45
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by qubyte** [comment] 2015-11-11 14:32
@othiym23 This no longer appears on the roadmap. Has there been any movement on this?

**Comment by boneskull** [comment] 2016-02-04 16:39
Is this a dupe of #2871?

**Comment by medikoo** [comment] 2016-04-21 06:45
> @othiym23 This no longer appears on the roadmap. Has there been any movement on this?

+1

It's quite important as now more of us wants to submit `node_modules` into repositories, and that this practice found place in [npm recommendations](https://docs.npmjs.com/cli/shrinkwrap#caveats)

(sadly it's not addressed for nearly 4 years already, it's when first request for that was issued)

**Comment by othiym23** [comment] 2016-09-20 21:48
This would be useful enough that it’s something we’d be happy to add if it were submitted as a patch, but looking at the priorities for the team, it’s not something that we ourselves are going to be able to do within the next 6-12 months. As such, we’re going to close this feature request, and y’all can send us a patch and we’ll review it, work with you to improve it, and merge it when it’s ready.

@iarna has this to add as far as what the patch might look like:

> To implement this you would need to add a new configuration option and then edit [npm/install.js](https://github.com/npm/npm/blob/master/lib/install.js) to not call the `preinstall`, `install`, `postinstall` or `build` steps.
> 
> Those steps are located in `executeActions` (approximately [here](https://github.com/npm/npm/blob/master/lib/install.js#L479) for dependencies.
> 
> And in `run` around [here](https://github.com/npm/npm/blob/master/lib/install.js#L263) and [here](https://github.com/npm/npm/blob/master/lib/install.js#L276) for the project level.
> 
> We would also want tests demonstrating the new behavior with and without the flag.

Thanks for your time and suggestions!

**Closed by othiym23** 2016-09-20 21:48 UTC
Labels: feature-request, lifecycle, patch-welcome, platform-integration

**Comment by medikoo** [comment] 2016-09-21 07:02
@othiym23 if you're open to take this feature, why you close the issue? This actually gives quite opposite signal. 
If it's not on your nearest roadmap, let's just keep it open in _patch-welcome_ bucket (?)

**Comment by othiym23** [comment] 2016-09-21 15:26
@medikoo, it's the policy of the npm CLI team to leave open only the feature requests that we intend to see included in the CLI within the next 6-12 months (either developed by the three of us on the team or by the community at large). Features that we'll accept because they're nice to have but that we don't deem integral to the road map of the CLI will be closed. This seems a little weird, I know, but it's one of the few tools we have to make clear to users the priorities of the project.

**Comment by lmj0011** [comment] 2018-04-26 21:18
@othiym23 

is there at least a "workaround" to being able to skip binaries produced from `npm install`?

is `npm install --ignore-scripts` safe to use for this case?

ref: https://stackoverflow.com/a/23506053/2445763

my use case is similiar to @qubyte 
https://github.com/npm/npm/issues/6529#issuecomment-90042328
