### ISSUE TITLE
Sign the version bump.

### ISSUE THREAD

**Issue by hemanth** [npm/npm#12288] opened 2016-04-09 15:06 UTC
Now that Github allows to sign the commits with GPG keys, would it make sense for `npm version` to have a `-S` flag to sign the version bumps?

**Comment by KenanY** [comment] 2016-07-10 14:30
Duplicate of https://github.com/npm/npm/issues/12696.

**Comment by hemanth** [comment] 2016-07-13 12:04
@KenanY Ins't `12288 < 12696` ? 

Shouldn't the other issue be closed and marked as duplicate?

**Comment by KenanY** [comment] 2016-07-13 13:22
@hemanth Whoops :)

**Comment by othiym23** [comment] 2016-07-13 17:30
in general, the CLI team treats the version of an issue with the most discussion or supporting documentation as the "master" issue, rather than the first filed. That's not a hard and fast rule, tho – more important is keeping duplicates to a minimum when possible.

**Comment by hemanth** [comment] 2016-07-14 04:18
@othiym23 Agree 👼

**Closed** 2017-06-16 22:47 UTC
Labels: bot-closed, documentation, support
