### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by shadowQ5** [npm/npm#15101] opened 2016-12-01 19:40 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?
running npm install produces this issue

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Development\\nodejs\\node.exe" "C:\\Development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\rjosu-w\AppData\Local\Temp\npm-13780-69a1a351\registry.npmjs.org\http-proxy\-\http-proxy-0.8.7.tgz
npm ERR! Expected: a7bc538618092cd26ed191e4625933baef6de80e
npm ERR! Actual:   b28ba8bf3e0becd7b6b6d05c6a0e692f6b90ba60
npm ERR! From:     https://registry.npmjs.org/http-proxy/-/http-proxy-0.8.7.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>




```

#### How can the CLI team reproduce the problem?

[npm-debug.log](https://gist.github.com/shadowQ5/dc248caf30c8af4598b80cca0d5fe033#file-npm-debug-log)

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2016-12-02 03:29
If it's just a strange network hiccup, simply running `npm install` again should work. If it doesn't, please let me know the following:

1. Are you behind a proxy?
2. Are you behind some sort of firewall?
3. Can you upload the contents of `C:\Users\rjosu-w\AppData\Local\Temp\npm-13780-69a1a351\registry.npmjs.org\http-proxy\-\http-proxy-0.8.7.tgz` somewhere that I can look at it?
  a. If that specific file isn't present, could you re-run the command and grab the file the error is referring to?

We've been seeing a bunch of these, and it would be very helpful if you helped us figure out if there's a particular pattern to these. Cheers!

**Comment by zkat** [comment] 2016-12-02 04:40
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:40 UTC
Labels: network, shasum, support
