### ISSUE TITLE
Error: Cannot find module './lib'

### ISSUE THREAD

**Issue by CanKer** [npm/npm#10193] opened 2015-10-31 01:00 UTC
I just updated my Node to version 5.0 and when I run npm I get this error:

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/index.js:1:80)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by othiym23** [comment] 2015-10-31 01:03
Closing as duplicate of #10166. The current theory is that a change made to the OS X installer for Node is causing two npm installations to be overlaid, which is understandably causing problems. If you remove `/usr/local/lib/node_modules/npm` and rerun the Node 5.0 installer, you should be left with a working npm.

**Closed by othiym23** 2015-10-31 01:03 UTC

**Comment by CanKer** [comment] 2015-10-31 06:46
Thank you so much and sorry. :)
