### ISSUE TITLE
npm install -g appium errno -5

### ISSUE THREAD

**Issue by helenakeep** [npm/npm#15118] opened 2016-12-02 10:16 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:  3.10.3
 - `node -v` prints:  v6.3.1
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by helenakeep** [comment] 2016-12-02 10:17
npm ERR! tar.unpack unzip error /var/folders/r7/1jw3mgkx40q782w5r5xk_6n40000gn/T/npm-35644-5bc46de1/registry.npmjs.org/appium-adb/-/appium-adb-2.6.19.tgz
npm ERR! tar.unpack unzip error /var/folders/r7/1jw3mgkx40q782w5r5xk_6n40000gn/T/npm-35644-5bc46de1/registry.npmjs.org/appium-uiautomator2-driver/-/appium-uiautomator2-driver-0.1.0.tgz
npm ERR! tar.unpack unzip error /var/folders/r7/1jw3mgkx40q782w5r5xk_6n40000gn/T/npm-35644-5bc46de1/registry.npmjs.org/babel-core/-/babel-core-5.8.24.tgz
npm ERR! tar.unpack unzip error /var/folders/r7/1jw3mgkx40q782w5r5xk_6n40000gn/T/npm-35644-5bc46de1/registry.npmjs.org/appium-uiautomator2-server/-/appium-uiautomator2-server-0.0.6.tgz
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR!

**Comment by zkat** [comment] 2016-12-02 19:17
closing as a duplicate of https://github.com/npm/npm/issues/11993

**Closed by zkat** 2016-12-02 19:17 UTC
