### ISSUE TITLE
`npm update --save` should not change "locked" versions

### ISSUE THREAD

**Issue by dominykas** [npm/npm#4261] opened 2013-12-06 12:20 UTC
Having this package.json:
```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "amdefine": "0.0.2",
    "strftime": "0.6.1"
  }
}
```

Do: `npm install; npm update --save`. Resulting package.json:
```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "amdefine": "0.0.2",
    "strftime": "~0.6.1"
  }
}
```

Then do `npm update --save` again. Resulting package.json:
```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "amdefine": "0.0.2",
    "strftime": "~0.6.2"
  }
}
```

Notice how strftime got updated to 0.6.2 in the second update, although it was locked at 0.6.1 in the beginning.

Expected result: no updates, since versions are locked.

This is not happening with npm 1.3.11 + node 0.10.20
This is happening with npm 1.3.11 + node 0.10.20 if you don't do `npm install`, i.e. run `npm update --save` in an empty folder containing initial package.json

This is happening with npm 1.3.14, 1.3.15 + node 0.10.22 regardless if you run `npm install` or not.

**Comment by smikes** [comment] 2015-02-21 21:25
Is this still a problem for you?

I think part of the issue here is that `npm update` has been a broken command for a long time.  However, I all the behavior you describe is still present in current `npm`, and I'm afraid that it's all actually "by design".

Here's what I think is happening. `npm update --save` is allowed to write versions to package.json, and it honors `npm.config("save-prefix")` which at the time you created this issue, defaulted to `~`.  Now it defaults to `^`; I think for your purposes you may wish to set it to `=`.  Anyway, the first time you run, `npm update --save` reads `"strftime": "0.6.1"` and writes `"strftime": "~0.6.1"`.  This is expected behavior.

The second time `npm update --save` is run, it sees "~0.6.1" and `npm.config("tag")` is `latest`, so `npm` looks up the version corresponding to `latest`, sees that it is "0.6.2", and installs that, writing `"strftime": "~0.6.2"` to `package.json`.  Again, expected behavior.

The simplest way to avoid this would be to not use `npm update --save`.

You can use  `npm install --save-prefix='=' --save strftime@0.6.1` to lock a specific version, preventing `npm update` for overriding it.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.11. Have you updated your npm installation?  The most recent `npm` — `npm@next`, v2.6.1 — contains some changes to how `npm update` and `npm outdated` work.

We are trying to clean up older npm issues, so pleaset let us know if you are no longer interested in this issue.

Thanks!

**Comment by dominykas** [comment] 2015-02-23 10:53
> The simplest way to avoid this would be to not use `npm update --save.`

This issue is no longer a problem for me, as I've long since given up on `npm update` - the only way I'm updating dependencies is `npm cache clean && rm -rf node_modules && npm install` after manually bumping versions (if needed/desired) after reviewing with `npm outdated --depth=0` and I do not intend to use any other way of running updates until I'm positively sure that `npm update` will result in the _exact_ same tree as `npm install` on an empty folder.

As for this particular issue - it's your call, I guess, on how `npm update` should behave:

* bump the version to latest (regardless of what's in package.json - current behavior)
* ask for user input to make a decision
* log a warning
* keep the version defined

Feel free to close this issue, if the behavior is "as designed".

**Comment by smikes** [comment] 2015-02-23 12:46
Just because I believe I can explain every step in the behavior and relate it to design, doesn't mean that the design is not a bug! ;-)

I think when `npm@3` is released, it will have a better, more comprehensive approach to `npm update`.  In the meantime, when @othiym23 has a chance he might want to comment/correct my analysis above.

**Comment by iarna** [comment] 2016-05-27 23:33
So the good news is that the original problem described here is fixed, in both `npm` v2 and v3. Neither of these will attempt to update either of those modules and thus won't add any prefix (`~` or `^`). As such, I'm gonna close this.

> `npm update` will result in the exact same tree as `npm install` on an empty folder

It is unlikely that `npm update` will ever do _that_, but I do want to see a way of doing that, probably in the form of a new command (which you'd be able to use in place of both update AND install).

**Closed by iarna** 2016-05-27 23:33 UTC
Labels: bug

**Comment by dominykas** [comment] 2016-05-28 09:23
Thanks
