### ISSUE TITLE
npm publish fails to send a file

### ISSUE THREAD

**Issue by serkanserttop** [npm/npm#12236] opened 2016-04-06 12:46 UTC
I updated a package by `npm publish` but `index.js` located under the root of package was not uploaded.
I checked if there is any issue related to an ignore file, but there was no such reference.
I published couple more times, and in all cases, `index.js` was missing.
This file existed in the package from its inception, there were no changes on it.
I don't have a reason why this might be the case.
Anyone experienced such an issue?

I moved the file under the `lib` folder after couple tries that did not work, and fixed my problem with a workaround.

**Comment by makenova** [comment] 2016-04-07 17:08
I haven't experienced your issue but you can explicitly include any files you want in the `files` array of your `package.json`.

```js
// package.json
{
  "files": [
    "foo.js",
    "lib/"
  ]
}
```

The above snippet is from [here](https://github.com/npm/npm/wiki/Files-and-Ignores) and some known issues are listed.

P.S. I'm not affiliated with npm, but hopefully some of this is helpful.

**Comment by serkanserttop** [comment] 2016-04-07 19:13
@makenova Thanks for the info. I fixed it with a workaround. I only experienced it in one repo. I wanted to report it in case other people have the same issue as well. I noticed it because it was the main file and everything broke. What if it was a lesser important file, I may not have noticed it for a while. That would cause for some concern.

**Comment by gethinwebster** [comment] 2016-04-13 11:21
I have seen a similar issue intermittently as well - one or more of the files specified in my package.json `files` array failing to be published. They also fail to get included in the tarball when running `npm pack`.

In my case, it was resolved by re-saving the file: it seems this change to the last-modified date and/or content caused it to get correctly re-included in the next publish.

I'm running npm 3.5.2 on OSX 10.11.2. A colleague running with a similar setup has also seen this happening on a number of occasions.

If I see it 'in action' I'll try to provide more details - if there are any log outputs, or verbose flags that can be used to get more information that'd be useful to know in advance.

**Comment by chrisamaral** [comment] 2016-05-17 16:29
I experimented deleting files around and the pattern I noticed was that npm always _(?)_ drops the last file from the project root.
I'm running npm `3.9.0` and node `6.1.0`, on Arch Linux.

**Comment by othiym23** [comment] 2016-05-17 16:50
Closing as duplicate of #5082 (which is under active remediation).

**Closed by othiym23** 2016-05-17 16:50 UTC
Labels: bug
