### ISSUE TITLE
Shasum check failed - Cordova Ionic Installation error

### ISSUE THREAD

**Issue by vinogeetha** [npm/npm#15837] opened 2017-02-23 05:09 UTC
###  **Error Log** 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\577818\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! shasum check failed for C:\Users\577818\AppData\Local\Temp\npm-8216-107
1b899\registry.npmjs.org\bplist-parser\-\bplist-parser-0.1.1.tgz
npm ERR! Expected: d60d5dcc20cba6dc7e1f299b35d3e1f95dafbae6
npm ERR! Actual:   bdab6f483d8f83838a00bfdec028a106208f04c7
npm ERR! From:     http://registry.npmjs.org/bplist-parser/-/bplist-parser-0.1.1
.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log

## **Tried already**
1. npm cache clean
2. Downgraded version of node
3. Tried changing registry (cnpm)
4. Updated npm.
5. Tried Setting proxy as I am behind corporate proxy.
6. Tried as said in issue  #14626 
7. Tried multiple npm install attempts.

**Comment by abdulhameedalyousef** [comment] 2017-02-23 11:31
Keep trying several times. I just got it working! start the terminal with:
`sudo -i`
and make sure you install a package at a time.

**Comment by legodude17** [comment] 2017-02-23 17:14
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by vinogeetha** [comment] 2017-03-03 11:04
No I tried updating npm, and also used sudo, tried installing several times also..

@legodude17 @abdulhameedalyousef

**Comment by legodude17** [comment] 2017-03-03 17:07
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`

**Comment by bhawin-bigstep** [comment] 2017-04-23 15:46
https://registry.npmjs.org/
undefined
null

**Closed** 2017-06-16 21:56 UTC
Labels: bot-closed, shasum, support
