### ISSUE TITLE
Cannot read property 'pause' of undefined

### ISSUE THREAD

**Issue by magicdawn** [npm/npm#18520] opened 2017-09-14 06:26 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`Cannot read property 'pause' of undefined`
from npm-lifecycle module

error log last lines
```
8925 silly preinstall basic-auth-connect@1.0.0
8926 info lifecycle basic-auth-connect@1.0.0~preinstall: basic-auth-connect@1.0.0
8927 silly preinstall basic-auth@1.0.4
8928 info lifecycle basic-auth@1.0.4~preinstall: basic-auth@1.0.4
8929 verbose lifecycle sails@0.12.13~preinstall: unsafe-perm in lifecycle true
8930 verbose lifecycle sails@0.12.13~preinstall: PATH: /Users/magicdawn/.nvm/v8.4.0/lib/node_modules/npm/bin/node-gyp-bin:/private/tmp/node_modules/sails/node_modules/.bin:/private/tmp/node_modules/.bin:/Users/magicdawn/.yarn/bin:/Users/magicdawn/.pyenv/shims:/Users/magicdawn/.rbenv/shims:/Users/magicdawn/.nvm/v8.4.0/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/magicdawn/bin:.:/Users/magicdawn/gopath/bin:/usr/local/share/dotnet:/Users/magicdawn/.composer/vendor/bin:/usr/local/sbin/:/Users/magicdawn/.fzf/bin
8931 verbose lifecycle sails@0.12.13~preinstall: CWD: /private/tmp/node_modules/sails
8932 silly lifecycle sails@0.12.13~preinstall: Args: [ '-c', 'node ./lib/preinstall_npmcheck.js' ]
8933 silly lifecycle sails@0.12.13~preinstall: Returned: code: 0  signal: null
8934 verbose stack TypeError: Cannot read property 'pause' of undefined
8934 verbose stack     at runCmd (/Users/magicdawn/.nvm/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:212:11)
8934 verbose stack     at dequeue (/Users/magicdawn/.nvm/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:201:12)
8934 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
8934 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
8935 verbose cwd /private/tmp
8936 verbose Darwin 16.7.0
8937 verbose argv "/Users/magicdawn/.nvm/v8.4.0/bin/node" "/Users/magicdawn/.nvm/v8.4.0/bin/npm" "i" "sails@0.12.13"
8938 verbose node v8.4.0
8939 verbose npm  v5.4.1
8940 error Cannot read property 'pause' of undefined
8941 verbose exit [ 1, true ]
```

caused by code in 
/Users/magicdawn/.nvm/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:212:11
![image](https://user-images.githubusercontent.com/4067115/30414946-718ab2da-9958-11e7-8459-bc6599ecb19e.png)

#### How can the CLI team reproduce the problem?

`npm install sails@0.12.13`

### supporting information:

 - `npm -v` prints: 5.4.1
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints:  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by HannesT117** [comment] 2017-09-14 14:23
Same issue here while trying to install `tns-template-master-detail-ng`.
`npm -v` 5.4.1
`node -v` 8.5.0
macOS

**Comment by iguerendiain** [comment] 2017-09-14 21:52
Same trying to install node-inspector

NPM version: 5.4.0
NODE version: 8.2.1
OS: Linux Mint 18.2

```
$ npm i -g node-inspector
> v8-profiler@5.7.0 preinstall /mnt/sto/dvlp/node-v8.2.1-linux-x64/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'
npm ERR! Cannot read property 'pause' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iguerendiain/.npm/_logs/2017-09-14T21_51_03_250Z-debug.log

```

**Comment by iguerendiain** [comment] 2017-09-14 22:25
Also tried on NPM 5.4.1 and NODE 8.5.0 with same result.

**Comment by homaily** [comment] 2017-09-16 16:22
Same issue here on both MacOS and Ubuntu. Had to go back to npm 5.3.0

**Comment by ndraiman** [comment] 2017-09-18 11:28
Same issue here.

* `npm v5.4.2`
* `node v6.11.3`
* OS: Windows 10

As a workaround, downgrading `npm` to `v4.6.1` solves the issue.

**Comment by hugodes** [comment] 2017-09-18 12:12
Same issue here with npm 5.4.2 and node 8.5.0

**Comment by simonua** [comment] 2017-09-18 12:44
@Nexxado, it's a radical step to downgrade all the way to 4.6.1, I think, as you lose out on a lot of the benefits that npm 5 provides. I've found that locking in at 5.3.0 for the time being yields the most success for our setup at my organization on Windows 7/10. Have you tried that version?

**Comment by hugodes** [comment] 2017-09-18 13:26
@Nexxado @simonua Indeed, downgrading from 5.4.2 to 5.3.0 fixes it. No need to go all the way down to 4.6.1 for us.

**Comment by ndraiman** [comment] 2017-09-19 14:19
@hugodes @simonua You guys are correct, I updated to 5.3.0 and it works fine. 

Thank you.

**Comment by luislobo** [comment] 2017-09-19 15:51
Same thing here:
```
28071 verbose stack TypeError: Cannot read property 'pause' of undefined
28071 verbose stack     at runCmd (/home/lobo/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:212:11)
28071 verbose stack     at dequeue (/home/lobo/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:201:12)
28071 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
28071 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
[...]
28073 verbose Linux 4.10.0-33-generic
28074 verbose argv "/home/lobo/.nvm/versions/node/v8.5.0/bin/node" "/home/lobo/.nvm/versions/node/v8.5.0/bin/npm" "i"
28075 verbose node v8.5.0
28076 verbose npm  v5.4.2
28077 error Cannot read property 'pause' of undefined

```

**Comment by evantahler** [comment] 2017-09-22 21:15
I'm seeing this issue as well with npm v5.4.x, and yes, downgrading to npm v5.3.x lets me install my packages.  (bug & fix tested on OSX and Ubuntu 16)

I've got 2 pieces of publicly accessible data which reproduce this:  
1) The [`package.json`](https://github.com/actionhero/actionhero/blob/master/package.json) for the [ActionHero](https://www.actionherojs.com/) project (just clone and type `npm install` to see the error)
2) The same project when deployed to Heroku.  Heroku automatically installs the latest `npm`, so downgrading isn't an option:

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=4.0.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=4.0.0...
       Downloading and installing node 8.5.0...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 5.3.0)...
       npm 5.4.2 installed
-----> Restoring cache
       Skipping cache restore (new-signature)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       
       > typechecker@2.0.8 preinstall /tmp/build_42c8cc8be3703393cdd3821ebdb1a4d4/actionhero-actionhero-c1797f2/node_modules/extendr/node_modules/typechecker
       > node ./cyclic.js
       
       npm ERR! Cannot read property 'pause' of undefined
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2017-09-22T21_10_31_425Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

```

**Comment by luislobo** [comment] 2017-09-25 20:24
I have just tested it with NPM Canary version (npmc) and it worked for me (sails 0.12.13 and other dependant dependencies had issues with 5.4.2 latest version)

EDIT: actually it did in one case, it didn't in other! ... solved adding `--ignore-scripts`

**Comment by Gautam17** [comment] 2017-10-02 04:20
same issue with
 npm 5.4.2
 node 8.4.0
 sails 0.12
 mac 10.12.5

thank you @simonua @hugodes, downgrading to 5.3.0 worked( npm install npm@5.3.0 -g )

**Comment by luislobo** [comment] 2017-10-02 06:20
@iarna idk if this one is under your radar... but there are several packages of different types failing because of this... Is it related to any other issue being worked on?
thanks!

**Comment by niftylettuce** [comment] 2017-10-02 17:56
Same bug here, yet another reason why everyone still stop using `npm` and switch to `yarn`.  I can't even support `npm` with my widely used packages anymore... 🤦‍♂️

**Comment by isaacs** [comment] 2017-10-02 18:32
Fixed by https://github.com/npm/lifecycle/commit/1a69ce8, but npm-lifecycle@1.0.3 needs to be pulled into the CLI.

**Comment by isaacs** [comment] 2017-10-02 18:35
Which is to say, yes, this is getting addressed, team is on it.  Apologies for the hassle.

**Comment by homaily** [comment] 2017-10-02 18:39
I've installed **npm-lifecycle** globally and the issue is resolved. Thanks @isaacs.

**Comment by simonua** [comment] 2017-10-02 18:53
As @luislobo indicated, it's in canary: https://github.com/npm/npm/compare/latest...release-next
I'm going to sit tight on 5.3.0 for the time being rather than installing the latest canary or installing npm-lifecycle globally as 5.4.0 introduced locale-agnostic sorting (good!) which has an effect on our package-lock files (bad!) when mixed with pre-5.4.0 npm developers. Hopefully, when canary's changes merge, and there'll be a 5.4.3 or 5.5.0, the recommendation across the board in my organization will be to upgrade to `latest`.

**Comment by niftylettuce** [comment] 2017-10-03 00:29
Thank you for resolving this quickly!  🙇

**Comment by simonua** [comment] 2017-10-05 18:56
npm 5.5.0/5.5.1 has been very stable for me now. I do not see this issue anymore. Please upvote this comment if these versions resolve the issue for you, too.

**Comment by luislobo** [comment] 2017-10-06 05:43
@simonua @isaacs 5.5.0 and 5.5.1 have the fixes for this issue. Thank you!

**Comment by simonua** [comment] 2017-10-06 10:38
@magicdawn, are you good to close this issue, please?

**Closed as completed** 2017-10-07 07:25 UTC
Labels: support, npm5

**Comment by profimedica** [comment] 2017-10-13 02:17
Same issue

npm -v 5.4.2
angular/cli: 1.3.1
node: 6.9.0
os: win32 ia32

**Comment by OmgImAlexis** [comment] 2017-10-13 03:04
@profimedica it states above that you need to update to `5.5.0` or above.

**Comment by vishalbiradar** [comment] 2017-10-13 10:05
I also faced same problem in my mac system.
So I downgraded npm version to 5.3.0.
And then everything was working fine.

To install/upgrade/downgrade npm version:

**`npm install -g npm@version`**

for ex. If I want to downgrade from npm 5.4.2 to 5.3.o
then,

**`npm install -g npm@5.3.0`**

This will work....

**Comment by paulogdm** [comment] 2017-10-16 14:07
No problems on 5.5.1 so far!
`npm i -g npm` is the way to go!

**Comment by stuk88** [comment] 2017-10-19 11:03
Ok. on node 8.7.0 the problem is back.
downgraded to 8.4.0

**Comment by Stono** [comment] 2017-10-19 11:40
Yup, broken again for us too.
Do you guys not have CI?!

```

npm ERR! Cannot read property 'pause' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-19T11_37_28_341Z-debug.log
Service 'app' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**Comment by paulogdm** [comment] 2017-10-19 12:50
Im running node 8.6 and npm 5.4.2. I also did a clean install of NPM and managed to fix npm permissions [docs here](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by simonua** [comment] 2017-10-19 12:53
Hi @stuk88, NodeJS 8.7.0 [ships with npm 5.4.2](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.7.0). The problem was fixed correctly with npm 5.5.0. I run NodeJS 8.7.0 on Windows with no problems with npm 5.5.1. Typically, node is only lagging behind a little in latest npm version but here it mattered for this issue. I suggest that when you install NodeJS, uncheck the option to install npm. This is possible in the Windows installer. I have not tried to do this on any other OS.

Of course, you can always install the latest available version of npm after the node install.

Downgrading to 8.4.0 solved your issue because it installed npm 5.3.0. The issue here didn't occur until 5.4.0

**Comment by simonua** [comment] 2017-10-19 12:56
Not npm's fault here, Karl. Please see my latest comment.

**Comment by nvtin** [comment] 2017-10-23 02:35
@simonua Yes exactly NodeJS 8.7.0 ships with npm 5.4.2.
I install latest version npm 5.5.1 but when I deploy docker, it dont understand latest version, it alway get 5.4.2 for node 8.7.0.
So I uninstalled node and reinstalled node with LTS version (v6.11.4) and npm is 3.10.10
But when I build docker, it still use npm@5.4.2 with node 8.7.0.

I check npm -v, it's result 3.10.10. I don't know how to make docker deploy understand and use npm with current local version.
Actually I've removed docker-machine and created a new one again but it still happend.
```
Step 15/19 : RUN npm install
 ---> Running in 237b814b1bd2
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle verypatient@0.0.1~preinstall: verypatient@0.0.1
```
Any way to force it use latest npm version or current version?

**Comment by luislobo** [comment] 2017-10-23 04:55
@nvtin just run `npm install -g npm@5.5.1` before running `npm install`

**Comment by simonua** [comment] 2017-10-23 12:16
Hi @nvtin, that sounds like a pathing issue to me, perhaps. In Windows, I run `echo %path%` to see what the system + user path combination looks like. I try to make sure that the path to the global npm installation is set towards the end (in my user path). For instance, on Windows that is `C:\Users\skurtz\AppData\Roaming\npm;` for me, so the global npm install will supersede any other.

**Comment by nvtin** [comment] 2017-10-24 02:21
Hi @luislobo @simonua 
I have tried to run `npm install -g npm@5.5.1` and check `npm -v`. it show 5.5.1 but when I deploy to docker. it always use node 8.7.0 and npm 5.4.2.
So I have removed docker-machine, node, npm on my machine and reinstall it again with node 8.6.0 and npm 5.3.0. And It worked now.
Btw thanks for your time to support.
Nice day guys.
