### ISSUE TITLE
Error: Callback called more than once. (npm install)

### ISSUE THREAD

**Issue by jeffreytu** [npm/npm#10194] opened 2015-10-31 01:03 UTC
```
$ npm install mongoose --save

> kerberos@0.0.17 install c:\Users\username\Desktop\gh-projects\pass\passport-mongo\node_modules\kerberos
> (node-gyp rebuild) || (exit 0)

npm WARN install:kerberos kerberos@0.0.17 install: `(node-gyp rebuild) || (exit 0)`
npm WARN install:kerberos spawn C:\Program Files (x86)\Git\bin\sh.exe --login -i ENOENT
npm WARN install:kerberos kerberos@0.0.17 install: `(node-gyp rebuild) || (exit 0)`
npm WARN install:kerberos Exit status -4058
passport-mongo@0.0.0 c:\Users\username\Desktop\gh-projects\pass\passport-mongo
└─┬ mongoose@4.2.3
  ├── async@0.9.0
  ├── bson@0.4.19
  ├── hooks-fixed@1.1.0
  ├── kareem@1.0.1
  ├─┬ mongodb@2.0.46
  │ ├── es6-promise@2.1.1
  │ ├── mongodb-core@1.2.19
  │ └─┬ readable-stream@1.0.31
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  ├── mpath@0.1.1
  ├── mpromise@0.5.4
  ├─┬ mquery@1.6.3
  │ └── bluebird@2.9.26
  ├── ms@0.1.0
  ├── muri@1.0.0
  ├── regexp-clone@0.0.1
  └── sliced@0.0.5

passport-mongo@0.0.0 c:\Users\username\Desktop\gh-projects\pass\passport-mongo
└─┬ mongoose@4.2.3
  ├── async@0.9.0
  ├── bson@0.4.19
  ├── hooks-fixed@1.1.0
  ├── kareem@1.0.1
  ├─┬ mongodb@2.0.46
  │ ├── es6-promise@2.1.1
  │ ├── mongodb-core@1.2.19
  │ └─┬ readable-stream@1.0.31
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  ├── mpath@0.1.1
  ├── mpromise@0.5.4
  ├─┬ mquery@1.6.3
  │ └── bluebird@2.9.26
  ├── ms@0.1.0
  ├── muri@1.0.0
  ├── regexp-clone@0.0.1
  └── sliced@0.0.5

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mongoose" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\username\Desktop\gh-projects\pass\passport-mongo\npm-debug.log
```

Tried: updating node/npm, node cache clean, and uninstall/reinstalling node.

**Comment by vignesh555** [comment] 2015-11-11 02:53
Facing same issue on Ionic install

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "ionic" "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
npm ERR! code 1

**Comment by vignesh555** [comment] 2015-11-11 02:53
Any solution please let me know.

**Comment by BridgeAR** [comment] 2015-11-25 23:45
Likely a duplicate of #10322

**Comment by busches** [comment] 2016-09-18 23:55
@kenany now a duplicate as @bridgear mentioned

**Comment by KenanY** [comment] 2016-09-19 04:34
@busches I don't know, "callback called more than once" is a generic error message that usually indicates a bug in `npm` (and because of how generic it is, I don't think one can easily say that two issues with that message are the same without further investigation).

@jeffreytu Are you still seeing this issue with newer versions of `npm`?

**Comment by KenanY** [comment] 2016-09-26 14:01
Closing as abandoned.

**Closed by KenanY** 2016-09-26 14:01 UTC
