### ISSUE TITLE
can't install body-parser package with npm

### ISSUE THREAD

**Issue by terryZY** [npm/npm#12740] opened 2016-05-18 05:27 UTC
C:\Users\sidanor>npm install body-parser --save
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\sidanor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "body-parser" "--save"
npm ERR! node v4.4.3
npm ERR! npm  v3.9.0

npm ERR! shasum check failed for C:\Users\sidanor\AppData\Local\Temp\npm-2356-6f092ddc\registry.npmjs.org\iconv-lite-\iconv-lite-0.4.13.tgz
npm ERR! Expected: 1f88aba4ab0b1508e8312acc39345f36e992e2f2
npm ERR! Actual:   3101ba5b2b92e93532a2eb53d6dee03c52d5dd99
npm ERR! From:     https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.13.tgz

**Comment by terryZY** [comment] 2016-05-18 05:29
My computer system is Windows_10.

**Comment by KenanY** [comment] 2016-05-18 12:33
@terryZY Have you tried running `npm cache clean`?

**Comment by SumantThakur1993** [comment] 2016-05-19 11:40
Yes, I tried it but it was of no use as I am still getting this error

**Comment by zkat** [comment] 2016-12-09 00:41
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:41 UTC
Labels: shasum, support
