### ISSUE TITLE
Why are Github URLs always outdated?

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#8170] opened 2015-05-03 22:22 UTC
When I do a `npm outdated --depth=0` and have some Github URLs in the package.json, it always lists these as outdated, no matter if I installed these one second ago.

I think it shouldn't list these as outdated if the latest commit hash matches on both sides.

**Comment by smikes** [comment] 2015-05-03 23:12
Because `npm` doesn't know whether you are asking for a SHA, branch, or tag, it does not make any assumptions about whether it can safely reuse the cached contents of the git repository.  This may change in a (far future) version of `npm`, when the local cache is content-addressible, but for the moment, this behavior is fixed as part of the public interface of `npm`.

**Comment by othiym23** [comment] 2015-05-03 23:18
By "far future", @smikes means "possibly as soon as 2.10", although we should probably wait until `npm@3` is out the door. @iarna and I have had some discussions of how we want git dependencies to interact with `npm outdated` / `npm update` and `npm ls` / `npm install`, and the basic split is that the former touch the network as part of figuring out what's up to date with respect to git, while the latter just use what's already in the cache or installed.

**Comment by smikes** [comment] 2015-05-03 23:23
Oh, I didn't know that! I thought it was slated for npm@4.  That's pretty exciting.

**Comment by binarykitchen** [comment] 2015-05-03 23:27
@smikes well, you can indicate a tag to Github URLs by amending something like `#v0.1.3` at the end of the URL. In other words, if there is no `#`, then it always refers to master. This should be pretty straightforward I think.

**Comment by smikes** [comment] 2015-05-04 16:39
@binarykitchen Right, the problem though is that tags can be moved and branches implicitly move.  So the only git reference that's reliably immutable is a full SHA hash (or an abbreviation of one).  So the current behavior tries to avoid risk -- if the git reference **could** have changed, `npm` re-fetches it.  And in the past `npm` didn't know how to tell one kind of git reference from another...

However, changing how `npm` handles this is apparently already in the works.  As you can see, this issue has been tagged as `feature-request`.  When that feature goes into `npm`, you'll be notified.

**Comment by binarykitchen** [comment] 2015-05-04 21:29
Right, I understand.

Problem is that I run `npm outdated --depth=0` quite often and have lots of packages references with GitHub URLs which are already up to date but `npm outdated` still lists these. Exactly because of the reasons you mentioned.

Now, when you have i.E. 10 of them, then the `npm outdated` output becomes a bit difficult to scan with human eyes. That's the real problem I am having here ... Hence I'd very welcome this feature-request!

**Comment by jonathanong** [comment] 2015-05-18 23:54
> the basic split is that the former touch the network as part of figuring out what's up to date with respect to git, while the latter just use what's already in the cache or installed.

i'd rather have it always touch the network as long as the sha's do not match (i.e. always unless you know for sure that the dependency is up to date). if i put a different commit sha and type `npm install`, i expect it to be installed.

otherwise, i would always have to run `npm update` after `npm install` whenever `node_modules` is cached, which uses even more network requests.

**Comment by binarykitchen** [comment] 2015-05-19 08:56
amen to that @jonathanong

**Comment by othiym23** [comment] 2016-03-03 22:07
See #8300's most recent update from me for the CLI team's current thinking on this. We'd very much like to have better tracking of the up-to-date status of Git dependencies, but it's going to be a little while until we get to that. For now, I'm going to close this as a duplicate of #8300, but watch that issue for further progress. Thanks for your time!

**Closed by othiym23** 2016-03-03 22:07 UTC
Labels: feature-request
