### ISSUE TITLE
phonegap cant coming!

### ISSUE THREAD

**Issue by muhammedMoussa** [npm/npm#14119] opened 2016-09-29 03:32 UTC
```
`npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Muhammed\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\Muhammed\AppData\Local\Temp\npm-1104-9
d9857b0\registry.npmjs.org\connect-phonegap\-\connect-phonegap-0.23.1.tgz
npm ERR! Expected: 34263d0105c0158f979bb25a58b9117ae2bb6419
npm ERR! Actual:   34edd42c493c12e7346dd7017352de526967f23b
npm ERR! From:     https://registry.npmjs.org/connect-phonegap/-/connect-phonega
p-0.23.1.tgz`
```

**Comment by busches** [comment] 2016-10-05 18:44
Are you still receiving this issue? Looks like you just had a corrupt download. Running ` npm install connect-phonegap@0.23.1` installs the expected version using the latest `npm`.

**Comment by zkat** [comment] 2016-12-09 00:36
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:36 UTC
