### ISSUE TITLE
npm cordova error

### ISSUE THREAD

**Issue by mersenarabzadeh** [npm/npm#10293] opened 2015-11-06 13:33 UTC
Hey, I used new and old version of Node.js but still it's not working :(
Would anybody help me plz? Thanks a lot

---

I get this in CMD:

```
npm ERR! registry error parsing json
npm ERR! Error: shasum check failed for C:\Users\mersen\AppData\Local\Temp\npm-3
664-ulby15uD\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-worl
d-3.9.0.tgz
npm ERR! Expected: 5866d8fed5582686c68ec59a6d1097c4ec0fcc4b
npm ERR! Actual:   30178a5146f1388da1a127b09a1011690aa1d435
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-
app-hello-world-3.9.0.tgz
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.
js:38:8
npm ERR!     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm
\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\Users\mersen
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

---

this is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs1\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs1\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 verbose node symlink C:\Program Files\nodejs1\\node.exe
5 verbose cache add [ 'cordova', null ]
6 verbose cache add name=undefined spec="cordova" args=["cordova",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'cordova',
7 verbose parsed url   path: 'cordova',
7 verbose parsed url   href: 'cordova' }
8 silly lockFile a98f2055-cordova cordova
9 verbose lock cordova C:\Users\mersen\AppData\Roaming\npm-cache\a98f2055-cordova.lock
10 silly lockFile a98f2055-cordova cordova
11 silly lockFile a98f2055-cordova cordova
12 verbose addNamed [ 'cordova', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile de8d9fad-cordova cordova@
15 verbose lock cordova@ C:\Users\mersen\AppData\Roaming\npm-cache\de8d9fad-cordova.lock
16 silly addNameRange { name: 'cordova', range: '*', hasData: false }
17 verbose request where is /cordova
18 verbose request registry https://registry.npmjs.org/
19 verbose request id 8b16f17507061dda
20 verbose url raw /cordova
21 verbose url resolving [ 'https://registry.npmjs.org/', './cordova' ]
22 verbose url resolved https://registry.npmjs.org/cordova
23 verbose request where is https://registry.npmjs.org/cordova
24 info trying registry request attempt 1 at 16:56:59
25 http GET https://registry.npmjs.org/cordova
26 http 200 https://registry.npmjs.org/cordova
27 silly registry.get cb [ 200,
27 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
27 silly registry.get     etag: '"85E52TRU2EBHRE5GF706W6M0Q"',
27 silly registry.get     'content-type': 'application/json',
27 silly registry.get     'cache-control': 'max-age=60',
27 silly registry.get     'content-length': '363929',
27 silly registry.get     'accept-ranges': 'bytes',
27 silly registry.get     date: 'Fri, 06 Nov 2015 13:27:02 GMT',
27 silly registry.get     via: '1.1 varnish',
27 silly registry.get     age: '0',
27 silly registry.get     connection: 'keep-alive',
27 silly registry.get     'x-served-by': 'cache-lhr6325-LHR',
27 silly registry.get     'x-cache': 'HIT',
27 silly registry.get     'x-cache-hits': '1',
27 silly registry.get     'x-timer': 'S1446816422.622173,VS0,VE90',
27 silly registry.get     vary: 'Accept' } ]
28 silly addNameRange number 2 { name: 'cordova', range: '*', hasData: true }
29 silly addNameRange versions [ 'cordova',
29 silly addNameRange   [ '0.0.1',
29 silly addNameRange     '0.0.2',
29 silly addNameRange     '0.0.3',
29 silly addNameRange     '0.0.4',
29 silly addNameRange     '0.0.5',
29 silly addNameRange     '0.0.6',
29 silly addNameRange     '0.0.7',
29 silly addNameRange     '0.0.8',
29 silly addNameRange     '0.0.9',
29 silly addNameRange     '0.1.0',
29 silly addNameRange     '0.1.1',
29 silly addNameRange     '0.1.2',
29 silly addNameRange     '0.1.3',
29 silly addNameRange     '0.1.4',
29 silly addNameRange     '0.1.5',
29 silly addNameRange     '0.1.6',
29 silly addNameRange     '0.1.7',
29 silly addNameRange     '0.1.8',
29 silly addNameRange     '0.1.9',
29 silly addNameRange     '0.1.10',
29 silly addNameRange     '0.1.11',
29 silly addNameRange     '0.1.12',
29 silly addNameRange     '0.1.13',
29 silly addNameRange     '0.1.14',
29 silly addNameRange     '2.2.0',
29 silly addNameRange     '2.3.0',
29 silly addNameRange     '2.3.1',
29 silly addNameRange     '2.3.2',
29 silly addNameRange     '2.3.3',
29 silly addNameRange     '2.3.5',
29 silly addNameRange     '2.3.6',
29 silly addNameRange     '2.4.0',
29 silly addNameRange     '2.4.1',
29 silly addNameRange     '2.4.2',
29 silly addNameRange     '2.4.3',
29 silly addNameRange     '2.4.4',
29 silly addNameRange     '2.4.5',
29 silly addNameRange     '2.4.6',
29 silly addNameRange     '2.4.7',
29 silly addNameRange     '2.4.8',
29 silly addNameRange     '2.4.9',
29 silly addNameRange     '2.4.10',
29 silly addNameRange     '2.5.0',
29 silly addNameRange     '2.5.2',
29 silly addNameRange     '2.5.3',
29 silly addNameRange     '2.5.4',
29 silly addNameRange     '2.5.5',
29 silly addNameRange     '2.6.0',
29 silly addNameRange     '2.6.1',
29 silly addNameRange     '2.6.2',
29 silly addNameRange     '2.7.0-rc.1',
29 silly addNameRange     '2.7.1-rc.1',
29 silly addNameRange     '2.7.2',
29 silly addNameRange     '2.7.3',
29 silly addNameRange     '2.7.4',
29 silly addNameRange     '2.8.0',
29 silly addNameRange     '2.8.1',
29 silly addNameRange     '2.8.2',
29 silly addNameRange     '2.8.3',
29 silly addNameRange     '2.8.4',
29 silly addNameRange     '2.8.5',
29 silly addNameRange     '2.8.6',
29 silly addNameRange     '2.8.7',
29 silly addNameRange     '2.8.8',
29 silly addNameRange     '2.8.9',
29 silly addNameRange     '2.8.10',
29 silly addNameRange     '2.8.11',
29 silly addNameRange     '2.8.12',
29 silly addNameRange     '2.8.13',
29 silly addNameRange     '2.8.14',
29 silly addNameRange     '2.8.15',
29 silly addNameRange     '2.8.16',
29 silly addNameRange     '2.8.17',
29 silly addNameRange     '2.8.18',
29 silly addNameRange     '2.8.19',
29 silly addNameRange     '2.8.20',
29 silly addNameRange     '2.8.21',
29 silly addNameRange     '2.8.22',
29 silly addNameRange     '2.8.23',
29 silly addNameRange     '2.8.24',
29 silly addNameRange     '2.8.25',
29 silly addNameRange     '2.9.0',
29 silly addNameRange     '2.9.1',
29 silly addNameRange     '2.9.2',
29 silly addNameRange     '2.9.3',
29 silly addNameRange     '2.9.4',
29 silly addNameRange     '2.9.5',
29 silly addNameRange     '2.9.6',
29 silly addNameRange     '2.9.7',
29 silly addNameRange     '3.0.0-rc1',
29 silly addNameRange     '3.0.0-rc1-1',
29 silly addNameRange     '3.0.0-rc1-3',
29 silly addNameRange     '3.0.0',
29 silly addNameRange     '3.0.1',
29 silly addNameRange     '3.0.2',
29 silly addNameRange     '3.0.3',
29 silly addNameRange     '3.0.4',
29 silly addNameRange     '3.0.5',
29 silly addNameRange     '3.0.6',
29 silly addNameRange     '3.0.7',
29 silly addNameRange     '3.0.8',
29 silly addNameRange     '3.0.9',
29 silly addNameRange     '3.0.10',
29 silly addNameRange     '3.1.0-0.1.0',
29 silly addNameRange     '3.1.0-0.2.0',
29 silly addNameRange     '3.2.0-rc.1',
29 silly addNameRange     '3.2.0-0.1.0',
29 silly addNameRange     '3.2.0-0.2.0',
29 silly addNameRange     '3.2.0-0.3.0',
29 silly addNameRange     '3.2.0-0.4.0',
29 silly addNameRange     '3.3.0-rc.1',
29 silly addNameRange     '3.3.0-0.1.1',
29 silly addNameRange     '3.3.1-0.1.2',
29 silly addNameRange     '2.9.0-rc1',
29 silly addNameRange     '3.3.1-0.3.0',
29 silly addNameRange     '3.3.1-0.3.1',
29 silly addNameRange     '3.3.1-0.4.1',
29 silly addNameRange     '3.3.1-0.4.2',
29 silly addNameRange     '3.4.0-0.1.0',
29 silly addNameRange     '3.4.0-0.1.1',
29 silly addNameRange     '3.4.0-0.1.2',
29 silly addNameRange     '3.4.0-0.1.3',
29 silly addNameRange     '0.0.0-fake',
29 silly addNameRange     '3.4.1-0.1.0',
29 silly addNameRange     '3.5.0-0.2.0',
29 silly addNameRange     '3.5.0-0.2.1',
29 silly addNameRange     '3.5.0-0.2.2',
29 silly addNameRange     '3.5.0-0.2.3',
29 silly addNameRange     '3.5.0-0.2.4',
29 silly addNameRange     '3.5.0-0.2.6',
29 silly addNameRange     '3.5.0-0.2.7',
29 silly addNameRange     '3.6.0-0.2.8',
29 silly addNameRange     '3.6.0-0.2.9',
29 silly addNameRange     '3.6.1-0.2.10',
29 silly addNameRange     '3.6.3-0.2.11',
29 silly addNameRange     '3.6.3-0.2.12',
29 silly addNameRange     '3.6.3-0.2.13',
29 silly addNameRange     '4.0.0',
29 silly addNameRange     '4.0.1',
29 silly addNameRange     '4.1.0',
29 silly addNameRange     '4.1.1',
29 silly addNameRange     '4.1.2',
29 silly addNameRange     '4.1.3-nightly.2014.10.21',
29 silly addNameRange     '4.2.0',
29 silly addNameRange     '4.3.0',
29 silly addNameRange     '5.0.0',
29 silly addNameRange     '4.3.1',
29 silly addNameRange     '5.1.1',
29 silly addNameRange     '5.2.0',
29 silly addNameRange     '5.3.1',
29 silly addNameRange     '5.3.3' ] ]
30 verbose addNamed [ 'cordova', '5.3.3' ]
31 verbose addNamed [ '5.3.3', '5.3.3' ]
32 silly lockFile 32a3786c-cordova-5-3-3 cordova@5.3.3
33 verbose lock cordova@5.3.3 C:\Users\mersen\AppData\Roaming\npm-cache\32a3786c-cordova-5-3-3.lock
34 silly lockFile 30dc52a9-js-org-cordova-cordova-5-3-3-tgz https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
35 verbose lock https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz C:\Users\mersen\AppData\Roaming\npm-cache\30dc52a9-js-org-cordova-cordova-5-3-3-tgz.lock
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz',
36 verbose addRemoteTarball   'd8933ea57cf4d390a1c86d0b43def76f61fb4d76' ]
37 info retry fetch attempt 1 at 16:57:06
38 verbose fetch to= C:\Users\mersen\AppData\Local\Temp\npm-320-4TuYRDDc\registry.npmjs.org\cordova\-\cordova-5.3.3.tgz
39 http GET https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
40 http 200 https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
41 silly lockFile 30dc52a9-js-org-cordova-cordova-5-3-3-tgz https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
42 silly lockFile 30dc52a9-js-org-cordova-cordova-5-3-3-tgz https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
43 silly lockFile 32a3786c-cordova-5-3-3 cordova@5.3.3
44 silly lockFile 32a3786c-cordova-5-3-3 cordova@5.3.3
45 silly lockFile de8d9fad-cordova cordova@
46 silly lockFile de8d9fad-cordova cordova@
47 error Error: shasum check failed for C:\Users\mersen\AppData\Local\Temp\npm-320-4TuYRDDc\registry.npmjs.org\cordova\-\cordova-5.3.3.tgz
47 error Expected: d8933ea57cf4d390a1c86d0b43def76f61fb4d76
47 error Actual:   a725b8ed6116c26f13fcdc2b491fad32e54e25af
47 error From:     https://registry.npmjs.org/cordova/-/cordova-5.3.3.tgz
47 error     at C:\Program Files\nodejs1\node_modules\npm\node_modules\sha\index.js:38:8
47 error     at ReadStream.<anonymous> (C:\Program Files\nodejs1\node_modules\npm\node_modules\sha\index.js:85:7)
47 error     at ReadStream.emit (events.js:117:20)
47 error     at _stream_readable.js:944:16
47 error     at process._tickCallback (node.js:448:13)
48 error If you need help, you may report this *entire* log,
48 error including the npm and node versions, at:
48 error     <http://github.com/npm/npm/issues>
49 error System Windows_NT 6.1.7601
50 error command "C:\\Program Files\\nodejs1\\\\node.exe" "C:\\Program Files\\nodejs1\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
51 error cwd D:\ionic
52 error node -v v0.10.38
53 error npm -v 1.4.28
54 verbose exit [ 1, true ]
```

**Comment by mersenarabzadeh** [comment] 2015-11-07 20:07
I get this now:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchNamedPackageData cordova
9 silly mapToRegistry name cordova
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org.au/
12 silly mapToRegistry uri http://registry.npmjs.org.au/cordova
13 verbose request uri http://registry.npmjs.org.au/cordova
14 verbose request no auth needed
15 info attempt registry request try #1 at 23:32:39
16 verbose request id 247f468ff8f75c32
17 http request GET http://registry.npmjs.org.au/cordova
18 http 404 http://registry.npmjs.org.au/cordova
19 verbose bad json <html>
19 verbose bad json <head><title>404 Not Found</title></head>
19 verbose bad json <body bgcolor="white">
19 verbose bad json <center><h1>404 Not Found</h1></center>
19 verbose bad json <hr><center>nginx/1.4.6 (Ubuntu)</center>
19 verbose bad json </body>
19 verbose bad json </html>
20 error registry error parsing json
21 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
21 verbose headers   date: 'Sat, 07 Nov 2015 20:00:18 GMT',
21 verbose headers   'content-type': 'text/html; charset=utf-8',
21 verbose headers   'transfer-encoding': 'chunked',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'content-encoding': 'gzip' }
22 silly get cb [ 404,
22 silly get   { server: 'nginx/1.4.6 (Ubuntu)',
22 silly get     date: 'Sat, 07 Nov 2015 20:00:18 GMT',
22 silly get     'content-type': 'text/html; charset=utf-8',
22 silly get     'transfer-encoding': 'chunked',
22 silly get     connection: 'keep-alive',
22 silly get     'content-encoding': 'gzip' } ]
23 silly fetchPackageMetaData SyntaxError: Unexpected token <
23 silly fetchPackageMetaData <html>
23 silly fetchPackageMetaData <head><title>404 Not Found</title></head>
23 silly fetchPackageMetaData <body bgcolor="white">
23 silly fetchPackageMetaData <center><h1>404 Not Found</h1></center>
23 silly fetchPackageMetaData <hr><center>nginx/1.4.6 (Ubuntu)</center>
23 silly fetchPackageMetaData </body>
23 silly fetchPackageMetaData </html>
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData     at Object.parse (native)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
23 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:7
23 silly fetchPackageMetaData     at Gunzip.onEnd (zlib.js:227:5)
23 silly fetchPackageMetaData     at emitNone (events.js:72:20)
23 silly fetchPackageMetaData     at Gunzip.emit (events.js:166:7)
23 silly fetchPackageMetaData     at endReadableNT (_stream_readable.js:905:12)
23 silly fetchPackageMetaData     at doNTCallback2 (node.js:450:9)
23 silly fetchPackageMetaData     at process._tickCallback (node.js:364:17)
23 silly fetchPackageMetaData  error for cordova [SyntaxError: Unexpected token <
23 silly fetchPackageMetaData <html>
23 silly fetchPackageMetaData <head><title>404 Not Found</title></head>
23 silly fetchPackageMetaData <body bgcolor="white">
23 silly fetchPackageMetaData <center><h1>404 Not Found</h1></center>
23 silly fetchPackageMetaData <hr><center>nginx/1.4.6 (Ubuntu)</center>
23 silly fetchPackageMetaData </body>
23 silly fetchPackageMetaData </html>
23 silly fetchPackageMetaData ]
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Starting
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token <
29 verbose stack <html>
29 verbose stack <head><title>404 Not Found</title></head>
29 verbose stack <body bgcolor="white">
29 verbose stack <center><h1>404 Not Found</h1></center>
29 verbose stack <hr><center>nginx/1.4.6 (Ubuntu)</center>
29 verbose stack </body>
29 verbose stack </html>
29 verbose stack
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:7
29 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
29 verbose stack     at emitNone (events.js:72:20)
29 verbose stack     at Gunzip.emit (events.js:166:7)
29 verbose stack     at endReadableNT (_stream_readable.js:905:12)
29 verbose stack     at doNTCallback2 (node.js:450:9)
29 verbose stack     at process._tickCallback (node.js:364:17)
30 verbose cwd C:\Users\mersen
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
33 error node v5.0.0
34 error npm  v3.3.6
35 error Unexpected token <
35 error <html>
35 error <head><title>404 Not Found</title></head>
35 error <body bgcolor="white">
35 error <center><h1>404 Not Found</h1></center>
35 error <hr><center>nginx/1.4.6 (Ubuntu)</center>
35 error </body>
35 error </html>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by freed00m** [comment] 2015-11-27 08:47
I encountered the gzip error while back, my problem went away when I started to use LTS node Argon. There are now 2 branches, Stable and LongTermSupport, the 5.0.1 did raise the gzip error. Might be worth a shot to downgrade to LTS node.

**Comment by zkat** [comment] 2016-12-09 00:53
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:53 UTC
Labels: support
