### ISSUE TITLE
Not possible to install aws-sdk after update to npm 3.5.0

### ISSUE THREAD

**Issue by robertolos** [npm/npm#10565] opened 2015-11-26 11:23 UTC
After the last update to npm v3.5.0 the installation of aws-sdk fails with the following error:
````
roberto@asusnbk generator-jhipster]$ sudo npm install aws-sdk
npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "aws-sdk"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/generator-jhipster/npm-debug.log

````

**Comment by KenanY** [comment] 2015-11-26 17:30
Cannot reproduce on `npm@3.5.0` nor `npm@3.5.1`. Not sure how to troubleshoot this. Maybe the `npm-debug.log` contains more information? Can't tell much from just the error message.

**Comment by robertolos** [comment] 2015-11-26 17:35
I think might be related to generator-jhipster. Following the npm-debug.log
https://gist.github.com/robertolos/0d38be7c47a55fdee1dc

**Comment by ErisDS** [comment] 2015-12-02 03:27
Getting the same error when trying to install ghost, the error is reproducible with npm 3.5.0, but not 3.4.1

Error with npm 3.5.0:

```
 npm install ghost
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

> ghost@0.7.2 preinstall /Users/hannah/testing/npm3.5/node_modules/.staging/ghost-ac9bc6ad1b6062b87af96b9832058bf9
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/hannah/.nave/installed/0.10.25/bin/npm" "install" "semver"
npm ERR! node v0.10.25
npm ERR! npm  v3.5.0

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hannah/testing/npm3.5/node_modules/.staging/ghost-ac9bc6ad1b6062b87af96b9832058bf9/npm-debug.log
/Users/hannah/testing/npm3.5
```

No error with npm 3.4.1:

```
Hannahs-MacBook-Air ~/testing/npm3.4 $ npm install ghost
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

> ghost@0.7.2 preinstall /Users/hannah/testing/npm3.4/node_modules/.staging/ghost-4c03cfbdc5a3af357ba678696fbab71f
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

ghost@0.7.2 /Users/hannah/testing/npm3.4/node_modules/.staging/ghost-4c03cfbdc5a3af357ba678696fbab71f
└── semver@5.0.3 


> sqlite3@3.1.1 install /Users/hannah/testing/npm3.4/node_modules/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/hannah/testing/npm3.4/node_modules/ghost/node_modules/sqlite3/lib/binding/node-v11-darwin-x64/node_sqlite3.node" is installed via remote
/Users/hannah/testing/npm3.4
└─┬ ghost@0.7.2 
```

Gist of the full test: https://gist.github.com/ErisDS/9431f5dfef8556f310cd

**Comment by ErisDS** [comment] 2015-12-02 03:31
P.S. I'm not sure if it's more helpful to raise a brand new bug without mentioning packages, or if there's anything else I can do to help make tracking this down easier, but please let me know if there is.

**Comment by KenanY** [comment] 2016-06-29 01:31
@robertolos Are you still seeing this with the latest version of `npm`?

**Comment by robertolos** [comment] 2016-06-29 10:14
Hi @KenanY ,
No seems to work fine now.

**Comment by KenanY** [comment] 2016-06-29 15:17
Closing as resolved then :)

**Closed by KenanY** 2016-06-29 15:17 UTC
Labels: support
