### ISSUE TITLE
error install try fixed many way it cannot

### ISSUE THREAD

**Issue by Enuhad** [npm/npm#13191] opened 2016-06-27 09:45 UTC
```
76 error Windows_NT 6.1.7601
77 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic" "-g"
78 error node v6.2.2
79 error npm  v3.9.5
80 error shasum check failed for C:\Users\iCom\AppData\Local\Temp\npm-6100-6eb8c472\registry.npmjs.org\ionic\-\ionic-1.7.16.tgz
80 error Expected: aeff62ee70b10b1563d85b9d4ea7005640bbc584
80 error Actual:   712351e02cbbe0cfc95135424a09d110f649add5
80 error From:     http://registry.npmjs.org/ionic/-/ionic-1.7.16.tgz
81 error If you need help, you may report this error at:
81 error     <https://github.com/npm/npm/issues>
82 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment] 2016-06-27 13:24
@Enuhad Have you tried running `npm cache clean`?

**Comment by Enuhad** [comment] 2016-06-29 12:44
already tried it, but it 's cannot

**Comment by Gyvanna** [comment] 2016-07-26 09:55
Hello, I'm getting the same error while trying to install cordova and ionic: `>install cordova ionic -g`. 
@Enuhad , I have tried to clean cache as well, but it doesn't work. Any aditional suggestions? 
Thank you very much!

**Comment by zkat** [comment] 2016-12-09 00:40
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:40 UTC
Labels: shasum, support, windows
