### ISSUE TITLE
Warning "root" does not have permission to access the dev dir #454

### ISSUE THREAD

**Issue by cliveb** [npm/npm#7889] opened 2015-04-08 21:34 UTC
tjwebb opened this issue on Jun 7, 2014 - still open April 7, 2015
https://github.com/TooTallNate/node-gyp/issues/454

Appreciate help from node committers to find a solution.

**Comment by KenanY** [comment] 2015-04-08 21:35
Duplicate of https://github.com/npm/npm/issues/7888?

**Comment by othiym23** [comment] 2015-04-08 21:35
Yes.

**Closed by othiym23** 2015-04-08 21:35 UTC
