### ISSUE TITLE
Add option: npm install --from-lock-file

### ISSUE THREAD

**Issue by joeytwiddle** [npm/npm#18286] opened 2017-08-24 06:33 UTC
#### What's the feature?

When using the `--from-lockfile` argument, npm would ignore the `package.json` file and install the exact versions specified in `package-lock.json`

#### What problem is the feature intended to solve?

[Many](https://github.com/npm/npm/issues/16866) developers are [confused](https://github.com/npm/npm/issues/17979) about how to get a reproducable set of dependencies. This options would make it clear and easy. The suggestion has been raised a couple of times as `--lock` or [`--lock-file`](https://github.com/npm/npm/issues/17979#issuecomment-320962329) or [`--read-only`](https://github.com/npm/npm/issues/17979#issuecomment-321019996).

It would mean developers could leave version ranges in their `package.json`, making it easy for them to install and test new versions of dependencies, updating their `package-lock.json` file in the process.

It would not change the existing/historical behaviour of `npm install`.

#### Is the absence of this feature blocking you or your team? If so, how?

It's inconvenient, but we think we have a process now. We have removed all the version range markers (`^` and `~`) from our `package.json` file.

(If someone adds a new dependency without using `--save-exact` then will have to go in again and remove the default range marker.)

When we want to update the dependencies, we might [use](https://www.npmjs.com/package/updtr) [one](https://www.npmjs.com/package/npm-update) of [these](https://www.npmjs.com/package/npm-check-updates) [tools](https://www.npmjs.com/package/npm-upgrade).

#### Is this feature similar to an existing feature in another tool?

People have been arguing that most package managers adopt this behaviour by default. npm has its reasons why it doesn't want to do that. So making the behaviour available as an option is the next closest thing.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure, I could have a go!

----

I am interested to know whether npm maintainers think this is a good idea. Or if there is already a good way to do reproducable deployments.

**Comment by novemberborn** [comment] 2017-08-24 13:06
If this would work without the `package.json` file being present then it'd be a great fit for Docker builds. You could copy the `package-lock.json` and install it, and only then copy remaining files. The dependencies would be their own layer and would not need to be reinstalled whenever source code changes.

**Comment by vovacodes** [comment] 2017-08-29 12:07
This option would totally make sense to me. Version ranges are handy for receiving security updates and bug fixes to the dependencies when developing the app, but on the CI I would like to use exactly the same versions of the deps I was using during development (having reproducible CI build). The fact that people are forced to use pinned dependency versions if they want to get a reproducible build makes the whole platform less secure and robust, so a huge support for the `--from-lock-file` option from me, I believe it is essential!

**Comment by wulfsberg** [comment] 2017-09-05 19:55
If you haven't changed the package.json, the lock file should give you consistent versions, even if your package.json has ranges. That is how the lock file is supposed to work, and if it doesn't, that's flat out a bug: https://github.com/npm/npm/issues/17979#issuecomment-326712196 point 4.

If you *do* change the package.json, but to something where the lock file version is still a valid resolution, I'd say it *should* give you what is in the lock file, but I don't know if it is supposed to do that, or if *any* change to the package.json triggers a complete re-evaluation of ranges. @zkat, can you clarify that?

**Comment by joeytwiddle** [comment] 2017-09-13 03:42
Thanks wulfsberg. It seems that the problem I was encountering before has now been fixed (I checked against npm 5.4.1).

That makes this feature less necessary, at least for me.

The comment you linked to also says that npm devs are trying to reduce the configurability of `npm`, to reduce its complexity, and that `cipm` might be the recommended way to get a reproducable build in future.

For those reasons, I think we can close this issue, if there are no objections.

**Comment by HipsterZipster** [comment] 2017-09-29 03:38
for enterprise scenarios that are more concerned with reliability and reproducibility, it's a deal breaker that npm doesn't have this. Yarn does. there's no reason why we shouldn't be able to reproduce the entire package tree.

**Comment by zkat** [comment] 2017-09-29 05:08
this is already on the way. Hang in there a bit while we get it out the door. It's what we're working on right now.

**Comment by callumlocke** [comment] 2017-11-02 13:10
Any progress on this? Do we know what the flag will be called?

**Comment by alexkreidler** [comment] 2017-11-25 16:23
Yarn already has this. This inconsistency in NPM is one of the main reasons I'm not using npm@5 now.

**Comment by broncha** [comment] 2017-11-27 19:47
I dont understand why `npm install` should update the lock file!! That defeats the entire purpose of the lock file!

**Comment by wulfsberg** [comment] 2017-11-27 21:33
@broncha Because the package.json describes the required dependencies of your project. If the current lock file cannot satisfy those, the lock file has to yield. The purpose of the lockfile is to create a repeatable installation across different machines, not to obsolete the package.json.

**Comment by zkat** [comment] 2017-11-27 21:37
It'll probably be called `npm ci`, which will include other CI-specific things and optimizations. You can try out the early alpha version by doing `npx cipm` in your project.

**Comment by Andarist** [comment] 2017-12-01 09:38
@zkat what is a purpose of the lock? I literally cannot find info about this, because there are so many issues with confused people and by reading https://docs.npmjs.com/files/package-lock.json I have no idea why the lock is changing.

I'm just curious what's the reasoning and what it does on technical level.

**Comment by broncha** [comment] 2017-12-01 09:43
@wulfsberg coming from composer from PHP land, this sounds a bit off to me. When I run `npm install <package>` in my development environment, it goes over the dependencies and writes the lock file. That is fine.
I push the lock file over to scm, pull it in server, and run `npm install`, that should not touch the lock file. If any dependencies cannot be resolved, it should complain about it.

**Comment by broncha** [comment] 2017-12-01 09:45
@wulfsberg What you intend to explain, was not actually what I meant in my comment! :)
I know if new dependencies are added, npm needs to update the lock file. That is how things work. But an up-to-date lock file is also updated. See my comment above.

**Comment by novemberborn** [comment] 2017-12-01 16:48
The lock file might also change due to improvements in npm itself, even if the dependencies haven't changed. This would be an issue if team members use different npm versions. As npm@5 stabilizes further I'd expect those occurrences to decrease.

**Comment by zefj** [comment] 2017-12-08 16:33
@wulfsberg I think this entire package-lock.json thing is a huge misunderstanding and a big source of confusion. Here's how our latest bug went:

package.json:
```
    "react-scroll": "^1.5.2",
```

package-lock.json
```
    "react-scroll": {
      "version": "1.6.7",
      "resolved": "https://registry.npmjs.org/react-scroll/-/react-scroll-1.6.7.tgz",
      ...
    },
```
And it actually installed 1.6.7 on my local env while I was developing the feature, needless to say it worked perfectly even despite the minor release was already different than what was stated in `package.json` - hence why I did not update it in the first place, I saw a lockfile, tested that everything worked, and just moved on. But some time later when it came to deployment, we ran `npm install` on our build server and despite the lockfile saying `1.6.7`, the actual version installed was `1.7.x` - which includes a breaking change. Suddenly the production app is broken.

So please explain to me how this helps in ensuring reproducible installs, because from my experience this seems to be completely useless. Why does it say `1.6.7` if it installs `1.7.x` in the end? To me, `1.6.7` in a file with `lock` in it's name pretty clearly implies the exact version that will be installed, but npm chooses to completely disregard it instead, so what is even going on? I understand my package.json allows `1.x.x`, but with the introduction of lockfiles this should very naturally transition into carrying information for a developer - if you remove the lockfile, the version will get bumped (if update is available), otherwise whatever the lockfile says stands. If that's not the case, what's the point of the lockfile anyway, when literally any semver range exposes you to possible bugs? So the only solution to reproducible installs seems to be pinning the exact version of each of your dependencies (80, in our case)... but then the lockfile becomes obsolete, because the `package.json` itself would already yield the same dependency tree every time (at least at the root level, but that's the only thing we care most of the time really).

I have yet to hear a single sensible argument or explanation as to why this cannot work this way. I might be missing something, but I don't understand how calculating the final dependency tree based on two files is easier/better than just relying on one source of information at a time. `package-lock.json` present? Install accordingly, otherwise use `package.json` and generate a new lockfile. Dead simple.

Not to mention the docs are outright lying:

> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on.

**Comment by wulfsberg** [comment] 2017-12-08 18:47
@zefj If the versions in the lock file can satisfy the requirements of the package.json, they should be used as-is.
If they don't, that's simply a bug which, as you say, completely undermines what the lock file is for.

What I disagree with is that the lock file should *always* take precedence over the package.json. The way I see it, the package.json is the authoritative requirements, and the lock file is subordinate to that. If the lock file cannot satisfy the requirements, it *has* to be updated, one way or another. Otherwise, you have essentially invented a new package manager which just happens to understand and auto-convert a legacy (package.json) format.

**Comment by zkat** [comment] 2017-12-08 21:21
as @wulfsberg says: if your lockfile says `1.6.7`, that's what you should see in that position in `node_modules/`. Please note that both `1.6.7` and `1.7.0` satisfy `^1.5.2`. Semver-minor versions are not considered breaking, and if 1.6 -> 1.7 included a breaking change, that's an issue with the package, and should be corrected. You can use `~1.5.2` in the meantime to prevent it from crossing the `1.5.x` series.

If you have a repro for that issue where the lockfile says one thing and node_modules has another, please post it.

As far as the larger issue goes: our experience was that having `package-lock.json` completely override `package.json` turned out to be very confusing for people (I'd argue _more_ confusing than things described here), and was kind of a UX nightmare. We have a solution coming for preventing _updates_ from happening during install, but it'll be a separate thing.

Reproducibility-wise, we're going to go a bit further with our guarantees: We're going to make it so that doing `npm install && npm pack` in a package on two different machines not only results in the same `node_modules`, but the resulting tarball will have _the exact same hash_. This is, of course, dependent on random run-scripts not doing time- or platform-dependent modifications, but the goal is to make it _possible_ to guarantee truly reproducible builds. Keep an eye out for that, since it's coming very soon. Cheers :)

**Comment by zefj** [comment] 2017-12-11 08:40
@zkat My bad, our npm versions dropped back to 3.10.10 and I did not notice that. Sorry.

**Comment by hobbs** [comment] 2018-01-17 00:34
While we wait for this, are there any known workarounds for this besides a mass-update to the `pakage.json` file?

**Comment by HipsterZipster** [comment] 2018-01-23 14:32
Any updates here @zkat ?

**Comment by broncha** [comment] 2018-01-23 15:24
> What I disagree with is that the lock file should always take precedence over the package.json. The way I see it, the package.json is the authoritative requirements, and the lock file is subordinate to that. If the lock file cannot satisfy the requirements, it has to be updated, one way or another. Otherwise, you have essentially invented a new package manager which just happens to understand and auto-convert a legacy (package.json) format.

@wulfsberg If lock file cannot satisfy the requirements, then there is a bug in npm. Lock file should always always be updated by npm, and dependencies should be properly updated in lock file. A version of lock file should always be enough to install dependencies. There should not be a question about lock file not satisfying the dependencies. In production/deployments servers, if packages depend on any global packages which are not installed, npm should complain.

**Comment by titocr** [comment] 2018-01-24 22:24
> Semver-minor versions are not considered breaking, and if 1.6 -> 1.7 included a breaking change, that's an issue with the package, and should be corrected.

True. And it's a lame excuse when I code something that breaks in QA, or god-forbid production, because some downstream dependency did something they shouldn't've. Is this a disconnect between the fast-churning node ecosystem and the world of enterprise software engineering? The build for a particular version or release has to be entirely consistent and reproducible. Maybe this feature was just poorly named. It seems like an extension of "npm ls".

(edited out less than constructive phrasing)

**Comment by sbkpilot1** [comment] 2018-02-12 19:40
bit confused about this whole lock file thing.. if there is no --use-lock switch then how exactly do you install based on a lock file?  I don't get it.  Here is what we want to do:

- in development we use package.json with the semver range versioning.  This pulls down the latest and updates the lock file.  We always check in the lock file to our source control so we have the snapshot of the latest update.  Works well.
- We reach a stage in development close to production that we decide to lock down the dependencies and not pull new versions going forward.  We do a final npm install --save to update package.json and package-lock.json, perform our sanity tests and determine that is the snapshot for both dev and our upcoming prod release.
- Now *in development* if we need to do a complete npm install again we need to use the lock file not package.json as that will not install dependencies based on the snapshot.
- After our prod release is complete and the next sprint starts we will go back to using package.json and pulling down latest versions as needed.

My question - the facility to install based on the lock file is mandatory otherwise the lock file makes no sense at all.  It's very purpose is to provide a way to install dependencies based on an exact snapshot.

I arrived at this thread in my search for a --use-lock switch that appears to not even exist so I am wondering how one can even use the lock file.

**Comment by zkat** [comment] 2018-02-13 02:20
We're landing `npm ci` this week. You can try the version in the canary -right now- by doing `$ npx npmc ci`.

**Comment by novemberborn** [comment] 2018-02-13 11:08
> I am wondering how one can even use the lock file.

The lock file is used by default. It's just that if you modify dependencies in `package.json` *those* changes will get installed instead, and the lock file will be updated. Assuming you commit the lock file you should notice it changing and can revert those changes if necessary.

If I understand it correctly, `npm ci` will *only* use the lock file and disregard the `package.json`. It's more useful in, well, CI, and when building Docker images. You'd still want to use `npm install` for local development.

**Comment by wiedikerli** [comment] 2018-02-14 10:19
@zkat i've tried this command. We get an error saying the version is invalid.
***package.json:*** `"@angular/animations": "^4.4.4"`
***package-lock.json:*** `"@angular/animations": "4.4.3"`

We also tried to change the version in the package.json to `4.4.3` but still the same error.

**Comment by trickpattyFH20** [comment] 2018-03-06 21:39
my lockfile is still changing after running `npm i` even when I have not changed any versions in package.json.

the lockfile should not change if I have not changed any versions in package.json. npm should just install the versions that are currently in the lockfile

**Comment by jcrben** [comment] 2018-04-04 22:10
We can close this right?

I'm wondering about the proper what to update only a single dependency.

**Comment by zkat** [comment] 2018-04-04 22:19
yup, this is closable. Cheers.

**Closed as completed by zkat** 2018-04-04 22:19 UTC
