### ISSUE TITLE
Incorrect version of vfile cached on npm servers

### ISSUE THREAD

**Issue by geek** [npm/npm#11234] opened 2016-01-21 19:31 UTC
``` sh
$ npm install vfile
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/.nvm/versions/node/v5.4.1/bin/node" "/Users/.nvm/versions/node/v5.4.1/bin/npm" "install" "vfile"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/vb/gnnlw81500xbv1j4cd9ynfv40000gn/T/npm-9325-de393100/registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
npm ERR! Expected: d272e8bb5c4adc196e6181515534ff57bfe2944f
npm ERR! Actual:   ffc1b808f0d5950e0a77bbb9c477f935324aadb0
npm ERR! From:     https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
```

Now if I wget the version and shasum it, depending on the way the wind blows its correct (seems like a caching issue on the npm servers).

``` sh
$ wget https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
--2016-01-21 13:24:56--  https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
Resolving registry.npmjs.org... 23.235.40.162
Connecting to registry.npmjs.org|23.235.40.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8990 (8.8K) [application/octet-stream]
Saving to: 'vfile-1.3.0.tgz'

vfile-1.3.0.tgz                                                                 100%[=======================================================================================================================================================================================================>]   8.78K  --.-KB/s   in 0s

2016-01-21 13:24:56 (114 MB/s) - 'vfile-1.3.0.tgz' saved [8990/8990]
```

``` sh
$ shasum vfile-1.3.0.tgz
ffc1b808f0d5950e0a77bbb9c477f935324aadb0  vfile-1.3.0.tgz
```

Remove that

``` sh
$ rm vfile-1.3.0.tgz
```

If we try again, we get a different response.

``` sh
$ wget https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
--2016-01-21 13:29:00--  https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
Resolving registry.npmjs.org... 23.235.44.162
Connecting to registry.npmjs.org|23.235.44.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8991 (8.8K) [application/octet-stream]
Saving to: 'vfile-1.3.0.tgz'

vfile-1.3.0.tgz                                                                 100%[=======================================================================================================================================================================================================>]   8.78K  --.-KB/s   in 0s

2016-01-21 13:29:01 (179 MB/s) - 'vfile-1.3.0.tgz' saved [8991/8991]
```

``` sh
$ shasum vfile-1.3.0.tgz
d272e8bb5c4adc196e6181515534ff57bfe2944f  vfile-1.3.0.tgz
```

The correct version is on 23.235.44.162 and a bad version is served from 23.235.40.162

Related issue logged: https://github.com/wooorm/vfile/issues/4

**Comment by wooorm** [comment] 2016-01-21 21:24
thanks for issuing this, @geek. Here’s some more information.

I’ve recently started adding “npm deployment” to Travis, meaning, Travis publishes a certain module iff it successfully build. Sounds great, work pretty great, except for two cases. This is the second, which broke everything, but a week ago I had what seems to be the same problem (but maybe not), namely, broken checksums. It *may* have to do with the fact that all my Travis node versions try to publish to npm, and, which ever comes first, wins (node 0.10, 0.11, 0.12, 4.0, 5.0, and iojs).

The Travis build in question for VFile can be found [here](https://travis-ci.org/wooorm/vfile/builds/103903331), whereas the seemingly similar failure for `quotation` can be found [here](https://travis-ci.org/wooorm/vfile/builds/103931633). There is however some difference between the two, for example, the VFile problem has one actual failure (namely, iojs), a [malformed token (on 0.10)](https://travis-ci.org/wooorm/vfile/jobs/103903332) error, and a [shasum error (on io.js v3.3.1)](https://travis-ci.org/wooorm/vfile/jobs/103903337) (probably ’cause of a recursive dependency).

Hope this helps, please let me know if I can provide more info! :smile:

**Comment by wooorm** [comment] 2016-01-24 08:43
It occurred again, this time with another [package](https://travis-ci.org/wooorm/unified/builds/104405756). I also did some digging into the first package, quotation, and think I’ve detected the culprit:

* Each time, Node 0.10 finishes first. For some reason, node@0.10 (with npm@1.4.29) cannot publish modules with the token given by travis,  and throws an error:

   ```
   ...
   publish Failed PUT 500
   npm ERR! Error: malformed token : quotation
   ...
   ```

   ([quotation](https://travis-ci.org/wooorm/quotation/jobs/102339975), [unified](https://travis-ci.org/wooorm/unified/jobs/104405757), [vfile](https://travis-ci.org/wooorm/vfile/jobs/103903332)).

*   Then, another build finishes and publishes the package A-OK: [vfile, at node@0.11.16 and npm@2.3.0](https://travis-ci.org/wooorm/vfile/jobs/103903333); [unified, at node@0.11.16 and npm@2.3.0](https://travis-ci.org/wooorm/unified/jobs/104405758); [quotation, at node@0.11.16 and npm@2.3.0](https://travis-ci.org/wooorm/quotation/jobs/102339976).

*   Now, that seemed to go ok, but didn’t. As can be seen from vfile and unified (which both depend on themselves deep down) as they fail when trying to download themselves ([unified](https://travis-ci.org/wooorm/unified/builds/104405756), [vfile](https://travis-ci.org/wooorm/vfile/builds/103903331)).

Hope that helps!

**Comment by zkat** [comment] 2016-12-09 00:48
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:48 UTC
