### ISSUE TITLE
shasum check failed for /var/folders/w3/nvln7hkd3wz0q7s9wwy8dd1w0000gn/T/npm-85484-a3528ede/registry.npmjs.org/appium/-/appium-1.6.5.tgz

### ISSUE THREAD

**Issue by yangheng** [npm/npm#18523] opened 2017-09-14 07:38 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### Now npm install appium faild ,but other package all successed. I had tried on three Mac computer and all the same. however，appium installed success two days before. the log is below :
```
npm install appium@1.6.5 -g
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "appium@1.6.5" "-g"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! shasum check failed for /var/folders/w3/nvln7hkd3wz0q7s9wwy8dd1w0000gn/T/npm-87684-01b36fae/registry.npmjs.org/appium/-/appium-1.6.5.tgz
npm ERR! Expected: cab50da890e9d2df9a25178fb1a8d802bf5c81e3
npm ERR! Actual:   4843e5aafd17b7e71b9973307d8d6532d4aca338
npm ERR! From:     https://registry.npmjs.org/appium/-/appium-1.6.5.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kukuchong/.npm/_logs/2017-09-14T07_23_38_973Z-debug.log

```

### supporting information:

 - `npm -v` prints:v4.2.0
 - `node -v` prints:v7.9.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-09-14 14:31
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by yangheng** [comment] 2017-09-15 02:18
Thank you ! Now all is OK

**Comment by kenany** [comment] 2017-09-27 12:03
Closing as resolved.

**Closed as completed by kenany** 2017-09-27 12:03 UTC
Labels: support, shasum
