### ISSUE TITLE
Err Windows_NT  10.0.10586 V6.3.1 -X64

### ISSUE THREAD

**Issue by rullymartanto** [npm/npm#13583] opened 2016-08-05 04:19 UTC
Hi Guys,

I git this err,.. Any body can help ?

Thanks

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\XXXX~1\AppData\Local\Temp\npm-9560-e1be6dbc\registry.npmjs.org\gulp-rtlcss\-\gulp-rtlcss-1.0.0.tgz.1316194217' -> 'C:\Users\RULLYM~1\AppData\Local\Temp\npm-9560-e1be6dbc\registry.npmjs.org\gulp-rtlcss\-\gulp-rtlcss-1.0.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\XXXXX~1\AppData\Local\Temp\npm-9560-e1be6dbc\registry.npmjs.org\gulp-chmod\-\gulp-chmod-1.3.0.tgz.2011504085' -> 'C:\Users\RULLYM~1\AppData\Local\Temp\npm-9560-e1be6dbc\registry.npmjs.org\gulp-chmod\-\gulp-chmod-1.3.0.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
```

**Comment by Astro533** [comment] 2016-08-05 21:17
I'm getting that error too but don't know how to fix

**Comment by durairajv** [comment] 2016-08-09 17:30
I am getting the same error when i try to install ember.. I tried rebooting multiple times,  reinstalled node , did npm cache clean still the issue persists. Please someone help

**Comment by othiym23** [comment] 2016-08-19 22:39
```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\XXXX~1\AppData\Local\Temp\npm-9560-e1be6dbc\registry.npmjs.org\gulp-rtlcss\-\gulp-rtlcss-1.0.0.tgz.1316194217' -> 'C:\Users\RULLYM~1\AppData\Local\Temp\npm-9560-e1be6dbc\registry.npmjs.org\gulp-rtlcss\-\gulp-rtlcss-1.0.0.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:39 UTC
Labels: support, windows

**Comment by shaozhiqi** [comment] 2016-08-31 02:28
I want to know how to fix ?
