### ISSUE TITLE
A weird one in the middle of node-bin

### ISSUE THREAD

**Issue by aredridel** [npm/npm#10714] opened 2015-12-06 03:53 UTC
```
:; npm i --save --save-exact --save-bundle node-darwin-x64
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/lib/node_modules/node-darwin-x64/bin/node" "/usr/local/bin/npm" "i" "--save" "--save-exact" "--save-bundle" "node-darwin-x64"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aredridel/Projects/t/npm-debug.log
```

debug log at https://gist.github.com/aredridel/54df50fde6dd0bc06700

**Comment by othiym23** [comment] 2015-12-07 16:39
I have a patch underway for this, but it needs tests that are particularly tricky to write, and probably an extraction of some tricky logic to properly address the underlying bug. The circumstances under which you encounter this bug are pretty constrained, too, because it requires a semver range in `package.json` and prerelease versions, which cause different parts of npm to come to different conclusions about which version should be cached and installed.

**Comment by othiym23** [comment] 2015-12-07 16:42
Closing as duplicate of #10686.

**Closed by othiym23** 2015-12-07 16:42 UTC
