### ISSUE TITLE
npm install grunt-contrib-nodeunit --save-dev

### ISSUE THREAD

**Issue by Guxingzhe** [npm/npm#15166] opened 2016-12-08 07:32 UTC
#### What's going wrong?
D:\workspace\nodejs\helloworld>npm install grunt-contrib-nodeunit --save-dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-contrib-nodeunit" "--save-d
ev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-6888-8
e957af8\registry.npmjs.org\nyc\-\nyc-7.1.0.tgz
npm ERR! Expected: 8e14971f3a15d1abbec7ac610ef54cb889e9ffb4
npm ERR! Actual:   50a2297e4fe343784ccdea9fe9427256be73f3a4
npm ERR! From:     https://registry.npmjs.org/nyc/-/nyc-7.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\nodejs\helloworld\npm-debug.log

**Comment by zkat** [comment] 2016-12-09 00:31
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:31 UTC
Labels: shasum

**Comment by Guxingzhe** [comment] 2016-12-09 02:22
My solution:
## 
npm install cnpm -g --registry=https://registry.npm.taobao.org
##
D:\workspace\nodejs\bower\hellbower>cnpm install -g bower
Downloading bower to C:\Users\Administrator\AppData\Roaming\npm\node_modules\bow
er_tmp
Copying C:\Users\Administrator\AppData\Roaming\npm\node_modules\bower_tmp\.1.8.0
@bower to C:\Users\Administrator\AppData\Roaming\npm\node_modules\bower
Installing bower's dependencies to C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\bower/node_modules
All packages installed (use 45ms, speed 0B/s, json 0(0B), tarball 0B)
[bower@1.8.0] link C:\Users\Administrator\AppData\Roaming\npm\bower@ -> C:\Users
\Administrator\AppData\Roaming\npm\node_modules\bower\bin\bower

**Comment by Guxingzhe** [comment] 2016-12-09 02:27
My solution:
##
D:\workspace\nodejs\helloworld>npm install cnpm -g --registry=https://registry.n
pm.taobao.org
##
D:\workspace\nodejs\helloworld>cnpm install grunt-contrib-nodeunit --save-dev
deprecate grunt-contrib-nodeunit@1.0.0 › nodeunit@0.9.5 › tap@7.1.2 › coveralls@
2.11.15 › request@2.75.0 › node-uuid@1.4.7 use uuid module instead
√ All packages installed (118 packages installed from npm registry, use 37s, sp
eed 150.29kB/s, json 132(854.33kB), tarball 4.6MB)
Recently updated (since 2016-12-02): 2 packages (detail see file D:\workspace\no
dejs\helloworld\node_modules\.recently_updates.txt)
