### ISSUE TITLE
Unable to Install Angular CLI in Mac (OSX Mavericks) 

### ISSUE THREAD

**Issue by ziszo** [npm/npm#14095] opened 2016-09-27 13:22 UTC
#### I'm opening this issue because:

  - [ ] can't install Angular CLI.
  - [ ] npm is doing something I don't understand.

#### VERSIONS
OSX Mavericks
node v6.6.0
npm v3.10.8

#### What's going wrong?

> 598 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/index.js
> 129599 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/license
> 129600 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/readme.md
> 129601 silly gentlyRm /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules is being purged
> 129602 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules
> 129603 silly vacuum-fs purging /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules
> 129604 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/.staging/npm-697dfe0f
> 129605 silly gentlyRm /usr/local/lib/node_modules/.staging/bower-f5744e65/node_modules is being purged
> 129606 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/bower-f5744e65/node_modules
> 129607 verbose unlock done using /Users/roland/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
> 129608 silly rollbackFailedOptional Starting
> 129609 silly rollbackFailedOptional Finishing
> 129610 silly runTopLevelLifecycles Starting
> 129611 silly runTopLevelLifecycles Finishing
> 129612 silly install printInstalled
> 129613 verbose stack Error: Invalid name: "@angular/tsc-wrapped"
> 129613 verbose stack at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
> 129613 verbose stack at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
> 129613 verbose stack at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
> 129613 verbose stack at Array.forEach (native)
> 129613 verbose stack at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
> 129613 verbose stack at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
> 129613 verbose stack at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
> 129613 verbose stack at ReadFileContext. (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
> 129613 verbose stack at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
> 129613 verbose stack at FSReqWrap.readFileAfterOpen as oncomplete
> 129614 verbose cwd /Users/roland
> 129615 error Darwin 13.4.0
> 129616 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
> 129617 error node v6.6.0
> 129618 error npm v3.10.3
> 129619 error Invalid name: "@angular/tsc-wrapped"
> 129620 error If you need help, you may report this error at:
> 129620 error https://github.com/npm/npm/issues
> 129621 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?

**Comment by ziszo** [comment] 2016-09-27 13:24
598 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/index.js
129599 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/license
129600 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/readme.md
129601 silly gentlyRm /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules is being purged
129602 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules
129603 silly vacuum-fs purging /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules
129604 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/.staging/npm-697dfe0f
129605 silly gentlyRm /usr/local/lib/node_modules/.staging/bower-f5744e65/node_modules is being purged
129606 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/bower-f5744e65/node_modules
129607 verbose unlock done using /Users/roland/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
129608 silly rollbackFailedOptional Starting
129609 silly rollbackFailedOptional Finishing
129610 silly runTopLevelLifecycles Starting
129611 silly runTopLevelLifecycles Finishing
129612 silly install printInstalled
129613 verbose stack Error: Invalid name: "@angular/tsc-wrapped"
129613 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
129613 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
129613 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
129613 verbose stack     at Array.forEach (native)
129613 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
129613 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
129613 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
129613 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
129613 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
129613 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
129614 verbose cwd /Users/roland
129615 error Darwin 13.4.0
129616 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
129617 error node v6.6.0
129618 error npm  v3.10.3
129619 error Invalid name: "@angular/tsc-wrapped"
129620 error If you need help, you may report this error at:
129620 error     <https://github.com/npm/npm/issues>
129621 verbose exit [ 1, true ]

**Comment by ziszo** [comment] 2016-09-27 13:26
Tried to force install as said by CanKer in #2161

> npm install -g -f angular-cli

but got the following errors:

> uid must be an unsigned int
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> npm ERR! Darwin 13.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "-f" "angular-cli"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.8
> npm ERR! uid must be an unsigned int

**Comment by ziszo** [comment] 2016-09-27 13:37
99209 verbose stack TypeError: uid must be an unsigned int
99209 verbose stack     at TypeError (native)
99209 verbose stack     at Object.fs.chown (fs.js:1190:11)
99209 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
99209 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
99209 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
99209 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
99209 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
99209 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
99210 verbose cwd /Users/roland
99211 error Darwin 13.4.0
99212 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "-f" "angular-cli"
99213 error node v6.6.0
99214 error npm  v3.10.8
99215 error uid must be an unsigned int
99216 error If you need help, you may report this error at:
99216 error     <https://github.com/npm/npm/issues>
99217 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2016-09-27 18:14
@ziszo Your latest error looks like a duplicate of https://github.com/npm/npm/issues/13918.

**Comment by ziszo** [comment] 2016-09-28 10:07
Thank you, @KenanY.

**Closed** 2016-09-28 11:15 UTC
