### ISSUE TITLE
npm install some package can not work successful(updated npm 3.10.8)

### ISSUE THREAD

**Issue by demopark** [npm/npm#14122] opened 2016-09-29 09:31 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
install node package. for example: ionic 2.1.0, yo.....

Err:   uid must be an unsigned int

#### How can the CLI team reproduce the problem?

install node.js pkg with 4.6.0

update npm to 3.10.8 with command:
sudo npm install npm -g

then command line:
sudo npm install -g ionic
ro
sudo npm install -g yo

issues happend~

### supporting information:

 - `npm -v` prints:3.10.8
 - `node -v` prints:v4.6.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X, or Linux?: macOS 10.12
 - `npm log` prints:
sudo npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jonas/npm-debug.log

----
ro
----

...
npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
....

**Comment by KenanY** [comment] 2016-09-29 14:19
Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-29 14:19 UTC
