### ISSUE TITLE
Not able to install Laravel and AngularJS Starter Application on ubuntu

### ISSUE THREAD

**Issue by Triusinfotech** [npm/npm#11543] opened 2016-02-15 20:04 UTC
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.1.66
3 info using node@v0.8.15
4 verbose read json /var/www/html/jatin-laravel/package.json
5 error install Couldn't read dependencies
6 error Error: ENOENT, open '/var/www/html/jatin-laravel/package.json'
7 error If you need help, you may report this log at:
7 error     <http://github.com/isaacs/npm/issues>
7 error or email it to:
7 error     <npm-@googlegroups.com>
8 error System Linux 3.13.0-32-generic
9 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
10 error cwd /var/www/html/jatin-laravel
11 error node -v v0.8.15
12 error npm -v 1.1.66
13 error path /var/www/html/jatin-laravel/package.json
14 error code ENOENT
15 error errno 34
16 verbose exit [ 34, true ]

**Comment by KenanY** [comment] 2016-02-15 20:37
Hi @Triusinfotech! `npm@1.1.66` is years old by now and has not been supported for quite some time. While your error does not look like something that an outdated `npm` installation would cause, I will nonetheless implore that you update **both** [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) before requesting support, since literally hundreds of bugs have been fixed over the years. For completeness sake, I'll add that the error you are receiving is usually caused by running `npm install` in a directory which does not contain a `package.json`. `npm` has no idea what to install unless you give it package names via command-line arguments or a `package.json` file.

**Comment by KenanY** [comment] 2016-05-15 17:50
@Triusinfotech Are you still seeing this issue?

**Comment by KenanY** [comment] 2016-06-28 21:01
Closing as abandoned.

**Closed by KenanY** 2016-06-28 21:01 UTC
