### ISSUE TITLE
npm5 doesn't seem to use proxy and https-proxy in user .npmrc

### ISSUE THREAD

**Issue by mderriey** [npm/npm#16783] opened 2017-05-29 21:57 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm in an enterprise setup behind a corporate proxy.
I configured the proxy in all the tools I need to: Git, VS Code, bower and it works fine.

For npm I used:
```
npm config set proxy http://<username>:<password>@proxy:port
npm config set https-proxy http://<username>:<password>@proxy:port
```

This has stopped working since I upgraded to npm@next.
The result is [in this gist](https://gist.github.com/mderriey/1f7ba11ca31294590b9c546b4c751bb3)

The only way to get it working again is by setting the `proxy` and `https-proxy` config values globally with the `-g` flag.

Please let me know if I can help further.

### supporting information:

 - `npm -v` prints: `5.0.0`
 - `node -v` prints: `v6.10.3`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2017-05-29 22:30
@mderriey ooh, interesting. How did you install npm4? I've had folks report issues before where their npm installations and configs are in different places when they do `npm i -g npm@next` (saw it during the beta. This is, then, a config problem rather than a proxy thing, and I'm glad `-g` at least works as an escape hatch for you.

Can you tell me what `npm config ls` says for both npm4 and npm5?

**Comment by mderriey** [comment] 2017-05-30 00:25
I don't have npm 4 anymore as I got rid of the `npm5` package and installed `npm@next` which installed npm 5 (I hope that makes sense).

Here's the output of `npm config ls` for npm 5:
```
npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.0.0 node/v6.10.3 win32 x64"

; userconfig C:\Users\dmi\.npmrc
progress = false

; globalconfig C:\Users\dmi\AppData\Roaming\npm\etc\npmrc
https-proxy = "http://<username>:<password>@<proxy>:<port>/"
proxy = "http://<username>:<password>@<proxy>:<port>/"

; builtin config undefined
prefix = "C:\\Users\\dmi\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\dmi\dev\UWworkflow
; HOME = C:\Users\dmi
; "npm config ls -l" to show all defaults.
```

**Comment by KatSick** [comment] 2017-06-21 10:54
Same problem is on my side. npm4 works fine

**Comment by kuldarim** [comment] 2017-06-22 17:39
yeah me too, I cannot get npm 5 working under proxy. When we can expect it to be fixed?

**Comment by Gioni06** [comment] 2017-06-27 15:58
Same problem here. Is there a way to prioritize this issue since a lot of businesses would benefit from the new features of 5 but this issue is a show stopper?

**Comment by zkat** [comment] 2017-07-01 03:32
I suspect this has been fixed in canary.

If any of y'all are still running into this: Could you do `npm i -g npmc@latest && npmc i` and see if you can repro it? More changes to proxy auth have landed which will be included in the next release.

**Comment by zkat** [comment] 2017-07-03 21:07
I believe this has been fixed. Please let me know if this is still broken for you _under the latest canary_ and I can reopen.

**Closed by zkat** 2017-07-03 21:07 UTC
Labels: npm5, proxy

**Comment by Gioni06** [comment] 2017-07-10 15:28
@zkat Can not confirm that this is fixed. For additional information please have a look at this output from our build pipeline. I tried npmc and it fails with the same error. 
```
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://github.com:80/component/emitter/archive/1.0.1.tar.gz failed, reason: write EPROTO 140278010189632:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:
npm ERR!
```

Npm is running behind a proxy and uses a custom artifactory registry. `strict-ssl=false`
Maybe you can tell what the issue is or if it is related to npm at all. 
Thx

**Comment by kuldarim** [comment] 2017-07-18 08:34
Seems to not work for me either. I'm using 5.0.3 version

**Comment by mderriey** [comment] 2017-07-18 21:53
> I'm using 5.0.3 version

`5.3.0` was the latest version last time I checked, you might want to update.

**Comment by kuldarim** [comment] 2017-07-19 07:34
@mderriey did it work for you? I think I just made a typo, I used 5.3.0 I guess because I just downloaded latest nodejs and npm versions with brew.

**Comment by mderriey** [comment] 2017-07-19 07:53
I'm not seeing the issue anymore since `5.2.0`.

**Comment by KatSick** [comment] 2017-07-21 09:30
confirms that bug not reproduced on `5.3.0`
