### ISSUE TITLE
uid must be an unsigned int

### ISSUE THREAD

**Issue by jasehigh** [npm/npm#13926] opened 2016-09-10 20:27 UTC
When I attempt to this (or any install):

   sudo npm install -g homebridge-lightwaverf

I get the error:

   uid must be an unsigned int

I'm running:

   node v4.5.0
   npm  v3.10.8

On a Mac OS X 10.10.5 (mac mini).

Can any one advise on this issue?

Ja

**Comment by mhaddon** [comment] 2016-09-12 10:50
duplicate of https://github.com/npm/npm/issues/13918

**Comment by KenanY** [comment] 2016-09-12 11:01
Closing as a duplicate.

**Closed by KenanY** 2016-09-12 11:01 UTC
