### ISSUE TITLE
self signed certificate in certificate chain error when installing ionic on mac

### ISSUE THREAD

**Issue by PsiStarStorm** [npm/npm#10118] opened 2015-10-26 17:51 UTC
CLI output:
npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!

**Comment by OmgImAlexis** [comment] 2015-12-01 06:04
Is this still an issue? If it's working now this can be closed.

This was likely caused by a misconfiguration on one of the npm servers and is most likely fixed now.

**Comment by aredridel** [comment] 2015-12-01 06:13
Yes, unless this is in a corporate network environment, or the registry configuration is not set to default.

**Closed** 2017-06-16 23:51 UTC
Labels: bot-closed, support
