### ISSUE TITLE
fetch failed with status code 504

### ISSUE THREAD

**Issue by bramdevries** [npm/npm#12001] opened 2016-03-22 09:04 UTC
Since this morning we are experiencing a 504 on certain packages:

```
npm stdout: Nothing written
npm stderr: npm ERR! fetch failed https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.4.tgz
npm ERR! Linux 3.13.0-54-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-spin"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.12

npm ERR! fetch failed with status code 504
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

The package is also not available in the registry: https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.4.tgz

This issue seems related to this one happening last week: http://status.npmjs.org/incidents/5tthzg86h67m

**Comment by bcowgill** [comment] 2016-03-22 10:49
and another one, different package  
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz

6573 silly fetchPackageMetaData async@https://registry.npmjs.org/async/-/async-
0.2.10.tgz
6574 silly fetchPackageMetaData deep-equal@https://registry.npmjs.org/deep-equa
l/-/deep-equal-1.0.0.tgz
6575 silly fetchPackageMetaData i@https://registry.npmjs.org/i/-/i-0.3.2.tgz

**Comment by AndrewEnder** [comment] 2016-03-22 18:53
105475 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105476 info retry will retry, error on last attempt: Error: server error 504
105477 info attempt registry request try #3 at 6:39:23 PM
105478 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105479 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105480 error fetch failed https://registry.npmjs.org/which/-/which-1.2.2.tgz
105481 warn retry will retry, error on last attempt: Error: fetch failed with status code 504
105482 info retry fetch attempt 2 at 6:40:23 PM
105483 info attempt registry request try #1 at 6:40:23 PM
105484 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105485 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105486 info retry will retry, error on last attempt: Error: server error 504
105487 info attempt registry request try #2 at 6:41:23 PM
105488 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105489 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105490 info retry will retry, error on last attempt: Error: server error 504
105491 info attempt registry request try #3 at 6:43:13 PM
105492 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105493 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105494 error fetch failed https://registry.npmjs.org/which/-/which-1.2.2.tgz
105495 warn retry will retry, error on last attempt: Error: fetch failed with status code 504
105496 info retry fetch attempt 3 at 6:45:04 PM
105497 info attempt registry request try #1 at 6:45:04 PM
105498 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105499 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105500 info retry will retry, error on last attempt: Error: server error 504
105501 info attempt registry request try #2 at 6:46:04 PM
105502 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105503 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105504 info retry will retry, error on last attempt: Error: server error 504
105505 info attempt registry request try #3 at 6:47:54 PM
105506 http fetch GET https://registry.npmjs.org/which/-/which-1.2.2.tgz
105507 http fetch 504 https://registry.npmjs.org/which/-/which-1.2.2.tgz
105508 error fetch failed https://registry.npmjs.org/which/-/which-1.2.2.tgz
105509 silly fetchPackageMetaData Error: fetch failed with status code 504
105509 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\jenkins-service\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
105509 silly fetchPackageMetaData     at emitOne (events.js:90:13)
105509 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
105509 silly fetchPackageMetaData     at Request.onRequestResponse (C:\Users\jenkins-service\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:952:10)
105509 silly fetchPackageMetaData     at emitOne (events.js:90:13)
105509 silly fetchPackageMetaData     at ClientRequest.emit (events.js:182:7)
105509 silly fetchPackageMetaData     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:458:21)
105509 silly fetchPackageMetaData     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
105509 silly fetchPackageMetaData     at TLSSocket.socketOnData (_http_client.js:348:20)
105509 silly fetchPackageMetaData     at emitOne (events.js:90:13)
105509 silly fetchPackageMetaData     at TLSSocket.emit (events.js:182:7)
105509 silly fetchPackageMetaData  error for which@https://registry.npmjs.org/which/-/which-1.2.2.tgz [Error: fetch failed with status code 504]
105510 silly rollbackFailedOptional Starting
105511 silly rollbackFailedOptional Finishing
105512 silly runTopLevelLifecycles Starting
105513 silly runTopLevelLifecycles Finishing
105514 silly install printInstalled
105515 verbose stack Error: fetch failed with status code 504
105515 verbose stack     at Request.<anonymous> (C:\Users\jenkins-service\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
105515 verbose stack     at emitOne (events.js:90:13)
105515 verbose stack     at Request.emit (events.js:182:7)
105515 verbose stack     at Request.onRequestResponse (C:\Users\jenkins-service\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:952:10)
105515 verbose stack     at emitOne (events.js:90:13)
105515 verbose stack     at ClientRequest.emit (events.js:182:7)
105515 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:458:21)
105515 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
105515 verbose stack     at TLSSocket.socketOnData (_http_client.js:348:20)
105515 verbose stack     at emitOne (events.js:90:13)
105515 verbose stack     at TLSSocket.emit (events.js:182:7)
105516 verbose cwd C:\compass\Deployments\test\ui\compass
105517 error Windows_NT 6.3.9600
105518 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jenkins-service\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
105519 error node v5.9.0
105520 error npm  v3.8.3
105521 error fetch failed with status code 504

**Comment by laurence-myers** [comment] 2016-03-23 01:00
504 attempting to get glob (using npm@2):
```
npm ERR! fetch failed https://registry.npmjs.org/glob/-/glob-4.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/glob/-/glob-4.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/glob/-/glob-4.4.1.tgz
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/Users/laurence/.nvm/v0.10.41/bin/npm" "install"
npm ERR! node v0.10.41
npm ERR! npm  v2.14.14

npm ERR! fetch failed with status code 504
```

**Comment by Gargol** [comment] 2016-03-23 10:17
Had the same problem as @bramdevries described, to get through `npm install` removed `npm-shrinkwrap.json` and it works again.

**Comment by earnubs** [comment] 2016-03-23 12:59
Had to edit my npm-shinkwrap.json to not refer to which 1.2.2 (which is now missing from registry) but 1.2.4 instead :(

**Comment by bcowgill** [comment] 2016-03-23 15:19
As a workaround, What I did was create a new directory /tmp/crap
and copied the package.json only into /tmp/crap
then ran npm install in /tmp/crap
then moved /tmp/crap/node_modules into the original project directory.

I also tried npm cache clear in the original project directory but that didn't help.

I also set up a local npm package cache to protect from this kind of problem in future.
http://willcodefor.beer/setup-your-own-npm-cache-server/

Problem sort of solved.

**Comment by joerideg** [comment] 2016-03-23 16:19
Currently we are having the same problem with fetching the package which@1.2.2.
This 'which' package is listed in the npm-shrinkwrap.json of our production app in all versions so every build is broken :(. 

Removing the shrinkwrap and then doing npm install resolves the problem, also manually adjusting the npm-shrinkwrap to point to which@1.2.4 instead of 1.2.2 fixes the problem. 

This is on node 5.9.0 and npm 3.8.2

**Comment by zkat** [comment] 2016-03-24 23:13
Hi all! We were seeing some 504s from the registry since yesterday (at least) -- is this still happening? It should have been fixed by now.

**Comment by adilfulara** [comment] 2016-03-25 19:45
+1 on the issue. Is this still an issue ?

``
npm ERR! fetch failed https://registry.npmjs.org/@ticketmaster/ice-ismds-plugin/-/ice-ismds-plugin-2.0.0-alpha.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
``

**Comment by bramdevries** [comment] 2016-03-25 20:14
@zkat the [package tar](https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.4.tgz) I linked is still saying that it does not exist. I've fixed the issue by updating the shrinkwrap we use (it luckily didn't include an affected version). 

I suspect it's still happening

**Comment by zkat** [comment] 2016-03-25 20:37
@bramdevries 
```

{ name: 'node-uuid',
  description: 'Rigorous implementation of RFC4122 (v1 and v4) UUIDs.',
  'dist-tags': { latest: '1.4.7' },
  versions:
   [ '1.0.0',
     '1.1.0',
     '1.2.0',
     '1.3.0',
     '1.3.1',
     '1.3.2',
     '1.3.3',
     '1.4.0',
     '1.4.1',
     '1.4.2',
     '1.4.3',
     '1.4.6',
     '1.4.7' ],
```

It looks like the version simply doesn't exist in the registry.

**Comment by bramdevries** [comment] 2016-03-25 20:41
@zkat That's the whole problem, so my question is: Was this package unpublished manually or did it get unpublished because of a bug? It seems to be happening with multiple packages so unless all these maintainers decided to unpublish very specific versions of their packages I'm betting on a bug with the registry

**Comment by AndrewEnder** [comment] 2016-03-25 21:02
I believe [this article from The Register](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) summarizes part of the issue.

**Comment by zkat** [comment] 2016-03-25 21:42
@bramdevries I passed on the message to the registry team (note that this issue tracker is primarily for the npm cli). You could consider talking to support@npmjs.com for a more timely (possibly) answer on registry-related matters, but I'll try and keep you posted on this.

**Comment by earnubs** [comment] 2016-03-25 21:42
FWIW in the case of 'which' it's not about a whole package disappearing from the registry, it's about a single version (1.2.2) disappearing from the registry.

**Comment by othiym23** [comment] 2016-03-25 22:23
The primary registry records a timestamp for each package version the registry has ever seen. In the case of versions that are still published, it's the publish time; in the case of versions that have been unpublished, it's the time at which the version was unpublished. So:

```
bauchelain% npm v node-uuid time

{ modified: '2015-11-13T20:31:28.475Z',
  created: '2012-02-06T13:13:29.968Z',
  '1.3.3': '2012-02-06T19:00:02.414Z',
  '1.2.0': '2012-02-06T18:37:58.432Z',
  '1.3.0': '2012-02-06T18:43:49.454Z',
  '1.3.1': '2012-02-06T18:46:09.071Z',
  '1.3.2': '2012-02-06T18:49:48.386Z',
  '1.1.0': '2012-02-06T18:54:52.771Z',
  '1.0.0': '2012-02-06T18:56:53.955Z',
  '1.4.0': '2012-10-18T13:51:34.289Z',
  '1.4.1': '2013-08-17T12:51:06.146Z',
  '1.4.2': '2014-12-03T23:17:39.913Z',
  '1.4.3': '2015-03-05T19:31:39.445Z',
  '1.4.4': '2015-11-12T01:29:51.514Z',
  '1.4.6': '2015-11-12T22:03:38.350Z',
  '1.4.7': '2015-11-13T20:31:28.475Z' }

bauchelain% npm v node-uuid versions

[ '1.0.0',
  '1.1.0',
  '1.2.0',
  '1.3.0',
  '1.3.1',
  '1.3.2',
  '1.3.3',
  '1.4.0',
  '1.4.1',
  '1.4.2',
  '1.4.3',
  '1.4.6',
  '1.4.7' ]
```

`node-uuid@1.4.4` was unpublished last November:

```
  '1.4.4': '2015-11-12T01:29:51.514Z',
```

A number of npm's hosts have been rebuilt recently, including the instances that host the package tarballs, and it's possible that in the process of reconstructing them, the tarball that had been hanging around got garbage-collected while files were being moved around. If there's a bug here, it's that the unpublished package tarball was still on the tarball server – it should have been removed at the same time its metadata was unpublished.

If you want to know why that version of `node-uuid` got published, I'd [ask its maintainers](https://github.com/broofa/node-uuid/issues), although my guess is that it has something to do with [this](https://github.com/broofa/node-uuid/issues/126).

For `which@1.2.2`:

```
bauchelain% npm v which versions

[ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.5',
  '1.0.6',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.2.0',
  '1.2.1',
  '1.2.4' ]

bauchelain% npm v which time

{ modified: '2016-01-27T00:02:14.530Z',
  created: '2011-08-07T18:36:12.410Z',
  '1.0.0': '2011-08-07T18:36:17.514Z',
  '1.0.1': '2011-09-03T00:20:41.576Z',
  '1.0.2': '2011-09-13T20:01:41.982Z',
  '1.0.3': '2012-02-05T07:26:29.424Z',
  '1.0.4': '2012-03-01T16:26:45.298Z',
  '1.0.5': '2012-03-02T00:07:45.774Z',
  '1.0.6': '2014-11-25T10:35:10.788Z',
  '1.0.7': '2014-11-25T10:38:55.262Z',
  '1.0.8': '2014-12-06T08:14:03.285Z',
  '1.0.9': '2015-02-25T20:30:56.254Z',
  '1.1.0': '2015-05-10T04:01:32.694Z',
  '1.1.1': '2015-05-10T04:24:28.768Z',
  '1.1.2': '2015-09-08T23:47:44.246Z',
  '1.2.0': '2015-10-07T19:12:30.993Z',
  '1.2.1': '2015-12-22T17:43:12.774Z',
  '1.2.2': '2016-01-22T02:06:39.513Z',
  '1.2.3': '2016-01-26T02:15:06.654Z',
  '1.2.4': '2016-01-26T23:39:48.262Z' }
```

So `which@1.2.2` was unpublished on 2016-01-22, I think due to https://github.com/IndigoUnited/node-cross-spawn-async/issues/7 (from looking at the commits).

As @zkat indicated, the registry team is in the process of taking a hard look at how we handle unpublishes in general, and there will probably be changes around this in the future. For now, though, this is the registry behaving as intended (for now).

Since this is the intended behavior, at least for now, I'm going to close this issue, but let us know if you encounter situations where a package version goes missing without a corresponding entry in `npm view package time`. Thanks for your time and patience, everybody!

**Closed by othiym23** 2016-03-25 22:23 UTC
Labels: registry, support

**Comment by earnubs** [comment] 2016-03-26 08:25
👍 Thanks for the explanation.

**Comment by joerideg** [comment] 2016-03-26 09:48
Thank you @othiym23 for your explanation! I am aware that npm is currently looking into the unpublish process, hope it will become clear soon.

**Comment by laurence-myers** [comment] 2016-03-30 04:58
@othiym23 This doesn't seem to explain my issue with glob-4.4.1. Running the command you posted tells me: `'4.4.1':` '2015-02-26T22:16:20.319Z'`. So, it doesn't seem to have been unpublished.
