### ISSUE TITLE
npm install -g cordova ionic install error

### ISSUE THREAD

**Issue by sourabhsurana1008** [npm/npm#12792] opened 2016-05-21 09:07 UTC
C:\Users\sourabh>npm cache clean

C:\Users\sourabh>npm install -g cordova ionic
loadRequestedDeps -> netw | |##################-----------------------------------------------------------------------|

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for C:\Users\sourabh\AppData\Local\Temp\npm-6656-e415e996\registry.npmjs.org\ionic-\ionic-1.7.14.tgz
npm ERR! Expected: af493d5df4688d917d778b0934d1739b9be6efe6
npm ERR! Actual:   906b419e6e6e17b314c53a91048a784eb0c50b7d
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sourabh\npm-debug.log

[Uploading npm-debug.log…]()

**Comment by SwatiMaheshwari** [comment] 2016-05-21 19:00
I am facing the same issue..is it resolved?

**Comment by LeonidasJP** [comment] 2016-05-23 07:33
Not yet resolved. This is a duplicate of #12783

**Comment by sourabhsurana1008** [comment] 2016-05-23 16:30
It working for me after remove node js and install this version of node js - https://nodejs.org/dist/v4.4.4/node-v4.4.4-x64.msi

**Comment by zkat** [comment] 2016-12-09 00:40
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:40 UTC
