### ISSUE TITLE
hubot install err!  npm ERR! System Linux 3.13.0-74-generic

### ISSUE THREAD

**Issue by lvyingde51** [npm/npm#12247] opened 2016-04-07 09:14 UTC
Have some problems,If you know how to solve it,Please help me..Thank you..

```
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/parser.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/parser.js
npm ERR! fstream_path /usr/local/lib/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/parser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/multiparty
npm http GET https://registry.npmjs.org/ee-first/1.1.0
npm http GET https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/ee-first/1.1.0
npm http 304 https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/inherits
PuTTYPuTTYnpm http 304 https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/hubot/npm-debug.log
npm ERR! not ok code 0
root@ip-172-31-35-251:/opt/hubot# sudo npm install -g
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http 200 https://registry.npmjs.org/cookie-signature/1.0.6
npm ERR! registry error parsing json
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/hubot/node_modules/connect-multiparty/node_modules/multiparty/node_modules/readable-stream/lib/_stream_readable.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/hubot/node_modules/connect-multiparty/node_modules/multiparty/node_modules/readable-stream/lib/_stream_readable.js
npm ERR! fstream_path /usr/local/lib/node_modules/hubot/node_modules/connect-multiparty/node_modules/multiparty/node_modules/readable-stream/lib/_stream_readable.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! SyntaxError: Unexpected token
npm ERR! �S���0��c
��NU�����#X����9M�S�$���NX����V���܈k�:l�&-�     ��
*����$´�bu_�����[��'�H�o�@��I�@K�B��<"���5��h�-]m�F�<�-�$�Gx�Fql�{�,:c=��u �5� ܁B�(���l=/K��sY"_����X�,-Į\��2㸩������H�s=�
                                          �M
                                            �B{��R,�Q��o{��������-R���EV�<��/振���X.y�8d"h�,�bCh��]���ތ2��(��o8�����@����(����kN�v��1�����C'L�5�~_���)o�8*8v�����C�s�x�<�%o.���`�B9;P<��Qc���N��(�����8^�C�<O���Q
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/hubot/node_modules/connect-multiparty/node_modules/type-is/node_modules/mime-types/node_modules/mime-db/db.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/hubot/node_modules/connect-multiparty/node_modules/type-is/node_modules/mime-types/node_modules/mime-db/db.json
npm ERR! fstream_path /usr/local/lib/node_modules/hubot/node_modules/connect-multiparty/node_modules/type-is/node_modules/mime-types/node_modules/mime-db/db.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
PuTTYPuTTY<http://github.com/isaacs/npm/issuesnpm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/hubot/npm-debug.log
npm ERR! not ok code 0
root@ip-172-31-35-251:/opt/hubot# PuTTYPuTTY<http://github.com/isaacs/npm/issuesSystem Linux 3.13.0-74-genericnpm ERR! System Linux 3.13.0-74-generic
bash: http://github.com/isaacs/npm/issuesSystem: No such file or directory
root@ip-172-31-35-251:/opt/hubot# cd /opt/hubot && sudo npm install             npm WARN package.json log@1.4.0 No repository field.
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/basic-auth
npm http GET https://registry.npmjs.org/connect/2.30.2
npm http GET https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/content-disposition/0.5.0
npm http GET https://registry.npmjs.org/commander/2.6.0
npm http GET https://registry.npmjs.org/cookie/0.1.3
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http 304 https://registry.npmjs.org/connect/2.30.2
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/escape-html/1.0.2
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/fresh/0.3.0
npm http GET https://registry.npmjs.org/merge-descriptors/1.0.0
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/mkdirp/0.5.1
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.13.0
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/basic-auth
npm http 304 https://registry.npmjs.org/cookie/0.1.3
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/content-disposition/0.5.0
npm http 200 https://registry.npmjs.org/cookie-signature/1.0.6
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/commander/2.6.0
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/escape-html/1.0.2
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/fresh/0.3.0
npm http 304 https://registry.npmjs.org/merge-descriptors/1.0.0
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/mkdirp/0.5.1
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/send/0.13.0
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/vary
npm ERR! SyntaxError: Unexpected token
npm ERR! �S���0��c
��NU�����#X����9M�S�$���NX����V���܈k�:l�&-�     ��
*����$´�bu_�����[��'�H�o�@��I�@K�B��<"���5��h�-]m�F�<�-�$�Gx�Fql�{�,:c=��u �5� ܁B�(���l=/K��sY"_����X�,-Į\��2㸩������H�s=�
                                          �M
                                            �B{��R,�Q��o{��������-R���EV�<��/振���X.y�8d"h�,�bCh��]���ތ2��(��o8�����@����(����kN�v��1�����C'L�5�~_���)o�8*8v�����C�s�x�<�%o.���`�B9;P<��Qc���N��(�����8^�C�<O���Q
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm http GET https://registry.npmjs.org/commander/2.3.0
npm http GET https://registry.npmjs.org/debug/2.2.0
npm http GET https://registry.npmjs.org/diff/1.4.0
npm http GET https://registry.npmjs.org/escape-string-regexp/1.0.2
npm http GET https://registry.npmjs.org/growl/1.8.1
npm http GET https://registry.npmjs.org/glob/3.2.3
npm http GET https://registry.npmjs.org/jade/0.26.3
npm http GET https://registry.npmjs.org/supports-color/1.2.0
npm http 304 https://registry.npmjs.org/debug/2.2.0
npm http 304 https://registry.npmjs.org/diff/1.4.0
PuTTYPuTTYnpm http 304 https://registry.npmjs.org/growl/1.8.1
npm http 304 https://registry.npmjs.org/supports-color/1.2.0
npm http 304 https://registry.npmjs.org/glob/3.2.3
npm http 304 https://registry.npmjs.org/jade/0.26.3
npm http 304 https://registry.npmjs.org/commander/2.3.0
npm http 304 https://registry.npmjs.org/escape-string-regexp/1.0.2
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 200 https://registry.npmjs.org/ms/0.7.1
npm ERR! registry error parsing json
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm ERR! Error: ENOENT, lstat '/opt/hubot/node_modules/mocha/node_modules/jade/jade.min.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /opt/hubot/node_modules/mocha/node_modules/jade/jade.min.js
npm ERR! fstream_path /opt/hubot/node_modules/mocha/node_modules/jade/jade.min.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm ERR! Error: ENOENT, lstat '/opt/hubot/node_modules/mocha/node_modules/glob/test/bash-results.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /opt/hubot/node_modules/mocha/node_modules/glob/test/bash-results.json
npm ERR! fstream_path /opt/hubot/node_modules/mocha/node_modules/glob/test/bash-results.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/hubot/npm-debug.log
npm ERR! not ok code 0
root@ip-172-31-35-251:/opt/hubot# lllllllllllllllll
lllllllllllllllll: command not found
root@ip-172-31-35-251:/opt/hubot# cd /opt/hubot && sudo npm install
npm WARN package.json log@1.4.0 No repository field.
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/basic-auth
npm http GET https://registry.npmjs.org/connect/2.30.2
npm http GET https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/content-disposition/0.5.0
npm http GET https://registry.npmjs.org/commander/2.6.0
npm http GET https://registry.npmjs.org/cookie/0.1.3
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/escape-html/1.0.2
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/fresh/0.3.0
npm http GET https://registry.npmjs.org/merge-descriptors/1.0.0
npm http 304 https://registry.npmjs.org/basic-auth
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/mkdirp/0.5.1
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.13.0
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/cookie/0.1.3
npm http 304 https://registry.npmjs.org/content-disposition/0.5.0
npm http 304 https://registry.npmjs.org/connect/2.30.2
npm http 200 https://registry.npmjs.org/cookie-signature/1.0.6
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/commander/2.6.0
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/escape-html/1.0.2
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/fresh/0.3.0
npm http 304 https://registry.npmjs.org/merge-descriptors/1.0.0
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/mkdirp/0.5.1
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/send/0.13.0
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/vary
npm ERR! SyntaxError: Unexpected token
npm ERR! �S���0��c
��NU�����#X����9M�S�$���NX����V���܈k�:l�&-�     ��
*����$´�bu_�����[��'�H�o�@��I�@K�B��<"���5��h�-]m�F�<�-�$�Gx�Fql�{�,:c=��u �5� ܁B�(���l=/K��sY"_����X�,-Į\��2㸩������H�s=�
                                          �M
                                            �B{��R,�Q��o{��������-R���EV�<��/振���X.y�8d"h�,�bCh��]���ތ2��(��o8�����@����(����kN�v��1�����C'L�5�~_���)o�8*8v�����C�s�x�<�%o.���`�B9;P<��Qc���N��(�����8^�C�<O���Q
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm http GET https://registry.npmjs.org/commander/2.3.0
npm http GET https://registry.npmjs.org/debug/2.2.0
npm http GET https://registry.npmjs.org/diff/1.4.0
npm http GET https://registry.npmjs.org/glob/3.2.3
npm http GET https://registry.npmjs.org/escape-string-regexp/1.0.2
npm http GET https://registry.npmjs.org/growl/1.8.1
npm http GET https://registry.npmjs.org/jade/0.26.3
npm http GET https://registry.npmjs.org/supports-color/1.2.0
npm http 304 https://registry.npmjs.org/diff/1.4.0
npm http 304 https://registry.npmjs.org/debug/2.2.0
npm http 304 https://registry.npmjs.org/commander/2.3.0
npm http 304 https://registry.npmjs.org/glob/3.2.3
npm http 304 https://registry.npmjs.org/jade/0.26.3
npm http 304 https://registry.npmjs.org/escape-string-regexp/1.0.2
npm http 304 https://registry.npmjs.org/growl/1.8.1
npm http 304 https://registry.npmjs.org/supports-color/1.2.0
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 200 https://registry.npmjs.org/ms/0.7.1
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/minimist/0.0.8
PuTTYPuTTYnpm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/mkdirp/0.3.0
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/hubot/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment] 2016-04-07 16:23
Duplicate of https://github.com/npm/npm/issues/12196.

**Comment by othiym23** [comment] 2016-04-07 16:39
Closing as duplicate of #12196. See that issue for details and current status.

**Closed by othiym23** 2016-04-07 16:39 UTC
Labels: registry, support
