### ISSUE TITLE
Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by qaqeqe0** [npm/npm#13272] opened 2016-07-04 19:18 UTC
```
$ npm install -g express
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\cookie-signature\-\cookie-signature-1.0.6.tgz.613947129' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\cookie-signature\-\cookie-signature-1.0.6.tgz'


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\media-typer\-\media-typer-0.3.0.tgz.3067017062' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\media-typer\-\media-typer-0.3.0.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\ms\-\ms-0.7.1.tgz.253562466' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\ms\-\ms-0.7.1.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
express@4.14.0 C:\Users\Administrator\AppData\Roaming\npm\node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── methods@1.1.2
├── merge-descriptors@1.0.1
├── content-type@1.0.2
├── encodeurl@1.0.1
├── content-disposition@0.5.1
├── fresh@0.3.0
├── vary@1.1.0
├── path-to-regexp@0.1.7
├── parseurl@1.3.1
├── cookie@0.3.1
├── range-parser@1.2.0
├── etag@1.7.0
├── serve-static@1.11.1
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)
├── debug@2.2.0 (ms@0.7.1)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, ms@0.7.1, mime@1.3.4, http-errors@1.5.0)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Web\Angular JS\Project\Udemy 10 Project\10-knowLedgebase\npm-debug.log
```

**Comment by othiym23** [comment] 2016-08-19 22:37
```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\cookie-signature\-\cookie-signature-1.0.6.tgz.613947129' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\npm-3952-8034c49f\registry.npmjs.org\cookie-signature\-\cookie-signature-1.0.6.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:37 UTC
Labels: support, windows

**Comment by wallacerodrigon** [comment] 2017-02-07 02:28
Loot at here https://github.com/npm/npm/issues/7370 with RakeshVenkat comment. It has been solved for me.

**Comment by vinaypdgr8** [comment] 2017-07-14 19:32
nodejs Latest Current Version: v8.1.4 (includes npm 5.0.3) at www.nodejs.org worked for me

**Comment by abhishek11210646** [comment] 2017-08-24 05:28
helped me by uninstalling antivirus.

**Comment by godwin-l** [comment] 2018-06-15 14:34
In Windows 10 64-bit OS, I have resolved this issue by uninstalling Anti-Malware software.
