### ISSUE TITLE
error while installing appium

### ISSUE THREAD

**Issue by Huang-Jacky** [npm/npm#11303] opened 2016-01-27 12:44 UTC
```
npm ERR! tar.unpack unzip error C:\Users\jincheng.hjc\AppData\Local\Temp\npm-109
00-cc31163b\registry.npmjs.org\appium-uiauto\-\appium-uiauto-1.10.10.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "-g" "appium"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jincheng.hjc\npm-debug.log
```

**Comment by zkat** [comment] 2016-01-27 23:07
Hey! Stuff like this is usually a hiccup caused by incomplete downloads due to network issues: Would you mind trying to run `npm cache clean` and then trying your installation again? lmk if that doesn't resolve the issue.

**Comment by zkat** [comment] 2016-02-17 21:36
I'm gonna close this one, since I assume it's probably fine by now. Please comment if you're still having trouble!

**Closed by zkat** 2016-02-17 21:36 UTC
Labels: support
