### ISSUE TITLE
Saving a private repo using github access token

### ISSUE THREAD

**Issue by reggi** [npm/npm#7136] opened 2015-01-14 16:34 UTC
So I recently found a solution to all my woes. It was this little gem.

```
"module": "git+https://access-token:x-oauth-basic@github.com/user/repository.git"
```

However when I install 

```
npm install git+https://access-token:x-oauth-basic@github.com/user/repository.git --save
```

It's saving the package as:

```
"module": "file:../../../../../var/folders/jt/043tcrbs3m386w8kxjlf3jz00000gn/T/npm-53807-103ebf96/1421252527887-0.7609346129465848/7fd7a721329d5b733bb302c06e282f90c19fa0a6"
```

Which isn't very helpful when `heroku` or another person on the team runs `npm install`.

The [tutorial I got this from](http://rzrsharp.net/2013/07/02/private-github-repos-with-npm-and-heroku.html) said something about a `_from` field in `package.json`, I can't find any documentation for it anywhere. I'm wondering if that was supposed to take care of this. The only reference to a `_from` or `from` field for `package.json` was in this other issue https://github.com/npm/npm/issues/3823. The expected behavior is that the `module` would save the github url, understandably would be an `access-token` in `package.json` but that's on the user. It's `npm`'s job to get things where they should be.

**Comment by KenanY** [comment] 2015-01-14 17:50
I believe this is a bug. https://github.com/npm/npm/issues/7121

**Comment by othiym23** [comment] 2015-01-17 07:16
Yes. I'm closing this as a duplicate of #7121. Watch there. It was super easy to replicate, so it will probably get fixed soon (also sorry!).

**Closed by othiym23** 2015-01-17 07:16 UTC
