### ISSUE TITLE
Ran into problem after updating npm.

### ISSUE THREAD

**Issue by cole2bass** [npm/npm#17175] opened 2017-06-13 15:00 UTC
#### I'm opening this issue because:

  - [ X] npm is crashing.
  - [] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I updated npm to 5.0.3, I tried uninstalling a package.  However, it ran into a problem.

#### How can the CLI team reproduce the problem?
I recently updated npm, I only ran the following command:  npm uninstall -g @angular/cli, and that didn't work.

https://gist.github.com/cole2bass/31bcaf9dfb7eb40b724ca1f0d32fa268

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v7.7.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-06-13 15:10
Duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-13 15:10 UTC
Labels: npm5
