### ISSUE TITLE
Unable to install appium using npm

### ISSUE THREAD

**Issue by harikrishnaburma** [npm/npm#15033] opened 2016-11-25 20:27 UTC
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
I'm trying to install appium using npm with the command : npm install -g appium
I'm receiving the following error after the execution of above command.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/Users/myUsername/.npm-packages/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/Users/myUsername/.npm-packages/bin/npm" "install" "-g" "appium"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myUsername/local/bin/npm-debug.log
### supporting information:

 - `npm -v` prints: 4.0.2
 - `node -v` prints: v7.2.0
 - `npm config get registry` prints: http://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
OSX
 - Network issues:
   - Geographic location where npm was run:

   - [ ] I use a proxy to connect to the web.

 - Container:

**Comment by KenanY** [comment] 2016-11-25 20:27
Looks like a duplicate of https://github.com/npm/npm/issues/14427.

**Closed by KenanY** 2016-11-25 20:27 UTC

**Comment by harikrishnaburma** [comment] 2016-11-25 20:34
@KenanY Hi KenanY, Shall I downgrade the npm?

**Comment by KenanY** [comment] 2016-11-25 20:37
@harikrishnaburma Sure. I think the fix should be out today.

**Comment by harikrishnaburma** [comment] 2016-11-25 20:39
@KenanY I would like to know whether the downgrade fixes the issue?

**Comment by KenanY** [comment] 2016-11-25 20:41
@harikrishnaburma Downgrade to `npm@3` will fix the issue.
