### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by katopz** [npm/npm#11299] opened 2016-01-27 04:54 UTC
I can reproduce by
```shell
npm install http://github.com/bessdsv/bower-installer.git
```
and got
```shell
D:\Layout>npm install http://github.com/bessdsv/bower-installer.git
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\katopz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "http://github.com/bessdsv/bower-installer.git"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Layout\npm-debug.log
```
// log
https://gist.github.com/katopz/370408e2fe944a27c826

The weird part is I did success install before but somehow (even clean install) it just simply didn't work anymore.

Any hint?

**Comment by zkat** [comment] 2016-01-27 23:21
Duplicate of https://github.com/npm/npm/issues/9953

**Closed by zkat** 2016-01-27 23:21 UTC
Labels: bug, windows
