### ISSUE TITLE
npm should not cache tarballs from Github alongside registry tarballs

### ISSUE THREAD

**Issue by grncdr** [npm/npm#6024] opened 2014-08-23 16:02 UTC
**Using `npm@2.0.0-beta.0`**

Tarballs from github should not be added to the npm cache, since they may (often) not be valid packages before their "prepublish" script is run.

For example:
``` bash
npm install petkaantonov/bluebird.git#v2.3.1
node -e 'require("bluebird")'
```
This will fail because bluebird needs a build step. What's worse though is if you install again from the registry, you get the cached github tarball:

``` bash
npm install bluebird@2.3.1
node -e 'require("bluebird")'
```

**Comment by othiym23** [comment] 2016-08-18 21:44
Closing as duplicate of #5941 – this is something we intend to fix via a cache rewrite. Thanks for your time, and patience!

**Closed by othiym23** 2016-08-18 21:44 UTC
Labels: feature-request
