### ISSUE TITLE
ionic and cordova installation problems

### ISSUE THREAD

**Issue by jovic94** [npm/npm#14704] opened 2016-11-22 13:09 UTC
Below is my npm debug log file. I am facing a problem while installing ionic and cordova. Any one with a way around this problem kindly offer a solution.

I have already installed node version 6.9.1 and npm 3.10.8

<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic',
1 verbose cli   'cordova' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchPackageMetaData cordova
9 silly fetchNamedPackageData ionic
10 silly mapToRegistry name ionic
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'ionic',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'ionic',
13 silly mapToRegistry   name: 'ionic',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/ionic
15 silly fetchNamedPackageData cordova
16 silly mapToRegistry name cordova
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'cordova',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'cordova',
19 silly mapToRegistry   name: 'cordova',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/cordova
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 2:09:46 PM
24 verbose request id a5a0899af7236ad3
25 verbose etag W/"582d1d7e-ef132"
26 verbose lastModified Thu, 17 Nov 2016 03:01:18 GMT
27 http request GET https://registry.npmjs.org/cordova
28 verbose request uri https://registry.npmjs.org/ionic
29 verbose request no auth needed
30 info attempt registry request try #1 at 2:09:46 PM
31 verbose etag W/"582e1003-c489d"
32 verbose lastModified Thu, 17 Nov 2016 20:16:03 GMT
33 http request GET https://registry.npmjs.org/ionic
34 http 304 https://registry.npmjs.org/ionic
35 verbose headers { date: 'Tue, 22 Nov 2016 11:09:48 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   etag: 'W/"582e1003-c489d"',
35 verbose headers   age: '27',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-ams4422-AMS',
35 verbose headers   'x-cache': 'HIT',
35 verbose headers   'x-cache-hits': '1',
35 verbose headers   'x-timer': 'S1479812988.131237,VS0,VE0',
35 verbose headers   vary: 'Accept-Encoding' }
36 silly get cb [ 304,
36 silly get   { date: 'Tue, 22 Nov 2016 11:09:48 GMT',
36 silly get     via: '1.1 varnish',
36 silly get     'cache-control': 'max-age=300',
36 silly get     etag: 'W/"582e1003-c489d"',
36 silly get     age: '27',
36 silly get     connection: 'keep-alive',
36 silly get     'x-served-by': 'cache-ams4422-AMS',
36 silly get     'x-cache': 'HIT',
36 silly get     'x-cache-hits': '1',
36 silly get     'x-timer': 'S1479812988.131237,VS0,VE0',
36 silly get     vary: 'Accept-Encoding' } ]
37 verbose etag https://registry.npmjs.org/ionic from cache
38 verbose get saving ionic to /home/jovic/.npm/registry.npmjs.org/ionic/.cache.json
39 verbose correctMkdir /home/jovic/.npm correctMkdir not in flight; initializing
40 http 200 https://registry.npmjs.org/cordova
41 verbose headers { server: 'nginx/1.10.1',
41 verbose headers   'content-type': 'application/json',
41 verbose headers   'last-modified': 'Tue, 22 Nov 2016 03:00:54 GMT',
41 verbose headers   etag: 'W/"5833b4e6-f3eb4"',
41 verbose headers   'content-encoding': 'gzip',
41 verbose headers   'cache-control': 'max-age=300',
41 verbose headers   'content-length': '37731',
41 verbose headers   'accept-ranges': 'bytes',
41 verbose headers   date: 'Tue, 22 Nov 2016 11:09:48 GMT',
41 verbose headers   via: '1.1 varnish',
41 verbose headers   age: '44',
41 verbose headers   connection: 'keep-alive',
41 verbose headers   'x-served-by': 'cache-ams4148-AMS',
41 verbose headers   'x-cache': 'HIT',
41 verbose headers   'x-cache-hits': '91',
41 verbose headers   'x-timer': 'S1479812988.140286,VS0,VE0',
41 verbose headers   vary: 'Accept-Encoding' }
42 silly get cb [ 200,
42 silly get   { server: 'nginx/1.10.1',
42 silly get     'content-type': 'application/json',
42 silly get     'last-modified': 'Tue, 22 Nov 2016 03:00:54 GMT',
42 silly get     etag: 'W/"5833b4e6-f3eb4"',
42 silly get     'content-encoding': 'gzip',
42 silly get     'cache-control': 'max-age=300',
42 silly get     'content-length': '37731',
42 silly get     'accept-ranges': 'bytes',
42 silly get     date: 'Tue, 22 Nov 2016 11:09:48 GMT',
42 silly get     via: '1.1 varnish',
42 silly get     age: '44',
42 silly get     connection: 'keep-alive',
42 silly get     'x-served-by': 'cache-ams4148-AMS',
42 silly get     'x-cache': 'HIT',
42 silly get     'x-cache-hits': '91',
42 silly get     'x-timer': 'S1479812988.140286,VS0,VE0',
42 silly get     vary: 'Accept-Encoding' } ]
43 verbose get saving cordova to /home/jovic/.npm/registry.npmjs.org/cordova/.cache.json
44 verbose correctMkdir /home/jovic/.npm correctMkdir not in flight; initializing
45 silly install normalizeTree
46 silly loadCurrentTree Finishing
47 silly loadIdealTree Starting
48 silly install loadIdealTree
49 silly cloneCurrentTree Starting
50 silly install cloneCurrentTreeToIdealTree
51 silly cloneCurrentTree Finishing
52 silly loadShrinkwrap Starting
53 silly install loadShrinkwrap
54 silly loadShrinkwrap Finishing
55 silly loadAllDepsIntoIdealTree Starting
56 silly install loadAllDepsIntoIdealTree
57 silly resolveWithNewModule ionic@2.1.12 checking installable status
58 silly cache add args [ 'ionic', null ]
59 verbose cache add spec ionic
60 silly resolveWithNewModule cordova@6.4.0 checking installable status
61 silly cache add args [ 'cordova', null ]
62 verbose cache add spec cordova
63 silly cache add parsed spec Result {
63 silly cache add   raw: 'ionic',
63 silly cache add   scope: null,
63 silly cache add   escapedName: 'ionic',
63 silly cache add   name: 'ionic',
63 silly cache add   rawSpec: '',
63 silly cache add   spec: 'latest',
63 silly cache add   type: 'tag' }
64 silly addNamed ionic@latest
65 verbose addNamed "latest" is being treated as a dist-tag for ionic
66 info addNameTag [ 'ionic', 'latest' ]
67 silly mapToRegistry name ionic
68 silly mapToRegistry using default registry
69 silly mapToRegistry registry https://registry.npmjs.org/
70 silly mapToRegistry data Result {
70 silly mapToRegistry   raw: 'ionic',
70 silly mapToRegistry   scope: null,
70 silly mapToRegistry   escapedName: 'ionic',
70 silly mapToRegistry   name: 'ionic',
70 silly mapToRegistry   rawSpec: '',
70 silly mapToRegistry   spec: 'latest',
70 silly mapToRegistry   type: 'tag' }
71 silly mapToRegistry uri https://registry.npmjs.org/ionic
72 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
73 silly cache add parsed spec Result {
73 silly cache add   raw: 'cordova',
73 silly cache add   scope: null,
73 silly cache add   escapedName: 'cordova',
73 silly cache add   name: 'cordova',
73 silly cache add   rawSpec: '',
73 silly cache add   spec: 'latest',
73 silly cache add   type: 'tag' }
74 silly addNamed cordova@latest
75 verbose addNamed "latest" is being treated as a dist-tag for cordova
76 info addNameTag [ 'cordova', 'latest' ]
77 silly mapToRegistry name cordova
78 silly mapToRegistry using default registry
79 silly mapToRegistry registry https://registry.npmjs.org/
80 silly mapToRegistry data Result {
80 silly mapToRegistry   raw: 'cordova',
80 silly mapToRegistry   scope: null,
80 silly mapToRegistry   escapedName: 'cordova',
80 silly mapToRegistry   name: 'cordova',
80 silly mapToRegistry   rawSpec: '',
80 silly mapToRegistry   spec: 'latest',
80 silly mapToRegistry   type: 'tag' }
81 silly mapToRegistry uri https://registry.npmjs.org/cordova
82 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
83 verbose get https://registry.npmjs.org/ionic not expired, no request
84 silly addNameTag next cb for ionic with tag latest
85 silly addNamed ionic@2.1.12
86 verbose addNamed "2.1.12" is a plain semver version for ionic
87 silly mapToRegistry name ionic
88 silly mapToRegistry using default registry
89 silly mapToRegistry registry https://registry.npmjs.org/
90 silly mapToRegistry data Result {
90 silly mapToRegistry   raw: 'ionic',
90 silly mapToRegistry   scope: null,
90 silly mapToRegistry   escapedName: 'ionic',
90 silly mapToRegistry   name: 'ionic',
90 silly mapToRegistry   rawSpec: '',
90 silly mapToRegistry   spec: 'latest',
90 silly mapToRegistry   type: 'tag' }
91 silly mapToRegistry uri https://registry.npmjs.org/ionic
92 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz not in flight; adding
93 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz',
93 verbose addRemoteTarball   'e0102b764d589a09e9cbd432c338d9c539feeebe' ]
94 verbose get https://registry.npmjs.org/cordova not expired, no request
95 silly addNameTag next cb for cordova with tag latest
96 silly addNamed cordova@6.4.0
97 verbose addNamed "6.4.0" is a plain semver version for cordova
98 info retry fetch attempt 1 at 2:09:50 PM
99 info attempt registry request try #1 at 2:09:50 PM
100 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
101 silly cache afterAdd cordova@6.4.0
102 verbose afterAdd /home/jovic/.npm/cordova/6.4.0/package/package.json not in flight; writing
103 verbose correctMkdir /home/jovic/.npm correctMkdir not in flight; initializing
104 verbose afterAdd /home/jovic/.npm/cordova/6.4.0/package/package.json written
105 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
106 silly fetchAndShaCheck shasum e0102b764d589a09e9cbd432c338d9c539feeebe
107 silly rollbackFailedOptional Starting
108 silly rollbackFailedOptional Finishing
109 silly runTopLevelLifecycles Finishing
110 silly install printInstalled
111 verbose stack Error: shasum check failed for /tmp/npm-13251-f8ec0f5a/registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
111 verbose stack Expected: e0102b764d589a09e9cbd432c338d9c539feeebe
111 verbose stack Actual:   ba1842f425bcd1ba3bc65a6013822c1348e55b25
111 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
111 verbose stack     at /usr/lib/node_modules/npm/node_modules/sha/index.js:25:8
111 verbose stack     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/node_modules/sha/index.js:72:7)
111 verbose stack     at emitNone (events.js:91:20)
111 verbose stack     at ReadStream.emit (events.js:185:7)
111 verbose stack     at endReadableNT (_stream_readable.js:974:12)
111 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
111 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
112 verbose cwd /home/jovic
113 error Linux 4.4.0-47-generic
114 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic" "cordova"
115 error node v6.9.1
116 error npm  v3.10.8
117 error shasum check failed for /tmp/npm-13251-f8ec0f5a/registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
117 error Expected: e0102b764d589a09e9cbd432c338d9c539feeebe
117 error Actual:   ba1842f425bcd1ba3bc65a6013822c1348e55b25
117 error From:     https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
118 error If you need help, you may report this error at:
118 error     <https://github.com/npm/npm/issues>
119 verbose exit [ 1, true ]
</pre></details>

**Comment by legodude17** [comment] 2016-11-29 01:09
Please check your internet connection and then run `npm cache clean ionic`.

**Comment by zkat** [comment] 2016-12-02 04:44
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:44 UTC
Labels: network, shasum, support
