### ISSUE TITLE
npm install error jpegtran optipng

### ISSUE THREAD

**Issue by hdcdstr8fwd** [npm/npm#15204] opened 2016-12-13 00:18 UTC
![screen shot 2016-12-12 at 23 55 43](https://cloud.githubusercontent.com/assets/23746188/21122456/0f0b4dd4-c0ca-11e6-897e-945758912408.png)
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Npm install fails with build errors for jpegtran and optipng in a local project folder. Have tested with LTS and latest version of node both returns the same error. 

I have tried to install these globally and the compile and the process runs as it should.

#### How can the CLI team reproduce the problem?
error is triggered any time imagemin is called in a local project

https://gist.github.com/hdcdstr8fwd/1a9e5dd538c8a0ec8db2c60271c03690#file-gistfile1-txt

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v7.2.1 also tested with LTS version returns same error.
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.75
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2016-12-13 01:07
This is most likely a problem with `imagemin` not with `npm` please file an issue over at their repo (`npm bugs imagemin`).

**Comment by zkat** [comment] 2016-12-15 05:45
Closing as a duplicate of https://github.com/imagemin/imagemin/issues/221 since this seems like an `optipng` issue to me.

**Closed by zkat** 2016-12-15 05:45 UTC
Labels: support
