### ISSUE TITLE
All attempted installs fail shasum check

### ISSUE THREAD

**Issue by davycassidy** [npm/npm#12392] opened 2016-04-18 07:18 UTC
I have downloaded and installed node.js version 5.10.1, which has version 3.8.3 of npm. I am running Windows 7.

I am behind a proxy so I've added this to my .npmrc in C:\Users\MyName

strict-ssl=false
proxy=http://myDomain%5CMyName:myPassword%3DMorePassWord@MyIp:ProxyPort/

**No matter what package I try to install I get a 'shasum check failed for ....'**

I have searched a lot but this error seems to occur quite frequently due to different factors over the years.

I'm not sure if it is related to the fact that I'm behind a proxy.
Is there anything I can do to fix this issue?

The debug informaitn is here:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt
8 silly fetchNamedPackageData grunt
9 silly mapToRegistry name grunt
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'grunt',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'grunt',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/grunt
14 verbose request uri https://registry.npmjs.org/grunt
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:16:17 AM
17 verbose request id 4bac1be8991cb38e
18 verbose etag "DT6R71WU421AW1JPVNN2AKCGW"
19 http request GET https://registry.npmjs.org/grunt
20 http 304 https://registry.npmjs.org/grunt
21 verbose headers { date: 'Mon, 18 Apr 2016 07:16:17 GMT',
21 verbose headers   via: '1.1 varnish, HTTPS/1.1 localhost.localdomain',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"DT6R71WU421AW1JPVNN2AKCGW"',
21 verbose headers   age: '67',
21 verbose headers   'x-served-by': 'cache-lcy1126-LCY',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '3',
21 verbose headers   'x-timer': 'S1460963777.081488,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   connection: 'close' }
22 silly get cb [ 304,
22 silly get   { date: 'Mon, 18 Apr 2016 07:16:17 GMT',
22 silly get     via: '1.1 varnish, HTTPS/1.1 localhost.localdomain',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"DT6R71WU421AW1JPVNN2AKCGW"',
22 silly get     age: '67',
22 silly get     'x-served-by': 'cache-lcy1126-LCY',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '3',
22 silly get     'x-timer': 'S1460963777.081488,VS0,VE0',
22 silly get     vary: 'Accept-Encoding',
22 silly get     connection: 'close' } ]
23 verbose etag https://registry.npmjs.org/grunt from cache
24 verbose get saving grunt to C:\Users\dcassidy\AppData\Roaming\npm-cache\registry.npmjs.org\grunt\.cache.json
25 verbose correctMkdir C:\Users\dcassidy\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule grunt@1.0.1 checking installable status
39 silly cache add args [ 'grunt', null ]
40 verbose cache add spec grunt
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'grunt',
41 silly cache add   scope: null,
41 silly cache add   name: 'grunt',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed grunt@latest
43 verbose addNamed "latest" is being treated as a dist-tag for grunt
44 info addNameTag [ 'grunt', 'latest' ]
45 silly mapToRegistry name grunt
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'grunt',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   name: 'grunt',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/grunt
50 verbose addNameTag registry:https://registry.npmjs.org/grunt not in flight; fetching
51 verbose get https://registry.npmjs.org/grunt not expired, no request
52 silly addNameTag next cb for grunt with tag latest
53 silly addNamed grunt@1.0.1
54 verbose addNamed "1.0.1" is a plain semver version for grunt
55 silly mapToRegistry name grunt
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'grunt',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   name: 'grunt',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/grunt
60 verbose addRemoteTarball https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz',
61 verbose addRemoteTarball   'e8778764e944b18f32bb0f10b9078475c9dfb56b' ]
62 info retry fetch attempt 1 at 8:16:17 AM
63 info attempt registry request try #1 at 8:16:17 AM
64 http fetch GET https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
65 http fetch 200 https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
66 silly fetchAndShaCheck shasum e8778764e944b18f32bb0f10b9078475c9dfb56b
67 silly rollbackFailedOptional Starting
68 silly rollbackFailedOptional Finishing
69 silly runTopLevelLifecycles Starting
70 silly runTopLevelLifecycles Finishing
71 silly install printInstalled
72 verbose stack Error: shasum check failed for C:\Windows\Temp\iotdx-disposable\Users\dcassidy\npm-25800-42e563e6\registry.npmjs.org\grunt\-\grunt-1.0.1.tgz
72 verbose stack Expected: e8778764e944b18f32bb0f10b9078475c9dfb56b
72 verbose stack Actual:   ae3bd341255f438f00ba2450906b9b8eda492bf1
72 verbose stack From:     https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
72 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
72 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
72 verbose stack     at emitNone (events.js:85:20)
72 verbose stack     at ReadStream.emit (events.js:179:7)
72 verbose stack     at endReadableNT (_stream_readable.js:913:12)
72 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
72 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
73 verbose cwd C:\
74 error Windows_NT 6.1.7601
75 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt"
76 error node v5.10.1
77 error npm  v3.8.3
78 error shasum check failed for C:\Windows\Temp\iotdx-disposable\Users\dcassidy\npm-25800-42e563e6\registry.npmjs.org\grunt\-\grunt-1.0.1.tgz
78 error Expected: e8778764e944b18f32bb0f10b9078475c9dfb56b
78 error Actual:   ae3bd341255f438f00ba2450906b9b8eda492bf1
78 error From:     https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
79 error If you need help, you may report this error at:
79 error     <https://github.com/npm/npm/issues>
80 verbose exit [ 1, true ]
```

**Comment by busches** [comment] 2016-09-25 19:07
Are you still facing this issue? Is it for any package or only grunt?

**Comment by zkat** [comment] 2016-12-09 00:42
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:42 UTC
Labels: proxy, support, windows
