### ISSUE TITLE
It should be possible to assign a different location to installed modules

### ISSUE THREAD

**Issue by 3m0** [npm/npm#8379] opened 2015-05-27 22:05 UTC
In the past, npm provided modules for node, but now there are many frontend modules, like angular and bootstrap. Sometimes, the developer may want to install these modules in a folder different from node_modules. This setting should be configurable.

**Comment by KenanY** [comment] 2015-05-28 03:58
@3m0 Please see [this FAQ entry](https://docs.npmjs.com/misc/faq#node-modules-is-the-name-of-my-deity-s-arch-rival-and-a-forbidden-word-in-my-religion-can-i-configure-npm-to-use-a-different-folder). This is not as simple as making a few changes to `npm`.

**Comment by zkat** [comment] 2016-02-25 22:06
There's two points to be made here. The first is that `node_modules/` is a particularly core part of how node's module system works, and is very unlikely to change, since it's built right into the runtime. We are not going to support a solution that involves picking arbitrary locations that are not `node_modules/` for that reason.

That said, my understanding of your particular request is that it seems to be directed at the case of non-node modules that would need to be put elsewhere or otherwise treated differently from the backend-related modules.

This particular use-case is on our longer-term roadmap. You can check the issues tagged with `front-end` (and `flat-dependencies`) to get a wider view of the sort of things we're looking at or planning for this, which will very very likely _*not*_ involve arbitrary directory name configuration.

Since this is part of a larger set of similar feature requests, I'm closing this as a duplicate of those. Cheers! :)

**Closed by zkat** 2016-02-25 22:06 UTC
Labels: feature-request, front-end
