### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by syaka-yin** [npm/npm#14620] opened 2016-11-14 08:56 UTC
when i`m using ```npm install```, i got some errors

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /var/folders/b_/j8fgt4gj6895213px41zf7_c0000gn/T/npm-76269-25b826e0/registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000580.tgz
npm ERR! Expected: 04bf77139486b792ca42b4ab8ef0cbec00fe4640
npm ERR! Actual:   0132886a0a696bad889af005df2d17dec495b3bc
npm ERR! From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000580.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

i run ```npm cache clean```, but it dosen`t work.

dose anyone know how to resolve this problem?

thank you!

**Comment by legodude17** [comment] 2016-11-14 18:08
Try updating to `npm@4.0.3`.

**Comment by branpar** [comment] 2016-11-14 19:30
I have the same issue right now with a different package. The version recommended does not exist. Are there any other ways we can resolve this issue? When this happens for us on our servers it prevents builds from being released.

**Comment by legodude17** [comment] 2016-11-14 19:38
I thought `npm` was at `4.0.3`? Guess I forgot. Anyway update to `latest`.

**Comment by branpar** [comment] 2016-11-14 19:39
Sure, locally I updated to 3.10.9 which is the latest release (excluding pre-release candidates). I still had the same issue with the latest release.

**Comment by legodude17** [comment] 2016-11-14 19:42
Did you try `npm cache clean` @branpar?

**Comment by branpar** [comment] 2016-11-14 20:36
Yes, I also went into the `App_Data/Temp` folder and deleted all the npm folders in there.

**Comment by jovic94** [comment] 2016-11-16 13:52
who has an idea of how to handle this problem...???

**Comment by legodude17** [comment] 2016-11-16 15:44
Ref #14630, pinging @soldair.

**Comment by GlintRain** [comment] 2016-11-25 06:48
I encountered a similar problem , and there is what I did .( I'm using macOS Sierra 10.12.1 and I'm going to install ionic.)
1.npm config set registry, I find Internet speed is slow, so I change the redistry;
2.update npm to 4.0.2,using sudo;
3.install cordova and ionic using sudo;
then I installed Cordova and Ionic successfully. I'm not sure which one really helped.╮(￣▽￣"")╭
Have a try?

**Comment by syaka-yin** [comment] 2016-12-01 02:52
Thank you very much for help me .
I think the reason is caused by my VPN, because i am in China.
So I disconnect my VPN, and use
```
npm install --registry=http://registry.cnpmjs.org
```

It works !  No error
Maybe there are other reasons, I will update npm to the latest version.

Thank you, very much.

**Comment by zkat** [comment] 2016-12-02 04:47
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:47 UTC
Labels: registry, shasum, support
