### ISSUE TITLE
npm 3.3.12, installing package that depends on npm v2 fails

### ISSUE THREAD

**Issue by robertbaker** [npm/npm#10234] opened 2015-11-02 23:14 UTC
```
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\gulp-cordova-create\node_modules\npm\node_modules\cmd-shim with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\gulp-cordova-create\node_modules\npm\node_modules\read-package-json with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\gulp-cordova-create\node_modules\npm\node_modules\read-installed with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\gulp-cordova-create\node_modules\npm\node_modules\rimraf with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\gulp-cordova-create\node_modules\npm\node_modules\sha with new installed version
npm ERR! Windows_NT 10.0.10576
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! path c:\git\pos\node_modules\gulp-cordova-create\node_modules\npm\node_modules\rimraf\bin.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'c:\git\pos\node_modules\gulp-cordova-create\node_modules\npm\node_modules\rimraf\bin.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\git\pos\npm-debug.log
```

**Comment by smikes** [comment] 2015-11-04 12:46
Thanks for creating this.

It looks like gulp-cordova-create is bundling an older version of `npm`, and I believe there are known problems with reverting to npm@2 with an installation of npm@3.

I suspect the only long-term "solution" is for gulp-cordova-create to bundle npm@3

Can you tell me what you're working on at a high level?  There may be ways to work around it (e.g., using a separate version of node or a version manager) if you need to have node 5 and npm 2 in order to work on a particular project.

**Comment by robertbaker** [comment] 2015-11-04 18:01
@smikes  It's actually cordova-lib that is bundling npm 2, gulp-cordova-create depends on cordova-lib.

I filed an issue with the cordova team that is unanswered so far. I tried to shrinkwrap it to force it to use npm@3 but that didn't work, their code breaks.

I'm working on an angular 1.4 cordova project (not using ionic). Ideally I want to use node 5 and npm 3.

I was able to complete the installation by reverting to npm@3.3.10 and running npm update.

The changes made in 3.3.11 and .12 caused this to break.

**Comment by smikes** [comment] 2015-11-05 01:24
Interesting - thanks for finding the source of the regression. I'll see if a core CLI team member can take a look.

**Comment by smikes** [comment] 2015-11-05 03:35
@iarna or @zkat , possible regression in 3.3.11 and 3.3.12

**Comment by iarna** [comment] 2015-11-06 19:47
Closing this as a duplicate of #9633

**Closed by iarna** 2015-11-06 19:47 UTC
