### ISSUE TITLE
ionic project creation : [ERROR] An error occurred while running npm install (exit code 1):

### ISSUE THREAD

**Issue by ghost** [npm/npm#17482] opened 2017-06-28 05:54 UTC
> npm install
? Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-d75da30c
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-8f1516dd\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-8f1516dd\3
1d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-d75da30c
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-8f1516dd\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:
        error: cannot spawn sh: No such file or directory
        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-d75da30c
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-8f1516dd\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: unable to fork
        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-d75da30c
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-8f1516dd\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-https-github-co
m-resin-io-bonjour-git-3f9321aa
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-534cbd12\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-534cbd12\3
1d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-https-github-co
m-resin-io-bonjour-git-3f9321aa
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-534cbd12\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:
        error: cannot spawn sh: No such file or directory
        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-https-github-co
m-resin-io-bonjour-git-3f9321aa
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-534cbd12\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: unable to fork
        npm ERR! git clone
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-https-github-co
m-resin-io-bonjour-git-3f9321aa
        C:\Users\Dell\AppData\Local\Temp\npm-6132-a1e44593\git-cache-534cbd12\31
d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:205:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:194:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:899:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-41f67eef
        because of error: { Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:205:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:194:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:899:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get
        remote.origin.url' }
        npm ERR! git clone
        --template=C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\_templat
es
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-41f67eef:
        Cloning into bare repository
        'C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef'...
        npm ERR! git clone
        --template=C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\_templat
es
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-41f67eef:
        error: cannot spawn ssh: No such file or directory
        npm ERR! git clone
        --template=C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\_templat
es
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-41f67eef:
        fatal: unable to fork
        npm ERR! Windows_NT 6.1.7601
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v7.10.0
        npm ERR! npm  v4.2.0
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\_templat
es
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resi
n-io-bonjour-git-41f67eef
        npm ERR! Cloning into bare repository
        'C:\Users\Dell\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef'...
        npm ERR! error: cannot spawn ssh: No such file or directory
        npm ERR! fatal: unable to fork
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!
        C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2017-06-28T05_13_49_485Z-d
ebug.log

**Comment by markaks** [comment] 2017-06-28 12:26
use "ionic start myapp tabs" inside uuid:
like: C:\io24\node_modules\uuid>ionic start myapp tabs
it's work for me!!!!

**Comment by AkshayMhatre1** [comment] 2017-06-28 13:08
try **ionic start --type=ionic1**

**Comment by kenany** [comment] 2017-06-30 22:24
dupe of https://github.com/npm/npm/issues/17460

**Closed as completed by kenany** 2017-06-30 22:24 UTC
Labels: support
