### ISSUE TITLE
npm@5.0.3 crash: Unhandled rejection Error: Argument #2: Expected string but got nullb464a5cc07bd

### ISSUE THREAD

**Issue by BurtHarris** [npm/npm#17070] opened 2017-06-07 21:36 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Crash while trying to remove global install of typedoc@0.7.1
#### How can the CLI team reproduce the problem?

- With typedoc@0.7.1 installed globally
- `npm uninstall -g typedoc`

See https://gist.github.com/BurtHarris/fba149c7189766de276fc67165e05bad

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints:v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by BurtHarris** [comment] 2017-06-07 21:39
My node install is via nvm-win version 1.1.4.

`npm prefix -g` reports `C:\Users\Burt_\AppData\Roaming\nvm\v6.10.3\node_modules\npm`

**Comment by BurtHarris** [comment] 2017-06-07 21:45
I worked around this by removing the command stubs and directory from the global path directory, and re-running the `npm uninstall -g typedoc` command.

**Comment by kenany** [comment] 2017-06-08 14:56
Looks like a duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-08 14:56 UTC
Labels: npm5

**Comment by BurtHarris** [comment] 2017-06-08 16:21
agreed
