### ISSUE TITLE
Problems upgrading npm on Ubuntu 15.04.

### ISSUE THREAD

**Issue by dreaddy** [npm/npm#8537] opened 2015-06-11 12:55 UTC
Also note. Not very npm savvy.

Running as root.

Dependencies Resolved

================================================================================
 Package                         Arch        Version            Repository
                                                                           Size
================================================================================
Updating:
 nodejs-npm-registry-client      noarch      0.2.28-3.el6       epel       20 k

Transaction Summary
================================================================================
Upgrade       1 Package(s)

Total download size: 20 k
Is this ok [y/N]: y
Downloading Packages:
nodejs-npm-registry-client-0.2.28-3.el6.noarch.rpm       |  20 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Updating   : nodejs-npm-registry-client-0.2.28-3.el6.noarch               1/2
Error unpacking rpm package nodejs-npm-registry-client-0.2.28-3.el6.noarch
error: unpacking of archive failed on file /usr/lib/node_modules/npm-registry-client/node_modules/chownr: cpio: rename
  Verifying  : nodejs-npm-registry-client-0.2.28-3.el6.noarch               1/2
nodejs-npm-registry-client-0.2.28-1.el6.noarch was supposed to be removed but is not!
  Verifying  : nodejs-npm-registry-client-0.2.28-1.el6.noarch               2/2

Failed:
  nodejs-npm-registry-client.noarch 0:0.2.28-1.el6
  nodejs-npm-registry-client.noarch 0:0.2.28-3.el6

Complete!

**Comment by vhaispdeaded** [comment] 2015-06-12 13:19
I am experiencing the same issue on RHEL6 systems.

**Comment by KenanY** [comment] 2015-06-13 21:30
@dreaddy This doesn't look like `npm` output to me.

**Comment by Neograph734** [comment] 2015-06-13 21:32
It is yum output. The package manager of RHEL systems. But I can confirm that the recent update does not install. Perhaps the package is broken?

**Comment by KenanY** [comment] 2015-06-13 21:35
@Neograph734 As far as I know, the `npm` CLI team does not maintain that package. The recommended way of updating `npm` is [using `npm` itself](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by Neograph734** [comment] 2015-06-13 21:38
I don't know, landed here a day ago with google and decided to follow the issue. But I suppose this is better asked in https://github.com/npm/npm-registry-client ?

**Comment by othiym23** [comment] 2015-06-13 21:44
@Neograph734 I think the issue is probably with the yum package for `nodejs-npm-registry-client-0.2.28-3.el6.noarch`, which is packaged by somebody in the Fedora community, and not anybody on the npm CLI team. We write the code and package it for npm's registry, but we don't have much control about how npm gets put together downstream. Sorry if that's not more useful, and thanks for bringing this to our attention!

**Closed by othiym23** 2015-06-13 21:44 UTC

**Comment by Neograph734** [comment] 2015-06-13 21:46
No problem, I suppose there will be another package some day :)

**Comment by tchollingsworth** [comment] 2015-09-11 21:24
This happens when you `npm update -g` all the modules installed with yum.  The content changes underneath rpm and it refuses to update to avoid potential data loss.

If you want to keep using npm to update npm:

```sh
repoquery --whatrequires 'nodejs(engine)' | xargs yum remove
curl https://www.npmjs.com/install.sh | sh`
```
And on future installs just:

```sh 
yum install nodejs #not npm
curl https://www.npmjs.com/install.sh | sh
```

If you want to keep using yum to update npm:

```sh
rm -rf /usr/lib/node_modules/*
repoquery --whatrequires 'nodejs(engine)' | xargs yum reinstall
```
...and [stop using sudo with npm](/sindresorhus/guides/blob/master/npm-global-without-sudo.md). :-)
