### ISSUE TITLE
unable to install with npm

### ISSUE THREAD

**Issue by sirediamond** [npm/npm#15962] opened 2017-03-06 15:19 UTC
#### I'm opening this issue because:

 i want to install ionic and am recieving this error

# **error**
 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://r.cnpmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ionic',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ionic',
12 silly mapToRegistry   name: 'ionic',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://r.cnpmjs.org/ionic
14 verbose request uri http://r.cnpmjs.org/ionic
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:59:59 PM
17 verbose request id 881d0cf2b592b1fb
18 http request GET http://r.cnpmjs.org/ionic
19 http 200 http://r.cnpmjs.org/ionic
20 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
20 verbose headers   date: 'Mon, 06 Mar 2017 14:59:59 GMT',
20 verbose headers   'content-type': 'application/json; charset=utf-8',
20 verbose headers   'transfer-encoding': 'chunked',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-current-requests': '1',
20 verbose headers   'x-readtime': '448',
20 verbose headers   'strict-transport-security': 'max-age=15768000',
20 verbose headers   'content-encoding': 'gzip' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.4.6 (Ubuntu)',
21 silly get     date: 'Mon, 06 Mar 2017 14:59:59 GMT',
21 silly get     'content-type': 'application/json; charset=utf-8',
21 silly get     'transfer-encoding': 'chunked',
21 silly get     connection: 'keep-alive',
21 silly get     'x-current-requests': '1',
21 silly get     'x-readtime': '448',
21 silly get     'strict-transport-security': 'max-age=15768000',
21 silly get     'content-encoding': 'gzip' } ]
22 verbose get saving ionic to C:\Users\SIRE DIAMOND\AppData\Roaming\npm-cache\r.cnpmjs.org\ionic\.cache.json
23 verbose correctMkdir C:\Users\SIRE DIAMOND\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose makeDirectory C:\Users\SIRE DIAMOND\AppData\Roaming\npm-cache creation not in flight; initializing
25 verbose makeCacheDir UID & GID are irrelevant on win32
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule ionic@2.2.1 checking installable status
39 silly cache add args [ 'ionic', null ]
40 verbose cache add spec ionic
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'ionic',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'ionic',
41 silly cache add   name: 'ionic',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed ionic@latest
43 verbose addNamed "latest" is being treated as a dist-tag for ionic
44 info addNameTag [ 'ionic', 'latest' ]
45 silly mapToRegistry name ionic
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry http://r.cnpmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'ionic',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'ionic',
48 silly mapToRegistry   name: 'ionic',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri http://r.cnpmjs.org/ionic
50 verbose addNameTag registry:http://r.cnpmjs.org/ionic not in flight; fetching
51 verbose get http://r.cnpmjs.org/ionic not expired, no request
52 silly addNameTag next cb for ionic with tag latest
53 silly addNamed ionic@2.2.1
54 verbose addNamed "2.2.1" is a plain semver version for ionic
55 silly mapToRegistry name ionic
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry http://r.cnpmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'ionic',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   escapedName: 'ionic',
58 silly mapToRegistry   name: 'ionic',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri http://r.cnpmjs.org/ionic
60 verbose addRemoteTarball http://r.cnpmjs.org/ionic/download/ionic-2.2.1.tgz not in flight; adding
61 verbose addRemoteTarball [ 'http://r.cnpmjs.org/ionic/download/ionic-2.2.1.tgz',
61 verbose addRemoteTarball   '2b9d90b3ae109138084473282c18ea162a5f8248' ]
62 info retry fetch attempt 1 at 4:00:03 PM
63 info attempt registry request try #1 at 4:00:03 PM
64 http fetch GET http://r.cnpmjs.org/ionic/download/ionic-2.2.1.tgz
65 http fetch 200 http://r.cnpmjs.org/ionic/download/ionic-2.2.1.tgz
66 silly fetchAndShaCheck shasum 2b9d90b3ae109138084473282c18ea162a5f8248
67 silly rollbackFailedOptional Starting
68 silly rollbackFailedOptional Finishing
69 silly runTopLevelLifecycles Finishing
70 silly install printInstalled
71 verbose stack Error: shasum check failed for C:\Users\SIREDI~1\AppData\Local\Temp\npm-7828-62e1863c\r.cnpmjs.org\ionic\download\ionic-2.2.1.tgz
71 verbose stack Expected: 2b9d90b3ae109138084473282c18ea162a5f8248
71 verbose stack Actual:   6e049e95b380f1da635acd1411d27827741afcde
71 verbose stack From:     http://r.cnpmjs.org/ionic/download/ionic-2.2.1.tgz
71 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
71 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
71 verbose stack     at emitNone (events.js:91:20)
71 verbose stack     at ReadStream.emit (events.js:185:7)
71 verbose stack     at endReadableNT (_stream_readable.js:974:12)
71 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
71 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
72 verbose cwd C:\Windows\system32
73 error Windows_NT 10.0.10240
74 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
75 error node v6.10.0
76 error npm  v3.10.10
77 error shasum check failed for C:\Users\SIREDI~1\AppData\Local\Temp\npm-7828-62e1863c\r.cnpmjs.org\ionic\download\ionic-2.2.1.tgz
77 error Expected: 2b9d90b3ae109138084473282c18ea162a5f8248
77 error Actual:   6e049e95b380f1da635acd1411d27827741afcde
77 error From:     http://r.cnpmjs.org/ionic/download/ionic-2.2.1.tgz
78 error If you need help, you may report this error at:
78 error     <https://github.com/npm/npm/issues>
79 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-03-06 16:49
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-17 03:56 UTC
Labels: bot-closed
