### ISSUE TITLE
when i do npm ls -g minimatch i can see tern is using minimatch@0.3.0 

### ISSUE THREAD

**Issue by tryko** [npm/npm#13766] opened 2016-08-25 11:37 UTC
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?
when i do npm view minimatch version i get 3.0.3
but when i do npm ls -g minimatch i see tern is using minimatch@0.3.0

#### How can the CLI team reproduce the problem?
performing sudo npm install -g tern i get the error:
```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints: v6.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: linux

EDIT: tried to fallow advices from https://github.com/npm/npm/issues/13323 didn't work

**Comment by KenanY** [comment] 2016-08-25 15:41
@tryko `npm ls` and `npm view` do completely different things. I would suggest reading the [documentation](https://docs.npmjs.com/) to find out what each do. When you run `npm view minimatch version`, you are querying the registry for the `latest` version of `minimatch`, which is `3.0.3` at the moment. When you run `npm ls -g minimatch`, you will get a dependency tree which indicates what versions of `minimatch` are present among your globally installed modules. Both of these commands are running 100% as intended and since there's no bug here I'm gonna close this. If you have any further questions, feel free to ask.

**Closed by KenanY** 2016-08-25 15:41 UTC
