### ISSUE TITLE
Extraneous global install warnings

### ISSUE THREAD

**Issue by paulmillr** [npm/npm#8887] opened 2015-07-10 02:24 UTC
Seeing these warnings pretty much on every global installation.

```
❯ npm -v
3.1.0
❯ node -v
v0.12.6
❯ npm install -g coffee-script 
/usr/local/bin/coffee -> /usr/local/lib/node_modules/coffee-script/bin/coffee
/usr/local/bin/cake -> /usr/local/lib/node_modules/coffee-script/bin/cake
/usr/local/lib
└── coffee-script@1.9.3 

npm WARN EPACKAGEJSON /usr/local/lib No description
npm WARN EPACKAGEJSON /usr/local/lib No repository field.
npm WARN EPACKAGEJSON /usr/local/lib No README data
npm WARN EPACKAGEJSON /usr/local/lib No license field.
```

**Comment by aredridel** [comment] 2015-07-10 03:24
I started getting these recently too, though on Yosemite. I think it's more an npm 3.1.0 than a MacOS thing.

**Comment by tarun** [comment] 2015-07-10 17:51
It is there with 3.1.1 too...

```
$ npm -v
3.1.1
$ node -v
v0.12.7
$ npm install -g coffee-script
/usr/local/bin/coffee -> /usr/local/lib/node_modules/coffee-script/bin/coffee
/usr/local/bin/cake -> /usr/local/lib/node_modules/coffee-script/bin/cake
/usr/local/lib
└── coffee-script@1.9.3

npm WARN EPACKAGEJSON /usr/local/lib No description
npm WARN EPACKAGEJSON /usr/local/lib No repository field.
npm WARN EPACKAGEJSON /usr/local/lib No README data
npm WARN EPACKAGEJSON /usr/local/lib No license field.
```

**Comment by iarna** [comment] 2015-07-11 02:00
It is indeed a 3.0.0 thing

**Comment by monolithed** [comment] 2015-07-14 21:15
```
➜ npm -v
3.1.2

➜ sudo npm install node-gyp -g

....

npm WARN EPACKAGEJSON /usr/local/lib No description
npm WARN EPACKAGEJSON /usr/local/lib No repository field.
npm WARN EPACKAGEJSON /usr/local/lib No README data
npm WARN EPACKAGEJSON /usr/local/lib No license field.
....
```

**Comment by jokeyrhyme** [comment] 2015-07-20 02:09
possibly duplicate: #8871

**Comment by iarna** [comment] 2015-07-27 19:55
Closing as duplicate of #8871

**Closed by iarna** 2015-07-27 19:55 UTC
Labels: bug
