### ISSUE TITLE
NPM Install command not Working on windows 10

### ISSUE THREAD

**Issue by jinkoom** [npm/npm#14028] opened 2016-09-21 19:11 UTC
I'm setting up my project space for angular JS and need to register modules with npm command.

I run the command 'npm install' on the windows command line and I get the following error:

ERR! EBUSY: resource busy or locked, rename 'C:\Users\SVR\AppData\Local\Temp\npm-9624-4023a017\registry.npmjs.org\angular2-in-memory-web-api-\angular2-in-memory-web-api-0.0.20.tgz.2031181547' -> 'C:\Users\SVR\AppData\Local\Temp\npm-9624-4023a017\registry.npmjs.org\angular2-in-memory-web-api-\angular2-in-memory-web-api-0.0.20.tgz'

I'm running windows 10.

Attached is the debug file npm-debug.log
[npm-debug.zip](https://github.com/npm/npm/files/485831/npm-debug.zip)

**Comment by jinkoom** [comment] 2016-09-23 15:49
Hi everyone,

Anyone has an idea about resolving the issue in my earlier post?

**Comment by mateodelnorte** [comment] 2016-12-30 19:22
see https://github.com/npm/npm/issues/12059

**Comment by legodude17** [comment] 2016-12-30 19:25
As @mateodelnorte says, this is a duplicate of #12059.

**Comment by tommck** [comment] 2017-06-08 14:25
something that will also potentially cause EPERM issues renaming is if this folder is "linked" (i.e. you have previously run "npm link" in this folder).

If this is the case, run "npm unlink" before running "npm install".

That removed my EPERM renaming issues

**Closed** 2017-06-16 22:34 UTC
Labels: bot-closed, support, windows
