### ISSUE TITLE
502 for https://registry.npmjs.org/bignumber.js/-/bignumber.js-1.1.1.tgz

### ISSUE THREAD

**Issue by brbester** [npm/npm#13292] opened 2016-07-06 12:45 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm install -g node-red-node-watson fails due to
https://registry.npmjs.org/bignumber.js/-/bignumber.js-1.1.1.tgz is returning 502

#### How can the CLI team reproduce the problem?

try to go to https://registry.npmjs.org/bignumber.js/-/bignumber.js-1.1.1.tgz

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by wenchaojiang** [comment] 2016-07-06 12:54
https://github.com/npm/npm/issues/13284

**Comment by othiym23** [comment] 2016-07-06 14:53
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:53 UTC
Labels: big-bug, bug, registry
