### ISSUE TITLE
`npm update --save` moves updated devDependencies into dependencies

### ISSUE THREAD

**Issue by adambuczynski** [npm/npm#11622] opened 2016-02-20 20:37 UTC
`npm update --save`

Expected behaviour: update all packages, save their new version, but keep them where they are, e.g. if a devDependency is updated, save the updated version into the devDependencies.

Actual behaviour: updates all packages and if devDependencies are updated, they are moved into the dependencies block.

I don't think this behaviour is intentional, or is it? It's very confusing, as I just want to update *all* packages, dev and regular, and save them "in place" where they are, not shuffle them around between deps and dev deps. Am I misusing the command?

**Comment by SurealCereal** [comment] 2016-04-29 18:56
Seems like a bug to me - deps really should not be moved around between blocks.

**Comment by iarna** [comment] 2016-09-21 20:50
Closing as duplicate of #10531

**Closed by iarna** 2016-09-21 20:50 UTC
Labels: bug, package-json
