### ISSUE TITLE
Add "npm exec" CLI command to run programs under ./node_modules/.bin

### ISSUE THREAD

**Issue by gajus** [npm/npm#12126] opened 2016-03-29 11:56 UTC
Certain deployment scripts require running programs that have been installed as devDependencies, e.g. my deployment script involves running webpack program:

```sh
nvm use v5.8.0;
npm set progress=false;
(cd ./src/client; npm install; NODE_ENV=production node ./node_modules/.bin/webpack --config ./webpack.config.production.js);
(cd ./src/api; npm install);
(cd ./src/bin; npm install);
pm2 delete ecosystem.json;
pm2 start ecosystem.json --env production;
```

Because webpack is installed as a devDependency, it is only available under `node ./node_modules/.bin/webpack`. The downside of this approach is that it is not cross-platform safe and the path depends on the npm version (i.e. it might change in the future versions).

Therefore, it would be nice to have `npm exec <alias name>` command, which would be equivalent to running `node ./node_modules/.bin/<alias name>`.

**Comment by gajus** [comment] 2016-03-29 12:05
This can be improved using `$(npm bin)/webpack`.

**Comment by othiym23** [comment] 2016-04-08 21:06
Closing as duplicate of #6053. This seems like it should be simple, but due to npm's baroque command-line argument handling, it's really not. If you want a standalone tool that gives you a lot of the power of this command, take a look at @timoxley's [`npm-run`](http://npm.im/npm-run). Thanks for your time!

**Closed by othiym23** 2016-04-08 21:06 UTC
Labels: feature-request
