### ISSUE TITLE
`npm show npm man` contains the `$HOME` of whoever did the release

### ISSUE THREAD

**Issue by ljharb** [npm/npm#17138] opened 2017-06-11 21:06 UTC
`npm show npm man`, `npm show npm@4 man`, etc.

I'm not sure what this information is useful for - but if it is useful, then I assume individual's home dirs shouldn't appear there, and if it's not useful, then the information shouldn't appear at all.

(This isn't a bug or anything, I just noticed it in the `npm show` output and wanted to throw it over the wall)

**Comment by kenany** [comment] 2017-06-11 23:22
Closing as a duplicate of https://github.com/npm/npm/issues/14541.

**Closed as completed by kenany** 2017-06-11 23:22 UTC
