### ISSUE TITLE
Throwing Unexpected Token in NPM install

### ISSUE THREAD

**Issue by TimothyDalbey** [npm/npm#12240] opened 2016-04-06 17:50 UTC
```
npm http GET https://registry.npmjs.org/commander/-/commander-2.3.0.tgz
npm ERR! SyntaxError: Unexpected token 
npm ERR! �TK��0�+��Uᕜr�a[�=T�^����΂�l�����;�ɣ���^������
Y�#(ͥ@KD#�E� 57RMd�J�4�������]��                        �D�ȎTP�
                               Z�>8r[�����ե6��D]*>�{�u
                                                      �p�,F�;n&���I�J���+�NZz>yZ6�V*Kj����Ń���Me;�`4��[�����V�-�eSJa/F��E����L���
�/�n:��                                                                                                                          ;t�l���
��(=�Ґn�J/˖��;�������ЃF������;�5� ����p4��Gf?l��R�gy�{z��xF|l���&m�8��(*�r��*��bV5�Q9K3��Mb����ce���k=�h����XUߒ�p���s�󗡾]K>����Ǡ:��$��6)�l]�
                                                                                                                                           Ro�0M��&+�$��Ͷb�j��M��,�����d4vV����5���_��w�{7Rp�?���v��G���5�������%�����f�*py��a�4XNM5<h*U���ʿW�e�4?ݒp%.�ߠ��⥊b�
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.1.17-boot2docker
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mocha"
npm ERR! cwd /
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
```

**Comment by KenanY** [comment] 2016-04-06 17:56
Looks like https://github.com/npm/npm/issues/12196.

**Comment by othiym23** [comment] 2016-04-06 18:12
Closing as a duplicate of #12196. See that issue for details and context – the npm registry team is working on resolving this issue on npm's end. A quick way to work around the problem for you would be to update your Dockerfile to use a newer build of both Node and npm (I suggest switching to `alpine-node` as a base image), which is a good idea anyway given that Node 0.10 is approaching the end of maintenance (and `npm@1.3` has been unsupported by the npm CLI team for several years now). Thanks for your time!

**Closed by othiym23** 2016-04-06 18:12 UTC
Labels: registry, support
