### ISSUE TITLE
npm install cordova -g doesn't works

### ISSUE THREAD

**Issue by dacas84** [npm/npm#15986] opened 2017-03-09 02:38 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have tried to install cordova and ionic but it hasn't been posible yet.
#### How can the CLI team reproduce the problem?

when I execute the command npm install cordova -g or  npm install cordova -g or npm install ionic cordova -g it try to get all the files required for installation but then it get stucked in:

npm ERR! shasum check failed for C:\Users\Hogar\AppData\Local\Temp\npm-6424-9a2f5bdb\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.11.0.tgz
npm ERR! Expected: 9214feb9dd713ca481a1cbabceeca60966c1c0cf
npm ERR! Actual:   2022c11c92507a216e0f634b83b65705b385667e
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz

thus I can't install.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: windows
 - Network issues:
   - Geographic location where npm was run: Venezuela
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by stripedpajamas** [comment] 2017-03-09 15:48
Hello! This looks like a duplicate of #14626. Try updating to the latest version of npm.

**Comment by dacas84** [comment] 2017-03-09 20:16
Thanks for responding Peter, I have resolved the problem doing the installation in this order:


npm install cordova -g


then


npm install ionic -g



Danny Castillo


________________________________
De: Peter Squicciarini <notifications@github.com>
Enviado: jueves, 09 de marzo de 2017 03:49 p.m.
Para: npm/npm
Cc: dacas84; Author
Asunto: Re: [npm/npm] npm install cordova -g doesn't works (#15986)


Hello! This looks like a duplicate of #14626<https://github.com/npm/npm/issues/14626>. Try updating to the latest version of npm.

**Comment by KenanY** [comment] 2017-03-13 13:08
Closing as resolved.

**Closed by KenanY** 2017-03-13 13:08 UTC
