### ISSUE TITLE
Out of JavaScript Heap Memory

### ISSUE THREAD

**Issue by jake32321** [npm/npm#13196] opened 2016-06-27 15:29 UTC
I received this issue when searching for a module.  Not sure if this is something on my end or somewhere within NPM.

![capture](https://cloud.githubusercontent.com/assets/7380109/16385311/e44c51ee-3c51-11e6-8077-20ecb1c21720.PNG)

**Comment by adam66** [comment] 2016-06-28 15:28
I get the same error with the same command, using a newly installed node.js with npm v 3.10.2 on Win7 and after running 'npm cache clean'.

**Comment by othiym23** [comment] 2016-06-28 16:04
Closing as duplicate of #12619.

**Closed by othiym23** 2016-06-28 16:04 UTC
Labels: big-bug, bug, search, support
