### ISSUE TITLE
Registry error building local index for the first time ("npm search")

### ISSUE THREAD

**Issue by laura-stone** [npm/npm#7178] opened 2015-01-20 15:55 UTC
NOTE: I have changed the registry to pull from http:// instead of https, which results in no output in console.
Below is a truncated output:

```
~$ sudo npm search
Password:
npm WARN Building the local index for the first time, please be patient
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected end of input
npm ERR! {"_updated":1421768968810,"0":{"name":"0","dist-tags":{"latest":"0.0.0"},"maintainers":address [TRUNCATED REPO INFO HERE]
ame":"amqp-retry","description":"Requeue messages with exponential delay","dist-tags":{"latest":"0.0.7"},"maintainers":[{"name":"lennon","email":"madbence@gmail.com"}],"author":{"name":"Purpose Industries","email":"dev@purposeindustries.co"},"repository":{"type":"git","url":"git@github.com:purposeindustries/node-amqp-retry.git"},"time":{"modified":"2013-12-20T11:46:20.491Z"},"versions":{"0.0.7":"latest"},"keywords":["amqp","rabbitmq"]},"amqp-route":{"name":"amqp-route","description":"Data Routing Helpers for AMQP","dist-tags":{"latest":"1.1.0"},"maintainers":[{"name":"typeduck","email":"typeduck@typeduck.net"}],"homepage":"https://github.com/typeduck/amqp-route","keywords":["amqp","routing","templates"],"repository":{"type":"git","url":"https://github.com/typeduck/amqp-route.git"},"author":{"name":"Ruquay K Calloway"},"bugs":{"url":"https://github.com/typeduck/amqp-route/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-12-03T19:07:41.549Z"},"versions":{"1.1.0":"latest"}},"amqp-rpc":{"name":"amqp-rpc","description":"AMQP RPC driver for node.js","dist-tags":{"latest":"0.0.8"},"maintainers":[{"name":"goldix","email":"it-bm@mail.ru"}],"author":{"name":"Eugene Demchenko"},"repository":{"type":"git","url":"git://github.com/demchenkoe/node-amqp-rpc.git"},"homepage":"https://github.com/demchenkoe/node-amqp-rpc","keywords":["amqp","rpc"],"bugs":{"url":"http://github.com/demchenkoe/node-amqp-rpc/issues"},"readmeFilename":"README.md","time":{"modified":"2014-05-07T15:40:27.535Z"},"versions":{"0.0.8":"latest"}},"amqp-rpc-factory":{"name":"amqp-rpc-factory","description":"Node.js AMQP RPC Consumer and Publisher Factory","dist-tags":{"latest":"0.2.2"},"maintainers":[{"name":"rudijs","email":"ooly.me@gmail.com"}],"homepage":"https://github.com/rudijs/amqp.node-rpc-factory","keywords":["AMQP","AMQP 0-9-1","RabbitMQ","RPC"],"repository":{"type":"git","url":"https://github.com/rudijs/amqp.node-rpc-factory.git"},"author":{"name":"Rudi Starcevic","email":"ooly.me@gmail.com"},"bugs":{"url":"https://github.com/rudijs/amqp.node-rpc-factory/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-10-28T06:48:07.874Z"},"versions":{"0.2.2":"latest"}},"amqp-schedule":{"name":"amqp-schedule","description":"Schedule jobs with `amqp`","dist-tags":{"latest":"0.0.5"},"maintainers":[{"name":"lennon","email":"madbence@gmail.com"}],"author":{"name":"Purpose Industries","email":"dev@purposeindustries.co"},"repository":{"type":"git","url":"https://github.com/purposeindustries/node-amqp-schedule.git"},"time":{"modified":"2013-12-19T13:32:31.245Z"},"versions":{"0.0.5":"latest"},"keywords":["amqp","rabbitmq","scheduler"]},"amqp-sqs":{"name":"amqp-sqs","description":"AMQP facade for SQS","dist-tags":{"latest":"0.7.0"},"maintainers":[{"name":"markbirbeck","email":"mark.birbeck@gmail.com"}],"readmeFilename":"README.md","time":{"modified":"2014-01-30T23:46:45.295Z"},"versions":{"0.7.0":"latest"},"repository":{"type":"git","url":"git://github.com/markbirbeck/amqp-sqs"},"keywords":["amqp","aws","sqs"]},"amqp-stats":{"name":"amqp-stats","description":"Interface for RabbitMQ Management statistics. http://www.rabbitmq.com/management.html","dist-tags":{"latest":"0.0.14"},"maintainers":[{"name":"timisbusy","email":"timisbusy@gmail.com"},{"name":"flybyme","email":"price.timmy@gmail.com"}],"author":{"name":"Tim Atkinson","email":"tim@gochime.com","url":"http://timisbusy.com"},"repository":{"url":"https://github.com/timisbusy/node-amqp-stats"},"users":{"fgribreau":true},"readmeFilename":"README.md","homepage":"https://github.com/timisbusy/node-amqp-stats","bugs":{"url":"https://github.com/timisbusy/node-amqp-stats/issues"},"time":{"modified":"2014-08-14T14:25:30.278Z"},"versions":{"0.0.14":"latest"}},"amqp-stream":{"name":"amqp-stream","description":"Stream interface to node's AMQP driver","dist-tags":{"latest":"0.1.0"},"maintainers":[{"name":"jasonpincin","email":"jason@pincin.com"}],"author":{"name":"Jason Pincin"},"repository":{"type":"git","url":"git://github.com/jasonpincin/node-amqp-stream.git"},"time":{"modified":"2012-10-28T18:22:07.781Z"},"versions":{"0.1.0":"latest"},"keywords":["amqp","stream"]},"amqp-stream-cli":{"name":"amqp-stream-cli","maintainers":[{"name":"petrofeed","email":"ops@petrofeed.com"}],"dist-tags":{"latest":"0.1.2"},"description":"Stream data to an AMQP server from the command-line.","homepage":"http://petrofeed.com","repository":{"type":"git","url":"git@github.com:PetroFeed/amqp-stream-cli.git"},"author":{"name":"PetroFeed Inc."},"bugs":{"url":"https://github.com/PetroFeed/amqp-stream-cli/issues"},"readmeFilename":"README.md","time":{"modified":"2014-10-22T23:27:43.472Z"},"versions":{"0.1.2":"latest"}},"amqp-tool":{"name":"amqp-tool","description":"Rabbitmq-tool - import/export data from a RabbitMQ broker","dist-tags":{"latest":"0.0.8"},"maintainers":[{"name":"fgribreau","email":"npm@fgribreau.com"}],"author":{"name":"Francois-Guillaume Ribreau","email":"npm@fgribreau.com","url":"http://fgribreau.com"},"repository":{"type":"git","url":"git://github.com/FGRibreau/node-amqp-tool.git"},"time":{"modified":"2013-07-01T08:31:40.702Z"},"versions":{"0.0.8":"latest"},"keywords":["amqp","rabbitmq","tool","export","import"]},"amqp-topic-pub-consume":{"name":"amqp-topic-pub-consume","description":"Simple lib to listen/send to a Message queue","dist-tags":{"latest":"0.0.1"},"maintainers":[{"name":"smlgbl","email":"smlgbl@gmail.com"}],"readmeFilename":"README.md","keywords":["amqp publish message queue consume"],"repository":{"type":"git","url":"http://github.com/smlgbl/amqp-topic-pub-consume.git"},"author":{"name":"Samuel Gabel","email":"smlgbl@gmail.com"},"bugs":{"url":"https://github.com/smlgbl/amqp-topic-pub-consume/issues"},"license":"MIT","time":{"modified":"2014-04-09T20:40:43.479Z"},"versions":{"0.0.1":"latest"}},"amqp-transport":{"name":"amqp-transport","description":"a winston transport using amqp","dist-tags":{"latest":"0.0.5"},"maintainers":[{"name":"oneminute","email":"oneminute3b@gmail.com"}],"author":{"name":"haoxin"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-09-11T08:34:15.258Z"},"versions":{"0.0.5":"latest"}},"amqp-uri":{"name":"amqp-uri","description":"creates an AMQP URI from a JS object","dist-tags":{"latest":"0.4.0"},"maintainers":[{"name":"quim","email":"joaquim.serafim@gmail.com"}],"homepage":"https://github.com/joaquimserafim/amqp-uri","keywords":["amqp","uri","format","create","object"],"author":{"name":"@joaquimserafim"},"bugs":{"url":"https://github.com/joaquimserafim/amqp-uri/issues"},"license":"ISC","readmeFilename":"README.md","repository":{"type":"git","url":"https://github.com/joaquimserafim/amqp-uri"},"time":{"modified":"2015-01-12T19:54:35.703Z"},"versions":{"0.4.0":"latest"}},"amqp-util":{"name":"amqp-util","description":"Convenience classes on which to build AMQP producers and consumers in Node.js.","dist-tags":{"latest":"0.1.1"},"maintainers":[{"name":"intellinote","email":"rod@intellinote.net"}],"homepage":"https://github.com/intellinote/amqp-util","repository":{"type":"git","url":"https://github.com/intellinote/amqp-util.git"},"author":{"name":"Intellinote","email":"https://www.intellinote.net/"},"bugs":{"url":"https://github.com/intellinote/amqp-util/issues"},"license":"MIT","readmeFilename":"README.md","users":{"intellinote":true,"rodw":true},"time":{"modified":"2014-10-07T00:05:04.796Z"},"versions":{"0.1.1":"latest"}},"amqp-vent":{"name":"amqp-vent","maintainers":[{"name":"gonzohunter","email":"colin.hemmings@gmail.com"}],"dist-tags":{"latest":"0.0.7"},"description":"PubSub message bus over rabbitmq","repository":{"url":"https://github.com/dataloop/vent"},"author":{"name":"Colin Hemmings","email":"colin.hemmings@dataloop.io","url":"www.dataloop.io"},"readmeFilename":"README.md","homepage":"https://github.com/dataloop/vent","bugs":{"url":"https://github.com/dataloop/vent/issues"},"time":{"modified":"2014-08-14T13:06:37.652Z"},"versions":{"0.0.7":"latest"}},"amqp-watcher":{"name":"amqp-watcher","description":"A tool to get and send messages from an amqp server from the command line","dist-tags":{"latest":"0.0.2"},"maintainers":[{"name":"killfill","email":"pneumann@gmail.com"}],"author":{"name":"Phillip Neumann","email":"pneumann@gmail.com"},"repository":{"type":"git","url":"git://github.com/killfill/amqp-watcher.git"},"time":{"modified":"2012-03-23T02:34:53.597Z"},"versions":{"0.0.2":"latest"},"keywords":["cli","amqp","rabbitmq","log","see","watcher"]},"amqp-website-capturer":{"name":"amqp-website-capturer","time":{"modified":"2014-04-30T03:32:40.012Z"}},"amqp-winston":{"name":"amqp-winston","description":"Winston logging transport for AMQP","dist-tags":{"latest":"1.0.0"},"maintainers":[{"name":"matatbread","email":"npm@mailed.me.uk"}],"homepage":"https://github.com/MailOnline/winston-amqp","keywords":["winston","logging","AMQP","RabbitMQ"],"repository":{"type":"git","url":"https://github.com/MailOnline/winston-amqp"},"author":{"name":"matthew.woolf@mailonline.co.uk"},"bugs":{"url":"https://github.com/MailOnline/winston-amqp/issues"},"license":"ISC","readmeFilename":"README.md","time":{"modified":"2015-01-20T13:24:38.208Z"},"versions":{"1.0.0":"latest"}},"amqp-wrapper":{"name":"amqp-wrapper","description":"A wrapper around https://github.com/squaremo/amqp.node to make consuming and publishing dead easy.","dist-tags":{"latest":"4.1.4"},"maintainers":[{"name":"timlesallen","email":"allen.timothy.email@gmail.com"}],"homepage":"https://github.com/noblesamurai/node-amqp-wrapper","keywords":["amqp","wrapper","rabbitmq"],"repository":{"type":"git","url":"https://github.com/noblesamurai/node-amqp-wrapper"},"author":{"name":"Timothy Leslie Allen","email":"allen.timothy.email@gmail.com","url":"https://github.com/timlesallen"},"bugs":{"url":"https://github.com/noblesamurai/node-amqp-wrapper/issues"},"license":"BSD","readmeFilename":"README.md","time":{"modified":"2015-01-12T02:31:08.428Z"},"versions":{"4.1.4":"latest"}},"amqp.channel":{"name":"amqp.channel","maintainers":[{"name":"jcready","email":"jcready@gmail.com"},{"name":"ngpvan","email":"matkins@ngpvan.com"}],"dist-tags":{"latest":"0.0.8"},"description":"A simplified way to setup an AMQP connection/channel with amqplib","homepage":"https://github.com/NGPVAN/amqp.channel","keywords":["rabbitmq","amqp"],"repository":{"type":"git","url":"https://github.com/NGPVAN/amqp.channel.git"},"author":{"name":"NGPVAN"},"bugs":{"url":"https://github.com/NGPVAN/amqp.channel/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-11-03T23:47:41.778Z"},"versions":{"0.0.8":"latest"}},"amqp2solr":{"name":"amqp2solr","description":"Pulls from an AMQP queue and pushes to Solr","dist-tags":{"latest":"0.0.8"},"maintainers":[{"name":"ifroz","email":"ifrozen@gmail.com"}],"author":{"name":"ifroz"},"license":"ISC","readmeFilename":"README.md","time":{"modified":"2014-10-18T13:47:25.242Z"},"versions":{"0.0.8":"latest"}},"amqpea":{"name":"amqpea","description":"Easy Peasy AMQP","dist-tags":{"latest":"0.3.2"},"maintainers":[{"name":"glenjamin","email":"glenjamin@gmail.com"}],"author":{"name":"Glen Mailer","email":"glenjamin@gmail.com"},"license":"BSD-3","readmeFilename":"README.md","time":{"modified":"2015-01-19T15:29:15.511Z"},"versions":{"0.3.2":"latest"}},"amqpjs":{"name":"amqpjs","description":"wraps the connection object from amqp.node/callback_api module to a simple way to be used","dist-tags":{"latest":"1.3.6"},"maintainers":[{"name":"quim","email":"joaquim.serafim@gmail.com"}],"author":{"name":"@joaquimserafim"},"license":"ISC","readmeFilename":"README.md","homepage":"https://github.com/joaquimserafim/amqpjs","keywords":["amqp","rabbitmq"],"repository":{"type":"git","url":"https://github.com/joaquimserafim/amqpjs"},"bugs":{"url":"https://github.com/joaquimserafim/amqpjs/issues"},"time":{"modified":"2015-01-13T17:36:31.490Z"},"versions":{"1.3.6":"latest"}},"amqplib":{"name":"amqplib","description":"An AMQP 0-9-1 (e.g., RabbitMQ) library and client.","dist-tags":{"latest":"0.3.0"},"maintainers":[{"name":"squaremo","email":"mikeb@squaremobius.net"}],"author":{"name":"Michael Bridgen","email":"mikeb@squaremobius.net"},"repository":{"type":"git","url":"https://github.com/squaremo/amqp.node.git"},"users":{"djensen47":true,"magomogo":true,"nekinie":true,"sherrman":true,"olamedia":true,"pihizi":true},"readmeFilename":"README.md","homepage":"http://squaremo.github.io/amqp.node/","keywords":["AMQP","AMQP 0-9-1","RabbitMQ"],"bugs":{"url":"https://github.com/squaremo/amqp.node/issues"},"license":"MIT","time":{"modified":"2014-10-21T08:31:17.811Z"},"versions":{"0.3.0":"latest"}},"amqplib-easy":{"name":"amqplib-easy","description":"Simplified API for interacting with AMQP","dist-tags":{"latest":"2.0.0"},"maintainers":[{"name":"lanetix","email":"engineering@lanetix.com"}],"homepage":"https://github.com/lanetix/node-lanetix-amqp-easy","keywords":["amqp","promise","easy"],"repository":{"type":"git","url":"https://github.com/lanetix/node-lanetix-amqp-easy"},"author":{"name":"Mike Atkins"},"bugs":{"url":"https://github.com/lanetix/node-lanetix-amqp-easy/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2015-01-19T15:32:32.505Z"},"versions":{"2.0.0":"latest"}},"amqplib-retry":{"name":"amqplib-retry","description":"Retry failed attempts to consume a message, with increasing delays between each attempt.","dist-tags":{"latest":"1.0.2"},"maintainers":[{"name":"lanetix","email":"engineering@lanetix.com"}],"homepage":"https://github.com/lanetix/node-amqplib-retry/","keywords":["amqplib","rabbitmq","message","queue","retry"],"repository":{"type":"git","url":"git://github.com/lanetix/node-amqplib-retry.git"},"author":{"name":"Lanetix","email":"engineering@lanetix.com","url":"https://github.com/lanetix/"},"bugs":{"url":"https://github.com/lanetix/node-amqplib-retry/issues"},"readmeFilename":"README.md","time":{"modified":"2015-01-04T08:51:42.292Z"},"versions":{"1.0.2":"latest"}},"amqpsnoop":{"name":"amqpsnoop","description":"snoop AMQP messages","dist-tags":{"latest":"0.2.0"},"maintainers":[{"name":"dap","email":"dap@cs.brown.edu"}],"author":{"name":"Dave Pacheco","email":"dap@cs.brown.edu"},"repository":{"type":"git","url":"git://github.com/davepacheco/node-amqpsnoop.git"},"time":{"modified":"2012-10-10T04:07:29.820Z"},"versions":{"0.2.0":"latest"},"keywords":["amqp","snoop","command","tool"]},"amqputil":{"name":"amqputil","description":"A thin wrapper around the amqp node module","dist-tags":{"latest":"0.0.23"},"maintainers":[{"name":"mindflash","email":"npmjs@mindflash.com"}],"author":{"name":"Mindflash"},"repository":{"type":"git","url":"git@github.com:Mindflash/amqpUtil.git"},"homepage":"https://github.com/Mindflash/amqpUtil","bugs":{"url":"https://github.com/Mindflash/amqpUtil/issues"},"license":"X11","readmeFilename":"README.md","time":{"modified":"2014-10-13T21:53:28.874Z"},"versions":{"0.0.23":"latest"}},"amqpworkers":{"name":"amqpworkers","description":"amqpworkers","dist-tags":{"latest":"0.0.3"},"maintainers":[{"name":"lights-of-apollo","email":"james@lightsofapollo.com"}],"author":{"name":"James Lal [:lightsofapollo]"},"repository":{"type":"git","url":"git://github.com/lightsofapollo/amqpworkers.git"},"homepage":"https://github.com/lightsofapollo/amqpworkers","bugs":{"url":"https://github.com/lightsofapollo/amqpworkers/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-03-05T00:36:46.065Z"},"versions":{"0.0.3":"latest"}},"amr":{"name":"amr","description":"Amr 打包工具","dist-tags":{"latest":"0.0.1"},"maintainers":[{"name":"alexyan","email":"5918760@gmail.com"}],"homepage":"https://github.com/alexyan/amr","keywords":["amr"],"repository":{"type":"git","url":"git@github.com:alexyan/amr.git"},"author":{"name":"alexyan"},"bugs":{"url":"https://github.com/alexyan/amr/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-05-17T11:45:13.755Z"},"versions":{"0.0.1":"latest"}},"amrio-seajs-builder":{"name":"amrio-seajs-builder","maintainers":[{"name":"amrio","email":"416995050@qq.com"}],"dist-tags":{"latest":"0.0.10"},"description":"seajs module builder","homepage":"https://github.com/amriogit/amrio-seajs-builder","keywords":["seajs","seajs-build","seajs-builder","grunt-cmd-transport","grunt-cmd-concat"],"repository":{"type":"git","url":"https://github.com/amriogit/amrio-seajs-builder.git"},"author":{"name":"amrio"},"bugs":{"url":"https://github.com/amriogit/amrio-seajs-builder/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-12-04T02:21:39.523Z"},"versions":{"0.0.10":"latest"}},"amrio-watcher":{"name":"amrio-watcher","maintainers":[{"name":"amrio","email":"amriogm@gmail.com"}],"dist-tags":{"latest":"0.0.6"},"description":"file watcher","homepage":"https://github.com/amriogit/amrio-watcher","keywords":["watcher"],"repository":{"type":"git","url":"https://github.com/amriogit/amrio-watcher.git"},"author":{"name":"Amrio"},"bugs":{"url":"https://github.com/amriogit/amrio-watcher/issues"},"license":"ISC","readmeFilename":"README.md","time":{"modified":"2014-07-19T14:50:52.323Z"},"versions":{"0.0.6":"latest"}},"amrophic-mandrill":{"name":"amrophic-mandrill","time":{"modified":"2014-06-10T19:53:49.317Z"}},"ams":{"name":"ams","description":"ams - asset management system - plugin enabled build tool with jquery like API","dist-tags":{"latest":"0.2.10"},"maintainers":[{"name":"kof","email":"oleg008@gmail.com"}],"author":{"name":"Oleg Slobodskoi","email":"oleg008@gmail.com"},"repository":{"type":"git","url":"git://github.com/kof/node-ams.git"},"users":{"leesei":true},"readmeFilename":"readme.md","homepage":"https://github.com/kof/node-ams","keywords":["build","tool","static server","minify","minifier","compressor","processor","base64","cssmin","uglifyjs","vendor css","amd","transport","dependencies manager"],"bugs":{"url":"https://github.com/kof/node-ams/issues"},"time":{"modified":"2014-03-06T17:18:32.069Z"},"versions":{"0.2.10":"latest"}},"amt":{"name":"amt","description":"Node API for Amazon Mechanical Turk","dist-tags":{"latest":"0.1.4"},"maintainers":[{"name":"volox","email":"voloxxx@gmail.com"}],"author":{"name":"Riccardo Volonterio","email":"voloxxx@gmail.com"},"repository":{"type":"git","url":"https://github.com/Volox/amt"},"homepage":"https://github.com/Volox/amt","bugs":{"url":"https://github.com/Volox/amt/issues"},"readmeFilename":"README.md","time":{"modified":"2014-08-13T14:01:49.344Z"},"versions":{"0.1.4":"latest"}},"amtoolbelt":{"name":"amtoolbelt","time":{"modified":"2014-06-19T18:54:18.573Z"}},"amui-hbs-helper":{"name":"amui-hbs-helper","description":"Amaze UI widget partials and helpers.","dist-tags":{"latest":"1.0.2"},"maintainers":[{"name":"minwe","email":"hegfirose@gmail.com"}],"homepage":"http://amazeui.org/widgets","keywords":["AMUI","AmazeUI","handlebars","AllMobilize"],"repository":{"type":"git","url":"https://github.com/amazeui/hbs-helper"},"author":{"name":"minwe","email":"minwe@yunshipei.com"},"bugs":{"url":"https://github.com/amazeui/hbs-helper/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-09-28T08:50:15.637Z"},"versions":{"1.0.2":"latest"}},"amulet":{"name":"amulet","description":"As-soon-as-possible streaming async mustache templating","dist-tags":{"latest":"1.0.7"},"maintainers":[{"name":"chbrown","email":"io@henrian.com"}],"author":{"name":"Christopher Brown","email":"io@henrian.com","url":"http://henrian.com"},"repository":{"type":"git","url":"git://github.com/chbrown/amulet.git"},"time":{"modified":"2014-01-14T03:24:23.968Z"},"versions":{"1.0.7":"latest"},"keywords":["template","mustache","mu","asynchronous","streaming","nodeps"]},"amygdala":{"name":"amygdala","description":"RESTful HTTP library for JavaScript powered web applications","dist-tags":{"latest":"0.4.2"},"maintainers":[{"name":"mlouro","email":"marco@lincolnloop.com"}],"homepage":"https://github.com/lincolnloop/amygdala","keywords":["REST","client","http","API","localStorage","store","browser","library","cache","ajax","offline"],"repository":{"type":"git","url":"git://github.com/lincolnloop/amygdala.git"},"author":{"name":"Marco Louro","email":"marco@lincolnloop.com","url":"http://lincolnloop.com"},"bugs":{"url":"https://github.com/lincolnloop/amygdala/issues"},"readmeFilename":"README.md","users":{"tarcio":true},"time":{"modified":"2014-11-21T00:50:00.158Z"},"versions":{"0.4.2":"latest"}},"amz":{"name":"amz","description":"Amazon EC2 cli on coffee-script","dist-tags":{"latest":"0.4.5"},"maintainers":[{"name":"selead","email":"allselead@gmail.com"}],"author":{"name":"Temnov Kirill, @selead"},"repository":{"type":"git","url":"https://github.com/selead/amz"},"time":{"modified":"2012-11-06T12:26:34.111Z"},"versions":{"0.4.5":"latest"},"keywords":["amazon","ec2","cli"]},"amz-products":{"name":"amz-products","description":"A thin wrapper for the Amazon Products API, supporting all methods on the API.","dist-tags":{"latest":"0.0.2"},"maintainers":[{"name":"jwd2a","email":"justin@maderalabs.com"}],"author":{"name":"Justin Davis","url":"http://justindavis.co"},"license":"ISC","readmeFilename":"README.md","homepage":"https://github.com/fetchlogic/amz-products","keywords":["amazon","products api","amazon product advertising api"],"repository":{"type":"git","url":"https://github.com/fetchlogic/amz-products"},"bugs":{"url":"https://github.com/fetchlogic/amz-products/issues"},"time":{"modified":"2014-12-06T20:54:36.823Z"},"versions":{"0.0.2":"latest"}},"an":{"name":"an","description":"Angular + NPM: Publish your AngularJS modules to npm","maintainers":[{"name":"anvaka","email":"anvaka@gmail.com"}],"dist-tags":{"latest":"0.0.7"},"readmeFilename":"README.md","author":{"name":"Andrei Kashcha"},"repository":{"type":"git","url":"https://github.com/anvaka/an"},"homepage":"https://github.com/anvaka/an","bugs":{"url":"https://github.com/anvaka/an/issues"},"license":"MIT","time":{"modified":"2014-09-09T06:46:03.527Z"},"versions":{"0.0.7":"latest"}},"an-array":{"name":"an-array","description":"Check if an object is an array or a typed array","dist-tags":{"latest":"1.0.0"},"maintainers":[{"name":"hughsk","email":"hughskennedy@gmail.com"}],"homepage":"https://github.com/hughsk/an-array","keywords":["typed","array","check","class","float32array","instance","is"],"repository":{"type":"git","url":"git://github.com/hughsk/an-array.git"},"author":{"name":"Hugh Kennedy","email":"hughskennedy@gmail.com","url":"http://hughsk.io/"},"bugs":{"url":"https://github.com/hughsk/an-array/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-11-03T11:08:26.421Z"},"versions":{"1.0.0":"latest"}},"an-array-of-english-words":{"name":"an-array-of-english-words","description":"An array of ~275,000 English words. Work with Node and Browserify.","dist-tags":{"latest":"1.0.0"},"maintainers":[{"name":"zeke","email":"zeke@sikelianos.com"}],"homepage":"https://github.com/zeke/an-array-of-english-words","repository":{"type":"git","url":"https://github.com/zeke/an-array-of-english-words"},"author":{"name":"zeke"},"bugs":{"url":"https://github.com/zeke/an-array-of-english-words/issues"},"license":"MIT","readmeFilename":"README.md","users":{"stany":true},"time":{"modified":"2014-09-01T14:52:29.147Z"},"versions":{"1.0.0":"latest"}},"an-async":{"name":"an-async","description":"Checks if the given API is an async or not.","dist-tags":{"latest":"0.1.0"},"maintainers":[{"name":"hemanth","email":"hemanth.hm@gmail.com"}],"homepage":"https://github.com/hemanth/node-an-async","keywords":["async","check"],"repository":{"type":"git","url":"https://github.com/hemanth/node-an-async.git"},"author":{"name":"Hemanth.HM"},"bugs":{"url":"https://github.com/hemanth/node-an-async/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-03-30T06:04:27.356Z"},"versions":{"0.1.0":"latest"}},"an-illusion":{"name":"an-illusion","description":"Intuition API emulation and documentation.","dist-tags":{"latest":"0.1.2"},"maintainers":[{"name":"hackliff","email":"xavier.bruhiere@gmail.com"}],"homepage":"https://github.com/intuition-io/illusion","keywords":["api","fake","nodejs","tool"],"repository":{"type":"git","url":"https://github.com/intuition-io/illusion"},"author":{"name":"Xavier Bruhiere","email":"xavier.bruhiere@gmail.com"},"bugs":{"url":"https://github.com/intuition-io/illusion/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-09-30T22:28:17.012Z"},"versions":{"0.1.2":"latest"}}
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:23)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "search"
npm ERR! cwd /Users/lstone
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! type unexpected_eos
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/lstone/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment] 2015-01-21 13:33
Unfortunately the `npm search` command is not very usable at present (for a number of reasons, chiefly because it was designed when there were between 100 and 1000 packages in the `npm` repository, and there are now over 100,000).

For the moment, can you work around this by using the online search form at <https://nodejs.com> ?

By the way, there have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`

Thanks!

**Comment by smikes** [comment] 2015-01-28 22:58
I'm working on a replacement for `npm search` -- it's <https://github.com/smikes/npm-kludge-search>

You can try it out like this:

```
npm install -g npm-kludge-search@latest
npm-kludge-search grunt
```

**Comment by laura-stone** [comment] 2015-01-29 01:31
Awesome - thanks! I ended up updating npm and used the online search as you instructed.

Will try out kluge-search, too.

**Comment by othiym23** [comment] 2015-02-21 07:59
Closing as resolved / duplicate of other issues / known issue.

**Closed by othiym23** 2015-02-21 07:59 UTC
Labels: bug
