### ISSUE TITLE
Must call `npm install` twice to get all the dependencies pulled down

### ISSUE THREAD

**Issue by JoeCianflone** [npm/npm#10727] opened 2015-12-07 14:42 UTC
This is a strange one.  I was updating my version of handlebars to the latest and I created a simple bash script for the rest of my team to use.  However, there's an issue whereby you need to call `npm install` twice in order to pull down all the dependencies.  So here's everything I've got:

My package.json file: https://gist.github.com/JoeCianflone/ea7ceffacd7a2aab36ab#file-package-json
My update script: https://gist.github.com/JoeCianflone/ea7ceffacd7a2aab36ab#file-update-sh
and the error I get when running gulp compile which indicates that gulp is missing a dependency: https://gist.github.com/JoeCianflone/ea7ceffacd7a2aab36ab#file-error-sh

I have tried moving the `npm install` to the end of the file, I've done this manually multiple times and I can always recreate this error.  I'm running npm 3.3.12 and I'm on OSX 10.11 using the built in terminal.  If you need any more info please let me know.

**Comment by callmevlad** [comment] 2015-12-08 06:05
@JoeCianflone Can you reproduce in the latest [3.5.1](https://github.com/npm/npm/releases/tag/v3.5.1) version?

**Comment by JoeCianflone** [comment] 2015-12-08 15:32
@callmevlad yes.  I just updated this morning and I get the exact same error.

**Comment by othiym23** [comment] 2015-12-17 00:01
This is a great test case, by which I mean I have no idea what's causing this behavior. It may be a few weeks until we get a chance to dig into this in more detail, but this is definitely a bug. Thanks for your time, and thanks for including a repro case!

**Comment by stanjer** [comment] 2015-12-28 10:34
+1 with npm 3.3.12 (node 5.1.0). Not reproducing on 3.5.*, but we are not using node 4.*

**Comment by tkalfigo** [comment] 2015-12-28 10:42
+1 node v5.1.0 (npm v3.3.12). Second `npm install` installs dependencies correctly (e.g. first npm install didn't install lodash fully, but second one did).

**Comment by bagusflyer** [comment] 2015-12-30 13:58
Got exactly the same issue. npm version is 3.3.8, node version is 0.12.7.

**Comment by bdefore** [comment] 2015-12-30 14:51
Also getting failures on first install once in a while (npm 3.3.12, node 5.2.0). Here's an example failure, followed by success running again: https://gist.github.com/bdefore/8150f341727a5d8f0423 ... after removing node_modules and trying again, I get an error about esprima not being available, which is listed as a dependency of webpack and should have been installed https://gist.github.com/bdefore/5c1f74ec73a492579cd3

**Comment by bagusflyer** [comment] 2015-12-30 16:50
I reinstalled node. Still got the same error. My node is 4.2.4, npm is 2.14.12.

**Comment by bagusflyer** [comment] 2016-01-07 03:26
My node 5.3.0, npm 3.3.12 got the same problem.

**Comment by dustinsmith1024** [comment] 2016-01-08 16:15
Same here on 5.3 and 3.3.12. If the log helps: https://gist.github.com/dustinsmith1024/cfcf983ed37c77d38620

Tried to run on the latest npm but ran into some other error.

**Comment by DannyDelott** [comment] 2016-01-08 19:32
Same issue on node v5.4.0 and npm 3.3.12.

**Comment by Jarlotee** [comment] 2016-01-13 17:52
:+1:

**Comment by TylerBrock** [comment] 2016-01-15 00:15
Also having this bug on Node v5.4.0 and npm 3.3.12

**Comment by browncolyn** [comment] 2016-02-03 01:02
I have the same issue running npm 3.7.0 and node v4.2.1. Likewise, its lodash that isn't installing the first time.

**Comment by jhford** [comment] 2016-02-03 10:55
I'm experiencing this as well with node 5.4.1 and npm 3.3.12.  this is happening with my local installation as well as with a docker image
```json
{
  "name": "cloud-mirror",
  "version": "0.0.1",
  "description": "Proxy files in one cloud storage system to another",
  "main": "index.js",
  "scripts": {
    "compile": "babel-compile -c tc-rules/babel-node5 src:lib test:.test",
    "prepublish": "npm run compile",
    "pretest": "npm run compile",
    "test": "mocha .test/*_test.js"
  },
  "author": "John Ford <jhford@mozilla.com>",
  "license": "MPL-2.0",
  "dependencies": {
    "aws-sdk": "^2.1.5",
    "aws-sdk-promise": "0.0.2",
    "babel-eslint": "^4.1.6",
    "babel-plugin-syntax-async-functions": "^6.1.18",
    "babel-plugin-transform-async-to-generator": "^6.1.18",
    "babel-plugin-transform-async-to-module-method": "^6.1.18",
    "babel-plugin-transform-regenerator": "^6.2.0",
    "babel-plugin-transform-runtime": "^6.1.18",
    "bluebird": "^3.2.1",
    "commander": "^2.9.0",
    "content-disposition": "^0.5.0",
    "continuation-local-storage": "^3.1.4",
    "cookie": "^0.2.3",
    "debug": "^2.2.0",
    "eslint": "^1.10.1",
    "redis": "^2.4.2",
    "request": "^2.65.0",
    "request-promise": "^1.0.2",
    "schema-validator-publisher": "^0.8.8",
    "source-map-support": "^0.4.0",
    "sqs-consumer": "^3.0.0",
    "stream-meter": "^1.0.3",
    "superagent-promise": "^1.0.3",
    "taskcluster-base": "^0.8.6",
    "typed-env-config": "^0.10.0"
  },
  "devDependencies": {
    "babel-compile": "^1.0.0",
    "babel-core": "^6.2.1",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-node5": "^10.0.0",
    "babel-preset-stage-1": "^6.1.18",
    "mocha": "^2.3.3",
    "tc-rules": "^2.0.3"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/taskcluster/cloud-mirror.git"
  }
}
```

```
FROM node:5-onbuild
MAINTAINER John Ford
EXPOSE 8080
ENTRYPOINT [ "node", "lib/main.js" ]
```

**Comment by pablo-pacheco** [comment] 2016-02-03 14:12
Same problem here

**Comment by almike** [comment] 2016-03-22 07:32
same here

**Comment by workmanw** [comment] 2016-03-25 23:32
I had this issue consistently happening on npm 3.3.12. I upgraded to the latest (npm 3.8.3) and it went away.

**Comment by ekryski** [comment] 2016-04-01 18:06
I've run into this issue multiple times with different versions of npm3 (3.3, 3.5, 3.8). It seems to be inconsistent. Most of the time I'm not able to consistently reproduce it. We've had this issues reported with Feathers. `feathers-errors` doesn't get installed the first time around: https://github.com/feathersjs/generator-feathers/issues/78.

I have a hunch that it might be a weird edge case where a module is deeply nested and used by multiple other modules so when it is brought top level it's not being retained. Running `npm install` again always seems to fix it.

**Comment by ekryski** [comment] 2016-04-01 19:22
Alright so I did a bit of digging because I'm able to replicate consistently on React Native project. This is what gets installed the first time around:

```
─┬ react-native@0.22.2
│ ├── absolute-path@0.0.0
│ ├── art@0.10.1
│ ├─┬ babel-core@6.7.4
│ │ ├─┬ babel-code-frame@6.7.4
│ │ │ └─┬ repeating@1.1.3
│ │ │   └── is-finite@1.0.1
│ │ ├─┬ babel-generator@6.7.2
│ │ │ ├── detect-indent@3.0.1
│ │ │ ├── is-integer@1.0.6
│ │ │ ├── lodash@3.10.1
│ │ │ ├── source-map@0.5.3
│ │ │ └── trim-right@1.0.1
│ │ ├── babel-helpers@6.6.0
│ │ ├── babel-messages@6.7.2
│ │ ├─┬ babel-traverse@6.7.4
│ │ │ ├── globals@8.18.0
│ │ │ └── lodash@3.10.1
│ │ ├── convert-source-map@1.2.0
│ │ ├── lodash@3.10.1
│ │ ├── path-exists@1.0.0
│ │ ├── path-is-absolute@1.0.0
│ │ ├── private@0.1.6
│ │ └── source-map@0.5.3
```

The modules that are missing are `shebang-regex@1.0.0` and `slash@1.0.0` (or at least that npm complains first about).

The second time around I end up with a bunch more modules installed. (below is just a snippet of the output)

```
├─┬ react-native@0.22.2
│ ├─┬ babel-core@6.7.4
│ │ ├─┬ babel-generator@6.7.2
│ │ │ ├── lodash@3.10.1
│ │ │ └── source-map@0.5.3
│ │ ├─┬ babel-traverse@6.7.4
│ │ │ └── lodash@3.10.1
│ │ ├── lodash@3.10.1
│ │ ├── path-is-absolute@1.0.0
│ │ ├── shebang-regex@1.0.0
│ │ ├── slash@1.0.0
│ │ └── source-map@0.5.3
│ ├─┬ babel-register@6.7.2
│ │ └── lodash@3.10.1
│ ├─┬ babel-types@6.7.2
│ │ └── lodash@3.10.1
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ connect@2.30.2
```

I'm on mac OS X 10.11.3, node v5.5.0, npm 3.8.0. Has the same problem when I upgraded to npm 3.8.5.

So now, I thought "Hey! Let's try npm 2". Well, it doesn't quite behave the same but it still looks modules are not getting installed (albeit different ones this time). In this case `babel-core` is not getting installed as part of my `babel` devDependency.

```
> mocha --require test/mocks --compilers js:babel-core/register --recursive test/specs/**/*.spec.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/eric/Development/rpm/app-offline/node_modules/mocha/bin/_mocha:302:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/eric/Development/rpm/app-offline/node_modules/mocha/bin/_mocha:296:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
npm ERR! Test failed.  See above for more details.
eric : app-offline (master) $ npm ls babel-core
rpmmobile@0.0.1 /Users/eric/Development/rpm/app-offline
├─┬ babel-preset-react-native-stage-0@1.0.1
│ └─┬ babel-preset-react-native@1.5.6
│   └─┬ babel-plugin-transform-regenerator@6.6.5
│     └── babel-core@6.7.4
└─┬ react-native@0.22.2
  ├── babel-core@6.7.4
  └─┬ fbjs-scripts@0.4.0
    └─┬ babel@5.8.38
      └── babel-core@5.8.38

eric : app-offline (master) $ npm ls babel
rpmmobile@0.0.1 /Users/eric/Development/rpm/app-offline
├── babel@6.5.2
└─┬ react-native@0.22.2
  └─┬ fbjs-scripts@0.4.0
    └── babel@5.8.38
```

For reference, here is my `package.json` file:

```json
{
  "name": "app-offline",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=5.0.0",
    "npm": "^3.8.0"
  },
  "scripts": {
    "push": "git push origin && git push origin --tags",
    "release:patch": "npm version patch && npm run push",
    "release:minor": "npm version minor && npm run push",
    "release:major": "npm version major && npm run push",
    "purge": "rm -rf node_modules/ && watchman watch-del-all && npm cache clean",
    "start": "node node_modules/react-native/local-cli/cli.js start --reset-cache",
    "test": "mocha --require test/mocks --compilers js:babel-core/register --recursive test/specs/**/*.spec.js"
  },
  "dependencies": {
    "lodash": "^4.6.1",
    "react-native": "^0.22.2",
    "react-native-device-info": "^0.9.1",
    "react-native-drawer": "^1.16.7",
    "react-native-router-flux": "2.3.1",
    "react-native-vector-icons": "^1.3.3",
    "realm": "^0.11.1"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "chai": "^3.5.0",
    "chai-enzyme": "^0.4.1",
    "enzyme": "^2.2.0",
    "istanbul": "^0.4.2",
    "mocha": "^2.4.5",
    "react": "^0.14.8",
    "react-dom": "^0.14.8",
    "react-native-mock": "^0.0.7",
    "sinon": "^1.17.3",
    "sinon-as-promised": "^4.0.0",
    "sinon-chai": "^2.8.0"
  }
}

```

**Comment by schmod** [comment] 2016-04-11 22:04
Multiple users on my team are reporting that this issue crops up when using lodash ~4.1.0 together with Grunt ~0.4.5 (which requires lodash ~0.9.2) on the same project.  

The initial run of `npm install` only installs lodash ~4.1.0 into the root `node_modules` folder, and does not install the version of lodash that will satisfy grunt's dependencies.  

This appears to be an issue with repeated transitive dependencies (ie. when my module depends on both grunt & lodash, and one of my dependencies _also_ requires grunt & lodash).  

I have managed to create a minimal reproduction scenario for this issue: 

---

## Steps to reproduce

Slightly convoluted.  Bear with me.  
Node v5.8.0 / npm 3.8.6 / Mac OS 10.11.4

### `module1/package.json`
```
{
  "name": "module1",
  "version": "1.0.0",
  "dependencies": {
    "grunt": "~0.4.5",
    "lodash": "^4.10.0",
  }
}
```

### `module2/package.json`
```json
{
  "name": "module2",
  "dependencies": {
    "grunt": "^0.4.5",
    "lodash": "^4.10.0",
    "module1": "file:../module1"
  }
}
```

```sh
$ cd module1
$ npm install 
# module1/node_modules/grunt/node_modules/lodash is now present, and the correct version

$ cd ../module2
$ npm install 
# module2/node_modules/grunt/node_modules does not exist after running the first npm install
# grunt's dependencies are not satisfied.

$ npm install 
# lodash 0.9.2 is now correctly installed to module2/node_modules/grunt/node_modules/lodash
```

There doesn't seem to be anything particularly interesting or relevant in NPM's console output during this process.

**Comment by eiriklv** [comment] 2016-04-13 17:13
Adding all `devDependencies` to `dependencies` seems to "fix" it for me. Any more clues?

**Comment by R-Kurbatovvakoms** [comment] 2016-04-22 11:20
The same here. `node v4.4.1`, `npm 3.8.3`. Had to do `npm install` twice as babel-register from devDependencies had not installed for the first time.

**Comment by rkurbatov** [comment] 2016-05-02 14:36
node v4.4.3, npm 3.8.8, still having same issue.

**Comment by AnimiVulpis** [comment] 2016-05-02 16:43
#11043 seems to be related (or the same).

I created a [minimal example repo](https://github.com/AnimiVulpis/npm-bug) on which a sub-dependency is missing on every clean install.

Must have something todo with **devDependencies** and **dependencies** (somehow the **idealTree** does not get constructed correctly)

**Comment by jeremyckahn** [comment] 2016-05-09 21:43
I am also experiencing this issue.  npm will not install Bootstrap unless I run `npm install` a second time.  Bootstrap is a top-level dependency (not nested).

**Comment by pwalczyszyn** [comment] 2016-05-10 11:54
I have the same problem. Another strange thing is that when I run `npm update` once a clean project it get's all the dependencies installed correctly and everything works.

**Comment by jkarttunen** [comment] 2016-05-18 10:43
+ for node 4.4

**Comment by schmod** [comment] 2016-05-23 14:08
I should note that my repro steps above do not use `devDependencies` at all.

**Comment by DerekOverlock** [comment] 2016-06-01 20:16
Just ran into a related issue that might have the same root cause. We are using `node v4.2.2 (npm v2.14.7)`.

Our project has a dependency on `express@^4.13.3`, while a dependency we have uses `express@~3.4.8`.

After shrinkwrapping our project, `npm install` will only install express@~3.4.8, for both our project and also for our dependency's project.

Running `npm ls` I get this error at the bottom of the output:
```
npm ERR! invalid: express@3.4.8 {PROJECT}/node_modules/express
```
So it looks like npm is aware that it has the wrong version. If I run `npm install` again it will install the correct version of express, according to what's in the shrinkwrap.

**FWIW**, was curious to see if this issue was corrected by a later version... it seems like upgrading to `node v6.2.0 (npm v3.8.9)` has resolved the issue.

**Comment by lfdoherty** [comment] 2016-06-19 08:26
I think I experienced a version of this bug - although in my case no matter how many times I ran "npm install" it would not install the transitive dependencies. However, moving a bunch of stuff (babel) into devDependencies worked around it. I suspect the conflict came from having babel in dependencies and babel-eslint in devDependencies. I notice other people are reporting bugs to do with babel in this thread...

Even calling e.g. "npm install wordwrap" to manually install one of the missing transitive dependencies would not install anything.

I tried npm cache clean, and deleting "~/.npm", to no effect.

HOWEVER, installing the latest node fixed it. I then downgraded to the version I was originally using - 6.2.1 - and it was still fixed. So I guess something gets cleaned up in the process of reinstalling node and npm...

HTH

**Comment by danez** [comment] 2016-07-04 22:03
Here is another easy to reproduce example:
`babel-core` requires `path-exists@1.0.0` but it does not get installed in the first npm install call
https://gist.github.com/danez/eeadff767ba13866be3050270c9651c0

I debugged a little bit and to me it seems that because prod- and dev-dependencies are resolved in separate runs, the dev-dependencies simply overwrite prod dependencies in the idealTree (https://github.com/npm/npm/blob/0ec3f663fcf541916b5201ff01404d79a19435fa/lib/install/deps.js#L549) and do not care if `package.requiredBy` is set. Ultimately before overwriting there should be task to put the 'to-be-overwriten' dependency back to the parents who require them.

**Comment by rkurbatov** [comment] 2016-07-05 09:13
@DerekOverlock yeah, after updating to 3.x branch of npm (instead of 2.x which is default for Node 4) we don't have this issue anymore.

**Comment by ekryski** [comment] 2016-07-05 18:28
@danez nice digging! `path-exists` has been one of the dependencies that seems to be offending quite frequently for me (obviously because we are using Babel errrwhere). I think you are right but which version of NPM and Node are you using? I'll see if I can confirm.

**Comment by danez** [comment] 2016-07-05 18:40
@ekryski oh I used node 4.4.7 and npm 3.10.4

**Comment by hollanderbart** [comment] 2016-07-14 12:45
+1

**Comment by v1rt** [comment] 2016-07-19 03:21
Getting the same issue like others

```
$ node -v
v6.2.2

$ npm -v
3.9.5
```

I have to re-execute `npm install` so that amdefine module gets installed. I've tried it like 10 times by doing `rm -rf node_modules` then `npm install` then finally doing an `ls node_modules/amdefine`. It's not there until I execute `npm install` again.

**Comment by yinquanteo** [comment] 2016-07-21 23:42
I can confirm that I'm facing this issue with 

```
$ node -v
v5.4.1
$ npm -v
3.9.0
```

and also

```
$ node -v
v6.3.0
$ npm -v
3.10.3
```

**Comment by ekryski** [comment] 2016-07-26 20:37
I can confirm @danez's example reproduces the issue on a bunch of node versions and npm > 3. I was able to have things install properly on npm 2.

```
npm -v
2.14.2
eric : npm-test  $ npm install
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
path-exists@3.0.0 node_modules/path-exists

babel-core@6.11.4 node_modules/babel-core
├── slash@1.0.0
├── shebang-regex@1.0.0
├── path-is-absolute@1.0.0
├── path-exists@1.0.0
├── babel-messages@6.8.0
├── babel-template@6.9.0
├── babel-helpers@6.8.0
├── private@0.1.6
├── convert-source-map@1.3.0
├── babylon@6.8.4
├── debug@2.2.0 (ms@0.7.1)
├── babel-types@6.11.1 (to-fast-properties@1.0.2, esutils@2.0.2)
├── minimatch@3.0.2 (brace-expansion@1.1.6)
├── json5@0.4.0
├── babel-traverse@6.11.4 (globals@8.18.0, invariant@2.2.1)
├── source-map@0.5.6
├── babel-code-frame@6.11.0 (js-tokens@2.0.0, esutils@2.0.2, chalk@1.1.3)
├── babel-generator@6.11.4 (detect-indent@3.0.1)
├── lodash@4.14.0
├── babel-register@6.11.5 (home-or-tmp@1.0.0, mkdirp@0.5.1, source-map-support@0.2.10, core-js@2.4.1)
└── babel-runtime@6.9.2 (regenerator-runtime@0.9.5, core-js@2.4.1)
eric : npm-test  $ npm ls path-exists
test@1.0.0 /Users/eric/Desktop/npm-test
├─┬ babel-core@6.11.4
│ └── path-exists@1.0.0
└── path-exists@3.0.0
```

**Comment by keithajackson** [comment] 2016-07-27 00:43
+1, having issues with `node 6.3.0` and `npm 3.10.3`.

**Comment by jannispl** [comment] 2016-08-08 15:55
Also experiencing this issue with nodejs 6.3.1 and npm 3.10.3

**Comment by fndcz** [comment] 2016-08-10 04:10
Same issue with nodejs v6.2.2 and npm 3.9.5

**Comment by NicolasPelletier** [comment] 2016-09-06 11:42
Same issue with Node v6.4.0 and npm 3.10.3.

**Comment by Michael-Hamburger** [comment] 2016-09-07 14:17
Same here.... Node v6.3.1 and npm 3.10.3 on win 10 education 64 bit

**Comment by davidknezic** [comment] 2016-09-19 08:43
Same issue v6.6.0 and npm 3.10.3 on Mac OS X 10.11.6

**Comment by sujaysudheendraa** [comment] 2016-10-07 18:18
seeing this issue as well. Node: 5.0.0, npm 3.3.9. osx 10.11.6. [Its](url) installing all the dependencies properly except the `lodash` module . Running npm for second time installs `lodash` under all module which ever is dependent on it.

1st time:

```
..
..
..
│ ├── json5@0.4.0 
│ ├── lodash@4.16.4 
│ ├─┬ minimatch@3.0.2 
│ │ └─┬ brace-expansion@1.1.5 
│ │   ├── balanced-match@0.4.1 
│ │   └── concat-map@0.0.1 
.. 
..
..
```

npm install for second time:
now it installs lodash under all dependencies properly
```
├─┬ babel-core@6.10.4
│ └── lodash@4.16.4 
├─┬ babel-preset-es2015@6.9.0
│ ├─┬ babel-plugin-transform-es2015-block-scoping@6.10.1
│ │ └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-classes@6.9.0
│ │ ├─┬ babel-helper-define-map@6.9.0
│ │ │ └── lodash@4.16.4 
│ │ ├─┬ babel-template@6.9.0
│ │ │ └── lodash@4.16.4 
│ │ ├─┬ babel-traverse@6.10.4
│ │ │ └── lodash@4.16.4 
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-computed-properties@6.8.0
│ │ ├─┬ babel-helper-define-map@6.9.0
│ │ │ └── lodash@4.16.4 
│ │ └─┬ babel-template@6.9.0
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-duplicate-keys@6.8.0
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-function-name@6.9.0
│ │ ├─┬ babel-helper-function-name@6.8.0
│ │ │ ├─┬ babel-template@6.9.0
│ │ │ │ └── lodash@4.16.4 
│ │ │ └─┬ babel-traverse@6.10.4
│ │ │   └── lodash@4.16.4 
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.10.3
│ │ ├─┬ babel-template@6.9.0
│ │ │ └── lodash@4.16.4 
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-object-super@6.8.0
│ │ └─┬ babel-helper-replace-supers@6.8.0
│ │   ├─┬ babel-template@6.9.0
│ │   │ └── lodash@4.16.4 
│ │   ├─┬ babel-traverse@6.10.4
│ │   │ └── lodash@4.16.4 
│ │   └─┬ babel-types@6.11.1
│ │     └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.9.0
│ │ ├─┬ babel-template@6.9.0
│ │ │ └── lodash@4.16.4 
│ │ ├─┬ babel-traverse@6.10.4
│ │ │ └── lodash@4.16.4 
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-shorthand-properties@6.8.0
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.8.0
│ │ ├─┬ babel-helper-regex@6.9.0
│ │ │ └── lodash@4.16.4 
│ │ └─┬ babel-types@6.11.1
│ │   └── lodash@4.16.4 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.11.0
│ │ └─┬ babel-helper-regex@6.9.0
│ │   └── lodash@4.16.4 
│ └─┬ babel-plugin-transform-regenerator@6.9.0
│   ├─┬ babel-traverse@6.10.4
│   │ └── lodash@4.16.4 
│   └─┬ babel-types@6.11.1
│     └── lodash@4.16.4 
```

Not sure if its happening because the same dependency is present at different levels (at top level as well as in some npm dependency)

**Comment by sujaysudheendraa** [comment] 2016-10-07 18:28
I think I solved the issue (at least for my case). I had lodash mentioned in package.json in my app and the same dependency was mentioned in different npm packages my app is dependent on.

 I removed the entry for lodash from my app's package.json (so no need of `lodash` at top level) and let the other dependencies resolve and install lodash (if its mentioned in their package.json). Now everything is being installed with just one try of `npm install` command.

**Comment by ibratoev** [comment] 2016-10-21 13:37
Same issue here - **npm 3.10.8**

**Comment by ibratoev** [comment] 2016-10-21 14:01
After a short research found an easy to repro case:
```
  "dependencies": {
    "fs-promise": "0.5.0"
  },
  "devDependencies": {
    "fs-extra": "0.30.0"
  }
```
Call 2 time `npm install`. Output:
```
Ω npm install
t@1.0.0 /Users/ibratoev/Work/t
├─┬ fs-extra@0.30.0
│ ├── graceful-fs@4.1.9
│ ├── jsonfile@2.4.0
│ ├── klaw@1.3.0
│ ├── path-is-absolute@1.0.1
│ └─┬ rimraf@2.5.4
│   └─┬ glob@7.1.1
│     ├── fs.realpath@1.0.0
│     ├─┬ inflight@1.0.6
│     │ └── wrappy@1.0.2
│     ├── inherits@2.0.3
│     ├─┬ minimatch@3.0.3
│     │ └─┬ brace-expansion@1.1.6
│     │   ├── balanced-match@0.4.2
│     │   └── concat-map@0.0.1
│     └── once@1.4.0
└─┬ fs-promise@0.5.0
  ├── any-promise@1.3.0
  ├─┬ mz@2.4.0
  │ └── object-assign@4.1.0
  └─┬ thenify-all@1.6.0
    └── thenify@3.2.1

npm WARN t@1.0.0 No description
npm WARN t@1.0.0 No repository field.

Ω npm install
t@1.0.0 /Users/ibratoev/Work/t
└─┬ fs-promise@0.5.0
  └── fs-extra@0.26.7
```

**Comment by ibratoev** [comment] 2016-10-21 17:05
I delved a bit into the code and I think I found how it can be fixed. Opened a quick PR here: https://github.com/npm/npm/pull/14369
@iarna, I see that you are assigned to this issue. Can you have a look and let me know if you are interested in a fix with this approach?
I understand that the **install** logic is quite complex and this is actually my first look into the npm codebase so feel free to ignore my PR ;)

**Comment by JoeCianflone** [comment] 2016-10-25 18:24
I resolved the issue by installing yarn and using that. Guys...you said this was something that would be fixed in the "next version" what does that mean?

**Comment by schmod** [comment] 2016-10-25 19:10
@ibratoev I've had another PR open (#12811) since May regarding this issue.

**Comment by ibratoev** [comment] 2016-10-26 11:38
@schmod Closed my in favor of your PR. You approach looks better ;) I hope @iarna manages to merge it soon. For me, this is an important issue to fix.

**Comment by schmod** [comment] 2016-10-26 16:28
At this point, I'm not holding out much hope.  It's rare for NPM to merge PRs from the community these days.

**Comment by hay** [comment] 2016-11-10 18:53
Just encountered this issue as well. It's bizarre that `npm` is a package manager that, well, doesn't actually install all dependencies.

**Closed** 2016-12-02 01:29 UTC
Labels: big-bug, bug, installer

**Comment by zkat** [comment] 2016-12-02 02:53
This is quite probably fixed as of `npm@4.0.5` thanks to #12811. Cheers!

**Comment by reisnera** [comment] 2017-03-22 01:45
I see this issue is closed, but I seem to be experiencing this problem with latest node and npm (versions 7.7.4 and 4.4.1, respectively). I must call `npm install` twice to get the relevant missing copies of the package (in this case, "boom") installed.
Here's the relevant portion of my package.json file:
```javascript
"dependencies": {
    "buble": "^0.15.2",
    "buble-loader": "^0.4.1",
    "copy-webpack-plugin": "^4.0.1",
    "ethereumjs-testrpc": "^3.0.3",
    "truffle": "^3.1.2",
    "truffle-contract": "^1.1.10",
    "web3": "^0.18.2",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  }
```

**Comment by emirdeliz** [comment] 2017-04-12 15:38
I have same problem with npm 4.4.4 and node v7.9.0

**Comment by zkat** [comment] 2017-04-12 20:27
Hrm. Any chance y'all can come up with a minimal repro case for us that we can use?

**Comment by lekhnath** [comment] 2017-05-29 05:35
I've just upgraded to npm v5 and I am using node v6.10.3 LTS. I've to install some dependencies one by one after initial npm install. Like:

npm install
npm install missing-pkg-1
npm install missing-pkg-2

**Comment by tweaty100** [comment] 2017-07-02 17:21
Hello @rkurbatov 
Does your problem solved as i am also having node --version as V4.4.3 and i am facing this problem that when i typed" npm install " it throws error as "npm WARN package.json node storage@0.0.7 no repository field ?will you please help if your issue is resolved.
Thanks

**Comment by ljharb** [comment] 2017-07-02 20:59
@tweaty100 that's just a warning, you can safely ignore it. It's unrelated to this issue.

**Comment by Zodiase** [comment] 2017-07-14 04:52
Just happened to me as well. Re-tried `rm -rf node_modules && npm install` many, many, many many times to finally get `underscore` installed but `request` is still missing... Using `npm@5.0.4`. I'm going to try again with `npm@5.2.0`.

Update: after updating to `npm@5.2.0` so far I haven't seen any error, yet...

**Comment by foryougautam** [comment] 2017-10-18 06:17
I am also getting this strange issue calling npm install twice fix this issue.
I am using node version 8.2.1 and npm are 5.3.0. 
![lodash](https://user-images.githubusercontent.com/1030063/31703378-ef766354-b3f9-11e7-908f-676413aace2d.png)

Is there any fix available?

**Comment by mleyb** [comment] 2018-01-25 08:13
i am also getting the same issue with node 9.2.0 & npm 5.6.0

has there been any progress on resolving this??

**Comment by AndrewBogdanovTSS** [comment] 2018-02-10 13:36
I still can reproduce this issue on:
node -v 8.9.4
npm -v 5.6.0
nuxt-community/typescript-template#29
I'm getting 
`Module build failed: Error: Cannot find module 'babel-core'`
after the first install, but after I do `npm install nuxt` explicitly it installs all dependencies correctly

**Comment by aguynamedben** [comment] 2018-02-20 01:50
This to me today.
```
$ nvm --version
0.33.2
$ node --version
v8.9.4
$ npm --version
5.6.0
$ ./node_modules/webpack/bin/webpack.js --version
3.11.0
```

I use Webpack 3 and I upgraded React from 15.6.1 to 15.6.2, and a lot of unrelated imports that depend on files in `node_modules` failed. It took me awhile to track down. I finally inspected a missing import in `node_modules/jquery-confirm/*` and was shocked to find that thew hole `node_modules/jquery-confirm` was missing, even thought that dependency is in my package.json/package-lock.json. This code was also previously working fine, and the failure was happening on multiple packages after the React upgrade, so I knew it wasn't something with the package itself. I ran `npm install` again out of chance, and then it was there. This appeared to happen with 8-10 different dependencies. I'm not sure how many times I actually ran `npm install` to get all the dependencies to work.

It's really confusing. Here's a sample of the commands I ran:
```
$ npm install
... succeeded
$ ls node_modules/jquery-<tab complete>
... (jquery-confirm not present, even though it's in my package.json and package-lock.json)
$ npm install
... succeded
$ ls node_modules/jquery-<tab_complete>
... jquery-confirm is present!
```

**Comment by dmwelch** [comment] 2018-02-21 19:09
Ran into this today.  @iarna, please mark this as "Open" again.  It doesn't appear that a stable solution has been implemented yet.
```
nvm --version  === 0.33.1
node --version === v6.9.0
npm --version === 3.10.8
```
(I know my node is old - see comments above for more current versions ^^^.) . Thank you!
