### ISSUE TITLE
Refusing to install redis as a dependency of itself

### ISSUE THREAD

**Issue by AshuPari** [npm/npm#15718] opened 2017-02-09 08:46 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment] 2017-02-09 08:49
Could you give us more detail, like `npm-debug.log`? Thanks.

**Comment by KenanY** [comment] 2017-02-09 18:03
@AshuPari Sounds like you've set your `"name"` in your `package.json` to `"redis"`, but then you're trying to install a package of the same name. This is not allowed, so I suggest that you simply change your `"name"` to something more unique. Also, in the future, _please_ take the time to fill out the support form in your post.

Closing since this is `npm` working as designed.

**Closed by KenanY** 2017-02-09 18:03 UTC

**Comment by dangonzo** [comment] 2017-03-10 19:24
ok sorry how do i change my name and where is the form

**Comment by KenanY** [comment] 2017-03-10 23:37
@dangonzo If you wanna change your project's name, simply edit the value of the `"name"` field in your `package.json` with your favorite text editor.
