### ISSUE TITLE
New shrinkwrap lifecycle breaks old scripts

### ISSUE THREAD

**Issue by STRML** [npm/npm#13253] opened 2016-07-02 13:31 UTC
#### I'm opening this issue because:

Our workflow defined a `shrinkwrap` npm script that would take care of specifying our custom registry and trimming unused properties from the output. That workflow is now broken due to https://github.com/npm/npm/commit/e8c80f20bfd5d1618e85dbab41660d6f3e5ce405.

Setting env vars in a `preshrinkwrap` hook does not work. We want to enforce a custom registry and development mode whenever devs shrinkwrap.

#### What's going wrong?

Our `shrinkwrap` definition:

`package.json`
```json
    "shrinkwrap": "scripts/shrinkwrap.sh",
```

`scripts/shrinkwrap.sh`
```bash
#!/bin/bash -ex

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN=$DIR/../node_modules/.bin

cd $DIR/..
npm shrinkwrap --dev --registries=npm-local.internal.xxx.com:4873

# Cleanup shrinkwrap
node $DIR/cleanShrinkwrap.js

# Check vulns
$BIN/nsp check
```

The error is when this script calls `npm shrinkwrap`, it fails with the following error:

```
sh: scripts/shrinkwrap.sh: Permission denied
```

When you call `npm shrinkwrap` from within a script named `shrinkwrap`, it actually recursively calls itself rather than the npm function. It does not, however, do this when running `npm shrinkwrap` from the command line.

Note that, strangely, the cwd for the `shrinkwrap` lifecycle event is correct, [unlike the pre- and post- hooks](https://github.com/npm/npm/issues/13252).

#### How can the CLI team reproduce the problem?

Add any `shrinkwrap` script that calls `npm shrinkwrap`.

### Supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.2.1

 - Windows, OS X, or Linux?: OS X

**Comment by iarna** [comment] 2016-07-15 23:41
Ok, seems like there are a few things here:

> sh: scripts/shrinkwrap.sh: Permission denied

This is an error from your operating system (or more specifically, from your shell). It happens if you haven't set the script as executable. You can do that with `chmod u+x scripts/shrinkwrap.sh`.

> recursively calls itself

So what happens when you run `npm run shrinkwrap` is it runs the `shrinkwrap` lifecycle script as if it had been triggered from within `npm`. This means it will also execute `preshrinkwrap` and `postshrinkwrap` if they exist. Your `scripts/shrinkwrap.sh` in turn calls `npm shrinkwrap` when then in turn runs the `shrinkwrap` lifecycle creating this loop…

You have two options here:

1. You can rename the thing you run to something other than shrinkwrap. Then it won't get caught calling back into itself when you call `npm shrinkwrap` inside it.

OR

2. You can change your `npm shrinkwrap` line to:
```
npm shrinkwrap --ignore-scripts --dev --registries=npm-local.internal.xxx.com:4873
```

By adding `--ignore-scripts` it won't run the shrinkwrap lifecycle scripts, and thus break the loop.

**Comment by STRML** [comment] 2016-07-16 17:47
See #13252 re: the permission denied error. It's not the executable bit. Strangely the error has changed now from `Permission denied` to `No such file or directory`. Not sure why.

The `--ignore-scripts` line is key - that works, but with a caveat:

`npm shrinkwrap` runs the shrinkwrap first, then runs the script, which recursively calls `npm shrinkwrap --dev --ignore-scripts`. But that fails again with the error:

```
sh: scripts/shrinkwrap.sh: No such file or directory
```

Yet `npm run shrinkwrap` works fine - it runs the lifecycle script first, then avoids the recursive call.

I can see how this is tricky - we basically want to enforce certain cli options (`--dev`, custom registry) whenever a developer shrinkwraps, then run a few cleanup scripts & node-security-project. The latter can be done easily via `postshrinkwrap` but I'm not sure how to easily populate the `--registry` and `--dev` options.

**Comment by cvrebert** [comment] 2016-07-16 21:09
Also, why doesn't [the docs website](https://docs.npmjs.com/misc/scripts) mention these new scripts now that they've hit stable npm?

**Comment by iarna** [comment] 2016-07-18 20:03
@cvrebert Because I forgot to push the docs repo! Thanks for pointing that out!

**Comment by iarna** [comment] 2016-07-18 20:08
@STRML I don't think there's going to be a way to inject options into a lifecycle script this way. How about this…

1. A `shrink` script that you have your users run that calls something like `npm shrinkwrap --for-real --registry=xyz --dev`.

2. A `preshrinkwrap` script that fails if `npm_config_for_real` isn't set.

That way you can ensure folks are running `npm shrinkwrap` via your script, while at the same time avoiding recursion.

**Comment by necolas** [comment] 2016-07-19 21:53
We have the same problem at Twitter. Isn't this a regression / breaking change that shouldn't have made it into 3.10?

FWIW, the main reason we have a custom shrinkwrap script is because npm's default shrinkwrap is so problematic and produces a lot of noise in the shrinkwrap file diffs.

**Comment by iarna** [comment] 2016-07-25 04:31
Historically we've not treated introducing new lifecycle scripts as breaking changes (because we didn't promise NOT to). See also the introduction of the `version` lifecycle. We did the same thing with `shrinkwrap` but it seems more folks were already using a lifecycle with that name. We may need to revisit that as a matter of policy, but it's definitely a change over previous project behavior.

**Comment by iarna** [comment] 2016-09-12 22:21
I'm going to close this because we're not going to revert this change and there's no way to fix the problem from our side.

The CLI team has discussed this and we have agreed that any further introductions of new lifecycle scripts will be breaking changes and necessitate a major version bump, so hopefully in future this sort of thing will be less surprising.

You can see an example of an upcoming new lifecycle script here: https://github.com/npm/npm/issues/10074

**Closed by iarna** 2016-09-12 22:21 UTC
Labels: big-bug, bug, lifecycle

**Comment by STRML** [comment] 2016-09-12 22:40
Understood that #10074 should be semver-major, but backing out a bug has historically been treated as semver-patch if it has broken good code.

Overriding `npm shrinkwrap` should still be possible in all cases as its implementation is rather fundamentally regarded as annoying or even broken.

**Comment by othiym23** [comment] 2016-09-13 00:39
> Understood that #10074 should be semver-major, but backing out a bug has historically been treated as semver-patch if it has broken good code.

The conclusion that the CLI team reached after discussing this issue is that this isnʻt a bug – itʻs neither a regression, nor is the behavior breaking anything inside npm itself. "Broken good code" is the crux of the issue here – it did break some package scripts, including yours. Package scripts arenʻt themselves part of npm, though, and itʻs hard to make a change to the package lifecycle without breaking something.

I think you, @iarna, and I all agree that breaking package scripts unexpectedly is bad, and this is what the CLI team wants to avoid in the future. We intend to use information derived from the corpus of packages on the primary registry to help us make these decisions more informed in the future. For instance, we know that around 40 packages have `prepare` scripts, and are likely to be affected by the changes we intend to land for #10074.

That said, the `shrinkwrap` lifecycle events have been in `npm@3` since `npm@3.10.1`, which is three months now, so removing it is just as likely to break something as introducing it did in the first place.

> Overriding `npm shrinkwrap` should still be possible in all cases as its implementation is rather fundamentally regarded as annoying or even broken.

If you look at [the CLIʻs CHANGELOG.md](https://github.com/npm/npm/blob/master/CHANGELOG.md), youʻll see that one of the our major projects over the last few months has been improving the consistency of shrinkwrap and making it feel more like an integrated, first-class part of the CLI. This work will continue until weʻre satisfied that `npm shrinkwrap` is solving the deployment and lifecycle management problems npmʻs users very obviously want it to solve. Given how much of shrinkwrapʻs behavior is undocumented and self-contradictory, this is inevitably going to involve moving some peopleʻs cheese, and for the work that incurs, we can only apologize. I feel pretty strongly that npmʻs users are better served by us doing (and / or coördinating) that work, rather than freezing the current situation in place, _especially_ if everyone agrees that the status quo is unsatisfactory.
