### ISSUE TITLE
npm install giving fetch errors for some packages

### ISSUE THREAD

**Issue by vishnu-onshape** [npm/npm#13289] opened 2016-07-06 10:00 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I am doing 'npm install', getting fetch error for some packages
#### How can the CLI team reproduce the problem?

> fsevents@1.0.12 install /Users/vkulkarni/repos/newton/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/vkulkarni/repos/newton/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
npm ERR! fetch failed https://registry.npmjs.org/popsicle-status/-/popsicle-status-1.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/weinre/-/weinre-2.0.0-pre-I0Z7U9OV.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/jasmine-core/-/jasmine-core-2.3.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/popsicle-status/-/popsicle-status-1.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/weinre/-/weinre-2.0.0-pre-I0Z7U9OV.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/jasmine-core/-/jasmine-core-2.3.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/popsicle-status/-/popsicle-status-1.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/weinre/-/weinre-2.0.0-pre-I0Z7U9OV.tgz
npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/jasmine-core/-/jasmine-core-2.3.4.tgz
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/vkulkarni/build_tools/node-v4.4.4-darwin-x64-npm-2.15.1/bin/node" "/Users/vkulkarni/build_tools/node-v4.4.4-darwin-x64-npm-2.15.1/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! fetch failed with status code 502
npm ERR! 

### supporting information:

 - `npm -v` prints: 2.15.1
 - `node -v` prints: v4.4.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by vishnu-onshape** [comment] 2016-07-06 10:02
Is a same Bad Gateway error as below?

https://github.com/npm/npm/issues/13287

**Comment by joanatzephyr** [comment] 2016-07-06 10:26
Having same 502 issue in codenvy and cloud9 'npm install' that worked fine yesterday.  Pls let me know if you want me to attach log...

**Comment by heshanindika** [comment] 2016-07-06 11:00
I'm also having the same issue
====================================================
npm http fetch GET https://registry.npmjs.org/sentence-case/-/sentence-case-1.1.3.tgz
npm http fetch 200 https://registry.npmjs.org/param-case/-/param-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/is-lower-case/-/is-lower-case-1.1.3.tgz
npm http fetch 200 https://registry.npmjs.org/pascal-case/-/pascal-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/swap-case/-/swap-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/snake-case/-/snake-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/lower-case/-/lower-case-1.1.3.tgz
npm http fetch 200 https://registry.npmjs.org/is-upper-case/-/is-upper-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/upper-case/-/upper-case-1.1.3.tgz
npm http fetch 200 https://registry.npmjs.org/title-case/-/title-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/constant-case/-/constant-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/upper-case-first/-/upper-case-first-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/camel-case/-/camel-case-1.2.2.tgz
npm http fetch 200 https://registry.npmjs.org/path-case/-/path-case-1.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/sentence-case/-/sentence-case-1.1.3.tgz
npm info retry fetch attempt 1 at 10:56:08 AM
npm info attempt registry request try #1 at 10:56:08 AM
npm http fetch GET https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm http fetch 502 https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm info retry will retry, error on last attempt: Error: server error 502
npm info attempt registry request try #2 at 10:56:18 AM
npm http fetch GET https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm http fetch 502 https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm info retry will retry, error on last attempt: Error: server error 502
npm info attempt registry request try #3 at 10:57:18 AM
npm http fetch GET https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm http fetch 502 https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm info retry fetch attempt 2 at 10:57:28 AM
npm info attempt registry request try #1 at 10:57:28 AM
npm http fetch GET https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm http fetch 502 https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm info retry will retry, error on last attempt: Error: server error 502
npm info attempt registry request try #2 at 10:57:38 AM
npm http fetch GET https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm http fetch 502 https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm info retry will retry, error on last attempt: Error: server error 502
npm info attempt registry request try #3 at 10:58:38 AM

**Comment by hoatle** [comment] 2016-07-06 12:14
I'm having the same issue when npm install on Heroku:

```
remote: npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
remote: npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
```

**Comment by damarna85** [comment] 2016-07-06 12:22
Please same happens here! What can we do? Docker Hub is also affected by this.

**Comment by veeracs** [comment] 2016-07-06 12:34
I'm getting fetch errors too...

```
npm ERR! fetch failed https://registry.npmjs.org/css-mediaquery/-/css-mediaquery-0.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

`/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! fetch failed https://registry.npmjs.org/css-mediaquery/-/css-mediaquery-0.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/abab/-/abab-1.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/abab/-/abab-1.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/css-mediaquery/-/css-mediaquery-0.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/abab/-/abab-1.0.3.tgz
npm WARN optional dep failed, continuing jsdom@7.2.2
npm ERR! Linux 4.2.0-27-generic
```

**Comment by kblcuk** [comment] 2016-07-06 12:36
Same as https://github.com/npm/npm/issues/13284

**Comment by veeracs** [comment] 2016-07-06 12:37
Looks good on a Mac but not good on Ubuntu.

**Comment by Larisho** [comment] 2016-07-06 13:02
Same thing happening on Win7

**Comment by keithics** [comment] 2016-07-06 13:20
having problem with centos 7

**Comment by jcarpe** [comment] 2016-07-06 13:21
I am having the same issue on OSX:
```
npm ERR! fetch failed https://registry.npmjs.org/babel-plugin-transform-react-jsx-self/-/babel-plugin-transform-react-jsx-self-6.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
```

**Comment by rogersdk** [comment] 2016-07-06 13:22
Same problem here, ubuntu server 16.04 LTS =/

**Comment by paranoidminotaur** [comment] 2016-07-06 13:23
osx here - multiple packages

**Comment by osadchiynikita** [comment] 2016-07-06 13:28
Same fetch 502 error for babel-plugin-transform-react-jsx-self

**Comment by alejodaraio** [comment] 2016-07-06 13:31
Same here on ubuntu :/

**Comment by veeracs** [comment] 2016-07-06 13:33
Issue still exists on EC2/Ubuntu, works locally on a Mac.

**Comment by superplussed** [comment] 2016-07-06 13:40
Same issue on CircleCI through a Dockerhub container: 

`npm ERR! fetch failed https://registry.npmjs.org/patch-text/-/patch-text-1.0.2.tgz`

**Comment by thebearjew** [comment] 2016-07-06 13:50
Current issue happening 

Node: 4.0.0
Npm. 3.7.3

Error:

```
npm ERR! fetch failed https://registry.npmjs.org/babel-plugin-transform-react-jsx-self/-/babel-plugin-transform-react-jsx-self-6.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
```

**Comment by stevenjob** [comment] 2016-07-06 13:56
Also having this problem on CircleCI

**Comment by dittonjs** [comment] 2016-07-06 13:57
im having this issue on osx npm: 3.8.3, node v5.10.1

**Comment by esanchezm** [comment] 2016-07-06 14:10
Same here

**Comment by lexyfeito** [comment] 2016-07-06 14:14
Same here, trying to install Karma

**Comment by wei-nete** [comment] 2016-07-06 14:15
Same here

**Comment by tommck** [comment] 2016-07-06 14:16
Same, with combine-lists from multiple machines on different networks

**Comment by arypurnomoz** [comment] 2016-07-06 14:21
Same, with node 6.2.1 and npm 3.9.5

**Comment by danbruder** [comment] 2016-07-06 14:23
Same, with node 6.1.0 and npm 3.8.6

**Comment by OlivierCuyp** [comment] 2016-07-06 14:27
Apparently npm is running into some issue and they are working on it.
Just follow: http://status.npmjs.org/ ;)

**Comment by lianyi** [comment] 2016-07-06 14:47
same issue`npm ERR! node v6.2.2
npm ERR! npm  v3.9.5`

**Comment by dedicatted** [comment] 2016-07-06 14:49
I'm can't even wget anything from my EC2 insance:
`wget https://registry.npmjs.org/babel-plugin-syntax-do-expressions/-/babel-plugin-syntax-do-expressions-6.8.0.tgz
HTTP request sent, awaiting response... 502 Bad Gateway`

But can from my home machine

**Comment by othiym23** [comment] 2016-07-06 14:51
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:51 UTC
Labels: big-bug, bug, registry

**Comment by bdgold** [comment] 2016-07-06 15:12
From https://github.com/npm/npm/issues/13284#issuecomment-230794281

> Fixed temporarily by adding the following in /etc/hosts
> 
> 151.101.36.162 registry.npmjs.com
> 151.101.36.162 registry.npmjs.org

**Comment by ArturVasyliev** [comment] 2017-10-04 07:13
The problem still exists. I have the same issue after more than one year. I am trying to npm install and I get an ECONNREFUSED error, tried to fix it with proxy configuration and set registry path to http-based but nothing happened. _Node version 6.11.4, npm version 3.10.10_

I just think that it is not good when there are several possible solutions and the only one which is helpful is so hard discovered and after one year it haven't been applied inside npm.

**Comment by i-Apoorva** [comment] 2018-03-04 16:00
_Use command_: **npm install npm@latest -g**

then try again.
**Worked for me**
