### ISSUE TITLE
verbose stack TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by apoorvbakshi** [npm/npm#15808] opened 2017-02-21 06:11 UTC
[npm-debug.txt](https://github.com/npm/npm/files/789211/npm-debug.txt)

**Comment by andreivasiletruta** [comment] 2017-02-21 14:04
I have bumped into a similar error while trying to install grunt-cli through npm on windows machine.
Is there like a quick workaround - considering I might be doing something wrong?

**Comment by andreivasiletruta** [comment] 2017-02-21 14:23
at least in my case it seems proxy related. I set the proxies for npm and it started to work
from my perspective this can be closed. it depends on you @apoorvbakshi 
Thanks

**Comment by MartinStern** [comment] 2017-03-03 06:12
I had same problem installing typescript. the solution for me was to use the **cmd** window as **administrator**, or use the Bash terminal installed with git. Both worked for me.

**Comment by legodude17** [comment] 2017-03-03 17:09
Duplicate of #10686.

**Comment by joluga** [comment] 2017-05-19 04:34
Check your spelling. I had the error and it was that I was writing 'coffescript' (One 'e') in the install command line.

**Closed** 2017-06-16 21:56 UTC
Labels: bot-closed, support
