### ISSUE TITLE
Error: fetch failed with status code 502

### ISSUE THREAD

**Issue by venkatesh008** [npm/npm#13296] opened 2016-07-06 13:51 UTC
npm ERR! fetch failed http://registry.npmjs.org/exec-buffer/-/exec-buffer-3.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! fetch failed http://registry.npmjs.org/lodash.templatesettings/-/lodash.templatesettings-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed http://registry.npmjs.org/exec-buffer/-/exec-buffer-3.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed http://registry.npmjs.org/lodash.templatesettings/-/lodash.templatesettings-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed http://registry.npmjs.org/exec-buffer/-/exec-buffer-3.0.0.tgz
npm WARN optional dep failed, continuing imagemin-gifsicle@5.1.0
npm WARN optional dep failed, continuing imagemin-optipng@5.1.0
npm WARN optional dep failed, continuing imagemin-jpegtran@5.0.2
npm ERR! fetch failed http://registry.npmjs.org/lodash.templatesettings/-/lodash.templatesettings-2.4.1.tgz
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/opt/node-v4.3.2-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12

npm ERR! fetch failed with status code 502
npm ERR! 

I am getting this issue at aws ubuntu instance. but this errors are not getting in local ubuntu system

**Comment by jasonmacdonald** [comment] 2016-07-06 14:03
I think NPM is having issues. I just posted a similar npm error but for a different package.

**Comment by lhogstrom** [comment] 2016-07-06 14:06
I am getting the same error

**Comment by gauri-shukla-viz** [comment] 2016-07-06 14:33
We are getting the same error!

**Comment by othiym23** [comment] 2016-07-06 14:55
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:55 UTC
Labels: big-bug, bug, registry
