### ISSUE TITLE
npm install fails in Docker container on system with Docker's userns-remap enabled

### ISSUE THREAD

**Issue by nickwalkmsft** [npm/npm#16892] opened 2017-06-01 22:18 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing an incorrect install.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm crashes on `npm install` when run inside a Docker container on a system with Docker's `userns-remap` enabled.

Docker images that run `npm install` during build (and are successfully built on a system without `userns-remap` enabled) cannot be pulled/run on systems with userns-remap enabled.

I believe it's related to https://github.com/npm/npm/issues/16766. `userns-remap` is picky about user IDs used within the container.

Problem does not occur with previous node/npm versions.

#### How can the CLI team reproduce the problem?

1. On a system with Docker's `userns-remap` enabled, run `docker run -it --rm --entrypoint bash node:8.0.0` (may require `sudo`). This will put you in a shell in the node 8 container.
2. Create a package.json with at least one dependency: `echo '{ "dependencies" : { "express": "latest" } }' > package.json`
3. `npm install`

Log output is [here](https://gist.github.com/nickwalkmsft/92fc97582dca81c07d6ffe80cc11829f).

This can also be reproduced by attempting to build a Docker image with a Dockerfile that runs the commands in steps 2 and 3 on a system with `userns-remap` enabled.

Additionally, a Docker image with the commands from steps 2 and 3 in its build instructions that is successfully built on a machine without `userns-remap` enabled cannot be `docker pull`ed on a machine where it is enabled.

### supporting information:

 - `npm -v` prints: `5.0.0`
 - `node -v` prints: `v8.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by nickwalkmsft** [comment] 2017-06-09 17:42
As can be seen from some of the linked commits, it looks like the core of the problem is running npm as root. Running as a non-root user appears to be a workaround.

**Comment by zkat** [comment] 2017-07-03 21:36
I believe this is a duplicate of https://github.com/npm/npm/issues/16766, so I'm closing it.

**Closed as completed by zkat** 2017-07-03 21:36 UTC
Labels: docker, npm5
