### ISSUE TITLE
init project error

### ISSUE THREAD

**Issue by hefs** [npm/npm#13607] opened 2016-08-08 07:57 UTC
19280 verbose cwd /Users/HeRay/Desktop/MyFirstReactApp
19281 error Darwin 15.6.0
19282 error argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-exact" "react-native"
19283 error node v5.10.1
19284 error npm  v3.8.3
19285 error shasum check failed for /var/folders/7q/6b9pz4m93dv42h7pp97qzvfw0000gn/T/npm-949-7e8f52af/registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
19285 error Expected: c8ce27de0acc76d896d2b1fad3df588d9e82f014
19285 error Actual:   a22f5c7a099b3938038823d7f7c65e5bbc23155c
19285 error From:     https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
19286 error If you need help, you may report this error at:
19286 error     https://github.com/npm/npm/issues
19287 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2016-08-08 14:31
@hefs Have you tried running `npm cache clean`?

**Comment by ebuckley** [comment] 2016-08-08 23:35
I am running into a similar issue.

This seems to be specific to a windows server environment. I have tried running `npm cache clean` as well as manually deleting the npm cache files from `AppData/local` and `AppData/Roaming`

**Comment by hefs** [comment] 2016-08-09 00:38
I run in a Macos server enviroment. I followed the docs from  the official website,and I`ve tried several times.

**Comment by zkat** [comment] 2016-12-09 00:39
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:39 UTC
