### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mr-moon** [npm/npm#14665] opened 2016-11-18 19:17 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
77888 silly build read-pkg@1.1.0
77889 silly build read-pkg-up@1.0.1
77890 verbose stack RangeError: Maximum call stack size exceeded
77890 verbose stack     at Array.map (native)
77890 verbose stack     at Object.color (/home/vagrant/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npmlog/node_modules/console-control-strings/index.js:119:29)
77890 verbose stack     at EventEmitter.log._format (/home/vagrant/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npmlog/log.js:252:51)
77890 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npmlog/log.js:138:24)
77890 verbose stack     at emitThree (events.js:116:13)
77890 verbose stack     at emit (events.js:194:7)
77890 verbose stack     at .<anonymous> (/home/vagrant/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
77890 verbose stack     at emitThree (events.js:116:13)
77890 verbose stack     at emit (events.js:194:7)
77890 verbose stack     at .<anonymous> (/home/vagrant/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
77891 verbose cwd /tactic
77892 error Linux 2.6.32-642.el6.x86_64
77893 error argv "/home/vagrant/.nvm/versions/node/v6.9.1/bin/node" "/home/vagrant/.nvm/versions/node/v6.9.1/bin/npm" "install" "--no-bin-links"
77894 error node v6.9.1
77895 error npm  v3.10.8
77896 error Maximum call stack size exceeded
77897 error If you need help, you may report this error at:
77897 error     <https://github.com/npm/npm/issues>
77898 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: CentOS 6.8
 - Network issues:
   - Geographic location where npm was run: EU
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Package.json:

```json
{
  "name": "project",
  "version": "1.10.0-rc1",
  "private": true,
  "scripts": {
    "lint": "node_modules/.bin/eslint --cache source/module/**/*.js",
    "precommit-msg": "echo 'Pre-commit checks...' && exit 0"
  },
  "pre-commit": [
    "precommit-msg",
    "lint"
  ],
  "dependencies": {
    "socket.io": "^1.3.5"
  },
  "devDependencies": {
    "chalk": "^1.0.0",
    "eslint": "3.8.1",
    "firefox-profile": "^0.4.0",
    "glob": "^5.0.3",
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "^1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^1.0.2",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-less": "^1.4.0",
    "grunt-contrib-requirejs": "^1.0.0",
    "grunt-contrib-sass": "^0.9.2",
    "grunt-contrib-uglify": "^0.8.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-exec": "^0.4.6",
    "grunt-merge-json": "^0.9.5",
    "grunt-string-replace": "^1.0.0",
    "grunt-svgmin": "^2.0.1",
    "grunt-svgstore": "^0.5.0",
    "grunt-text-replace": "^0.4.0",
    "jasmine-core": "^2.2.0",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.12.37",
    "karma-chrome-launcher": "^0.1.12",
    "karma-cli": "0.0.4",
    "karma-coverage": "^0.3.1",
    "karma-jasmine": "^0.3.8",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-requirejs": "^0.2.2",
    "karma-verbose-reporter": "0.0.3",
    "load-grunt-config": "^0.16.0",
    "lodash": "^3.5.0",
    "ng-annotate": "^0.15.4",
    "pre-commit": "^1.1.3",
    "protractor-jasmine2-screenshot-reporter": "^0.2.0",
    "q": "^1.4.1",
    "request": "^2.69.0",
    "time-grunt": "^1.1.0"
  }
}
```

**Comment by legodude17** [comment] 2016-12-20 21:12
Duplicate of #14608.

**Closed** 2017-06-19 04:15 UTC
Labels: big-bug, bot-closed, bug
