### ISSUE TITLE
npm install npm -g (upgrade) - erros

### ISSUE THREAD

**Issue by wojtas911** [npm/npm#10492] opened 2015-11-20 09:29 UTC
Hi,
sudo npm install npm -g
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

Any command generate error

npm install npm-registry-client
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by pliashkou** [comment] 2015-11-20 09:51
@isaacs Please, check this. We have the same

**Comment by sqrthree** [comment] 2015-11-20 10:13
Oh snap. I have the same, and npm is dead.

**Comment by Boboss74** [comment] 2015-11-20 10:21
same

**Comment by RosyTucker** [comment] 2015-11-20 10:24
+1

**Comment by dathwinter** [comment] 2015-11-20 10:35
I get the same issue after installing using https://www.npmjs.com/install.sh

**Comment by joshbrw** [comment] 2015-11-20 11:03
+1

**Comment by kubawalinski** [comment] 2015-11-20 11:03
@RosyTucker Did not help in our case :(

**Comment by alxsad** [comment] 2015-11-20 11:08
+1 on Debian Jessie. Installing using https://www.npmjs.com/install.sh

**Comment by kattybilly** [comment] 2015-11-20 11:33
+1. Same issue with me.

**Comment by charlie-rudenstal** [comment] 2015-11-20 11:45
Recently had the same issue, but `rm -rf /usr/local/lib/node_modules` fixed it for me

**Comment by yanaki** [comment] 2015-11-20 12:34
:+1:  same issue

**Comment by peterbraden** [comment] 2015-11-20 13:31
Reproed with npm install -g npm@latest on SnapCI

**Comment by rvolker** [comment] 2015-11-20 13:57
What's up with this, please? I'm new to npm & homebrew and I keep chancing my tail.I just completed uninstall and clean reinstall of node & npm following a variation of Dan Herberts suggestion, http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

curl -L https://www.npmjs.org/install.sh | sh

What is the recommended method to pull down a stable & tested install of npm?

**Comment by kattybilly** [comment] 2015-11-20 14:12
@rvolker use this cmd `npm install -g npm@latest`

**Comment by stissot** [comment] 2015-11-20 14:12
+1

**Comment by othiym23** [comment] 2015-11-20 15:13
It sounds like a bug I thought was part of `npm@3.4.0` was actually part of `npm@3.4.1` (or was part of both). Since the underlying bug _is_ fixed in `npm@3.5.0`, you should try upgrading from `npm@3.3.6` directly to `npm@next`, which will bypass the buggy versions of npm. If you're currently stuck with a broken npm, firstly I apologize, and you can get back to a working npm by reinstalling Node.js.

**Comment by KenanY** [comment] 2015-11-20 15:40
Duplicate of https://github.com/npm/npm/issues/10394, perhaps?

**Comment by othiym23** [comment] 2015-11-20 16:33
This is indeed a dupe of #10394, and since it's a duplicate, and the underlying issue is resolved (although the fix is kind of annoying, at least until `npm@3.5.0` becomes `latest`), I'm going to close this issue as well. See my final comment on #10394 for explanation and further apologies.

**Closed by othiym23** 2015-11-20 16:33 UTC

**Comment by thomas-dotworx** [comment] 2015-11-21 00:00
I'm having the same issue

**Comment by danielsiwiec** [comment] 2015-11-21 00:01
+1

**Comment by danielsiwiec** [comment] 2015-11-21 01:01
+1

**Comment by danielsiwiec** [comment] 2015-11-21 02:37
+1

**Comment by rvolker** [comment] 2015-11-21 02:40
Me too, still immediately fails.
$ npm --version
module.js:339
throw err;

$ rm -rf .node
$ rm -rf .npm
$ rm -rf .node-gyp
$ brew install node --without-npm
curl -L https://www.npmjs.org/install.sh | sh

I'm just starting to look at the shell script... 
Either it's not getting the latest 3.5.0, or the bug hasn't been smashed?

**Comment by danielsiwiec** [comment] 2015-11-21 02:42
According to https://www.npmjs.com/package/npm, 3.4.1 is still the latest.

**Comment by othiym23** [comment] 2015-11-21 02:44
`npm@3.5.0` is still `npm@next`, for the reasons I outline above – we need to make sure that no new regressions have been introduced by the fix to the previous regressions. The best way to jump over this problem is to reinstall Node using an official Node installer (not Homebrew) and use the packaged npm to upgrade straight to `npm@next`.

**Comment by kubawalinski** [comment] 2015-11-21 05:21
@othiym23 Maybe to save other people from this issue it would be a good idea to release a fix with a new version 3.4.2?

**Comment by othiym23** [comment] 2015-11-21 05:31
The fix is complex enough that it's the primary potential source of regressions. I know this is a super annoying thing to hack around in your build systems, but please, bear with us. Unless there _is_ another regression in there, the current situation will only last until next Wednesday.

**Comment by scottaddie** [comment] 2015-11-21 19:37
For those who are still stuck, a reinstall of Node.js didn't fix the problem on my Windows 10 machine. I had to manually delete the npm folders in my roaming profile folder (cd %APPDATA%). Running npm i -g npm@next after that did work.

**Comment by rvolker** [comment] 2015-11-21 20:50
Thank you for your support and quick response othiym23.

Until npm 3.5.0 is available it's best to avoid homebrew install on osx.

**Comment by nick3499** [comment] 2015-11-23 06:15
After `https://www.npmjs.com/install.sh` install failed...

`rm -rf /usr/local/lib/node_modules`
`curl -L https://www.npmjs.org/install.sh | sh`
`It worked`

`npm -v`
`Error: Cannot find module 'npm-registry-client'`

`npm i npm-registry-client`
`Error: Cannot find module 'npm-registry-client'`

(sounds like a Catch 22)

**Comment by vcernomschi** [comment] 2015-11-23 16:53
I have the same issue.

npm -v
Error: Cannot find module 'npm-registry-client'

**Comment by nick3499** [comment] 2015-11-23 17:12
Had to purge node.js and npm and delete all files and directories outside of project folders. Including .bashrc, etc. I did not change the project folders. They seem to be fine. Then a fresh install of node. Kept running into a problem that seems to be related to upgrading npm after installing node, so I am not upgrading the npm that came with the node install. So far so good. Also, I am running Ubuntu 15.10 while npm supports up to 14.04, so my situation is not ideal to begin with. The next LTS will probably not be around until about the end of April.

**Comment by michaeldscherr** [comment] 2015-11-23 17:48
ok here is what worked for me on **Mac OS X El Capitan (10.11.1)**:

1. git clone NPM in your root directory:  `git clone https://github.com/npm/npm.git npm`
2. move into that directory: `cd npm`
3. run the uninstaller: `sudo make uninstall` -- [documentation reference for uninstall](https://docs.npmjs.com/misc/removing-npm)
  1. per documentation, this will *remove npm, but leave behind anything you've installed.*
4. run NPM install: `npm install npm@latest -g`

hope that helps.

**Comment by NathanWalker** [comment] 2015-11-24 02:59
@michaeldscherr ^ that by far and away, helped me tremendously, thank you. Past couple days have been node/npm hell :(

**Comment by vcernomschi** [comment] 2015-11-24 06:43
Issue was fixed after steps below:

brew cleanup
brew link node
brew uninstall node
brew install node

**Comment by thomas-dotworx** [comment] 2015-11-24 08:08
I did the following on Amazon Linux:
`yum remove -y nodejs`
`yum install -y nodejs`
`npm install npm@VERSIONNUMBER`

**Comment by alxsad** [comment] 2015-11-24 08:24
I install node using https://www.npmjs.com/install.sh by CI-server. Need to fix shell script.

**Comment by bertest** [comment] 2015-11-24 16:43
same issue

**Comment by srinivasanvee** [comment] 2015-11-24 18:45
reinstall latest nodejs fixed the issue in Windows. (4.x)

**Comment by mhurwicz** [comment] 2015-11-25 04:29
After installing node using homebrw on OSX 10.9.5, got this trying to run npm:
 **Error: Cannot find module 'npm-registry-client'**

Tried various things suggested here, most recently:
**brew install node**

Got:
**Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`**

Tried that, got:
**Error: Permission denied - /usr/local/lib/node_modules/npm/AUTHORS**

This:
**npm -v**

Gives this:
**-bash: /Users/mh/.node/bin/npm: No such file or directory**

Could this have anything to do with adding these two lines to my .bash_profile  ?

**PATH=“$PATH:$HOME/bin”**

**PATH="$HOME/.node/bin:$PATH"**

New at this, any help will be greatly appreciated.

**Comment by designlobby** [comment] 2015-11-25 19:37
@michaeldscherr Hi, i tried your solution for El Capitan but on running "npm install npm@latest -g" im getting the error:

 -bash: /usr/local/bin/npm: No such file or directory

Any suggestions?

**Comment by michaeldscherr** [comment] 2015-11-25 20:31
@designlobby I also had node install view brew (which comes with NPM). maybe try to install node?

`brew install node`

my `where npm` shows:

`/Users/mscherr/.node/bin/npm`
`/usr/local/bin/npm`

but my `which npm` shows:

`/Users/mscherr/.node/bin/npm`

so it appears that when I ran the uninstall script, it then moved my node NPM up front.

**Comment by TakoSeijin** [comment] 2015-11-25 20:52
@vcernomschi Thank you this solution worked for me

**Comment by othiym23** [comment] 2015-11-26 00:21
`npm@3.5.0` is now the latest stable version of npm. It contains a fix for what caused your build servers to break themselves, so after removing and reinstalling node one more time, `npm install npm -g` will no longer produce a broken npm, _unless_ you're running `npm@3.4.1` (or `npm@3.4.0`) when you do so. Once again, my apologies for the mess.

**Comment by halhenke** [comment] 2015-11-26 03:10
`brew cleanup`
`brew uninstall node`
`brew install node`
`npm i -g npm`

brought me up to `3.5.0` and resolved the issue on El Capitan.

**Comment by nick3499** [comment] 2015-11-27 04:47
In Ubuntu 15.10: 
 - installed current node tar.gz (5.1.0)
 - symlinked `node` and `npm` (`/opt/node-v5.1.0-linux-x64/bin`)
 - upgraded npm 3.3.12 to 3.5.0 (`npm install npm@latest`)
 - installed a node module in a project dir > no error message

No longer receiving `Error: Cannot find module 'npm-registry-client'` error message.

**Comment by designlobby** [comment] 2015-11-27 10:12
For installs via package download, and not using brew, this helped me: https://github.com/brock/node-reinstall
