### ISSUE TITLE
npm update doesn't do anything at all

### ISSUE THREAD

**Issue by TheDutchCoder** [npm/npm#11108] opened 2016-01-10 18:24 UTC
I'm encountering what I believe to be a bug, where `npm update` or `npm update --dev` is not doing anything at all.

My package.json contains some outdated packages:
```
Package            Current  Wanted  Latest  Location
gulp-sass            1.3.3   1.3.3   2.1.1  twentyfifteen-child
glob                 4.5.3   4.5.3   6.0.4  twentyfifteen-child
gulp-autoprefixer    2.3.1   2.3.1   3.1.0  twentyfifteen-child
gulp-jshint         1.12.0  1.12.0   2.0.0  twentyfifteen-child
gulp-load-plugins    0.8.1   0.8.1   1.2.0  twentyfifteen-child
gulp-plumber         0.6.6   0.6.6   1.0.1  twentyfifteen-child
gulp-sass            1.3.3   1.3.3   2.1.1  twentyfifteen-child
gulp-scss-lint       0.2.4   0.2.4   0.3.9  twentyfifteen-child
jshint-stylish       1.0.2   1.0.2   2.1.0  twentyfifteen-child
```

However, running `npm update`, `sudo npm update`, `npm update --dev`, or  `sudo npm update --dev` doesn't do anything and nothing gets updated.

This is extremely frustrating, as I have to manually uninstall and then reinstall each package.

Verbose logging gives me the following message for each outdated package:
```
npm verb outdated not updating gulp-sass because it's currently at the maximum version that matches its specified semver range
```

Is this due to packages being installed as `"glob": "^4.5.3",` where it will ignore anything above `5.x.y`?
If so, how do I prevent this from happening, there's very little documentation about `npm update` that deals with this and in my opinion it should be easy to just update everything regardless of their version if I chose so.

Any help would be appreciated!

**Comment by ruipaulo** [comment] 2016-01-11 09:40
I suppose this is not a bug, but a problem of your package.json:
 `"glob": "^4.5.3"` means npm will update to any newer version 4.x.x but not to 5.x.x or 6.x.x.
If you want any newer version try `"glob":">4.5.3"` or even `"glob":"*"`

See also: https://docs.npmjs.com/cli/update#caret-dependencies-below-1-0-0

**Comment by TheDutchCoder** [comment] 2016-01-11 12:04
Is there any way to install a package with --save-dev that prevents the ^?

It's silly that I have to go in and manually adjust that each time.

**Comment by ruipaulo** [comment] 2016-01-11 13:10
You can use `npm config set save-prefix=''` to some different prefix.

http://stackoverflow.com/questions/16073603/how-do-i-update-each-dependency-in-package-json-to-the-latest-version

**Comment by othiym23** [comment] 2016-01-18 06:41
> Is this due to packages being installed as `"glob": "^4.5.3",` where it will ignore anything above `5.x.y`?

Yes, and this is intended to protect you from whatever breaking changes have been introduced that caused the semver-major bump. A major version increment implies that something has changed in a backwards-incompatible way, and the various semver operators are designed to protect apps using semver from being broken by these kinds of changes.

It is a _very_ good idea to update packages including semver-major version changes one at a time, using something like `npm install --save-dev 'gulp-sass@^2'` and then running the app's tests to ensure that the changes haven't broken anything. This is what I do when dealing with npm's own (bundled) dependencies, and yes, it's a little laborious, but it's a _lot_ simpler than upgrading everything at once and spending several hours figuring which of several upgrades caused the tests to break.

The current behavior is absolutely intended, so I'm closing this issue. (While you can escape out of it by something like `npm config set save-prefix ">="`, I strongly recommend not doing that. Both you and your users _will_ end up losing time to this at some point in the future, should you go down that path.)

**Closed by othiym23** 2016-01-18 06:41 UTC
Labels: support
