### ISSUE TITLE
NPM error on MacOS Sierra 

### ISSUE THREAD

**Issue by mragwa** [npm/npm#14187] opened 2016-10-05 10:12 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I tried to update npm on MacOS Sierra but i'm getting an error:
 `uid must be an unsigned int`
then when i tried to install ionic i got the same error.
i'm using:
node v4.6.0
npm  v3.10.8

I installed latest version of NodeJS 
also uninstalled latest ionic version
then removed all npm cache files
but while installing it again i get the same error.

any solution will be appreciated. 
thank you.

**Comment by KenanY** [comment] 2016-10-05 10:53
Duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-10-05 10:53 UTC
Labels: support
