### ISSUE TITLE
Using fuse sshfs with local git workspaces leads to errors when using npm

### ISSUE THREAD

**Issue by silkentrance** [npm/npm#7120] opened 2015-01-12 22:04 UTC
I am using a virtual box machine for hosting my linux box where I do the actual development. The physical host is a MacBook Pro running OSX Yosemite.

I have settled upon using fuse sshfs to mount my workspaces located on the physical host instead of using virtual box shared folders.

Whenever I try to `npm install` the dependencies for a given package from within a folder inside that fuse sshfs mount point, npm will fail since it is not able to preserve or set the permissions/ownership for a given installed package.

It would be great if npm would not try to restore the ownership/permission, or at least would issue warnings instead of terminally failing upon these errors so that the installation of the dependencies will succeed.

**Comment by smikes** [comment] 2015-01-13 14:20
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

**Comment by silkentrance** [comment] 2015-01-13 17:42
See https://gist.github.com/silkentrance/dbd532c3a8fff00abafa

**Comment by silkentrance** [comment] 2015-01-13 17:46
I basically boils down to npm trying to change the ownership and then fails

````
564 error Error: EACCES, chown '/home/cklein/workspaces/consolidated workspaces/projects/vibejs/libraries/vibejs-subclassof/node_modules/semver/package.json'
564 error  { [Error: EACCES, chown '/home/cklein/workspaces/consolidated workspaces/projects/vibejs/libraries/vibejs-subclassof/node_modules/semver/package.json']
564 error   errno: 3,
564 error   code: 'EACCES',
564 error   path: '/home/cklein/workspaces/consolidated workspaces/projects/vibejs/libraries/vibejs-subclassof/node_modules/semver/package.json',
564 error   fstream_finish_call: 'chown',
564 error   fstream_type: 'File',
564 error   fstream_path: '/home/cklein/workspaces/consolidated workspaces/projects/vibejs/libraries/vibejs-subclassof/node_modules/semver/package.json',
564 error   fstream_class: 'FileWriter',
564 error   fstream_stack:
564 error    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:308:19',
564 error      '/usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:143:7',
564 error      'Object.oncomplete (evalmachine.<anonymous>:107:15)' ] }
565 error Please try running this command again as root/Administrator.
566 verbose exit [ 3, true ]
```

**Comment by silkentrance** [comment] 2015-01-13 17:55
Apart of that, I am actively using `chmod`, `git`. `vi`, `mkdir`, `touch` and other CLI tools and everything works just fine, even running `vows` and generating a `coverage.html` document from files having been instrumented using `coffee-coverage` and also `grunt` work just fine in that scenario.

Except npm, of course :grin:

**Comment by silkentrance** [comment] 2015-01-13 17:58
I do not know whether the error regarding `chown` stems from setting the user or the group. Here is the default user/group assignment for that directory.

`
drwxr-xr-x 1 cklein dialout    544 Jan 13 17:52 .
drwxr-xr-x 1 cklein dialout    476 Jan 12 23:11 ..
-rw-r--r-- 1 cklein dialout    269 Dec 29 21:13 CHANGELOG
drwxr-xr-x 1 cklein dialout    442 Jan 12 22:44 .git
-rw-r--r-- 1 cklein dialout     80 Nov 28 19:49 .gitignore
-rw-r--r-- 1 cklein dialout  10768 Jan 12 22:44 Gruntfile.coffee
-rw-r--r-- 1 cklein dialout  10143 Nov 17 20:14 LICENSE
-rw-r--r-- 1 cklein dialout    352 Nov 17 20:14 NOTES.md
-rw-r--r-- 1 cklein dialout 127942 Jan 13 17:52 npm-debug.log
-rw-r--r-- 1 cklein dialout 127950 Jan 13 17:37 npm-debug.log.1
-rw-r--r-- 1 cklein dialout   1236 Jan 12 22:44 package.json
-rw-r--r-- 1 cklein dialout   3034 Dec 29 21:08 README.md
drwxr-xr-x 1 cklein dialout    204 Dec 29 19:51 src
drwxr-xr-x 1 cklein dialout    272 Dec 29 21:03 test
-rw-r--r-- 1 cklein dialout    124 Nov 20 20:17 TODO
-rw-r--r-- 1 cklein dialout     41 Nov 22 18:51 .travis.yml
`

**Comment by silkentrance** [comment] 2015-01-13 18:04
But I think that we can narrow it down to

```
> chown cklein LICENSE
-> no error or other kind of message

> chown cklein:dialout LICENSE
-> no error or other kind of message

> chown cklein:cklein LICENSE
chown: changing ownership of ‘LICENSE’: Permission denied
```

It seems that trying to set the group to `cklein` fails as its `gid` is unknown to the physical host.

Perhaps not trying to set the group would help? In that case, the `g+s` flag on the directory will also have an effect and the group ownership will be inherited from that directory.

**Comment by silkentrance** [comment] 2015-01-13 18:16
It seems that you are stat-ing the cached files, which, of course have an ownership of cklein:cklein and apply the same uid/gid to the files written to and directories created in for example ./node_modules.

See for example lib/cache/add-local.js @ around line 102.

**Comment by othiym23** [comment] 2015-01-13 18:23
*Not* setting the permissions within the cache causes problems for far more people, though, because many users are using `sudo` for global installs, and not cleaning up the permissions would cause their cache folders to end up in an inconsistent state. In addition, without a bunch of extra logic, npm can't tell whether it's important for the uid or gid to be set before caching.

I could maybe see making failures to `chownr` being configurable as a warn-only option, but in general, making sure the cache has consistent permissions addresses a very significant and longstanding supportability issue, and any proposed changes need to take that into account.

**Comment by silkentrance** [comment] 2015-01-13 18:27
Yes, making this a warn-only thing would be great.

**Comment by silkentrance** [comment] 2015-01-13 18:35
I will try and provide a patch for this by reusing the --force option.

**Comment by silkentrance** [comment] 2015-01-13 20:10
This one is quite involved as chown is not the only culprit. The tar utility will try to set the uid/gid and will always run into an error. Looking into this now.

**Comment by silkentrance** [comment] 2015-01-13 20:48
Yikes!, I have looked into the tar pits of hell :grin:  Nothing will harm me now, ever.

**Comment by silkentrance** [comment] 2015-01-13 21:21
Well, it seems that the actual error with the tar util lies in fstream#Writer.
There it tests for (look for the keyword EPERM)

```
195 function endChown (me, want, current, path, cb) {
196   // Don't even try it unless root.  Too easy to EPERM.
197   if (process.platform === "win32") return cb()
198   if (!process.getuid || !process.getuid() === 0) return cb()
```

Here, `!process.getuid() === 0` will fail, causing the process to continue trying to change the ownership.

Changing this to just `!process.getuid() == 0` seems to do the trick. I am now able to `npm install`.

Will file an issue against fstream.

**Comment by silkentrance** [comment] 2015-01-15 19:47
See also PR #7143.

**Comment by silkentrance** [comment] 2015-01-22 22:06
Further investigating this: running npm -g install from inside an sshfs mount will fail as well.
I do not know why, but I guess that npm is trying to create a file in that directory or something else.
Perhaps npm should use /tmp/<npm-tmp-file-or-folder> instead of writing to the current directory...

**Comment by smikes** [comment] 2015-01-23 02:16
`npm` doesn't write temp files in the current directory, but it may be trying to write an `npm-debug.log`  There's a PR somewhere for making that go into the (known-writable) npm cache directory...

**Comment by silkentrance** [comment] 2015-01-23 21:25
Good to know, will not further investigate into that direction.

**Comment by silkentrance** [comment] 2015-02-21 17:47
Good news, the patch for fstream seems to have done the trick. Closing this one now.

**Comment by silkentrance** [comment] 2015-02-21 22:17
Must reopen, as npm fails to update existing node_modules as per the following error

```
npm ERR! Linux 3.16-3-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.13.0-pre
npm ERR! npm  v2.6.0
npm ERR! path /home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cklein/workspaces/consolidated_workspaces/projects/vibejs/libraries/vibejs-mtemitter/npm-debug.log
```

**Comment by smikes** [comment] 2015-02-21 23:06
`node>=0.11` sometimes throws these errors, and it's not clear to us that this is an `npm` problem.  Can you reproduce this with `node@0.10` or `iojs@1.3.0`?

Also you may be able to work around this by taking ownership of the affected files:

```
$ sudo chown -R $(whoami) node_modules
```

**Comment by silkentrance** [comment] 2015-02-21 23:44
@smikes Taking over ownership in this situation is not a viable option as I am not root and mounted a remote file system tree via sshfs.

At the moment I am using node@v0.13.0-pre

**Comment by smikes** [comment] 2015-02-21 23:51
Right, but the deeper question is: are you getting EACCES because of an error in `npm`, in which case, of course here is the right place to raise the issue; or is it a problem with `node@0.13` (which is, of course, on the unstable line); or possibly some interaction between your filesystem / OS / toolchain.

So when you get the EACCES error, does the file exist? Is its parent writable by your user?

Also, what is your goal in running `npm update` ?  With `npm@2.6.0`, that will start an install on all outdated dependencies at once, asynchronously.  That's probably not a good idea.  

You can try `npm --depth 0 update` which will only update the immediate dependencies of your module.

**Comment by iarna** [comment] 2015-02-22 01:04
(Wrong button 😁)

**Comment by silkentrance** [comment] 2015-02-22 18:32
Here are some steps to reproduce the issue:

1. I used npm link grunt-coffee-coverage which symlink from ./node_modules/grunt-coffee-coverage to the globally installed /usr/local/lib/node_modules/grunt-coffee-coverage
2. The globally installed one is of course owned by root
3. Now I tried to npm update and the process will fail upon trying to unlink ./node_modules/grunt-coffee-coverage/node_modules/.bin/coffeeCoverage

It seems as if npm update tries to update the linked module instead of unlinking and then reinstalling the module in the user's context.

**Comment by silkentrance** [comment] 2015-02-22 18:46
@iarna Please have a look at https://github.com/npm/npm/issues/7120#issuecomment-75449780

**Comment by jurajseffer** [comment] 2015-12-22 11:19
In my use case, Docker instance uses local volume that is mounted via sshfs from the host system. The eagerness of npm to change owners during `npm link` makes it unusable. Wish I could disable it.

**Comment by silkentrance** [comment] 2015-12-22 19:16
@jurajseffer the bindfs trick is a nice work around. thanks for the hint!

**Comment by othiym23** [comment] 2016-10-11 20:34
Closing as a result of https://github.com/npm/npm/issues/7120#issuecomment-75449780; there are still some issue around links, permissions, and filesystems that don't support them, but they can be handled better individually on new issues. Thanks for your time!

**Closed by othiym23** 2016-10-11 20:34 UTC
Labels: feature-request, patch-welcome
