### ISSUE TITLE
Environment variables which begin with DYLD_ are not available to npm scripts

### ISSUE THREAD

**Issue by iambrandonn** [npm/npm#13243] opened 2016-07-01 18:07 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I set an environment variable that begins with `DYLD_` it is `undefined` when I run an npm script. If I run the code directly (i.e. `node index.js`) it is defined as expected.

#### How can the CLI team reproduce the problem?

1. Set an environment variable like this `export DYLD_TEST=hi`
2. Create a JS file like this:
``` javascript
console.log(process.env.DYLD_TEST);
```
3. Setup a npm script to execute that file.
4. Run the script and note it outputs `undefined`.

### supporting information:

 - `npm -v` prints: 3.8.5
 - `node -v` prints: v4.2.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X - El Capitan
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by othiym23** [comment] 2016-07-05 21:28
A patch to `lib/utils/lifecycle.js` to make it stop filtering out these environment variables would be welcome. Thanks for your time!

**Comment by lholmquist** [comment] 2016-09-08 16:30
@othiym23 if no one has fixed this yet, mind if i take a try at it?

**Comment by legodude17** [comment] 2016-09-08 18:14
In [here](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L306-L307), everything not starting with `npm_` are copied. This should mean that your `DYLD_` env should be there still.

**Comment by lholmquist** [comment] 2016-09-08 18:17
@legodude17 currently debugging this and after that code,  those `DYLD_` env vars are still there, but at some point after it goes away,  not sure why yet.  still hitting next line in the debugger :)

**Comment by legodude17** [comment] 2016-09-08 18:36
With index.js being
```js
console.log(process.env.DYLD_TEST);
```
and running `npm test` that ran `node index.js`, it printed `undefined`. But with `DYLD_TEST=1 npm test`, it printed 1.

**Comment by lholmquist** [comment] 2016-09-08 19:19
@legodude17 @othiym23 @iambrandonn npm scripts basically just spawns a child process,  this is basically, what it is running, https://gist.github.com/lholmquist/0382f71f15fdb39a856afb562a7fa401

this also outputs the `undefined` when `DYLD_TEST=hi`

so it doesn't seem like it is an "npm" issue,  but that is weird though

**Comment by lholmquist** [comment] 2016-09-08 20:23
probably a "no duh", but it is only related to OS X,  the spawn example i gave above works on ubuntu(15.05)

**Comment by legodude17** [comment] 2016-09-08 22:56
That explains why it was working for me on Ubuntu 15.10

**Comment by lholmquist** [comment] 2016-09-09 13:37
Just created a node issue,  https://github.com/nodejs/node/issues/8465

**Comment by lholmquist** [comment] 2016-09-13 13:25
According to the Node issue i created for the child_process(https://github.com/nodejs/node/issues/8465), which has been closed,  this is not a bug, but is standard behavior on OSX.  I think this can probably be closed

**Comment by othiym23** [comment] 2016-09-13 16:58
OK, I'm going to close this, @lholmquist. Thanks for doing the investigative work, and good luck figuring out how to get this information through to your build! Dynamic linking is kind of a pain in any platform, and there are a few wrinkles to it on OS X; as you've now learned, that make it extra challenging.

**Closed by othiym23** 2016-09-13 16:58 UTC
Labels: bug, lifecycle, patch-welcome
