### ISSUE TITLE
selectively install only dependencies and / or devDependencies from shrinkwrap

### ISSUE THREAD

**Issue by andersjanmyr** [npm/npm#5403] opened 2014-06-04 11:06 UTC
We use `npm shrinkwrap` to lock down our `devDependencies` so that our CI machine does not randomly fail.

We also use `npm shrinkwrap` to lock down our dependencies for production deployment. 

Currently we cannot do this (without unwanted file manipulation) since `npm shrinkwrap` only saves one tree of dependencies into `npm-shrinkwrap.json`.

If we use `npm shrinkwrap --dev`, the `dependencies` section contains all dependencies and if we use `npm shrinkwrap`, it only contains production dependencies.

I propose that `npm-shrinkwrap.json` mirrors the `devDependencies` and `dependencies` sections of `package.json` in order to support locking down both development and production dependencies at the same time.

**Comment by SirZach** [comment] 2015-07-09 15:20
is this going to be fixed in NPM 3? would love to have this feature

**Comment by marcello3d** [comment] 2015-07-10 00:23
Just hit a build failure because devDependencies is not covered by shrinkwrap and a devDependency's dependency introduced a breaking change.

**Comment by SirZach** [comment] 2015-07-10 00:55
That was the cause for finding this issue

**Comment by iarna** [comment] 2015-07-10 03:38
So this is not currently in npm@3 (which is already out). We're certainly not going to delay its exit from beta for any new features, but if there were a pull request we would absolutely consider it– new stuff goes in every week.

**Comment by jackyzhai** [comment] 2016-07-16 06:32
+1 for this feature. =)

**Comment by othiym23** [comment] 2016-07-19 20:40
This will be resolved when #10073 is (finally) merged – see that pull request for further details, as well as what remains to be done to get it over the line and landed.

**Comment by busches** [comment] 2016-09-27 20:00
#10073 was merged in back in August. This should now be resolved. :)

cc\ @KenanY

**Comment by KenanY** [comment] 2016-09-27 20:56
woot!

**Closed by KenanY** 2016-09-27 20:56 UTC
Labels: already-looked-at, feature-request, shrinkwrap
