### ISSUE TITLE
Unable to install Ionic2 and Cordova

### ISSUE THREAD

**Issue by vijaypatoliya** [npm/npm#16454] opened 2017-04-27 03:46 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?
unable to install ionic 2 and cordova

#### How can the CLI team reproduce the problem?
npm install -g ionic cordova

### supporting information:

 - `npm -v` prints:
3.10.10

 - `node -v` prints:
6.10.2

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
Window 8.1

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic',
1 verbose cli   'cordova' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchPackageMetaData cordova
9 silly fetchNamedPackageData ionic
10 silly mapToRegistry name ionic
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'ionic',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'ionic',
13 silly mapToRegistry   name: 'ionic',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/ionic
15 silly fetchNamedPackageData cordova
16 silly mapToRegistry name cordova
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'cordova',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'cordova',
19 silly mapToRegistry   name: 'cordova',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/cordova
21 verbose request uri https://registry.npmjs.org/ionic
22 verbose request no auth needed
23 info attempt registry request try #1 at 8:52:42 AM
24 verbose request id 23da6fce34e5a6eb
25 http request GET https://registry.npmjs.org/ionic
26 verbose request uri https://registry.npmjs.org/cordova
27 verbose request no auth needed
28 info attempt registry request try #1 at 8:52:43 AM
29 http request GET https://registry.npmjs.org/cordova
30 http 200 https://registry.npmjs.org/ionic
31 verbose headers { server: 'nginx/1.10.1',
31 verbose headers   'content-type': 'application/json',
31 verbose headers   'last-modified': 'Wed, 26 Apr 2017 20:08:50 GMT',
31 verbose headers   etag: 'W/"5900fe52-fa324"',
31 verbose headers   'content-encoding': 'gzip',
31 verbose headers   'cache-control': 'max-age=300',
31 verbose headers   'content-length': '55698',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Thu, 27 Apr 2017 03:23:49 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   age: '0',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-ams4134-AMS',
31 verbose headers   'x-cache': 'HIT',
31 verbose headers   'x-cache-hits': '1',
31 verbose headers   'x-timer': 'S1493263429.076870,VS0,VE86',
31 verbose headers   vary: 'Accept-Encoding' }
32 silly get cb [ 200,
32 silly get   { server: 'nginx/1.10.1',
32 silly get     'content-type': 'application/json',
32 silly get     'last-modified': 'Wed, 26 Apr 2017 20:08:50 GMT',
32 silly get     etag: 'W/"5900fe52-fa324"',
32 silly get     'content-encoding': 'gzip',
32 silly get     'cache-control': 'max-age=300',
32 silly get     'content-length': '55698',
32 silly get     'accept-ranges': 'bytes',
32 silly get     date: 'Thu, 27 Apr 2017 03:23:49 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     age: '0',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-ams4134-AMS',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '1',
32 silly get     'x-timer': 'S1493263429.076870,VS0,VE86',
32 silly get     vary: 'Accept-Encoding' } ]
33 verbose get saving ionic to C:\Users\patoliya\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
34 verbose correctMkdir C:\Users\patoliya\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
35 verbose makeDirectory C:\Users\patoliya\AppData\Roaming\npm-cache creation not in flight; initializing
36 verbose makeCacheDir UID & GID are irrelevant on win32
37 http 200 https://registry.npmjs.org/cordova
38 verbose headers { server: 'nginx/1.10.1',
38 verbose headers   'content-type': 'application/json',
38 verbose headers   'last-modified': 'Wed, 26 Apr 2017 14:25:02 GMT',
38 verbose headers   etag: 'W/"5900adbe-13f0a0"',
38 verbose headers   'content-encoding': 'gzip',
38 verbose headers   'cache-control': 'max-age=300',
38 verbose headers   'content-length': '46030',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   date: 'Thu, 27 Apr 2017 03:23:49 GMT',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   age: '265',
38 verbose headers   connection: 'keep-alive',
38 verbose headers   'x-served-by': 'cache-ams4444-AMS',
38 verbose headers   'x-cache': 'HIT',
38 verbose headers   'x-cache-hits': '3',
38 verbose headers   'x-timer': 'S1493263429.087305,VS0,VE0',
38 verbose headers   vary: 'Accept-Encoding' }
39 silly get cb [ 200,
39 silly get   { server: 'nginx/1.10.1',
39 silly get     'content-type': 'application/json',
39 silly get     'last-modified': 'Wed, 26 Apr 2017 14:25:02 GMT',
39 silly get     etag: 'W/"5900adbe-13f0a0"',
39 silly get     'content-encoding': 'gzip',
39 silly get     'cache-control': 'max-age=300',
39 silly get     'content-length': '46030',
39 silly get     'accept-ranges': 'bytes',
39 silly get     date: 'Thu, 27 Apr 2017 03:23:49 GMT',
39 silly get     via: '1.1 varnish',
39 silly get     age: '265',
39 silly get     connection: 'keep-alive',
39 silly get     'x-served-by': 'cache-ams4444-AMS',
39 silly get     'x-cache': 'HIT',
39 silly get     'x-cache-hits': '3',
39 silly get     'x-timer': 'S1493263429.087305,VS0,VE0',
39 silly get     vary: 'Accept-Encoding' } ]
40 verbose get saving cordova to C:\Users\patoliya\AppData\Roaming\npm-cache\registry.npmjs.org\cordova\.cache.json
41 verbose correctMkdir C:\Users\patoliya\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
42 silly install normalizeTree
43 silly loadCurrentTree Finishing
44 silly loadIdealTree Starting
45 silly install loadIdealTree
46 silly cloneCurrentTree Starting
47 silly install cloneCurrentTreeToIdealTree
48 silly cloneCurrentTree Finishing
49 silly loadShrinkwrap Starting
50 silly install loadShrinkwrap
51 silly loadShrinkwrap Finishing
52 silly loadAllDepsIntoIdealTree Starting
53 silly install loadAllDepsIntoIdealTree
54 silly resolveWithNewModule ionic@2.2.3 checking installable status
55 silly cache add args [ 'ionic', null ]
56 verbose cache add spec ionic
57 silly resolveWithNewModule cordova@6.5.0 checking installable status
58 silly cache add args [ 'cordova', null ]
59 verbose cache add spec cordova
60 silly cache add parsed spec Result {
60 silly cache add   raw: 'ionic',
60 silly cache add   scope: null,
60 silly cache add   escapedName: 'ionic',
60 silly cache add   name: 'ionic',
60 silly cache add   rawSpec: '',
60 silly cache add   spec: 'latest',
60 silly cache add   type: 'tag' }
61 silly addNamed ionic@latest
62 verbose addNamed "latest" is being treated as a dist-tag for ionic
63 info addNameTag [ 'ionic', 'latest' ]
64 silly mapToRegistry name ionic
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry https://registry.npmjs.org/
67 silly mapToRegistry data Result {
67 silly mapToRegistry   raw: 'ionic',
67 silly mapToRegistry   scope: null,
67 silly mapToRegistry   escapedName: 'ionic',
67 silly mapToRegistry   name: 'ionic',
67 silly mapToRegistry   rawSpec: '',
67 silly mapToRegistry   spec: 'latest',
67 silly mapToRegistry   type: 'tag' }
68 silly mapToRegistry uri https://registry.npmjs.org/ionic
69 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
70 silly cache add parsed spec Result {
70 silly cache add   raw: 'cordova',
70 silly cache add   scope: null,
70 silly cache add   escapedName: 'cordova',
70 silly cache add   name: 'cordova',
70 silly cache add   rawSpec: '',
70 silly cache add   spec: 'latest',
70 silly cache add   type: 'tag' }
71 silly addNamed cordova@latest
72 verbose addNamed "latest" is being treated as a dist-tag for cordova
73 info addNameTag [ 'cordova', 'latest' ]
74 silly mapToRegistry name cordova
75 silly mapToRegistry using default registry
76 silly mapToRegistry registry https://registry.npmjs.org/
77 silly mapToRegistry data Result {
77 silly mapToRegistry   raw: 'cordova',
77 silly mapToRegistry   scope: null,
77 silly mapToRegistry   escapedName: 'cordova',
77 silly mapToRegistry   name: 'cordova',
77 silly mapToRegistry   rawSpec: '',
77 silly mapToRegistry   spec: 'latest',
77 silly mapToRegistry   type: 'tag' }
78 silly mapToRegistry uri https://registry.npmjs.org/cordova
79 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
80 verbose get https://registry.npmjs.org/ionic not expired, no request
81 silly addNameTag next cb for ionic with tag latest
82 silly addNamed ionic@2.2.3
83 verbose addNamed "2.2.3" is a plain semver version for ionic
84 verbose get https://registry.npmjs.org/cordova not expired, no request
85 silly addNameTag next cb for cordova with tag latest
86 silly addNamed cordova@6.5.0
87 verbose addNamed "6.5.0" is a plain semver version for cordova
88 silly mapToRegistry name ionic
89 silly mapToRegistry using default registry
90 silly mapToRegistry registry https://registry.npmjs.org/
91 silly mapToRegistry data Result {
91 silly mapToRegistry   raw: 'ionic',
91 silly mapToRegistry   scope: null,
91 silly mapToRegistry   escapedName: 'ionic',
91 silly mapToRegistry   name: 'ionic',
91 silly mapToRegistry   rawSpec: '',
91 silly mapToRegistry   spec: 'latest',
91 silly mapToRegistry   type: 'tag' }
92 silly mapToRegistry uri https://registry.npmjs.org/ionic
93 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz not in flight; adding
94 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz',
94 verbose addRemoteTarball   '27fb75bf5f357b319ab23a5df3a1a098d2d9d27d' ]
95 silly mapToRegistry name cordova
96 silly mapToRegistry using default registry
97 silly mapToRegistry registry https://registry.npmjs.org/
98 silly mapToRegistry data Result {
98 silly mapToRegistry   raw: 'cordova',
98 silly mapToRegistry   scope: null,
98 silly mapToRegistry   escapedName: 'cordova',
98 silly mapToRegistry   name: 'cordova',
98 silly mapToRegistry   rawSpec: '',
98 silly mapToRegistry   spec: 'latest',
98 silly mapToRegistry   type: 'tag' }
99 silly mapToRegistry uri https://registry.npmjs.org/cordova
100 verbose addRemoteTarball https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz not in flight; adding
101 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz',
101 verbose addRemoteTarball   'e6ec81b17dd50c17c40b4b87330f7ced38fb0b47' ]
102 info retry fetch attempt 1 at 8:52:44 AM
103 info attempt registry request try #1 at 8:52:44 AM
104 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz
105 info retry fetch attempt 1 at 8:52:44 AM
106 info attempt registry request try #1 at 8:52:44 AM
107 http fetch GET https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz
108 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz
109 http fetch 200 https://registry.npmjs.org/cordova/-/cordova-6.5.0.tgz
110 silly fetchAndShaCheck shasum e6ec81b17dd50c17c40b4b87330f7ced38fb0b47
111 verbose addTmpTarball C:\Users\patoliya\AppData\Local\Temp\npm-7028-f6d2a73a\registry.npmjs.org\cordova\-\cordova-6.5.0.tgz not in flight; adding
112 verbose addTmpTarball already have metadata; skipping unpack for cordova@6.5.0
113 verbose correctMkdir C:\Users\patoliya\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
114 silly cache afterAdd cordova@6.5.0
115 verbose afterAdd C:\Users\patoliya\AppData\Roaming\npm-cache\cordova\6.5.0\package\package.json not in flight; writing
116 verbose correctMkdir C:\Users\patoliya\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
117 verbose afterAdd C:\Users\patoliya\AppData\Roaming\npm-cache\cordova\6.5.0\package\package.json written
118 info retry will retry, error on last attempt: Error: read ECONNRESET
119 silly fetchAndShaCheck shasum 27fb75bf5f357b319ab23a5df3a1a098d2d9d27d
120 silly rollbackFailedOptional Starting
121 silly rollbackFailedOptional Finishing
122 silly runTopLevelLifecycles Finishing
123 silly install printInstalled
124 verbose stack Error: shasum check failed for C:\Users\patoliya\AppData\Local\Temp\npm-7028-f6d2a73a\registry.npmjs.org\ionic\-\ionic-2.2.3.tgz
124 verbose stack Expected: 27fb75bf5f357b319ab23a5df3a1a098d2d9d27d
124 verbose stack Actual:   52bd0cf8984ffb335eb3ee39cb5189f8a489a100
124 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz
124 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
124 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
124 verbose stack     at emitNone (events.js:91:20)
124 verbose stack     at ReadStream.emit (events.js:185:7)
124 verbose stack     at endReadableNT (_stream_readable.js:974:12)
124 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
124 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
125 verbose cwd F:\Office\Work\RandD\ionic2
126 error Windows_NT 6.3.9600
127 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
128 error node v6.10.2
129 error npm  v3.10.10
130 error shasum check failed for C:\Users\patoliya\AppData\Local\Temp\npm-7028-f6d2a73a\registry.npmjs.org\ionic\-\ionic-2.2.3.tgz
130 error Expected: 27fb75bf5f357b319ab23a5df3a1a098d2d9d27d
130 error Actual:   52bd0cf8984ffb335eb3ee39cb5189f8a489a100
130 error From:     https://registry.npmjs.org/ionic/-/ionic-2.2.3.tgz
131 error If you need help, you may report this error at:
131 error     <https://github.com/npm/npm/issues>
132 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-04-27 16:17
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-04-29 06:44 UTC
Labels: support
