### ISSUE TITLE
An error occurred while running npm install

### ISSUE THREAD

**Issue by Mahichandran89** [npm/npm#17484] opened 2017-06-28 06:31 UTC
> npm install
? Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! git clone
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-d75da30c
        C:\Users\intel\AppData\Local\Temp\npm-2912-4dbb51ae\git-cache-336fbd82\3
1d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\intel\AppData\Local\Temp\npm-2912-4dbb51ae\git-cache-336fbd82\
31d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-d75da30c
        C:\Users\intel\AppData\Local\Temp\npm-2912-4dbb51ae\git-cache-336fbd82\3
1d080cee1d8a4b74e03818aaee14da8062f0ea1:
        error: cannot spawn sh: No such file or directory
        npm ERR! git clone
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-d75da30c
        C:\Users\intel\AppData\Local\Temp\npm-2912-4dbb51ae\git-cache-336fbd82\3
1d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: unable to fork
        npm ERR! git clone
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-d75da30c
        C:\Users\intel\AppData\Local\Temp\npm-2912-4dbb51ae\git-cache-336fbd82\3
1d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-https-github-c
om-resin-io-bonjour-git-3f9321aa
        because of error: { Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get
        remote.origin.url' }
        npm ERR! git clone
        --template=C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\_templa
tes
        --mirror https://github.com/resin-io/bonjour.git
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-https-github-c
om-resin-io-bonjour-git-3f9321aa:
        Cloning into bare repository
        'C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-https-github-
com-resin-io-bonjour-git-3f9321aa'...
        npm ERR! git clone
        --template=C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\_templa
tes
        --mirror https://github.com/resin-io/bonjour.git
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-https-github-c
om-resin-io-bonjour-git-3f9321aa:
        fatal: Unable to find remote helper for 'https'
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef
        because of error: { Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get
        remote.origin.url' }
        npm ERR! git clone
        --template=C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\_templa
tes
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef:
        Cloning into bare repository
        'C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-re
sin-io-bonjour-git-41f67eef'...
        npm ERR! git clone
        --template=C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\_templa
tes
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef:
        error: cannot spawn ssh: No such file or directory
        npm ERR! git clone
        --template=C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\_templa
tes
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef:
        fatal: unable to fork
        npm ERR! Windows_NT 6.1.7600
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.11.0
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\_templa
tes
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-res
in-io-bonjour-git-41f67eef
        npm ERR! Cloning into bare repository
        'C:\Users\intel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-re
sin-io-bonjour-git-41f67eef'...
        npm ERR! error: cannot spawn ssh: No such file or directory
        npm ERR! fatal: unable to fork
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Program Files\nodejs\myfirstApp\npm-debug.log

**Comment by reverie-ss** [comment] 2017-06-28 07:24
**# I too had a similar kind of error :** 
`> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears to be a git command, but we were not
        npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe git-submodule is broken?
        npm ERR! git submodule -q update --init --recursive:
        npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears to be a git command, but we were not
        npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe git-submodule is broken?
        npm ERR! git submodule -q update --init --recursive:
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Host key verification failed.
        npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: fatal: Could not read from remote repository.
        npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Please make sure you have the correct access rights
        npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: and the repository exists.
        npm ERR! Windows_NT 10.0.14393
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:resin-io/bonjour.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef
        npm ERR! Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! Host key verification failed.
        npm ERR! fatal: Could not read from remote repository.
        npm ERR!
        npm ERR! Please make sure you have the correct access rights
        npm ERR! and the repository exists.
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\user\Desktop\Work\Invincix\XimpleThings\invincixWave2\npm-debug.log'

**Comment by ceofvo** [comment] 2017-06-28 10:14
I have same issue ( 32 bit Windows 7 using  Git for Windows )

> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        done.
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: This operation must be run in a work tree
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        warning: Clone succeeded, but checkout failed.
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        You can inspect what was checked out with 'git status'
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        and retry the checkout with 'git checkout -f HEAD'
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-7cf998ca\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        done.
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: This operation must be run in a work tree
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        warning: Clone succeeded, but checkout failed.
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        You can inspect what was checked out with 'git status'
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        and retry the checkout with 'git checkout -f HEAD'
        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git clone
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-resin-io-bonjour-git-3f9321aa
        C:\Users\user\AppData\Local\Temp\npm-656-4979c8d2\git-cache-95fbfecf\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef
        because of error: { Error: Command failed: git -c core.longpaths=true
        config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler
        (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose
        (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit
        (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get
        remote.origin.url' }
        npm ERR! git clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        Cloning into bare repository
        'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! git clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        Permission denied (publickey).
        npm ERR! git clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        fatal: Could not read from remote repository.
        npm ERR! git clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:

        npm ERR! git clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        Please make sure you have the correct access rights
        npm ERR! git clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        and the repository exists.
        npm ERR! Windows_NT 6.1.7601
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.11.0
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates
        --mirror git@github.com:resin-io/bonjour.git
        C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef
        npm ERR! Cloning into bare repository
        'C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! Permission denied (publickey).
        npm ERR! fatal: Could not read from remote repository.
        npm ERR!
        npm ERR! Please make sure you have the correct access rights
        npm ERR! and the repository exists.
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\user\myApp\npm-debug.log

**Comment by markaks** [comment] 2017-06-28 10:29
C:\ionic24>ionic start q tabs
✔ Creating directory .\q - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template tabs (https://github.com/ionic-team/ionic2-starter-tabs/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        git-upload-pack
        'C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c':
        git-upload-pack: command not found
        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: Could not read from remote repository.
        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Please make sure you have the correct access rights
        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        and the repository exists.
        npm ERR! git clone
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-d75da30c
        C:\Users\Acer\AppData\Local\Temp\npm-7692-f58d338e\git-cache-0b37ec31\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        npm ERR! git fetch -a origin (https://github.com/resin-io/bonjour.git) fatal: Unable to find remote helper for
        'https'
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef because of
        error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Cloning into
        bare repository
        'C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! git clone --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Host key
        verification failed.
        npm ERR! git clone --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: fatal: Could
        not read from remote repository.
        npm ERR! git clone --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef:
        npm ERR! git clone --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: Please make
        sure you have the correct access rights
        npm ERR! git clone --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef: and the
        repository exists.
        npm ERR! Windows_NT 10.0.14393
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.11.0
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef
        npm ERR! Cloning into bare repository
        'C:\Users\Acer\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-41f67eef'...
        npm ERR! Host key verification failed.
        npm ERR! fatal: Could not read from remote repository.
        npm ERR!
        npm ERR! Please make sure you have the correct access rights
        npm ERR! and the repository exists.
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\ionic24\q\npm-debug.log

**Comment by markaks** [comment] 2017-06-28 12:25
use "ionic start myapp tabs" inside uuid:
like:   C:\io24\node_modules\uuid>ionic start myapp tabs
it's work for me!!!!

**Comment by AkshayMhatre1** [comment] 2017-06-28 13:07
try  **ionic start --type=ionic1**

**Comment by ceofvo** [comment] 2017-06-28 16:01
okay, but is there any solution for the latest version of ionic

**Comment by kenany** [comment] 2017-06-28 21:48
Looks like a duplicate of ~~https://github.com/npm/npm/issues/17484~~ https://github.com/npm/npm/issues/17460.

EDIT: corrected link

**Closed as completed by kenany** 2017-06-28 21:48 UTC
Labels: support, git

**Comment by ceofvo** [comment] 2017-06-29 05:03
@KenanY this tread is #17484. Can you assist with a solution?

**Comment by kenany** [comment] 2017-06-29 15:12
@ceofvo My bad, I meant https://github.com/npm/npm/issues/17460 :) I'll edit my comment.
