### ISSUE TITLE
Can not install third party module

### ISSUE THREAD

**Issue by nirmalgoswami** [npm/npm#13363] opened 2016-07-13 04:38 UTC
i am trying to install ionic@beta in my windows 10 pc but i am not able to install.please find attached log file code

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic@2.0.0-beta.25' ]
2 info using npm@3.10.5
3 info using node@v6.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic@2.0.0-beta.25
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ionic',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ionic',
12 silly mapToRegistry   name: 'ionic',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ionic
14 verbose request uri https://registry.npmjs.org/ionic
15 verbose request no auth needed
16 info attempt registry request try #1 at 9:41:12 AM
17 verbose request id 21ac28adf639242a
18 verbose etag "6CYQ3B90FUT1I7UAKADMO3A6V"
19 http request GET https://registry.npmjs.org/ionic
20 http 304 https://registry.npmjs.org/ionic
21 verbose headers { date: 'Wed, 13 Jul 2016 04:11:16 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"6CYQ3B90FUT1I7UAKADMO3A6V"',
21 verbose headers   age: '51',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lcy1129-LCY',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '2',
21 verbose headers   'x-timer': 'S1468383076.479349,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Wed, 13 Jul 2016 04:11:16 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"6CYQ3B90FUT1I7UAKADMO3A6V"',
22 silly get     age: '51',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lcy1129-LCY',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '2',
22 silly get     'x-timer': 'S1468383076.479349,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/ionic from cache
24 verbose get saving ionic to C:\Users\username\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
25 verbose correctMkdir C:\Users\username\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule ionic@2.0.0-beta.25 checking installable status
39 silly cache add args [ 'ionic@2.0.0-beta.25', null ]
40 verbose cache add spec ionic@2.0.0-beta.25
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'ionic@2.0.0-beta.25',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'ionic',
41 silly cache add   name: 'ionic',
41 silly cache add   rawSpec: '2.0.0-beta.25',
41 silly cache add   spec: '2.0.0-beta.25',
41 silly cache add   type: 'version' }
42 silly addNamed ionic@2.0.0-beta.25
43 verbose addNamed "2.0.0-beta.25" is a plain semver version for ionic
44 silly mapToRegistry name ionic
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry data Result {
47 silly mapToRegistry   raw: 'ionic',
47 silly mapToRegistry   scope: null,
47 silly mapToRegistry   escapedName: 'ionic',
47 silly mapToRegistry   name: 'ionic',
47 silly mapToRegistry   rawSpec: '',
47 silly mapToRegistry   spec: 'latest',
47 silly mapToRegistry   type: 'tag' }
48 silly mapToRegistry uri https://registry.npmjs.org/ionic
49 verbose addNameVersion registry:https://registry.npmjs.org/ionic not in flight; fetching
50 verbose get https://registry.npmjs.org/ionic not expired, no request
51 silly mapToRegistry name ionic
52 silly mapToRegistry using default registry
53 silly mapToRegistry registry https://registry.npmjs.org/
54 silly mapToRegistry data Result {
54 silly mapToRegistry   raw: 'ionic',
54 silly mapToRegistry   scope: null,
54 silly mapToRegistry   escapedName: 'ionic',
54 silly mapToRegistry   name: 'ionic',
54 silly mapToRegistry   rawSpec: '',
54 silly mapToRegistry   spec: 'latest',
54 silly mapToRegistry   type: 'tag' }
55 silly mapToRegistry uri https://registry.npmjs.org/ionic
56 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz not in flight; adding
57 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz',
57 verbose addRemoteTarball   '0184b9f610b8c52e72bfa287eebcdde08a1443be' ]
58 info retry fetch attempt 1 at 9:41:13 AM
59 info attempt registry request try #1 at 9:41:13 AM
60 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
61 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
62 info retry will retry, error on last attempt: Error: read ECONNRESET
63 info retry will retry, error on last attempt: Error: read ECONNRESET
64 silly fetchAndShaCheck shasum 0184b9f610b8c52e72bfa287eebcdde08a1443be
65 silly rollbackFailedOptional Starting
66 silly rollbackFailedOptional Finishing
67 silly runTopLevelLifecycles Starting
68 silly runTopLevelLifecycles Finishing
69 silly install printInstalled
70 verbose stack Error: shasum check failed for C:\Users\username\AppData\Local\Temp\npm-2732-bd61fcfc\registry.npmjs.org\ionic\-\ionic-2.0.0-beta.25.tgz
70 verbose stack Expected: 0184b9f610b8c52e72bfa287eebcdde08a1443be
70 verbose stack Actual:   8e69665108bfb4f095575931eee047c68c4f8471
70 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
70 verbose stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:25:8
70 verbose stack     at ReadStream.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:72:7)
70 verbose stack     at emitNone (events.js:91:20)
70 verbose stack     at ReadStream.emit (events.js:185:7)
70 verbose stack     at endReadableNT (_stream_readable.js:973:12)
70 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
70 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
71 verbose cwd C:\Users\username
72 error Windows_NT 10.0.10240
73 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic@2.0.0-beta.25"
74 error node v6.3.0
75 error npm  v3.10.5
76 error shasum check failed for C:\Users\username\AppData\Local\Temp\npm-2732-bd61fcfc\registry.npmjs.org\ionic\-\ionic-2.0.0-beta.25.tgz
76 error Expected: 0184b9f610b8c52e72bfa287eebcdde08a1443be
76 error Actual:   8e69665108bfb4f095575931eee047c68c4f8471
76 error From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.25.tgz
77 error If you need help, you may report this error at:
77 error     <https://github.com/npm/npm/issues>
78 verbose exit [ 1, true ]

```

**Comment by zkat** [comment] 2016-12-09 00:39
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:39 UTC
