### ISSUE TITLE
Hi, I am very new to node/npm, trying to install nightwatch and I am getting the error as shashum check failed. Please help.

### ISSUE THREAD

**Issue by sharath506222** [npm/npm#9416] opened 2015-08-26 13:36 UTC
```
C:\Users\506222>npm install -g nightwatch
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nightwatch"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\506222\AppData\Local\Temp\npm-5384-6e536883\registry.npmjs.org\nightwatch\-\nightwatch-0.7.11.tgz
npm ERR! Expected: d058f9d5bcfe655e9047c7be9a2fcb78d8cda4a3
npm ERR! Actual:   58117271a1a0d05f0b63192df523c8af2fe190f9
npm ERR! From:     http://registry.npmjs.org/nightwatch/-/nightwatch-0.7.11.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\506222\npm-debug.log
```

**Comment by KenanY** [comment] 2015-08-26 14:37
@sharath506222 Could you try running `npm cache clear` and seeing if that solves your issue?

**Comment by sharath506222** [comment] 2015-08-27 07:00
@KenanY Tried running npm cache clear , but still facing the same issue..

**Comment by gyzerok** [comment] 2015-08-31 10:59
Same issue OS X 10.10.5

**Comment by zkat** [comment] 2016-12-09 00:54
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:54 UTC
Labels: proxy, support, windows
