### ISSUE TITLE
npm errors when trying to Install Appium

### ISSUE THREAD

**Issue by elyanivson** [npm/npm#15267] opened 2016-12-20 12:33 UTC
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.

#### What's going wrong?
Trying to Instal Appium via npm but having some errors.
### supporting information:
   - Geographic location where npm was run:

Here's the errors log I'm getting when trying to install Appium:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\x3686167>npm install appium -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\x3686167\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "appium" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\x3686167\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "appium" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\x3686167\npm-debug.log

Thanks

**Comment by legodude17** [comment] 2016-12-20 21:10
Duplicate of #15096.

**Comment by Manikanta29** [comment] 2017-01-20 13:20
if you have npm 4.0.3, it's not possible to get the latest appium.  

Get the latest npm with command : npm install -g npm@latest
You will get npm:4.1.1

And run the command: npm install -g appium 
You will get appium:1.6.3

**Comment by KenanY** [comment] 2017-02-03 13:06
Closing as a duplicate.

**Closed by KenanY** 2017-02-03 13:06 UTC
