### ISSUE TITLE
npm Windows 7 x64 error

### ISSUE THREAD

**Issue by huangmarc** [npm/npm#10951] opened 2015-12-24 07:39 UTC
I would like to install Web Starter Kit of Google initiative.
https://github.com/google/web-starter-kit
After git the source and excuse npm install command with administrator permission command line windows, it response some error messages about npm.
I can't seem to find much support for this error

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! path C:\Users\marc522\AppData\Roaming\npm-cache\loud-rejection\1.2.0\pa
ckage\package.json.20a45f3418da440f51a07fff06cd5896
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\marc522\AppData
\Roaming\npm-cache\loud-rejection\1.2.0\package\package.json.20a45f3418da440f51a
07fff06cd5896' -> 'C:\Users\marc522\AppData\Roaming\npm-cache\loud-rejection\1.2
.0\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\marc522\App
Data\Roaming\npm-cache\loud-rejection\1.2.0\package\package.json.20a45f3418da440
f51a07fff06cd5896' -> 'C:\Users\marc522\AppData\Roaming\npm-cache\loud-rejection
\1.2.0\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\marc522\\AppData\\Roaming\\npm-cache\\loud-rejectio
n\\1.2.0\\package\\package.json.20a45f3418da440f51a07fff06cd5896',
npm ERR!   dest: 'C:\\Users\\marc522\\AppData\\Roaming\\npm-cache\\loud-rejectio
n\\1.2.0\\package\\package.json',
npm ERR!   parent: 'meow' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     E:\web-starter-kit\npm-debug.log
```

[npm-debug.zip](https://github.com/npm/npm/files/71530/npm-debug.zip)
![npm_error](https://cloud.githubusercontent.com/assets/5966558/11991361/8ca50682-aa54-11e5-883a-1ea034cca26e.jpg)

**Comment by sam-github** [comment] 2016-07-15 20:24
possible duplicate of https://github.com/npm/npm/issues/12059?

**Closed** 2017-06-16 23:41 UTC
Labels: bot-closed, support, windows
