### ISSUE TITLE
Problem Installing Cordova using npm on Windows

### ISSUE THREAD

**Issue by elmarssi2015** [npm/npm#10795] opened 2015-12-11 21:48 UTC
Hey everybody

i got a problem while installing CORDOVA can anyone explain to me what's the cause of this problem?

I'm using NPM v3.5.1 and NodeJS v5.2.0

```
C:\Users\Crazy>npm install -g cordova
C:\vendor\js
└── (empty)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\vendor\\js\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.1
npm ERR! path C:\vendor\js\node_modules\.staging\has-unicode-561d5218cc54ead8cd3becf382923f01
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\vendor\js\node_modules\.staging\has-unicode-561d5218cc54ead8cd3becf382923f01' -> 'C:\vendor\js\node_modules\cordova\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\has-unicode'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\vendor\js\node_modules\.staging\has-unicode-561d5218cc54ead8cd3becf382923f01' -> 'C:\vendor\js\node_modules\cordova\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\has-unicode'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Crazy\npm-debug.log
npm ERR! code 1
```

**Comment by elmarssi2015** [comment] 2015-12-12 18:28
Can anyone help me

**Comment by othiym23** [comment] 2015-12-16 22:36
You might want to try upgrading to `npm@3.5.2`, which I believe [includes a fix](https://github.com/npm/npm/blob/master/CHANGELOG.md#enoent-more-like-enomorebugs) for this exact problem.

**Comment by othiym23** [comment] 2016-02-16 17:01
Closing as duplicate of #11265. Please see that issue if you want to help the CLI team identify and fix the underlying bug, which is probably a race condition. Thanks for your time!

**Closed by othiym23** 2016-02-16 17:01 UTC
Labels: support
