### ISSUE TITLE
Use `engines` (or other) to designate ES6 codebases

### ISSUE THREAD

**Issue by rektide** [npm/npm#7119] opened 2015-01-12 22:03 UTC
In iojs/io.js#90 , talking about enabling `harmony` by default, I mentioned that `package.json` should include information on what level of ecmascript is required. Perhaps this information might be held in the `engines` tag or perhaps a new field might be added to package.json?

There's a lot of "will this package work in my environment" questions out there that npm will hopefully come to answer, and I hope npm accepts that challenge; both here, with "what version of JavaScript does this package need", and on-goingly & in regards to other compatibility questions. Thanks all.

**Comment by domenic** [comment] 2015-01-12 22:07
Spec versions are a fiction and don't correspond to anything real in implementations. -1

**Comment by othiym23** [comment] 2015-01-17 02:16
I have some thoughts on how to implement a helper package that will use `process.versions.v8` to determine at install time whether a given package needs to be preprocessed with an ES6 transpiler or can be run as-is; when I have some time I may throw together a strawman implementation everyone can bikeshed on. At some point it may make sense to move some kind of functionality along those lines into npm itself, but I do think that while we're just entering the transitional period from ES5 to ES6, and also waiting to see how long the split between Node.js and io.js lasts, it's a bit premature.

I'm closing this as a duplicate of iojs/io.js#269, which is an issue that @iarna opened explicitly for this purpose, as I don't think this is a problem that is npm's to solve alone.

**Closed by othiym23** 2015-01-17 02:16 UTC
Labels: feature-request
