### ISSUE TITLE
TACO 0204: Error installing taco-remote-multiplexer via npm. Exit code:1

### ISSUE THREAD

**Issue by raysefo** [npm/npm#9828] opened 2015-10-02 18:14 UTC
Hi,

I am using VS 2015 and when I try to remotebuild IOS, I am getting this error. Would you please help me?

Thanks in advance and Best Regards.

Edit 1: Inner error says, ENOENT: no such file or directory...

**Comment by KenanY** [comment] 2015-10-02 18:28
@raysefo `node --version`? `npm --version`? `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by raysefo** [comment] 2015-10-02 18:46
Kenan selam,

node: 4.1.1
npm: 3.3.5
npm-debug.log'u nasıl alacağımı bilemedim?!

**Comment by KenanY** [comment] 2015-10-02 19:00
@raysefo Sorry, I don't speak Turkish :) my name can be misleading like that though. Unfortunately it is difficult to say what is going on here with just one line of the error log (especially considering how `ENOENT` is a pretty generic error code).

**Comment by raysefo** [comment] 2015-10-02 19:06
Hi Kenan,

Here is the error log:https://gist.github.com/raysefo/4d74b35e37b6229e008a

In case I couldn't manage to create it.

Cenks-Mac:~ kizildagcenk$ remotebuild test
Remote build server listening on [https] port 3000
Please view/edit server configuration at /Users/kizildagcenk/.taco_home/RemoteBuild.config. You many need to run 'remotebuild saveconfig' to generate it. You will have to restart the server if you update the server configurations.
New build request submitted:
/build/tasks/?vcordova=4.3.0&vcli=1.1.0&cfg=debug&command=build&options=--emulator
{ host: 'cenks-mac.local:3000',
  connection: 'close',
  'transfer-encoding': 'chunked' }
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "taco-remote-multiplexer" "--loglevel" "warn"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/npm-debug.log
For more information please refer to http://aka.ms/TacoCliKnownIssues
TACO0204: Error installing taco-remote-multiplexer via npm. Exit Code: 1. See output for details.

POST /cordova/build/tasks/?vcordova=4.3.0&vcli=1.1.0&cfg=debug&command=build&options=--emulator 500 5163.982 ms - 471
Error: taco-remote test failed.
[Error: TACO0208: Error attempting to recover from failed installation at /Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer.
Inner Error:
ENOENT: no such file or directory, rename '/Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer_backup' -> '/Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer']
/usr/local/lib/node_modules/remotebuild/node_modules/q/q.js:126
                    throw e;
                    ^

Error: TACO0208: Error attempting to recover from failed installation at /Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer.
Inner Error:
ENOENT: no such file or directory, rename '/Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer_backup' -> '/Users/kizildagcenk/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer'
    at Request._callback (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/lib/selftest.js:71:37)
    at Request.self.callback (/usr/local/lib/node_modules/remotebuild/node_modules/request/request.js:121:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/remotebuild/node_modules/request/request.js:985:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/remotebuild/node_modules/request/request.js:936:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
Cenks-Mac:~ kizildagcenk$ node --version
v4.1.1
Cenks-Mac:~ kizildagcenk$ npm --version
3.3.5

**Comment by KenanY** [comment] 2015-10-02 19:08
@raysefo Thanks! This is a known issue :) https://github.com/npm/npm/issues/9766

**Comment by raysefo** [comment] 2015-10-02 19:48
Hello Kenan,

I downgraded to 3.4.4 and clean cache. Now I can build with 2 warnings but couldn't deploy to remote iPhone!

How can I fix this?

Cenks-Mac:~ kizildagcenk$ npm cache clean
Cenks-Mac:~ kizildagcenk$ remotebuild
Remote build server listening on [https] port 3000
Please view/edit server configuration at /Users/kizildagcenk/.taco_home/RemoteBuild.config. You many need to run 'remotebuild saveconfig' to generate it. You will have to restart the server if you update the server configurations.
New build request submitted:
/build/tasks?command=build&vcordova=4.3.0&cfg=debug&options=--device&loglevel=warn
{ 'accept-language': 'en-US',
  host: 'cenks-mac.local:3000',
  connection: 'close',
  'transfer-encoding': 'chunked' }
Build will be executed under: /Users/kizildagcenk/.taco_home/remote-builds/taco-remote/builds/2238
Saving build request payload to : /Users/kizildagcenk/.taco_home/remote-builds/taco-remote/builds/2238
Saved uploaded build to /Users/kizildagcenk/.taco_home/remote-builds/taco-remote/builds/2238/upload_2238.tgz
POST /cordova/build/tasks?command=build&vcordova=4.3.0&cfg=debug&options=--device&loglevel=warn 202 3433.411 ms - 696
GET /cordova/build/tasks/2238 200 3.587 ms - 696
Extracted app contents from uploaded build request to /Users/kizildagcenk/.taco_home/remote-builds/taco-remote/builds/2238/cordovaApp. Requesting build.
Taking 2238 as current build
GET /cordova/build/tasks/2238 200 24.743 ms - 79891
GET /cordova/build/tasks/2238 200 7.701 ms - 79891
GET /cordova/build/tasks/2238 200 10.259 ms - 79891
Done with current build. Checking for next build in queue.
GET /cordova/build/tasks/2238 200 10.185 ms - 79878
GET /cordova/build/tasks/2238/log 200 104.821 ms - -
GET /cordova/files/2238/cordovaApp/plugins/ios.json 200 39.025 ms - 2275
GET /cordova/build/2238/download 200 62.218 ms - -
GET /cordova/build/2238/deploy 404 178.846 ms - 63

On VS 2015 warnings says: resource rules has been deprecated in MAC OS X > 10.10
A launch storyboard or xib must be provided unless the app requires full screen.

**Comment by raysefo** [comment] 2015-10-03 07:39
@KenanY any ideas why?

**Comment by KenanY** [comment] 2015-10-03 14:32
@raysefo Sorry, doesn't look like a `npm` issue anymore. I have never used TACO before. Maybe you can ask on [StackOverflow](https://stackoverflow.com/questions/tagged/taco)?

**Comment by othiym23** [comment] 2015-10-05 19:57
Closing as a duplicate of #9766, and also because the remaining issues are, as @KenanY said, not due to npm issues (and I haven't used TACO either, so I'm not of much help regardless). Good luck!

**Closed by othiym23** 2015-10-05 19:57 UTC

**Comment by AntosTech** [comment] 2015-11-04 18:32
Can someone help me please. I am trying to setup the remote build on my mac, but I am getting an error. It worked fine on my iMAC, but on my macbook it is not working. I do not understand the error:

Akisha-Anthonys-MacBook-Pro:~ akishaanthony$ remotebuild test --server http://localhost:3000
Remote build server listening on [https] port 3000
Please view/edit server configuration at /Users/akishaanthony/.taco_home/RemoteBuild.config. You many need to run 'remotebuild saveconfig' to generate it. You will have to restart the server if you update the server configurations.
Error: taco-remote test failed.
connect EHOSTUNREACH

/usr/local/lib/node_modules/remotebuild/node_modules/q/q.js:126
                    throw e;
                          ^
Error: connect EHOSTUNREACH
    at errnoException (net.js:905:11)
    at connect (net.js:767:19)
    at net.js:846:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)

**Comment by KenanY** [comment] 2015-11-04 19:03
Hi @AntosTech :)

Sorry but this is the issue tracker for `npm`, the package manager, but your error is not coming from `npm` (see the stack trace). I believe you will have a greater chance at finding the best solution to your issue if you ask the developers of the software you are having trouble with.

**Comment by AntosTech** [comment] 2015-11-05 07:31
Thank you. Sorry about that.
