### ISSUE TITLE
Problem with npm install --save psi

### ISSUE THREAD

**Issue by AramilRey** [npm/npm#11071] opened 2016-01-07 17:15 UTC
The console throws this error:

Cannot read property 'target' of null

npm-debug-log:
(It's long, so I'm copying only the piece where I see the error)

```
11941 silly generateActionsToTake Starting
11942 silly install generateActionsToTake
11943 verbose stack TypeError: Cannot read property 'target' of null
11943 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
11943 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
11943 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
11943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
11943 verbose stack     at Object.Installer.computeLinked (/usr/local/lib/node_modules/npm/lib/install.js:411:41)
11943 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
11943 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
11943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
11943 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/diff-trees.js:50:3)
11943 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
11944 verbose cwd /home/arey/source/perfschool-playground/using_the_pagespeed_api
11945 error Linux 3.16.0-4-amd64
11946 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "psi"
11947 error node v5.4.0
11948 error npm  v3.5.2
11949 error Cannot read property 'target' of null
11950 error If you need help, you may report this error at:
11950 error     <https://github.com/npm/npm/issues>
11951 verbose exit [ 1, true ]
```

**Comment by mikesherov** [comment] 2016-01-08 00:13
Thanks for contributing! This seems like it's a duplicate of https://github.com/npm/npm/issues/10686 Is it?

**Comment by iarna** [comment] 2016-01-08 01:44
Yeah, I concur, this is a duplicate, albeit with a much less involved use case. Similarly I can't reproduce it.

I'm going to close this in favor of #10686 so we can have discussion all in one place.

**Closed by iarna** 2016-01-08 01:44 UTC
Labels: big-bug, bug
