### ISSUE TITLE
Ionic failed to install

### ISSUE THREAD

**Issue by petrelli22** [npm/npm#14363] opened 2016-10-21 10:24 UTC
I tried to install ionic on a new macOS Sierra laptop
IT failed to install and here's the error I got

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for /var/folders/vf/8hj4q2bn7jg46r4nq0h2lw600000gn/T/npm-647-c283cfe6/registry.npmjs.org/ionic/-/ionic-2.1.1.tgz
npm ERR! Expected: 7345b56915da2100a0efcd5257a4626848c4da80
npm ERR! Actual:   c13dfc7f09aeb49a788d5d33ce47db2b40b85c3c
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

[npm-debug.log.zip](https://github.com/npm/npm/files/544096/npm-debug.log.zip)

**Comment by hsxfjames** [comment] 2016-10-23 03:23
I got a similar error. Since here is already an issue, I comment here and will not open a new issue.

> npm ERR! Linux 4.4.0-38-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> 
> npm ERR! shasum check failed for /tmp/npm-26725-bb67faad/registry.npmjs.org/ionic/-/ionic-2.1.1.tgz
> npm ERR! Expected: 7345b56915da2100a0efcd5257a4626848c4da80
> npm ERR! Actual:   c429173b9f7af91439657dd755f5afe78f4835c4
> npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.1.tgz

I've zipped the log file and uploaded it.
[npm-debug.log.zip](https://github.com/npm/npm/files/546154/npm-debug.log.zip)

**Comment by zkat** [comment] 2016-12-09 00:35
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:35 UTC
Labels: bug, cache, support
