### ISSUE TITLE
`npm unlink` in npm 5 removes all dependencies from target folder.

### ISSUE THREAD

**Issue by n3dst4** [npm/npm#16922] opened 2017-06-02 15:24 UTC
#### I'm opening this issue because:

  - :ballot_box_with_check: npm is doing something I don't understand.
  - :ballot_box_with_check: npm is producing an incorrect install.

#### What's going wrong?

When I `npm link <thing>` and then subsequently `npm unlink <thing>`, the `node_modules` in `<thing>` is deleted and npm chirpily reports, `removed 377 packages in 8.616s`

#### How can the CLI team reproduce the problem?

In a shell:

```
mkdir foo
cd foo
npm init -y
npm i left-pad
cd ..
mkdir bar
cd bar
npm init -y
npm link ../foo
ls ../foo
# observe that ../foo contains a node_modules
npm unlink ../foo
ls ../foo
```

EXPECTED: `foo` would still have its dependencies

ACTUAL: `foo` has lost it's `node_modules` folder

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows :(

**Comment by pix2D** [comment] 2017-06-04 05:21
This also happens when running `npm install package` (where package is any package) while having an active link, this did not happen pre-v5. The package gets installed but `node_modules` in the linked package disappears.

`added 1 package and removed 1133 packages in 13.503s`

**Comment by zkat** [comment] 2017-06-05 15:56
Closing as dupe of https://github.com/npm/npm/issues/16788

**Closed as completed by zkat** 2017-06-05 15:56 UTC
Labels: npm5

**Comment by n3dst4** [comment] 2017-06-05 16:27
Thank you, @zkat.

**Comment by skygragon** [comment] 2017-06-06 05:37
is it the same reason as #16988? The node_modules are cleared after install globally.
