### ISSUE TITLE
npm@5: Unable to uninstall global package after upgrading to npm 5

### ISSUE THREAD

**Issue by danthegoodman** [npm/npm#16738] opened 2017-05-26 16:08 UTC
#### I'm opening this issue because:

  - [X] npm is crashing.

#### What's going wrong?

```
> npm -v
4.6.1
> npm i -g npm@5
> npm rm -g serve
Unhandled rejection Error: Argument #2: Expected string but got null5
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    ...
> npm i -g serve
updated 178 packages in 20.377s
> npm rm -g serve
removed 178 packages in 2.835s
```

#### How can the CLI team reproduce the problem?

1. Start off w/ npm@4 installed
2. Globally install a package (any will do, i tested with many. `serve` is what I reported with)
3. Upgrade to npm@5
4. Try to uninstall package.

https://gist.github.com/danthegoodman/c4f1604ae6bfc98c9a7b84fa1e5c6384

### supporting information:

 - `npm -v` prints: `5.0.0`
 - `node -v` prints: `6.9.5`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `macOS`

**Comment by zkat** [comment] 2017-05-26 16:34
Thanks for the report! I'll take a look in a bit.

**Comment by lednhatkhanh** [comment] 2017-05-29 04:05
Report the same issue when trying to uninstall yarn.

**Comment by jharris4** [comment] 2017-05-31 16:26
I'm hitting the same issue with npm 5 and node 8. Trying to uninstall `npm-check-updates`

```
npm uninstall -g npm-check-updates
```
```
Unhandled rejection Error: Argument #2: Expected string but got null0
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!
```

**Comment by offwork** [comment] 2017-06-03 07:22
I also had the same problems after npm upgrading to 5:


`npm uninstall -g loopback-sdk-angular-cli
Unhandled rejection Error: Argument #2: Expected string but got null0
    at addDependency (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/keremozdemir/.npm-packages/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/keremozdemir/.npm-packages/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/keremozdemir/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/keremozdemir/.npm/_logs/2017-06-03T07_08_47_780Z-debug.log`

**Comment by jnv** [comment] 2017-06-04 12:39
Same issue on Ubuntu 17.04, Node v7.10.0

**Comment by NoahDragon** [comment] 2017-06-04 22:26
Got same error when uninstall global package. https://github.com/npm/npm/issues/16971

**Comment by btargac** [comment] 2017-06-05 08:19
the same issue on mac osx when `npm uninstall -g reaction-cli`

**Comment by GabeDuarteM** [comment] 2017-06-05 13:51
Can confirm this happens on W10 npm@5.0.2 node@8.0.0.

It happens when trying to unninstall any app from the globals packages

**EDIT:** 

"Solved" this problem with that: Found out that if you reinstall the packages, the error doesn't show for that package.

For example: if you try to uninstall eslint, it gives you that error. If you reinstall the package and then uninstall it again, now it removes the package successfully...

**So, to solve**:

```
npm ls -g --depth=0 // To get all the packages installed globally

npm i -g "package" // For each one of the packages listed above, its best to reinstall, to solve the problem to every one of them. 

npm uninstall -g "package" // Now you can uninstall the one you dont want anymore
```

**Comment by offwork** [comment] 2017-06-05 17:27
I solved the problem like this:

1. Uninstall node and npm from your computer.
2. Enter the command 'brew install node' at the terminal.
3. Follow the directions in [npm](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by zkat** [comment] 2017-06-06 08:01
### A note on repro

This is trivially reproducible by installing a package globally with `npm@4` and removing it with `npm@5`. I'm looking into it.

**Comment by btargac** [comment] 2017-06-06 08:17
Easiest solution that worked for me is re-installing the package globally then try uninstalling it with npm@5.0.2 

`npm i -g PACKAGE_NAME`
`npm uninstall -g PACKAGE_NAME`

**Comment by edalee** [comment] 2017-06-08 07:20
@btargac Thanks, this resolved the issue for me on Ubuntu 16.04LTS

**Comment by xtreemrage** [comment] 2017-06-14 12:24
@btargac 
This also works for windows 10 pro. 
`npm -v 5.0.3`
`node -v 8.1.1`

**Comment by rex** [comment] 2017-06-25 05:44
@btargac Confirmed, your fix works for macOS Sierra 10.12.5. Thank you!
`npm -v 5.0.3`
`node -v v8.1.2`

**Comment by Iwerzhon** [comment] 2017-06-27 10:22
`npm -v 5.0.3`
`node -v 6.10.0`

I installed all my global packages before uninstalling them, but then got an error for some of them (`webpack` and `webpack-dev-server` in particular).
```
npm ls -g --depth=0
+-- cordova@6.5.0
+-- ionic@2.2.1
+-- npm@5.0.3
+--  error: ENOENT: no such file or directory, open 'PATH\TO\AppData\Roaming\npm\node_modules\webpack\package.json
`--  error: ENOENT: no such file or directory, open 'PATH\TO\AppData\Roaming\npm\node_modules\webpack-dev-server\package.json

npm ERR! error in PATH\TO\AppData\Roaming\npm\node_modules\webpack: ENOENT: no such file or directory, open 'PATH\TO\AppData\Roaming\npm\node_modules\webpack\package.json'
npm ERR! missing: nan@^2.3.0, required by fsevents@1.1.2
npm ERR! missing: node-pre-gyp@^0.6.36, required by fsevents@1.1.2
npm ERR! error in PATH\TO\AppData\Roaming\npm\node_modules\webpack-dev-server: ENOENT: no such file or directory, open 'PATH\TO\AppData\Roaming\npm\node_modules\webpack-dev-server\package.json'
npm ERR! missing: nan@^2.3.0, required by fsevents@1.1.2
npm ERR! missing: node-pre-gyp@^0.6.36, required by fsevents@1.1.2
```
Considering that the other global packages were correctly uninstalled, can we consider that it is unrelated to this issue ?

**Comment by kaplan81** [comment] 2017-06-27 13:25
Same happened to me:
`MBP-de-Andres:~ ANDRESITO$ npm ls -g --depth=0
/usr/local/lib
├── @angular/cli@1.0.0
├── angular-cli@1.0.0-beta.19-3
├── bower@1.5.3
├── brew@0.0.8
├── grunt-cli@0.1.13
├── gulp@3.9.0
├── mongo-edu@0.2.19
├── mongodb@2.0.42
├── nativescript@2.1.0
├── npm@5.0.3
├── rimraf@2.5.4
└── source-map-explorer@1.3.2

npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/async-some: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/async-some/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/normalize-git-url: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/normalize-git-url/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/realize-package-specifier: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/package.json'
npm ERR! invalid: validate-npm-package-license@1.0.0-prerelease-2 /usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/validate-npm-package-license
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/package.json'
npm ERR! invalid: glob /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/path-array/package.json'
npm ERR! invalid: tar@1.0.3 /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/minimatch/node_modules/sigmund: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/minimatch/node_modules/sigmund/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/package.json'
npm ERR! invalid: has-unicode@1.0.0 /usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/has-unicode
npm ERR! missing: graceful-fs@^3.0.4, required by readdir-scoped-modules@1.0.1
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/isarray: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/isarray/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/node-uuid/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async/package.json'
npm ERR! invalid: combined-stream@0.0.7 /usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/chalk: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/chalk/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/package.json'
npm ERR! error in /usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend/package.json'
npm ERR! invalid: glob@4.5.3 /usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob`

**Comment by kaplan81** [comment] 2017-06-27 14:45
I solved it in a very rude way, starting fresh.

I followed this guy to completely manually uninstall node and npm:
https://gist.github.com/TonyMtz/d75101d9bdf764c890ef

Then installed node v8.1.2 and npm 5.0.3 downloading the package for MacOSX from the Node site.

Everything seems to work like a charm now.

**Comment by jeanlucaslima** [comment] 2017-06-27 20:14
Same problem here, on Windows 10 and npm `5.0.4`. I cannot uninstall ember-cli:

```
> npm uninstall -g ember-cli
Unhandled rejection Error: Argument #2: Expected string but got null align-text@^0.1.3 fetched in 150ms

(...)

npm ERR! cb() never called!
```

Also, I cannot install some ember addons because npm fails, e.g., `ember-bulma`. Sometimes deleting `node_modules` and installing all again works, but I gave up on that after the 4th time doing it just today.

**Comment by Teja-Konjeti** [comment] 2017-07-02 18:13
Same Issue updated from Node6, npm 3..

**Comment by zkat** [comment] 2017-07-04 22:03
This is fixed in the canary and will be included in tomorrow's release.

**Closed by zkat** 2017-07-04 22:03 UTC
Labels: npm5

**Comment by RazvanSebastian** [comment] 2018-04-12 17:19
Step1: Reinstall global packages
Find npm folders on your HD
`npm -ls global`
Delete manually npm folders
Install globally the latest version
`npm install --save @angular/cli@latest`

Step2: Reinstall node_modules locally (in your app)
Delete manually node_modules folder
Reinstall local packages
`npm install --save @angular/cli@latest`

Try ng -v in your app folder to check if everything installed; type ng -build and good luck to coding!
