### ISSUE TITLE
npm http fetch never ends

### ISSUE THREAD

**Issue by KenetJervet** [npm/npm#11144] opened 2016-01-14 07:35 UTC
I admit that our network environment sucks (Mainland China).

But wouldn't it be better to timeout and retry/fail a hung connection instead of getting stuck there forever?

Without the `-verbose` option it looks like it's working hard on something but in fact it's only wasting time.

**Comment by othiym23** [comment] 2016-01-18 05:52
npm does in fact retry failed connections, and there is a timeout on requests, but it is super-long, and there are some circumstances under which `request` seems to hang. The CLI team is going to tackle this at some point this year by doing a pretty thorough rewrite of npm's networking code, but until then, patience is advised, and perhaps the use of a VPN if you have access to one.

Closing as duplicate of #7862, which is sort of a master tracking issue for many of the CLI's networking issues.

**Closed by othiym23** 2016-01-18 05:52 UTC
Labels: proxy, support
