### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by dogukandemir** [npm/npm#9580] opened 2015-09-14 12:12 UTC
I'm trying to install ionic behind firewall but I've got this error.

.npmrc file:

``` ini
registry=https://registry.npmjs.org/
proxy=http://{domain}%5C{username}:{mypassword}@{proxyip}:{port}/
https-proxy=http://{domain}%5C{username}:{mypassword}@{proxyip}:{port}/
```

npm-debug.log file:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose install initial load of C:\Users\\{username}\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\\{username}\AppData\Roaming\npm\package.json
6 silly cache add args [ 'ionic', null ]
7 verbose cache add spec ionic
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'ionic',
8 silly cache add   scope: null,
8 silly cache add   name: 'ionic',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed ionic@*
10 verbose addNamed "*" is a valid semver range for ionic
11 silly addNameRange { name: 'ionic', range: '*', hasData: false }
12 silly mapToRegistry name ionic
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ionic
16 verbose addNameRange registry:https://registry.npmjs.org/ionic not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ionic
18 verbose request no auth needed
19 info attempt registry request try #1 at 15:00:47
20 verbose request id c660984a1ef9cecb
21 http request GET https://registry.npmjs.org/ionic
22 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
23 info attempt registry request try #2 at 15:00:57
24 http request GET https://registry.npmjs.org/ionic
25 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
26 info attempt registry request try #3 at 15:01:58
27 http request GET https://registry.npmjs.org/ionic
28 verbose stack Error: unable to get local issuer certificate
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:567:8)
29 verbose cwd C:\Windows\system32
30 error Windows_NT 6.3.9600
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
32 error node v4.0.0
33 error npm  v2.14.2
34 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
35 error unable to get local issuer certificate
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

![npm](https://cloud.githubusercontent.com/assets/5173991/9849272/f8031ebc-5af1-11e5-9414-ee66665ee1d7.png)

**Comment by mprentic-harris** [comment] 2015-09-15 15:13
Same issue here after upgrading to node 4.0.0.

**Comment by neocotic** [comment] 2015-10-12 11:01
I can confirm that this problem appears to have been introduced since node 4.x. I've tried npm@2.14.4 and npm@3.3.6 and neither are working since upgrading from node 0.10 to 4.1.

**Comment by rakeshghodasara** [comment] 2015-10-14 20:53
I am also seeing the same error with aws-sdk 
>npm install aws-sdk
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "aws-sdk"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Comment by robertsmith16** [comment] 2015-11-04 15:17
I can confirm its a problem with node 5 as well

npm info using node@v5.0.0
npm info attempt registry request try #1 at 9:09:10 AM
npm http request GET https://registry.npmjs.org/laut
npm info retry will retry, error on last attempt: Error: unable to get local issuer certificate
npm info attempt registry request try #2 at 9:09:20 AM
npm http request GET https://registry.npmjs.org/laut
npm info retry will retry, error on last attempt: Error: unable to get local issuer certificate
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm info attempt registry request try #3 at 9:10:21 AM
npm http request GET https://registry.npmjs.org/laut
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-d" "--https-proxy={http://user:pwd@proxy:port} "-g" "install" "laut"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by Nikhil0538** [comment] 2015-11-09 22:16
what is the solution, can some one help me on this?

**Comment by mprentic-harris** [comment] 2015-11-10 17:04
Only solution I have was that our team moved back to Node 0.12.7 and we aren't going to try upgrading again until this issue is resolved.

**Comment by greenmountains** [comment] 2015-11-10 17:10
We haven't found a solution either.  We are delaying upgrading from 0.12.7 until this is resolved. 

We tried setting the CAfile &/or the CA array since that's often the issue with this error.  In this case it didn't help.  No useful log info even at the silly log level (-ddd).

**Comment by othiym23** [comment] 2015-11-10 17:12
If this isn't already filed as an issue on nodejs/node, then one or more of the people on this thread should let the Node.js maintainers, because npm uses the SSL provided by the Node binary. Just to make sure: everyone on this issue is using a proxy to connect to the npm registry, right?

**Comment by mprentic-harris** [comment] 2015-11-10 17:14
Yes, we have an HTTP and HTTPS proxy between us and the internet.

**Comment by greenmountains** [comment] 2015-11-10 17:44
othiym23, thanks for the response!

It would be helpful to have log statements from node_modules\npm\lib\config\load-cafile.js & whatever loads the ca[] so we can verify that the entire cert chain is being loaded & passed in correctly.  If both are set is one ignored?  were the certs loaded & validated from the PEM file?  How many loaded successfully?  were any found to be invalid?
From the documentation it sounds like the CAfile needs to be a PEM file & not a cacert keystore?   

thanks

**Comment by othiym23** [comment] 2015-11-10 18:11
@greenmountains The fact that this works under Node.js 0.12 and earlier, but breaks on 4.0 and greater is significant here. This indicates that something has changed either in the OpenSSL bindings, or in how Node's HTTPSAgents are constructed or configured. Unfortunately, no changes to the SSL code are enumerated in the Node 4.0.0 release notes, which means that this is probably a change that was made in the io.js fork. I lack the time to sort through those release notes and figure out where the regression is, which is why this should be opened as an issue over yonder in Node.js-land.

If you look at the relevant code [where `--cafile` is loaded](https://github.com/npm/npm/blob/master/lib/config/load-cafile.js) and turned into a CA string, and then [where `ca` is used](https://github.com/npm/npm/blob/master/lib/cache/caching-client.js#L198), and finally [where the HTTPSAgent is created](https://github.com/npm/npm-registry-client/blob/master/lib/initialize.js), you'll see there's not really much to log – most of the low-level stuff is handled within Node's OpenSSL bindings.

> If both are set is one ignored?

By "both" I'm going to assume that you mean `ca` and `cafile`, and in that case, yes, one is discarded (my assumption based on how the code is written is that `cafile` will win because `loadCAFile` will run after the rest of the configuration has loaded). The intent was that you'd use one or the other, but not both.

> were the certs loaded & validated from the PEM file?

If the HTTPSAgent doesn't throw upon construction, then my assumption that whatever was passed as the CA certificate / bundle was parsed correctly, but I don't believe there's a supported interface for consumers of the agent to verify that the CA is set after the fact (there are properties you can examine on the agent, but [none of them are documented](https://nodejs.org/api/https.html#https_class_https_agent), and the Node.js core devs get tetchy when developers rely on those properties having particular names or values, because they reserve the right to change the implementation of Node's internal machinery).

> How many loaded successfully? 

A good question, and not one that I'm sure the current OpenSSL bindings allow you to answer. This is a good question to ask Node core.

> were any found to be invalid?

My assumption is that it's all or nothing.

> From the documentation it sounds like the CAfile needs to be a PEM file & not a cacert keystore?

I've always used a PEM file, and `loadCAFile` was written under that assumption as well, as it looks for ASCII-encoded PEM file delimiters in its parsing. In general, this isn't something handled by npm – it just loads a file into memory, does some mild cleanup, and passes it on to Node for its handling.

**Comment by greenmountains** [comment] 2015-11-10 18:31
@othiym23 thanks for the detailed response.  

Actually, the 0.12 version doesn't require a CAfile to work behind a company proxy.  This requirement appears to be new in the 4.0 version.   We don't have a custom CAfile or CA[] set in our 0.12 version.

**Comment by othiym23** [comment] 2015-11-10 18:43
> Actually, the 0.12 version doesn't require a CAfile to work behind a company proxy. This requirement appears to be new in the 4.0 version. We don't have a custom CAfile or CA[] set in our 0.12 version.

So that's a useful thing to note when talking to Node core (_hint, hint_) – that indicates that something has changed in terms of how Node enforces connection validity. If I had to guess, certificate or CA validation is more strict now? In any case, this is all firmly outside the bounds of npm.

**Comment by greenmountains** [comment] 2015-11-10 18:56
submitted here: https://github.com/nodejs/node/issues/3742

**Comment by mprentic-harris** [comment] 2015-11-10 18:57
@greenmountains thank you.

**Comment by ilanc** [comment] 2015-12-22 12:20
As a workaround you can turn ssl checking off in your .npmrc
`strict-ssl=false`

**Comment by aerialls** [comment] 2015-12-30 17:29
To add more information, I've the same problem. We're using a corporate proxy with MITM HTTPS decryption. The internal root CA is added in the certificate store of the machine. A curl or wget to an HTTPS website is working.

But npm do not seems to use the internal root CA...

```
root@4b7ec71e7d76:/# printenv
...
http_proxy=...
https_proxy=...
HTTP_PROXY=...
HTTPS_PROXY=...
...
```

```
root@4b7ec71e7d76:/# npm get https-proxy
null
```

```
root@4b7ec71e7d76:/# npm get proxy
null
```

```
root@4b7ec71e7d76:/# npm install -g gulp
...
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
...
```

The only solution for this issue is to specified the cafile of the system :

```
root@4b7ec71e7d76:/# npm install -g gulp --cafile /etc/ssl/certs/ca-certificiles.crt
```

**Comment by samdeesh** [comment] 2017-01-09 11:02
I am facing the same issue, tried with node 6.x and 3.x
[npm-debug.txt](https://github.com/npm/npm/files/693256/npm-debug.txt)

**Comment by cdaringe** [comment] 2017-01-12 22:14
for those who landed here for a similar issue, if you are `shrinkwrap`ing, make sure your shrinkwrap file is zen with all resolved URIs pointing to their intended place.  we were transitioning registry URIs and ended up in an inconsistent state (especially with local caching issues!).  trashing your shrinkwrap, re-installing, and re-shrinkwrapping showed me that i had a bunch of mismatches, and resolved my `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error.  makes sense after those realizations are made.

**Comment by Sebisnow** [comment] 2017-03-21 12:29
A simple solution should be to set the proxies before the npm update within npm with:

    npm set proxy=http://{domain}%5C{username}:{mypassword}@{proxyip}:{port}/
    npm set https-proxy=https://{domain}%5C{username}:{mypassword}@{proxyip}:{port}/

But not even that seems to help even though thus the proxy is set within npm. Which can be verified with
    
    npm get proxy

**Comment by nishantkmr** [comment] 2017-03-24 05:38
I ran this command and it worked for me like a charm :)
`npm config set strict-ssl false`

**Comment by KenanY** [comment] 2017-03-24 13:46
I take it that this can be closed now that `node-gyp` has supported `npm`'s `cafile` config for a long time now? If I'm wrong just let me know and I can easily reopen :)

**Closed by KenanY** 2017-03-24 13:46 UTC
Labels: node-bug, support

**Comment by WilliamGroc** [comment] 2017-09-11 11:47
> npm config set strict-ssl false
It's work very well for me (node version v8.4.0 and npm version 5.3.0)
