### ISSUE TITLE
When installing newman in nodejs command line getting error

### ISSUE THREAD

**Issue by gayaniwaduge** [npm/npm#12727] opened 2016-05-17 09:15 UTC
>npm install -g newman

info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli 'newman' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose install initial load of C:\Users\sysadmin\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\sysadmin\AppData\Roaming\npm\package.json
6 silly cache add args [ 'newman', null ]
7 verbose cache add spec newman
8 silly cache add parsed spec Result {
8 silly cache add raw: 'newman',
8 silly cache add scope: null,
8 silly cache add name: 'newman',
8 silly cache add rawSpec: '',
8 silly cache add spec: 'latest',
8 silly cache add type: 'tag' }
9 silly addNamed newman@latest
10 verbose addNamed "latest" is being treated as a dist-tag for newman
11 info addNameTag [ 'newman', 'latest' ]
12 silly mapToRegistry name newman
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry raw: 'newman',
15 silly mapToRegistry scope: null,
15 silly mapToRegistry name: 'newman',
15 silly mapToRegistry rawSpec: '',
15 silly mapToRegistry spec: 'latest',
15 silly mapToRegistry type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/newman
17 verbose addNameTag registry:https://registry.npmjs.org/newman not in flight; fetching
18 verbose request uri https://registry.npmjs.org/newman
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:44:54 AM
21 verbose request id fa7764891d8c8430
22 http request GET https://registry.npmjs.org/newman
23 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 23.235.47.162:443
24 info attempt registry request try #2 at 3:45:25 AM
25 http request GET https://registry.npmjs.org/newman
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:44:54 AM
21 verbose request id fa7764891d8c8430
22 http request GET https://registry.npmjs.org/newman
23 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 23.235.47.162:443
24 info attempt registry request try #2 at 3:45:25 AM
25 http request GET https://registry.npmjs.org/newman
26 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 23.235.40.162:443
27 info attempt registry request try #3 at 3:46:46 AM
28 http request GET https://registry.npmjs.org/newman
29 verbose stack Error: connect ETIMEDOUT 23.235.40.162:443
29 verbose stack at Object.exports._errnoException (util.js:870:11)
29 verbose stack at exports._exceptionWithHostPort (util.js:893:20)
29 verbose stack at TCPConnectWrap.afterConnect as oncomplete
30 verbose cwd C:\Users\sysadmin\AppData\Roaming\npm
31 error Windows_NT 6.1.7601
32 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "newman"
33 error node v4.4.4
34 error npm v2.15.1
35 error code ETIMEDOUT
36 error errno ETIMEDOUT
37 error syscall connect
38 error network connect ETIMEDOUT 23.235.40.162:443
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly. See: 'npm help config'

**Comment by KenanY** [comment] 2016-05-17 14:27
@gayaniwaduge As the error message explains, this looks like an issue with your internet connection rather than an issue with `npm`. Are you behind a proxy? If so, have you configured `npm` to use your proxy? You might also be behind a firewall.

**Comment by KenanY** [comment] 2016-06-07 18:24
@gayaniwaduge It has been about three weeks now without any response from you. Are you still experiencing this issue?

**Comment by KenanY** [comment] 2016-06-29 01:55
Closing as abandoned.

**Closed by KenanY** 2016-06-29 01:55 UTC
Labels: support, windows

**Comment by wadehundley** [comment] 2016-06-29 15:33
I am having a similar problem with Windows 7.  I have confirmed I do not have a proxy using the command : netsh winhttp show proxy.  If I run npm in global mode it works find, but in local mode it has connection issues.  I have also confirmed I can ping the IP of registry.npmjs.org .  This is a subset of the error log:

317 verbose stack Error: connect ETIMEDOUT 23.235.40.162:443
317 verbose stack     at Object.exports._errnoException (util.js:870:11)
317 verbose stack     at exports._exceptionWithHostPort (util.js:893:20)
317 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
318 verbose cwd c:\work\source\engage\Trunk\user-sdm
319 error Windows_NT 6.1.7601
320 error argv "c:\\work\\tools\\nodejs\\node.exe" "c:\\work\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
321 error node v4.4.6
322 error npm  v2.15.5
323 error code ETIMEDOUT
324 error errno ETIMEDOUT
325 error syscall connect
326 error network connect ETIMEDOUT 23.235.40.162:443
326 error network This is most likely not a problem with npm itself
326 error network and is related to network connectivity.
326 error network In most cases you are behind a proxy or have bad network settings.
326 error network
326 error network If you are behind a proxy, please make sure that the
326 error network 'proxy' config is set properly.  See: 'npm help config'
327 verbose exit [ 1, true ]
