### ISSUE TITLE
install ionic error

### ISSUE THREAD

**Issue by xzui** [npm/npm#12479] opened 2016-04-26 09:42 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@3.8.6
3 info using node@v5.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ionic',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'ionic',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ionic
14 verbose request uri https://registry.npmjs.org/ionic
15 verbose request no auth needed
16 info attempt registry request try #1 at 17:09:22
17 verbose request id 9187b7c18a6c7a4c
18 verbose etag "9U7HNWGHT4VIUIL8TGWNTG646"
19 http request GET https://registry.npmjs.org/ionic
20 http 304 https://registry.npmjs.org/ionic
21 verbose headers { date: 'Tue, 26 Apr 2016 09:09:34 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"9U7HNWGHT4VIUIL8TGWNTG646"',
21 verbose headers   age: '167',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-nrt6120-NRT',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1461661774.920760,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 26 Apr 2016 09:09:34 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"9U7HNWGHT4VIUIL8TGWNTG646"',
22 silly get     age: '167',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-nrt6120-NRT',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1461661774.920760,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/ionic from cache
24 verbose get saving ionic to C:\Users\Administrator\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
25 verbose correctMkdir C:\Users\Administrator\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule ionic@1.7.14 checking installable status
39 silly cache add args [ 'ionic', null ]
40 verbose cache add spec ionic
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'ionic',
41 silly cache add   scope: null,
41 silly cache add   name: 'ionic',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed ionic@latest
43 verbose addNamed "latest" is being treated as a dist-tag for ionic
44 info addNameTag [ 'ionic', 'latest' ]
45 silly mapToRegistry name ionic
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'ionic',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   name: 'ionic',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/ionic
50 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
51 verbose get https://registry.npmjs.org/ionic not expired, no request
52 silly addNameTag next cb for ionic with tag latest
53 silly addNamed ionic@1.7.14
54 verbose addNamed "1.7.14" is a plain semver version for ionic
55 silly mapToRegistry name ionic
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'ionic',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   name: 'ionic',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/ionic
60 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz',
61 verbose addRemoteTarball   'af493d5df4688d917d778b0934d1739b9be6efe6' ]
62 info retry fetch attempt 1 at 17:09:27
63 info attempt registry request try #1 at 17:09:27
64 http fetch GET https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
65 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
66 info retry will retry, error on last attempt: Error: read ECONNRESET
67 info retry will retry, error on last attempt: Error: read ECONNRESET
68 silly fetchAndShaCheck shasum af493d5df4688d917d778b0934d1739b9be6efe6
69 silly rollbackFailedOptional Starting
70 silly rollbackFailedOptional Finishing
71 silly runTopLevelLifecycles Starting
72 silly runTopLevelLifecycles Finishing
73 silly install printInstalled
74 verbose stack Error: shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-8728-dbe0c03a\registry.npmjs.org\ionic\-\ionic-1.7.14.tgz
74 verbose stack Expected: af493d5df4688d917d778b0934d1739b9be6efe6
74 verbose stack Actual:   57447ffcd377c92825f983e8c3ec78e37a78e28e
74 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
74 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
74 verbose stack     at ReadStream.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
74 verbose stack     at emitNone (events.js:85:20)
74 verbose stack     at ReadStream.emit (events.js:179:7)
74 verbose stack     at endReadableNT (_stream_readable.js:913:12)
74 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
74 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
75 verbose cwd C:\Users\Administrator
76 error Windows_NT 6.1.7601
77 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
78 error node v5.11.0
79 error npm  v3.8.6
80 error shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-8728-dbe0c03a\registry.npmjs.org\ionic\-\ionic-1.7.14.tgz
80 error Expected: af493d5df4688d917d778b0934d1739b9be6efe6
80 error Actual:   57447ffcd377c92825f983e8c3ec78e37a78e28e
80 error From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
81 error If you need help, you may report this error at:
81 error     <https://github.com/npm/npm/issues>
82 verbose exit [ 1, true ]
```

**Comment by zkat** [comment] 2016-12-09 00:41
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:41 UTC
Labels: network, support, windows
