### ISSUE TITLE
 Refusing to install angular2-google-map-auto-complete as a dependency of itself

### ISSUE THREAD

**Issue by kunalpawar** [npm/npm#16254] opened 2017-04-05 09:33 UTC
Refusing to install angular2-google-map-auto-complete as a dependency of itself

**Comment by KenanY** [comment] 2017-04-05 11:46
@kunalpawar Make sure that the `"name"` field in your `package.json` is not the same as the name of any dependency you are installing. Make it more unique! :)

Closing since this is intended behavior of `npm`, but let me know if you need further help.

**Closed by KenanY** 2017-04-05 11:46 UTC
Labels: support

**Comment by kunalpawar** [comment] 2017-04-05 12:38
thanks its work
