### ISSUE TITLE
Ability to sign commits

### ISSUE THREAD

**Issue by riyadhalnur** [npm/npm#13333] opened 2016-07-10 09:57 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?
Ability to sign commits

#### What problem is the feature intended to solve?
Similar to signing tags which NPM already has, ability to sign commits would be handy as well.

#### Is the absence of this feature blocking you or your team? If so, how?
Not blocking. It's a nice-to-have.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
Yes

**Comment by KenanY** [comment] 2016-07-10 14:29
Duplicate of https://github.com/npm/npm/issues/12696.

**Closed** 2016-07-10 14:29 UTC
Labels: feature-request, git
