### ISSUE TITLE
appium installed failed with "npm ERR! tar.unpack unzip error /tmp/npm-16373-0d525ef3/registry.npmjs.org/appium-adb/-/appium-adb-2.4.3.tgz"

### ISSUE THREAD

**Issue by Aimely** [npm/npm#12026] opened 2016-03-23 10:50 UTC
I'm trying to install appium in my Mac  , but it failed ; I've tried reinstalled node.js again ,it didn't work, what's the problem ?  Any suggestions?

npm ERR! tar.unpack unzip error /tmp/npm-16373-0d525ef3/registry.npmjs.org/appium-adb/-/appium-adb-2.4.3.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/didi/npm-debug.log

**Comment by zkat** [comment] 2016-03-23 21:02
Hey! This sort of thing will occasionally happen due to unknown issues with the cache, terminating processes, etc. Basically it involves a bad tarball somehow making its way into your cache. I'm going to close this as a duplicate of #11993.

For now, could you try doing `npm cache clean` and trying again? That tends to clear up the issue. Please direct further discussion with more details at that other thread, if it doesn't work. :)

**Closed by zkat** 2016-03-23 21:02 UTC
Labels: cache, support

**Comment by grrowl** [comment] 2018-01-11 06:25
For future reference: Node 8.9.0+ (and 9+) fix an issue where streams are terminated early in some scenarios. If you're getting this error upgrade to 8.9.

https://github.com/nodejs/node/issues/13391
