### ISSUE TITLE
NodeJS:  ccap failed to install on centos7 with "npm install ccap -y"

### ISSUE THREAD

**Issue by Fanniewang** [npm/npm#10432] opened 2015-11-17 10:37 UTC
root@tengyun01 soft]# cd nodejs
[root@tengyun01 nodejs]# npm install ccap -y
npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "/usr/tycom/yjmall/soft/nodejs/bin/node" "/usr/tycom/yjmall/soft/nodejs/bin/npm" "install" "ccap" "-y"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for /tmp/npm-56711-b3c8f1fb/registry.npmjs.org/ccap/-/ccap-0.6.4.tgz
npm ERR! Expected: ee2f51f5aefac3b2cf285c4a0555beeb020bc621
npm ERR! Actual:   1bab8585f691e52c859a9f309ce9f3e97405e3dd
npm ERR! From:     https://registry.npmjs.org/ccap/-/ccap-0.6.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/tycom/yjmall/soft/nodejs/npm-debug.log
[root@tengyun01 nodejs]# uname -a
Linux tengyun01 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[npm-debug-log.txt](https://github.com/npm/npm/files/36535/npm-debug-log.txt)

**Comment by OmgImAlexis** [comment] 2015-12-01 05:31
Looks like they may have forgotten to update the sha hash.
https://github.com/DoubleSpout/ccap/commit/1654f91348a0b1f5862a2d60dd9aa22ead3f4dfb

**Comment by DoubleSpout** [comment] 2016-06-09 06:38
please update your node to 6.2.0, ndoe-gyp to 3.3.1,retry it~

**Comment by zkat** [comment] 2016-12-09 00:53
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:53 UTC
