### ISSUE TITLE
Unable to install jade in a node.js project on mac os x

### ISSUE THREAD

**Issue by Daemon-Devarshi** [npm/npm#8486] opened 2015-06-07 11:09 UTC
I am trying a sample node.js based project by referring this tutorial: [How To Write A Simple Node.js/MongoDB Web Service for an iOS App][1]. I have configured my package.json like this:
```json
    {
    	"name": "mango-server",
    	"version": "0.0.1",
    	"private": true,
    	"dependencies": {
    		"express": "*",
    		"jade": "*"
    	}
    }
```
Problem is - when I try `npm update` or `npm install` it is showing me below error messages on console:

    npm ERR! Error: No compatible version found: uglify-js@'^2.4.19'
    npm ERR! Valid install targets:
    npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.1.0","1.1.1","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","1.2.5","1.2.6","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","2.2.0","2.2.1","2.2.2","2.2.3","2.2.4","2.2.5","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","2.3.5","2.3.6","1.3.5","2.4.0","2.4.1","2.4.2","2.4.3","2.4.4","2.4.5","2.4.6","2.4.7","2.4.8","2.4.9","2.4.10","2.4.11","2.4.12","2.4.13","2.4.14","2.4.15","2.4.16","2.4.17","2.4.18","2.4.19","2.4.20","2.4.21","2.4.22","2.4.23"]
    npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
    npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
    npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
    npm ERR!     at Object.oncomplete (fs.js:107:15)
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>
    
    npm ERR! System Darwin 14.0.0
    npm ERR! command "node" "/usr/local/bin/npm" "update"
    npm ERR! cwd /Users/devarshi/Documents/NodeTutorial
    npm ERR! node -v v0.10.3
    npm ERR! npm -v 1.2.17
    npm http 304 https://registry.npmjs.org/constantinople
    npm http 304 https://registry.npmjs.org/jstransformer/0.0.2
    npm http 304 https://registry.npmjs.org/character-parser/1.2.1
    npm http 304 https://registry.npmjs.org/with
    npm http 304 https://registry.npmjs.org/clean-css
    npm http 304 https://registry.npmjs.org/void-elements
    npm http 304 https://registry.npmjs.org/transformers/2.1.0
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /Users/devarshi/Documents/NodeTutorial/npm-debug.log
    npm ERR! not ok code 0

I am clueless, please suggest.

  [1]: http://www.raywenderlich.com/61078/write-simple-node-jsmongodb-web-service-ios-app

**Comment by sweber6106** [comment] 2015-06-07 14:02
The package.json is fine.  The install works on my machine.  (OSX 10.10.3, npm v1.4.28).

**Comment by sweber6106** [comment] 2015-06-07 14:05
My install uses v2.4.23 of the uglify dependency.

$ npm install
express@4.12.4 node_modules/express
├── merge-descriptors@1.0.0
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── cookie@0.1.2
├── fresh@0.2.4
├── range-parser@1.0.2
├── content-type@1.0.1
├── finalhandler@0.3.6
├── escape-html@1.0.1
├── vary@1.0.0
├── parseurl@1.3.0
├── serve-static@1.9.3
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── etag@1.6.0 (crc@3.2.1)
├── debug@2.2.0 (ms@0.7.1)
├── send@0.12.3 (destroy@1.0.3, ms@0.7.1, mime@1.3.4)
├── accepts@1.2.7 (negotiator@0.5.3, mime-types@2.0.14)
└── type-is@1.6.2 (media-typer@0.3.0, mime-types@2.0.14)

jade@1.10.0 node_modules/jade
├── character-parser@1.2.1
├── void-elements@2.0.1
├── commander@2.6.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── jstransformer@0.0.2 (is-promise@2.0.0, promise@6.1.0)
├── with@4.0.3 (acorn-globals@1.0.4, acorn@1.2.2)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
├── constantinople@3.0.1 (acorn-globals@1.0.4)
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
└── clean-css@3.3.1 (commander@2.8.1, source-map@0.4.2)

**Comment by alanbsmith** [comment] 2015-06-07 14:15
The issue looks like it's not finding a compatible version of uglify-js. As stated above ^. You might need to specifically declare a version in your `package.json`.

If that doesn't work, you might look at your version of node. If you have 0.13.0, it's unstable and very few things will work with it. In that case, back it down to any 0.12 version and you should be fine.

**Comment by KenanY** [comment] 2015-06-14 21:44
@Daemon-Devarshi This is certainly caused by your extremely old version of `npm`, which does not support the `^` semver operator. Try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment] 2016-05-15 17:57
@Daemon-Devarshi It has been a while... are you still experiencing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment] 2016-06-28 21:01
Closing as abandoned.

**Closed by KenanY** 2016-06-28 21:01 UTC
Labels: support
