### ISSUE TITLE
npm install --save isn't writing to package.json after manual delete

### ISSUE THREAD

**Issue by thebenwaters** [npm/npm#15448] opened 2017-01-11 13:03 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to do 
Also i'm doing this because the server runs out of server with the package in it with the dependencies.

```
sed delete package from package.json
npm install
npm install --save package (the same one deleted from the line)
```

Then the package isn't written to the package.json

### supporting information:

 - `npm -v` prints:
3.3.12
 - `node -v` prints:
v5.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 14.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-01-11 15:20
Cannot reproduce on `npm@4.1.1`. Try updating to latest.

**Comment by KenanY** [comment] 2017-01-18 17:26
Closing as abandoned.

**Closed by KenanY** 2017-01-18 17:26 UTC
