### ISSUE TITLE
i need  help...

### ISSUE THREAD

**Issue by Perterually** [npm/npm#12462] opened 2016-04-25 08:12 UTC
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/bin/npm" "view"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6

npm ERR! Invalid package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/perterually/npm-debug.log
```

**Comment by KenanY** [comment] 2016-04-25 13:15
@Perterually 

```
npm ERR! Invalid package.json
```

Do you have a `package.json` file in your current directory (`/Users/perterually/`)? If not, then can you explain what you are expecting to happen when you run `npm view`?

**Comment by Perterually** [comment] 2016-04-26 01:45
@KenanY 

I did not find。。。
what should i do

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6

npm ERR! Invalid package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/perterually/npm-debug.log

**Comment by KenanY** [comment] 2016-04-26 02:07
@Perterually Without answering my second question, you've left me lost as to what you are trying to accomplish. As [documented in the `npm view` docs](https://docs.npmjs.com/cli/view), `npm view` has no idea what package you want it to view info for unless you either pass it an argument or run it in a directory which contains a `package.json`.

**Comment by Perterually** [comment] 2016-04-26 02:43
Sorry I made a mistake。。
You look at the log


npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hexo-site
npm ERR! 404
npm ERR! 404  'hexo-site' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/perterually/hexo/npm-debug.log





0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'view' ]
2 info using npm@3.8.6
3 info using node@v5.11.0
4 silly mapToRegistry name hexo-site
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'hexo-site',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   name: 'hexo-site',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/hexo-site
9 verbose request uri https://registry.npmjs.org/hexo-site
10 verbose request no auth needed
11 info attempt registry request try #1 at 10:35:04 AM
12 verbose request id 53792c07f0cfc998
13 http request GET https://registry.npmjs.org/hexo-site
14 http 404 https://registry.npmjs.org/hexo-site
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '2',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Tue, 26 Apr 2016 02:35:20 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-itm7427-ITM',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1461638120.219074,VS0,VE186',
15 verbose headers   vary: 'Accept-Encoding' }
16 silly get cb [ 404,
16 silly get   { 'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '2',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Tue, 26 Apr 2016 02:35:20 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-itm7427-ITM',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1461638120.219074,VS0,VE186',
16 silly get     vary: 'Accept-Encoding' } ]
17 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/hexo-site
17 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
17 verbose stack     at emitTwo (events.js:100:13)
17 verbose stack     at Request.emit (events.js:185:7)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
17 verbose stack     at emitOne (events.js:95:20)
17 verbose stack     at Request.emit (events.js:182:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
18 verbose statusCode 404
19 verbose pkgid hexo-site
20 verbose cwd /Users/perterually/hexo
21 error Darwin 14.5.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
23 error node v5.11.0
24 error npm  v3.8.6
25 error code E404
26 error 404 Registry returned 404 for GET on https://registry.npmjs.org/hexo-site
27 error 404
28 error 404 'hexo-site' is not in the npm registry.
29 error 404 You should bug the author to publish it (or use the name yourself!)
30 error 404 Note that you can also install from a
31 error 404 tarball, folder, http url, or git url.
32 verbose exit [ 1, true ]

**Comment by Perterually** [comment] 2016-04-26 02:43
@KenanY 

Sorry I made a mistake。。
You look at the log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
npm ERR! node v5.11.0
npm ERR! npm v3.8.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hexo-site
npm ERR! 404
npm ERR! 404 'hexo-site' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/perterually/hexo/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'view' ]
2 info using npm@3.8.6
3 info using node@v5.11.0
4 silly mapToRegistry name hexo-site
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry raw: 'hexo-site',
7 silly mapToRegistry scope: null,
7 silly mapToRegistry name: 'hexo-site',
7 silly mapToRegistry rawSpec: '',
7 silly mapToRegistry spec: 'latest',
7 silly mapToRegistry type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/hexo-site
9 verbose request uri https://registry.npmjs.org/hexo-site
10 verbose request no auth needed
11 info attempt registry request try #1 at 10:35:04 AM
12 verbose request id 53792c07f0cfc998
13 http request GET https://registry.npmjs.org/hexo-site
14 http 404 https://registry.npmjs.org/hexo-site
15 verbose headers { 'content-type': 'application/json',
15 verbose headers 'cache-control': 'max-age=0',
15 verbose headers 'content-length': '2',
15 verbose headers 'accept-ranges': 'bytes',
15 verbose headers date: 'Tue, 26 Apr 2016 02:35:20 GMT',
15 verbose headers via: '1.1 varnish',
15 verbose headers age: '0',
15 verbose headers connection: 'keep-alive',
15 verbose headers 'x-served-by': 'cache-itm7427-ITM',
15 verbose headers 'x-cache': 'MISS',
15 verbose headers 'x-cache-hits': '0',
15 verbose headers 'x-timer': 'S1461638120.219074,VS0,VE186',
15 verbose headers vary: 'Accept-Encoding' }
16 silly get cb [ 404,
16 silly get { 'content-type': 'application/json',
16 silly get 'cache-control': 'max-age=0',
16 silly get 'content-length': '2',
16 silly get 'accept-ranges': 'bytes',
16 silly get date: 'Tue, 26 Apr 2016 02:35:20 GMT',
16 silly get via: '1.1 varnish',
16 silly get age: '0',
16 silly get connection: 'keep-alive',
16 silly get 'x-served-by': 'cache-itm7427-ITM',
16 silly get 'x-cache': 'MISS',
16 silly get 'x-cache-hits': '0',
16 silly get 'x-timer': 'S1461638120.219074,VS0,VE186',
16 silly get vary: 'Accept-Encoding' } ]
17 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/hexo-site
17 verbose stack at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack at CachingRegistryClient. (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
17 verbose stack at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
17 verbose stack at emitTwo (events.js:100:13)
17 verbose stack at Request.emit (events.js:185:7)
17 verbose stack at Request. (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
17 verbose stack at emitOne (events.js:95:20)
17 verbose stack at Request.emit (events.js:182:7)
17 verbose stack at IncomingMessage. (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
18 verbose statusCode 404
19 verbose pkgid hexo-site
20 verbose cwd /Users/perterually/hexo
21 error Darwin 14.5.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
23 error node v5.11.0
24 error npm v3.8.6
25 error code E404
26 error 404 Registry returned 404 for GET on https://registry.npmjs.org/hexo-site
27 error 404
28 error 404 'hexo-site' is not in the npm registry.
29 error 404 You should bug the author to publish it (or use the name yourself!)
30 error 404 Note that you can also install from a
31 error 404 tarball, folder, http url, or git url.
32 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2016-04-26 03:46
@Perterually Since there's no module in the registry named `hexo-site`, `npm view` is correctly returning a `404` error here. This is expected behavior.

**Comment by Perterually** [comment] 2016-04-26 05:12
@KenanY 

Thank you very much, I don't know.

**Comment by KenanY** [comment] 2016-06-28 21:26
Closing as resolved.

**Closed by KenanY** 2016-06-28 21:26 UTC
Labels: support
