### ISSUE TITLE
npm install command fails while creating a MeanJS Application

### ISSUE THREAD

**Issue by shrikantsharda** [npm/npm#11009] opened 2016-01-02 10:38 UTC
When I try to create a web application using the meanjs generator, the terminal shows the following output. I am new to this and don't really understand the output that I get on the terminal.

Any help regarding this would be deeply appreciated.

I am using Mac OS X Yosemite.

```
Shrikants-MacBook-Pro:Documents shrikantsharda$ sudo yo meanjs
Password:
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.2
0.4.2
? In which folder would you like the project to be generated? This can be change
? In which folder would you like the project to be generated? This can be change
d later. TestApp
Cloning the MEAN repo.......
? What would you like to call your application? TestApp
? How would you describe your application? Test Web App
? How would you describe your application in comma seperated key words? MongoDB,
 Express, AngularJS, Node.js
? What is your company/author name? TestApp
? Would you like to generate the article example CRUD module? Yes
? Would you like to generate the chat example module? No
Running npm install for you....
This may take a couple minutes.
Error: Command failed: /bin/sh -c cd TestApp && npm install
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.4","npm":"3.5.2"})
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2

npm ERR! shasum check failed for /tmp/npm-458-330a159c/registry.npmjs.org/v8-debug/-/v8-debug-0.7.0.tgz
npm ERR! Expected: 9696d6120ff3ee7f56e6d42cc32156eb32f5f647
npm ERR! Actual:   78d98b315160189da16eccc87176d455c3a10e83
npm ERR! From:     https://registry.npmjs.org/v8-debug/-/v8-debug-0.7.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shrikantsharda/Documents/TestApp/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

```

[npm-debug.log.pdf](https://github.com/npm/npm/files/76182/npm-debug.log.pdf)
Please refer to the attached file incase you wish to go through the npm-debug.log of the Application

**Comment by zkat** [comment] 2016-12-09 00:49
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:49 UTC
Labels: support
