### ISSUE TITLE
install sqlite3

### ISSUE THREAD

**Issue by zhangayndou** [npm/npm#15414] opened 2017-01-06 11:51 UTC
npm install sqlite3 error.
error follow:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "Sqlite3"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! shasum check failed for C:\Users\xdja\AppData\Local\Temp\npm-8564-30f9e
88d\registry.npmjs.org\sqlite3\-\sqlite3-3.1.8.tgz
npm ERR! Expected: 4cbcf965d8b901d1b1015cbc7fc415aae157dfaa
npm ERR! Actual:   8f2d37c07476ab97ca1724dddae2a27639b355fc
npm ERR! From:     https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues

**Comment by Charlotteis** [comment] 2017-01-06 17:06
This is a duplicate of https://github.com/npm/npm/issues/14626

Please upgrade npm to the latest version.

```
npm install -g npm@latest
```

🌸

**Comment by KenanY** [comment] 2017-02-03 13:10
Closing as a duplicate.

**Closed by KenanY** 2017-02-03 13:10 UTC
