### ISSUE TITLE
Config setting to prevent npm-debug.log from being written

### ISSUE THREAD

**Issue by mike-spainhower** [npm/npm#7648] opened 2015-03-17 00:39 UTC
Moving an off-topic issue request in https://github.com/npm/npm/issues/6350 to its own issue.

@maxogden:

> this is slightly off topic, but is there some magic command I can run to completely disable the npm-debug log from ever getting written on my computer?

@jsdevel:

> It would be really nice if the creation of npm-debug.log could be entirely disabled in ~/.npmrc.

I don't know the use case, I am just try to prevent an issue I do care about from being hijacked :wink:

**Comment by KenanY** [comment] 2015-03-17 00:55
Hmm, I wonder if this could fall under https://github.com/npm/npm/issues/7614 (i.e. set log count to 0)?

**Comment by gabipetrovay** [comment] 2015-10-06 14:41
+1

**Comment by othiym23** [comment] 2016-03-22 20:54
Closing as duplicate of #7614. If / when the CLI team (or enterprising contributors HINT HINT) have time to tackle that one, it will considerably improve the user experience around debug logging to the point that these kinds of concerns will be much less significant (although I'm overall -1 on disabling debug logging entirely). Thanks for your time and patience!

**Closed by othiym23** 2016-03-22 20:54 UTC
Labels: feature-request
