### ISSUE TITLE
Path problem (double path appended) with [windows]

### ISSUE THREAD

**Issue by MetaMemoryT** [npm/npm#7623] opened 2015-03-13 21:33 UTC
```
$ npm --version
2.5.1
```

npm-debug.log: https://gist.githubusercontent.com/MetaMemoryT/e4e5f900cc85c8d305ef/raw/gistfile1.txt

```
npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\A
ppData\Local\Temp\npm-3476-0e535199\git-cache-45e70f968897\a41a40b49046747b3af57341cda048bbd3d9df79                                                                       
npm ERR! Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-3476-0e535199\git-cache-45e70f968897\a41a40b49046747b3af57341cda048bbd3d9df79'...                             
npm ERR! fatal: '/c/Users/Sean/AppData/Roaming/npm-cache/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\htt
ps-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository                                                                                          
npm ERR! fatal: Could not read from remote repository.                                                                                                                    

```

**Comment by othiym23** [comment] 2015-03-13 22:21
Your error log shows that you're using Cygwin, and [npm doesn't support Cygwin](https://github.com/npm/npm#installing-on-cygwin). I know that's a pain, but it turns out that supporting Cygwin is extra-hard when you also support both full Unix and WIndows, and there aren't enough Cygwin users out there to make the extra complexity of supporting Cygwin tenable.

This particular issue is something that Git does when `longpaths` support is enabled, but npm needs that turned on to support regular Windws (and mingw2 / Git Bash) users. You might be able to get that behavior fixed in git, and that's where it should be fixed.

**Comment by MetaMemoryT** [comment] 2015-03-13 22:24
Thanks for providing an excellent explanation of the problem.

**Comment by silverwind** [comment] 2015-03-15 17:17
Related: https://github.com/npm/npm/issues/7456

@MetaMemoryT are you really on Cygwin? the `/c/` path leads me to believe this is an MSYS enviroment (Used by Git Bash), can you confirm?

**Comment by MetaMemoryT** [comment] 2015-03-16 14:04
Yah, I am using msys.

```
$ git --version
git version 1.9.3
```

**Comment by MetaMemoryT** [comment] 2015-03-16 18:23
@othiym23 this is not due to using Cygwin, I switched to plain cmd and got the same problem

the new npm-debug.log: 
https://gist.githubusercontent.com/MetaMemoryT/eff62dfbe08c7c97a350/raw/e9f417efc41115201e13de348ac8007732acda5f/gistfile1.txt


```
C:\Users\Sean\p\atom-beautify>npm update
npm ERR! git -c core.longpaths=true clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79: Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79'...
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79: fatal: '/c/Users/Sean/AppData/Roaming/npm-cache/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79:
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79: and the repository exists.
npm ERR! git clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79:
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.2
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79
npm ERR! Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79'...
npm ERR! fatal: '/c/Users/Sean/AppData/Roaming/npm-cache/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sean\p\atom-beautify\npm-debug.log
```

**Comment by silverwind** [comment] 2015-03-16 18:27
You still have the  `'/c/'`path in there, which makes me believe your `git` is MSYS's too on `cmd`. Does reinstalling http://git-scm.com/download/win help? (Though I'm not sure if that isn't actually MSYS too)

**Comment by MetaMemoryT** [comment] 2015-03-16 18:30
@silverwind giving the reinstall a try

**Comment by silverwind** [comment] 2015-03-16 18:36
The root issue for me at least is that a local clone like `git clone c:\src c:\dst` gets paths merged wrongly.

I think there is real native git for windows in the works (without msys), but I can't find the repo right now.

**Comment by othiym23** [comment] 2015-03-16 18:39
```
npm ERR! Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79'...
npm ERR! fatal: '/c/Users/Sean/AppData/Roaming/npm-cache/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
```

I think @silverwind may be right, because here's the command that npm is running under the hood:

```
git -c core.longpaths=true clone C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9 C:\Users\Sean\AppData\Local\Temp\npm-4864-1e04ad5e\git-cache-84affc80ee5b\a41a40b49046747b3af57341cda048bbd3d9df79
```

As you can see, that doesn't include `/c/` at all. If it's not the MSYS version of Git being confused about paths, then it's probably the MSYS / Cygwin versions of Git being confused by `-c core.longpaths=true`. If that's the case, then we're going to need to revisit how npm deals with git on Windows. That switch was added (59eb112eec7bfd0e39b6098142d76ad66d3aca14) to prevent issues for ordinary Windows users using the default git (#5525), so the safest solution is probably to feature test on whether or not you're using a Windows or POSIXified Git. @silverwind, if you wanted to take a stab at fixing that, I could try to get it landed in the next week or two.

**Comment by othiym23** [comment] 2015-03-16 18:40
I've previously confirmed that using a stock install of Git using GitHub's Windows installer does not have this problem, back when I merged 59eb112eec7bfd0e39b6098142d76ad66d3aca14.

**Comment by MetaMemoryT** [comment] 2015-03-16 18:40
Horay! This version of git seems to fix it!

```
$ git --version
git version 1.9.5.msysgit.0
```

**Comment by silverwind** [comment] 2015-03-16 18:43
I don't thing it's related to `longpaths`, and I'm quite surprised it shows on  msys 1.9.3, but not 1.9.5, makes be believe the cause must be on shared code between cygwin and msys.

I have to do further tests in an VM, as I don't want to mess up my otherwise working git from Cygwin.

**Comment by othiym23** [comment] 2015-03-16 18:46
@silverwind Are you sure that was a msysgit version before? I'd have to double-check to make sure, but I was under the impression that even 1.9.3 included `msysgit` in the version string.

**Comment by silverwind** [comment] 2015-03-16 18:48
@MetaMemoryT remember where you obtained your previous git?

@othiym23 If you could point me to the code parts where platform detection is performed, I might be able to add a tiny Cygwin fix. I assume it would work if npm wouldn't use `C:\` style paths on Cygwin.

**Comment by MetaMemoryT** [comment] 2015-03-16 18:56
@silverwind it could have been an ancient pacman vanilla msys installed one, the order of my PATH variable was choosing this one over the msysgit one.

**Comment by silverwind** [comment] 2015-03-16 19:04
I think it's safe to assume that @MetaMemoryT didn't have the non-posix version of git installed.

So the fix would probably be to test `git version` for an `'msysgit'` string, and if not found, use posix paths in clone (`'/c/'` and `'/cygdrive/c/'`). That might get messy...

**Comment by othiym23** [comment] 2015-03-16 19:59
> If you could point me to the code parts where platform detection is performed, I might be able to add a tiny Cygwin fix.

Those normalized paths are coming from Node, not npm, and I won't accept any Cygwin-specific patches that override what Node returns on Windows. Every time npm has tried to support Cygwin in the past it has ended in tears. I'm willing to support fixes for known issues with MSYS, but not Cygwin.

**Comment by silverwind** [comment] 2015-03-16 22:41
Yeah, it's not something that should be fixed in npm itself, but rather upstream.

I still intend to research this further and bring up this issue on the Cygwin mailing list if I can reproduce on a vanilla Cygwin Installation.

As for this issue, I think it can be closed, as it's been proven to work using the lastes Git Bash.

**Comment by othiym23** [comment] 2015-03-16 22:44
:+1: Closing as resolved.

Sorry if I'm being obnoxious, @silverwind. Keeping things working smoothly on Windows and dealing with proxy weirdness are the two most fragile parts of the npm codebase, and so I have to take a pretty hard line there.

**Closed by othiym23** 2015-03-16 22:44 UTC
Labels: bug, next-patch, patch-welcome, windows
