### ISSUE TITLE
npm validation for package install

### ISSUE THREAD

**Issue by js08** [npm/npm#10035] opened 2015-10-20 04:18 UTC
I have a react app, in which folder name is sports, inside the sports folder I have node modules, inside the node modules folder I have football folder and react folder.
If go to football folder and do npm install react its installing react, which makes my application fail, how to prevent this command npm install react from being successful.
Is it anyway we can right a script to prevent this process to happen, but it should work when we do npm install react in sports folder. Is there any already npm packages which we use it make automatically validated our npm commands.

**Comment by othiym23** [comment] 2015-10-21 05:16
`npm ls` will tell you whether the overall install tree contains any invalid or extraneous packages. `npm@3` uses a new package layout algorithm that installs the packages as flat as possible, so assuming there are no semver conflicts, you'll end up with only one copy of `react` in the installed tree.

It's unclear to me why you'd want to manually install `react` into a folder inside your application's `node_modules` directory, but be aware that the singleton pattern that (older versions of) react relies on is not a safe one to use with npm – it will install as many copies of a package as it needs to install to ensure that all of a package's dependencies get the versions of their own dependencies that they need, and any package that requires that it be the only copy of that package in the install tree is therefore broken by design. I believe that newer versions of `react` are designed in such a way that they ensure that everybody is using the same instance of the react framework without relying on this dangerous assumption.

If you want to see if you can force your application to only have a single copy of `react` and you're using `npm@2`, then run `npm dedupe`. If it can't convert the installed `node_modules` to only have a single copy of react, it will print out diagnostic information pointing at the conflicts between the different versions.

Good luck! I hope this helps you figure out the issues you're seeing. Because this isn't a bug in npm, I'm going to close this issue out now.

**Closed by othiym23** 2015-10-21 05:16 UTC
Labels: support

**Comment by js08** [comment] 2015-10-21 05:20
@othiym23 is it possible to automate the process

**Comment by othiym23** [comment] 2015-10-21 05:22
In effect, yes, if you're using `npm@3`, because it uses a new install algorithm that looks at the current state of `node_modules` before deciding what it needs to do to bring the tree up to date. If it notices extraneous modules (and the tree was originally installed by `npm@3`, which sets some special metadata in the installed packages for its own use), it will move them / deduplicate them automatically.

**Comment by js08** [comment] 2015-10-21 05:25
@othiym23 can we move that part of code aline in npm 2 versiom

**Comment by othiym23** [comment] 2015-10-21 05:28
No. This is the primary feature that makes `npm@3` a new major version, and it makes no sense to backport it to `npm@2`, especially as `npm@3` is now the latest stable version of npm. If you want to get behavior like this in `npm@2`, use `npm dedupe` after running `npm install`.

**Comment by js08** [comment] 2015-10-21 05:31
@othiym23 is it Possible to automate the process if there is auch scenario
