### ISSUE TITLE
Cannot uninstall yarn from global packages

### ISSUE THREAD

**Issue by mateo-leal** [npm/npm#17326] opened 2017-06-19 17:42 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I try to uninstall yarn `npm uninstall -g yarn` this error appears

```
Unhandled rejection Error: Argument #2: Expected string but got null62521a7d779c
    at addDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:463:5
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Program Files\nodejs\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mateo\AppData\Roaming\npm-cache\_logs\2017-06-19T17_14_16_384Z-debug.log
```

#### How can the CLI team reproduce the problem?

[Debug log](https://gist.github.com/Mateolegi/7692bdb5a338f761d9eedc8a740deaf5)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-06-19 17:57
Looks like a duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-19 17:57 UTC
Labels: npm5
