### ISSUE TITLE
shasum check failed for C:\Users\hp\AppData\Local\Temp\npm-6464-c8623232\registry.npmjs.org\ionic\-\ionic-2.1.12.tgz

### ISSUE THREAD

**Issue by othadem** [npm/npm#14670] opened 2016-11-19 18:44 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by othadem** [comment] 2016-11-19 18:46
F:\Installation\nodejs>npm install ionic
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\Installation\\nodejs\\node.exe" "F:\\Installation\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\hp\AppData\Local\Temp\npm-6464-c8623232\registry.npmjs.org\ionic\-\ionic-2.1.12.tgz
npm ERR! Expected: e0102b764d589a09e9cbd432c338d9c539feeebe
npm ERR! Actual:   901a569e94e8b01803a94f58948ae664c9cff40f
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.12.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment] 2016-11-29 01:27
Check you internet connection and then `npm cache clean ionic`.

**Comment by zkat** [comment] 2016-12-02 04:46
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:46 UTC
Labels: network, shasum, support
