### ISSUE TITLE
unpublish does not work

### ISSUE THREAD

**Issue by caperavensoftware** [npm/npm#12399] opened 2016-04-18 16:12 UTC
I have a private repository and I have two packages there that I used for testing purposes trying to get my head around package management.

I would like to delete those two packages but unpublish gives me a 400 error.
I also tried using --force but that still did not help getting it deleted.

How can I remove "redundant" private repositories?

**Comment by KenanY** [comment] 2016-04-18 16:15
@caperavensoftware I think this is caused by the [recent change in unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy).

**Comment by caperavensoftware** [comment] 2016-04-18 19:32
aah excellent, ty, I will contact support as per instructions in the link.

**Comment by othiym23** [comment] 2016-04-18 20:44
Closing as redirected to support.

**Closed by othiym23** 2016-04-18 20:44 UTC
Labels: registry, support
