### ISSUE TITLE
Parsoid install error

### ISSUE THREAD

**Issue by capedmadman** [npm/npm#14530] opened 2016-11-04 20:28 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have mediawiki installed and I am trying to install parsoid to use the VisualEditor extension. I am trying to install it on Server 2012 and getting the following error.

```
54123 verbose stack TypeError: Cannot read property 'debug' of undefined
54123 verbose stack     at C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:35:40
54123 verbose stack     at Array.filter (native)
54123 verbose stack     at inflateShrinkwrap (C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:34:49)
54123 verbose stack     at C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:16
54123 verbose stack     at C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
54123 verbose stack     at zalgoSafe (C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\node_modules\dezalgo\dezalgo.js:20:10)
54123 verbose stack     at finalize (C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\node_modules\realize-package-specifier\index.js:39:5)
54123 verbose stack     at C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\node_modules\realize-package-specifier\index.js:22:20
54123 verbose stack     at C:\Users\wikiuser\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:276:29
54123 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
54124 verbose cwd C:\Users\wikiuser
54125 error Windows_NT 6.3.9600
54126 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wikiuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "parsoid"
54127 error node v6.9.1
54128 error npm  v4.0.2
54129 error Cannot read property 'debug' of undefined
54130 error If you need help, you may report this error at:
54130 error     <https://github.com/npm/npm/issues>
54131 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment] 2016-11-04 20:50
Closing as duplicate of #14427.

**Closed by othiym23** 2016-11-04 20:50 UTC
Labels: big-bug, bug, shrinkwrap
