### ISSUE TITLE
Unable to do npm install

### ISSUE THREAD

**Issue by seekshiva** [npm/npm#10801] opened 2015-12-13 06:58 UTC
```
npm install --save react-color
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "react-color"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/l6/ffsn9z154ms70xxx21cnw4zc0000gn/T/npm-26751-78d96325/registry.npmjs.org/react-color/-/react-color-1.3.0.tgz
npm ERR! Expected: 04f40589814af28e821a61e13e92e9c19caba3d2
npm ERR! Actual:   7c806aa609df81e8efd897a80f083874775186ef
npm ERR! From:     https://registry.npmjs.org/react-color/-/react-color-1.3.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shiva/project/npm-debug.log
```

**Comment by KenanY** [comment] 2015-12-13 07:56
@seekshiva Could you see if running `npm cache clean` fixes this issue?

**Comment by seekshiva** [comment] 2015-12-13 09:03
No @KenanY. I still get the same error.

**Comment by Reinmar** [comment] 2015-12-13 17:56
Seems that I've got the same error here: https://github.com/npm/npm/issues/10804#issuecomment-164281759

I've reinstalled whole Node in the meantime and run `npm cache clean`. Nothing helped (actually, it's getting worse with every npm/Node upgrade :D).

**Comment by zkat** [comment] 2016-12-09 00:50
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:50 UTC
Labels: shasum, support
