### ISSUE TITLE
error:  install bower 

### ISSUE THREAD

**Issue by TatjanavonLemberg** [npm/npm#15335] opened 2016-12-28 16:48 UTC
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.

#### What's going wrong?

I thy to install bower using command

 npm install -g bower 

I get the error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchNamedPackageData bower
9 silly mapToRegistry name bower
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'bower',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'bower',
12 silly mapToRegistry   name: 'bower',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/bower
14 verbose request uri https://registry.npmjs.org/bower
15 verbose request no auth needed
16 info attempt registry request try #1 at 14:46:05
17 verbose request id db0b5a364b2f517e
18 http request GET https://registry.npmjs.org/bower
19 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
20 info attempt registry request try #2 at 14:46:15
21 http request GET https://registry.npmjs.org/bower
22 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
23 info attempt registry request try #3 at 14:47:15
24 http request GET https://registry.npmjs.org/bower
25 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
25 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
25 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
25 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
25 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
25 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
25 silly fetchPackageMetaData  error for bower Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
25 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
25 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
25 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
25 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
25 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
30 verbose stack     at Error (native)
30 verbose stack     at Object.createSecureContext (_tls_common.js:90:19)
30 verbose stack     at Object.exports.connect (_tls_wrap.js:1020:48)
30 verbose stack     at Agent.createConnection (https.js:82:22)
30 verbose stack     at Agent.createSocket (_http_agent.js:195:26)
30 verbose stack     at Agent.addRequest (_http_agent.js:157:10)
30 verbose stack     at new ClientRequest (_http_client.js:160:16)
30 verbose stack     at Object.exports.request (http.js:31:10)
30 verbose stack     at Object.exports.request (https.js:199:15)
30 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
31 verbose cwd C:\Users\D035787\DEV
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
34 error node v6.9.2
35 error npm  v3.10.9
36 error error:0906D06C:PEM routines:PEM_read_bio:no start line
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints:
3.10.9
 - `node -v` prints:
v 6.9.2
 - `npm config get registry` prints:
https://registry.npmjs.org
 - Windows 7
*************
configuration

```
npm config ls -l
; cli configs
long = true
user-agent = "npm/3.10.9 node/v6.9.2 win32 x64"

; userconfig C:\Users\D035787\.npmrc
foo:port = "80"
key = "value"
prefix = "C:\\Users\\D035787"

; globalconfig C:\Users\D035787\etc\npmrc
; prefix = "C:\\Users\\D035787\\AppData\\Roaming\\npm" (overridden)

; builtin config undefined
; prefix = "C:\\Users\\D035787\\AppData\\Roaming\\npm" (overridden)

; default values
access = null
also = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\D035787\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\D035787\\etc\\npmrc"
globalignorefile = "C:\\Users\\D035787\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\D035787\\.npm-init.js"
init-version = "1.0.0"
json = false
; key = null (overridden)
legacy-bundling = false
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
maxsockets = 50
message = "%s"
node-version = "6.9.2"
npat = false
onload-script = null
only = null
optional = true
parseable = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
progress = true
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "C:\\Users\\D035787\\AppData\\Local\\Temp"
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overri
dden)
userconfig = "C:\\Users\\D035787\\.npmrc"
version = false
versions = false
viewer = "browser"
```

Thanks and best regards,
Tatjana

**Comment by legodude17** [comment] 2016-12-29 08:50
Duplicate of #14726. See [this comment](https://github.com/npm/npm/issues/14726#issuecomment-264370861).

**Closed** 2017-06-18 10:38 UTC
Labels: bot-closed
