### ISSUE TITLE
npm  start 报错

### ISSUE THREAD

**Issue by yumenglong** [npm/npm#12101] opened 2016-03-28 06:45 UTC
```
G:\xampphtdocs\LFFworkSpace\flux-master>npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\program files\\nodejs\\node.exe" "G:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\xampphtdocs\LFFworkSpace\flux-master\npm-debug.log
```

**Comment by watilde** [comment] 2016-03-28 10:47
Hi yumenglong, can you show me the result of `npm run`? The error is missing script so I guess the problem is inside the script field in `package.json`.

**Comment by othiym23** [comment] 2016-04-12 05:43
As @watilde says, to use `npm start`, you must have a `"start"` script defined in the `"scripts"` section of `package.json`. Follow the links he includes, and the documentation will show you what to do. Closing as resolved.

**Closed by othiym23** 2016-04-12 05:43 UTC
Labels: support, windows
