### ISSUE TITLE
Receiving 404 Error

### ISSUE THREAD

**Issue by ScottTradepost** [npm/npm#17763] opened 2017-07-13 13:19 UTC
This just started happening within the last week, and now I'm unable to get any builds to work on the windows machine. 

Can you give me a hand to figure out what I need to change? I've already tried updating Node, and CLI. 

I've attached the debug log, and here is the output:

Running with gitlab-ci-multi-runner 9.3.0 (3df822b)
  on CDTP (73d2fd89)
Using Shell executor...
Running on CDTP...
Fetching changes...
Removing npm-debug.log
HEAD is now at c3b5d95 Setting it up to look at a value from the web.config to change an order to 'hold' if it's over a certain amount. this should help with large fraudulent orders.
error: cannot lock ref 'refs/remotes/origin/45-on-the-store-s-order-page-there-is-not-an-indicator-on-whether-they-have-an-item-in-stock-or-not-store-employees-are-searching-for-items-that-are-not-in-stock-at-their-store': Unable to create 'C:/GitLab/builds/73d2fd89/0/tradepostentertainment/Website/.git/refs/remotes/origin/45-on-the-store-s-order-page-there-is-not-an-indicator-on-whether-they-have-an-item-in-stock-or-not-store-employees-are-searching-for-items-that-are-not-in-stock-at-their-store.lock': Filename too long
From https://gitlab.com/tradepostentertainment/Website
 ! [new branch]      45-on-the-store-s-order-page-there-is-not-an-indicator-on-whether-they-have-an-item-in-stock-or-not-store-employees-are-searching-for-items-that-are-not-in-stock-at-their-store -> origin/45-on-the-store-s-order-page-there-is-not-an-indicator-on-whether-they-have-an-item-in-stock-or-not-store-employees-are-searching-for-items-that-are-not-in-stock-at-their-store  (unable to update local ref)
Checking out c3b5d951 as 121-need-to-add-a-new-status-field-to-hold-an-order...
Skipping Git submodules setup
$ call npm install
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitLab\builds\73d2fd89\0\tradepostentertainment\Website\npm-debug.log
ERROR: Job failed: exit status 1

[npm-debug.zip](https://github.com/npm/npm/files/1145266/npm-debug.zip)

**Comment by kenany** [comment] 2017-07-13 15:10
dupe of https://github.com/npm/npm/issues/17723

**Closed as completed by kenany** 2017-07-13 15:10 UTC
Labels: support
