### ISSUE TITLE
Error: uid must be an unsigned int

### ISSUE THREAD

**Issue by herrbischoff** [npm/npm#14057] opened 2016-09-23 16:36 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Running `sudo npm update -g` produces the following error:

```
$ sudo npm update -g
npm ERR! Darwin 16.0.0
npm ERR! argv "/opt/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mbischoff/npm-debug.log
```

#### How can the CLI team reproduce the problem?

See above for command run and environment.

npm-debug.log: https://gist.github.com/herrbischoff/53bcf9f0a3e58c7be1dabe0525add535

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ChuckGoehring** [comment] 2016-09-23 17:29
I get same error with this command:   sudo npm install -g node-inspector   First time trying debug on this newly instlled version of node.   This command sent it into a loop.  Output of loop is:

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.8


I'm dead in the water without debugging.

**Comment by KenanY** [comment] 2016-09-23 17:57
See https://github.com/npm/npm/issues/14047#issuecomment-249099655. Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-23 17:57 UTC
