### ISSUE TITLE
执行npm install --save react npm install --save react-dom  npm install --save-dev webpack 　的时候遇到以下错误

### ISSUE THREAD

**Issue by wuxia510** [npm/npm#15857] opened 2017-02-24 07:22 UTC
Is this ok? (yes) yes

D:\myreact>npm install --save react
myreact@1.0.0 D:\myreact
`-- react@15.4.2

npm WARN myreact@1.0.0 No repository field.

D:\myreact>npm install --save react-dom
myreact@1.0.0 D:\myreact
`-- react-dom@15.4.2

npm WARN myreact@1.0.0 No repository field.

D:\myreact>npm install --save-dev webpack
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Fil
node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "webpack"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Tem
e496a53\registry.npmjs.org\pako\-\pako-0.2.9.tgz
npm ERR! Expected: f3f7522f4ef782348da8161bad9ecfd51bf83a75
npm ERR! Actual:   d4e22a9f107defe26c24f8888dba314887bf91f8
npm ERR! From:     https://registry.npmjs.org/pako/-/pako-0.2.9.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by bsc1780** [comment] 2017-02-24 14:41
Dont eory i got it

**Comment by legodude17** [comment] 2017-02-24 22:14
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-17 04:03 UTC
Labels: bot-closed
