### ISSUE TITLE
NPM 3.3.3: Unable to `npm install zookeeper`

### ISSUE THREAD

**Issue by swsnider** [npm/npm#9713] opened 2015-09-22 17:31 UTC
When I run `npm install zookeeper`, I get the following error:

```
swsnider@Silass-MacBook-Pro: node-zk-browser [master]× » npm install zookeeper                                                                                                                    [10:26:43]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install" "zookeeper"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/swsnider/.npm/zookeeper/3.4.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/swsnider/.npm/zookeeper/3.4.5/package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/swsnider/node-zk-browser/npm-debug.log
```

Interestingly, it downloaded zookeeper 3.4.6, but somehow still looks for 3.4.5?

I've attached the debug log as well:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'zookeeper' ]
2 info using npm@3.3.3
3 info using node@v4.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData zookeeper@>=3.4.1-4
8 silly fetchNamedPackageData zookeeper
9 silly mapToRegistry name zookeeper
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/zookeeper
13 verbose request uri https://registry.npmjs.org/zookeeper
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:26:46
16 verbose request id 43f4d1be0ffc7a29
17 verbose etag "7429D75VTGKVER6H2U8P8NF3L"
18 http request GET https://registry.npmjs.org/zookeeper
19 http 304 https://registry.npmjs.org/zookeeper
20 silly get cb [ 304,
20 silly get   { date: 'Tue, 22 Sep 2015 17:26:44 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     'cache-control': 'max-age=60',
20 silly get     etag: '"7429D75VTGKVER6H2U8P8NF3L"',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-bma7028-BMA',
20 silly get     'x-cache': 'HIT',
20 silly get     'x-cache-hits': '1',
20 silly get     'x-timer': 'S1442942804.067916,VS0,VE196',
20 silly get     vary: 'Accept' } ]
21 verbose etag https://registry.npmjs.org/zookeeper from cache
22 verbose get saving zookeeper to /Users/swsnider/.npm/registry.npmjs.org/zookeeper/.cache.json
23 silly install normalizeTree
24 silly loadCurrentTree Finishing
25 silly loadIdealTree Starting
26 silly install loadIdealTree
27 silly cloneCurrentTree Starting
28 silly install cloneCurrentTreeToIdealTree
29 silly cloneCurrentTree Finishing
30 silly loadShrinkwrap Starting
31 silly install loadShrinkwrap
32 silly loadShrinkwrap Finishing
33 silly loadAllDepsIntoIdealTree Starting
34 silly install loadAllDepsIntoIdealTree
35 silly resolveWithNewModule zookeeper@3.4.5 checking installable status
36 silly cache add args [ 'zookeeper@>=3.4.1-4', null ]
37 verbose cache add spec zookeeper@>=3.4.1-4
38 silly cache add parsed spec Result {
38 silly cache add   raw: 'zookeeper@>=3.4.1-4',
38 silly cache add   scope: null,
38 silly cache add   name: 'zookeeper',
38 silly cache add   rawSpec: '>=3.4.1-4',
38 silly cache add   spec: '>=3.4.1-4',
38 silly cache add   type: 'range' }
39 silly addNamed zookeeper@>=3.4.1-4
40 verbose addNamed ">=3.4.1-4" is a valid semver range for zookeeper
41 silly addNameRange { name: 'zookeeper', range: '>=3.4.1-4', hasData: false }
42 silly mapToRegistry name zookeeper
43 silly mapToRegistry using default registry
44 silly mapToRegistry registry https://registry.npmjs.org/
45 silly mapToRegistry uri https://registry.npmjs.org/zookeeper
46 verbose addNameRange registry:https://registry.npmjs.org/zookeeper not in flight; fetching
47 verbose get https://registry.npmjs.org/zookeeper not expired, no request
48 silly addNameRange number 2 { name: 'zookeeper', range: '>=3.4.1-4', hasData: true }
49 silly addNameRange versions [ 'zookeeper',
49 silly addNameRange   [ '3.3.2-1',
49 silly addNameRange     '3.3.2-2',
49 silly addNameRange     '3.3.2-3',
49 silly addNameRange     '3.3.2-4',
49 silly addNameRange     '3.3.3-0',
49 silly addNameRange     '3.4.1',
49 silly addNameRange     '3.4.1-3',
49 silly addNameRange     '3.4.1-2',
49 silly addNameRange     '3.4.1-4',
49 silly addNameRange     '3.4.5',
49 silly addNameRange     '3.4.6',
49 silly addNameRange     '3.4.5-1',
49 silly addNameRange     '3.4.5-2',
49 silly addNameRange     '3.4.6-0',
49 silly addNameRange     '3.4.6-1',
49 silly addNameRange     '3.4.6-2',
49 silly addNameRange     '3.4.6-3',
49 silly addNameRange     '3.4.6-4',
49 silly addNameRange     '3.4.6-5',
49 silly addNameRange     '3.4.6-6',
49 silly addNameRange     '3.4.6-7',
49 silly addNameRange     '3.4.6-8' ] ]
50 silly addNamed zookeeper@3.4.6
51 verbose addNamed "3.4.6" is a plain semver version for zookeeper
52 silly cache afterAdd zookeeper@3.4.6
53 verbose afterAdd /Users/swsnider/.npm/zookeeper/3.4.6/package/package.json not in flight; writing
54 verbose afterAdd /Users/swsnider/.npm/zookeeper/3.4.6/package/package.json written
55 silly rollbackFailedOptional Starting
56 silly rollbackFailedOptional Finishing
57 silly runTopLevelLifecycles Starting
58 silly runTopLevelLifecycles Finishing
59 silly install printInstalled
60 verbose stack Error: Error extracting /Users/swsnider/.npm/zookeeper/3.4.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/swsnider/.npm/zookeeper/3.4.5/package.tgz'
60 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:276:10)
60 verbose stack     at emitOne (events.js:77:13)
60 verbose stack     at ReadStream.emit (events.js:169:7)
60 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
60 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
60 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
61 verbose cwd /Users/swsnider/node-zk-browser
62 error Darwin 14.5.0
63 error argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install" "zookeeper"
64 error node v4.1.0
65 error npm  v3.3.3
66 error code EREADFILE
67 error Error extracting /Users/swsnider/.npm/zookeeper/3.4.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/swsnider/.npm/zookeeper/3.4.5/package.tgz'
68 error If you need help, you may report this error at:
68 error     <https://github.com/npm/npm/issues>
69 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment] 2015-09-22 17:44
@swsnider Does `npm cache clean zookeeper` or `npm cache clean` help at all? Just a hunch of mine.

**Comment by swsnider** [comment] 2015-09-22 17:47
@KenanY No :(

**Comment by w3hacker** [comment] 2015-10-04 16:07
```cd ~/.npm/zookeeper/``` and ```mv 3.4.6 3.4.5```

**Comment by iarna** [comment] 2015-11-06 19:15
This is a known issue, and is a duplicate of #10057.

**Closed by iarna** 2015-11-06 19:15 UTC
