### ISSUE TITLE
shasum check failed if set registry when build docker image.

### ISSUE THREAD

**Issue by jaggerwang** [npm/npm#16398] opened 2017-04-20 13:19 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [y ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

If set registry to "https://registry.npm.taobao.org/", got the following error when build docker image. Without set registry, npm install is ok. And it's ok when log into a running docker container, set the same registry.
```
...
npm http fetch 200 https://registry.npm.taobao.org/react-tap-event-plugin/download/react-tap-event-plugin-2.0.1.tgz
npm http fetch 200 https://registry.npm.taobao.org/react-select/download/react-select-1.0.0-rc.3.tgz
npm ERR! Linux 3.13.0-106-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.3.0
npm ERR! npm v3.10.10
npm ERR! shasum check failed for /tmp/npm-7-7196df14/registry.npm.taobao.org/react-dom/download/react-dom-15.5.4.tgz
npm ERR! Expected: ba0c28786fd52ed7e4f2135fe0288d462aef93da
npm ERR! Actual: c00247b641ce86ea658c8d23a1f1254b70117886
npm ERR! From: https://registry.npm.taobao.org/react-dom/download/react-dom-15.5.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR! /app/npm-debug.log
Removing intermediate container 17ffb79fc833
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

The dockerfile is here.
```
FROM node:7.3.0
MAINTAINER wangjiajun@bicitech.cn

ENV TZ="/usr/share/zoneinfo/Asia/Shanghai"

RUN npm config set registry https://registry.npm.taobao.org/

COPY . /app/
WORKDIR /app
RUN npm install
RUN npm run build

VOLUME /data

EXPOSE 5000

CMD ["npm", "run", "deploy"]
```

#### How can the CLI team reproduce the problem?

Build docker image using the above dockerfile.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v7.3.0
 - `npm config get registry` prints: https://registry.npm.taobao.org/
 - Windows, OS X/macOS, or Linux?: Debian jessie
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [y ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-04-20 16:15
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-17 03:25 UTC
Labels: bot-closed
