### ISSUE TITLE
shasum check failed while creating hello world project for apigee 127

### ISSUE THREAD

**Issue by raj-3105** [npm/npm#10738] opened 2015-12-08 07:22 UTC
```
D:\Apigee-127>a127 project create hello-world
Copying files to D:\Apigee-127\hello-world...
creating: .npmignore
creating: README.md
creating: api\controllers\README.md
creating: api\controllers\hello_world.js
creating: api\helpers\README.md
creating: api\mocks\README.md
creating: api\swagger\swagger.yaml
creating: app.js
creating: config\README.md
creating: config\default.yaml
creating: deployments\.npmignore
creating: deployments\README.md
creating: package.json
creating: test\api\controllers\README.md
creating: test\api\controllers\hello_world.js
creating: test\api\helpers\README.md
Running 'npm install'...
npm
 ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"

npm ERR! node v4.2.2
npm ERR! npm  v2.14.7


npm ERR! shasum check failed for C:\Users\480257\AppData\Local\Temp\npm-13856-91d4cb07\registry.npmjs.org\rndm\-\rndm-1.1.1.tgz
npm ERR! Expected: efcef4374021f78b63de6226b5985120269d64f1
npm ERR! Actual:   131f2377a9b9023f1ee85c9965d3d0566cf1cba9
npm ERR! From:     http://registry.npmjs.org/rndm/-/rndm-1.1.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>


npm ERR! Please include the following file with any support request:
npm ERR!     D:\Apigee-127\hello-world\npm-debug.log

'npm install' failed. Please run 'npm install' from the project directory.
```

**Comment by zkat** [comment] 2016-12-09 00:50
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:50 UTC
Labels: support, windows
