### ISSUE TITLE
NPM crash on search

### ISSUE THREAD

**Issue by ranisalt** [npm/npm#13788] opened 2016-08-28 19:09 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Can't use search, first it issues an undefined property error, then a heap allocation fault and ends with SIGBART. npm allocates around 2GB memory before erroring after a few seconds.

#### How can the CLI team reproduce the problem?

It happened with two packages I tried, flow and sandra. `npm search <package>` breaks.

Here's a debug log: https://gist.github.com/ranisalt/1c0fc076039719baf34340caf44d852c
Here's an image of the crash: ![http://imgur.com/a/rcVpu](http://i.imgur.com/HYhRT9G.png)

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux 4.7.2 x86_64
 - Network issues:
   - Geographic location where npm was run: Santa Catarina, southern region of Brazil
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-08-28 19:27
I'm gonna close this as a duplicate of https://github.com/npm/npm/issues/12619. If I'm wrong I can reopen.

**Closed by KenanY** 2016-08-28 19:27 UTC

**Comment by ranisalt** [comment] 2016-08-28 20:07
@KenanY it's probably a duplicate, I just didn't find it amongst 2.3k open issues. Thanks!
