### ISSUE TITLE
Recommended way to login (adduser) from a script

### ISSUE THREAD

**Issue by nodesocket** [npm/npm#12283] opened 2016-04-08 23:17 UTC
Is there a way to provide the username and password without interactive?

    export $NPM_PASSWORD=pass1wd
    npm adduser --user nodesocket --password $NPM_PASSWORD

**Comment by KenanY** [comment] 2016-04-09 00:03
https://github.com/npm/npm/issues/12111#issuecomment-202497588?

**Comment by othiym23** [comment] 2016-04-11 21:07
Closing as duplicate of #12111.

**Closed by othiym23** 2016-04-11 21:07 UTC
Labels: feature-request
