### ISSUE TITLE
cannot install bower

### ISSUE THREAD

**Issue by kumbulanitshuma** [npm/npm#7660] opened 2015-03-17 18:15 UTC
i am trying to install bower and the is the errors i am getting
```
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/bower/node_modules/.bin'
npm ERR! error rolling back  bower@1.3.12 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/bower/node_modules/.bin']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/bower/node_modules/.bin' }
npm ERR! Error: No compatible version found: request@'^2.40.0'
npm ERR! Valid install targets:
npm ERR! ["0.10.0","0.8.3","0.9.0","0.9.1","0.9.5","1.0.0","1.1.0","1.1.1","1.2.0","1.9.0","1.9.1","1.9.2","1.9.3","1.9.5","1.9.7","1.9.8","1.9.9","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.1.0","2.1.1","2.2.0","2.2.5","2.2.6","2.2.9","2.9.0","2.9.1","2.9.2","2.9.3","2.9.100","2.9.150","2.9.151","2.9.152","2.9.153","2.9.200","2.9.201","2.9.202","2.9.203","2.10.0","2.11.0","2.11.1","2.11.2","2.11.3","2.11.4","2.12.0","2.14.0","2.16.0","2.16.2","2.16.4","2.16.6","2.18.0","2.19.0","2.20.0","2.21.0","2.22.0","2.23.0","2.24.0","2.25.0","2.26.0","2.27.0","2.28.0","2.29.0","2.30.0","2.31.0","2.32.0","2.33.0","2.34.0","2.35.0","2.36.0","2.37.0","2.38.0","2.39.0","2.40.0","2.41.0","2.42.0","2.43.0","2.44.0","2.45.0","2.46.0","2.47.0","2.48.0","2.49.0","2.50.0","2.51.0","2.52.0","2.53.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at RegClient.get_ (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.js:266:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! Error: ENOENT, open '/usr/local/lib/node_modules/bower/node_modules/mout/random.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/mout/random.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/bower/node_modules/semver'
File exists: /usr/local/lib/node_modules/bower/node_modules/semver
Move it away, and try again.

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/semver
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/semver/semver.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/bower/node_modules/decompress-zip/lib'
File exists: /usr/local/lib/node_modules/bower/node_modules/decompress-zip/lib
Move it away, and try again.

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/decompress-zip/lib
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/decompress-zip/lib/file-details.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/bower-json/test/test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/bower-json/test/test.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/bower-json/test/test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/bower/node_modules/cardinal/examples'
File exists: /usr/local/lib/node_modules/bower/node_modules/cardinal/examples
Move it away, and try again.

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/cardinal/examples
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/cardinal/examples/.cardinalrc
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/read
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/shell-quote/test/parse.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/shell-quote/test/parse.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/shell-quote/test/parse.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/local/lib/node_modules/bower/node_modules/retry/test/integration/test-retry-operation.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/retry/test/integration/test-retry-operation.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/retry/test/integration/test-retry-operation.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:222:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/fstream-ignore/test/read-file-order.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/fstream-ignore/test/read-file-order.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/fstream-ignore/test/read-file-order.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/prompts/checkbox.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/inquirer/lib/prompts/checkbox.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/inquirer/lib/prompts/checkbox.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/pump
npm http GET https://registry.npmjs.org/tar-stream
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/q/q.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/q/q.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/q/q.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/request/request.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/request/request.js
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/request/request.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bower/node_modules/handlebars/coverage/coverage.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root/node-v0.10.4
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/bower/node_modules/handlebars/coverage/coverage.json
npm ERR! fstream_path /usr/local/lib/node_modules/bower/node_modules/handlebars/coverage/coverage.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
```

how can i solve this issue

**Comment by KenanY** [comment] 2015-03-17 19:32
@kumbulanitshuma Your issue is caused by your version of `npm`... it is **years** old, and does not support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: request@'^2.40.0'
```

The solution is to [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

**Comment by smikes** [comment] 2015-05-03 10:08
Is this still a problem for you?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-05-20 03:34
Closing as resolved.

**Closed by othiym23** 2015-05-20 03:34 UTC
Labels: support
