### ISSUE TITLE
npm install -g ionic cordova Error

### ISSUE THREAD

**Issue by richardmarais** [npm/npm#15121] opened 2016-12-02 17:19 UTC
#### I'm opening this issue because:

Trying to install Ionic Cordova and I get an error.

#### What's going wrong?

Check sum failed.

http://stackoverflow.com/questions/40928345/install-ionic-cordova-error

#### How can the CLI team reproduce the problem?

Run:

npm install -g ionic cordova

### supporting information:

Node v7.2.0 and v6.9.1
OS X/macOS

**Comment by helio-frota** [comment] 2016-12-02 18:49
looks like a problem with Mac ?
2 hours ago I get it installed on linux:
https://github.com/npm/npm/issues/13375#issuecomment-264496618

**Comment by zkat** [comment] 2016-12-02 19:00
@richardmarais please post the full error, preferably putting up an `npm-debug.log`. There's nothing I can really comment on here.

**Comment by helio-frota** [comment] 2016-12-02 19:05
looks like a problem with Mac ?
2 hours ago I get it installed on linux:
https://github.com/npm/npm/issues/13375#issuecomment-264496618
alsto tested with npm 3.10.8

**Comment by ALCales** [comment] 2016-12-02 20:13
I have the same problem.

`npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\ales6\AppData\Local\Temp\npm-7800-abd8b2e6\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.11.0.tgz
npm ERR! Expected: 9214feb9dd713ca481a1cbabceeca60966c1c0cf
npm ERR! Actual:   db087505f3845d40e3702b8375bdcfb20c5a5968
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log`

**Comment by legodude17** [comment] 2016-12-02 21:45
Duplicate of #14626?

**Comment by zkat** [comment] 2016-12-09 00:31
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:31 UTC
Labels: support
