### ISSUE TITLE
Broken npm after updating to node 5.4.0 (Cannot find module 'brace-expansion')

### ISSUE THREAD

**Issue by franzip** [npm/npm#11088] opened 2016-01-08 13:06 UTC
I have installed Node and NPM installed with Homebrew.
After updating to Node 5.4.0 I have run: ```npm install npm -g; npm update -g```
This seems to have broken NPM:

```
$ node -v
v5.4.0

$ npm -v
3.5.4

$ npm install
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'brace-expansion'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/franzip/Sandbox/npm-debug.log

$ cat /Users/franzip/Sandbox/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.5.4
3 info using node@v5.4.0
4 verbose stack Error: Cannot find module 'brace-expansion'
4 verbose stack     at Function.Module._resolveFilename (module.js:326:15)
4 verbose stack     at Function.Module._load (module.js:277:25)
4 verbose stack     at Module.require (module.js:354:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minimatch/minimatch.js:10:14)
4 verbose stack     at Module._compile (module.js:398:26)
4 verbose stack     at Object.Module._extensions..js (module.js:405:10)
4 verbose stack     at Module.load (module.js:344:32)
4 verbose stack     at Function.Module._load (module.js:301:12)
4 verbose stack     at Module.require (module.js:354:17)
4 verbose stack     at require (internal/module.js:12:17)
5 verbose cwd /Users/franzip/Sandbox
6 error Darwin 14.5.0
7 error argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "install"
8 error node v5.4.0
9 error npm  v3.5.4
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'brace-expansion'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

$ cd ~/.npm
$ ls brace-expansion/1.1.2
npm-debug.log  package/       package.tgz
```

**Comment by WoodyWoodsta** [comment] 2016-01-08 13:14
Getting a similar error on npm v3.5.4 (node v5.4.0) after running `npm update -g` except the module not found is `npmlog`

For what it is worth:
```
$ npm -v
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/sean/.nvm/versions/node/v5.4.0/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/home/sean/.nvm/versions/node/v5.4.0/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by franzip** [comment] 2016-01-08 13:29
I got npm to work again by manually cloning the missing modules into ```/usr/local/lib/node_modules/```

**Comment by admorphit** [comment] 2016-01-08 22:19
Getting exact same error as @WoodyWoodsta- on node 5.4.0
How did this pass build tests?

**Comment by kgryte** [comment] 2016-01-08 22:36
I am getting the same error as @WoodyWoodsta for builds running on Travis Ci. For Node version `v5.4.0` and NPM `v3.5.4`, the module `npmlog` cannot be found. Builds were working for NPM `v3.5.3`. A regression appears to have happened somewhere.

**Comment by szines** [comment] 2016-01-09 02:15
Using `nvm` on mac, installed node 5.4, after updated npm with `npm update -g npm` to `3.5.4`.

Getting the same error as above.

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/szines/.nvm/versions/node/v5.4.0/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/Users/szines/.nvm/versions/node/v5.4.0/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

Solution was to remove the node folder and reinstall it.

```
rm -rf ~/.nvm/versions/node/v5.4.0/
nvm install 5.4
```

And don't update npm after. :)

**Comment by kgryte** [comment] 2016-01-09 02:20
@szines Seems like an odd workaround, given that this problem is not encountered for NPM version `<= 3.5.3` running on Node `v5.4.0`.

**Comment by szines** [comment] 2016-01-09 02:36
@kgryte Thanks, brilliant... `npm install -g npm@3.5.3` is working smoothly. :+1:  :-)

**Comment by ActionScripted** [comment] 2016-01-14 15:54
@kgryte, @szines: +1, thanks! `npm install -g npm@3.5.3` worked like a charm and I'll just hold on updating things.

**Comment by JeanPerriault** [comment] 2016-01-18 14:30
Hi all, not sure to understand. How can you run this ```npm install -g npm@3.5.3``` command while npm is broken?

**Comment by kgryte** [comment] 2016-01-18 18:31
@JeanPerriault Node does not come already preloaded with `npm@3.5.4`, you have to upgrade to it. The version of NPM bundled installed with Node works fine. You can upgrade to whatever version you want from this working version. The problem arises when you upgrade to the latest available `npm`, which is when things start breaking.

**Comment by JeanPerriault** [comment] 2016-01-19 14:00
@kgryte Yes I fully agree. My point is that it looks impossible to downgrade npm with ```npm install -g npm@3.5.3``` after upgrading to ```npm@3.5.4``` because ```npm``` command doesn't work anymore. (@szines / @ActionScripted: is there a step I didn't get? how did you make that thing work?)

**Comment by dcwarwick** [comment] 2016-01-19 14:43
@JeanPerriault You're correct that it will be difficult to downgrade npm once '''npm''' command is broken. There are two options:
* Use nuclear option to remove and reinstall node 5.4.x, complete with accompanying version of npm. Then, if you want to update your npm, use '''npm install -g npm@3.5.3''' instead of '''npm install -g npm''', so as to avoid running off the edge of the cliff again.
* When '''npm''' command is broken, use another version of npm (for example, if you are using nvm, you could load up a different version of node), change directory to the node_modules folder for your node 5.4.x version, and use the other version of npm to run '''npm install -g npm@3.5.3''' to place npm 3.5.3 in place of the broken version.
I hope this helps.

**Comment by JeanPerriault** [comment] 2016-01-19 15:10
Ok thanks @dcwarwick, I'll give it a try asap. I'm not familiar with nvm, it will be a great exercise. 
By the way, I'm under the impression that it is frequent to have several node installations (I'm not a huge fan of it, I fear it will add complexity and increase dependency hell), is there a specific reason for that?
Finally does anybody know if there are any investigation to address that 3.5.4 npm (or npmlog or other..) issue? I didn't find it.. thx

**Comment by mikkeloscar** [comment] 2016-01-19 17:48
I have investigated a bit. This happens if you go from `npm 3.3.12` (current version provided with node 5.4.1) to `npm 3.5.4`. However if you first install `npm 3.5.3` as described in the other comments here, and THEN install `npm 3.5.4` (`npm install -g npm@3.5.4` or `npm install -g npm@next`), then it seems to work.

I think the problem is that `/usr/lib/node_modules/npm/node_modules/npmlog/` doesn't include a `package.json` file after you update from `3.3.12` to `3.5.4`, but it does if you go from `3.3.12` to `3.5.3` to `3.5.4`. Why it gets deleted when going from `3.3.12` to `3.5.4` I don't know?

**Comment by mikkeloscar** [comment] 2016-01-19 19:33
I did a psuedo bisect of the problem using this script https://gist.github.com/mikkeloscar/b45e2584a0c125cfd754 .

It turns out the problem was introduced in 5b820c4. Reverting this commit solves the problem, but I doubt that is the correct solution.

**Comment by iarna** [comment] 2016-01-19 21:16
@mikkeloscar Yeah, check out #11129

**Comment by iarna** [comment] 2016-01-19 21:18
The plan is:

1. We're not going to promote 3.5.4 to latest.
2. This week, 3.5.3 will remain latest and 3.5.5 become next. 3.5.5 will come with the fix for this. Next week 3.5.5 will become latest.

**Comment by heqian** [comment] 2016-01-19 22:58
It's interesting that when I run `npm show npm`, it shows:
```js
{
...,
'dist-tags': 
   { latest: '3.5.3',
     next: '3.5.4',
     'latest-2': '2.14.14',
     'v3.x-latest': '3.5.3',
     '3.x-latest': '3.5.3',
     '3.x-next': '3.5.4',
     'v3.x-next': '3.5.4',
     'next-2': '2.14.15',
     'latest-1': '1.4.29',
     lts: '2.14.14' },
versions:
  [
    ...,
    '3.5.3',
    '3.5.4'
  ],
...
}
```
According to NPM document (https://docs.npmjs.com/cli/update), `npm update`, "This command will update all the packages listed to the **latest version** (specified by the tag config), respecting semver."

However, the actual behavior of this command is to update to **`next`** version, or the last item in the array **`versions`**.

I don't know if I missed any information here.

**Comment by kgryte** [comment] 2016-01-20 20:30
@heqian Yeah, for whatever reason, `npm` is installing `next` rather than `latest` (which is not the behavior discussed in the [docs](https://docs.npmjs.com/cli/update#updating-globally-installed-packages)), so even the plan mentioned by @iarna fails to stop builds from failing due to running `npm -g update npm`.

**Comment by heqian** [comment] 2016-01-21 19:11
@kgryte @iarna When I ran **`npm outdated -g`**, I got "Wanted: 3.5.4" and "Latest: 3.5.3".

So, I took a look of how NPM's **`outdated`** function (`npm/lib/outdated.js`) and **`update`** function (`npm/lib/update.js`) work.

The **`update`** function calls **`outdated`** function to get the "current" version, "wanted" version, and "latest" version of a given npm package. And then, the `update` function will update the package to the "wanted" version if it is not equal to "current".

I think the problem is in the **`outdated`** function (https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/outdated.js), which returns an array of package's metadata.

**Comment by ashleygwilliams** [comment] 2016-02-06 18:22
this was solved with npm `3.5.5`. closing.

**Closed by ashleygwilliams** 2016-02-06 18:22 UTC
Labels: support

**Comment by verpixelt** [comment] 2016-04-26 15:13
I'm running `node v5.11.0` and `npm 3.8.7` and I get the following error
```
module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by krotscheck** [comment] 2016-05-18 16:48
A similar issue appears to be impacting the ubuntu world: https://bugs.launchpad.net/ubuntu/+source/npm/+bug/1583252

**Comment by artuska** [comment] 2016-05-18 21:30
I have `npm@3.9.0` and I have the same issue — `Error: Cannot find module 'brace-expansion'`

**Comment by FredericHeem** [comment] 2016-06-15 13:13
@artuska: same issue here with `npm@3.9.3` and `node@6.2.1`, have you find a solution ?

**Comment by artuska** [comment] 2016-06-15 13:24
@FredericHeem I just installed some modules separately (not with `npm install` into your project directory but `npm install -g node-sass`) and with `-g` parameter. As I remember I've installed `node-sass` and... ufff... cannot remember, maybe some other library, but I'm sure `node-sass` was the main reason of the errors in my above comment.

**Comment by don4of4** [comment] 2016-07-05 13:12
Same issue with `npm@3.9.5`

**Comment by zhixia** [comment] 2016-07-29 10:56
Same issue with node@6.2.0 and npm@3.3.12

**Comment by vennsoh** [comment] 2016-08-06 04:46
Same for node 6.3.1, npm 3.10.3

**Comment by piyushmanurkar** [comment] 2018-02-19 17:45
Same for node 8.9.4, npm 5.6.0
