### ISSUE TITLE
Error npm install bcrypt-as-promised im using windows 8.1

### ISSUE THREAD

**Issue by Ingosmar89219** [npm/npm#15418] opened 2017-01-06 19:22 UTC
C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm install bcrypt-
as-promised --save
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\osmarvirux\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt-as-prom
ised" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for C:\Users\OSMARV~1\AppData\Local\Temp\npm-6040-8
71a3f77\registry.npmjs.org\nan\-\nan-2.3.5.tgz
npm ERR! Expected: 822a0dc266290ce4cd3a12282ca3e7e364668a08
npm ERR! Actual:   82b23db6e6d2dc41d06c94673fdb24126357ba32
npm ERR! From:     https://registry.npmjs.org/nan/-/nan-2.3.5.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\npm-de
bug.log

**Comment by Charlotteis** [comment] 2017-01-06 23:34
Hi! This is a duplicate of #14620.

Please update your version of npm

```
npm install -g npm@latest
```

Thanks! 🌸

**Comment by Ingosmar89219** [comment] 2017-01-07 04:21
i did it but doesn't work just update npm but doesn't work bro please help me. 

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm install bcrypt-
as-promised --save
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt-as-promised" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.5 <------- update npm version but doesn't work
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\npm-de
bug.log

**Comment by Charlotteis** [comment] 2017-01-07 13:19
I am most definitely not a bro :)

The first problem you had was fixed. Now it looks like you might be behind a proxy, and thus need to make sure it is configured properly: https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by Ingosmar89219** [comment] 2017-01-07 20:33
im sorry my sister hehe! I did you said me but i got this error please help:( me im a little noob yet with npm hehe. 
C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm config set prox
y http://proxy.company.com:8080

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm config set http
s-proxy http://proxy.company.com:8080

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm install bcrypt-
as-promised --save
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt-as-promised" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.5
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ETIMED
OUT 74.122.238.10:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\npm-de
bug.log

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm help config

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>

My npm.config.html

<!doctype html>
<html>
  <title>npm-config</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="../../static/style.css">
  <link rel="canonical" href="https://www.npmjs.org/doc/cli/npm-config.html">
  <script async=true src="../../static/toc.js"></script>

  <body>
    <div id="wrapper">

<h1><a href="../cli/npm-config.html">npm-config</a></h1> <p>Manage the npm configuration files</p>
<h2 id="synopsis">SYNOPSIS</h2>
<pre><code>npm config set &lt;key&gt; &lt;value&gt; [-g|--global]
npm config get &lt;key&gt;
npm config delete &lt;key&gt;
npm config list
npm config edit
npm get &lt;key&gt;
npm set &lt;key&gt; &lt;value&gt; [-g|--global]

aliases: c
</code></pre><h2 id="description">DESCRIPTION</h2>
<p>npm gets its config settings from the command line, environment
variables, <code>npmrc</code> files, and in some cases, the <code>package.json</code> file.</p>
<p>See <a href="../files/npmrc.html">npmrc(5)</a> for more information about the npmrc files.</p>
<p>See <code><a href="../misc/npm-config.html">npm-config(7)</a></code> for a more thorough discussion of the mechanisms
involved.</p>
<p>The <code>npm config</code> command can be used to update and edit the contents
of the user and global npmrc files.</p>
<h2 id="sub-commands">Sub-commands</h2>
<p>Config supports the following sub-commands:</p>
<h3 id="set">set</h3>
<pre><code>npm config set key value
</code></pre><p>Sets the config key to the value.</p>
<p>If value is omitted, then it sets it to &quot;true&quot;.</p>
<h3 id="get">get</h3>
<pre><code>npm config get key
</code></pre><p>Echo the config value to stdout.</p>
<h3 id="list">list</h3>
<pre><code>npm config list
</code></pre><p>Show all the config settings.</p>
<h3 id="delete">delete</h3>
<pre><code>npm config delete key
</code></pre><p>Deletes the key from all configuration files.</p>
<h3 id="edit">edit</h3>
<pre><code>npm config edit
</code></pre><p>Opens the config file in an editor.  Use the <code>--global</code> flag to edit the
global config.</p>
<h2 id="see-also">SEE ALSO</h2>
<ul>
<li><a href="../files/npm-folders.html">npm-folders(5)</a></li>
<li><a href="../misc/npm-config.html">npm-config(7)</a></li>
<li><a href="../files/package.json.html">package.json(5)</a></li>
<li><a href="../files/npmrc.html">npmrc(5)</a></li>
<li><a href="../cli/npm.html">npm(1)</a></li>
</ul>

</div>

<table border=0 cellspacing=0 cellpadding=0 id=npmlogo>
<tr><td style="width:180px;height:10px;background:rgb(237,127,127)" colspan=18>&nbsp;</td></tr>
<tr><td rowspan=4 style="width:10px;height:10px;background:rgb(237,127,127)">&nbsp;</td><td style="width:40px;height:10px;background:#fff" colspan=4>&nbsp;</td><td style="width:10px;height:10px;background:rgb(237,127,127)" rowspan=4>&nbsp;</td><td style="width:40px;height:10px;background:#fff" colspan=4>&nbsp;</td><td rowspan=4 style="width:10px;height:10px;background:rgb(237,127,127)">&nbsp;</td><td colspan=6 style="width:60px;height:10px;background:#fff">&nbsp;</td><td style="width:10px;height:10px;background:rgb(237,127,127)" rowspan=4>&nbsp;</td></tr>
<tr><td colspan=2 style="width:20px;height:30px;background:#fff" rowspan=3>&nbsp;</td><td style="width:10px;height:10px;background:rgb(237,127,127)" rowspan=3>&nbsp;</td><td style="width:10px;height:10px;background:#fff" rowspan=3>&nbsp;</td><td style="width:20px;height:10px;background:#fff" rowspan=4 colspan=2>&nbsp;</td><td style="width:10px;height:20px;background:rgb(237,127,127)" rowspan=2>&nbsp;</td><td style="width:10px;height:10px;background:#fff" rowspan=3>&nbsp;</td><td style="width:20px;height:10px;background:#fff" rowspan=3 colspan=2>&nbsp;</td><td style="width:10px;height:10px;background:rgb(237,127,127)" rowspan=3>&nbsp;</td><td style="width:10px;height:10px;background:#fff" rowspan=3>&nbsp;</td><td style="width:10px;height:10px;background:rgb(237,127,127)" rowspan=3>&nbsp;</td></tr>
<tr><td style="width:10px;height:10px;background:#fff" rowspan=2>&nbsp;</td></tr>
<tr><td style="width:10px;height:10px;background:#fff">&nbsp;</td></tr>
<tr><td style="width:60px;height:10px;background:rgb(237,127,127)" colspan=6>&nbsp;</td><td colspan=10 style="width:10px;height:10px;background:rgb(237,127,127)">&nbsp;</td></tr>
<tr><td colspan=5 style="width:50px;height:10px;background:#fff">&nbsp;</td><td style="width:40px;height:10px;background:rgb(237,127,127)" colspan=4>&nbsp;</td><td style="width:90px;height:10px;background:#fff" colspan=9>&nbsp;</td></tr>
</table>
<p id="footer">npm-config &mdash; npm@4.0.5</p>

**Comment by Ingosmar89219** [comment] 2017-01-07 22:05
hey sister!! i could solucionate the error BUT im getting this error right now 

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm config set prox
y null npm config set https-proxy null

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm install bcrypt-
as-promised --save

> bcrypt@0.8.7 install C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayme
nts\node_modules\bcrypt
> node-gyp rebuild


C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\node_modules\bcrypt
>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  el
se (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform
Toolset = 'v100') cannot be found. To build using the v100 build tools, either
click the Project menu or right-click the solution, and then select "Update VC+
+ Projects...". Install Visual Studio 2010 to build using the Visual Studio 201
0 build tools. [C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\no
de_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\node_m
odules\bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt-as-promised" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\npm-de
bug.log

**Comment by legodude17** [comment] 2017-01-09 23:10
It looks like you have to install Visual Studio 2010 so you can build the package bcrypt...

**Comment by KenanY** [comment] 2017-02-03 13:10
Closing as abandoned.

**Closed by KenanY** 2017-02-03 13:10 UTC
