### ISSUE TITLE
npm is giving me alot of errors when trying to run code with it

### ISSUE THREAD

**Issue by deep12154** [npm/npm#16507] opened 2017-05-03 13:23 UTC
Im trying to build an amazon echo using a raspberry pi for a school project. when i run the code cd ~/Desktop/alexa-avs-sample-app/samples and then cd companionService && npm start it gives me this: 

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService

node ./bin/www
This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:340
throw err;
^
Error: Cannot find module 'express'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: node ./bin/www
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./bin/www
npm ERR! You can get their info via:
npm ERR! npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by deep12154** [comment] 2017-05-03 13:28
Im trying to build an amazon echo using a raspberry pi for a school project. when i run the code cd ~/Desktop/alexa-avs-sample-app/samples and then cd companionService && npm start it gives me this: > alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.


module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment] 2017-05-03 17:19
Looks like you forgot to run `npm install` from within the project directory. You are missing at least one dependency of the project, so the solution would be to `npm install` them.

Also, I should note that the version of `npm` you are using is at least a year old now and is no longer supported. This isn't the cause of your issue now, but if you run into further issues you would be better off updating `npm` in order to get dozens of existing bug fixes.

**Comment by deep12154** [comment] 2017-05-05 13:08
KenanY I ran npm install and got more errors:

pi@raspberrypi:~ $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/pi/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by deep12154** [comment] 2017-05-05 13:11
@KenanY I ran npm install but I got more errors:

pi@raspberrypi:~ $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/pi/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

idk what is wrong so any help would be helpful

**Comment by KenanY** [comment] 2017-05-05 16:27
@deep12154 Try running `npm install` from the

```
/home/pi/Desktop/alexa-avs-sample-app/samples/companionService
```

directory.

**Comment by deep12154** [comment] 2017-05-09 13:15
@KenanY I ran it with that directory, but when I did it gave me a spinning slash for 5 mins and then this:

 npm ERR! Error: CERT_NOT_YET_VALID
npm ERR!     at SecurePair.<anonymous> (tls.js:1365:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:977:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:323:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:585:24)
npm ERR!     at flow (_stream_readable.js:594:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:626:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment] 2017-05-09 15:21
Is your system time configured correctly? The error messages makes it seem like your clock is behind the actual time.

**Comment by deep12154** [comment] 2017-05-11 13:23
@KenanY the time and date were not set correctly. I managed to get the correct date but the time is still about 4 hours behind the actual time. i have the time zone set to my nearest city, new york, im in the same time zone as new york but the time is still wrong. i ran npm install again anyway and got the same thing i think:

~/Desktop/alexa-avs-sample-app/samples $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/pi/Desktop/alexa-avs-sample-app/samples/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/Desktop/alexa-avs-sample-app/samples/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/npm-debug.log
npm ERR! not ok code 0

**Comment by deep12154** [comment] 2017-05-11 13:24
@KenanY the time and date were not set correctly. I managed to get the correct date but the time is still about 4 hours behind the actual time. i have the time zone set to my nearest city, new york, im in the same time zone as new york but the time is still wrong. i ran npm install again anyway and got the same thing i think:

~/Desktop/alexa-avs-sample-app/samples $ npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/pi/Desktop/alexa-avs-sample-app/samples/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/Desktop/alexa-avs-sample-app/samples/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment] 2017-05-11 14:43
As I said before (https://github.com/npm/npm/issues/16507#issuecomment-299511431), try running `npm install` from this directory:

```
/home/pi/Desktop/alexa-avs-sample-app/samples/companionService
```

**Comment by deep12154** [comment] 2017-05-15 13:12
thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash  mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by deep12154** [comment] 2017-05-15 13:14
@KenanY thank you for the help i got npm installed and it worked like it was supposed to. but i have another problem. i have to put in: cd javaclient && mvn exec:exec but when i do it says bash mvn command not found. i tried doing some of the things i did for npm like npm install but for mvn but it still doesnt work

**Comment by KenanY** [comment] 2017-05-15 15:27
Probably gotta install `maven`. Closing this since the `npm` bit has been resolved.

**Closed by KenanY** 2017-05-15 15:27 UTC
Labels: support
