### ISSUE TITLE
npm install opencv -g  error:Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by ningy1009** [npm/npm#9326] opened 2015-08-19 02:16 UTC
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program\\nodejs\\\\node.exe" "D:\\Program\\nodejs\\node_modul
es\\npm\\bin\\npm-cli.js" "install" "opencv" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for D:\Program\nodejs\tmp\npm-7340-c0e1b9c4\registr
y.npmjs.org\opencv\-\opencv-3.1.0.tgz
npm ERR! Expected: c4ee06cf49d85a2a301c966cfb2e43978e888290
npm ERR! Actual:   e44e1d1186224ea51aaacaee96f9f667375cfb4b
npm ERR! From:     https://registry.npmjs.org/opencv/-/opencv-3.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\npm-debug.log
```

**Comment by KenanY** [comment] 2015-08-19 21:38
@ningy1009 Have you tried `npm cache clean`?

**Comment by ningy1009** [comment] 2015-08-21 13:25
No, I'll try it, and I'll contact you, thank you.

**Comment by ningy1009** [comment] 2015-08-21 13:27
No, I'll try it, and I'll contact you, thank you.

**Comment by ningy1009** [comment] 2015-08-28 01:23
C:\Users\hp>npm install opencv -g
npm WARN installMany node-pre-gyp was bundled with opencv@3.0.0, but bundled pac
kage wasn't found in unpacked tree

> opencv@3.0.0 install D:\Program\nodejs\node_global\node_modules\opencv
> node-pre-gyp install --fallback-to-build

[opencv] Command failed: D:\Program\nodejs\node.exe --eval require('D:/Program/n
odejs/node_global/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-win32
-x64/opencv.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.

D:\Program\nodejs\node_global\node_modules\opencv\build\opencv\v3.0.0\Release\no
de-v14-win32-x64\opencv.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile

child_process: customFds option is deprecated, use stdio instead.
'pkg-config' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
gyp: Call to 'pkg-config --cflags "opencv >= 2.4.9"' returned exit status 1. whi
le trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Program\nodejs\node_modules\npm\
node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program\\nodejs\\node.exe" "D:\\Program\\nodejs\\node_modu
les\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=opencv" "-
-configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--
runtime=node" "--node_abi=node-v14" "--platform=win32" "--target_platform=win32"
 "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://n
ode-opencv.s3.amazonaws.com/" "--module_path=D:\\Program\\nodejs\\node_global\\n
ode_modules\\opencv\\build\\opencv\\v3.0.0\\Release\\node-v14-win32-x64" "--modu
le=D:\\Program\\nodejs\\node_global\\node_modules\\opencv\\build\\opencv\\v3.0.0
\\Release\\node-v14-win32-x64\\opencv.node" "--remote_path=./opencv/v3.0.0/Relea
se/" "--package_name=node-v14-win32-x64.tar.gz" "--staged_tarball=build\\stage\\
opencv\\v3.0.0\\Release\\node-v14-win32-x64.tar.gz" "--hosted_path=https://node-
opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-o
pencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-win32-x64.tar.gz"
gyp ERR! cwd D:\Program\nodejs\node_global\node_modules\opencv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Program\nodejs\node.exe D:\
Program\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js rebuild --
name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major
=3 --runtime=node --node_abi=node-v14 --platform=win32 --target_platform=win32 -
-arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-openc
v.s3.amazonaws.com/ --module_path=D:\Program\nodejs\node_global\node_modules\ope
ncv\build\opencv\v3.0.0\Release\node-v14-win32-x64 --module=D:\Program\nodejs\no
de_global\node_modules\opencv\build\opencv\v3.0.0\Release\node-v14-win32-x64\ope
ncv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-win32-x6
4.tar.gz --staged_tarball=build\stage\opencv\v3.0.0\Release\node-v14-win32-x64.t
ar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/
--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node
-v14-win32-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Program\nodejs\node_
global\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "D:\\Program\\nodejs\\node_global\\node_modules
\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-t
o-build"
node-pre-gyp ERR! cwd D:\Program\nodejs\node_global\node_modules\opencv
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute 'D:\Program\nodejs\node.exe D:\Program\nodejs\node_modules\npm
\node_modules\node-gyp\bin\node-gyp.js rebuild --name=opencv --configuration=Rel
ease --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=no
de-v14 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --m
odule_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_pa
th=D:\Program\nodejs\node_global\node_modules\opencv\build\opencv\v3.0.0\Release
\node-v14-win32-x64 --module=D:\Program\nodejs\node_global\node_modules\opencv\b
uild\opencv\v3.0.0\Release\node-v14-win32-x64\opencv.node --remote_path=./opencv
/v3.0.0/Release/ --package_name=node-v14-win32-x64.tar.gz --staged_tarball=build
\stage\opencv\v3.0.0\Release\node-v14-win32-x64.tar.gz --hosted_path=https://nod
e-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-o
pencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-win32-x64.tar.gz' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program\\nodejs\\\\node.exe" "D:\\Program\\nodejs\\node_modul
es\\npm\\bin\\npm-cli.js" "install" "opencv" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\npm-debug.log

C:\Users\hp>

**Comment by SeratFatima** [comment] 2015-10-06 16:21
Even I am getting the same error also tried clearing the cache but no help :(

**Comment by zkat** [comment] 2016-12-09 00:54
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:54 UTC
Labels: support, windows
