### ISSUE TITLE
package.json autoformatted when running jspm install

### ISSUE THREAD

**Issue by simonewebdesign** [npm/npm#9390] opened 2015-08-24 09:20 UTC
In our npm project we have ~30 lifecycle scripts defined in package.json, and we find useful to indent the lines, e.g.:

``` json
"scripts": {
  "build:js":      "jspm bundle-sfx source/app dist/app.js",
  "build:js:prod": "jspm bundle-sfx source/app dist/app.js --minify",

  "prebuild": "npm run clean",

  "build":      "npm run build:js      && npm run build:css      && npm run build:html",
  "build:prod": "npm run build:js:prod && npm run build:css:prod && npm run build:html:prod",
},
...
```

We add spaces in order to improve readability, and it makes a lot of difference for us. However, when we run `jspm install`, the package.json gets autoformatted, i.e. all the empty lines and extra spaces are automatically removed.

Is it possible to disable this feature?

**Comment by KenanY** [comment] 2015-08-24 11:24
@simonewebdesign I think you should open issues with `jspm` over at [jspm/jspm-cli](https://github.com/jspm/jspm-cli).

**Comment by simonewebdesign** [comment] 2015-08-24 13:50
I think it's actually related with npm, because the same thing happens also when I run `npm i --save package-name`.

**Comment by KenanY** [comment] 2015-08-24 14:55
@simonewebdesign Ah, so duplicate of https://github.com/npm/npm/issues/5694 perhaps?

**Comment by othiym23** [comment] 2015-08-24 20:46
@KenanY Indeed, it is. Closing as duplicate.

@simonewebdesign, this is a thing npm does, and it can't be disabled. When it makes changes to `package.json`, it rewrites the file using `JSON.stringify(pkg, null, 2)`. This is how npm has always worked, with the assumption that `package.json` is more a configuration file for npm than a user-maintained source file. As a way of lessening the sting for this as far as readability is concerned, I'll offer you this tip: did you know that `npm run-script` (with no other parameters) will print out a formatted list of all the lifecycle and package scripts in your `package.json`?

**Closed by othiym23** 2015-08-24 20:46 UTC
