### ISSUE TITLE
issue in npm install

### ISSUE THREAD

**Issue by priteec** [npm/npm#16553] opened 2017-05-06 20:22 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by priteec** [comment] 2017-05-06 20:23
C:\Users\Mahesh\Desktop\pritee\angular2-seed>npm install
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Mahesh\AppData\Local\Temp\npm-4684-76263dc8\registry.n
pmjs.org\to-string-loader\-\to-string-loader-1.1.5.tgz.3942683847' -> 'C:\Users\
Mahesh\AppData\Local\Temp\npm-4684-76263dc8\registry.npmjs.org\to-string-loader\
-\to-string-loader-1.1.5.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues

**Comment by wbhob** [comment] 2017-05-07 02:40
Please use the issue template, otherwise, we can't help you because we don't know how to reproduce.

**Comment by gao-pan** [comment] 2017-05-07 02:41
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /var/folders/yt/jwn4dzcd37gbff0b59tlx4hh0000gn/T/npm-498-8033b8fb/registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm ERR! Expected: 4de911e667b0eae9124e34254b53aea6fc618d3e
npm ERR! Actual:   4c3750785b3ced2fad220b42410acaad1c8828a5
npm ERR! From:     https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by wbhob** [comment] 2017-05-07 04:44
Yes, see that is an example of I have no idea what the problem is. Also seems like another issue, PLEASE USE THE TEMPLATE and open a new one. @gao-pan

**Comment by legodude17** [comment] 2017-05-09 18:01
This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:53 UTC
Labels: bot-closed, support
