### ISSUE TITLE
Could not install packages with bundledDependencies

### ISSUE THREAD

**Issue by monolithed** [npm/npm#14641] opened 2016-11-16 15:50 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.

#### What's going wrong?

```json
{
	"name": "@qa/npm-cache",
	"version": "0.0.1",

	"engines": {
		"node": ">=6.2",
		"npm": ">=3.8"
	},

	"bundledDependencies": [
		"git-info-sync",
		"debug",
		"fs-extra",
		"http-status",
		"request",
		"minimist",
		"tar-fs",
		"url-join"
	],

	"dependencies": {
		"git-info-sync": "^0.0.3",
		"debug": "^2.2.0",
		"fs-extra": "^1.0.0",
		"http-status": "^0.2.3",
		"request": "^2.76.0",
		"minimist": "^1.2.0",
		"tar-fs": "^1.5.2",
		"url-join": "^1.1.0"
	},

	"devDependencies": {
		"mocha": "3.1.2"
	}
}
```

```
➜ npm publish
```

```
➜ npm install
```

```
@qa/yoda-e.mail.ru@0.0.1 /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@qa/npm-cache"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! path /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/.staging/ansi-regex-1c385f6b
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/.staging/ansi-regex-1c385f6b' -> '/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/@qa/npm-cache/node_modules/ansi-regex'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/.staging/ansi-regex-1c385f6b' -> '/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/@qa/npm-cache/node_modules/ansi-regex'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/npm-debug.log
npm ERR! code 1
```

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v7.0.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Darwin

 - Network issues:
   - [x] I use a proxy to connect to the npm registry (own registry)

Maybe similar issue https://github.com/npm/npm/issues/10283

**Comment by kachkaev** [comment] 2016-11-17 11:35
I'm experiencing the same thing. Interesting. After temporarily removing `bundledDependencies` from package.json the error disappeared. The original log was:

```
$ npm install @company/package-with-bundled-deps --quiet
@company/gitlab-repo-name@0.3.0 /builds/gitlab-group-name/gitlab-repo-name
`-- (empty)

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@company/package-with-bundled-deps" "--quiet"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /builds/gitlab-group-name/gitlab-repo-name/node_modules/.staging/ms-97f7caed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/builds/gitlab-group-name/gitlab-repo-name/node_modules/.staging/ms-97f7caed' -> '/builds/gitlab-group-name/gitlab-repo-name/node_modules/@company/package-with-bundled-deps/node_modules/ms'
npm ERR! enoent ENOENT: no such file or directory, rename '/builds/gitlab-group-name/gitlab-repo-name/node_modules/.staging/ms-97f7caed' -> '/builds/gitlab-group-name/gitlab-repo-name/node_modules/@company/package-with-bundled-deps/node_modules/ms'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

Bundled dependencies in `@company/package-with-bundled-deps` included `bluebird`, `debug` and `semver` (if that helps).

**Comment by legodude17** [comment] 2016-11-17 17:27
Does it happen if you try to install a non-scoped package with bundled deps? `npm`, for example.

**Comment by kachkaev** [comment] 2016-11-17 17:48
@legodude17 I haven't tried this for non-scoped packages. Anyone?

**Comment by julien-f** [comment] 2016-11-23 10:58
Same issue here and it failed on a scoped package as well.

The package (which was generated with npm 3.10.8) looks fine but install fails on both npm 3.10.8 and 4.0.2 with Node 6.9.1 on Debian.

**Comment by julien-f** [comment] 2016-11-23 11:01
Looks like a duplicate of #12834 and #13619.

**Comment by julien-f** [comment] 2016-11-23 11:04
It works when the package is built with npm 3.10.6!

**Comment by legodude17** [comment] 2016-11-23 21:58
I think it is mostly #12834.

**Closed** 2017-06-19 04:16 UTC
Labels: big-bug, bot-closed, bug, needs-repro
