### ISSUE TITLE
Why does npm specify black background color? Consider removing background color?

### ISSUE THREAD

**Issue by ryancole** [npm/npm#15193] opened 2016-12-10 20:01 UTC
#### I'm opening this issue because:

npm is doing something I don't understand.

#### What's going wrong?

Why does `npm` specify a background color on its output? I understand the text being colored, but why a background color on certain elements? It looks like `npm` specifies black as the background color, but not all console windows have a black background. For example, look at this powershell console ...

![untitled](https://cloud.githubusercontent.com/assets/484801/21075802/e3c0d666-bee0-11e6-9ffa-c1bef63fe0e8.png)

Wouldn't it be much better to not specify a black background color at all?

#### How can the CLI team reproduce the problem?

Just install a dependency using a console that does not have a black background color.

### supporting information:

npm version 3.10.9, on Windows.

**Comment by KenanY** [comment] 2016-12-10 20:05
Duplicate of https://github.com/npm/npm/issues/10208?

**Comment by ryancole** [comment] 2016-12-10 20:09
> Duplicate of #10208?

Yup, appears to be.

**Closed** 2016-12-10 20:09 UTC
