### ISSUE TITLE
Missing script: start

### ISSUE THREAD

**Issue by DikshaDeo** [npm/npm#10809] opened 2015-12-14 09:27 UTC
w.r.t. https://github.com/npm/npm/issues/10177

Argument error: 8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start".

Seems like there is something missing in **npm-cli.js**

Files are attached, debug.txt and error output snapshot.

![npm-start](https://cloud.githubusercontent.com/assets/10798762/11777184/97c9783e-a272-11e5-86bf-b0f14367cd15.PNG)

**Comment by KenanY** [comment] 2015-12-14 18:26
@DikshaDeo What do you think is missing? Have you seen [my comment](https://github.com/npm/npm/issues/10177#issuecomment-152565138) on that issue?

**Comment by othiym23** [comment] 2015-12-16 21:52
As @KenanY suggests, this isn't a bug with npm itself, but instead a missing piece of configuration: `npm start` requires there to be a `"start"` key in the `"scripts"` section of `package.json`, or for there to be a file named `server.js` in the same directory of `package.json`. Since npm is working as intended here, I'm going to close this issue. You might find the documentation on [npm package scripts](https://docs.npmjs.com/misc/scripts#default-values) helpful. Good luck!

**Closed by othiym23** 2015-12-16 21:52 UTC
Labels: support
