### ISSUE TITLE
@angular/cli installetion problem by npm

### ISSUE THREAD

**Issue by ranacse** [npm/npm#16976] opened 2017-06-05 06:58 UTC
Hi,

i face problem in @angular/cli. then when i checked ng --version..its show local and global version not same.  then i got suggestion that i need to make both global and local same version b y using 
Global package:

npm uninstall -g @angular/cli
npm cache clean
npm install -g angular-cli@1.0.0-beta.21

Local project package:

rm -rf node_modules dist # use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell
npm install --save-dev angular-cli@1.0.0-beta.21
npm install

but when i try to uninstall @angular/cli..it show error
$ npm uninstall -g @angular/cli

Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:463:5
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Program Files\nodejs\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-06-05T06_46_33_259Z-debug.log
        

present 
$  ng --version                                                              
Your global Angular CLI version (1.0.0) is greater than your local           
version (1.0.0-rc.2). The local Angular CLI version is used.                 
                                                                             
To disable this warning use "ng set --global warnings.versionMismatch=false".
                                              
@angular/cli: 1.0.0-rc.2                                                     
node: 6.10.0                                                                 
os: win32 x64                                                                
@angular/animations: error                                                   
@angular/common: 2.4.9                                                       
@angular/compiler: 2.4.9                                                     
@angular/core: 2.4.9                                                         
@angular/forms: 2.4.9                                                        
@angular/http: 2.4.9                                                         
@angular/platform-browser: 2.4.9                                             
@angular/platform-browser-dynamic: 2.4.9                                     
@angular/router: 4.1.3                                                       
@angular/cli: 1.0.0-rc.2                                                     
@angular/compiler-cli: 2.4.9                                                 
                                                           
Please suggest.

**Comment by zkat** [comment] 2017-06-05 16:57
Closing as duplicate of https://github.com/npm/npm/issues/16738

**Closed as completed by zkat** 2017-06-05 16:57 UTC
Labels: npm5
