### ISSUE TITLE
npm ERR! errno: -4048, npm ERR! code: 'EPERM', npm ERR! in npm install

### ISSUE THREAD

**Issue by vidhimishra** [npm/npm#18441] opened 2017-09-07 15:34 UTC
Hi Everyone,

I am facing a very weired issue. I update my node version and when i did npm install in my repository, i am h=getting the error:

npm ERR! errno: -4048,
npm ERR! code: 'EPERM',
npm ERR! syscall: 'unlink',
npm ERR! path: 'C:\Vidhi\code\react-eon-de\eon-de-react\node_modules\fsevents\node_modules\node-pre-gyp\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

There is nothing wrong with the admin rights, and before updating node from 6.10 to 8 ,and npm from 3.10.10 to 5.4.0, it was working fine for me. I tried running the command in admin mode on command prompt in windows, but no luck.

Version: 5.4.0
Platform : 64-bit (Windows 10)
Subsystem : npm install -g

**Comment by robv8r** [comment] 2017-09-07 22:49
Possible duplicate of #18380

**Comment by marcins** [comment] 2017-09-08 13:15
Duplicate of #17671 - I have a lot of notes on my investigation of the issue there, and a potential fix in PR.

**Comment by OmarHegazi94** [comment] 2017-09-08 17:09
same error here and still no fix

**Comment by nicholasp** [comment] 2017-09-13 12:17
guys is there any fix yet??? i have 5.4.1 version should i go back? and if yes what version is the next stable for Win10??

**Closed as completed** 2017-09-15 00:42 UTC

**Comment by VisheshSingh** [comment] 2018-03-08 18:11
Try running the `npm install ` command as admin. I was dealing with the same issue and running the command as admin worked for me.
