### ISSUE TITLE
Updating npm has deleted/uninstalled global modules like gulp

### ISSUE THREAD

**Issue by Sheeryada** [npm/npm#10423] opened 2015-11-16 20:57 UTC
I updated my npm and then onwards gulp like commands are not working.

Trying install gulp like libraries shows below error,
```
$sudo npm install -g gulp
```

Error: 
Couldn't install optional dependency: No compatible version found: camelcase@^2.0.0

Also, I am facing the similar kind of errors with other global libraries like bower etc..

PS: 
-I am on mac OS - Yosemite

**Comment by schalivendri** [comment] 2015-11-16 21:06
Same issue here...
npm WARN install Couldn't install optional dependency: No compatible version found: camelcase@^2.0.0
npm WARN install Valid install targets:
npm WARN install 1.2.1, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 1.0.0
npm WARN install

**Comment by KenanY** [comment] 2015-11-16 21:09
Please post the output of `npm --version` and/or upload the _full_ `npm-debug.log` file to, for example, [gist.github.com](https://gist.github.com/). I can't be absolutely certain of what the issue is with just a few lines from an entire log.

**Comment by schalivendri** [comment] 2015-11-16 21:21
npm version: 3.4.0

**Comment by Sheeryada** [comment] 2015-11-16 21:27
@KenanY I am using npm version 3.4.1.. I don't find npm-debug.log on my finder not sure why. !

**Comment by KenanY** [comment] 2015-11-16 21:36
If anything I am confused as to why `npm` thinks that `camelcase` is an optional dependency when it actually isn't. In any case, I unfortunately cannot reproduce this:

``` sh
$ npm --version
3.4.1
$ npm install gulp
$ npm ls camelcase
/
└─┬ gulp@3.9.0
  └─┬ gulp-util@3.0.7
    └─┬ dateformat@1.0.11
      └─┬ meow@3.6.0
        └─┬ camelcase-keys@2.0.0
          └── camelcase@2.0.0 
```

**Comment by Sheeryada** [comment] 2015-11-16 21:45
@KenanY Thanks for trying..  I am not sure if this has something to do with mac OS version.

**Comment by mattgaspar** [comment] 2015-11-17 02:28
I just updated to npm 3.4.0 on Windows and it appears that the "-g" parameter doesn't work it just gets ignored!  Maybe this is the same issue on mac/linux as well?
Ex. The following command should update the global directory but it updated the main directory
npm config set prefix "${APPDATA}/npm" -g

**Comment by schalivendri** [comment] 2015-11-17 16:25
Gulp was installed in my local directory through I ran with `-g`.
 `npm config set prefix /usr/local` solved the issue for me.
more info [here](http://blog.webbb.be/command-not-found-node-npm/).

**Comment by KenanY** [comment] 2016-06-07 18:39
@Sheeryada Are you still seeing this issue with newer versions of `npm`?

**Comment by KenanY** [comment] 2016-06-28 19:51
Closing as abandoned and likely not an issue with `npm` anyways. If it can be demonstrated otherwise, we can reopen.

**Closed by KenanY** 2016-06-28 19:51 UTC
Labels: support
