### ISSUE TITLE
npm outdated -g hangs (v3.3.3)

### ISSUE THREAD

**Issue by JaKXz** [npm/npm#9698] opened 2015-09-21 19:24 UTC
I tried running `npm outdated -g` on version `2.14.5` (which works as expected) and `3.3.3`, both on node `4.1.0`.

**Comment by othiym23** [comment] 2015-09-21 20:31
`npm@3` is just really, really slow when running `npm outdated -g` right now (it takes about 17 minutes(!) on my top of the line Macbook Pro with an SSD). See #8826 for further discussion – improving its performance (starting with this exact problem, probably) is currently the team's highest priority. I'm going to close this as a duplicate of #8826, but belive me, I personally want this to improve _very urgently_.

**Closed by othiym23** 2015-09-21 20:31 UTC
Labels: support
