### ISSUE TITLE
NPM docs website shows wrong `last modified` date

### ISSUE THREAD

**Issue by jo-m** [npm/npm#21205] opened 2018-07-12 16:02 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other

#### What's going wrong?
Last modified date in docs is wrong, e.g. https://docs.npmjs.com/cli/ci shows `Last modified October 26, 1985`.

![Screenshot](https://user-images.githubusercontent.com/2587503/42645086-c22c567e-85c2-11e8-98df-518d642ff26c.png)
#### How can the CLI team reproduce the problem?
Go to https://docs.npmjs.com/cli/ci and scroll down.

**Comment by kenany** [comment] 2018-07-12 16:43
Duplicate of https://github.com/npm/npm/issues/21032, https://github.com/npm/docs/issues/990, https://github.com/npm/docs/issues/1013.

**Closed as completed by kenany** 2018-07-12 16:43 UTC
Labels: documentation
