### ISSUE TITLE
npm search with private npm repository fails in npm client versions 2.1.7+

### ISSUE THREAD

**Issue by OlgaoO** [npm/npm#7443] opened 2015-02-24 14:42 UTC
This is a problem in the newer versions of NPM (2.1.7+) with Private NPM repository - npm search doesn't work. 

Here is what defined in .npmrc:
registry=http://localhost:8081/artifactory/api/npm/repo

Starting npm client version 2.1.7 when performing ‘npm search’ , this pattern being broke down and the query sends the following request:
‘npm http request GET http://localhost:8081/-/all’ 
instead: 'npm http GET http://localhost:8081/artifactory/api/npm/repo/-/all'

With earlier npm versions < 2.1.7 - the request is working properly.

**Comment by smikes** [comment] 2015-02-24 21:25
Thanks for the bug report.

**Comment by othiym23** [comment] 2015-02-26 06:21
@OlgaoO Can you paste some output from running `npm -dd search`? I'm confused, because `npm search` should have been *fixed* by `npm@2.1.7` instead of broken, because that release switched to a new registry client API that was meant to deal with registry URLs with relative paths.

Does this problem still exist with `npm@latest` (`npm@2.6.0`)?

**Comment by OlgaoO** [comment] 2015-03-10 03:15
Hi @othiym23,
The output with the -dd is the same in in versions starting from @2.1.7 and also in the latest @2.6.0, the search doesn't work.

**Comment by destroyerofbuilds** [comment] 2015-03-25 17:07
I can confirm the behavior @OlgaoO experienced with an Artifactory setup.

I have the following `.npmrc` file that sets my registry to use a private Artifactory mirror of the public npm registry:

```
registry=http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/
```

I downgraded to `npm` version 2.1.6, as shown below:

```bash
(~)-()--> npm --version
2.1.6
```

I then ran a search as shown:

```bash
(~)-()--> npm search generator -dd
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/user/hbetts/.local/var/nvm/v0.10.37/bin/npm',
npm verb cli   'search',
npm verb cli   'generator',
npm verb cli   '-dd' ]
npm info using npm@2.1.6
npm info using node@v0.10.37
npm verb config Skipping project config: /home/user/hbetts/.npmrc. (matches userconfig)
npm verb mapToRegistry name -/all
npm verb mapToRegistry uri http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all
npm verb request on initialization, where is /artifactory/api/npm/npm/-/all
npm verb request after pass 1, where is /artifactory/api/npm/npm/-/all
npm verb request url raw /artifactory/api/npm/npm/-/all
npm verb request resolving registry [ 'http://<PRIVATE REGISTRY>/',
npm verb request   './artifactory/api/npm/npm/-/all' ]
npm verb request after pass 2, where is http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all
npm verb request no auth needed
npm info attempt registry request try #1 at 12:37:42
npm verb request id <REQUESTID>
npm http request GET http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all
npm http 200 http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all
```

Works great. Next I upgrade my version of npm:

```bash
(~)-()--> npm --version
2.7.3
```

And I ran the same search again:

```bash
(~)-()--> npm search generator -dd
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/user/hbetts/.local/var/nvm/v0.10.37/bin/npm',
npm verb cli   'search',
npm verb cli   'generator',
npm verb cli   '-dd' ]
npm info using npm@2.7.3
npm info using node@v0.10.37
npm verb config Skipping project config: /home/user/hbetts/.npmrc. (matches userconfig)
npm info updateIndex /home/user/hbetts/.npm/<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all/.cache.json
npm verb request uri http://<PRIVATE REGISTRY>/-/all/since?stale=update_after&startkey=1424195313631
npm verb request no auth needed
npm info attempt registry request try #1 at 12:43:25
npm verb request id <REQUESTID>
npm http request GET http://<PRIVATE REGISTRY>/-/all/since?stale=update_after&startkey=1424195313631
npm http 404 http://<PRIVATE REGISTRY>/-/all/since?stale=update_after&startkey=1424195313631
npm verb bad json <html><head><title>Apache Tomcat/7.0.56 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /-/all/since</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/-/all/since</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.56</h3></body></html>
npm ERR! registry error parsing json
npm verb headers { server: 'Apache-Coyote/1.1',
npm verb headers   'content-type': 'text/html;charset=utf-8',
npm verb headers   'content-language': 'en',
npm verb headers   'content-length': '973',
npm verb headers   date: 'Wed, 25 Mar 2015 16:43:25 GMT' }
npm verb type unexpected_token
npm verb stack SyntaxError: Unexpected token <
npm verb stack <html><head><title>Apache Tomcat/7.0.56 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /-/all/since</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/-/all/since</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.56</h3></body></html>
npm verb stack     at Object.parse (native)
npm verb stack     at CachingRegistryClient.<anonymous> (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
npm verb stack     at Request._callback (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
npm verb stack     at Request.self.callback (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/request/request.js:344:22)
npm verb stack     at Request.emit (events.js:98:17)
npm verb stack     at Request.<anonymous> (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/request/request.js:1239:14)
npm verb stack     at Request.emit (events.js:117:20)
npm verb stack     at IncomingMessage.<anonymous> (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/request/request.js:1187:12)
npm verb stack     at IncomingMessage.emit (events.js:117:20)
npm verb stack     at _stream_readable.js:944:16
npm verb cwd /home/user/hbetts
npm ERR! <LINUX>
npm ERR! argv "node" "/home/user/hbetts/.local/var/nvm/v0.10.37/bin/npm" "search" "generator" "-dd"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.3

npm ERR! Unexpected token <
npm ERR! <html><head><title>Apache Tomcat/7.0.56 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /-/all/since</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/-/all/since</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.56</h3></body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/hbetts/npm-debug.log
```

**Comment by othiym23** [comment] 2015-03-25 17:12
@destroyerofbuilds Can you run that with `-ddd` (one more d)? I would like to see how the registry URL is being resolved in this case, and for that I need `--loglevel=silly`.

**Comment by destroyerofbuilds** [comment] 2015-03-25 17:15
Looking into this a little more:

Line 73 of update-index.js: https://github.com/npm/npm/blob/master/lib/cache/update-index.js#L73
 
That's what's changing the URL. It's _resolving_ the URL using the `url` package.
 
The URL package documentation is here: https://www.npmjs.com/package/url#urlresolvefrom-to
 
Based on it's documentation, it's behaving as designed.
 
So, changing line 73 from:

```javascript
full = url.resolve(uri, "/-/all")
```

to

```
full = url.resolve(uri, "../-/all")
```

and changing line 76 from:

```javascript
full = url.resolve(uri, "/-/all/since?stale=update_after&startkey=" + t)
```

to

```javascript
full = url.resolve(uri, "../-/all/since?stale=update_after&startkey=" + t)
```

Causes `npm search` to work for the npm mirror registry.

**Comment by destroyerofbuilds** [comment] 2015-03-25 17:15
@othiym23, yep, one minute.

**Comment by destroyerofbuilds** [comment] 2015-03-25 17:24
@othiym23 

```
(~/.../lib/node_modules)-(git::master)--> npm search generator -ddd
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/user/hbetts/.local/var/nvm/v0.10.37/bin/npm',
npm verb cli   'search',
npm verb cli   'generator',
npm verb cli   '-ddd' ]
npm info using npm@2.7.3
npm info using node@v0.10.37
npm sill mapToRegistry name -/all
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/
npm sill mapToRegistry uri http://<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all
npm info updateIndex /home/user/hbetts/.npm/<PRIVATE REGISTRY>/artifactory/api/npm/npm/-/all/.cache.json
npm verb request uri http://<PRIVATE REGISTRY>/-/all/since?stale=update_after&startkey=1427303663288
npm verb request no auth needed
npm info attempt registry request try #1 at 13:19:06
npm verb request id <REQUESTID>
npm http request GET http://<PRIVATE REGISTRY>/-/all/since?stale=update_after&startkey=1427303663288
npm http 404 http://<PRIVATE REGISTRY>/-/all/since?stale=update_after&startkey=1427303663288
npm verb bad json <html><head><title>Apache Tomcat/7.0.56 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /-/all/since</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/-/all/since</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.56</h3></body></html>
npm ERR! registry error parsing json
npm verb headers { server: 'Apache-Coyote/1.1',
npm verb headers   'content-type': 'text/html;charset=utf-8',
npm verb headers   'content-language': 'en',
npm verb headers   'content-length': '973',
npm verb headers   date: 'Wed, 25 Mar 2015 17:19:06 GMT' }
npm verb type unexpected_token
npm verb stack SyntaxError: Unexpected token <
npm verb stack <html><head><title>Apache Tomcat/7.0.56 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /-/all/since</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/-/all/since</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.56</h3></body></html>
npm verb stack     at Object.parse (native)
npm verb stack     at CachingRegistryClient.<anonymous> (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
npm verb stack     at Request._callback (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
npm verb stack     at Request.self.callback (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/request/request.js:344:22)
npm verb stack     at Request.emit (events.js:98:17)
npm verb stack     at Request.<anonymous> (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/request/request.js:1239:14)
npm verb stack     at Request.emit (events.js:117:20)
npm verb stack     at IncomingMessage.<anonymous> (/home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm/node_modules/request/request.js:1187:12)
npm verb stack     at IncomingMessage.emit (events.js:117:20)
npm verb stack     at _stream_readable.js:944:16
npm verb cwd /home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules
npm ERR! Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! argv "node" "/home/user/hbetts/.local/var/nvm/v0.10.37/bin/npm" "search" "generator" "-ddd"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.3

npm ERR! Unexpected token <
npm ERR! <html><head><title>Apache Tomcat/7.0.56 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /-/all/since</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/-/all/since</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.56</h3></body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/hbetts/.local/var/nvm/v0.10.37/lib/node_modules/npm-debug.log
```

**Closed** 2015-03-25 19:42 UTC
Labels: bug
