### ISSUE TITLE
Cannot shrinkwarp with missing peer dependency

### ISSUE THREAD

**Issue by tgabi333** [npm/npm#10836] opened 2015-12-15 17:15 UTC
With npm 3.5.2

```
vagrant@packer-debian-7:/workspace/test$ npm install mongoose --save
test@1.0.0 /workspace/test
└─┬ mongoose@4.3.1 
  ├── async@0.9.0 
  ├── bson@0.4.19 
  ├── hooks-fixed@1.1.0 
  ├── kareem@1.0.1 
  ├─┬ mongodb@2.1.0 
  │ ├── es6-promise@3.0.2 
  │ ├── UNMET PEER DEPENDENCY kerberos@~0.0
  │ ├─┬ mongodb-core@1.2.26 
  │ │ └── bson@0.4.20 
  │ └─┬ readable-stream@1.0.31 
  │   ├── core-util-is@1.0.2 
  │   ├── inherits@2.0.1 
  │   ├── isarray@0.0.1 
  │   └── string_decoder@0.10.31 
  ├── mpath@0.1.1 
  ├── mpromise@0.5.4 
  ├─┬ mquery@1.6.3 
  │ ├── bluebird@2.9.26 
  │ └── debug@2.2.0 
  ├── ms@0.7.1 
  ├── muri@1.0.0 
  ├── regexp-clone@0.0.1 
  └── sliced@0.0.5 

npm WARN mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
vagrant@packer-debian-7:/workspace/test$ npm shrinkwrap
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "shrinkwrap"
npm ERR! node v0.12.9
npm ERR! npm  v3.5.2

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: kerberos@~0.0, required by mongodb-core@1.2.26
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/test/npm-debug.log
```

**Comment by simonstiphanos** [comment] 2015-12-30 02:38
I have the same issue, but this probably belongs in the mongoose forum...

**Comment by williamle8300** [comment] 2015-12-31 18:18
This issue is being tracked: https://github.com/npm/npm/issues/3066

**Comment by emgeee** [comment] 2016-01-13 00:28
I am having this same issue with npm v3.5.4 when installing [mongodb](https://github.com/mongodb/node-mongodb-native)

**Comment by emps** [comment] 2016-01-13 22:56
someone of npm plz fix this i dont wanna install modules just cause they are peer in other modules

**Comment by Spacelapp** [comment] 2016-01-30 14:12
Same here...

**Comment by szimek** [comment] 2016-03-16 14:01
I'm having this issue with `eslint-config-airbnb` package which defines `eslint` and `eslint-plugin-react` as its peer dependencies, but `eslint-plugin-react` is optional if one doesn't use React. I'm not using `eslint-plugin-react` in my project and I can't do `shrinkwrap --dev`, because of this error.

**Comment by kelsin** [comment] 2016-04-09 02:36
Same issue with globalize. We package our own cldr data instead of using the full package (for size reasons) but we can't shrinkwrap without installing the full (now optional) peer dependency.

**Comment by romseguy** [comment] 2016-05-25 07:58
This is not specific to any package, problem is the package maintainers sometimes do not keep the peer dependencies up to date, and we either can't shrinkwrap or update the peer dependencies anymore.

Example with my own project, I'm using react-formable package, which has ["react": "^0.14.0"](https://github.com/willowtreeapps/react-formable/blob/develop/package.json#L48) as peer dependency, but my project is using React 15 and until this [PR](https://github.com/willowtreeapps/react-formable/pull/76/files) is merged, I can't use shrinkwrap anymore. Hope that makes the issue clearer.

**Comment by benmosher** [comment] 2016-08-16 20:15
I have a similar case to @romseguy where I knowingly use React 14 even though a dependency declares it requires v13. It works fine in practice, and we are unable to upgrade that dependency as the next major revision represents a substantial set of breaking API changes.

I'd like to be able to `npm shrinkwrap --force` or something similar to accept the consequences of shrinkwrapping my (potentially invalid, but intentional) set of dependencies.

**Comment by alloy** [comment] 2016-08-24 15:08
As a stop-gap solution, I’m just hand-editing the `package.json` files of the deps that have those requirements and make them satisfy my preferred graph, after which I can run shrinkwrap just fine. Clearly not ideal, but better than nothing.

**Comment by bholloway** [comment] 2016-10-21 04:46
I work in a large, remote team. I am happy to perform the stop-gap solution (because I am the one adding the offending package). However I don't think the rest of the team will feel the same.

Frankly I am experiencing nothing but problems with `peerDependencies` as liberally used in the react ecosystem. That is not `npm`'s problem, but post `npm@3` I feel we should move on from the concept.

**Comment by isiahmeadows** [comment] 2016-12-07 10:49
Question: why can't `optionalDependencies` work? I thought that was designed for this use case.

**Comment by ramijarrar** [comment] 2016-12-24 04:30
@isiahmeadows They are pretty much useless without https://github.com/npm/npm/issues/14185

**Closed** 2017-06-16 23:42 UTC
Labels: bot-closed, peerdependencies, support
