### ISSUE TITLE
npm ls does not display shared dependencies correctly

### ISSUE THREAD

**Issue by ajcrites** [npm/npm#8691] opened 2015-06-26 06:52 UTC
`npm ls` does not seem to work as advertised

> `npm ls` now shows you your dependency tree organized around what requires what, rather than where those modules are on disk.

If you have a dependency that multiple modules depend on, `npm ls` will only show that as a dependency of one module.  If the dependency is a hard dependency of a module in the file system, it will still show, though.

For example:

    npm i --save connect

`npm ls` will show `parseurl@1.3.0` as a dependency of `connect`.

    └─┬ connect@3.4.0
      ├─┬ debug@2.2.0
      │ └── ms@0.7.1
      ├─┬ finalhandler@0.4.0
      │ ├── escape-html@1.0.2
      │ ├─┬ on-finished@2.3.0
      │ │ └── ee-first@1.1.1
      │ └── unpipe@1.0.0
      ├── parseurl@1.3.0
      └── utils-merge@1.0.0

    npm i --save parseurl

Now, `parseurl` shows as a top level dependency, but it does *not* show as a dependency of `connect`.

    ├─┬connect@3.4.0
    │ ├─┬ debug@2.2.0
    │ │ └── ms@0.7.1
    │ ├─┬ finalhandler@0.4.0
    │ │ ├── escape-html@1.0.2
    │ │ ├─┬ on-finished@2.3.0
    │ │ │ └── ee-first@1.1.1
    │ │ └── unpipe@1.0.0
    │ └── utils-merge@1.0.0
    └── parseurl@1.3.0

However you can still get `npm ls` to show it as a dependency of `connect` if you manipulate the file system such that `connect` has its own copy of parseurl.

    npm i --save parseurl@1.3.0
    ├─┬ connect@3.4.0
    │ └── parseurl@1.3.0 
    └── parseurl@1.0.0 

Now `npm ls` will show `parseurl@1.0.0` as a top level  dependency, but `parseurl@1.3.0` as a dependency of `connect.

    ├─┬ connect@3.4.0
    │ ├─┬ debug@2.2.0
    │ │ └── ms@0.7.1
    │ ├─┬ finalhandler@0.4.0
    │ │ ├── escape-html@1.0.2
    │ │ ├─┬ on-finished@2.3.0
    │ │ │ └── ee-first@1.1.1
    │ │ └── unpipe@1.0.0
    │ ├── parseurl@1.3.0
    │ └── utils-merge@1.0.0
    └── parseurl@1.0.0

Finally, you can get `parseurl@1.3.0` to show as a top level dependency *and* a dependency of connect with `npm i --save parseurl@1.3.0`

    ├─┬ connect@3.4.0
    │ ├─┬ debug@2.2.0
    │ │ └── ms@0.7.1
    │ ├─┬ finalhandler@0.4.0
    │ │ ├── escape-html@1.0.2
    │ │ ├─┬ on-finished@2.3.0
    │ │ │ └── ee-first@1.1.1
    │ │ └── unpipe@1.0.0
    │ ├── parseurl@1.3.0
    │ └── utils-merge@1.0.0
    └── parseurl@1.3.0

**Comment by iarna** [comment] 2015-06-26 20:37
This is by design, but I'm not sure I'm on board with the current behavior. I find it confusing too.

I'm flagging this as a `feature-request` so that we'll come back to it to discuss what we actually want `npm ls` to be doing. Particularly in light of `npm@3` where it no longer shows you what's on disk.

**Comment by othiym23** [comment] 2016-02-17 21:59
Closing this as a duplicate of #10984, which is currently being worked on. Thanks for filing this!

**Closed by othiym23** 2016-02-17 21:59 UTC
Labels: feature-request, support
