### ISSUE TITLE
Global package location on Windows [Discussion]

### ISSUE THREAD

**Issue by robertbaker** [npm/npm#10230] opened 2015-11-02 20:12 UTC
Currently NPM includes a `npmrc` file that tells npm to install global packages in `%appdata\npm`.
I'm guessing this was a way to remove the admin elevation requirement when installing global packages.

However, storing them in `%appdata%` causes performance problems in a domain environment with roaming profiles turn on.

Ideally the packages should be installed in `%localappdata%\npm` instead.

**Comment by KenanY** [comment] 2015-11-02 20:37
Duplicate of https://github.com/npm/npm/issues/4564?

**Comment by robertbaker** [comment] 2015-11-02 20:45
@KenanY  yes.

Looks like the NPM & Node team never got around to addressing this.

I vote for `%localappdata%` or `%programdata%` leaning towards `%programdata%`

**Comment by othiym23** [comment] 2015-11-02 21:25
Closing as duplicate of #4564. This is a call I would like to see made by somebody at Microsoft, as MS developers are the ones who chose `%APPDATA%` as the default prefix for Windows in the first place.

**Closed by othiym23** 2015-11-02 21:25 UTC

**Comment by othiym23** [comment] 2015-11-02 21:29
That said, I'm still happy to see the cache directory move, and the reason this didn't land in `npm@3` and Node 5 is that everybody involved had a billion other things to do (which is why it would be _super_ helpful to see this handled via PRs against the MSI build files and npm's configuration code, rather than proposals or discussions).

**Comment by robertbaker** [comment] 2015-11-02 22:11
If you look at the issue ref someone made a PR offer ready to go

**Comment by othiym23** [comment] 2015-11-02 22:17
I see a potential patch in a gist but no PR, which is significantly less useful.
