### ISSUE TITLE
npm ERR! shasum check failed for /tmp/npm-8839-e9fb0d5e/registry.npmjs.org/through2/-/through2-0.6.5.tgz

### ISSUE THREAD

**Issue by kurtnolanlopez** [npm/npm#9623] opened 2015-09-16 16:15 UTC
Hi, I keep getting this error when I try to install dependencies.

ERR! node v4.0.0
npm ERR! npm v2.14.3

npm ERR! shasum check failed for /tmp/npm-8839-e9fb0d5e/registry.npmjs.org/through2/-/through2-0.6.5.tgz
npm ERR! Expected: 41ab9c67b29d57209071410e1d7a7a968cd3ad48
npm ERR! Actual: da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From: https://registry.npmjs.org/through2/-/through2-0.6.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

**Comment by KenanY** [comment] 2015-09-16 16:16
@kurtnolanlopez Please see http://status.npmjs.org/incidents/pyw00fmpjzrh

**Comment by seldo** [comment] 2015-09-16 16:39
Duplicate of #9601

**Closed by seldo** 2015-09-16 16:39 UTC
