### ISSUE TITLE
Error While Installing cordova ionic

### ISSUE THREAD

**Issue by vinothmoorthkumar** [npm/npm#11660] opened 2016-02-24 12:43 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\Vinothkumar\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@3.7.3
3 info using node@v4.2.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/cordova
14 silly fetchNamedPackageData ionic
15 silly mapToRegistry name ionic
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/ionic
19 verbose request uri https://registry.npmjs.org/cordova
20 verbose request no auth needed
21 info attempt registry request try #1 at 6:07:16 PM
22 verbose request using bearer token for auth
23 verbose request id 959cc2315ac47a5e
24 verbose etag "D4LSYY2HK3ZTV0W0SXIQE1GRX"
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 6:07:16 PM
29 verbose request using bearer token for auth
30 verbose etag "4CXYYRU27RMQOJGID7VDS5HOU"
31 http request GET https://registry.npmjs.org/ionic
32 http 304 https://registry.npmjs.org/ionic
33 verbose headers { 'cache-control': 'max-age=300',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Wed, 24 Feb 2016 12:37:19 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-sin6922-SIN',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1456317439.147557,VS0,VE242' }
34 silly get cb [ 304,
34 silly get   { 'cache-control': 'max-age=300',
34 silly get     'accept-ranges': 'bytes',
34 silly get     date: 'Wed, 24 Feb 2016 12:37:19 GMT',
34 silly get     via: '1.1 varnish',
34 silly get     connection: 'keep-alive',
34 silly get     'x-served-by': 'cache-sin6922-SIN',
34 silly get     'x-cache': 'MISS',
34 silly get     'x-cache-hits': '0',
34 silly get     'x-timer': 'S1456317439.147557,VS0,VE242' } ]
35 verbose etag https://registry.npmjs.org/ionic from cache
36 verbose get saving ionic to C:\Users\Vinothkumar\AppData\Roaming\npm-cache\registry.npmjs.org\ionic.cache.json
37 verbose correctMkdir C:\Users\Vinothkumar\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
38 http 304 https://registry.npmjs.org/cordova
39 verbose headers { 'cache-control': 'max-age=300',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Wed, 24 Feb 2016 12:37:20 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-sin6923-SIN',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1456317439.158994,VS0,VE968' }
40 silly get cb [ 304,
40 silly get   { 'cache-control': 'max-age=300',
40 silly get     'accept-ranges': 'bytes',
40 silly get     date: 'Wed, 24 Feb 2016 12:37:20 GMT',
40 silly get     via: '1.1 varnish',
40 silly get     connection: 'keep-alive',
40 silly get     'x-served-by': 'cache-sin6923-SIN',
40 silly get     'x-cache': 'MISS',
40 silly get     'x-cache-hits': '0',
40 silly get     'x-timer': 'S1456317439.158994,VS0,VE968' } ]
41 verbose etag https://registry.npmjs.org/cordova from cache
42 verbose get saving cordova to C:\Users\Vinothkumar\AppData\Roaming\npm-cache\registry.npmjs.org\cordova.cache.json
43 verbose correctMkdir C:\Users\Vinothkumar\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
44 silly install normalizeTree
45 silly loadCurrentTree Finishing
46 silly loadIdealTree Starting
47 silly install loadIdealTree
48 silly cloneCurrentTree Starting
49 silly install cloneCurrentTreeToIdealTree
50 silly cloneCurrentTree Finishing
51 silly loadShrinkwrap Starting
52 silly install loadShrinkwrap
53 silly loadShrinkwrap Finishing
54 silly loadAllDepsIntoIdealTree Starting
55 silly install loadAllDepsIntoIdealTree
56 silly resolveWithNewModule ionic@1.7.14 checking installable status
57 silly cache add args [ 'ionic', null ]
58 verbose cache add spec ionic
59 silly resolveWithNewModule cordova@6.0.0 checking installable status
60 silly cache add args [ 'cordova', null ]
61 verbose cache add spec cordova
62 silly cache add parsed spec Result {
62 silly cache add   raw: 'ionic',
62 silly cache add   scope: null,
62 silly cache add   name: 'ionic',
62 silly cache add   rawSpec: '',
62 silly cache add   spec: 'latest',
62 silly cache add   type: 'tag' }
63 silly addNamed ionic@latest
64 verbose addNamed "latest" is being treated as a dist-tag for ionic
65 info addNameTag [ 'ionic', 'latest' ]
66 silly mapToRegistry name ionic
67 silly mapToRegistry using default registry
68 silly mapToRegistry registry https://registry.npmjs.org/
69 silly mapToRegistry uri https://registry.npmjs.org/ionic
70 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
71 silly cache add parsed spec Result {
71 silly cache add   raw: 'cordova',
71 silly cache add   scope: null,
71 silly cache add   name: 'cordova',
71 silly cache add   rawSpec: '',
71 silly cache add   spec: 'latest',
71 silly cache add   type: 'tag' }
72 silly addNamed cordova@latest
73 verbose addNamed "latest" is being treated as a dist-tag for cordova
74 info addNameTag [ 'cordova', 'latest' ]
75 silly mapToRegistry name cordova
76 silly mapToRegistry using default registry
77 silly mapToRegistry registry https://registry.npmjs.org/
78 silly mapToRegistry uri https://registry.npmjs.org/cordova
79 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
80 verbose get https://registry.npmjs.org/ionic not expired, no request
81 silly addNameTag next cb for ionic with tag latest
82 silly addNamed ionic@1.7.14
83 verbose addNamed "1.7.14" is a plain semver version for ionic
84 verbose get https://registry.npmjs.org/cordova not expired, no request
85 silly addNameTag next cb for cordova with tag latest
86 silly addNamed cordova@6.0.0
87 verbose addNamed "6.0.0" is a plain semver version for cordova
88 silly mapToRegistry name ionic
89 silly mapToRegistry using default registry
90 silly mapToRegistry registry https://registry.npmjs.org/
91 silly mapToRegistry uri https://registry.npmjs.org/ionic
92 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz not in flight; adding
93 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz',
93 verbose addRemoteTarball   'af493d5df4688d917d778b0934d1739b9be6efe6' ]
94 silly cache afterAdd cordova@6.0.0
95 verbose afterAdd C:\Users\Vinothkumar\AppData\Roaming\npm-cache\cordova\6.0.0\package\package.json not in flight; writing
96 verbose correctMkdir C:\Users\Vinothkumar\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
97 info retry fetch attempt 1 at 6:07:23 PM
98 info attempt registry request try #1 at 6:07:23 PM
99 http fetch GET https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
100 verbose request using bearer token for auth
101 verbose afterAdd C:\Users\Vinothkumar\AppData\Roaming\npm-cache\cordova\6.0.0\package\package.json written
102 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
103 silly fetchAndShaCheck shasum af493d5df4688d917d778b0934d1739b9be6efe6
104 silly rollbackFailedOptional Starting
105 silly rollbackFailedOptional Finishing
106 silly runTopLevelLifecycles Starting
107 silly runTopLevelLifecycles Finishing
108 silly install printInstalled
109 verbose stack Error: shasum check failed for C:\Users\VINOTH~1\AppData\Local\Temp\npm-1768-fbe88a67\registry.npmjs.org\ionic-\ionic-1.7.14.tgz
109 verbose stack Expected: af493d5df4688d917d778b0934d1739b9be6efe6
109 verbose stack Actual:   1ecf1ca05a4bde83a961e3fd120aec9e09932330
109 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
109 verbose stack     at C:\Users\Vinothkumar\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:25:8
109 verbose stack     at ReadStream.<anonymous> (C:\Users\Vinothkumar\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:72:7)
109 verbose stack     at emitNone (events.js:72:20)
109 verbose stack     at ReadStream.emit (events.js:166:7)
109 verbose stack     at endReadableNT (_stream_readable.js:905:12)
109 verbose stack     at doNTCallback2 (node.js:441:9)
109 verbose stack     at process._tickCallback (node.js:355:17)
110 verbose cwd C:\Users\Vinothkumar
111 error Windows_NT 6.1.7601
112 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Vinothkumar\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
113 error node v4.2.2
114 error npm  v3.7.3
115 error shasum check failed for C:\Users\VINOTH~1\AppData\Local\Temp\npm-1768-fbe88a67\registry.npmjs.org\ionic-\ionic-1.7.14.tgz
115 error Expected: af493d5df4688d917d778b0934d1739b9be6efe6
115 error Actual:   1ecf1ca05a4bde83a961e3fd120aec9e09932330
115 error From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
116 error If you need help, you may report this error at:
116 error     https://github.com/npm/npm/issues
117 verbose exit [ 1, true ]

**Comment by zkat** [comment] 2016-12-09 00:46
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:46 UTC
Labels: support
