### ISSUE TITLE
npm on Dragonflybsd

### ISSUE THREAD

**Issue by koneude** [npm/npm#4520] opened 2014-01-20 16:13 UTC
I am trying to get npm installed on a dragonflybsd system. node installed all right, and once I figured out npm much prefers GNU make over BSD make, I got a few steps further. Alas, I don't have luck with everything:

gmake install fails: 

```
node cli.js install -g -f
npm WARN using --force I sure hope you know what you are doing.
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at /usr/xiqit/npm/npm/node_modules/uid-number/uid-number.js:38:18
npm ERR!     at ChildProcess.exithandler (child_process.js:641:7)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:735:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System DragonFly 3.6-RELEASE
npm ERR! command "node" "/usr/xiqit/npm/npm/cli.js" "install" "-g" "-f"
npm ERR! cwd /usr/xiqit/npm/npm
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.24
npm ERR! type unexpected_eos
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/xiqit/npm/npm/npm-debug.log
npm ERR! not ok code 0
gmake: *** [install] Error 1

```
(This also appears to be why installing npm from the dragonflybsd package collection fails). 

I'm stymied.

**Comment by smikes** [comment] 2015-02-03 02:18
Can this issue now be closed?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.24.  We have not heard of any other problems installing on `dragonflybsd` since this report. Can you try with a newer npm version?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-02-20 20:46
Closing as abandoned.

**Closed by othiym23** 2015-02-20 20:46 UTC
Labels: support

**Comment by sysadminmike** [comment] 2015-02-26 20:34
Just been trying todo this as well - i think the issue isnt with npm but actually with node as there is no specific dragonfly.c in 

https://github.com/joyent/node/tree/master/deps/uv/src/unix

I think the dports is currently using the freebsd.c to try to get process info from:

http://muscles.dragonflybsd.org/bulk/latest-per-pkg/node/0.12.0_1/bleeding-edge-potential.log

  gcc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../deps/uv/include -I../deps/uv/src  -pthread -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g --std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer  -MMD -MF /wrkdirs/www/node/work/node-v0.12.0/out/Release/.deps//wrkdirs/www/node/work/node-v0.12.0/out/Release/obj.target/libuv/deps/uv/src/unix/freebsd.o.d.raw -pipe -O2 -fno-strict-aliasing -c -o /wrkdirs/www/node/work/node-v0.12.0/out/Release/obj.target/libuv/deps/uv/src/unix/freebsd.o ../deps/uv/src/unix/freebsd.c

Also see http://muscles.dragonflybsd.org/latest-failures/logs/npm-2.2.0.log npm build fails

**Comment by othiym23** [comment] 2015-02-26 20:54
@sysadminmike That stacktrace at the end is pure Node -- there are definitely some issues with how the ports team has adapted Node for DragonflyBSD. Thanks for the detective work!

**Comment by sysadminmike** [comment] 2015-02-26 21:11
i have done a little more digging perhaps something todo with:

https://github.com/DragonFlyBSD/DragonFlyBSD/blob/4ff4d99fc851da1a09ed7e6a9fe054d2dd3d6013/sys/sys/unistd.h#L90

tbh c is not my forte so this is just me stabbing in the dark 

from testing:
 

    mike@dfly.gw.office:~ % cat j.js 

    console.log(process.getuid)
    console.log(process.getuid())
    mike@dfly.gw.office:~ % node j.js 
    [Function]
    2223
    mike@dfly.gw.office:~ % 

So node is getting my uid correctly

**Comment by sysadminmike** [comment] 2015-02-26 21:13
I dont think its the ports team as the node source does have if defs for dragonfly but dont think it handeling uid/guid stuff correctly somewhere

**Comment by sysadminmike** [comment] 2015-02-26 21:38
I think it has todo with the tty stuff

https://github.com/joyent/node/blob/857975d5e7e0d7bf38577db0478d9e5ede79922e/deps/uv/src/unix/tty.c

and 

https://github.com/joyent/node/blob/7c0419730b237dbfa0ec4e6fb33a99ff01825a8f/src/tty_wrap.cc

Perhaps it is not recognising a dragonfly tty correctly as i think the error comes from this function

https://github.com/joyent/node/blob/857975d5e7e0d7bf38577db0478d9e5ede79922e/deps/uv/src/unix/tty.c#L162
