### ISSUE TITLE
Crashing on uninstalling global packages

### ISSUE THREAD

**Issue by embarq** [npm/npm#16957] opened 2017-06-04 00:30 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Trying to uninstall global packages. Those has been installed via `npm@4.6.1`. After update to `npm@5.0.2` I get an error: `Unhandled rejection Error: Argument #2: Expected string but got null`

#### How can the CLI team reproduce the problem?

Currently I have the following list of global packages:

```sh
> npm ls -g --depth 0
/home/embarq/.nvm/versions/node/v6.10.0/lib
├── @angular/cli@1.0.0
├── bower@1.8.0
├── cordova@6.5.0
├── elm@0.18.0
├── feathers-cli@2.0.5
├── firebase-tools@3.6.0
├── gulp@3.9.1
├── ionic@3.3.0
├── loopback-cli@2.5.0
├── npm@5.0.2
├── pnpm@0.68.0
├── tslint@5.0.0
└── typescript@2.3.2
```

Trying to `npm un -g feathers-cli firebase-tools pnpm` I get the `Unhandled rejection`.

`npm-debug.log` and full error message can be found [here](https://gist.github.com/embarq/51c54f8200e7da18de80d983fa7b8145)

### supporting information:

 - `npm -v` prints: `5.0.2`
 - `node -v` prints: `v6.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Linux`
 - Network issues:
   - Geographic location where npm was run: Ukraine
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by codekraft-studio** [comment] 2017-06-04 21:06
same error but on Windows for me

**Comment by zkat** [comment] 2017-06-05 16:28
Closing as duplicate of https://github.com/npm/npm/issues/16738

**Closed as completed by zkat** 2017-06-05 16:28 UTC
Labels: npm5
