### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by anandseshadri** [npm/npm#7781] opened 2015-03-28 17:20 UTC
i am just starting i get the following error when i try to install most of the node packages .Please help
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
```

**Comment by KenanY** [comment] 2015-03-28 18:15
```
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'
```

@anandseshadri This looks like an issue with your internet connection, not `npm`. Are you behind a proxy by any chance?

**Comment by anandseshadri** [comment] 2015-03-28 18:35
no i am not behind any proxy server,can firewall cause this type of issue

**Comment by smikes** [comment] 2015-03-29 11:23
Yes, this can be caused either by a firewall or a proxy.  Can you `ping` the npm registry host and fetch a simple file?

```
> ping registry.npmjs.org
> npm view npm version
```

**Comment by rodrigobotti** [comment] 2015-04-18 20:07
I have the same problem.
I'm not behind a proxy or firewall, still I can't install `bower` with `npm`.
I can ping the registry and retrieve the latest version just fine.
When I run `npm install -g bower` I get the following:
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rodrigo\npm-debug.log
```

**Comment by smikes** [comment] 2015-04-29 17:01
@anandseshadri Is this still a problem for you?

@rodrigobotti could you please create a new issue so we can follow your issue separately?  You may not have exactly the same root cause as the OP.

One thing I note is that you are both using `node@0.12`, and there is a bad interaction between a known bug in `node@0.12` and `npm@<2.8.2` which can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by rodrigobotti** [comment] 2015-04-30 22:15
@smikes after updating my `npm` to the latest version (`2.8.4`) it worked.
Thanks for the help!

**Comment by othiym23** [comment] 2015-05-07 03:49
Closing as resolved / abandoned.

**Closed by othiym23** 2015-05-07 03:49 UTC
Labels: support, windows

**Comment by hasenstein** [comment] 2015-05-17 10:45
I'm using io.js v2.0.2 and I have NO PROXY, can ping registry.npmjs.org, "npm view npm version" shows 2.10.0. "npm install" results in a timeout like above.

**Comment by smikes** [comment] 2015-05-17 16:44
Michael- could you please open a new issue and attach your npm-debug.log ?  Thanks!

**Comment by hasenstein** [comment] 2015-05-17 16:57
Ahem... see the reference just above your comment...? :-)

**Comment by pkvpraveen** [comment] 2015-06-25 17:49
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Praveen>npm -v
2.11.2

C:\Users\Praveen>npm install -g bower
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Praveen\npm-debug.log

**Comment by xiaoliuzi** [comment] 2015-09-16 14:36
$ npm install hexo-cli -g
    npm WARN optional dep failed, continuing fsevents@0.3.8
    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program      Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "hexo-cli" "-g"
    npm ERR! node v4.0.0
    npm ERR! npm  v2.14.2

    npm ERR! shasum check failed for C:\Users\John\AppData\Local\Temp\npm-4504-            7766cd51\registry.npmjs.org\core-util-is\-\core-util-is-1.0.1.tgz
    npm ERR! Expected: 6b07085aef9a3ccac6ee53bf9d3df0c1521a5538
    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    npm ERR! From:     https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\John\npm-debug.log



I have the same problems.  I have try this method:

https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

but, it doesn't work.

**Comment by mnegi** [comment] 2015-12-29 03:30
I have the same problem too. There is no proxy and firewall.

npm install --save browserify@11.0.1

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "browserify@11.0.1"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 103.245.222.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by cbeaujoin** [comment] 2016-02-25 16:52
https://github.com/felixrieseberg/npm-windows-upgrade

**Comment by skakkar** [comment] 2016-04-16 13:04
I was also facing similar issues. I followed below mentioned steps and it worked for me:

Windows>Start>Node.js>Run as a Administrator NodeJs Command Prompt

ping registry.npmjs.org

npm view npm version
cd %ProgramFiles%\nodejs
npm install npm@latest
and npm updated successfully. earlier I was trying for CMD and that was throwing error. may be some path issue that got resolved by running NodeJs Command Prompt. hope it'll work for you. try this.

**Comment by khan789** [comment] 2016-05-18 00:09
Ok, This solved my problem. 
In windows I have Environment variable as NODE_ENV=production. I removed it and NPM started working again for me.

**Comment by michelgotta** [comment] 2016-07-25 09:38
For all those where **`npm set registry` doesn't work and they don't use a firewall or proxy**, here is a solution that worked for me:

The problem occurred when installing from `package.json`. I have setup resulting in around 700 npm modules. When I installed all the dependencies from my `package.json` one after another `npm install autoprefixer@^6.0.0; npm install bootstrap-sass@^3.3.5; …` and so on there was no problem.

I think there are to many requests and the npm registry just blocks the connection. When I install from a `package.json` with just a few npm packages it works fine. Is there a way to authenticate to npm from the commandline to let the registry server know I am not bruteforcing or something?

**Comment by venkatav5a8** [comment] 2016-08-09 18:29
While i was trying to install reactjs i was going to do npm install on the particular folder, but it is simply throwing me ETIMEDOUT error, don't able to know the root cause of this, Please see the attachments with npm-debug.log file along with snagit.

![2016-08-09_13-25-07](https://cloud.githubusercontent.com/assets/9933383/17528340/b6421716-5e34-11e6-8966-09b73421cbbc.png)

**Comment by kumarvishalvishnoi** [comment] 2016-08-11 12:20
Getting the same error when trying to install **protractor**

![error](https://cloud.githubusercontent.com/assets/20640392/17588376/0d69e57e-5fec-11e6-8e29-903fd549fa16.png)

**Comment by mayerwin** [comment] 2016-11-03 17:13
You can try to throttle the number of simultaneous connections with the following command (for example 3 maximum simultanous connections):

    npm set maxsockets 3

The CLI has been allowing this option since npm@3.8.0. The default is 50 simultaneous connections max. See [this link][1] for further reference.


  [1]: https://github.com/npm/npm/blob/5b4e3f3caff1f7ed30281b0b450de056a817bbc5/CHANGELOG.md#limit-concurrent-requests

**Comment by avinashl3175** [comment] 2016-11-24 07:51
![image](https://cloud.githubusercontent.com/assets/14246174/20590398/d8dcbd04-b248-11e6-9d6f-9f8c902fc0a7.png)

Same issue I am facing. Please provide a solution.

**Comment by slawojstanislawski** [comment] 2016-12-07 15:44
Windows7, Node 6.9.2, npm 3.10.9 . I was not behind a proxy, executing `npm config list` didn't show any proxy settings, yet it appears npm used http_proxy environment variable, as indicated in this comment: https://github.com/npm/npm/issues/14099#issuecomment-250335737. Additional removal of environment variable `http_proxy` resulted in npm installing packages again.

**Comment by CrisDan1905** [comment] 2017-02-17 02:28
I had the very same problem. The thing is that I don't know how on earth I was connected to a proxy and none of the commands guys said until now helped me to quite that proxy. The only way was:

`pm config set proxy null`

**Comment by zhengxkq** [comment] 2017-03-29 03:15
npm install -g cnpm --registry=https://registry.npm.taobao.org
npm ERR! Linux 2.6.18-308.el5
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "-g" "cnpm" "--registry=https://registry.npm.taobao.org"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 114.55.80.225:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/node/npm-debug.log


I have same problem when i use linux,please help me to solve the problem

**Comment by songproducer** [comment] 2017-04-05 09:13
Please reopen this - I'm experiencing it too on Ubuntu 14.04

**Comment by prathamesh-12** [comment] 2017-06-02 06:45
I also have the same issue..

![issue-timeout](https://cloud.githubusercontent.com/assets/21258235/26714032/1970a43c-478d-11e7-9dbd-5d3f866e8712.PNG)

**Comment by vigyanhoon** [comment] 2017-08-24 12:10
Getting the same issue.

**Comment by Littlehhh** [comment] 2017-09-01 15:12
npm config set registry http://registry.npmjs.org/      from`https://github.com/npm/npm/issues/9630`

**Comment by Littlehhh** [comment] 2017-09-01 15:14
`npm config set registry http://registry.npmjs.org/`
from [https://github.com/npm/npm/issues/9630](https://github.com/npm/npm/issues/9630)    it works
Thanks @xushvai

**Comment by knapcio** [comment] 2017-09-13 19:23
`npm update`
worked for me

**Comment by mtliendo** [comment] 2018-01-15 05:39
Thanks @Littlehhh, my issue was that I was using `https` but `http` was required.

**Comment by nishantkaushik74** [comment] 2018-03-03 06:20
I was going through the same error. the root cause was the proxy settings : there are several answers provided in here to reset the proxy but none of them worked for me.
below are the commands that solved my problem give them a try.

npm config rm proxy
npm config rm https-proxy

**Comment by montao** [comment] 2018-05-31 13:10
Using Win 10 + npm 5.6.0, it won't work. I tried everything. It is not working.

**Comment by nishantkaushik74** [comment] 2018-05-31 15:48
Edit  firewall settings and then try above commands it will work..
