### ISSUE TITLE
NPM install causes catastrophic damages to node_modules directory

### ISSUE THREAD

**Issue by Dillybob1992** [npm/npm#19559] opened 2018-01-09 11:48 UTC
**Specs**: Node-v8.9.4-x64. Windows 7 64-bit, GTX 950

### How to replicate:
 - Install a fresh node-v8.9.4-x-64
 - Go inside directory, open CMD
 - type `npm install limiter`
 - After, you will receive:
![](https://i.gyazo.com/8f3e5287c054d29b978c8d7b0aa5f899.png)
-- `added 1 package and removed 476 packages in 2.774s`
 - Howevever, now when using NPM, the user receives:
![](https://i.gyazo.com/4d3596dbcee1914abc6618e74c8e73ab.png)
-- 

### Caveats 
 - Seems like it removed all my folders inside `node_modules`, except for `limiter`
 - Happens not just with `limiter`, but other packages as well
 - Tested on node-v9.3.0-x64 as well, still happens
 - Can't replicate on Node 7.0 however
 - Tested on Windows 10, does happen there as well

Sorry if it's been reported already, couldn't find anything :) 

### supporting information:
 - `npm -v` prints: (can't access)
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: (can't access)

**Comment by KenanY** [comment] 2018-01-09 18:11
It's probably because you ran that install command from within your Node.js installation directory. That directory contains `npm` itself within the `node_modules` folder, so by installing `limiter` you have overwritten your `npm` installation.

Since this seems to be about auto-pruning, I'll close as a duplicate of https://github.com/npm/npm/issues/16853.

**Closed by KenanY** 2018-01-09 18:11 UTC
Labels: npm5, support, windows
