### ISSUE TITLE
Following error when i trying to run React js basic program

### ISSUE THREAD

**Issue by harishkatta** [npm/npm#14005] opened 2016-09-19 14:18 UTC
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hari\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! basicreact@1.0.0 start: `webpack-dev-server --content-base src --inline
 --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the basicreact@1.0.0 start script 'webpack-dev-server --conte
nt-base src --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the basicreact package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base src --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs basicreact
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls basicreact
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hari\Desktop\basic react\npm-debug.log
```

**Comment by KenanY** [comment] 2016-09-19 14:30
@harishkatta Looks like your `"start"` script is exiting with an error code. Have you tried running it outside of `npm` to see what the issue is?

**Comment by marinintim** [comment] 2016-09-19 15:56
> npm ERR! If you do, this is most likely a problem with the basicreact package,
> npm ERR! not with npm itself.

**Comment by KenanY** [comment] 2016-09-26 14:01
Closing as abandoned.

**Closed by KenanY** 2016-09-26 14:01 UTC
Labels: support
