### ISSUE TITLE
NPM will not install any packages, hangs on 'addRemoteTarball'

### ISSUE THREAD

**Issue by sinrise** [npm/npm#7590] opened 2015-03-10 21:56 UTC
When I try to install any package with 'npm install', or any variant:

    npm install gulp -g -verbose

    npm install gulp -verbose

    npm install gulp

    npm install

    npm install connect

I get the following output but it just hangs on the last line, never finishing the install:

    npm info it worked if it ends with ok
    npm verb cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
    npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    npm verb cli   'install',
    npm verb cli   'gulp',
    npm verb cli   '-g',
    npm verb cli   '-verbose' ]
    npm info using npm@2.5.1
    npm info using node@v0.12.0
    npm verb node symlink C:\Program Files\nodejs\\node.exe
    npm verb cache add spec gulp
    npm verb addNamed gulp@*
    npm verb addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
    npm verb request uri https://registry.npmjs.org/gulp
    npm verb request no auth needed
    npm info attempt registry request try #1 at 4:09:05 PM
    npm verb request id 77dfc5813704dba8
    npm verb etag "EOZJDNUCAN683DXC55T2W1JVT"
    npm http request GET https://registry.npmjs.org/gulp
    npm http 304 https://registry.npmjs.org/gulp
    npm verb etag https://registry.npmjs.org/gulp from cache
    npm verb get saving gulp to C:\Users\iwiegand.TMI\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
    npm verb addNamed gulp@3.8.11
    npm verb addRemoteTarball https://registry.npmjs.org/gulp/-/gulp-3.8.11.tgz not in flight; adding
    npm verb addRemoteTarball [ 'https://registry.npmjs.org/gulp/-/gulp-3.8.11.tgz',
    npm verb addRemoteTarball   'd557e0a7283eb4136491969b0497767972f1d28a' ]
    ^CTerminate batch job (Y/N)?

It's definitely not https, since changing it to http yields the same result. It does this from any folder on my machine, no matter what package, or even just 'npm install'. I've restarted, resintalled node.js, etc. I'm on a Windows 8.1 machine and wishing I had a Mac.

The crazy thing is it HAS worked. I got Composer, Laravel and a bunch of other stuff installed just fine, then one day, it just started doing this. I have no idea what could be interfering. Checking the TaskManager, npm IS running with like 18% CPU usage the whole time it's "trying" to install.

Apparently I'm the only one on Earth with this problem. I've searched and searched on Google and nothing. I'm resorting to Facebook and Google groups. So far no suggestions from SO users have helped, although I very much appreciate the attempts.

**Comment by elegantweb** [comment] 2015-03-11 17:25
i have same problem plz help :(

**Comment by imperat0r** [comment] 2015-03-23 18:29
Same problem here.

**Comment by sinrise** [comment] 2015-03-23 21:20
I'm not sure if this is related. When I run npm install from bash, it creates a folder off my c: drive: C:\c\Users\<myusername>\AppData\Local. That 'c' after the drive letter is not a typo. It creates that folder. The 'Local' folder is completely empty. It doesn't do it if I run it from the standard Windows Command Prompt OR from my console emulator (cmder).

**Comment by mfundo** [comment] 2015-03-27 13:17
Happens to be a problem with the new version of node or npm, didnt really debug it further but rolling back to a previous version sorts it out, know its not a solution but at least you can continue to work and install your stuff.

**Comment by smikes** [comment] 2015-05-03 03:01
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by imperat0r** [comment] 2015-05-03 19:05
I somehow find out that problem is because I have to temp variables defined, I deleted one and now everything works.

**Comment by philsco** [comment] 2015-05-05 15:03
Took me a while to figure out what @imperat0r was referring to, after trying EVERY single option listed in the instructions.....
I ran:
npm config ls -l 

and indeed had two 'tmp' folder paths (the result of a faulty entry in the Win 8.1 Environment Variables control panel).

Just thought I'd post it here since I wasted a whole day on the issue....

**Comment by othiym23** [comment] 2015-05-20 03:26
Closing as resolved.

**Closed by othiym23** 2015-05-20 03:26 UTC
Labels: support, windows

**Comment by acoatsCalicosol** [comment] 2015-12-06 13:49
philsco - I had the same problem too.

**Comment by PyroSA** [comment] 2016-03-02 12:24
Had a similar one on a colleagues's machine.
TEMP was set to two folders separated with a semi-colon for some reason.

**Comment by akshat-reglobe** [comment] 2016-05-02 12:06
This issue is still not resolved . I also faced the same issue in Windows 10. Thanks for the temporary solution , urge Node Developers to find solution.

**Comment by korneliuskristianr** [comment] 2016-07-12 20:09
Hi, thanks i works.
I use windows 10-64bit. The problem is because there is 2 TEMP path on windows environment

**Comment by jessisharon13** [comment] 2017-02-02 22:11
Thank you! 
Every time I tried to 'npm install', it would get stuck on loadAllDepsIntoIdealTree and never finish. Fixing the Temp environment variable fixed it.

**Comment by AJIBS** [comment] 2017-05-20 15:13
I also had **two TEMP  variables** defined in my **USER Environment ** variables, and I had to **delete one** of the variables for my _"npm install"_ to start working. (Although, earlier I had changed the **TEMP variable** in my **SYSTEM Environment variables** to **C:/tmp**, after creating a new "**tmp" folder** in my C drive. This action was based on this post: http://stackoverflow.com/questions/40874237/npm-install-hangs-on-loadrequesteddeps)

This issue drove me crazy for about a day before I found that solution.
I was so glad when I found it. Many thanks to you all.

**Comment by ghost** [comment] 2017-06-11 08:49
@AJIBS my Environment variables looks like this. 
![2](https://user-images.githubusercontent.com/29344698/27009642-c615b8be-4eac-11e7-928a-e800ff826f4d.png)

I changed TEMP = c:\tmp and created folder name tmp in C:\ but still its not working :(

**Comment by ajibs** [comment] 2017-06-11 09:25
Try moving the "npm path" in the USER VARIABLES to the bottom of the list i.e. below all the other paths like ruby and co
