### ISSUE TITLE
`npm uninstall somepackage --save` no longer works in npm 3.5.0

### ISSUE THREAD

**Issue by mikemaccana** [npm/npm#10571] opened 2015-11-26 15:19 UTC
[`npm uninstall somepackage --save`](https://docs.npmjs.com/cli/uninstall) no longer works in npm 3.5.0

    npm uninstall cookieparser --save
    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node[" "/usr/local/bin/npm" "uninstall" "cookieparser" "--save"
    npm ERR! node v4.2.1
    npm ERR! npm  v3.5.0
    npm ERR! code EMISSINGARG

    npm ERR! typeerror Error: Missing required argument #3
    npm ERR! typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:438:3)
    npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:234:7
    npm ERR! typeerror     at Array.forEach (native)
    npm ERR! typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:230:8)
    npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
    npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    npm ERR! typeerror This is an error with npm itself. Please report this error at:
    npm ERR! typeerror     <http://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/mike/Documents/certsimple/npm-debug.log

**Comment by jb29** [comment] 2015-11-27 09:11
+1, I've got the same problem with `jasmine-core`. Uninstalling other packages worked fine.
It's not a problem with v3.5.0 though. I get the same error with 3.4.1 or 3.3.12.

(*I'm using Windows 10 x64*)

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'uninstall',
1 verbose cli   '--save-dev',
1 verbose cli   'jasmin-core' ]
2 info using npm@3.5.0
3 info using node@v4.2.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 verbose stack Error: Missing required argument #3
19 verbose stack     at replaceModule (C:\npm\node_modules\npm\lib\install\deps.js:438:3)
19 verbose stack     at C:\npm\node_modules\npm\lib\install\deps.js:234:7
19 verbose stack     at Array.forEach (native)
19 verbose stack     at exports.removeDeps (C:\npm\node_modules\npm\lib\install\deps.js:230:8)
19 verbose stack     at Array.<anonymous> (C:\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at chain (C:\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
19 verbose stack     at Uninstaller.loadAllDepsIntoIdealTree (C:\npm\node_modules\npm\lib\uninstall.js:72:3)
19 verbose stack     at Array.<anonymous> (C:\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
20 verbose cwd C:\dev\hskv
21 error Windows_NT 10.0.10240
22 error argv "C:\\nodejs\\node.exe" "C:\\npm\\node_modules\\npm\\bin\\npm-cli.js" "uninstall" "--save-dev" "jasmin-core"
23 error node v4.2.2
24 error npm  v3.5.0
25 error code EMISSINGARG
26 error typeerror Error: Missing required argument #3
26 error typeerror     at replaceModule (C:\npm\node_modules\npm\lib\install\deps.js:438:3)
26 error typeerror     at C:\npm\node_modules\npm\lib\install\deps.js:234:7
26 error typeerror     at Array.forEach (native)
26 error typeerror     at exports.removeDeps (C:\npm\node_modules\npm\lib\install\deps.js:230:8)
26 error typeerror     at Array.<anonymous> (C:\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
26 error typeerror     at LOOP (C:\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
26 error typeerror     at chain (C:\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
26 error typeerror     at Uninstaller.loadAllDepsIntoIdealTree (C:\npm\node_modules\npm\lib\uninstall.js:72:3)
26 error typeerror     at Array.<anonymous> (C:\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
26 error typeerror     at LOOP (C:\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 error typeerror This is an error with npm itself. Please report this error at:
27 error typeerror     <http://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
```

**Comment by marcoms** [comment] 2015-12-04 18:54
From #10378:

> looks like it only occurs when the package does not exist in node_modules/. However this means that it is impossible to remove a dependency from package.json using npm if for example you forgot the -S/-D flag the first time removing it.

Could help people to workaround the bug by manually removing the entry in `package.json` if the `node_modules/*` directory does not exist

**Comment by jb29** [comment] 2015-12-05 15:27
Well, in my case `--save-dev` worked like it should. The package was successfully removed from `package.json`. The problem was that the package wasn't removed from `node_modules`.

I got the same error message even without `--save-dev`.

**Comment by Olgagr** [comment] 2016-01-03 07:28
I have the same issue in npm 3.3.12 and uninstalling lodash. I get an error:

```
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "lodash" "--save"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:427:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:236:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:232:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by gajus** [comment] 2016-01-04 14:58
Same error NPM@3.5.2:

```
➜  server  npm uninstall pragmatist --save-dev
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/gajus/.nvm/versions/node/v5.2.0/bin/node" "/Users/gajus/.nvm/versions/node/v5.2.0/bin/npm" "uninstall" "pragmatist" "--save-dev"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/gajus/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gajus/Documents/dev/applaudience/showtime-dashboard/server/npm-debug.log
```

**Comment by prashcr** [comment] 2016-01-09 12:02
Having the same issue on 3.5.2

```
newman-uhoo git:master ❯ npm uninstall --save concat-stream duplexer2 highlander                         ✹
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/prashanthcr/.nvm/versions/node/v5.3.0/bin/node" "/Users/prashanthcr/.nvm/versions/node/v5.3.0/bin/npm" "uninstall" "--save" "concat-stream" "duplexer2" "highlander"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG



npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/prashanthcr/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by druvisc** [comment] 2016-02-15 16:45
Having the same issue on `npm 3.6` (OS X El Capitan 10.11.3):

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/Users/druvis/.node/bin/npm" "uninstall" "request" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.6.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/Users/druvis/.node/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/druvis/Work/n-fuse/restorecommerce/migrate/npm-debug.log
```

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.5.0/bin/node',
1 verbose cli   '/Users/druvis/.node/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   'request',
1 verbose cli   '--save' ]
2 info using npm@3.6.0
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 verbose stack Error: Missing required argument #3
19 verbose stack     at replaceModule (/Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:438:3)
19 verbose stack     at /Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:234:7
19 verbose stack     at Array.forEach (native)
19 verbose stack     at exports.removeDeps (/Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:230:8)
19 verbose stack     at Array.<anonymous> (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at Uninstaller.loadAllDepsIntoIdealTree (/Users/druvis/.node/lib/node_modules/npm/lib/uninstall.js:72:3)
19 verbose stack     at Array.<anonymous> (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose cwd /Users/druvis/Work/n-fuse/restorecommerce/migrate
21 error Darwin 15.3.0
22 error argv "/usr/local/Cellar/node/5.5.0/bin/node" "/Users/druvis/.node/bin/npm" "uninstall" "request" "--save"
23 error node v5.5.0
24 error npm  v3.6.0
25 error code EMISSINGARG
26 error typeerror Error: Missing required argument #3
26 error typeerror     at replaceModule (/Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:438:3)
26 error typeerror     at /Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:234:7
26 error typeerror     at Array.forEach (native)
26 error typeerror     at exports.removeDeps (/Users/druvis/.node/lib/node_modules/npm/lib/install/deps.js:230:8)
26 error typeerror     at Array.<anonymous> (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror     at chain (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
26 error typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/Users/druvis/.node/lib/node_modules/npm/lib/uninstall.js:72:3)
26 error typeerror     at Array.<anonymous> (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/Users/druvis/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 error typeerror This is an error with npm itself. Please report this error at:
27 error typeerror     <http://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
```

**Comment by zkat** [comment] 2016-08-11 23:52
I can't reproduce this on the latest version of npm. Can anyone confirm that it's still happening with `npm@latest`?

**Comment by zkat** [comment] 2016-08-11 23:54
Actually I confirmed that I could repro this on `3.6.0` and then tried latest, and can no longer reproduce. Closing as resolved, though idk exactly what fixed it. (any clues, @iarna ?)

**Closed by zkat** 2016-08-11 23:54 UTC
Labels: big-bug, bug, needs-repro
