### ISSUE TITLE
Not all instructions running when using multiple flags

### ISSUE THREAD

**Issue by joseph-norman** [npm/npm#7414] opened 2015-02-21 12:08 UTC
Current version of npm: 1.4.9 (`npm install -g npm@latest` to verify its the latest).

Not sure if this is an existing issue or not, couldn't find it amongst the others. I was recently trying to install browserify via using the following command: `npm install --save -g browserify` and from the looks of things only the last flag was done (I checked the package.json and found it wasn't being saved).

**Comment by KenanY** [comment] 2015-02-21 14:43
@joseph-norman Latest version is `2.6.0` :) https://github.com/npm/npm/releases

``` bash
$ npm info npm version
2.6.0
```

Also, your command doesn't really make sense to me. You're trying to save a globally-installed module as a local dependency in your app/module? You should probably ditch the `-g` flag, no? The module has to be installed locally if you want to `require()` it.

**Comment by joseph-norman** [comment] 2015-02-21 15:18
Strange, not sure why it didn't install that. 

Well the idea behind it is to install it both locally and globally - I suppose that would count as separate installs though, right? Thanks for your help

**Comment by KenanY** [comment] 2015-02-21 15:50
@joseph-norman Yes, it would require separate installs. One `npm install --save browserify` and one `npm install -g browserify` :)

**Comment by joseph-norman** [comment] 2015-02-21 16:55
Do you think this would be something that might be desirable in a version of npm? just seems like if it can pass more than one flag then it should be able to do both. Just a thought. If so, may create a PR for it.

**Comment by othiym23** [comment] 2015-02-21 17:38
Different flags are different kinds of things:

* `--global` / `-g` is a **mode flag** – it changes what _kind_ of thing npm is doing, between installing locally (in which case you want the module code most of the time) and installing globally (in which case you want the binaries exported by the package almost all of the time). Mode switches tend to be excluive – you're either installing something locally or globally, you can't do both.
* `--save` / `-S` is a **configuration flag** -- it provides additional information to the various npm commands.

In this particular case, the mode flag trumps one or more of the configuration flags. `npm install -g` tells npm to install one or more dependencies into the `globalPrefix`. I believe it would be at best confusing were `npm install` to ever install into both the global and local prefixes, because those are satisfying very different requirements.

There's been a discussion under way for a couple years about what to do when saving in the absense of a `package.json` file (https://github.com/npm/npm/issues/3576#issuecomment-74379389). There's never going to be a `package.json` when installing globally, because it doesn't make any sense for there to be a `package.json` in the global prefix. There should probably be a warning or an error when `--save` / `--save-dev` / `--save-optional` / `--save-bundled` / `--save-exact` are set when there's no `package.json` set *or* you're installing globally.

Thanks for your time and your offer, but I don't think it makes sense to change npm's behavior in the way you suggest. Weigh in on #3576 if you have opinions about how that should work, or maybe put together a PR for that change if you like (the comment I linked to at the end of that issue seems like the best behavior, although with a warning and not an error). For now, I'm going to close this as being how npm works by design.

**Closed by othiym23** 2015-02-21 17:38 UTC
Labels: feature-request
