### ISSUE TITLE
Registry shasum for selenium-webdriver@2.43.3 incorrect

### ISSUE THREAD

**Issue by jleyba** [npm/npm#6179] opened 2014-09-13 17:36 UTC
The npm registry has the shasum for 2.43.3 recored as `225d2896c8f959e008622306c6ddc0574d7508ec`. This causes installs of selenium-webdriver to fail with:

```
npm ERR! Error: shasum check failed for /var/folders/jd/jp2ggp392fx68vk0rbrh63f80000gn/T/npm-56395--fScOFtO/registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.43.3.tgz
npm ERR! Expected: 225d2896c8f959e008622306c6ddc0574d7508ec
npm ERR! Actual:   1a0d36d7cd1c2dc97592f9788c3c2c2385ffc867
npm ERR! From:     https://registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.43.3.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "selenium-webdriver"
npm ERR! cwd /Users/jleyba/Development/test
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jleyba/Development/test/npm-debug.log
npm ERR! not ok code 0
```

The shasum in the error report, `1a0d36d7cd1c2dc97592f9788c3c2c2385ffc867`, matches the tarball I published (which was generated with `npm pack`). If I install the version directly, it will update the local cache so subsequent `npm install selenium-webdriver` attempts succeed.

I just published `2.43.4` (no changes than required version bump) and everything seems to be working, but the registry is still incorrect for `2.43.3`.

```
$ npm publish selenium-webdriver-2.43.4.tgz 
+ selenium-webdriver@2.43.4

$ shasum selenium-webdriver-2.43.4.tgz 
c0eb002dd80287d5caae0a529abe3fd3d49abca1  selenium-webdriver-2.43.4.tgz

$ npm view selenium-webdriver | grep shasum
   { shasum: 'c0eb002dd80287d5caae0a529abe3fd3d49abca1',
```

**Comment by zkat** [comment] 2016-12-09 00:56
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:56 UTC
Labels: bug, registry, shasum
