### ISSUE TITLE
upgrading to 5.0.2 - cannnot find semver using docker node:latest and updating manually

### ISSUE THREAD

**Issue by pszabop** [npm/npm#16952] opened 2017-06-03 17:56 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when I log into my docker container and run npm it suggests I upgrade to 5.0.2 (apparently Docker image hasn't caught up).  When I follow the instructions given, npm no longer runs, it cannot find the  the module semver.

#### How can the CLI team reproduce the problem?

my docker file.  Note another problem with not auto-rebuilding bcrypt which is probably another issue:

```
FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
# apparently install doesn't handle major npm changes correctly
RUN npm rebuild bcrypt --update-binary

# Bundle app source
COPY . /usr/src/app/

EXPOSE 8080
CMD [ "npm", "test" ]
```
then I run the docker image but override the default command with /bin/bash.  I then run the suggested command `npm i -g npm`, and now all is broken.

### supporting information:

```
root@7c5d56326254:/usr/src/app# npm
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

```

package.json (probably shouldn't matter but just in case)

```
{
  "name": "docker_web_app",
  "version": "1.0.0",
  "description": "Node.js on Docker",
  "author": "Pa Sa  <coldsponger@gmail.com>",
  "main": "server.js",
  "scripts": {
    "start": "DEBUG=* DEBUG_FD=1 node server.js",
    "test": "DEBUG=* DEBUG_FD=1 NODE_ENV=test node_modules/.bin/tape"
  },
  "devDependencies": {
    "leaked-handles": "^5.2.0",
    "tape": "^4.2.2",
    "blue-tape": "^1.0.0",
    "supertest": "^2.0.1",
    "supertest-as-promised": "^4.0.2",
    "eslint": "^3.12.2"
  },
  "dependencies": {
    "express": "^4.14.0",
    "helmet": "^3.5.0",
    "express-limiter": "^1.6.0",
    "cors": "^2.8.1",
    "body-parser": "^1.15.2",
    "connect-ensure-login": "^0.1.1",
    "cookie-parser": "^1.4.3",
    "ejs": "^2.5.2",
    "express-session": "^1.14.2",
    "passport": "^0.3.2",
    "passport-facebook": "^2.1.1",
    "passport-local": "^1.0.0",
    "passport-mocked": "^1.2.0",
    "connect-redis": "^3.1.0",
    "express-bunyan-logger": "^1.3.1",
    "bunyan": "^1.8.5",
    "ioredis": "^2.4.0",
    "random-js": "^1.0.8",
    "graphql": "^0.8.2",
    "graphql-tools": "^0.9.1",
    "express-graphql": "^0.6.1",
    "graphql-relay": "^0.4.3",
    "jsonlint": "^1.6.2",
    "lodash": "^4.17.4",
    "elasticsearch": "^12.1.3",
    "minio": "^3.1.3",
    "base-64": "^0.1.0",
    "utf8": "^2.1.2",
    "bcrypt": "^1.0.2",
    "mime-types": "^2.1.14",
    "microtime": "^2.1.2",
    "dashify": "^0.2.2",
    "validator": "^7.0.0",
    "bluebird": "^3.4.7"
  }
}

```

**Comment by zkat** [comment] 2017-06-06 04:26
Closing as duplicate of https://github.com/npm/npm/issues/16807

**Closed as completed by zkat** 2017-06-06 04:26 UTC
Labels: npm5
