### ISSUE TITLE
TESTRPC from rpm

### ISSUE THREAD

**Issue by dion26** [npm/npm#17418] opened 2017-06-24 15:50 UTC
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: Germany
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dion26** [comment] 2017-06-24 15:52
npm ERR! git clone --template=/Users/dion/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/dion/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: Cloning into bare repository '/Users/dion/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! git clone --template=/Users/dion/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/dion/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: remote: Repository not found.
npm ERR! git clone --template=/Users/dion/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/dion/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: fatal: repository 'https://github.com/debris/bignumber.js.git/' not found
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/dion/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/dion/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1
npm ERR! Cloning into bare repository '/Users/dion/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/debris/bignumber.js.git/' not found
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dion/npm-debug.log

**Comment by kenany** [comment] 2017-06-25 15:17
Duplicate of https://github.com/npm/npm/issues/17413.

**Closed as completed by kenany** 2017-06-25 15:17 UTC
Labels: support, git
