### ISSUE TITLE
Verbose Bad JSON when performing NPM install

### ISSUE THREAD

**Issue by danielwray** [npm/npm#12209] opened 2016-04-05 16:37 UTC
Hi,

When performing an npm install istanbul or npm install gulper I am getting the attached output causing the install to fail - the package actually does exist locally afterwards under the npm directory.

This has been tested on multiple clean vagrant instances and local development machines with the same issue.

Note output has been cut as a large bulk of the output is non-ascii characters.

```
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'gulper' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'gulper', null ]
5 verbose cache add name=undefined spec="gulper" args=["gulper",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'gulper',
6 verbose parsed url   path: 'gulper',
6 verbose parsed url   href: 'gulper' }
7 silly lockFile cdecd70a-gulper gulper
8 verbose lock gulper /home/danielw/.npm/cdecd70a-gulper.lock
9 silly lockFile cdecd70a-gulper gulper
10 silly lockFile cdecd70a-gulper gulper
11 verbose addNamed [ 'gulper', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile caf514ff-gulper gulper@
14 verbose lock gulper@ /home/danielw/.npm/caf514ff-gulper.lock
15 silly addNameRange { name: 'gulper', range: '*', hasData: false }
16 verbose url raw gulper
17 verbose url resolving [ 'https://registry.npmjs.org/', './gulper' ]
18 verbose url resolved https://registry.npmjs.org/gulper
19 info trying registry request attempt 1 at 17:29:20
20 http GET https://registry.npmjs.org/gulper
21 http 200 https://registry.npmjs.org/gulper
22 silly registry.get cb [ 200,
22 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly registry.get     etag: '"AACBUTIUZITAQKKJC8KM007N7"',
22 silly registry.get     'content-type': 'application/json',
22 silly registry.get     'cache-control': 'max-age=300',
22 silly registry.get     'content-length': '6155',
22 silly registry.get     'accept-ranges': 'bytes',
22 silly registry.get     date: 'Tue, 05 Apr 2016 16:28:27 GMT',
22 silly registry.get     via: '1.1 varnish',
22 silly registry.get     age: '0',
22 silly registry.get     connection: 'keep-alive',
22 silly registry.get     'x-served-by': 'cache-fra1240-FRA',
22 silly registry.get     'x-cache': 'MISS',
22 silly registry.get     'x-cache-hits': '0',
22 silly registry.get     'x-timer': 'S1459873707.510238,VS0,VE108',
22 silly registry.get     vary: 'Accept-Encoding' } ]
23 silly addNameRange number 2 { name: 'gulper', range: '*', hasData: true }
24 silly addNameRange versions [ 'gulper', [ '0.1.0-dev', '0.1.0', '0.1.1', '0.1.2' ] ]
25 verbose addNamed [ 'gulper', '0.1.2' ]
26 verbose addNamed [ '0.1.2', '0.1.2' ]
27 silly lockFile e9995f15-gulper-0-1-2 gulper@0.1.2
28 verbose lock gulper@0.1.2 /home/danielw/.npm/e9995f15-gulper-0-1-2.lock
29 silly lockFile a1bee54e-pmjs-org-gulper-gulper-0-1-2-tgz https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz
30 verbose lock https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz /home/danielw/.npm/a1bee54e-pmjs-org-gulper-gulper-0-1-2-tgz.lock
31 verbose addRemoteTarball [ 'https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz',
31 verbose addRemoteTarball   'fa1e27ba12ac51b30d89bb668c1a1d64483399a5' ]
32 info retry fetch attempt 1 at 17:29:21
33 verbose fetch to= /home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/tmp.tgz
34 http GET https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz
35 http 200 https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz
36 verbose tar unpack /home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/tmp.tgz
37 silly lockFile 125c0eff-61052-0-5804754588752985-package tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
38 verbose lock tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package /home/danielw/.npm/125c0eff-61052-0-5804754588752985-packa
ge.lock
39 silly lockFile 48f8d043-61052-0-5804754588752985-tmp-tgz tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/tmp.tgz
40 verbose lock tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/tmp.tgz /home/danielw/.npm/48f8d043-61052-0-5804754588752985-tmp-t
gz.lock
41 silly gunzTarPerm modes [ '755', '644' ]
42 silly gunzTarPerm extractEntry package.json
43 silly gunzTarPerm extractEntry .npmignore
44 silly gunzTarPerm extractEntry README.md
45 silly gunzTarPerm extractEntry bin/gulper
46 silly lockFile 125c0eff-61052-0-5804754588752985-package tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
47 silly lockFile 125c0eff-61052-0-5804754588752985-package tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
48 silly lockFile 48f8d043-61052-0-5804754588752985-tmp-tgz tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/tmp.tgz
49 silly lockFile 48f8d043-61052-0-5804754588752985-tmp-tgz tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/tmp.tgz
50 verbose tar pack [ '/home/danielw/.npm/gulper/0.1.2/package.tgz',
50 verbose tar pack   '/home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package' ]
51 verbose tarball /home/danielw/.npm/gulper/0.1.2/package.tgz
52 verbose folder /home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
53 silly lockFile 125c0eff-61052-0-5804754588752985-package tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
54 verbose lock tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package /home/danielw/.npm/125c0eff-61052-0-5804754588752985-packa
ge.lock
55 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
56 verbose lock tar:///home/danielw/.npm/gulper/0.1.2/package.tgz /home/danielw/.npm/f7a177fe-elw-npm-gulper-0-1-2-package-tgz.lock
57 silly lockFile 125c0eff-61052-0-5804754588752985-package tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
58 silly lockFile 125c0eff-61052-0-5804754588752985-package tar:///home/danielw/tmp/npm-39766-UI7ROnvO/1459873761052-0.5804754588752985/package
59 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
60 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
61 silly lockFile 24e68c33-danielw-npm-gulper-0-1-2-package /home/danielw/.npm/gulper/0.1.2/package
62 verbose lock /home/danielw/.npm/gulper/0.1.2/package /home/danielw/.npm/24e68c33-danielw-npm-gulper-0-1-2-package.lock
63 silly lockFile 24e68c33-danielw-npm-gulper-0-1-2-package /home/danielw/.npm/gulper/0.1.2/package
64 silly lockFile 24e68c33-danielw-npm-gulper-0-1-2-package /home/danielw/.npm/gulper/0.1.2/package
65 verbose tar unpack /home/danielw/.npm/gulper/0.1.2/package.tgz
66 silly lockFile 2e76577d-danielw-npm-gulper-0-1-2-package tar:///home/danielw/.npm/gulper/0.1.2/package
67 verbose lock tar:///home/danielw/.npm/gulper/0.1.2/package /home/danielw/.npm/2e76577d-danielw-npm-gulper-0-1-2-package.lock
68 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
69 verbose lock tar:///home/danielw/.npm/gulper/0.1.2/package.tgz /home/danielw/.npm/f7a177fe-elw-npm-gulper-0-1-2-package-tgz.lock
70 silly gunzTarPerm modes [ '755', '644' ]
71 silly gunzTarPerm extractEntry package.json
72 silly gunzTarPerm extractEntry .npmignore
73 silly gunzTarPerm extractEntry README.md
74 silly gunzTarPerm extractEntry bin/gulper
75 silly lockFile 2e76577d-danielw-npm-gulper-0-1-2-package tar:///home/danielw/.npm/gulper/0.1.2/package
76 silly lockFile 2e76577d-danielw-npm-gulper-0-1-2-package tar:///home/danielw/.npm/gulper/0.1.2/package
77 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
78 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
79 verbose chmod /home/danielw/.npm/gulper/0.1.2/package.tgz 644
80 verbose chown /home/danielw/.npm/gulper/0.1.2/package.tgz [ 1000, 1000 ]
81 silly lockFile a1bee54e-pmjs-org-gulper-gulper-0-1-2-tgz https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz
82 silly lockFile a1bee54e-pmjs-org-gulper-gulper-0-1-2-tgz https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz
83 silly lockFile e9995f15-gulper-0-1-2 gulper@0.1.2
84 silly lockFile e9995f15-gulper-0-1-2 gulper@0.1.2
85 silly lockFile caf514ff-gulper gulper@
86 silly lockFile caf514ff-gulper gulper@
87 silly resolved [ { name: 'gulper',
87 silly resolved     version: '0.1.2',
87 silly resolved     description: 'Gulper is gulp.js task runner runner to restart on change gulpfile.js.',
87 silly resolved     scripts: { test: 'echo "Error: no test specified" && exit 1' },
87 silly resolved     author: { name: 'Mitsunori KUBOTA' },
87 silly resolved     license: 'MIT',
87 silly resolved     preferGlobal: 'true',
87 silly resolved     repository: { type: 'git', url: 'https://github.com/anatoo/gulper.git' },
87 silly resolved     keywords: [ 'gulp.js', 'gulp', 'task', 'runner', 'wrapper', 'restart' ],
87 silly resolved     bin: { gulper: 'bin/gulper' },
87 silly resolved     dependencies: { 'node-dev': '^2.6.0', 'npm-which': '^2.0.0' },
87 silly resolved     readme: '# Gulper\n\n[![npm version](https://badge.fury.io/js/gulper.png)](http://badge.fury.io/js/gulper)\n\nGulper is gulp.js cli wrap
per to restart gulp automatically on gulpfile change.\n\n## Installation\n\n```\n$ npm install -g gulp gulper\n```\n\n## Usage\n\nYou can simply replace `gulp
` with `gulper`.\n\n```\n$ gulper <task-name>\n```\n\nIf you change gulpfile.js, gulper will restart gulp.js task runner.\n\n## License\n\nThe MIT License (MI
T)\n\nCopyright &copy; 2014, Mitsunori KUBOTA \\<anatoo.jp@gmail.com\\>\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of thi
s software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, c
opy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, sub
ject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Soft
ware.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, F
ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, W
HETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n',
87 silly resolved     readmeFilename: 'README.md',
87 silly resolved     bugs: { url: 'https://github.com/anatoo/gulper/issues' },
87 silly resolved     _id: 'gulper@0.1.2',
87 silly resolved     dist: { shasum: '3688c3eadcebf93a7f2f77987ad3e99badde549a' },
87 silly resolved     _from: 'gulper@',
87 silly resolved     _resolved: 'https://registry.npmjs.org/gulper/-/gulper-0.1.2.tgz' } ]
88 info install gulper@0.1.2 into /home/danielw
89 info installOne gulper@0.1.2
90 info /home/danielw/node_modules/gulper unbuild
91 verbose tar unpack /home/danielw/.npm/gulper/0.1.2/package.tgz
92 silly lockFile e546732e-home-danielw-node-modules-gulper tar:///home/danielw/node_modules/gulper
93 verbose lock tar:///home/danielw/node_modules/gulper /home/danielw/.npm/e546732e-home-danielw-node-modules-gulper.lock
94 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
95 verbose lock tar:///home/danielw/.npm/gulper/0.1.2/package.tgz /home/danielw/.npm/f7a177fe-elw-npm-gulper-0-1-2-package-tgz.lock
96 silly gunzTarPerm modes [ '755', '644' ]
97 silly gunzTarPerm extractEntry package.json
98 silly gunzTarPerm extractEntry .npmignore
99 silly gunzTarPerm extractEntry README.md
100 silly gunzTarPerm extractEntry bin/gulper
101 silly lockFile e546732e-home-danielw-node-modules-gulper tar:///home/danielw/node_modules/gulper
102 silly lockFile e546732e-home-danielw-node-modules-gulper tar:///home/danielw/node_modules/gulper
103 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
104 silly lockFile f7a177fe-elw-npm-gulper-0-1-2-package-tgz tar:///home/danielw/.npm/gulper/0.1.2/package.tgz
105 info preinstall gulper@0.1.2
106 verbose readDependencies using package.json deps
107 verbose readDependencies using package.json deps
108 verbose cache add [ 'node-dev@^2.6.0', null ]
109 verbose cache add name=undefined spec="node-dev@^2.6.0" args=["node-dev@^2.6.0",null]
110 verbose parsed url { protocol: null,
110 verbose parsed url   slashes: null,
110 verbose parsed url   auth: null,
110 verbose parsed url   host: null,
110 verbose parsed url   port: null,
110 verbose parsed url   hostname: null,
110 verbose parsed url   hash: null,
110 verbose parsed url   search: null,
110 verbose parsed url   query: null,
110 verbose parsed url   pathname: 'node-dev@^2.6.0',
110 verbose parsed url   path: 'node-dev@^2.6.0',
110 verbose parsed url   href: 'node-dev@^2.6.0' }
111 verbose cache add name="node-dev" spec="^2.6.0" args=["node-dev","^2.6.0"]
112 verbose parsed url { protocol: null,
112 verbose parsed url   slashes: null,
112 verbose parsed url   auth: null,
112 verbose parsed url   host: null,
112 verbose parsed url   port: null,
112 verbose parsed url   hostname: null,
112 verbose parsed url   hash: null,
112 verbose parsed url   search: null,
112 verbose parsed url   query: null,
112 verbose parsed url   pathname: '^2.6.0',
112 verbose parsed url   path: '^2.6.0',
112 verbose parsed url   href: '^2.6.0' }
113 verbose addNamed [ 'node-dev', '^2.6.0' ]
114 verbose addNamed [ null, '>=2.6.0-0 <3.0.0-0' ]
115 silly lockFile 4cb70d54-node-dev-2-6-0 node-dev@^2.6.0
116 verbose lock node-dev@^2.6.0 /home/danielw/.npm/4cb70d54-node-dev-2-6-0.lock
117 verbose cache add [ 'npm-which@^2.0.0', null ]
118 verbose cache add name=undefined spec="npm-which@^2.0.0" args=["npm-which@^2.0.0",null]
119 verbose parsed url { protocol: null,
119 verbose parsed url   slashes: null,
119 verbose parsed url   auth: null,
119 verbose parsed url   host: null,
119 verbose parsed url   port: null,
119 verbose parsed url   hostname: null,
119 verbose parsed url   hash: null,
119 verbose parsed url   search: null,
119 verbose parsed url   query: null,
119 verbose parsed url   pathname: 'npm-which@^2.0.0',
119 verbose parsed url   path: 'npm-which@^2.0.0',
119 verbose parsed url   href: 'npm-which@^2.0.0' }
120 verbose cache add name="npm-which" spec="^2.0.0" args=["npm-which","^2.0.0"]
121 verbose parsed url { protocol: null,
121 verbose parsed url   slashes: null,
121 verbose parsed url   auth: null,
121 verbose parsed url   host: null,
121 verbose parsed url   port: null,
121 verbose parsed url   hostname: null,
121 verbose parsed url   hash: null,
121 verbose parsed url   search: null,
121 verbose parsed url   query: null,
121 verbose parsed url   pathname: '^2.0.0',
121 verbose parsed url   path: '^2.0.0',
121 verbose parsed url   href: '^2.0.0' }
122 verbose addNamed [ 'npm-which', '^2.0.0' ]
123 verbose addNamed [ null, '>=2.0.0-0 <3.0.0-0' ]
124 silly lockFile d93efe71-npm-which-2-0-0 npm-which@^2.0.0
125 verbose lock npm-which@^2.0.0 /home/danielw/.npm/d93efe71-npm-which-2-0-0.lock
126 silly addNameRange { name: 'node-dev', range: '>=2.6.0-0 <3.0.0-0', hasData: false }
127 silly addNameRange { name: 'npm-which',
127 silly addNameRange   range: '>=2.0.0-0 <3.0.0-0',
127 silly addNameRange   hasData: false }
128 verbose url raw node-dev
129 verbose url resolving [ 'https://registry.npmjs.org/', './node-dev' ]
130 verbose url resolved https://registry.npmjs.org/node-dev
131 info trying registry request attempt 1 at 17:29:21
132 http GET https://registry.npmjs.org/node-dev
133 verbose url raw npm-which
134 verbose url resolving [ 'https://registry.npmjs.org/', './npm-which' ]
135 verbose url resolved https://registry.npmjs.org/npm-which
136 info trying registry request attempt 1 at 17:29:21
137 http GET https://registry.npmjs.org/npm-which
138 http 200 https://registry.npmjs.org/node-dev
139 verbose bad json �
m�\�z7��y�i��T��json ��b%y� 	�GW����
                h=��+k��^L�2y�M:5o���~�:��f
�}��.�QsZբ����t�w�e躜�y��v���j�-j���;(�k���5A��]Y����
139 verbose bad json :���
139 verbose bad json N���}>��,��vb��sK@{Ք���Cs:�����͝�0�AvV-���׹�C��ȶ
                                                                            �.Kt�2��"�<�<�qf�2V\�2J���ћ�b���������&4�`���Cu��&�Y�0�2f#�XGQ'
139 verbose bad json xf���t^L�K���T'AF�q�HI?�A�U��^L��#�N�nJE�O�}������`?�������v1hy��$�wA���f�^L���,
                                                                                                              �q!�"A�Jb4� �&����m��,SL�h����J���)�o�����SJ�����_+�)E2�6J_`8^1�Ŀw����}`b��^LwQ�1�{X����9{��$xx���8
Y�Q1:�+� ."Ͳ�͏���1�;�p��#��fƥMY�C
139 verbose bad json άTR�Hh�b�E*J3�H��La�H lk��J��D/�y���d�C��M��js�ʺ7T��j���ǟ���=U��>Mx�wO�hO�p|�3,?�ڗ���ob�h� }:J{���vW��-����`�����mʺ����R�^��b���^��y�aXǜGZ��XD	�^LD(2���LX�bˇ[�]�����9�c8�X��V���sΦIJ��������R1��R��
�c��%�:Z2fр�d�GƌcH���z(0@CI{$EtI��6~���bzf�}�A��y�*�'�����,y�J!.�s��u���������1�)"E��1Il���q��
                                                                                                       ��"�9�|� 
�h)8�o��s�)����n$�O9��*��bmZ��v�����.�$��]��H#Mt��h����e���̼Vـ��"��`)"���������_/�p�k�����ٗ�*�����z�~�AQ8@}��>k)�:�k����Ǧ�9�,��{�����`��$^L�l���_k ��1�_Х��
�IX�/����^LT��)7��eSЭ7%M�_��R.O2��������nJωQ�~Dk���`�̣F��$u ���5}.<�u2����賧j�^L��zݔS�M�9]�%j>��Hǐl�
```

**Comment by othiym23** [comment] 2016-04-05 16:49
Closing as duplicate of #12196. See that issue for status and resolution. Thanks!

**Closed by othiym23** 2016-04-05 16:49 UTC
Labels: bug, registry
