### ISSUE TITLE
npm install grunt very slow

### ISSUE THREAD

**Issue by pauldraper** [npm/npm#13819] opened 2016-08-30 22:18 UTC
Just installing grunt takes over five minutes.

```
$ mkdir /tmp/test
$ npm -v
3.10.6
$ npm cache clear
$ time npm install grunt@1.01
...
real    5m11.529s
user    0m15.440s
sys     0m1.192s
```

I see this on several environments; this should be easily reproducible.

**Comment by KenanY** [comment] 2016-08-30 22:33
Can't reproduce :(

``` bash
$ npm -v
3.10.6
$ npm cache clean
$ time npm install grunt@1.0.1
real	0m25.457s
user	0m6.003s
sys	0m0.603s
```

**Comment by othiym23** [comment] 2016-08-30 22:37
Where are you running `npm install grunt` from? Are you running from inside AWS? We've seen a couple reports of slow installs today, but haven't yet figured out what they share in common.

**Comment by KenanY** [comment] 2016-09-08 05:45
Closing as abandoned.

**Closed by KenanY** 2016-09-08 05:45 UTC
Labels: registry, support
