### ISSUE TITLE
Install redux removing packages

### ISSUE THREAD

**Issue by bhargavgoli** [npm/npm#18765] opened 2017-10-09 11:56 UTC
when i try to install package(npm install --save [package name]), its removing already installed packages. See the below log:

```
[Bhargavs-MacBook-Pro:manager bhargavgoli$ npm install --save redux react-redux]
npm WARN gentlyRm not removing /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/.bin/jest as it wasn't installed by /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/jest
npm WARN gentlyRm not removing /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/.bin/uglifyjs as it wasn't installed by /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/uglify-js
npm WARN gentlyRm not removing /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/.bin/json5 as it wasn't installed by /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/json5
npm WARN gentlyRm not removing /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN gentlyRm not removing /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/.bin/esparse as it wasn't installed by /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/esprima
npm WARN gentlyRm not removing /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/.bin/esvalidate as it wasn't installed by /Users/bhargavgoli/Documents/Projects/react/manager/node_modules/esprima
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

+ react-redux@5.0.6
+ redux@3.7.2
added 5 packages, removed 850 packages and updated 18 packages in 227.611s
```

how can i solve this issue.

**Comment by kenany** [comment] 2017-10-09 15:36
Sounds like a duplicate of https://github.com/npm/npm/issues/17379.

**Closed as completed by kenany** 2017-10-09 15:36 UTC
Labels: support, npm5

**Comment by Imran-ss** [comment] 2017-11-14 04:15
Run `npm install` again, it will work.
