### ISSUE TITLE
Info, rather than Warn, when skipping packages not suitable to target OS

### ISSUE THREAD

**Issue by mikemaccana** [npm/npm#11632] opened 2016-02-22 12:12 UTC
Per #10768, many users are confused by the message NPM shows when skipping packages not relevant to target OS:

Currently:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
```

Suggest:

```
npm INFO optional Skipping optional dependency /chokidar/fsevents:
npm INFO notsup Not compatible with your operating system or architecture: fsevents@1.0.7
```

I.e, remove the word 'failed' and use 'INFO' instead of 'WARN'

**Comment by dikiaap** [comment] 2016-02-22 12:23
need label bug and feature-request. :+1:

**Comment by bendavis78** [comment] 2016-04-23 18:32
This should really be a DEBUG level message and not shown at all by default. If an optional dependency isn't meant for my OS, there's no reason I need to know about it. The way the error message is written, it still *looks* like an error. Plus, npm already doesn't tell me whether or not install was successful, so when I get *any* output from npm my first reaction is to think it's an error.

**Comment by simonbuchan** [comment] 2016-05-11 23:46
I'm fine with this being a WARN if it's only shown when it would be installed if it was supported:

```
$ npm i -S glob
test-npm@ C:\code\test-npm
`-- glob@7.0.3
  <snip>
$ npm i
```
Yay, no output when nothing happened!
```
$ npm i -S chokidar
test-npm@ C:\code\test-npm
`-- chokidar@1.5.0
  <snip>
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```
OK, it tried and failed to install something, that's reasonable.
```
$ npm i
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```
Boo! It did nothing, nothing has changed, there's no reason to complain!
```
$ npm i -S object-assign
test-npm@ C:\code\test-npm
`-- object-assign@4.1.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```
Boo! `object-assign` installed fine and problem free, there shouldn't be a warning!

I suggest adding, for a strawman, `_failedDependencies.fsevents: "1.0.12"` to `node_modules/chokidar/package.json` so npm knows at least not to message again, and maybe it can know to not bother trying to install again.

**Comment by jods4** [comment] 2016-05-24 12:54
+1
This should be given a higher priority (the problem exists at least since Dec 2015), especially since it's a trivial fix.

This is not just a semantic / nitpicker question. Using WARN rather than INFO triggers some downstream tooling errors, see the issue Kukkimonsuta linked above. It is highly annoying to see a yellow warning sign in your tools when everything is OK. Moreover, you end up ignoring it, which may hide other issues.

**Comment by bjorngi** [comment] 2016-05-25 16:19
+1

**Comment by Vanuan** [comment] 2016-06-07 21:28
Is is possible to tell npm to stop downloading that package? 

npm info attempt registry request try #1 at 8:48:59 PM
npm http request GET https://registry.npmjs.org/fsevents

It happens on every npm install.

**Comment by gigablox** [comment] 2016-06-07 22:17
Yea this is super obnoxious from a devops perspective. WARN's usually mean I need to investigate something and now I'm deviating build script code to let these types of exceptions run by.

**Comment by maxant** [comment] 2016-06-16 20:31
+1

**Comment by Vanuan** [comment] 2016-06-30 22:05
The problem here is the http fetch, not the warning itself.

Some people suggest using `npm install --no-optional`.

**Comment by shamank** [comment] 2016-08-06 15:03
> This should really be a DEBUG level message and not shown at all by default. If an optional dependency > isn't meant for my OS, there's no reason I need to know about it. The way the error message is written, it > still looks like an error. 

100% right. I'm here because I thought it was an error.

**Comment by Vanuan** [comment] 2016-08-06 21:00
There is a reason. Otherwise you wouldn't know why npm install is so slow.

**Comment by jods4** [comment] 2016-08-07 16:26
@Vanuan 
> The problem here is the http fetch, not the warning itself.

Reading the OP again, I really think this issue is about reporting `WARN` vs `INFO`. 
Maybe you need to open another issue if you have trouble with the http fetch.

And I really wish someone would do something about this! 😡 I really don't like ignoring all warnings when I run my toolchain, it makes me feel that one day I'll have a real problem.

**Comment by Vanuan** [comment] 2016-08-07 19:40
>  it makes me feel that one day I'll have a real problem.

But you do have a real problem. If you want to ignore optional dependencies, use `--no-optional`

**Comment by jods4** [comment] 2016-08-07 23:23
@Vanuan Sorry but I don't get you.
`fsevents` is the implementation strategy of `chokidar` on Mac OS-X, using FSEvents native API. 
I run on Windows, where Chokidar uses another strategy. Where is my real problem?

> If you want to ignore optional dependencies, use `--no-optional`

What if I don't want to ignore all of them? Imagine there is an optional package to use Windows native file watchers, you're telling me that I can't use it?

What if I can't control that flag? As others have mentioned before, `npm` is called by other tools, like Visual Studio.

In the end, the problem is that NPM doesn't follow what is generally considered an ERROR vs a WARNING vs an INFO. And it would be nice to fix it.

**Comment by Vanuan** [comment] 2016-08-08 12:11
I agree, that `--no-optional` is not a best workaround. But hiding a problem is a poor one.

The proper workaround would be that npm somehow remembers which optional dependency installs have already failed and skips trying reinstalling them. We'd still have a warning on the very first `npm install` as package.json format doesn't support platform-specific dependencies, and optional dependencies are being abused.

The solution would be to add support of platform-specific dependencies.

**Comment by rodriguezmilton** [comment] 2016-08-08 13:13
Hi there !
I totally agree with @jods4. 
The best workaround I found is going back to previous versions and wait for npm to solve this problem. I think it's better than `--no-optional`.
Let's wait for them to fix it soon :)

**Comment by rjgotten** [comment] 2016-08-18 08:25
> The proper workaround would be that npm somehow remembers which optional dependency installs have already failed and skips trying reinstalling them. We'd still have a warning on the very first `npm install` as package.json format doesn't support platform-specific dependencies, and optional dependencies are being abused.

And on that very first `npm install` we'd still have downstream tooling break when a warning is output over `stderr`. So no; that's not a proper workaround.

**Comment by Vanuan** [comment] 2016-08-18 13:44
Ok. So there are the following subissues caused by platform (in)compatibility:

1. CI use case (tooling can't ignore a specific warning)
2. Developer use case

    a. developers are confused
    b. `npm install` is longer than needed

**Comment by rjgotten** [comment] 2016-08-18 14:13
> Workaround to the first issue is to patch your tooling

Which is a no-go in case of closed source tooling. E.g. Visual Studio.

**Comment by jods4** [comment] 2016-08-18 14:24
> Workaround to the first issue is to patch your tooling

LOL, seriously? Workaround to NPM raising warnings when they are meaningless is to patch all the tools?
What about patching NPM instead?

**Comment by Vanuan** [comment] 2016-08-18 16:19
That's a difference between workaround and solution.

**Comment by rjgotten** [comment] 2016-08-18 21:27
> change your tooling? :)

You're right. We should all ditch NPM as a package manager and look for a better alternative...

**Comment by isdzulqor** [comment] 2016-08-28 01:12
I got this error too when want to install  `npm install html-webpack-plugin --save-dev` 
![coba](https://cloud.githubusercontent.com/assets/12388558/18030995/e8c864a8-6cf6-11e6-838d-797d0becdbed.png)

`npm install --no-optional` not working. I am using npm version 3.10.3. any solution guys? 
thank you

**Comment by glen-84** [comment] 2016-08-28 12:18
@isdzulqor You can ignore the warnings. This issue is about changing the log level from WARN to INFO (or, better yet, DEBUG, so that they won't even show up by default).

**Comment by lowend** [comment] 2016-09-02 01:27
Thanks for the info.

**Comment by Sidewinder1138** [comment] 2016-09-16 22:19
I want to reiterate and agree with what @bendavis78 said earlier: this is a DEBUG type message and should not be output by npm by default. It serves no purpose for me as a Windows user to see a warning about failing to install an optional mac os package.

**Comment by dandv** [comment] 2016-10-19 05:33
> You're right. We should all ditch NPM as a package manager and look for a better alternative...

[yarn](https://code.facebook.com/posts/1840075619545360) also displays this warning.

**Comment by viridia** [comment] 2016-10-31 05:08
Not to open up a can of worms or anything, but it seems like the 'correct' solution is to have some method of conditional dependencies - a way for a package to indicate that one or more of it's dependencies should not be installed on some platforms. This is not the same as a package describing *itself* as platform specific - a package doesn't know whether it's optional or not, so all it can say is 'if you install me on the wrong platform, that's an error'.

But if you go high enough in the dependency chain, at some point there's some package that knows when the platform-specific package is needed and when it's not. Presumably this package has some conditional logic in it that indicates at runtime whether the dependency should be required or not. But currently there's no way to express that contingency in the package.json language, so the package gets downloaded regardless.

The other alternative would be to remove the platform-specific tag from fsevents and make it 'work' on other platforms in the sense that it's a no-op - it does nothing, but doesn't crash either.

**Comment by torrentx** [comment] 2017-01-04 21:04
Any updates on this? It make npm a no-go until it's corrected.

**Comment by dzift** [comment] 2017-01-09 21:32
"no-go" is too harsh. Just a really annoying cosmetic bug.

**Comment by rjgotten** [comment] 2017-01-10 08:15
It *is* a no-go if this breaks other tooling.

**Comment by legodude17** [comment] 2017-01-10 21:25
How is it not sane to report the a package is not compatible with your operating system? If you want just errors then use `--loglevel=error`.

**Comment by jods4** [comment] 2017-01-10 21:35
@legodude17 this has been discussed times and again in this issue.

It is sane, just not at the warning level. 
Because a warning is something suspicious that you should investigate. Because some tooling reports a bad status when they see warning. Because people stop looking at warnings when there are permanent warnings.
An optional package that is meant for another OS is not a sane warning, just the normal process.
It can be reported at the log, or even better debug, level.

And no, I don't want to mute _all_ warnings. Especially not _legitimate_ warnings that should have caught my attention.
Plus sometimes you can't even set that option, for example when npm is called by tools.

It's unbelievable that this issue is only about a message level, has 88 👍 , has been opened for nearly a year and nobody in NPM org seems to care.

**Comment by legodude17** [comment] 2017-01-10 21:42
As I have said in many issues in the past, the npm team is very small, though a PR to make this happen will be considered.

**Comment by rjgotten** [comment] 2017-01-10 22:23
> the npm team is very small

Which is really not an excuse for putting off this issue for close to a year.

**Comment by oocx** [comment] 2017-01-11 06:30
I submitted a PR for this problem months ago. However, it was not accepted by the npm team and I don't know enough about npm to change my PR as requested by the comments in the PR.

https://github.com/npm/npm/pull/12841

**Comment by legodude17** [comment] 2017-01-13 21:06
@rjgotten getting annoyed won't help anyone. The npm team has a lot of there plate, all of them issues with much more priority then this one.

While I can't force the npm team to do what you want, I can submit a PR for this based on the comments on #12841.

**Comment by rjgotten** [comment] 2017-01-14 15:39
> @legodude17 
> getting annoyed won't help anyone. The npm team has a lot of there plate, all of them issues with much more priority then this one.

Maybe the fact that this issue continues to have people actively complaining, revisiting and looking/asking for status updates and getting annoyed at non-progress should tell you something about changing its assigned priority.

How hard can it be to flip warning level down to debug or log level for this one type of message anyway?
You'd think added real-world value vs time spent would've resulted into this being fast-tracked and resolved *months* ago. Yet here we are...

**Comment by jods4** [comment] 2017-01-14 15:50
NPM team decides their priorities as they see fit, but just saying: on github this is the **top** issue by upvotes (89 right now) and by a fair margin (2nd issue only has 66).

**Comment by WhitneyLand** [comment] 2017-02-20 23:53
Ok let's get down to it.  How much cash would it take for the NPM team to fix or accept the PR for this?  I'm willing to create a bounty.

The sheer amount of wasted time with hundreds or thousands of people stopping work to try and investigate this is just crazy.

**Comment by dandv** [comment] 2017-02-21 01:32
Count me in, but I doubt any amount short of $100k would convince them.

**Comment by simonbuchan** [comment] 2017-02-21 01:50
Just noting, there is already a PR: #12841 (the thread is not that long!)

Before I start, please note I'm only an interested user, I have no special knowledge of the NPM orgs thoughts. The situation AFAICT however, is that the current behavior is (mostly, see my earlier comment) *by design*: `optionalDependencies` *just* means optional *in general*: for example, a `special-xml-parser` might optionally depend on `some-xml-native-parser` that fails to build if you don't have the build dependencies, because it still works, but slower: you definitely want this to be a warning!

The thing that is breaking people here is that e.g. `chokidar` really wants to be able to say "on macOS only, I depend on `fsevents`", which is a new type of dependency in package.json - this is possibly a really freaking big deal, considering how much tooling has built up over the existing spec the work to avoid breaking the whole ecosystem is prohibitive: see the closing comment for #3870 for example.

**Comment by misterfresh** [comment] 2017-03-21 13:10
Why do I get a warning when everything is fine. Seriously this is so annoying, you try to present nodejs as a mature platform in your organization and then this undermines your efforts. Are we all supposed to buy Macbook Pros to avoid this error? Is npm secretly subsidized by Apple? Just asking.

**Comment by MartinJohns** [comment] 2017-03-21 15:00
> Are we all supposed to buy Macbook Pros to avoid this error? Is npm secretly subsidized by Apple? Just asking.

@misterfresh You remind me of [Dances with Smurfs](https://en.wikipedia.org/wiki/Dances_with_Smurfs):

> Cartman makes outrageous claims with no basis for fact under the guise that he is simply asking rhetorical questions and seeking further discussion.

**Comment by legodude17** [comment] 2017-03-23 16:50
@misterfresh It is not an error, it is a warning.

**Comment by helmer** [comment] 2017-05-10 18:46
Updates? Should I expect something from NPM (if not, perhaps close this issue with a resolve of WONTFIX), or should I write my own workaround for my team processes to silence this warning? Just a random thought - npmrc confoption to silence warnings based on ie regex?

+1 to @oocx @ https://github.com/npm/npm/pull/12841
> This is confusing and it trains people to ignore warnings, which might cause them to later overlook a "real" warning.

+1 to @jods4 @ this thread
> Because a warning is something suspicious that you should investigate. Because some tooling reports a bad status when they see warning.

**Comment by Vanuan** [comment] 2017-05-11 14:22
Here's what you could do:

1. Complain
2. Use `--no-optional` on all environments excepts OSX effectively disabling the cause of the warning. 
3. Change log level to error so that you won't see warnings
4. (do nothing) Just ignore this specific warning, fix the tooling

Here's what npm could do:

1. Change optional dependencies and not supported messages from WARN to INFO (what most people want).
2. Implement platform specific dependencies (proper solution)
3. Do nothing

Here's what fsevents could do:

1. Make it not fail on non OSX platforms without any warnings, just INFO message about platform not supported
2. Support more platforms
3. Do nothing

Here's what chokidar could do:

1. Include fsevents code into chokidar
2. Make it non-optional if fsevents supports other platforms or doesn't fail
3. Do nothing

As you can see the preferred choice for all parties is "Complain" and "Do nothing" as it takes the least effort.

**Closed** 2017-06-19 10:08 UTC
Labels: bot-closed, feature-request, platform-integration

**Comment by glen-84** [comment] 2017-06-19 10:31
Maybe the bot shouldn't auto-close issues if they have > X 👍. (more than 0, or 2, or 10)

**Comment by gaearon** [comment] 2017-06-27 14:08
>yarn also displays this warning.

I'm actually not sure if this was an intentional decision.
I filed https://github.com/yarnpkg/yarn/issues/3738 about this.

**Comment by Oduig** [comment] 2017-06-27 14:38
I came across this while cleaning up our build output. Earlier, we almost missed an important error because the logs were full of warning messages and we do not want to turn them off because they, too, can be important. 

Warnings are a quality tool. If the first and most important tool in the chain advises to ignore them, that says something about their quality standards. 

NPM: half the world runs on your software. Your quality and maintenance standards should be higher than anyone elses. The community is willing to help, literally all it needs is your attention. Take it seriously. Reopen this issue and address the concerns.

**Comment by watilde** [comment] 2017-06-30 08:54
I opened PR: https://github.com/npm/npm/pull/17530.

~There is one thing I changed with the original proposal in my pull request. We have `log.info` for sure but it doesn't display `INFO` anymore, so I replaced `info` with `notice`.~

**Comment by jods4** [comment] 2017-07-14 18:27
BTW Yarn just fixed this. In their next release this "warning" will be `info`.
Meanwhile, npm still doesn't care -- even closes the issue -- although it's their top voted issue.

If you can you should switch from NPM to Yarn, it's better in pretty much every regard: speed, determinist install, offline mode, lock file by default, `yarn run` local packages (yeah -- just released `npx`, too late for me).

**Comment by akvadrako** [comment] 2017-09-06 11:01
This issue should be reopened and fixed.

**Comment by mikemaccana** [comment] 2017-09-11 17:14
Confirmed this is fixed in yarn 1.0.1:

    info fsevents@1.1.2: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.

**Comment by whitneyland** [comment] 2017-10-08 18:47
>>BTW Yarn just fixed this. In their next release this "warning" will be info.
>>Meanwhile, npm still doesn't care -- even closes the issue -- although it's their top voted issue.

>>If you can you should switch from NPM to Yarn, it's better in pretty much every regard: speed, 
>>determinist install, offline mode, lock file by default, yarn run local packages (yeah -- just released npx, 
>>too late for me).

@jods4 Interesting response from the NPM team, considering that community feedback is such a powerful tool to maintain momentum of success.  Proactively responding to feedback is usually required to prevent projects from slowly losing relevance, or even eventually failing.

I’ll tell you this, I may have projects that fail, but if they do I guarantee it will never happen for some straightforward issue that is being held up in front of my face by the community.

Btw, thanks for the [yarn](https://yarnpkg.com) recommendation.  It seems to work great as a drop in replacement with no hassles.

**Comment by mborysenko** [comment] 2017-12-09 13:55
Today have updated the npm till the 5.6.0 version and now I'm getting ERR instead of WARN while installing the react-redux package. Some of the dependencies in my project have a dependency on a chokidar. Before I could just ignore that warning but now my builds are failing. --no-optional parameter doesn't help
```
D:\dev\styles-demo>npm install react-redux@latest --save --no-optional
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```
Question: why npm tries to install something that is considered as optional(is installed in defined conditions) or should be installed on a certain platform? Shouldn't it skip it if does not meet conditions?

**Comment by mborysenko** [comment] 2017-12-09 14:23
```
D:\projects\styles-demo>npm install react-redux@latest --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack-env\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
Message when npm of version 5.5.1 is used

**Comment by gaearon** [comment] 2017-12-09 19:03
It's probably better to file a separate bug report for this.
Maintainers typically don't read closed issues.

**Comment by YasharF** [comment] 2017-12-29 08:43
New PR: https://github.com/npm/npm/pull/19198

**Comment by shane-reaume** [comment] 2018-01-26 03:45
@gaearon So this was fixed? I still get errors so maybe we should re-open?

**Comment by jeffvandyke** [comment] 2018-01-31 01:54
Yes, this absolutely should be re-opened. It's labeled and clear, PR #19198 is not merged yet, this issue is clear, and Linux and Windows people have been seeing that wretched `npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents...` for *years* now whenever at least webpack is installed. Still semi-optimistic for a WARN-free `npm install` on popular projects though...

**Comment by YasharF** [comment] 2018-01-31 03:20
In case if anyone is looking for the current state of the issue and haven't had a chance to read all of the related GitHub issues and pull requests, here is a summary:

**The current "open" ticket for this problem seems to be: https://github.com/npm/npm/issues/17466
The current PR for resolving this is: https://github.com/npm/npm/pull/19198**


_Historically from what I gathered:_

- This was initially brought up in Issue https://github.com/npm/npm/issues/8921
- Issue 8921 was closed and then the problem resurfaced and a new GitHub issue was opened for it: Issue https://github.com/npm/npm/issues/10768
- The discussions in Issue 10768 resulted in its replacement with this ticket (aka Issue https://github.com/npm/npm/issues/11632) to capture the actionable item.
- PR https://github.com/npm/npm/pull/12841 was created by a community member to address Issue 11632, but the feedback from the maintainers asked for changes  (https://github.com/npm/npm/pull/12841#issuecomment-226160129) to the PR.
- PR https://github.com/npm/npm/pull/17530 was created by another community member to address the feedback by the maintainers in the prior PR.  More changes were requested by the maintainers, however the PR was closed by the submitter.
- There was no response on this ticket (Issue https://github.com/npm/npm/issues/11632) for a while which resulted in it being autoclosed by a bot.  This resulted in creation of two new GitHub issues by the community, one to ask for this ticket to be reopened (Issue https://github.com/npm/npm/issues/17500), and the other to replace this request: Issue https://github.com/npm/npm/issues/17466
- PR https://github.com/npm/npm/pull/19198 was submitted to address the feedback by the maintainers for the prior PRs.

I know this history list is long and perhaps a sign that some process improvement may be needed, but this is where we are now.  Again:

**The current "open" ticket for this problem seems to be: https://github.com/npm/npm/issues/17466
The current PR for resolving this is: https://github.com/npm/npm/pull/19198**

**Comment by vandyw95** [comment] 2018-02-13 18:18
Y'all gonna face a problem in the future if y'all ignore the "WARN".
Please read it here [#19198](https://github.com/npm/npm/pull/19198#issuecomment-365346816) as how this impact my company apps and of course wasting my time to refactor that done nothing good to fix the bug.
WARN works as it does. It doesn't mean that if your app is fine you can just ignore. It is **NOT** no problem but it **IS** a problem but you just don't know it yet because it hasn't happened yet.

**Comment by vandyw95** [comment] 2018-02-13 18:30
@YasharF -1 for any reason?
Is it wrong if it "WARN"? Because I got more trouble by looking at it only as a (read: ignore) "WARN" not "ERROR", and lower it to "INFO" rather than "WARN"?

**Comment by YasharF** [comment] 2018-02-13 18:41
@vandyw95 you haven't read the discussions and commenting on a closed github issue.

**Comment by vandyw95** [comment] 2018-02-13 18:50
@YasharF  discussions which point to this one in conclusion >> **remove the word 'failed' and use 'INFO' instead of 'WARN'**
And this the [reason](https://github.com/npm/npm/pull/19198#issuecomment-365346816) of my comment about changing "WARN" to "INFO".
And I had read the discussions. If commenting here is wrong why don't you point out your thought [here](https://github.com/npm/npm/pull/19198)? :)
