### ISSUE TITLE
[Install pomelo failure]uid must be an unsigned int

### ISSUE THREAD

**Issue by yanghjmuyi** [npm/npm#14079] opened 2016-09-26 08:58 UTC
dooooota:NodeJs yanghj$ sudo npm install pomelo -g
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pomelo" "-g"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yanghj/Desktop/NodeJs/npm-debug.log

**Comment by KenanY** [comment] 2016-09-26 11:01
Duplicate of https://github.com/npm/npm/issues/13918, I believe.

**Closed by KenanY** 2016-09-26 11:01 UTC
Labels: support
