### ISSUE TITLE
`npm version` doesn't create a commit when in a git submodule.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#8377] opened 2015-05-27 20:17 UTC
I'm in a git submodule of another git project, and the submodule is an npm package with a package.json and everything, but running `npm version patch -m 'v%s'` doesn't create a new commit in the submodule.

Is this by design? Is there a way to make it happen?

**Comment by ktarplee** [comment] 2015-07-22 20:21
GIT uses a different structure for submodules that NPM likely needs to know about to determine if it is in a git repository.  The .git in a submodule is not a directory but rather a file that contains
gitdir: ../.git/modules/uploader

I just got burned by this so it would be nice to fix this.

**Comment by ktarplee** [comment] 2015-07-22 20:27
npm --loglevel verbose version patch

when in a submodule you will se in the log
not tagging in git

The issue is in lib/version.js:145.  You need to drop the s.isDirectory() from the expression as it is not required to be a directory.  I think it is sufficient that .git exists to claim you are in a GIT repo.

**Comment by zkat** [comment] 2016-02-26 21:41
This is fixed as of #9033 -- thanks for the patch! Took a while for us to notice :P

**Closed by zkat** 2016-02-26 21:41 UTC
Labels: feature-request
