### ISSUE TITLE
EMISSINGARG when doing npm uninstall

### ISSUE THREAD

**Issue by floriansimon1** [npm/npm#11492] opened 2016-02-10 20:50 UTC
Installed on Debian Stretch fetched from deb.nodesource.com.

Kernel: 4.3.0-1-amd64

[npm-debug.log.txt](https://github.com/npm/npm/files/125464/npm-debug.log.txt)

**Comment by floriansimon1** [comment] 2016-02-10 20:54
Note: I didn't have any bacon package. Maybe this happens when you try to delete a package that you don't have installed?

**Comment by watilde** [comment] 2016-02-10 21:36
This may be related to https://github.com/npm/npm/issues/10201

**Comment by othiym23** [comment] 2016-02-12 06:14
@watilde 
> This may be related to #10201

Indeed, and as such I'm going to close this as a duplicate of #10201. Thanks for the pointer! And thanks, @floriansimon1, for the original report!

**Closed by othiym23** 2016-02-12 06:14 UTC

**Comment by watilde** [comment] 2016-02-12 11:54
@othiym23 Many similar issues related missing symlinks are reported actually. https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+EMISSINGARG

could you please check this fix for them? https://github.com/npm/read-package-tree/pull/6
