### ISSUE TITLE
Files excluded by .npmignore are included in `npm pack` tarball

### ISSUE THREAD

**Issue by smikes** [npm/npm#7435] opened 2015-02-23 20:27 UTC
Details here: https://github.com/npm/npm/issues/7030#issuecomment-75600089

Ref Issue #7030

**Comment by mjackson** [comment] 2015-03-17 20:59
@othiym23 The examples I gave in #7030 reproduce this behavior consistently. Do you need something else to repro?

**Comment by julien-f** [comment] 2015-04-01 08:38
I can reproduce  this behavior with npm 2.7.4.

**Comment by gtheraud** [comment] 2015-12-10 09:59
Same issue with npm 2.14.1
I also have missing directories in tarball !

**Comment by mjackson** [comment] 2015-12-23 17:29
Here's how to repro:

```
michael:~/Projects/test-project$ npm -v
2.1.17
michael:~/Projects/test-project$ tree -a
.
├── .npmignore
├── modules
│   ├── __tests__
│   │   └── main-test.js
│   └── main.js
└── package.json

2 directories, 4 files
michael:~/Projects/test-project$ cat package.json 
{
  "name": "test-project",
  "version": "1.0.0",
  "files": [
    "modules"
  ]
}
michael:~/Projects/test-project$ cat .npmignore 
modules/**/__tests__/*-test.js
michael:~/Projects/test-project$ npm pack
test-project-1.0.0.tgz
michael:~/Projects/test-project$ tar -tvf test-project-1.0.0.tgz 
-rw-r--r--  0 501    20         83 Dec 29 11:23 package/package.json
-rw-r--r--  0 501    20         19 Dec 29 11:19 package/modules/main.js
-rw-r--r--  0 501    20         21 Dec 29 11:19 package/modules/__tests__/main-test.js
```

The `files` array includes the `modules` dir, but `modules/**/__tests__/*-test.js` is explicitly ignored in `.npmignore` which means it shouldn't be included in the package. But `npm pack` includes it anyway.

**Comment by taion** [comment] 2016-01-09 21:51
I just hit this as well. Is this intentional, or just a docs error?

**Comment by binki** [comment] 2016-08-24 14:30
@othiym23 There is a repro now, please remove the needs-repro label. Thanks.

**Comment by Turbo87** [comment] 2016-09-17 16:39
this seems to be a duplicate of https://github.com/npm/npm/issues/4479

**Closed** 2017-06-19 10:56 UTC
Labels: bot-closed, needs-repro
