### ISSUE TITLE
Uninstalling Causes Failure on Ubuntu

### ISSUE THREAD

**Issue by ziyadmutawy** [npm/npm#17553] opened 2017-07-01 05:00 UTC
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running `sudo npm uninstall npm -g` it causes the following:
![image](https://user-images.githubusercontent.com/19981991/27759208-ad5f3826-5df8-11e7-8e60-f70822d2cf41.png)

### supporting information:

![image](https://user-images.githubusercontent.com/19981991/27759204-9b6ca81a-5df8-11e7-9045-64500a9a5ebb.png)

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-07-01 15:25
dupe of https://github.com/npm/npm/issues/16738

**Closed as completed by kenany** 2017-07-01 15:25 UTC
Labels: npm5
