### ISSUE TITLE
Cannot find module 'internal/util/types' after upgrading node v8.9.1

### ISSUE THREAD

**Issue by johnsonsamuel** [npm/npm#19166] opened 2017-11-15 11:46 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am unable to run my tests. 

Error 

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/Users/path/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:32:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/path/node_modules/@aos/asi-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

#### How can the CLI team reproduce the problem?
running tests using node - v8.9.1
npm - 5.5.1

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-11-15 11:59
Duplicate of https://github.com/npm/npm/issues/19032.

**Closed as completed by kenany** 2017-11-15 11:59 UTC

**Comment by dorothyDorothy** [comment] 2018-02-09 10:14
I found that I can use npm version 9.0.0 but I had to uninstall gulp-sass and then reinstall it.  All was fine after that.  Possibly you have a npm module that is misbehaving.  Would be great if that could be flagged up in the error message.

**Comment by sharanbm** [comment] 2018-05-09 11:27
Delete npm and npm-cache directories from AppData\Roaming directory on windows if you are facing this problem. 

it worked for me.
