### ISSUE TITLE
does npm behave differently on different platforms?

### ISSUE THREAD

**Issue by zmLGBBM** [npm/npm#10276] opened 2015-11-05 15:50 UTC
Hi, I'm using node on `linux`, and the npm is:
```
➜  ~  npm --version
3.3.6
```
However, npm still tends to put all the dependencies nested in each packages' own node_modules, which gives a very long path. Thought npm 3 was supposed to changed it's behavior, at least it works on my `windows` machine.

PS: After a `npm dedupe`, it will eventually flatten all dependencies into the `node_module` folder.

**Comment by snopeks** [comment] 2015-11-11 18:43
Hi @zmLGBBM , did you by any chance see this in modules installed with npm@2? npm@3 install behavior does flatten dependency trees, but will not automatically go in and change dependency trees installed with npm@2. 

Since it sounds like you've resolved the initial issue with some deduping, I'm going to close this issue, but let me know if you have more questions :)

**Closed by snopeks** 2015-11-11 18:43 UTC
Labels: support

**Comment by zmLGBBM** [comment] 2015-11-12 08:10
@snopeks Hi, nope, I have a fresh installed Ubuntu 15.10 with node 5.0 (with npm version 3.3.6). And after I tried to install some packages like `bower`, it tend to nest all the dependencies under the `node_module` directory under `bower`. Even with the packages I installed globally.

Something like this:
```
/usr/lib/node_modules/bower/node_modules
├── abbrev
│   ├── abbrev.js
│   ├── CONTRIBUTING.md
│   ├── LICENSE
│   ├── package.json
│   ├── README.md
│   └── test.js
├── archy
│   ├── examples
│   │   ├── beep.js
│   │   └── multi_line.js
│   ├── index.js
│   ├── LICENSE
│   ├── package.json
│   ├── readme.markdown
│   └── test
│       ├── beep.js
│       ├── multi_line.js
│       └── non_unicode.js
├── bower-config
│   ├── lib
│   │   ├── Config.js
│   │   └── util
│   │       ├── defaults.js
│   │       ├── expand.js
│   │       ├── paths.js
│   │       ├── proxy.js
│   │       └── rc.js
│   ├── LICENSE
│   ├── node_modules
│   │   ├── graceful-fs
│   │   │   ├── fs.js
│   │   │   ├── graceful-fs.js
│   │   │   ├── legacy-streams.js
│   │   │   ├── LICENSE
│   │   │   ├── package.json
│   │   │   ├── polyfills.js
│   │   │   └── README.md
│   │   ├── optimist
│   │   │   ├── example
│   │   │   │   ├── boolean_double.js
│   │   │   │   ├── boolean_single.js
│   │   │   │   ├── bool.js
│   │   │   │   ├── default_hash.js
│   │   │   │   ├── default_singles.js
│   │   │   │   ├── divide.js
│   │   │   │   ├── line_count.js
│   │   │   │   ├── line_count_options.js
│   │   │   │   ├── line_count_wrap.js
│   │   │   │   ├── nonopt.js
│   │   │   │   ├── reflect.js
│   │   │   │   ├── short.js
│   │   │   │   ├── string.js
│   │   │   │   ├── usage-options.js
│   │   │   │   └── xup.js
│   │   │   ├── index.js
│   │   │   ├── LICENSE
│   │   │   ├── node_modules
│   │   │   │   ├── minimist
│   │   │   │   │   ├── example
│   │   │   │   │   │   └── parse.js
│   │   │   │   │   ├── index.js
│   │   │   │   │   ├── LICENSE
│   │   │   │   │   ├── package.json
│   │   │   │   │   ├── readme.markdown
│   │   │   │   │   └── test
│   │   │   │   │       ├── bool.js
│   │   │   │   │       ├── dash.js
│   │   │   │   │       ├── default_bool.js
│   │   │   │   │       ├── dotted.js
│   │   │   │   │       ├── long.js
│   │   │   │   │       ├── num.js
│   │   │   │   │       ├── parse.js
│   │   │   │   │       ├── parse_modified.js
│   │   │   │   │       ├── short.js
│   │   │   │   │       └── whitespace.js
│   │   │   │   └── wordwrap
......
```

**Comment by zmLGBBM** [comment] 2015-11-16 09:29
@snopeks Hi again, I'm testing it on my windows machine, and it still perform alike--it tend to put everything in the `node_modules` directory instead of flatten them down. (`dedupe` still do the trick.)

This is very confusing since `npm3` claims to perform the flattening.

**Comment by TheBerleyman** [comment] 2016-01-26 21:53
I'm having this issue with npm 3.3.12. node_modules folder didn't exist previously (just had the packages.json). Running 'npm install' downloaded all of the dependencies to my node_modules folder.
It appears the issue is limited to a few modules (ex: bower) that are deeply nesting their dependencies. I could procure a full list of modules, if that would be helpful.
