### ISSUE TITLE
urijs shasum check fails the installation 

### ISSUE THREAD

**Issue by Marius-Stroe** [npm/npm#17108] opened 2017-06-09 07:49 UTC
#### I'm opening this issue because:

I can't create or use a react app anymore as `npm` fails with the following message:

```
...
npm WARN deprecated URIjs@1.16.1: package renamed to "urijs" (lower-case), please update accordingly
npm ERR! Darwin 16.6.0
npm ERR! argv "/opt/twitter_mde/package/nodejs/50795fcb58758f3e10af6e1e6b3b7ced68e9f86dd0d43b8db9e2acb47a04c8db/bin/node" "/opt/twitter_mde/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/5t/mnbrxjw94sz6m_16x5b10jj00000gn/T/npm-58587-74a0ef4c/artifactory.twitter.biz_443/api/npm/js-virtual/URIjs/-/URIjs-1.16.1.
tgz
npm ERR! Expected: edebc678b8b74b26b05d2b481e12383f5ae04b8b
npm ERR! Actual:   859ad31890f5f9528727be89f1932c94fb4731e2
npm ERR! From:     https://artifactory.twitter.biz:443/api/npm/js-virtual/URIjs/-/URIjs-1.16.1.tgz
...
```

[See entire `npm-debug.log`](https://gist.github.com/Marius-Stroe/fffcaa4d210d39a1582896191f23cd2b)

It suddenly started happening when creating a simple react app with `create-react-app dummy_app`. Any help would be appreciated as I can't do anything right now: can't install any `package.json` dependencies.

Thanks!

**Comment by legodude17** [comment] 2017-06-09 20:39
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by iarna** [comment] 2017-06-16 21:01
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

**Closed as completed by iarna** 2017-06-16 21:01 UTC
Labels: support, shasum, bot-closed
