### ISSUE TITLE
npm list ignores --depth=x when used with --parseable

### ISSUE THREAD

**Issue by SrTobi** [npm/npm#11531] opened 2016-02-13 12:23 UTC
`npm list --depth=0` only lists the direct dependencies of the current package.
But `npm list --depth=0 --parseable` prints the directories of all dependencies and completely ignores the `--depth=0`.

**Comment by KenanY** [comment] 2016-02-13 16:40
Duplicate of https://github.com/npm/npm/issues/11495?

**Comment by KenanY** [comment] 2016-05-15 17:54
I believe this was fixed in `npm@2.15.0` and `npm@3.8.2` (https://github.com/npm/npm/pull/11773).

**Comment by KenanY** [comment] 2016-06-28 21:01
Closing as fixed. Can reopen if this is demonstrated to not be the case.

**Closed by KenanY** 2016-06-28 21:01 UTC
