### ISSUE TITLE
NPM dont update dependencies recursively  

### ISSUE THREAD

**Issue by StarpTech** [npm/npm#13096] opened 2016-06-17 22:44 UTC
NPM: 3.8.1
NodeJs: 4.2.3

Structure:

State 1
```
module-a  v2.0.0
 node_modules
   @private
      module-b
        node_modules
          module-c v1.0.14
```

State 2 - after `npm version patch && npm publish` of module-c
```
module-a  v2.0.0
 node_modules
   @private
      module-b
        node_modules
          module-c v1.0.15
```

npm install && npm update in the root of module-a has no effect. module-c will not be updated. I have to call `npm update` in the directory of module-b.

**Comment by othiym23** [comment] 2016-06-17 22:58
If you want npm to update nested or transitive dependencies below the top level, you need to use `--depth`. The default depth for `npm update` is 0 (only top-level dependencies), and in this case, you'd need to use `--depth=2`. npm used to update at all levels simultaneously, and it caused _bad things_ to happen, and also was somewhat surprising to new users, hence the change in defaults. Since the current behavior is by design, I'm going to close this issue. Thanks for your time!

**Closed by othiym23** 2016-06-17 22:58 UTC
Labels: support
