### ISSUE TITLE
Uncaught, Unspecified "error" event

### ISSUE THREAD

**Issue by SanjanaTailor** [npm/npm#16502] opened 2017-05-03 07:42 UTC
[npm.docx](https://github.com/npm/npm/files/972700/npm.docx)
[npm.pdf](https://github.com/npm/npm/files/972701/npm.pdf)

Error: Uncaught, unspecified "error" event. (  Error from Cordova Fetch: Error: cmd: Command failed with exit code 1 Error output:
npm ERR! fetch failed https://github.com/SanjanaTailor/TemplateApp/#Template1
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/SanjanaTailor/TemplateApp/#Template1
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/SanjanaTailor/TemplateApp/#Template1
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/SanjanaTailor/TemplateApp/#Template1"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! fetch failed with status code 406
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sanjana.tailor\.cordova\node_modules\npm-debug.log) 
and npm file log attached here :

**Comment by KenanY** [comment] 2017-05-03 19:14
I cannot reproduce this with `npm@4.6.1`. Any chance you could update your version of `npm`?

I should also note that what you're trying to `npm install` will not work anyways because that git branch does not contain a `package.json` file.

**Comment by SanjanaTailor** [comment] 2017-05-04 10:40
yes, that's right. Package.json is not added, i resolved it. Thank you

**Comment by SanjanaTailor** [comment] 2017-05-04 10:41
Error: Uncaught, unspecified "error" event. (  Error from Cordova Fetch: Failed to get absolute path to installed module)
For this error go to your .cordova directory delete if you have created a template delete it and npm_modules folders needs to delete it. Error will resolved

**Comment by KenanY** [comment] 2017-05-04 14:22
Closing since `npm` issue has been resolved.

**Closed by KenanY** 2017-05-04 14:22 UTC
Labels: support
