### ISSUE TITLE
Error installing typescript@next "uid must be an unsigned int"

### ISSUE THREAD

**Issue by bidkar** [npm/npm#14249] opened 2016-10-12 00:10 UTC
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@3.10.8
3 info using node@v6.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData typescript
8 silly fetchNamedPackageData typescript
9 silly mapToRegistry name typescript
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'typescript',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'typescript',
12 silly mapToRegistry   name: 'typescript',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/typescript
14 verbose request uri https://registry.npmjs.org/typescript
15 verbose request no auth needed
16 info attempt registry request try #1 at 19:02:22
17 verbose request id 565e1ee8028dc0e6
18 verbose etag "6K6M6O4T9HO2EOP3HMMWNDY2N"
19 http request GET https://registry.npmjs.org/typescript
20 http 304 https://registry.npmjs.org/typescript
21 verbose headers { date: 'Wed, 12 Oct 2016 00:02:23 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"6K6M6O4T9HO2EOP3HMMWNDY2N"',
21 verbose headers   age: '214',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lax8622-LAX',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '2',
21 verbose headers   'x-timer': 'S1476230543.136820,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Wed, 12 Oct 2016 00:02:23 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"6K6M6O4T9HO2EOP3HMMWNDY2N"',
22 silly get     age: '214',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lax8622-LAX',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '2',
22 silly get     'x-timer': 'S1476230543.136820,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/typescript from cache
24 verbose get saving typescript to /Users/bidkar/.npm/registry.npmjs.org/typescript/.cache.json
25 verbose correctMkdir /Users/bidkar/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule typescript@2.0.3 checking installable status
39 silly cache add args [ 'typescript', null ]
40 verbose cache add spec typescript
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'typescript',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'typescript',
41 silly cache add   name: 'typescript',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed typescript@latest
43 verbose addNamed "latest" is being treated as a dist-tag for typescript
44 info addNameTag [ 'typescript', 'latest' ]
45 silly mapToRegistry name typescript
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'typescript',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'typescript',
48 silly mapToRegistry   name: 'typescript',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/typescript
50 verbose addNameTag registry:https://registry.npmjs.org/typescript not in flight; fetching
51 verbose get https://registry.npmjs.org/typescript not expired, no request
52 silly addNameTag next cb for typescript with tag latest
53 silly addNamed typescript@2.0.3
54 verbose addNamed "2.0.3" is a plain semver version for typescript
55 silly cache afterAdd typescript@2.0.3
56 verbose afterAdd /Users/bidkar/.npm/typescript/2.0.3/package/package.json not in flight; writing
57 verbose correctMkdir /Users/bidkar/.npm correctMkdir not in flight; initializing
58 verbose afterAdd /Users/bidkar/.npm/typescript/2.0.3/package/package.json written
59 silly loadAllDepsIntoIdealTree Finishing
60 silly loadIdealTree Finishing
61 silly currentTree lib
61 silly currentTree └── typescript@1.8.10
62 silly idealTree lib
62 silly idealTree └── typescript@2.0.3
63 silly generateActionsToTake Starting
64 silly install generateActionsToTake
65 silly generateActionsToTake Finishing
66 silly diffTrees action count 1
67 silly diffTrees update typescript@2.0.3
68 silly decomposeActions action count 8
69 silly decomposeActions fetch typescript@2.0.3
70 silly decomposeActions extract typescript@2.0.3
71 silly decomposeActions test typescript@2.0.3
72 silly decomposeActions preinstall typescript@2.0.3
73 silly decomposeActions build typescript@2.0.3
74 silly decomposeActions install typescript@2.0.3
75 silly decomposeActions postinstall typescript@2.0.3
76 silly decomposeActions finalize typescript@2.0.3
77 silly runTopLevelLifecycles Starting
78 silly executeActions Starting
79 silly install executeActions
80 silly doSerial global-install 0
81 silly doParallel fetch 1
82 verbose correctMkdir /Users/bidkar/.npm/_locks correctMkdir not in flight; initializing
83 verbose lock using /Users/bidkar/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
84 silly doParallel extract 1
85 silly extract typescript@2.0.3
86 verbose unbuild lib/node_modules/.staging/typescript-663f1fa5
87 silly gentlyRm /usr/local/lib/node_modules/.staging/typescript-663f1fa5 is being purged from base /usr/local
88 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/typescript-663f1fa5
89 verbose tar unpack /Users/bidkar/.npm/typescript/2.0.3/package.tgz
90 verbose tar unpacking to /usr/local/lib/node_modules/.staging/typescript-663f1fa5
91 silly gentlyRm /usr/local/lib/node_modules/.staging/typescript-663f1fa5 is being purged
92 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/typescript-663f1fa5
93 silly gunzTarPerm modes [ '755', '644' ]
94 silly gunzTarPerm extractEntry package.json
95 silly gunzTarPerm modified mode [ 'package.json', 438, 420 ]
96 silly gunzTarPerm extractEntry .npmignore
97 silly gunzTarPerm modified mode [ '.npmignore', 438, 420 ]
98 silly gunzTarPerm extractEntry README.md
99 silly gunzTarPerm modified mode [ 'README.md', 438, 420 ]
100 silly gunzTarPerm extractEntry ThirdPartyNoticeText.txt
101 silly gunzTarPerm modified mode [ 'ThirdPartyNoticeText.txt', 438, 420 ]
102 silly gunzTarPerm extractEntry AUTHORS.md
103 silly gunzTarPerm modified mode [ 'AUTHORS.md', 438, 420 ]
104 silly gunzTarPerm extractEntry CONTRIBUTING.md
105 silly gunzTarPerm modified mode [ 'CONTRIBUTING.md', 438, 420 ]
106 silly gunzTarPerm extractEntry CopyrightNotice.txt
107 silly gunzTarPerm modified mode [ 'CopyrightNotice.txt', 438, 420 ]
108 silly gunzTarPerm extractEntry Gulpfile.ts
109 silly gunzTarPerm modified mode [ 'Gulpfile.ts', 438, 420 ]
110 silly gunzTarPerm extractEntry LICENSE.txt
111 silly gunzTarPerm modified mode [ 'LICENSE.txt', 438, 420 ]
112 silly gunzTarPerm extractEntry .mailmap
113 silly gunzTarPerm modified mode [ '.mailmap', 438, 420 ]
114 silly gunzTarPerm extractEntry bin/tsc
115 silly gunzTarPerm modified mode [ 'bin/tsc', 438, 420 ]
116 silly gunzTarPerm extractEntry bin/tsserver
117 silly gunzTarPerm modified mode [ 'bin/tsserver', 438, 420 ]
118 silly gunzTarPerm extractEntry lib/README.md
119 silly gunzTarPerm modified mode [ 'lib/README.md', 438, 420 ]
120 silly gunzTarPerm extractEntry lib/typescript.js
121 silly gunzTarPerm modified mode [ 'lib/typescript.js', 438, 420 ]
122 silly gunzTarPerm extractEntry lib/tsserverlibrary.js
123 silly gunzTarPerm modified mode [ 'lib/tsserverlibrary.js', 438, 420 ]
124 silly gunzTarPerm extractEntry lib/tsserver.js
125 silly gunzTarPerm modified mode [ 'lib/tsserver.js', 438, 420 ]
126 silly gunzTarPerm extractEntry lib/tsc.js
127 silly gunzTarPerm modified mode [ 'lib/tsc.js', 438, 420 ]
128 silly gunzTarPerm extractEntry lib/typescriptServices.js
129 silly gunzTarPerm modified mode [ 'lib/typescriptServices.js', 438, 420 ]
130 silly gunzTarPerm extractEntry lib/lib.es2017.sharedmemory.d.ts
131 silly gunzTarPerm modified mode [ 'lib/lib.es2017.sharedmemory.d.ts', 438, 420 ]
132 silly gunzTarPerm extractEntry lib/lib.es2015.d.ts
133 silly gunzTarPerm modified mode [ 'lib/lib.es2015.d.ts', 438, 420 ]
134 silly gunzTarPerm extractEntry lib/lib.es2015.iterable.d.ts
135 silly gunzTarPerm modified mode [ 'lib/lib.es2015.iterable.d.ts', 438, 420 ]
136 silly gunzTarPerm extractEntry lib/lib.es2015.promise.d.ts
137 silly gunzTarPerm modified mode [ 'lib/lib.es2015.promise.d.ts', 438, 420 ]
138 silly gunzTarPerm extractEntry lib/lib.es2015.proxy.d.ts
139 silly gunzTarPerm modified mode [ 'lib/lib.es2015.proxy.d.ts', 438, 420 ]
140 silly gunzTarPerm extractEntry lib/lib.es2015.reflect.d.ts
141 silly gunzTarPerm modified mode [ 'lib/lib.es2015.reflect.d.ts', 438, 420 ]
142 silly gunzTarPerm extractEntry lib/lib.es2015.symbol.d.ts
143 silly gunzTarPerm modified mode [ 'lib/lib.es2015.symbol.d.ts', 438, 420 ]
144 silly gunzTarPerm extractEntry lib/lib.es2015.symbol.wellknown.d.ts
145 silly gunzTarPerm modified mode [ 'lib/lib.es2015.symbol.wellknown.d.ts', 438, 420 ]
146 silly gunzTarPerm extractEntry lib/lib.es2016.array.include.d.ts
147 silly gunzTarPerm modified mode [ 'lib/lib.es2016.array.include.d.ts', 438, 420 ]
148 silly gunzTarPerm extractEntry lib/lib.d.ts
149 silly gunzTarPerm modified mode [ 'lib/lib.d.ts', 438, 420 ]
150 silly gunzTarPerm extractEntry lib/lib.es2017.d.ts
151 silly gunzTarPerm modified mode [ 'lib/lib.es2017.d.ts', 438, 420 ]
152 silly gunzTarPerm extractEntry lib/lib.es2017.object.d.ts
153 silly gunzTarPerm modified mode [ 'lib/lib.es2017.object.d.ts', 438, 420 ]
154 silly gunzTarPerm extractEntry lib/lib.es2015.generator.d.ts
155 silly gunzTarPerm modified mode [ 'lib/lib.es2015.generator.d.ts', 438, 420 ]
156 silly gunzTarPerm extractEntry lib/lib.es5.d.ts
157 silly gunzTarPerm modified mode [ 'lib/lib.es5.d.ts', 438, 420 ]
158 silly gunzTarPerm extractEntry lib/lib.es6.d.ts
159 silly gunzTarPerm modified mode [ 'lib/lib.es6.d.ts', 438, 420 ]
160 silly gunzTarPerm extractEntry lib/lib.scripthost.d.ts
161 silly gunzTarPerm modified mode [ 'lib/lib.scripthost.d.ts', 438, 420 ]
162 silly gunzTarPerm extractEntry lib/lib.webworker.d.ts
163 silly gunzTarPerm modified mode [ 'lib/lib.webworker.d.ts', 438, 420 ]
164 silly gunzTarPerm extractEntry lib/lib.es2015.core.d.ts
165 silly gunzTarPerm modified mode [ 'lib/lib.es2015.core.d.ts', 438, 420 ]
166 silly gunzTarPerm extractEntry lib/lib.es2015.collection.d.ts
167 silly gunzTarPerm modified mode [ 'lib/lib.es2015.collection.d.ts', 438, 420 ]
168 silly gunzTarPerm extractEntry lib/tsserverlibrary.d.ts
169 silly gunzTarPerm modified mode [ 'lib/tsserverlibrary.d.ts', 438, 420 ]
170 silly gunzTarPerm extractEntry lib/lib.dom.iterable.d.ts
171 silly gunzTarPerm modified mode [ 'lib/lib.dom.iterable.d.ts', 438, 420 ]
172 silly gunzTarPerm extractEntry lib/typescript.d.ts
173 silly gunzTarPerm modified mode [ 'lib/typescript.d.ts', 438, 420 ]
174 silly gunzTarPerm extractEntry lib/lib.dom.d.ts
175 silly gunzTarPerm modified mode [ 'lib/lib.dom.d.ts', 438, 420 ]
176 silly gunzTarPerm extractEntry lib/typescriptServices.d.ts
177 silly gunzTarPerm modified mode [ 'lib/typescriptServices.d.ts', 438, 420 ]
178 silly gunzTarPerm extractEntry lib/lib.es2016.d.ts
179 silly gunzTarPerm modified mode [ 'lib/lib.es2016.d.ts', 438, 420 ]
180 silly gunzTarPerm extractEntry test.config
181 silly gunzTarPerm modified mode [ 'test.config', 438, 420 ]
182 verbose stack TypeError: uid must be an unsigned int
182 verbose stack     at TypeError (native)
182 verbose stack     at Object.fs.chown (fs.js:1190:11)
182 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
182 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
182 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
182 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
182 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
182 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
183 verbose cwd /Applications/XAMPP/xamppfiles/htdocs/meeser.sencha
184 error Darwin 16.0.0
185 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "typescript"
186 error node v6.7.0
187 error npm  v3.10.8
188 error uid must be an unsigned int
189 error If you need help, you may report this error at:
189 error     <https://github.com/npm/npm/issues>
190 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2016-10-12 01:15
Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-10-12 01:15 UTC
Labels: support
