### ISSUE TITLE
npm license has expired : yosay when trying to install generator-ractive

### ISSUE THREAD

**Issue by troubadorian** [npm/npm#8631] opened 2015-06-21 23:17 UTC
I am on v0.12.4 of node

```
==> node -v
v0.12.4
```

When I try to install generator-ractive

````
==> npm install -g generator-ractive
npm ERR! tar.unpack untar error /home/ubuntu/.npm/generator-ractive/0.2.0/package.tgz
npm ERR! Linux 3.11.0-15-generic
npm ERR! argv "/home/ubuntu/.nvm/v0.12.4/bin/node" "/home/ubuntu/.nvm/v0.12.4/bin/npm" "install" "-g" "generator-ractive"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /home/ubuntu/npm/lib/node_modules/generator-ractive
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/home/ubuntu/npm/lib/node_modules/generator-ractive'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/home/ubuntu/npm/lib/node_modules/generator-ractive']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/ubuntu/npm/lib/node_modules/generator-ractive',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/ubuntu/npm/lib/node_modules/generator-ractive',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/home/ubuntu/.nvm/v0.12.4/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/home/ubuntu/.nvm/v0.12.4/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/Sites/www.ageofmachine.com/public_html/npm-debug.log


==> sudo npm install -g generator-ractive
npm ERR! Linux 3.11.0-15-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-ractive"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code E402

npm ERR! npm license has expired : yosay
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by mejamiewilson** [comment] 2015-06-21 23:21
I've got exactly the same issue just happening with 'elementtree'

**Comment by sir-dunxalot** [comment] 2015-06-21 23:22
This is occurring on new Travis CI builds. Started about 5 mins ago. https://travis-ci.org/sir-dunxalot/ember-travis-status/jobs/67771945

**Comment by Raynos** [comment] 2015-06-21 23:23
Seeing this problem too.

**Comment by Raynos** [comment] 2015-06-21 23:23
Looks like travis might be talking to npm enterprise ?

**Comment by vcczh** [comment] 2015-06-21 23:23
+1

**Comment by artoartnik** [comment] 2015-06-21 23:23
Got the same issue in Circle CI, it's probably something to do with the npm service?

**Comment by corbinu** [comment] 2015-06-21 23:23
Same issue in the node:12.4 docker container

**Comment by mooce** [comment] 2015-06-21 23:23
Same issue as of a few minutes ago

**Comment by AdrianRossouw** [comment] 2015-06-21 23:23
yup. me three. works locally.

I was also doing npm install -g npm, in my .travis.yml.

**Comment by Raynos** [comment] 2015-06-21 23:24
```sh
npm ERR! Error: npm license has expired : ldjson-stream
npm ERR!     at RegClient.<anonymous> (/home/raynos/projects/nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/home/raynos/projects/nvm/v0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/home/raynos/projects/nvm/v0.10.32/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/raynos/projects/nvm/v0.10.32/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/raynos/projects/nvm/v0.10.32/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "node" "/home/raynos/projects/nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/raynos/uber/tchannel/node
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! 
```

https://gist.github.com/Raynos/57a455cf420c0a227bee

This is a problem with npm@1.4.28

**Comment by Raynos** [comment] 2015-06-21 23:25
Can reproduce locally. Getting a bunch of 402 HTTP exceptions from the registry.

**Comment by Raynos** [comment] 2015-06-21 23:26
Does not happen with npm@2.7.4

**Comment by Raynos** [comment] 2015-06-21 23:26
No wait...

```
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/home/raynos/projects/nvm/v0.10.32/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.7.4
npm ERR! code E402

npm ERR! npm license has expired : portscanner
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raynos/uber/tchannel/node/npm-debug.log
```

**Comment by zladuric** [comment] 2015-06-21 23:26
+1, a lot of expired licenses reported, for unexpected stuff, like mongoose and mpromise.
Npm 2.11.0.

**Comment by mjreich** [comment] 2015-06-21 23:26
+1 - big issue breaking production deploys/rollbacks.

**Comment by garedean** [comment] 2015-06-21 23:27
Running into this issue. Happy to see I'm not the only one.

**Comment by pcothenet** [comment] 2015-06-21 23:27
+1

**Comment by christian-beeke** [comment] 2015-06-21 23:28
+1

**Comment by rf** [comment] 2015-06-21 23:28
+1

**Comment by danpaz** [comment] 2015-06-21 23:28
+2

**Comment by francis-liberty** [comment] 2015-06-21 23:28
+1

**Comment by paulshapiro** [comment] 2015-06-21 23:30
+2

**Comment by brann** [comment] 2015-06-21 23:30
Getting this too in our docker CI builds:

Step 28 : RUN npm install uglify-js -g  ---> Running in fe5a1fff929a npm ERR! Error: npm license has expired : source-map
...
npm ERR! System Linux 3.19.8-ci npm 
ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "uglify-js" "-g" npm 
ERR! cwd /app npm 
ERR! node -v v0.10.38 npm 
ERR! npm -v 1.4.28 npm 
ERR! not ok code 0

second build a couple of minutes later has just worked. so not sure if fixed, or intermittent...

**Comment by hayesgm** [comment] 2015-06-21 23:30
Same here with CircleCI / Heroku builds

**Comment by Raynos** [comment] 2015-06-21 23:32
```
HTTP response statsuCode 402
HTTP response headers    { 'content-type': 'application/json',
     'cache-control': 'max-age=60',
     'content-length': '35',
     'accept-ranges': 'bytes',
     date: 'Sun, 21 Jun 2015 23:30:09 GMT',
     via: '1.1 varnish',
     connection: 'keep-alive',
     'x-served-by': 'cache-lax1421-LAX',
     'x-cache': 'MISS',
     'x-cache-hits': '0',
     'x-timer': 'S1434929409.460152,VS0,VE71' },
HTTP response body: {"error":"npm license has expired"}
```

**Comment by poteto** [comment] 2015-06-21 23:33
CircleCI is failing for us too.

**Comment by vjpr** [comment] 2015-06-21 23:34
+1

**Comment by qimingfang** [comment] 2015-06-21 23:35
+1

**Comment by sk-** [comment] 2015-06-21 23:36
+1

**Comment by andyyykerr** [comment] 2015-06-21 23:36
+1

**Comment by daggmano** [comment] 2015-06-21 23:36
+1

**Comment by danielfariati** [comment] 2015-06-21 23:36
+1

**Comment by metalaureate** [comment] 2015-06-21 23:37
+1

**Comment by salbahra** [comment] 2015-06-21 23:37
+1

**Comment by mrhota** [comment] 2015-06-21 23:37
Stop with the +1. Jesus. You're making it harder to find substantive information. This isn't reddit. Developers should know better.

First noticed this about 45 minutes ago.
vagrant machine, node 0.10.38 and npm 1.4.28

```
npm WARN package.json karma-coffee-preprocessor@0.2.1 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
npm ERR! Error: npm license has expired : stringmap
npm ERR!     at RegClient.<anonymous> (/home/vagrant/.nvm/v0.10.38/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/home/vagrant/.nvm/v0.10.38/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/home/vagrant/.nvm/v0.10.38/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/vagrant/.nvm/v0.10.38/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/vagrant/.nvm/v0.10.38/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-49-generic
npm ERR! command "/home/vagrant/.nvm/v0.10.38/bin/node" "/home/vagrant/.nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/portal
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by Vykook** [comment] 2015-06-21 23:38
+1

**Comment by preetampvp** [comment] 2015-06-21 23:38
+1

**Comment by Laurian** [comment] 2015-06-21 23:39
CodeShip builds failing too

**Comment by salbahra** [comment] 2015-06-21 23:39
Also seeing this in Travis-CI. Link to specific build failure: https://travis-ci.org/OpenSprinkler/OpenSprinkler-App/builds/67771861

Error:
`
-|npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.0
npm ERR! code E402
npm ERR! npm license has expired : blanket
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/travis/build/OpenSprinkler/OpenSprinkler-App/npm-debug.log
The command "npm install" failed and exited with 1 during .
`

**Comment by diunko** [comment] 2015-06-21 23:39
$ npm -v
2.11.2
$ node -v
v0.10.38

**Comment by othiym23** [comment] 2015-06-21 23:40
@seldo is taking a look at this right now. It's a serious issue, but at this point, adding +1s just adds noise for everybody, so if you could hold off, I think everyone would appreciate it.

**Comment by soutarm** [comment] 2015-06-21 23:40
+1

**Comment by jscn** [comment] 2015-06-21 23:40
This is also affecting local Docker builds for me:
```
npm ERR! Error: npm license has expired : fstream
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-55-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /app
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by daggmano** [comment] 2015-06-21 23:40
As a workaround, I kept repeating the same install command until the package was installed (xconsole.io in my case).  Looks like each run through fails on a different package.

**Comment by othiym23** [comment] 2015-06-21 23:42
Quoting @seldo on Twitter just now:

> Still working out what's going on here. Can you try running npm login again? That may resolve it.

**Comment by jscn** [comment] 2015-06-21 23:44
Initially it was failing on the same package for me each time, but like @daggmano reported above, it now seems to be failing on a different package each time.

**Comment by Raynos** [comment] 2015-06-21 23:44
I'm seeing installs working locally with npm@2.7.4 but I still see 402s; looks like npm-client does retries

https://gist.github.com/Raynos/269330470b6d055025c9

**Comment by patrickarlt** [comment] 2015-06-21 23:46
Installs worked locally for me on npm@2.5.1 (yeah I know) after upgrading ti appears to fail on random modules. Running `npm login` then `npm install` does not appear to work.

**Comment by mirrr** [comment] 2015-06-21 23:46
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code E402
...

**Comment by othiym23** [comment] 2015-06-21 23:46
It looks like the user cache in one of our data centers is down at the moment, which is why retries will succeed (as requests get routed to different availability zones). It's probably best to hold off on installing until we get the situation resolved, because until that's fixed, everything's going to be a bit of a crapshoot.

**Comment by Raynos** [comment] 2015-06-21 23:46
Same thing with npm@1.4.28 retries seem to make it work but getting 402 in the background

https://gist.github.com/Raynos/4a6bb8c1bdbaa7e1badd

**Comment by Raynos** [comment] 2015-06-21 23:50
It's non-deterministic locally because of npm client cache interaction. If clear cache it takes about 10 installs to succeed and then succeeds more aggressively;

Production and CI failures fail a lot more because travis installs with an empty npm cache.

**Comment by paralin** [comment] 2015-06-21 23:52
Do we have an ETA on a fix for this?

**Comment by serapath** [comment] 2015-06-21 23:53
> Still working out what's going on here. Can you try running npm login again? That may resolve it.

Did that, but did not help.
`npm install -g cordova` fails with:
```bash
...
npm ERR! node v2.0.0
npm ERR! npm  v2.11.1
npm ERR! code E402

npm ERR! npm license has expired : cordova-registry-mapper
...
```
after re-login it failed with:
```bash
...
npm ERR! node v2.0.0
npm ERR! npm  v2.11.1
npm ERR! code E402

npm ERR! npm license has expired : hosted-git-info
....
```

**Comment by serapath** [comment] 2015-06-21 23:55
just tried again and this time it worked

**Comment by othiym23** [comment] 2015-06-21 23:55
> Do we have an ETA on a fix for this?

No. We're still figuring out the source of the issue within our infrastructure. Once that's done, fixing the should be relatively quick, but we still haven't identified the root cause of the outage.

**Comment by Raynos** [comment] 2015-06-21 23:57
They are all working on it; It will be fixed.

In the meanwhile; install from any of the many archives.

`npm install --registry=http://archive.uber.com/npm` works just fine for me.

**Comment by paralin** [comment] 2015-06-21 23:58
@Raynos Uber has an npm mirror? Cool. Thanks for the info.

**Comment by formula1** [comment] 2015-06-22 00:00
Another work around is to add individual modules to the cache. The whole of npm doesn't seem down just certian parts. However I'll probably be using the uber archive instead

**Comment by othiym23** [comment] 2015-06-22 00:02
We've rebooted the server with the failing authorization service, and believe that everything is once again functioning as expected. Please let us know if you notice any further breakage, but in the absence of further reports, we believe this incident is resolved. Sorry for disrupting your Sundays, everybody!

**Comment by Raynos** [comment] 2015-06-22 00:03
`npm cache clear && npm install`.

All 402s are gone. looks clean on my end.

**Comment by armab** [comment] 2015-06-22 00:03
Retried install a couple of seconds ago and it worked for me.

**Comment by phizch** [comment] 2015-06-22 00:03
Works for me now!! Thanks


"Good" that I'm not the only one with the issue. First time ever I try to use node.js, and I got this error :-&

npm install -g express
npm install -g express-generator
express myExpressApp
cd myExpressApp
npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code E402

npm ERR! npm license has expired : raw-body

**Closed by othiym23** 2015-06-22 00:02 UTC
Labels: bug, next-patch, registry

**Comment by sebajs** [comment] 2015-06-22 00:07
Thank you guys!

**Comment by Raynos** [comment] 2015-06-22 00:07
Thanks @othiym23 for resolving the issue.

**Comment by ianbelcher** [comment] 2015-06-22 00:08
Confirming that I'm no longer getting this error. Thanks for the quick work!

Will have to remember the --registry trick if there are future issues too.

**Comment by othiym23** [comment] 2015-06-22 00:14
Locking this just to keep it from getting spammed to heck and gone. Thanks to everyone for the prompt heads-up that something was busted!
