### ISSUE TITLE
provide npm client a forced way to always GET packages from a specific registry, no matter what the package metadata suggests

### ISSUE THREAD

**Issue by peterlynch** [npm/npm#6445] opened 2014-10-09 14:31 UTC
Creating new issue based on feedback in 
https://github.com/npm/npm/issues/3581#issuecomment-58516251

Also see #6444

- npm shrinkwrap creates metadata that explicitly includes a resolved field
- an npm client that attempts to resolve dependencies from this package will attempt by default to download from the complete URL specified in resolved field.

Problem:
- where a package is resolved from should be in full control of the npm client, not the metadata

----

Hardcoding full URLs that could go away at any time inside a dependency metadata is a design flaw with NPM.

If the intent of the resolved field was to force dependencies to be retrieved from a private npm repo, then the cart was put before the horse. The npm client should instead fully control where dependencies are asked from. A package should only define what to ask for (package + version/version range).

Other dependency tools have learned this the hard way. Maven, Gradle, Ivy, etc all give the client full control over where to get artifacts.

Private npm repositories behind firewalls are becoming more common. By hardcoding complete URLs to registry.npmjs.org inside shrinkwrap json, you are forcing npm clients to ignore your shrinkwrap file. Is that a good thing?

A client can ignore the shrinkwrap json file ( and therefore the resolved field ) by using npm c set shrinkwrap false. However, does this not also ignore perhaps useful version specification inside the shrinkwrap file?

Please:

- provide npm client a forced way to always GET packages from a specific registry, no matter what the package metadata suggests

**Comment by sophister** [comment] 2015-12-30 11:36
problem still exists, 1 year later...
plz, plz, fix add this feature

**Comment by othiym23** [comment] 2016-09-16 20:59
I'm going to close this as a duplicate of #6324, and have added a [new comment](https://github.com/npm/npm/issues/6324#issuecomment-247707225) that reflects the specific requirements of an environment described in the original post here. My guess is that this won't land until `npm@5`, which is intended to be dedicated to substantially improving npm's dependency locking functionality. Thanks for your time and your patience!

**Closed by othiym23** 2016-09-16 20:59 UTC
Labels: feature-request, shrinkwrap
