### ISSUE TITLE
`npm install` doesn't notice when changes have been made to a local dependency

### ISSUE THREAD

**Issue by gaye** [npm/npm#8480] opened 2015-06-06 13:14 UTC
Suppose I have a package a where `a/package.json` looks like

```
{
  "name": "a",
  "version": "0.0.1",
  "dependencies": {
    "b": "file:./b"
  }
}
```

and depends on a package b where `a/b/package.json looks like

```
{
  "name": "b",
  "version": "0.0.1"
}
```

Running `npm install` on npm >= 2 works as expected. But then if I make changes within `a/b/` (or its local dependencies for that matter) and run `npm install` again, the changes aren't propagated to `a/node_modules`.

I've written a small, stopgap solution [here](https://github.com/gaye/npmr) that plays nicer with local modules.

**Comment by iarna** [comment] 2016-02-23 22:05
I'm closing this as a duplicate of https://github.com/npm/npm/issues/8422

**Comment by iarna** [comment] 2016-02-23 22:08
This is the same as https://github.com/npm/npm/issues/9073 and my comments there stand, while the core team too would like npm to do this, we unfortunately won't have the resources to available to work on it this year. As such, I'm going to close this, but if you wanted to make a go at a patch to npm itself, it would be welcome.

**Closed by iarna** 2016-02-23 22:08 UTC
Labels: feature-request, patch-welcome
