### ISSUE TITLE
Can not update npm

### ISSUE THREAD

**Issue by churre9** [npm/npm#10058] opened 2015-10-21 07:45 UTC
I'm trying to update npm to the new version and I obtain a strange error (attached error.png)
I also include npm-debug.log file for more info.

![error](https://cloud.githubusercontent.com/assets/15227234/10630531/70bf8bea-77d7-11e5-9a43-67f7596a7d19.PNG)

**Comment by KenanY** [comment] 2015-10-21 14:48
@churre9 Hmm, could you upload the `npm-debug.log` as a [gist](https://gist.github.com/) so that I can take a look? There must be a `package.json` somewhere with a `"name"` property of "$JordiView", which is an invalid name.

**Comment by KenanY** [comment] 2016-06-07 18:35
@churre9 It has been several months with no reply from you. Are you still seeing this issue?

**Comment by KenanY** [comment] 2016-06-28 19:53
Closing as abandoned and not a bug with `npm`.

**Closed by KenanY** 2016-06-28 19:53 UTC
Labels: support, windows
