### ISSUE TITLE
npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xereda** [npm/npm#10033] opened 2015-10-19 17:50 UTC
I am unable to update the npm packages. Please find attached log.

resume:

```
npm WARN install:array-differ ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/verb/node_modules/template/node_modules/load-templates/node_modules/map-files/node_modules/globby/node_modules/array-differ' -> '/usr/local/lib/node_modules/update/node_modules/extract-comments/node_modules/array-differ'
npm WARN install:array-uniq ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/verb/node_modules/template/node_modules/load-templates/node_modules/map-files/node_modules/globby/node_modules/array-union/node_modules/array-uniq' -> '/usr/local/lib/node_modules/update/node_modules/extract-comments/node_modules/array-uniq'
npm WARN install:array-unique ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/filter-array/node_modules/array-unique' -> '/usr/local/lib/node_modules/update/node_modules/filter-array/node_modules/array-unique'
npm WARN install:minimatch ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/glob-stream/node_modules/minimatch' -> '/usr/local/lib/node_modules/update/node_modules/glob-stream/node_modules/minimatch'
npm WARN install:has-value ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/has-any-deep/node_modules/has-value' -> '/usr/local/lib/node_modules/update/node_modules/has-any-deep/node_modules/has-value'
npm WARN install:export-files ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/verb/node_modules/helper-license/node_modules/markdown-utils/node_modules/export-files' -> '/usr/local/lib/node_modules/update/node_modules/helper-related/node_modules/export-files'
npm WARN install:is-number ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/helper-related/node_modules/is-number' -> '/usr/local/lib/node_modules/update/node_modules/helper-related/node_modules/is-number'
npm WARN install:relative ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/js-comments/node_modules/relative' -> '/usr/local/lib/node_modules/update/node_modules/js-comments/node_modules/relative'
npm WARN install:object.omit ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/load-templates/node_modules/object.omit' -> '/usr/local/lib/node_modules/update/node_modules/load-templates/node_modules/object.omit'
npm WARN install:object.pick ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/load-templates/node_modules/object.pick' -> '/usr/local/lib/node_modules/update/node_modules/load-templates/node_modules/object.pick'
npm WARN install:option-cache ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/load-templates/node_modules/option-cache' -> '/usr/local/lib/node_modules/update/node_modules/load-templates/node_modules/option-cache'
npm WARN install:ansi-styles ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/verb/node_modules/helper-apidocs/node_modules/js-comments/node_modules/lodash-helpers/node_modules/chalk/node_modules/ansi-styles' -> '/usr/local/lib/node_modules/update/node_modules/logging-helpers/node_modules/ansi-styles'
npm WARN install:ms ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/update/node_modules/lookup-path/node_modules/ms' -> '/usr/local/lib/node_modules/update/node_modules/lookup-path/node_modules/ms'
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm" "to" "update"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.5

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xereda/Sites/giceruttiapp/npm-debug.log
```

Jackson

**Comment by KenanY** [comment] 2015-10-19 18:08
This might be another instance of https://github.com/npm/npm/issues/9224.

**Comment by othiym23** [comment] 2015-10-19 18:23
I think you're right, @KenanY, so I'm going to close this as a duplicate of #9224, but also:

```
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm" "to" "update"
```

If you want to update npm, @xereda, you want to run `npm install -g npm` instead of `npm install -g npm to update`. Also, if you run `npm install -g npm` again, it should run without error this time.

**Closed by othiym23** 2015-10-19 18:23 UTC
