### ISSUE TITLE
Error: Cannot find module 'npm-registry-client' when using npm

### ISSUE THREAD

**Issue by hakimelek** [npm/npm#10498] opened 2015-11-20 17:36 UTC
I was trying to fix a broken install of npm, I had uninstalled node, reinstalled it but I was still having the same problem. It is impossible to use any npm command without having this error: 

```
module.js:340
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/username/.node/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

All the solutions out there did not solve my problem.

**Comment by othiym23** [comment] 2015-11-20 17:48
Closing as a duplicate of #10394, which tells you how to work around this bug.

**Closed by othiym23** 2015-11-20 17:48 UTC
Labels: bug

**Comment by hakimelek** [comment] 2015-11-20 18:31
I did not get it working. I have tried to remove any node node_modules[following this](http://stackoverflow.com/a/11178106).  Then reinstalled nodejs from the stable version on the website. I am still having the same problem. I cannot even check which version of npm I am using.

**Comment by gabovanlugo** [comment] 2015-11-22 10:02
Same thing here.

```
Last login: Sun Nov 22 03:57:12 on ttys001
~                                                                                                                                                          3:59
🍔  > npm
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/gabo/.npm-packages/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by hakimelek** [comment] 2015-11-22 19:27
try to remove nodejs and rm -r ~/.node/bin/npm , then install again the official nodejs

**Comment by amonnphillip** [comment] 2016-01-18 23:18
I resolved this issue by simply making sure the npm cache was empty, making sure I had the latest npm, and then installing the missing module.

npm cache-clean
npm -g install npm
npm install -g npm-registry-client

all done in a cmd window with admin privileges
