### ISSUE TITLE
error initializing command 

### ISSUE THREAD

**Issue by guru4rmzion** [npm/npm#13818] opened 2016-08-30 21:40 UTC
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32> cd/

C:\>npm install -g react-native-cli
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\prompt\-\prompt-0.2.14.tgz.2757462651' -> 'C:\Users\Hannah\AppData\Loca
l\Temp\npm-1992-5da9ebbb\registry.npmjs.org\prompt\-\prompt-0.2.14.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\chalk\-\chalk-1.1.3.tgz.1188590232' -> 'C:\Users\Hannah\AppData\Local\T
emp\npm-1992-5da9ebbb\registry.npmjs.org\chalk\-\chalk-1.1.3.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\minimist\-\minimist-1.2.0.tgz.1758010077' -> 'C:\Users\Hannah\AppData\L
ocal\Temp\npm-1992-5da9ebbb\registry.npmjs.org\minimist\-\minimist-1.2.0.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\has-ansi\-\has-ansi-2.0.0.tgz.3201091987' -> 'C:\Users\Hannah\AppData\L
ocal\Temp\npm-1992-5da9ebbb\registry.npmjs.org\has-ansi\-\has-ansi-2.0.0.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\supports-color\-\supports-color-2.0.0.tgz.3489774787' -> 'C:\Users\Hann
ah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.npmjs.org\supports-color\-\supp
orts-color-2.0.0.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\escape-string-regexp\-\escape-string-regexp-1.0.5.tgz.2845427727' -> 'C
:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.npmjs.org\escape-st
ring-regexp\-\escape-string-regexp-1.0.5.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\read\-\read-1.0.7.tgz.1381931836' -> 'C:\Users\Hannah\AppData\Local\Tem
p\npm-1992-5da9ebbb\registry.npmjs.org\read\-\read-1.0.7.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\revalidator\-\revalidator-0.1.8.tgz.2937859759' -> 'C:\Users\Hannah\App
Data\Local\Temp\npm-1992-5da9ebbb\registry.npmjs.org\revalidator\-\revalidator-0
.1.8.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\has-ansi\-\has-ansi-2.0.0.tgz.60207873' -> 'C:\Users\Hannah\AppData\Loc
al\Temp\npm-1992-5da9ebbb\registry.npmjs.org\has-ansi\-\has-ansi-2.0.0.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\supports-color\-\supports-color-2.0.0.tgz.4191536375' -> 'C:\Users\Hann
ah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.npmjs.org\supports-color\-\supp
orts-color-2.0.0.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\escape-string-regexp\-\escape-string-regexp-1.0.5.tgz.159585258' -> 'C:
\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.npmjs.org\escape-str
ing-regexp\-\escape-string-regexp-1.0.5.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.n
pmjs.org\revalidator\-\revalidator-0.1.8.tgz.3512889026' -> 'C:\Users\Hannah\App
Data\Local\Temp\npm-1992-5da9ebbb\registry.npmjs.org\revalidator\-\revalidator-0
.1.8.tgz'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli
"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry.npmj
s.org\supports-color\-\supports-color-2.0.0.tgz.3399438530
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\Hannah\AppData\Local\T
emp\npm-1992-5da9ebbb\registry.npmjs.org\supports-color\-\supports-color-2.0.0.t
gz.3399438530' -> 'C:\Users\Hannah\AppData\Local\Temp\npm-1992-5da9ebbb\registry
.npmjs.org\supports-color\-\supports-color-2.0.0.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by busches** [comment] 2016-09-10 10:53
Duplicate of https://github.com/npm/npm/issues/8564 @KenanY

**Comment by KenanY** [comment] 2016-09-10 14:39
Closing as a duplicate.

**Closed by KenanY** 2016-09-10 14:39 UTC
