### ISSUE TITLE
pm is not installing cordova 

### ISSUE THREAD

**Issue by Abdollahd** [npm/npm#10039] opened 2015-10-20 14:19 UTC

**Comment by KenanY** [comment] 2015-10-20 15:21
@Abdollahd So is this `pm`'s fault or what? This is way too ambiguous. You have not provided enough information for me to even understand what the issue is.

If `npm` is throwing an error, then a `npm-debug.log` file should be generated in your current working directory. You can upload the file as a [gist](https://gist.github.com/) so that I can take a took.

If you think `npm` is doing something incorrectly, then please describe exactly what commands you are running and what you _expect_ to happen as a result of running those commands. This way, I can see if your reasoning is sound and whether or not this is actually an issue with `npm`.

**Comment by KenanY** [comment] 2016-06-07 18:32
@Abdollahd It has been several months now with no response from you... it is still impossible for me to provide any solutions for your problem since no `npm-debug.log` file has been provided despite all the time that has passed. Are you still seeing this issue?

**Comment by KenanY** [comment] 2016-06-28 19:54
Closing as abandoned.

**Closed by KenanY** 2016-06-28 19:54 UTC
Labels: support
