### ISSUE TITLE
"npm run build" command in Ubuntu 16.04

### ISSUE THREAD

**Issue by ManasRanjanSahoo** [npm/npm#13664] opened 2016-08-13 17:38 UTC
When i ran this command "npm run build" in Ubuntu 16.04 getting this error
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/manas/reactApp/npm-debug.log
root@manas-HP-Notebook:/home/manas/reactApp# npm cache clean
root@manas-HP-Notebook:/home/manas/reactApp# npm run build
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/manas/reactApp/npm-debug.log

This is what in npm-debug.log file.
----------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/share/npm/node_modules/read-package-json/read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (/usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd /home/manas/reactApp
6 error Linux 4.4.0-31-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
8 error node v4.2.6
9 error npm  v3.5.2
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Please help me..

**Comment by KenanY** [comment] 2016-08-13 20:13
@ManasRanjanSahoo 

```
npm ERR! missing script: build
```

Do you have a `"build"` script defined in your `package.json`?

**Comment by ManasRanjanSahoo** [comment] 2016-08-14 04:58
Hi Kenan, First of all many many thanks for your reply. And about the build script, No it is not in my package.json. This is what in my package.json. 

{
  "name": "manas",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --hot"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.3.0",
    "react-dom": "^15.3.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1"
  }
}

I searched in google and found to add build script like this
    "build": "browserify index.js > myproject.min.js",

It should be like this or something else...

As am a beginner to it, so if you could please guide me, it will be great.. Thanks

**Comment by KenanY** [comment] 2016-08-15 00:40
@ManasRanjanSahoo Before running `npm run build`, you need to define a `"build"` script in your `package.json`. Otherwise, how could `npm` know what you want it to do? Of course, builds scripts will vary among different projects so I cannot give you the exact script you need. Rather, I can show you an example:

``` json
{
"name": "manas",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "your build script goes here!",
    "start": "webpack-dev-server --hot"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.3.0",
    "react-dom": "^15.3.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1"
  }
}
```

Since this is not a bug or feature request with `npm` itself, I'm gonna close this, but if you run into any other issues regarding `npm` feel free to leave a comment or create a new issue. Good luck with your project!

**Closed by KenanY** 2016-08-15 00:40 UTC
