### ISSUE TITLE
NPM duplicate dependency for each project

### ISSUE THREAD

**Issue by imben1109** [npm/npm#20682] opened 2018-05-20 05:13 UTC
#### I'm opening this issue because:

  - npm is doing something I don't understand.
  - npm is producing incorrect or undesirable behavior.

#### What's going wrong?
I am use npm to download dependency.As I did a lot of trial project and store the copy of trial result, it would use a lot of storage and I need to waste resource to download or install package again. 

#### What's the feature?
use a shared folder to store dependency and share the dependency with all project.

#### What problem is the feature intended to solve?
reduce waste of storage and time

#### Is this feature similar to an existing feature in another tool?
Maven

**Comment by kenany** [comment] 2018-05-21 16:11
Duplicate of https://github.com/npm/npm/issues/18068?

**Comment by imben1109** [comment] 2018-05-24 02:28
I think yes... but still cannot find any workaround solution.

**Comment by kenany** [comment] 2018-05-24 04:07
Closing as a duplicate then.

**Closed as completed by kenany** 2018-05-24 04:07 UTC
