### ISSUE TITLE
Unable to install protractor

### ISSUE THREAD

**Issue by installa** [npm/npm#7258] opened 2015-02-02 14:57 UTC
Here's the log that I got on my cmd window...The npm install seems to have worked fine but I am having a problem when I try to install protractor. Thanks in advance.

```
G:\>npm install -g protractor
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1365:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:977:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:323:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:585:24)
npm ERR!     at flow (_stream_readable.js:594:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:626:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"

npm ERR! cwd G:\
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     G:\npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment] 2015-02-03 02:35
You are running into a problem caused by using a quite old version of `npm`.  The latest version is 2.4.1.  There have been a lot of improvements to `node` and `npm` -- especially around conflicts and race conditions during install -- since 1.4.14. Can you try updating your npm installation?

To update npm on Windows, first install the latest version of node from <https://nodejs.org/download> (latest is currently 0.10.36) and then follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by installa** [comment] 2015-02-05 20:44
Thanks smikes!
The problem was I learnt from a developer friend is my company network. I had to run the following commands to make the strict-ssl false:
git config --global http.sslVerify false

npm config set strict-ssl false

I now installed protractor successfully. My joy was shortlived since I am not able to update webdriver-manager and start it...Here's what I get on my cmd console:
C:\Users\skoti>webdriver-manager update
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.44/selenium-server
-standalone-2.44.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.13/chromedriver_win32.
zip...
Error: Got error Error: CERT_UNTRUSTED from https://chromedriver.storage.googlea
pis.com/2.13/chromedriver_win32.zip
Error: Got error Error: CERT_UNTRUSTED from https://selenium-release.storage.goo
gleapis.com/2.44/selenium-server-standalone-2.44.0.jar

C:\Users\skoti>webdriver-manager start
Selenium Standalone is not present. Install with webdriver-manager update --stan
dalone

C:\Users\skoti>

=================================
So as you can see, it seems like it is all about the CERT_UNTRUSTED error. Do you think I need to run some other kind of command to make ssl false again?

Any help will be appreciated.
For what its worth, I would like to mention that on my home desktop (win xp), I have no problems, just my company desktop (win7 enterprise 64-bit). Anyway, I think if I figure out a way to get past the CERT_UNTRUSTED error, I should be good.

Thanks in advance!

**Comment by smikes** [comment] 2015-02-05 22:42
This might work

```
webdriver-manager --ignore_ssl update
```

Unfortunately I don't know enough about protractor / angular to help troubleshoot this problem, but you can check their issue tracker: https://github.com/angular/protractor/issues

**Comment by installa** [comment] 2015-02-06 17:35
Thanks! Actually the --ignore_ssl worked.

**Comment by othiym23** [comment] 2015-02-06 22:55
Closing as resolved.

**Closed by othiym23** 2015-02-06 22:55 UTC
Labels: support

**Comment by javeed369** [comment] 2015-03-02 13:33
The below command works for CERT_UNTRUSTED in protractor
webdriver-manager --ignore_ssl update --standalone
