### ISSUE TITLE
Error Install cordova > concat stream

### ISSUE THREAD

**Issue by ainulyaqin** [npm/npm#9612] opened 2015-09-16 14:56 UTC
Hi,, 

I am getting error when to try install cordova "npm install -g cordova",
![capture](https://cloud.githubusercontent.com/assets/5828719/9908365/7d845322-5cbd-11e5-9d70-9954167119d1.JPG)

anyone, can you help me to give suggest, what the problem with my npm version or node version ? or other..

most. thanks.

**Comment by KenanY** [comment] 2015-09-16 15:03
Duplicate of several other tickets at the moment. Registry seems to be serving 0-length files to some people.

**Comment by jtand** [comment] 2015-09-16 15:06
+1 I'm seeing this as well, but with any package I try to install with npm. I'm trying on CentOS, Fedora, and Arch. 

npm install -g yo
```bash
npm ERR! Error: shasum check failed for /root/tmp/npm-5598-N1PFSrYC/1442415663439-0.45429079933092/tmp.tgz
npm ERR! Expected: 00ad402c0dba027bd8b4b7228dc7d42cefe3c81a
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR!     at /usr/lib/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.1.5-x86_64-linode61
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /root
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

npm install -g bower
```bash
npm ERR! Error: shasum check failed for /root/tmp/npm-5606-y9FlypbM/1442415708189-0.03028397588059306/tmp.tgz
npm ERR! Expected: 18c891db01b782a74a7bff936a0f24997741c7ab
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR!     at /usr/lib/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.1.5-x86_64-linode61
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /root
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm http 304 https://registry.npmjs.org/mout
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment] 2015-09-16 15:16
@jtand While it won't solve your issue, I must warn you that `npm@1.3.6` is years old and has not been supported for a long time.

**Comment by jtand** [comment] 2015-09-16 15:18
@KenanY I'm aware of that. it was just what was installed on CentOS 6 and what I happened to have up at the time. It is also happening on Arch: 
```bash
npm --version
2.14.3
```

**Comment by ainulyaqin** [comment] 2015-09-16 15:18
@KenanY 
wht do u mean about several tickets at the moment? 
i have cleared my computer, registry and temp files..
and still getting error..

**Comment by jtand** [comment] 2015-09-16 15:23
@ainulyaqin Look at #9601. There are many other issues open for this right now.

**Comment by seldo** [comment] 2015-09-16 15:31
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updates: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh

**Closed by seldo** 2015-09-16 15:31 UTC
