### ISSUE TITLE
AWS EC2 issue with npm make install

### ISSUE THREAD

**Issue by leshane** [npm/npm#8906] opened 2015-07-11 17:55 UTC
I'm trying to follow instructions for setting up an AWS environment running nodejs and npm. Here is the issue I've run into at the end of the process making the npm install. Thoughts? Help?

```
sudo make install
scripts/doc-build.sh doc/api/npm-view.md man/man3/npm-view.3
make[1]: Entering directory `/home/ec2-user/node/npm'
node cli.js install marked-man --no-global
npm ERR! Linux 3.14.35-28.38.amzn1.x86_64
npm ERR! argv "node" "/home/ec2-user/node/npm/cli.js" "install" "marked-man" "--no-global"
npm ERR! node v0.12.2
npm ERR! npm  v3.1.1
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected object but got string
npm ERR! typeerror     at resolveWithNewModule (/home/ec2-user/node/npm/lib/install/deps.js:375:3)
npm ERR! typeerror     at /home/ec2-user/node/npm/lib/install/deps.js:163:5
npm ERR! typeerror     at /home/ec2-user/node/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /home/ec2-user/node/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/home/ec2-user/node/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/home/ec2-user/node/npm/lib/install/deps.js:158:3)
npm ERR! typeerror     at Array.<anonymous> (/home/ec2-user/node/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/home/ec2-user/node/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/node/npm/npm-debug.log
make[1]: *** [node_modules/.bin/marked-man] Error 1
make[1]: Leaving directory `/home/ec2-user/node/npm'
make: *** [man/man3/npm-view.3] Error 2
```

**Comment by KenanY** [comment] 2015-07-11 19:19
Dupe of https://github.com/npm/npm/issues/8904?

**Comment by leshane** [comment] 2015-07-11 22:49
Ah, didn't see the dupe.

I'm not completely clear if/what these errors have affected. I seem to be able to use npm just fine.

**Closed** 2015-07-11 22:49 UTC
