### ISSUE TITLE
npm5: git+ssh:// urls started to return error 128

### ISSUE THREAD

**Issue by matenadasdi** [npm/npm#16830] opened 2017-05-31 15:45 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm install git+ssh://git@github.mycompany.com:example/example.git` url is producing `npm ERR! exited with error code: 128`. It works like a charm with previous NPM versions.

#### How can the CLI team reproduce the problem?
I cannot provide our URL to you, but I guess every kind of git+ssh setup can produce this error.

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v7.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by risa** [comment] 2017-05-31 18:59
The same error here as well for gitlab url. 

782 silly fetchPackageMetaData error for git+ssh://git@gitlab.mycompany.com:group/package.git exited with error code: 128
783 verbose stack Error: exited with error code: 128
783 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
783 verbose stack     at emitTwo (events.js:125:13)
783 verbose stack     at ChildProcess.emit (events.js:213:7)
783 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
784 verbose cwd /home/risa/projects/msp/openimp-oauth2-server
785 verbose Linux 4.10.0-21-generic
786 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
787 verbose node v8.0.0
788 verbose npm  v5.0.0
789 error exited with error code: 128
790 verbose exit [ 1, true ]

Thank you!

**Comment by nicmyers** [comment] 2017-05-31 20:44
I am getting the same error as those above, also for a self-hosted gitlab url. 
It seems from multiple issues reported against npm5 relating specifically to git+ssh URLs. 

**Similar npm5 Issues with git+ssh URLs:**
https://github.com/npm/npm/issues/16841
https://github.com/npm/npm/issues/16789
https://github.com/npm/npm/issues/16726

Thanks!

**Comment by zkat** [comment] 2017-06-01 02:40
I just pushed out `npm@5.0.1` with a bunch of git-related changes. Could you all try that version and let me know if it helped?

**Comment by risa** [comment] 2017-06-01 06:07
Unfortunately the same problem persists:
```
13 silly fetchPackageMetaData error for package-lib-npm@git+ssh://git@gitlab.mycompany.com:group/package.git#397fbdf870ab01d27f6665213c52eca66b769241 exited with error code: 128
14 verbose stack Error: exited with error code: 128
14 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
15 verbose cwd /home/risa/projects/msp/openimp-oauth2-server
16 verbose Linux 4.10.0-21-generic
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
18 verbose node v8.0.0
19 verbose npm  v5.0.1
20 error exited with error code: 128
21 verbose exit [ 1, true ]
```

**Comment by zkat** [comment] 2017-06-01 06:28
Ah right! Yes, this issue is pending figuring out https://github.com/npm/npm-package-arg/pull/23

scp URIs are the worst lol

Are you able to switch url types? As a temporary fix, you might be able to edit any _gitlab_ URIs such that they hit `git+ssh://git@gitlab.mycompany.com/group/package.git`, while we get scp-style URIs in good condition again.

Note that this will only work for git servers that do the same sort of thing github does, where scp, ssh, https, etc, are all available on similar URIs.

**Comment by risa** [comment] 2017-06-01 07:31
Confirmed. Changing the uri from:
```
"my-lib-npm": "git+ssh://git@gitlab.mycompany.com:group/package.git",
```
to:
```
"my-lib-npm": "git+ssh://git@gitlab.mycompany.com/group/package.git",
```
Solved the problem for now. 

Thanks and I am  looking forward to a final fix.

**Comment by yandongxu** [comment] 2017-06-01 10:34
@zkat
node: 8.0.0
npm: 5.0.1 

Still have this problem.

**Comment by blanxii** [comment] 2017-06-01 15:44
@yandongxu did you try Risa solution? also remember to delete the lock file to force to fetch the new repo.

**Comment by zkat** [comment] 2017-06-01 23:39
Closing as a duplicate of https://github.com/npm/npm/issues/16726

**Closed as completed by zkat** 2017-06-01 23:39 UTC
Labels: git, npm5

**Comment by chuckhacker** [comment] 2017-06-05 22:22
Still seeing this problem in 5.0.2

**Comment by maraymer** [comment] 2017-06-07 23:00
This problem is still very much an issue in 5.0

**Comment by legodude17** [comment] 2017-06-08 21:34
Look at #16726, it is the same issue.

**Comment by jhchill666** [comment] 2017-06-14 08:26
It seems to me that changing:

`"my-lib-npm": "git+ssh://git@gitlab.mycompany.com:group/package.git"`

to

`"my-lib-npm": "git+ssh://git@gitlab.mycompany.com/group/package.git"`

the work around, doesn't wash, when additionally specifying a port:

`"my-lib-npm": "git+ssh://git@gitlab.mycompany.com:9000/group/package.git"`

**Comment by balupton** [comment] 2017-06-20 02:55
for other people making URL changes for this, the `git+ssh://git@` requires git+ssh to be configured correctly - we ended up going with npm's built in support for github urls - https://docs.npmjs.com/files/package.json#github-urls

for other formats, for git urls: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

to summarise, `git+ssh//git@` isn't the only option for the fix for this issue, any of these work:

```
git://github.com/user/project.git#commit-ish
git+ssh://user@hostname:project.git#commit-ish
git+ssh://user@hostname/project.git#commit-ish
git+http://user@hostname/project/blah.git#commit-ish
git+https://user@hostname/project/blah.git#commit-ish
```

and for github:

```
    "express": "expressjs/express",
    "mocha": "mochajs/mocha#4727d357ea",
    "module": "user/repo#feature\/branch"
````

**Comment by BryanCrotaz** [comment] 2017-06-24 05:40
Your comment "any of these work" isn't correct:

`package.json`
```
...
  "devDependencies": {
    "awsmqtt": "git+ssh://git@bitbucket.org/silvercurve/awsmqtt.git",
...
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.0.3
3 info using node@v6.9.1
4 verbose npm-session 021a649846d197e2
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall pixelpipe-show-control-player@0.0.0
7 info lifecycle pixelpipe-show-control-player@0.0.0~preinstall: pixelpipe-show-control-player@0.0.0
8 silly lifecycle pixelpipe-show-control-player@0.0.0~preinstall: no script for preinstall, continuing
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly fetchPackageMetaData error for awsmqtt@git+ssh://git@bitbucket.org/myteam/awsmqtt.git#12ea269c9f121dde19c2459599ebd36343029310 exited with error code: 128
15 verbose stack Error: exited with error code: 128
15 verbose stack     at ChildProcess.onexit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at ChildProcess.emit (events.js:191:7)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
16 verbose cwd C:\projects\pixelpipe-show-control-player
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19 verbose node v6.9.1
20 verbose npm  v5.0.3
21 error exited with error code: 128
22 verbose exit [ 1, true ]
```
