### ISSUE TITLE
Add hooks to `npm version`?

### ISSUE THREAD

**Issue by bebraw** [npm/npm#8044] opened 2015-04-23 05:25 UTC
In various libraries of mine I like to maintain a general distribution (just copy and paste the files) at `/dist` and a Node specific one (`/dist-modules`). Latter gets generated through `prepublish` hook while I generate the first one manually using `npm run dist` script.

The problem is that it's very easy to forget to run the dist script before invoking `npm version`. And I definitely want to make sure the version gets the right dist attached.

Would it be possible to add something like a `preversion` hook that would trigger just before `npm version` creates a git commit? In my case I would just make it trigger my `npm run dist` command making the updated dist appear within the version commit which `npm version` makes.

To keep it consistent with the rest you could have `postversion` and `version` hooks there as well.

**Comment by martinheidegger** [comment] 2015-04-23 17:34
Duplicate of #7906

**Comment by bebraw** [comment] 2015-04-23 17:43
@martinheidegger Alright, thanks. Feel free to close!

**Closed** 2015-04-23 17:43 UTC
