### ISSUE TITLE
Unable to deprecate package

### ISSUE THREAD

**Issue by ljharb** [npm/npm#11357] opened 2016-01-30 21:29 UTC
When I run `npm deprecate string.prototype.padleft 'padLeft was renamed to padStart in November 2015. Please use "string.prototype.padstart" instead!'`, I get the following output:
```
npm ERR! Darwin 14.5.0
npm ERR! argv "$HOME/.nvm/versions/node/v5.4.1/bin/node" "$HOME/.nvm/versions/node/v5.4.1/bin/npm" "deprecate" "string.prototype.padleft" "padLeft was renamed to padStart in November 2015. Please use \"string.prototype.padstart\" instead!"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3

npm ERR! invalid version range: latest
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     $PWD/npm-debug.log
```

The contents of `npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '$HOME/.nvm/versions/node/v5.4.1/bin/node',
1 verbose cli   '$HOME/.nvm/versions/node/v5.4.1/bin/npm',
1 verbose cli   'deprecate',
1 verbose cli   'string.prototype.padleft',
1 verbose cli   'padLeft was renamed to padStart in November 2015. Please use "string.prototype.padstart" instead!' ]
2 info using npm@3.5.3
3 info using node@v5.4.1
4 silly mapToRegistry name string.prototype.padleft
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/string.prototype.padleft
8 verbose stack Error: invalid version range: latest
8 verbose stack     at CachingRegistryClient.deprecate ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/deprecate.js:23:15)
8 verbose stack     at $HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/lib/deprecate.js:48:18
8 verbose stack     at mapToRegistry ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/lib/utils/map-to-registry.js:55:3)
8 verbose stack     at EventEmitter.deprecate ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/lib/deprecate.js:40:3)
8 verbose stack     at Object.commandCache.(anonymous function) ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/lib/npm.js:216:13)
8 verbose stack     at EventEmitter.<anonymous> ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/bin/npm-cli.js:74:30)
8 verbose stack     at nextTickCallbackWith0Args (node.js:452:9)
8 verbose stack     at process._tickCallback (node.js:381:13)
9 verbose cwd $PWD
10 error Darwin 14.5.0
11 error argv "$HOME/.nvm/versions/node/v5.4.1/bin/node" "$HOME/.nvm/versions/node/v5.4.1/bin/npm" "deprecate" "string.prototype.padleft" "padLeft was renamed to padStart in November 2015. Please use \"string.prototype.padstart\" instead!"
12 error node v5.4.1
13 error npm  v3.5.3
14 error invalid version range: latest
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

This has been happening on many versions of node and npm since November. I was able to deprecate `string.prototype.padright` just fine.

**Comment by othiym23** [comment] 2016-01-30 21:38
This is a known consequence of a [seemingly unrelated change](https://github.com/npm/npm/commit/1e834c2) ([original pull request](https://github.com/npm/npm-package-arg/pull/15)) made in [`npm@3.4.1`](https://github.com/npm/npm/blob/master/CHANGELOG.md#ask-for-nothing-get-latest). This is already logged as #10974, so I'm going to close this as a duplicate of that.

Fortunately, there's a workaround, and it's pretty simple:

```
npm deprecate 'string.prototype.padleft@*' 'padLeft was renamed to padStart in November 2015. Please use "string.prototype.padstart" instead!'
```

Thanks for your time! I hope this gets you unstuck!

**Closed by othiym23** 2016-01-30 21:38 UTC

**Comment by ljharb** [comment] 2016-01-30 21:49
When I try that, I get the error I used to get:
```
$ npm deprecate string.prototype.padleft@* 'padLeft was renamed to padStart in November 2015. Please use "string.prototype.padstart" instead!'
npm ERR! Darwin 14.5.0
npm ERR! argv "$HOME/.nvm/versions/node/v5.4.1/bin/node" "$HOME/.nvm/versions/node/v5.4.1/bin/npm" "deprecate" "string.prototype.padleft@*" "padLeft was renamed to padStart in November 2015. Please use \"string.prototype.padstart\" instead!"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code E500

npm ERR! "name and _id should match" : string.prototype.padleft
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     $PWD/npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '$HOME/.nvm/versions/node/v5.4.1/bin/node',
1 verbose cli   '$HOME/.nvm/versions/node/v5.4.1/bin/npm',
1 verbose cli   'deprecate',
1 verbose cli   'string.prototype.padleft@*',
1 verbose cli   'padLeft was renamed to padStart in November 2015. Please use "string.prototype.padstart" instead!' ]
2 info using npm@3.5.3
3 info using node@v5.4.1
4 silly mapToRegistry name string.prototype.padleft
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/string.prototype.padleft
8 verbose get GET as part of write; not caching result
9 verbose request uri https://registry.npmjs.org/string.prototype.padleft?write=true
10 verbose request no auth needed
11 info attempt registry request try #1 at 1:39:16 PM
12 verbose request using bearer token for auth
13 verbose request id 604441321b8d089e
14 http request GET https://registry.npmjs.org/string.prototype.padleft?write=true
15 http 200 https://registry.npmjs.org/string.prototype.padleft?write=true
16 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 verbose headers   etag: '"159XQYGSOM8EQHQP0HXJMB7XH"',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '7113',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Sat, 30 Jan 2016 21:39:17 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-sjc3135-SJC',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1454189956.926149,VS0,VE165',
16 verbose headers   vary: 'Accept' }
17 silly get cb [ 200,
17 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
17 silly get     etag: '"159XQYGSOM8EQHQP0HXJMB7XH"',
17 silly get     'content-type': 'application/json',
17 silly get     'cache-control': 'max-age=0',
17 silly get     'content-length': '7113',
17 silly get     'accept-ranges': 'bytes',
17 silly get     date: 'Sat, 30 Jan 2016 21:39:17 GMT',
17 silly get     via: '1.1 varnish',
17 silly get     connection: 'keep-alive',
17 silly get     'x-served-by': 'cache-sjc3135-SJC',
17 silly get     'x-cache': 'MISS',
17 silly get     'x-cache-hits': '0',
17 silly get     'x-timer': 'S1454189956.926149,VS0,VE165',
17 silly get     vary: 'Accept' } ]
18 verbose get saving string.prototype.padleft to $HOME/.npm/registry.npmjs.org/string.prototype.padleft_3Fwrite_3Dtrue/.cache.json
19 verbose request uri https://registry.npmjs.org/string.prototype.padleft
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 1:39:17 PM
22 verbose request using bearer token for auth
23 http request PUT https://registry.npmjs.org/string.prototype.padleft
24 http 500 https://registry.npmjs.org/string.prototype.padleft
25 verbose headers { 'content-type': 'application/json',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'content-length': '57',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Sat, 30 Jan 2016 21:39:17 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-sjc3133-SJC',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1454189957.417226,VS0,VE107' }
26 info retry will retry, error on last attempt: Error: "name and _id should match" : string.prototype.padleft
27 info attempt registry request try #2 at 1:39:27 PM
28 verbose request using bearer token for auth
29 http request PUT https://registry.npmjs.org/string.prototype.padleft
30 http 500 https://registry.npmjs.org/string.prototype.padleft
31 verbose headers { 'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=0',
31 verbose headers   'content-length': '57',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Sat, 30 Jan 2016 21:39:28 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-sjc3124-SJC',
31 verbose headers   'x-cache': 'MISS',
31 verbose headers   'x-cache-hits': '0',
31 verbose headers   'x-timer': 'S1454189967.935978,VS0,VE140' }
32 info retry will retry, error on last attempt: Error: "name and _id should match" : string.prototype.padleft
33 info attempt registry request try #3 at 1:40:28 PM
34 verbose request using bearer token for auth
35 http request PUT https://registry.npmjs.org/string.prototype.padleft
36 http 500 https://registry.npmjs.org/string.prototype.padleft
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=0',
37 verbose headers   'content-length': '57',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Sat, 30 Jan 2016 21:40:28 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-sjc3131-SJC',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1454190028.219372,VS0,VE138' }
38 verbose request invalidating $HOME/.npm/registry.npmjs.org/string.prototype.padleft on PUT
39 verbose stack Error: "name and _id should match" : string.prototype.padleft
39 verbose stack     at makeError ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
39 verbose stack     at CachingRegistryClient.<anonymous> ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
39 verbose stack     at Request._callback ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
39 verbose stack     at Request.self.callback ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/request/request.js:198:22)
39 verbose stack     at emitTwo (events.js:87:13)
39 verbose stack     at Request.emit (events.js:172:7)
39 verbose stack     at Request.<anonymous> ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/request/request.js:1035:10)
39 verbose stack     at emitOne (events.js:82:20)
39 verbose stack     at Request.emit (events.js:169:7)
39 verbose stack     at IncomingMessage.<anonymous> ($HOME/.nvm/versions/node/v5.4.1/lib/node_modules/npm/node_modules/request/request.js:962:12)
40 verbose statusCode 500
41 verbose pkgid string.prototype.padleft
42 verbose cwd $PWD
43 error Darwin 14.5.0
44 error argv "$HOME/.nvm/versions/node/v5.4.1/bin/node" "$HOME/.nvm/versions/node/v5.4.1/bin/npm" "deprecate" "string.prototype.padleft@*" "padLeft was renamed to padStart in November 2015. Please use \"string.prototype.padstart\" instead!"
45 error node v5.4.1
46 error npm  v3.5.3
47 error code E500
48 error "name and _id should match" : string.prototype.padleft
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

I believe this should be reopened.

**Comment by deepsweet** [comment] 2016-02-08 07:08
same here :(

**Comment by jdalton** [comment] 2016-02-12 18:44
I have the same issue with lodash packages that contain the word "start" for `npm owner` operations. See https://github.com/npm/npm/issues/9760 so far no response from npm.

I just hit it again when trying to deprecate the package to point to the renamed one:

```bash
npm ERR! argv "/Users/jdalton/.nvm/versions/node/v5.5.0/bin/node" "/Users/jdalton/.nvm/versions/node/v5.5.0/bin/npm" "deprecate" "lodash.padleft@*" "This package has been renamed. Use lodash.padstart@^4.0.0"
npm ERR! node v5.5.0
npm ERR! npm  v2.14.18
npm ERR! code E500
```

```bash
npm ERR! argv "/Users/jdalton/.nvm/versions/node/v5.5.0/bin/node" "/Users/jdalton/.nvm/versions/node/v5.5.0/bin/npm" "deprecate" "lodash.trimleft@*" "This package has been renamed. Use lodash.trimstart@^4.0.0"
npm ERR! node v5.5.0
npm ERR! npm  v2.14.18
npm ERR! code E500

npm ERR! "name and _id should match" : lodash.trimleft
```

**Comment by jdalton** [comment] 2016-02-12 18:47
This is not the "*" bug (so should not be closed as a dup of it). I can deprecate packages using "*". This is related to the "start" issue.

**Comment by soldair** [comment] 2016-02-12 18:48
im looking into this still. will update soon

**Comment by deepsweet** [comment] 2016-02-12 18:50
surprisingly I tried to deprecate `start-simple-logger` package, so I can confirm the issue with "start" word.

**Comment by soldair** [comment] 2016-02-12 23:51
i posted an update on #9760 but there will be a registry fix rolled out monday.
