### ISSUE TITLE
unable to start program

### ISSUE THREAD

**Issue by ankitpachori** [npm/npm#13516] opened 2016-07-28 16:41 UTC
i am running command npm start. but i am getting this error:--
![new error](https://cloud.githubusercontent.com/assets/19892558/17221106/f1a0bd36-550f-11e6-8017-e70d0d2f4b8d.PNG)

[npm-debug11.txt](https://github.com/npm/npm/files/388896/npm-debug11.txt)

**Comment by othiym23** [comment] 2016-07-28 18:10
Closing as duplicate of #13513.

**Closed by othiym23** 2016-07-28 18:10 UTC
Labels: support
