### ISSUE TITLE
Shasum mismatch for active-model-adapter

### ISSUE THREAD

**Issue by fivetanley** [npm/npm#8979] opened 2015-07-17 15:57 UTC
Hey there npm team :heart:

This problem originally manifest on version 1.13.4.

I maintain the active-model-adapter package. I have an open issue that somebody can't install my package because of a shasum mismatch. I've tried using various versions of npm 2.x and can't reproduce their failure.

They did some debugging and they think the shasum is somehow being changed after being uploaded to the registry.

https://github.com/ember-data/active-model-adapter/issues/28#issuecomment-122225298

Here's the log from that issue:

```
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/deniz/.nvm/versions/node/v0.12.7/bin/node" "/Users/deniz/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for /var/folders/wz/_d0wflt540j52g8_vd94qbs40000gn/T/npm-2362-f6536181/registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
npm ERR! Expected: 894bbae414278da6f68229959ee72aff34a669b5
npm ERR! Actual:   23212ae5107f7b7b1c109f72a69cc554eb3b491e
npm ERR! From:     https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
```

We release through Travis CI, so I wouldn't be surprised if something got mixed up in the release process. I could upload a new version, but if something is wrong in our release process I'd like to know so we can prevent stuff like this happening again.

Thanks! :tada:

**Comment by fivetanley** [comment] 2015-07-17 16:00
Some more information from the issue creator:

> We had the same problem from different machines and even from our CI (different network). changing the value from "^1.13.3" to "1.13.3" in the package.json fixes it for the moment (completly acceptable for me right now).

https://github.com/ember-data/active-model-adapter/issues/28#issuecomment-122094098

**Comment by mongeta** [comment] 2015-07-21 18:09
I'm having exactly the same problem, if you need more info I'm here to help ...
    
    npm config get registry => https://registry.npmjs.org/
    npm -v => 2.12.1
    ember -v => version: 1.13.1
    node => 0.12.7
    
    ember install active-model-adapter
    version: 1.13.1
    Could not find watchman, falling back to NodeWatcher for file system events.
    Visit http://www.ember-cli.com/#watchman for more info.
    shasum check failed for /var/folders/rw/1gqpm58534gbslpbzyvcnb340000gn/T/npm-20449-c0056507/registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
    Expected: 894bbae414278da6f68229959ee72aff34a669b5
    Actual:   23212ae5107f7b7b1c109f72a69cc554eb3b491e
    From:     https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
    Error: shasum check failed for /var/folders/rw/1gqpm58534gbslpbzyvcnb340000gn/T/npm-20449-c0056507/registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
    Expected: 894bbae414278da6f68229959ee72aff34a669b5
    Actual:   23212ae5107f7b7b1c109f72a69cc554eb3b491e
    From:     https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
        at /Users/montx/Dropbox/Ember/borrowers/node_modules/ember-cli/node_modules/npm/node_modules/sha/index.js:38:8
        at ReadStream.<anonymous> (/Users/montx/Dropbox/Ember/borrowers/node_modules/ember-cli/node_modules/npm/node_modules/sha/index.js:85:7)
        at ReadStream.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)


thanks

**Comment by zkat** [comment] 2016-12-09 00:30
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:30 UTC
Labels: registry, support
