### ISSUE TITLE
ENOENT with 3.3.12

### ISSUE THREAD

**Issue by aredridel** [npm/npm#10266] opened 2015-11-05 01:00 UTC
```
:; npm i
asn1@0.1.11 node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/asn1 -> node_modules/asn1
- core-util-is@1.0.1 node_modules/bl/node_modules/readable-stream/node_modules/core-util-is
- inherits@2.0.1 node_modules/bl/node_modules/readable-stream/node_modules/inherits
- isarray@0.0.1 node_modules/bl/node_modules/readable-stream/node_modules/isarray
- string_decoder@0.10.31 node_modules/bl/node_modules/readable-stream/node_modules/string_decoder
- readable-stream@1.0.32 node_modules/bl/node_modules/readable-stream
cssom@0.3.0 node_modules/jsdom/node_modules/cssom -> node_modules/cssom
entities@1.0.0 node_modules/jsdom/node_modules/htmlparser2/node_modules/entities -> node_modules/entities
readable-stream@1.1.13 node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream -> node_modules/htmlparser2/node_modules/readable-stream
- browser-request@0.3.2 node_modules/jsdom/node_modules/browser-request
- nan@1.3.0 node_modules/jsdom/node_modules/contextify/node_modules/nan
- contextify@0.1.9 node_modules/jsdom/node_modules/contextify
- cssstyle@0.2.21 node_modules/jsdom/node_modules/cssstyle
- domelementtype@1.1.1 node_modules/jsdom/node_modules/htmlparser2/node_modules/domelementtype
- domhandler@2.2.0 node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler
- domutils@1.5.0 node_modules/jsdom/node_modules/htmlparser2/node_modules/domutils
- htmlparser2@3.7.3 node_modules/jsdom/node_modules/htmlparser2
- core-util-is@1.0.1 node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/node_modules/core-util-is
- inherits@2.0.1 node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/node_modules/inherits
- isarray@0.0.1 node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/node_modules/isarray
- string_decoder@0.10.31 node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/node_modules/string_decoder
- nwmatcher@1.3.3 node_modules/jsdom/node_modules/nwmatcher
- aws-sign2@0.5.0 node_modules/jsdom/node_modules/request/node_modules/aws-sign2
- caseless@0.6.0 node_modules/jsdom/node_modules/request/node_modules/caseless
- forever-agent@0.5.2 node_modules/jsdom/node_modules/request/node_modules/forever-agent
- async@0.9.0 node_modules/jsdom/node_modules/request/node_modules/form-data/node_modules/async
- delayed-stream@0.0.5 node_modules/jsdom/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream
- combined-stream@0.0.5 node_modules/jsdom/node_modules/request/node_modules/form-data/node_modules/combined-stream
- mime@1.2.11 node_modules/jsdom/node_modules/request/node_modules/form-data/node_modules/mime
- form-data@0.1.4 node_modules/jsdom/node_modules/request/node_modules/form-data
- hoek@0.9.1 node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/hoek
- boom@0.4.2 node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/boom
- cryptiles@0.2.2 node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/cryptiles
- sntp@0.2.4 node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/sntp
- hawk@1.1.1 node_modules/jsdom/node_modules/request/node_modules/hawk
- assert-plus@0.1.2 node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/assert-plus
- ctype@0.5.2 node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/ctype
- http-signature@0.10.0 node_modules/jsdom/node_modules/request/node_modules/http-signature
- json-stringify-safe@5.0.0 node_modules/jsdom/node_modules/request/node_modules/json-stringify-safe
- node-uuid@1.4.1 node_modules/jsdom/node_modules/request/node_modules/node-uuid
- oauth-sign@0.4.0 node_modules/jsdom/node_modules/request/node_modules/oauth-sign
- qs@1.2.2 node_modules/jsdom/node_modules/request/node_modules/qs
- stringstream@0.0.4 node_modules/jsdom/node_modules/request/node_modules/stringstream
- punycode@1.3.1 node_modules/jsdom/node_modules/request/node_modules/tough-cookie/node_modules/punycode
- tough-cookie@0.12.1 node_modules/jsdom/node_modules/request/node_modules/tough-cookie
- tunnel-agent@0.4.0 node_modules/jsdom/node_modules/request/node_modules/tunnel-agent
- request@2.45.0 node_modules/jsdom/node_modules/request
- xmlhttprequest@1.6.0 node_modules/jsdom/node_modules/xmlhttprequest
- bindings@1.1.1 node_modules/bindings
- bl@0.9.3 node_modules/bl
webring@1.0.0 /Users/aredridel/Projects/webring
├── abab@1.0.0  extraneous
├── acorn-globals@1.0.9  extraneous
├── assert-plus@0.1.5  extraneous
├── aws-sign2@0.6.0  extraneous
├── browser-request@0.3.3  extraneous
├── caseless@0.11.0  extraneous
├── cssstyle@0.2.30  extraneous
├── ctype@0.5.3  extraneous
├── escodegen@1.7.0  extraneous
├── extend@3.0.0  extraneous
├── forever-agent@0.6.1  extraneous
├── form-data@1.0.0-rc3  extraneous
├── har-validator@2.0.2  extraneous
├── hawk@3.1.0  extraneous
├── htmlparser2@3.8.3  extraneous
├── isstream@0.1.2  extraneous
├── json-stringify-safe@5.0.1  extraneous
├─┬ kraken-js@1.0.3
│ ├─┬ body-parser@1.7.0
│ │ └─┬ type-is@1.3.2
│ │   └── mime-types@1.0.2
│ └─┬ compression@1.0.11
│   └─┬ accepts@1.0.7
│     └── mime-types@1.0.2
├─┬ level@0.18.0
│ └─┬ leveldown@0.10.2
│   └── bindings@1.1.1
├── node-uuid@1.4.3  extraneous
├── nwmatcher@1.3.6  extraneous
├── oauth-sign@0.8.0  extraneous
├── parse5@1.5.0  extraneous
├── qs@5.2.0  extraneous
├── stringstream@0.0.5  extraneous
├── symbol-tree@3.1.3  extraneous
├── tough-cookie@2.2.0  extraneous
├── tunnel-agent@0.4.1  extraneous
├── webidl-conversions@2.0.0  extraneous
├── whatwg-url-compat@0.6.5  extraneous
└── xml-name-validator@2.0.1  extraneous

npm WARN EPACKAGEJSON webring@1.0.0 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/lib/node_modules/node-darwin-x64/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.12
npm ERR! path /Users/aredridel/Projects/webring/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/asn1
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/aredridel/Projects/webring/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/asn1' -> '/Users/aredridel/Projects/webring/node_modules/asn1'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aredridel/Projects/webring/npm-debug.log
```

Debug log: https://gist.github.com/aredridel/b02a5a8b491ee81a7dcc

**Comment by othiym23** [comment] 2015-11-06 19:41
Closing as a duplicate of #9573. We're going to get to the bottom of this :soon:.

**Closed by othiym23** 2015-11-06 19:41 UTC
