### ISSUE TITLE
EACCES error on node-nodifier module

### ISSUE THREAD

**Issue by sandro-pasquali** [npm/npm#18399] opened 2017-09-04 17:58 UTC
OSX 10.12.4
Node v8.4.0

`npm 5.4` introduces permission errors when using `node-notifier`. Cannot use `node-notifier` if installed with `npm 5.4`.

To replicate

```
> npm i -g npm@5.3
> npm i node-notifier

// index.js
const notifier = require('node-notifier');
notifier.notify('Message');
notifier.notify({
    'title': 'My notification',
    'message': 'Hello, there!'
});

> node index.js

(system notification appears. Works).

> npm i -g npm@5.4
> npm i node-notifier

>node index.js

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommandJson (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/lib/utils.js:79:13)
    at NotificationCenter.notify (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/notifiers/notificationcenter.js:87:20)
    at Object.<anonymous> (Desktop/temp/eaccess_npm5.4/index.js:3:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

> npm i -g npm@5.3
> node index.js

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommandJson (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/lib/utils.js:79:13)
    at NotificationCenter.notify (Desktop/temp/eaccess_npm5.4/node_modules/node-notifier/notifiers/notificationcenter.js:87:20)
    at Object.<anonymous> (Desktop/temp/eaccess_npm5.4/index.js:3:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

> npm i node-notifier
> node index.js

(works)

```

**Comment by jaydenseric** [comment] 2017-09-05 00:34
Next.js users are having issues too: https://github.com/zeit/next.js/issues/2904#issuecomment-327035249.

**Comment by floriangosse** [comment] 2017-09-05 08:35
We have the same problem with flow-bin and fixed it by using npm@5.3.

There problem seems to be that npm don't keep the "executable" permission of binaries.

**Comment by kenany** [comment] 2017-09-05 11:47
So, duplicate of https://github.com/npm/npm/issues/18324 perhaps?

**Comment by floriangosse** [comment] 2017-09-05 11:49
@KenanY yes. it looks like the same problem.

**Closed as completed** 2017-09-06 22:46 UTC
