### ISSUE TITLE
NPM Fails on a new install. Windows 8 64 bit

### ISSUE THREAD

**Issue by f1tech** [npm/npm#7286] opened 2015-02-06 06:53 UTC
Trying to install express and receive: ENOENT, stat 'C:\Users\Mike\AppData\Roaming\npm'. I tried all of the solutions that seem applicable at http://stackoverflow.com/questions/25093276/node-js-windows-error-enoent-stat-c-users-rt-appdata-roaming-npm.

Below is the complete contents of the log file. 

Thanks
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm',
1 verbose cli   '-',
1 verbose cli   'g' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: ENOENT, stat 'C:\Users\Mike\AppData\Roaming\npm'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.2.9200
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-" "g"
9 error cwd c:\Users\Mike\projects\helloworld
10 error node -v v0.10.36
11 error npm -v 1.4.28
12 error path C:\Users\Mike\AppData\Roaming\npm
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```

**Comment by iarna** [comment] 2015-02-06 07:04
This is caused by the issue described in our [troubleshooting](https://github.com/npm/npm/wiki/Troubleshooting#error-enoent-stat-cusersuserappdataroamingnpm-on-windows-7) guide. For your case in particular, you can (probably) get things working by running this from `cmd.exe` (or powershell):

```
mkdir C:\Users\Mike\AppData\Roaming\npm
```

After you do that, npm should work normally.

I'm going to close this ticket as resolved, but if you find that you have further issues, please don't hesitate to open a new one.

**Closed by iarna** 2015-02-06 07:04 UTC
Labels: support, windows

**Comment by f1tech** [comment] 2015-02-06 13:06
Thank you. That was the issue.
