### ISSUE TITLE
npm install <package>@<tag> is different from npm install <package> --tag <tag>

### ISSUE THREAD

**Issue by thegiantbeast** [npm/npm#7141] opened 2015-01-14 19:46 UTC
I discovered that **npm_config_tag** is not set properly in **process.env** when `npm install <package>@<tag>` is run.

Example:
- `npm install nodejs@unstable` - sets **process.env.npm_config_tag** as **latest**
- and if `npm install nodejs --tag unstable` is executed it sets **process.env.npm_config_tag** as **unstable**

Is this somehow intended?

**Comment by smikes** [comment] 2015-01-15 14:04
> Is this somehow intended?

I don't know that I'd call it "intended" but it can be explained by the current design.

`npm install pkg@string` causes `npm` to fetch the `pkg` information from the registry (see `npm view`) and then look for a tarball matching `string` -- as either a version number or a tag -- and then install that tarball

`npm install pkg --tag string` causes the config/command-line processing to deal with the arguments `--tag string` which incidentally sets `npm_config_tag` to `string` for all subprocesses 

Are you trying to do something in an `install` or `postinstall` script that uses `npm_config_tag`?

**Comment by thegiantbeast** [comment] 2015-01-16 17:20
Well I understood the mechanics of it, but shouldn't `pkg@string` behave the same way as `pkg --tag string`? After all it will process the tag.
But I would expect that if I specified the string as `pkg@myMissingTag` to return `latest` or return an error to the user.

I'm trying to preserve the tag information with which the `pkg` was installed. So if the user executed as `pkg@unstable`, I want to store it somehow.
But it seems very hard from the npm side to provide that info.

Do you have any other suggestion?

**Comment by smikes** [comment] 2015-01-16 20:30
I think it may be like this by design - that is, the user's asked-for package is deliberately not given to the package being installed, but I will let @othiym23 comment on that, and possibly @iarna can say whether this will change as a result of multi-stage install -- which will land in npm@3 reasonably soon.

**Comment by smikes** [comment] 2015-01-17 02:25
I believe "npm_config_tag" is always set, so if the user does "npm install foo@1.2.3" you will still see "latest" in the env even if latest points to some other version such  as 2.3.4

**Comment by othiym23** [comment] 2015-01-17 07:57
@smikes is correct; the default value for tag (set in `lib/config/defaults.js`) is `latest`, so that's what it will be set to in the script environment unless otherwise specified. I understand what you're trying to do (I think!), and this isn't something you can do with npm right now. The version spec is resolved by the caching process, but the `tag` config value that gets mapped to `npm_config_tag` in the `run-script` environment is never set by that resolution process, because it's only used internally by the installer until it gets written to `_from` in the installed `package.json`.

The reason `--tag=<tag>` works is because it goes ahead and sets the value in the npm configuration; `npm install <name> --tag=<tag>` isn't the idiomatic way to do that, and only works the way you're expecting because it's using the `--tag` parameter in the same way it's used in `npm publish` and the other commands that will accept it as a parameter.

If what you want to know is what was requested that led to this version of that package being installed, that `_from` field in the `package.json` written into `node_modules` is what you want. If you want to know the explicit **tag** requested (in the comparatively rare times in which a tag is what was actually requested), it would be relatively straightforward to add `npm.config.set("tag", tag)` once that tag has been resolved (see the `addNameTag` function in `lib\cache\add-named.js`. If you want to have access to the non-normalized `<thing>`, you'd need to create a new config variable to hold it (so it would get mapped to the child environment for run-scripts), and then set that somewhere in `lib/cache.js`, probably in the callback for `realizePackageSpecifier`.

This is one of those things that seems like it should be simple, but is surprisingly complex, mostly because I don't think anyone envisioned third party code would want to hook into the internals of the specifier resolution process (that, and the the `<thing>` on the right side of `<package>@<thing>` can be a lot of things, comparatively few of which are actually tags). If you want to add some more detail around what exactly it is you want to do with that information after you capture it, I might be able to give you some more concrete pointers on how you might put together a patch (or a wrapper) that would get you the information you need. This is actually a feature request, though, not a bug. Things are working here pretty much exactly as they were designed.

**Comment by thegiantbeast** [comment] 2015-01-17 21:24
The idea is to have distribution channels such as stable, experimental, unstable, etc.
So if a user installed an "unstable" channel I would like to preserve that information so I can inform them if there's a new version for that distribution channel.

The workaround that I've used is the one that @othiym23 mentioned, I used/parsed `_from` and that way I can get what I want, but I would "prefer" to have some kind of `tag`property in `package.json`or in the environment variables.

But I believe you understand what I'm trying to achieve. Thats for the detailed description.

**Comment by othiym23** [comment] 2015-01-18 01:09
OK! I understand completely now. If you wanted to put together a patch that does this:

> add `npm.config.set("tag", tag)` once that tag has been resolved (see the `addNameTag` function in `lib\cache\add-named.js`)

I'd be happy to work with you to get it landed.

**Comment by othiym23** [comment] 2016-10-11 20:41
Following from my last message in this thread, I'm going to leave the `patch-welcome` label on this issue, but close it. While this behavior would be useful for people who want to support multiple release lines, this isn't something urgent enough that the CLI team is going to make it a priority within the next 6-12 months. If someone feels like taking a whack at this, we're glad to provide help. Thanks for your time!

**Closed by othiym23** 2016-10-11 20:41 UTC
Labels: feature-request, patch-welcome

**Comment by thegiantbeast** [comment] 2016-10-11 22:59
@othiym23 I've been working on this solution, but I had to stop for personal reasons. I hopefully can contribute with the first PR in the next couple of weeks.

And I agree, this feature should come from the community as a PR and not from the core team. I've just seen the roadmap for npm@4 and npm@5 and you have a lot on your plate guys. Thanks for everything.

Once I create the PR I'll ask you to make the first review because I'm pretty sure that I may miss something.
