### ISSUE TITLE
package.json scripts run in incorrect shell on windows when using a bash shell

### ISSUE THREAD

**Issue by SteveALee** [npm/npm#9420] opened 2015-08-26 16:59 UTC
When using npm in a bash shell on windows (eg GitHub Shell, minGW or Cygwin POSIX emulations) all scripts specified in package.json incorrectly run under Cmd. They should run under Bash by default. This means portable scripts cannot be written that run the same on Windows and POSIX environments.

Actually npm uses the shell specified in COMSPEC here
https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L208-L212

This is wrong and the problem is the code here mixes up 'platform' with 'shell'. They are separate and win32 platform does not always mean cmd shell or what is specified in COMPSPEC (which is cmd specific)

Bash on windows leaves comspec alone but sets Bash (at least in MinSys Bash used in GitHub for windows) so the above code fails. Even if you try to override the shell config using the npm_config_shell in the calling shell, it is ignored. It appears to be possible to set shell in npmrc but other tests in the lifecycle.js file also mix platform and shell so it's doesn't work correctly.

A further problem is that while It is possible to update lifecycle.js to correctly separate platform and shell, the process.env contents is also incorrect and does not appear to be the calling shell's environment as you'd expect and required to test for Bash being set (say). To be CLEAR Bash environment variable do not appear. I'm not sure why this is as I have not yet located the code setting process.env

**Comment by SteveALee** [comment] 2015-08-26 17:40
Also run "npm run env" does not show the bash calling shells environment. Perhaps they are hidden by bash?

**Comment by smartmouse** [comment] 2015-08-26 20:48
see this https://github.com/npm/npm/issues/8233  , Cygwin is unsupported.

**Comment by SteveALee** [comment] 2015-08-27 08:28
Ah, OK. 

This is not cygwin though. it's the MinGW bash shell supplied with GitHub for Windows. The difference ins Cygwin attempts to be a complete POSIX emulation with MinGW is just a Bash shell (.exe) and some win32 native ports of POSIX utilities.

Even so supporting a shell other than Cmd (or Powershell) on Windows does require some effort. It's not just the shell environment as mentioned above, but also paths. While Microsoft APIs have supported / as the path separator since MS-DOS, many programs do not. So some painful conversion of paths can crop up. this is often worse in cygwin but still occurs in MinGW as it tries to auto map.

I'll comment on #8233

**Comment by othiym23** [comment] 2015-08-28 21:12
We absolutely do support `mingw` and Git Bash, but there are other platform considerations at play here, because npm does try to provide fully Windows experience on Windows, and muddling the two for mingw bash could cause issues elsewhere. I'm not ruling the change out, but it would need to be done carefully and would probably be a breaking change, requiring it go out in a semver-major version of npm.

**Comment by SteveALee** [comment] 2015-08-29 16:14
Also related - #7209

**Comment by SteveALee** [comment] 2015-08-29 18:27
I'm not sure what exactly bikeshedding entails here but here are some initial thoughts. Sorry if this is all obvious. This is for MinGW Msys bash and derivatives only (ie not cygwin)

# Requirements
* Must not break Windows cmd and Powershell experience in anyway
* Ensure npm can be called from bash
  * should just work
* Ensure bash can be called from npm.
  * Work via run-script invoked script entries and shortcuts like start
  * Q: is this required elsewhere like explore which creates a shell?

# Calling npm from minsys bash
*  command option switch character is - (Who uses / these days anyway?)
  * Not a problem as npm uses -. Only -l and -h and few subcommand specific switches. 
* paths consumed by npm
  * Minsys assumes called commands (.exe) consume windows style mutli root paths so maps it's posix single root paths using complex heuristics on invoking them. http://www.mingw.org/wiki/Posix_path_conversion. 
  * Doubling the leading / should disable this if for example you want to pass a posix path into a command. This is a rare requirement and almost certainly not an issue for npm
  * This should all be fine as win32 version of npm will be expecting win paths 
    * Q: are unc paths (\\server\share) an issue? Does npm support them anyway?

# Calling bash from npm run-script
  * Option (preferred): automatically call Bash if npm was invoked in bash
    * COMSPEC env var cant be used as msys does not set or use it.
      * Current npm code to launch shell uses this to find shell to use
      * arguably COMSPEC is cmd specific, though that undoubtably is not the intention (was in DOS)
    * npm has the shell config option but this appears to be ignored if set (perhaps OK if set in npmrc)
      * According to #6543 shell is only used for explore command
    * the env in the sub shell is not set correctly and appears to be the parent cmd env
      * Is not yet clear the npm process has not inherited the bash env or the env for the scripts sub shell is set incorrectly

## locating and running bash 
  * Might want to run a non login shell - assuming env inheritance is working correctly
  * GitHub for windows 
    * uses a appref-ms Click-once thingie  - yuk!
    * sets GIT_INSTALL_ROOT
    * uname = MINGW32_NT-6.2 
  * Git for windows 
    * installs git-bash.exe
    * Sets EXEPATH
    * uname = MINGW64_NT-10.0 
  * mingw msys 
     * installs a bat file 

# Other points
* path access in API calls from npm will not be effected (msys is just an .exe)
* commands called in scripts will use posix paths (and so will be portable). bash will transform them for any win32 commands (.exes) as above.

# Possible solutions
  * Option: add a flag to scripts section syntax
    * this would break portability of scripts
  * Option:Add a command line option to npm
    * this would also break portability with nested npm scripts   
  * Option:make shell config option work
    * this would break in obscure nested scripts that use different  shells (total edge case - ignore )
  * Q: Are there any issues when using npm programatically?

**Comment by othiym23** [comment] 2016-01-28 23:49
The Windows shell was originally chosen by developers from Microsoft, I believe, and was designed to provide a Windows-native user experience by default. It sounds like what you’d really like is some way to explicitly set which shell is invoked by Windows at runtime, which seems like a generally useful bit of configurability to add to the CLI. The team is agreed that this would be nice to have, and at the same time, we’re probably not going to have the time to get to that this year. So we’re going to close this, but mark it as `patch-welcome`, which is what we’re currently doing with nice-to-have feature requests we’re not intending to ship within the next year.

Be advised that this is something that’s going to need careful testing, because it’s not as simple as just switching which shell gets invoked, and that writing good tests will probably be much simpler once the team finishes our current project of getting the test suite running under Windows CI; because this is a feature request pretty tightly tied to Windows, it’s going to need Windows-specific functional tests to land.

Thanks for putting this together, and thanks for your patience!

**Closed by othiym23** 2016-01-28 23:49 UTC
Labels: feature-request, needs-discussion, windows

**Comment by SteveALee** [comment] 2016-01-29 08:27
Thanks for the response. I've had a few more thoughts subsequently

> The Windows shell was originally chosen by developers from Microsoft, I believe, and was designed to provide a Windows-native user experience by default

Though Windows has for some time now shipped with 2 Shells: Cmd & PowerShell. I guess CMD is the old favourite plus it possibly has a lower runtime cost. As I note below rather than Windows native I figured I'm largely after portability.

> It sounds like what you’d really like is some way to explicitly set which shell is invoked by Windows at runtime, which seems like a generally useful bit of configurability to add to the CLI. 

Indeed. Either explicitly or via a predefined OS mechanism. 

How do you do this on *NIX which has traditionally had a choice of shells. Using the SHELL environment variable? This has the advantage of being inherited by subshells so you should get whatever the process invoking npm has set, and so ultimately the user's choice. Unfortunately on Windows there is no such standard. COMSPEC has be around since DOS days but only Cmd seems to set/use it and unlike *NIX I don't believe the user can set their default shell. The result is you do not have an obvious generic mechanism to detect what shell you should use on Windows.

> So we’re going to close this, but mark it as patch-welcome, which is what we’re currently doing with nice-to-have feature requests we’re not intending to ship within the next year.

Thanks for considering it anyway :)

Actually, what I was trying to achieve was portable npm scripts for build. It seems this is a bigger though related problem. That would require different functional test too. The approaches an npm use can take seem to be.

* Assume Cmd or Bash and limit to a shared subset of shell features and external commands - hard but mostly possible with some restrictions.
* Assume bash and common commands are available and prefix each script with "bash -c " - escaping quotes can get confusing and an extra shell process is invoked. May lose some environment settings, especially if env is not cleanly inherited through CMD on windows.
* Forget about shells and use javascipt and node modules like shelljs - perhaps the bes choice but lose the benefits of shells
* Use frameworks built on Javascript like Grunt and Gulp - these added complication and restrictions compared to JS.

A related issues is that none of these provide dependency management for minimal build like good old make does. You can of course invoke make from an npm script but it just calls shell so you get back to the beginning again. That's not something that npm should be helping with as it's concept of buildable modules is not the same, it's courser.

> Thanks for putting this together, and thanks for your patience!

Not at all. For some reason I care about this stuff. Plus I've experience working on cross platform dev tools.

**Comment by othiym23** [comment] 2016-01-29 08:30
You may want to take a look at, or leave some thoughts on, #11291, which is where I kick around the idea of offering some kind of subset of POSIX shell scripting interpreted by npm itself for use in package scripts, which sounds related to what you're looking for.

**Comment by SteveALee** [comment] 2016-01-29 11:55
> You may want to take a look at, or leave some thoughts on, #11291,

interesting thanks. I'll take a look.

**Comment by SteveALee** [comment] 2016-01-30 18:40
Some closing thoughts on ' some way to explicitly set which shell is invoked by Windows at runtime' in case this is picked up again

Q Why would anyone want to run another shell on WIndows?
A: because the use Bash on Windows for everyday work. Or to create portable npm scripts 

Q: is this useful on other platforms too? eg should a project be able to specify a list of shells it supports?
A: No. npm invokes `sh` (bourne) which is ubiquitous on Linux, OS X and BSD. the type of uses common in npm scripts makes it effectively indistinguishable from bash or other shells (eg a common subset). Not sure about IoT platforms that might arrive soon, for example the The microsoft Chakra port PR made to nodejs may mean npm follows in supporting new platforms (which may end up being windows anyway)

Q:On Windows npm runs whatever is in the `comspec` env var or `cmd.exe` so can't users just set `comspec` to the shell they want?
A: No npm also specifies a number of command line switches using `/` which beaks other uses. For example git4windows bash uses -c. Comspec is expected to be a path and there is no way to specify switches.

Q What other shells might be used on Windows?
A The Git4Windows bash builds on Msys and is preferable to the MinGW distribution. It' can be invoked as an exe and works as expected. The supplied commands are usable but some are old versions. Cygwin supplies various shells. bash can be run but the path is not simply inherited from parent shell so needs more work. A login shell can be used but it has side effects like using .rc scripts and outputting text. PowerShell can also be invoked and works fine. It exists on recent windows installations

**Comment by mattecapu** [comment] 2016-04-02 10:44
Why changing COMSPEC to point to the bash executable doesn't work then? 
![image](https://cloud.githubusercontent.com/assets/5738009/14225808/86a1e0b4-f8d0-11e5-9361-a7726fe07db1.png)

**Comment by SteveALee** [comment] 2016-04-02 15:46
I wondered that. Something strange somewhere. 

 The environment is otherwise correctly inherited from the shell you run npm from. For example path is inherited as I run git bash and bash is correctly on the path in npm scripts so can prefix scripts with bash -c to get portability.

**Comment by SteveALee** [comment] 2016-04-02 15:47
But the requirement for portable npm scripts is anout to largely disappear now Microsoft have announced bash on Ubuntu on Windows.!!!!!

**Comment by SteveALee** [comment] 2016-04-02 15:51
Ms realised the docs for bash today and it should arrive for Windows insiders in a couple of weeks, and on the summer win 10 release.  

https://msdn.microsoft.com/commandline/wsl/about?f=255&MSPPError=-2147217396

Itmight take awhile to iron out all the bugs fir npm script builds.

**Comment by mattecapu** [comment] 2016-04-02 16:11
Yeah it's surely a great relief to have bash natively on Windows, yet I suspect the issue remains for people using different shells (and for a lot of people until the Windows update is released).
Is there anyway I can debug the issue on my machine?

**Comment by SteveALee** [comment] 2016-04-02 16:35
I assume you mean on Windows? Easiest is to fiddle around with the environment of the shell you run npm from and put commands like "set" in the scripts.. If you find anything interesting do please leave a comment on my [blog post](http://opendirective.net/blog/2016/03/more-on-portable-npm-scripts/)

For debugging the npm  JS you can use ms code or visual studio with the node tools adding. For c code you'll need visual studio.

**Comment by petesouth** [comment] 2016-07-01 19:06
I just had an issue where the Native windows javascript runner was being used.. Instead of node.. Causing strange javascript errors that shouldn't have been.  Found a 

C:\Users\pete_south\AppData\Roaming\npm

Found a

trueviewstackutils.cmd   (trueviewstackutils) is the name of my command line app.

Originally.. I noticed the file looks like this:

@"%~dp0\node_modules\trueviewstackutils\main.js"   %*

This fails...

When I made it be this...  

node "%~dp0\node_modules\trueviewstackutils\main.js"   %*

It works.

THis is doing a npm install -g from my directory on my local box containing my package.json.

I have to edit this file... and make this change anytime I run npm install -g from my directory.

Seems that's a bug in NPM on windows.. It does wortk.. When I add the mentioned edit.. in the cmd link you guys create.

Maybe this helps ya?

**Comment by ErBlack** [comment] 2017-05-18 08:23
@mattecapu problem with comspec is here https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L239.

Also i found a funny solution to use vars in windows:

```js
cmd = cmd.replace(/\$\{(\w+)\}/g, function(match, search) {return `%${search}%`});
```

Looks pretty ugly, but works.
