### ISSUE TITLE
fatal: insane git directory for a private dependency in package.json

### ISSUE THREAD

**Issue by calmath** [npm/npm#11220] opened 2016-01-20 16:06 UTC
Setting the scene we have created a few of our own modules for our front end development and these are stored within our own git repository sitting under Visual Studio Team Services. A .NET Web application then tried to make use of these modules as dependencies though the process is falling over at the build stage I think due to the directly naming convention. We are working entirely on windows OS as well just for full clarity.

So within package.json we have:
"devDependencies": {
    "module": "git+https://username:<auth_token_50 chars>@<account>.visualstudio.com/DefaultCollection/_git/module",

On executing a build, the npm process starts off and finally gets to the step of getting the latest code for this module, hence it looks at performing a git clone as follows:
git clone --template=C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://username:<auth_token_50 chars>@<account>.visualstudio.com/DefaultCollection/_git/module C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\npm-cache\_git-remotes\https-username-<auth_token_50 chars>-<account>-visualstudio-com-DefaultCollection-git-module-291122e2

This is causing a fatal error: fatal: insane git directory C:/Windows/ServiceProfiles/LocalService/AppData/Roaming/npm-cache/_git-remotes/https-username-<auth_token_50 chars>-<account>-visualstudio-com-DefaultCollection-git-module-291122e2

I cannot find and detail on ways to get around this, maybe there is an option to only use the module name as the folder rather than the entire dependency url as the folder name. Any help would be appreciated.

I apologise if this is not the correct place to ask this though running low on ideas.
Thanks
Mark

**Comment by zkat** [comment] 2016-02-03 21:37
I believe this is a duplicate of #9143. Closing in favor of that issue.

**Closed by zkat** 2016-02-03 21:37 UTC
Labels: bug, git, windows
