### ISSUE TITLE
No compatible version found: left-pad@0.0.3

### ISSUE THREAD

**Issue by givanse** [npm/npm#12015] opened 2016-03-22 22:01 UTC
Reproduced with:

```
npm cache clear
rm -rf node_modules
npm install babel-core
```

error:
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/gsilvae/.nvm/versions/node/v5.9.0/bin/node" "/Users/gsilvae/.nvm/versions/node/v5.9.0/bin/npm" "install" "babel-core"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! 0.0.9
```

**Comment by othiym23** [comment] 2016-03-22 22:02
Closing as duplicate of #12012.

**Closed by othiym23** 2016-03-22 22:02 UTC
