### ISSUE TITLE
Reg- npm start Failed

### ISSUE THREAD

**Issue by tamilmovieskaari** [npm/npm#15980] opened 2017-03-08 07:28 UTC
#### I'm opening this issue because:

  - [ ] missing script: start.

 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: start

**Comment by doshisid** [comment] 2017-03-08 08:10
does your package.json file has a `start` script?
if it does please show your package.json file.

**Comment by m1rwen** [comment] 2017-03-13 15:13
Having the same issue , new to nodejs , help please

> simulator@0.0.0 start c:\simulator\simulator
> node ./bin/www


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! file C:\windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
npm ERR! path C:\windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
npm ERR! simulator@0.0.0 start: `node ./bin/www`
npm ERR! spawn C:\windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin ENOENT
npm ERR!
npm ERR! Failed at the simulator@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the simulator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs simulator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls simulator
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! simulator@0.0.0 start: `node ./bin/www`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the simulator@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the simulator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs simulator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls simulator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\simulator\simulator\npm-debug.log

**Comment by KenanY** [comment] 2017-03-13 17:29
@m1rwen Your issue is different. Your error is coming from `node ./bin/www`, not from `npm` itself (who is simply catching the error for you).

**Comment by tamilmovieskaari** [comment] 2017-03-29 07:38
package.json

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {

    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "tsc && concurrently \"npm run tsc:w\"npm run lite",

    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },

**Comment by tamilmovieskaari** [comment] 2017-03-29 07:39
Pbm Occured:
D:\my-proj>npm start

> angular-quickstart@1.0.0 prestart D:\my-proj
> npm run build


> angular-quickstart@1.0.0 build D:\my-proj
> tsc -p src/

src/app/comments/components/comment-form.component.ts(8,10): error TS2305: Module '"D:/my-proj/node_modules/@angular/common/common"' has no exported member 'NgForm'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaarivanan.e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\my-proj\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaarivanan.e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\my-proj\npm-debug.log

D:\my-proj>npm start

> angular-quickstart@1.0.0 prestart D:\my-proj
> npm run build


> angular-quickstart@1.0.0 build D:\my-proj
> tsc -p src/

src/app/comments/components/comment-form.component.ts(8,10): error TS2305: Module '"D:/my-proj/node_modules/@angular/common/common"' has no exported member 'NgForm'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaarivanan.e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\my-proj\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaarivanan.e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\my-proj\npm-debug.log

**Comment by doshisid** [comment] 2017-03-29 07:51
As stated in the error, this issue has nothing to do with npm itself.
The issue is with @angular package.
You can try deleting `node_modules` folder and run `npm install` and see if problem persists.

**Comment by KenanY** [comment] 2017-03-29 11:18
@tamilmovieskaari As @doshisid said, this error is coming from `tsc` and not `npm`:

```
src/app/comments/components/comment-form.component.ts(8,10): error TS2305: Module '"D:/my-proj/node_modules/@angular/common/common"' has no exported member 'NgForm'.
```

I'm gonna close this one since you have apparently solved your original issue, and furthermore all of the errors in this thread are either:

  1. Intentional, such as running `npm start` without having a `"start"` script defined
  2. Not from `npm` itself.

**Closed by KenanY** 2017-03-29 11:18 UTC
Labels: support
