### ISSUE TITLE
NPM search does not work against namespace/packages

### ISSUE THREAD

**Issue by chickendinosaur** [npm/npm#8453] opened 2015-06-04 00:05 UTC
Hi,

I used the new namespace functionality for a recent public package I created using --access=public. I was planning on using the new format from here out but notice that when searching for the package in both command line and npmjs.org there are no results. The search does not even recognize the package keywords so nothing comes up nor does it recognize if i search the entire package name. 

The package: @chickendinosaur/footprint
Search params: footprint, chickendinosaur

I would like to market my new packages going forward of course but there hasn't been one single download from the public which is odd. Is this broken? Thanks!

**Comment by othiym23** [comment] 2015-06-04 00:11
This is a known limitation of scoped packages. I'm closing this as a duplicate of #8244, which has the explanation of why this limitation exists.

**Closed by othiym23** 2015-06-04 00:11 UTC
Labels: feature-request
