### ISSUE TITLE
Missing unicode support in npm init

### ISSUE THREAD

**Issue by dotnetCarpenter** [npm/npm#4424] opened 2014-01-06 13:37 UTC
### Steps to reproduce:
`npm init`
`name: demægtigevikinger.dk`
fill out the rest (not important)

### Result:
```bash
npm ERR! Error: Invalid name: "demægtigevikinger.dk"
npm ERR!     at ensureValidName (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
npm ERR!     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/read-json.js:234:40
npm ERR!     at fs.js:266:14
npm ERR!     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "init"
npm ERR! cwd /Volumes/mystuff/dotnetCarpenter/Projects/IT-Kollektivet/fuzzypress/demægtigevikinger.dk
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
```
### Expected result
```bash
About to write to /Volumes/mystuff/dotnetCarpenter/Projects/IT-Kollektivet/fuzzypress/demægtigevikinger.dk/package.json:

{
  "name": "demægtigevikinger.dk",
  "version": "0.1.0",
  "description": "blah blah",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://dotnetCarpenter@bitbucket.org/dotnetCarpenter/dem-gtigevikinger.dk.git"
  },
  "author": "",
  "license": "WTFPL"
}

Is this ok? (yes)
```

### Debug information
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.24/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'init' ]
2 info using npm@1.3.21
3 info using node@v0.10.24
4 silly package data undefined
5 info init written successfully
6 error Error: Invalid name: "demægtigevikinger.dk"
6 error     at ensureValidName (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
6 error     at Object.module.exports.fixNameField (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
6 error     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
6 error     at Array.forEach (native)
6 error     at normalize (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
6 error     at final (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/read-json.js:310:33)
6 error     at then (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:33)
6 error     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/read-package-json/read-json.js:234:40
6 error     at fs.js:266:14
6 error     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
7 error If you need help, you may report this *entire* log,
7 error including the npm and node versions, at:
7 error     <http://github.com/isaacs/npm/issues>
8 error System Darwin 13.0.0
9 error command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "init"
10 error cwd /Volumes/mystuff/dotnetCarpenter/Projects/IT-Kollektivet/fuzzypress/demægtigevikinger.dk
11 error node -v v0.10.24
12 error npm -v 1.3.21
13 verbose exit [ 1, true ] 
```

**Comment by othiym23** [comment] 2016-06-08 21:08
> Any reasons not to move this check into the npm publish function?

It's a footgun if you can create a package that you later can't publish. Arguably, it should be allowed anyway, but doing this properly _without_ turning it into a footgun is a tricky UX problem, and one that the team won't really have the cycles for for a while.

I'm closing this as a duplicate of #10817 – this is a larger issue than just `npm init`. The registry as well as the CLI would need changes to properly handle non-ASCII characters in package or user names, and while we've expressed some interest in that idea in the past, it's not currently on the road map, nor is there a lot of urgency to get it onto the road map. Thanks to all for the discussion!

**Closed by othiym23** 2016-06-08 21:08 UTC
Labels: feature-request

**Comment by dotnetCarpenter** [comment] 2016-06-11 00:07
@othiym23 Not to bash any of your arguments, which are sound. Can we please make a joint effort to push away ASCII RFC stuff and just use utf8? I don't know anyone in Europe who would implement a RFC with strict adhesion to ASCII because it's impractical in every situation - ever!

**Comment by dholth** [comment] 2016-07-22 20:04
punycode?
