### ISSUE TITLE
Why npm allows to unpublish packages?

### ISSUE THREAD

**Issue by nkt** [npm/npm#12035] opened 2016-03-23 20:24 UTC
Hi!
Today "pad-left" package has been unpublished by its author.
Many other packages depends on this package.
It may be proper to prevent the removal of a package if others depend on it?
Or introduce functionality, which blocks the interaction of npm with a package, it marks it as deprecated?

Here [is the story](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.n9onjs41q) from author which unpublished this package and many others.
What is the official NPM position about transfering package ownership without previous owner agreement (Trademark issue)?

**Comment by artyomtrityak** [comment] 2016-03-23 20:27
This is very important question because it does not make any sense of 99% NPM package service availability if any package can be unpublished and totally removed from registry.

**Comment by zkat** [comment] 2016-03-23 20:47
There's two parts to this. The first is the answer in the topic:

* npm has been designed, from the beginning, as a tool to empower the community on its terms. We give a tremendous amount of control to developers over publishing and managing the code they publish. That is the actual answer but I know it doesn't address the larger topic and the other issues involved. And I'm not going to.

* This is also a duplicate of #12017 and I'm closing it as such. Please refer to the discussion there, and note that the issue has been locked for now.

**Closed by zkat** 2016-03-23 20:47 UTC
Labels: support

**Comment by niklabh** [comment] 2016-03-24 19:17
Keep calm and use scopes https://docs.npmjs.com/getting-started/scoped-packages
