### ISSUE TITLE
npm ignores "prefix" in project-local .npmrc

### ISSUE THREAD

**Issue by kevin-at-reflexion** [npm/npm#8820] opened 2015-07-03 22:14 UTC
See issue https://github.com/npm/npmconf/issues/42, which is the same issue, on the old npm/npmconf repository.

I have as a sibling of my **package.json** an **.npmrc** with `prefix = ./vendor/npm`.
When run, `npm` does create a directory `./vendor/npm/etc`, but then proceeds to install packages at `./node_modules` anyways.

**Comment by iarna** [comment] 2015-07-06 03:38
Closing as duplicate of #8036

**Closed by iarna** 2015-07-06 03:38 UTC
