### ISSUE TITLE
 npm install fails

### ISSUE THREAD

**Issue by ImanMh** [npm/npm#10665] opened 2015-12-02 10:14 UTC
```npm install async --save```
or 
```sudo npm install async --save```
return error to me. 

here is my npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'async', '--save' ]
2 info using npm@3.5.0
3 info using node@v0.12.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData async
8 silly fetchNamedPackageData async
9 silly mapToRegistry name async
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/async
13 verbose request uri https://registry.npmjs.org/async
14 verbose request no auth needed
15 info attempt registry request try #1 at 12:05:38 PM
16 verbose request using bearer token for auth
17 verbose request id b9ee42a9618a23dd
18 http request GET https://registry.npmjs.org/async
19 http 200 https://registry.npmjs.org/async
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"4XCMOBG7U0EMAW9QZYGRHBIK5"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   'content-length': '132300',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 02 Dec 2015 08:35:40 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lcy1121-LCY',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1449045339.488589,VS0,VE806',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"4XCMOBG7U0EMAW9QZYGRHBIK5"',
21 silly get     'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=60',
21 silly get     'content-length': '132300',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 02 Dec 2015 08:35:40 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lcy1121-LCY',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1449045339.488589,VS0,VE806',
21 silly get     vary: 'Accept' } ]
22 verbose get saving async to /Users/Iman/.npm/registry.npmjs.org/async/.cache.json
23 verbose makeDirectory /Users/Iman/.npm creation not in flight; initializing
24 silly makeDirectory /Users/Iman/.npm uid: 501 gid: 20
25 silly install normalizeTree
26 verbose stack TypeError: Cannot set property 'lodash' of undefined
26 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:96:36
26 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:17:12
26 verbose stack     at RawTask.call (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/asap.js:40:19)
26 verbose stack     at flush (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/raw.js:50:29)
26 verbose stack     at process._tickCallback (node.js:355:11)
27 verbose cwd /Users/Iman/Documents/projects/squirl/squirl-server
28 error Darwin 14.5.0
29 error argv "node" "/usr/local/bin/npm" "install" "async" "--save"
30 error node v0.12.5
31 error npm  v3.5.0
32 error Cannot set property 'lodash' of undefined
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by Tiagojdferreira** [comment] 2015-12-03 21:20
I have tried to reproduce this bug and I did not succeed. 
Using nvm, I did:
````
nvm install v0.12.5
npm install npm@3.5.0 -g
npm install async --save
````
And I had no problems installing the package.

Have you tried installing a fresh version of node using nvm?

**Comment by megakoresh** [comment] 2015-12-03 21:33
Someone called me?
I think if possible npm should detect whether the a pre-3.0 version has been used before and offer to reinstall local and global modules on first use. I am not an expert at npm, but I have a feeling this has to do with the transition to flat folder structure from the nested one.

**Comment by ImanMh** [comment] 2015-12-04 13:33
I think I know what is the source of the problem, This is my package.json : 
```json
{
  "name": "sss",
  "private": true,
  "version": "0.0.0",
  "description": "a Sails application",
  "keywords": [],
  "dependencies": {
    "ejs": "~0.8.4",
    "grunt": "0.4.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "handlebars": "^4.0.4",
    "include-all": "~0.1.3",
    "node-uuid": "^1.4.7",
    "rc": "~0.5.0",
    "sails": "~0.11.2",
    "sails-disk": "~0.10.0",
    "sails-mongo": "^0.11.5"
  },
  "scripts": {
    "debug": "node debug app.js",
    "start": "node app.js"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "git@gitlab.com:server/servergit"
  },
  "author": "Iman",
  "license": "",
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-expect-file": "0.0.7",
    "gulp-sass": "^2.1.0"
  }
}
```
I can successfully install ```async``` library when I delete package.json so there should be a problem with this file.

**Comment by megawac** [comment] 2015-12-04 18:14
Dupe of https://github.com/npm/npm/issues/9676

**Comment by othiym23** [comment] 2015-12-04 18:31
So here's what I just tried, using `npm@next` (aka `npm@3.5.2`):

```
bauchelain% mkdir test-npm-2-kaboom
bauchelain% cd test-npm-2-kaboom
bauchelain% cat > package.json
// paste package.json from above
bauchelain% nave use 0.12 npm -v
Already installed: 0.12.9
using 0.12.9
2.14.9
bauchelain% nave use 0.12 npm install
Already installed: 0.12.9
using 0.12.9
// npm@2 runs the install without error
bauchelain% npm -v
3.5.2
bauchelain% npm install async --save
abbrev@1.0.7 node_modules/grunt-contrib-watch/node_modules/tiny-lr/node_modules/noptify/node_modules/nopt/node_modules/abbrev -> node_modules/abbrev
nopt@2.0.0 node_modules/grunt-contrib-watch/node_modules/tiny-lr/node_modules/noptify/node_modules/nopt -> node_modules/nopt
- kerberos@0.0.17 node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos
- nan@2.0.9 node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos/node_modules/nan
sss@0.0.0 /Users/ogd/Documents/projects/test-npm-2-kaboom
├── async@1.5.0
├─┬ gulp-sass@2.1.0
│ └─┬ node-sass@3.4.2
│   └─┬ request@2.67.0
│     └─┬ form-data@1.0.0-rc3
│       └── async@1.5.0
├─┬ handlebars@4.0.5
│ └── async@1.5.0
└─┬ sails@0.11.3
  └─┬ sails-generate@0.12.3
    └─┬ sails-generate-new@0.10.22
      └── async@1.5.0

npm WARN mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
```

So, starting from an `npm@2`-installed tree and then using the newest `npm@3`, I can't reproduce this issue. If you upgrade to `npm@next` does the problem still exist? If you `rm -rf node_modules` and start with a fresh install from scratch does the problem still exist?

**Comment by othiym23** [comment] 2015-12-04 18:32
@megawac The error message is the same, but I can't get a repro using `npm@latest` on either this or #9676, so I'm going to treat them as separate until we can identify whether it's the same underlying issue, or even an issue at all. Thanks for pointing out the similarity!

**Comment by ImanMh** [comment] 2015-12-05 09:13
Thanks for your response. I've also manually added async to my package.json and tried to run ```npm install```  This turned my node_modules directory into a mess. There are many packages in node_modules right now. here is a screenshot: 

![screen shot 1394-09-14 at 12 42 42](https://cloud.githubusercontent.com/assets/4482199/11607058/b783e6d6-9b4d-11e5-8d99-f00c7f37685f.png)

**Comment by KenanY** [comment] 2015-12-05 16:03
@ImanMh That is intended behavior. `npm@3` flattens your dependencies as much as possible.

**Comment by busches** [comment] 2016-09-20 18:38
@KenanY no updates in months and @othiym23and others can't reproduce

**Comment by KenanY** [comment] 2016-09-20 18:44
@busches Good catch, closing.

**Closed by KenanY** 2016-09-20 18:44 UTC
Labels: bug, needs-repro
