### ISSUE TITLE
npm-version disregards build metadata

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#12825] opened 2016-05-24 21:14 UTC
`npm version 1.2.3-foo+sha` is bumped and tagged as 1.2.3-foo, completely dropping any build metadata. As `+build` information is expressly documented in the semver spec, this is a spec compliance violation.

What's worse is the build metadata is dropped *silently* and the commit/tag proceeds without said metadata. Thus, subsequent similar attempts will likely fail as they attempt to duplicate an existing git-tag (same version-pre, if differentiated only be the build metadata, which was dropped). related to #3403

**Comment by othiym23** [comment] 2016-05-24 23:45
> As `+build` information is expressly documented in the semver spec, this is a spec compliance violation.

I don't mean to sound tendentious, but I think that's _a_ reading of the spec, but not necessarily the most obvious one:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

In `node-semver`, if two versions have the same precedence according to SemVer, they're the same version, because dependency resolution is based on there being a total ordering over semver versions. To me, it makes sense that the build metadata is dropped by `npm version`. (The build metadata won't ever be included in the version tag published to a registry.)

Because build metadata is [ignored for purposes of spec comparison](https://github.com/npm/node-semver/blob/master/semver.js#L105), that means it also doesn't count as part of the version identifier for publishing purposes. You may argue that this limits the utility of build metadata in SemVer, and I agree, but I think to both @isaacs and me, the current behavior is in conformance with the spec. As such, I'm going to close this as not a bug. I'd be happy to review patches that incorporate build information into tags, but be forewarned that would probably require changes to `node-semver` that are more subtle than they first appear.

**Closed by othiym23** 2016-05-24 23:45 UTC
Labels: support

**Comment by jasonkarns** [comment] 2016-05-25 13:19
I would understand that, per the spec, the build metadata doesn't impact ordering. But that's because it can't be sorted. It's presumed that build metadata is commonly git shas or other build specific, non orderable text. But to extrapolate that they are the *same version* simply because they can't be ordered makes no sense.

**Comment by abirmingham** [comment] 2017-10-18 15:23
@othiym23 thanks for the explanation. In my case I need to include metadata about the build (including commit sha and git branch) in order to meet reproducible builds criteria. I can use prerelease for this, but it feels like the wrong place for it according to semver. Build metadata feels like the right place, but if I have no way to publish build metadata to an npm server then I'm not sure what good it does.

If build metadata is ignored by npm-version and by npm servers, what is it good for? Perhaps I'm missing something.
