### ISSUE TITLE
npm ERR! tarball.destroy is not a function

### ISSUE THREAD

**Issue by krushnachandra** [npm/npm#13537] opened 2016-07-31 10:57 UTC
```
npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or                                                                                                                 locked, rename 'C:\Users\CMM\AppData\Local\Temp\npm-5816-a97fff8c\registry.npmj                                                                                                                s.org\express\-\express-4.14.0.tgz.1163441574' -> 'C:\Users\CMM\AppData\Local\Te                                                                                                                mp\npm-5816-a97fff8c\registry.npmjs.org\express\-\express-4.14.0.tgz'
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\CMM\\AppDa                                                                                                                ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.6
```

**Comment by othiym23** [comment] 2016-08-19 22:38
Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:38 UTC

**Comment by jpepper07** [comment] 2016-10-25 15:11
This issue was caused by ByteFence Anti-Malware on windows 10. I uninstalled and npm install immediately worked for me.

**Comment by anilgautamm** [comment] 2018-03-10 02:19
I am having this issue on mac os high sierra, What should I do?
