### ISSUE TITLE
npm outdated : cb() never called!

### ISSUE THREAD

**Issue by DickSmith** [npm/npm#17498] opened 2017-06-28 19:47 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
$ npm outdated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/...
[2017-06-28T19_40_43_223Z-debug.txt](https://github.com/npm/npm/files/1110012/2017-06-28T19_40_43_223Z-debug.txt)

/.npm/_logs/2017-06-28T19_39_42_336Z-debug.log
```
#### How can the CLI team reproduce the problem?

Upgrade to v5.0.4
```
npm i -g npm
npm outdated
```

### supporting information:

 - `npm -v` prints:
**5.0.4**
 - `node -v` prints:
**v7.10.0**
 - `npm config get registry` prints:
**https://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?:
**ProductName:	Mac OS X**
**ProductVersion:	10.12.5**
**BuildVersion:	16F73**
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by watilde** [comment] 2017-06-28 20:49
Hello! I think this issue is duplicated with https://github.com/npm/npm/issues/17433.

**Comment by kenany** [comment] 2017-06-28 21:43
Looks like a duplicate of https://github.com/npm/npm/issues/16825.

**Closed as completed by kenany** 2017-06-28 21:43 UTC
Labels: support, npm5
