### ISSUE TITLE
npm error (v3.8.6) Callback called more than once Windows Server 2008 R2

### ISSUE THREAD

**Issue by raw-deluxe** [npm/npm#12571] opened 2016-05-04 09:13 UTC
Hi there,

I have installed the newest node.js version 6.0.0 (x64) with npm version 3.8.6 on Windows Server 2008 R2 German x64 with all latest updates.

I'm getting the following error if I try to use the cmd "npm search mkdir"
"npm ERR! Callback called more than once."
The search result table is shown, but the error is displayed.

Gist for npm-debug.log:
https://gist.github.com/raw-deluxe/f05ed907cb6bac7b0e67ac2a7308f181

If I repeat the search, I get the following error:

https://gist.github.com/raw-deluxe/a8818a6183fd2032705d079a1b656a43

And the gist with the console output:
https://gist.github.com/raw-deluxe/b75579bf955c24b6351f694c34bea08c

The Windows Server machine does have a total of 32GB of RAM and about 20 GB free.

I even tried to update npm to the newest version with the cmd "npm install npm -g".
The problem persists with npm version 3.8.8.

In my opinion this is a bug and should be resolved asap.

Thanks in advance!

Kind regards from Germany,

raw-deluxe

**Comment by zkat** [comment] 2016-08-23 23:42
Closing as a duplicate of #12587

**Closed by zkat** 2016-08-23 23:42 UTC
Labels: big-bug, bug, search
