### ISSUE TITLE
Cat does't work with windows wild cards

### ISSUE THREAD

**Issue by DennisNerush** [npm/npm#11732] opened 2016-03-01 12:44 UTC
I have the following file structure:

```
|-package.json
|-output/
|-Client/
|------ js/
|-------- component1/
|---------------------------one.css 
|---------------------------one.js 
|---------component2/
|---------------------------two.css 
|---------------------------two.js 
```

The package.json and Client directory are in the same root directory.
I want to cat all the css files into a single css file.

Here is my Package.json:
  "scripts": {
    		"cat-css": "cat Client/js/*.css > output/styles.css"
  },

When I run npm run cat-css I get the following error:

Error: ENOENT: no such file or directory, open 'C:\dev\somefolder\somefolder\somefolder\Client\js\*.css'
    at Error (native)

I'm ruining it on Windows. Perhaps there is something wrong with the wild card?

[npm-debug.txt](https://github.com/npm/npm/files/152765/npm-debug.txt)

**Comment by othiym23** [comment] 2016-03-01 18:10
It's a little tricky writing package scripts that will work across Windows and the other platforms supported by npm, because the package script runner mostly just hands off commands to the underlying command shell. On Unix, that's `/bin/sh`, but on Windows, it's `cmd.exe`. In this case, this is tricky, because `cmd.exe` doesn't expand globs the same way that Unix command shells do – it passes the glob pattern to the command being executed, which is responsible for expanding it. Hence the `ENOENT` you're getting in this case, which is coming from the `cat` command, not npm.

Unfortunately, this means that either the files to be concatenated need to be explicitly enumerated on the package script line, or you need to find a concatenation utility that's written with Windows in mind and will do the glob expansion for you. The CLI team has [some ideas](https://github.com/npm/npm/issues/11291) about how to make this experience smoother in a future version of npm, but it's going to be a little while until we get to that point.

As this is the currently expected behavior of npm, I'm going to close this issue. Thanks for your time, though, and I hope you find a solution to this that doesn't feel too clunky!

**Closed by othiym23** 2016-03-01 18:10 UTC
Labels: support, windows
