### ISSUE TITLE
No clue what do 

### ISSUE THREAD

**Issue by worldlynx** [npm/npm#8732] opened 2015-06-27 20:05 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'foundation-cli',
1 verbose cli   'bower',
1 verbose cli   'gulp' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'foundation-cli', null ]
7 verbose cache add spec foundation-cli
8 silly cache add args [ 'bower', null ]
9 verbose cache add spec bower
10 silly cache add args [ 'gulp', null ]
11 verbose cache add spec gulp
12 silly cache add parsed spec { raw: 'foundation-cli',
12 silly cache add   scope: null,
12 silly cache add   name: 'foundation-cli',
12 silly cache add   rawSpec: '',
12 silly cache add   spec: '*',
12 silly cache add   type: 'range' }
13 silly addNamed foundation-cli@*
14 verbose addNamed "*" is a valid semver range for foundation-cli
15 silly addNameRange { name: 'foundation-cli', range: '*', hasData: false }
16 silly mapToRegistry name foundation-cli
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry uri https://registry.npmjs.org/foundation-cli
20 verbose addNameRange registry:https://registry.npmjs.org/foundation-cli not in flight; fetching
21 silly cache add parsed spec { raw: 'bower',
21 silly cache add   scope: null,
21 silly cache add   name: 'bower',
21 silly cache add   rawSpec: '',
21 silly cache add   spec: '*',
21 silly cache add   type: 'range' }
22 silly addNamed bower@*
23 verbose addNamed "*" is a valid semver range for bower
24 silly addNameRange { name: 'bower', range: '*', hasData: false }
25 silly mapToRegistry name bower
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/bower
29 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
30 silly cache add parsed spec { raw: 'gulp',
30 silly cache add   scope: null,
30 silly cache add   name: 'gulp',
30 silly cache add   rawSpec: '',
30 silly cache add   spec: '*',
30 silly cache add   type: 'range' }
31 silly addNamed gulp@*
32 verbose addNamed "*" is a valid semver range for gulp
33 silly addNameRange { name: 'gulp', range: '*', hasData: false }
34 silly mapToRegistry name gulp
35 silly mapToRegistry using default registry
36 silly mapToRegistry registry https://registry.npmjs.org/
37 silly mapToRegistry uri https://registry.npmjs.org/gulp
38 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
39 verbose request uri https://registry.npmjs.org/foundation-cli
40 verbose request no auth needed
41 info attempt registry request try #1 at 4:00:44 PM
42 verbose request id 2aa72208e9cad438
43 verbose etag "4P0UPV5QM014QUQS0198GAAHK"
44 http request GET https://registry.npmjs.org/foundation-cli
45 verbose request uri https://registry.npmjs.org/gulp
46 verbose request no auth needed
47 info attempt registry request try #1 at 4:00:45 PM
48 verbose etag "90XN1S3R3BONQPU7TA7OT2XEW"
49 http request GET https://registry.npmjs.org/gulp
50 verbose request uri https://registry.npmjs.org/bower
51 verbose request no auth needed
52 info attempt registry request try #1 at 4:00:45 PM
53 verbose etag "EXMI99QUQ4G9JF8M0AB6UVSTR"
54 http request GET https://registry.npmjs.org/bower
55 http 304 https://registry.npmjs.org/gulp
56 silly get cb [ 304,
56 silly get   { date: 'Sat, 27 Jun 2015 20:00:45 GMT',
56 silly get     via: '1.1 varnish',
56 silly get     'cache-control': 'max-age=60',
56 silly get     etag: '"90XN1S3R3BONQPU7TA7OT2XEW"',
56 silly get     age: '36',
56 silly get     connection: 'keep-alive',
56 silly get     'x-served-by': 'cache-jfk1030-JFK',
56 silly get     'x-cache': 'HIT',
56 silly get     'x-cache-hits': '1',
56 silly get     'x-timer': 'S1435435245.225646,VS0,VE0',
56 silly get     vary: 'Accept' } ]
57 verbose etag https://registry.npmjs.org/gulp from cache
58 verbose get saving gulp to /Users/jazz/.npm/registry.npmjs.org/gulp/.cache.json
59 http 304 https://registry.npmjs.org/bower
60 silly get cb [ 304,
60 silly get   { date: 'Sat, 27 Jun 2015 20:00:45 GMT',
60 silly get     via: '1.1 varnish',
60 silly get     'cache-control': 'max-age=60',
60 silly get     etag: '"EXMI99QUQ4G9JF8M0AB6UVSTR"',
60 silly get     age: '56',
60 silly get     connection: 'keep-alive',
60 silly get     'x-served-by': 'cache-jfk1024-JFK',
60 silly get     'x-cache': 'HIT',
60 silly get     'x-cache-hits': '1',
60 silly get     'x-timer': 'S1435435245.225786,VS0,VE1',
60 silly get     vary: 'Accept' } ]
61 verbose etag https://registry.npmjs.org/bower from cache
62 verbose get saving bower to /Users/jazz/.npm/registry.npmjs.org/bower/.cache.json
63 silly addNameRange number 2 { name: 'gulp', range: '*', hasData: true }
64 silly addNameRange versions [ 'gulp',
64 silly addNameRange   [ '0.0.1',
64 silly addNameRange     '0.0.2',
64 silly addNameRange     '0.0.3',
64 silly addNameRange     '0.0.4',
64 silly addNameRange     '0.0.5',
64 silly addNameRange     '0.0.7',
64 silly addNameRange     '0.0.8',
64 silly addNameRange     '0.0.9',
64 silly addNameRange     '0.1.0',
64 silly addNameRange     '0.2.0',
64 silly addNameRange     '1.0.0',
64 silly addNameRange     '1.1.0',
64 silly addNameRange     '1.2.0',
64 silly addNameRange     '1.2.1',
64 silly addNameRange     '2.0.0',
64 silly addNameRange     '2.0.1',
64 silly addNameRange     '2.1.0',
64 silly addNameRange     '2.2.0',
64 silly addNameRange     '2.3.0',
64 silly addNameRange     '2.4.0',
64 silly addNameRange     '2.4.1',
64 silly addNameRange     '2.6.0',
64 silly addNameRange     '2.6.1',
64 silly addNameRange     '2.7.0',
64 silly addNameRange     '3.0.0',
64 silly addNameRange     '3.1.1',
64 silly addNameRange     '3.1.2',
64 silly addNameRange     '3.1.3',
64 silly addNameRange     '3.1.4',
64 silly addNameRange     '3.2.0',
64 silly addNameRange     '3.2.1',
64 silly addNameRange     '3.2.2',
64 silly addNameRange     '3.2.3',
64 silly addNameRange     '3.2.4',
64 silly addNameRange     '3.2.5',
64 silly addNameRange     '3.3.0',
64 silly addNameRange     '3.3.1',
64 silly addNameRange     '3.3.2',
64 silly addNameRange     '3.3.4',
64 silly addNameRange     '3.4.0',
64 silly addNameRange     '3.5.0',
64 silly addNameRange     '3.5.1',
64 silly addNameRange     '3.5.2',
64 silly addNameRange     '3.5.5',
64 silly addNameRange     '3.5.6',
64 silly addNameRange     '3.6.0',
64 silly addNameRange     '3.6.1',
64 silly addNameRange     '3.6.2',
64 silly addNameRange     '3.7.0',
64 silly addNameRange     '3.8.0',
64 silly addNameRange     '3.8.1',
64 silly addNameRange     '3.8.2',
64 silly addNameRange     '3.8.3',
64 silly addNameRange     '3.8.4',
64 silly addNameRange     '3.8.5',
64 silly addNameRange     '3.8.6',
64 silly addNameRange     '3.8.7',
64 silly addNameRange     '3.8.8',
64 silly addNameRange     '3.8.9',
64 silly addNameRange     '3.8.10',
64 silly addNameRange     '3.8.11',
64 silly addNameRange     '3.9.0' ] ]
65 silly addNamed gulp@3.9.0
66 verbose addNamed "3.9.0" is a plain semver version for gulp
67 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
68 silly addNameRange versions [ 'bower',
68 silly addNameRange   [ '0.1.0',
68 silly addNameRange     '0.1.2',
68 silly addNameRange     '0.1.3',
68 silly addNameRange     '0.2.0',
68 silly addNameRange     '0.3.0',
68 silly addNameRange     '0.3.1',
68 silly addNameRange     '0.3.2',
68 silly addNameRange     '0.4.0',
68 silly addNameRange     '0.5.0',
68 silly addNameRange     '0.5.1',
68 silly addNameRange     '0.6.0',
68 silly addNameRange     '0.6.1',
68 silly addNameRange     '0.6.2',
68 silly addNameRange     '0.6.3',
68 silly addNameRange     '0.6.4',
68 silly addNameRange     '0.6.5',
68 silly addNameRange     '0.6.6',
68 silly addNameRange     '0.6.7',
68 silly addNameRange     '0.6.8',
68 silly addNameRange     '0.7.0',
68 silly addNameRange     '0.7.1',
68 silly addNameRange     '0.8.0',
68 silly addNameRange     '0.8.1',
68 silly addNameRange     '0.8.2',
68 silly addNameRange     '0.8.3',
68 silly addNameRange     '0.8.4',
68 silly addNameRange     '0.8.5',
68 silly addNameRange     '0.8.6',
68 silly addNameRange     '0.9.0',
68 silly addNameRange     '0.9.1',
68 silly addNameRange     '0.9.2',
68 silly addNameRange     '0.10.0',
68 silly addNameRange     '1.0.0',
68 silly addNameRange     '1.0.1',
68 silly addNameRange     '1.0.2',
68 silly addNameRange     '1.0.3',
68 silly addNameRange     '1.1.0',
68 silly addNameRange     '1.1.1',
68 silly addNameRange     '1.1.2',
68 silly addNameRange     '1.2.0',
68 silly addNameRange     '1.2.1',
68 silly addNameRange     '1.2.2',
68 silly addNameRange     '1.2.3',
68 silly addNameRange     '1.2.4',
68 silly addNameRange     '1.2.5',
68 silly addNameRange     '1.2.6',
68 silly addNameRange     '1.2.7',
68 silly addNameRange     '1.2.8',
68 silly addNameRange     '1.3.0',
68 silly addNameRange     '1.3.1',
68 silly addNameRange     '1.3.2',
68 silly addNameRange     '1.3.3',
68 silly addNameRange     '1.3.4',
68 silly addNameRange     '1.3.5',
68 silly addNameRange     '1.3.6',
68 silly addNameRange     '1.3.7',
68 silly addNameRange     '1.3.8',
68 silly addNameRange     '1.3.9',
68 silly addNameRange     '1.3.10',
68 silly addNameRange     '1.3.11',
68 silly addNameRange     '1.3.12',
68 silly addNameRange     '1.4.0',
68 silly addNameRange     '1.4.1' ] ]
69 silly addNamed bower@1.4.1
70 verbose addNamed "1.4.1" is a plain semver version for bower
71 http 304 https://registry.npmjs.org/foundation-cli
72 silly get cb [ 304,
72 silly get   { date: 'Sat, 27 Jun 2015 20:00:45 GMT',
72 silly get     via: '1.1 varnish',
72 silly get     'cache-control': 'max-age=60',
72 silly get     etag: '"4P0UPV5QM014QUQS0198GAAHK"',
72 silly get     age: '0',
72 silly get     connection: 'keep-alive',
72 silly get     'x-served-by': 'cache-jfk1026-JFK',
72 silly get     'x-cache': 'MISS',
72 silly get     'x-cache-hits': '0',
72 silly get     'x-timer': 'S1435435245.170394,VS0,VE83',
72 silly get     vary: 'Accept' } ]
73 verbose etag https://registry.npmjs.org/foundation-cli from cache
74 verbose get saving foundation-cli to /Users/jazz/.npm/registry.npmjs.org/foundation-cli/.cache.json
75 silly cache afterAdd gulp@3.9.0
76 verbose afterAdd /Users/jazz/.npm/gulp/3.9.0/package/package.json not in flight; writing
77 silly cache afterAdd bower@1.4.1
78 verbose afterAdd /Users/jazz/.npm/bower/1.4.1/package/package.json not in flight; writing
79 verbose afterAdd /Users/jazz/.npm/gulp/3.9.0/package/package.json written
80 silly addNameRange number 2 { name: 'foundation-cli', range: '*', hasData: true }
81 silly addNameRange versions [ 'foundation-cli',
81 silly addNameRange   [ '0.1.0',
81 silly addNameRange     '0.2.0',
81 silly addNameRange     '1.0.0-rc.1',
81 silly addNameRange     '1.0.0',
81 silly addNameRange     '1.0.1',
81 silly addNameRange     '1.0.2',
81 silly addNameRange     '1.0.3',
81 silly addNameRange     '1.0.4',
81 silly addNameRange     '1.1.0',
81 silly addNameRange     '1.1.1' ] ]
82 silly addNamed foundation-cli@1.1.1
83 verbose addNamed "1.1.1" is a plain semver version for foundation-cli
84 verbose afterAdd /Users/jazz/.npm/bower/1.4.1/package/package.json written
85 silly cache afterAdd foundation-cli@1.1.1
86 verbose afterAdd /Users/jazz/.npm/foundation-cli/1.1.1/package/package.json not in flight; writing
87 verbose afterAdd /Users/jazz/.npm/foundation-cli/1.1.1/package/package.json written
88 silly install resolved [ { name: 'gulp',
88 silly install resolved     description: 'The streaming build system',
88 silly install resolved     version: '3.9.0',
88 silly install resolved     homepage: 'http://gulpjs.com',
88 silly install resolved     repository: { type: 'git', url: 'git+https://github.com/gulpjs/gulp.git' },
88 silly install resolved     author:
88 silly install resolved      { name: 'Fractal',
88 silly install resolved        email: 'contact@wearefractal.com',
88 silly install resolved        url: 'http://wearefractal.com/' },
88 silly install resolved     tags: [ 'build', 'stream', 'system', 'make', 'tool', 'asset', 'pipeline' ],
88 silly install resolved     files: [ 'index.js', 'lib', 'bin', 'completion' ],
88 silly install resolved     bin: { gulp: './bin/gulp.js' },
88 silly install resolved     man: [ 'gulp.1' ],
88 silly install resolved     dependencies:
88 silly install resolved      { archy: '^1.0.0',
88 silly install resolved        chalk: '^1.0.0',
88 silly install resolved        deprecated: '^0.0.1',
88 silly install resolved        'gulp-util': '^3.0.0',
88 silly install resolved        interpret: '^0.6.2',
88 silly install resolved        liftoff: '^2.1.0',
88 silly install resolved        minimist: '^1.1.0',
88 silly install resolved        orchestrator: '^0.3.0',
88 silly install resolved        'pretty-hrtime': '^1.0.0',
88 silly install resolved        semver: '^4.1.0',
88 silly install resolved        tildify: '^1.0.0',
88 silly install resolved        v8flags: '^2.0.2',
88 silly install resolved        'vinyl-fs': '^0.3.0' },
88 silly install resolved     devDependencies:
88 silly install resolved      { coveralls: '^2.7.0',
88 silly install resolved        'graceful-fs': '^3.0.0',
88 silly install resolved        istanbul: '^0.3.0',
88 silly install resolved        jscs: '~1.12.0',
88 silly install resolved        jshint: '^2.5.0',
88 silly install resolved        'jshint-stylish': '^1.0.0',
88 silly install resolved        'marked-man': '^0.1.3',
88 silly install resolved        mkdirp: '^0.5.0',
88 silly install resolved        mocha: '^2.0.1',
88 silly install resolved        'mocha-lcov-reporter': '^0.0.1',
88 silly install resolved        q: '^1.0.0',
88 silly install resolved        rimraf: '^2.2.5',
88 silly install resolved        should: '^5.0.1' },
88 silly install resolved     scripts:
88 silly install resolved      { prepublish: 'marked-man --name gulp docs/CLI.md > gulp.1',
88 silly install resolved        lint: 'jshint lib bin test index.js --reporter node_modules/jshint-stylish/stylish.js --exclude node_modules && jscs lib bin test index.js',
88 silly install resolved        test: 'npm run-script lint && mocha --reporter spec',
88 silly install resolved        coveralls: 'istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage' },
88 silly install resolved     engines: { node: '>= 0.9' },
88 silly install resolved     license: 'MIT',
88 silly install resolved     gitHead: '657213a52d5e9c19b85df6a42f76341a98c08ae8',
88 silly install resolved     bugs: { url: 'https://github.com/gulpjs/gulp/issues' },
88 silly install resolved     _id: 'gulp@3.9.0',
88 silly install resolved     _shasum: 'cf1fba4cb558bb8c6ae6c9613f583ae2620d214a',
88 silly install resolved     _from: 'gulp@*',
88 silly install resolved     _npmVersion: '2.8.3',
88 silly install resolved     _nodeVersion: '0.10.36',
88 silly install resolved     _npmUser: { name: 'phated', email: 'blaine@iceddev.com' },
88 silly install resolved     maintainers: [ [Object], [Object] ],
88 silly install resolved     dist:
88 silly install resolved      { shasum: 'cf1fba4cb558bb8c6ae6c9613f583ae2620d214a',
88 silly install resolved        tarball: 'http://registry.npmjs.org/gulp/-/gulp-3.9.0.tgz' },
88 silly install resolved     directories: {},
88 silly install resolved     _resolved: 'https://registry.npmjs.org/gulp/-/gulp-3.9.0.tgz',
88 silly install resolved     readme: 'ERROR: No README data found!' },
88 silly install resolved   { name: 'bower',
88 silly install resolved     version: '1.4.1',
88 silly install resolved     description: 'The browser package manager',
88 silly install resolved     author: { name: 'Twitter' },
88 silly install resolved     licenses: [ [Object] ],
88 silly install resolved     repository: { type: 'git', url: 'git+https://github.com/bower/bower.git' },
88 silly install resolved     main: 'lib',
88 silly install resolved     homepage: 'http://bower.io',
88 silly install resolved     engines: { node: '>=0.10.0' },
88 silly install resolved     dependencies:
88 silly install resolved      { abbrev: '^1.0.5',
88 silly install resolved        archy: '1.0.0',
88 silly install resolved        'bower-config': '^0.6.1',
88 silly install resolved        'bower-endpoint-parser': '^0.2.2',
88 silly install resolved        'bower-json': '^0.4.0',
88 silly install resolved        'bower-logger': '^0.2.2',
88 silly install resolved        'bower-registry-client': '^0.3.0',
88 silly install resolved        cardinal: '0.4.4',
88 silly install resolved        chalk: '^1.0.0',
88 silly install resolved        chmodr: '0.1.0',
88 silly install resolved        configstore: '^0.3.2',
88 silly install resolved        'decompress-zip': '^0.1.0',
88 silly install resolved        fstream: '^1.0.3',
88 silly install resolved        'fstream-ignore': '^1.0.2',
88 silly install resolved        github: '^0.2.3',
88 silly install resolved        glob: '^4.3.2',
88 silly install resolved        'graceful-fs': '^3.0.5',
88 silly install resolved        handlebars: '^2.0.0',
88 silly install resolved        inquirer: '0.8.0',
88 silly install resolved        insight: '^0.5.0',
88 silly install resolved        'is-root': '^1.0.0',
88 silly install resolved        junk: '^1.0.0',
88 silly install resolved        lockfile: '^1.0.0',
88 silly install resolved        'lru-cache': '^2.5.0',
88 silly install resolved        mkdirp: '0.5.0',
88 silly install resolved        mout: '^0.11.0',
88 silly install resolved        nopt: '^3.0.1',
88 silly install resolved        opn: '^1.0.1',
88 silly install resolved        'p-throttler': '0.1.1',
88 silly install resolved        promptly: '0.2.0',
88 silly install resolved        q: '^1.1.2',
88 silly install resolved        request: '2.53.0',
88 silly install resolved        'request-progress': '0.3.1',
88 silly install resolved        retry: '0.6.1',
88 silly install resolved        rimraf: '^2.2.8',
88 silly install resolved        semver: '^2.3.0',
88 silly install resolved        'shell-quote': '^1.4.2',
88 silly install resolved        'stringify-object': '^1.0.0',
88 silly install resolved        'tar-fs': '^1.4.1',
88 silly install resolved        tmp: '0.0.24',
88 silly install resolved        'update-notifier': '^0.3.0',
88 silly install resolved        'user-home': '^1.1.0',
88 silly install resolved        which: '^1.0.8' },
88 silly install resolved     devDependencies:
88 silly install resolved      { chai: '^1.10.0',
88 silly install resolved        coveralls: '^2.11.2',
88 silly install resolved        'expect.js': '^0.3.1',
88 silly install resolved        grunt: '^0.4.5',
88 silly install resolved        'grunt-cli': '^0.1.13',
88 silly install resolved        'grunt-contrib-jshint': '^0.10.0',
88 silly install resolved        'grunt-contrib-watch': '^0.6.1',
88 silly install resolved        'grunt-exec': '^0.4.6',
88 silly install resolved        'grunt-simple-mocha': '^0.4.0',
88 silly install resolved        istanbul: '^0.3.5',
88 silly install resolved        'load-grunt-tasks': '^2.0.0',
88 silly install resolved        mocha: '^2.1.0',
88 silly install resolved        multiline: '^1.0.2',
88 silly install resolved        nock: '^0.56.0',
88 silly install resolved        'node-uuid': '^1.4.2',
88 silly install resolved        proxyquire: '^1.3.0',
88 silly install resolved        'spawn-sync': '^1.0.5' },
88 silly install resolved     scripts: { test: 'grunt test' },
88 silly install resolved     bin: { bower: 'bin/bower' },
88 silly install resolved     preferGlobal: true,
88 silly install resolved     gitHead: 'a1287416d40f944d58cb8f2e774e2076bfffd32f',
88 silly install resolved     bugs: { url: 'https://github.com/bower/bower/issues' },
88 silly install resolved     _id: 'bower@1.4.1',
88 silly install resolved     _shasum: 'a18be39d030792754f30f1c5b32d37b0156ba8dd',
88 silly install resolved     _from: 'bower@*',
88 silly install resolved     _npmVersion: '2.7.4',
88 silly install resolved     _nodeVersion: '0.12.0',
88 silly install resolved     _npmUser: { name: 'sheerun', email: 'sheerun@sher.pl' },
88 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
88 silly install resolved     dist:
88 silly install resolved      { shasum: 'a18be39d030792754f30f1c5b32d37b0156ba8dd',
88 silly install resolved        tarball: 'http://registry.npmjs.org/bower/-/bower-1.4.1.tgz' },
88 silly install resolved     directories: {},
88 silly install resolved     _resolved: 'https://registry.npmjs.org/bower/-/bower-1.4.1.tgz',
88 silly install resolved     readme: 'ERROR: No README data found!' },
88 silly install resolved   { name: 'foundation-cli',
88 silly install resolved     version: '1.1.1',
88 silly install resolved     description: 'Command-line interface for Foundation for Apps.',
88 silly install resolved     author: { name: 'ZURB' },
88 silly install resolved     main: 'lib/index.js',
88 silly install resolved     bin: { 'foundation-apps': './bin/cli.js' },
88 silly install resolved     dependencies:
88 silly install resolved      { async: '^0.9.0',
88 silly install resolved        bower: '^1.3.12',
88 silly install resolved        colors: '^1.0.3',
88 silly install resolved        exec: '^0.1.2',
88 silly install resolved        'is-root': '^1.0.0',
88 silly install resolved        nopt: '^3.0.1',
88 silly install resolved        npm: '^2.1.12',
88 silly install resolved        open: '0.0.5',
88 silly install resolved        rimraf: '^2.2.8',
88 silly install resolved        semver: '^4.3.0',
88 silly install resolved        'string-length': '^1.0.0',
88 silly install resolved        'update-notifier': '^0.2.2',
88 silly install resolved        which: '^1.0.8' },
88 silly install resolved     repository:
88 silly install resolved      { type: 'git',
88 silly install resolved        url: 'git+https://github.com/zurb/foundation-cli.git' },
88 silly install resolved     bugs: { url: 'https://github.com/zurb/foundation-cli/issues' },
88 silly install resolved     scripts:
88 silly install resolved      { postinstall: 'node lib/welcome.js',
88 silly install resolved        test: 'node bin/cli.js new test --debug' },
88 silly install resolved     preferGlobal: true,
88 silly install resolved     engines: { node: '>=0.10.33' },
88 silly install resolved     license: 'MIT',
88 silly install resolved     gitHead: '7fef13ec82e2454cbcbcf986dc55cc6efa05477e',
88 silly install resolved     homepage: 'https://github.com/zurb/foundation-cli',
88 silly install resolved     _id: 'foundation-cli@1.1.1',
88 silly install resolved     _shasum: '7fad96a44a73bcd3e00f7f7e8e4562231b546544',
88 silly install resolved     _from: 'foundation-cli@*',
88 silly install resolved     _npmVersion: '1.4.28',
88 silly install resolved     _npmUser: { name: 'gakimball', email: 'geoff@zurb.com' },
88 silly install resolved     maintainers: [ [Object], [Object] ],
88 silly install resolved     dist:
88 silly install resolved      { shasum: '7fad96a44a73bcd3e00f7f7e8e4562231b546544',
88 silly install resolved        tarball: 'http://registry.npmjs.org/foundation-cli/-/foundation-cli-1.1.1.tgz' },
88 silly install resolved     directories: {},
88 silly install resolved     _resolved: 'https://registry.npmjs.org/foundation-cli/-/foundation-cli-1.1.1.tgz',
88 silly install resolved     readme: 'ERROR: No README data found!' } ]
89 info install gulp@3.9.0 into /usr/local/lib
90 info install bower@1.4.1 into /usr/local/lib
91 info install foundation-cli@1.1.1 into /usr/local/lib
92 info installOne gulp@3.9.0
93 verbose installOne of gulp to /usr/local/lib not in flight; installing
94 info installOne bower@1.4.1
95 verbose installOne of bower to /usr/local/lib not in flight; installing
96 info installOne foundation-cli@1.1.1
97 verbose installOne of foundation-cli to /usr/local/lib not in flight; installing
98 warn locking Error: EACCES, open '/Users/jazz/.npm/_locks/bower-e8debc5417026b57.lock'
98 warn locking     at Error (native)
98 warn locking  /Users/jazz/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/jazz/.npm/_locks/bower-e8debc5417026b57.lock']
98 warn locking   errno: -13,
98 warn locking   code: 'EACCES',
98 warn locking   path: '/Users/jazz/.npm/_locks/bower-e8debc5417026b57.lock' }
99 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
99 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
99 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
99 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
99 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
99 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
99 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
99 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
100 verbose cwd /Users/jazz
101 error Darwin 14.3.0
102 error argv "node" "/usr/local/bin/npm" "install" "-g" "foundation-cli" "bower" "gulp"
103 error node v0.12.5
104 error npm  v2.11.2
105 error Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
106 error If you need help, you may report this error at:
106 error     <https://github.com/npm/npm/issues>
107 verbose exit [ 1, true ]

**Comment by ldez** [comment] 2015-06-28 09:56
try to suppress all `.lock` file from folder `/Users/jazz/.npm/_locks/` and check user permission on this folder.

**Comment by eric96k** [comment] 2015-06-30 21:21
You issue looks to be the same as this one, which is a folder permission issue.
https://github.com/npm/npm/issues/8498

I had the same log file as you and run the solution there and it worked.

**Comment by zkat** [comment] 2016-02-03 21:58
Closing as a duplicate of #8498

**Closed by zkat** 2016-02-03 21:58 UTC
Labels: support
