### ISSUE TITLE
Upon using big private repositories, npm search can fail.

### ISSUE THREAD

**Issue by AlexeiVainshtein** [npm/npm#13744] opened 2016-08-23 19:11 UTC
If the private registry is big (bigger then the official one) then the npm search fails:

npm verb stack Error: toString failed
npm verb stack  at Buffer.toString (buffer.js:379:11)
npm verb stack  at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:193:19)
npm verb stack  at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
npm verb stack  at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
npm verb stack  at emitTwo (events.js:87:13)
npm verb stack  at Request.emit (events.js:172:7)
npm verb stack  at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
npm verb stack  at emitOne (events.js:82:20)
npm verb stack  at Request.emit (events.js:169:7)
npm verb stack  at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)

It seems that NPM can read only 256mb +- of String, however, in my registry the String that is returned is bigger and therefore the above error is thrown.

**Comment by zkat** [comment] 2016-08-23 21:31
Hey, there's some [work in progress](https://github.com/npm/npm/pull/10615) to fix these issues in general and have a fully-streamed search on the CLI. Stand by for news on that. There's dupes of this but I'll hunt them down and mark them as such later. I picked up the work from @aredridel and I'm finishing up and polishing some changes :)

**Comment by zkat** [comment] 2016-08-23 23:36
Closing as a duplicate of https://github.com/npm/npm/issues/12619

**Closed by zkat** 2016-08-23 23:36 UTC
Labels: big-bug, bug, search
