### ISSUE TITLE
npm update chooses higher version number over latest published package

### ISSUE THREAD

**Issue by doublerebel** [npm/npm#7215] opened 2015-01-25 23:43 UTC
Hello,

I just ran into stormpath/passport-stormpath#20, where an old version was versioned starting at 1.0.3 but the newer versions are 0.x.x .  `npm install` correctly installs the latest `0.2.3`, and `npm outdated` correctly recognizes the `0.2.3` version as latest when either `0.2.3` or `1.0.3` are installed.  Only `npm update` seems to think that `1.0.3` should be installed as an update to `0.2.3`.

I am using `>=0.2.3` for version range in my package.json, but that shouldn't be an issue -- `npm update` should have the same versioning logic as `install` and `outdated`.

I searched through issues but the only one that might be relevant is #6778 ?

Thanks for npm!

**Comment by smikes** [comment] 2015-01-27 23:53
I think the problem you are seeing is that `npm update` explicitly does not honor semantic versioning, which is why `npm update` should not (in general) be used.

I would recommend avoiding `npm update` and using tools such as `npm-check` (npm install -g npm-check) instead.

Also, you may wish to open an issue on `passport-stormpath` suggesting that they bump their major version to `2.0.0`, since that's better practice than having the latest version be a pre-stable (0.x.y) when a 1.w.z version has already been published.

**Comment by doublerebel** [comment] 2015-01-28 19:13
I'm not aware of any other package manager where `update` works in this manner.  If `update` should not be used, I propose it should be removed.

If it is to stay, it should have the same versioning logic as `install` and `outdated`, like other package managers.  Are there any users that actually depend on this unique feature of update?  Is there some advantage that I'm not seeing?

**Comment by smikes** [comment] 2015-01-28 19:42
>  I propose it should be removed.

I do not disagree with this.

I don't have enough of the history to know why it's present, why it ignores semver, why it hasn't yet been removed/fixed.

**Comment by doublerebel** [comment] 2015-01-28 20:29
Thanks @smikes, I appreciate the quick reply, I know npm has plenty of issues to sift through.  Perhaps it's time for a blog post "npm update considered harmful" :wink:

**Comment by nathan7** [comment] 2015-01-28 20:34
@doublerebel http://meyerweb.com/eric/comment/chech.html (;

**Comment by smikes** [comment] 2015-01-28 20:41
I believe the title of the #npm channel on Freenode is "don't use npm update"

Here's the issue about fixing `npm update` https://github.com/npm/npm/issues/6247

**Comment by smikes** [comment] 2015-02-19 13:42
Can this issue now be closed?  It's effectively a duplicate of #6247.

**Comment by smikes** [comment] 2015-02-22 14:43
Actually, `npm update` does respect semver -- saying it didn't was an error on my part.

The thing I missed before was this:
> I am using >=0.2.3 for version range in my package.json, but that shouldn't be an issue -- npm update should have the same versioning logic as install and outdated.

For this package, since the `1.0.x` versions are to be avoided, can you set your requirement to `">= 0.2.3 <1.0"` ? That would prevent `update` from installing the `1.0` versions.

**Comment by smikes** [comment] 2015-02-24 13:12
Is this still a problem for you?

Can you try the fix I suggested, which is to set your `semver` version requirement to exclude the problem versions:

```
"dependencies": {
  "passport-stormpath": ">= 0.2.3 <1.0"
}
```

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by oncletom** [comment] 2015-03-02 21:12
If it is considered harmful, and acknowledged this way, could the doc be updated to eventually explain if there is a different mechanism with `npm update -g` and `npm update`?

Because so far, nothing in the doc states that the `update` command ignores the semver spec: https://docs.npmjs.com/cli/update

**Comment by othiym23** [comment] 2015-03-02 21:20
@oncletom If you read [this comment](https://github.com/npm/npm/issues/7215#issuecomment-75438431) from @smikes, you'll see that we all got a little confused for a while, but `npm update` *does* respect semver, it just does so in a way that can cause problems because it runs the whole update process simultaneously, which can, in some cases, leave the tree in an undefined state. I believe this behavior is what @doublerebel was encountering in the OP.

If you upgrade to `npm@2.6.1` (the latest stable version), `npm update` and `npm update -g` are much safer, thanks to changing the default depth for the update operation to only change top-level packages. As such, I'm going to go ahead and close this issue as resolved. There are further improvements coming in the next major version of npm that will also improve the safety of running `npm update` with a depth greater than 0, but most of the time, that's not something you want to do anyway.

**Closed by othiym23** 2015-03-02 21:20 UTC
Labels: support
