### ISSUE TITLE
Error installing heroku CLI in my mac osx terminal

### ISSUE THREAD

**Issue by ragz2dev** [npm/npm#12265] opened 2016-04-08 01:14 UTC
```
apples-iMac:~ apple$ heroku
heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package. 
 ▸    npm ERR! Darwin 15.4.0
 ▸    npm ERR! argv "/Users/apple/.heroku/node-5.10.1-darwin-amd64/node" "/Users/apple/.heroku/npm-3.8.5/cli.js" "install" "heroku-apps" "heroku-cli-addons" "heroku-fork" "heroku-git" "heroku-local" "heroku-orgs" "heroku-pipelines" "heroku-run" "heroku-spaces" "heroku-status"
 ▸    npm ERR! node v5.10.1
 ▸    npm ERR! npm  v3.8.5
 ▸    
 ▸    npm ERR! shasum check failed for /var/folders/db/3b53s_b97dg2zqg78ndnwbgc0000gp/T/npm-42213-05685087/cli-npm.heroku.com/heroku-cli-util/-/heroku-cli-util-5.8.0/875ced5426ee4f58fcd271bd71609eac90e07db1.tgz
 ▸    npm ERR! Expected: 875ced5426ee4f58fcd271bd71609eac90e07db1
 ▸    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
 ▸    npm ERR! From:     https://cli-npm.heroku.com/heroku-cli-util/-/heroku-cli-util-5.8.0/875ced5426ee4f58fcd271bd71609eac90e07db1.tgz
 ▸    npm ERR! 
 ▸    npm ERR! If you need help, you may report this error at:
 ▸    npm ERR!     <https://github.com/npm/npm/issues>
 ▸    
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /Users/apple/.heroku/npm-debug.log
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package. 
 ▸    npm ERR! Darwin 15.4.0
 ▸    npm ERR! argv "/Users/apple/.heroku/node-5.10.1-darwin-amd64/node" "/Users/apple/.heroku/npm-3.8.5/cli.js" "install" "heroku-apps" "heroku-cli-addons" "heroku-fork" "heroku-git" "heroku-local" "heroku-orgs" "heroku-pipelines" "heroku-run" "heroku-spaces" "heroku-status"
 ▸    npm ERR! node v5.10.1
 ▸    npm ERR! npm  v3.8.5
 ▸    
 ▸    npm ERR! shasum check failed for /var/folders/db/3b53s_b97dg2zqg78ndnwbgc0000gp/T/npm-42218-8627c18f/cli-npm.heroku.com/heroku-cli-util/-/heroku-cli-util-5.8.0/875ced5426ee4f58fcd271bd71609eac90e07db1.tgz
 ▸    npm ERR! Expected: 875ced5426ee4f58fcd271bd71609eac90e07db1
 ▸    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
 ▸    npm ERR! From:     https://cli-npm.heroku.com/heroku-cli-util/-/heroku-cli-util-5.8.0/875ced5426ee4f58fcd271bd71609eac90e07db1.tgz
 ▸    npm ERR! 
 ▸    npm ERR! If you need help, you may report this error at:
 ▸    npm ERR!     <https://github.com/npm/npm/issues>
 ▸    
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /Users/apple/.heroku/npm-debug.log
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
```

**Comment by zkat** [comment] 2016-12-09 00:44
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:44 UTC
Labels: network, support
