### ISSUE TITLE
Not able to install angular/cli  ... please find log file.

### ISSUE THREAD

**Issue by dhrubajyoti** [npm/npm#16499] opened 2017-05-02 21:10 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@angular%2fcli
16 verbose request uri https://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 4:42:31 PM
19 verbose request id fcc80c6db4ca731d
20 http request GET https://registry.npmjs.org/@angular%2fcli
21 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
21 verbose stack     at Error (native)
21 verbose stack     at Object.createSecureContext (_tls_common.js:90:19)
21 verbose stack     at Object.exports.connect (_tls_wrap.js:1033:48)
21 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:201:28
21 verbose stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:162:7)
21 verbose stack     at ClientRequest.g (events.js:291:16)
21 verbose stack     at emitThree (events.js:116:13)
21 verbose stack     at ClientRequest.emit (events.js:194:7)
21 verbose stack     at Socket.socketOnData (_http_client.js:394:11)
21 verbose stack     at emitOne (events.js:96:13)
22 verbose cwd C:\Users\deyd
23 error Windows_NT 6.1.7601
24 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
25 error node v6.10.1
26 error npm  v3.10.10
27 error error:0906D06C:PEM routines:PEM_read_bio:no start line
28 error If you need help, you may report this error at:
28 error     <https://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-05-02 21:27
Hello! This is a duplicate of #10897. Please try `npm config set registry http://registry.npmjs.org`.

**Closed** 2017-06-16 21:53 UTC
Labels: bot-closed, support
