### ISSUE TITLE
Refusing to install npm as a dependency of itself

### ISSUE THREAD

**Issue by jiw0220** [npm/npm#9723] opened 2015-09-23 02:51 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   'npm' ]
2 info using npm@3.3.3
3 info using node@v4.1.1
4 silly mapToRegistry name npm
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/npm
8 verbose request uri https://registry.npmjs.org/npm
9 verbose request no auth needed
10 info attempt registry request try #1 at 10:33:40
11 verbose request id e3baca96c2b154cc
12 http request GET https://registry.npmjs.org/npm
13 http 200 https://registry.npmjs.org/npm
14 silly get cb [ 200,
14 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
14 silly get     etag: '"7QIP2IYFXYXAPP14CBDH48NPR"',
14 silly get     'content-type': 'application/json',
14 silly get     'cache-control': 'max-age=60',
14 silly get     'content-length': '3269887',
14 silly get     'accept-ranges': 'bytes',
14 silly get     date: 'Wed, 23 Sep 2015 02:33:36 GMT',
14 silly get     via: '1.1 varnish',
14 silly get     age: '44',
14 silly get     connection: 'keep-alive',
14 silly get     'x-served-by': 'cache-nrt6125-NRT',
14 silly get     'x-cache': 'HIT',
14 silly get     'x-cache-hits': '1',
14 silly get     'x-timer': 'S1442975616.870211,VS0,VE43',
14 silly get     vary: 'Accept' } ]
15 verbose get saving npm to C:\Users\Administrator\AppData\Roaming\npm-cache\registry.npmjs.org\npm\.cache.json
16 info outdated updating [ { dep:
16 info outdated      { id: 5,
16 info outdated        package: [Object],
16 info outdated        path: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm',
16 info outdated        realpath: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm',
16 info outdated        parent: [Object],
16 info outdated        isLink: false,
16 info outdated        children: [Object],
16 info outdated        error: null,
16 info outdated        loaded: false,
16 info outdated        requiredBy: [],
16 info outdated        requires: [Object],
16 info outdated        missingDeps: {},
16 info outdated        missingDevDeps: {},
16 info outdated        userRequired: false,
16 info outdated        existing: false },
16 info outdated     depname: 'npm',
16 info outdated     current: '3.3.3',
16 info outdated     wanted: '3.3.4',
16 info outdated     latest: '3.3.3',
16 info outdated     req: '*',
16 info outdated     what: 'npm@3.3.4' } ]
17 silly loadCurrentTree Starting
18 silly install loadCurrentTree
19 silly install readGlobalPackageData
20 silly fetchPackageMetaData npm@3.3.4
21 silly fetchNamedPackageData npm
22 silly mapToRegistry name npm
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry https://registry.npmjs.org/
25 silly mapToRegistry uri https://registry.npmjs.org/npm
26 verbose get https://registry.npmjs.org/npm not expired, no request
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install npm as a dependency of itself
44 verbose stack     at checkSelf (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:40:14)
44 verbose stack     at Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
44 verbose stack     at LOOP (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
44 verbose stack     at chain (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
44 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:15:5
44 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
45 verbose cwd D:\workspace\html5\AnpiSportMobileWeb_release
46 error Windows_NT 6.1.7600
47 error argv "D:\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "npm"
48 error node v4.1.1
49 error npm  v3.3.3
50 error code ENOSELF
51 error Refusing to install npm as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

please help me...

I run the Grunt task is not normal...

Doubt due to the problem...

**Comment by Ouro17** [comment] 2015-09-23 17:15
I have the same problem!
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Ouro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm',
1 verbose cli   '-g',
1 verbose cli   '--verbose' ]
2 info using npm@3.3.3
3 info using node@v4.1.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/npm
13 verbose request uri https://registry.npmjs.org/npm
14 verbose request no auth needed
15 info attempt registry request try #1 at 19:11:53
16 verbose request id 824ba8fb54120ffc
17 verbose etag "7QIP2IYFXYXAPP14CBDH48NPR"
18 http request GET https://registry.npmjs.org/npm
19 http 304 https://registry.npmjs.org/npm
20 silly get cb [ 304,
20 silly get   { date: 'Wed, 23 Sep 2015 17:12:25 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     'cache-control': 'max-age=60',
20 silly get     etag: '"7QIP2IYFXYXAPP14CBDH48NPR"',
20 silly get     age: '33',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-lhr6334-LHR',
20 silly get     'x-cache': 'HIT',
20 silly get     'x-cache-hits': '2',
20 silly get     'x-timer': 'S1443028345.119013,VS0,VE0',
20 silly get     vary: 'Accept' } ]
21 verbose etag https://registry.npmjs.org/npm from cache
22 verbose get saving npm to C:\Users\Ouro\AppData\Roaming\npm-cache\registry.npmjs.org\npm\.cache.json
23 silly install normalizeTree
24 silly loadCurrentTree Finishing
25 silly loadIdealTree Starting
26 silly install loadIdealTree
27 silly cloneCurrentTree Starting
28 silly install cloneCurrentTreeToIdealTree
29 silly cloneCurrentTree Finishing
30 silly loadShrinkwrap Starting
31 silly install loadShrinkwrap
32 silly loadShrinkwrap Finishing
33 silly loadAllDepsIntoIdealTree Starting
34 silly install loadAllDepsIntoIdealTree
35 silly rollbackFailedOptional Starting
36 silly rollbackFailedOptional Finishing
37 silly runTopLevelLifecycles Starting
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: Refusing to install npm as a dependency of itself
40 verbose stack     at checkSelf (C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:40:14)
40 verbose stack     at Array.<anonymous> (C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
40 verbose stack     at LOOP (C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
40 verbose stack     at chain (C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
40 verbose stack     at C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:15:5
40 verbose stack     at C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
40 verbose stack     at Array.forEach (native)
40 verbose stack     at C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
40 verbose stack     at Array.forEach (native)
40 verbose stack     at asyncMap (C:\Users\Ouro\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
41 verbose cwd C:\Users\Ouro
42 error Windows_NT 10.0.10240
43 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ouro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g" "--verbose"
44 error node v4.1.1
45 error npm  v3.3.3
46 error code ENOSELF
47 error Refusing to install npm as a dependency of itself
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]

**Comment by ldez** [comment] 2015-09-28 10:35
Duplicate of #9695

**Comment by ehsalazar** [comment] 2015-11-04 23:06
Closing as a duplicate. I believe this has been addressed as of v3.3.5. [Updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) should get it in order. If it doesn't, please let us know and we'll happily reopen this issue.

**Closed by ehsalazar** 2015-11-04 23:06 UTC

**Comment by ranganathbrr** [comment] 2016-03-03 13:40
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mysql' ]
2 info using npm@3.6.0
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mysql
8 silly fetchNamedPackageData mysql
9 silly mapToRegistry name mysql
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/mysql
13 verbose request uri https://registry.npmjs.org/mysql
14 verbose request no auth needed
15 info attempt registry request try #1 at 7:04:07 PM
16 verbose request using bearer token for auth
17 verbose request id 3c91ee8786034265
18 verbose etag "27ID9DD8U313TE78DUW2W4IXR"
19 http request GET https://registry.npmjs.org/mysql
20 http 304 https://registry.npmjs.org/mysql
21 verbose headers { 'cache-control': 'max-age=300',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Thu, 03 Mar 2016 13:34:12 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-sin6926-SIN',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1457012051.838105,VS0,VE973' }
22 silly get cb [ 304,
22 silly get   { 'cache-control': 'max-age=300',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Thu, 03 Mar 2016 13:34:12 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-sin6926-SIN',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1457012051.838105,VS0,VE973' } ]
23 verbose etag https://registry.npmjs.org/mysql from cache
24 verbose get saving mysql to C:\Users\Admin\AppData\Roaming\npm-cache\registry.npmjs.org\mysql\.cache.json
25 verbose correctMkdir C:\Users\Admin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install mysql as a dependency of itself
43 verbose stack     at checkSelf (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\sp-node-mysql
45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "mysql"
47 error node v5.5.0
48 error npm  v3.6.0
49 error code ENOSELF
50 error Refusing to install mysql as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by noxidsoft** [comment] 2016-09-29 03:04
Yep, still doing the same with this type of command:
$ npm install susy sass-loader --save-dev

**Comment by martinduo** [comment] 2017-06-05 01:33
Doing the same thing: same error:
npm ERR! Refusing to install npm as a dependency of itself
Using command: npm install npm@latest -g
How to solve?
UPDATE: As suggested in a Google search result, I added the -f flag to the command, and it worked.
