### ISSUE TITLE
cannot install rimraf package.

### ISSUE THREAD

**Issue by blood217** [npm/npm#14121] opened 2016-09-29 09:05 UTC
`sudo npm install -g rimraf`

**Error**
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "rimraf"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
```

[npm-debug.txt](https://github.com/npm/npm/files/500204/npm-debug.txt)

**Comment by KenanY** [comment] 2016-09-29 14:19
Closing as a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-29 14:19 UTC
