### ISSUE TITLE
npm install solc not working

### ISSUE THREAD

**Issue by mkotov13** [npm/npm#10282] opened 2015-11-06 00:46 UTC
here is the npm-debug.log file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'solc' ]
2 info using npm@3.3.6
3 info using node@v4.1.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData solc
8 silly fetchNamedPackageData solc
9 silly mapToRegistry name solc
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/solc
13 verbose request uri https://registry.npmjs.org/solc
14 verbose request no auth needed
15 info attempt registry request try #1 at 7:44:47 PM
16 verbose request id 771bac70f2f64011
17 verbose etag "8RNEF22J87XTX3I0KD5M4O4X3"
18 http request GET https://registry.npmjs.org/solc
19 http 304 https://registry.npmjs.org/solc
20 verbose headers { date: 'Fri, 06 Nov 2015 00:43:17 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"8RNEF22J87XTX3I0KD5M4O4X3"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-iad2142-IAD',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1446770597.515719,VS0,VE19',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Fri, 06 Nov 2015 00:43:17 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"8RNEF22J87XTX3I0KD5M4O4X3"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-iad2142-IAD',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1446770597.515719,VS0,VE19',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/solc from cache
23 verbose get saving solc to /Users/maksimkotov/.npm/registry.npmjs.org/solc/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule solc@0.1.5 checking installable status
37 silly cache add args [ 'solc', null ]
38 verbose cache add spec solc
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'solc',
39 silly cache add   scope: null,
39 silly cache add   name: 'solc',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: '*',
39 silly cache add   type: 'range' }
40 silly addNamed solc@*
41 verbose addNamed "*" is a valid semver range for solc
42 silly addNameRange { name: 'solc', range: '*', hasData: false }
43 silly mapToRegistry name solc
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry uri https://registry.npmjs.org/solc
47 verbose addNameRange registry:https://registry.npmjs.org/solc not in flight; fetching
48 verbose get https://registry.npmjs.org/solc not expired, no request
49 silly addNameRange number 2 { name: 'solc', range: '*', hasData: true }
50 silly addNameRange versions [ 'solc',
50 silly addNameRange   [ '0.1.3',
50 silly addNameRange     '0.1.3-1',
50 silly addNameRange     '0.1.3-2',
50 silly addNameRange     '0.1.4',
50 silly addNameRange     '0.1.4-1',
50 silly addNameRange     '0.1.5',
50 silly addNameRange     '0.1.5-1',
50 silly addNameRange     '0.1.6',
50 silly addNameRange     '0.1.6-1',
50 silly addNameRange     '0.1.6-2' ] ]
51 silly addNamed solc@0.1.6
52 verbose addNamed "0.1.6" is a plain semver version for solc
53 silly cache afterAdd solc@0.1.6
54 verbose afterAdd /Users/maksimkotov/.npm/solc/0.1.6/package/package.json not in flight; writing
55 verbose afterAdd /Users/maksimkotov/.npm/solc/0.1.6/package/package.json written
56 silly rollbackFailedOptional Starting
57 silly rollbackFailedOptional Finishing
58 silly runTopLevelLifecycles Starting
59 silly runTopLevelLifecycles Finishing
60 silly install printInstalled
61 verbose stack Error: Error extracting /Users/maksimkotov/.npm/solc/0.1.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/maksimkotov/.npm/solc/0.1.5/package.tgz'
61 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:276:10)
61 verbose stack     at emitOne (events.js:77:13)
61 verbose stack     at ReadStream.emit (events.js:169:7)
61 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
61 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
61 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
62 verbose cwd /usr/local/bin
63 error Darwin 15.0.0
64 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "solc"
65 error node v4.1.2
66 error npm  v3.3.6
67 error code EREADFILE
68 error Error extracting /Users/maksimkotov/.npm/solc/0.1.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/maksimkotov/.npm/solc/0.1.5/package.tgz'
69 error If you need help, you may report this error at:
69 error     <https://github.com/npm/npm/issues>
70 verbose exit [ 1, true ]
 ```

**Comment by othiym23** [comment] 2015-11-06 19:15
This is a known issue, and is a duplicate of #10057.

**Closed by othiym23** 2015-11-06 19:15 UTC
