### ISSUE TITLE
npm install results in shasum check failed 

### ISSUE THREAD

**Issue by branpar** [npm/npm#14190] opened 2016-10-05 15:58 UTC
#### I'm opening this issue because:
- [ ] npm is crashing.
- [X] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for C:\Users\<user>\AppData\Local\Temp\npm-18644-4ec7aa82\registry.npm
js.org\kss\-\kss-2.4.0.tgz
npm ERR! Expected: 6a2e8bba3b476469fbd3eefb922731bf3f5125cb
npm ERR! Actual:   1ab843dab5610173eae7d5dceb28abda79098dd3
npm ERR! From:     https://registry.npmjs.org/kss/-/kss-2.4.0.tgz
```
#### How can the CLI team reproduce the problem?

I am running an npm install with the kss@2.4.0 package as one of the dependencies. I have cleared my cache multiple times, the npm install used to work earlier today, no further changes have been made to package,json, and now it fails.

### supporting information:
- `npm -v` prints:
  3.10.3
- `node -v` prints:
  v6.6.0
- `npm config get registry` prints:
  https://registry.npmjs.org
- Windows, OS X, or Linux?:
  Windows
- Network issues:
  - Geographic location where npm was run:
    Chicago, IL
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by branpar** [comment] 2016-10-05 16:46
If I change the registry from https://registry.npmjs.org to https://registry.npmjs.com I am able to install. When I run a `tracert` on https://registry.npmjs.org I see I am getting some timeouts for some of the hops

```
C:\>tracert registry.npmjs.org

Tracing route to prod.a.sni.global.fastlylb.net [151.101.44.162]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  10.19.56.2
  2     1 ms     1 ms     1 ms  10.99.100.62
  3     *        *        *     Request timed out.
  4     2 ms     2 ms     2 ms  cr1.cgcil.ip.att.net [12.122.133.198]
  5     2 ms     2 ms     3 ms  ggr4.cgcil.ip.att.net [12.122.133.33]
  6     2 ms     2 ms     2 ms  chi-b21-link.telia.net [213.248.87.253]
  7     *        *        *     Request timed out.
  8    22 ms    22 ms    22 ms  151.101.44.162

Trace complete.
```

Looks like there are some network issues. I can temporarily change my registry URL.

**Comment by zkat** [comment] 2016-12-05 22:44
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-05 22:44 UTC
