### ISSUE TITLE
 Refusing to install gulp as it is a dependency of itself?

### ISSUE THREAD

**Issue by Stanzilla** [npm/npm#9165] opened 2015-08-05 02:03 UTC
Can't really make any sense of this
```
vagrant@homestead:/home/sites/weakauras$ sudo npm update
â-? â¢â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-O â¢â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-? â¢â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-? â¢â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'loadIdealTree â┼' cloneCurr â-? â¢â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-runTopLevelLifecycles     â-O â¢â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-^â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'ânpm ERR! Linux 3.16.0-23-generic
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.1
npm ERR! code ENOSELF

npm ERR! Refusing to install gulp as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.1
npm ERR! path npm-debug.log.5580f25cf26f0a6d5e1dcfd187e4be2f
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.5580f25cf26f0a6d5e1dcfd187e4be2f'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sites/weakauras/npm-debug.log
``` 

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'update' ]
2 info using npm@3.2.1
3 info using node@v0.12.7
4 silly mapToRegistry name gulp
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/gulp
8 silly mapToRegistry name laravel-elixir
9 silly mapToRegistry using default registry
10 silly mapToRegistry registry https://registry.npmjs.org/
11 silly mapToRegistry uri https://registry.npmjs.org/laravel-elixir
12 verbose request uri https://registry.npmjs.org/gulp
13 verbose request no auth needed
14 info attempt registry request try #1 at 2:00:36 AM
15 verbose request id d85e186412d3dc9a
16 http request GET https://registry.npmjs.org/gulp
17 verbose request uri https://registry.npmjs.org/laravel-elixir
18 verbose request no auth needed
19 info attempt registry request try #1 at 2:00:36 AM
20 http request GET https://registry.npmjs.org/laravel-elixir
21 http 200 https://registry.npmjs.org/gulp
22 silly get cb [ 200,
22 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly get     etag: '"DC22RRDUIXBU3V2LXMPUG1IGJ"',
22 silly get     'content-type': 'application/json',
22 silly get     'cache-control': 'max-age=60',
22 silly get     'content-length': '105121',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Wed, 05 Aug 2015 02:01:11 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     age: '52',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lcy1124-LCY',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1438740071.662931,VS0,VE1',
22 silly get     vary: 'Accept' } ]
23 verbose get saving gulp to /home/vagrant/.npm/registry.npmjs.org/gulp/.cache.json
24 http 200 https://registry.npmjs.org/laravel-elixir
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"93SDJ5NKA4ZVUE27RES0683S5"',
25 silly get     'content-type': 'application/json',
25 silly get     'cache-control': 'max-age=60',
25 silly get     'content-length': '239830',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Wed, 05 Aug 2015 02:01:11 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-lcy1120-LCY',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1438740071.666373,VS0,VE165',
25 silly get     vary: 'Accept' } ]
26 verbose get saving laravel-elixir to /home/vagrant/.npm/registry.npmjs.org/laravel-elixir/.cache.json
27 info outdated updating [ { dep:
27 info outdated      { id: 1,
27 info outdated        package: [Object],
27 info outdated        path: '/home/sites/weakauras/node_modules/gulp',
27 info outdated        realpath: '/home/sites/weakauras/node_modules/gulp',
27 info outdated        parent: [Object],
27 info outdated        isLink: false,
27 info outdated        children: [Object],
27 info outdated        error: null,
27 info outdated        loaded: false,
27 info outdated        requiredBy: [Object],
27 info outdated        requires: [Object],
27 info outdated        missingDeps: {},
27 info outdated        missingDevDeps: {},
27 info outdated        userRequired: false,
27 info outdated        existing: false },
27 info outdated     depname: 'gulp',
27 info outdated     current: '3.8.11',
27 info outdated     wanted: '3.9.0',
27 info outdated     latest: '3.9.0',
27 info outdated     req: '^3.8.8',
27 info outdated     what: 'gulp@3.9.0' },
27 info outdated   { dep:
27 info outdated      { id: 3,
27 info outdated        package: [Object],
27 info outdated        path: '/home/sites/weakauras/node_modules/laravel-elixir',
27 info outdated        realpath: '/home/sites/weakauras/node_modules/laravel-elixir',
27 info outdated        parent: [Object],
27 info outdated        isLink: false,
27 info outdated        children: [Object],
27 info outdated        error: null,
27 info outdated        loaded: false,
27 info outdated        requiredBy: [Object],
27 info outdated        requires: [Object],
27 info outdated        missingDeps: [Object],
27 info outdated        missingDevDeps: {},
27 info outdated        userRequired: false,
27 info outdated        existing: false },
27 info outdated     depname: 'laravel-elixir',
27 info outdated     current: '1.0.1',
27 info outdated     wanted: '1.0.3',
27 info outdated     latest: '3.1.1',
27 info outdated     req: '^1.0.0',
27 info outdated     what: 'laravel-elixir@1.0.3' } ]
28 silly loadCurrentTree Starting
29 silly install loadCurrentTree
30 silly install readLocalPackageData
31 silly fetchPackageMetaData gulp@3.9.0
32 silly fetchNamedPackageData gulp
33 silly mapToRegistry name gulp
34 silly mapToRegistry using default registry
35 silly mapToRegistry registry https://registry.npmjs.org/
36 silly mapToRegistry uri https://registry.npmjs.org/gulp
37 verbose get https://registry.npmjs.org/gulp not expired, no request
38 silly install normalizeTree
39 silly loadCurrentTree Finishing
40 silly loadIdealTree Starting
41 silly install loadIdealTree
42 silly cloneCurrentTree Starting
43 silly install cloneCurrentTreeToIdealTree
44 silly cloneCurrentTree Finishing
45 silly loadShrinkwrap Starting
46 silly install loadShrinkwrap
47 silly loadShrinkwrap Finishing
48 silly loadAllDepsIntoIdealTree Starting
49 silly install loadAllDepsIntoIdealTree
50 silly rollbackFailedOptional Starting
51 silly rollbackFailedOptional Finishing
52 silly runTopLevelLifecycles Starting
53 silly runTopLevelLifecycles Finishing
54 silly install printInstalled
55 verbose stack Error: Refusing to install gulp as a dependency of itself
55 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:40:14)
55 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
55 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
55 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
55 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:5
55 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
55 verbose stack     at Array.forEach (native)
55 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
55 verbose stack     at Array.forEach (native)
55 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
56 verbose cwd /home/sites/weakauras
57 error Linux 3.16.0-23-generic
58 error argv "node" "/usr/local/bin/npm" "update"
59 error node v0.12.7
60 error npm  v3.2.1
61 error code ENOSELF
62 error Refusing to install gulp as a dependency of itself
63 error If you need help, you may report this error at:
63 error     <https://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]
```

My package.json is just
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "^1.0.0"
  }
}
```

**Comment by iamstarkov** [comment] 2015-08-05 12:08
why do you need gulp as a dep to gulp?

**Comment by Stanzilla** [comment] 2015-08-05 16:19
I don't actually but I don't see where I set it that way either?

**Comment by iamstarkov** [comment] 2015-08-05 16:35
circular deps are tricky, arent they?

**Comment by robertbaker** [comment] 2015-08-07 17:50
This is a valid issue it happens on several packages, on NPM 3.2.0+

**Comment by iamstarkov** [comment] 2015-08-07 17:54
why do you, people, need circular deps?

**Comment by robertbaker** [comment] 2015-08-07 21:49
@iamstarkov This wasn't happening on 3.1.x. Gulp doesn't depend on itself. Neither does cordova-android, eslint, etc that npm is now claiming it has a dependency on itself.

Your input isn't constructive...this isn't an actual circular dependency, it's a bug in npm 3.2.

Care to actually explain why you think this is a circular dependency?

**Comment by iamstarkov** [comment] 2015-08-07 22:00
sorry, i have been confused by original tittle. now i get it, thank you

**Comment by Stanzilla** [comment] 2015-08-08 00:57
Changed the title to be a little easier to understand :)

**Comment by Stanzilla** [comment] 2015-08-09 13:24
Still happening in 3.2.2

**Comment by iarna** [comment] 2015-08-11 19:49
I'm closing this as a duplicate of #9095

**Closed by iarna** 2015-08-11 19:49 UTC
Labels: bug
