### ISSUE TITLE
errors on cloud 9 sdk 

### ISSUE THREAD

**Issue by abubakaralsadiq** [npm/npm#15868] opened 2017-02-25 19:05 UTC
#### I'm opening this issue because:
i am really have problem with runing npm test
  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
after installing cloud 9 sdk i now run the npm test it return this 👍 
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ctest"

npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: ctest
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin\home\user\c9sdk\Usersuserabubakar\web developerbootCamp\IntorToNode\npm-debug.log

#### How can the CLI team reproduce the problem?
i really need some help

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2017-02-25 19:07
@abubakaralsadiq Looks like you're trying to do `npm run ctest`, but you don't have a script named `"ctest"` in your `package.json`. Please see <https://docs.npmjs.com/misc/scripts> for information on how to write scripts. I'm gonna close this since this is `npm` working as intended.

**Closed by KenanY** 2017-02-25 19:07 UTC

**Comment by abubakaralsadiq** [comment] 2017-03-04 08:44
hlo,there wil you pls help i was trying to run express on c9sdk but i used
localhost 3000 ,to run the server but it return an error what should i do .
help pls i really need it to work.

**Comment by KenanY** [comment] 2017-03-06 16:16
@abubakaralsadiq No idea :(
