### ISSUE TITLE
`npm shrinkwrap` detects devDependencies' peerDependencies as dependencies

### ISSUE THREAD

**Issue by sanemat** [npm/npm#8238] opened 2015-05-12 13:59 UTC
* my app uses webpack as devDependencies
* webpack added node-libs-browser as peerDependencies
* `npm shrinkwrap` in my app detects node-libs-browser as dependencies

Is this expected behavior?

This is changed npm-shrinkwrap.json:
https://github.com/lyrictenor/nwjs-close-your-issues/pull/123/files#diff-36018a6a9e1de1798516799b84841318R178

npm v2.7.4 and v2.9.1 and v2.10.0 have same behavior.
node version v0.12.2

**Comment by othiym23** [comment] 2015-08-31 22:25
This may be addressed in `npm@3`, so I'm going to have @iarna take a look at this when she's not in the middle of moving across the country to say for sure.

**Comment by othiym23** [comment] 2015-10-28 21:59
This is a bug, but it's one that's no longer relevant in `npm@3`, because of the changes to how `peerDependencies` work in `npm@3`. Since you have to explicitly add those `peerDependencies` to `devDependencies` in `npm@3` to deal with the changed behavior, and since this isn't a new regression within `npm@2`, I suggest you switch to using (and running shrinkwrap from) `npm@3`, and the team isn't going to fix this within the `npm@2` release series. Thanks for bringing the issue to our attention!

**Closed by othiym23** 2015-10-28 21:59 UTC
Labels: bug, peerdependencies
