### ISSUE TITLE
Argument #1: Expected object but got string (npm 3.1.1)

### ISSUE THREAD

**Issue by substack** [npm/npm#8913] opened 2015-07-12 04:12 UTC
From a [hyperlog-index](https://github.com/substack/hyperlog-index) project directory I run:

```
$ npm install fwdb
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/substack/prefix/bin/node-iojs" "/home/substack/prefix/bin/npm" "install" "fwdb"
npm ERR! node v2.0.0
npm ERR! npm  v3.1.1
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected object but got string
npm ERR! typeerror     at resolveWithNewModule (/home/substack/projects/npm/lib/install/deps.js:375:3)
npm ERR! typeerror     at /home/substack/projects/npm/lib/install/deps.js:163:5
npm ERR! typeerror     at /home/substack/projects/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /home/substack/projects/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/home/substack/projects/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/home/substack/projects/npm/lib/install/deps.js:158:3)
npm ERR! typeerror     at Array.<anonymous> (/home/substack/projects/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/home/substack/projects/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/substack/projects/hyperlog-index/npm-debug.log
```

and the npm-debug.log is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/substack/prefix/bin/node-iojs',
1 verbose cli   '/home/substack/prefix/bin/npm',
1 verbose cli   'install',
1 verbose cli   'fwdb' ]
2 info using npm@3.1.1
3 info using node@v2.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 verbose stack Error: Argument #1: Expected object but got string
19 verbose stack     at resolveWithNewModule (/home/substack/projects/npm/lib/install/deps.js:375:3)
19 verbose stack     at /home/substack/projects/npm/lib/install/deps.js:163:5
19 verbose stack     at /home/substack/projects/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (native)
19 verbose stack     at /home/substack/projects/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (native)
19 verbose stack     at asyncMap (/home/substack/projects/npm/node_modules/slide/lib/async-map.js:51:8)
19 verbose stack     at exports.loadRequestedDeps (/home/substack/projects/npm/lib/install/deps.js:158:3)
19 verbose stack     at Array.<anonymous> (/home/substack/projects/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/home/substack/projects/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose cwd /home/substack/projects/hyperlog-index
21 error Linux 3.16.0-4-amd64
22 error argv "/home/substack/prefix/bin/node-iojs" "/home/substack/prefix/bin/npm" "install" "fwdb"
23 error node v2.0.0
24 error npm  v3.1.1
25 error code EINVALIDTYPE
26 error typeerror Error: Argument #1: Expected object but got string
26 error typeerror     at resolveWithNewModule (/home/substack/projects/npm/lib/install/deps.js:375:3)
26 error typeerror     at /home/substack/projects/npm/lib/install/deps.js:163:5
26 error typeerror     at /home/substack/projects/npm/node_modules/slide/lib/async-map.js:52:35
26 error typeerror     at Array.forEach (native)
26 error typeerror     at /home/substack/projects/npm/node_modules/slide/lib/async-map.js:52:11
26 error typeerror     at Array.forEach (native)
26 error typeerror     at asyncMap (/home/substack/projects/npm/node_modules/slide/lib/async-map.js:51:8)
26 error typeerror     at exports.loadRequestedDeps (/home/substack/projects/npm/lib/install/deps.js:158:3)
26 error typeerror     at Array.<anonymous> (/home/substack/projects/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/home/substack/projects/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror This is an error with npm itself. Please report this error at:
26 error typeerror     <http://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]
```

It seems that the `Installer` constructor in lib/install.js is getting an array of string arguments but `resolveWithNewModule()` in `lib/install/deps.js` expects each argument to be an object with `name` and `_requested` properties, not a string.

**Comment by KenanY** [comment] 2015-07-12 04:19
Looks like a dupe of https://github.com/npm/npm/issues/8904.

**Comment by williamboman** [comment] 2015-07-12 11:00
dupe of #8893

**Comment by iarna** [comment] 2015-07-13 16:52
Closing as duplicate.

**Closed by iarna** 2015-07-13 16:52 UTC
Labels: bug
