### ISSUE TITLE
Reduce NPM run's error output

### ISSUE THREAD

**Issue by gauntface** [npm/npm#13234] opened 2016-06-30 15:33 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's the feature?

When you run an npm script, if the task returns an error code, npm will output something along the lines of:

```
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! project-github-pages@0.0.1 serve: `jekyll serve --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project-github-pages@0.0.1 serve script 'jekyll serve --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the project-github-pages package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jekyll serve --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs project-github-pages
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls project-github-pages
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matt/Projects/Code/project-github-pages/npm-debug.log

```

This wall of text prevents the author from showing a meaningful message since the only thing the user sees for an avg. terminal height if  'npm ERR!' and because it looks like a wall of the text, the well intended messages are obvious or easy to find and read.

Just reduce the above to one or two lines of very simple tests:

```

Error runnin "npm run serve". Tell the author that this fails on your system:
     jekyll serve --watch
```

#### What problem is the feature intended to solve?

Make it possible for authors of npm scripts to show meaningful errors and help users identify problems easier.

#### Is the absence of this feature blocking you or your team? If so, how?

Nope. Just caused a lot of painful debugging with users because NPM makes it less obvious where the  useful error logs are.

#### Is this feature similar to an existing feature in another tool?

I don't know of any other tool that does what NPM does

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Depending on licensing - totally. :)

-->

**Comment by KenanY** [comment] 2016-06-30 15:38
Probably a duplicate of https://github.com/npm/npm/issues/8821. https://github.com/npm/npm/issues/5452 could be a solution to this.

**Comment by KenanY** [comment] 2016-07-07 16:35
Gonna close as a duplicate. Can reopen if this is not the case.

**Closed by KenanY** 2016-07-07 16:35 UTC
Labels: feature-request
