### ISSUE TITLE
error in installing go-debug package in atom on windows 10

### ISSUE THREAD

**Issue by vinod4006** [npm/npm#12801] opened 2016-05-23 08:51 UTC
```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\vinods\\AppData\\Local\\atom\\app-1.7.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\vinods\\AppData\\Local\\atom\\app-1.7.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\vinods\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\vinods\\.atom\\.apmrc" "install" "C:\\Users\\vinods\\AppData\\Local\\Temp\\d-116423-8972-2l1nq3\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\vinods\AppData\Local\Temp\apm-install-dir-116423-8972-1a7y4s7\node_modules\go-debug\package.json.72e327d18900710d56634619ed39ac6c
npm ERR! code EBUSY
npm ERR! errno 10

npm ERR! EBUSY, rename 'C:\Users\vinods\AppData\Local\Temp\apm-install-dir-116423-8972-1a7y4s7\node_modules\go-debug\package.json.72e327d18900710d56634619ed39ac6c'
```

**Comment by othiym23** [comment] 2016-08-19 22:01
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 22:01 UTC
Labels: support, windows
