### ISSUE TITLE
Separate devDependecies from dependencies

### ISSUE THREAD

**Issue by calidion** [npm/npm#11906] opened 2016-03-15 06:42 UTC
the mixture of dev and prod node_modules always cause module missing problem.
it would be better to separate them.

**Comment by KenanY** [comment] 2016-03-15 14:37
@calidion You mean, into different directories?

**Comment by calidion** [comment] 2016-03-15 15:00
yes.

a possible structure.
totally separate test modules from package modules.

  ├── packagename
  │   ├── package.json
  │   ├── node_modules   #only store packages by dependencies
  │   ├── test
  │   │   └── node_modules    #only store packages by devDependencies
  │   │       ├── test.js

**Comment by zkat** [comment] 2016-03-15 23:38
You should not be running into missing modules if you've declared your dependencies correctly. If you want to prevent devDependencies from being installed, though, and you wanna make sure that works, you can do `npm install --only=prod` to install only production modules.

If you want a way to have devDeps but also run your test suite, that's a bit more involved and then it's a duplicate of #11899 (with the corresponding resolution).

In general, changing the way dependencies/devDependencies/optionalDependencies/etc work is very tricky to manage for us, because of the enormous consequences of even a small change to that structure.

I hope the above suggestions help with this particular issue -- I'm closing this for the time being, but feel free to respond further if I didn't really catch what you were intending to say, and thank you for taking the time for filing this with us <3

**Closed by zkat** 2016-03-15 23:38 UTC
Labels: feature-request

**Comment by calidion** [comment] 2016-03-16 06:30
they are different things.
I need test enabled while I am verifying the integrity of a package.
<code>npm install --only=prod</code>
it a way to install prod packages only.
But i also need test repeatedly when errors found.

my suggested solution is very easy to adopt.

the only thing need to be done is to install dependencies and devDependencies into different folder.
and i find nothing tricky.
the only thing need to be done is  to let the test program uses package folder in the current directory instead of the upper directory.

And the really tricky thing is that package modules and test modules are sharing the same folder.
which causes numerous problems and leads to time wasting.

**Comment by calidion** [comment] 2016-04-21 02:57
please reopen this. Currently npm packages can not be fully tested due to the mixture of the package path. where devDependencies are not installed with npm install --save package. but will be install with npm install.
With test alone the package sanity cannot be verified!

**Comment by othiym23** [comment] 2016-04-21 03:19
@calidion What you request isn't possible with the design of the [Node module loader](https://nodejs.org/api/modules.html#modules_all_together) as it currently stands. Even were npm to install dependencies and `devDependencies` into separate folders, Node wouldn't know how to load both of them without modification. As this is a locked API within Node, this isn't something I anticipate will ever change.

**Comment by calidion** [comment] 2016-04-21 03:35
@othiym23 I don't think so.

At least, you can provide a way to avoid devDependencies to be installed.

1. <code>npm install</code> will not install devDependencies
2. <code>npm install --dev </code> will install devDependencies

it is a very simple solution. but every useful.

**Comment by calidion** [comment] 2016-04-22 02:47
@othiym23

currently, I can not avoid npm package missing.
use 
npm install 
or
npm install --only=prod

It is useless to install prod dependencies, while it can't be tested.
I just published a package with wrong dependencies but it passed all my tests.

Online CI is very expensive for me, it takes too much time.
I think a need a simple way to verify my package and make sure its integrity.

**Comment by binki** [comment] 2016-11-25 02:46
@calidion you need to write a script that installs your folder to a separate directory (not beneath your repo root). Then your test scripts just require that alternate directory instead of the current one. As long as your module is installed to a directory tree that doesn’t have your `devDependencies` in a `node_modules` folder in any of its parents or globally available, it will fail to resolve dependencies then. This should cause you to notice missing dependencies.
