### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kapolos** [npm/npm#10536] opened 2015-11-23 22:56 UTC
`npm install -g babel-core`

Only happens if installing globally. User `root`.
````
# uname -a
Linux 92614f191454 4.1.6-250 #1 SMP Mon Aug 31 14:48:51 UTC 2015 armv7l armv7l armv7l GNU/Linux
````

````
2009 silly doParallel preinstall 1
2010 silly preinstall babel-core@6.2.1 /usr/local/lib/node_modules/.staging/babel-core-4c05bc0b67a0e09e175351509acf3d66
2011 info lifecycle babel-core@6.2.1~preinstall: babel-core@6.2.1
2012 silly lifecycle babel-core@6.2.1~preinstall: no script for preinstall, continuing
2013 silly doReverseSerial remove 0
2014 silly doSerial move 0
2015 silly doSerial finalize 1
2016 silly finalize /usr/local/lib/node_modules/babel-core
2017 verbose stack RangeError: Maximum call stack size exceeded
2017 verbose stack     at Array.filter (native)
2017 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:55:37
2017 verbose stack     at Array.forEach (native)
2017 verbose stack     at markAsFailed (/usr/local/lib/node_modules/npm/lib/install/actions.js:54:16)
2017 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:57:7
2017 verbose stack     at Array.forEach (native)
2017 verbose stack     at markAsFailed (/usr/local/lib/node_modules/npm/lib/install/actions.js:54:16)
2017 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/actions.js:57:7
2017 verbose stack     at Array.forEach (native)
2017 verbose stack     at markAsFailed (/usr/local/lib/node_modules/npm/lib/install/actions.js:54:16)
2018 verbose cwd /webroot/webapp/back
2019 error Linux 4.1.6-250
2020 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "babel-core"
2021 error node v5.1.0
2022 error npm  v3.3.12
2023 error Maximum call stack size exceeded
2024 error If you need help, you may report this error at:
2024 error     <https://github.com/npm/npm/issues>
2025 verbose exit [ 1, true ]
````

Full log: http://pastebin.com/Y0bYihcc

**Comment by fastest963** [comment] 2015-12-03 19:34
Related to #9224, #9953, #10430, #10228

**Comment by datpham23** [comment] 2016-03-02 23:39
also happening to me on:
mac: 10.11.3
node v5.3.0
npm  v3.3.12

**Comment by iarna** [comment] 2016-08-15 21:27
Closing as duplicate of #11702.

**Closed by iarna** 2016-08-15 21:27 UTC
Labels: big-bug, bug
