### ISSUE TITLE
npm should not modify .gitignore files

### ISSUE THREAD

**Issue by chrishyle** [npm/npm#11061] opened 2016-01-07 08:42 UTC
I recently found that an `npm install` renames `.gitignore` files to `.npmignore`. This is very surprising behavior and broke a yeoman generator of mine when it was included as a dependency in another project because the `.gitignore` template file was suddenly missing. (My workaround has been to rename the template file to something else, but now it's the only template in my generator whose source does not match its output.)

I assume that there is probably a good reasons for doing it, but it seems like a violation of npm's scope to modify the internals of the package in this way, and obviously there are some edge cases like mine where it is not just modifying some unnecessary git internals, but breaking functionality. The safest resolution would be for npm NOT to rename `.gitignore` files, and to instead find a cleaner way to solve whatever the original reason is for doing this.

**Comment by chrishyle** [comment] 2016-01-07 08:45
Offending code: https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/utils/tar.js#L326

**Comment by iarna** [comment] 2016-01-08 02:09
Thanks for bringing this up! I agree that it is unexpected, but this was introduced a very long time ago (2212118) in response to #1862, which goes into some detail as to why this was added and what problems it solves. If you can provide an alternative solution that still solves those problems without introducing backwards compatibility concerns, we would probably take it, but we aren't going to have any time to do anything beyond vetting a design and code-reviewing PRs, as [our plates are full](https://github.com/npm/npm/wiki/Roadmap#areas-of-focus) for the foreseeable future.

I'm going to close this issue, but if finding a better solution interests you, I encourage you to open a new one with a proposed solution.

**Closed by iarna** 2016-01-08 02:09 UTC
Labels: feature-request

**Comment by yaycmyk** [comment] 2016-03-03 19:51
You're breaking the referential integrity of the repository by rewriting a file within it. This is really bad behavior.

**Comment by othiym23** [comment] 2016-03-03 20:01
@yaycmyk The file doesn't get renamed or committed to the Git repository. The change is made only to the file included in the tarball published to the registry, and is done on the fly as the tarball of the package to be published is created. No changes are made to the referential integry of the repository, which isn't even possible for the CLI, as it does all of its Git operations via calls to the Git CLI.

**Comment by julmot** [comment] 2016-03-24 12:35
I am having the same troubles with a yeoman [generator](https://www.npmjs.com/package/generator-wabp) (v3.0.0). In my case the problem is that npm renames __all__ `.gitignore` files to `.npmignore` (including subdirectories). I wouldn't have a problem if npm would just rename the root `.gitignore` (even though I find it incredibly unprofessional), but renaming all those files regardless in which directories they are seems to be unnecessary.

@iarna For my case the solution would be to only rename the root `.gitignore` and nothing inside any subdirectory.
