### ISSUE TITLE
install protractor-html-screenshot-reporter fails

### ISSUE THREAD

**Issue by lfrohman** [npm/npm#12214] opened 2016-04-05 18:42 UTC
I ran:

npm install protractor-html-screenshot-reporter --save-dev

and got the error below

I have run
npm cache clear
(several times)

thanks,
Lance

```
npm WARN package.json xxxxxx@3.0.0 No repository field.
npm http GET https://registry.npmjs.org/protractor-html-screenshot-reporter
npm http 200 https://registry.npmjs.org/protractor-html-screenshot-reporter
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
npm ERR! (binary garbage here)

npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:238:23)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protractor-html-screenshot-reporter"
npm ERR! cwd C:\workspace\genehub-js
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     C:\workspace\genehub-js\npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment] 2016-04-05 19:07
Closing as duplicate of #12196. See that for resolution, and to contribute if you're unable to upgrade npm or get the problem fixed by clearing your cache (again).

**Closed by othiym23** 2016-04-05 19:07 UTC
