### ISSUE TITLE
Validate CLI parameters

### ISSUE THREAD

**Issue by dandv** [npm/npm#6812] opened 2014-11-29 04:41 UTC
`npm install --savedev grunt-shell`

Then I pull my hair off for a while until I realize it's `save` DASH `dev`.

**Comment by Delapouite** [comment] 2015-11-04 13:51
This issue will be resolved there : https://github.com/npm/npm/issues/10047

**Comment by othiym23** [comment] 2016-10-04 20:59
Closing as duplicate of #10047; as that issue indicates, this is something we'd like to fix, but the CLI team isn't going to have time to address soon. Patches welcome! Thanks for your time!

**Closed by othiym23** 2016-10-04 20:59 UTC
Labels: feature-request
