### ISSUE TITLE
bin shorthand creates slightly odd links for scoped packages

### ISSUE THREAD

**Issue by quarterto** [npm/npm#10085] opened 2015-10-22 21:21 UTC
A package `foo` in the `bar` scope with `"bin": "bin.js"` in package.json will create (e.g.) `/usr/local/bin/@bar/foo` when installed/linked, which seems a bit odd. I don't know how well folders in `bin` are supported, but I (*think* I) would expect this to create `/usr/local/bin/foo`.

**Comment by othiym23** [comment] 2015-10-22 22:27
This is definitely a bug, and in fact this a duplicate of #8640, so I'm going to close this in favor of that one. The binary should go in `/usr/local/bin`, and shouldn't be creating any subdirectories. This hasn't gotten fixed yet because nobody's had the time, so if you wanted to take a stab at fixing this (or maybe work with @toddself fix it), it would be most appreciated. Thanks for filing the issue!

**Closed by othiym23** 2015-10-22 22:27 UTC
Labels: bug

**Comment by quarterto** [comment] 2015-10-23 10:04
Ah, thanks @othiym23. That didn't come up on my (admittedly cursory) search.
