### ISSUE TITLE
cannot read property 'path' of null

### ISSUE THREAD

**Issue by Sunnyherb** [npm/npm#15924] opened 2017-03-02 14:47 UTC
## when i install node-sass using npm but it always make mistake.Here are the errors below,what's the property 'path' of null?

C:\Users\manning-jr>npm install -g node-sass
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Dev\\Installations\\Nodejs\\node.exe" "D:\\Dev\\Installations\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-sass"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2

## npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\manning-jr\npm-debug.log

**Comment by legodude17** [comment] 2017-03-02 17:35
Duplicate of #10686.

**Closed** 2017-06-17 04:00 UTC
Labels: bot-closed
