### ISSUE TITLE
`npm install -g bower` goes into infinite loop on windows with %appdata% being a UNC path

### ISSUE THREAD

**Issue by korroz** [npm/npm#8814] opened 2015-07-03 14:39 UTC
We seem to have a strange edge case in our environment where npm goes into an infinite loop/stalls when trying to globally install some packages. Eventually the process runs out of memory and exits with `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`.

With packages like _gulp_ we have no issues but with _bower_ it reliably fails. Following is more info about the environment.

```
$ npm -v
2.11.1

$ node -v
v0.12.4

$ echo $APPDATA
\\Server\Home-Folders\MyUser\Application Data
```

The reason the UNC path seems suspicious is that I tried the following tests:
1. Setting `cache` to a local path (i.e. `C:\Temp\npm-cache`). Still **failed**.
2. Setting `prefix` to a local path (i.e. `C:\Temp\Server\Home-Folders\MyUser\Application Data`). **Success**.

I used a similarly long path for `prefix` to rule out any _long path_ issues, although it doesn't rule it out completely.

Searching around for others with similar issues didn't turn up much, which makes me believe it's a pretty rare edge case. The only hit was [this post on SO](http://stackoverflow.com/questions/25514839/node-npm-install-g-bower-fatal-error-call-and-retry-2-on-win7).

I've seen some discussions going on in this area of npm, like in #4564. While pointing `prefix` to a safer location like `%LOCALAPPDATA%` would fix this issue, it would fix it by sidestepping it.

In any case, I suppose the 4 actions that could be taken on this issue are:
- Consider the issue sidestepped in the future and close it.
- Consider the issue rare and fixable by non-default npm configuration and close it.
- Decide that UNC paths aren't supported and implement warnings for it in npm.
- Investigate deeper and find out why exactly npm goes into an infinite loop and fix that.

I'm wondering though if this issue might not be an edge case, just that npm hasn't spread into corporate windows environments enough to be discovered?
The practice to map `%APPDATA%` to a UNC path might be uncommon even within corporate evironments?

I am not sure, does have any insights on this?

**Comment by syedihuda** [comment] 2015-07-22 22:31
Hi korroz, I'm having the exact same issue since I joined a new company recently.
I'm on windows, in a corporate environment with %APPDATA% pointing to a UNC path.

I definitely need to get this working ASAP.  Do you recommend just sidestepping the issue by using %LOCALAPPDATA%?  Do you have any updates?

**Comment by syedihuda** [comment] 2015-07-22 23:50
UPDATE:
I was able to make the changes necessary to npm configurations to install bower globally.
To confirm, you need to set both cache AND prefix to %LOCALAPPDATA% (since a UNC path %APPDATA% doesn't work)

But now I'm running into another issue, I put %LOCALAPPDATA%\npm\node_modules\bower\bin as part of my path.  But bower is still not recognized command.

**Comment by syedihuda** [comment] 2015-07-23 13:09
UPDATE 2:
I fixed the bower command not found problem by following steps in this post:
http://stackoverflow.com/questions/21732447/bower-command-not-found-windows

**Comment by korroz** [comment] 2015-07-24 10:07
@syedihuda Yes, sidestepping it with user configuration (.npmrc) and editing your path accordingly is what we are doing at the moment. Looks like you got around it already.

**Comment by clshortfuse** [comment] 2015-07-29 13:14
Can confirm this happened to me and fixed it by changing prefix and cache to local folders (maybe both were required, but I did both at the same time).

**Comment by korroz** [comment] 2015-08-04 06:56
The cache works fine on the UNC path (at least for me) but moving it to local is probably a good idea anyway.

**Comment by yamlfd** [comment] 2015-09-14 12:44
%LOCALAPPDATA% is no solution as this folders are excluded from roaming and will be deleted everytime a user logoff from this computer. I guess my case https://github.com/npm/npm/issues/9581 is a duplicate of this here.

**Closed** 2017-06-19 10:44 UTC
Labels: bot-closed, bug, windows
