### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JESii** [npm/npm#12047] opened 2016-03-24 16:01 UTC
Here's a failure; adding npm-debug.log. No package.json as I just want to install Appium. here's the command line output.
```
yc98js1@a4660809:[dev->]~/dev$ npm install wd
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "install" "wd"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yc98js1/dev/npm-debug.log
```
[npm-debug.log.txt](https://github.com/npm/npm/files/188167/npm-debug.log.txt)

**Comment by zkat** [comment] 2016-03-24 18:12
Closing as a duplicate of #9224, which we're using to track call stack problems.

**Closed by zkat** 2016-03-24 18:12 UTC
Labels: bug
