### ISSUE TITLE
npmjs.com should show that a package is deprecated.

### ISSUE THREAD

**Issue by mbostock** [npm/npm#10304] opened 2015-11-07 17:10 UTC
When you `npm deprecate` a package, neither the deprecation nor its associated message are displayed on npmjs.com. Deprecating a package would be more effective if that deprecation were made more apparent on npmjs.com.

For example, yesterday I deprecated [d3-xhr](https://www.npmjs.com/package/d3-xhr) because I renamed it to [d3-request](https://www.npmjs.com/package/d3-request). (Related request: it would be nice to rename a package without using `npm deprecate`.) Yet there’s no evidence of this deprecation when you visit the d3-xhr package on npmjs.com. Nor is there any indication of deprecated packages in the search results:

[![screen shot 2015-11-07 at 9 07 54 am](https://cloud.githubusercontent.com/assets/230541/11016218/11f56b06-852f-11e5-8a7c-a655966fdefc.png)](https://www.npmjs.com/browse/keyword/XMLHttpRequest)

I could publish a new version of d3-xhr that replaces the README and package.json description with a deprecation warning. (And I probably will…) But wouldn’t it be better if `npm deprecate` took care of that automatically?

**Comment by KenanY** [comment] 2015-11-07 17:20
Seems like a duplicate of https://github.com/npm/newww/issues/413.

**Comment by othiym23** [comment] 2015-11-07 19:53
This is indeed an issue for the web team rather than the CLI team. Thanks for pointing that out, @KenanY! Closing! (And yes, I agree, @mbostock, the web site should do something when a package is deprecated.)

**Closed by othiym23** 2015-11-07 19:53 UTC
