### ISSUE TITLE
npm install in laravel-homestead

### ISSUE THREAD

**Issue by lhbfilwmyseve** [npm/npm#15264] opened 2016-12-20 10:00 UTC
Hi there,
i am following this <https://laravel.com/docs/5.3/elixir> docs to  run  command on vagrant  homestead box . when it's done.there are problems.
like this:
vagrant@homestead:~/Code/dataIndex$ npm install --no-bin-links
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@                                                                                                                                         ^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.c                                                                                                                                         om/chalk/supports-color
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/dataIndex/npm-debug.log

now,i have no idea how to work out with it.the next step can't run. so ,i come here and i need help

**Comment by legodude17** [comment] 2016-12-20 21:11
Duplicate of #14608.

**Closed** 2016-12-22 06:12 UTC
