### ISSUE TITLE
“npm faq” fails on Windows 7 (“spawn ENOENT” errors)

### ISSUE THREAD

**Issue by xDEADC0DE** [npm/npm#4714] opened 2014-02-18 14:19 UTC
I have installed node using the latest installer. When I try "npm faq" though, I get :

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'faq' ]
2 info using npm@1.3.24
3 info using node@v0.10.25
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: spawn ENOENT
5 error     at errnoException (child_process.js:988:11)
5 error     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/isaacs/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "faq"
9 error cwd E:\
10 error node -v v0.10.25
11 error npm -v 1.3.24
12 error syscall spawn
13 error code ENOENT
14 error errno ENOENT
15 verbose exit [ 1, true ]
```

**Comment by smikes** [comment] 2015-01-31 15:08
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since Feb 2014. Can you try updating your npm installation?  One improvement is that we log what command was being run when a `spawn` fails.

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-02-01 05:29
I believe this is still an issue on Windows, albeit in a different way. I don't get the error the OP was seeing, but I can't get it to display help, either -- I always get back a list of search results.

**Comment by smikes** [comment] 2015-02-09 03:49
I can't reproduce this on Windows 7 right now with `npm@2.5.0`; when I run `npm faq` , the correct page opens in the browser.  I did not try `npm help`, but surely that should be its own case?

**Comment by othiym23** [comment] 2015-02-09 23:26
[Nope!](https://github.com/npm/npm/blob/master/lib/faq.js#L8)

**Closed** 2017-06-19 11:18 UTC
Labels: bot-closed, bug, documentation, windows
