### ISSUE TITLE
npm ERR!  This is an error with npm itself. (I cannot install packages)

### ISSUE THREAD

**Issue by Darkwynd** [npm/npm#16955] opened 2017-06-03 22:57 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i', '-g', 'npm' ]
2 info using npm@5.0.0
3 info using node@v4.2.4
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 error cb() never called!
7 error This is an error with npm itself. Please report this error at:
8 error <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: ?
 - `node -v` prints: ?
 - `npm config get registry` prints: ?
 - Windows, OS X/macOS, or Linux?: Linux (Raspbian Lite)
 - Network issues:
   - Geographic location where npm was run: Home Network
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by RillingDev** [comment] 2017-06-04 10:15
Duplicate of #16904

**Comment by zkat** [comment] 2017-06-05 16:29
Closing as duplicate of https://github.com/npm/npm/issues/16904 👍

**Closed as completed by zkat** 2017-06-05 16:29 UTC
Labels: npm5
