### ISSUE TITLE
npm hangs out while  install/update

### ISSUE THREAD

**Issue by sbsaqi** [npm/npm#16567] opened 2017-05-08 16:58 UTC
C:\Users\Bruger\Documents\STUDIES n Education\The Full Stack web developer (course)\Section 8 Backend Programming with Node.js\Development\3- Express Install n Routing\myexpress>npm install
npm info it worked if it ends with ok
npm info using npm@4.5.0
npm info using node@v6.10.3
npm info attempt registry request try #1 at 6:53:22 PM
npm http request GET https://registry.npmjs.org/express
npm info attempt registry request try #1 at 6:53:22 PM
npm http request GET https://registry.npmjs.org/body-parser
npm ERR! 9 == 0
npm ERR! 9 == 0

Node.js is not working infact it hangsout ... when install/update 

{
  "name": "myexpress",
  "version": "1.0.0",
  "description": "Simple express application",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express":"*",
    "body-parser":"*"
  }
}

**Comment by KenanY** [comment] 2017-05-08 18:02
Is this mostly a duplicate of your previous issue (https://github.com/npm/npm/issues/16557)?

**Comment by sbsaqi** [comment] 2017-05-08 21:10
yes ... it is ..  and i m stuck here

**Comment by KenanY** [comment] 2017-05-08 21:10
Closing as a duplicate then.

**Closed by KenanY** 2017-05-08 21:10 UTC
Labels: support
