### ISSUE TITLE
i'm try to run "  sudo npm install -g react-native-cli  "

### ISSUE THREAD

**Issue by zentechtypham** [npm/npm#14093] opened 2016-09-27 10:32 UTC
npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/imac1/.nvm/versions/v6.6.0/bin/node" "/Users/imac1/.nvm/versions/v6.6.0/bin/npm" "install" "-g" "react-native-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/imac1/.nvm/versions/v6.6.0/bin/node" "/Users/imac1/.nvm/versions/v6.6.0/bin/npm" "install" "-g" "react-native-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/imac1/.nvm/versions/v6.6.0/bin/node" "/Users/imac1/.nvm/versions/v6.6.0/bin/npm" "install" "-g" "react-native-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/imac1/.nvm/versions/v6.6.0/bin/node" "/Users/imac1/.nvm/versions/v6.6.0/bin/npm" "install" "-g" "react-native-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/imac1/.nvm/versions/v6.6.0/bin/node" "/Users/imac1/.nvm/versions/v6.6.0/bin/npm" "install" "-g" "react-native-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

**Comment by KenanY** [comment] 2016-09-27 13:05
Duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-27 13:05 UTC
