### ISSUE TITLE
No compatible version found

### ISSUE THREAD

**Issue by zakirsajib** [npm/npm#11824] opened 2016-03-09 07:01 UTC
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.8.0

npm ERR! No compatible version found: espree@^3.1.1
npm ERR! Valid install targets:
npm ERR! 3.0.2, 3.0.1, 3.0.0, 3.0.0-alpha-3, 3.0.0-alpha-2, 3.0.0-alpha-1, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.0, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.12.3, 1.12.2, 1.12.1, 1.12.0, 1.11.0, 1.10.0, 1.9.1, 1.9.0, 1.8.1, 1.8.0, 1.7.1, 1.7.0, 1.6.0, 1.5.0, 1.4.0, 1.3.1, 1.3.0, 1.2.2

[npm-debug.log.zip](https://github.com/npm/npm/files/164643/npm-debug.log.zip)

**Comment by KenanY** [comment] 2016-03-09 15:33
I cannot reproduce this. I see that `espree@3.1.1` is indeed available:

``` sh
$ npm info espree versions | grep '3.1.1'
  '3.1.1' ]
```

**Comment by zakirsajib** [comment] 2016-03-09 17:12
Let me explain what really happened, **npm install** command was actually worked before I did following:

I installed **vagrant** and **homebrew**. And then today when I run `npm install` l and it generated those errors.

But if I run following command it works.

`npm run build:all `
or
`npm run build:css`

**Comment by zakirsajib** [comment] 2016-03-09 17:14
I tried to install my package.json file using npm command. May be something wrong there!

Here is my package.json


[package.json.zip](https://github.com/npm/npm/files/165675/package.json.zip)

**Comment by zakirsajib** [comment] 2016-03-09 17:34
I tried to run `npm install` and it works!

Weird!

**Comment by busches** [comment] 2016-09-20 18:40
@KenanY looks like his comment said he got it working and this can be closed

**Comment by KenanY** [comment] 2016-09-20 18:45
@busches Yup, don't know why I didn't close this sooner.

**Closed by KenanY** 2016-09-20 18:45 UTC
