### ISSUE TITLE
npm is renaming .gitignore to .npmignore

### ISSUE THREAD

**Issue by simonewebdesign** [npm/npm#14216] opened 2016-10-08 16:50 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm for some reason renames `.gitignore` to `.npmignore`. I think it might happen [here](https://github.com/npm/npm/blob/8fa75cd0313e3cea8459f89b79208461e54b033b/lib/utils/tar.js#L351).

This introduced a bug in [my tool](https://www.npmjs.com/package/elm-new), which is simply supposed to have a `.gitignore` file, along many others. However it has a `.npmignore` instead.

#### How can the CLI team reproduce the problem?

1. install the tool: `npm install --save-dev elm-new`
2. check under `node_modules/elm-new/share/elm-new/src/`. There is a `.npmignore` file which was originally a `.gitignore`.

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: v6.7.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by othiym23** [comment] 2016-10-10 21:56
This is the defined behavior of the CLI when `.npmignore` files exist but `.gitignore` doesn't. The _behavior_ is described in [the developer documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package), but the implementation (renaming `.gitignore` to `.npmignore` at publish time) isn't clearly documented. If you wanted to take a stab at providing a documentation patch to make that clearer, it would be very helpful. Since this is the expected behavior, though, I'm going to close this issue.

If you want to work around this for a generator, I suggest using a templating tool, or something like [`tacks`](http://npm.im/tacks) to create default `.gitignores` at runtime.

Thanks for your time!

**Closed by othiym23** 2016-10-10 21:56 UTC
Labels: support

**Comment by simonewebdesign** [comment] 2016-10-11 11:15
Thanks for your reply!

To be honest I think it's a strange behaviour regardless of the absence of documentation. I feel like npm shouldn't really mess around with user-defined files. Anyway, thanks for the suggestion. I guess there's no way other than creating the file at runtime to work around the issue.
