### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by schwrrring** [npm/npm#7654] opened 2015-03-17 09:25 UTC
hey i keep on getting errors, trying to install things. I am very very new to node and coding in general. Help would be great - using easy terms even better ;)

best, malte

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'request' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'request', null ]
6 verbose cache add spec request
7 silly cache add parsed spec { raw: 'request',
7 silly cache add   scope: null,
7 silly cache add   name: 'request',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed request@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'request', range: '*', hasData: false }
12 silly mapToRegistry name request
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/request
16 verbose addNameRange registry:https://registry.npmjs.org/request not in flight; fetching
17 verbose request uri https://registry.npmjs.org/request
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:13:52
20 verbose request id a7d0d88dca51d5fe
21 verbose etag "50NK5OQZWXHL1G7SVH0NGODH5"
22 http request GET https://registry.npmjs.org/request
23 http 304 https://registry.npmjs.org/request
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 17 Mar 2015 09:13:52 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Tue, 17 Mar 2015 09:13:16 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"50NK5OQZWXHL1G7SVH0NGODH5"',
24 silly get     age: '38',
24 silly get     'x-served-by': 'cache-fra1230-FRA',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '4',
24 silly get     'x-timer': 'S1426583632.174305,VS0,VE0',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/request from cache
26 verbose get saving request to /Users/maltehildebrand/.npm/registry.npmjs.org/request/.cache.json
27 silly addNameRange number 2 { name: 'request', range: '*', hasData: true }
28 silly addNameRange versions [ 'request',
28 silly addNameRange   [ '0.10.0',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.5',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.9.0',
28 silly addNameRange     '1.9.1',
28 silly addNameRange     '1.9.2',
28 silly addNameRange     '1.9.3',
28 silly addNameRange     '1.9.5',
28 silly addNameRange     '1.9.7',
28 silly addNameRange     '1.9.8',
28 silly addNameRange     '1.9.9',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.0.1',
28 silly addNameRange     '2.0.2',
28 silly addNameRange     '2.0.3',
28 silly addNameRange     '2.0.4',
28 silly addNameRange     '2.0.5',
28 silly addNameRange     '2.1.0',
28 silly addNameRange     '2.1.1',
28 silly addNameRange     '2.2.0',
28 silly addNameRange     '2.2.5',
28 silly addNameRange     '2.2.6',
28 silly addNameRange     '2.2.9',
28 silly addNameRange     '2.9.0',
28 silly addNameRange     '2.9.1',
28 silly addNameRange     '2.9.2',
28 silly addNameRange     '2.9.3',
28 silly addNameRange     '2.9.100',
28 silly addNameRange     '2.9.150',
28 silly addNameRange     '2.9.151',
28 silly addNameRange     '2.9.152',
28 silly addNameRange     '2.9.153',
28 silly addNameRange     '2.9.200',
28 silly addNameRange     '2.9.201',
28 silly addNameRange     '2.9.202',
28 silly addNameRange     '2.9.203',
28 silly addNameRange     '2.10.0',
28 silly addNameRange     '2.11.0',
28 silly addNameRange     '2.11.1',
28 silly addNameRange     '2.11.2',
28 silly addNameRange     '2.11.3',
28 silly addNameRange     '2.11.4',
28 silly addNameRange     '2.12.0',
28 silly addNameRange     '2.14.0',
28 silly addNameRange     '2.16.0',
28 silly addNameRange     '2.16.2',
28 silly addNameRange     '2.16.4',
28 silly addNameRange     '2.16.6',
28 silly addNameRange     '2.18.0',
28 silly addNameRange     '2.19.0',
28 silly addNameRange     '2.20.0',
28 silly addNameRange     '2.21.0',
28 silly addNameRange     '2.22.0',
28 silly addNameRange     '2.23.0',
28 silly addNameRange     '2.24.0',
28 silly addNameRange     '2.25.0',
28 silly addNameRange     '2.26.0',
28 silly addNameRange     '2.27.0',
28 silly addNameRange     '2.28.0',
28 silly addNameRange     '2.29.0',
28 silly addNameRange     '2.30.0',
28 silly addNameRange     '2.31.0',
28 silly addNameRange     '2.32.0',
28 silly addNameRange     '2.33.0',
28 silly addNameRange     '2.34.0',
28 silly addNameRange     '2.35.0',
28 silly addNameRange     '2.36.0',
28 silly addNameRange     '2.37.0',
28 silly addNameRange     '2.38.0',
28 silly addNameRange     '2.39.0',
28 silly addNameRange     '2.40.0',
28 silly addNameRange     '2.41.0',
28 silly addNameRange     '2.42.0',
28 silly addNameRange     '2.43.0',
28 silly addNameRange     '2.44.0',
28 silly addNameRange     '2.45.0',
28 silly addNameRange     '2.46.0',
28 silly addNameRange     '2.47.0',
28 silly addNameRange     '2.48.0',
28 silly addNameRange     '2.49.0',
28 silly addNameRange     '2.50.0',
28 silly addNameRange     '2.51.0',
28 silly addNameRange     '2.52.0',
28 silly addNameRange     '2.53.0' ] ]
29 verbose addNamed request@2.53.0
30 silly addNamed semver.valid 2.53.0
31 silly addNamed semver.validRange 2.53.0
32 silly cache afterAdd request@2.53.0
33 verbose afterAdd /Users/maltehildebrand/.npm/request/2.53.0/package/package.json not in flight; writing
34 verbose afterAdd /Users/maltehildebrand/.npm/request/2.53.0/package/package.json written
35 silly install resolved [ { name: 'request',
35 silly install resolved     description: 'Simplified HTTP request client.',
35 silly install resolved     tags: [ 'http', 'simple', 'util', 'utility' ],
35 silly install resolved     version: '2.53.0',
35 silly install resolved     author: { name: 'Mikeal Rogers', email: 'mikeal.rogers@gmail.com' },
35 silly install resolved     repository: { type: 'git', url: 'https://github.com/request/request.git' },
35 silly install resolved     bugs: { url: 'http://github.com/request/request/issues' },
35 silly install resolved     license: 'Apache-2.0',
35 silly install resolved     engines: { node: '>=0.8.0' },
35 silly install resolved     main: 'index.js',
35 silly install resolved     dependencies:
35 silly install resolved      { bl: '~0.9.0',
35 silly install resolved        caseless: '~0.9.0',
35 silly install resolved        'forever-agent': '~0.5.0',
35 silly install resolved        'form-data': '~0.2.0',
35 silly install resolved        'json-stringify-safe': '~5.0.0',
35 silly install resolved        'mime-types': '~2.0.1',
35 silly install resolved        'node-uuid': '~1.4.0',
35 silly install resolved        qs: '~2.3.1',
35 silly install resolved        'tunnel-agent': '~0.4.0',
35 silly install resolved        'tough-cookie': '>=0.12.0',
35 silly install resolved        'http-signature': '~0.10.0',
35 silly install resolved        'oauth-sign': '~0.6.0',
35 silly install resolved        hawk: '~2.3.0',
35 silly install resolved        'aws-sign2': '~0.5.0',
35 silly install resolved        stringstream: '~0.0.4',
35 silly install resolved        'combined-stream': '~0.0.5',
35 silly install resolved        isstream: '~0.1.1' },
35 silly install resolved     scripts:
35 silly install resolved      { test: 'npm run lint && node node_modules/.bin/taper tests/test-*.js && npm run test-browser && npm run clean',
35 silly install resolved        'test-browser': 'node tests/browser/start.js',
35 silly install resolved        lint: 'node node_modules/.bin/eslint lib/ *.js tests/ && echo Lint passed.' },
35 silly install resolved     devDependencies:
35 silly install resolved      { browserify: '~5.9.1',
35 silly install resolved        'browserify-istanbul': '~0.1.3',
35 silly install resolved        coveralls: '~2.11.2',
35 silly install resolved        eslint: '0.5.1',
35 silly install resolved        'function-bind': '~1.0.0',
35 silly install resolved        istanbul: '~0.3.2',
35 silly install resolved        karma: '~0.12.21',
35 silly install resolved        'karma-browserify': '~3.0.1',
35 silly install resolved        'karma-cli': '0.0.4',
35 silly install resolved        'karma-coverage': '0.2.6',
35 silly install resolved        'karma-phantomjs-launcher': '~0.1.4',
35 silly install resolved        'karma-tap': '~1.0.1',
35 silly install resolved        rimraf: '~2.2.8',
35 silly install resolved        'server-destroy': '~1.0.0',
35 silly install resolved        tape: '~3.0.0',
35 silly install resolved        taper: '~0.4.0' },
35 silly install resolved     gitHead: '541ce25648bc2ecab924d7d7197a2685fa16d348',
35 silly install resolved     homepage: 'https://github.com/request/request',
35 silly install resolved     _id: 'request@2.53.0',
35 silly install resolved     _shasum: '180a3ae92b7b639802e4f9545dd8fcdeb71d760c',
35 silly install resolved     _from: 'request@*',
35 silly install resolved     _npmVersion: '1.4.14',
35 silly install resolved     _npmUser: { name: 'nylen', email: 'jnylen@gmail.com' },
35 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '180a3ae92b7b639802e4f9545dd8fcdeb71d760c',
35 silly install resolved        tarball: 'http://registry.npmjs.org/request/-/request-2.53.0.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/request/-/request-2.53.0.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install request@2.53.0 into /Users/maltehildebrand/Documents/Node-Tutorial/chat/home/my_app
37 info installOne request@2.53.0
38 verbose installOne of request to /Users/maltehildebrand/Documents/Node-Tutorial/chat/home/my_app not in flight; installing
39 warn locking Error: EACCES, open '/Users/maltehildebrand/.npm/_locks/request-3ac52a2c92967410.lock'
39 warn locking     at Error (native)
39 warn locking  /Users/maltehildebrand/.npm/_locks/request-3ac52a2c92967410.lock failed { [Error: EACCES, open '/Users/maltehildebrand/.npm/_locks/request-3ac52a2c92967410.lock']
39 warn locking   errno: -13,
39 warn locking   code: 'EACCES',
39 warn locking   path: '/Users/maltehildebrand/.npm/_locks/request-3ac52a2c92967410.lock' }
40 verbose stack Error: Attempt to unlock /Users/maltehildebrand/Documents/Node-Tutorial/chat/home/my_app/node_modules/request, which hasn't been locked
40 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
40 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
40 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
40 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
41 verbose cwd /Users/maltehildebrand/Documents/Node-Tutorial/chat/home/my_app
42 error Darwin 14.1.0
43 error argv "node" "/usr/local/bin/npm" "install" "request"
44 error node v0.12.0
45 error npm  v2.5.1
46 error Attempt to unlock /Users/maltehildebrand/Documents/Node-Tutorial/chat/home/my_app/node_modules/request, which hasn't been locked
47 error If you need help, you may report this error at:
47 error     <http://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
 ```

**Comment by KenanY** [comment] 2015-03-17 13:49
@schwrrring It appears as though you do not have the permissions necessary to write to `~/.npm`. Could you try taking ownership back?

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by smikes** [comment] 2015-05-03 10:05
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-05-20 03:33
Closing as resolved.

**Closed by othiym23** 2015-05-20 03:33 UTC
Labels: support

**Comment by saketamraotkar13** [comment] 2015-05-27 09:48
I am also facing same issue,

i did npm install -g cordova, and i git the same error, also when i ran below command, i get to see cordova version 5.0.0.

cordova -version.

Please help us, since its really frustrating.

**Comment by smikes** [comment] 2015-05-27 14:10
@saketamraotkar13 could you please open a new issue and run

```
npm -ddd install -g cordova
```

This will leave an `npm-debug.log` file - please upload that to <https://gist.github.com> and post the link to the issue you create.

Thanks!

**Comment by saketamraotkar13** [comment] 2015-05-31 12:59
Hi Smikes, Thanks for replying, i think the server machine which i was trying to create Cordova container was affected by virus which was preventing to set the proxy.

Smikes also, i am looking for plugin which will integrate bluetooth printer with the hybrid application, dopes Cordova provides any plugin which helps integrating with bluetooth printer.

Printer make up is: Intermec PB42 by Honeywell.

I have already reached to Intermec development team and they confirmed that they don't have any plugin for HTML5.

we are targeting Windows 8.1 devices and SAPUI5 for developing Hybrid application which will be packaged in Cordova container for native feel.

Your valuable inputs are welcome.
 
Regards
Saket
