### ISSUE TITLE
`npm install` errors " ENOENT, readdir '/Users/user/.npm/_git-remotes/git-github-com-user-project/hooks/post-merge'"

### ISSUE THREAD

**Issue by fent** [npm/npm#3585] opened 2013-06-19 18:22 UTC
I get this error if I run `npm install` or `npm install package`.

```
lood $ npm i
npm WARN package.json flood@0.0.1 No repository field.
npm WARN package.json pudding@0.0.1 No repository field.
npm WARN package.json pudding@0.0.2 No repository field.
npm ERR! Error: ENOENT, readdir '/Users/roly/.npm/_git-remotes/git-github-com-poptip-pudding-git-572b2fa3/hooks/post-merge'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "i"
npm ERR! cwd /Users/roly/code/poptip/flood
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /Users/roly/.npm/_git-remotes/git-github-com-poptip-pudding-git-572b2fa3/hooks/post-merge
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/roly/code/poptip/flood/npm-debug.log
npm ERR! not ok code 0
```

I tried clearing the cache, and deleting `node_modules`. This happens everywhere I run it. Please let me know of any additional info you may need.

**Comment by smikes** [comment] 2015-01-21 13:16
Is this still a problem for you?

This looks like it could have been caused by a race condition -- many of these have been fixed in newer `npm` versions.  There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.2.32. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by fent** [comment] 2015-01-21 17:09
No I have not encountered this error anymore.

**Closed** 2015-01-24 01:38 UTC
Labels: support
