### ISSUE TITLE
 npm is producing an incorrect install.

### ISSUE THREAD

**Issue by billyliu** [npm/npm#14484] opened 2016-11-01 09:12 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by billyliu** [comment] 2016-11-01 09:26
I install the cordova with"npm install -g cordova", but there is

9331 silly mapToRegistry uri https://registry.npmjs.org/cordova-app-hello-world
9332 verbose addRemoteTarball https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz not in flight; adding
9333 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz',
9333 verbose addRemoteTarball   '9214feb9dd713ca481a1cbabceeca60966c1c0cf' ]
9334 info retry fetch attempt 1 at 16:55:07
9335 info attempt registry request try #1 at 16:55:07
9336 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz
9337 silly cache afterAdd shelljs@0.3.0
9338 verbose afterAdd C:\Users\billy.liu\AppData\Roaming\npm-cache\shelljs\0.3.0\package\package.json not in flight; writing
9339 verbose correctMkdir C:\Users\billy.liu\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
9340 verbose afterAdd C:\Users\billy.liu\AppData\Roaming\npm-cache\shelljs\0.3.0\package\package.json written
9341 http fetch 200 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz
9342 silly fetchAndShaCheck shasum 9214feb9dd713ca481a1cbabceeca60966c1c0cf
9343 silly rollbackFailedOptional Starting
9344 silly rollbackFailedOptional Finishing
9345 silly runTopLevelLifecycles Finishing
9346 silly install printInstalled
9347 verbose stack Error: shasum check failed for C:\Users\billy.liu\AppData\Local\Temp\npm-184-b64f62b4\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.11.0.tgz
9347 verbose stack Expected: 9214feb9dd713ca481a1cbabceeca60966c1c0cf
9347 verbose stack Actual:   dc638861511c7c26695851514884d59bc0fb59bc
9347 verbose stack From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz
9347 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
9347 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
9347 verbose stack     at emitNone (events.js:91:20)
9347 verbose stack     at ReadStream.emit (events.js:185:7)
9347 verbose stack     at endReadableNT (_stream_readable.js:974:12)
9347 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
9347 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
9348 verbose cwd C:\Users\billy.liu
9349 error Windows_NT 6.3.9600
9350 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
9351 error node v6.9.1
9352 error npm  v3.10.8
9353 error shasum check failed for C:\Users\billy.liu\AppData\Local\Temp\npm-184-b64f62b4\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.11.0.tgz
9353 error Expected: 9214feb9dd713ca481a1cbabceeca60966c1c0cf
9353 error Actual:   dc638861511c7c26695851514884d59bc0fb59bc
9353 error From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.11.0.tgz
9354 error If you need help, you may report this error at:
9354 error     <https://github.com/npm/npm/issues>
9355 verbose exit [ 1, true ]

I'm not know how todo it. please help me.

C:\Users\billy.liu>npm -v
3.10.8

C:\Users\billy.liu>node -v
v6.9.1

C:\Users\billy.liu>npm config get registry
https://registry.npmjs.org/

THX

**Comment by legodude17** [comment] 2016-11-01 16:03
Try running `npm cache clean`.

**Comment by billyliu** [comment] 2016-11-02 11:34
OK, thank you.

**Comment by legodude17** [comment] 2016-11-02 18:44
Are you still having this issue?

**Comment by zkat** [comment] 2016-12-09 00:34
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:34 UTC
Labels: network, shasum, support
