### ISSUE TITLE
Npm not throwing `npm ERR! missing`

### ISSUE THREAD

**Issue by lone-star** [npm/npm#9652] opened 2015-09-18 11:38 UTC
### Context

I created an empty project for that. Here is my `package.json`. Note the intentionally non-matching repository name.

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "express-2": "strongloop/express"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}        
```

### Problem

- When running `npm list`, I am getting this result (Which is the expected one):

```
test@1.0.0 /Users/lone-star/dev/test
└── UNMET DEPENDENCY express-2@github:strongloop/express

npm ERR! missing: express-2@github:strongloop/express, required by test@1.0.0
```

- When running `npm install`, I am getting this result:

```
➜  test  npm install
➜  test  echo $?
0
```

It successfully installed in spite of the missing repository, and `node_modules/` is empty. Not sure if this is the expected behaviour, but I would rather have the install fail.

I am having the problem since upgrading from 2.X to 3.X. Before the dependency would install, and be added in `node_modules/` in spite of a non-matching repository name.

npm version: 3.3.3

**Comment by othiym23** [comment] 2015-09-21 21:07
Closing as a duplicate of #9652 -- the issue here is that npm doesn't let you rename packages in `package.json` (like you've done with `express-2` in your example there), but doesn't error, either. That is absolutely a bug, and one we should get fixed relatively soon.

**Closed by othiym23** 2015-09-21 21:07 UTC
Labels: bug
