### ISSUE TITLE
npm issue .

### ISSUE THREAD

**Issue by lalitkumar1994** [npm/npm#15180] opened 2016-12-09 06:36 UTC
sgs:node lalitkumar$ npm install phantom
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantom"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lalitkumar/Documents/node/npm-debug.log

**Comment by zkat** [comment] 2016-12-09 07:24
Closing as a duplicate of https://github.com/npm/npm/issues/14579

**Closed by zkat** 2016-12-09 07:24 UTC
