### ISSUE TITLE
Failed to run "npm install -g grunt-cli"

### ISSUE THREAD

**Issue by w971463** [npm/npm#11407] opened 2016-02-04 07:09 UTC
ERR!!! Write EIO
[npm-debug.zip](https://github.com/npm/npm/files/116979/npm-debug.zip)

**Comment by ashleygwilliams** [comment] 2016-02-06 17:43
hi! this is a duplicate of https://github.com/npm/npm/issues/3538

please refer to that issue to solve your problem. if you continue to have trouble, please open a new issue.

**Closed by ashleygwilliams** 2016-02-06 17:43 UTC
