### ISSUE TITLE
Refusing to Install Knex as a Dependency of Itself

### ISSUE THREAD

**Issue by ASA2** [npm/npm#11286] opened 2016-01-26 16:01 UTC
Trying to install knex: npm install knex --save.

Getting this error:
Refusing to install knex as a dependency of itself
[npm-debug.zip](https://github.com/npm/npm/files/105196/npm-debug.zip)

**Comment by ASA2** [comment] 2016-01-26 16:13
This error occurs when the project directory matches npm module name. For example, trying to install the NPM module 'knex' in a parent directory named 'knex' will cause this error.

**Comment by KenanY** [comment] 2016-01-26 16:31
So rename the directory :)

**Comment by ASA2** [comment] 2016-01-26 18:43
Obviously. However, it probably shouldn't work that way...

On Tue, Jan 26, 2016 at 11:31 AM, Kenan Yildirim <notifications@github.com>
wrote:

> So rename the directory :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11286#issuecomment-175103399>.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by KenanY** [comment] 2016-01-26 18:54
I'll just wait for a member of the CLI team to chime in on what they think abou this. I couldn't think of a solid reason for disallowing this naming, but at the same time I could not imagine why I, _personally_, would name my current directory after one of my dependencies.

**Comment by ASA2** [comment] 2016-01-26 19:15
The use case is during development when you want to test a particular
module. So, let's say I want to checkout 'kext'. It seems reasonable to
name that directory 'kext'! It's not a big deal. But the error message did
not give us any indication of what the problem was, so we submitted a
ticket. Also, I can't think of a good reason for this naming conflict to
exist in the first place. Why would the containing directory name matter?

On Tue, Jan 26, 2016 at 1:55 PM, Kenan Yildirim <notifications@github.com>
wrote:

> I'll just wait for a member of the CLI team to chime in on what they think
> abou this. I couldn't think of a solid reason for disallowing this naming,
> but at the same time I could not imagine why I, *personally*, would name
> my current directory after one of my dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11286#issuecomment-175176002>.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by KenanY** [comment] 2016-01-26 19:37
@ASA2 If you want to work on a module you should `git clone` it not `npm install` it, no?

**Comment by ASA2** [comment] 2016-01-26 19:57
That's not the issue.  We're not working on npm modules. We're using them
for our own product. So, if we wanted to experiment with, for example, the
'jsql' npm module the most logic thing to do is to create a directory named
'jsql' to hold a test app, change to that directory and then use npm to
install it into node_modules. Currently, that will cause an error during
install without any informative message as to what the problem is. Still
not sure why the containing directory should matter. Anyway, the real issue
is that uninformative error message.



On Tue, Jan 26, 2016 at 2:37 PM, Kenan Yildirim <notifications@github.com>
wrote:

> @ASA2 <https://github.com/ASA2> If you want to work on a module you
> should git clone it not npm install it, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11286#issuecomment-175193576>.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by timoxley** [comment] 2016-01-26 20:02
this really is a non-problem, just call it `jsql-test` or `knex-test` instead.

**Comment by ASA2** [comment] 2016-01-26 20:04
You're totally missing the point. How would anyone know that they need to
change the directory name from "Refusing to Install Knex as a Dependency of
Itself"? There's absolutely nothing in the error message that tells me what
the problem is or how to solve it.

On Tue, Jan 26, 2016 at 3:02 PM, Tim Oxley <notifications@github.com> wrote:

> this really is a non-problem, just call it jsql-test or knex-test instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11286#issuecomment-175202741>.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by ASA2** [comment] 2016-01-26 20:12
You're right, this is not a big deal. Just use a different directory name.
The ONLY issue is that the error message does not tell me what the problem
is.  So, how would I know that I need to use a different name?

On Tue, Jan 26, 2016 at 3:04 PM, Lee Mellinger <
lee.mellinger@infinisuite.com> wrote:

> You're totally missing the point. How would anyone know that they need to
> change the directory name from "Refusing to Install Knex as a Dependency of
> Itself"? There's absolutely nothing in the error message that tells me what
> the problem is or how to solve it.
>
> On Tue, Jan 26, 2016 at 3:02 PM, Tim Oxley <notifications@github.com>
> wrote:
>
>> this really is a non-problem, just call it jsql-test or knex-test
>> instead.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/npm/npm/issues/11286#issuecomment-175202741>.
>>
>
>
>
> --
> *Lee Mellinger*
> President & CEO
> InfiniSuite, LLC
> www.infinisuite.com
> Mobile: 1.734.531.8702
> Skype: leemellinger
> LinkedIn: linkedin.com/in/leemellinger
> <https://www.linkedin.com/in/leemellinger>
>
> *Business Solutions for Cloud 2.0*
>
> NOTICE: The information contained in this e-mail, and in any accompanying
> documents, may constitute confidential and/or legally privileged
> information. The information is intended only for use by the designated
> recipient. If you are not the intended recipient (or responsible for the
> delivery of the message to the intended recipient), you are hereby notified
> that any dissemination, distribution, copying, or other use of, or taking
> of any action in reliance on this e-mail is strictly prohibited. If you
> have received this e-mail communication in error, please notify the sender
> immediately and delete the message from your system.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by zkat** [comment] 2016-01-26 22:12
Hey,

As others said, this is the expected behavior: You can't install packages as dependencies of themselves and npm can't handle that. Renaming your parent package may be prudent (or using a different name in `package.json`).

If you feel like the error message could be clearer, that sounds like a good patch to submit to our error messaging, and I think we could probably merge something that clarified that a bit. Would you be willing to put that together, by any chance?

In the meantime, I'm closing this (note that we're closing things a bit more aggressively lately because of the sheer volume of stuff we're dealing with, so I don't want it to come off as dismissive <3).

Thanks for taking the time to submit/discuss this!

**Closed by zkat** 2016-01-26 22:12 UTC
Labels: error-handling, patch-welcome, support

**Comment by ASA2** [comment] 2016-01-27 13:52
Kat, hi. Just a simple message like  'Module directory name conflicts with
parent directory name' would work.

Thanks!

On Tue, Jan 26, 2016 at 5:13 PM, Kat Marchán <notifications@github.com>
wrote:

> Hey,
>
> As others said, this is the expected behavior: You can't install packages
> as dependencies of themselves and npm can't handle that. Renaming your
> parent package may be prudent (or using a different name in package.json).
>
> If you feel like the error message could be clearer, that sounds like a
> good patch to submit to our error messaging, and I think we could probably
> merge something that clarified that a bit. Would you be willing to put that
> together, by any chance?
>
> In the meantime, I'm closing this (note that we're closing things a bit
> more aggressively lately because of the sheer volume of stuff we're dealing
> with, so I don't want it to come off as dismissive <3).
>
> Thanks for taking the time to submit/discuss this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/11286#issuecomment-175257897>.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.
