### ISSUE TITLE
Cannot Run ng new on Windows 7

### ISSUE THREAD

**Issue by tachyon80** [npm/npm#18912] opened 2017-10-20 13:11 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I cannot run the "ng new" command.
#### How can the CLI team reproduce the problem?

--Error Log--
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   '@angular/cli@latest' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose config Skipping project config: C:\Users\FZZ4J8/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData @angular/cli@latest
9 silly fetchNamedPackageData @angular/cli
10 silly mapToRegistry name @angular/cli
11 silly mapToRegistry scope (from package name) @angular
12 verbose mapToRegistry no registry URL found in name for scope @angular
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://artifactory.gm.com/artifactory/api/npm/javascript
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: '@angular/cli',
15 silly mapToRegistry   scope: '@angular',
15 silly mapToRegistry   escapedName: '@angular%2fcli',
15 silly mapToRegistry   name: '@angular/cli',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli
17 verbose request uri https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli
18 verbose request always-auth set; sending authorization
19 info attempt registry request try #1 at 7:39:08 AM
20 verbose request id 995987a9b690fb46
21 verbose etag 9323c49f6797b9200e2c30ef1d5f4d821d53d3a0
22 http request GET https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli
23 http 304 https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli
24 verbose headers { server: 'Artifactory/4.16.0',
24 verbose headers   'x-artifactory-id': '3948c94328654ca718584f09d8cbd159e723f461',
24 verbose headers   'x-artifactory-node-id': 'dcmipvmarf002.edc.nam.gm.com',
24 verbose headers   date: 'Fri, 20 Oct 2017 12:39:09 GMT' }
25 silly get cb [ 304,
25 silly get   { server: 'Artifactory/4.16.0',
25 silly get     'x-artifactory-id': '3948c94328654ca718584f09d8cbd159e723f461',
25 silly get     'x-artifactory-node-id': 'dcmipvmarf002.edc.nam.gm.com',
25 silly get     date: 'Fri, 20 Oct 2017 12:39:09 GMT' } ]
26 verbose etag https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli from cache
27 verbose get saving @angular/cli to C:\Users\FZZ4J8\AppData\Roaming\npm-cache\artifactory.gm.com\artifactory\api\npm\javascript\_40angular_252fcli\.cache.json
28 verbose correctMkdir C:\Users\FZZ4J8\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
29 silly install normalizeTree
30 silly loadCurrentTree Finishing
31 silly loadIdealTree Starting
32 silly install loadIdealTree
33 silly cloneCurrentTree Starting
34 silly install cloneCurrentTreeToIdealTree
35 silly cloneCurrentTree Finishing
36 silly loadShrinkwrap Starting
37 silly install loadShrinkwrap
38 silly loadShrinkwrap Finishing
39 silly loadAllDepsIntoIdealTree Starting
40 silly install loadAllDepsIntoIdealTree
41 silly rollbackFailedOptional Starting
42 silly rollbackFailedOptional Finishing
43 silly runTopLevelLifecycles Finishing
44 silly install printInstalled
45 verbose stack Error: Refusing to install @angular/cli as a dependency of itself
45 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
45 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
45 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
45 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
45 verbose stack     at Array.forEach (native)
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
45 verbose stack     at Array.forEach (native)
45 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
46 verbose cwd C:\Users\FZZ4J8
47 error Windows_NT 6.1.7601
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@angular/cli@latest"
49 error node v6.11.4
50 error npm  v3.10.10
51 error code ENOSELF
52 error Refusing to install @angular/cli as a dependency of itself
53 error If you need help, you may report this error at:
53 error     <https://github.com/npm/npm/issues>
54 verbose exit [ 1, true ]
--END Error Log--

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.4
 - `npm config get registry` prints: https://artifactory.gm.com/artifactory/api/npm/javascript
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-10-20 18:47
So this is the output of `ng new`? Looks like that command is running `npm install --save-dev @latest`, doesn't really make sense since that would make the current package depend on itself. Since this is expected behavior from `npm`, I'm gonna close this, but feel free to continue discussion if necessary.

**Closed as completed by kenany** 2017-10-20 18:47 UTC
Labels: support
