### ISSUE TITLE
Install Ionic shasum check failed

### ISSUE THREAD

**Issue by changwcn** [npm/npm#14539] opened 2016-11-06 15:10 UTC
changweiMBP:~ ChangWei$ npm i ionic -g
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "i" "ionic" "-g"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for /var/folders/g3/42v7_2jd7rsffffqwf7q2myw0000gn/T/npm-1246-1f52165c/registry.npmjs.org/ionic/-/ionic-2.1.4.tgz
npm ERR! Expected: 3e799d20ea079c0191ed5f0d187f565c539879db
npm ERR! Actual:   78d74180f379d9683620ba59732c530e55a239ed
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by watilde** [comment] 2016-11-06 17:26
Hello! It seems that you're catching a wrong cache file of the package in your cache directory. Could you please clear the cache by the following command first, and then try again?

```
npm cache clean
```

**Comment by zkat** [comment] 2016-12-09 00:33
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:33 UTC
Labels: network, support
