### ISSUE TITLE
npm@5 outdated --global doesn't show anything

### ISSUE THREAD

**Issue by joakin** [npm/npm#16909] opened 2017-06-02 09:38 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm outdated --global` produced output on npm@4 but after upgrading it shows nothing with npm@5.0.1

#### How can the CLI team reproduce the problem?

1. Ensure you have outdated packages installed locally.
2. Run with npm@4 `npm outdated -g`
3. Confirm you have outdated packages
4. Install npm@5 `npm install -g npm@5`
5. Run `npm outdated -g`
6. **Expected**: Same list of outdated packages appears. **Actual**: See that no output is printed.

Here's a print out of the scenario on my machine:

```
$ npm install -g npm@4
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
added 12 packages, removed 60 packages and updated 36 packages in 8.946s

$ npm -v
4.6.1

$ npm outdated -g
Package                       Current  Wanted  Latest  Location
browserify                     14.3.0  14.3.0  14.4.0
create-elm-app                  0.6.3   0.8.1   0.8.1
create-react-app                1.3.0   1.3.0   1.3.1
firebase-tools                  3.6.1   3.6.1   3.9.1
js-beautify                    1.6.12  1.6.14  1.6.14
mermaid                         7.0.0   7.0.0   7.0.2
nativefier                      7.3.1   7.4.0   7.4.0
node-gyp                        3.6.1   3.6.2   3.6.2
now                             6.1.0   6.2.5   6.2.5
npm                             4.6.1   5.0.1   5.0.1
preact-cli                      1.0.1   1.1.0   1.1.0
typescript                      2.3.2   2.3.4   2.3.4
webpack-bundle-size-analyzer    2.6.0   2.7.0   2.7.0
yarn                           0.23.4  0.24.5  0.24.5

$ npm install -g npm@5
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
- asap@2.0.5 node_modules/npm/node_modules/asap
- once@1.3.3 node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/node_modules/once
- os-homedir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-homedir
- os-tmpdir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-tmpdir
- osenv@0.1.4 node_modules/npm/node_modules/nopt/node_modules/osenv
- pseudomap@1.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap
- yallist@2.0.0 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist
- lru-cache@4.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache
- spdx-exceptions@1.0.4 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-exceptions
- spdx-license-ids@1.2.0 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-license-ids
- normalize-git-url@3.0.2 node_modules/npm/node_modules/normalize-git-url
- realize-package-specifier@3.0.3 node_modules/npm/node_modules/realize-package-specifier
/usr/local/lib
└─┬ npm@5.0.1
  ├─┬ cacache@9.2.6
  │ ├── glob@7.1.2  deduped
  │ ├── lru-cache@4.0.2  deduped
  │ ├── promise-inflight@1.0.1  deduped
  │ ├── ssri@4.1.4  deduped
  │ └── y18n@3.2.1
  ├─┬ columnify@1.5.4
  │ └── wcwidth@1.0.1
  ├── detect-indent@5.0.0
  ├─┬ dezalgo@1.0.3
  │ └── asap@2.0.5
  ├─┬ fstream-npm@1.2.1
  │ └─┬ fstream-ignore@1.0.5
  │   └─┬ minimatch@3.0.4
  │     └── brace-expansion@1.1.7
  ├─┬ glob@7.1.2
  │ └─┬ minimatch@3.0.4
  │   └── brace-expansion@1.1.7
  ├─┬ init-package-json@1.10.1
  │ ├── glob@7.1.2  deduped
  │ └── npm-package-arg@5.0.1  deduped
  ├─┬ lru-cache@4.0.2
  │ ├── pseudomap@1.0.2
  │ └── yallist@2.1.2
  ├─┬ mississippi@1.3.0
  │ ├── end-of-stream@1.4.0
  │ ├─┬ pump@1.0.2
  │ │ └── end-of-stream@1.4.0  deduped
  │ └─┬ stream-each@1.2.0
  │   └── end-of-stream@1.4.0  deduped
  ├─┬ node-gyp@3.6.1
  │ ├── glob@7.1.2  deduped
  │ ├─┬ minimatch@3.0.4
  │ │ └── brace-expansion@1.1.7
  │ └── npmlog@4.1.0  deduped
  ├── npm-package-arg@5.0.1
  ├─┬ npm-registry-client@8.3.0
  │ ├── npm-package-arg@5.0.1  deduped
  │ ├── npmlog@4.1.0  deduped
  │ └── ssri@4.1.4  deduped
  ├── npm-user-validate@1.0.0
  ├── npmlog@4.1.0
  ├─┬ pacote@2.7.26
  │ ├── cacache@9.2.6  deduped
  │ ├── glob@7.1.2  deduped
  │ ├── lru-cache@4.0.2  deduped
  │ ├─┬ make-fetch-happen@2.4.10
  │ │ ├─┬ agentkeepalive@3.1.0
  │ │ │ └─┬ humanize-ms@1.2.1
  │ │ │   └── ms@2.0.0
  │ │ ├── cacache@9.2.6  deduped
  │ │ ├── http-cache-semantics@3.7.3
  │ │ ├─┬ http-proxy-agent@1.0.0
  │ │ │ ├─┬ agent-base@2.1.1
  │ │ │ │ ├── extend@3.0.1  deduped
  │ │ │ │ └── semver@5.0.3
  │ │ │ ├─┬ debug@2.6.8
  │ │ │ │ └── ms@2.0.0
  │ │ │ └── extend@3.0.1
  │ │ ├─┬ https-proxy-agent@1.0.0
  │ │ │ ├─┬ agent-base@2.1.1
  │ │ │ │ ├── extend@3.0.1  deduped
  │ │ │ │ └── semver@5.0.3
  │ │ │ ├─┬ debug@2.6.8
  │ │ │ │ └── ms@2.0.0
  │ │ │ └── extend@3.0.1
  │ │ ├── lru-cache@4.0.2  deduped
  │ │ ├─┬ node-fetch-npm@2.0.1
  │ │ │ ├─┬ encoding@0.1.12
  │ │ │ │ └── iconv-lite@0.4.17
  │ │ │ ├─┬ json-parse-helpfulerror@1.0.3
  │ │ │ │ └── jju@1.3.0
  │ │ │ └── safe-buffer@5.0.1  deduped
  │ │ ├── promise-retry@1.1.1  deduped
  │ │ ├─┬ socks-proxy-agent@2.1.0
  │ │ │ ├─┬ agent-base@2.1.1
  │ │ │ │ ├── extend@3.0.1  deduped
  │ │ │ │ └── semver@5.0.3
  │ │ │ ├── extend@3.0.1
  │ │ │ └─┬ socks@1.1.10
  │ │ │   ├── ip@1.1.5
  │ │ │   └── smart-buffer@1.1.15
  │ │ └── ssri@4.1.4  deduped
  │ ├─┬ minimatch@3.0.4
  │ │ └─┬ brace-expansion@1.1.7
  │ │   ├── balanced-match@0.4.2
  │ │   └── concat-map@0.0.1
  │ ├── npm-package-arg@5.0.1  deduped
  │ ├─┬ npm-pick-manifest@1.0.3
  │ │ └── npm-package-arg@5.0.1  deduped
  │ ├── promise-inflight@1.0.1  deduped
  │ ├─┬ promise-retry@1.1.1
  │ │ └── err-code@1.1.2
  │ ├─┬ protoduck@4.0.0
  │ │ └── genfun@4.0.1
  │ ├── safe-buffer@5.0.1  deduped
  │ ├── ssri@4.1.4  deduped
  │ ├─┬ tar-fs@1.15.2
  │ │ ├─┬ pump@1.0.2
  │ │ │ └── end-of-stream@1.4.0
  │ │ └── tar-stream@1.5.4  deduped
  │ └─┬ tar-stream@1.5.4
  │   ├── bl@1.2.1
  │   ├── end-of-stream@1.4.0
  │   └── xtend@4.0.1
  ├── promise-inflight@1.0.1
  ├─┬ read@1.0.7
  │ └── mute-stream@0.0.7
  ├─┬ read-package-json@2.0.5
  │ └── glob@7.1.2  deduped
  ├─┬ request@2.81.0
  │ ├── extend@3.0.1
  │ ├─┬ form-data@2.1.4
  │ │ └── mime-types@2.1.15  deduped
  │ ├─┬ har-validator@4.2.1
  │ │ └── ajv@4.11.8
  │ ├─┬ http-signature@1.1.1
  │ │ ├─┬ jsprim@1.4.0
  │ │ │ └── assert-plus@1.0.0
  │ │ └─┬ sshpk@1.13.0
  │ │   └── getpass@0.1.7
  │ └─┬ mime-types@2.1.15
  │   └── mime-db@1.27.0
  ├─┬ rimraf@2.6.1
  │ └── glob@7.1.2  deduped
  ├── safe-buffer@5.0.1
  ├─┬ sorted-union-stream@2.1.3
  │ └─┬ stream-iterate@1.2.0
  │   └── stream-shift@1.0.0
  ├─┬ ssri@4.1.4
  │ └── safe-buffer@5.0.1  deduped
  ├─┬ tar@2.2.1
  │ └── block-stream@0.0.9
  ├─┬ update-notifier@2.1.0
  │ ├─┬ boxen@1.0.0
  │ │ ├── camelcase@4.1.0
  │ │ └─┬ term-size@0.1.1
  │ │   └─┬ execa@0.4.0
  │ │     └─┬ cross-spawn-async@2.2.5
  │ │       └── lru-cache@4.0.2  deduped
  │ ├─┬ configstore@3.0.0
  │ │ └── write-file-atomic@1.3.4
  │ └─┬ latest-version@3.1.0
  │   └─┬ package-json@4.0.1
  │     ├─┬ registry-auth-token@3.3.0
  │     │ ├── rc@1.2.1
  │     │ └── safe-buffer@5.0.1
  │     └─┬ registry-url@3.1.0
  │       └── rc@1.2.1
  ├─┬ validate-npm-package-license@3.0.1
  │ ├─┬ spdx-correct@1.0.2
  │ │ └── spdx-license-ids@1.2.2
  │ └── spdx-expression-parse@1.0.4
  └── write-file-atomic@2.1.0

$ npm -v
5.0.1

$ npm outdated -g

$ npm outdated -g --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'outdated',
npm verb cli   '-g',
npm verb cli   '--verbose' ]
npm info using npm@5.0.1
npm info using node@v7.9.0
npm verb exit [ 0, true ]
npm info ok

```

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX 10.11.5 (15F34)
 - Network issues:
   - Geographic location where npm was run: Spain
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by joakin** [comment] 2017-06-02 09:42
I've run ls to check that the previously installed global modules are seen by npm@5, and it seems to be the case:

 ```
$ npm ls -g --depth=0
/usr/local/lib
├── browserify@14.3.0
  ...
```

**Comment by ben-page** [comment] 2017-06-02 17:10
I'm seeing the same behavior.

**Comment by choyan** [comment] 2017-06-04 12:03
Same problem is occurring here. npm 5 is unable to show outdated packages.

**Comment by jokeyrhyme** [comment] 2017-06-04 18:54
This seems to affect `npm update --global` as that no longer appears to perform any updates, which is logical if it internally shares logic with `npm outdated --global`

**Comment by zkat** [comment] 2017-06-05 15:56
Closing as dupe of https://github.com/npm/npm/issues/16840

**Closed as completed by zkat** 2017-06-05 15:56 UTC
Labels: npm5
