### ISSUE TITLE
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by robet8888** [npm/npm#14388] opened 2016-10-23 14:11 UTC
im newbie in ionic i got error when i want to install cordova

```
C:\Users\WIN7\AppData\Roaming\npm\node_modules\cordova>npm install -g cordova
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\WIN7\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\WIN7\AppData\Roaming\npm\node_modules\cordova
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\WIN7\AppData\Roaming\npm\node_modules\cordova' -> 'C:\Users\WIN7\AppData\Roaming\npm\node_modules.cordova.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\WIN7\AppData\Roaming\npm\node_modules\cordova\npm-debug.log
```

i already try 
 npm install -g npm@latest 
npm install -g minimatch@latest
npm install -g cordova

and still got same error

**supporting information:**
npm -v:  3.10.9
node -v: 6.9.1

**Comment by watilde** [comment] 2016-10-30 16:44
Hello! It seems to be duplicated issue to https://github.com/npm/npm/issues/8564

**Comment by othiym23** [comment] 2016-11-23 22:38
Good call, @watilde-san! Closing as duplicate of #8564. (This is probably fixed by `npm@latest`, which uses a more forgiving version of `graceful-fs`, so try [upgrading to the latest version](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows).

**Closed by othiym23** 2016-11-23 22:38 UTC
Labels: support, windows
