### ISSUE TITLE
Installing npm 3.4.1 via npm 3.4.1 is broken

### ISSUE THREAD

**Issue by mzgol** [npm/npm#10394] opened 2015-11-14 21:07 UTC
Update: this report originally said about updating from 3.4.0 to 3.4.1 but it's "updating" from 3.4.1 to 3.4.1 (i.e. to itself) that's a problem.

I've used npm 3.4.1 and tried to upgrade via `npm -g i npm@next` (when 3.4.1 itself was next). I did it for 4 different Node versions (0.10.40, 0.12.7, 4.2.2 & 5.0.0) and in all cases it ended with:
```
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > npm-registry-client with new installed version
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mgol/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
Now invoking any `npm` command immediately terminates with this error, making it effectively broken since you can't even dowgrade to a previous npm when you get into such a state.

**Comment by robertbaker** [comment] 2015-11-16 22:34
A solution to get you on 3.4.1 is to install npm@latest into a project. Copy the files inside `node-modules/npm` to your global npm installation, minus the npmrc file.

**Comment by jokeyrhyme** [comment] 2015-11-18 06:40
It helps if you keep the npm that comes with node.js separate from npm updates. Then you have a fallback when updates go wrong.

**Comment by mzgol** [comment] 2015-11-18 10:50
@jokeyrhyme 
> It helps if you keep the npm that comes with node.js separate from npm updates. Then you have a fallback when updates go wrong.

How would I do it? npm on UNIX-like systems updates in-place.

@robertbaker 
> A solution to get you on 3.4.1 is to install npm@latest into a project.

How would I install it when I don't have a working npm? I had to re-install Node.js to make it work (it wasn't that hard considering I use nvm but I had to reinstall global packages afterwards).

**Comment by jokeyrhyme** [comment] 2015-11-18 16:28
@mzgol you can control where global packages are installed (including npm updates) with the prefix setting:

```sh
mkdir -p ~/.npm-packages
npm config set prefix ~/.npm-packages
export PATH=~/.npm-packages/bin:$PATH
```

Note that nvm detects this and complains, so don't use this method with nvm.

Now, everytime I run `npm update -g` and npm 3.4.1 is installed in a broken state, I can re-run `/usr/bin/npm -g install npm`, because the system-global npm was never impacted.

**Comment by imyejin** [comment] 2015-11-18 16:28
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <Re: [npm] Upgrading npm from 3.4.0 to 3.4.1 is broken (#10394)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by jokeyrhyme** [comment] 2015-11-18 16:29
@mzgol alternatively, maybe use nvm to keep a parallel install of a slightly older node+npm, so you always have a safe known-good copy of npm?

**Comment by jokeyrhyme** [comment] 2015-11-18 16:32
I'm surprised that 3.4.1 has not been unpublished yet. `npm` breaking itself seems like a pretty serious regression.

@isaacs ? @othiym23 ? @iarna ?

**Comment by othiym23** [comment] 2015-11-18 17:08
The issue isn't with npm@3.4.1, it's with 3.4.0 (and maybe with a few earlier versions that include this regression). There are a small number of packages with bundled dependencies, unfortunately including npm itself, that have issues with a change (fixed in `npm@3.4.1`, Alanis Morisette-ironically) made to how `bundledDependencies` are managed in some edge cases where the bundled dependencies didn't match the semver in `package.json`. It should be possible to use `npm@2` or `npm@3.3.6` to upgrade directly to `npm@next`.

**Comment by jokeyrhyme** [comment] 2015-11-18 18:47
@othiym23 ah, okay. This makes sense. Thanks for the explanation. Besides @robertbaker's solution above, or having to reinstall npm somehow (usually by reinstall node), is there a recommended way of resolving this issue?

**Comment by thealjey** [comment] 2015-11-20 09:37
In my case the steps to reproduce are very clear:

1. I have `npm@3.4.0` istalled
2. `npm i npm@latest -g` installs the latest `npm@3.4.1` (at this point everything is fine)
3. but, if you use `npm@3.4.1` to install itself by running `npm i npm@latest -g` again - you end up with a broken and completely unusable npm

**Comment by mzgol** [comment] 2015-11-20 10:19
I can reproduce @thealjey's steps (but starting from 3.3.6 instead of 3.4.0). Moreover, to exclude bugs in 3.x I installed 2.14.2 (i.e. latest 2) and tried then:
```
$ npm -g i npm@2.4.12
$ npm -g i npm@3.4.1
$ npm -v
3.4.1
$ npm -g i npm@3.4.1
$ npm -v
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mgol/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

So npm 3.4.1 is definitely broken...

**Comment by othiym23** [comment] 2015-11-20 16:31
See also #10492 and #10482 (which describes the underlying problem, and which @iarna heroically identified and fixed in a single day so we could get it into `npm@3.5.0`): I was wrong about where the issue lay, and I now think _both_ `npm@3.4.0` and `npm@3.4.1` have variations of this problem. Because it's related to `bundleDependencies`, and because npm bundles all its dependencies (because it has to), using npm to install itself is particularly likely to trigger #10482.

So, `npm@3.4.1` _is_ broken, but only when you use it to install npm. 😐 For that reason, I don't think we're going to push `npm@3.4.1` to Node.js, and are going to encourage the Node.js release team to skip including `npm@3.4.0` in any releases, and instead go straight to `npm@3.5.0` when it becomes available in a week (assuming that fixing #10482 didn't introduce any new, unforeseen regressions – part of the reason the CLI team is spending the year working on its test suite).

For now, the workaround is pretty simple: uninstall Node, make sure that npm's gotten removed from the global `node_modules` folder, reinstall Node, and (if you like) upgrade directly to `npm@next`. These things happen (package installation is hard!), but I apologize to everyone for their lost time and mental well-being.

**Closed by othiym23** 2015-11-20 16:32 UTC

**Comment by eins78** [comment] 2015-11-20 16:35
@othiym23 Do I understand you correctly that `npm@latest` will stay broken till next week?
We are always upgrading npm to latest as part of our deploy scripts (which seemed like a good idea at the time…), so I would need to work around that.

**Comment by othiym23** [comment] 2015-11-20 16:44
@eins78 `npm@3.4.1` / `npm@latest` is sort of a roach motel release – once you upgrade to it, you won't be able to upgrade _from_ it to other versions of npm. I'm unsure of how many other packages with `bundleDependencies` the regression will actually affect – maybe `ember-cli` (sorry, @stefanpenner!), although I suspect it's relatively few.

I'll discuss with the team the possibility of fast-tracking `npm@3.5.0` to `latest`, but I'm reluctant to do that because I want to be confident that the fix to #10482 is sound.

The safest thing to do would be to just use the npm bundled with the CI environment's Node, unless you specifically need `npm@3` features (or to publish); second-safest thing to do would be to switch to `npm@next` – but just for the next week.

**Comment by mzgol** [comment] 2015-11-20 17:37
TBH I'd wait with PR-ing npm 3.5.0 to Node until #10489 is fixed, lots of
bogus warnings don't inspire confidence. I've just tried 3.5.0 and that's
the first thing I've noticed while installing packages.

**Comment by othiym23** [comment] 2015-11-20 17:51
@mzgol Given the team's switch of emphasis to [working on npm's test suite](https://github.com/npm/npm/blob/master/CHANGELOG.md#a-brief-note-on-npms-backwards-compatibility), it might be next year before #10489 is fixed, and I'm not sure it's in the best interests of the user community to wait that long to ship a new version of npm. That said, if somebody wanted to send us a patch that fixes the issue (which should be relatively straightforward), we could get that merged and released fairly quickly.

**Comment by eins78** [comment] 2015-11-20 17:51
@othiym23 Thanks for the clarification, I'll take the chance to update our scripts to make the npm-version configurable and the upgrade. I agree with @mzgol that there shouldn't be any rush getting a new `next` out.

**Comment by othiym23** [comment] 2015-11-20 19:57
We've tested this, and `npm@3.4.1` can update to `npm@3.5.0` just fine, so this problem will actually magically take care of itself as soon as `npm@latest` is no longer `npm@3.4.1`. Retitled to reflect this.

**Comment by kubawalinski** [comment] 2015-11-20 20:47
@othiym23 I think you are underestimating the gravity of this issue. On my CI server I am unable to execute any action with npm, not even `npm -v`. All attempts end with the error message `Cannot find module 'npm-registry-client'`. The suggested workaround of running `npm install -g npm@next` results in the same error.

**Comment by eins78** [comment] 2015-11-20 20:55
@kubawalinski The suggested fix is to re-install nodejs (`apt-get install --reinstall nodejs`), then avoiding upgrading to the naughty version.

**Comment by stefanpenner** [comment] 2015-11-20 21:08
@othiym23 you will be happy to know, we have dropped bundling entirely (because the v3 dedupe was causing issues for some of our users) but all appears well without bundling. :)

**Comment by othiym23** [comment] 2015-11-20 21:47
@stefanpenner I'm going to focus on the positive here:
> all appears well without bundling. :)

:tada:

**Comment by othiym23** [comment] 2015-11-20 21:50
@kubawalinski 
> I think you are underestimating the gravity of this issue.

To be clear, I think this is a grave issue, it's just one that's difficult to remedy without potentially causing other serious (and unknown) problems. The change that @iarna made in `npm@3.5.0` looks good, but it needs time and testing in the real world to assure everyone that it introduces no new regressions, and `npm@3.4.0` and `npm@3.4.1` contain fixes to other serious issues. I posted the comment before yours to assure everyone that the current breakage is transient, not to diminish the severity of the issue.

**Comment by kubawalinski** [comment] 2015-11-20 21:56
@othiym23 Ok, fair enough. I just meant to indicate that it is not possible to update from 3.4.1 to 3.5.0 (at least it was not possible in my situation).

I can now happily report that I reinstalled node, updated npm to 3.4.0 and all is well :)

**Comment by stefanpenner** [comment] 2015-11-20 22:09
> @stefanpenner I'm going to focus on the positive here:
> 
> all appears well without bundling. :)

@othiym23 yup, this is the important part. :tada:

**Comment by othiym23** [comment] 2015-11-20 22:10
@kubawalinski 
To clarify: If you upgrade to `npm@3.4.1`, and then do _not_ run `npm install -g npm` for the next week, you'll be able to upgrade to `npm@latest` once it points at `npm@3.5.0` (next Wednesday, since Thursday's a holiday in the US). Once it's broken it stays broken, but otherwise you can safely upgrade out of `npm@3.4.1` to `npm@3.5.0` (because of [this change](https://github.com/npm/npm-registry-client/commit/2b5a60727f99a9941951d205c47db47abf1ef2b2) I made to one of npm's dependencies that is bundled into `npm@3.5.0`'s tree).

**Comment by neraliu** [comment] 2015-11-21 07:23
it is too late for me to find out this thread, let me wait for the fix :(

**Comment by baslr** [comment] 2015-11-24 14:32
`curl https://www.npmjs.com/install.sh | sh` doesnt work ether. (node v5.1.0)

```
curl https://www.npmjs.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6263  100  6263    0     0  10041      0 --:--:-- --:--:-- --:--:-- 10036
tar=/bin/tar
version:
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: http://registry.npmjs.org/npm/-/npm-3.4.1.tgz
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib
└─┬ npm@3.4.1
...
  ├─┬ npm-registry-client@7.0.7
  │ ├─┬ concat-stream@1.5.0
  │ │ └─┬ readable-stream@2.0.2
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ └─┬ npmlog@2.0.0
  │   ├── ansi@0.3.0
  │   ├─┬ are-we-there-yet@1.0.4
  │   │ ├── delegates@0.1.0
  │   │ └─┬ readable-stream@1.1.13
  │   │   ├── core-util-is@1.0.2
  │   │   ├── isarray@0.0.1
  │   │   └── string_decoder@0.10.31
  │   └─┬ gauge@1.2.2
  │     ├─┬ lodash.pad@3.1.1
  │     │ ├── lodash._basetostring@3.0.1
  │     │ └─┬ lodash._createpadding@3.6.1
  │     │   └── lodash.repeat@3.0.1
  │     ├── lodash.padleft@3.1.1
  │     └── lodash.padright@3.1.1
  ...

It worked
root@host:~/node/out/Release# npm
module.js:340
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by JustinVerLocal** [comment] 2015-11-25 03:32
@othiym23 what time tomorrow will it be safe to run "npm install -g npm"

**Comment by othiym23** [comment] 2015-11-25 03:34
As early as I can get the release done, so likely mid-afternoon PST.

**Comment by stefanpenner** [comment] 2015-11-25 04:56
@othiym23 good luck with the release :)

**Comment by eatgrass** [comment] 2015-11-25 05:38
@othiym23 good luck, looking forward 3.5

**Comment by evereq** [comment] 2015-11-25 14:40
Just hit it now... (with `npm install npm -g`)

On Windows, simple reinstall (update) of Node did not help me (i.e. after reinstall I got same issue with non working npm)

So I remove `C:\Program Files (x86)\nodejs\node_modules\npm` and `C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm` folders and repair NodeJS again (run installation and select Repair). This time it helps as NPM was reinstalled completely from the bundled version (Node@5.1.0 have npm@3.3.12).

Next as many other suggests, I run `npm install npm@next -g` and end up with working npm@3.5.0 :)

**Comment by jasonhodges** [comment] 2015-11-25 15:46
I too was without npm this morning after some work but following the steps @evereq laid out got me back in working order with Node v5.1.0 and npm v3.5.0

**Comment by kagha** [comment] 2015-11-25 16:35
I have encountered this issue as well. Please let me know if any debugging info is required.

**Comment by 3pepe3** [comment] 2015-11-25 17:36
# nodejs -v
v5.1.0
#  npm -v

module.js:333
    throw err;
          ^
Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)

**Comment by othiym23** [comment] 2015-11-26 00:24
`npm@3.5.0` is now the version pointed to by `latest`, so after you clean things up (one more time?) this error should not recur. My sincere apologies to everyone bitten by this situation.

You may still want to upgrade to `npm@next` instead of `latest`, if only because `npm@3.5.0` still has some spurious warnings about replacing `bundleDependencies`. See [the release notes for `npm@3.5.1`](https://github.com/npm/npm/releases/tag/v3.5.1) for details.

**Comment by SerbanC** [comment] 2015-11-26 15:22
I had node installed through Homebrew so I tried `brew reinstall node` and it restored npm to 3.3.12 (without wiping my global npm packages), after which `npm i -g npm@latest` worked fine, I am now on node 5.1.0 / npm 3.5.0

**Comment by kagha** [comment] 2015-11-26 16:30
I use nvm no manage my node installation. I had to completely remove my tns, node/npm and nvm environments in that order to get things working again and reinstall latest. I also had to install cocoapods to get rid of a tns installation bug in 1.5.

I now have a tns 1.5, node 5.1.0, npm 3.5.0 and nvm 0.29 running on my machine.

**Comment by solocshaw** [comment] 2016-12-04 18:27
@SerbanC this worked for me. Thanks.

![screen shot 2016-12-04 at 12 23 22 pm](https://cloud.githubusercontent.com/assets/4841820/20868260/e30f5cd8-ba1c-11e6-90a6-89a01ec5293b.png)
