### ISSUE TITLE
`npm unlink` won't remove global links because gentlyRm takes its job very seriously

### ISSUE THREAD

**Issue by othiym23** [npm/npm#9980] opened 2015-10-15 01:24 UTC
Only affects `npm@3`, with the following output:

```
npm ERR! gentlyRm containing path /usr/local/lib/node_modules/npm isn't under npm's control
npm WARN install:npm Refusing to delete: /usr/local/bin/npm not in /usr/local/lib/node_modules/npm
npm verb install:npm Error: Refusing to delete: /usr/local/bin/npm not in /usr/local/lib/node_modules/npm
```

Repro case is to run `make link` from a checkout of the npm repository, and then run `npm unlink` (with no arguments) afterwards.

**Comment by denysdovhan** [comment] 2015-10-21 11:49
I have the same problem.

**Comment by jasonkarns** [comment] 2015-10-21 14:54
dupe of #9680 ?

**Comment by denysdovhan** [comment] 2015-10-21 15:02
Looks like it is the same

**Comment by iarna** [comment] 2015-10-30 18:36
I didn't get time to get this in for 3.3.10, so I'm pushing this to next week.

**Comment by denysdovhan** [comment] 2015-10-30 20:59
No problem. I'm just still use Unix `rm` for unlinking.

**Comment by iarna** [comment] 2015-11-06 05:41
This was pushed out One More Week, because while I have a PR available, we would like to take the opportunity to write some unit tests for it, now that it's been rewritten to be unit-testable.

**Comment by denysdovhan** [comment] 2015-11-06 07:55
Okay, not problem.

**Closed** 2015-11-12 23:01 UTC
Labels: big-bug, bug

**Comment by vproman** [comment] 2015-11-19 19:52
v3.4.1 fixes this issue (per #10270) if `npm install -g npm` doesn't get you 3.4.1+ because it's not yet in the repo, do `npm install -g npm@v3.4.1`.
