### ISSUE TITLE
After creating project using yoaman , create simple controller to check but getting error app is not defined

### ISSUE THREAD

**Issue by karanbisht** [npm/npm#10467] opened 2015-11-19 02:56 UTC
controller in controll.js ---
app.controller('loginCtrl',[function(){
	console.log('Inside Login Module');
	var login = this;
}]); 

Error in browser console ----
Uncaught ReferenceError: app is not defined(anonymous function) @ loginctrl.js:2
angular.js:12477 Error: [ng:areq] Argument 'loginCtrl' is not a function, got undefined
http://errors.angularjs.org/1.4.7/ng/areq?p0=loginCtrl&p1=not%20aNaNunction%2C%20got%20undefined
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at assertArg (http://localhost:9000/bower_components/angular/angular.js:1796:11)
    at assertArgFn (http://localhost:9000/bower_components/angular/angular.js:1806:3)
    at http://localhost:9000/bower_components/angular/angular.js:9112:9
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:4018:28
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8789:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8289:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7680:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:7555:30)
    at updateView (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:3959:23)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246invokeLinkFn @ angular.js:8791nodeLinkFn @ angular.js:8289compositeLinkFn @ angular.js:7680publicLinkFn @ angular.js:7555updateView @ angular-ui-router.js:3959(anonymous function) @ angular-ui-router.js:3921Scope.$broadcast @ angular.js:16311$state.transition.resolved.then.$state.transition @ angular-ui-router.js:3311processQueue @ angular.js:14745(anonymous function) @ angular.js:14761Scope.$eval @ angular.js:15989Scope.$digest @ angular.js:15800Scope.$apply @ angular.js:16097done @ angular.js:10546completeRequest @ angular.js:10744requestLoaded @ angular.js:10685
17livereload.js?snipver=1:191 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by emkay** [comment] 2015-11-19 04:09
Just looking at this snippet it doesn't seem like an npm error. Do you happen to have a npm-debug.log file in that folder? Do you have a `package.json` file and did you run an `npm` command? It also looks like some bower_components were installed. Maybe all the dependencies are not there. Are you following these instructions https://github.com/yeoman/generator-angular#usage?

**Comment by karanbisht** [comment] 2015-11-20 07:47
Hi emjay , 
Yes , i have npm-debug.log , package.json and also run npm.
I am new to node  , i like to tell you real scenario , previously about a month ago , i created project using yoaman which work perfect as expected but few days back i again created new project using yoaman where i'm getting this error.
while still my old project works fine.This might be some updated versions which i'm not getting it.I also try to create new project on another system and getting same error.

**Comment by emkay** [comment] 2015-11-20 13:28
Hi @karanbisht 

can you please post your `npm-debug.log`? Then we might be able to see if there was anything npm related that broke installing.

From what you pasted above there are a couple things I can see that are having problems. 
`Uncaught ReferenceError: app is not defined(anonymous function) @ loginctrl.js:2` and 
`WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED` 

The first is saying that `app` isn't around. This could be for various reasons. Could you paste the code where `app` is defined? The second seems like whatever is supposed to start listening on that websocket isn't starting. It might be that a watch command wasn't run, but it's also hard to tell without knowing what commands you are running.

It would also be good to know what yeoman generator you are running.

**Comment by busches** [comment] 2016-09-18 23:56
@kenany this isn't a problem with npm and the issue is inactive

**Comment by KenanY** [comment] 2016-09-19 04:34
Closing as abandoned.

**Closed by KenanY** 2016-09-19 04:34 UTC
