### ISSUE TITLE
invalid config key requested

### ISSUE THREAD

**Issue by bernal-dev** [npm/npm#20424] opened 2018-04-24 19:15 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
 The issue is related to the latest npm v6.0.0. The error I am getting is " invalid config key requested" which I think npm is randomly failing when fetching the package data from the server. I said randomly failing because it does it at different times and while trying with different packages. I went back and installed latest npm v5 and everything is working nicely.

#### How can the CLI team reproduce the problem?
 I think you might be able to replicate the problem if you tried to do npm i in a big project (a lot of package dependencies).

### supporting information:

 - `npm -v` prints: v6.0.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 64-bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dryganets** [comment] 2018-05-09 18:09
Have the same, though it happens only in case package-lock is enabled.
```
17:46:42,504 ERROR - [exec] Unhandled rejection Error: invalid config key requested: single
17:46:42,504 INFO  - [exec] at pudGet (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/figgy-pudding/index.js:31:11)
17:46:42,504 INFO  - [exec] at FiggyPudding.get (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/figgy-pudding/index.js:13:12)
17:46:42,504 INFO  - [exec] at Object.get (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/figgy-pudding/index.js:71:16)
17:46:42,504 INFO  - [exec] at _parse (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/ssri/index.js:138:11)
17:46:42,504 INFO  - [exec] at parse (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/ssri/index.js:125:12)
17:46:42,504 INFO  - [exec] at Object.checkData (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/ssri/index.js:216:9)
17:46:42,504 INFO  - [exec] at write (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/cacache/lib/content/write.js:34:31)
17:46:42,504 INFO  - [exec] at putData (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/cacache/put.js:25:10)
17:46:42,504 INFO  - [exec] at Object.x.put (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/cacache/locales/en.js:28:37)
17:46:42,504 INFO  - [exec] at readFileAsync.then.data (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/pacote/lib/fetchers/file.js:38:28)
17:46:42,504 INFO  - [exec] at tryCatcher (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17:46:42,504 INFO  - [exec] at Promise._settlePromiseFromHandler (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
17:46:42,504 INFO  - [exec] at Promise._settlePromise (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
17:46:42,504 INFO  - [exec] at Promise._settlePromise0 (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
17:46:42,504 INFO  - [exec] at Promise._settlePromises (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
17:46:42,504 INFO  - [exec] at Promise._fulfill (/home/builder/buildagent/workspace/366314/clients/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)

```

**Comment by degardinn** [comment] 2018-05-11 19:39
Same thing for me, on a few projects. Also npm 6.0.0, also developing under Windows 10...
Indeed, `package-lock.json` seems to be incriminated, each time when trying to _npm install_ with a `package-lock.json` created with npm 5.

The solution in my case was to remove `package-lock.json` and the `node_modules` directory (removing this directory but not `package-lock.json` is not enough), before running _npm install_.

Don't know to what extent it could be related, but under Windows, I always had troubles with the npm modules directory getting locked either by _Visual Studio Code_ or by _Docker for Windows_ (when it is part of the mounted volume of a container). I always have to close the former or remove the latter for node_modules files to be deletable.

```
web_1  | Executing: npm run-script dev
web_1  |
web_1  | > webapp@2.0.0 dev /srv
web_1  | > npm install && MODE=wds node_modules/.bin/webpack-dev-server --mode development --hot --watch-poll --colors --progress
web_1  |
web_1  | Unhandled rejection Error: invalid config key requested: single
web_1  |     at pudGet (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:31:11)
web_1  |     at FiggyPudding.get (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:13:12)
web_1  |     at Object.get (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:71:16)
web_1  |     at _parse (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:138:12)
web_1  |     at parse (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:125:12)
web_1  |     at Object.checkData (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:216:9)
web_1  |     at write (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:34:31)
web_1  |     at putData (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/put.js:25:10)
web_1  |     at Object.x.put (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/locales/en.js:28:37)
web_1  |     at readFileAsync.then.data (/home/node/.npm/lib/node_modules/npm/node_modules/pacote/lib/fetchers/file.js:38:28)
web_1  |     at tryCatcher (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
web_1  |     at Promise._settlePromiseFromHandler (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
web_1  |     at Promise._settlePromise (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
web_1  |     at Promise._settlePromise0 (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
web_1  |     at Promise._settlePromises (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
web_1  |     at Promise._fulfill (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
web_1  | npm ERR! cb() never called!
web_1  |
web_1  | npm ERR! This is an error with npm itself. Please report this error at:
web_1  | npm ERR!     <https://github.com/npm/npm/issues>
web_1  |
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /home/node/.npm/_logs/2018-05-11T17_12_10_649Z-debug.log
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! webapp@2.0.0 dev: `npm install && MODE=wds node_modules/.bin/webpack-dev-server --mode development --hot --watch-poll --colors --progress`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR!
web_1  | npm ERR! Failed at the webapp@2.0.0 dev script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web_1  |
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /home/node/.npm/_logs/2018-05-11T17_12_10_787Z-debug.log
```

**Comment by edusperoni** [comment] 2018-06-15 12:26
Is there any fix for this? We are all using npm 6 with node 8 and when I commit my package-lock.json on windows, others using Linux/MacOS have to delete it+node_modules and install everything again because it bugs their install, and if they commit on Linux/MacOS, the same bug appears on Windows.

**Comment by degardinn** [comment] 2018-06-15 13:27
From my memory... We had the issue a few times ago, because
- some people were using npm 5 and some others npm 6
- or because tarball packages were associated an absolute path in the "version" string of the lock file (which, naturally, was system specific)
- also, I think we had troubles related to git repo packages

In our case, the workaround is: everybody manipulates npm from a development Docker container.

By the way, removing the lock file is not an option anymore for us: NPM sets the packages version to "^x.x.x" as a default, which stands for "use the latest minor" (whatever the way the version is specified in an NPM install command), but some packages we rely on (Typescript amont others) break the backward compatibility on a minor version change (and we don't have the time to track them all and set their version manually). In other words: removing the package-lock.json file is very dangerous, unless you have set very specific versions for each package.

**Comment by jbcpollak** [comment] 2018-06-20 02:43
I've run into this as well. Are you buy chance using `git+https://` dependency specifications, or another unusual way to reference dependencies?

**Comment by dryganets** [comment] 2018-06-20 09:15
Yes, we are using git+https a lot. Also for some rare cases we consume packages through file://.

**Comment by degardinn** [comment] 2018-06-20 18:52
Same for me. I think the culprits, in my **package.json**, are:

```
"dependencies": {
    "@pivohub/label-to-bottle": "file:src/pivohub-label-to-bottle-0.3.0.tgz",
    "@pivohub/sdk": "file:src/pivohub-sdk-0.2.0.tgz",
```

In **package.lock.json**:
```
"dependencies": {
    "@pivohub/label-to-bottle": {
      "version": "file:src/pivohub-label-to-bottle-0.3.0.tgz",
      "integrity": "sha512-RxsmKpA/f37POKIZtFZyjMAz7+XCaPMPYjjOYbfjNME9CSQWiSCb8K9rmjgp5WEbHXQF+VJV8IEgx8plk2SbrQ=="
    },
    "@pivohub/sdk": {
      "version": "file:src/pivohub-sdk-0.2.0.tgz",
      "integrity": "sha512-ZHOzpHz/cFHYYO+wbraAEbtxuqs/ctv7kIKv0g7QDiW5zioY8UPcNTDwYKOJ+vMC8H5Xj/jnjKvSuJ03YF4pKg==",
      "requires": {
        "@serafin/pipeline": "^0.9.0",
        "axios": "^0.18.0"
      }
    },
```

    "@pivohub/sdk": {
      "version": "file:src/pivohub-sdk-0.2.0.tgz",
      "integrity": "sha512-ZHOzpHz/cFHYYO+wbraAEbtxuqs/ctv7kIKv0g7QDiW5zioY8UPcNTDwYKOJ+vMC8H5Xj/jnjKvSuJ03YF4pKg==",
      "requires": {
        "@serafin/pipeline": "^0.9.0",
        "axios": "^0.18.0"
      }
    },

Returning this error:
```
> npm install

Unhandled rejection Error: invalid config key requested: single
    at pudGet (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:31:11)
    at FiggyPudding.get (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:13:12)
    at Object.get (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:71:16)
    at _parse (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:138:12)
    at parse (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:125:12)
    at Object.checkData (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:216:9)
    at write (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:34:31)
    at putData (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/put.js:25:10)
    at Object.x.put (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/locales/en.js:28:37)
    at readFileAsync.then.data (/home/node/.npm/lib/node_modules/npm/node_modules/pacote/lib/fetchers/file.js:38:28)
    at tryCatcher (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
Unhandled rejection Error: invalid config key requested: single
    at pudGet (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:31:11)
    at FiggyPudding.get (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:13:12)
    at Object.get (/home/node/.npm/lib/node_modules/npm/node_modules/figgy-pudding/index.js:71:16)
    at _parse (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:138:12)
    at parse (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:125:12)
    at Object.checkData (/home/node/.npm/lib/node_modules/npm/node_modules/ssri/index.js:216:9)
    at write (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:34:31)
    at putData (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/put.js:25:10)
    at Object.x.put (/home/node/.npm/lib/node_modules/npm/node_modules/cacache/locales/en.js:28:37)
    at readFileAsync.then.data (/home/node/.npm/lib/node_modules/npm/node_modules/pacote/lib/fetchers/file.js:38:28)
    at tryCatcher (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/node/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2018-06-20T18_23_47_295Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webapp@2.1.2 predev: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webapp@2.1.2 predev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2018-06-20T18_23_47_375Z-debug.log
```

The error is related to **ssri**, a module used to check the file integrity.
I get 2 times this error, and have 2 _file://_ dependencies, I don't think it's a coincidence.

To reproduce the error, I can remove **node_modules**, keep the **package.lock.json** file and run **npm install**.
To work around the error, I can remove both **node_modules** and the **package.lock.json** file and run **npm install**.
Surprisingly, after having removed the **node_modules** and **package.lock.json** file, and reinstalled, the new **package.lock.json** values for the 2 _file://_ dependencies didn't change.

**Comment by jbcpollak** [comment] 2018-06-20 18:55
I made a PR which I believe resolves this: https://github.com/zkat/cacache/pull/136

**Comment by herman-rogers** [comment] 2018-06-21 14:32
Definitely a bug somewhere - I had the same issue. As a work around I just deleted the offending line ("custom-package": "./custom-package.tar.gz"), ran ```npm install```, waited for npm to finish then added back in "custom-package", ran ```npm install```, and it worked.

**Closed as completed** 2018-07-02 18:34 UTC
