### ISSUE TITLE
npm -g update installs non-stable npm

### ISSUE THREAD

**Issue by mzgol** [npm/npm#9924] opened 2015-10-09 15:00 UTC
npm global update installs non-stable npm:
```
$ npm info npm dist-tags
 
{ latest: '3.3.6',
  next: '3.3.7',
  'latest-2': '2.14.7',
  'next-2': '2.14.8',
  'v3.x-latest': '3.3.6',
  '3.x-latest': '3.3.6',
  '3.x-next': '3.3.7',
  'v3.x-next': '3.3.7' }

$ npm -g i npm
/Users/mgol/.nvm/versions/node/v4.1.2/bin/npm -> /Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/bin/npm-cli.js
- add-to-path@1.1.2 node_modules/npm/node_modules/add-to-path
/Users/mgol/.nvm/versions/node/v4.1.2/lib
└── npm@3.3.6 

$ npm --version
3.3.6
$ npm -g update
/Users/mgol/.nvm/versions/node/v4.1.2/bin/npm -> /Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/bin/npm-cli.js
/Users/mgol/.nvm/versions/node/v4.1.2/lib
└── npm@3.3.7 

$ npm --version
3.3.7
```

**Comment by judu** [comment] 2015-10-14 10:05
I totally back this issue, I'm having the same issue and npm does not handle a "update npm@2.14.7". Is there a way to go around that manually?

**Comment by mzgol** [comment] 2015-10-14 11:43
This is what I use if I want `npm@latest` and still update all global packages:
```
# Update npm first to use the latest npm to update the rest.
npm -g install npm

for package in $(npm -g outdated --parseable --depth=0 | cut -d: -f2 | egrep -v "^npm@"); do
	npm -g install "$package"
done
```
This will invoke `npm -g install PACKAGE` for each package that is out of date.

**Comment by othiym23** [comment] 2015-11-06 22:33
You've independently discovered an inconsistency in `npm update`'s logic that was also found in #5024 (which I'm going to close this as a duplicate of) – while the documentation says that `npm update` will update to `latest`, instead it updates to the _newest_ version (i.e. `*`) that matches any applicable semver ranges. Those semver ranges are typically found in `package.json`, which is absent in the global prefix. `npm update -g` should absolutely only update npm to the latest stable version, but ironing out this inconsistency is probably going to be a semver-major change, because it's a subtle but fairly sweeping change to how `npm outdated` and `npm install` work. Thanks for including such a clear description of the bug, @mzgol!

**Closed by othiym23** 2015-11-06 22:33 UTC
