### ISSUE TITLE
NPM Package Cache defaults to the wrong location.

### ISSUE THREAD

**Issue by Grauenwolf** [npm/npm#12218] opened 2016-04-05 21:49 UTC
The NPM package cache is defaulting to C:\Users\USERNAME\AppData\Roaming\npm-cache. This is inappropriate because it will cause the entire package cache to be copied to the domain server and then replicate onto every machine the user logs into. 

This will cause slow logins and logoffs and may cause the user to exceed their quota on the domain server.

Meanwhile, it means two users sharing the same machine can't share the package cache, as one user can't see another user's AppData folder.

****

Machine-wide program data, like package caches, go in `%ProgramData%`, which is normally `C:\ProgramData`.

**Comment by othiym23** [comment] 2016-04-05 21:56
Closing as duplicate of #4564. It would be nice to choose a new default for this that's satisfactory for a broad segment of npm's Windows users, but for completeness's sake I'd like to point out that `APPDATA` / `%AppData%` was chosen by developers from Microsoft in the first place.

**Closed by othiym23** 2016-04-05 21:56 UTC
Labels: feature-request, windows
