### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by xiaomi1120** [npm/npm#9305] opened 2015-08-17 13:54 UTC
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-nodeunit@0.3.3 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.10.0 wants grunt@~0.4.0
npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\jngongzuo\slackend-wei-jail\ui\npm-debug.log
```

**Comment by othiym23** [comment] 2015-08-18 00:05
Closing as a duplicate of #9275.

**Closed by othiym23** 2015-08-18 00:05 UTC
Labels: peerdependencies, support
