### ISSUE TITLE
npm 5 does not preserve range when updates package.json

### ISSUE THREAD

**Issue by Delagen** [npm/npm#16813] opened 2017-05-31 05:12 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
package.json
```
{
"dependencies":{"some-module":"~1.2.3"}
}
```
currently available version 1.3.0 & 1.2.4
when perform `npm update some-module`
npm override version in package.json to `^1.3.0`

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 8.0.0

**Comment by zkat** [comment] 2017-05-31 05:28
Hm. So, npm4 doesn't do this either afaik (nor does any older version). Usually, the way to do this is to set `save-prefix='~'` in your local project's `.npmrc` (or in `~/.npmrc`).

Having npm autodetect this and preserve this sounds like a nice thing to have. I think it's reasonable to take a PR for it 👍  I'll double-check with @iarna who might have more context about the implications, though.

**Comment by delagen** [comment] 2017-05-31 06:05
I understand it. But when doing update it should not change range in package.json

**Comment by AdriVanHoudt** [comment] 2017-05-31 10:05
Had the same issue. (if I understand the original issue correct)

I did 
```diff
-    "hapi": "16.2.x",
+    "hapi": "16.3.x",
```
Run `npm update` and it did
```diff
-    "hapi": "16.3.x",
+    "hapi": "^16.3.0",
```

npm 4 did not do this and this behaviour is not wanted so it is a bug to me!

npm -v: 5.0.0
node -v: 8.0.0

**Comment by zkat** [comment] 2017-05-31 22:49
Fair enough! Thanks for pointing that out, @AdriVanHoudt

**Comment by AdriVanHoudt** [comment] 2017-06-01 05:05
np, point me in the right direction and I might even try to PR :P

**Comment by zkat** [comment] 2017-06-01 05:26
@AdriVanHoudt ...I should probably take off that tag huh. The more I think about it, the more I realize I've *no idea* how npm4 even did this. @iarna might know but I've no clue :s

**Comment by AdriVanHoudt** [comment] 2017-06-01 07:20
I didn't even saw the label haha
I what do you mean by no idea how? npm 4 just did not edit package.json on update (don't know the internals ofc)

**Comment by zkat** [comment] 2017-06-01 23:48
oh I thought you meant that `npm up --save pkg` would magically preserve this.

Ok yeah, this is back to feature request.

This is actually something someone might put up a PR for, here's the summary: add some logic to [the bit in `deps.js` that calculates the version spec to use](https://github.com/npm/npm/blob/latest/lib/install/deps.js#L273-L280) to default to the specific prefix used by that version, _if there was one_. Forget about the `save-exact` case, since it's expected that people _must_ use `save-exact` to get npm to save as a non-range and I don't think we're gonna change this (and if we do, it should be a separate thing with a separate discussion).

Give that a whirl, and if the patch works, put up a PR? 👍

**Comment by AdriVanHoudt** [comment] 2017-06-02 07:26
Just to clarify my issue (let me know if you prefer a separate one)

I have a package.json with
```
"hapi": 16.2.x
```
I run `npm i`
It installed 16.2.0
I update my package.json to 
```
"hapi": 16.3.x
```
I run `npm update`
it installs 16.3.0 (as it should)
it updates my package.json to 
```
"hapi": ^16.3.0
```

Why would it edit the package.json? npm 4 does all the sames things except that :O

**Comment by zkat** [comment] 2017-06-05 17:59
@AdriVanHoudt try `npm update --save` in `npm@4`. That's the difference.

**Comment by AdriVanHoudt** [comment] 2017-06-06 07:35
@zkat :mindblown: 
ok that makes sense. 🙄 I would still prefer if it kept the .x notation, is that possible?

**Comment by zkat** [comment] 2017-06-06 08:33
@AdriVanHoudt as per twitter, if you can figure out a good, clean way to do this and you have well-defined semantics for it, we might take a patch (I haven't checked with @iarna but I defer to her if she'd rather not have this)

**Comment by AdriVanHoudt** [comment] 2017-06-06 10:14
@zkat I think I will switch to just using the default notation, it is more correct and works better with the lockfile imo

**Comment by Maistho** [comment] 2017-06-06 13:45
@zkat Why does `npm update` default to `--save` at all?

I don't really see the point, since I don't need to change my semver ranges except for breaking changes (e.g. `^1.0.0` => `^2.0.0`) and shouldn't those be manual anyways? 😕 

I find the commands in `yarn` to make a lot more sense in comparison:
- `yarn upgrade` will upgrade each package to the latest version specified by `package.json`, without modifing `package.json`
- `yarn upgrade package` will upgrade `package` to `latest`, and save the new version with the default range in `package.json`
- `yarn upgrade package@^2.0.0` will upgrade `package` according to the given semver range, and if needed save the new range in `package.json`

### Example of npm breaking my ranges
I have a package `a` that depends on package `b`.

`b` has three published versions: `1.0.0`, `1.0.1` and `1.1.0`.

For some reason, I do not want to use `b@1.1.0`, so I set my dependencies to `"b": "~1.0.0"`

I run `npm update`, thinking that I will get `b@1.0.1`, which I do. But npm will change my dependencies to `"b": "^1.0.1`.

The next time I run `npm update`, I will get `b@1.1.0`, which is *not* in the original range!

---
It feels like I will have to use `npm update --no-save` all the time, and also instruct everyone on my team to do the same. 😕 Or is there a better solution?

**Comment by zkat** [comment] 2017-06-06 18:16
@Maistho If you want to stick with `~`, I recommend you set it in your _project_ config with `echo 'save-prefix="~"' >> npmrc` (in your project dir). That'll set that to default.

As for everything else? Well, that's the result of setting `--save` as the default across the CLI. This is the behavior as it's always been if you'd set `--save`.

`update` is a command we've been intending to overhaul, and we know it's something where the warts start getting more obvious as soon as you start saving. I wish we'd had time to actually redesign it by the time npm5 came out, but we really just didn't have the bandwidth for it, and it seemed better to just get something out there asap and then do a proper redesign. The same goes for `npm outdated`, which is right now tied up directly with update.

The stuff you're saying is super useful and sounds like a really good direction to take the command in. It's good to hear about the different expectations people have of this so we can make sure to write the thing people want this to be.

If you care enough for it, it'd be great to get a more complete RFC filed that describes the `update` that you wish we had and that outlines your needs from it. If that sounds like too much, just hang tight -- we'll be getting to it soon. 👍 

Thanks y'all for your commentary, and for your understanding!

**Comment by Maistho** [comment] 2017-06-07 14:25
@zkat Thanks for the detailed response :smile: 

Setting the save-prefix will instead change all `^` prefixes into `~`, which will just replace my problem with a different one (since I want to mix caret and tilde ranges).

I'd the more than happy to write an RFC concerning `update`, but I'm not sure how I would go about it. Do you have any example/guide on how it should be structured?

**Comment by broofa** [comment] 2017-06-26 14:13
Landed here after noticing npm changing my package.json in ways similar to the above. In my case, `npm update some_module` changed the package declaration from `some_module: ^0.1.6` to `some_module: 0.1.8` (dropping the caret specifier).  As it turns out this was because I'd added `save-prefix=` to `~/.npmrc`.

This behavior feels pretty broken to me.  I added the caret to this particular module as a way of saying, "take minor updates".  In removing it, NPM effectively reversed that decision, which is categorically wrong.

I believe the problem here is that the`save-prefix` option is given precedence over what is in `package.json`.  Instead,  `save-prefix` should only apply when installing a new module.  For existing modules, the range specifier should not be altered.

Also, given that `package-lock.json` is now a thing, I can see a case for saying `npm update` shouldn't touch `package.json` at all.  (But I'm still trying to understand how package.json and package-lock.json interact, so not gonna get on a soap box about that.)

**Comment by AdriVanHoudt** [comment] 2017-06-26 14:50
touching package.json only makes sense on update if you go from `x: ^0.1.6` to `x: ^0.1.8` since then you say `0.1.8` is the new lowest version. In all other cases it feels weird and counter intuitive that update touches package.json. Since you want it to get your modules up to date that is all.
I think an upgrade command which does this (and preserves the notation in package.json) makes more sense.

**Comment by Hirse** [comment] 2017-07-18 12:46
Usually my dependency versions are carefully crafted, so I don't really see a use case for `npm update` or `npm update --save` ever, except if you don't care about versions at all.

Is there a shorter alias of `npm update --no-save` or any way I can reset the previous update behaviour?

Btw, the [update docs](https://docs.npmjs.com/cli/update) currently don't mention the npm@5 behavior.

**Comment by mlc-mlapis** [comment] 2017-08-24 20:33
I think that the changed behavior of NPM is really very dangerous. We very carefully monitor which module is being changed and we always use exact versioning for all modules. The fact that now `npm update` is changing `package.json` is totally a breaking change. It is absolutely unclear why this change was done. No docs, no arguments, ... nothing. 😟

**Comment by Stexxen** [comment] 2017-10-13 14:06
The use of Tilde is even in the docs. 

https://docs.npmjs.com/cli/update#tilde-dependencies

IMO this is a bug, not a feature-request...

**Comment by zkat** [comment] 2017-10-13 16:25
> it'd be great to get a more complete RFC filed that describes the update that you wish we had and that outlines your needs from it.
(from https://github.com/npm/npm/issues/16813#issuecomment-306572698)

This is the important bit preventing this from moving forward. This is one of those things where a number of good behaviors are mixing in unexpected ways.

**Comment by Stexxen** [comment] 2017-10-16 09:49
Sorry, but I don't understand the need for an RFC?
The docs state tilde does a quite specific thing, and now it doesn't do that. 
![image](https://user-images.githubusercontent.com/4494301/31605900-7ab42204-b25f-11e7-9943-314684c1c2a9.png)

The docs aren't version specific; should they be?

**Comment by willbattel** [comment] 2018-03-17 22:33
This is still a relatively major issue, but it seems the trail has gone cold for quite a few months. We want to keep very close tabs on our dependencies, where we mostly use tildes but not for everything. Every time we update, NPM is adding an unnecessary chance for human error should the developer forget to correct the change made to `package.json` before committing the changes. Sometimes it adds carats, sometimes it removes the prefix entirely. Why hasn't this gotten more attention?

`npm -v 5.7.1`

**Comment by Fotiman** [comment] 2018-05-30 21:36
This was opened 1 year ago tomorrow.  How can we get some traction on this?
First, I think the "feature-request" label needs to be removed and replaced with a "bug" label.  This is not a feature request.  This is npm update behaving in a way that produces unexpected and dangerous results.

**Comment by Fotiman** [comment] 2018-05-30 21:51
@zkat It looks like you removed the Bug label originally. Can you add it back?

**Comment by bjouhier** [comment] 2018-07-08 12:51
This is a serious bug. `npm update` must preserve the semantics of the ranges when it updates `package.json`.
It is ok to update:
* `~1.2.3` -> `~1.2.8` 
* `^1.2.3` -> `^1.4.0`

But it is **not ok** to replace `~` by `^`.

**Comment by bjouhier** [comment] 2018-07-08 16:46
Or maybe update should have strong/weak options. Strong option would update all dependencies to latest and save them with carets in package.json. Weak option would only update to the latest on the existing ranges (and preserve existing tildes).

**Comment by bjouhier** [comment] 2018-07-08 17:14
Just discovered `npx npm-check -u` and `npm-merge-driver`. Looks this is not such a major issue because there are better ways to update.

**Comment by DanielRuf** [comment] 2018-07-08 20:06
> But it is not ok to replace ~ by ^.

Ouch, saw the same in a few of our projects. This is really bad and a regression.

**Comment by DanielRuf** [comment] 2018-07-08 20:07
This is why we will move to yarn and pnpm.

**Comment by zkat** [comment] 2018-07-08 20:11
This is not a regression. This is the behavior npm has always had when it comes to this. The change is that it's more notable due to auto save.

**Comment by zkat** [comment] 2018-07-08 20:17
I've locked this thread to make it clear that this is no longer the place to have feature request discussions. This is not a bug.

If anyone cares enough to see this behavior changed, please [file a formal RFC](https://github.com/npm/rfcs) with more details around expected behavior. We no longer have the time or bandwidth to discuss more informal, off-the-cuff ideas.

Furthermore, if what you want to do is discuss ideas more openly without a formal proposal, with the understanding that the npm team won't really engage with you about it, you can also post in the [ideas category in npm.community](https://npm.community/c/ideas), which is a great place to brainstorm before filing an RFC.

**Closed by zkat** 2018-07-08 20:17 UTC
Labels: feature-request, npm5, patch-welcome
