### ISSUE TITLE
iCOnic not installing on mac

### ISSUE THREAD

**Issue by VINUOJHA** [npm/npm#15439] opened 2017-01-10 13:59 UTC
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.3.3: use uuid module instead
npm ERR! unpack Could not read data for @ionic/app-generators@0.0.3
/usr/local/lib
└── cordova@6.4.0 

npm WARN In ionic@2.1.18 replacing bundled version of cross-spawn with cross-spawn@4.0.2
npm WARN In ionic@2.1.18 replacing bundled version of mime-types with mime-types@2.0.14
npm WARN In ionic@2.1.18 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.18 replacing bundled version of form-data with form-data@0.2.0
npm WARN In ionic@2.1.18 replacing bundled version of request with request@2.51.0
npm WARN In ionic@2.1.18 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.9
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic" "cordova"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/test/npm-debug.log

**Comment by legodude17** [comment] 2017-01-10 21:11
Duplicate of #14563.

**Comment by KenanY** [comment] 2017-01-18 17:27
Closing as a duplicate.

**Closed by KenanY** 2017-01-18 17:27 UTC
