### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames when fetching from registry.npmjs.org

### ISSUE THREAD

**Issue by kpalmvik** [npm/npm#8249] opened 2015-05-13 09:19 UTC
Since a few hours, our build servers as well as my local dev environment is getting the following error when running npm install --loglevel verbose:

```
npm info using npm@2.9.1
npm info using node@v0.12.2
...
npm info retry will retry, error on last attempt : error : Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.ssl.fastly.net, DNS:*.a.ssl.fastly.net, DNS:fast.wistia.com, DNS:purge.fastly.net, DNS:mirrors.fastly.net, DNS:*.parsecdn.com, DNS:*.fastssl.net, DNS:voxer.com, DNS:www.voxer.com, DNS:*.firebase.com, DNS:sites.yammer.com, DNS:sites.staging.yammer.com, DNS:*.skimlinks.com, DNS:*.skimresources.com, DNS:cdn.thinglink.me, DNS:*.fitbit.com, DNS:*.hosts.fastly.net, DNS:control.fastly.net, DNS:*.wikia-inc.com, DNS:*.perfectaudience.com, DNS:*.wikia.com, DNS:f.cloud.github.com, DNS:*.digitalscirocco.net, DNS:*.etsy.com, DNS:*.etsystatic.com, DNS:*.addthis.com, DNS:*.addthiscdn.com, DNS:fast.wistia.net, DNS:raw.github.com, DNS:www.userfox.com, DNS:*.assets-yammer.com, DNS:*.staging.assets-yammer.com, DNS:assets.huggies-cdn.net, DNS:api.kinja.com, DNS:orbit.shazamid.com, DNS:about.jstor.org, DNS:*.global.ssl.fastly.net, DNS:web.voxer.com, DNS:pypi.python.org, DNS:*.12wbt.com, DNS:www.holderdeord.no, DNS:secured.indn.infolinks.com, DNS:play.vidyard.com, DNS:play-staging.vidyard.com, DNS:secure.img.wfrcdn.com, DNS:secure.img.josscdn.com, DNS:*.gocardless.com, DNS:widgets.pinterest.com, DNS:*.7digital.com, DNS:*.7static.com, DNS:p.datadoghq.com, DNS:*.plan3.se, DNS:new.mulberry.com, DNS:www.safariflow.com, DNS:cdn.contentful.com, DNS:tools.fastly.net, DNS:*.huevosbuenos.com, DNS:*.goodeggs.com, DNS:*.fastly.picmonkey.com, DNS:*.cdn.whipplehill.net, DNS:*.whipplehill.net, DNS:cdn.media34.whipplehill.net, DNS:cdn.media56.whipplehill.net, DNS:cdn.media78.whipplehill.net, DNS:cdn.media910.whipplehill.net, DNS:*.modcloth.com, DNS:*.disquscdn.com, DNS:*.jstor.org, DNS:*.dreamhost.com, DNS:www.flinto.com, DNS:*.chartbeat.com, DNS:*.hipmunk.com, DNS:content.beaverbrooks.co.uk, DNS:secure.common.csnstores.com, DNS:*.vsco.co, DNS:www.joinos.com, DNS:staging-mobile-collector.newrelic.com, DNS:*.modcloth.net, DNS:*.foursquare.com, DNS:*.shazam.com, DNS:*.4sqi.net, DNS:*.metacpan.org, DNS:*.fastly.com, DNS:wikia.com, DNS:fastly.com, DNS:kinja.com, DNS:*.gadventures.com, DNS:www.gadventures.com.au, DNS:www.gadventures.co.uk, DNS:kredo.com, DNS:cdn-tags.brainient.com, DNS:my.billspringapp.com, DNS:rvm.io"
```

So far I have been unable to reproduce the certificate problem in a browser.

The other day we were also heavily affected by http://status.npmjs.org/incidents/bbd998rhfbfm, but it is not clear that this is related in any way.

**Comment by kpalmvik** [comment] 2015-05-13 11:44
After contacting the npmjs hosting provider Fastly, I was given the following information from their support:

>We narrowed down the issue to a single cache node in Frankfurt that was misbehaving.
>It's taken out of service, and we're investigating the root cause of this.

Installing from npm is now working in all our environments again.

**Comment by othiym23** [comment] 2015-05-13 16:33
I'm glad you and Fastly were able to work this out while the npm team was asleep! :tada: Thank you for bringing this to our attention, and for letting us know that the problem has been addressed. Closing as resolved!

**Closed by othiym23** 2015-05-13 16:33 UTC
Labels: bug, registry

**Comment by seldo** [comment] 2015-05-13 23:24
I requested follow-up from Fastly on root cause and steps they were taking to avoid in future, got this: 

> it looks like there was a race condition after the host was rebooted for a kernel upgrade. This caused a problem with a program we use to associate SSL certs with their services.
> We have identified the race condition and have added monitoring around rebooting caches to reduce our response time to fix problems like this.
