### ISSUE TITLE
deprecate: invalid version range "latest"

### ISSUE THREAD

**Issue by isaacs** [npm/npm#12163] opened 2016-03-31 23:41 UTC
When deprecating a package, it should deprecate all versions if no version specifier is provided.  It looks like not getting a version range, it's defaulting to "latest" instead.

```
$ npm deprecate asset_builder "this package is abandoned. Contact <support@npmjs.com> to use the name." -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'deprecate',
npm verb cli   'asset_builder',
npm verb cli   'this package is abandoned. Contact <support@npmjs.com> to use the name.',
npm verb cli   '-ddd' ]
npm info using npm@3.8.5
npm info using node@v5.6.0
npm sill mapToRegistry name asset_builder
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'asset_builder',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   name: 'asset_builder',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/asset_builder
npm verb stack Error: invalid version range: latest
npm verb stack     at CachingRegistryClient.deprecate (/Users/isaacs/dev/npm/npm/node_modules/npm-registry-client/lib/deprecate.js:23:15)
npm verb stack     at /Users/isaacs/dev/npm/npm/lib/deprecate.js:48:18
npm verb stack     at mapToRegistry (/Users/isaacs/dev/npm/npm/lib/utils/map-to-registry.js:62:3)
npm verb stack     at EventEmitter.deprecate (/Users/isaacs/dev/npm/npm/lib/deprecate.js:40:3)
npm verb stack     at Object.commandCache.(anonymous function) (/Users/isaacs/dev/npm/npm/lib/npm.js:114:13)
npm verb stack     at EventEmitter.<anonymous> (/Users/isaacs/dev/npm/npm/bin/npm-cli.js:74:30)
npm verb stack     at nextTickCallbackWith0Args (node.js:453:9)
npm verb stack     at process._tickCallback (node.js:382:13)
npm verb cwd /Users/isaacs/dev/npm/npm
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "asset_builder" "this package is abandoned. Contact <support@npmjs.com> to use the name." "-ddd"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.5

npm ERR! invalid version range: latest
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/isaacs/dev/npm/npm/npm-debug.log
```

Using `$pkg@"*"` works fine, though.

**Comment by KenanY** [comment] 2016-04-01 13:30
Might be a duplicate of https://github.com/npm/npm/issues/10974.

**Comment by othiym23** [comment] 2016-04-12 04:50
Agreed, @KenanY. @isaacs, give this a shot with `npm@next` and see if it's still around? Lemme know or reopen #10974 if it's not fixed. Thanks!

**Closed by othiym23** 2016-04-12 04:50 UTC
Labels: bug
