### ISSUE TITLE
error installing cordova and ionic on windows 7

### ISSUE THREAD

**Issue by joelmm1** [npm/npm#11156] opened 2016-01-15 11:49 UTC
```
npm@2.14.12 C:\Program Files (x86)\nodejs\node_modules\npm

C:\Users\Joel>npm -g install cordova
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x8
6)\nodejs\node_modules\npm\bin\npm-cli.js" "-g" "install" "cordova"
npm ERR! node v4.2.4
npm ERR! npm v2.14.12

npm ERR! Unexpected token R
npm ERR!
npm ERR! Raw HTTP Request received by this server:
npm ERR!
npm ERR! GET http://registry.npmjs.org/cordova HTTP/1.1
npm ERR! accept-encoding: gzip
npm ERR! version: 2.14.12
npm ERR! accept: application/json
npm ERR! referer: install cordova
npm ERR! npm-session: ccd96adc73cbfd9c
npm ERR! user-agent: npm/2.14.12 node/v4.2.4 win32 ia32
npm ERR! host: registry.npmjs.org
npm ERR! Connection: keep-alive
npm ERR!
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Joel\npm-debug.log

C:\Users\Joel>
```
Please advice

**Comment by KenanY** [comment] 2016-01-15 15:05
This looks like a duplicate of https://github.com/npm/npm/issues/9541, by the same user.

**Comment by othiym23** [comment] 2016-01-15 17:30
It certainly seems to be. Closing as duplicate / weighing in on #9541. Thanks, @KenanY!

**Closed by othiym23** 2016-01-15 17:30 UTC
Labels: support
