### ISSUE TITLE
Uninstall refusing to delete .bin files - npm 3.3.0

### ISSUE THREAD

**Issue by bdukes** [npm/npm#9394] opened 2015-08-24 15:19 UTC
Using npm 3.3.0, I get an error trying to uninstall the module _nativefier_:
 > Refusing to delete: C:\Code\npm-uninstall-test\node_modules\.bin\nativefier.cmd not in C:\Code\npm-uninstall-test\node_modules\nativefier

I was able to uninstall a different package.  I do not get the error in npm 2.14.0.  I'm running Windows 10.

[See silly log output](http://pastebin.com/raw.php?i=pg07sg8w)

**Comment by othiym23** [comment] 2015-08-24 20:24
```
npm ERR! gentlyRm C:\Code\npm-uninstall-test\node_modules\.bin\nativefier.cmd is outside C:\Code\npm-uninstall-test\node_modules\nativefier and not a link
```

Whoops! Looks like our deletion code needs to be made aware that `cmd` shims are a thing, @iarna. :sob: 

Thanks for the report, @bdukes, and we'll try to get this fixed soon!

**Comment by iarna** [comment] 2015-08-24 20:27
That was surely caused by https://github.com/npm/npm/pull/9198

**Comment by robertbaker** [comment] 2015-08-25 18:58
@iarna please fix this and release https://github.com/npm/npm/issues/9095 asap. It's really annoying

**Comment by amyspark** [comment] 2015-09-05 02:10
Using npm 3.3.2, this bug is still present.
`node install gulp-sass@"~2.0.4" --save`
```
npm ERR! Refusing to delete: d:\Documents\Amyspark\TheSilvermoonSentinelFrontend\node_modules\node-sass\node_modules\.bin\supports-color.cmd not in d:\Documents\Amyspark\TheSilvermoonSentinelFrontend\node_modules\node-sass\node_modules\supports-color
File exists: d:\Documents\Amyspark\TheSilvermoonSentinelFrontend\node_modules\node-sass\node_modules\.bin\supports-color.cmd
Move it away, and try again.
```

**Comment by iarna** [comment] 2015-09-11 22:19
Good news, this should be fixed as of 3.3.3!

**Closed by iarna** 2015-09-11 22:19 UTC
Labels: blocker, bug, windows

**Comment by vjpr** [comment] 2015-10-19 21:12
I'm having this same issue with npm 2.14.8.

I use `npm link ~/dev/gulp` then I get:

```
npm ERR! Refusing to delete: ~/dev/gulp4/node_modules/.bin/gulp not in ~/dev-live/foo
File exists: ~/dev/gulp4/node_modules/.bin/gulp
Move it away, and try again. 
npm ERR! gentlyRm ~/dev/gulp4/node_modules/gulp-cli/bin/gulp.js symlink target ~/dev/gulp4/node_modules/.bin/gulp is not controlled by npm ~/dev-live/foo
npm ERR! error rolling back Error: Refusing to delete: ~/dev/gulp4/node_modules/.bin/gulp not in ~/dev-live/foo
npm ERR! error rolling back     at clobberFail (/usr/local/lib/node_modules/npm/lib/utils/gently-rm.js:193:12)
npm ERR! error rolling back     at /usr/local/lib/node_modules/npm/lib/utils/gently-rm.js:132:18
npm ERR! error rolling back     at FSReqWrap.oncomplete (fs.js:95:15)
npm ERR! error rolling back  { [Error: Refusing to delete: ~/dev/gulp4/node_modules/.bin/gulp not in ~/dev-live/foo]
npm ERR! error rolling back   code: 'EEXIST',
npm ERR! error rolling back   path: '~/dev/gulp4/node_modules/.bin/gulp' }
```

Any module which has gulp fails

**Comment by othiym23** [comment] 2015-10-21 04:55
@vjpr The way `npm link <package>` is supposed to work is to install a package on which `npm link` has previously been run, because what `npm link <package>` does is make a symbolic link from your global install location into the current package. It's not surprising (to me, at least) that npm has logic to handle this case, but it's also not surprising to me that this has some surprising behavior. What you're seeing is probably a bug, but it's not related to this issue, so if you'd like to see it addressed, please open a new issue.
