### ISSUE TITLE
`npm view <package-with-one-version> versions` output incorrect

### ISSUE THREAD

**Issue by davidchambers** [npm/npm#8527] opened 2015-06-10 20:57 UTC
The behaviour is inconsistent for packages with one version:

```console
$ npm view <package-with-multiple-versions> versions

[ '1.0.0',
  '1.0.1' ]

$ npm view <package-with-one-version> versions
1.0.0
```

The expected output is:

```console
$ npm view <package-with-one-version> versions

[ '1.0.0' ]
```

**Comment by davidchambers** [comment] 2015-06-10 22:02
The `--json` option has the same problem.

Here's a workaround:

```bash
for version in $(npm view "$name" versions | sed "s:[^0-9.]::g") ; do
  # ...
done
```

**Comment by KenanY** [comment] 2015-06-14 20:06
@davidchambers Duplicate of https://github.com/npm/npm/issues/7757. This has been "fixed" on the `multi-stage` branch and will be coming in `npm@3` (since it _is_ kind of a breaking change).

**Comment by othiym23** [comment] 2015-06-17 23:54
@iarna, can you confirm that this is fixed (and that it's fixed on purpose) in `multi-stage`?

**Comment by KenanY** [comment] 2015-06-18 01:51
@othiym23 I hope so https://github.com/npm/npm/pull/7770#issuecomment-93762889 :see_no_evil:

**Comment by othiym23** [comment] 2015-06-18 02:29
Me too! :speak_no_evil:

**Comment by iarna** [comment] 2015-06-18 13:01
Yup, it does indeed look good!

**Comment by iarna** [comment] 2015-06-19 06:02
Closing this as resolved in the `multi-stage` branch.

**Closed by iarna** 2015-06-19 06:02 UTC
Labels: bug
