### ISSUE TITLE
Cannot read property 'path' of null

### ISSUE THREAD

**Issue by ypalacios2** [npm/npm#16067] opened 2017-03-16 23:20 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I get an error - Cannot read property 'path' of null
#### How can the CLI team reproduce the problem?

I typed in: npm install foundation-cli --global

### supporting information:

 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'foundation-cli',
1 verbose cli   '--global' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData foundation-cli
8 silly fetchNamedPackageData foundation-cli
9 silly mapToRegistry name foundation-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'foundation-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'foundation-cli',
12 silly mapToRegistry   name: 'foundation-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/foundation-cli
14 verbose request uri https://registry.npmjs.org/foundation-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:00:06 PM
17 verbose request id 3ea9e86a4d0cbb64
18 http request GET https://registry.npmjs.org/foundation-cli
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.24.162:443
20 info attempt registry request try #2 at 4:01:31 PM
21 http request GET https://registry.npmjs.org/foundation-cli
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.24.162:443
23 info attempt registry request try #3 at 4:03:46 PM
24 http request GET https://registry.npmjs.org/foundation-cli
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.24.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1033:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1056:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
25 silly fetchPackageMetaData  error for foundation-cli { Error: connect ETIMEDOUT 151.101.24.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1033:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1056:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.24.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (/usr/local/lib/node_modules/npm/lib/install.js:511:29)
27 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
27 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
27 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:337:5
27 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
27 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
27 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:294:5
27 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
28 verbose cwd /Users/pc06411
29 error Darwin 14.4.0
30 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "foundation-cli" "--global"
31 error node v7.7.3
32 error npm  v4.1.2
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-03-16 23:27
Duplicate of #10686.

**Comment by ypalacios2** [comment] 2017-03-16 23:52
Sorry, I'm totally new to this. How do I resolve this?

**Comment by KenanY** [comment] 2017-03-17 00:55
The error messages seem to indicate that your internet connection is timing out, so the issue likely lies there.

**Closed** 2017-06-17 03:47 UTC
Labels: bot-closed
