### ISSUE TITLE
npm 5 breaks codecommit git urls

### ISSUE THREAD

**Issue by jaslo** [npm/npm#16841] opened 2017-05-31 22:03 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
dependencies using git urls in codecommit (that don't end in .git) are not installed
and no error is produced

#### How can the CLI team reproduce the problem?
I had this line in my package.json dependencies:
 "mongopackage": "git+ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/mongopackage",

So, simply set up an amazon codecommit, set appropriate rsa keys and do an npm install.
The package WILL NOT be installed.

### supporting information:
This only happens on npm 5, fixed by going to npm 4.6.1.

**Comment by zkat** [comment] 2017-06-01 02:38
@jaslo I just pushed out `npm@5.0.1`. Could you try this again with that? It has a bunch of git fixes.

**Comment by mroswald** [comment] 2017-06-01 10:34
@zkat Does not work for me on 5.0.1

**Comment by jaslo** [comment] 2017-06-01 22:52
still broken for me too.

**Comment by zkat** [comment] 2017-06-01 23:40
Closing as a duplicate of https://github.com/npm/npm/issues/16726

**Closed as completed by zkat** 2017-06-01 23:40 UTC
Labels: git, npm5
