### ISSUE TITLE
package-lock.json is created even when package.json does not exist. Wondering if this is desired behavior.

### ISSUE THREAD

**Issue by chevex** [npm/npm#16808] opened 2017-05-31 01:03 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

NPM creates a package-lock.json file even when no package.json file is present.

#### How can the CLI team reproduce the problem?

```
mkdir bug
cd bug
npm i bluebird
```

`--save` is now default which is great, except in the case where `package.json` does not exist which makes sense. However a `package-lock.json` file is still created. Is this desired behavior? Not a huge issue but thought I'd bring it up for consistency's sake. Personally I'd prefer it to leave my directory clean (aside from `node_modules`) if I have no package.json file.

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2017-05-31 04:17
This is a good question, and I can't remember right now what the intention was. /cc @iarna

**Comment by Gaafar** [comment] 2017-06-01 08:49
Same issue here. In my opinion, if `package.json` is missing, then running `npm install` should not have any side effects. I can work on this issue, just need someone to point me in the right direction.

**Comment by dolanmiu** [comment] 2017-06-01 14:47
is `package-lock.json` a new feature? It didn't used to happen on this project. Only after I upgraded to npm `5.0.x`

**Comment by BeekeeperAlex** [comment] 2017-06-01 15:03
@dolanmiu Yes, it's new with 5.0 I believe. I don't mind it. I could see it being pretty useful outside of the npm ecosystem. I just don't think it should be created if I don't even have a package.json because usually the absence of a package.json means I'm just messing around in a local project I don't intend to upload. Minor inconvenience but still.

**Comment by dolanmiu** [comment] 2017-06-01 15:10
Shall I commit this in source control? It seems very verbose. I am afraid to commit it

**Comment by BeekeeperAlex** [comment] 2017-06-01 15:12
It won't hurt to check it in. I believe the point is for it to be a verbose description of each dependency so non-npm systems can use it since dependencies listed in package.json usually specify a version range rather than a specific version. Listings in package.json also don't include a link back to the source without further querying the registry.

**Comment by fredbt** [comment] 2017-06-01 15:20
cool. I've just upgraded the system, and now this package is created. I'm also wondering if I should check it in or not.

**Comment by BeekeeperAlex** [comment] 2017-06-01 15:22
You don't ***have*** to check it in but it was intended to live next to package.json and won't hurt to check it in.

**Comment by fredbt** [comment] 2017-06-01 15:23
Cool, thanks @chevex !
So amazing to see software evolving in real time!

**Comment by dolanmiu** [comment] 2017-06-01 15:25
> I believe the point is for it to be a verbose description of each dependency so non-npm systems can use it

Is it possible to disable it, because my company will only be ever using npm and not a third party alternative

**Comment by BeekeeperAlex** [comment] 2017-06-01 15:26
That's a good question. Not that I'm aware of, but it may just be that I haven't discovered how yet.

**Comment by jakewies** [comment] 2017-06-03 15:29
I just updated `node` to `v8.0.0` and `npm` to `v5.0.2` this morning. I wanted to play around with an idea using **nextjs** so I ran `npm install next@beta react react-dom` and a `package-lock.json` file was created but no `package.json`. If I want to add, say, an `npm script` I would need to do that in `package.json` but it doesn't exist. 

Should the correct practice be to create the `package.json` _before_ I run `npm install` to initialize a project?

I apologize in advance for bringing this question into this issue, but it seems that it could help add to the discussion on desired behavior 👍

**Comment by trusktr** [comment] 2017-06-17 22:38
Should package-lock.json be checked into source control for non top-level apps, for example for packages being used in an app?

I know that package-lock.json will be ignored and not published to NPM, but should I commit it anyways for my libraries that I publish to NPM? It is useful in any way? 

Or is it just for top-level applications?

If so, what is recommended as far as libraries? For example, every time I dev them, package-lock.json appears. Should I add it to .gitignore? Or should I delete it after every time I install dependencies for deving? etc? What is the recommendation?

**Comment by dolanmiu** [comment] 2017-06-18 21:42
https://docs.npmjs.com/files/package-lock.json

> This file is intended to be committed into source repositories

Seems like it, but I don't like it 😢

**Comment by trusktr** [comment] 2017-06-19 00:06
It's not clear if the docs are talking to app authors or library authors. It'd be nice to address both types of authors specifically, in the docs.

If app authors are meant to commit package-lock.json, and it behaves exactly the same as shrinkwrap, then it really makes no difference for the app author, so it seems like the docs might be talking to liibrary authors.

But, if the docs are talking to library authors, what's the point if library authors shouldn't rely on it because it is not published to NPM?

Is it for during dev, that package-lock.json can be helpful for library authors? But then, if a library author devs against a package-lock.json file, then they won't detect possible bugs from higher versions of the libraries dependencies that an app author may have installed.

It really just seems like _app authors _ can optionally use package-lock.json, and library authors should only use shrinkwrap if needed.

Finally, by that logic, it seems like package-lock.json is not useful for anything because app authors already have shrinkwrap (except that it isn't automatic like package-lock is, which is the good thing about package-lock), and that library authors don't need to care about package-lock at all.

Any clarification would be greatly appreciated. 😄

**Closed** 2017-07-10 22:47 UTC
Labels: bot-closed, needs-discussion, npm5, support

**Comment by BeekeeperAlex** [comment] 2017-07-10 23:54
So where do they provide support?

**Comment by claudiuconstantin** [comment] 2017-07-25 08:49
Probably here: https://www.npmjs.com/support
