### ISSUE TITLE
Shrinkwrap removes dev deps that satisfy descendants' prod deps

### ISSUE THREAD

**Issue by lennym** [npm/npm#11434] opened 2016-02-05 11:59 UTC
I have a case where I rely on a package (in my situation `deep-diff`) as a dev dependency on my top-level project, and another dependency has the same package, with a compatible version, in its dependency tree as one of its prod dependencies (namely `sails->waterline->deep-diff`).

However, since my dev dependency will also satisfy the prod dependency, the same package is not installed further down the dependency tree.

*However*, when I run my builds, I npm-shrinkwrap before publishing, and shrinkwrap ignores the `deep-diff` package since it is a dev dependency, and then when installing with `--production` later the child dependencies throw an error about a missing dependency of `deep-diff` since it was not included in the shrinkwrap file.

A workaround workflow would be to `npm test`, `npm prune --production` and `npm install --production` before shrinkwrapping, but this would effectively make the shrinkwrap process redundant as it no longer means that the dependencies listed in the shrinkwrap are necessarily the same as those that were tested against.

The preferable solution would obviously be for npm-shrinkwrap to recognise when a dev dependency is also satisfying a descendants prod dependency and not ignore it. Or at the very least throw an error since the generated shrinkwrap cannot satisfy the dependency tree of the project.

Note: all of this is on npm@2.14.12

**Comment by ashleygwilliams** [comment] 2016-02-06 15:16
related to #11438

**Comment by lennym** [comment] 2016-02-06 22:48
Thans @ashleygwilliams, it does seem like these are different manifestations of the same issue.

**Comment by othiym23** [comment] 2016-02-12 06:31
I'm going to close this as a duplicate of #11438, which is tagged with `big-bug`, which means that it will get addressed relatively soon (after the current phase of work on npm's test suite is completed). Thanks for your time and patience, @lennym!

**Closed by othiym23** 2016-02-12 06:31 UTC
Labels: bug
