### ISSUE TITLE
npm install after npm link deletes linked module dependencies in it's node_modules folder

### ISSUE THREAD

**Issue by HosseinAgha** [npm/npm#17287] opened 2017-06-18 13:24 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

npm installing should not do anything with linked package modules but it completely messes up linked package dependency tree and installed modules.  
In other words you cannot do anything in npm 5 if you rely on linked packages.

#### How can the CLI team reproduce the problem?

npm link to package that you already `npm installed 

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: macOS

This is probably a duplicate of https://github.com/npm/npm/issues/10343 but as it is an old issue and none of the project maintainers noticed that this issue is popped up again in version 5 I'm opening a new issue here. I think some people have not faced this issue, because they have not `npm installed` in their main package yet.

**Comment by lejeunerenard** [comment] 2017-06-19 18:55
This is probably a duplicate of #16788.

**Comment by HyperBrain** [comment] 2017-07-24 14:03
@lejeunerenard I think this one is a superset of #16788 . The major issue here is, that you cannot do any module development and local testing with npm 5 because it just removes the linked modules as soon as you do a "npm install".

**Comment by marijnh** [comment] 2017-08-06 10:15
(Still happening with 5.3. My multi-module workflow which worked fine with 3.x and 4.x has become very painful since 5.x, due to unpredictable changes in sub-module's `node_modules` directory. The most obvious/consistent one is that `node_modules/.bin` is deleted in the linked modules every time I run `npm install` on the outer module.)

**Comment by HosseinAgha** [comment] 2017-08-15 13:20
I don't understand the existence of this bug after such a long time. maybe link is not a priority for npm community?!

**Comment by bertho-zero** [comment] 2017-08-17 12:25
Same here

**Comment by Legogris** [comment] 2017-09-28 13:17
Still an issue with npm 5.4.2. This really breaks the workflow.

**Comment by jimsugg** [comment] 2017-11-01 08:16
Our team relies on linking to test a set of interacting packages. In this regard, npm 5 is a nightmare. We have no choice but to revert to npm 4 until we have the time to figure out how to adjust our workflow, or find an acceptable workaround. Note this is one of many issues open related to problems related to linking introduced in npm 5.

**Comment by HosseinAgha** [comment] 2017-11-04 05:35
Actually we got tired of asking every team member using node 8 to revert her npm using `npm i -g npm@latest-4` so we switched to yarn on every environment and we are really happy with it's speed and stability.

**Comment by nemoDreamer** [comment] 2017-11-14 21:39
This has broken in the past (#3767, among others), and had been fixed.

Why does this keep breaking? It seems like `npm link` is part of any node package developer's vital workflow, no?

We too are about to switch to `yarn` because of this issue.

**Comment by mightyiam** [comment] 2017-11-14 21:42
Actually, I don't mind so much. And I do use npm link. On an npm install, the whole tree is installed, overriding the links. What would make more sense than that? To leave the links in place? Perhaps to do that and to warn?

I doesn't happen that I have more than one linked package at a time, so maybe that's why I'm fine with it.

**Comment by HosseinAgha** [comment] 2017-11-15 06:06
@mightyiam It's not only about deleting the link from package's node_module (yarn also have this behavior) installing after link completely messes up node_modules of linked module!
You can see the detailed explanation in #16788

**Comment by mightyiam** [comment] 2017-11-15 09:23
Oh. That actually happened to me today. I didn't know how to eat that. Ok,
so that's an issue right there.

**Comment by jimsugg** [comment] 2017-11-16 01:31
To be clear about what I found:
Some background: I am responsible for development of a set of packages to support our app team. They all have various interdependencies, so I use npm link a lot during development where I have to add functionality to multiple packages. I will link a subset of the packages in order to do this.
I also link to globally installed packages: e.g., typescript, webpack, tslint.
I first noticed an issue when I decided to try using Yarn. I initially thought it was Yarn, but the issue persisted when I reverted to just npm. I then realized the issue was in npm v5, which Yarn had installed. (I had been using node v7 and npm v4.)
Here is the problem, as best as I can tell:
Every time I run npm install, all of my symbolic links are removed. I have to reset every one after an npm install.
Since I have my packages internally declared as peerDependencies, I have to manually install the versions of packages that I want to pull from npm. This makes it even more difficult, because every time I do a separate npm install to pull one or more of my packages, it again removes the links. In other words, I am not just doing a single npm install - I have to do that more often because of peerDependencies.
Because of all of this, in general, every time I need to shift my module install setup, it is a struggle to get everything back to a state where it works.
The major problem I see is the removal of links by doing an npm install. I have no idea of the reasoning behind which the decision was made to do this. However, at minimum, there needs to be a way to tell npm install NOT to remove existing symbolic links. Until that is in place, I simply cannot use npm v5.

**Comment by nemoDreamer** [comment] 2017-11-16 17:04
@jimsugg I came across http://codetunnel.io/npm-5-changes-to-npm-link/, which speculates that this might be an intentional (but undocumented!) change...

I disagree with the final conclusion of the author, though, and would argue that the cons far outweigh the pros. I don't want my `package.json` to be littered with local changes that I'm not allowed to stage and commit...!

If `npm link` is now only meant for temporarily pointing to a dev folder, then we need an alternative solution to support long-term development of inter-connected packages without risking an accidental break in builds.

**Comment by jimsugg** [comment] 2017-11-16 20:59
@nemoDreamer Thanks for posting this Medium article link - that helps my understanding a bit. I think I had seen some of his comments in various threads, but this is a clearer explanation. I will have to consider this a bit more to see how it might apply to our situation.

There is also the issue of linking to global packages (e.g., tools like Typescript,) which I suppose may also be addressable by the approach suggested in this article (npm install /usr/local/bin/.. - Ugh!)

I certainly agree with you that the changes made to package.json are a problem. We have already experienced some unwanted changes to the package.json file that got inadvertently committed within our team.

It is very disappointing that the npm team doesn't make a bit more effort to explain major changes like this, and to fail to update the documentation. Npm 5 has been out what, six months now?

**Comment by maerzhase** [comment] 2017-12-05 13:28
@nemoDreamer thanks for the article that clarified a lot to us. for us the __CONS__ outweigh because the relative path symlink references stored in `package.json` dont resolve correctly unless you ensure that the file-system looks the same on any DEV's machine. that might make sense for the use-case u mention (plugin architecture) but how does that make sense for any other use-case? 

like @jimsugg says it above: its disappointing that the npm team doesn't make any effort to explain such a change and neither reacting on this thread.

**Comment by ties-s** [comment] 2017-12-11 19:11
Created a little command line app for this problem, so if you need to keep those packages linked: [npm/persistent-package-linker](https://www.npmjs.com/package/persistent-package-linker)
[EDIT: doesn't fix all the issues though :(]

**Comment by ibc** [comment] 2018-01-18 12:09
I waste about 5% of my life redoing soft links after **any** `npm install whatever` in my apps. This is a pain.

Please, `npm install --dont-delete-my-links`

**Comment by jwhitmarsh** [comment] 2018-01-24 15:52
This occurs even after running `npm unlink` and installing the modules from github. Is there _any_ workaround to this?

**Comment by Niffy** [comment] 2018-01-24 16:16
Yep, this is sure annoying when you have lots of modules.

**Comment by 8eecf0d2** [comment] 2018-02-01 09:32
I'm lowkey working on a solution to this because its soo damn irritating, the idea in simple terms is to just use a new file called `package-local.json` to hold local dev stuffs (mainly dependencies - but also extra scripts which is neat).

In practice `npm link` will change to `package-local.json` and `npm install` will change `package.json`. The two are merged whenever either is updated and then all the missing linked packages are re-linked, in most situations the `package-local.json` probably wouldn't be committed to sc.

Any suggestions / improvements welcome!

**Comment by HyperBrain** [comment] 2018-02-01 09:52
@brod I'm not sure introducing a new `package-local` definition file won't not only solve the problem but introduce much more side effects and complexity. This creates many additional combinations of possible manual user changes that have to be solved too. What if a user adds the very same package to his `package.json` and then does a `npm install` while the link is also present in the `package-local.json`? Do links always have precedence?
Additionally `package-lock` has to be consistently integrated into the whole system and makes that approach even more complex. What if you have a dependency in `package.json` and in `package-local.json`? Would the npm link also change the `package-lock` json to the currently linked version?

**Comment by ibc** [comment] 2018-02-01 09:59
>  a new file called `package-local.json`

Please, no. We need a fix, not a workaround.

**Comment by ties-s** [comment] 2018-02-01 11:59
@brod what would be the difference between your idea and the workaround [package](https://www.npmjs.com/package/persistent-package-linker) I created that puts links in package-links.json? [(see my comment)](https://github.com/npm/npm/issues/17287#issuecomment-350826266)

**Comment by nemoDreamer** [comment] 2018-02-01 20:10
Sorry, but our team are now using `yarn link`, which behaves the way `npm link` is _supposed_ to. We are yet to find a reason to come back to `npm`...

**Comment by shavyg2** [comment] 2018-02-22 15:27
about to leave npm for the same reason...

**Comment by Niffy** [comment] 2018-02-23 10:04
Same here, we use linking a lot when doing dev work locally, we are now using yarn link + yarn add, currently we only use npm to start servers and a full install, some in the office use yarn full stop.

**Comment by brandonkirsch** [comment] 2018-03-02 19:07
> npm install nodemailer

Just deleted three other modules without consent or confirmation, wiping out several weeks of work.

Who on earth thought it was a good idea to automatically delete unrelated modules during a package install?

**Comment by nemoDreamer** [comment] 2018-03-02 20:11
@brandonkirsch that sounds awful!!
If you say it "wiped out several weeks of work", does that mean you'd placed your _working copy_ of a package into a `node_modules` folder, instead of sym-linking it into there? And weren't separately source-controlling it as well? 😱 
I know I know... Captain Hindsight here...

**Comment by brandonkirsch** [comment] 2018-03-02 20:32
@nemoDreamer I'm on Windows and as far as I can see (which is kind of difficult on this OS) there are no symlinks involved.

So yes, it was my working copy and it also contained the git repo itself.  It's a haphazard setup that blew up in my face in a really bad way due to the unexpected behavior in NPM.

The good news is that I found a fully working backup that contains both my code and my repo.  I created the backup after a big sprint of activity and I am so relieved to have it back.

The bad news is that I am now very, very scared of NPM.

EDIT:  I found that my troubles come from package-lock.json, which was automatically generated by NPM but apparently not kept up-to-date.

**Comment by nemoDreamer** [comment] 2018-03-06 16:58
What a relief, @brandonkirsch !! 😅

**Comment by mjdease** [comment] 2018-03-07 14:54
Not ideal but I've worked around this by adding a `postinstall` script that re-links my dependencies. eg:
```json
  "scripts": {
    "postinstall": "npm link my-linked-dep"
  }
```

**Comment by shavyg2** [comment] 2018-03-07 20:57
and we thought we would have flying cars by year 2000...
```postinstall and install the linked module seems to be the only way.```

I don't mean to belittle the situation but local development and test ensures that the npm community doesn't just ship broken modules.

There are a lot of things that can be done to make this a non issue and still have good code quality, but in the end it comes down to the community.

It's in the interest of npm to ensure that many avenues are available to gain over all quality.

I am interested in helping out as well.


How do we move from complaining about the issue to steps to resolving it?

**Comment by oleics** [comment] 2018-03-23 14:32
Still true for 5.7.1. Please please please fix this.

**Comment by cuijiemmx** [comment] 2018-03-28 17:19
why not fix it!!!

**Comment by jhampton** [comment] 2018-03-29 18:15
@oleics and @shavyg2 – Do you see a consensus around how we could work to resolve this issue?  We're facing the same issue over here, and for a variety of reasons `symlink`s aren't always available.  I'm more than happy to put some time and weight behind a direction, I just don't have a sense of what the `Right Thing To Do`® is in this case.

Thanks in advance!

**Comment by ibc** [comment] 2018-03-29 21:09
Non deleting links in `node_modules` when calling `npm install whatever` would be a good start.

**Comment by kayahr** [comment] 2018-04-09 06:44
Is this issue fixed in 5.8.0? Haven't used npm linking for a while (Wrote my own link tool for it) but a quick test with 5.8.0 looks promising. Links are no longer removed on `npm install`. To test this I used three projects:

* Project A (No dependencies)
* Project B (Depends on linked project A)
* Project C (Depends on linked project A and B)

All three links survived `npm install` in Project C.

**Comment by oleics** [comment] 2018-04-09 07:55
@jhampton I disable shrinkwrap in every package (``package-lock=false`` in .npmrc)

I don't know if this is the right thing to do, but ``It just works`` ^^

**Comment by UD-UD** [comment] 2018-04-12 01:35
Hi, 
A bit late for the reply.
I have developed a cli utility that helps you to keep your local links unbroken even after installing dependencies.
You can download it from [npm](https://www.npmjs.com/package/npm-safe-install)

Also you can find the source code in [github](https://github.com/UD-UD/npm-safe-install)

Hope it helps. :)

**Comment by legodude17** [comment] 2018-05-15 20:33
Ref npm/rfcs#3

**Comment by kneczaj** [comment] 2018-05-17 13:51
**The following cases has the linked package version smaller (1.0.0) than the remote one (1.0.30). Package.json's required version is "^1.0.0"**

The following works for me (the linked package stays):
1. `rm -R node_modules && rm package-lock.json`
2. `npm link <package>`
3. `npm install`

In this situation `npm install` does not overwrite the linked `<package>`. The key point here is to delete package-lock.json which may contain `<package>` version available only from remote repo not the one from linked `<package>`.

The following does not work for me (`npm install` overwrites copied package):
1. `rm -R node_modules && rm package-lock.json`
2. `cp <package>/dist/* node_modules/<package>`
3. `npm install`

The following does not work for me (`npm install` overwrites linked package):
1. `npm install` - this will create package-lock.json with later linked package version set to remote one
2. `rm -R node_modules`
3. `rm -R node_modules/<package>`
4. `npm link <package>`
3. `npm install` - this will overwrite the linked package to satisfy package-lock.json version

Looks like the links are choosen not to be overwritten as long as they satisfy package.json and package-lock.json requirements.

My environment:
- node v8.11.1
- Windows 7
- CYGWIN (although nodejs is installed as native windows)
- links are real windows symlinks (in cygwin they can be emulated too)

**Comment by zkat** [comment] 2018-06-27 21:25
We are well aware of `npm link` issues, and it will be overhauled with `npm@7` later this year. As @legodude17 says, please refer to https://npm.community/t/new-npm-link-command/24/1 for more information on this, and discussions about what it should do. Until then, consider npm as it is to be broken and the overhaul to be the fix.

**Closed as completed by zkat** 2018-06-27 21:25 UTC
