### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by xu283900277xiu** [npm/npm#14090] opened 2016-09-27 08:11 UTC
D:\work\rn\AwesomeProject>npm install --save react-native-code-push
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "--save" "react-native-code-push"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-24364-
ce63bb13\registry.npmjs.org\react-native-code-push-\react-native-code-push-1.14
.6-beta.tgz
npm ERR! Expected: d237f9f06a5d1aad592d9ad0b9013df455e0003d
npm ERR! Actual:   2ddde49aa2eebc46a30dd5adfd1b647d2fbe4531
npm ERR! From:     http://registry.npmjs.org/react-native-code-push/-/react-nati
ve-code-push-1.14.6-beta.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by KenanY** [comment] 2016-09-27 13:05
@xu283900277xiu Have you tried `npm cache clean`?

**Comment by zkat** [comment] 2016-12-09 00:37
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:37 UTC
Labels: shasum, support
