### ISSUE TITLE
Scoped name packages don't work when installed from github

### ISSUE THREAD

**Issue by parkan** [npm/npm#9798] opened 2015-09-30 16:32 UTC
I have a repo at https://github.com/parkan/graffiti-mongoose forked from https://github.com/RisingStack/graffiti-mongoose. Their package is named `@risingstack/graffiti-mongoose` (scoped name)

If I try to install directly from github (at any revision), I am unable to require the module:

```
[failtest]% npm init --yes
[failtest]% npm install parkan/graffiti-mongoose --save (arkadiy@helium:~/mine/failtest)
failtest@1.0.0 /Users/arkadiy/mine/failtest
└── @risingstack/graffiti-mongoose@2.0.0  (git://github.com/parkan/graffiti-mongoose.git#01a8480fa7d787a4d74bf3bcb257d01b4d73129a)

npm WARN EPACKAGEJSON failtest@1.0.0 No description
npm WARN EPACKAGEJSON failtest@1.0.0 No repository field.
[failtest]% node                                        (arkadiy@helium:~/mine/failtest)
> require('@risingstack/graffiti-mongoose');
Error: Cannot find module '@risingstack/graffiti-mongoose'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
```

However, if I install directly from npm, it works fine. Likewise, the same repo checked out to filesystem and installed from there works fine.

It appears that the github install loses a bunch of files:

```
[failtest]% ls node_modules/@risingstack/graffiti-mongoose
CHANGELOG.md	LICENSE		fixture
CONTRIBUTING.md	README.md	package.json
```

versus the real deal:
```
% ls node_modules/@risingstack/graffiti-mongoose
CHANGELOG.md				graffiti-mongoose.sublime-project
CONTRIBUTING.md				graffiti-mongoose.sublime-workspace
LICENSE					lib
README.md				package.json
fixture
```

(ignore the sublime files in the checkout)

**Comment by parkan** [comment] 2015-09-30 16:35
I can confirm that this is broken when installing from the parent repo as well, not just the fork

**Comment by iarna** [comment] 2015-09-30 18:58
Hi there, so this is a known issue with installing from git repos. Specifically, as git repos never go through the publication step, they're missing build artifacts that happen as part of that step.  For instance, your example has a prepublish that runs `npm run build`, which in turn runs:

```
rm -rf lib/* && babel src --ignore __tests__ --out-dir lib"
```

For your fork, if you were to add the `lib` dir to the repo then it would work for you.

Another alternative would be to change the scope in the `package.json` to your own and publish it to the registry. As it'd be going through the publication step then, it would work.

**Comment by iarna** [comment] 2015-09-30 18:59
I'm going to close this as a duplicate of #3055.

**Closed by iarna** 2015-09-30 18:59 UTC

**Comment by iarna** [comment] 2015-09-30 19:00
(I should add: This is something we want to address, and I have a tentative plan as to how to do so, but unfortunately doing it right will require some refactoring.)

**Comment by parkan** [comment] 2015-09-30 21:34
iarna: that makes sense, I suspected some kind of build step got skipped. Is it possible to at least document this behavior for now? The docs [here](https://docs.npmjs.com/cli/install) happily tell you to go ahead and install from github, and I couldn't find any other info on the issue.

**Comment by parkan** [comment] 2015-09-30 21:36
(I'll admit that maybe I was searching for the wrong terms, since I see the thread in #3055 is quite long and active, but maybe it'd still be nicer to warn casual users?)

**Comment by iarna** [comment] 2015-09-30 22:08
If you wanted to put together a pull request with a docs patch, we'd love that!
