### ISSUE TITLE
tarball.destroy() is preventing all npm installs

### ISSUE THREAD

**Issue by panickerr** [npm/npm#12153] opened 2016-03-31 04:29 UTC
everytime i try to run npm install this issue occurs, but while installing bower through npm it didnt happen. Even Gulp which i installed through Npm is working; but when i run npm intall -g npm or npm install to install all the node packages it fails to run and throws me the error that:

- tallbar.destory is not a function

- callback called more than once

i cannot proceed without this and also cannot attack the npm-debug.log file here so im copying it in the code section:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm',
1 verbose cli   '-g' ]
2 info using npm@2.14.20
3 info using node@v4.4.1
4 verbose install initial load of C:\Users\admin\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\admin\AppData\Roaming\npm\package.json
6 silly cache add args [ 'npm', null ]
7 verbose cache add spec npm
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'npm',
8 silly cache add   scope: null,
8 silly cache add   name: 'npm',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed npm@latest
10 verbose addNamed "latest" is being treated as a dist-tag for npm
11 info addNameTag [ 'npm', 'latest' ]
12 silly mapToRegistry name npm
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/npm
16 verbose addNameTag registry:https://registry.npmjs.org/npm not in flight; fetching
17 verbose request uri https://registry.npmjs.org/npm
18 verbose request no auth needed
19 info attempt registry request try #1 at 9:49:59 AM
20 verbose request id 47e64c778ddd96f0
21 verbose etag "DEY47IDEWVH8684OA5S6H8VRG"
22 http request GET https://registry.npmjs.org/npm
23 http 200 https://registry.npmjs.org/npm
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"1EY48QJCCCTP5XMYSYRTLSV0J"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'cache-control': 'max-age=300',
24 verbose headers   'content-length': '4703546',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Thu, 31 Mar 2016 04:20:03 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   age: '196',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-sin6922-SIN',
24 verbose headers   'x-cache': 'HIT',
24 verbose headers   'x-cache-hits': '4',
24 verbose headers   'x-timer': 'S1459398003.006107,VS0,VE0',
24 verbose headers   vary: 'Accept' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"1EY48QJCCCTP5XMYSYRTLSV0J"',
25 silly get     'content-type': 'application/json',
25 silly get     'cache-control': 'max-age=300',
25 silly get     'content-length': '4703546',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Thu, 31 Mar 2016 04:20:03 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     age: '196',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-sin6922-SIN',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '4',
25 silly get     'x-timer': 'S1459398003.006107,VS0,VE0',
25 silly get     vary: 'Accept' } ]
26 verbose get saving npm to C:\Users\admin\AppData\Roaming\npm-cache\registry.npmjs.org\npm\.cache.json
27 verbose correctMkdir C:\Users\admin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
28 silly addNameTag next cb for npm with tag latest
29 silly addNamed npm@3.8.3
30 verbose addNamed "3.8.3" is a plain semver version for npm
31 silly mapToRegistry name npm
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/npm
35 verbose addRemoteTarball https://registry.npmjs.org/npm/-/npm-3.8.3.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/npm/-/npm-3.8.3.tgz',
36 verbose addRemoteTarball   'f2c40972f023e17594d570a3da1d619bdf96bdb7' ]
37 info retry fetch attempt 1 at 9:50:03 AM
38 info attempt registry request try #1 at 9:50:03 AM
39 http fetch GET https://registry.npmjs.org/npm/-/npm-3.8.3.tgz
40 http fetch 200 https://registry.npmjs.org/npm/-/npm-3.8.3.tgz
41 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\Temp\npm-6380-29dd285a\registry.npmjs.org\npm\-\npm-3.8.3.tgz.2359998618' -> 'C:\Users\admin\AppData\Local\Temp\npm-6380-29dd285a\registry.npmjs.org\npm\-\npm-3.8.3.tgz'
42 verbose stack TypeError: tarball.destroy is not a function
42 verbose stack     at WriteStreamAtomic.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-tarball.js:85:15)
42 verbose stack     at emitOne (events.js:82:20)
42 verbose stack     at WriteStreamAtomic.emit (events.js:169:7)
42 verbose stack     at WriteStreamAtomic.emit (C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:60:34)
42 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:89:19
42 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
43 verbose cwd C:\Users\admin\Desktop\trail
44 error Windows_NT 6.1.7600
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
46 error node v4.4.1
47 error npm  v2.14.20
48 error tarball.destroy is not a function
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by nerrull** [comment] 2016-04-02 19:56
This happened to me today because I didn't have enough disk space available for the install. Freeing up some space fixed it.

**Comment by ningappa** [comment] 2016-04-25 08:40
Hi I'm having same issue while installing react-dom module. 

I'm able install other modules like react express modules. 
````
npm install react-dom
npm WARN package.json seo-panel-client@1.0.0 No description
npm WARN package.json seo-panel-client@1.0.0 No repository field.
npm WARN package.json seo-panel-client@1.0.0 No README data
npm WARN package.json seo-panel-client@1.0.0 No license field.
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz.2090210803' -> 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-dom"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz.2000813013' -> 'C:\Users\NOI-DE~1\AppData\Local\Temp\npm-3064-f12f714d\registry.npmjs.org\react-dom\-\react-dom-0.14.8.tgz'
```
My OS is windows 10. 64 bit machine.

**Comment by ronaldoats** [comment] 2016-08-04 19:37
hey, solution is:
`sudo rm /tmp/* -R -f`
all problem with `npm -g install `

> Error: tarball.destory

**Comment by othiym23** [comment] 2016-08-19 21:58
```
41 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\Temp\npm-6380-29dd285a\registry.npmjs.org\npm\-\npm-3.8.3.tgz.2359998618' -> 'C:\Users\admin\AppData\Local\Temp\npm-6380-29dd285a\registry.npmjs.org\npm\-\npm-3.8.3.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 21:58 UTC
Labels: support, windows

**Comment by ningappa** [comment] 2016-09-07 10:21
might be anti-malware problem, please check the link on [stackoverflow](http://stackoverflow.com/questions/36835882/npm-err-tarball-destroy-is-not-a-function)
