### ISSUE TITLE
Trying to install modules locally to a project and there's 3 modules that keep giving me issues "Error: Cannot find module 'C:\Users\USER\install.js'

### ISSUE THREAD

**Issue by kvntrn** [npm/npm#7333] opened 2015-02-10 20:47 UTC
![image](https://cloud.githubusercontent.com/assets/4700929/6136084/7f1d872a-b133-11e4-9fa1-28ab3022d499.png)

Is there anything I can do to fix this? Been looking everywhere and so far no solution.

**Comment by smikes** [comment] 2015-02-11 15:05
It looks like something is causing `npm` to try to run post-install scripts relative to your home directory instead of the install directory.  I haven't seen a bug like that before, but since you are running a pretty old version of `npm` (not your fault, `node` hasn't been updated for a while and it used to bundle an old version; new `node` versions will come with 2.5.1)

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation and see if the problem persists?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Also, next time, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Thanks!

**Comment by kvntrn** [comment] 2015-02-16 17:35
I updated my npm to 2.5.1 and I am still getting the same errors.

Here is the npm-debug.log:

https://gist.github.com/2e76f520eca24034ec4a.git

Thanks for helping smikes!

**Comment by smikes** [comment] 2015-02-16 17:54
OK, it's still failing to run the install scripts but at least it's looking in the right place now (at least, it looks that way).

Both `phantomjs` and `node-sass` will require either that you have a certain set of tools installed (Python 2.x and a C++ compiler – Visual Studio Express for Windows Desktop), or else that you download pre-compiled versions of the libraries.  It may be that the problem is that the `postinstall` scripts are trying to build/download the appropriate libraries but can't.

Can you try the following steps:

1. Download and install phantom js <http://phantomjs.org/download.html>
2. npm -d install -g phantomjs

and post the npm-debug.log from step 2 (if any).  If that works, then retry your `npm install`.  

If `npm install` doesn't work even though the `npm install -g phantomjs` did work, then can you please post your `package.json` to a gist – remove any proprietary information, of course – to help me in analyzing the problem.

**Comment by kvntrn** [comment] 2015-02-17 16:52
Okay, so I installed phantom js, ran npm -d install -g phantomjs and the install failed.

https://gist.github.com/a03b571b77bd3b6fccca.git

**Comment by smikes** [comment] 2015-02-18 01:11
Well, I'm out of ideas, so I will kick this over to @othiym23  -- any thoughts here? Windows installation failing in lifecycle script.

**Comment by othiym23** [comment] 2015-02-18 23:56
What does `npm config ls` return? There is something very peculiar going on here that I haven't seen before.

**Comment by kvntrn** [comment] 2015-02-19 19:59
Thank you for trying @smikes!

@othiym23 npm config ls returns:

C:\Users\ktran>npm config ls
; cli configs
user-agent = "npm/2.5.1 node/v0.10.33 win32 ia32"

; node bin location = C:\Program Files (x86)\nodejs\\node.exe
; cwd = C:\Users\ktran
; HOME = C:\Users\ktran
; 'npm config ls -l' to show all defaults.

**Comment by saper** [comment] 2015-08-10 22:14
At node-sass we have quite a few complaints recently about this: https://github.com/sass/node-sass/issues/1027, https://github.com/sass/node-sass/issues/1012, even with ancient `npm` and ancient `node-sass`: https://github.com/sass/node-sass/issues/659, https://github.com/sass/node-sass/issues/603. On my ancient Windows XP box things work fine though.

In [one case](https://github.com/sass/node-sass/issues/1012#issuecomment-115715502) an obscure registry setting has been identified as a culprit (`HKEY_CURRENT_USER\Software\Microsoft\Command Processor`) where a script was run on every start of `cmd.exe` that changed directories.

But I suspect other users do not have that problem.

Common factors: various versions of node-sass, various version of npm, sometimes it tries to execute "C:\scripts\install.js", sometimes "%HOME%\install.js" (more often the former).

**Comment by saper** [comment] 2015-08-11 00:13
File #9227 to help troubleshooting stuff like this. Maybe even we should log in `spawn.js`?

**Comment by saper** [comment] 2015-08-11 19:01
Question: Do we have any specific reason not to start node directly - but we rely on cmd.exe instead? (Similar question could be of course asked for UNIX). `sh` invocation is used whenever something (including executable name) needs to be expanded or some redirects need to be done or subshell `( ... )` commands or pipes are to be used - none of those I think applies there.

**Comment by othiym23** [comment] 2015-08-21 01:15
Fixed by 204ebbb3e0cab696a429a878ceeb4a7e78ec2b94 / #9245, included in `npm@2.14.1`.

**Closed by othiym23** 2015-08-21 01:15 UTC
Labels: support, windows
