### ISSUE TITLE
.npmignore is ignored by files array in package.json when using npm pack

### ISSUE THREAD

**Issue by mjackson** [npm/npm#7030] opened 2014-12-29 19:34 UTC
From the [package.json docs](https://docs.npmjs.com/files/package.json):

> The "files" field is an array of files to include in your project. If you name a folder in the array, then it will also include the files inside that folder. (Unless they would be ignored by another rule.)
> 
> You can also provide a ".npmignore" file in the root of your package, which will keep files from being included, even if they would be picked up by the files array. The ".npmignore" file works just like a ".gitignore".

If that's true, then this seems like a bug:

``` sh
michael:~/Projects/test-project$ npm -v
2.1.17
michael:~/Projects/test-project$ tree -a
.
├── .npmignore
├── modules
│   ├── __tests__
│   │   └── main-test.js
│   └── main.js
└── package.json

2 directories, 4 files
michael:~/Projects/test-project$ cat package.json 
{
  "name": "test-project",
  "version": "1.0.0",
  "files": [
    "modules"
  ]
}
michael:~/Projects/test-project$ cat .npmignore 
modules/**/__tests__/*-test.js
michael:~/Projects/test-project$ npm pack
test-project-1.0.0.tgz
michael:~/Projects/test-project$ tar -tvf test-project-1.0.0.tgz 
-rw-r--r--  0 501    20         83 Dec 29 11:23 package/package.json
-rw-r--r--  0 501    20         19 Dec 29 11:19 package/modules/main.js
-rw-r--r--  0 501    20         21 Dec 29 11:19 package/modules/__tests__/main-test.js
```

The `files` array includes the `modules` dir, but `modules/**/__tests__/*-test.js` is explicitly ignored in `.npmignore` which means it shouldn't be included in the package. But `npm pack` includes it anyway.

**Comment by mjackson** [comment] 2015-01-02 15:18
@smikes I didn't know about `dirs`. Is that documented somewhere? Or are you talking about `directories`? If so, I was under the impression that (almost) everything in `directories` was pretty much metadata, except for `directories.bin` which specifies executables.

**Comment by smikes** [comment] 2015-01-02 21:01
You're right, sorry, `dirs` isn't a real thing.  The behavior I see is that when I omit `files`, `.npmignore` is honored.

**Comment by othiym23** [comment] 2015-01-08 18:15
"files" is a pretty literal-minded name for what the attribute does. Does this behavior recur if you include the actual filenames, and not the directory name, in the `files` array?

**Comment by smikes** [comment] 2015-02-05 23:14
@mjackson we never heard back from you on this one.

I think the process by which `npm pack` puts together is file inclusion/exclusion list is pretty opaque.  What happens if you drop the double-glob from `.npmignore`:

```
modules/__tests__/*-test.js
modules/*/__tests__/*-test.js
# etc
```

**Comment by mjackson** [comment] 2015-02-23 18:22
> Does this behavior recur if you include the actual filenames, and not the directory name, in the files array?

@othiym23 Let's see:

```
michael:~/Projects/test-project$ npm -v
2.1.17
michael:~/Projects/test-project$ tree -a
.
├── .npmignore
├── modules
│   ├── __tests__
│   │   └── main-test.js
│   └── main.js
└── package.json

2 directories, 4 files
michael:~/Projects/test-project$ cat .npmignore 
modules/**/__tests__/*-test.js
michael:~/Projects/test-project$ npm pack
test-project-1.0.0.tgz
michael:~/Projects/test-project$  tar -tvf test-project-1.0.0.tgz 
-rw-r--r--  0 501    20         91 Feb 23 10:17 package/package.json
-rw-r--r--  0 501    20         19 Dec 29 11:19 package/modules/main.js
```

Yup, that seems to work! But I'd rather not have to list every file individually in the `files` array.

> What happens if you drop the double-glob from `.npmignore`

@smikes Let's see:

```
michael:~/Projects/test-project$ npm -v
2.1.17
michael:~/Projects/test-project$ tree -a
.
├── .npmignore
├── modules
│   ├── __tests__
│   │   └── main-test.js
│   └── main.js
├── package.json
└── test-project-1.0.0.tgz

2 directories, 5 files
michael:~/Projects/test-project$ cat .npmignore 
modules/__tests__/*-test.js
michael:~/Projects/test-project$ npm pack
test-project-1.0.0.tgz
michael:~/Projects/test-project$  tar -tvf test-project-1.0.0.tgz 
-rw-r--r--  0 501    20         83 Feb 23 10:20 package/package.json
-rw-r--r--  0 501    20         19 Dec 29 11:19 package/modules/main.js
-rw-r--r--  0 501    20         21 Dec 29 11:19 package/modules/__tests__/main-test.js
```

Hmm, nope. That doesn't work. Looks like the package.json docs are lying :)

**Comment by smikes** [comment] 2015-02-23 20:26
> Looks like the package.json docs are lying :) 

Fascinating.  I will spin that off into a separate issue, I bet I'll have to chase it through several modules.

**Comment by Turbo87** [comment] 2016-09-17 16:39
this seems to be a duplicate of https://github.com/npm/npm/issues/4479

**Closed** 2017-06-19 11:02 UTC
Labels: bot-closed, bug, documentation
