### ISSUE TITLE
error while updating node

### ISSUE THREAD

**Issue by abmsoftware** [npm/npm#14150] opened 2016-10-01 12:40 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem? root# npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.
MacBook-Pro:~ root# npm install -g n

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'n' ]
2 info using npm@3.10.8
3 info using node@v4.2.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData n
8 silly fetchNamedPackageData n
9 silly mapToRegistry name n
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'n',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'n',
12 silly mapToRegistry   name: 'n',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/n
14 verbose request uri https://registry.npmjs.org/n
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:05:35 AM
17 verbose request id 5c88ee3a21612313
18 http request GET https://registry.npmjs.org/n
19 http 200 https://registry.npmjs.org/n
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"6LV7U9A40EABRHFUCBKPAE9NW"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '12088',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 01 Oct 2016 12:05:35 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '173',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lax8635-LAX',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1475323535.287483,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"6LV7U9A40EABRHFUCBKPAE9NW"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '12088',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 01 Oct 2016 12:05:35 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '173',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lax8635-LAX',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1475323535.287483,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving n to /var/root/.npm/registry.npmjs.org/n/.cache.json
23 verbose correctMkdir /var/root/.npm correctMkdir not in flight; initializing
24 verbose makeDirectory /var/root/.npm creation not in flight; initializing
25 silly makeDirectory /var/root/.npm uid: 501 gid: 20
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule n@2.1.4 checking installable status
39 silly cache add args [ 'n', null ]
40 verbose cache add spec n
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'n',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'n',
41 silly cache add   name: 'n',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed n@latest
43 verbose addNamed "latest" is being treated as a dist-tag for n
44 info addNameTag [ 'n', 'latest' ]
45 silly mapToRegistry name n
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'n',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'n',
48 silly mapToRegistry   name: 'n',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/n
50 verbose addNameTag registry:https://registry.npmjs.org/n not in flight; fetching
51 verbose get https://registry.npmjs.org/n not expired, no request
52 silly addNameTag next cb for n with tag latest
53 silly addNamed n@2.1.4
54 verbose addNamed "2.1.4" is a plain semver version for n
55 silly mapToRegistry name n
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'n',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   escapedName: 'n',
58 silly mapToRegistry   name: 'n',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/n
60 verbose addRemoteTarball https://registry.npmjs.org/n/-/n-2.1.4.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/n/-/n-2.1.4.tgz',
61 verbose addRemoteTarball   '7546bc467a120cc96718f2716cd86c43290f94c5' ]
62 info retry fetch attempt 1 at 5:05:35 AM
63 info attempt registry request try #1 at 5:05:35 AM
64 http fetch GET https://registry.npmjs.org/n/-/n-2.1.4.tgz
65 http fetch 200 https://registry.npmjs.org/n/-/n-2.1.4.tgz
66 silly fetchAndShaCheck shasum 7546bc467a120cc96718f2716cd86c43290f94c5
67 verbose addTmpTarball /tmp/npm-1244-4fa96261/registry.npmjs.org/n/-/n-2.1.4.tgz not in flight; adding
68 verbose addTmpTarball already have metadata; skipping unpack for n@2.1.4
69 verbose correctMkdir /var/root/.npm correctMkdir not in flight; initializing
70 silly cache afterAdd n@2.1.4
71 verbose afterAdd /var/root/.npm/n/2.1.4/package/package.json not in flight; writing
72 verbose correctMkdir /var/root/.npm correctMkdir not in flight; initializing
73 verbose afterAdd /var/root/.npm/n/2.1.4/package/package.json written
74 silly loadAllDepsIntoIdealTree Finishing
75 silly loadIdealTree Finishing
76 silly currentTree lib
77 silly idealTree lib
77 silly idealTree └── n@2.1.4
78 silly generateActionsToTake Starting
79 silly install generateActionsToTake
80 silly generateActionsToTake Finishing
81 silly diffTrees action count 1
82 silly diffTrees add n@2.1.4
83 silly decomposeActions action count 8
84 silly decomposeActions fetch n@2.1.4
85 silly decomposeActions extract n@2.1.4
86 silly decomposeActions test n@2.1.4
87 silly decomposeActions preinstall n@2.1.4
88 silly decomposeActions build n@2.1.4
89 silly decomposeActions install n@2.1.4
90 silly decomposeActions postinstall n@2.1.4
91 silly decomposeActions finalize n@2.1.4
92 silly runTopLevelLifecycles Starting
93 silly executeActions Starting
94 silly install executeActions
95 silly doSerial global-install 0
96 silly doParallel fetch 1
97 verbose correctMkdir /var/root/.npm/_locks correctMkdir not in flight; initializing
98 verbose makeDirectory /var/root/.npm/_locks creation not in flight; initializing
99 silly makeDirectory /var/root/.npm/_locks uid: 501 gid: 20
100 verbose lock using /var/root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
101 silly doParallel extract 1
102 silly extract n@2.1.4
103 verbose unbuild lib/node_modules/.staging/n-3eb27508
104 silly gentlyRm /usr/local/lib/node_modules/.staging/n-3eb27508 is being purged from base /usr/local
105 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/n-3eb27508
106 verbose tar unpack /var/root/.npm/n/2.1.4/package.tgz
107 verbose tar unpacking to /usr/local/lib/node_modules/.staging/n-3eb27508
108 silly gentlyRm /usr/local/lib/node_modules/.staging/n-3eb27508 is being purged
109 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/n-3eb27508
110 silly gunzTarPerm modes [ '755', '644' ]
111 silly gunzTarPerm extractEntry package.json
112 silly gunzTarPerm extractEntry README.md
113 silly gunzTarPerm extractEntry Makefile
114 silly gunzTarPerm extractEntry bin/n
115 verbose stack TypeError: uid must be an unsigned int
115 verbose stack     at TypeError (native)
115 verbose stack     at Object.fs.chown (fs.js:1033:11)
115 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
115 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
115 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
115 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
115 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
115 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
116 verbose cwd /private/var/root
117 error Darwin 15.5.0
118 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
119 error node v4.2.2
120 error npm  v3.10.8
121 error uid must be an unsigned int
122 error If you need help, you may report this error at:
122 error     <https://github.com/npm/npm/issues>
123 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-10-01 13:43
Looks like a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-10-01 13:43 UTC
