### ISSUE TITLE
Trying to uninstall a global npm module and getting a crash

### ISSUE THREAD

**Issue by bjornharvold** [npm/npm#17080] opened 2017-06-08 03:11 UTC
#### I'm opening this issue because:

  - [X ] npm is crashing.

#### What's going wrong?
`npm uninstall -g @angular/cli`

```
> Unhandled rejection Error: Argument #2: Expected string but got null ini@~1.3.0 fetched in 17ms
>     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
>     at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
>     at Array.forEach (native)
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
>     at Array.forEach (native)
>     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
>     at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
>     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
>     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
>     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
>     at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
>     at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
>     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
```

[2017-06-08T03_07_40_231Z-debug.log.zip](https://github.com/npm/npm/files/1059846/2017-06-08T03_07_40_231Z-debug.log.zip)

**Comment by MasterJames** [comment] 2017-06-08 05:36
Trying node 8.0.0
I was getting
`ENOENT: no such file or directory, uv_cwd `
from 
`path.js:1163  cwd = process.cwd();`
and even `npm cache clean` triggered that error.
`npm uninstall -g n`
trigger your npm error to "report please", this thread is the closest match in time and type of error.

```
cat /root/.npm/_logs/2017-06-08T05_31_39_209Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'n' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly install loadIdealTree
7 silly install cloneCurrentTreeToIdealTree
8 silly install loadShrinkwrap
9 silly uninstall loadAllDepsIntoIdealTree
10 silly install loadAllDepsIntoIdealTree
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://github.com/npm/npm/issues>

```
Program won't run, it gets the same initial cwd error?

calling install for n says there's an update but it's suppose to come with node via n, no?
Finally with `npm i -g npm` 
it seems to have resolved?!

next I did this ...
```
npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@2.1.7
updated 1 package in 0.785s
```

and the program runs again now.

**Comment by kenany** [comment] 2017-06-08 14:56
Duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-08 14:56 UTC
Labels: npm5
