### ISSUE TITLE
Travis CI failing on Node.js 0.8

### ISSUE THREAD

**Issue by TaMe3971** [npm/npm#10023] opened 2015-10-18 17:46 UTC
Should npm be testing Node.js 0.8?
I made a Documentation change and Travis CI failed.

**Comment by ashleygwilliams** [comment] 2015-10-18 17:50
hey! after looking through a bunch of travis history/merged PRs.. looks like this might be always happening? 

is there a reason for continuing to test in 0.8 and/or how do we feel about merging @TaMe3971's doc PR even though it is failing on 0.8?

:)

**Comment by othiym23** [comment] 2015-10-18 18:29
This is a good issue to have open, because yes, npm does absolutely support Node 0.8, and will continue to do so until the sun burns out or the large installations still running production services on 0.8 stop doing so (my bet is on the sun, personally). Getting it fixed is a matter of dealing with the fact that some of npm's `devDependencies` aren't as fanatical about backwards compatibility as the CLI team, so we'll either need to replace those tools in the tests or hack around their incompatibilities. That this hasn't been done yet is more a consequence of the team having lots to do and not a lack of desire to see it fixed. We had CI green for a while and it was really nice. :(

With that in mind, the criterion for merging a PR is that it be reviewed and approved by some subset of the core team, and we're more likely than not to accept documentation changes, especially ones that improve the language like #10021. We now have a schedule for when we land PRs in new releases, so it'll take 1-3 weeks from when a PR is filed to when it's released.

I'm going to close this as a duplicate of #7832 (which has been open since April), but if somebody finds this issue and wants to help us out by fixing some tests to work with 0.8, that would be fantastic! Thanks for the reminder @TaMe3971!

**Closed by othiym23** 2015-10-18 18:29 UTC
Labels: bug, tests
