### ISSUE TITLE
I'm trying to run the example from the book I have a fairly fresh install of linuxmint

### ISSUE THREAD

**Issue by MrFoldAnyTen** [npm/npm#10949] opened 2015-12-24 02:10 UTC

**Comment by KenanY** [comment] 2015-12-24 16:52
This is probably a duplicate of https://github.com/npm/npm/issues/10948, which has the same title and has also been opened by @MrFoldAnyTen.

**Comment by iarna** [comment] 2016-01-08 19:58
Closing as duplicate of #10948

**Closed by iarna** 2016-01-08 19:58 UTC
