### ISSUE TITLE
getting this issue. Not sure what really is !!

### ISSUE THREAD

**Issue by SuryaJD** [npm/npm#10107] opened 2015-10-25 12:40 UTC
Hi I installed VS15 With all components on my windows 10 home base pc.
I created ionic tab projects but whenever I am trying to bulid that project following error occurs.
I am totally new to this.This is my 1st project 

```
1>------ Build started: Project: IonicCordovaProject5, Configuration: Debug iOS ------
1>  Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
1>  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.13
1>  ------ Package not currently installed globally.
1>  ------ Installing globally from source package. This could take a few minutes...
1>  npm ERR! Windows_NT 6.3.9600
1>  npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO 14.0\\COMMON7\\IDE\\EXTENSIONS\\APACHECORDOVATOOLS\\packages\\vs-tac" "--loglevel" "warn"
1>  npm ERR! node v0.12.2
1>  npm ERR! npm  v2.7.4
1>  npm ERR! shasum check failed for C:\Users\SURAJJ~1\AppData\Local\Temp\npm-5436-bb23d3f1\registry.npmjs.org\edge\-\edge-0.10.1.tgz
1>  npm ERR! Expected: 2c87d94a81e70537cbd916f52adc1c57d3b1a3bb
1>  npm ERR! Actual:   f86b10f019a486329183f0b5f8a9343b97737a0d
1>  npm ERR! From:     https://registry.npmjs.org/edge/-/edge-0.10.1.tgz
1>  npm ERR!
1>RUNMDAINSTALL : npm ERR! If you need help, you may report this error at:
1>  npm ERR!     <https://github.com/npm/npm/issues>
1>  npm ERR! Please include the following file with any support request:
1>  npm ERR!     c:\Users\suraj jadhav\Documents\Visual Studio 2015\Projects\IonicCordovaProject5\IonicCordovaProject5\npm-debug.log
1>  ------ npm install failed. Exit code: 1
1>  ------ Package installation failed. Retrying...
1>  npm WARN uninstall not installed in C:\Users\suraj jadhav\AppData\Roaming\npm\node_modules: "vs-tac"
1>  npm ERR! Windows_NT 6.3.9600
1>  npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "C:\\PROGRAM FILES (X86)\\MICROSOFT VISUAL STUDIO 14.0\\COMMON7\\IDE\\EXTENSIONS\\APACHECORDOVATOOLS\\packages\\vs-tac" "--loglevel" "warn"
1>  npm ERR! node v0.12.2
1>  npm ERR! npm  v2.7.4
1>  npm ERR! shasum check failed for C:\Users\SURAJJ~1\AppData\Local\Temp\npm-6636-faf4b933\registry.npmjs.org\edge\-\edge-0.10.1.tgz
1>  npm ERR! Expected: 2c87d94a81e70537cbd916f52adc1c57d3b1a3bb
1>  npm ERR! Actual:   79fa36228b8f82a64e2138d49a2dd00b0c244880
1>  npm ERR! From:     https://registry.npmjs.org/edge/-/edge-0.10.1.tgz
1>  npm ERR!
1>RUNMDAINSTALL : npm ERR! If you need help, you may report this error at:
1>  npm ERR!     <https://github.com/npm/npm/issues>

```

**Comment by KenanY** [comment] 2015-10-25 21:22
@SuryaJD Have you tried running `npm cache clean`?

**Comment by SuryaJD** [comment] 2015-10-26 07:38
@KenanY  thanks for reply buddy.
But I don't know about such thing . How can do that ?

**Comment by bboysathish** [comment] 2015-10-26 12:18
Open the terminal and run npm cache clean.

**Comment by SuryaJD** [comment] 2015-10-26 12:58
Done with it still getting same issue.

**Comment by zkat** [comment] 2016-12-09 00:54
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:54 UTC
Labels: support
