### ISSUE TITLE
npm install gets stuck on windows

### ISSUE THREAD

**Issue by vraptorche** [npm/npm#8745] opened 2015-06-28 17:55 UTC
When trying to execute npm install it gets stuck om loadDep npm-fetch

**Comment by ldez** [comment] 2015-06-30 21:03
Hi,
Please, give versions of Node, NPM and logs.

**Comment by vraptorche** [comment] 2015-07-01 04:53
Hi,
I'm using these vesrions: Node version - 0.12.5, npm 3.0.0

**Comment by iarna** [comment] 2015-07-01 04:56
Closing this as a duplicate of #8685.

**Closed by iarna** 2015-07-01 04:56 UTC
Labels: bug

**Comment by iarna** [comment] 2015-07-01 07:45
The mention of `loadDep` makes it clear this is an `npm@3` bug.
