### ISSUE TITLE
npm install needs a date option

### ISSUE THREAD

**Issue by jf26** [npm/npm#16011] opened 2017-03-12 03:22 UTC
Now I know this isn't really an npm issue, but npm is perfectly positioned to fix this problem with the node (and angular2) ecosystem.

The number of times doing an npm install works on one machine on one day, but not on another day is outrageous.

And by 'works' I mean all the dependencies actually run together.

If it was possible to just say npm install -date <whatever> it would make life a million times easier.

Please consider this feature.

**Comment by KenanY** [comment] 2017-03-12 03:55
Duplicate of https://github.com/npm/npm/issues/12994?

**Comment by jf26** [comment] 2017-03-13 07:34
Ah good point, didn't come up when I searched for 'date'. Thanks :)

**Closed** 2017-03-13 12:47 UTC

**Comment by tetratorus** [comment] 2017-10-12 17:05
npm-time-machine is what you are looking for
