### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by jayashreekr** [npm/npm#14695] opened 2016-11-22 06:03 UTC
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### What's going wrong?

```
npm WARN invalid config registry=""
npm WARN invalid config Must be a full url with 'http://'
npm WARN invalid config registry=""
npm WARN invalid config Must be a full url with 'http://'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "lighthouse"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for C:\Users\jayraj\AppData\Local\Temp\npm-11208-f8709d10\registry.npmjs.org\lighthouse\-\lighthouse-1.2.0.tgz
npm ERR! Expected: 6150016b8ab8a5d1468e72535b2474ae6d5f0abb
npm ERR! Actual:   5b6a06788bc9226c3bdeaca620c269e35103e2d2
npm ERR! From:     https://registry.npmjs.org/lighthouse/-/lighthouse-1.2.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log
```

#### How can the CLI team reproduce the problem?

While installing lighthouse

**Comment by gabriellira** [comment] 2016-11-22 23:25
I'm having the same problem. I'm running **node v6.9.1** and **npm v3.10.8** on Ubuntu 16.04.
This is the generated log: [npm-debug.log.txt](https://github.com/npm/npm/files/607810/npm-debug.log.txt)
That problem occurs with any package I try to install.

**Comment by gabriellira** [comment] 2016-11-22 23:38
Well, I tried again a few moments later...and it's worked

**Comment by zkat** [comment] 2016-12-02 04:46
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:46 UTC
Labels: shasum, support
