### ISSUE TITLE
eslint-plugin-react install typeerror

### ISSUE THREAD

**Issue by illfittingshoes** [npm/npm#8910] opened 2015-07-11 21:22 UTC
Tried installing eslint-plugin-react, but got code EINVALIDTYPE. I used "--no-bin-links" flag because I'm running in a Vagrant/VirtualBox on Windows 8, and symlinks don't work right in a shared folder.
There are currently 461 local modules in my project's node_modules directory, installed with npm 3.1.0.

I'm running npm 3.1.1 beta on Node 0.12.6 on Ubuntu Trusty/64
I tried to track down the debug log but it didn't appear to have been created.
![npm-3-1-1-eslint-plugin-react-install-error](https://cloud.githubusercontent.com/assets/3780063/8635428/44eda0ce-27f0-11e5-8164-fa84bba65950.png)

I'm only posting this because it said "This is an error with npm itself" :) Thanks for a great package manager, especially as of 3.x with much flatter folder structures that Windows doesn't reject!

**Comment by KenanY** [comment] 2015-07-12 04:20
Dupe of https://github.com/npm/npm/issues/8904?

**Comment by williamboman** [comment] 2015-07-12 10:59
dupe of #8893

**Comment by iarna** [comment] 2015-07-13 17:11
Closing as duplicate.

**Closed by iarna** 2015-07-13 17:11 UTC
