### ISSUE TITLE
npm init -y skips validation checks

### ISSUE THREAD

**Issue by patrickkettner** [npm/npm#14177] opened 2016-10-04 20:35 UTC
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [X] Other (_see below for feature requests_):
#### What's going wrong?

Inside of a folder named `FOO`, if I run `npm init`, I get something like the following

```
Press ^C at any time to quit.
name: (DELETE_ME) 
Sorry, name can no longer contain capital letters.
name: (DELETE_ME) 
```

if I run `npm init -y`, I get this

```
npm init -y 
Wrote to /Users/pdk/projects/Modernizr/DELETE_ME/package.json:

{
  "name": "DELETE_ME",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
#### How can the CLI team reproduce the problem?

mkdir /tmp/FOO && cd FOO && npm init -y
### supporting information:
- `npm -v` prints: 3.10.8
- `node -v` prints: v6.6.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OS X

**Comment by lholmquist** [comment] 2016-10-07 13:37
@patrickkettner maybe i'm missing something,  but is the problem exactly?  Do you need to run `npm init` first and cancel out of it, then run it again with the `-y` flag ?

**Comment by KenanY** [comment] 2016-10-07 15:33
@lholmquist I believe it's that `npm init -y` sets your package's `"name"` to something invalid (in this case, capital letters) without a warning/error.

**Comment by patrickkettner** [comment] 2016-10-07 16:42
Sorry for not being clearer. @kenany is correct, it is the fact that -y allows for an invalid name without error or warnings

**Comment by lholmquist** [comment] 2016-10-07 17:03
@patrickkettner @KenanY ah, got it now.   Yea that does seem like a bug

**Comment by lholmquist** [comment] 2016-10-07 17:09
so it looks like there is PR in the "interviewer" package that will make the default name lowercase,  https://github.com/npm/init-package-json/pull/67

**Comment by othiym23** [comment] 2016-12-05 22:54
Believe it or not, this is the intended behavior. This doesn't make sense unless you're aware that for `npm init`, `npm init -y` is merely a shortcut for `npm init --force`. I agree that this is less than useful for the vast majority of users. It may not make sense to you even then, but that's how it was designed and implemented.

I'd support a patch that splits apart `-y` / `--yes` and `-f` / `--force` and ensures that all validation checks pass in the former case. That said, this isn't something the CLI team is going to have time to do itself, so I'm marking this as a patch-welcome feature request and closing it. All of the necessary work is contained within [`init-package-json`](http://npm.im/init-package-json) itself, which drastically reduces the amount of code y'all will need to understand, and as time allows, we can answer questions if you decide to work on this and need guidance. Thanks for your time and the thorough discussion!

**Closed by othiym23** 2016-12-05 22:54 UTC
Labels: feature-request, footgun
