### ISSUE TITLE
npm install fails on Debian (npm v1.4.21, nodejs v4.2.4) - probably node-gyp and/or contextify

### ISSUE THREAD

**Issue by tufixm** [npm/npm#11335] opened 2016-01-29 07:39 UTC
```
myuser@barney:~/projects/scribeAPI$ npm install
npm WARN package.json scribeAPI@ No repository field.
npm WARN package.json json-api-client@0.2.11 No repository field.
npm WARN engine jest-cli@0.4.19: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.4","npm":"1.4.21"})
 
> contextify@0.1.15 install /home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.0-1-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! tar.unpack untar error /home/myuser/.npm/cssstyle/0.2.31/package.tgz
npm ERR! tar.unpack untar error /home/myuser/.npm/ansi-styles/2.1.0/package.tgz
npm ERR! tar.unpack untar error /home/myuser/.npm/escape-string-regexp/1.0.4/package.tgz
npm ERR! tar.unpack untar error /home/myuser/.npm/strip-ansi/3.0.0/package.tgz
npm ERR! tar.unpack untar error /home/myuser/.npm/supports-color/2.0.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/hoek/test/modules'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  jsdom@0.10.6 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/hoek/test/modules']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/hoek/test/modules' }
npm ERR! tar.unpack untar error /home/myuser/.npm/has-ansi/2.0.0/package.tgz
npm ERR! Error: ENOENT: no such file or directory, open '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4/anyOf.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/myuser/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4/anyOf.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! Error: ENOENT: no such file or directory, open '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/commander/node_modules/graceful-readlink/README.md'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/myuser/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/commander/node_modules/graceful-readlink/README.md
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/myuser/.npm/json-schema/0.2.2/package.tgz
npm ERR! tar.unpack untar error /home/myuser/.npm/verror/1.3.6/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  jest-cli@0.4.19 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples' }
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/myuser/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  js-yaml@3.5.2 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/lib'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  istanbul@0.3.22 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/lib']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/myuser/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/lib' }
npm ERR! tar.unpack untar error /home/myuser/.npm/argparse/1.0.4/package.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/myuser/projects/scribeAPI/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment] 2016-01-29 07:48
```
/bin/sh: 1: node: not found
```

You've probably run `sudo apt-get install nodejs`, which installs the node binary to `/usr/bin/nodejs`. If you want to get the `node` most Node.js programs require, you're either going to need to symlink `/usr/local/bin/node` to `/usr/bin/nodejs` or install the `nodejs-legacy` package (which is spectacularly misnamed, but is something to take up with the Debian JavaScript packaging team). Also, `npm@1.4.21` is no longer supported by the CLI team. You should run `sudo npm install -g npm@latest` (or `sudo npm install -g npm@lts` if you want an LTS npm to match your LTS Node). (After doing so, you'll want to run `sudo chown -R $(whoami) "$HOME/.npm"`, because it looks like some of the files in your npm cache have ended up being owned by root, which was caused by a bug in some older versions of npm.)

If you take care of those two things, that should address this problem, so I'm going to close this issue. Thanks for your time, and let us know if you have further issues.

**Closed by othiym23** 2016-01-29 07:48 UTC
Labels: support
