### ISSUE TITLE
cannot install ionic

### ISSUE THREAD

**Issue by xumes** [npm/npm#14163] opened 2016-10-03 13:57 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to install ionic from npm and it is not working. I tried a lot of suggestions I found over the webbut the issue persists.
I am on Mac El Capitain

#### How can the CLI team reproduce the problem?

[npm-debug.log.zip](https://github.com/npm/npm/files/506374/npm-debug.log.zip)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ X

] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-10-03 14:05
Looks like a duplicate of https://github.com/npm/npm/issues/14104.

**Closed by KenanY** 2016-10-03 14:05 UTC
Labels: support
