### ISSUE TITLE
Can't install ref

### ISSUE THREAD

**Issue by MrRedstonePro** [npm/npm#21059] opened 2018-06-23 14:02 UTC
#### I'm opening this issue because:

  - [ ] Some npm install packages won't install.
  - [ ] Can't see where I went wrong.

#### What's going wrong?
I'm trying to get my Discord music bot going, but first of all I need to have, or opusscript, or node-opus. I did 'npm install opusscript' and it installed succesfully. When I ran my bot, it said Error: OPUS_ENIGINE_MISSING. I've sought for help on the Discord.JS server, but no success. They said, I had to install node-opus then. So I did... I tried.. After that didn't work as well, I searched the internet. Stackoverflow, github etc. Then someone asked, 'Can you install ref using 'npm  install ref''. I tried but this was the result:

https://pastebin.com/GTqx4ccu

I'm not sure if that was the problem, but the main issue here, what do I do to fix this?
#### How can the CLI team reproduce the problem?

   1. Install node.
   2. Press WinKey+R
   3. type cmd
   4. Type inside the cmd: 'npm install ref'

### supporting information:

 - `npm -v` prints:
6.0.0
 - `node -v` prints:
8.11.3
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Windows
 - Network issues:
 - [ ]   None.
 - Container:
   Does not apply

**Comment by legodude17** [comment] 2018-06-24 00:26
Please report this to ref, as their install script is failing

**Comment by kenany** [comment] 2018-06-25 14:27
Hmm I think it's `node-gyp` trying to run `reg query`, but `reg` doesn't exist on your system. I don't know why that is the case, nor how to solve the issue unfortunately, but since the issue is not the fault of `npm` itself I'm gonna close this one out. Feel free to ask on StackOverflow if you need more support.

**Closed as completed by kenany** 2018-06-25 14:27 UTC
Labels: support
