### ISSUE TITLE
--save does not respect symlinked package.json

### ISSUE THREAD

**Issue by mntnoe** [npm/npm#12002] opened 2016-03-22 09:13 UTC
Steps to reproduce:
1. Create `package.json` as  a symlink to somewhere else.
2. Install something with the `--save` flag.
3. `package.json` is now a regular file.

We have a product line that share the same core, dependencies and build script. In order to minimize the overhead of synchronizing changes to our core during the current stage of our product lifecycle, we have opted to keep `package.json` and `node_modules` in a subdirectory using git subtree. This approach has worked really well the past year.

The problem of this approach is that some tools expect `package.json` to be in the root directory of the project. While we have been able to work around these issues, it would be nice if `npm` could respect symlinked files.

**Comment by iarna** [comment] 2016-03-22 20:41
Thanks for writing this up! This is caused by npm's attempts to make writing to the `package.json` atomic– it writes to a different file and if that succeeds replaces your existing file with the one it wrote.  But I agree that what you describe would be less surprising.  The cli core team will not be getting to this over the next year, so I'm going to close this issue, but if you want to take a crack at it, we would accept a patch to this effect.  

I think the best place for this would be in [`write-file-atomic`](https://github.com/npm/write-file-atomic) where it would see if the destination were a symlink and if so, replace the destination instead of the symlink.

**Closed by iarna** 2016-03-22 20:41 UTC
Labels: feature-request
