### ISSUE TITLE
Failed to install Mavensmate-atom package

### ISSUE THREAD

**Issue by Nicolav77** [npm/npm#17961] opened 2017-07-27 12:36 UTC
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

I can´t install mavensmate-atom package

### supporting information:
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 resetting remote C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Nicolas\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository 'C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=C:\Users\Nicolas\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: remote: Repository not found.
npm ERR! git clone --template=C:\Users\Nicolas\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Nicolas\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Nicolas\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Nicolas\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Nicolas\\.atom\\.apmrc" "install" "C:\\Users\\Nicolas\\AppData\\Local\\Temp\\d-117627-10144-53rwi3.vgan3wstt9\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Nicolas\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository 'C:\Users\Nicolas\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/Benvie/harmony-collections.git/' not found
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nicolas\AppData\Local\Temp\apm-install-dir-117627-10144-1smwwwx.amq7fzuxr\npm-debug.log

**Comment by kenany** [comment] 2017-07-27 14:20
Duplicate of https://github.com/npm/npm/issues/17925

**Closed as completed by kenany** 2017-07-27 14:20 UTC
Labels: support, git
