### ISSUE TITLE
Error install cordova using Nodejs

### ISSUE THREAD

**Issue by monbassam** [npm/npm#11561] opened 2016-02-16 10:51 UTC
Hello,
I've tride to install Cordova with npm but I got this error. Can somebody, help me...

```
C:\>npm install -g cordova
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
C:\Users\bassa\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bassa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.2
npm ERR! path C:\Users\bassa\AppData\Roaming\npm\node_modules\.staging\abbrev-3bd14f62
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\bassa\AppData\Roaming\npm\node_modules\.staging\abbrev-3bd14f62' -> 'C:\Users\bassa\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\bassa\AppData\Roaming\npm\node_modules\.staging\abbrev-3bd14f62' -> 'C:\Users\bassa\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log
npm ERR! code 1
```

**Comment by othiym23** [comment] 2016-02-16 16:54
Closing as duplicate of #11265. See that issue if you want to help the CLI team isolate and fix this bug.

**Closed by othiym23** 2016-02-16 16:54 UTC
Labels: bug, windows

**Comment by numanayhan** [comment] 2016-08-24 05:00
thanks
