### ISSUE TITLE
Unable to install modules in ubuntu.

### ISSUE THREAD

**Issue by SidVader** [npm/npm#14074] opened 2016-09-25 14:47 UTC
```
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "express" "--save"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for /tmp/npm-11364-5ff102fc/registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.1.1.tgz
npm ERR! Expected: c791d95f52b29c1247d5df80ada39b8a73647230
npm ERR! Actual:   606936856066b4091e1f5b2d7b2c5fd1c2b14977
npm ERR! From:     https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.1.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/siddhant/npm-debug.log
```

**Comment by KenanY** [comment] 2016-09-25 14:52
@SidVader Have you tried `npm cache clean`?

**Comment by SidVader** [comment] 2016-09-25 14:54
No

**Comment by SidVader** [comment] 2016-09-25 15:01
I get the error when I use npm install express/any other package --save
Is it due to the --save dependencies.

**Comment by KenanY** [comment] 2016-09-25 15:24
Nah it's just that the shasum of the downloaded package does not match what the registry says it should be. Might be a sign that someone is modifying your downloads mid-flight.

**Comment by zkat** [comment] 2016-12-09 00:37
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:37 UTC
Labels: network, support
