### ISSUE TITLE
Unable to install protractor using cmd 'npm install -g protractor'

### ISSUE THREAD

**Issue by rajega** [npm/npm#13401] opened 2016-07-16 10:15 UTC
Hi All,

I'm new to npm. 
My requirement is: Test the angular js application using protractor and jasmine frameworks
i have installed nodejs and started all required services with the help of youtube vides.

My issue is: facing issue while installing protractor in eclipse... i have followed the below link but no luck.

https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor
http://www.protractortest.org/#/

when i execute the command : 'npm install -g protractor' , getting following error.
*****************************************************************************************

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jt>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\jt\AppData\Roaming\npm\node_modules\protractor\selenium\s
elenium-server-standalone-2.52.0.jar
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall unlink

npm ERR! EBUSY: resource busy or locked, unlink 'C:\Users\jt\AppData\Roaming\npm
\node_modules\protractor\selenium\selenium-server-standalone-2.52.0.jar'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, unlink 'C:\Us
ers\jt\AppData\Roaming\npm\node_modules\protractor\selenium\selenium-server-stan
dalone-2.52.0.jar'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, unlink 'C
:\Users\jt\AppData\Roaming\npm\node_modules\protractor\selenium\selenium-server-
standalone-2.52.0.jar']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: 'C:\\Users\\jt\\AppData\\Roaming\\npm\\node_
modules\\protractor\\selenium\\selenium-server-standalone-2.52.0.jar' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jt\npm-debug.log

C:\Users\jt>
```
**************************************************************************************
please please help me. this is an urgent requirement for my project.

Thanks,
Raju Ega

**Comment by anglichanen** [comment] 2016-08-12 13:07
[13:56:40][Step 3/19] npm WARN package.json nemlig@1.0.0 No repository field.
[13:56:40][Step 3/19] npm WARN package.json nemlig@1.0.0 No README data
[13:57:41][Step 3/19] npm WARN optional dep failed, continuing fsevents@1.0.14
[13:58:28][Step 3/19] npm ERR! Windows_NT 6.3.9600
[13:58:28][Step 3/19] npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[13:58:28][Step 3/19] npm ERR! node v0.12.7
[13:58:28][Step 3/19] npm ERR! npm  v2.11.3
[13:58:28][Step 3/19] npm ERR! path \\inter-olymp.local\files\appdata\pavlo.shchyrba\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.aa4c19bd5127bc4171f7fb1b23891fed
[13:58:28][Step 3/19] npm ERR! code EBUSY
[13:58:28][Step 3/19] npm ERR! errno -4082
[13:58:28][Step 3/19] 
[13:58:28][Step 3/19] npm ERR! EBUSY, rename '\\inter-olymp.local\files\appdata\pavlo.shchyrba\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.aa4c19bd5127bc4171f7fb1b23891fed'
[13:58:28][Step 3/19] npm ERR! 
[13:58:28][Step 3/19] npm ERR! If you need help, you may report this error at:
[13:58:28][Step 3/19] npm ERR!     <https://github.com/npm/npm/issues>;
[13:58:29][Step 3/19] 
[13:58:29][Step 3/19] npm ERR! Please include the following file with any support request:


the same error for me. How it can be fixed? Re-install of npm does not help. Also server reboot also have no success.

Please, take a look on this.

**Comment by othiym23** [comment] 2016-08-19 22:37
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 22:37 UTC
Labels: support, windows
