### ISSUE TITLE
NODE_ENV=production and package-lock.json

### ISSUE THREAD

**Issue by fibo** [npm/npm#17255] opened 2017-06-16 13:00 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

My current scenario is: I am developing locally (`NODE_ENV` environment variable is not set), then I deploy on a server where in my profile I have

```bash
export NODE_ENV=production
```

I am versioning *package-lock.json* file as suggested, and two of my deploy steps are to launch a `git pull` and then an`npm install` to update deps on my server side project.
When I perform this step, since my *package-lock.json* was created and committed locally, and I also need to install dev dependencies, there are some development dependencies listed. Then
when I deploy, since I install no dev dep on the server, cause of the `NODE_ENV` var, my *package-lock.json* has some changes. If I launch a `git diff` they are exactly the development dependecies removed from the lock file. Since the *package-lock.json* file is changed, I cannot do another `git pull`.

Which is the suggested solution?

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by fibo** [comment] 2017-06-19 08:18
As a workaround, by now I am setting server side `npm config set package-lock false`, this solves my git issue but I lose deterministic dependency installs.

**Comment by jyotman** [comment] 2017-06-23 07:34
This is the same issue I'm facing #16967

**Comment by zkat** [comment] 2017-07-01 04:59
Closing as a duplicate o https://github.com/npm/npm/issues/16967. The issue is also fixed (see dupe issue)

**Closed as completed by zkat** 2017-07-01 04:59 UTC
