### ISSUE TITLE
shasum check failed for /tmp/npm-6438-1d9ad5d9/registry.npmjs.org/ionic/-/ionic-1.7.12.tgz

### ISSUE THREAD

**Issue by shiva2492** [npm/npm#10943] opened 2015-12-23 17:22 UTC
whenever I install ionic through npm it gives shashum error I have even tried npm cache clean but nothing works.I am working on a ubuntu 12.04 and have following issues ...

```
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9

npm ERR! shasum check failed for /tmp/npm-6438-1d9ad5d9/registry.npmjs.org/ionic/-/ionic-1.7.12.tgz
npm ERR! Expected: 87cdf5b9ff748009182a10c61bbc3a39a000fe59
npm ERR! Actual:   4238d66d98fa64f3338c9e97bf4e09fe04a87578
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.12.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shiva/npm-debug.log
```

**Comment by cithukyaw** [comment] 2015-12-26 03:55
Same error in Windows 7 with git bash:

    $ npm install -g ionic
    /c/Program Files/nodejs/npm: line 6: uname: command not found
    /c/Program Files/nodejs/npm: line 17: uname: command not found
    npm ERR! Windows_NT 6.1.7600
    npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\b
    in\\npm-cli.js" "install" "-g" "ionic"
    npm ERR! node v4.2.3
    npm ERR! npm  v2.14.7

    npm ERR! shasum check failed for C:\Users\TPP\AppData\Local\Temp\npm-1540-82baa0b4\registry.npmjs.or
    g\ionic\-\ionic-1.7.12.tgz
    npm ERR! Expected: 87cdf5b9ff748009182a10c61bbc3a39a000fe59
    npm ERR! Actual:   1e90fbe289f198206672054fddf17fe32958fd13
    npm ERR! From:     http://registry.npmjs.org/ionic/-/ionic-1.7.12.tgz
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\nodejsapp\ion-todo\npm-debug.log

**Comment by girishsortur** [comment] 2015-12-27 07:19
I am also getting same error when trying to install packages locally. Here's the error -
```
npm ERR! registry error parsing json
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "protractor" "--save-dev"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2

npm ERR! shasum check failed for /var/folders/f8/0jp3fzdx2pvbrhbb1qxhsl6h0000gn/T/npm-967-28ec6481/registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.47.0.tgz
npm ERR! Expected: e29b52d2daa0f648c40f602f4d2a8e8bee351ea5
npm ERR! Actual:   f9db642de62cb81f0f297b5ad1e518e61ec8d7ac
npm ERR! From:     https://registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.47.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ibm/Desktop/Work/test_js/npm-debug.log
```

**Comment by shiva2492** [comment] 2015-12-27 07:53
Is it some kind of bug ?
Cause now me and you two have the problem with installation so someone from the ionic community should do something about it.

**Comment by girishsortur** [comment] 2015-12-27 12:12
I am getting this error for all packages that i am trying to install. Not sure of the cause, but i even tried running following commands and yet they didn't work - 

```
npm uninstall -g <package>
npm cache clean
npm cache clean <package>
npm config set registry <npm-registry-url>
```
Hope it gets resolved soon.

**Comment by shiva2492** [comment] 2016-05-27 20:47
any solution for the same ?

**Comment by zkat** [comment] 2016-12-09 00:49
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:49 UTC
Labels: shasum, support
