### ISSUE TITLE
unable to install oracledb

### ISSUE THREAD

**Issue by rapidosai** [npm/npm#11147] opened 2016-01-14 09:54 UTC
I am unable to install oracledb by doing npm install oracledb
This is the error I am getting, 

```
npm ERR! EBUSY, rmdir 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY, rmdir 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, rmdir 'C:\Users\vsaipras\Desktop\nodeoracle\node_modules\oracledb\build']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Users\\vsaipras\\Desktop\\nodeoracle\\node_modules\\oracledb\\build' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vsaipras\Desktop\nodeoracle\npm-debug.log
```

**Comment by othiym23** [comment] 2016-08-19 21:55
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:55 UTC
Labels: support, windows
