### ISSUE TITLE
blur-admin-master templete not install npm

### ISSUE THREAD

**Issue by krrishkbk** [npm/npm#15994] opened 2017-03-10 07:10 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:426:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
5 verbose cwd D:\test\blur-admin-master
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v7.4.0
9 error npm  v4.0.5
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-03-10 22:35
Hello! The error log said you're missing the `start` script. To use `npm start`, you need to put it into the script field in your package.json like:

{
  "script": {
    "start": "echo hi"
  }
}
See this example for your reference: https://docs.npmjs.com/misc/scripts#examples

Thanks

**Comment by KenanY** [comment] 2017-03-11 01:49
Closing since @legodude17 is correct here. This is `npm` working as intended. Feel free to continue discussion here if you still need assistance writing a `"start"` script.

**Closed by KenanY** 2017-03-11 01:49 UTC

**Comment by krrishkbk** [comment] 2017-03-14 06:02
77 verbose linkBins blur_admin@1.3.1
78 verbose linkMans blur_admin@1.3.1
79 silly install blur_admin@1.3.1
80 info lifecycle blur_admin@1.3.1~install: blur_admin@1.3.1
81 silly lifecycle blur_admin@1.3.1~install: no script for install, continuing
82 silly postinstall blur_admin@1.3.1
83 info lifecycle blur_admin@1.3.1~postinstall: blur_admin@1.3.1
84 verbose lifecycle blur_admin@1.3.1~postinstall: unsafe-perm in lifecycle true
85 verbose lifecycle blur_admin@1.3.1~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\test\blur-admin-master\node_modules\.bin;C:\Users\kishor.kadam\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Smart Projects\IsoBuster;C:\Users\kishor.kadam\AppData\Roaming\npm;.bin
86 verbose lifecycle blur_admin@1.3.1~postinstall: CWD: D:\test\blur-admin-master
87 silly lifecycle blur_admin@1.3.1~postinstall: Args: [ '/d /s /c', 'bower install' ]
88 silly lifecycle blur_admin@1.3.1~postinstall: Returned: code: 1  signal: null
89 info lifecycle blur_admin@1.3.1~postinstall: Failed to exec postinstall script
90 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
91 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
92 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
92 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
92 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
92 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
93 warn blur_admin@1.3.1 No repository field.
94 verbose If you need help, you may report this error at:
94 verbose     <https://github.com/npm/npm/issues>
95 warn blur_admin@1.3.1 No license field.
96 verbose If you need help, you may report this error at:
96 verbose     <https://github.com/npm/npm/issues>
97 verbose stack Error: blur_admin@1.3.1 postinstall: `bower install`
97 verbose stack Exit status 1
97 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
97 verbose stack     at emitTwo (events.js:106:13)
97 verbose stack     at EventEmitter.emit (events.js:191:7)
97 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
97 verbose stack     at emitTwo (events.js:106:13)
97 verbose stack     at ChildProcess.emit (events.js:191:7)
97 verbose stack     at maybeClose (internal/child_process.js:885:16)
97 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
98 verbose pkgid blur_admin@1.3.1
99 verbose cwd D:\test\blur-admin-master
100 error Windows_NT 6.1.7601
101 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
102 error node v7.4.0
103 error npm  v4.0.5
104 error code ELIFECYCLE
105 error blur_admin@1.3.1 postinstall: `bower install`
105 error Exit status 1
106 error Failed at the blur_admin@1.3.1 postinstall script 'bower install'.
106 error Make sure you have the latest version of node.js and npm installed.
106 error If you do, this is most likely a problem with the blur_admin package,
106 error not with npm itself.
106 error Tell the author that this fails on your system:
106 error     bower install
106 error You can get information on how to open an issue for this project with:
106 error     npm bugs blur_admin
106 error Or if that isn't available, you can get their info via:
106 error     npm owner ls blur_admin
106 error There is likely additional logging output above.
107 verbose exit [ 1, true ]
