### ISSUE TITLE
npm 3 install generates broken flattened hierarchy

### ISSUE THREAD

**Issue by jfirebaugh** [npm/npm#11881] opened 2016-03-13 04:34 UTC
With node v5.8.0, npm 3.7.3, and the following package.json:

```
{
  "dependencies": {
    "babel-core": "^6.5.2"
  },
  "devDependencies": {
    "lodash": "~4.3.0"
  }
}
```

Run `npm install`.

Then, `npm ls` outputs:

```
├─┬ babel-core@6.7.2
│ ├─┬ babel-code-frame@6.7.2
│ │ ├─┬ chalk@1.1.1
│ │ │ ├─┬ ansi-styles@2.2.0
│ │ │ │ └── color-convert@1.0.0
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.1
│ │ │ └── supports-color@2.0.0
│ │ ├── esutils@2.0.2
│ │ ├── js-tokens@1.0.2
│ │ ├─┬ line-numbers@0.2.0
│ │ │ └── left-pad@0.0.3
│ │ └─┬ repeating@1.1.3
│ │   └─┬ is-finite@1.0.1
│ │     └── number-is-nan@1.0.0
│ ├─┬ babel-generator@6.7.2
│ │ ├─┬ detect-indent@3.0.1
│ │ │ ├── get-stdin@4.0.1
│ │ │ └── minimist@1.2.0
│ │ ├── is-integer@1.0.6
│ │ ├── UNMET DEPENDENCY lodash@^3.10.1
│ │ └── trim-right@1.0.1
│ ├── babel-helpers@6.6.0
│ ├── babel-messages@6.7.2
│ ├─┬ babel-register@6.7.2
│ │ ├── core-js@2.1.5
│ │ ├─┬ home-or-tmp@1.0.0
│ │ │ ├── os-tmpdir@1.0.1
│ │ │ └── user-home@1.1.1
│ │ ├── UNMET DEPENDENCY lodash@^3.10.0
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ └─┬ source-map-support@0.2.10
│ │   └─┬ source-map@0.1.32
│ │     └── amdefine@1.0.0
│ ├─┬ babel-runtime@5.8.35
│ │ └── core-js@1.2.6
│ ├─┬ babel-template@6.7.0
│ │ └── UNMET DEPENDENCY lodash@^3.10.1
│ ├─┬ babel-traverse@6.7.3
│ │ ├── globals@8.18.0
│ │ ├─┬ invariant@2.2.1
│ │ │ └── loose-envify@1.1.0
│ │ └── UNMET DEPENDENCY lodash@^3.10.1
│ ├─┬ babel-types@6.7.2
│ │ ├── UNMET DEPENDENCY lodash@^3.10.1
│ │ └── to-fast-properties@1.0.1
│ ├── babylon@6.7.0
│ ├── convert-source-map@1.2.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── json5@0.4.0
│ ├── UNMET DEPENDENCY lodash@^3.10.0
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.3
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├── path-exists@1.0.0
│ ├── path-is-absolute@1.0.0
│ ├── private@0.1.6
│ ├── shebang-regex@1.0.0
│ ├── slash@1.0.0
│ └── source-map@0.5.3
└── lodash@4.3.0

npm ERR! missing: lodash@^3.10.0, required by babel-core@6.7.2
npm ERR! missing: lodash@^3.10.1, required by babel-generator@6.7.2
npm ERR! missing: lodash@^3.10.0, required by babel-register@6.7.2
npm ERR! missing: lodash@^3.10.1, required by babel-template@6.7.0
npm ERR! missing: lodash@^3.10.1, required by babel-traverse@6.7.3
npm ERR! missing: lodash@^3.10.1, required by babel-types@6.7.2
```

And babel-core is broken:

```
$ node -e "require('babel-core')"
module.js:341
    throw err;
    ^

Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/john/Development/scratch/node_modules/babel-core/lib/api/node.js:14:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by jfirebaugh** [comment] 2016-03-13 04:42
Looks like this may be a duplicate of #11766.

**Comment by perlun** [comment] 2016-03-22 07:54
I am seeing something similar with `ember-cli`; certain combinations of `dependencies` and `devDependencies` cause these highly annoying bugs. In my case, it's the `mktemp` package that doesn't get resolved as a dependency from `quick-temp`.

**Comment by zkat** [comment] 2016-03-25 23:56
Like @jfirebaugh pointed out, this is a duplicate of #11766, so I'm closing it as such. Please keep an eye on that one, and thanks for reporting this!

**Closed by zkat** 2016-03-25 23:56 UTC
Labels: big-bug
