### ISSUE TITLE
npm error missing script: build

### ISSUE THREAD

**Issue by LeeJim** [npm/npm#14669] opened 2016-11-19 10:12 UTC
it is weird.

when i commit my git. something was happened:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false commit -q -F C:\Users\Administrator\AppData\Local\Temp\ytg3mlfm.jbp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>










npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\WEB-Projects\guosen-fenjile-client-web\npm-debug.log
```

is any one can help me?

**Comment by KenanY** [comment] 2016-11-19 15:16
@LeeJim Make sure you have a `"build"` script defined in your `package.json`. See [this page](https://docs.npmjs.com/misc/scripts) for how to write your own npm scripts.

**Comment by LeeJim** [comment] 2016-11-21 07:51
@KenanY 

here is my npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:425:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
5 verbose cwd C:\Program Files\WEB-Projects\guosen-fenjile-client-web
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 error node v7.0.0
9 error npm  v3.10.8
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

i think is was not the `"build"'s problem.

**Comment by KenanY** [comment] 2016-11-21 14:14
@LeeJim Nah, this is still a problem on your end only. Again, you are trying to run `npm run build` but you have not yet defined a `"build"` script in your `package.json`. Hence, you are receiving that "missing script" error, because you are asking `npm` to do something that it does not know how to do.

**Comment by KenanY** [comment] 2016-12-03 16:55
Closing since this is expected behavior.

**Closed by KenanY** 2016-12-03 16:55 UTC
Labels: support

**Comment by veljkocasa** [comment] 2017-07-21 08:41
Hi @KenanY , I am experiencing the same issue with configured 
```
 "scripts": {
            "build": "ionic-app-scripts build",
            "serve": "ionic-app-scripts serve"
        }
```
I tried also with "ionic:build" and calling it like that from cmd but nothing ...
Any suggestion ?

**Comment by kenany** [comment] 2017-07-21 14:09
@veljkocasa I suggest opening a new issue with the full debug log and your `package.json`.
