### ISSUE TITLE
Github install with hashref broke in 5.0.1

### ISSUE THREAD

**Issue by ericeslinger** [npm/npm#16846] opened 2017-06-01 03:10 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can't install gulp 4.0 anymore, specifically.

#### How can the CLI team reproduce the problem?

```
mkdir foo && cd foo && npm init
npm i  github:gulpjs/gulp#4.0
```

Note that I am successfully able to install *other* hashreffed npm packages off of github, and I'm also able to install github:gulpjs/gulp, so I'm not entirely sure what the error is - it could be gulp. All I know is that this worked in 5.0.0 and fails in 5.0.1

Error gist: https://gist.github.com/ericeslinger/5b72014f39765acd7ab31b1c190cf679

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run: frisco

**Comment by zkat** [comment] 2017-06-01 04:29
lol FML.

I fixed this in pacote -- it will go into the next release.

I also ended up publishing https://npm.im/npmc as a "canary" version of npm for folks who want faster updates as we merge them into `release-next`. The release process for this one can be a bit lighterweight, which is nice! You can `npm i -g npmc` and you'll get a separate `npmc` binary. It'll notify you as updates come in. Cheers~

I'm closing this because I've confirmed it works in `npmc`.

**Closed as completed by zkat** 2017-06-01 04:29 UTC
Labels: git, npm5
