### ISSUE TITLE
npm man pages are broken after running install.sh

### ISSUE THREAD

**Issue by oshybystyi** [npm/npm#8210] opened 2015-05-08 09:15 UTC
#### Pre-steps:

debian jessie on virtual box
npm ~~2.9.0~~ 2.9.1

``` sh
# going to root
sudo -s
apt-get install nodejs nodejs-legacy -y
curl -L http://npmjs.com/install.sh > install.sh
# without set -o -pipefail installation fails, hm :(
npm_debug=1 set -o pipefail && sh install.sh
```
### Bug

After that having npm installed in **/usr/lib/node_modules/npm** - so that's good.
But `man npm` - outputs:

``` sh
man: warning: /usr/share/man/man1/npm.1 is a dangling symlink
man: warning: /usr/share/man/man3/npm.3 is a dangling symlink
No manual entry for npm
See 'man 7 undocumented' for help when manual pages are not available.
```

Output from ls command:

``` sh
root@debianvbox:/media/sf_Debian# ls -l /usr/share/man/man1/npm.1
lrwxrwxrwx 1 root root 36 тра  7 11:52 /usr/share/man/man1/npm.1 -> /tmp/npm.7371/package/man/man1/npm.1
```

So it links to temporary folder and not to **/usr/lib/node_modules/npm/man/man1/npm.1**

**Comment by othiym23** [comment] 2015-05-08 10:25
This looks like it could be a consequence of mixing the Debian-packaged Node / npm with source installations. Does this problem occur if you build and install Node and npm from a Node source tarball and then run `sudo npm -g install npm`? If not, then it's not something that we can really do anything about, because the Debian packaging for Node / npm that you're starting from is not something over which the npm team has control.

**Comment by oshybystyi** [comment] 2015-05-08 12:57
@othiym23 with `npm -g install npm` - problem is still present

**Comment by remcohaszing** [comment] 2016-03-01 08:17
Any news on this? This problem still persists. I have installed `npm` in the `~/.local` prefix using the `install.sh` script ignoring the one that comes with NodeJS from the PPA. I've installed some other tools and at least upgraded `npm` once.

All references to the `npm` man pages are dead links, referring to `/tmp`. The link to the one other tool installed using `npm` (`gulp`) seems to be just fine:

```
$ tree .local/share/man/
.local/share/man/
├── man1
│   ├── gulp.1 -> ../../../lib/node_modules/gulp/gulp.1
│   ├── npm.1 -> /tmp/npm.22184/package/man/man1/npm.1
│   ├── npm-access.1 -> /tmp/npm.22184/package/man/man1/npm-access.1
│   ├── npm-adduser.1 -> /tmp/npm.22184/package/man/man1/npm-adduser.1
│   ├── npm-bin.1 -> /tmp/npm.22184/package/man/man1/npm-bin.1
│   ├── npm-bugs.1 -> /tmp/npm.22184/package/man/man1/npm-bugs.1
│   ├── npm-build.1 -> /tmp/npm.22184/package/man/man1/npm-build.1
│   ├── npm-bundle.1 -> /tmp/npm.22184/package/man/man1/npm-bundle.1
│   ├── npm-cache.1 -> /tmp/npm.22184/package/man/man1/npm-cache.1
│   ├── npm-completion.1 -> /tmp/npm.22184/package/man/man1/npm-completion.1
│   ├── npm-config.1 -> /tmp/npm.22184/package/man/man1/npm-config.1
│   ├── npm-dedupe.1 -> /tmp/npm.22184/package/man/man1/npm-dedupe.1
│   ├── npm-deprecate.1 -> /tmp/npm.22184/package/man/man1/npm-deprecate.1
│   ├── npm-dist-tag.1 -> /tmp/npm.22184/package/man/man1/npm-dist-tag.1
│   ├── npm-docs.1 -> /tmp/npm.22184/package/man/man1/npm-docs.1
│   ├── npm-edit.1 -> /tmp/npm.22184/package/man/man1/npm-edit.1
│   ├── npm-explore.1 -> /tmp/npm.22184/package/man/man1/npm-explore.1
│   ├── npm-help.1 -> /tmp/npm.22184/package/man/man1/npm-help.1
│   ├── npm-help-search.1 -> /tmp/npm.22184/package/man/man1/npm-help-search.1
│   ├── npm-init.1 -> /tmp/npm.22184/package/man/man1/npm-init.1
│   ├── npm-install.1 -> /tmp/npm.22184/package/man/man1/npm-install.1
│   ├── npm-install-test.1 -> /tmp/npm.22184/package/man/man1/npm-install-test.1
│   ├── npm-link.1 -> /tmp/npm.22184/package/man/man1/npm-link.1
│   ├── npm-logout.1 -> /tmp/npm.22184/package/man/man1/npm-logout.1
│   ├── npm-ls.1 -> /tmp/npm.22184/package/man/man1/npm-ls.1
│   ├── npm-outdated.1 -> /tmp/npm.22184/package/man/man1/npm-outdated.1
│   ├── npm-owner.1 -> /tmp/npm.22184/package/man/man1/npm-owner.1
│   ├── npm-pack.1 -> /tmp/npm.22184/package/man/man1/npm-pack.1
│   ├── npm-ping.1 -> /tmp/npm.22184/package/man/man1/npm-ping.1
│   ├── npm-prefix.1 -> /tmp/npm.22184/package/man/man1/npm-prefix.1
│   ├── npm-prune.1 -> /tmp/npm.22184/package/man/man1/npm-prune.1
│   ├── npm-publish.1 -> /tmp/npm.22184/package/man/man1/npm-publish.1
│   ├── npm-README.1 -> /tmp/npm.22184/package/man/man1/npm-README.1
│   ├── npm-rebuild.1 -> /tmp/npm.22184/package/man/man1/npm-rebuild.1
│   ├── npm-repo.1 -> /tmp/npm.22184/package/man/man1/npm-repo.1
│   ├── npm-restart.1 -> /tmp/npm.22184/package/man/man1/npm-restart.1
│   ├── npm-root.1 -> /tmp/npm.22184/package/man/man1/npm-root.1
│   ├── npm-run-script.1 -> /tmp/npm.22184/package/man/man1/npm-run-script.1
│   ├── npm-search.1 -> /tmp/npm.22184/package/man/man1/npm-search.1
│   ├── npm-shrinkwrap.1 -> /tmp/npm.22184/package/man/man1/npm-shrinkwrap.1
│   ├── npm-star.1 -> /tmp/npm.22184/package/man/man1/npm-star.1
│   ├── npm-stars.1 -> /tmp/npm.22184/package/man/man1/npm-stars.1
│   ├── npm-start.1 -> /tmp/npm.22184/package/man/man1/npm-start.1
│   ├── npm-stop.1 -> /tmp/npm.22184/package/man/man1/npm-stop.1
│   ├── npm-tag.1 -> /tmp/npm.22184/package/man/man1/npm-tag.1
│   ├── npm-team.1 -> /tmp/npm.22184/package/man/man1/npm-team.1
│   ├── npm-test.1 -> /tmp/npm.22184/package/man/man1/npm-test.1
│   ├── npm-uninstall.1 -> /tmp/npm.22184/package/man/man1/npm-uninstall.1
│   ├── npm-unpublish.1 -> /tmp/npm.22184/package/man/man1/npm-unpublish.1
│   ├── npm-update.1 -> /tmp/npm.22184/package/man/man1/npm-update.1
│   ├── npm-version.1 -> /tmp/npm.22184/package/man/man1/npm-version.1
│   ├── npm-view.1 -> /tmp/npm.22184/package/man/man1/npm-view.1
│   └── npm-whoami.1 -> /tmp/npm.22184/package/man/man1/npm-whoami.1
├── man5
│   ├── npm-folders.5 -> /tmp/npm.22184/package/man/man5/npm-folders.5
│   ├── npm-global.5 -> /tmp/npm.22184/package/man/man5/npm-global.5
│   ├── npm-json.5 -> /tmp/npm.22184/package/man/man5/npm-json.5
│   ├── npmrc.5 -> /tmp/npm.22184/package/man/man5/npmrc.5
│   └── package.json.5 -> /tmp/npm.22184/package/man/man5/package.json.5
└── man7
    ├── npm-coding-style.7 -> /tmp/npm.22184/package/man/man7/npm-coding-style.7
    ├── npm-config.7 -> /tmp/npm.22184/package/man/man7/npm-config.7
    ├── npm-developers.7 -> /tmp/npm.22184/package/man/man7/npm-developers.7
    ├── npm-disputes.7 -> /tmp/npm.22184/package/man/man7/npm-disputes.7
    ├── npm-index.7 -> /tmp/npm.22184/package/man/man7/npm-index.7
    ├── npm-orgs.7 -> /tmp/npm.22184/package/man/man7/npm-orgs.7
    ├── npm-registry.7 -> /tmp/npm.22184/package/man/man7/npm-registry.7
    ├── npm-scope.7 -> /tmp/npm.22184/package/man/man7/npm-scope.7
    ├── npm-scripts.7 -> /tmp/npm.22184/package/man/man7/npm-scripts.7
    ├── removing-npm.7 -> /tmp/npm.22184/package/man/man7/removing-npm.7
    └── semver.7 -> /tmp/npm.22184/package/man/man7/semver.7
```

**Comment by remcohaszing** [comment] 2016-03-25 13:18
I just found out the same problem also exists on OSX when installing `npm` manually after installing `nodejs` using `brew`.

If I recall correcty, this is how to reproduce it:
```sh
$ brew install node --without-npm
$ curl -L https://www.npmjs.com/install.sh | npm_config_prefix=/usr/local sh
```
I have updated `npm` using `npm` several times after this. The `npm` `man` pages also appear to be broken symlinks in this case.
```sh
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/share/man/man1/npm-README.1
    /usr/local/share/man/man1/npm-access.1
    /usr/local/share/man/man1/npm-adduser.1
    /usr/local/share/man/man1/npm-bin.1
    /usr/local/share/man/man1/npm-bugs.1
    /usr/local/share/man/man1/npm-build.1
    /usr/local/share/man/man1/npm-bundle.1
    /usr/local/share/man/man1/npm-cache.1
    /usr/local/share/man/man1/npm-completion.1
    /usr/local/share/man/man1/npm-config.1
    /usr/local/share/man/man1/npm-dedupe.1
    /usr/local/share/man/man1/npm-deprecate.1
    /usr/local/share/man/man1/npm-dist-tag.1
    /usr/local/share/man/man1/npm-docs.1
    /usr/local/share/man/man1/npm-edit.1
    /usr/local/share/man/man1/npm-explore.1
    /usr/local/share/man/man1/npm-help-search.1
    /usr/local/share/man/man1/npm-help.1
    /usr/local/share/man/man1/npm-init.1
    /usr/local/share/man/man1/npm-install-test.1
    /usr/local/share/man/man1/npm-install.1
    /usr/local/share/man/man1/npm-link.1
    /usr/local/share/man/man1/npm-logout.1
    /usr/local/share/man/man1/npm-ls.1
    /usr/local/share/man/man1/npm-outdated.1
    /usr/local/share/man/man1/npm-owner.1
    /usr/local/share/man/man1/npm-pack.1
    /usr/local/share/man/man1/npm-ping.1
    /usr/local/share/man/man1/npm-prefix.1
    /usr/local/share/man/man1/npm-prune.1
    /usr/local/share/man/man1/npm-publish.1
    /usr/local/share/man/man1/npm-rebuild.1
    /usr/local/share/man/man1/npm-repo.1
    /usr/local/share/man/man1/npm-restart.1
    /usr/local/share/man/man1/npm-root.1
    /usr/local/share/man/man1/npm-run-script.1
    /usr/local/share/man/man1/npm-search.1
    /usr/local/share/man/man1/npm-shrinkwrap.1
    /usr/local/share/man/man1/npm-star.1
    /usr/local/share/man/man1/npm-stars.1
    /usr/local/share/man/man1/npm-start.1
    /usr/local/share/man/man1/npm-stop.1
    /usr/local/share/man/man1/npm-tag.1
    /usr/local/share/man/man1/npm-team.1
    /usr/local/share/man/man1/npm-test.1
    /usr/local/share/man/man1/npm-uninstall.1
    /usr/local/share/man/man1/npm-unpublish.1
    /usr/local/share/man/man1/npm-update.1
    /usr/local/share/man/man1/npm-version.1
    /usr/local/share/man/man1/npm-view.1
    /usr/local/share/man/man1/npm-whoami.1
    /usr/local/share/man/man1/npm.1
    /usr/local/share/man/man5/npm-folders.5
    /usr/local/share/man/man5/npm-global.5
    /usr/local/share/man/man5/npm-json.5
    /usr/local/share/man/man5/npmrc.5
    /usr/local/share/man/man5/package.json.5
    /usr/local/share/man/man7/npm-coding-style.7
    /usr/local/share/man/man7/npm-config.7
    /usr/local/share/man/man7/npm-developers.7
    /usr/local/share/man/man7/npm-disputes.7
    /usr/local/share/man/man7/npm-index.7
    /usr/local/share/man/man7/npm-orgs.7
    /usr/local/share/man/man7/npm-registry.7
    /usr/local/share/man/man7/npm-scope.7
    /usr/local/share/man/man7/npm-scripts.7
    /usr/local/share/man/man7/removing-npm.7
    /usr/local/share/man/man7/semver.7
```

**Comment by remcohaszing** [comment] 2016-10-18 08:33
Just reinstalled npm. The issue still exists.

This issue is incorrectly marked as *support*. It is definitely a bug, so perhaps the label should be updated.

I've created a shell script to fix the man pages:
```sh
#!/usr/bin/env bash

prefix="$(npm prefix --global)"

for pagesource in $prefix/lib/node_modules/npm/man/*/*; do
  relative="$(basename "$(dirname $pagesource)")/$(basename $pagesource)"
  pagedest="$prefix/share/man/$relative"
  mkdir -p "$(dirname $pagedest)"
  ln --symbolic --verbose --force --relative "$pagesource" "$pagedest"
done

```

**Closed** 2017-06-17 02:58 UTC
Labels: bot-closed, support
