### ISSUE TITLE
shasum check failed for /tmp/npm-7258-0f974c30/registry.npmjs.org/ionic/-/ionic-2.2.1.tgz

### ISSUE THREAD

**Issue by 3jFernando** [npm/npm#15540] opened 2017-01-20 15:50 UTC
![captura de pantalla de 2017-01-20 10-31-52](https://cloud.githubusercontent.com/assets/14837781/22155646/277331e6-defe-11e6-86fb-ba64a00a26a0.png)

tengo el siguiente problema tratando de instalar Ionic:

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-7258-0f974c30/registry.npmjs.org/ionic/-/ionic-2.2.1.tgz
npm ERR! Expected: 2b9d90b3ae109138084473282c18ea162a5f8248
npm ERR! Actual:   080144bfff7a6210fd6f98ec96f58699eeec3281
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.2.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment] 2017-01-20 18:07
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-02-03 13:06 UTC
