### ISSUE TITLE
Option to automatically save dependencies to package.json

### ISSUE THREAD

**Issue by ariporad** [npm/npm#8945] opened 2015-07-15 01:18 UTC
Hi Everyone,

I'll skip the praise of npm, and ask my question:

If I submitted a pull request giving you an option in your package.json to automatically save dependencies without the --save flag, would it be accepted?

Here's why:
Everywhere on the internet, it lists installing as `npm install mysuperawesomepackage`, which really it's `npm install --save mysuperawesomepackage`, if you're being a good developer and putting your dependencies into your package.json. This causes the problem that you have to hold down the left arrow in the terminal till you get before the name of the package, type `--save`, then hit enter, as opposed to simply copy and pasting. Therefore, it would make a lot of sense to have the `--save` flag be automatic.

Also, the `--save-dev` flag could override that.

Thoughts?

**Comment by KenanY** [comment] 2015-07-15 02:49
@ariporad Just set `save` to `true` in your global config :)

**Comment by ariporad** [comment] 2015-07-15 02:49
Oh… :face palm:


Thanks!Ari

**Comment by KenanY** [comment] 2015-07-15 02:51
@ariporad But you're right that the most common case involves `--save`. Duplicate of https://github.com/npm/npm/issues/5108 :)

**Comment by othiym23** [comment] 2015-07-15 03:33
Closing as resolved / a duplicate of #5108.

**Closed by othiym23** 2015-07-15 03:33 UTC
