### ISSUE TITLE
Linux: npm pack skipping "README.md" when ignoring ".npmignore" with installed node_modules

### ISSUE THREAD

**Issue by stevenbenner** [npm/npm#12542] opened 2016-05-01 22:15 UTC
I've spent a couple hours trying to debug this, but I'm having a very hard time tracking down the source of this issue. It's not as simple as the title makes it sound and I have not been able to create a reduced test cast to demonstrate it.

##### Environment:
```
~ > uname -rs
Linux 4.5.1-1-ARCH
~ > node --version
v6.0.0
~ > npm --version
3.8.8
```

##### Reproduction steps:

1. `git clone https://github.com/stevenbenner/jquery-powertip.git`
2. `cd jquery-powertip`
4. `npm pack`
5. `tar -tvf jquery-powertip-1.2.0.tgz` (see that README.md is in the tgz file)
6. `npm install`
7. `npm pack`
8. `tar -tvf jquery-powertip-1.2.0.tgz` (see that README.md is no longer in the tgz file)
9. Remove or comment out ".npmignore" from the .npmignore file in the root
10. `npm pack`
11. `tar -tvf jquery-powertip-1.2.0.tgz` (see that README.md has returned)

##### Testing notes:

* Repro on Arch Linux x86_64 on regular desktop and Arch Linux Arm on Raspberry Pi
* Did not repro on Window 7 (with node 6.0.0 and npm 3.8.6)
* Did not test on Mac OSX
* Did not test on any other Linux distos

##### Debugging notes:

* README.md doesn’t look to be caught by the filters
  * It still exists in the entries list in fstream-ignore after `filterEntries` ([code](https://github.com/npm/fstream-ignore/blob/86c835eef61049496003f6b90c1e6c1236c92d6a/ignore.js#L181))
* It looks like the file simply never gets `stat`ed
  * The root README.md never appears in the `_entryStat` event ([code](https://github.com/npm/fstream-ignore/blob/86c835eef61049496003f6b90c1e6c1236c92d6a/ignore.js#L59))
* For some reason it's the combination of my node_modules folder and the .npmignore that's causing the problem

I'd appreciate it if someone more familiar with the npm code could take a look, or offer any debugging tips. Or even just a report that someone else could reproduce this issue so I would know if it's just me.

**Comment by boennemann** [comment] 2016-05-02 12:17
I can confirm that the README.md file is missing from published tarballs (only) with Node 6. Played around and even when the README.md is explicitly added to `files` it does not end up in the tarball.
We didn't use an npmignore file, only `files`.

Happened to us on a Travis box, Node 6.0.0, npm 3.8.6: https://travis-ci.org/greenkeeperio/greenkeeper/jobs/126721422

**Comment by blyork** [comment] 2016-05-02 19:25
I am having a similar issue after updating to Node 6 on Ubuntu 16.04.

Version:
```
$ node --version
v6.0.0

$ npm --version
3.8.6
```
Here is the root of my projects directory structure:
```
$ ls -la
total 64
drwxrwxr-x   5 blyork blyork  4096 May  2 14:26 .
drwxrwxr-x  22 blyork blyork  4096 Apr 27 19:06 ..
drwxrwxr-x   8 blyork blyork  4096 May  2 14:13 .git
-rw-rw-r--   1 blyork blyork   409 Apr 27 18:25 .gitignore
-rw-rw-r--   1 blyork blyork  7355 May  2 12:07 gulpfile.js
-rw-rw-r--   1 blyork blyork  5019 May  2 12:26 index.js
-rw-rw-r--   1 blyork blyork   567 Apr 27 18:25 .jsbeautifyrc
-rw-rw-r--   1 blyork blyork  5790 Apr 27 18:25 .jshintrc
drwxrwxr-x   2 blyork blyork  4096 Apr 28 14:49 lib
drwxrwxr-x 209 blyork blyork 12288 May  2 12:07 node_modules
-rw-rw-r--   1 blyork blyork   937 May  2 14:07 package.json
```

Here is my .gitignore:
```
# Directories

build
node_modules

# File Types

*.log
*.orig

# IDE

.idea
.project

# Windows

Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
*.cab
*.msi
*.msm
*.msp
*.lnk

# Mac

.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk

# Linux
.Trash-*
*~
```
This is the files field in my package.json:
```json
"files": [
  "lib/**/*",
  "index.js",
  "package.json"
]
```

When I do npm pack the index.js file is missing. While trying to debug I added a file and then the index.js was added but the new file was missing.

```json
"files": [
  "lib/**/*",
  "index.js",
  "package.json",
  "gulpfile.js"
]
```

**Comment by othiym23** [comment] 2016-05-02 20:58
Closing as duplicate of #5082. @evanlucas has a candidate fix, and I'm working on writing tests for `fstream` so that we can confirm that the fix is complete. Thanks for the thorough reports and your time!

**Closed by othiym23** 2016-05-02 20:58 UTC
Labels: bug
