### ISSUE TITLE
npm@5 uninstall module  error with -g

### ISSUE THREAD

**Issue by blackmatch** [npm/npm#16869] opened 2017-06-01 13:27 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when I run `sudo npm uninstall -g babel-cli` or `npm uninstall -g babel-cli`, error occurred. 

Unhandled rejection Error: Argument #2: Expected string but got null0
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blackmatch/.npm/_logs/2017-06-01T13_12_38_889Z-debug.log . 

2017-06-01T13_12_38_889Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'babel-cli' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly install loadIdealTree
7 silly install cloneCurrentTreeToIdealTree
8 silly install loadShrinkwrap
9 silly uninstall loadAllDepsIntoIdealTree
10 silly install loadAllDepsIntoIdealTree
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://github.com/npm/npm/issues>

I try to uninstall other global modules, same error!  

#### How can the CLI team reproduce the problem?
just run `npm uninstall -g <module_name>`   

### supporting information:

 - `npm -v` prints:5.0.1
 - `node -v` prints:v8.0.0
 - `npm config get registry` prints:https://registry.npm.taobao.org/
 - Windows, OS X/macOS, or Linux?:macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by blackmatch** [comment] 2017-06-01 13:30
I change the registry to `https://registry.npmjs.org/`, error still occurred!

**Comment by uloco** [comment] 2017-06-01 13:52
I tried uninstalling global `@angular/cli` with `npm@5`, same error on windows. After downgrading to `npm@4` it could be uninstalled. I also cannot install `@angular/cli` with` npm@5`, globally and locally, doesn't matter. On my mac, everything works fine. It just hangs on install after some packages are retrieved, no really error output or anything....

**Comment by industrylinq** [comment] 2017-06-01 16:25
I got the same issue when I tried to uninstall  @angular/angular-cli globally on Windows. This occured since I upgraded to npm 5.0.1 this morning.

Error is also npm ERR! cb() never called!

**Comment by gszy** [comment] 2017-06-01 17:29
Same problem on Linux, npm 5.0.1, node v7.10.0. I’m unable to uninstall `@angular/cli`.

**Comment by j7an** [comment] 2017-06-04 02:15
Does this mean we need to use npm@4.x to uninstall all global packages, then upgrade npm to 5 and reinstall the same packages?

**Comment by blackmatch** [comment] 2017-06-05 01:00
does it work? @j7an . If yes, I want to try~~

**Comment by j7an** [comment] 2017-06-05 01:40
@blackmatch based on https://github.com/npm/npm/issues/16869#issuecomment-305499683, installing angular cli with npm5 generated errors after uninstalling with npm4.

I haven't tried and my use case might be different from everyone else as I'm using npm and nodejs separately based on @johnpapa's article https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

**Comment by zkat** [comment] 2017-06-05 15:33
Closing as duplicate of https://github.com/npm/npm/issues/16738

**Closed as completed by zkat** 2017-06-05 15:33 UTC
Labels: npm5
