### ISSUE TITLE
Flat dependencies also flattens the bin folder

### ISSUE THREAD

**Issue by ashaffer** [npm/npm#11105] opened 2016-01-10 11:45 UTC
Since the `/.bin/` folder is flat, that means that a nested dependency can change the meaning of an otherwise global command in a script.

For instance, i'm using babel, and i'd like to avoid adding it to my dev dependencies (because installing it with npm3 is so slow), and just rely on its global presence. However, if any dependencies of mine (or dependencies of theirs, etc..) include babel, it'll show up in my bin folder, and potentially at an older version, and there doesn't seem to be any way I can opt out of that.

**Comment by othiym23** [comment] 2016-01-18 06:48
We're working on improving `npm@3`'s performance, even though it will be a little while until we can devote our full attention to it. This is pertinent, because the behavior you're describing is exactly what I would expect. The behavior you're talking about is a natural consequence of having a flatter install tree, and is a situation it was easy to encounter with older versions of npm when using `npm dedupe`. The correct way to deal with is to explicitly depend on the versions of tools you need and to call them via package scripts.

As npm is behaving as intended here, and as this particular issue is not a new one (although more commonly encountered now that maximally flat trees are the default), I'm closing this issue. But as I said at the top, the install times will be coming down again soon, so it won't be as much of a wait to directly depend on tooling. Thanks for your time!

**Closed by othiym23** 2016-01-18 06:48 UTC
Labels: support
