### ISSUE TITLE
npm init is not working

### ISSUE THREAD

**Issue by soggie** [npm/npm#17126] opened 2017-06-10 11:01 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm init` does not work. Hangs at version entry. Tried on two different folders, both do not work.

#### How can the CLI team reproduce the problem?

1. Go to a folder
2. Run `npm version`, verify that it's 5.0.3
3. Run `npm init`, press enter twice
4. Does not progress beyond version
5. Expected: should progress beyond version

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by playinteractive-it** [comment] 2017-06-10 20:12
Same issue here, same version of node and npm, but on Windows 10

**Comment by robertklep** [comment] 2017-06-10 20:14
I can confirm, but it seems to be related to the combination of `npm@5.0.3` and `node@8.1.0`; it doesn't happen with `node@8.0.0`.

**Comment by robertklep** [comment] 2017-06-10 20:24
@soggie there's already an issue for this problem: https://github.com/npm/npm/issues/17093

**Comment by gzaripov** [comment] 2017-06-11 23:08
the same issue(
Windows 10 x64
npm init -y works

**Comment by kenany** [comment] 2017-06-12 11:43
Duplicate of https://github.com/npm/npm/issues/17093.

**Closed as completed by kenany** 2017-06-12 11:43 UTC
Labels: node-bug
