### ISSUE TITLE
shasum check field Error

### ISSUE THREAD

**Issue by karboom** [npm/npm#8719] opened 2015-06-27 05:40 UTC
When I try to install package route-fs, I get follow error message:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'route-fs' ]
2 info using npm@2.10.0
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /Users/karboom/projects/javascript/json-server/package.json
6 warn package.json json-server@1.0.0 No description
7 warn package.json json-server@1.0.0 No repository field.
8 warn package.json json-server@1.0.0 No README data
9 verbose readDependencies loading dependencies from /Users/karboom/projects/javascript/json-server/package.json
10 silly cache add args [ 'route-fs', null ]
11 verbose cache add spec route-fs
12 silly cache add parsed spec { raw: 'route-fs',
12 silly cache add   scope: null,
12 silly cache add   name: 'route-fs',
12 silly cache add   rawSpec: '',
12 silly cache add   spec: '*',
12 silly cache add   type: 'range' }
13 silly addNamed route-fs@*
14 verbose addNamed "*" is a valid semver range for route-fs
15 silly addNameRange { name: 'route-fs', range: '*', hasData: false }
16 silly mapToRegistry name route-fs
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry uri https://registry.npmjs.org/route-fs
20 verbose addNameRange registry:https://registry.npmjs.org/route-fs not in flight; fetching
21 verbose request uri https://registry.npmjs.org/route-fs
22 verbose request no auth needed
23 info attempt registry request try #1 at 13:38:06
24 verbose request id 818324b4ca4cd280
25 verbose etag "EKQMUQNDW86TWNRL19AZD1Z6C"
26 http request GET https://registry.npmjs.org/route-fs
27 http 304 https://registry.npmjs.org/route-fs
28 silly get cb [ 304,
28 silly get   { date: 'Sat, 27 Jun 2015 05:38:07 GMT',
28 silly get     via: '1.1 varnish',
28 silly get     'cache-control': 'max-age=60',
28 silly get     etag: '"EKQMUQNDW86TWNRL19AZD1Z6C"',
28 silly get     age: '19',
28 silly get     connection: 'keep-alive',
28 silly get     'x-served-by': 'cache-lax1423-LAX',
28 silly get     'x-cache': 'HIT',
28 silly get     'x-cache-hits': '1',
28 silly get     'x-timer': 'S1435383487.566732,VS0,VE1',
28 silly get     vary: 'Accept' } ]
29 verbose etag https://registry.npmjs.org/route-fs from cache
30 verbose get saving route-fs to /Users/karboom/.npm/registry.npmjs.org/route-fs/.cache.json
31 silly addNameRange number 2 { name: 'route-fs', range: '*', hasData: true }
32 silly addNameRange versions [ 'route-fs',
32 silly addNameRange   [ '1.0.0',
32 silly addNameRange     '2.0.0',
32 silly addNameRange     '2.0.1',
32 silly addNameRange     '2.0.2',
32 silly addNameRange     '2.0.3',
32 silly addNameRange     '2.0.4',
32 silly addNameRange     '2.1.0',
32 silly addNameRange     '2.1.1',
32 silly addNameRange     '2.1.2',
32 silly addNameRange     '2.1.3',
32 silly addNameRange     '2.1.4',
32 silly addNameRange     '2.1.5' ] ]
33 silly addNamed route-fs@2.1.5
34 verbose addNamed "2.1.5" is a plain semver version for route-fs
35 silly mapToRegistry name route-fs
36 silly mapToRegistry using default registry
37 silly mapToRegistry registry https://registry.npmjs.org/
38 silly mapToRegistry uri https://registry.npmjs.org/route-fs
39 verbose addRemoteTarball https://registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz not in flight; adding
40 verbose addRemoteTarball [ 'https://registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz',
40 verbose addRemoteTarball   '47be96c2693f1e8f1cce85b1c5bcc2e7f389daf7' ]
41 info retry fetch attempt 1 at 13:38:07
42 info attempt registry request try #1 at 13:38:07
43 http fetch GET https://registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz
44 http fetch 200 https://registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz
45 silly fetchAndShaCheck shasum 47be96c2693f1e8f1cce85b1c5bcc2e7f389daf7
46 verbose stack Error: shasum check failed for /var/folders/vt/mcyr4q1x0mdf_wv7mzwjrwkr0000gn/T/npm-3324-3b7638a7/registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz
46 verbose stack Expected: 47be96c2693f1e8f1cce85b1c5bcc2e7f389daf7
46 verbose stack Actual:   5297c843919054686f92aa97e0c2c85c0b29f685
46 verbose stack From:     https://registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz
46 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
46 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
46 verbose stack     at ReadStream.emit (events.js:129:20)
46 verbose stack     at _stream_readable.js:908:16
46 verbose stack     at process._tickCallback (node.js:355:11)
47 verbose cwd /Users/karboom/projects/javascript/json-server
48 error Darwin 14.1.0
49 error argv "node" "/usr/local/bin/npm" "install" "route-fs"
50 error node v0.12.2
51 error npm  v2.10.0
52 error shasum check failed for /var/folders/vt/mcyr4q1x0mdf_wv7mzwjrwkr0000gn/T/npm-3324-3b7638a7/registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz
52 error Expected: 47be96c2693f1e8f1cce85b1c5bcc2e7f389daf7
52 error Actual:   5297c843919054686f92aa97e0c2c85c0b29f685
52 error From:     https://registry.npmjs.org/route-fs/-/route-fs-2.1.5.tgz
53 error If you need help, you may report this error at:
53 error     <https://github.com/npm/npm/issues>
54 verbose exit [ 1, true ]
```

I have tried `npm cache clean`, but not work

**Comment by zkat** [comment] 2016-12-09 00:56
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:56 UTC
Labels: shasum, support
