### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kannach** [npm/npm#12676] opened 2016-05-12 13:06 UTC
I use angular fullstack for mean app. When I run npm install inside my project i get the follwoing error

```
Linux 3.13.0-62-generic
npm ERR! argv "/home//.nvm/v6.1.0/bin/node" "/home//.nvm/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home//test/node_modules/-/npm-debug.log
```

I didnt get error when I use node v4.4.4 or previous

**Comment by othiym23** [comment] 2016-05-16 21:15
There's not enough information here for the team to figure out what happened – we'll need either an `npm-debug.log` or a repro case of some kind. Thanks in advance for your time!

**Comment by helio-frota** [comment] 2016-12-02 16:40
@kannach 

Can you share more information to try to reproduce?
Possible to share the package.json?
What you trying to install?
thanks

**Comment by jinkeeb** [comment] 2017-03-30 19:02
Hi @helio-frota, I am having the same issue, here is my package.json
`{
    "name": "Magento2",
    "author": "Magento Commerce Inc.",
    "description": "Magento2 node modules dependencies for local development",
    "version": "2.0.0",
    "license": "(OSL-3.0 OR AFL-3.0)",
    "repository": {
        "type": "git",
        "url": "https://github.com/magento/magento2.git"
    },
    "homepage": "http://magento.com/",
    "devDependencies": {
        "glob": "^7.1.1",
        "grunt": "^1.0.1",
        "grunt-autoprefixer": "^3.0.4",
        "grunt-banner": "^0.6.0",
        "grunt-contrib-clean": "^1.0.0",
        "grunt-contrib-connect": "^1.0.2",
        "grunt-contrib-cssmin": "^2.0.0",
        "grunt-contrib-imagemin": "^1.0.1",
        "grunt-contrib-jasmine": "^1.1.0",
        "grunt-contrib-less": "^1.4.1",
        "grunt-contrib-watch": "^1.0.0",
        "grunt-eslint": "19.0.0",
        "grunt-exec": "^2.0.0",
        "grunt-jscs": "3.0.1",
        "grunt-replace": "^1.0.1",
        "grunt-template-jasmine-requirejs": "^0.2.3",
        "grunt-text-replace": "^0.4.0",
        "imagemin-svgo": "^5.2.1",
        "load-grunt-config": "^0.19.2",
        "morgan": "^1.5.0",
        "node-minify": "^2.0.3",
        "path": "^0.12.7",
        "serve-static": "^1.7.1",
        "strip-json-comments": "^2.0.1",
        "time-grunt": "^1.0.0",
        "underscore": "^1.7.0"
    },
    "engines": {
        "node": ">=0.10.0"
    }
}`

and attached is the npm-debug.log

[npm-debug.log.txt](https://github.com/npm/npm/files/883514/npm-debug.log.txt)

**Comment by admosity** [comment] 2017-04-19 13:22
I was able to reproduce this by trying to upgrade typescript globally (I do have `nvm` installed though). I also ran into this issue a couple times on trying to `npm install` on a repo that had a symlink somewhere.

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/some-user/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/Users/some-user/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'up',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack RangeError: Maximum call stack size exceeded
4 verbose stack     at Array.types.A (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/node_modules/aproba/index.js:9:25)
4 verbose stack     at types.O (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/node_modules/aproba/index.js:13:85)
4 verbose stack     at module.exports (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/node_modules/aproba/index.js:30:10)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
4 verbose stack     at flatNameFromTree (/Users/some-user/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
5 verbose cwd /Users/some-user/git/
6 error Darwin 16.5.0
7 error argv "/Users/some-user/.nvm/versions/node/v7.4.0/bin/node" "/Users/some-user/.nvm/versions/node/v7.4.0/bin/npm" "up" "-g" "typescript"
8 error node v7.4.0
9 error npm  v4.0.5
10 error Maximum call stack size exceeded
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by Krinkle** [comment] 2017-04-21 00:54
Possibly a duplicate of #9224.

**Closed** 2017-06-19 04:38 UTC
Labels: big-bug, bot-closed, bug, needs-repro
