### ISSUE TITLE
error while npm install "is-running" module

### ISSUE THREAD

**Issue by npeditto** [npm/npm#12207] opened 2016-04-05 15:39 UTC
Hi,

I'm getting an error when I try to install "is-running" module (during the last week I installed it successfully)... below the output error:

### npm install -g is-running

npm http GET https://registry.npmjs.org/is-running
npm http 200 https://registry.npmjs.org/is-running
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
npm ERR! �YKs�6 �+�|�3�(<	P3�f294�^��P;c�(1�H�;J&��ݥHIV�� �MR��� �

                                                                        |�>>�37 �jX6y���������0F��{���T:�PK]��NU ��'LR Ĺ��] �W�� uV�0u��:��� �����������Iv��`�� ���z�U��6�j0�8�� �A
npm ERR! 
'��V���3�� � --q�P8R����""���� ~�������� ݀�� kwYi�Ѭiр�0BC R i]� �0�� �g�}� �a�& K�(�ڗA�� W� U ����z�@'O� �6�l�{< �ȴIB[�GyV c�" m63D���/��ҁ-� �ٸ�N� ���� �^��|��x`�zZ���s�o�� /;%(u�Y�Wh��W/� ���
                                                                            ���j��� E�H� �S � ��c��(UBq�H �@Mm�����Ӻ^T���O@^�
�a#��� ����� Ra�׻���7 ͥ[;�9H��:�p �������.���>�*��y��r\ '��e���Jy��ɽ���Xpb��   _�G8=<8���                                   ���m �d����֟ak@XO>���e��C�z���2���D7����N�3 �f%�; '
                                                                                          'x5���8�S��ѱ�^GRix�l� Ƿ5�pf��:�
                                                                                                                          N|?8�G8�߃��Y�h��; ClV5 �� ,��f �ZD�@�*�J �i�l�S#(5\8Ϩ�SO( �w�#��4 e C~�hQ��G
��4��Ȝ s�0 �+��5�a����~��ۅ�r�hCd G���TRm��Ƌ8�F2)�e,N� �b 8��a � 8�s<��N�~n3ϽS�ۉ� A� �%��Ra�~�� �]h{��                                                                                                n���-���� ��1
npm ERR! �K�A�Iy Sn#�)d�� �E�1���;��rOhcH��A{����� t��`Uy�� o�
npm ERR! �� / �- F����
`��3���T(�$��NQkud�$�x�(/C��3�} ���5^
                       �w����,yW�����`
��F����rG� �@��VX�}}� Y �/P�f �D �Y~ ��A��ӣ��|j���;�b���[���㯿_.ݮ޲St����?�>o�} ��M�To����.�%�S6k���;o�6 .�ɓ�0<iխ{ � �t��
                                         �h�3;�/ r
                                                  �� t����EK{ �� ��߯��-��h�� �..ޚK�jh�嗦D آ	� ����>��a߶9| v�Ey V y�n�&�h?숰 �4�j r�6�!��Z�G@���#�<�w�� ;�_P�'���g��h��8���.����{{q
                                                                                                                                                                                       8�z� � �ѿ7��
                                                                                                                                                                                                    q�]=}笃 �g�Ɇ ; A�d5����{ 8 lp�|+�Aēa��#��\�f {i�P9�dH�	�Ƃ��
npm ERR! 	W �� @Y�D|Hؐ� �Ƅ�9	U,�h�_k����P�5	��P �p�B�XDc�C �^
npm ERR! ��wI��E!W�'��_G 6� ��T��
`qExb������� �$9- J�u�iaH��T�V YMG†L� �+"pɋ �t����� ��C
npm ERR! �Hrut�u���:� �;����J )Uŉy%����JV%E��� ���L�`|��ib�n&T 4��XR������W 2�� ���� 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "is-running"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

Is there some problem in the npm repo?

Thank you in advance!

Nicola

**Comment by othiym23** [comment] 2016-04-05 15:42
Closing as duplicate of #12196. See that issue for details and resolution. Thanks!

**Closed by othiym23** 2016-04-05 15:42 UTC
