### ISSUE TITLE
npm install fails when node_modules is a symlink

### ISSUE THREAD

**Issue by myitcv** [npm/npm#10013] opened 2015-10-17 18:33 UTC
Steps to reproduce:

```
cd `mktemp -d`
npm init --force
ln -s `mktemp -d` node_modules
npm install --save-dev typescript@1.7.0-dev.20151006
npm install --save-dev typescript@1.7.0-dev.20151014
```

Gives the following warning:

```
npm WARN update-linked node_modules/typescript needs updating to 1.7.0-dev.20151014 from 1.7.0-dev.20151006 but we can't, as it's a symlink
```

which should be an error because the install has **not** updated the installed version:

```
$ ./node_modules/.bin/tsc --version
message TS6029: Version 1.7.0-dev.20151006
```

Repeat the above but without a symlinked `node_modules` and it works just fine:

```
$ ./node_modules/.bin/tsc --version
message TS6029: Version 1.7.0-dev.20151014
```

Important details:

```
$ node --version
v4.2.0
$ npm --version
3.3.8
```

**Comment by lencioni** [comment] 2015-11-03 04:46
At @brigade we are storing our `node_modules` directory in `~/node_modules` and then symlinking it in to the project in CI where we then run `npm prune` and `npm install`. This speeds up our builds because it is mostly cached.

We recently upgraded from npm@2 to npm@3 and we started seeing some messages like:

```
npm WARN skippingAction Module is inside a symlinked module: not running remove ast-types@0.7.8 node_modules/babel-core/node_modules/ast-types
npm WARN skippingAction Module is inside a symlinked module: not running update core-js@1.2.4 node_modules/babel-core/node_modules/core-js
npm WARN skippingAction Module is inside a symlinked module: not running remove debug@2.2.0 node_modules/babel-core/node_modules/debug
```

And also some messages like:

```
npm WARN update-linked node_modules/minimist needs updating to 1.2.0 from 1.1.3 but we can't, as it's a symlink
npm WARN update-linked node_modules/omniscient-debugging needs updating to 0.0.2 from 0.0.2 but we can't, as it's a symlink
npm WARN update-linked node_modules/recast needs updating to 0.10.24 from 0.10.34 but we can't, as it's a symlink
```

We are currently running node 5.0.0 and npm 3.3.6.

I hope this info is helpful. In the meantime, I think we are going to avoid using a symlink. Also, if you have any alternative suggestions for keeping npm fast for our CI builds I'm definitely interested.

**Comment by avdd** [comment] 2015-11-03 05:25
So because npm is essentially incompatible with anything that is the sanctioned npm way, my workaround is to run npm from the directory physically containing node_modules, and symlink package.json and npm-shrinkwrap.json.  But npm#10223 makes this more awkward than it need be, hence the assertion in the first sentence of this comment.

**Comment by danielsiwiec** [comment] 2015-11-05 00:35
+1

**Comment by hadim** [comment] 2015-11-16 17:35
+1

**Comment by evanemolo** [comment] 2015-11-18 19:32
+1

**Comment by mathiasslawik** [comment] 2015-11-30 12:36
I am seeing the same behavior on my machine. It worked fine with npm 2.x - even on Windows, but not with npm 3.x. I'm using node 5.1.0 with npm 3.5.0 on an Archlinux 64bit machine.

The reason for relying on a symlinked node_modules is that I sync my development folder over multiple machines, but symlink all huge folders, such as npm's node_modules to a local directory in order to save on bandwidth and to be able to develop both on Linux as well as on Windows.

If the node_modules symlinked directory is empty, I can run `npm install` successfully. But as soon as I try to install additional modules, I get the same errors as @myitcv.

Is npm not operating on symlinks a design feature or just a regular bug?

**Comment by genyded** [comment] 2015-12-10 17:30
+100 for some sane way to address this... with 3.x out there are literally hundreds of warnings even if NPM itself cannot be updated via a symlink

**Comment by pieterjandesmedt** [comment] 2015-12-14 09:03
+1

**Comment by dphaener** [comment] 2015-12-14 15:53
+1 npm version 3.3.12, node version 5.2.0

**Comment by STRML** [comment] 2015-12-15 00:57
This is a bad one. At the very least it should error (exit 1), it should not simply warn and do the wrong thing. We ended up with an unexpected mixture of code and dependencies because of this that caused some issues. This workflow (symlinked node_modules between deploys) worked fine in 2.x. Downgrading for now.

**Comment by eXon** [comment] 2015-12-15 16:06
+1, same problem with NPM 3.5.2, have to roll back to 2 for now

**Comment by mking** [comment] 2015-12-19 13:21
:+1: Just ran into this, this breaks our deployment process (we have a single shared node_modules dir across multiple deployments)

**Comment by nburwell** [comment] 2016-01-06 00:34
:+1: just ran into this in our development process as we also utilize symlinks to consolidate our node_modules and was working great with NPM 2

**Comment by furins** [comment] 2016-01-10 17:27
+1

**Comment by dave-newson** [comment] 2016-01-14 03:13
I personally didn't have a problem with `npm install` and `node_modules` being a symlink, however when trying to run `npm run build` for the build process in the local package, I get the following error:
`Cannot find module 'gulp-util'`

My guess is it simply can't resolve the path of gulp-util, which is probably the first requested child-dependency, as my build script calls gulp.

This was encountered this while trying to fix long path names on a Windows hosted VM with a shared folder. The symlink was used to stop windows inheriting the files inside the share, and instead divert them to somewhere else on the VM.  This was then reproduced on the raw VM outside of any share paths, using `ubuntu/trusty64`.

Steps to reproduce, you can probably try this with any project that has sub-deps;
- `npm install`
- `npm run build`

Should complete OK
- `mv node_modules /tmp/nm`
- `ln -s /tmp/nm node_modules`
- `npm run build`

Observe failure.

npm 3.3.12, node 5.4.1

**Comment by mnpenner** [comment] 2016-01-15 21:08
We're having the exact same issue as @dave-newson but with the `glob` package. Symlinks would shave 1-3 minutes off our build, which we do quite frequently, so this is a big deal for us.

**Comment by STRML** [comment] 2016-01-15 21:20
Was there a good reason for this change? If not, can we simply remove the symlink check?

**Comment by othiym23** [comment] 2016-01-15 21:23
There absolutely is a good reason for this change, which is the team's ongoing efforts to improve the developer experience when working with `npm link`ed packages, to better support doing active development on several packages at once. It turns out there are a lot of thorny edge cases left to work through on this, and some of the requirements are starting to seem a little contradictory. So, the underlying feature needs some refinement, and it's not as simple as removing the check, no.

**Comment by STRML** [comment] 2016-01-15 21:30
Thanks for the explanation - wasn't insinuating that this was a dumb
check or feature, npm is simply so large and complicated at this point
that it's difficult as an outsider to judge.

**Comment by mikermcneil** [comment] 2016-02-01 22:48
@othiym23 thanks!  To give you another use case, we ran across this because `sails new` spits out a new Sails app and creates symlinks to dependencies of the globally installed sails in the new `node_modules/` folder (purely to avoid the ~30 sec `npm install`).  This still works fine-- but as soon as our users try to `npm install some-other-thing`, everything explodes.  So i.e. it's not that `node_modules/` itself is a symlink-- rather that the packages are symlinks.

For now we're just sniffing `npm -v` (if <"v3.0.0" use symlinks, otherwise run `npm install` manually and [display a message](https://github.com/balderdashy/sails-generate-new/blob/73175bad1f6a9227bab0502142312c5ae29ed5ee/lib/after.js#L68)).  It'd be great to be able to work around this in an official NPM way, but I know you guys are busy.  In the mean time we'll keep searching for a workaround-- was going to look into `--global-style` next, and after that maybe calling `npm link` and `npm link foo` programmatically for each dep. I'll try to remember to report back here with what we come up with.

**Comment by jeffgran** [comment] 2016-02-02 04:35
:+1:  using docker, mounting node_modules as a shared volume in another container, symlinked from app dir.

**Comment by rishabhmhjn** [comment] 2016-02-08 08:18
We are using **capistrano** for our deployments have added our `node_modules` directory as shared dir. Now, the first install of all modules are ok but subsequent changes to the `package.json` modules are not reflected and are met with following errors

```
...
npm WARN skippingAction Module is inside a symlinked module: not running move mime-db@1.12.0 node_modules/accepts/node_modules/mime-db
npm WARN skippingAction Module is inside a symlinked module: not running move mime-types@2.0.14 node_modules/accepts/node_modules/mime-types
npm WARN skippingAction Module is inside a symlinked module: not running remove kind-of@2.0.1 node_modules/align-text/node_modules/kind-of
npm WARN skippingAction Module is inside a symlinked module: not running remove geojsonhint@1.1.0 node_modules/anchor/node_modules/geojsonhint
npm WARN skippingAction Module is inside a symlinked module: not running remove lodash@3.9.3 node_modules/anchor/node_modules/lodash
npm WARN skippingAction Module is inside a symlinked module: not running remove validator@3.41.2 node_modules/anchor/node_modules/validator
npm WARN skippingAction Module is inside a symlinked module: not running remove glob@5.0.15 node_modules/express-handlebars/node_modules/glob
npm WARN skippingAction Module is inside a symlinked module: not running add node-uuid@1.4.7 node_modules/google-auth-library/node_modules/request/node_modules/node-uuid
...
```

**Comment by jchonde** [comment] 2016-02-24 10:40
Still failing on npm 3.7.3.

**Comment by digitallawyer** [comment] 2016-02-24 17:46
+1

**Comment by jchonde** [comment] 2016-02-26 09:09
Found a solution. The source and target of the symlink must have the same name.

**Comment by rishabhmhjn** [comment] 2016-02-26 09:15
I have the same name, but I got the error above

**Comment by huguenin** [comment] 2016-03-08 09:12
Thanks @jchonde that solved the problem for me!

**Comment by bouk** [comment] 2016-03-10 15:58
@jchonde what exactly do you mean by the source and target having the same name? On 3.7.3 I still get the same error if both the folder and the symlink are called `node_modules`

**Comment by huguenin** [comment] 2016-03-10 16:04
@bouk We're on npm 2.14.12 - could well be that this was "fixed" later.

**Comment by jeffgran** [comment] 2016-03-10 16:58
@huguenin that explains it. this is a problem with npm 3.x. several of us have reverted to npm 2.x to avoid this problem.

**Comment by maxlk** [comment] 2016-03-16 17:24
After upgrade to npm 3.x we faced similar problem in our CI: we have a symlink to `node_modules` and launch `npm prune` and `npm update`. It causes **No compatible version found: MODULE_NAME@linked** error.

Is there any workaround besides downgrade to npm 2.x?

npm output:
```
$ npm update
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: lodash@linked
npm ERR! Valid install targets:
npm ERR! 4.6.1, 4.6.0, 4.5.1, 4.5.0, 4.4.0, 4.3.0, 4.2.1, 4.2.0, 4.1.0, 4.0.1, 4.0.0, 3.10.1, 3.10.0, 3.9.3, 3.9.2, 3.9.1, 3.9.0, 3.8.0, 3.7.0, 3.6.0, 3.5.0, 3.4.0, 3.3.1, 3.3.0, 3.2.0, 3.1.0, 3.0.1, 3.0.0, 2.4.2, 2.4.1, 2.4.0, 2.3.0, 2.2.1, 2.2.0, 2.1.0, 2.0.0, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 1.0.0-rc.3, 1.0.0-rc.2, 1.0.0-rc.1, 0.10.0, 0.9.2, 0.9.1, 0.9.0, 0.8.2, 0.8.1, 0.8.0, 0.7.0, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.5.0-rc.1, 0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /sdnc_users/adj/aimsys/sdnc01/npm-update/2/npm-debug.log
```

**Comment by shaimo** [comment] 2016-03-19 09:02
+1

**Comment by adamchainz** [comment] 2016-03-19 10:32
It looks to me like the main symlinking problems came in with #6934.

The "npm WARN update-linked node_modules/foo needs updating to x from y but we can't, as it's a symlink" error seems to be a false positive caught by the "don't update symlinked module" semantics, caused because `node_modules` itself is a symlink, around here: https://github.com/npm/npm/blob/master/lib/install/diff-trees.js#L135 . I'm afraid I'm not familiar enough with the code myself to update this to ignore the root of the tree (`node_modules`) being a symlink.

**Comment by simon-lifelike** [comment] 2016-04-14 09:10
This is still an issue in v3.8.7

**Comment by flying-sheep** [comment] 2016-04-23 18:59
shouldn’t this only happen if the *package* is symlinked instead of the *node_modules* directory?

**Comment by corbt** [comment] 2016-05-03 20:31
This issue also affects me. I understand that symlinked packages might need some special considerations, but there should be no problem with symlinking the entire `node_modules` directory.

**Comment by nitsujri** [comment] 2016-05-07 04:25
+1 This makes it very difficult to update via capistrano and even by commandline on our servers.

**Comment by nitsujri** [comment] 2016-05-07 04:26
@maxlk ran into this issue. if you haven't or for anyone else, upgrading past `3.7.3` fixes it

**Comment by myitcv** [comment] 2016-05-07 16:38
@nitsujri are you suggesting that upgrading to a version `> 3.7.3` fixes the problem? 

If so, then I don't believe that's the case: the problem still remains with `3.9.0`

**Comment by nitsujri** [comment] 2016-05-08 01:07
@myitcv sorry, i should've mentioned context. @maxlk's issue is different than the one in this thread. His/her is this one: https://github.com/npm/npm/issues/4984

**Comment by iarna** [comment] 2016-05-12 19:46
Status update– I have a fix for this over in https://github.com/npm/read-package-tree/pull/10. I expect it to be done with review and ready for merged for next weeks' release so I'm bumping the milestone forward.

**Comment by iarna** [comment] 2016-05-17 01:12
not actually fixed in npm yet github, argh

**Closed** 2016-05-19 21:59 UTC
Labels: big-bug, bug, link

**Comment by JKillian** [comment] 2016-06-02 17:55
I was seeing this issue in a project of mine, and happily upgrading to the latest version of NPM made it go away. However, `npm install` now fails with a "Maximum call stack size exceeded" message similar to https://github.com/npm/npm/issues/10776 instead, which still makes things difficult.

**Comment by sposmen** [comment] 2016-06-08 12:08
As workaround for old versions, and if fast deployments is the goal, one suggestion is to wrap the npm install through fast backup copies. 

1. Execute deploy process before npm install. 
2. FROM the node_modules backup , clone it to the app directory. 
3. Execute npm install. 
4. Generate a new backup copy. 
5. Continue the deployment process after the npm install step.

**Comment by STRML** [comment] 2016-06-08 13:52
See also [npm-cache](https://www.npmjs.com/package/npm-cache) for a formalized version of the above

**Comment by sandeep-mvd** [comment] 2017-04-02 23:36
I get this same error even with node 6.10.1

```
root@beaglebone:~# npm i -g mraa
npm WARN update-linked node_modules/mraa needs updating to 1.6.0 from 1.0.0-dirty but we can't, as it's a symlink
root@beaglebone:~# node -v
v6.10.1
root@beaglebone:~# npm -v
4.4.4
```

I dont know if it is relevant, but i did clean the npm cache for updating node.
Following are the steps I did to update my node.
```
npm cache clean -f
npm install -g n
n 6.10.1
```
I am not sure if `npmp cache clean -f` is the reason for this issue.

**Comment by fcce** [comment] 2018-01-16 03:29
@rishabhmhjn the same errors, using  Capistrano too. Do you have any solution?

**Comment by tareksha** [comment] 2018-02-10 07:48
hi @myitcv , @iarna , I'm not really sure I understood the progress on this. Although a fix has already been merge the exact issue still reproduces for me in npm 5.5.1 .

this flow reproduces it consistently:

1. go to an empty folder
2. create a smylink from `node_modules` to another place
example: `ln -s $(mktemp -d -p $HOME) node_modules`
3. run `npm install`
things install correctly
4. run `npm install` again from the same directory
chaos. new packages installed. some removed. hierarchy broken. some dependencies lost...

**Comment by heberuriegas** [comment] 2018-02-16 15:57
Same here, cannot work anymore with npm link using node v8.9.4 and npm v5.6.0. It only break when a second npm install is called.
