### ISSUE TITLE
Bower install failed

### ISSUE THREAD

**Issue by thepian** [npm/npm#11432] opened 2016-02-05 10:35 UTC
I tried `npm install -g bower` (also tried with sudo) on OS X.
Tried clear cache
Tried re-installing bower (homebrew)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.7.1
3 info using node@v4.2.1
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:166:22)
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
5 verbose cwd /Users/henrikvendelbo/workspace/oil-ui
6 error Darwin 15.2.0
7 error argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "update" "-g" "bower"
8 error node v4.2.1
9 error npm  v3.7.1
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:166:22)
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by ashleygwilliams** [comment] 2016-02-06 15:45
i can't reproduce this on my machine with the same versions of node and npm, which makes me think it may be an issue with (and/or somehow related to) homebrew, as it looks like you installed node with homebrew?

also perhaps related to: https://github.com/npm/npm/issues/9659 though this was an error in previous versions and is since closed.

**Comment by othiym23** [comment] 2016-02-12 06:33
My guess is that this is due to a stray broken link in the global `node_modules`, which is a bug that's open in a few other places (but which I can't remember the ID for offhand). In any case, every instance of a missing argument error is a serious bug, so I'll tag this with `big-bug` for now and then we can establish which other issue(s) it may be a duplicate of when we start working on the list of crashers in a bit.

**Closed** 2017-06-19 10:11 UTC
Labels: big-bug, bot-closed, bug, needs-repro
