### ISSUE TITLE
npm install -g cordova -v5.3.3 OR npm install ./cordova-5.3.3.tgz -g face lot of errors :|

### ISSUE THREAD

**Issue by deadmann** [npm/npm#11006] opened 2016-01-01 22:21 UTC
```
C:\Users\Hassan\Downloads>npm install ./cordova-5.3.3.tgz -g
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "./cordova-5.3.3.tgz" "-g"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! shasum check failed for C:\Users\Hassan\AppData\Local\Temp\npm-10708-2243e6a5\registry.npmjs.org\cordova-app-hello-world\-\cordova-app-hello-world-3.9.0.tgz
npm ERR! Expected: 5866d8fed5582686c68ec59a6d1097c4ec0fcc4b
npm ERR! Actual:   31453ecefd10cad7a743df249c8f0071b9db7f0b
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.9.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hassan\Downloads\npm-debug.log
```

[npm-debug.zip](https://github.com/npm/npm/files/76056/npm-debug.zip)

**Comment by smikes** [comment] 2016-01-05 14:25
You probably want 

```
> npm install -g cordova@5.3.3
```

**Comment by deadmann** [comment] 2016-01-05 16:27
i fix it using set registery to http and shutdown that ssl enforcment thing, and push myself over to a proxy server, and also turn modem firewall which never become truble untile now, down, i'm not sure it the last one was truble but as some folk noted it i did it, but the first two really are matter, and people should be able to configure it using simple interface, as it's really a pain for someone who don't now, it take around a week of my time :(, even the previous time i was with my partner, i just get it to work with installing some kinda of application, which really changed the way my connection adapter works (on that OS, and it is no longer configurable, due that app)

**Comment by zkat** [comment] 2016-12-09 00:49
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:49 UTC
Labels: shasum, support
