### ISSUE TITLE
.npmrc option `ignore-scripts` is breaking `npm run`

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#10675] opened 2015-12-02 21:11 UTC
In our `.npmrc` we added this line:
```
; always amends --ignore-scripts on npm installs
ignore-scripts=true
```

but it seems to break `npm run xxx` as well. Cannot run any scripts defined in package.json anymore.

Looks like a bug. `ignore-scripts` should affect `npm i` only, not `npm run`. If this was intentional, then we need a new option to separate both.

**Comment by binarykitchen** [comment] 2015-12-03 20:28
Anyone? @othiym23

**Comment by othiym23** [comment] 2015-12-17 00:19
This is pretty much by definition, given that `npm run` is short for `npm run-script`, and `--ignore-scripts` is saying to ignore scripts. This is npm doing exactly what it's been asked to do, so it's pretty definitively not a bug. I'm going to close this as not a bug, but: what are you trying to do?

If you wanted to put together a patch to print a warning when you run `npm run` or `npm test` with `ignore-scripts` set, that would get landed without much discussion. It's a confusing user experience when you don't know what npm is doing, or why.

**Closed by othiym23** 2015-12-17 00:19 UTC
Labels: support

**Comment by binarykitchen** [comment] 2015-12-17 00:29
@othiym23 thanks for replying. i think we are discussing about two entirely different things here. let me clarify.

first, yes, i agree, the user experience here can be improved. a warning would be good here. have already wasted hours until i found it out.

and now, to the main issue here, the `npm install` command! when you install complex packages, i.E. gulp, scripts are being run on post-install, compiling stuff depending on your OS. they are crucial so that the package can be run on your machine. but `--ignore-scripts` prevents from this. no binaries exist and you cannot run gulp.

that's why i think this one option affects two entirely different things. hence i suggest to split it into two options. for example have:

- `--ignore-run-scripts` which prevents npm from running scripts defined in the package.json where you cannot call them via `npm run xxx` anymore at all
- `--ignore-run-scripts-on-install` which does not call the run scripts on install but the user still can manually call them via `npm run xxx`

how does this sound?

**Comment by othiym23** [comment] 2015-12-17 00:42
I still don't understand why you have `ignore-scripts` set in the first place, which is essential to responding to anything else you've written. Why do you want it set globally?

**Comment by binarykitchen** [comment] 2015-12-17 01:07
@othiym23 because we check in all our node modules into our private git repository without the compiled binaries

**Comment by othiym23** [comment] 2015-12-17 01:25
Adding yet another configuration option with very slightly different behavior makes it trickier to understand both options, adds more complicated conditional logic to the CLI, and probably also doesn't solve your problem here. (Side note: in retrospect, using `ignore-scripts` is a packaging smell, and @iarna and I are sort of sad that it exists in npm.) I don't think that change makes sense.

@iarna raised the very good point that it makes no sense to straight up ignore `npm run`, which is an explicit request to run a script, if `ignore-scripts` is set. In other words, it should take precedence. The current behavior isn't a bug, being more being (yet another) surprising consequence of how npm's configuration framework works. _However,_ if somebody put together a patch to override the setting of `ignore-scripts` when `npm run` is called, we'd land it without much discussion (the CLI team itself is unlikely to have the time to work on this anytime in the foreseeable future).

**Comment by binarykitchen** [comment] 2015-12-17 01:34
@othiym23 understand.

before we go deep here, let me ask you a quick question: do you have an idea how we can check in the node modules into our private repo without the os-specific binaries?

**Comment by othiym23** [comment] 2015-12-17 01:37
`.gitignore` is how I would do it (something like `build/**/*.{node,o}`, although that's straight off the top of my head and probably doesn't work), especially because disabling scripts altogether may break packages with postinstall or other behaviors.

**Comment by binarykitchen** [comment] 2015-12-17 01:59
@othiym23 basically, what we do here is to install new npm packages like that:

`npm i -S --ignore-scripts i_am_a_package`

then git add/commit that to our repo. 

after that, we compile the binaries with `npm rebuild` and put those artefacts into our `.gitignore`. which works fine except we cannot use `npm run-script ... ` anymore. this is our use case which led to this bug report.

**Comment by wjagodfrey** [comment] 2016-03-29 22:32
Weighing in here if I may. I agree that this is an issue. For high risk business applications - APIs and the like - even shrinkwrapping isn't a robust enough solution. The downside right now is that it's difficult to keep npm package binaries out of git (which is what @binarykitchen is trying to solve).

Ideally, npm would guarantee binary build locations. Similar to `node_modues/.bin/`, which could be ignored instead. Deployment pipeline would then call `npm rebuild` instead of `npm install`.

But solving this issue would help in the meanwhile.
