### ISSUE TITLE
Recursive install ignoring commit(ish)

### ISSUE THREAD

**Issue by Crispy1975** [npm/npm#9832] opened 2015-10-02 20:45 UTC
We're testing some updated plugins in our code, as a result we have some `package.json` files targetting specific branches and commits so we can trial the new features. When running `npm install` in the parent folder all dependencies are installed, but the commitish sometimes gets ignored and reverts to master branch HEAD.

We have tried clearing the npm cache, manually deleting the `node_modules` folder, only way we can get the correct dependency version is to navigate to the relevant sub node_module folder and run an `npm install` from there.

Any ideas welcomed.

**Comment by KenanY** [comment] 2015-10-02 20:58
@Crispy1975 `npm --version`?

**Comment by Crispy1975** [comment] 2015-10-02 21:03
@KenanY `2.11.1`

**Comment by KenanY** [comment] 2015-10-02 21:23
Duplicate of https://github.com/npm/npm/issues/8429 perhaps :(

**Comment by Crispy1975** [comment] 2015-10-02 21:27
@KenanY yeah, that seems to be the case. At least we know it's not us. :)

**Comment by othiym23** [comment] 2015-10-05 19:46
Closing as duplicate of #8429. In the medium term, we have items on [the road map](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-git) to continue improving how npm handles Git-hosted dependencies. Sorry this bit you!

**Closed by othiym23** 2015-10-05 19:46 UTC
Labels: big-bug, git

**Comment by Crispy1975** [comment] 2015-10-05 20:03
No problem, looking forward to a fix or solution. :)
