### ISSUE TITLE
help!!! 

### ISSUE THREAD

**Issue by tecnosoftware** [npm/npm#14478] opened 2016-11-01 00:14 UTC
```
C:\Users\Jose Cedeño>npm install -g cordova
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\JOSECE~1\AppData\Local\Temp\npm-6224-1adbee5d\registry
.npmjs.org\cordova\-\cordova-6.4.0.tgz.2685501306' -> 'C:\Users\JOSECE~1\AppData
\Local\Temp\npm-6224-1adbee5d\registry.npmjs.org\cordova\-\cordova-6.4.0.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\JOSECE~1\AppData\Local\Temp\npm-6224-1adbee5d\registry
.npmjs.org\semver\-\semver-5.3.0.tgz.3971079051' -> 'C:\Users\JOSECE~1\AppData\L
ocal\Temp\npm-6224-1adbee5d\registry.npmjs.org\semver\-\semver-5.3.0.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

npm ERR! tarball.destroy is not a function
npm ERR!
```

**Comment by legodude17** [comment] 2016-11-01 00:20
I believe this is a duplicate of #14124. Or it is related but different, and it is a duplicate of different issue. Do you agree @KenanY?

**Comment by KenanY** [comment] 2016-11-01 01:20
@legodude17 Not sure what the current stance on `EBUSY` is. Looks like they're all being consolidated into https://github.com/npm/npm/issues/8564.

**Comment by legodude17** [comment] 2016-11-01 14:34
@tecnosoftware you can check out the solution in #8564. One option is just to go ahead and reboot.

**Comment by othiym23** [comment] 2016-11-03 21:16
Closing as duplicate of #8564.

**Closed by othiym23** 2016-11-03 21:16 UTC
Labels: support
