### ISSUE TITLE
npm install operation not permitted

### ISSUE THREAD

**Issue by springRey** [npm/npm#19949] opened 2018-03-01 07:27 UTC
when i npm install I find the problem like this 
Unhandled rejection Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\node_cache\_cacache'

**Comment by kenany** [comment] 2018-03-01 16:35
Duplicate of https://github.com/npm/npm/issues/19948

**Closed as completed by kenany** 2018-03-01 16:35 UTC
Labels: support
