### ISSUE TITLE
npm search runs out of memory

### ISSUE THREAD

**Issue by nirmalksamuel** [npm/npm#10357] opened 2015-11-12 12:31 UTC
Steps to recreate the problem  (OR what i did so far):
1. Reference https://github.com/nodejs/node-v0.x-archive/issues/25370  to see how my first installation attempt got messy.  I do not think this issue is related to that, but i thought i will reference it anyway.
2. Went to  *c:\Documents And Settings\<USERNAME>\Application Data*  directory and removed all directories  related to npm.
3. Uninstalled  node.js using Windows Control Panel.  
4. Reboot machine & install node 4.x.x  stable version.
5. Reboot machine again.
6. Start  node.js  command prompt and issue the command  `npm  search prompt`.  The machine has nothing running after reboot and has 4GB  RAM,  but gives the error as seen in attached image.
7. Afterwards, i tried `npm init` and  while going through the default fields (name, version, description...),  i got a prompt saying  `entry point: (.mongorc.js)`.   I did have a mongoDB related package installed when i was using the previous node.js installation (that was done in summer 2014). But, how did npm know about it, after i completely uninstalled  node.js in previous steps ? Obviously the uninstall process is not cleaning up registry entries of prior versions. 

![screenshot 2015-11-12 03 13 27](https://cloud.githubusercontent.com/assets/7623186/11118368/2f47be14-88f6-11e5-819d-1c6ff2270aa3.png)

**Comment by nirmalksamuel** [comment] 2015-11-13 04:39
At the suggestion in another bug report,  i tried  defrag  of registry  using  PageDeFrag (Microsoft utility).  Then i removed  node.js using control panel and removed  npm directories like mentioned above.  Reboot and fresh installed  node.js.   Again i get the same error like shown in image when running  *npm  search prompt*.   It seems totally  broken on xp.  Has anyone tested this on xp ?

**Comment by nirmalksamuel** [comment] 2015-11-13 16:44
I continued with *npm init*  and  *npm install prompt -S*  followed by running a sample program called *solve.js*.  Here is the output i got.  I see a *prompt* directory under $APPDATA\npm-cache, but under c:\Program Files\nodejs\node_modules  i see only a directory called npm.  Can someone point me to solution. Thanks.
![screenshot 2015-11-13 07 41 04](https://cloud.githubusercontent.com/assets/7623186/11151580/c3864ca2-89e2-11e5-851c-d1d0adbf520c.png)
![screenshot 2015-11-13 08 32 31](https://cloud.githubusercontent.com/assets/7623186/11151579/c38384f4-89e2-11e5-8543-0a3aeb52aae3.png)

**Comment by nirmalksamuel** [comment] 2016-01-13 17:08
This is surprising. After 2 months of opening an issue, there is no comment on this.  Perhaps the wrong title  that makes people ignore this thread ?

**Comment by othiym23** [comment] 2016-01-13 21:21
There are many more issues open on npm than the team has time to deal with. Sorry for the delay!

1. `npm search` was designed for a registry that contained a couple hundred packages, not several hundred thousand. It uses an extremely naïve strategy to build and search its index. Nobody is happy with the state of CLI search, but we haven't had time to fix it yet, and it's still a ways down the priority queue. See [the `search` label](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Asearch) on the issue tracker for more detail. I don't have a specific expectation for when we'll land improvements to search, but there is work on it underway right now, and the current situation is embarrassing enough that the team isn't going to stop thinking about it altogether.
2. I'd take a closer look at how Node is configured on your system, because the amount of memory being used by Node in your first screenshot is pretty low for a memory failure. In particular, I'd check to see how much memory it was using when it crashed. An easy way to do this would be to run the Task Manager and see how much memory Node is using while you're running `npm search`. It's not uncommon for `npm search` to use up to a gigabyte when initially building the search index, so if it's using, say, around 100MB when it crashes, it might be worth digging into how your system is configured a little more deeply.
3. You need to be installing `prompt` from the same project root that you're running `solve.js` within. Looking at your screenshots, you're running `npm install prompt` in `C:\Documents and Settings\bharath`, and then running `solve.js` within `C:\nirmal\Coursera\Full Stack Dev\BootStrap-(Frontend Web Frameworks and Tools)\conFusion`. Node isn't going to be able to see `prompt` from the latter path. Node and npm don't install packages into a single package repository like Python or Ruby; dependent packages are installed into the current project. If you install `prompt` there, you should be set.

I'm going to close this issue as partially resolved, partially a duplicate (for the search stuff). Good luck getting things sorted out!

**Closed by othiym23** 2016-01-13 21:21 UTC
Labels: search, support
