### ISSUE TITLE
npm error in 5 MIN QUICKSTART example of Angular JS

### ISSUE THREAD

**Issue by GhosTTrain** [npm/npm#13900] opened 2016-09-08 08:19 UTC
I'm opening this issue because:
As stated above I am doing the 5 minute quickstart on Angular JS. Whenever I npm install the following error is produced. 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! file /Users/GhostMuse/angular2-quickstart/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /Users/GhostMuse/angular2-quickstart/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/GhostMuse/angular2-quickstart/npm-debug.log

The package installed previously without npm errors, however, that was short lived and now I cannot proceed with the quickstart until these errors are fixed. 

Please help out!!

Thanks

**Comment by frank-dspeed** [comment] 2016-09-08 10:25
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR! /Users/GhostMuse/angular2-quickstart/npm-debug.log

**Comment by frank-dspeed** [comment] 2016-09-08 10:25
The error tells you this is a bug with your package :D not NPM read it

**Comment by gholtslander-va** [comment] 2016-09-08 14:31
Your package.json file might just be empty anyway. It probably isn't a problem with either package.

`Failed to parse package.json data`

**Comment by GhosTTrain** [comment] 2016-09-12 22:36
I am doing the angular 5 min quick start example. I closely followed the steps but for some reason I received NPM ERR. So my package.json file is not empty it just does not compile. :(

**Comment by KenanY** [comment] 2016-09-13 04:31
@GhosTTrain Could you provide us with `/Users/GhostMuse/angular2-quickstart/package.json`?

**Comment by KenanY** [comment] 2016-09-19 19:01
Closing as abandoned.

**Closed by KenanY** 2016-09-19 19:01 UTC

**Comment by renzherl** [comment] 2017-02-16 06:13
1.Delete node_modules folder from your project.
2.Run 'npm cache clean' command.
3.Run 'npm install' command.

**Comment by manojmarneni** [comment] 2017-03-18 04:32
use `npm init` in your project folder.
You will be asked a series of questions – enter a value or hit Return to accept defaults. A package.json file will be created on completion which stores your npm configuration settings.
Now run your command again
