### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by yugam1** [npm/npm#16094] opened 2017-03-19 10:44 UTC
yugam@yugam-Inspiron-3542:~$ npm -g install embark
npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "embark"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/embark/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "embark"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! shasum check failed for /tmp/npm-4602-13b5514d/registry.npmjs.org/preserve/-/preserve-0.2.0.tgz
npm ERR! Expected: 815ed1f6ebc65926f865b310c0713bcb3315ce4b
npm ERR! Actual:   cb4d42d690c09435bc33236a44f549ce2595d8ce
npm ERR! From:     https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yugam/npm-debug.log

yugam@yugam-Inspiron-3542:~$ npm config get proxy
http://10.3.100.207:8080/
 i have latest version of npm and node geth
i have also tried cleaning cache

**Comment by legodude17** [comment] 2017-03-20 16:57
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by alyssaq** [comment] 2017-04-12 01:41
I ran into the same issue with modules using fsevents. This is with node v7.8.0 on linux.
I downgraded npm to `npm@4.1.1` as per the advice in #14626 and added this into my package.json:

     "optionalDependencies": {
       "fsevents": "*"
     }

**Comment by legodude17** [comment] 2017-04-12 16:23
If you used `yarn`, then why are you reporting it here?

**Comment by alyssaq** [comment] 2017-04-13 06:49
Good point.
I merely wanted to say that I ran into the same fsevents error using `npm install --no-optional` and came across this issue:
   
    npm ERR! Linux 4.9.13-moby
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-optional"
    npm ERR! node v7.8.0
    npm ERR! npm  v4.2.0
    npm ERR! code EBADPLATFORM

    npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm ERR! notsup Valid OS:    darwin
    npm ERR! notsup Valid Arch:  any
    npm ERR! notsup Actual OS:   linux
    npm ERR! notsup Actual Arch: x64


However, switching to `yarn install --no-optional` correctly excluded fsevent and I was able to get past the error:

    verbose 74.736 Performing "GET" request to "https://registry.yarnpkg.com/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz".
    verbose 74.787 Performing "GET" request to "https://registry.yarnpkg.com/builtin-modules/-/builtin-modules-1.1.1.tgz".
    verbose 74.807 Performing "GET" request to "https://registry.yarnpkg.com/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz".
    warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
    ...
    verbose 106.723 Copying "/root/.cache/yarn/v1/npm-websocket-driver-0.6.5-5cb2556ceb85f4373c6d8238aa691c8454e13a36/lib/websocket/driver/hybi/message.js" to "/app/node_modules/websocket-driver/lib/websocket/driver/hybi/message.js".
    [4/4] Building fresh packages...
    success Saved lockfile.

I also tried `npm install --no-optional` with npm@4.1.1 and had no luck.

**Closed** 2017-06-17 03:44 UTC
Labels: bot-closed
