### ISSUE TITLE
npm uninstall succeeds even if the package isn't installed

### ISSUE THREAD

**Issue by robertmain** [npm/npm#18760] opened 2017-10-08 23:51 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When running `npm uninstall` if no packages were uninstalled, it still says that 2 packages were uninstalled.

#### How can the CLI team reproduce the problem?

1. Run `npm uninstall blahblahlbhalbhjaioasdij` or really try to `npm uninstall` any package that doesn't exist

### supporting information:

 - `npm -v` prints: `5.3.0`

 - `node -v` prints: `v8.4.0`

 - `npm config get registry` prints: `https://registry.npmjs.org/`

 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run: USA (North East)
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2017-10-09 11:08
Duplicate of https://github.com/npm/npm/issues/16956.

**Closed as completed by kenany** 2017-10-09 11:08 UTC
Labels: npm5
