### ISSUE TITLE
Remove not exists package

### ISSUE THREAD

**Issue by rmalca** [npm/npm#17021] opened 2017-06-06 14:22 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm -g remove package_that_not_exist` returns `removed 1 package in 0.046s`.

### supporting information:

 - `npm -v` prints:
5.0.3
 - `node -v` prints:
v6.10.3
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [X] I don't use a proxy, but have limited or unreliable internet access.

**Comment by siddharthkp** [comment] 2017-06-06 16:01
I would like to add this happens without global flag `-g` as well.

**Comment by kenany** [comment] 2017-06-06 16:44
I believe this is a duplicate of https://github.com/npm/npm/issues/16956.

**Closed as completed by kenany** 2017-06-06 16:44 UTC
Labels: npm5
