### ISSUE TITLE
npm 5.0.0 fails to uninstall module | cb() never called!

### ISSUE THREAD

**Issue by sagarkm** [npm/npm#16826] opened 2017-05-31 13:41 UTC
Updated NPM to v5.0.0 on MAC. Trying to uninstall few npm packages like plotly:
npm uninstall plotly -g

Gives error:

> npm ERR! cb() never called!

Log attached

**Comment by thibmaek** [comment] 2017-05-31 16:18
Yes same here with full output:

Upgrading to node v8 fixes this.

<details>

```
 → npm uninstall -g yarn
Unhandled rejection Error: Argument #2: Expected string but got null json-stable-stringify@^1.0.1 fetched in 57ms
    at addDependency (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/thibaultmaekelbergh/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

</details>

**Comment by jochim-van-dijck** [comment] 2017-05-31 16:32
I am on node v8.0.0 but it doesn't seem to fix this issue for me.

**Comment by kudiaborm** [comment] 2017-05-31 16:45
On windows

I receive a similar error when trying to install npm itself "npm install npm -g"
And receive a "hex is not a function" error when trying to run npm install on any module

I can't even rollback to a previous version
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\kudiabom_a\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@3.10.8' ]
2 info using npm@5.0.0
3 info using node@v4.3.1
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 error cb() never called!
7 error This is an error with npm itself. Please report this error at:
8 error <https://github.com/npm/npm/issues>
`

**Comment by saschanaz** [comment] 2017-05-31 17:41
I got the same error today when uninstalling. Workaround: install the target package again and then uninstall.

I think npm5 expects an internal lock file and tries reading it before the file is actually generated, but not sure.

**Comment by jasonrpoteet** [comment] 2017-05-31 20:34
@SaschaNaz workaround worked for me!  thanks!  I was having this exact issue with uninstalling yarn after upgrading my ish.

**Comment by vladimirpavk** [comment] 2017-05-31 21:19
I got the same error today when i tried **_npm install_** for cloned repository.
@thibmaek answer solves the problem for me.

**Comment by DivineGod** [comment] 2017-06-01 04:38
Upgraded npm with `npm install -g npm@latest` then tried uninstalling `eslint` and other global modules that where previously installed. Got the same error and the workaround provided did work for most packages except `eslint-plugin-jsx-ally`

**Comment by romafederico** [comment] 2017-06-01 08:02
Updated to node v8 but the error presists. Any ideas?

**Comment by alasdairhurst** [comment] 2017-06-01 09:21
I get the same error when trying to *install* (windows)

```
d:\ahurst\Documents\module (master)
λ³ npm i
Unhandled rejection RangeError: Maximum call stack size exceedede module@1.5.1~preinstall: no script for prein
    at exports.create (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install\node.js:31:40)
    at C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install\node.js:33:25)
    at C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install\node.js:33:25)
    at normalizeTree (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (C:\Users\ahurst\AppData\Roaming\nvm\v7.7.3\node_modules\npm\lib\install.js:379:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ahurst\AppData\Roaming\npm-cache\_logs\2017-06-01T09_15_57_671Z-debug.log
```

log:
```λ³ cat C:\Users\ahurst\AppData\Roaming\npm-cache\_logs\2017-06-01T09_15_57_671Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i' ]
2 info using npm@5.0.0
3 info using node@v7.7.3
4 silly install runPreinstallTopLevelLifecycles
5 silly preinstall lbimaginearrow2@1.5.1
6 info lifecycle lbimaginearrow2@1.5.1~preinstall: lbimaginearrow2@1.5.1
7 silly lifecycle lbimaginearrow2@1.5.1~preinstall: no script for preinstall, continuing
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 error cb() never called!
11 error This is an error with npm itself. Please report this error at:
12 error <https://github.com/npm/npm/issues>
```

**Comment by saschanaz** [comment] 2017-06-01 09:27
The error in this issue is actually about `Expected string but got null`. I think RangeError is another one :smile:

**Comment by alasdairhurst** [comment] 2017-06-01 09:28
@SaschaNaz  fair enough, i'll make another ticket 👍

**Comment by ayushsinghvi92** [comment] 2017-06-03 21:02
same. Experiencing this on ubuntu

**Comment by NoahDragon** [comment] 2017-06-04 22:28
Got same error when uninstall global package on OS X. https://github.com/npm/npm/issues/16971

**Comment by zkat** [comment] 2017-06-05 15:15
Closing as duplicate of https://github.com/npm/npm/issues/16738

**Closed as completed by zkat** 2017-06-05 15:15 UTC
Labels: npm5
