### ISSUE TITLE
version not found: left-pad@0.0.3

### ISSUE THREAD

**Issue by camsaul** [npm/npm#12016] opened 2016-03-22 23:15 UTC
```bash
npm ERR! version not found: left-pad@0.0.3
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by othiym23** [comment] 2016-03-22 23:17
Closing as duplicate of #12012 / azer/left-pad#4.

**Closed by othiym23** 2016-03-22 23:17 UTC
