### ISSUE TITLE
Wrong npm install command

### ISSUE THREAD

**Issue by BalaKrishna-BALU** [npm/npm#9148] opened 2015-08-03 19:03 UTC
Hi,

I have written and published my logical-conversion npm module. After publishing, at right side in the sidebar panel the npm install command is displayed wrong.

Instead of displaying **npm install logical-conversion** it is displaying *npm i logical-conversion*.

[My module](https://www.npmjs.com/package/logical-conversion)

**Comment by othiym23** [comment] 2015-08-03 19:16
The npm web site (which has its own [i. ssue tracker](https://github.com/npm/newww/issues)) has a little bit of cleverness to try to fit longer package names into the little widget that displays the installation instructions. Because `npm i` is a shortcut that aliases to `npm install`, the page can drop a bunch of letters to try to make the install command fit into the display more nicely. Since this is by design, I'm going to close this issue, but if you think that it's surprising or confusing that npm switches between `npm i` and `npm install` on package pages, you can file an issue on npm/newww.

**Closed by othiym23** 2015-08-03 19:16 UTC
Labels: support

**Comment by BalaKrishna-BALU** [comment] 2015-08-03 19:32
Thanks for your help [othiym23](https://github.com/othiym23).
