### ISSUE TITLE
Errors building cordova

### ISSUE THREAD

**Issue by djErock** [npm/npm#11541] opened 2016-02-15 16:05 UTC
```
C:\newappfolder>npm install -g cordova
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
C:\Users\IT-ADMIN\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IT-ADMIN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.3.0
npm ERR! npm  v3.7.2
npm ERR! path C:\Users\IT-ADMIN\AppData\Roaming\npm\node_modules\.staging\abbrev-e9577473
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\IT-ADMIN\AppData\Roaming\npm\node_modules\.staging\abbrev-e9577473' -> 'C:\Users\IT-ADMIN\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\IT-ADMIN\AppData\Roaming\npm\node_modules\.staging\abbrev-e9577473' -> 'C:\Users\IT-ADMIN\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\newappfolder\npm-debug.log
npm ERR! code 1
```
[npm-debug.zip](https://github.com/npm/npm/files/131050/npm-debug.zip)

**Comment by othiym23** [comment] 2016-02-16 16:55
Closing as duplicate of #11265. Please see that issue if you want to help the CLI team isolate and / or fix the underlying bug. Thanks for your time!

**Closed by othiym23** 2016-02-16 16:55 UTC
Labels: bug, windows

**Comment by djErock** [comment] 2016-02-16 18:33
I had to reinstall node from scratch to fix the error

Sent from my Sprint Phone.

----- Reply message -----
