### ISSUE TITLE
Error: EACCES, open '/Users/Profile/.npm/_locks/browser-sync-ed941186c435fb34.lock'

### ISSUE THREAD

**Issue by jodriscoll** [npm/npm#7407] opened 2015-02-20 15:56 UTC
Trying to install browser-sync through command line with npm and receiving the following error:
```
mbpro:~ $ npm install -g browser-sync
npm WARN locking Error: EACCES, open '/Users/Profile/.npm/_locks/browser-sync-ed941186c435fb34.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/Profile/.npm/_locks/browser-sync-ed941186c435fb34.lock failed { [Error: EACCES, open '/Users/Profile/.npm/_locks/browser-sync-ed941186c435fb34.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Profile/.npm/_locks/browser-sync-ed941186c435fb34.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "browser-sync"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/browser-sync, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Profile/npm-debug.log
```

NPM is active
```javascript
mbpro:~ $ npm -v
2.5.1
```

As directed, I've uploaded my log file for further examination ([npm-debug.log](https://www.dropbox.com/s/p3ncscoijqo3vv2/npm-debug.log?dl=0))

**Comment by jodriscoll** [comment] 2015-02-20 15:57
I do apologize if this issue has already been addressed.  Thank you.

**Comment by KenanY** [comment] 2015-02-20 16:00
@jodriscoll Can you try taking ownership of your `.npm` directory?:

``` bash
$ sudo chown -R $(whoami) $HOME/.npm
```

**Comment by jodriscoll** [comment] 2015-02-20 17:13
@KenanY, just performed the execution without error.

I then navigated back to the folder I'd like to install browser-sync too, ran the command and was met with:
````javascript
mbpro:{location_directory} $ npm install -g browser-sync
npm ERR! tar.unpack untar error /Users/{profile}/.npm/browser-sync/2.2.1/package.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "browser-sync"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/lib/node_modules/browser-sync
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/browser-sync'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/browser-sync']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/browser-sync',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/browser-sync',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/{external_storage}/Environments/localhost/{location_directory}/npm-debug.log
````

Excuse the { ... } tags, I was simply trying to emit information to specific to my configuration.

**Comment by othiym23** [comment] 2015-02-21 08:15
Looks like you need `sudo` to run installs to `/usr/local` on your machine:

```
npm ERR! Please try running this command again as root/Administrator.
```

Give that a shot and see if it helps with the problem.

**Comment by nifl** [comment] 2015-03-04 04:25
@othiym23 [What, no sudo?!](http://foohack.com/2010/08/intro-to-npm/#what_no_sudo)

**Comment by othiym23** [comment] 2015-03-04 04:27
@nifl I let every user come to that place on their own. My job is to get people unstuck with their npm problems, not rework their entire workflow for them.

**Comment by ArwinLabWork** [comment] 2015-04-17 04:56
Run with sudo command and enter the  password of system user will solve the problem.
sudo npm install -g bower

**Comment by KenanY** [comment] 2015-04-17 10:56
@ArwinLabWork That's what @othiym23 said.

**Comment by othiym23** [comment] 2015-04-21 01:05
I'm going to close this as resolved. To the best of my knowledge, the command I included above will fix this every time with newish versions of npm.

**Closed by othiym23** 2015-04-21 01:05 UTC
Labels: support

**Comment by aaronhoffman** [comment] 2015-04-30 01:49
Wanted to mention that thanks to this issue #6922 I was able to resolve this by first executing `npm cache clean`

**Comment by KingJahfy** [comment] 2015-05-22 01:28
@aaronhoffman thank you was also able to solve this issue with `npm cache clean`

**Comment by waheb** [comment] 2015-06-10 01:40
re-trying with sudo works for me

**Comment by create10** [comment] 2015-06-12 12:51
If anyone gets those errors you have to run as administrator.You can run sudo before the comand or (which I didn't know until watching this video), you can also run: 
$ sudo !!   
(which will run the last command). This video is helpful. https://github.com/npm/npm/issues/7407

**Comment by HanQuang** [comment] 2015-08-11 14:47
@aaronhoffman  npm cache clean solved it for me too

**Comment by shieldsdesignstudio** [comment] 2015-08-18 13:30
Don't use sudo per [Browsersync documentation](http://www.browsersync.io/docs/#installation).

> WARNING - do not use sudo! If you're running Mac OSX and encounter problems when trying to install Browsersync - either globally or locally, it's almost always because you have problems with NPM permissions. Checkout their docs for a guide on how to fix this once and for all - it only takes 2 minutes :)

**Comment by vbalas6** [comment] 2016-02-02 09:16
sudo solved the problem

**Comment by ryansmith94** [comment] 2016-03-09 19:39
Thanks @tkolleh `npm cache clean` did the trick :+1:

**Comment by c0d3rman** [comment] 2016-05-15 19:52
^ 👍 `npm cache clean` is the proper solution, worked for me

**Comment by lucasar** [comment] 2016-05-31 18:29
In my case, changing the default directory was the solution: [Their docs](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory)

**Comment by ZelphirKaltstahl** [comment] 2018-05-24 11:54
`npm cache clean` only politely informs me it was capable of managing itself. After introducing it to the idea, that this might not be the case using the `--force`, that still did not fix it for me. Weirder even is, that the problem started to appear yesterday and never before, while I am on the same version as before.

Something is up again with the way npm manages permissions and ownership of files. I should not have to use anything with sudo in my home directory for tools like npm.

**Comment by kenany** [comment] 2018-05-24 21:13
> I should not have to use anything with sudo in my home directory for tools like npm.

This should indeed be the case. If not, open a new bug report and try to include minimal set of steps to reproduce. The reason `sudo` was suggested above was because users were installing packages to `/usr/local/`, which is outside of their home directory and not writable by their current account on their system.
