### ISSUE TITLE
ERR! Darwin 15.6.0 issue while doing ~: sudo npm install -g cordova

### ISSUE THREAD

**Issue by mynameisrandy** [npm/npm#15190] opened 2016-12-10 08:55 UTC
~:sudo npm install -g cordova
Password:
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-ef9cc920
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/randyphalla/npm-debug.log
npm ERR! code 1

**Comment by nicotheprogrammer** [comment] 2016-12-10 15:59
Got similar problem. Can anyone solve this?

**Comment by reigh-g** [comment] 2016-12-10 17:18
I was successful in installing it in an windows 8.1 environment a few days back. I'm replicating the installation in a windows 7 environment and I am also getting the same errors. I tried to un-install and install node.js and upate JDK but to no avail. I appreciate any help.

24084 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\HOME\AppData\Roaming\npm\node_modules\.staging\abbrev-34aaf29b' -> 'C:\Users\HOME\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
24084 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
24084 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
24084 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
24084 verbose stack
24084 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\HOME\AppData\Roaming\npm\node_modules\.staging\abbrev-34aaf29b' -> 'C:\Users\HOME\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
24084 verbose stack     at Error (native)
24085 verbose cwd C:\Users\HOME
24086 error Windows_NT 6.1.7601
24087 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
24088 error node v6.9.2
24089 error npm  v3.10.9
24090 error path C:\Users\HOME\AppData\Roaming\npm\node_modules\.staging\abbrev-34aaf29b
24091 error code ENOENT
24092 error errno -4058
24093 error syscall rename
24094 error enoent ENOENT: no such file or directory, rename 'C:\Users\HOME\AppData\Roaming\npm\node_modules\.staging\abbrev-34aaf29b' -> 'C:\Users\HOME\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
24095 error enoent ENOENT: no such file or directory, rename 'C:\Users\HOME\AppData\Roaming\npm\node_modules\.staging\abbrev-34aaf29b' -> 'C:\Users\HOME\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
24095 error enoent This is most likely not a problem with npm itself
24095 error enoent and is related to npm not being able to find a file.
24096 verbose exit [ -4058, true ]

**Comment by reigh-g** [comment] 2016-12-10 19:23
I was able to clear teh error and install apache cordova, I got the answer from https://github.com/npm/npm/issues/9633

1. npm clean cache
2. npm uninstall -g cordova
3. npm install -g cordova

**Comment by zkat** [comment] 2016-12-10 23:22
Closing as a duplicate of https://github.com/npm/npm/issues/15034

**Closed by zkat** 2016-12-10 23:22 UTC

**Comment by sumitebizon** [comment] 2017-01-25 07:35
Yes this solved my problem. Thanks!

**Comment by ragowthaman** [comment] 2017-06-30 17:52
This is awesome. Just a minor correction.....it should be

1. npm cache clean

Thanks a lot
