### ISSUE TITLE
updating npm is painful

### ISSUE THREAD

**Issue by matthewmueller** [npm/npm#4974] opened 2014-03-30 19:40 UTC
If you run:

```
npm install -g npm
```

And you get an error, `npm` is blown away from your system. This is especially problematic when you forget `sudo`.

**Comment by OmgImAlexis** [comment] 2015-12-01 04:18
@othiym23 isn't this a duplicate of https://github.com/npm/npm/issues/5050?

**Closed** 2017-06-19 11:16 UTC
Labels: bot-closed, bug
