### ISSUE TITLE
Package installed via github always appears in `outdated` results

### ISSUE THREAD

**Issue by feimosi** [npm/npm#11791] opened 2016-03-06 11:39 UTC
I've installed a package like so: 
`npm i github:saintmac/angular-cache-buster#06e95ad -S`
Now when I run `npm outdated` I get such result:
```
Package               Current  Wanted  Latest 
angular-cache-buster    0.4.3     git     git 
```
Using `npm update` doesn't help.
It's worth mentioning that I had to use direct Git installation because npm repository contains only the old version (namely 0.4.0)

**Comment by KenanY** [comment] 2016-03-06 15:56
ref. https://github.com/npm/npm/issues/8170

**Comment by KenanY** [comment] 2016-05-15 18:31
also ref. https://github.com/npm/npm/issues/8300

**Comment by KenanY** [comment] 2016-07-02 17:59
I'm gonna close this as a duplicate of the issues I linked above.

**Closed by KenanY** 2016-07-02 17:59 UTC
