### ISSUE TITLE
Error installing Cordova - fetch failed with status code 502

### ISSUE THREAD

**Issue by alextrejo** [npm/npm#13294] opened 2016-07-06 13:29 UTC
**I'm opening this issue because:**

npm is returning following error:
error fetch failed https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz

**What's going wrong?**
Can't install Apache Cordova

**How can the CLI team reproduce the problem?**

npm install -g cordova

**Supporting information:**

 - `npm -v` prints:
error npm  v3.9.5
 - `node -v` prints:
error node v6.2.2

 - `npm config get registry` prints:
error Windows_NT 10.0.10586

**Logs excerpt**:
9791 silly gunzTarPerm extractEntry node_modules/write-file-atomic/.nyc_output/47250.json
9792 silly gunzTarPerm modified mode [ 'node_modules/write-file-atomic/.nyc_output/47250.json',
9792 silly gunzTarPerm   420,
9792 silly gunzTarPerm   438 ]
9793 silly gunzTarPerm extractEntry node_modules/write-file-atomic/.travis.yml
9794 silly gunzTarPerm modified mode [ 'node_modules/write-file-atomic/.travis.yml', 420, 438 ]
9795 silly gunzTarPerm extractEntry node_modules/write-file-atomic/test/basic.js
9796 silly gunzTarPerm modified mode [ 'node_modules/write-file-atomic/test/basic.js', 420, 438 ]
9797 info retry fetch attempt 2 at 8:10:27 AM
9798 info attempt registry request try #1 at 8:10:27 AM
9799 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9800 http fetch 502 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9801 info retry will retry, error on last attempt: Error: server error 502
9802 info attempt registry request try #2 at 8:10:37 AM
9803 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9804 http fetch 502 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9805 info retry will retry, error on last attempt: Error: server error 502
9806 silly addBundled read tarball
9807 silly cleanup remove extracted module
9808 info attempt registry request try #3 at 8:11:37 AM
9809 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9810 http fetch 502 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9811 error fetch failed https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9812 warn retry will retry, error on last attempt: Error: fetch failed with status code 502
9813 info retry fetch attempt 3 at 8:12:38 AM
9814 info attempt registry request try #1 at 8:12:38 AM
9815 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9816 http fetch 502 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9817 info retry will retry, error on last attempt: Error: server error 502
9818 info attempt registry request try #2 at 8:12:48 AM
9819 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9820 http fetch 502 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9821 info retry will retry, error on last attempt: Error: server error 502
9822 info attempt registry request try #3 at 8:13:48 AM
9823 http fetch GET https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9824 http fetch 502 https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9825 error fetch failed https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
9826 silly rollbackFailedOptional Starting
9827 silly rollbackFailedOptional Finishing
9828 silly runTopLevelLifecycles Starting
9829 silly runTopLevelLifecycles Finishing
9830 silly install printInstalled
9831 verbose stack Error: fetch failed with status code 502
9831 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
9831 verbose stack     at emitOne (events.js:96:13)
9831 verbose stack     at Request.emit (events.js:188:7)
9831 verbose stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:977:10)
9831 verbose stack     at emitOne (events.js:96:13)
9831 verbose stack     at ClientRequest.emit (events.js:188:7)
9831 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
9831 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
9831 verbose stack     at TLSSocket.socketOnData (_http_client.js:361:20)
9831 verbose stack     at emitOne (events.js:96:13)
9831 verbose stack     at TLSSocket.emit (events.js:188:7)
9832 verbose cwd C:\Windows\System32
9833 error Windows_NT 10.0.10586
9834 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
9835 error node v6.2.2
9836 error npm  v3.9.5
9837 error fetch failed with status code 502
9838 error If you need help, you may report this error at:
9838 error     <https://github.com/npm/npm/issues>
9839 verbose exit [ 1, true ]

**Comment by erickrawczyk** [comment] 2016-07-06 13:51
shit's broken, yo #13284 http://status.npmjs.org/

**Comment by othiym23** [comment] 2016-07-06 14:53
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:53 UTC
