### ISSUE TITLE
npm auto remove my other packages when install a package

### ISSUE THREAD

**Issue by NextZeus** [npm/npm#18206] opened 2017-08-17 13:06 UTC
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
when i install timekeeper , npm auto remove my local 4 packages from node_modules:

async-listener
emitter-listener
shimmer
tingyun

~ » node -v                                                    
v8.0.0
------------------------------------------------------------
~ » npm -v                                                     
5.0.0

**Comment by kenany** [comment] 2017-08-17 13:37
Duplicate of https://github.com/npm/npm/issues/16853.

**Closed as completed by kenany** 2017-08-17 13:37 UTC
Labels: npm5
