### ISSUE TITLE
npm install shelljs - ECONNABORTED

### ISSUE THREAD

**Issue by xsapguru** [npm/npm#7604] opened 2015-03-11 21:34 UTC
Hi All,

I have installed the NodeJS recent version v0.12.0. And tried to use the command ( on Windows 7 Professional 64 bit) > npm install shelljs
This gave me an error as attached. 

```
npm WARN package.json create_fiori_client@3.6.3 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "shelljs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ECONNABORTED
npm ERR! errno ECONNABORTED
npm ERR! syscall connect

npm ERR! connect ECONNABORTED
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\SAP\MobileSDK3\KapselSDK\apps\fiori_client\npm-debug.log
```

I am in corporate network. and have used the npm config set registry options as well. But no luck. 

Can someone please help me in this regard ?

Sam

**Comment by smikes** [comment] 2015-03-20 01:25
Thanks for reporting this.  Could you please upload your full log (`c:\SAP\MobileSDK3\KapselSDK\apps\fiori_client\npm-debug.log`) to github as a gist: https://gist.github.com

This may be a problem with node 0.12.0, but we really need to see the stack trace (which should be in that file) in order to narrow down the cause.

Thanks!

**Comment by smikes** [comment] 2015-05-03 03:04
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment] 2015-08-11 21:33
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Closed by ehsalazar** 2015-08-11 21:33 UTC
Labels: support, windows
