### ISSUE TITLE
ERR! Converting circular structure to JSON

### ISSUE THREAD

**Issue by JustinBeckwith** [npm/npm#11400] opened 2016-02-03 16:37 UTC
Using NPM 3.7, tried running `npm install`, and got a circular structure error.  `package.json` and `npm-debug.log` are here:

https://gist.github.com/JustinBeckwith/9eb7e0cd0a27f51cf550

Thanks!

**Comment by KenanY** [comment] 2016-02-03 18:15
@JustinBeckwith Duplicate of https://github.com/npm/npm/issues/11349. Fix already released in `3.7.1`

**Comment by ashleygwilliams** [comment] 2016-02-06 16:29
closing. @JustinBeckwith please open a new issue if you continue to have trouble in version `3.7.1`!

**Closed by ashleygwilliams** 2016-02-06 16:29 UTC
