### ISSUE TITLE
peerDependencies for scoped packages are installed incorrectly

### ISSUE THREAD

**Issue by evil-shrike** [npm/npm#6970] opened 2014-12-18 13:14 UTC
Given a scoped package with a peerDependency
```json
{
  "name": "@myco/generator-my",
  "peerDependencies": {
    "yo": ">=1.0.4"
  }
}
```
When I install the package npm puts yo inside additional 'node_modules' folder (probably it ignore 2-level folding for scoped packages):
```
\node_modules
    \@myco
        \generator-my
    \node_modules\
        \yo
```
npm's vesion: 2.1.12

**Comment by msamblanet** [comment] 2015-02-23 20:56
I encountered this same issue - I am not familiar enough with the NPM code to be comfortable offering a patch, but until someone does, I have found the hack below seems to resolve the issue for me...hopefully this will help someone...

Find npm's lib/install.js and locate installMany (around line 633)
First thing inside this function add the following code:

```js
  //***** BEGIN HACK *****
  // MRS 2/23/2015 - Hack around NPM  bug 6970 - https://github.com/npm/npm/issues/6970
  // This detects that we seem to be installing into the wrong folder and adjusts
  // the folder name.  I am not sure if this is the best or a fully general purpose
  // fix to this bug but it seems to resolve the issue for us...
  if (/[\/\\]node_modules$/.exec(where)) {
    var newWhere = where.substring(0, where.length - 13);
    log.info("install-hack-6970", "Altering where from %s to %s", where, newWhere);
    where = newWhere;
  }
  //***** END HACK *****
```

**Comment by msamblanet** [comment] 2015-04-20 17:53
For others who may bump into this issue, this sounds like it is fixed by [this pull request](https://github.com/npm/npm/pull/7920)

**Comment by othiym23** [comment] 2015-04-20 22:04
@msamblanet it is indeed, and so I'm closing it as a duplicate of #7454. Thanks for the heads up!

**Closed by othiym23** 2015-04-20 22:04 UTC
Labels: bug, next-patch, patch-welcome
