### ISSUE TITLE
Bad gateway (502) when trying to install babel-preset-stage-2

### ISSUE THREAD

**Issue by elcuy** [npm/npm#13287] opened 2016-07-06 09:07 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Can't install babel-preset-stage-2

#### How can the CLI team reproduce the problem?
npm install --save-dev babel-preset-stage-2

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: 6.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows

### Logs:
npm install --save-dev babel-preset-stage-2
npm ERR! fetch failed https://registry.npmjs.org/babel-plugin-transform-object-rest-spread/-/babel-plugin-transform-object-rest-spread-6.8.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

**Comment by michaelneale** [comment] 2016-07-06 09:13
We are seeing the same thing from AWS. Curling the resources produces a 502 bad gateway error: 
```
+ curl -I https://registry.npmjs.org/babel-plugin-transform-react-jsx-self/-/babel-plugin-transform-react-jsx-self-6.11.0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Cache-Control: max-age=21600
Transfer-Encoding: chunked
Accept-Ranges: bytes
Date: Wed, 06 Jul 2016 09:12:37 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-jfk1025-JFK
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1467796357.794423,VS0,VE7

[Pipeline] sh
[npmsucks] Running shell script
+ curl -I https://registry.npmjs.org/babel-plugin-transform-object-rest-spread/-/babel-plugin-transform-object-rest-spread-6.8.0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Cache-Control: max-age=21600
Transfer-Encoding: chunked
Accept-Ranges: bytes
Date: Wed, 06 Jul 2016 09:12:38 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-jfk1044-JFK
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1467796358.070094,VS0,VE64
```

**Comment by michaelneale** [comment] 2016-07-06 09:22
I can access it from Sydney, australia, which uses a local varnish cache. 

@elcuy can you run: 
```
curl -I 'https://registry.npmjs.org/babel-plugin-transform-object-rest-spread/-/babel-plugin-transform-object-rest-spread-6.8.0.tgz'
```
And paste results? I wonder if we are both hitting the same bad varnish cache instance.

**Comment by davecozens** [comment] 2016-07-06 09:22
See https://github.com/npm/npm/issues/13284

**Comment by elcuy** [comment] 2016-07-06 10:30
It is solved! Thanks all. I just had to wait for the npm general issue to be solved

**Comment by othiym23** [comment] 2016-07-06 14:51
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:51 UTC
