### ISSUE TITLE
Proposal: Downgrade to warn for "npm ls" of known extraneous packages

### ISSUE THREAD

**Issue by thanpolas** [npm/npm#6141] opened 2014-09-08 09:04 UTC
While trying to apply `npm shrinkwrap` I had issues with extraneous packages. Their origin was known, they were installed by the [napa package](https://github.com/shama/napa) which is a handy library that installs frontend libraries as npm modules for consumption by browserify.

The extraneous Error originates from `npm ls` and I wanted to ask, before taking the time to submit a PR, if you would be open to create an array of `knownPackages` like napa and honor their respective keys in package.json (in this case it would be the `napa` key) so that detected extraneous packages that can be resolved to known packages like napa would not generate an Error but a Warn, allowing shrinkwrap to move forward.

/cc shama/napa#20

**Comment by othiym23** [comment] 2016-08-19 21:21
Things have changed a bit since the advent of `npm@3`. Now, if you have a dependency included in `bundledDependencies` that’s _not_ in your `dependencies`, it will still be included in the published package, and copied to the local install at `npm install` time. It doesn’t necessarily have to be in the `dependencies` list, but if it is, it just needs to have a `”version”` that matches what’s in `dependencies`. That makes it possible to send `napa`-installed dependencies along for the ride when publishing a package. Those dependencies will still be marked as extraneous at `npm shrinkwrap` or `npm ls` time, so maybe an `--ignore-extraneous` switch would still make sense.

As to the rest, the point of `npm shrinkwrap` is to create reproducible builds. So far, that concept has assumed that all of the reproducibility is coming from npm itself. It is, and should be, an error at shrinkwrap time when there’s something in an installed application that npm doesn’t know how to reproduce. Perhaps tools like `napa` could be modified to run `npm prune` before creating the shrinkwrap file, or perhaps the CLI could implement an `--ignore-extraneous` switch, although the latter feels like a footgun that shouldn’t just be left lying around without a stronger justification. The CLI team is mulling over potential changes to how shrinkwrap works, and a number of those changes revolve around what kinds of install metadata are captured in the shrinkwrap file, and it’s possible that some kind of external tool integration could be incorporated there at some point. For now, though, I think it’s prudent to err on the side of conservatism and just say that we don’t intend to land these particular changes within npm itself in the near term. Thanks for your time, and all the discussion!

**Closed by othiym23** 2016-08-19 21:21 UTC
Labels: feature-request
