### ISSUE TITLE
Changes in npm5 break my optional dependencies workflow

### ISSUE THREAD

**Issue by dominikwilkowski** [npm/npm#16772] opened 2017-05-29 01:44 UTC
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?

`npm i @gov.au/body` (btw running this twice will eventually work)

Will produce an error:

`ENOENT: no such file or directory, uv_cwd`

We have a script running on `postinstall` that installs optional packages via `npm install` in a child process. This is so we can disable certain packages in ci and production builds that need to be faster. Regardless this has worked amazingly well in the past until I just tested it in npm 5. I'm guessing how you stage your installed packages has changed before running `postinstall`? It's hard to debug so any tips I could get about what has changed so I can fix this issue?

### supporting information:

 - `npm -v` prints: `5.0.0`
 - `node -v` prints: `7.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by zkat** [comment] 2017-05-29 05:01
@dominikwilkowski Do you have a debug log, or perhaps output from pancake? `uv_cwd` looks super suspicious to me, and I wasn't able to reproduce this when installing your repo.

**Comment by dominikwilkowski** [comment] 2017-05-29 05:04
@zkat Every time I run `npm init --yes && npm i @gov.au/body` in an empty folder I get the same issue. If you can't reproduce then it must be my machine... I will investigate further.

**Comment by zkat** [comment] 2017-05-29 05:10
The `uv_cwd` makes me suspect it might have to do with your node version for some reason. I have no clue how an internal `libuv` thing would leak out like that.

I made another fresh attempt, btw, and still no dice (sorry, I hope we can figure this out, it sounds awful):

<img width="494" alt="screen shot 2017-05-28 at 22 09 16" src="https://cloud.githubusercontent.com/assets/17535/26537230/664f496e-43f2-11e7-8bb1-f0446f2a5479.png">

**Comment by dominikwilkowski** [comment] 2017-05-29 05:13
Ah I'm glad you can reproduce it at least. I did install npm5 on top of node 7.10 via `npm i npm@next -g`... Maybe that helps? I keep working on it

**Comment by zkat** [comment] 2017-05-29 05:14
ahahhaah I *completely* missed that in the output, I'm so sorry. It looks like I *can* reproduce this but my eyes lost it in the color space. I'll 🕵️‍♀️ some more soon.

**Comment by zkat** [comment] 2017-05-29 05:20
Ahhh. It looks like `uv_cwd` gets thrown like this when the cwd is removed, and the user calls `process.cwd()`. So basically something going awry and cwd is going away in postinstall _somehow_. I'm surprised this is a bug in npm itself. I wonder if it's `pancake` doing something funny. I'll take a look at postinstall anyway :)

**Comment by dominikwilkowski** [comment] 2017-05-29 05:29
Have a look at the code here: https://github.com/govau/pancake

The only time I actually run `process.cwd()` is here: https://github.com/govau/pancake/blob/master/packages/pancake/src/helpers.js#L74
From there on out I pass it to each function.

I know that postinstall scripts are called from inside the staging folder. Have there been any changes in staging? Would the folder structure change from the beginning of a script to the end of it while in postinstall?

**Comment by dominikwilkowski** [comment] 2017-06-18 10:46
Any head waves on this one yet?

**Comment by elclanrs** [comment] 2017-06-27 16:39
We are being affected by this bug as well if I understand it correctly. In postinstall `$PWD` in npm@4 is the project folder, but in npm@5 is the package folder.

So if my project is `/home/my-project` and my package is at `/home/my-package` then:

- In npm@4 with `npm install ../my-package` then `PWD` in postinstall is `/home/my-project`
- In npm@5 with `npm install file:../my-package` then `PWD` in postinstall is `/home/my-package`

This breaks everything else in our postintall because we use `$PWD` throughout the script.

@dominikwilkowski, is this the same bug being reported here?

**EDIT:** I guess it not the same error, there is another issue linked below with the exact title of the issue I'm having.

**Comment by zkat** [comment] 2017-07-01 03:31
This seems to be working just fine as of the latest canary. It will land in the next release, probably next Wednesday. Not sure what fixed this, but yay it works.

Note: you still have to run npm with node 7 because apparently node-sass hates node8. But that's not an npm issue.

Closing this! Cheers!

**Closed by zkat** 2017-07-01 03:31 UTC
Labels: bug, lifecycle, npm5
