### ISSUE TITLE
Why npm install is not working while creating ionic2 project

### ISSUE THREAD

**Issue by RakeshKW** [npm/npm#17462] opened 2017-06-27 12:26 UTC
Here is my problem:

E:\Ionic>ionic start asa1 blank
✔ Creating directory .\asa1 - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN peerDependencies The peer dependency @angular/tsc-wrapped@* included from @ionic/app-scripts will no
        npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
        npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Cloning into
        'C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1'...
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        git-upload-pack
        'C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979':
        git-upload-pack: command not found
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        fatal: Could not read from remote repository.
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        Please make sure you have the correct access rights
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:
        and the repository exists.
        npm ERR! git clone
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-7c47a979
        C:\Users\rakes\AppData\Local\Temp\npm-7756-ccc181f5\git-cache-5713e4c2d2f7\31d080cee1d8a4b74e03818aaee14da8062f0ea1:

        npm ERR! git fetch -a origin (https://github.com/resin-io/bonjour.git) fatal: Unable to find remote helper for
        'https'
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit  resin-io/bonjour resetting remote
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee because of
        error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: Cloning into
        bare repository
        'C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee'...
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: Host key
        verification failed.
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: fatal: Could
        not read from remote repository.
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee:
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: Please make
        sure you have the correct access rights
        npm ERR! git clone --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee: and the
        repository exists.
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe"
        "C:\\Users\\rakes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.9.1
        npm ERR! npm  v2.15.11
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        git@github.com:resin-io/bonjour.git
        C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee
        npm ERR! Cloning into bare repository
        'C:\Users\rakes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-resin-io-bonjour-git-a2c5a7ee'...
        npm ERR! Host key verification failed.
        npm ERR! fatal: Could not read from remote repository.
        npm ERR!
        npm ERR! Please make sure you have the correct access rights
        npm ERR! and the repository exists.
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     E:\Ionic\asa1\npm-debug.log

**Comment by miami1109** [comment] 2017-06-27 12:40
Hi, is this your first project ??

Actually, I have done my first project,  I didn't face any problem..all npm packages were installed properly.  But now I am facing so many issues.. :(
Am really not getting where is the problem is exactly.

**Comment by miami1109** [comment] 2017-06-27 12:45
C:\Users\xxxxx>ionic
_ _
() ()

| |/ _ | '_ | |/ |
| | (_) | | | | | (
||___/|| |||___| CLI 3.4.0

Usage:

$ ionic <command> [--help] [--verbose] [--quiet] [<args>] [options]
$ ionic [--confirm] [--no-interactive] [--yarn] [--no-timeout]
Global Commands:

docs ..................... Open the Ionic documentation website
info ..................... Print system/environment info
login .................... Login with your Ionic ID
signup ................... Create an Ionic account
start .................... Create a new project
telemetry ................ Opt in and out of telemetry
Project Commands:

**You are not in a project directory.**
Now again I have encountered some issues

Global Commands like : emulate, plugin, resources, bulid, run , platform etc are not installed
What does it mean "**You are not in a project directory**"??

Also I have faced this issues.

**Comment by RakeshKW** [comment] 2017-06-27 12:47
no its not my first project..
Actually like you i also created project 3 day ago and its working fine....
But today i don't know what happens to "npm install" ....i am trying to create new project  but its not creating properly and giving above error what i mentioned in issue

**Comment by miami1109** [comment] 2017-06-27 12:53
hmm.. i think npm is dead.

**Comment by RakeshKW** [comment] 2017-06-27 13:39
ya ....i think there are updating something ....

**Comment by relativokobe** [comment] 2017-06-27 15:07
I'm having thesame problem...:(

**Comment by kenany** [comment] 2017-06-27 15:08
Looks like a duplicate of https://github.com/npm/npm/issues/17460.

**Closed as completed by kenany** 2017-06-27 15:08 UTC
Labels: support, git

**Comment by rtanzifi** [comment] 2017-06-27 15:57
Same problem here. What is wrong with that?

**Comment by laerteuliam** [comment] 2017-06-27 17:31
same problem here...

**Comment by alejandrofransoy** [comment] 2017-06-27 19:16
same problem here

**Comment by relativokobe** [comment] 2017-06-27 19:24
https://www.polymer-project.org/2.0/docs/tools/polymer-cli follow these steps then run npm install @ionic/app-scripts@latest --save-d.

**Comment by KaleKing** [comment] 2017-06-28 03:07
I have the same problem and I tried the above method from @relativokobe and it doesn't work I get the following error when trying to run npm install @latest --save-d

Unhandled rejection Error: Invalid tag name "@latest": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
    at resolve (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Users\claude\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:200:16
    at C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:199:3)
    at Object.Installer.loadArgMetadata (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\lib\install.js:325:3)
    at C:\Users\claude\AppData\Roaming\npm\node_modules\npm\lib\install.js:648:16
    at BB.join.then (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\claude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)

**Comment by sakib0hasan** [comment] 2017-06-28 05:19
Hey, I just ran command prompt with admin rights, and **it worked for me**. Can anyone else verify it?
Thanks!

**Comment by teerasej** [comment] 2017-06-28 05:54
@walcott911 it has progress, by running command prompt with admin rights.

Now it stucks with new error at this error while running in **npm install** section

```
C:\Users\Teerasej\Desktop\MyApp>ionic start NFApp-test blank
✔ Creating directory .\NFApp-test - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm ERR! code 1
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Teerasej\AppData\Roaming\npm-cache\_logs\2017-06-28T05_53_05_216Z-debug.log
```

**Comment by skylercole** [comment] 2017-06-28 06:29
Also note that first line: object-keys version WARN outdated. Local version installed is 1.0.11, so why is it telling us to update?
I wonder is this problem true for other npm installs? Doesn't this affect like a 100 billion devs or so? :)

**Comment by skylercole** [comment] 2017-06-28 06:34
@relativokobe not much luck after updating polymer-cli

**Comment by stardigits** [comment] 2017-06-28 06:35
The solution for me on Windows 8 by doing **downgrade git to version 1.9.5**.

**Comment by miami1109** [comment] 2017-06-28 06:45
The problem is from npm
All the devs are facing same issues.
What shall we do now ??

**Comment by RakeshKW** [comment] 2017-06-28 08:21
go to your project root directory in CLI mode

run npm install @ionic/app-scripts@latest
then open package.json file of your project and add "reflect-metadata": "^0.1.3" in dependancies and 
then run npm install command 
then run ionic serve --lab 
it will work

**Comment by RakeshKW** [comment] 2017-06-28 09:36
go to your project root directory in CLI mode

run npm install @ionic/app-scripts@latest
then open package.json file of your project and add "reflect-metadata": "^0.1.3" in dependancies and 
then run npm install command 
then run ionic serve --lab 
it will work

**Comment by RakeshKW** [comment] 2017-06-28 09:36
> go to your project root directory in CLI mode
> 
> run npm install @ionic/app-scripts@latest
> then open package.json file of your project and add "reflect-metadata": "^0.1.3" in dependancies and 
> then run npm install command 
> then run ionic serve --lab 
> it will work

**Comment by RakeshKW** [comment] 2017-06-28 09:37
```
> `go to your project root directory in CLI mode
> 
> run npm install @ionic/app-scripts@latest
> then open package.json file of your project and add "reflect-metadata": "^0.1.3" in dependancies and 
> then run npm install command 
> then run ionic serve --lab 
> it will work`
```

**Comment by khinchotin** [comment] 2017-10-12 06:43
You can try this. It work for me.Very nice 😄 


Run  these commands,

1.  ionic cordova platform rm android
2.  npm update -g ionic cordova

Thanks.

**Comment by himanshurajputx** [comment] 2018-01-05 14:00
My first ionic app (ionic start Myapp tabs)
but I found some error please solved this error  
===========================================================
√ Creating directory .\MyLove - done!
√ Downloading and extracting tabs starter - done!

? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
√ Personalizing ionic.config.json and package.json - done!
> ionic integrations enable cordova --quiet
[ERROR] Error with .\MyLove\node_modules\ionic-angular\package.json file: FILE_NOT_FOUND
[ERROR] Error with .\MyLove\node_modules\@ionic\app-scripts\package.json file: FILE_NOT_FOUND
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Added cordova integration!

Installing dependencies may take several minutes.

  *   IONIC  DEVAPP  *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):



        > node-sass@4.5.3 install C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > uglifyjs-webpack-plugin@0.4.6 postinstall
        C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.js


        > node-sass@4.5.3 postinstall C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe
        C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext=
        --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@9.3.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError
        (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError
        (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError
        (C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:80:29)\n    at
        C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:89:16\n    at
        C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete
        (fs.js:166:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError
        (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError
        (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError
        (C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:80:29)\n    at
        C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\which\\which.js:89:16\n    at
        C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete
        (fs.js:166:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython
        (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous>
        (C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
        gyp ERR! System Windows_NT 10.0.16299
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
        "C:\\DaTa@DrIvE\\WorKsPace\\Ionic\\MyLove\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
        "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\DaTa@DrIvE\WorKsPace\Ionic\MyLove\node_modules\node-sass
        gyp ERR! node -v v9.3.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted
        {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.5.3 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Himanshu Rajput\AppData\Roaming\npm-cache\_logs\2018-01-05T13_54_38_725Z-debug.log

**Comment by AmrAbdalrahman** [comment] 2018-07-10 14:35
try 
`npm cache clean --force`
