### ISSUE TITLE
npm update shasum check failure

### ISSUE THREAD

**Issue by billfranklin** [npm/npm#12162] opened 2016-03-31 20:14 UTC
```
70 error Windows_NT 6.1.7601
71 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\etani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
72 error node v5.9.1
73 error npm  v3.3.9
74 error shasum check failed for C:\Users\etani\AppData\Local\Temp\npm-21408-9d2a4617\registry.npmjs.org\npm\-\npm-3.8.3.tgz
74 error Expected: f2c40972f023e17594d570a3da1d619bdf96bdb7
74 error Actual:   084037eb69a0302a25577082bd0ff5e07d1f8320
74 error From:     http://registry.npmjs.org/npm/-/npm-3.8.3.tgz
75 error If you need help, you may report this error at:
75 error     <https://github.com/npm/npm/issues>
```

**Comment by billfranklin** [comment] 2016-03-31 20:19
Tried npm cache clean and that did not resolve the issue

**Comment by zkat** [comment] 2016-12-09 00:45
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:45 UTC
Labels: shasum, support
