### ISSUE TITLE
registry returns gzip'ed response even if the client has no accept-encoding header

### ISSUE THREAD

**Issue by ds82** [npm/npm#12205] opened 2016-04-05 14:30 UTC
Hi,

it seems the registry returns gzip'ed results for some requests lately. I believe this leads to the many bugs that were reported lately (e.g. #12203, and some others).

For us, it breaks our build! We use an internal npm registry mirror (krakenjs/kappa) which uses hapi proxy internally. hapi proxy can't handle gzip'ed responses. 

I already patched the kappa code to explicitly remove the `accept-encoding` header, but registry.npmjs.org still responds with gzip'ed files.

It's strange that it not happens for all packages .. e.g.:

 The response to ```http://registry.npmjs.org/async``` is gezip'ed. The response to ```http://registry.npmjs.org/tiny-di``` is not.

**Comment by benjdlambert** [comment] 2016-04-05 14:41
@ds82 that's what I was seeing, see #12202. I thought it was bad cache variants.. as in its cached a gzip response on a resource without the `accept-encoding`.

**Comment by benjdlambert** [comment] 2016-04-05 14:49
Doesn't content length have to be above a certain size for g-zipping to be enabled on some resources?

**Comment by mikedoug** [comment] 2016-04-05 14:50
This makes a lot of sense.  Hopefully they can fix their web server configurations to not respond with gzipped data on responses without the client.  Does anyone know of a mirror that isn't affected by this issue?

**Comment by ds82** [comment] 2016-04-05 14:53
> Doesn't content length have to be above a certain size for g-zipping to be enabled on some resources?

I observed this behaviour as well .. it seems that if the JSON response is below a certain size threshold, it is not gezip'ed.

**Comment by mikedoug** [comment] 2016-04-05 14:55
That makes sense.  Though if the client isn't asking for gzipped data, it shouldn't be receiving it.

**Comment by ds82** [comment] 2016-04-05 15:25
I tried to setup a nginx proxy to registry.npmjs.org which de-compresses all requests before forwarding it to the client .. but that doesn't seem to work. 

I hope the npm guys are fixing this soon!

**Comment by othiym23** [comment] 2016-04-05 15:25
Closing as duplicate of #12196.

**Closed by othiym23** 2016-04-05 15:25 UTC
Labels: bug, registry

**Comment by jasisk** [comment] 2016-04-06 00:14
For anyone stumbling onto this for kappa, I pushed a fix in `rc` dist-tag ~17 hours ago. It's sitting in the [https://github.com/krakenjs/kappa/tree/760cf6e4c4119641abdded1768f8e36696dd7be6](always-attempt-gzip) branch and released as `1.0.0-rc.14`. Not yet in master as it was a hotfix and I need to backfill some tests (but it's been running smoothly for us since).

**Comment by Chaoui05** [comment] 2016-04-06 11:11
i installed this modul to get a report in Dalek
![dalekreport1](https://cloud.githubusercontent.com/assets/18040660/14313196/7f877a14-fbf0-11e5-99e7-880915d650e5.png)
 And when i use the line command this error message appears :+1: 
![dalekreport2](https://cloud.githubusercontent.com/assets/18040660/14313225/a4db423c-fbf0-11e5-9906-98f5e2f7cbca.png)
