### ISSUE TITLE
git+ssh:// changed to ssh:// on npm install

### ISSUE THREAD

**Issue by sruf** [npm/npm#11176] opened 2016-01-16 18:51 UTC
When installing an update of a package referenced by an git+ssh:// url, npm overwrites package.json (even without --save flag) and changes the git+ssh:// uri to ssh://

**Comment by othiym23** [comment] 2016-01-18 03:52
This is a duplicate of #9679, so I'm closing it as such, but be aware that #11091 will fix this, and is due to be landed in the next stable versions of `npm@3` and `npm@lts`.

**Closed by othiym23** 2016-01-18 03:52 UTC
Labels: bug, git
