### ISSUE TITLE
Re-allow updates to pre-existing "invalid" named packages

### ISSUE THREAD

**Issue by isaacs** [npm/npm#7195] opened 2015-01-23 01:52 UTC
See https://github.com/fb55/CSSwhat/pull/7#issuecomment-71124026

If folks would like to push updates to packages that have mixed-case names, or even deprecate those packages in favor of lower-case ones, we're blocking them from doing so because of our well-intended data cleanup bits and bobs.

Probably that should just rely on server-side validation?  I'm not 100% sure of the right course of action here, but it feels like we inadvertently left some folks stuck and unable to do the right thing.

**Comment by othiym23** [comment] 2015-02-26 01:07
This is making @dominictarr sad over on #7260. I'm investigating whether a change to npm or `normalize-package-data` will be sufficient to handle this without making any server-side changes.

**Comment by dominictarr** [comment] 2015-02-26 01:51
not me, so much as the ???? of people who use JSONStream and need to used a better version of it. ;)

**Comment by okv** [comment] 2015-03-18 07:11
Any update on this? (still waiting for JSONStream update ;)

**Comment by othiym23** [comment] 2015-03-19 06:32
No, alas, we haven't had time to come up with a plan for this. It's probably sufficient to relax the restrictions in npm / `normalize-package-data` to allow mixed case in and then start enforcing the restrictions on the server side (and maybe warning / erroring in `npm init`, to help prevent this from being an issue in the future, but it hasn't risen to the top of the stack for the core team yet.

**Comment by dominictarr** [comment] 2015-03-19 09:01
this did work previously, may I ask what broke it?

**Comment by shakty** [comment] 2015-03-27 13:24
I add myself to the queue.. cannot publish new versions of JSUS ... I cannot even go lowercase, because in the meantime some dude has published a package named jsus ! So I am really stuck! 

JSUS is a dependency of many other packages of mine, so this is a very bad situation for me.

I tried to use an older version of npm 1.5.x, but I get other errors and I cannot even login.

Please re-enable publishing names with upper case characters. Thanks!

**Comment by othiym23** [comment] 2015-03-30 23:51
It's on the list of things to do, but hasn't made it to the top of the list yet. If somebody wanted to submit a patch to `normalize-package-data` that relaxes this restriction, it would probably get merged and published pretty quickly.

**Comment by dominictarr** [comment] 2015-03-31 20:48
@othiym23 can you give us a hit as to what fix is necessary?

**Comment by othiym23** [comment] 2015-03-31 20:51
@dominictarr `normalize-package-data` currently errors on package names with capital letters, blocking publishes. It should be a warning again. As far as I know, the registry will allow the publishes, even though the client won't (right now).

**Comment by rodneyrehm** [comment] 2015-04-05 12:33
Having the same problem with [URIjs](https://www.npmjs.com/package/URIjs) and npm 1.7.5 just now. changing the name to [uri.js](https://www.npmjs.com/package/uri.js) is not an option, because an incomplete and inactive project took the name. I could go with `urijs`, but I can't say I want to. 

What's the plan here?

**Comment by zertosh** [comment] 2015-05-07 17:51
browserify versions 5.0.0 - 10.1.1 (10.1.2 is the latest) can't be installed because of JSONStream vs jsonstream on OS X and windows. It's related to the issue described in this issue. From https://github.com/substack/node-browserify/pull/1247#issuecomment-99956642:

> JSONStream has been stuck on 0.10.1 because https://github.com/npm/npm/issues/7195 won't allow @dominictarr to update it to 1.0.3. As a workaround, he published it as jsonstream (lowercase) (see https://github.com/dominictarr/JSONStream/issues/59) - which is an entirely new package.

> browserify, browser-pack, deps-sort, insert-module-globals, and module-deps, each depend on "JSONStream". I updated each of them so they used jsonstream@^1.0.3 instead of JSONStream@~0.10.0. The updates were all semver patch.

> If someone tries to install a browserify that uses "JSONStream@~0.10.0", but has a dep that uses jsonstream@^1.0.3 (because the sub deps fall within the allowed semver range), npm will crap out. It seems that once it sees "JSONStream@~0.10.0" it tries to install "jsonstream@^1.0.3" as "JSONStream@^1.0.3" - which doesn't exist. It must be something with case nature of the fs because this doesn't happen on linux.

**Comment by stevengill** [comment] 2015-05-07 18:36
cordova has a dependency on browserify 7.1.0 and now all of our published versions are failing to install. What changed?

**Comment by zertosh** [comment] 2015-05-07 18:39
@stevengill the explanation is in https://github.com/substack/node-browserify/pull/1247#issuecomment-99956642. Your best bet is to update to 10.1.2. Because of how versions float, this seems to only affect v5.0.0-v10.1.1.

**Comment by muratsu** [comment] 2015-05-07 18:43
Hmm, even if we release a new version of Cordova the last few major releases are going to remain broken.

**Comment by stevengill** [comment] 2015-05-07 18:52
All downstreams of cordova are breaking too (phonegap, ionic, cca, etc). Ugh

**Comment by jwhitehorn** [comment] 2015-05-07 19:36
Yes, this breaks many of my dependencies and I can no longer `npm install`.

**Comment by TheSharpieOne** [comment] 2015-05-07 19:53
Yeah, when browserify made this change, $#!t hit the fan.  Having something like JSONString == jsonstring seems like a larger issue.

**Comment by ashleahhill** [comment] 2015-05-07 19:54
+1

**Comment by stevengill** [comment] 2015-05-07 20:27
Looks like the issue got fixed by using an old version of npm to publish JSONStream. https://github.com/dominictarr/JSONStream/issues/68

**Comment by dominictarr** [comment] 2015-05-07 20:32
@stevengill hey i think it's fixed can you try installing cordova again (I can't reproduce because I'm on linux)

**Comment by stevengill** [comment] 2015-05-07 20:37
@dominictarr it is fixed. Thanks!

**Comment by muratsu** [comment] 2015-05-07 20:49
@dominictarr thanks!

**Comment by dblotsky** [comment] 2015-05-07 21:04
@dominictarr, great work. Many thanks!

**Comment by othiym23** [comment] 2015-05-22 05:27
This is closed by 1da9b0411d3416c7fca17d08cbbcfca7ae86e92d and e9267830ab261c751f12723e84d2458ae9238646, which will be included in `npm@2.11.0`. So sorry it took us this long to get this addressed!

**Closed by othiym23** 2015-05-22 05:27 UTC
Labels: feature-request, next-minor
