### ISSUE TITLE
write a brief npm manual for Windows users

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6219] opened 2014-09-18 02:25 UTC
npm is pretty unixy in philosophy and its UX, and Windows users could use a little help in getting their heads wrapped around it, both in terms of how it does its thing and how it integrates (or doesn't) with Windows. The Windows bits in the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) have been very enthusiastically received.

**Comment by migg24** [comment] 2016-03-22 19:10
I am using npm on Windows at work. I could write some documentation but I would need some more details of what exactly the documentation should cover. Do you have a unix counterpart of the desired documentation for Windows?

**Comment by iarna** [comment] 2016-08-26 20:55
Closing as a duplicate of https://github.com/npm/docs/issues/379.

**Closed by iarna** 2016-08-26 20:55 UTC
Labels: documentation, feature-request
