### ISSUE TITLE
Install a package from cache (without internet connection)

### ISSUE THREAD

**Issue by reza-farhadian** [npm/npm#7341] opened 2015-02-11 13:34 UTC
Is there any way to install a package from npm cache? (without internet connection)

I see some issues about to use --no-registry but it seems it doesn't work.

**Comment by reza-farhadian** [comment] 2015-02-11 13:50
Sorry, i forget to include node and npm version

Node version: 0.10.33
Npm version: 1.4.28

**Comment by smikes** [comment] 2015-02-11 14:54
First off, you should really update to a newer version of `npm`.  There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28.

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Secondly, with respect to your question: No, there is no way to install a package from the cache with no connection to the registry.  Even specifying an explicit version number causes the install to fail with `npm ERR! registry URL is required` (tested with npm@2.5.1)

However, if what you would like to do is create a package that can be installed on a network-disconnected host, I suggest you look into `bundledDependencies` which is what `npm` itself uses to create a single self-sufficient tarball that can be installed with a command like this:

```
npm install -g https://.../npm-2.5.1.tgz
```

Can you tell me a bit more about your use case, what you are trying to do?  That will help me answer your question more usefully.

**Comment by reza-farhadian** [comment] 2015-02-12 12:10
I just want to install packages hout any internet connection (offline) from npm cache folder, and it seems this future this future isn't available yet.

I try to create a utility to install package

**Comment by reza-farhadian** [comment] 2015-02-12 12:13
I try to create a utility to install a package without internet connection.

Read, unpack and install content of npm cache with a simple command.

Thx.

**Comment by Log-of-e** [comment] 2015-02-13 05:30
Way to go Reza!

-----Original Message-----

**Comment by othiym23** [comment] 2015-02-21 09:41
Closing as duplicate of #5509 / #2568. `--no-registry` sort of worked once upon a time, but the caching logic needs to be straightened out to support it properly with npm's current architecture.

**Closed by othiym23** 2015-02-21 09:41 UTC

**Comment by rzr** [comment] 2017-11-02 13:56
--no-registry sort of worked once upon a time, do you remember when ?
