### ISSUE TITLE
failed to fetch from registry: https://registry.npmjs.org/sass

### ISSUE THREAD

**Issue by matthiaskurte** [npm/npm#9172] opened 2015-08-05 06:38 UTC
Cannot install node module sass. This causes failing builds.
Any ideas?

```
npm ERR! Error: failed to fetch from registry: https://registry.npmjs.org/sass
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:159:18)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:57:9)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:137:16)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:166:9)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:320:12)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/matthiaskurte/htdocs/prototype
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

Thanks in advance
Matthias

**Comment by arenoux** [comment] 2015-08-05 09:56
This may help you: https://github.com/npm/npm/issues/9177#issuecomment-127922092

**Comment by bstst** [comment] 2015-08-05 14:40
https://github.com/npm/npm/issues/9168

**Comment by Yvem** [comment] 2015-08-05 15:32
pb apparently solved https://github.com/npm/npm/issues/9168#issuecomment-128034802

**Comment by othiym23** [comment] 2015-08-10 06:29
Closing as duplicate of #9168, which has since been resolved.

**Closed by othiym23** 2015-08-10 06:29 UTC
Labels: bug, registry
