### ISSUE TITLE
Feature request: Equivalent to Bundler's `bundle exec`

### ISSUE THREAD

**Issue by mcandre** [npm/npm#7429] opened 2015-02-22 20:39 UTC
As a command line user, I would like an NPM command that behaves like Bundler's `bundle exec <command>`, that allows me to execute dynamic commands in an NPM-aware shell.

As a workaround, I can edit commands in the `scripts` section of my `package.json`, but this is a terribly slow way to experiment with command line flags for NPM package binaries.

**Comment by bengl** [comment] 2015-02-22 21:28
If you just want to pass arguments to things you've put in your `scripts`, as of npm@2.0.0, you can just pass in `--` and anything after that will be passed to the command in `scripts`. ([Docs](https://docs.npmjs.com/cli/run-script))

If you really need something like `bundle exec`, one thing you can do is something like this:

```javascript
  "scripts": {
    "exec": "exec"
  }
```

And now you can do `npm run exec -- <command with args>`.

**Comment by KenanY** [comment] 2015-02-22 21:39
@mcandre I think there are a ton of issues about this already. There's a [label](https://github.com/npm/npm/labels/npm-exec), https://github.com/npm/npm/issues/1543, https://github.com/npm/npm/pull/2460, https://github.com/npm/npm/issues/3313, https://github.com/npm/npm/pull/4058, https://github.com/npm/npm/pull/4554, just to name a few.

**Comment by smikes** [comment] 2015-02-23 02:51
@bengl that's an awesome hack, I wish I had thought of it.

@mcandre Yes, this is a widely-requested feature.  Currently the main development effort is on multi-stage-install, but that's expected to be finished soon.

**Comment by mcandre** [comment] 2015-02-23 04:02
I tried this, but `npm run exec -- csslint stylesheet.css` strangely has no output, even though `node_modules/csslint/bin/csslint stylesheet.css` lists a few dozen messages.

**Comment by smikes** [comment] 2015-02-23 04:10
I don't think you need the npm package `exec`.  `exec` should be a shell builtin.

Try

```
npm run exec -- ls      # should do standard `ls`
npm run exec -- echo $PATH  # should show ./node_modules/.bin in $PATH
npm run exec -- env    # should have several $npm_config_xxx variables
```

If those don't work, then there's a problem with `exec`

**Comment by aredridel** [comment] 2015-02-23 15:34
You can even do `"scripts": { "exec": "" }` and it'll work, no need to trigger the shell builtin exec

**Comment by mcandre** [comment] 2015-02-23 15:41
My NPM assumes exec is an NPM package binary.

```
$ npm run exec -- jshint .
npm ERR! Error: ENOENT, open '/Users/apennebaker/Desktop/src/regenboog/node_modules/exec/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/apennebaker/.nvm/v0.10.36/bin/node" "/Users/apennebaker/.nvm/v0.10.36/bin/npm" "run" "exec" "--" "jshint" "."
npm ERR! cwd /Users/apennebaker/Desktop/src/regenboog
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/apennebaker/Desktop/src/regenboog/node_modules/exec/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/apennebaker/Desktop/src/regenboog/npm-debug.log
npm ERR! not ok code 0
```

System:

```
$ specs node os
Specs:

specs 0.12
https://github.com/mcandre/specs#readme

npm --version
1.4.28

node --version
v0.10.36

system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.10.2 (14C109)
```

**Comment by bengl** [comment] 2015-02-23 16:24
@mcandre Your npm is pretty old. Try upgrading it: `npm i -g npm`

**Comment by smikes** [comment] 2015-02-23 20:24
> "scripts": { "exec": "" }

@aredridel Unfortunately we broke that with `npm@2.2.0`, https://github.com/npm/npm/commit/0aefae9bc2598a4b7a3ee7bb2306b42e3e12bb28  

Now if you define `"exec": ""` you'll get:

```
$ npm run exec -- env
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/smikes/.nvm/versions/io.js/v1.2.0/bin/npm" "run" "exec" "--" "env"
npm ERR! node v1.2.0
npm ERR! npm  v2.6.1

npm ERR! missing script: exec
npm ERR! 
```

**Comment by mcandre** [comment] 2015-02-23 22:37
Rather than a hack, could npm please include an official subcommand, such as `npm exec` (though I really don't care what it's called), that behaves like `bundle exec`?

**Comment by smikes** [comment] 2015-02-24 12:51
> I tried this, but npm run exec -- csslint stylesheet.css strangely has no output, even though node_modules/csslint/bin/csslint stylesheet.css lists a few dozen messages.

As @bengl says, you'll need to update `npm` to take advantage of the `pass args to scripts` feature.  That feature was the breaking change that bumped `npm` to 2.0.0 , so 1.4.28 doesn't have it.  Also, there were many race conditions fixed in the early versions of 2.0 - 2.2, so you really should upgrade to `npm@latest`.

> Rather than a hack, could npm please include an official subcommand, such as npm exec (though I really don't care what it's called), that behaves like bundle exec?

As @kenanY showed, this is a widely-requested feature that is planned for a future version of `npm`.  Currently most development effort is targeted at improving the installation experience (see: <http://blog.npmjs.org/post/98233700815/multi-stage-installs-and-a-better-npm>), with some volunteer effort going towards other long-standing bugs like search (<https://github.com/npm/npm/issues/6016>), so we don't know when anyone will be free to work on `npm exec`.

**Comment by mcandre** [comment] 2015-02-24 15:43
@smikes Thanks for the info!

As an nvm user, how do I update npm?

**Comment by smikes** [comment] 2015-02-24 15:50
I let nvm create a separate prefix for each installation (I think this is better BC of native module ABI issues but some people prefer a single global prefix)

npm i -g npm@latest

Should work, once per installed node/iojs.

**Comment by othiym23** [comment] 2015-02-26 06:57
Closing as a duplicate of #6053. For a variety of reasons, adding a new `npm exec` command that does something directly equivalent to `bundle exec` is more or less untenable (due to how tightly coupled npm's command-line argument parsing is to everything else it does). However, if you upgrade to `npm@latest` and use one of @bengl or @aredridel's clever hacks, that should probably get you much closer to where you want to be than you are now. You may also want to look at [`npm explore`](https://docs.npmjs.com/cli/explore) too.

**Closed by othiym23** 2015-02-26 06:57 UTC
Labels: feature-request, npm-exec
