### ISSUE TITLE
Lifecycle: script that runs just before (and only before) `npm publish`

### ISSUE THREAD

**Issue by olalonde** [npm/npm#8402] opened 2015-05-30 04:18 UTC
It would be nice to have a script that runs only when running `npm publish`. For example, this would allow developers to compile files (coffeescript, babel, etc), automatically tag a git repository with the package's version, generate documentation, run tests, etc. 

There is currently a trigger called `prepublish` but it also runs on `npm install` which is not ideal for the use cases mentioned (see https://github.com/npm/npm/issues/3059).

**Comment by AlastairTaft** [comment] 2015-05-30 05:21
+1

**Comment by mtscout6** [comment] 2015-05-30 13:36
I would like to re-emphasize @dfellis's point (https://github.com/npm/npm/issues/3059#issuecomment-12257387) that the current behavior is not semantically the same as all the other lifecycle hooks.

I also understand the caveats of whether or not this should be classified as a "breaking change" even though it was initially released as a Minor change. If that is still a concern then can this please make it into the upcoming 3.0.0 release?

**Comment by othiym23** [comment] 2015-05-30 13:39
> If that is still a concern then can this please make it into the upcoming 3.0.0 release?

It most definitely is still a concern, and for that reason `npm@3` (which is really very close to completion – see #7774 for work remaining) is too soon to release this change. A message could be added to warn for top-level packages using prepublish saying that the behavior will change (although I need to decide what, exactly, it's going to change to – the current behavior is _not_ the same as running the same hooks for `install` and `prepublish`, as @iarna helped me understand), but this is  a change that will need to be trailed for a longer period than the few weeks to ~month remaining before `npm@3`'s release.

**Comment by mtscout6** [comment] 2015-05-30 13:48
If npm3 hasn't been released then I don't see why it's too late for this. Are you planning a v4 release soon after v3?

**Comment by othiym23** [comment] 2015-05-30 14:27
If npm is to deprecate or change behavior that packages rely upon, the change must be trailed in documentation and / or warning messages for at least a full major release cycle or 6 months prior. This may seem like a straightforward fix to the people on this thread, but I already know it's going to cause pain.

**Comment by david0178418** [comment] 2015-05-30 20:13
@othiym23 Great to hear this is still on the radar.  I'm looking forward to seeing the timeline for this change set.

**Comment by dperetti** [comment] 2015-06-02 21:29
+1...

**Comment by flockonus** [comment] 2015-06-09 18:52
afaik, npm is the best package manager for any platform, in a big part because it's so intuitive to use and powerful.
This particular behaviour is completely counter intuitive, and despite being mildly infuriating every time i `npm i` and slowing down my test pipeline by a lot, i don't see myself moving away from npm just because of it.
It's understandable to focus preventing major pain points on users that depend on this flow, but please deprecate this asap and keep npm rocking!

**Comment by dbartholomae** [comment] 2015-06-16 23:11
From my point of view there are 2 things currently mixed up in the discussion:
1. The behavior of "prepublish" is counter intuitive to some, as it differs to other pre-hooks
2. There is no way inside npm to run a script before publishing without running it on "npm install"

I understand that backwards compatability is a strong argument to carefully consider changing 1 in npm3 already. But many people are even more concerned with 2.
Why not simply introduce another hook like "prepurepublish" that runs precisely before publish? If backward compatability is the main concern, you could even go so far as to check whether there is a "purepublish" script and if there is, prepurepublish runs before purepublish, and the behavior 2 only is run when there is nu purepublish script defined.

**Comment by monolithed** [comment] 2015-07-06 23:35
+1, the current behaviour is unexpected

**Comment by iarna** [comment] 2015-07-07 03:25
@dbartholomae Your comments are on point here.

So what prepublish currently actually does is:

1. Is run when you run `npm install` on a target

2. Is run (almost) any time a tarball is made of your module, prior to the tarball being made.

This includes when you run `npm pack`, when you run `npm publish`, when you install a module from a local folder (`npm install /path/to/thingy/`) and when you add folder to the cache (`npm cache add /path/to/thingy/`).

In the future this will also probably ALSO include when you install from a git repository.

---

We still very much need a lifecycle that runs at these times.  if it's called `prepublish` or something else, it can't be decoupled.

What folks seem to ALSO want is something that runs prior to the `publish` command, or possibly in all of the scenarios under 2 above. Though I don't think we have clarity on that final point.

If you _really_ want to only run when you're preparing to push to the repository I would strongly recommend **using the new `preversion/postversion` hooks**. I think they capture this intent a lot better.

Alternatively, you can use my [in-publish](https://www.npmjs.com/package/in-publish) module, which will only run your script when you actually use the `npm publish` command. It's limited, but not actually fragile (despite my original fears).

**Comment by mik01aj** [comment] 2015-07-07 08:09
@iarna , I totally agree with you. And thanks for [in-publish](https://www.npmjs.com/package/in-publish), this addresses the (imho) most common use case.

**Comment by SystemParadox** [comment] 2015-07-07 08:52
As discussed in #3059, the current promiscuous behaviour of `prepublish` should be called `build` or `install`.

**Comment by mathieumg** [comment] 2015-07-07 17:36
> Is run when you run npm install on a target

Sorry, I don't mean to hijack, but is there a hook that does #1 *only*? (See https://github.com/npm/npm/issues/8263)

If there is demand for standalone versions of 1 and 2, perhaps they should indeed be separated or at least have a separate hook for their standalone version.

**Comment by iarna** [comment] 2015-07-07 21:33
Relatedly: #6887

**Comment by malandrew** [comment] 2015-07-10 00:53
@othiym23 Getting this into 3.0 is perfectly reasonable. This has been an issue for 2 years now. You know an issue is bad when you drop into the thread and notice at least 3 co-workers bitten by the bug by three isolated and unrelated cases. 

If this breaks the behavior of certain modules, it's only going to break for people who upgrade to 3.0. For those that are adventurous and upgrade early, they'll go and find the projects that depend on the completely unintuitive and frustrating to workaround behavior and submit pull requests to fix those modules that rely on the old behavior.

Putting this off until 4.0 is nuts when it's been biting people for so long already. I'd prefer to see this get into npm 3 by delaying it by 6 months from today than to wait who knows how long until version 4.0, unless you plan on releasing 4.0 approximately 6 months from today.

**Comment by AlastairTaft** [comment] 2015-07-10 03:20
malandrew's comments are right on point +1

**Comment by mik01aj** [comment] 2015-07-10 08:05
+1 @malandrew

**Comment by leebyron** [comment] 2015-07-28 02:53
I was bitten badly by this today. I was attempting to set up a custom deploy script using Travis CI to ensure only test-passing and correctly formatted bundles can be published to npm, and wanted a `prepublish` script which checked to ensure `npm publish` could only be run from the CI environment to keep any well-intending coworkers from accidentally subverting it by running the command directly.

After I set this up, I started getting reports that people were unable to check out the repo and install dependencies. I was totally surprised that this pre- lifecycle script was being run by an unrelated script (`install`) and also surprised to find that there existed no lifecycle script that would run before publishing in the way other lifecycle scripts behave.

In my opinion this behavior was ill-considered. A `postinstall` hook already exists for this purpose and those who wish to transpile coffeescript after installing should be using that hook.

Thank you for `in-publish` as a temporary work around, but I look forward to seeing this revert to the expected behavior to avoid the hackery.

**Comment by ekristen** [comment] 2015-08-13 16:11
`prepublish` should **NOT** be run with npm install, please fix this!

**Comment by rondonjon** [comment] 2015-08-29 11:02
> Please deprecate pre-publish with npm install in favor of post-install scripts for the next major version.

+1

**Comment by david0178418** [comment] 2015-09-02 04:07
I really think that "feature-request" is the incorrect tag here.  Naming is quite important.  If "install" actually uninstalled, I doubt anyone would call it anything less than a bug.  That's not far off of this.  The name implies something entirely different than what one would expect.  It might be correct according to the design, but that just means it's a design bug.

**Comment by othiym23** [comment] 2015-10-22 00:54
Closing in favor of #10074.

**Closed by othiym23** 2015-10-22 00:54 UTC
Labels: feature-request
