### ISSUE TITLE
`git+` is dropped from `git+ssh`

### ISSUE THREAD

**Issue by donaldpipowitch** [npm/npm#9732] opened 2015-09-23 13:52 UTC
It looks like calling `$ npm i --save-dev git+ssh://git@git.foo.lan:bar/baz.git#some-branch` will add `"baz": "ssh://git@git.foo.lan:bar/baz.git#some-branch"` to `package.json` (without `git+`). I haven't seen this with npm@2. I'm using npm@3.3.3 now.

We need `git+` or our CI server complaints with the following error:

````
npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at exports.findRequirement (.../lib/node_modules/npm/lib/install/deps.js:475:3)
````

**Comment by fischmax** [comment] 2015-09-29 08:05
I can confirm this with node 4.1.1, npm 3.3.3 and Ubuntu 14.04.

**Comment by KenanY** [comment] 2015-10-07 15:04
Might be a dupe of https://github.com/npm/npm/issues/9679.

**Comment by ehsalazar** [comment] 2015-11-04 23:24
Closing as a duplicate of #9679. If you believe it's something different, please let us know. We'll be happy to reopen this issue.

**Closed by ehsalazar** 2015-11-04 23:24 UTC
