### ISSUE TITLE
npm run fails, using the new windows bash (ubuntu - Windows Insider Preview)

### ISSUE THREAD

**Issue by ebuchmann** [npm/npm#12447] opened 2016-04-23 14:54 UTC
Anytime I attempt to do any `npm run` commands I just get errors. I'm using the latest Windows Insider Preview build 14328 (the previous build had the same issue). Any existing projects I have will fail, and to test this further I created a new folder and did `npm init` while using the `Bash on Ubuntu` (in Windows). That worked fine, but when I did `npm run test` it failed, and didn't do the `echo` command that is initially set up. Swapping over to a terminal that is ran under Windows it does do the `echo`.

Here is the log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest npmtest@1.0.0
6 info test npmtest@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info npmtest@1.0.0 Failed to exec test script
9 verbose stack Error: npmtest@1.0.0 test: `echo "Error: no test specified"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid npmtest@1.0.0
11 verbose cwd /mnt/d/Web/npmtest
12 error Linux 3.4.0+
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error npmtest@1.0.0 test: `echo "Error: no test specified"`
17 error Exit status 1
18 error Failed at the npmtest@1.0.0 test script 'echo "Error: no test specified"'.
18 error This is most likely a problem with the npmtest package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     echo "Error: no test specified"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs npmtest
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls npmtest
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

And the current contents of my `package.json` file:

```
{
  "name": "npmtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\""
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by Lorac** [comment] 2016-04-23 16:22
See : #12445

**Comment by othiym23** [comment] 2016-04-25 15:48
Closing as duplicate of #12445.

**Closed by othiym23** 2016-04-25 15:48 UTC
