### ISSUE TITLE
shasum check failed for registry.npmjs.org\ms\-\ms-0.7.1.tgz

### ISSUE THREAD

**Issue by prabhat2486** [npm/npm#11244] opened 2016-01-22 03:49 UTC
While installing the node-gyp getting below error:

npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "node-gyp"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\d775432\AppData\Local\Temp\npm-4420-08
01a9db\registry.npmjs.org\ms-\ms-0.7.1.tgz
npm ERR! Expected: 9cd13c03adbff25b65effde7ce864ee952017098
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     http://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\npm-debug.log

Does anyone help here?

**Comment by zkat** [comment] 2016-12-09 00:48
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:48 UTC
