### ISSUE TITLE
npm issues when installing ionic

### ISSUE THREAD

**Issue by DianaGu** [npm/npm#9379] opened 2015-08-23 13:49 UTC
```
DianatekiMacBook-Air:~ workshop$ sudo npm install -g cordova ionic
Password:
npm ERR! tar.unpack untar error /tmp/npm-27294-87fe9029/registry.npmjs.org/npm/-/npm-2.1.3.tgz
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/workshop/npm-debug.log


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/workshop/npm-debug.log
```

**Comment by roymj88** [comment] 2015-08-23 22:46
:+1: I too am getting this damn error an its crazy!!

**Comment by kashyapgajiwala** [comment] 2015-08-24 10:43
I faced same error !!!
please any one fix this.

**Comment by learningjs** [comment] 2015-10-14 20:11
+1 still today

**Comment by lingxuesonga** [comment] 2016-07-05 02:51
same problem ,how do you do

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v4.4.7
npm ERR! npm v2.15.8

npm ERR! shasum check failed for /tmp/npm-1304-298e0fe1/registry.npmjs.org/ionic/-/ionic-1.7.16.tgz
npm ERR! Expected: aeff62ee70b10b1563d85b9d4ea7005640bbc584
npm ERR! Actual: c2e75ad9285eb373ce6e85f5704fd05b719eccb9
npm ERR! From: https://registry.npmjs.org/ionic/-/ionic-1.7.16.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

**Comment by zkat** [comment] 2016-12-09 00:54
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:54 UTC
Labels: support
