### ISSUE TITLE
package.json encoded in UTF8 + BOM causes install --save to silently fail   

### ISSUE THREAD

**Issue by gravidThoughts** [npm/npm#8615] opened 2015-06-19 15:53 UTC
`npm 2.10.0`

#### Repro

Create package.json in Visual Studio project. By default it will encode UTF8 + BOM.

Install any package locally using `--save` flag. The package.json will not be updated, and no exception will be displayed in the console.

**Comment by iarna** [comment] 2015-07-01 08:42
Duplicate of #3358

**Closed by iarna** 2015-07-01 08:42 UTC
Labels: bug, windows
