### ISSUE TITLE
npm install git+ssh://... --save

### ISSUE THREAD

**Issue by lc60005457** [npm/npm#10594] opened 2015-11-29 03:21 UTC
When I use `npm install git+ssh://... --save`, the `package.json`

```
"dependencies": {
    "...": "ssh://...",
}
```

then, `npm install`, will error:

```
npm ERR! Unsupported URL Type: ssh://...
```

and, I need edit the `package.json`

```
"dependencies": {
    "...": "git+ssh://...",
}
```

**Comment by KenanY** [comment] 2015-11-29 04:16
@lc60005457 Is this a duplicate of https://github.com/npm/npm/issues/9679?

**Comment by lc60005457** [comment] 2015-11-29 05:51
@KenanY Yeah, it is. And I update npm to `v3.5.0` with mac. It also.

**Comment by KenanY** [comment] 2015-11-29 14:48
@lc60005457 Could you close this issue in favor of https://github.com/npm/npm/issues/9679 then? This way we can keep the issue tracker just a little cleaner :)

**Closed** 2015-11-29 14:53 UTC
