### ISSUE TITLE
npm ERR! Windows_NT 6.1.7600

### ISSUE THREAD

**Issue by justVilla** [npm/npm#9830] opened 2015-10-02 20:08 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-d' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose readDependencies loading dependencies from D:\Projects\myApp\package.json
5 warn package.json myapp@1.0.0 No repository field.
6 warn package.json myapp@1.0.0 No README data
7 warn package.json myapp@1.0.0 No license field.
8 verbose install where, deps [ 'D:\\Projects\\myApp',
8 verbose install   [ 'gulp',
8 verbose install     'gulp-sass',
8 verbose install     'gulp-concat',
8 verbose install     'gulp-minify-css',
8 verbose install     'gulp-rename',
8 verbose install     'bower',
8 verbose install     'gulp-util',
8 verbose install     'shelljs',
8 verbose install     'grunt',
8 verbose install     'grunt-contrib-jshint',
8 verbose install     'grunt-contrib-nodeunit',
8 verbose install     'grunt-contrib-uglify' ] ]
9 verbose install where, peers [ 'D:\\Projects\\myApp', [] ]
10 verbose installManyTop reading for lifecycle D:\Projects\myApp\package.json
11 info preinstall myapp@1.0.0
12 verbose readDependencies loading dependencies from D:\Projects\myApp\package.json
13 silly cache add args [ 'gulp-sass@^1.3.3', null ]
14 verbose cache add spec gulp-sass@^1.3.3
15 silly cache add parsed spec Result {
15 silly cache add   raw: 'gulp-sass@^1.3.3',
15 silly cache add   scope: null,
15 silly cache add   name: 'gulp-sass',
15 silly cache add   rawSpec: '^1.3.3',
15 silly cache add   spec: '>=1.3.3 <2.0.0',
15 silly cache add   type: 'range' }
16 silly addNamed gulp-sass@>=1.3.3 <2.0.0
17 verbose addNamed ">=1.3.3 <2.0.0" is a valid semver range for gulp-sass
18 silly addNameRange { name: 'gulp-sass', range: '>=1.3.3 <2.0.0', hasData: false }
19 silly mapToRegistry name gulp-sass
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/gulp-sass
23 verbose addNameRange registry:https://registry.npmjs.org/gulp-sass not in flight; fetching
24 silly cache add args [ 'gulp-concat@^2.2.0', null ]
25 verbose cache add spec gulp-concat@^2.2.0
26 silly cache add parsed spec Result {
26 silly cache add   raw: 'gulp-concat@^2.2.0',
26 silly cache add   scope: null,
26 silly cache add   name: 'gulp-concat',
26 silly cache add   rawSpec: '^2.2.0',
26 silly cache add   spec: '>=2.2.0 <3.0.0',
26 silly cache add   type: 'range' }
27 silly addNamed gulp-concat@>=2.2.0 <3.0.0
28 verbose addNamed ">=2.2.0 <3.0.0" is a valid semver range for gulp-concat
29 silly addNameRange { name: 'gulp-concat', range: '>=2.2.0 <3.0.0', hasData: false }
30 silly mapToRegistry name gulp-concat
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/gulp-concat
34 verbose addNameRange registry:https://registry.npmjs.org/gulp-concat not in flight; fetching
35 silly cache add args [ 'gulp-minify-css@^0.3.0', null ]
36 verbose cache add spec gulp-minify-css@^0.3.0
37 silly cache add parsed spec Result {
37 silly cache add   raw: 'gulp-minify-css@^0.3.0',
37 silly cache add   scope: null,
37 silly cache add   name: 'gulp-minify-css',
37 silly cache add   rawSpec: '^0.3.0',
37 silly cache add   spec: '>=0.3.0 <0.4.0',
37 silly cache add   type: 'range' }
38 silly addNamed gulp-minify-css@>=0.3.0 <0.4.0
39 verbose addNamed ">=0.3.0 <0.4.0" is a valid semver range for gulp-minify-css
40 silly addNameRange { name: 'gulp-minify-css',
40 silly addNameRange   range: '>=0.3.0 <0.4.0',
40 silly addNameRange   hasData: false }
41 silly mapToRegistry name gulp-minify-css
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/gulp-minify-css
45 verbose addNameRange registry:https://registry.npmjs.org/gulp-minify-css not in flight; fetching
46 silly cache add args [ 'gulp-rename@^1.2.0', null ]
47 verbose cache add spec gulp-rename@^1.2.0
48 silly cache add parsed spec Result {
48 silly cache add   raw: 'gulp-rename@^1.2.0',
48 silly cache add   scope: null,
48 silly cache add   name: 'gulp-rename',
48 silly cache add   rawSpec: '^1.2.0',
48 silly cache add   spec: '>=1.2.0 <2.0.0',
48 silly cache add   type: 'range' }
49 silly addNamed gulp-rename@>=1.2.0 <2.0.0
50 verbose addNamed ">=1.2.0 <2.0.0" is a valid semver range for gulp-rename
51 silly addNameRange { name: 'gulp-rename', range: '>=1.2.0 <2.0.0', hasData: false }
52 silly mapToRegistry name gulp-rename
53 silly mapToRegistry using default registry
54 silly mapToRegistry registry https://registry.npmjs.org/
55 silly mapToRegistry uri https://registry.npmjs.org/gulp-rename
56 verbose addNameRange registry:https://registry.npmjs.org/gulp-rename not in flight; fetching
57 silly cache add args [ 'bower@^1.3.3', null ]
58 verbose cache add spec bower@^1.3.3
59 silly cache add parsed spec Result {
59 silly cache add   raw: 'bower@^1.3.3',
59 silly cache add   scope: null,
59 silly cache add   name: 'bower',
59 silly cache add   rawSpec: '^1.3.3',
59 silly cache add   spec: '>=1.3.3 <2.0.0',
59 silly cache add   type: 'range' }
60 silly addNamed bower@>=1.3.3 <2.0.0
61 verbose addNamed ">=1.3.3 <2.0.0" is a valid semver range for bower
62 silly addNameRange { name: 'bower', range: '>=1.3.3 <2.0.0', hasData: false }
63 silly mapToRegistry name bower
64 silly mapToRegistry using default registry
65 silly mapToRegistry registry https://registry.npmjs.org/
66 silly mapToRegistry uri https://registry.npmjs.org/bower
67 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
68 silly cache add args [ 'gulp-util@^2.2.14', null ]
69 verbose cache add spec gulp-util@^2.2.14
70 silly cache add parsed spec Result {
70 silly cache add   raw: 'gulp-util@^2.2.14',
70 silly cache add   scope: null,
70 silly cache add   name: 'gulp-util',
70 silly cache add   rawSpec: '^2.2.14',
70 silly cache add   spec: '>=2.2.14 <3.0.0',
70 silly cache add   type: 'range' }
71 silly addNamed gulp-util@>=2.2.14 <3.0.0
72 verbose addNamed ">=2.2.14 <3.0.0" is a valid semver range for gulp-util
73 silly addNameRange { name: 'gulp-util', range: '>=2.2.14 <3.0.0', hasData: false }
74 silly mapToRegistry name gulp-util
75 silly mapToRegistry using default registry
76 silly mapToRegistry registry https://registry.npmjs.org/
77 silly mapToRegistry uri https://registry.npmjs.org/gulp-util
78 verbose addNameRange registry:https://registry.npmjs.org/gulp-util not in flight; fetching
79 silly cache add args [ 'shelljs@^0.3.0', null ]
80 verbose cache add spec shelljs@^0.3.0
81 silly cache add parsed spec Result {
81 silly cache add   raw: 'shelljs@^0.3.0',
81 silly cache add   scope: null,
81 silly cache add   name: 'shelljs',
81 silly cache add   rawSpec: '^0.3.0',
81 silly cache add   spec: '>=0.3.0 <0.4.0',
81 silly cache add   type: 'range' }
82 silly addNamed shelljs@>=0.3.0 <0.4.0
83 verbose addNamed ">=0.3.0 <0.4.0" is a valid semver range for shelljs
84 silly addNameRange { name: 'shelljs', range: '>=0.3.0 <0.4.0', hasData: false }
85 silly mapToRegistry name shelljs
86 silly mapToRegistry using default registry
87 silly mapToRegistry registry https://registry.npmjs.org/
88 silly mapToRegistry uri https://registry.npmjs.org/shelljs
89 verbose addNameRange registry:https://registry.npmjs.org/shelljs not in flight; fetching
90 silly cache add args [ 'grunt@~0.4.5', null ]
91 verbose cache add spec grunt@~0.4.5
92 silly cache add parsed spec Result {
92 silly cache add   raw: 'grunt@~0.4.5',
92 silly cache add   scope: null,
92 silly cache add   name: 'grunt',
92 silly cache add   rawSpec: '~0.4.5',
92 silly cache add   spec: '>=0.4.5 <0.5.0',
92 silly cache add   type: 'range' }
93 silly addNamed grunt@>=0.4.5 <0.5.0
94 verbose addNamed ">=0.4.5 <0.5.0" is a valid semver range for grunt
95 silly addNameRange { name: 'grunt', range: '>=0.4.5 <0.5.0', hasData: false }
96 silly mapToRegistry name grunt
97 silly mapToRegistry using default registry
98 silly mapToRegistry registry https://registry.npmjs.org/
99 silly mapToRegistry uri https://registry.npmjs.org/grunt
100 verbose addNameRange registry:https://registry.npmjs.org/grunt not in flight; fetching
101 silly cache add args [ 'grunt-contrib-jshint@~0.10.0', null ]
102 verbose cache add spec grunt-contrib-jshint@~0.10.0
103 silly cache add parsed spec Result {
103 silly cache add   raw: 'grunt-contrib-jshint@~0.10.0',
103 silly cache add   scope: null,
103 silly cache add   name: 'grunt-contrib-jshint',
103 silly cache add   rawSpec: '~0.10.0',
103 silly cache add   spec: '>=0.10.0 <0.11.0',
103 silly cache add   type: 'range' }
104 silly addNamed grunt-contrib-jshint@>=0.10.0 <0.11.0
105 verbose addNamed ">=0.10.0 <0.11.0" is a valid semver range for grunt-contrib-jshint
106 silly addNameRange { name: 'grunt-contrib-jshint',
106 silly addNameRange   range: '>=0.10.0 <0.11.0',
106 silly addNameRange   hasData: false }
107 silly mapToRegistry name grunt-contrib-jshint
108 silly mapToRegistry using default registry
109 silly mapToRegistry registry https://registry.npmjs.org/
110 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-jshint
111 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-jshint not in flight; fetching
112 silly cache add args [ 'grunt-contrib-nodeunit@~0.4.1', null ]
113 verbose cache add spec grunt-contrib-nodeunit@~0.4.1
114 silly cache add parsed spec Result {
114 silly cache add   raw: 'grunt-contrib-nodeunit@~0.4.1',
114 silly cache add   scope: null,
114 silly cache add   name: 'grunt-contrib-nodeunit',
114 silly cache add   rawSpec: '~0.4.1',
114 silly cache add   spec: '>=0.4.1 <0.5.0',
114 silly cache add   type: 'range' }
115 silly addNamed grunt-contrib-nodeunit@>=0.4.1 <0.5.0
116 verbose addNamed ">=0.4.1 <0.5.0" is a valid semver range for grunt-contrib-nodeunit
117 silly addNameRange { name: 'grunt-contrib-nodeunit',
117 silly addNameRange   range: '>=0.4.1 <0.5.0',
117 silly addNameRange   hasData: false }
118 silly mapToRegistry name grunt-contrib-nodeunit
119 silly mapToRegistry using default registry
120 silly mapToRegistry registry https://registry.npmjs.org/
121 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-nodeunit
122 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-nodeunit not in flight; fetching
123 silly cache add args [ 'grunt-contrib-uglify@~0.5.0', null ]
124 verbose cache add spec grunt-contrib-uglify@~0.5.0
125 silly cache add parsed spec Result {
125 silly cache add   raw: 'grunt-contrib-uglify@~0.5.0',
125 silly cache add   scope: null,
125 silly cache add   name: 'grunt-contrib-uglify',
125 silly cache add   rawSpec: '~0.5.0',
125 silly cache add   spec: '>=0.5.0 <0.6.0',
125 silly cache add   type: 'range' }
126 silly addNamed grunt-contrib-uglify@>=0.5.0 <0.6.0
127 verbose addNamed ">=0.5.0 <0.6.0" is a valid semver range for grunt-contrib-uglify
128 silly addNameRange { name: 'grunt-contrib-uglify',
128 silly addNameRange   range: '>=0.5.0 <0.6.0',
128 silly addNameRange   hasData: false }
129 silly mapToRegistry name grunt-contrib-uglify
130 silly mapToRegistry using default registry
131 silly mapToRegistry registry https://registry.npmjs.org/
132 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-uglify
133 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-uglify not in flight; fetching
134 silly cache add args [ 'gulp@^3.5.6', null ]
135 verbose cache add spec gulp@^3.5.6
136 silly cache add parsed spec Result {
136 silly cache add   raw: 'gulp@^3.5.6',
136 silly cache add   scope: null,
136 silly cache add   name: 'gulp',
136 silly cache add   rawSpec: '^3.5.6',
136 silly cache add   spec: '>=3.5.6 <4.0.0',
136 silly cache add   type: 'range' }
137 silly addNamed gulp@>=3.5.6 <4.0.0
138 verbose addNamed ">=3.5.6 <4.0.0" is a valid semver range for gulp
139 silly addNameRange { name: 'gulp', range: '>=3.5.6 <4.0.0', hasData: false }
140 silly mapToRegistry name gulp
141 silly mapToRegistry using default registry
142 silly mapToRegistry registry https://registry.npmjs.org/
143 silly mapToRegistry uri https://registry.npmjs.org/gulp
144 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
145 verbose request uri https://registry.npmjs.org/gulp-sass
146 verbose request no auth needed
147 info attempt registry request try #1 at 1:32:20 AM
148 verbose request id 70612c1350846b23
149 http request GET https://registry.npmjs.org/gulp-sass
150 verbose request uri https://registry.npmjs.org/gulp-concat
151 verbose request no auth needed
152 info attempt registry request try #1 at 1:32:20 AM
153 http request GET https://registry.npmjs.org/gulp-concat
154 verbose request uri https://registry.npmjs.org/gulp-minify-css
155 verbose request no auth needed
156 info attempt registry request try #1 at 1:32:20 AM
157 http request GET https://registry.npmjs.org/gulp-minify-css
158 verbose request uri https://registry.npmjs.org/gulp-rename
159 verbose request no auth needed
160 info attempt registry request try #1 at 1:32:20 AM
161 http request GET https://registry.npmjs.org/gulp-rename
162 verbose request uri https://registry.npmjs.org/gulp-util
163 verbose request no auth needed
164 info attempt registry request try #1 at 1:32:20 AM
165 http request GET https://registry.npmjs.org/gulp-util
166 verbose request uri https://registry.npmjs.org/grunt-contrib-nodeunit
167 verbose request no auth needed
168 info attempt registry request try #1 at 1:32:20 AM
169 http request GET https://registry.npmjs.org/grunt-contrib-nodeunit
170 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
170 verbose stack     at Error (native)
170 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
170 verbose stack     at Object.exports.connect (_tls_wrap.js:955:21)
170 verbose stack     at Agent.createConnection (https.js:73:22)
170 verbose stack     at Agent.createSocket (_http_agent.js:174:16)
170 verbose stack     at Agent.addRequest (_http_agent.js:143:23)
170 verbose stack     at new ClientRequest (_http_client.js:133:16)
170 verbose stack     at Object.exports.request (http.js:31:10)
170 verbose stack     at Object.exports.request (https.js:163:15)
170 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:803:30)
171 verbose cwd D:\Projects\myApp
172 error Windows_NT 6.1.7600
173 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-d"
174 error node v4.1.1
175 error npm  v2.14.4
176 error error:0906D06C:PEM routines:PEM_read_bio:no start line
177 error If you need help, you may report this error at:
177 error     <https://github.com/npm/npm/issues>
178 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment] 2015-10-05 19:48
Closing as duplicate of #9829.

**Closed by othiym23** 2015-10-05 19:48 UTC
Labels: proxy, support
