### ISSUE TITLE
error installing cordova on windows 7

### ISSUE THREAD

**Issue by fwuts** [npm/npm#15106] opened 2016-12-01 22:07 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

https://gist.github.com/fwuts/a65c4f086b14c075d6daf18053f8be72

### supporting information:

 - `npm -v` prints:  3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

<!--
    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

    - Please check if there's a solution in the troubleshooting wiki:
      https://github.com/npm/npm/wiki/Troubleshooting

**Comment by zkat** [comment] 2016-12-02 03:23
Closing as a duplicate of https://github.com/npm/npm/issues/11265

Recent versions of `graceful-fs` used in the latest version of npm may mitigate this problem. Try `npm install -g npm@next` and see if it improves. Otherwise, watch that other issue for progress.

**Closed by zkat** 2016-12-02 03:23 UTC
Labels: support

**Comment by fwuts** [comment] 2016-12-02 06:11
Thanks but that did not help.Frank.

**Comment by zkat** [comment] 2016-12-02 08:21
@fwuts: What version of npm are you running? Can you please post further info in #11265, which tracks the main issue, from now on?

**Comment by fwuts** [comment] 2016-12-02 16:46
npm -v = 4.0.5

**Comment by fwuts** [comment] 2016-12-02 21:59
Strange thing. I was able to install phonegap and phonegap lets me run cordova.Do you know if it is the same cordova?
