### ISSUE TITLE
Global Uninstall Fails

### ISSUE THREAD

**Issue by realistschuckle** [npm/npm#17089] opened 2017-06-08 12:15 UTC
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I type `npm rm --global bower`, I'd expect the package to be removed from the global package cache. However, I get an `npm` error that tells me that `npm` has a problem. :-(

#### How can the CLI team reproduce the problem?

I upgraded `node` and `npm` from 7.x and 4.x, respectively. Now, when I try to uninstall any of the global packages, `npm` fails. here's a gist of the log file:

https://gist.github.com/realistschuckle/6593acd9bc6998886e9eb225785c121b

### supporting information:

 - `npm -v` prints: **5.0.2**

 - `node -v` prints: **v8.0.0**

 - `npm config get registry` prints: **https://registry.npmjs.org/**

 - Windows, OS X/macOS, or Linux?: **macOS**

**Comment by izaera** [comment] 2017-06-08 16:23
I'm attaching the exception I get in the console, in case it helps:

```
$ npm uninstall browserify -g
Unhandled rejection Error: Argument #2: Expected string but got null0
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ivan/.npm/_logs/2017-06-08T16_21_50_245Z-debug.log
```

**Comment by realistschuckle** [comment] 2017-06-08 16:25
Thanks, @izaera!

**Comment by izaera** [comment] 2017-06-08 16:26
BTW, it doesn't seem to fail for every package, because I was able to remove `node-gyp` just before trying to uninstall `browserify`.

And that's all. I don't have more info ;-).

**Comment by realistschuckle** [comment] 2017-06-08 16:29
I had four global packages: `bower`, `polymer-cli`, `@angular/cli`, and `yo`. It would not uninstall any of them. ¯\(◉◡◔)/¯

**Comment by kenany** [comment] 2017-06-08 16:45
Looks like a duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-08 16:45 UTC
