### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by 571024079** [npm/npm#16416] opened 2017-04-22 12:53 UTC
23436 error Darwin 16.0.0
23437 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
23438 error node v6.10.1
23439 error npm  v3.10.10
23440 error shasum check failed for /var/folders/c7/1xvbtt2501bc7zvrq5v2h4vc0000gn/T/npm-24301-8a8161b2/registry.npmjs.org/node-notifier/-/node-notifier-5.1.2.tgz
23440 error Expected: 2fa9e12605fa10009d44549d6fcd8a63dde0e4ff
23440 error Actual:   206d4d9db4863d421fe2378839c44c64b81f6357
23440 error From:     https://registry.npmjs.org/node-notifier/-/node-notifier-5.1.2.tgz
23441 error If you need help, you may report this error at:
23441 error     <https://github.com/npm/npm/issues>
23442 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-04-26 21:31
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:54 UTC
Labels: bot-closed, shasum, support
