### ISSUE TITLE
issue when installing jsdoc

### ISSUE THREAD

**Issue by amolc** [npm/npm#10854] opened 2015-12-16 15:53 UTC
```
123 error Darwin 15.0.0
124 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jsdoc"
125 error node v4.1.1
126 error npm  v2.14.4
127 error shasum check failed for /var/folders/yc/z1270swn0pq_1sctz89fxh0r0000gp/T/npm-26231-585b2462/registry.npmjs.org/jsdoc/-/jsdoc-3.4.0.tgz
127 error Expected: 341cdb06e44a113d9541efd212c95a488064e9ee
127 error Actual:   a92272cd92db46a223c14b9dea8faa1d13f8cc8c
127 error From:     https://registry.npmjs.org/jsdoc/-/jsdoc-3.4.0.tgz
128 error If you need help, you may report this error at:
```

**Comment by zkat** [comment] 2016-12-09 00:50
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:50 UTC
Labels: support
