### ISSUE TITLE
Looks like NPM can not find the node executable

### ISSUE THREAD

**Issue by srossross** [npm/npm#7659] opened 2015-03-17 18:09 UTC
I'm trying to install a 3rd party package which works find when I install it manually, however this happens when I run it in an automated build script.

I think the `Error: spawn ENOENT` is coming from `child_process.spawn('node', ...)` which can not find `node`.

I have tried this with npm v2.7.1 and v1.4.28

```
+ which node
/Users/sean/anaconda/envs/_build/bin/node
+ node --version
v0.10.35
+ echo PATH is /Users/sean/anaconda/envs/_build/bin:/Users/sean/anaconda/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin
PATH is /Users/sean/anaconda/envs/_build/bin:/Users/sean/anaconda/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin
+ npm install --debug git://github.com/srossross/node-authenticate-pam.git
npm WARN package.json wnext@0.0.0 No repository field.
-
> authenticate-pam@0.2.2 install /Users/sean/Documents/workspace/wnext/node_modules/authenticate-pam
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/sean/anaconda/envs/_build/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sean/Documents/workspace/wnext/node_modules/authenticate-pam
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! authenticate-pam@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the authenticate-pam@0.2.2 install script.
npm ERR! This is most likely a problem with the authenticate-pam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls authenticate-pam
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/sean/anaconda/envs/_build/bin/node" "/Users/sean/anaconda/envs/_build/bin/npm" "install" "--debug" "git://github.com/srossross/node-authenticate-pam.git"
npm ERR! cwd /Users/sean/Documents/workspace/wnext
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
Command failed: /bin/bash -x -e /Users/sean/Documents/workspace/wnext/conda.recipe/build.sh
mr_chomps:conda.recipe sean$ 

```

**Comment by smikes** [comment] 2015-03-20 12:16
Thanks for the bug report. 

Since it fails with `npm@2.7.1` as well, can you please upload the full `npm-debug.log` from that failure as a gist (https://gist.github.com)?

**Comment by srossross** [comment] 2015-03-20 15:00
Where can I find the npm-debug.log?

**Comment by smikes** [comment] 2015-03-20 16:00
`npm-debug.log` should be generated in the current directory by current versions of `npm`.

You may need to tell your automatic build system not to clean up the temporary directory if your automated build script fails.

**Comment by srossross** [comment] 2015-03-20 16:31
https://gist.github.com/srossross/f44ec759d86aa3c98d25

**Comment by srossross** [comment] 2015-03-31 14:10
Any idea what is going on here?

**Comment by smikes** [comment] 2015-03-31 14:16
Unfortunately, no.

I can reproduce the `node-gyp rebuild` failure on my machine, but not the `node` not found.  I get `node-gyp` not in path

**Comment by srossross** [comment] 2015-03-31 14:27
What information do you need to debug this? I have checked all of the inputs that are given to the spawn command running `sh -c node-gyp rebuild` 

All of the directories and files do exist. The PATH variable is correct. I have added debug statements to this line:
```
/Users/sean/anaconda/envs/_build/lib/node_modules/npm/lib/utils/lifecycle.js:213
```

How do I check  if the `node-gyp rebuild` command is failing or the spawn is failing?  How can I look at the output from `node-gyp rebuild`?

**Comment by smikes** [comment] 2015-03-31 14:38
If you have a manual checkout, you can run `node-gyp rebuild` from the command line, directly.  You can also run `npm rebuild` and `npm install`.  But we already know that works.

I just tested another thing: I checked out the git repository and ran `npm pack` to generate `authenticate-pam-0.2.2.tgz`, then used `npm install authenticate-pam-0.2.2.tgz` to test installation, and *that* worked, too.

**Comment by smikes** [comment] 2015-05-03 10:07
Is this still a problem for you?  To my knowledge, we haven't done anything in `npm` that would fix this, but it's always possible that it "magically" got fixed by some other change -- can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we may close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-05-20 03:33
Closing as abandoned.

**Closed by othiym23** 2015-05-20 03:33 UTC
Labels: support
