### ISSUE TITLE
Issue while installing using npm behind proxy

### ISSUE THREAD

**Issue by chayanjana20** [npm/npm#11480] opened 2016-02-09 14:29 UTC
Hi All,

While running the command npm install -g cordova I am getting the following error:

```
npm verb addRemoteTarball   '2c1e75a9c0dd6cee8381d5608870087ab44f3e68' ]
npm info retry fetch attempt 1 at 7:56:51 PM
npm info attempt registry request try #1 at 7:56:51 PM
npm http fetch GET http://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz
npm http fetch 200 http://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz
npm verb stack Error: shasum check failed for C:\Users\168500\AppData\Local\Temp\npm-5200-4bcd080a\registry.npmjs.org\cordova\-\cordova-6.0.0.tgz
npm verb stack Expected: 2c1e75a9c0dd6cee8381d5608870087ab44f3e68
npm verb stack Actual:   3afa59daf61885503a077f67b44a15e2e3a7e277
npm verb stack From:     http://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz
npm verb stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
npm verb stack     at ReadStream.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
npm verb stack     at emitNone (events.js:72:20)
npm verb stack     at ReadStream.emit (events.js:166:7)
npm verb stack     at endReadableNT (_stream_readable.js:903:12)
npm verb stack     at doNTCallback2 (node.js:439:9)
npm verb stack     at process._tickCallback (node.js:353:17)
npm verb cwd D:\RAPDRP\CordovaApp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "--verbose"
```

Please help me on this , any quick help is much appreciated.

Best regards,
Chayan

**Comment by zkat** [comment] 2016-12-09 00:46
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:46 UTC
Labels: support, windows
