### ISSUE TITLE
Can't install anything with "npm install"/"sudo npm install"

### ISSUE THREAD

**Issue by gio1135** [npm/npm#16168] opened 2017-03-27 22:14 UTC
I can't install anything with `npm install`. I just get lines of `npm ERR!` messages.
![screenshot 2017-03-27 at 3 14 01 pm](https://cloud.githubusercontent.com/assets/11164851/24380410/089dec76-1300-11e7-9fcc-366eb4edd374.png)

Here's the debug log:
[npm-debug.txt](https://github.com/npm/npm/files/873970/npm-debug.txt)

**Comment by KenanY** [comment] 2017-03-28 00:11
@gio1135 Could you try doing `npm install -g polymer-cli` instead? (Note that the entire package name is lowercase.)

**Comment by legodude17** [comment] 2017-03-28 15:46
Duplicate of #10686. This is normally a network issue, check your internet connection.

**Closed** 2017-06-16 21:56 UTC
Labels: bot-closed, support
