### ISSUE TITLE
npm excludes LICENSE when archiving, even when it's explicitly included in `files`

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#12564] opened 2016-05-03 20:49 UTC
Minimal testcase:
```sh
$ npm -v
3.8.8
$ tree -a
.
├── LICENSE
├── node_modules
│   └── foo
│       └── LICENSE
└── package.json

2 directories, 4 files
$ cat package.json 
{
  "name": "test",
  "version": "0.0.0",
  "files": [
    "LICENSE"
  ]
}
$ npm pack; tar -tvf test-0.0.0.tgz 
test-0.0.0.tgz
-rw-r--r-- 1000/100         75 2016-05-03 23:45 package/package.json
-rw-r--r-- 1000/100       1568 2016-05-03 23:37 package/LICENSE
$ touch .gitignore
$ npm pack; tar -tvf test-0.0.0.tgz 
test-0.0.0.tgz
-rw-r--r-- 1000/100         75 2016-05-03 23:45 package/package.json
$ rm -r node_modules
$ npm pack; tar -tvf test-0.0.0.tgz 
test-0.0.0.tgz
-rw-r--r-- 1000/100         75 2016-05-03 23:45 package/package.json
-rw-r--r-- 1000/100       1568 2016-05-03 23:37 package/LICENSE
```

Given that (almost) any dependency includes a LICENSE and the chance of one of the deps including a LICENSE is near 100%, this probably affects everyone who uses `files` and has an `.gitignore`.

**Comment by ChALkeR** [comment] 2016-05-03 21:09
The same happens with `README.md`, if it's present.
It looks like it affects only one file, though — if `README.md` should be included but is missing, then `LICENSE` is present.

**Comment by zkat** [comment] 2016-05-03 22:47
This seems like a duplicate of #5082, which @othiym23 is working on right now. It's a really old bug, but is particularly easy to reproduce in `node@6`. Stand by for a fix. :)

**Closed by zkat** 2016-05-03 22:47 UTC

**Comment by ChALkeR** [comment] 2016-05-03 23:03
@zkat Thanks!

**Comment by ChALkeR** [comment] 2016-05-03 23:28
Note: this is reproduceable to me even if `node_modules/foo` doesn't have any files, but is present and is a directory.

This is not reproduceable to me if `node_modules/{something}` is not present.
