### ISSUE TITLE
'C:\Windows\system32\npm' is not recognized as an internal or external command. 

### ISSUE THREAD

**Issue by TheAwesomeGuy** [npm/npm#18214] opened 2017-08-17 20:13 UTC
I still did not receive any help on this?

I have tried everything, but have no idea what to do. I don't know how it even picks npm up at system32 when I installed in at users

**Comment by kenany** [comment] 2017-08-17 21:42
Duplicate of #18191

**Closed as completed by kenany** 2017-08-17 21:42 UTC
Labels: support
