### ISSUE TITLE
Valid JSON: npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by vitto** [npm/npm#11972] opened 2016-03-19 13:50 UTC
I'm trying to publish a [new release of my node module](https://github.com/vitto/a-pollo/releases/tag/1.15.90) but I get this error:

```
npm cache clean && npm publish

npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT undefined
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.2
npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write

npm ERR! write EPIPE
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vitto/repo/a-pollo/npm-debug.log
```

There are additional details in [npm-debug.log](https://github.com/npm/npm/files/180829/npm-debug.log.txt) file.

I've tried to clean cache, validated package.json with http://package-json-validator.com without success.

Online i continue seeing the [old release version](https://www.npmjs.com/package/a-pollo).

Can someone help me to understand where I'm wrong?

**Comment by tk120404** [comment] 2016-03-20 14:22
Check the package.json file structure at http://www.jsoneditoronline.org/

**Comment by vitto** [comment] 2016-03-21 07:11
This is my [package.json](https://github.com/vitto/a-pollo/blob/master/package.json), also [jsoneditoronline.org](http://www.jsoneditoronline.org) doesn't throw errors.

**Comment by vitto** [comment] 2016-03-21 14:50
I suppose the JSON parse error is because i get this as response from npm server?

```
49 info retry <?xml version="1.0" encoding="utf-8"?>
49 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
49 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
49 info retry <html>
49 info retry   <head>
49 info retry     <title>503 backend write error</title>
49 info retry   </head>
49 info retry   <body>
49 info retry     <h1>Error 503 backend write error</h1>
49 info retry     <p>backend write error</p>
49 info retry     <h3>Guru Mediation:</h3>
49 info retry     <p>Details: cache-fra1221-FRA 1458394654 2580915162</p>
49 info retry     <hr>
49 info retry     <p>Varnish cache server</p>
49 info retry   </body>
49 info retry </html>
```

Is this a server cache problem?

**Comment by vitto** [comment] 2016-03-21 23:55
The problem was that I've unintentionally added a **vendors folder which added 25MB of files** useless to the module.

It would be nice if there is a **more verbose error** which explains there is some **quota limitation** or some info for module **file size warning**.

**Comment by KenanY** [comment] 2016-03-22 01:38
@vitto ref. https://github.com/npm/npm/issues/6252, https://github.com/npm/npm/issues/8339

**Comment by othiym23** [comment] 2016-03-22 20:44
Closing as duplicate of #8339, and the message there holds – the CLI team would love to see somebody contribute a check for this, but we're not going to have time to deal with this ourselves within the next 6-12 months. Thanks for your time! And thanks to @KenanY for the pointers!

**Closed by othiym23** 2016-03-22 20:44 UTC
Labels: feature-request, patch-welcome, ux
