### ISSUE TITLE
Npm installs wrong version when github source + devDependency are used

### ISSUE THREAD

**Issue by ivan-kleshnin** [npm/npm#7806] opened 2015-03-31 11:59 UTC
``` javascript
"dependencies": {
    "gulp-jsx": "git://github.com/ivan-kleshnin/gulp-jsx.git",
},
```

`$ npm install gulp-jsx` installs **git://github.com/ivan-kleshnin/gulp-jsx.git** (+)

``` javascript
"devDependencies": {
    "gulp-jsx": "git://github.com/ivan-kleshnin/gulp-jsx.git",
},
```

`$ npm install gulp-jsx` installs **last npm version** :disappointed: 

Checked in `NPM 2.7.3 | OS X`

**Comment by KenanY** [comment] 2015-03-31 13:50
Confirmed on `npm@2.7.5` as well. I wonder if this is intentional, hmm, symmetry would be nice though.

Works if you add the `--dev` flag, but that's a footgun and not recommended https://github.com/npm/npm/issues/6200

**Comment by iarna** [comment] 2015-03-31 20:09
And of course: `npm install` by itself would install the right thing.
Still, this behavior is definitely weird.

**Comment by othiym23** [comment] 2015-04-01 00:48
I don't believe the current behavior was ever intended, but I also think this is an edge case we've never really thought about explicitly. Marked as a bug while we chew on it.

I'd like to hear @iarna's reasons for disliking the current behavior when a git dependency is explicitly `npm installed`. My intuitive expectation would be that `npm install foo` would look first in `npm-shrinkwrap.json`, then in `dependencies` in `package.json`, then in `devDependencies` in `package.json`, and finally just ask the registry what it should install. That is, if we have some knowledge of what version the package wants installed of a given package, we should use that. It would also make sense that the presence of `--save` and `--save-dev` would override that.

**Comment by ivan-kleshnin** [comment] 2015-04-01 07:19
> My intuitive expectation would be that npm install foo would look first in npm-shrinkwrap.json, then in dependencies in package.json, then in devDependencies in package.json, and finally just ask the registry what it should install. That is, if we have some knowledge of what version the package wants installed of a given package, we should use that. 

This exactly fits my expectation as well.

**Closed** 2017-06-19 10:53 UTC
Labels: bot-closed, bug, git, needs-discussion
