### ISSUE TITLE
The SSL certificate for go.npm.me is expired

### ISSUE THREAD

**Issue by eseliger** [npm/npm#20683] opened 2018-05-20 07:40 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

https://go.npm.me/audit-guide
![image](https://user-images.githubusercontent.com/19534377/40276713-1ea76758-5bc6-11e8-92b4-7f6eb15ef026.png)

#### How can the CLI team reproduce the problem?

Open https://go.npm.me/audit-guide in your browser
### supporting information:

 - `npm -v` prints: 6.0.0
 - `node -v` prints: 10.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: San Jose, CA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2018-05-21 03:25
Duplicate of https://github.com/npm/npm/issues/20685.

**Closed as completed by kenany** 2018-05-21 03:25 UTC
Labels: support

**Comment by eseliger** [comment] 2018-05-21 03:26
Actually, #20685 was the duplicate

**Comment by kenany** [comment] 2018-05-21 16:00
True 👍

**Comment by knod** [comment] 2018-05-21 18:11
I think KenanY was just saying that this belongs in https://github.com/npm/www, as they mention there.
