### ISSUE TITLE
Still the same issue persists #20791

### ISSUE THREAD

**Issue by husainkhan** [npm/npm#20846] opened 2018-05-31 11:02 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
On installing the dependencies in the project, its fails with error code 418
The team said that the issue was closed 2 days ago on issue #20791 , but it still persists.
npm ERR! 418 I'm a teapot: @angular/platform-server@4.0.1

#### How can the CLI team reproduce the problem?
npm i

### supporting information:

 - `npm -v` prints:6.1.0
 - `node -v` prints:10.3.0
 - `npm config get registry` prints:http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ x] I use a proxy to connect to the npm registry.
   - [ x] I use a proxy to connect to the web.
   - [ x] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2018-05-31 15:27
Duplicate of https://github.com/npm/npm/issues/20836 (which is still open at the moment).

**Closed as completed by kenany** 2018-05-31 15:27 UTC
Labels: registry, support

**Comment by jaegz** [comment] 2018-06-13 20:13
#20836 is now closed. See https://github.com/npm/registry/issues/335

I solved this issue by:
1. [wiping my system clean of nodejs and npm](https://stackoverflow.com/a/20711410)
2. reinstalling the [nodejs msi](https://nodejs.org/en/)
3. updating my .npmrc to use https rather than http `registry=https://registry.npmjs.org/`

**Comment by simonjcarr** [comment] 2018-06-16 09:21
I still have the same issue.

**Comment by erikdstock** [comment] 2018-06-27 11:44
I'm still having this issue with a node 8 docker image. I have set the registry on it using npm config.
