### ISSUE TITLE
uid must be an unsigned int

### ISSUE THREAD

**Issue by iamola** [npm/npm#14083] opened 2016-09-26 14:07 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Trying to install Appium 1.6 Beta and its failing constantly. Tried everything. 

#### How can the CLI team reproduce the problem?

Debug Log Attached.
Running: sudo npm install -g appium@beta
Node 0.12.7
NVM 0.31.1
NPM 3.10.8

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: 0.12.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### What's the feature?
Appium 1.6 Beta
#### What problem is the feature intended to solve?
Xcode 8 issue when running Appium. 
#### Is the absence of this feature blocking you or your team? If so, how?
Yes, no testing can be done team-wide. 
#### Is this feature similar to an existing feature in another tool?
Nope.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

[npm-debug.log.zip](https://github.com/npm/npm/files/493259/npm-debug.log.zip)

**Comment by KenanY** [comment] 2016-09-26 14:11
Duplicate of https://github.com/npm/npm/issues/13918, I believe.

**Closed by KenanY** 2016-09-26 14:11 UTC

**Comment by iamola** [comment] 2016-09-26 14:19
Similar but not exactly the same and there is no resolution on the other ticket.

**Comment by KenanY** [comment] 2016-09-26 14:31
@iamola See https://github.com/npm/npm/issues/14047#issuecomment-249099655. Care to expand on how your issue is not exactly the same?
