### ISSUE TITLE
npm-deprecate results in E400 for scoped packages

### ISSUE THREAD

**Issue by neenhouse** [npm/npm#12113] opened 2016-03-28 21:31 UTC
When running the following command:

```
> npm deprecate @scope/package "Please use @scope/other-package"
```

I get the following output:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "@scope/package" "Please use @scope/other-package"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code E400

npm ERR! unsupported registry call : @scope/package
```

Seems like npm-deprecate does not work on scoped packages when using node 4.2.3 and npm 2.14.7.  Has anyone looked at this?

**Comment by zkat** [comment] 2016-03-28 22:12
Deprecating scoped packages should've been fixed as of `npm@2.14.5`, through https://github.com/npm/npm/pull/9558 -- I'm unable to reproduce this in `npm@2.14.7` -- could you upgrade and try again? Are you using the standard registry? Are you behind some kind of firewall that could be messing with the request?

**Comment by neenhouse** [comment] 2016-03-29 12:29
We are using Sinopia/1.4.0.  I'll try upgrading my local NPM client and see if that makes a difference.

**Comment by neenhouse** [comment] 2016-03-29 12:32
Upgraded to latest LTS and now I get a more specific error:

```
npm info using npm@2.14.20
npm info using node@v4.4.1
npm verb stack Error: invalid version range: latest
```

**Comment by neenhouse** [comment] 2016-03-29 12:35
When I specify a range:

```
>  npm deprecate @scope/package@'<1.1.1' "Please use @scope/other-package"


npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "@scope/package@<1.1.1" "Please use @scope/other-package instead" "--verbose"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code E400

npm ERR! unsupported registry call : @scope/package
```

**Comment by othiym23** [comment] 2016-03-29 15:03
This sounds like an issue with Sinopia, and not the CLI. It may have only partial support for scoped packages. Are you running the latest version of Sinopia?

**Comment by zkat** [comment] 2016-03-29 21:13
The `invalid version range` issue is a known CLI issue (that I have to hunt down the ticket for, but it's known to me!)

The `unsupported registry call`, on the other hand, is likely a Sinopia issue. Since it's a server-side code. :)

**Closed** 2017-06-16 22:49 UTC
Labels: bot-closed, support
