### ISSUE TITLE
npm install module_name many times changes it's deps version if installed twice

### ISSUE THREAD

**Issue by bitplanets** [npm/npm#6844] opened 2014-12-04 11:05 UTC
Take a look at these commits:

 - https://github.com/bitplanets/node_modules_test/commit/1b7788b3d2aa2c25244c7e0b6565d7583794274a
 - https://github.com/bitplanets/node_modules_test/commit/12be5407049de743422837acfad3cec3bf5ac456
 - https://github.com/bitplanets/node_modules_test/commit/a74f9ddc0caec2b78ca332e7018c0e793b80db0f

**Comment by smikes** [comment] 2015-01-06 13:25
Is this issue now resolved?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by bitplanets** [comment] 2015-01-06 17:58
I didn't tested on the last version, but if no one worked on this issue I think it still happens.

**Comment by smikes** [comment] 2015-01-06 18:25
Per @othiym23 above, "What about this behavior is a problem for you? What behavior are you expecting to see?"

`npm` processes recursive dependencies asynchronously; thus it is not deterministic which versions of a package will be installed when running `npm install`.  It is possible to work around this using `npm shrinkwrap`, as you have done.

This behavior may change when the `multi-stage-install` branch lands.  In the meantime, what you are describing is expected behavior of `npm`.

**Comment by bitplanets** [comment] 2015-01-07 14:06
I've said that even with shrinkwrap the version of the modules changes. Isn't supposed to be the exact same version across `npm install`s?

**Comment by smikes** [comment] 2015-01-07 14:41
The version that's installed changes or the version that it's installed "from" changes?


If, with shrink wrap, different versions are installed on different runs, that would be a serious bug in npm.

**Comment by bitplanets** [comment] 2015-01-07 20:14
@smikes Have you seen the body of this issue? You can see that project and even try it on your own device. So, yes as I've said different times I think is a bug because shrinkwrap should not mess the modules once are "fixed".

**Comment by smikes** [comment] 2015-01-07 21:45
It sounds like your concern is that npm writes to the package.json files after they are installed. Is that right?


I don't understand what you mean by "the body of this issue". Are you referring to another issue number?




What would npm have to do to not have this bug, in your view?

**Comment by bitplanets** [comment] 2015-01-08 13:53
I'm referring to the links. Look at this for example and look at the commit names to understand what I've done: https://github.com/bitplanets/node_modules_test/commit/1b7788b3d2aa2c25244c7e0b6565d7583794274a

**Comment by smikes** [comment] 2015-01-08 14:33
That link shows that the metadata npm stores in installed "package.json" files may change from one installation to another.  This is expected behavior. 


I believe your concern is equivalent to objecting that a particular pointer has a different value between different runs of the same program, or that files are installed to different disk sectors even though they have the same file system paths. 




Could you please tell me what in your view would the correct behavior be?  For npm to not store "_from" metadata in the installed package.json?

**Comment by bitplanets** [comment] 2015-01-08 16:06
I will be sincere with you. For me it really seem fragile and somehow broken something that should has the same output to has these changes:

    -  "_from": "inherits@~2.0.1",
    +  "_from": "inherits@2",

So if I install once on system A it will have `"_from": "inherits@~2.0.1",`. If I install again it will be `"_from": "inherits@2",`. 

I understand that there is no changed source code (in this case) but is still an issue IMO.

>I believe your concern is equivalent to objecting that a particular pointer has a different value between different runs of the same program, or that files are installed to different disk sectors even though they have the same file system paths. 

No, is like saying that a function that returns metadata for example `getMetadata()` sometimes will return you "v2" and other times "~v2.0.1". 

>Could you please tell me what in your view would the correct behavior be?  For npm to not store "_from" metadata in the installed package.json?

Not having this diff when installing twice on the same machine at 1 minute interval.

    -  "_from": "inherits@~2.0.1",
    +  "_from": "inherits@2",

**Comment by smikes** [comment] 2015-01-08 16:21
If you implemented a function getMetadata() which accessed the "_from" field, you would be relying on explicitly undocumented, internal behavior, so I would agree that would be wrong. 


Two possible fixes, then:




1. Rewrite npm internals to be deterministic wrt which source requirement is attributed to an installed dependency;




2. Delete the "_from" field from package.json




@othiym23 what do you think about #2?

**Comment by othiym23** [comment] 2015-01-09 01:35
`_from` in `npm-shrinkwrap.json` is undocumented, but _is_ used. It's a fallback in case the `resolved` fields are missing. `npm shrinkwrap` has already led a pretty peripatetic existence, and `resolved` has not always been part of how it works. The field currently communicates "this is the package semver spec that led to this tarball being downloaded and unpacked for this installation". Because of the complex interdependencies between packages, it's possible that more than one package will lead to a given package + version getting installed at a certain level in the dependency tree, and whichever one npm saw first is the one that ends up getting written to `_from`. When I resume work on the cache rewrite, `_from` will continue to play a role in dependency resolution, which will be more explicitly based around falling back from shasum to URL to version (i.e. `_from`).

@bitplanets, now that I understand the nature of your objection, I can say I respectfully disagree with you. This behavior is not evidence of fragility in npm. We're working towards a more deterministic and transactional install process, which should be in a version of npm available for testing soon, but there's always going to be a certain amount of nondeterminism in the caching and installation process due to how npm makes use of Node-style concurrency. If the correct package ends up installed on disk, the state of the shrinkwrap metadata is an irrelevant implementation detail. I wouldn't dismiss a patch to make this consistent, but it's also not a patch I'd be looking for, either.

Closing as resolved.

**Closed by othiym23** 2015-01-09 01:35 UTC
Labels: support
