### ISSUE TITLE
Yeoman installation error

### ISSUE THREAD

**Issue by MengtingXie** [npm/npm#11945] opened 2016-03-17 17:43 UTC
when use npm install -g yo to install yoman on Mac, I get :

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "i" "-g" "yo"
npm ERR! node v5.1.0
npm ERR! npm v3.3.12
npm ERR! path /usr/local/lib/node_modules/yo
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/yo' -> '/usr/local/lib/node_modules/.yo.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm version 3.3.12,  node verison v5.1.0
Please help!

**Comment by iyogeshjoshi** [comment] 2016-03-19 10:40
Seems like there is already a `yo` module installed globally. Try doing `npm prune yo -g` then `npm cache clean` and then try installing again `npm install -g yo`. I think this should do the trick :wink:

**Comment by amandeepmittal** [comment] 2016-03-19 10:59
@MengtingXie 
First clear the cache:
`npm cache clean`
Then Try:
`sudo npm install yo -g`

**Comment by MengtingXie** [comment] 2016-03-22 05:54
tried both, still getting the same error

**Comment by amandeepmittal** [comment] 2016-03-23 05:43
the only other possible solution I can think of is that you don't have permissions to write in `/usr/local/lib/node_modules` dir. Please refer to [Fixing NPM Permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and follow step 1, that might solve your issue.

**Comment by MengtingXie** [comment] 2016-03-24 14:44
thank you, but step 1 doesn't solve the problem,

**Comment by MengtingXie** [comment] 2016-03-24 14:49
It's complaining about my /usr/local/lib/node_modules/yo not empty, asking me to rename it, but there's no yo folder in the node_modules

**Comment by amandeepmittal** [comment] 2016-03-24 16:52
are you installing yeoman from cli by going inside the directory `node_modules`? If you are the it won't install.

**Comment by MengtingXie** [comment] 2016-03-24 17:18
no, I install under the /Users/{myUsername} folder or my project folder

**Comment by zkat** [comment] 2016-03-25 00:32
This looks like a duplicate of #11889.

That issue is used for tracking the bug itself, which is intermittent.

The best way to fix it, for now, is to delete the offending file: `sudo rm /usr/local/lib/node_modules/.yo.DELETE`

Let me know if this helps you get going. :)

**Comment by MengtingXie** [comment] 2016-03-25 03:30
rm: /usr/local/lib/mode_modules/.yo.DELETE: No such file or directory
rm: /usr/local/lib/mode_modules/.yo: No such file or directory

the file doesn't exist at all!

**Comment by MengtingXie** [comment] 2016-03-25 03:34
It worked!!!
Thanks a lot!

**Closed** 2016-03-25 03:34 UTC
Labels: support

**Comment by zkat** [comment] 2016-03-25 08:08
Any time! :tada:
