### ISSUE TITLE
npm install and ipv6 (Windows 10)

### ISSUE THREAD

**Issue by lordgreg** [npm/npm#10804] opened 2015-12-13 16:22 UTC
With so many Issues open here on Github, where users as I are having so many difficulties, I ask myself if npm team is actually doing any tests on Windows computers or are you forcing, on purpose, developers to switch to Mac / Linux system?
- The npm modules, which installed in a flash on mac under ipv4, take 5 minutes to install on Windows machine. 
- Having constant errors of type

```
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
```

is really getting on nerves too. There's no proxy, firewall or similar. This is just pure ipv6 connection which, obviously, npm isn't handling as it should.

I've tried so many node, npm versions without any success. And not replying to any of Windows issues, just answers everything by itself. You just don't mind the market's 90%+ of Windows users. 

And let's not start the whole `node-gyp' issue under Windows, for which, you need to have Python 2.x (forget about 3.x) and Visual Studio installed. But that's another story...

**Comment by Reinmar** [comment] 2015-12-13 17:52
I've just seen the same errors. Node 5.1.0, npm 3.5.2. I reinstalled Node and got them again (5.2.0,  3.3.12).

Both times I've been on MacOS 10.11.1 and I've been using network which never caused any problems like this.

Actually, this wasn't the only error I got from npm recently. It suddenly started throwing weird errors after some recent upgrades. I was hoping to report them, but suddenly the `network read ECONNRESET` is being thrown and I can't do anything ;|

Recent npm-debug.log: https://gist.github.com/Reinmar/a4af4e38801f4a4e40bc

```
npm ERR! shasum check failed for /var/folders/qc/1rqv2jz539jd6b66q85h2t9w0000gn/T/npm-12527-0ce0c78f/registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz
npm ERR! Expected: 03726561bc268f2e5444f54c665b7fd4a8c029e2
npm ERR! Actual:   2ac2bcf6891ed000840623f68bed0a1410ec8591
npm ERR! From:     https://registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by stefda** [comment] 2015-12-30 01:11
I'm having the same issue. Windows 10, npm 1.3.10, no proxy or firewall.

`npm config set registry http://registry.npmjs.org/` followed by `npm cache clean` as suggested elsewhere doesn't help.

**Comment by zkat** [comment] 2016-12-09 00:50
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:50 UTC
Labels: support
