### ISSUE TITLE
sudo npm uninstall npm -g crashed (npm@5)

### ISSUE THREAD

**Issue by Y-Taras** [npm/npm#16779] opened 2017-05-29 14:50 UTC
I decided  to downgrade NPM to v4 or at least reinstall npm5 but got an error:
(Ubuntu 14.04 LTS 64bit)
```
$ sudo npm uninstall npm -g

Unhandled rejection Error: Argument #2: Expected string but got null lru-cache@
    at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by skapin** [comment] 2017-05-30 14:53
Same for me.

**Comment by zkat** [comment] 2017-06-05 15:03
Closing as a duplicate of https://github.com/npm/npm/issues/16738

**Closed by zkat** 2017-06-05 15:03 UTC
Labels: npm5
