### ISSUE TITLE
Undocumented breaking change: new npm users cannot use always-auth with Basic auth

### ISSUE THREAD

**Issue by doublerebel** [npm/npm#8319] opened 2015-05-20 16:25 UTC
Hello,

We use a proxy layer over npm that allows us to seamlessly use private npm with public ([nodejitsu/smart-private-npm](//github.com/nodejitsu/smart-private-npm) by @indexzero and others, this may interest them too).

Yesterday I onboarded a new member of our team who did not have a npm account.  After hours of trial and error, comparing configurations, it is clear that new npm accounts do not work with Basic auth.

All of the existing npm accounts on our team are at least a few months old, and we have always-auth turned on to authorize us with our private npm.  This has been working great since early last year.  The side effect is that our proxy also passes the Basic auth to public npm for GETs like `npm install`, `npm owner`.  This works fine with our existing accounts, but any new account we create receives a 401 Unauthorized response for Basic auth requests.

I've checked this on Mac, Linux, with npm versions 1.4.x to 2.x.x, and the responses are the same, so the issue must be server-side.

For the new user, wiping .npmrc and `npm login` to save a bearer token does work to always-auth with public npm.

The npm client does allow me to `npm login` to my private registry without error, and saves a bearer token.  Of course that bearer token does not work since my private registry expects Basic auth.

I know I can set multiple registries in .npmrc by logging into each registry individually with `npm install --registry` -- and set the bearer token for public and the Basic auth for private.  No matter the order of registries, the public npm always takes priority and therefore npm can't find my private packages.  This setup totally breaks our seamless private/public interface.

In summary:
**1.  What happened to Basic auth for new accounts, and what is the roadmap for auth going forward?**
I see that my old accounts may have ["old-style passwords" (#7720)](https://github.com/npm/npm/issues/7720#issuecomment-85353965), what does that mean?  Will my old accounts need a change made?

**2.  How does always-auth work now, and what is the plan going forward?**
I read in [an issue comment from npm dev (#6162)](https://github.com/npm/npm/issues/6162#issuecomment-55318919) that always-auth only applies to Basic auth.  However this is not documented in [the `adduser` docs for always-auth](https://github.com/npm/npm/blob/master/doc/cli/npm-adduser.md#always-auth), it points to the docs for `config` but those docs [do not mention more details](https://github.com/npm/npm/blob/21148620fa03a582f4ec436bb16bd472664f2737/doc/misc/npm-config.md#always-auth).  In npm/npm-registry-client#78 it's suggested that always-auth not be used for public npm.

**3.  Where is documentation for multiple registry support?**
I.e. how to set default registry, different types of auth supported, possibility to fallback or check multiple registries for a package?

**Comment by tyler-johnson** [comment] 2016-05-23 22:48
I'm doing some work for a company using a Nexus server as an NPM registry (which doesn't have the auth token support) and running into the same issue. I'm not sure this is entirely server side as I noticed this line in the verbose output:

```
npm verb request using bearer token for auth
```

My setup consists of a global `.npmrc` file with a normal NPM registry authToken, as well as a project specific `.npmrc` file that specifies an `_auth` value. Ideally NPM would use the local `_auth` value over the global `_authToken` value, especially when the authToken is configured specifically for `//registry.npmjs.com/` which is not the same domain as the Nexus server.

**Comment by indexzero** [comment] 2016-05-23 22:54
Can you drop in the full .npmrc used? always-auth can definitely be set per registry using the nerfdart style config. I'm AFK atm, but if you drop in an .npmrc (no passwords plz) I can examine when I'm back.

**Comment by tyler-johnson** [comment] 2016-05-23 23:18
yes I'm sorry, this was my mistake. I was using tarballs with the `_auth` config. Once I set the registry directly everything started working. My original issue was a dupe of #10060.

**Closed** 2017-06-17 02:56 UTC
Labels: bot-closed, support
