### ISSUE TITLE
npm install finishes successfully, but npm list shows a huge number of unmet dependencies

### ISSUE THREAD

**Issue by jasonburrows** [npm/npm#16936] opened 2017-06-03 00:30 UTC
#### I'm opening this issue because:
  - [X] npm is producing an incorrect install.

#### What's going wrong?

I can install my project with npm install and it succeeds, but it will not run and I get errors about missing modules.  When I run npm list, it shows many unmet dependencies.  

#### How can the CLI team reproduce the problem?

I know this happens with the package 'onchange'.  In my case, I can make a project with 'onchange' as a dependency, install it, check that in to GitHub (along with the resulting package-lock.json file).  Then clone that out to a new system and run npm install.  The install will succeed.  Then run npm list.  You will see about 8 unmet dependencies for onchange alone.  This isn't unique to onchange so I don't think it is their bug - I see this with many packages now (never saw it with v4), but onchange is just an easy one to use as an example.

Note that if you just delete the package-lock.json file, remove the node_modules directory, and start again - it all works.  I don't think the package-lock.json mechanism is working as intended.

### supporting information:

 - `npm -v` prints:
5.0.1

 - `node -v` prints:
6.10.3

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:
Ubuntu 16.04.2 LTS

 - Network issues:
No proxy, network is great.

 - Container:
No container.

**Comment by zkat** [comment] 2017-06-05 16:17
Closing as duplicate of https://github.com/npm/npm/issues/16902

**Closed as completed by zkat** 2017-06-05 16:17 UTC
Labels: npm5
