### ISSUE TITLE
Errors with npm install  

### ISSUE THREAD

**Issue by ayoubhamaoui** [npm/npm#20828] opened 2018-05-30 14:12 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [* ] npm is doing something I don't understand.
  - [* ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - Windows 10 64bit:
 
```
npm install
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm@latest',
1 verbose cli   '-g' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session 8f01e9d6da50b46d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for npm@latest error:0906D06C:PEM routines:PEM_read_bio:no start line
8 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
8 verbose stack     at Object.createSecureContext (_tls_common.js:104:17)
8 verbose stack     at Object.exports.connect (_tls_wrap.js:1049:48)
8 verbose stack     at HttpsAgent.createConnection (https.js:111:22)
8 verbose stack     at HttpsAgent.createSocket (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\agentkeepalive\lib\_http_agent.js:271:26)
8 verbose stack     at HttpsAgent.createSocket (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\agentkeepalive\lib\agent.js:77:11)
8 verbose stack     at HttpsAgent.addRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\agentkeepalive\lib\_http_agent.js:240:10)
8 verbose stack     at new ClientRequest (_http_client.js:258:16)
8 verbose stack     at Object.request (http.js:38:10)
8 verbose stack     at request (https.js:239:15)
8 verbose stack     at fetch.Promise (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:54:17)
8 verbose stack     at new Promise (<anonymous>)
8 verbose stack     at fetch (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:41:10)
8 verbose stack     at retry (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\index.js:332:14)
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\promise-retry\index.js:29:24
8 verbose stack     at <anonymous>
9 verbose cwd C:\Users\dell
10 verbose Windows_NT 10.0.17134
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
12 verbose node v8.11.2
13 verbose npm  v5.6.0
14 error error:0906D06C:PEM routines:PEM_read_bio:no start line
15 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2018-05-30 16:07
Hello! This is a duplicate of #10897. Please try `npm config set registry http://registry.npmjs.org`.

**Closed as completed** 2018-05-30 22:22 UTC
