### ISSUE TITLE
npm5.4 fails to install packages that depend on fsevents on windows

### ISSUE THREAD

**Issue by filipesilva** [npm/npm#18287] opened 2017-08-24 08:54 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When using npm5.4 on a windows machine, and installing a package that has an optional dependency on `fsevents` (like `chokidar`), install will fail with a `EPERM` error while unlinking subdependencies of `fsevents`. There is no error when installing packages that do not depend of `fsevents` (like `glob`).

I think this might be related to https://github.com/npm/npm/issues/17671 / https://github.com/npm/npm/issues/17747, but is the 5.4 version of the problem.

#### How can the CLI team reproduce the problem?
```
> mkdir npm-fsevents
> cd npm-fsevents
> npm i glob
npm WARN saveError ENOENT: no such file or directory, open 'D:\sandbox\npm-fsevents\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'D:\sandbox\npm-fsevents\package.json'
npm WARN npm-fsevents No description
npm WARN npm-fsevents No repository field.
npm WARN npm-fsevents No README data
npm WARN npm-fsevents No license field.

+ glob@7.1.2
added 11 packages in 0.762s

> npm i chokidar
npm ERR! path D:\sandbox\npm-fsevents\node_modules\fsevents\node_modules\assert-plus\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\sandbox\npm-fsevents\node_modules\fsevents\node_modules\assert-plus\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\sandbox\npm-fsevents\node_modules\fsevents\node_modules\assert-plus\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\sandbox\\npm-fsevents\\node_modules\\fsevents\\node_modules\\assert-plus\\package.json\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\sandbox\\npm-fsevents\\node_modules\\fsevents\\node_modules\\assert-plus\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kamik\AppData\Roaming\npm-cache\_logs\2017-08-24T08_48_16_741Z-debug.log

```

### supporting information:

 - `npm -v` prints: 5.4.0
 - `node -v` prints: v6.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by cchamberlain** [comment] 2017-08-25 05:27
As you mentioned, this seems to be the exact same issue as https://github.com/npm/npm/issues/17747. Seeing as Windows npm installs are completely broken (from both basic usage / package lock perspectives) post `5.0.4` and don't appear to be getting any prioritization or core team feedback, dupes seem appropriate. 😉

Mentioned prior - I'm happy to work on a PR but it would be helpful to get a bit of direction first from maintainers on where the issue is likely to sit and buy-in that a PR would be accepted.

**Comment by zfeher** [comment] 2017-08-25 06:54
I am experiencing the same issue on windows with 5.4.0. With 5.3.0 it works just fine. 

Attached debug file: [debug.txt](https://github.com/npm/npm/files/1251066/debug.txt)

**Comment by lukeapage** [comment] 2017-08-25 13:53
Same error for me. fsevents and only npm 5.4, 5.3 is fine.

Also reproduced on 2 different PCs - definitely not environmental.

**Comment by filipesilva** [comment] 2017-08-25 14:08
Can you try `npm install --no-optional` and see if it works for now? It was suggested in https://github.com/npm/npm/issues/17671#issuecomment-324908221.

**Comment by lukeapage** [comment] 2017-08-25 14:17
@filipesilva yes very weirdly `--no-optional` works, despite the fact it actually installs our 2 optional dependencies..

**Comment by zfeher** [comment] 2017-08-25 17:20
@filipesilva I've tried without running VS Code the issue remains. 

Interestingly if I remove the _node_modules_ folder `npm i` works. After this every `npm i` fails.

I've tried the `npm i --no-optional` version too, it run successfully (removed 100 packages). Running an `npm i` after this fails again.

I've also noticed that it takes a lot more time when it will fail.

**Comment by AlQuraian** [comment] 2017-08-26 11:51
Same issue for me. --no-optional seem to avoid the issue though.

**Comment by Paddelu** [comment] 2017-09-02 13:31
Same issue here. Glad i found this workaround, been driving me crazy all day

**Comment by MissCuriosity** [comment] 2017-09-04 07:38
same issue here

**Comment by n3dst4** [comment] 2017-09-04 13:06
Just pasting a link to some research I did on #18380 to identify the commit which introduced this behaviour:

https://github.com/npm/npm/issues/18380#issuecomment-326954754

**Comment by fabianchoxD** [comment] 2017-09-05 08:39
downgrade th node version has works for me

`npm install -g npm@5.3`

**Comment by Shtokins** [comment] 2017-09-06 20:45
same issue. downgrading of node helped

**Comment by Teamop** [comment] 2017-09-08 02:30
Upgrade to v5.4.1, still get the same error, even cannot work around with `--no-optional`

**Comment by Mds92** [comment] 2017-09-08 08:29
Upgrade to v5.4.1, still get the same error, even cannot work around with --no-optional :-(

**Comment by clener** [comment] 2017-09-08 08:59
I've been stuck for over a day due to this issue. Thanks for giving me the one line of code to fix it 😄 `npm install -g npm@5.3` works beautifully.

**Comment by Mds92** [comment] 2017-09-08 09:51
If you downgrade to 5.3 and still get the same error in Windows like me.
After hours working with npm versions I found the following solution:

https://stackoverflow.com/a/46113451/191647

**Comment by marcins** [comment] 2017-09-08 13:15
Duplicate of #17671 - I have a lot of notes on my investigation of the issue there, and a potential fix in PR.

**Comment by iarna** [comment] 2017-09-09 00:06
Closing as a dup of #17671. The PR @marcins provided will be landing v soon.

**Closed as completed by iarna** 2017-09-09 00:06 UTC
Labels: bug, windows, npm5

**Comment by jumpDuckEgg** [comment] 2017-09-13 10:28
the same error  ||   npm@5.4

**Comment by ilich** [comment] 2017-09-13 21:09
The same problem with npm 5.4.1 on Windows 10.

**Comment by FHoulbreque** [comment] 2017-09-14 16:19
Encountered the same issue as described here, had to roll back to 5.3.

**Comment by jimmymain** [comment] 2017-09-29 07:26
same problem for me on 5.4.2, downgraded to 5.3.0, woks perfectly.
why is the issue closed?

**Comment by zfeher** [comment] 2017-09-29 07:44
Updating to 5.4.2 solved the problem for me. You may try to remove the _node_modules_ and do an `npm i`. I don't remember if I did this or not.

**Comment by tomihawk** [comment] 2017-10-05 21:20
Still happening for me too after upgrading to 5.4.2.  How many times has this claimed to have been fixed now?

**Comment by motss** [comment] 2017-10-15 09:59
Facing this issue on Travis with `node 8.7.0` + `npm 5.4.2`. Any solution?

**Comment by deadwards90** [comment] 2017-11-06 11:02
As above, still happening on 5.4.2, moved down to 5.3 for now.

**Comment by awesomepeng** [comment] 2018-04-05 12:31
webpack-dev-server@2.8 chokidar from fsevents to readdip ,so just use webpack-dev-server@2.8
