### ISSUE TITLE
Prefer current node in run-script

### ISSUE THREAD

**Issue by segrey** [npm/npm#11175] opened 2016-01-16 17:43 UTC
Running an npm script using a fully specified path to node doesn't result in spawning child node processes using this node interpreter. Instead, a node interpreter from `PATH` is used. Consider this example:

```JSON
{
  "name": "sample-project",
  "scripts": {
    "print-version": "echo $PATH"
  }
}
```
Commands in terminal:
```
$ node --version
v0.12.9
$ /home/segrey/.nvm/versions/node/v5.4.0/bin/npm run-script print-version

> sample-project@ print-version /home/segrey/sample-project
> node --version

v0.12.9
```

However, v5.4.0 was expected, as it was specified explicitly.

Is it possible to prepend directory of current node interpreter to `PATH`, like it's already done with `node_modules/.bin`?

**Comment by othiym23** [comment] 2016-01-18 05:00
I agree with you that this is the common-sense way that this should work, but I also know what the CLI team's workload looks like, and we're not going to have time to get to this within the next 6-12 months (it's useful, but it's not as urgent as the other things we have scheduled). Therefore, I'm going to close this feature request.

You _can_ work around this by running

```sh
$ PATH=/home/segrey/.nvm/versions/node/v5.4.0:$PATH /home/segrey/.nvm/versions/node/v5.4.0/bin/npm run-script print-version
```

(which is more or less what nvm and other version managers do internally), but I agree that npm's current default behavior is kind of a surprise / disappointment.

However! Take a look at [the code that sets up the package script environment](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L83-L94), which is what sets up the path handed off to child scripts. Either `require('path').dirname(process.execPath)` would need to be prepended to the path at the very end, or (less disruptively), pushed onto the array after the list of `node_modules.bin` folders but before the existing `${PATH}` gets appended. If you want to put together a patch that does this (with a test), we'd be happy to land the patch.

Thanks for your time!

**Closed by othiym23** 2016-01-18 05:00 UTC
Labels: feature-request, platform-integration

**Comment by segrey** [comment] 2016-01-18 09:50
@othiym23 Thank you for the detailed reply! Will try to come up with a patch. Btw, just curious, would it be more convenient to keep low priority (but valid) issues open?

**Comment by othiym23** [comment] 2016-01-18 10:00
Given the number of open issues, no. It is incredibly hard to use the issue tracker to figure out where the team's attention is right now, at least in part because there are hundreds of open feature requests, the vast majority of which will never be addressed by the maintainers. This leads to (yet more) duplicate requests and also contributes to the write-only nature of the issue tracker, as issue search gets decreasingly useful as the number of open issues grows.

We've made a calculated decision that it will be more valuable to more users to close all but the feature requests we intend to implement in the next 6-12 months. If we can get the list of open issues down under a couple hundred, we can adjust how we use the tracker, but until then, we have to be pretty aggressive about closing as much as we can. I hope this makes sense! Transparency and utility impose some pretty hard tradeoffs here.

**Comment by segrey** [comment] 2016-01-18 10:04
Yeah, this makes sense. Thank you for the details!

**Comment by sciyoshi** [comment] 2016-04-12 14:10
@segrey @iarna this commit caused a regression: see #5876 for the original issue. NPM shouldn't be clobbering the PATH variable from scripts since it breaks the functionality of other tools (rvm, virtualenv).
