### ISSUE TITLE
npm Issue on windows for installation npm (tarball instatallation not working as well).

### ISSUE THREAD

**Issue by sibStephen** [npm/npm#13048] opened 2016-06-14 11:33 UTC
```
13905 silly addNamed async@0.2.10
13906 verbose addNamed "0.2.10" is a plain semver version for async
13907 silly cache afterAdd async@0.2.10
13908 verbose afterAdd C:\Users\Akhil\AppData\Roaming\npm-cache\async\0.2.10\package\package.json not in flight; writing
13909 verbose correctMkdir C:\Users\Akhil\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
13910 info retry fetch attempt 1 at 4:50:48 PM
13911 info attempt registry request try #1 at 4:50:48 PM
13912 http fetch GET https://registry.npmjs.org/request-replay/-/request-replay-0.2.0.tgz
13913 verbose afterAdd C:\Users\Akhil\AppData\Roaming\npm-cache\async\0.2.10\package\package.json written
13914 http fetch 200 https://registry.npmjs.org/request-replay/-/request-replay-0.2.0.tgz
13915 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Akhil\AppData\Local\Temp\npm-8848-3405b941\registry.npmjs.org\request-replay\-\request-replay-0.2.0.tgz.3189921909' -> 'C:\Users\Akhil\AppData\Local\Temp\npm-8848-3405b941\registry.npmjs.org\request-replay\-\request-replay-0.2.0.tgz'
13916 verbose stack TypeError: tarball.destroy is not a function
13916 verbose stack     at WriteStreamAtomic.<anonymous> (C:\Users\Akhil\AppData\Roaming\npm\node_modules\npm\lib\cache\add-remote-tarball.js:97:15)
13916 verbose stack     at emitOne (events.js:82:20)
13916 verbose stack     at WriteStreamAtomic.emit (events.js:169:7)
13916 verbose stack     at WriteStreamAtomic.emit (C:\Users\Akhil\AppData\Roaming\npm\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:60:34)
13916 verbose stack     at C:\Users\Akhil\AppData\Roaming\npm\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:89:19
13916 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
13917 verbose cwd C:\Users\Akhil\BEST\Probetools
13918 error Windows_NT 10.0.10586
13919 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Akhil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
13920 error node v4.4.5
13921 error npm  v3.9.5
13922 error tarball.destroy is not a function
13923 error If you need help, you may report this error at:
13923 error     <https://github.com/npm/npm/issues>
13924 verbose exit [ 1, true ]
```

**Comment by sibStephen** [comment] 2016-06-14 11:34
npm installation not working on windows 10 , looked out for other options but not able to install npm as such.

**Comment by othiym23** [comment] 2016-08-19 22:04
```
13915 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Akhil\AppData\Local\Temp\npm-8848-3405b941\registry.npmjs.org\request-replay\-\request-replay-0.2.0.tgz.3189921909' -> 'C:\Users\Akhil\AppData\Local\Temp\npm-8848-3405b941\registry.npmjs.org\request-replay\-\request-replay-0.2.0.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:04 UTC
