### ISSUE TITLE
npm install - issue with installing multiple versions of github repo

### ISSUE THREAD

**Issue by charlierudolph** [npm/npm#7384] opened 2015-02-18 22:15 UTC
A, B, C, D are private github projects that are each npm modules.

A has dependencies: B, C, and D
B has dependencies: D
C has dependencies: D

If I attempt to use different versions of D (ie A uses D@0.0.1, B uses D@0.0.2, C used D@0.0.3) on each repo by specifying tags, it does not work and instead just installs the same repo version for all them which causes errors.

**Comment by KenanY** [comment] 2015-02-18 22:22
@charlierudolph `npm` version? So you're saying that `npm` is ignoring the specified tags?

**Comment by charlierudolph** [comment] 2015-02-18 22:27
npm version 2.1.18.
It appears to install properly the first time the repo is installed, but then assumes the rest are the same version and disregarding their tags.

**Comment by othiym23** [comment] 2015-02-19 07:51
Closing as duplicate of #6469. If you think this is sufficiently different from that issue to merit separate tracking, let us know and I'll reopen, or if possible, note the additional details there.

**Closed by othiym23** 2015-02-19 07:51 UTC
