### ISSUE TITLE
npm shrinkwrap installs devDependencies by default

### ISSUE THREAD

**Issue by pgarrison** [npm/npm#14479] opened 2016-11-01 05:39 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm shrinkwrap` saves `devDependencies` by default. See [this gist](https://gist.github.com/pgarrison/4b447ed651c18c62c137030f25ad7c9a) for my `package.json` and the `npm-shrinkwrap.json` get it generates. I was expecting the shrinkwrap file to ignore `wrappy` entirely. 

It looks like from #10073 npm sets `dev=true` if `--production` or `--only=prod` are not included. On the other hand, `man npm shrinkwrap` says that "devDependencies  will not  be  included  unless  you  explicitly  set the --dev flag when you run npm shrinkwrap."

#### How can the CLI team reproduce the problem?
See [this gist](https://gist.github.com/pgarrison/4b447ed651c18c62c137030f25ad7c9a).

### supporting information:

 - `npm -v` prints: 4.0.1
 - `node -v` prints: 6.8.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pgarrison** [comment] 2016-11-01 06:24
Seems like this was #9727 ?

**Comment by legodude17** [comment] 2016-11-01 16:13
What is your opinion on this @othiym23? This seems like an actual bug.

**Comment by mourner** [comment] 2016-11-01 21:57
We're experiencing the same issue with NPM v3.10.8.

**Comment by legodude17** [comment] 2016-11-01 23:16
Dug a little deeper. The expected behavior is that devDeps get marked `dev: true`. Then when you install, if you have `--only`, it will narrow by things marked `dev: true`. @pgarrison, what happens when you use that shrinkwrap file and then just `npm install`?

**Comment by pgarrison** [comment] 2016-11-02 01:48
With a simple `npm install` it gets everything, including the dev dependencies. Whether it's installing the dev dependencies according to `package.json` or `npm-shrinkwrap.json` I haven't checked yet. It appears `npm i` works as documented.

**Comment by othiym23** [comment] 2016-11-03 21:15
As of `npm@4.0.1`, this is the [intended behavior](https://github.com/npm/npm/blob/release-next/CHANGELOG.md#v401-2016-10-24), and the CLI team simply got ahead of ourselves and forgot to update the documentation. That will be fixed soon. As far as seeing the same behavior in `npm@3.10.8`, @mourner, it must be something else going on – can you put together a repro case?

**Comment by mourner** [comment] 2016-11-03 23:31
@othiym23 nevermind, I misunderstood the issue. It's working as expected.

**Closed** 2016-11-04 02:37 UTC
Labels: bug, documentation
