### ISSUE TITLE
tried to uninstall angular cli but its says error with npm

### ISSUE THREAD

**Issue by sahithya03** [npm/npm#17137] opened 2017-06-11 17:42 UTC
C:\Users\sahithya mulapalli>npm uninstall -g angular-cli
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Unhandled rejection Error: Argument #2: Expected string but got null randomatic@^1.1.3 fetched in 181ms
    at addDependency (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\sahithya mulapalli\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

**Comment by kenany** [comment] 2017-06-11 23:23
You didn't include the full log, so I'm just gonna assume you are using `npm@5`, in which case this is a duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-11 23:23 UTC
Labels: support
