### ISSUE TITLE
Issue Updating Node Global Modules After Update to Node 5.0.0

### ISSUE THREAD

**Issue by icn2you** [npm/npm#10216] opened 2015-11-02 04:04 UTC
Upon attempting to execute an update of Node's global packages (`npm update -g`) this evening, I received the following error:

```
npm ERR! addLocal Could not install /private/tmp/node20151029-26743-1ckc41u/node-v5.0.0/npm_install
```

This error occurred immediately after an update of Node via Homebrew (`brew upgrade --all`). (Updates of Node global modules were successful prior to the update.) I'm running OS X 10.9.5 (Mavericks) on a MBP (mid-2009). Node version is 5.0.0 (installed and updated via Homebrew); NPM version is 3.3.9. I tried running `npm cache clean`, but it had no effect on the error.

Please assist.

**Comment by KenanY** [comment] 2015-11-02 15:59
Duplicate of https://github.com/npm/npm/issues/10165?

**Comment by icn2you** [comment] 2015-11-07 06:20
Indeed, it is, @KenanY! Thanks a million! :+1:

**Closed** 2015-11-07 06:20 UTC
