### ISSUE TITLE
Think about splitting package.json into parts in order to improve docker experience

### ISSUE THREAD

**Issue by xaka** [npm/npm#11446] opened 2016-02-06 07:04 UTC
Hi there,

The problem is very simple. In order to speed up docker builds, one needs to leverage layers caching and usual approach is:

```
COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app/
```

It works well in cases when you don't touch package.json too often, but in case of active development you start messing around with everything in that file, but dependencies. You adjust scripts sections, change main property, etc., but dependencies are unchanged. What happens next is docker recognizes files as modified and so bypasses cached `npm install` results.

It would be really helpful to have a composable package.json in order to extract dependencies into external files so further changes to package.json doesn't affect docker caching.

Thanks!

**Comment by othiym23** [comment] 2016-02-09 23:47
Hi! Thanks for putting this together! You’ve identified a real problem, which is that the churn-heavy nature of developing using npm works poorly with the layered filesystem concept that Docker is built on. There are a few other cases where the CLI team’s desire to have npm work in an atomic, transactional way collides with how Docker wants to do things, and we’d love to have input from Docker users about how we can improve the development experience on Docker. At the same time, this isn’t a solution we can use – there are significant backwards and forward compatibility issues involved with pulling package metadata out of `package.json`, and this generally feels like a solution that shifts the problem around without directly addressing it. So, please do keep thinking about this, and making these suggestions, but I’m going to close this issue, because this particular solution is one that we’re not going to implement.

**Closed by othiym23** 2016-02-09 23:47 UTC
Labels: feature-request, package-json

**Comment by BelfordZ** [comment] 2016-04-12 20:38
What if we allowed npm install to take a file path to a package.json file, and have npm install the dependencies into the cwd's node_modules folder? then you could have

```
app/
  package.json ## works as usual
  aggressively-cached-package.json
```

then do 
```
COPY aggressive-cache
npm install aggressive-cached-package.json

COPY package.json .
npm install
```

Perhaps a flag to `npm install` would make this easier, like `npm install -f [some package.json file]`

**Comment by BelfordZ** [comment] 2016-04-12 20:48
alternatively, what about a new cli command 
`npm fetch [dependencies.json]` where dependencies.json is a shortened version of package.json which only has devDependencies and dependencies keys.

**Comment by BelfordZ** [comment] 2016-04-21 17:37
@othiym23 Any advice on this one? Im thinking about scripting something to read the json, and manually call npm install on each dep.

**Comment by jezell** [comment] 2016-04-23 09:40
Don't npm install in your docker build. npm install is a dev time activity. Use a container to npm install with your node_modules folder mounted while you are developing. Then you can simply add node_modules in the docker build and skip the npm install. Downloading files during a docker build doesn't give you reproducible or reliable builds, and it's way slower than adding local files, so it should generally be avoided.

**Comment by BelfordZ** [comment] 2016-07-11 15:54
@jezell Thanks for the tip! That does seem like a reasonable idea, and would certainly reduce the time to boot a container, and reduce odds that a build fails due to npm servers. 

That said, have you run into issues where peoples local env npm install differently (diff node version, etc)? 

Also, currently my team doesn't build their own containers. The containers are used for CI / CD only, so having the devs create builds is a bit of a regression in our process.

**Comment by shankiesan** [comment] 2016-09-06 12:34
I've been facing a similar situation @BelfordZ when trying to create a Docker image that uses NPM as a build tool. The solution that I've come up with is separating my `package.json` into two bits – and to merge them together in the Dockerfile using `node mergePackages.js`, where `mergePackages.js` looks like this:

```
var packageJSON = require('../packageDependencies.json');
var packageAdditions = require('../packageAdditions.json');
var fs = require('fs');

fs.writeFile("package.json", JSON.stringify(Object.assign(packageJSON, packageAdditions)), function(err) {
    if(err) {
        return console.log(err);
    }
    // The file was saved
});
```

Seems to do the trick...

**Comment by advance512** [comment] 2017-03-21 01:19
Another idea is having a package.json and package.dev.json, and on Docker build do:

```
COPY package.dev.json package.json
RUN npm install

COPY package.json package.json
RUN npm install --production
```

The only issue then, would be keeping the two files synchronized..

**Comment by mtpultz** [comment] 2017-09-11 19:54
@advance512 I like that just needs package.dev.json to be able to inherit from package.json and override x, y, z of the production version then you wouldn't need to manually synchronize.  Something like package.dev.json has `{ "inherit": "package.json", ... }` then internally npm could Object.assign inherited JSON files found at the same level or up.  Similar to what occurs packages do with their config files so wouldn't be foreign.

**Comment by BelfordZ** [comment] 2017-11-15 20:52
@othiym23 How can I make a proposal to the CLI team? 

I'd like to propose adding a CLI option to specify which file to use as `package.json`. Something like
`npm install --package-file-name package.docker.json`. This also solves many other problems when using NPM with docker.

**Comment by DanielRamosAcosta** [comment] 2018-05-09 11:30
I would love to see this issue solved. Right now, every time I bump a new version of my services I have to install all the dependencies again :cry:
