### ISSUE TITLE
npm requests@2.69.1 not found

### ISSUE THREAD

**Issue by Gogfather** [npm/npm#13123] opened 2016-06-20 23:11 UTC
At around 2;30pm PDT today all of a sudden we keep getting this error:
```
      npm WARN package.json origin-grunt-component-packager@0.0.0 No repository field.
      npm WARN package.json origin-grunt-component-packager@0.0.0 license should be a valid SPDX license expression
      npm ERR! Linux 3.5.0-23-generic
      npm ERR! argv "/home/originautomation/.nvm/versions/node/v0.12.7/bin/node" "/home/originautomation/.nvm/versions/node/v0.12.7/bin/npm" "install"
      npm ERR! node v0.12.7
      npm ERR! npm  v2.11.3
      
      npm ERR! version not found: request@2.69.1
      npm ERR! 
      npm ERR! If you need help, you may report this error at:
      npm ERR!     <https://github.com/npm/npm/issues>
```

Can some versions go offline?

**Comment by ligerzero459** [comment] 2016-06-20 23:37
I'm on npm v3.10.1, Node 5.11.1 and am encountering the same error as of about 30 minutes go.

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.11.1
npm ERR! npm  v3.10.1

npm ERR! No compatible version found: request@2.69.1
```

**Comment by pbomb** [comment] 2016-06-20 23:39
I'm getting this error as well. Trying to track down which package is depending on that

**Comment by ligerzero459** [comment] 2016-06-20 23:43
Looks like it's might be `tap`, at least on my end. I removed it from my package.json and was able to install the rest of my deps.

**Comment by eugeneiiim** [comment] 2016-06-20 23:43
tap 2.2.0 and grunt-contrib-nodeunit 0.3.3 are broken because of this dependency.

**Comment by pbomb** [comment] 2016-06-20 23:45
yeah, upgrading grunt-contrib-nodeunit fixed it for me

**Comment by ligerzero459** [comment] 2016-06-20 23:49
codecov.io@0.1.7 seems to be the root cause. It's included in tap and trying to install it by itself instantly throws the error

**Comment by rferreira** [comment] 2016-06-21 00:02
how does a package disappear from npm? That's just nutty.

**Comment by othiym23** [comment] 2016-06-21 00:08
https://github.com/cainus/codecov.io/issues/33 is the issue on `codecov.io`, and it's not that the package existed, it's that `request@2.69.1` never existed in the first place. Unfortunately, there's not a lot npm can do on its own to resolve this, so we'll have to wait until either a new version of `codecov.io` is released or `tap` is patched to no longer depend on it (or to pin to a previous version that doesn't have this problem). Sorry for the interruption in service, everyone.

**Comment by othiym23** [comment] 2016-06-21 00:09
We're also [working on a patch](https://github.com/npm/npm/pull/13124) that will make clearer what's depending on a missing package to make it easier to troubleshoot these kinds of problems in the future.

**Comment by bassamyan** [comment] 2016-06-21 00:20
VUE完全装不来了

**Comment by othiym23** [comment] 2016-06-21 00:28
With @isaacs's speedy release of `tap@5.7.3`, this issue is resolved for npm itself. Reinstalling the latest versions of npm and / or `grunt-contrib-nodeunit` should address this problem. Closing as resolved. Thanks to all for your time!

**Closed by othiym23** 2016-06-21 00:28 UTC
Labels: big-bug, bug
