### ISSUE TITLE
Seeing elevated network read ECONNRESET from AWS

### ISSUE THREAD

**Issue by nodesocket** [npm/npm#12484] opened 2016-04-26 18:43 UTC
Today been seeing lots of `npm ERR! network read ECONNRESET` when invoking `npm install`.

Does this indicate a CDN issue on npm's side? This is from multiple AWS instances in the `us-west-1` and `us-west-2` regions.

**Comment by nodesocket** [comment] 2016-04-26 20:14
Still seeing consistently.

```
npm ERR! node v0.12.7
npm ERR! npm  v2.14.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
```

**Comment by nodesocket** [comment] 2016-04-28 16:57
Anybody else confirm?

**Comment by pyramation** [comment] 2016-04-28 17:17
there was an issue where an accepted answer was to change https to http [here](http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset)

however, that solution isn't ideal. Our registry is set to `https://registry.npmjs.org/`... could it be something with the cert or a configuration? This issue has been intermittent. Any ideas are greatly appreciated, cheers!

**Comment by blopker** [comment] 2016-04-28 21:20
Having this issue as well. CentOS 7.

**Comment by blopker** [comment] 2016-04-28 21:22
Confirmed that changing registry to use `http` fixes issue.

**Comment by nodesocket** [comment] 2016-04-28 21:30
I'm not going to switch to `http` since it is a security concern because of man in the middle attacks. I'
m guessing npm is having intermittent https issues upstream at their cdn? The status page does not indicate anything.

**Comment by othiym23** [comment] 2016-04-28 21:33
This is a discussion for [`npm/registry`](https://github.com/npm/registry/issues) because the CLI is just using stock Node.js HTTP / HTTPS, so I'm to redirect y'all there and close this issue. I can say that this is generally a local networking issue that happens when there's a lot of simultaneous HTTPS connections, and not a problem with npm's CDN provider. Somebody from @npm/registry-team can give you more information once you open an issue over there.

**Closed by othiym23** 2016-04-28 21:33 UTC
Labels: registry, support

**Comment by szarouski** [comment] 2016-06-10 03:43
It is worth to mention that the issue and solution is described here: https://github.com/npm/registry/issues/10.
