### ISSUE TITLE
Node Js problem in installation of kraken

### ISSUE THREAD

**Issue by yash199649** [npm/npm#15712] opened 2017-02-08 17:46 UTC
after installing kraken generator "npm install -g yo generator-kraken bower grunt-cli" and using yo kraken to create an application giftrees i get this error everytime i try to run server or install any dependency
module.js:471
    throw err;
    ^

Error: Cannot find module 'kraken-js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\projects\gifts\giftrees\index.js:4:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node.exe" "C:\\Users\\yash\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! giftrees@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the giftrees@0.1.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the giftrees package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs giftrees
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls giftrees
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\gifts\giftrees\npm-debug.log

**Comment by watilde** [comment] 2017-02-09 12:24
This issue seems duplicate of #11265. Can you check that issue?

**Closed** 2017-06-17 04:14 UTC
Labels: bot-closed
