### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by anupkumar0072000** [npm/npm#17738] opened 2017-07-12 07:55 UTC
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0
.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0
.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0
.tgz

**Comment by golovan** [comment] 2017-07-12 11:58
Same for me. Nothing changed in the project but got this error today.

**Comment by laureysruben** [comment] 2017-07-12 12:45
Same here. Someone opened an issue on the ansi-styles project. But the owner closed the issue immediately and referred to npm for resolving it.

I added 2 log files showing the issue in attachment

[logs.zip](https://github.com/npm/npm/files/1141971/logs.zip)

**Comment by laureysruben** [comment] 2017-07-12 14:18
@anupkumar0072000 Maybe you should update the title of this issue to be a bit more descriptive? Maybe mention ansi-styles etc

**Comment by kenany** [comment] 2017-07-12 16:40
Duplicate of https://github.com/npm/npm/issues/17723

**Closed as completed by kenany** 2017-07-12 16:40 UTC
Labels: support
