### ISSUE TITLE
npm@5.0.1 will generate lockfile differences if installing over previously version

### ISSUE THREAD

**Issue by danpoltawski** [npm/npm#16856] opened 2017-06-01 08:23 UTC
#### I'm opening this issue because:
  - [x] npm is producing an incorrect install.

#### What's going wrong?

When npm@5.0.1 runs npm install, it creates [lockfile differences](https://gist.github.com/danpoltawski/bb15ab8046bcddc55ad35f2e3eb07dd5) if the node_modules folder was created by a previous npm version.

(This issue is similar to #16728 and from the comments there I think you might be aware, but I didn't see this specific case tracked, so here it is).

#### How can the CLI team reproduce the problem?

I have produced a testcase at https://github.com/danpoltawski/MDL-59103 which has a lockfile created 

Here is how to demonstrate the problem:
```
$ git clone --quiet git://github.com/danpoltawski/MDL-59103.git && cd MDL-59103

$ nvm use 5
Now using node v5.12.0 (npm v3.8.6)

$ npm install
MDL-59103@ /Users/danp/git/MDL-59103
└─┬ glob@7.1.2 
  ├── fs.realpath@1.0.0 
  ├─┬ inflight@1.0.6 
  │ └── wrappy@1.0.2 
  ├── inherits@2.0.3 
  ├─┬ minimatch@3.0.4 
  │ └─┬ brace-expansion@1.1.7 
  │   ├── balanced-match@0.4.2 
  │   └── concat-map@0.0.1 
  ├── once@1.4.0 
  └── path-is-absolute@1.0.1 

$ nvm use 8
Now using node v8.0.0 (npm v5.0.1)

$ npm install
up to date in 0.14s

$ git status -s
 M package-lock.json

# Ok try clean install instead..

$ rm -R node_modules/ && git checkout package-lock.json

$ npm install

$ git status -s
# no changes..
```
Here are the differences generated:
https://gist.github.com/danpoltawski/bb15ab8046bcddc55ad35f2e3eb07dd5

#### Further comments

We ([moodle/moodle](https://github.com/moodle/moodle)) want to ship locked version of our dev dependencies  so that developers can install them and get a consistent state. Ideally we would not be too picky about npm versions so it works as well as possible for as many contributors as possible which is reason for this issue.

**Comment by gnapse** [comment] 2017-06-01 19:49
I have this problem too.

**Comment by zkat** [comment] 2017-06-05 15:28
Closing as a duplicate of https://github.com/npm/npm/issues/16728

**Closed as completed by zkat** 2017-06-05 15:28 UTC
Labels: npm5
