### ISSUE TITLE
npm search

### ISSUE THREAD

**Issue by olartewashere** [npm/npm#13769] opened 2016-08-25 14:36 UTC
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

here is the .log file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'search' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose config Skipping project config: /Users/luisolartegervacio/.npmrc. (matches userconfig)
5 verbose stack Error: search must be called with arguments
5 verbose stack     at EventEmitter.search (/usr/local/lib/node_modules/npm/lib/search.js:57:15)
5 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:124:13)
5 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:73:30)
5 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:67:7)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
6 verbose cwd /Users/luisolartegervacio
7 error Darwin 14.5.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "search"
9 error node v6.4.0
10 error npm  v3.10.3
11 error search must be called with arguments
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment] 2016-08-25 15:33
@olartewashere Could you explain what is the issue here? The log shows that you are running
`npm install-test` in a directory that does not have a `package.json`. As such, `npm` correctly throws the error that such file was not found, since a `package.json` is necessary for a) running `npm install` with no arguments and b) running `npm test`.

**Comment by legodude17** [comment] 2016-08-25 17:19
@KenanY, already responded but why does the title say "npm search" but in the log file you ran `npm install-test`.

**Comment by boxxxie** [comment] 2016-08-25 20:27
i'll add to this.

```
npm search assert                                          16:20:36
npm WARN Building the local index for the first time, please be patient
[..................] | : WARN Building the local index for the first time, please be patient
<--- Last few GCs --->

  171560 ms: Mark-sweep 926.8 (1359.8) -> 901.4 (1333.1) MB, 731.2 / 0 ms [allocation failure] [GC in old space requested].
  172344 ms: Mark-sweep 901.4 (1333.1) -> 901.3 (1331.1) MB, 783.9 / 0 ms [allocation failure] [GC in old space requested].
  173126 ms: Mark-sweep 901.3 (1331.1) -> 901.3 (1324.1) MB, 781.4 / 0 ms [last resort gc].
  173891 ms: Mark-sweep 901.3 (1324.1) -> 901.2 (1317.1) MB, 765.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2fab271c9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x117bbdb11b0] (this=0x2fab27104189 <undefined>,string=0xa3b9714c589 <Very long string[194181677]>,encoding=0x2fab271d7a21 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x117bbd7e8f6] (this=0x113ac77ffe49 <JS Function Buffer (SharedFunctionInfo 0x2fab271e32d1)>,value=0xa3b9714c589 <Very long string[194181677]>,encodingOrOffset=0x2fab271d...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [npm]
 2: 0xfb1c8c [npm]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [npm]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
13: 0x9d5b0b [npm]
14: 0x9d60b1 [npm]
15: 0x117bb70961b
fish: “npm search assert” terminated by signal SIGABRT (Abort)
```

**Comment by KenanY** [comment] 2016-08-25 21:42
@olartewashere I see you edited your post. Next time, post a comment saying so that I am notified of the change. Is there any particular reason why you would like to run `npm search` with no arguments?

@boxxxie `npm search` is currently not in a working state because of how big the registry has become. There are open tickets already (https://github.com/npm/npm/issues/12619)  which discuss this and a pull request (https://github.com/npm/npm/pull/13746) which should help a bit. Nevertheless, your comment appears to be unrelated to this ticket.

**Comment by othiym23** [comment] 2016-08-29 21:29
Responding only to the original issue, because the rest is stuff best handled elsewhere, as @KenanY said.

```
11 error search must be called with arguments
```

As the error message above indicates, `npm search` on its own doesn't return any results, because the only reasonably intuitive thing it could do in that case is enumerate every package on the registry, which is unlikely to be illuminating now that there are 330k+ packages on the registry. As such, we landed a patch a year or so ago to return this message when `npm search` is invoked with no parameters. As this behavior is by design, I'm going to close this issue. For the rest of you, a fix to search is coming soon that will address the out of memory errors; check one of the other issues linked to by Kenan for details. Thanks to all for your time!

**Closed by othiym23** 2016-08-29 21:29 UTC
Labels: search, support

**Comment by wtsiamruk** [comment] 2017-01-14 11:18
@KenanY can you give me a link or explain by yourself how to create and set package.json file. What must be inside? or i need a simple empty file? (sorry about my English, just start studying it)

**Comment by KenanY** [comment] 2017-01-14 16:10
@wtsiamruk Check out <https://docs.npmjs.com/getting-started/using-a-package.json> :)

**Comment by wtsiamruk** [comment] 2017-01-15 14:44
@KenanY thanks
