### ISSUE TITLE
Is it normal that npm errors are so verbose?

### ISSUE THREAD

**Issue by testerez** [npm/npm#12910] opened 2016-05-31 14:48 UTC
Every time I get an error with npm, It prints about 20 lines of useless Darwin error. For example, if I run `eslint` with `npm run lint` and it detects lint errors, I get this:
```
/Users/testerez/projects/test/webpack.config.js
  11:7  error  'modules' is defined but never used  no-unused-vars

✖ 1 problem (1 errors, 0 warnings)


npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/testerez/.nvm/versions/node/v4.4.2/bin/node" "/Users/testerez/.nvm/versions/node/v4.4.2/bin/npm" "run" "lint"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 lint: `eslint . --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 lint script 'eslint . --fix'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint . --fix
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/testerez/projects/test/npm-debug.log
```

I lived with it for months now but I found it noisy and I'm wondering if it's the expected behavior.

running:
node v4.4.2 installed with nvm
npm 3.8.5
on OSX el Capitan

_I originally posted this question [on stackoverflow](http://stackoverflow.com/questions/37495101/is-it-normal-that-npm-errors-are-so-verbose)_

**Comment by KenanY** [comment] 2016-05-31 15:16
@testerez Yeah this is intended behavior. You can use the `--silent`/`-s` flag to silence that output.

**Comment by KenanY** [comment] 2016-06-07 18:18
@testerez It has been a week now with no response from you... has your question been sufficiently answered?

**Comment by testerez** [comment] 2016-06-07 18:20
IMO the default output is too verbose but I can leave with it :)

**Comment by KenanY** [comment] 2016-06-07 18:30
@testerez Here you go then :) https://github.com/npm/npm/issues/5452

**Comment by KenanY** [comment] 2016-06-28 19:55
Closing in favor of https://github.com/npm/npm/issues/5452.

**Closed by KenanY** 2016-06-28 19:55 UTC
Labels: lifecycle, support
