### ISSUE TITLE
I can't use npm to install Yeoman : ERR- this package has been reintegrated into npm and is now out of date with respect to npm

### ISSUE THREAD

**Issue by lisafra** [npm/npm#14100] opened 2016-09-28 01:48 UTC
#### I'm opening this issue because:

I can't use npm to install Yeoman, npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

#### What's going wrong?

when I input ' npm install -g yo ' , that wrong I mentioned  above occurred, what should I do ?

#### How can the CLI team reproduce the problem?

there is debug.log:

19097 verbose stack TypeError: uid must be an unsigned int
19097 verbose stack     at TypeError (native)
19097 verbose stack     at Object.fs.chown (fs.js:1184:11)
19097 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
19097 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19097 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19097 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
19097 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
19097 verbose stack     at FSReqWrap.oncomplete (fs.js:117:15)
19098 verbose cwd /Users/Yulia
19099 error Darwin 15.6.0
19100 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
19101 error node v6.2.0
19102 error npm  v3.10.8
19103 error uid must be an unsigned int
19104 error If you need help, you may report this error at:
19104 error     <https://github.com/npm/npm/issues>
19105 verbose exit [ 1, true ]
 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-09-28 11:40
@lisafra I think the warning is something you can safely ignore. This is your real error:

```
19103 error uid must be an unsigned int
```

which is a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-09-28 11:40 UTC
Labels: support
