### ISSUE TITLE
error when trying to install cli-color package and any other packages using npm install (package name)

### ISSUE THREAD

**Issue by Speneto** [npm/npm#12437] opened 2016-04-22 06:28 UTC
I got this error when trying to install cli-color package and any other packages using npm install (package name)

```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\memoizee\-\memoizee-0.3.10.tgz.639004961' -> 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\memoizee\-\memoizee-0.3.10.tgz'
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cli-color"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\next-tick\-\next-tick-0.2.2.tgz.3573450220' -> 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\next-tick\-\next-tick-0.2.2.tgz'
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cli-color"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\es6-symbol\-\es6-symbol-3.0.2.tgz.1450446164' -> 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\es6-symbol\-\es6-symbol-3.0.2.tgz'
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cli-color"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
cli-color@1.1.0 node_modules\cli-color
├── ansi-regex@2.0.0
├── d@0.1.1
├── timers-ext@0.1.0 (next-tick@0.2.2)
├── es5-ext@0.10.11 (es6-symbol@3.0.2)
├── es6-iterator@2.0.0 (es6-symbol@3.0.2)
└── memoizee@0.3.10 (next-tick@0.2.2, lru-queue@0.1.0, event-emitter@0.3.4, es6-weak-map@0.1.4)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cli-color"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DAVID\Desktop\Sample\npm-debug.log
```

**Comment by luongs3** [comment] 2016-05-06 09:19
i have the same problem, any solution please

**Comment by vamsikrishnamannem** [comment] 2016-06-10 20:38
I got same issue when I try to install npm in global.

**Comment by raspberry101** [comment] 2016-06-15 20:50
I got the same issue when I tried npm install any_package, mongoose concretely

**Comment by IsuruCham** [comment] 2016-06-22 10:42
Seriously, this error is everywhere, I cannot update npm itself and cannot install any node module through npm. Please guys, this is a serious issue. Please take a look.

**Comment by othiym23** [comment] 2016-08-19 22:00
```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\memoizee\-\memoizee-0.3.10.tgz.639004961' -> 'C:\Users\DAVID\AppData\Local\Temp\npm-6096-3486b7a0\registry.npmjs.org\memoizee\-\memoizee-0.3.10.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:00 UTC
Labels: bug, error-handling, support, ux, windows
