### ISSUE TITLE
URL of my app doesn t work and i don t know why or how i could fix it........ https://github.com/npm/npm/issues

### ISSUE THREAD

**Issue by yehia67** [npm/npm#15927] opened 2017-03-02 17:58 UTC
so sorry wrong link ...   https://desolate-lowlands-64937.herokuapp.com/

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-03-02 18:04
Duplicate of #15926.

**Comment by KenanY** [comment] 2017-03-02 18:09
Closing as a duplicate.

**Closed by KenanY** 2017-03-02 18:09 UTC
