### ISSUE TITLE
Pre-publish runs before install

### ISSUE THREAD

**Issue by andrewshawcare** [npm/npm#9238] opened 2015-08-11 15:34 UTC
Setup: `npm install`
Expected behaviour: Run `npm preinstall`, `npm install`, `npm postinstall` scripts
Actual behaviour: Runs `npm prepublish` script

**Comment by KenanY** [comment] 2015-08-11 20:47
Duplicate of https://github.com/npm/npm/issues/3059, https://github.com/npm/npm/issues/5000?

**Comment by othiym23** [comment] 2015-08-11 21:59
Indeed. @andersjanmyr, this is definitely something we've been discussing a bunch on both of the issues @KenanY mentions, so I'm going to close this issue as a duplicate of #5000. Check out #3059 and #5000 if you want to understand why this happens the way it does, why it's tough to change, and how we might make things less confusing.

**Closed by othiym23** 2015-08-11 21:59 UTC

**Comment by andrewshawcare** [comment] 2015-08-12 18:20
@othiym23 Thanks for your feedback. Reading the issues it looks like the main thread is #3059 but is locked for conversation? Is there any reason why?

**Comment by othiym23** [comment] 2015-08-12 18:55
The issue had been closed since 2013 and so pretty much the entire discussion was a dead letter. We're still figuring out the best way to solve the underlying problem, but having that discussion on an issue that's been closed since basically the beginning is unproductive.
