### ISSUE TITLE
npm documentation doesn't mention prepare script

### ISSUE THREAD

**Issue by AgentME** [npm/npm#15226] opened 2016-12-15 02:26 UTC
https://docs.npmjs.com/misc/scripts mentions the partly-deprecated prepublish script without mentioning prepare.

**Comment by zkat** [comment] 2016-12-15 05:08
Closing as a duplicate of https://github.com/npm/docs/issues/636 -- we're having some issues with syncing the npm repo with the site. You can see that https://github.com/npm/npm/blob/latest/doc/misc/npm-scripts.md has already been updated. Thanks for the reminder, though!

**Closed by zkat** 2016-12-15 05:08 UTC
Labels: documentation

**Comment by pke** [comment] 2017-02-13 15:55
This docs page is still not updated. I just ran into this when updating to npm 4.3.0 and having a "prepare" command in my package.json that I used in ancient times.

**Comment by bfreis** [comment] 2017-03-23 02:26
We're approaching the end of March 2017 (ie, over 3 months), and the documentation page is still not updated... seriously?
