### ISSUE TITLE
npm install angular2 fails with npm -v 3.3.6 on Mac

### ISSUE THREAD

**Issue by StephenC16** [npm/npm#10456] opened 2015-11-18 17:13 UTC
npm-debug.log Logfile is attached...

Angular support team says the problem is not using a current version of npm...

It references missing dependency: @reactivex/rxjs .

[npm-debug.txt](https://github.com/npm/npm/files/38107/npm-debug.txt)

**Comment by imyejin** [comment] 2015-11-18 17:13
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <[npm] npm install angular2 fails with npm -v 3.3.6 on Mac (#10456)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by iarna** [comment] 2015-11-18 19:21
This is due to a bug in node's installer, where it doesn't remove the old npm before installing the new one, which results in a broken npm installation. The easiest way to work around this is to remove the version installed by node:

```
rm -rf /usr/local/lib/node_modules/npm
```

And then reinstall the node 5 package.

**Comment by StephenC16** [comment] 2015-11-18 19:59
Brilliant! That did it. Thanks!!

**Comment by othiym23** [comment] 2015-11-18 20:09
Closing as resolved (and also a duplicate of #10434). It would be super nice to get this fixed at some point, but that's going to have to happen over in Node-land.

**Closed by othiym23** 2015-11-18 20:09 UTC
Labels: node-bug
