### ISSUE TITLE
npm pack doesn't bundle scoped bundledDependencies

### ISSUE THREAD

**Issue by falsecz** [npm/npm#8614] opened 2015-06-19 14:23 UTC
test package.json
```json 
{
  "name": "npm-bundle-test",
  "version": "1.0.0",
  "dependencies": {
    "@myscope/debug": "*"
  },
  "bundledDependencies": [
    "@myscope/debug"
  ]
}
```

`npm install` creates `node_modules/@myscope/debug/`, but `npm pack` ignore all scoped bundled dependencies 

```sh
# tar -tvf npm-bundle-test-1.0.0.tgz`
-rw-r--r-- 501/20          152 2015-06-19 16:09 package/package.json
```

It probably does not work because scoped modules are in @*scope* subdirectory.

**Comment by steve-jansen** [comment] 2015-07-09 22:54
+1 on npm 2.9.0

**Comment by steve-jansen** [comment] 2015-07-10 14:05
I may be hunting the wrong rabbit... any chance this is related: ["not some old 0.x style bundle with a @" in lib/build.js](https://github.com/npm/npm/blob/master/lib/build.js#L171)

```
return !file.match(/^[\._-]/) &&
          // not some old 0.x style bundle
          file.indexOf('@') === -1 &&
          // either not a dep, or explicitly bundled
          (deps.indexOf(file) === -1 || bundles.indexOf(file) !== -1)
```

**Comment by sam-github** [comment] 2015-07-20 18:33
@steve-jansen `+1` means this is fixed on npm 2.9, or still present on 2.9?

**Comment by MiniGod** [comment] 2015-07-29 10:33
@sam-github I believe he means it is still present on `2.9.0`.
In fact, the bug is still present in `2.13.2`.

**Comment by othiym23** [comment] 2015-08-24 22:52
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by aleung** [comment] 2015-12-11 05:39
Duplicate of #9175

**Comment by forivall** [comment] 2016-07-20 01:50
I fixed it: fstream-npm#22. ping @othiym23 @zkat @iarna ❤️

**Closed** 2016-08-02 18:48 UTC
Labels: big-bug, bug, scopes

**Comment by timche** [comment] 2016-10-10 16:01
@forivall @othiym23 @zkat @iarna I'm using `3.10.8` and it looks like this issue hasn't been fixed with 29cf56d #8614. I've downgraded to `3.10.7` as well, but no difference.

Related issue with @flekmatik confirming it: https://github.com/npm/npm/issues/9175

**Comment by timche** [comment] 2016-10-10 16:29
Nvm, it has been fixed, but the reason why it's not working for me is because my scoped package is a symlink. Nevertheless, non-scoped packages that are symlinked are being packed correctly. So it looks like symlinked scoped packages are not being treated correctly.

**Comment by forivall** [comment] 2016-10-11 17:01
@timche Was it created with [`linklocal`](https://github.com/timoxley/linklocal)? I'd like to be able to create a replicable test case.

**Comment by timche** [comment] 2016-10-11 22:30
@forivall The symlink was created with [Lerna](https://github.com/lerna/lerna), but it shouldn't make any difference if the scoped package is a normal symlink. Thanks for helping.

**Comment by forivall** [comment] 2016-10-12 00:46
**offtopic** @timche ah, I didn't consider lerna since my project that uses it is still on an older version that uses the "proxy" files. Which wouldn't work, unless you used [`pplink --relative`](https://github.com/forivall/pplink)
