### ISSUE TITLE
shasum check failed when npm install

### ISSUE THREAD

**Issue by Cueroqu** [npm/npm#10867] opened 2015-12-17 13:22 UTC
I ran 'npm install' and got below error information

loadDevDep:vinyl-paths →  ...
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/_r/sy32z6hd32g9m6n_c0rc_bxnb37rcb/T/npm-9771-bcae3a1c/registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz
npm ERR! Expected: 03726561bc268f2e5444f54c665b7fd4a8c029e2
npm ERR! Actual:   78904ad6ed36678d8cd2e8c438c497386140851d
npm ERR! From:     https://registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../Documents/codes/npm-debug.log

It still failed ever after I ran 'npm cache clean'.

How can I avoid this error?

**Comment by dannyphung** [comment] 2015-12-18 06:55
+1 on centos 6.5 
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.0

**Comment by zkat** [comment] 2016-12-09 00:49
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:49 UTC
