### ISSUE TITLE
npm ERR! shasum check failed

### ISSUE THREAD

**Issue by jami4n** [npm/npm#9559] opened 2015-09-12 03:19 UTC
i'm trying to install cordova but i cant seem to work around this issue. Please help

C:\Users\User\AppData\Roaming\npm>npm install -g cordova
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for C:\Users\User\AppData\Local\Temp\npm-3544-2597a8
bc\registry.npmjs.org\cordova-app-hello-world-\cordova-app-hello-world-3.9.0.tg
z
npm ERR! Expected: 5866d8fed5582686c68ec59a6d1097c4ec0fcc4b
npm ERR! Actual:   665b81c63bb4679db32e5e11cc8f74af801b819a
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-
app-hello-world-3.9.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\AppData\Roaming\npm\npm-debug.log

**Comment by KenanY** [comment] 2015-09-12 03:45
@jami4n Have you tried `npm cache clear`?

**Comment by balupton** [comment] 2015-09-12 18:22
been getting this a lot the past week, especially in the last hour

**Comment by balupton** [comment] 2015-09-12 18:30
Switching to the chinese mirror has worked: `npm set registry http://r.cnpmjs.org/`

**Comment by zaggino** [comment] 2015-09-14 01:15
using npm `2.14.4`:
```
C:\Windows\system32>npm install -g mocha
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mocha"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.4

npm ERR! shasum check failed for C:\Users\Zaggi\AppData\Local\Temp\npm-5452-092674ab\registry.npmjs.org\escape-string-regexp\-\escape-string-regexp-1.0.2.tgz
npm ERR! Expected: 4dbc2fe674e71949caf3fb2695ce7f2dc1d9a8d1
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

C:\Windows\system32>npm get registry
https://registry.npmjs.org/

C:\Windows\system32>tracert registry.npmjs.org

Tracing route to a.sni.fastly.net [103.245.222.162]
over a maximum of 30 hops:

  1     1 ms     1 ms     1 ms  10.100.0.1
  2     3 ms     3 ms     3 ms  180.148.79.17.static.amnet.net.au [180.148.79.17]
  3     2 ms     2 ms     2 ms  te3-2.600-br02.nsw.amcom.net.au [180.148.64.5]
  4     3 ms     2 ms     2 ms  te3-2.cr02.nsw.amcom.net.au [180.148.64.118]
  5     4 ms     7 ms     3 ms  as4826.nsw.ix.asn.au [218.100.52.6]
  6     3 ms     3 ms     3 ms  bundle-100.cor03.syd03.nsw.VOCUS.net.au [114.31.192.44]
  7     5 ms     2 ms     2 ms  ten-1-1-0.bdr03.syd03.nsw.VOCUS.net.au [175.45.72.116]
  8     *        *        *     Request timed out.
  9     3 ms     4 ms     2 ms  103.245.222.162
```

now, when I download the file manually and check the hash, it has the hash of `4dbc2fe674e71949caf3fb2695ce7f2dc1d9a8d1` which is expected and not the hash of `da39a3ee5e6b4b0d3255bfef95601890afd80709` which npm claims is actual.

furthermore, when I try to install another package, npm claims again that the actual hash is again `da39a3ee5e6b4b0d3255bfef95601890afd80709`.

switching to `http://r.cnpmjs.org/` indeed solves this.

**Comment by koresar** [comment] 2015-09-14 02:50
The proper workaround is here: https://github.com/npm/npm/issues/9574#issuecomment-139940172

**Comment by jakemdunn** [comment] 2015-09-16 16:25
Still seeing this issue on my end, and the workaround from @koresar didn't work for me, unfortunately. Thankfully, the Chinese mirror still did the trick!

**Comment by tancolo** [comment] 2015-09-21 03:22
Hi guys， I'm also getting into this trouble. But I resolved it using Administrator cmd.
I'm in china, my OS is WIN10 Win 64.
=============Before==============
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>npm set registry http://r.cnpmjs.org/

C:\Users\Administrator>npm -g install cordova
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.0","npm":"2.14.3"})
C:\Users\Administrator\AppData\Roaming\npm\cordova -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\bin\cordova
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install"
 "cordova"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code EIO
npm ERR! errno EIO
npm ERR! syscall write

npm ERR! write EIO
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

======AND I execute npm cache clear===============
C:\Users\Administrator>npm cache clear
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "cache" "clear
"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! path C:\Users\Administrator\AppData\Roaming\npm-cache
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rmdir

npm ERR! Error: EPERM: operation not permitted, rmdir 'C:\Users\Administrator\AppData\Roaming\npm-cache'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rmdir 'C:\Users\Administrator\AppData\Roaming\npm-cache']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm-cache' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

C:\Users\Administrator>

============AFTER==========
1) open cmd usring Administator. 

Microsoft Windows [版本 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

# ===========>step  2 
C:\WINDOWS\system32>npm cache clear

# ===========>step  3
C:\WINDOWS\system32>npm set registry http://r.cnpmjs.org/

# ===========>step  4 npm -g install cordova

C:\WINDOWS\system32>npm -g install cordova
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"4.1.0","npm":"2.14.3"})
C:\Users\Administrator\AppData\Roaming\npm\cordova -> C:\Users\Administrator\App
Data\Roaming\npm\node_modules\cordova\bin\cordova
cordova@5.3.1 C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.7)
└── cordova-lib@5.3.1 (valid-identifier@0.0.1, unorm@1.3.3, osenv@0.1.0, prop
erties-parser@0.2.3, bplist-parser@0.0.6, semver@4.3.6, dep-graph@1.1.0, shelljs
@0.3.0, rc@0.5.2, xcode@0.8.0, elementtree@0.1.6, glob@4.0.6, npmconf@2.1.2, cor
dova-serve@0.1.3, request@2.47.0, init-package-json@1.9.1, tar@1.0.2, aliasify@1
.7.2, cordova-registry-mapper@1.1.11, cordova-app-hello-world@3.9.0, plist@1.1.0
, cordova-js@4.1.1, npm@2.14.5)

C:\WINDOWS\system32>

**Comment by koresar** [comment] 2015-09-21 03:30
@tancolo this is completely different issue mate.
You have installed npm as Administrator, so some folders/files were created with Admin only access.

Either do not install npm ass admin, or always use admin permissions when executing npm.

**Comment by tancolo** [comment] 2015-09-21 03:42
@koresar  Oh, really?  ,,, Sorry,  I just see the question of  @jami4n, and I resolved it with that method.
I hope my solution is useful to @jami4n .

**Comment by koresar** [comment] 2015-09-21 03:44
I believe you have resolved it because of Admin command line.
If you revert the workaround and try ordinary `npm -g install cordova` but with the Admin priviledges it would also work.

**Comment by balupton** [comment] 2015-09-21 05:13
My issues were resolved when npm fixed their Australian mirror.

**Comment by june-jianglan** [comment] 2016-10-21 10:20
try to install cordova-app-hello-world-3.9.0.tg. Download it and npm install xxx. I come across similar question, and now it is solved.

**Comment by zkat** [comment] 2016-12-09 00:54
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:54 UTC
Labels: shasum, support
