### ISSUE TITLE
Npm crashes on Windows on command window resize

### ISSUE THREAD

**Issue by b1rdex** [npm/npm#13184] opened 2016-06-27 01:11 UTC
### I'm opening this issue because:

  - [x] npm is crashing
  - [ ] npm is producing an incorrect install
  - [ ] npm is doing something I don't understand
  - [ ] other (_see below for feature requests_)

#### Node version:
v5.2.0

#### npm version:
3.3.12

#### How did you install Node and npm?
installer

#### Operating system version and distribution:
Windows 10

#### What problem are you seeing?
```
C:\>npm -v
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed.
    at WriteStream.Socket._writeGeneric (net.js:641:19)
    at WriteStream.Socket._write (net.js:695:8)
    at doWrite (_stream_writable.js:293:12)
    at writeOrBuffer (_stream_writable.js:279:5)
    at WriteStream.Writable.write (_stream_writable.js:208:11)
    at WriteStream.Socket.write (net.js:619:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
 3.3.12
```
#### How can the problem be reproduced?
1. Npm install something
2. Resize command window when you see progress bar
3. Npm crashes and starts to work only in new command window

There is no npm-debug.log in folder I did `npm install` finished with error.

**Comment by b1rdex** [comment] 2016-06-27 01:15
Updated npm to `3.10.2` with `npm install -g npm`. Oh, new progress indicator. But it still crahses on window resize.

```
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed.
    at WriteStream.Socket._writeGeneric (net.js:641:19)
    at WriteStream.Socket._write (net.js:695:8)
    at doWrite (_stream_writable.js:293:12)
    at writeOrBuffer (_stream_writable.js:279:5)
    at WriteStream.Writable.write (_stream_writable.js:208:11)
    at WriteStream.Socket.write (net.js:619:40)
    at EventEmitter.log.write (C:\Users\Anatoly\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js:263:10)
    at EventEmitter.<anonymous> (C:\Users\Anatoly\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js:226:12)
    at Array.forEach (native)
    at EventEmitter.log.emitLog (C:\Users\Anatoly\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js:224:28)

**Comment by KenanY** [comment] 2016-06-27 01:31
Looks like a duplicate of https://github.com/npm/npm/issues/12887.

**Closed** 2016-06-27 01:34 UTC
