### ISSUE TITLE
npm install --save socket.io ERROR in Ubuntu 14.04

### ISSUE THREAD

**Issue by vivistoc** [npm/npm#7027] opened 2014-12-29 04:07 UTC
I am trying to follow the chat example from http://socket.io/get-started/chat/  and get the following error when I try "npm install --save socket.io". Previous steps in the example works fine. I am running Ubuntu 14.04.1 LTS 64bit. Please let me know how to resolve this.
```
make: Leaving directory `/home/vivek/projects/socket/test/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "socket.io"
npm ERR! node v0.10.28
npm ERR! npm  v2.1.16

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vivek/projects/socket/test/npm-debug.log
```

**Comment by othiym23** [comment] 2015-01-08 18:31
Closing this as a duplicate of #7070, but this is a legitimate issue that I unfortunately lack adequate information to resolve. Please keep an eye on that issue for a resolution.

**Closed by othiym23** 2015-01-08 18:31 UTC
