### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by duzy** [npm/npm#10679] opened 2015-12-03 14:38 UTC
Got the following errors while running "sudo npm install -g babelify babel-preset-react".

```
npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "babelify" "babel-preset-react"
npm ERR! node v6.0.0-pre
npm ERR! npm  v3.3.12

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /open/npm-debug.log
```

**Comment by fastest963** [comment] 2015-12-03 19:34
Related to #9224, #9953, #10430, #10228, #10536

**Comment by othiym23** [comment] 2015-12-17 00:11
Closing as a duplicate of #9953.

**Closed by othiym23** 2015-12-17 00:11 UTC
