### ISSUE TITLE
Can't seem to install babel...

### ISSUE THREAD

**Issue by rscharfer** [npm/npm#10333] opened 2015-11-10 18:07 UTC
I would like node to be able to read arrow functions in my js files.

I was told I need to "npm install -g babel".  The seemed to work OK.  I then tried to run my script "babel-node myscript.js", and instead of reading what I console.log in the script, I got "the CLI has been moved into the package 'babel-cli'".  I then "npm install -g babel-cli" as it suggested and I received a large amount of errors and node still cannot read my arrow functions...  I will like to add my debug file here somewhere, but I am not sure how...

**Comment by KenanY** [comment] 2015-11-11 20:03
@rscharfer You can upload the `npm-debug.log` file to [gist.github.com](https://gist.github.com/) and post the link here.

**Comment by rscharfer** [comment] 2015-11-12 07:31
Thank you.  Already something new learned.  : ) 

Here is the link to my npm-debug.log file:  https://gist.github.com/rscharfer/7494fa07b9870cb628c0

**Comment by rscharfer** [comment] 2015-11-20 09:34
Hi KenanY,

do you have any ideas as to what my be the problem?  I tried completing reinstalling node.js this morning, and I still have the same issue trying to install babel-cli.

**Comment by KenanY** [comment] 2015-11-20 12:36
@rscharfer Looks like an issue with your internet connection. Maybe there is a proxy or firewall in the way?

**Comment by rscharfer** [comment] 2015-11-20 14:24
Weird.Ok, thanks.  That might be due to some configuration on my router I guess.   What line of the debug.log tells you there is an issue with my internet connection?  Maybe I could Google around some more and fix the problem with my router (if that's it).

**Comment by KenanY** [comment] 2015-11-20 15:38
@rscharfer Last few lines:

```
24219 error Windows_NT 6.1.7601
24220 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "babel-cli"
24221 error node v0.12.7
24222 error npm  v2.11.3
24223 error code ECONNRESET
24224 error errno ECONNRESET
24225 error syscall read
24226 error network read ECONNRESET
24226 error network This is most likely not a problem with npm itself
24226 error network and is related to network connectivity.
24226 error network In most cases you are behind a proxy or have bad network settings.
24226 error network
24226 error network If you are behind a proxy, please make sure that the
24226 error network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by vickenliu** [comment] 2016-03-04 10:27
any one can have a look of my error plz, i could not install the babel-cli anyway, i have installed node.js. 
the link is https://gist.github.com/vickenliu/68bfe3471986a230b7d2

**Comment by KenanY** [comment] 2016-03-04 13:40
@vickenliu Your error looks unrelated to that of @rscharfer. To me, it looks like you need to run that command with `sudo` since you do not have permission to modify `/usr/local/`.

**Comment by vickenliu** [comment] 2016-03-04 21:11
@KenanY  thank you so much, it works...

**Comment by KenanY** [comment] 2016-06-28 21:03
Closing as resolved.

**Closed by KenanY** 2016-06-28 21:03 UTC
Labels: support

**Comment by KenanY** [comment] 2016-06-28 21:04
Well, @rscharfer's issue was never confirmed to be resolved but it is an issue with their internet connection and not with `npm`. Can reopen if this is not the case.
