### ISSUE TITLE
Install issues globally for angular-cli

### ISSUE THREAD

**Issue by Uvii** [npm/npm#14637] opened 2016-11-16 04:32 UTC
npm install -g angular-cli

error as follows : 

<details><pre>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SDYKS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for C:\Users\SDYKS\AppData\Local\Temp\npm-920-4fa44464\registry.npmjs.org\_40ngtools\webpack\-\webpack-1.1.7.tgz
npm ERR! Expected: 350539194286f13f01682ba07ee4243ce20f7e17
npm ERR! Actual:   ae77098f3a1ba0790e8a78be989d9053ca5d460e
npm ERR! From:     https://registry.npmjs.org/@ngtools/webpack/-/webpack-1.1.7.tgz
npm ERR!

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SDYKS\npm-debug.log
</pre></details>

I tried to install a debug file using $ npm install debug 

it generates an error as 

$ is not recognized as an internal or external command, operable program 

How to start with Angular2??? kindly help me out

Thanks in prior.

**Comment by KenanY** [comment] 2016-11-16 11:29
@Uvii Have you already tried running `npm cache clean`?

**Comment by Uvii** [comment] 2016-11-16 11:52
No, didn't I tried it cleaning cache. I need some help on working those.

On 16-Nov-2016 16:59, "Kenan Yildirim" <notifications@github.com> wrote:

@Uvii <https://github.com/Uvii> Have you already tried running npm cache
clean?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/14637#issuecomment-260923236>, or mute
the thread

**Comment by legodude17** [comment] 2016-11-16 18:10
What do you mean?

**Comment by Uvii** [comment] 2016-11-17 02:20
How to overcome those issues and wt's d way to run angular 2 project
without errors.

We can't install node modules for each and every project separately right.
So that how to install it globally without these errors. I tried to install
globally using
npm install  -g angular-cli

but it's not working. How to clear entire cache of system for npm then
again I want to install it. Else is there any other process to do it.

**Comment by KenanY** [comment] 2016-11-17 03:57
@Uvii Did you try running the command `npm cache clean` from your command-line?

**Comment by KenanY** [comment] 2016-11-25 20:06
Not gonna close this as abandoned just yet, since @Uvii opened https://github.com/npm/npm/issues/15030 instead of continuing the conversation here.

**Comment by Uvii** [comment] 2016-11-27 09:26
Yes, I tried on cleaning cache still I can't able to run my project. I'm
facing same problem.

On 26-Nov-2016 01:36, "Kenan Yildirim" <notifications@github.com> wrote:

Not gonna close this as abandoned just yet, since @Uvii
<https://github.com/Uvii> opened #15030
<https://github.com/npm/npm/issues/15030> instead of continuing the
conversation here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/14637#issuecomment-263017420>, or mute
the thread

**Comment by zkat** [comment] 2016-12-09 00:32
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:32 UTC
Labels: network, support
