### ISSUE TITLE
Errors installing "npm install -g  angular-cli"

### ISSUE THREAD

**Issue by tdiatgithub** [npm/npm#14319] opened 2016-10-18 13:39 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I try to install angular-cli by runing
     npm install -g  angular-cli
and just get errors

I tried to uninstall and reinstall but that doesn't help.
I looked through all kinds of post but couldn't find a solution.

That's my first reported issues so forgive me if i did something wrong ;-)

#### How can the CLI team reproduce the problem?

[https://gist.github.com/tdiatgithub/dca0b9a0f807edcc40b77da76fd785d8]

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v4.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X El Capitan Version 10.11.5
 - Network issues:
   - Geographic location where npm was run: Switzerland
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2016-10-18 22:30
Closing as duplicate of #13918 – either reinstalling Node and only using the distributed version of npm, downgrading to a Node.js LTS (which doesn't have this issue), or using npm no newer than npm@3.10.7 should all fix it. See the linked issue for details. Thanks for your time!

**Closed by zkat** 2016-10-18 22:30 UTC
Labels: support
