### ISSUE TITLE
Error in installing node-gyp

### ISSUE THREAD

**Issue by velvizhip** [npm/npm#10743] opened 2015-12-08 12:07 UTC
I tried installing node-gyp using 'sudo npm install -g node-gyp'.
node version - v4.2.2
npm - v2.14.7

I got the error like this:

```
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-gyp"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for /tmp/npm-13911-0bc7d4b5/registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR! Expected: 8e4d2a256c0e2185c6b18ad694aec968b83cb1d1
npm ERR! Actual:   f7ceb02fae8108dbd25be417b8db7f271f082159
npm ERR! From:     http://registry.npmjs.org/tar/-/tar-2.2.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/local/PAYODA/velvizhi.p/npm-debug.log
```

please help me.

**Comment by zkat** [comment] 2016-12-09 00:50
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:50 UTC
Labels: support
