### ISSUE TITLE
unable to update or run npm 

### ISSUE THREAD

**Issue by issacting93** [npm/npm#14680] opened 2016-11-21 06:50 UTC
#### I'm opening this issue because: 
  - [ ] npm is doing something I don't understand. 

####

I tried running node several times but consistently get this

<pre>
67 error Windows_NT 10.0.14393
68 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "latest-version"
69 error node v6.9.1
70 error npm  v3.10.8
71 error tarball.destroy is not a function
72 error If you need help, you may report this error at:
72 error     <https://github.com/npm/npm/issues>
</pre>

 

// debug log below 

<details>
<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'latest-version' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData latest-version
8 silly fetchNamedPackageData latest-version
9 silly mapToRegistry name latest-version
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'latest-version',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'latest-version',
12 silly mapToRegistry   name: 'latest-version',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/latest-version
14 verbose request uri https://registry.npmjs.org/latest-version
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:46:17 PM
17 verbose request id 72ffb5c59bcf6269
18 http request GET https://registry.npmjs.org/latest-version
19 http 200 https://registry.npmjs.org/latest-version
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Fri, 09 Oct 2015 20:22:20 GMT',
20 verbose headers   etag: 'W/"561821fc-27c9"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '1760',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Mon, 21 Nov 2016 06:46:19 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '269',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-hkg6820-HKG',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '4',
20 verbose headers   'x-timer': 'S1479710779.081134,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Fri, 09 Oct 2015 20:22:20 GMT',
21 silly get     etag: 'W/"561821fc-27c9"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '1760',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Mon, 21 Nov 2016 06:46:19 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '269',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-hkg6820-HKG',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '4',
21 silly get     'x-timer': 'S1479710779.081134,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving latest-version to C:\Users\ZaC\AppData\Roaming\npm-cache\registry.npmjs.org\latest-version\.cache.json
23 verbose correctMkdir C:\Users\ZaC\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule latest-version@2.0.0 checking installable status
37 silly cache add args [ 'latest-version', null ]
38 verbose cache add spec latest-version
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'latest-version',
39 silly cache add   scope: null,
39 silly cache add   escapedName: 'latest-version',
39 silly cache add   name: 'latest-version',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: 'latest',
39 silly cache add   type: 'tag' }
40 silly addNamed latest-version@latest
41 verbose addNamed "latest" is being treated as a dist-tag for latest-version
42 info addNameTag [ 'latest-version', 'latest' ]
43 silly mapToRegistry name latest-version
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry data Result {
46 silly mapToRegistry   raw: 'latest-version',
46 silly mapToRegistry   scope: null,
46 silly mapToRegistry   escapedName: 'latest-version',
46 silly mapToRegistry   name: 'latest-version',
46 silly mapToRegistry   rawSpec: '',
46 silly mapToRegistry   spec: 'latest',
46 silly mapToRegistry   type: 'tag' }
47 silly mapToRegistry uri https://registry.npmjs.org/latest-version
48 verbose addNameTag registry:https://registry.npmjs.org/latest-version not in flight; fetching
49 verbose get https://registry.npmjs.org/latest-version not expired, no request
50 silly addNameTag next cb for latest-version with tag latest
51 silly addNamed latest-version@2.0.0
52 verbose addNamed "2.0.0" is a plain semver version for latest-version
53 silly mapToRegistry name latest-version
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry data Result {
56 silly mapToRegistry   raw: 'latest-version',
56 silly mapToRegistry   scope: null,
56 silly mapToRegistry   escapedName: 'latest-version',
56 silly mapToRegistry   name: 'latest-version',
56 silly mapToRegistry   rawSpec: '',
56 silly mapToRegistry   spec: 'latest',
56 silly mapToRegistry   type: 'tag' }
57 silly mapToRegistry uri https://registry.npmjs.org/latest-version
58 verbose addRemoteTarball https://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz',
59 verbose addRemoteTarball   '56f8d6139620847b8017f8f1f4d78e211324168b' ]
60 info retry fetch attempt 1 at 2:46:17 PM
61 info attempt registry request try #1 at 2:46:17 PM
62 http fetch GET https://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz
63 http fetch 200 https://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz
64 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\ZaC\AppData\Local\Temp\npm-12980-83914eb7\registry.npmjs.org\latest-version\-\latest-version-2.0.0.tgz.2536460881' -> 'C:\Users\ZaC\AppData\Local\Temp\npm-12980-83914eb7\registry.npmjs.org\latest-version\-\latest-version-2.0.0.tgz'
65 verbose stack TypeError: tarball.destroy is not a function
65 verbose stack     at WriteStreamAtomic.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-tarball.js:97:15)
65 verbose stack     at emitOne (events.js:101:20)
65 verbose stack     at WriteStreamAtomic.emit (events.js:188:7)
65 verbose stack     at WriteStreamAtomic.emit (C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:60:34)
65 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:89:19
65 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
66 verbose cwd C:\Users\ZaC\Desktop\angular-quickstart
67 error Windows_NT 10.0.14393
68 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "latest-version"
69 error node v6.9.1
70 error npm  v3.10.8
71 error tarball.destroy is not a function
72 error If you need help, you may report this error at:
72 error     <https://github.com/npm/npm/issues>
73 verbose exit [ 1, true ]
</pre>
</details>

**Comment by legodude17** [comment] 2016-11-29 01:22
Try updating npm. Also try npm cache clean.

**Comment by Charlotteis** [comment] 2016-11-29 19:49
Hey @issacting93, that sounds frustrating!

So, whilst upgrading npm is a good idea, you can't actually do that yet because it won't let you!
I've seen a lot of folk have the same problem with Windows, something is keeping the resources you need busy, so you can't do anything with npm.

It might sound a little strange, but do you have "ByteFence Anti-malware software" installed?
Several people have had your problem and solved it by uninstalling this piece of software, see https://github.com/npm/npm/issues/13537#issuecomment-256063866 for example.

I hope this fixes your problem, do let me know if it does ⭐️

**Comment by zkat** [comment] 2016-11-30 01:48
https://github.com/npm/npm/issues/14680#issuecomment-263678582 is almost certainly correct: Windows does not allow more than one program to access a file at the same time, and overeager antivirus software can suddenly start scanning a file that npm created in the staging area right before it moves it to its final destination in `node_modules`. The resulting error (`EBUSY` or `EPERM`), is often confusing. This issue has been at least somewhat mitigated by the latest `graceful-fs`, which is available as of `npm@4.0.2`, so you can upgrade to that version and it will likely stop happening altogether.

That said, there's a small bug here that's preventing the specific error from bubbling up correctly. The error handler itself is erroring. :) So that's why I've marked this as a bug. The resolution for you, @issacting93, is no different: upgrade, and if you keep seeing it happen, disable or uninstall your antivirus software while running npm.

**Comment by zkat** [comment] 2017-01-04 20:01
Closing as a duplicate of https://github.com/npm/npm/issues/8564

**Closed by zkat** 2017-01-04 20:01 UTC
Labels: bug, support, windows
