### ISSUE TITLE
ETIMEDOUT Not able install any package

### ISSUE THREAD

**Issue by pankajadhyapak** [npm/npm#10062] opened 2015-10-21 17:43 UTC
Hi i'm trying to install Gulp but not able to install . here is the error i got...i'm on OSX EL Capitan

sudo npm install --global gulp

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "gulp"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 103.245.222.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pankaj/Desktop/nodetest/npm-debug.log

**Comment by KenanY** [comment] 2015-10-21 17:54
@pankajadhyapak I'm basically reiterating what the error message says, but this is an issue with your internet connection. Are you behind a proxy or firewall?

**Comment by pankajadhyapak** [comment] 2015-10-21 17:59
@KenanY  No i guess 

npm config get proxy 
null

**Comment by KenanY** [comment] 2015-10-21 18:38
@pankajadhyapak I think there are websites for checking if your connection is behind a proxy, but I cannot vouch for any in particular so you will have to try a few out on your own after a search for them. The fault usually lies in workplace proxies/firewalls for many users here. Sometimes it's the firewall of your antivirus (is that a thing in OS X?). Regardless, something somewhere is messing with `npm`'s requests to the registry.

(Does `103.245.222.162:443` even map to `registry.npmjs.org`? I can't `curl` it...)

**Comment by niktrix** [comment] 2015-10-22 05:12
@pankajadhyapak did you find the solution, I also have same issue

**Comment by niktrix** [comment] 2015-10-22 05:13
engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 103.245.222.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by pankajadhyapak** [comment] 2015-10-22 07:10
@KenanY  This is my npm config list 

npm config ls -l    
      
; cli configs
long = true
user-agent = "npm/2.14.7 node/v4.2.1 darwin x64"

; userconfig /Users/pankaj/.npmrc
registry = "http://registry.npmjs.org/"
strict-ssl = false

; builtin config undefined
prefix = "/usr/local"

; default values
access = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "/Users/pankaj/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "/usr/local/etc/npmrc"
globalignorefile = "/usr/local/etc/npmignore"
group = 20
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/Users/pankaj/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "4.2.1"
npat = false
onload-script = null
optional = true
parseable = false
; prefix = "/usr/local/Cellar/node/4.2.1" (overridden)
production = false
proprietary-attribs = true
proxy = null
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "/bin/zsh"
shrinkwrap = true
sign-git-tag = false
spin = true
; strict-ssl = true (overridden)
tag = "latest"
tag-version-prefix = "v"
tmp = "/var/folders/_q/3b_vk3cx2glcw54mbk12xycm0000gn/T"
umask = 18
unicode = true
unsafe-perm = true
usage = false
user = 501
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/Users/pankaj/.npmrc"
version = false
versions = false
viewer = "man"

**Comment by pankajadhyapak** [comment] 2015-10-22 07:11
@KenanY  Do i need to change anything

**Comment by niktrix** [comment] 2015-10-22 09:54
@pankajadhyapak 

npm set strict-ssl false

**Comment by pankajadhyapak** [comment] 2015-10-22 13:58
@niktrix tried that but no luck and even tried setting registry still same error

**Comment by KenanY** [comment] 2015-10-22 14:41
@pankajadhyapak I don't know, the configurations look okay to me. Can you successfully `ping` that IP address?

**Comment by niktrix** [comment] 2015-10-22 17:06
i was having same problem, after changing router it is working for me, looks like something is blocking by router

**Comment by pankajadhyapak** [comment] 2015-10-25 17:19
@niktrix  thanks for the hint man ...problem with router firewall

**Comment by hyzhak** [comment] 2015-11-17 10:32
@niktrix got same error. And fix it by turning of firewall on router. Thanks for the hint!

**Comment by renatobenks** [comment] 2015-12-28 02:55
I'm having the same problem. My router is already off. And now? What I do? Haha I'm with problems, i need resolve then, please, anyone help me

**Comment by kirankaushik** [comment] 2016-04-15 05:22
Hi.I am trying to install node-mysql.this is the error that am getting.here is the error list.

 npm ERR! Windows_NT 5.1.2600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
node_modules\\npm\\bin\\npm-cli.js" "install" "mysql"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 103.245.222.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network set
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Program Files\nodejs\npm-debug.log

**Comment by skakkar** [comment] 2016-04-16 07:28
I was also facing similar issues. I followed below mentioned steps and it worked for me:

1. Windows>Start>Node.js>Run as a Administrator NodeJs Command Prompt

2. ping registry.npmjs.org
3. npm view npm version
4. cd %ProgramFiles%\nodejs
5. npm install npm@latest

and npm updated successfully. earlier I was trying for CMD and that was throwing error. may be some path issue that got resolved by running NodeJs Command Prompt. hope it'll work for you. try this.

**Closed** 2016-04-25 16:00 UTC
Labels: support

**Comment by khan789** [comment] 2016-05-18 00:09
I have above config exactly as @pankajadhyapak . but i forgot to delete the environment variable I added. 
Ok, This solved my problem. 
In windows I have Environment variable as NODE_ENV=production. I removed it and NPM started working again for me.

**Comment by baloda** [comment] 2016-06-05 08:50
@khan789  i am having same issues. i cleared all the proxy but yet it is showing the error.
I don't know from where this proxy 192.168.1.107:3128 is coming.  i removed all possible proxies in cmd.

connect ETIMEDOUT 192.168.1.107:3128
This is most likely not a problem with npm itself
and is related to network connectivity.

how can i solve this problem

i tried registry file setting, cache cleaning , proxy setting for git and npm still getting the same error

no installation is working using npm

**Comment by baloda** [comment] 2016-06-05 09:15
I solved this problem by setting the node_env. Although i don't know why it is causing the problem.

setx NODE_ENV development

**Comment by nishantkaushik74** [comment] 2018-03-03 06:21
I was going through the same error. the root cause was the proxy settings : there are several answers provided in here to reset the proxy but none of them worked for me.
below is the commands that solved my problem give them a try.

npm config rm proxy
npm config rm https-proxy

**Comment by Houssk** [comment] 2018-05-22 10:42
thanks @nishantkaushik74  it solve my problem

**Comment by nishantkaushik74** [comment] 2018-05-22 10:54
Happy to know that 😃😃

**Comment by anand-tiwari** [comment] 2018-06-11 08:22
i am getting same error i tried 
npm config rm proxy
npm config rm https-proxy

can anybody help??

@nishantkaushik74

**Comment by nishantkaushik74** [comment] 2018-06-11 08:52
Please remove or disable your firewall settings and then try same commands it should work.  Best of luck

**Comment by anand-tiwari** [comment] 2018-06-15 18:25
thanks @nishantkaushik74 it was network issue.
