### ISSUE TITLE
Error while installing npm

### ISSUE THREAD

**Issue by swetapatil** [npm/npm#12391] opened 2016-04-18 06:30 UTC
```
C:\Users\swetpati>npm install grunt grunt-cli bower -g
npm http GET http://registry.npmjs.org/grunt
npm http GET http://registry.npmjs.org/grunt-cli
npm http GET http://registry.npmjs.org/bower
npm http 304 http://registry.npmjs.org/grunt-cli
npm http 304 http://registry.npmjs.org/bower
npm http GET http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm http GET http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm http 200 http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! Error: shasum check failed for C:\Users\swetpati\AppData\Local\Temp\npm
-5520-mLaiOROQ\1460960593147-0.5624208080116659\tmp.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   af271342893ede79587a04de74fbdbb220d6db2a
npm ERR! From:     http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.
js:38:8
npm ERR!     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm
\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:919:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "grunt-cli" "bower" "
-g"
npm ERR! cwd C:\Users\swetpati
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm http 304 http://registry.npmjs.org/grunt
npm http 200 http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm http GET http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm http 200 http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\swetpati\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment] 2016-04-18 11:27
@swetapatil Have you tried running `npm cache clean`?

**Comment by swetapatil** [comment] 2016-04-19 02:41
Yes I tried running npm cache clean. But it didn't work.

**Comment by swetapatil** [comment] 2016-04-25 11:02
Can anyone please help here. I am getting this error


npm http GET http://registry.npmjs.org/grunt-cli
npm http GET http://registry.npmjs.org/grunt
npm http GET http://registry.npmjs.org/bower
npm http 407 http://registry.npmjs.org/grunt
npm ERR! registry error parsing json
npm http 407 http://registry.npmjs.org/bower
npm ERR! registry error parsing json
npm http GET http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm http GET http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm http 407 http://registry.npmjs.org/grunt-cli
npm ERR! registry error parsing json
npm http GET http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm http 407 http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! fetch failed http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! Error: 407 Proxy Authentication Required
npm ERR!     at WriteStream.<anonymous> (C:\Program Files\nodejs\node_modules\np
m\lib\utils\fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1598:14
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-f
s\graceful-fs.js:105:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "grunt-cli" "bower" "
-g"
npm ERR! cwd C:\Users\swetpati
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm http 407 http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm http 407 http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\swetpati\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment] 2016-04-25 13:12
@swetapatil 

```
npm ERR! Error: 407 Proxy Authentication Required
```

Are you behind a proxy?

**Comment by swetapatil** [comment] 2016-04-28 03:31
Hi,

I am getting below error now after removing proxy setting.


npm http GET http://registry.npmjs.org/grunt
npm http GET http://registry.npmjs.org/grunt-cli
npm http GET http://registry.npmjs.org/bower
npm http GET http://registry.npmjs.org/grunt-cli
npm http GET http://registry.npmjs.org/bower
npm http GET http://registry.npmjs.org/grunt
npm http GET http://registry.npmjs.org/grunt-cli
npm http GET http://registry.npmjs.org/bower
npm http GET http://registry.npmjs.org/grunt
npm http GET http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm http GET http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm http GET http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm ERR! fetch failed http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm http GET http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm http GET http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm http GET http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm ERR! fetch failed http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm http GET http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm http GET http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm http GET http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:904:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "grunt-cli" "bower" "
-g"
npm ERR! cwd C:\Users\swetpati
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! syscall connect
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! stack Error: connect ECONNREFUSED
npm ERR! stack     at errnoException (net.js:904:11)
npm ERR! stack     at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR! fetch failed http://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! fetch failed http://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\swetpati\npm-debug.log
npm ERR! not ok code 0





Regards,
Sweta Patil

**Comment by swetapatil** [comment] 2016-04-28 06:14
Hi,

I am getting below error

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "grunt-cli" "bower" "-g"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! shasum check failed for C:\Users\swetpati\AppData\Local\Temp\npm-7876-0
fd9dbe5\registry.npmjs.org\grunt-cli\-\grunt-cli-1.2.0.tgz
npm ERR! Expected: 562b119ebb069ddb464ace2845501be97b35b6a8
npm ERR! Actual:   7fba459fecd197d334fd25722b1c815b89d5a532
npm ERR! From:     http://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\swetpati\npm-debug.log


Regards,
Sweta Patil

**Comment by zkat** [comment] 2016-12-09 00:42
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:42 UTC
Labels: support, windows
