### ISSUE TITLE
run npm install from ~/ fails cb() never called!

### ISSUE THREAD

**Issue by mearleycf** [npm/npm#16924] opened 2017-06-02 16:02 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
$ npm install
Unhandled rejection Error: Argument #2: Expected string but got nullath-to-regexp@latest fetched in 75ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?

ran ```npm install``` after running ```sudo npm install npm -g```
https://gist.github.com/mearleycf/b93ad6959c6d423ae2ecd59b2a52719f

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: mac
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I think I'm behind a proxy? I'm at work. But I'm unable to find the proxy information.

**Comment by jessieiswise** [comment] 2017-06-02 21:16
bump, seeing the same issue installing Npm inside a docker container.

' curl -L https://npmjs.org/install.sh |  sh ' failed with 'Unhandled rejection Error: Argument #2: Expected string but got null'

**Comment by zkat** [comment] 2017-06-05 15:57
Closing as dupe of https://github.com/npm/npm/issues/16904

**Closed as completed by zkat** 2017-06-05 15:57 UTC
Labels: npm5
