### ISSUE TITLE
Darwin error installing cordova

### ISSUE THREAD

**Issue by masscreation** [npm/npm#14267] opened 2016-10-13 04:56 UTC
#### I'm opening this issue because:

  -  npm is crashing.

#### What's going wrong?

When I run `npm install -g cordova  ` I get: 

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-ef9cc920
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-ef9cc920' -> '/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MassCreation/code/npm-debug.log
npm ERR! code 1
```

#### How can the CLI team reproduce the problem?

   npm install -g cordova
  
https://gist.github.com/masscreation/e255a52611d294c2f41805213d929401
 

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOS El Capitan 
 - Network issues:
   - Geographic location where npm was run: Tokyo
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.

**Comment by KenanY** [comment] 2016-10-13 14:06
Closing since this appears to be a duplicate of https://github.com/npm/npm/issues/12526.

**Closed by KenanY** 2016-10-13 14:06 UTC
Labels: support
