### ISSUE TITLE
unable to npm install from cache without internet connection when npm-shrinkwrap.json is present

### ISSUE THREAD

**Issue by tsing80** [npm/npm#10808] opened 2015-12-14 07:09 UTC
npm version: 3.5.2

When try to install offline from cache  after npm shrinkwrap. npm still try to fetch the package from registry resulting in  bunch of NPM FETCH error,  this problem do not exist when npm-shrinkwrap.json is not present

**Comment by othiym23** [comment] 2015-12-16 21:56
This is by design – because `npm-shrinkwrap.json` is intended to produce reproducible installs and deploys, it bypasses the cache to install exactly the value of the `resolved` fields in `npm-shrinkwrap.json`. Most of those fields are going to be package tarballs hosted on a registry, which npm will then download and install as found. Because some registries allow versions of packages to be published multiple times, the version number is an insufficiently strong guarantee of reproducibility.

At some point in the future, the CLI team intends to add shasums to `npm-shrinkwrap.json`. Doing so will allow us to stop bypassing the cache, as another piece of that will be making the cache content-addressable, so we know that fetching the tarball by shasum will give us a guaranteed consistent build. Until then, npm is working as designed, so I'm closing this issue. Thanks for your time!

**Closed by othiym23** 2015-12-16 21:56 UTC
Labels: shrinkwrap, support

**Comment by tsing80** [comment] 2015-12-17 01:59
@othiym23: Is there any way we could install shrinkwrap dependencies on production server without internet connection then?

**Comment by othiym23** [comment] 2015-12-17 02:05
You could rewrite the `resolved` fields in `npm-shrinkwrap.json` to be paths to the tarballs you want deployed in production, but I think it would probably be simpler just to pack up your entire app and unpack it on the deploy host without using npm at all.
