### ISSUE TITLE
readme files not included in `npm pack`

### ISSUE THREAD

**Issue by jdalton** [npm/npm#12614] opened 2016-05-06 19:53 UTC
I've tried `npm@^2.0.0` and `npm@^3.0.0` and on OSX `npm pack` is not including the `README.md` for projects like [lodash/lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin). I'm not sure when this started happening but can confirm others aren't seeing it so I figured I'd post.

**Comment by KenanY** [comment] 2016-05-09 00:57
@jdalton Node.js version?

**Comment by jdalton** [comment] 2016-05-09 01:11
Node v6.0.0 via `nvm`. I'm wondering if it's an issue with `nvm` + `npm`.

**Comment by othiym23** [comment] 2016-05-09 02:47
Closing as duplicate of #5082. Please check that issue for what's up and what action we're taking to remedy it. Thanks for your time!

**Closed by othiym23** 2016-05-09 02:47 UTC
