### ISSUE TITLE
Installation error 'npm install -g powerbi-visuals-tools'

### ISSUE THREAD

**Issue by trimantra** [npm/npm#15240] opened 2016-12-16 12:06 UTC
Hi,

I am getting the error while installing the command line tool for Power BI visuals. I run this command  'npm install -g powerbi-visuals-tools'  and I am getting the error. See the Error log file attached with this issue.
[npm-debug.txt](https://github.com/npm/npm/files/657112/npm-debug.txt)

**Comment by Charlotteis** [comment] 2016-12-16 12:12
Hey @trimantra!

Looks like this is a duplicate of https://github.com/npm/npm/issues/14626.

Have a great day.

**Comment by zkat** [comment] 2016-12-16 21:34
Also likely fixed. See https://github.com/npm/npm/issues/14626#issuecomment-267701302

**Closed by zkat** 2016-12-16 21:34 UTC
Labels: network, support

**Comment by Sikhumbuzo-Nzimande** [comment] 2018-04-16 11:50
Hi i also have a similar issue, please see the attached file
[2018-04-16T11_49_29_452Z-debug.log](https://github.com/npm/npm/files/1915097/2018-04-16T11_49_29_452Z-debug.log)
