### ISSUE TITLE
https://nodejs.org/dist/npm/ dont list latest npm versions

### ISSUE THREAD

**Issue by digitalkaoz** [npm/npm#10346] opened 2015-11-11 21:41 UTC
can someone reenable the automated build publish to https://nodejs.org/dist/npm/ ? to https://nodejs.org/dist/ it seems to be done for node version, but the npm versions are outdated. 

im using it this way in our build environment through https://github.com/eirslett/frontend-maven-plugin

**Comment by othiym23** [comment] 2015-11-11 21:54
Closing as a duplicate of #6474, and the same logic from there applies here: there's already a source of truth about what versions of npm exist, and that's the npm registry.

**Closed by othiym23** 2015-11-11 21:54 UTC
Labels: support
