### ISSUE TITLE
npm search out of memory

### ISSUE THREAD

**Issue by AlgoTrader** [npm/npm#12658] opened 2016-05-11 07:53 UTC
npm search failed on the PC with 16GB of RAM. Node 6.1.0

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted (core dumped)

I can understand I can add 100Gb of swap and wait an hour or two. Isn't it enough? npm search proved to be troublesome on VPS with limited RAM long before now. npm search should use some server-accelerated index. 

Please do it, enough this pain

**Comment by lxe** [comment] 2016-05-18 22:12
I'm surprised npm search still behaves by hitting the `/-/all` route, which dumps 161mb worth of JSON.

**Comment by othiym23** [comment] 2016-05-18 22:17
Closing as duplicate of #12619, which is a known issue. Fixing / replacing npm's search is something that persistently sits on the second shelf, urgency-wise. Fixing it is a cross-company project that we intend to get to, but there are other, higher priorities the involved teams need to address first. Thanks for your time!

**Closed by othiym23** 2016-05-18 22:17 UTC
Labels: bug, search
