### ISSUE TITLE
Cannot read property 'target' of null

### ISSUE THREAD

**Issue by imaculate** [npm/npm#11138] opened 2016-01-13 18:03 UTC
When I run the following command on windows 
```
 npm install –g bower yo generator-office gulp tsd
```

I get the above error. 
Cannot read property 'target' of null.
I have attached my logfile
[npm-debug.txt](https://github.com/npm/npm/files/89300/npm-debug.txt)

```
25576 verbose stack TypeError: Cannot read property 'target' of null
25576 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\lib\install\filter-invalid-actions.js:24:35)
25576 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
25576 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
25576 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
25576 verbose stack     at Object.Installer.computeLinked (C:\Program Files\nodejs\node_modules\npm\lib\install.js:411:41)
25576 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
25576 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
25576 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
25576 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\lib\install\diff-trees.js:50:3)
25576 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)

25580 error node v4.2.4
25581 error npm  v3.5.3

```

**Comment by jadbox** [comment] 2016-02-08 16:49
This may be a duplicate of #10686

**Comment by othiym23** [comment] 2016-02-08 17:01
It is indeed, which just goes to show one of the problems with having such an active issue tracker – even when we suspect that a bug already exists, it's really hard to find the duplicates right now. I'm closing this one as a duplicate, and the team should get to #10686 when we move from working on fixing npm's tests to fixing the outstanding issues in the `npm@3` installer (which basically is what the `big-bug` tag denotes right now). That should probably be within the next month or so. Thank you for the pointer, @jadbox!

**Closed by othiym23** 2016-02-08 17:01 UTC
Labels: big-bug, bug

**Comment by cuiyongjian** [comment] 2016-02-21 08:48
yongjiancui-MC1:generator-backbone cuiyongjian$ npm install generator-mocha
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "generator-mocha"
npm ERR! node v5.6.0
npm ERR! npm  v3.5.3

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/generator-backbone/npm-debug.log
