### ISSUE TITLE
Shrinkwrap ignored after adding manually module to package

### ISSUE THREAD

**Issue by maxime-helen-sb** [npm/npm#11950] opened 2016-03-17 23:10 UTC
I noticed an inconsistency between npm `v2.10.1` and `v3.3.12` regarding `npm shrinkwrap` behavior.

Here are the steps to reproduce my observations:
1. `mkdir test_case && cd test_case`
2. `npm init`
3. `npm install react --save` Note that react is chosen as an example, it could any other module
4. `npm shrinkwrap`
5. Add any other module to package,json by hand
6. `npm install`

With `v2.10.1`, the module specified in step 5 doesn't get installed. I imagine this result to be the right behavior.
With `v3.3.12`, the module added manually in step 5 is installed anyways, ignoring the shrinkwrap

Is this is intended? Or is this a bug?

Thank you!

**Comment by zkat** [comment] 2016-03-25 00:27
This looks possibly like a duplicate of #11971

**Closed** 2017-06-18 12:03 UTC
Labels: bot-closed
