### ISSUE TITLE
`npm install` in npm repo explodes

### ISSUE THREAD

**Issue by othiym23** [npm/npm#9847] opened 2015-10-05 21:11 UTC
(starting from `iarna/performance` branch)

1. `git fetch --all`
2. `git checkout master`
3. `git merge --ff-only origin/master`
4. `npm i`

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.6
npm ERR! path /Users/ogd/Documents/projects/npm/npm/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/node_modules/amdefine
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/ogd/Documents/projects/npm/npm/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/node_modules/amdefine' -> '/Users/ogd/Documents/projects/npm/npm/node_modules/amdefine'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ogd/Documents/projects/npm/npm/npm-debug.log
```

[ [`npm-debug.log`](https://gist.github.com/555eee679eebf0afad04) ]

**Comment by martndemus** [comment] 2015-10-06 10:28
I have a similar thing with `npm install -g bower`

```
$ npm -v
3.3.5
$ npm install -g bower
npm WARN install:async ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/bower/node_modules/form-data/node_modules/async' -> '/usr/local/lib/node_modules/bower/node_modules/form-data/node_modules/async'
async@0.9.2 node_modules/bower/node_modules/form-data/node_modules/async -> node_modules/bower/node_modules/form-data/node_modules/async
form-data@0.2.0 node_modules/bower/node_modules/request/node_modules/form-data -> node_modules/bower/node_modules/form-data
- /usr/local/lib/node_modules/bower/node_modules/form-data node_modules/bower/node_modules/form-data
/usr/local/lib
└── (empty)

npm ERR! code 1
```

**Comment by dhritzkiv** [comment] 2015-10-06 17:51
I get the `no such file or directory, rename` error about one in three times when running `npm install`. This (usually?) happens when installing using multiple package names (but I don't suspect this is the actual cause). Fortunately, running the same command a second time always rectifies the problem.

OS X 10.11 & npm v3.3.6 (though, this has been happening since 10.10 and v3.3.3)

**Comment by iamwave007** [comment] 2015-10-09 12:53
is this still happening at v3.3.7?

**Comment by dhritzkiv** [comment] 2015-10-12 01:43
Yes – just happened. Here's the error (with certain parts of paths `[redacted]`)

```bash
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "node-quickbooks@latest" "request@latest" "shipwire@latest" "winston@latest"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.7
npm ERR! path /Users/dhritzkiv/Development/[redacted]/node_modules/shipwire/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/dhritzkiv/Development/[redacted]/node_modules/shipwire/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash' -> '/Users/dhritzkiv/Development/[redacted]/node_modules/xmlbuilder/node_modules/lodash'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dhritzkiv/Development/[redacted]/npm-debug.log
```

**Comment by iamwave007** [comment] 2015-10-12 14:30
Nice, thought i was the only one haunted. how to fix it?

**Comment by fadak** [comment] 2015-10-17 10:01
i have similar issue when running ``` npm install ```

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\mosafer\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.8
npm ERR! path D:\app1\node_modules\google-cdn\node_modules\bower-config\node_modules\graceful-fs
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'D:\app1\node_modules\google-cdn\node_modules\bower-config\node_modules\graceful-fs' -> 'D:\app1\node_modules\grunt-google-cdn\node_modules\bower-registry-client\node_modules\graceful-fs'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by asottile** [comment] 2015-11-02 22:50
I'm having a similar issue in http://github.com/pre-commit/mirrors-jshint

**Comment by iarna** [comment] 2015-11-06 19:49
Closing this as a duplicate of #9633

**Closed by iarna** 2015-11-06 19:49 UTC
Labels: already-triaged, big-bug, bug
