### ISSUE TITLE
npm publish, incorrect tag name error

### ISSUE THREAD

**Issue by debris** [npm/npm#8531] opened 2015-06-11 03:26 UTC
Hi. I recently updated node and npm and today tried publishing package for the first time since then.
I run:

```
npm publish --loglevel verbose . --tag 0.6.0
```

and get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--loglevel',
1 verbose cli   'verbose',
1 verbose cli   '.',
1 verbose cli   '--tag',
1 verbose cli   '0.6.0' ]
2 info using npm@2.11.1
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose publish [ '.' ]
6 verbose stack Error: Tag name must not be a valid SemVer range: 0.6.0
6 verbose stack     at EventEmitter.publish (/usr/local/lib/node_modules/npm/lib/publish.js:41:14)
6 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:217:11)
6 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:72:28)
6 verbose stack     at process._tickCallback (node.js:355:11)
7 verbose cwd /Users/marekkotewicz/ethereum/ethereum.js
8 error Darwin 14.3.0
9 error argv "node" "/usr/local/bin/npm" "publish" "--loglevel" "verbose" "." "--tag" "0.6.0"
10 error node v0.12.4
11 error npm  v2.11.1
12 error Tag name must not be a valid SemVer range: 0.6.0
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

This was surprising, cause `0.6.0` is in valid SemVar range. Also I used to publish packages with similar versioning in the past, so something must have changed.

edit.
Also after I run `npm publish` everything was published correctly and the tag was set to `0.6.0`.

**Comment by othiym23** [comment] 2015-06-11 03:48
```
6 verbose stack Error: Tag name must not be a valid SemVer range: 0.6.0
```

Because of how the registry uses semver, `dist-tags` must not be interpretable as valid semver versions or ranges themselves, so packages don't end up with nonsensical or ambiguous tags like `package@0.6.0` actually mapping to the version `1.1.2`. `dist-tags` are symbolic names for versions and can be moved around in a way that semver versions and ranges cannot.

For further details, here's a chunk of the [`npm dist-tag` documentation](https://docs.npmjs.com/cli/dist-tag):

> Tags must share a namespace with version numbers, because they are specified in the same slot: `npm install <pkg>@<version>` vs `npm install <pkg>@<tag>`.
>
> Tags that can be interpreted as valid semver ranges will be rejected. For example, `v1.4` cannot be used as a tag, because it is interpreted by semver as `>=1.4.0 <1.5.0`. See https://github.com/npm/npm/issues/6082.
>
> The simplest way to avoid semver problems with tags is to use tags that do not begin with a number or the letter v.

As far as:

>Also I used to publish packages with similar versioning in the past, so something must have changed.

...there was a time when nmp allowed this, but it was a regression that was fixed in `npm@2`.

**Closed by othiym23** 2015-06-11 03:48 UTC

**Comment by debris** [comment] 2015-06-11 04:03
Thank you!
