### ISSUE TITLE
"npm install" filters "build/" subdirectory by default

### ISSUE THREAD

**Issue by jbeard4** [npm/npm#2048] opened 2012-01-17 02:17 UTC
I'm trying to package my node module with npm. My project has a sub-directory named "build/", and I've found that running "npm install" on my project will install all the files in the project to node_modules, except for the "build/" subdirectory. It therefore seems that "build/" is getting filtered by default. It's not clear from the documentation whether this is expected behavior, and whether it is possible to override it.

**Comment by zkat** [comment] 2016-12-03 01:12
This is likely one of two possible causes:

* A duplicate of https://github.com/npm/npm/issues/5082 (unlikely, since that one's a heisenbug, and this seems consistent)
* An instance of confusion about how ignores work, or a related gotcha. For more info on how file inclusion works, see: https://github.com/npm/npm/wiki/Files-and-Ignores

If you want to be able to test things yourself, you can also do `npm pack` on your project, which runs the tarball-creation part of publish.

That said, this is a pretty ancient issue, so I'm gonna close it. I've assigned it to myself so feel free to respond if this is something you're still seeing and can reproduce.

**Closed by zkat** 2016-12-03 01:12 UTC
Labels: support
