### ISSUE TITLE
About CLI install error in Windows(Expo Package)

### ISSUE THREAD

**Issue by VimalRaj571** [npm/npm#16561] opened 2017-05-08 09:11 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

###
![expoerr](https://cloud.githubusercontent.com/assets/8166149/25797716/f4c608a6-33fb-11e7-9985-1686d6adc98d.JPG)

**_

> When I try to install npm package on windows it shows the error in CLI.....!

_**
 
supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-05-09 17:54
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by VimalRaj571** [comment] 2017-05-09 18:06
@legodude17 Thanks !!!!! 👍

**Closed** 2017-05-09 20:31 UTC
Labels: shasum, support
