### ISSUE TITLE
Installation error!!

### ISSUE THREAD

**Issue by onkareee** [npm/npm#8611] opened 2015-06-19 07:04 UTC
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt',
1 verbose cli   '--save-dev' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/bin/node
5 verbose install initial load of /home/proptiger/Documents/workspace/package.json
6 warn package.json @ No description
7 warn package.json @ No repository field.
8 warn package.json @ No README data
9 warn package.json @ No license field.
10 verbose readDependencies loading dependencies from /home/proptiger/Documents/workspace/package.json
11 silly cache add args [ 'grunt', null ]
12 verbose cache add spec grunt
13 silly cache add parsed spec { raw: 'grunt',
13 silly cache add   scope: null,
13 silly cache add   name: 'grunt',
13 silly cache add   rawSpec: '',
13 silly cache add   spec: '*',
13 silly cache add   type: 'range' }
14 silly addNamed grunt@*
15 verbose addNamed "*" is a valid semver range for grunt
16 silly addNameRange { name: 'grunt', range: '*', hasData: false }
17 silly mapToRegistry name grunt
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/grunt
21 verbose addNameRange registry:https://registry.npmjs.org/grunt not in flight; fetching
22 verbose request uri https://registry.npmjs.org/grunt
23 verbose request no auth needed
24 info attempt registry request try #1 at 12:29:06
25 verbose request id cbbc04ab22eefe94
26 http request GET https://registry.npmjs.org/grunt
27 http 200 https://registry.npmjs.org/grunt
28 silly get cb [ 200,
28 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
28 silly get     etag: '"1E31OVR0BV200XV6U8MFEI27M"',
28 silly get     'content-type': 'application/json',
28 silly get     'cache-control': 'max-age=60',
28 silly get     'content-length': '89496',
28 silly get     'accept-ranges': 'bytes',
28 silly get     date: 'Fri, 19 Jun 2015 06:59:06 GMT',
28 silly get     via: '1.1 varnish',
28 silly get     age: '1',
28 silly get     connection: 'keep-alive',
28 silly get     'x-served-by': 'cache-sin6921-SIN',
28 silly get     'x-cache': 'HIT',
28 silly get     'x-cache-hits': '4',
28 silly get     'x-timer': 'S1434697146.567758,VS0,VE0',
28 silly get     vary: 'Accept' } ]
29 verbose get saving grunt to /home/proptiger/.npm/registry.npmjs.org/grunt/.cache.json
30 silly addNameRange number 2 { name: 'grunt', range: '*', hasData: true }
31 silly addNameRange versions [ 'grunt',
31 silly addNameRange   [ '0.1.0',
31 silly addNameRange     '0.1.1',
31 silly addNameRange     '0.1.2',
31 silly addNameRange     '0.2.0',
31 silly addNameRange     '0.2.1',
31 silly addNameRange     '0.2.2',
31 silly addNameRange     '0.2.3',
31 silly addNameRange     '0.2.4',
31 silly addNameRange     '0.2.5',
31 silly addNameRange     '0.2.6',
31 silly addNameRange     '0.2.7',
31 silly addNameRange     '0.2.8',
31 silly addNameRange     '0.2.9',
31 silly addNameRange     '0.2.10',
31 silly addNameRange     '0.2.11',
31 silly addNameRange     '0.2.12',
31 silly addNameRange     '0.2.13',
31 silly addNameRange     '0.2.14',
31 silly addNameRange     '0.2.15',
31 silly addNameRange     '0.3.0',
31 silly addNameRange     '0.3.1',
31 silly addNameRange     '0.3.2',
31 silly addNameRange     '0.3.3',
31 silly addNameRange     '0.3.4',
31 silly addNameRange     '0.3.5',
31 silly addNameRange     '0.3.6',
31 silly addNameRange     '0.3.7',
31 silly addNameRange     '0.3.8',
31 silly addNameRange     '0.3.9',
31 silly addNameRange     '0.3.10',
31 silly addNameRange     '0.3.11',
31 silly addNameRange     '0.3.12',
31 silly addNameRange     '0.3.13',
31 silly addNameRange     '0.3.14',
31 silly addNameRange     '0.3.15',
31 silly addNameRange     '0.3.16',
31 silly addNameRange     '0.3.17',
31 silly addNameRange     '0.4.0',
31 silly addNameRange     '0.4.1',
31 silly addNameRange     '0.4.2',
31 silly addNameRange     '0.4.3',
31 silly addNameRange     '0.4.4',
31 silly addNameRange     '0.4.5',
31 silly addNameRange     '0.3.13-a',
31 silly addNameRange     '0.4.0-a',
31 silly addNameRange     '0.4.0-rc1',
31 silly addNameRange     '0.4.0-rc2',
31 silly addNameRange     '0.4.0-rc3',
31 silly addNameRange     '0.4.0-rc4',
31 silly addNameRange     '0.4.0-rc5',
31 silly addNameRange     '0.4.0-rc6',
31 silly addNameRange     '0.4.0-rc7',
31 silly addNameRange     '0.4.0-rc8' ] ]
32 silly addNamed grunt@0.4.5
33 verbose addNamed "0.4.5" is a plain semver version for grunt
34 silly mapToRegistry name grunt
35 silly mapToRegistry using default registry
36 silly mapToRegistry registry https://registry.npmjs.org/
37 silly mapToRegistry uri https://registry.npmjs.org/grunt
38 verbose addRemoteTarball https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz not in flight; adding
39 verbose addRemoteTarball [ 'https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz',
39 verbose addRemoteTarball   '56937cd5194324adff6d207631832a9d6ba4e7f0' ]
40 info retry fetch attempt 1 at 12:29:08
41 info attempt registry request try #1 at 12:29:08
42 http fetch GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
43 http fetch 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
44 silly fetchAndShaCheck shasum 56937cd5194324adff6d207631832a9d6ba4e7f0
45 verbose addTmpTarball /tmp/npm-4888-8cf38b56/registry.npmjs.org/grunt/-/grunt-0.4.5.tgz not in flight; adding
46 verbose addTmpTarball already have metadata; skipping unpack for grunt@0.4.5
47 silly cache afterAdd grunt@0.4.5
48 verbose afterAdd /home/proptiger/.npm/grunt/0.4.5/package/package.json not in flight; writing
49 verbose afterAdd /home/proptiger/.npm/grunt/0.4.5/package/package.json written
50 silly install resolved [ { name: 'grunt',
50 silly install resolved     description: 'The JavaScript Task Runner',
50 silly install resolved     version: '0.4.5',
50 silly install resolved     author: { name: '"Cowboy" Ben Alman', url: 'http://benalman.com/' },
50 silly install resolved     homepage: 'http://gruntjs.com/',
50 silly install resolved     repository: { type: 'git', url: 'git://github.com/gruntjs/grunt.git' },
50 silly install resolved     bugs: { url: 'http://github.com/gruntjs/grunt/issues' },
50 silly install resolved     licenses: [ [Object] ],
50 silly install resolved     main: 'lib/grunt',
50 silly install resolved     scripts: { test: 'grunt test' },
50 silly install resolved     engines: { node: '>= 0.8.0' },
50 silly install resolved     keywords:
50 silly install resolved      [ 'task',
50 silly install resolved        'async',
50 silly install resolved        'cli',
50 silly install resolved        'minify',
50 silly install resolved        'uglify',
50 silly install resolved        'build',
50 silly install resolved        'lodash',
50 silly install resolved        'unit',
50 silly install resolved        'test',
50 silly install resolved        'qunit',
50 silly install resolved        'nodeunit',
50 silly install resolved        'server',
50 silly install resolved        'init',
50 silly install resolved        'scaffold',
50 silly install resolved        'make',
50 silly install resolved        'jake',
50 silly install resolved        'tool' ],
50 silly install resolved     dependencies:
50 silly install resolved      { async: '~0.1.22',
50 silly install resolved        'coffee-script': '~1.3.3',
50 silly install resolved        colors: '~0.6.2',
50 silly install resolved        dateformat: '1.0.2-1.2.3',
50 silly install resolved        eventemitter2: '~0.4.13',
50 silly install resolved        'findup-sync': '~0.1.2',
50 silly install resolved        glob: '~3.1.21',
50 silly install resolved        hooker: '~0.2.3',
50 silly install resolved        'iconv-lite': '~0.2.11',
50 silly install resolved        minimatch: '~0.2.12',
50 silly install resolved        nopt: '~1.0.10',
50 silly install resolved        rimraf: '~2.2.8',
50 silly install resolved        lodash: '~0.9.2',
50 silly install resolved        'underscore.string': '~2.2.1',
50 silly install resolved        which: '~1.0.5',
50 silly install resolved        'js-yaml': '~2.0.5',
50 silly install resolved        exit: '~0.1.1',
50 silly install resolved        getobject: '~0.1.0',
50 silly install resolved        'grunt-legacy-util': '~0.2.0',
50 silly install resolved        'grunt-legacy-log': '~0.1.0' },
50 silly install resolved     devDependencies:
50 silly install resolved      { temporary: '~0.0.4',
50 silly install resolved        'grunt-contrib-jshint': '~0.6.4',
50 silly install resolved        'grunt-contrib-nodeunit': '~0.2.0',
50 silly install resolved        'grunt-contrib-watch': '~0.5.3',
50 silly install resolved        difflet: '~0.2.3',
50 silly install resolved        semver: '2.1.0',
50 silly install resolved        shelljs: '~0.2.5' },
50 silly install resolved     _id: 'grunt@0.4.5',
50 silly install resolved     dist:
50 silly install resolved      { shasum: '56937cd5194324adff6d207631832a9d6ba4e7f0',
50 silly install resolved        tarball: 'http://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz' },
50 silly install resolved     _from: 'grunt@*',
50 silly install resolved     _npmVersion: '1.4.4',
50 silly install resolved     _npmUser: { name: 'cowboy', email: 'cowboy@rj3.net' },
50 silly install resolved     maintainers: [ [Object], [Object] ],
50 silly install resolved     directories: {},
50 silly install resolved     _shasum: '56937cd5194324adff6d207631832a9d6ba4e7f0',
50 silly install resolved     _resolved: 'https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz' } ]
51 info install grunt@0.4.5 into /home/proptiger/Documents/workspace
52 info installOne grunt@0.4.5
53 verbose installOne of grunt to /home/proptiger/Documents/workspace not in flight; installing
54 warn locking Error: EACCES, open '/home/proptiger/.npm/_locks/grunt-900bc41316be6541.lock'
54 warn locking     at Error (native)
54 warn locking  /home/proptiger/.npm/_locks/grunt-900bc41316be6541.lock failed { [Error: EACCES, open '/home/proptiger/.npm/_locks/grunt-900bc41316be6541.lock']
54 warn locking   errno: -13,
54 warn locking   code: 'EACCES',
54 warn locking   path: '/home/proptiger/.npm/_locks/grunt-900bc41316be6541.lock' }
55 verbose stack Error: Attempt to unlock /home/proptiger/Documents/workspace/node_modules/grunt, which hasn't been locked
55 verbose stack     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:66:11)
55 verbose stack     at cb (/usr/lib/node_modules/npm/lib/install.js:1017:5)
55 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:1021:20
55 verbose stack     at /usr/lib/node_modules/npm/lib/utils/locker.js:40:9
55 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
55 verbose stack     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
55 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
56 verbose cwd /home/proptiger/Documents/workspace
57 error Linux 3.13.0-24-generic
58 error argv "/usr/bin/node" "/usr/bin/npm" "install" "grunt" "--save-dev"
59 error node v0.12.4
60 error npm  v2.10.1
61 error Attempt to unlock /home/proptiger/Documents/workspace/node_modules/grunt, which hasn't been locked
62 error If you need help, you may report this error at:
62 error     <https://github.com/npm/npm/issues>
63 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment] 2015-06-19 17:41
@onkareee 

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by rstack** [comment] 2015-06-22 17:29
If it's still locked at that point:

`$ rm /home/proptiger/.npm/_locks/grunt-900bc41316be6541.lock`

**Comment by snopeks** [comment] 2015-10-16 21:35
hello @onkareee, it looks like the problem is solved, so I'm going to go ahead and close this issue. If you are still running into this issue, please let me know and I'll be happy to reopen. Thanks!

**Closed by snopeks** 2015-10-16 21:35 UTC
Labels: support
