### ISSUE TITLE
npm packages that don't install on npm#multi-stage

### ISSUE THREAD

**Issue by Atrophius** [npm/npm#8395] opened 2015-05-29 14:33 UTC
Hey @iarna - Here's my preliminary list of npm packages that install on npm@stable but fail on npm#multi-stage:

- karma
- pm2

There are also several `EPEERINVALID` errors across all of the Yeoman generators I've tried, but I'm assuming those are issues with their dependencies rather than issues with npm itself.

**Comment by iarna** [comment] 2015-06-04 09:45
These both install with current HEAD. There have been some fixes around optional dependency rollback, but I didn't see any optional dep failures either. Can you give it a try with the most recent HEAD?

**Comment by iarna** [comment] 2015-06-04 11:06
The `EPEERINVALID`'s are probably due to the intentional breaking change in npm@3, where we no longer install peer deps for you.  peerDependency's now act as assertions, producing `EPEERINVALID` errors if their requirements aren't otherwise installed.

**Comment by paulharris** [comment] 2015-06-10 07:31
Hi,  I've been playing with multi-stage.

This use-case fails using new npm, and is ok on old npm.
I am using the "superheroes" package (on github, i saw it in someone's twitter randomly).
It installs meow@3.1 as a dependency.

So I thought, what if I'm developing something that requires both superheroes and an older meow ?

npm install sindresorhus/superheroes
npm install meow@2.1

npm ls
(for old npm -- all ok)
(for new npm -- unmet dependencies as superheroes's meow is stomped by the old meow)

is this a "do not fix" issue, or something real that developers are going to suffer with?

cheers,
Paul

**Comment by iarna** [comment] 2015-06-10 07:36
No, this is definitely a regression, in fact up till pretty recently it worked in the multi-stage branch. I actually know exactly what patch broke this so it'll be an easy fix. Thanks for pointing it out!

**Comment by paulharris** [comment] 2015-06-10 07:37
Note that if you install the old meow first and THEN superheroes, then it works,
as npm installs the newer meow as a nested mod.

Installation ordering pain...

**Comment by iarna** [comment] 2015-06-10 07:41
@paulharris I'm going to delete our comments on this issue– I've moved them over to #8514

**Comment by iarna** [comment] 2015-06-12 06:04
@Atrophius In the interest of keeping the `multi-stage` milestone issue list manageable, I'm going to close this as whatever issue you were having seems to have been resolved (or I can't reproduce it). If you are still having problems or you otherwise run into any problems, please open a new issue. Thanks!

**Closed by iarna** 2015-06-12 06:04 UTC
Labels: bug, in progress
