### ISSUE TITLE
how to resolve shasum check failed while installing typescript??

### ISSUE THREAD

**Issue by salinimt** [npm/npm#18255] opened 2017-08-21 14:46 UTC
C:\Users\user>npm install -g typescript
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
npm ERR! node v6.10.0
npm ERR! npm  v1.0.0

npm ERR! shasum check failed for C:\Users\user\AppData\Local\Temp\npm-4180-6c6a63b4\registry.npmjs.org\typescript\-\typescript-2.4.2.tgz
npm ERR! Expected: f8395f85d459276067c988aa41837a8f82870844
npm ERR! Actual:   257f8186887ede8dd7d19579a705091453e887ba
npm ERR! From:     https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment] 2017-08-21 15:05
@salinimt I'm gonna close this as a duplicate of your previous issue, https://github.com/npm/npm/issues/18254.

**Closed as completed by kenany** 2017-08-21 15:05 UTC
Labels: support, shasum
