### ISSUE TITLE
install truffle on ubuntu16.04

### ISSUE THREAD

**Issue by Luiniux** [npm/npm#14597] opened 2016-11-11 12:56 UTC
#### I'm opening this issue because:

npm is producing an incorrect install.

#### What's going wrong?
I can't install truffle on ubuntu16.04

#### How can the CLI team reproduce the problem?
my node version is 7.0.0
When I install truffle on ubuntu16.04,it always failed and display that 
luiniux@luiniux-DELL:~$ npm install -g truffle
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "truffle"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for /tmp/npm-917-383ae112/registry.npmjs.org/solc/-/solc-0.3.6.tgz
npm ERR! Expected: ee1678e144701fbc1635efb21213c7953cf2bba9
npm ERR! Actual:   e62b729e4fd3527e7bd1ecc3e1e8b2c74ccb6c13
npm ERR! From:     https://registry.npmjs.org/solc/-/solc-0.3.6.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/luiniux/npm-debug.log
I would like to know whether truffle could support ubuntu16.04 or not ,and how could I use truffle on ubuntu16.04.
Please forgive my pool English,thanks a lot.

**Comment by KenanY** [comment] 2016-11-11 16:58
@Luiniux Maybe try running `npm cache clean`?

**Comment by KenanY** [comment] 2016-12-03 16:55
Closing as abandoned.

**Closed by KenanY** 2016-12-03 16:55 UTC
Labels: network, shasum, support

**Comment by syntacticsolutions** [comment] 2016-12-30 04:04
I'm having this issue as well when trying to install node in elementary OS

**Comment by legodude17** [comment] 2016-12-30 05:40
This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.
