### ISSUE TITLE
npm i: Warning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by oaleynik** [npm/npm#13724] opened 2016-08-22 13:18 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm i` throws tons of 'Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit' warnings.

#### How can the CLI team reproduce the problem?

Create `package.json` with the following content and run `npm i`:

```json
{
  "name": "npm-80939",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "es6-promise": "^3.2.1",
    "express": "^4.14.0",
    "isomorphic-fetch": "^2.2.1",
    "lodash.debounce": "^4.0.8",
    "serialize-javascript": "^1.3.0",
    "serve-favicon": "^2.3.0",
    "vue": "^2.0.0-rc.2",
    "vue-router": "^2.0.0-rc.3",
    "vue-server-renderer": "^2.0.0-rc.2",
    "vuex": "^2.0.0-rc.5",
    "vuex-router-sync": "^3.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.0",
    "babel-core": "^6.13.2",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-0": "^6.5.0",
    "css-loader": "^0.23.1",
    "eslint": "^3.3.1",
    "eslint-config-airbnb-base": "^5.0.2",
    "eslint-friendly-formatter": "^2.0.6",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-html": "^1.5.2",
    "eslint-plugin-import": "^1.13.0",
    "extract-text-webpack-plugin": "^2.0.0-beta.3",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.22.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "node-sass": "^3.8.0",
    "postcss-loader": "^0.10.1",
    "progress-bar-webpack-plugin": "^1.9.0",
    "sass-loader": "^4.0.0",
    "style-loader": "^0.13.1",
    "vue-loader": "^9.3.2",
    "webpack": "^2.1.0-beta.21",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-hot-middleware": "^2.12.2"
  }
}
```

### supporting information:

 - `npm -v` prints: 3.10.7
 - `node -v` prints: 6.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by oaleynik** [comment] 2016-08-22 13:19
Possibly related #13327

**Comment by KenanY** [comment] 2016-08-22 15:09
Gonna close this as a duplicate of https://github.com/npm/npm/issues/13656. If you believe I'm wrong I will happily reopen.

**Closed by KenanY** 2016-08-22 15:09 UTC

**Comment by oaleynik** [comment] 2016-08-22 15:11
@KenanY oh, sorry. Somehow search through issue didn't show 13656. Thanks!
