### ISSUE TITLE
user password is saved in the npm config

### ISSUE THREAD

**Issue by noamokman** [npm/npm#8926] opened 2015-07-13 15:05 UTC
Hi there!
I took a look at the npmrc file and was a bit shocked to see my password in there.
(it is actually saved in base64 but it is still there)
I wanted to ask if this is mandatory and if we can replace the password with a token instead.

I want to help but this is more of a joined server side / client side effort, and wanted to talk about it first.
Thanks a lot :smile:

**Comment by KenanY** [comment] 2015-07-13 18:49
Previously: https://github.com/npm/npm/issues/4905

**Comment by othiym23** [comment] 2015-07-15 04:52
Storing your publish credentials is one of the primary purposes of `.npmrc`, and is probably something that will always be in that file. _However,_ if you run `npm login` again (at least against the primary npm registry), you'll end up with a token rather than a Base64-encrypted password. That token is still a word of power, and as such, shouldn't be checked into revision control or shared in public, but it's at least revocable (by running `npm logout` on a host using it as the auth token). We're still working on moving towards some sort of OAuth-based client session token + shared secret auth, but that's not on our immediate horizon.

Either way, this behavior is by design, and changing it is a major effort distributed over the whole project / company, so I'm going to close this out. In the meantime, you should probably log in again and switch to using a session token!

**Closed by othiym23** 2015-07-15 04:52 UTC
Labels: support

**Comment by noamokman** [comment] 2015-07-19 04:47
OK, Thanks! :+1:

**Comment by edi9999** [comment] 2016-12-09 07:55
I ended up using environment variables for npm configuration, for example : 

```
export npm_config_loglevel=silent
```

instead of 

```
loglevel=silent 

in .npmrc
```
