### ISSUE TITLE
Cannot read property 'target' of null

### ISSUE THREAD

**Issue by isowsy** [npm/npm#11755] opened 2016-03-03 07:53 UTC
when I try to run npm install, it shows:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\node_modules\bootstrap\npm-debug.log

**Comment by ashleygwilliams** [comment] 2016-03-03 14:55
hi! are you trying to run `npm install` in a directory with a `package.json`?

**Comment by nkbt** [comment] 2016-03-09 02:24
Most likely duplicate of https://github.com/npm/npm/issues/10686

**Comment by iarna** [comment] 2017-07-06 03:00
This is likely fixed! Please give npm@5 a try and if you still have problems open a new issue. Thanks!

**Closed by iarna** 2017-07-06 03:00 UTC
Labels: bug
