### ISSUE TITLE
Maximum call stack size exceeded during npm install

### ISSUE THREAD

**Issue by andersem** [npm/npm#15886] opened 2017-02-27 20:05 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
As seen in [npm-debug.txt](https://github.com/npm/npm/files/804870/npm-debug.txt), during `npm install` I get an Maximum call stack size exceeded-error.

These are my dependencies. 
```
{
  "devDependencies": {
    "autoprefixer": "^6.3.6",
    "babel-core": "^6.4.5",
    "babel-eslint": "5.0.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-object-rest-spread": "^6.16.0",
    "babel-plugin-transform-regenerator": "^6.6.5",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.3.13",
    "babel-register": "^6.4.3",
    "browser-sync": "^2.11.2",
    "chai": "^3.5.0",
    "css-loader": "^0.23.1",
    "deep-freeze-node": "^1.1.1",
    "dirty-chai": "1.2.2",
    "enzyme": "2.3.0",
    "es6-promise": "^3.0.2",
    "eslint": "2.2.0",
    "eslint-config-airbnb": "6.0.2",
    "eslint-plugin-react": "4.1.0",
    "file-loader": "^0.9.0",
    "font-awesome-webpack": "0.0.4",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "http-proxy-middleware": "^0.13.0",
    "jsdom": "^8.0.2",
    "less": "^2.6.1",
    "less-loader": "^2.2.3",
    "loose-envify": "^1.1.0",
    "mocha": "^2.5.3",
    "node-sass": "^3.4.2",
    "postcss": "^5.0.19",
    "postcss-loader": "^0.9.1",
    "react-addons-test-utils": "^15.2.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "redux-devtools": "^3.0.2",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.2",
    "redux-logger": "^2.3.2",
    "redux-saga-test-plan": "^1.3.1",
    "reselect": "^2.0.2",
    "sass-loader": "^3.2.3",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.15",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-hot-middleware": "^2.12.1",
    "webpack-livereload-plugin": "^0.8.0"
  },
  "dependencies": {
    "babel-polyfill": "^6.9.1",
    "bluebird": "^3.0.5",
    "blueimp-md5": "^2.3.0",
    "bowser": "^1.0.0",
    "classnames": "2.2.5",
    "font-awesome": "^4.6.1",
    "history": "^1.17.x",
    "lodash": "^3.10.1",
    "material-ui": "^0.16.6",
    "moment": "^2.10.6",
    "popmotion": "^3.6.2",
    "react": "^15.4.0",
    "react-collapse": "^2.3.0",
    "react-custom-scrollbars": "^4.0.0",
    "react-dom": "^15.2.1",
    "react-height": "^2.1.0",
    "react-motion": "^0.4.2",
    "react-redux": "^4.4.6",
    "react-router": "^2.5.2",
    "react-router-redux": "^4.0.0",
    "react-tap-event-plugin": "^2.0.1",
    "recompose": "^0.19.0",
    "redux": "^3.5.2",
    "redux-saga": "^0.9.5",
    "redux-thunk": "^2.1.0",
    "sass-loader": "^4.0.0",
    "seamless-immutable": "^6.1.1",
    "shortid": "^2.2.6",
    "zenscroll": "3.2.3"
  }
}
```

What could be the problem?

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x] I use a private registry from nexus

**Comment by denverlmartin** [comment] 2017-03-04 00:43
I am experiencing a similar issue:

86938 verbose stack RangeError: Maximum call stack size exceeded
86938 verbose stack     at EventEmitter.get [as globalDir] (/usr/lib/node_modules/npm/lib/npm.js:353:32)
86938 verbose stack     at build.writeBuiltinConf (/usr/lib/node_modules/npm/lib/build.js:81:16)
86938 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/bind-actor.js:15:8)
86938 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:15:14)
86938 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:18:7
86938 verbose stack     at build.linkStuff (/usr/lib/node_modules/npm/lib/build.js:96:53)
86938 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/bind-actor.js:15:8)
86938 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:15:14)
86938 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:20:5)
86938 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/action/build.js:9:3)
86939 verbose cwd /vagrant
86940 error Linux 3.10.0-327.22.2.el7.x86_64
86941 error argv "/usr/bin/node" "/bin/npm" "install" "--no-bin-links"
86942 error node v6.9.4
86943 error npm  v3.10.10
86944 error Maximum call stack size exceeded

**Comment by jinkeeb** [comment] 2017-03-30 18:53
Same error here: 

`1063 verbose stack RangeError: Maximum call stack size exceeded
51063 verbose stack     at Array.filter (native)
51063 verbose stack     at /usr/lib/node_modules/npm/lib/install/actions.js:72:37
51063 verbose stack     at Array.forEach (native)
51063 verbose stack     at markAsFailed (/usr/lib/node_modules/npm/lib/install/actions.js:71:16)
51063 verbose stack     at /usr/lib/node_modules/npm/lib/install/actions.js:74:7
51063 verbose stack     at Array.forEach (native)
51063 verbose stack     at markAsFailed (/usr/lib/node_modules/npm/lib/install/actions.js:71:16)
51063 verbose stack     at /usr/lib/node_modules/npm/lib/install/actions.js:74:7
51063 verbose stack     at Array.forEach (native)
51063 verbose stack     at markAsFailed (/usr/lib/node_modules/npm/lib/install/actions.js:71:16)
51064 verbose cwd /var/www/html/local.magento2.com
51065 error Linux 3.10.0-514.10.2.el7.x86_64
51066 error argv "/usr/bin/node" "/bin/npm" "install"
51067 error node v6.9.4
51068 error npm  v3.10.10
51069 error Maximum call stack size exceeded`

**Comment by legodude17** [comment] 2017-03-31 15:53
Duplicate of #12676.

**Closed** 2017-06-17 04:02 UTC
Labels: bot-closed
