### ISSUE TITLE
Facing below issue

### ISSUE THREAD

**Issue by dsraidu** [npm/npm#16961] opened 2017-06-04 06:19 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

C:\Users\daris>npm install macaca-cli -g
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> devicelog@1.0.2 preinstall C:\Users\daris\AppData\Roaming\npm\node_modules\.staging\devicelog-d4aaf383
> xcodebuild

'xcodebuild' is not recognized as an internal or external command,
operable program or batch file.
- buffer-shims@1.0.0 node_modules\macaca-cli\node_modules\buffer-shims
- commander@2.8.1 node_modules\macaca-cli\node_modules\webdriver-server\node_modules\detect-port\node_modules\commander
C:\Users\daris\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "macaca-cli" "-g"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! devicelog@1.0.2 preinstall: `xcodebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devicelog@1.0.2 preinstall script 'xcodebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the devicelog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xcodebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs devicelog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls devicelog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\daris\npm-debug.log
npm ERR! code 1

**Comment by kenany** [comment] 2017-06-04 13:21
Closing as a duplicate of https://github.com/npm/npm/issues/16960.

**Closed as completed by kenany** 2017-06-04 13:21 UTC
Labels: support
