### ISSUE TITLE
npm install creates empty node_modules folder

### ISSUE THREAD

**Issue by xeoneux** [npm/npm#11967] opened 2016-03-18 21:06 UTC
This might be a really tiny issue, but running `npm install` in a directory without any `package.json` file creates an empty `node_modules` folder.

```
npm WARN enoent ENOENT: no such file or directory, open '/Users/xeoneux/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
```

I'm using version `3.8.2`

**Comment by IAmAnubhavSaini** [comment] 2016-03-19 08:08
Same for 3.7.3

**Comment by iyogeshjoshi** [comment] 2016-03-19 10:32
:+1:  Yep I also checked it. Happening same for me in version `3.8.2`. I guess they forgot to delete the folder while reverting.

**Comment by zkat** [comment] 2016-03-24 23:53
This is a regression from `npm@2`, I think. I think we took a patch at one point to do this, but I can't seem to find it.

**Comment by xeoneux** [comment] 2016-04-27 09:36
@zkat - Did you get time to find it? 😄

**Comment by davidrissato** [comment] 2016-09-15 16:29
In my opinion, npm should not leave an empty `node_modules` folder even when you have a `package.json` that declare no dependencies. 

I noticed that npm uses `node_modules` folder during its processing even when there is no `packages.json`. I believe this is the reason this directory gets created.

Running `npm --verbose install` in an empty directory produce these lines:

```
...
/Users/david/testnpm/node_modules/.staging
npm verb unlock done using /Users/david/.npm/_locks/staging-90db8ded1da867d0.lock for /Users/david/testnpm/node_modules/.staging
...
```

Considering even those files are removed at the end of npm execution, I suggest npm should just remove `node_modules` folder before exiting when it detects that this folder is empty.

**Comment by legodude17** [comment] 2016-09-23 17:34
That makes sense to me @davidrissato.

**Comment by akeating** [comment] 2016-11-12 14:43
My use case is this: I have a root directory with a package.json primarily for scripting and no defined dependencies. One of the child application directories contains a package.json and all the dependency definitions. `npm install` in root simply calls a script that in part calls npm install in the sub-directory. An empty `node_modules` directory is created in the root directory. It is ignored by git but seems an unnecessary artifact, kind of like a build script that doesn't cleanup after itself.

**Comment by CezaryDanielNowak** [comment] 2017-01-26 14:35
Check if there is `.staging` directory inside node_modules and
https://github.com/npm/npm/issues/12540

**Comment by pkunal9** [comment] 2017-03-25 18:20
Same with version 4.0.5

**Comment by umair-khanzada** [comment] 2017-04-20 18:18
Anyone have resolve this issue ???

**Comment by umair-khanzada** [comment] 2017-04-20 18:56
`npm cache clean` and than `npm install` works for me 💃 💃 💃

**Comment by saurabhshr123** [comment] 2017-05-24 09:55
Works for me thanks....

**Comment by martin-sweeny** [comment] 2018-05-31 19:51
@umair-khanzada Did not work for me.

**Comment by zkat** [comment] 2018-05-31 20:46
I'm going to close this, as I can't reproduce this with the latest npm. If anyone can still reproduce this **using `npm@latest`**, then feel free to file a new bug with a detailed repro over in https://npm.community/c/bugs. Otherwise, I'm going to consider this resolved.

**Closed by zkat** 2018-05-31 20:46 UTC
Labels: bug
