### ISSUE TITLE
npm search has been broken for days

### ISSUE THREAD

**Issue by geuis** [npm/npm#13310] opened 2016-07-07 08:24 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm search <term>` has been broken for days. This has been occurring across multiple devices and multiple networks.

Just to completely verify, I did a completely fresh installation of both homebrew and then node 6.3.0. 

`npm search <term>` is producing these results:

```
geuis-macbook-pro:apps geuis$ npm search hapi
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "search" "hapi"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

  142756 ms: Mark-sweep 871.9 (1137.5) -> 846.0 (1122.1) MB, 752.6 / 0 ms [allocation failure] [GC in old space requested].
  143529 ms: Mark-sweep 846.0 (1122.1) -> 846.0 (1126.1) MB, 773.6 / 0 ms [allocation failure] [GC in old space requested].
  144334 ms: Mark-sweep 846.0 (1126.1) -> 846.0 (1118.1) MB, 805.0 / 0 ms [last resort gc].
  145145 ms: Mark-sweep 846.0 (1118.1) -> 845.9 (1111.1) MB, 810.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x34c62f1c9e59 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x3edc0ced2230] (this=0x34c62f104189 <undefined>,string=0x78cfeadcdd9 <Very long string[181392993]>,encoding=0x34c62f1d7a49 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x3edc0cea8516] (this=0x7d108ce1e09 <JS Function Buffer (SharedFunctionInfo 0x34c62f1e3541)>,value=0x78cfeadcdd9 <Very long string[181392993]>,encodingOrOffset=0x34c62f1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x3edc0c80961b
Abort trap: 6
geuis-macbook-pro:apps geuis$ 
```

#### How can the CLI team reproduce the problem?

Try searching for something with the latest release version of npm.

npm-debug.log:
geuis-macbook-pro:apps charleslawrence$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'search',
1 verbose cli   'hapi' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.npmjs.org/-/all
9 info updateIndex /Users/charleslawrence/.npm/registry.npmjs.org/-/all/.cache.json
10 verbose correctMkdir /Users/charleslawrence/.npm correctMkdir not in flight; initializing
11 verbose stack TypeError: Cannot read property '_updated' of undefined
11 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/update-index.js:61:26
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
11 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
12 verbose cwd /usr/local/apps
13 error Darwin 15.5.0
14 error argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "search" "hapi"
15 error node v6.3.0
16 error npm  v3.10.3
17 error Cannot read property '_updated' of undefined
18 error If you need help, you may report this error at:
18 error     <https://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]
geuis-macbook-pro:apps charleslawrence$ 

### supporting information:
OS X
node 6.3.0
npm 3.10.3

**Comment by ocoka** [comment] 2016-07-07 10:29
+1 Same here


13:27 $ npm search karma
npm WARN Building the local index for the first time, please be patient
[..................] | : WARN Building the local index for the first time, please be patient
<--- Last few GCs --->

   62012 ms: Mark-sweep 872.4 (1137.5) -> 846.3 (1120.1) MB, 646.6 / 0 ms [allocation failure] [GC in old space requested].
   62694 ms: Mark-sweep 846.3 (1120.1) -> 846.2 (1122.1) MB, 681.6 / 0 ms [allocation failure] [GC in old space requested].
   63474 ms: Mark-sweep 846.2 (1122.1) -> 846.2 (1115.1) MB, 780.3 / 0 ms [last resort gc].
   64275 ms: Mark-sweep 846.2 (1115.1) -> 846.1 (1109.1) MB, 800.9 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1ef1361c9e59 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x2edbbb757bf0] (this=0x1ef136104189 <undefined>,string=0x3f519f00cf49 <Very long string[181417634]>,encoding=0x1ef1361d7a49 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x2edbbb73a056] (this=0x3c3e4a2e2af9 <JS Function Buffer (SharedFunctionInfo 0x1ef1361e2f51)>,value=0x3f519f00cf49 <Very long string[181417634]>,encodingOrOffset=0x1ef1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [npm]
 2: 0xff17dc [npm]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [npm]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
13: 0x9cdfca [npm]
14: 0x9ce3dc [npm]
15: 0x2edbbaf0961b

**Comment by reach4thelasers** [comment] 2016-07-09 23:25
I have not been able to do a search from npm for MONTHS.  I was on 6.2.1 for a while, and to my joy saw that 6.3.0 was out.... I had a "they fixed the search" moment...  But it was short-lived - same Javascript out of memory bs

**Comment by reach4thelasers** [comment] 2016-07-09 23:27
I've been using this for the last few months: https://npmsearch.com/

**Comment by Sampo123** [comment] 2016-07-14 10:40
Isn't this kind of bad? I got this same going on and it is kind of annoying.

**Comment by mspaulding06** [comment] 2016-07-16 02:33
Yep, I'm running into the same problem as well.  Using the same version as stated above (npm 3.10.3 and node 6.3.0 on macosx).

**Comment by vsemozhetbyt** [comment] 2016-07-23 12:10
Windows 7 x64
node: 6.3.1
npm 3.10.3
```
npm search jsdom
npm WARN Building the local index for the first time, please be patient
[..................] / : WARN Building the local index for the first time, please be patient
<--- Last few GCs --->

   79633 ms: Mark-sweep 879.4 (1143.6) -> 877.6 (1148.6) MB, 1115.8 / 0 ms (+ 77.3 ms in 166 steps since start of marking, biggest step 13.7 ms) [allocation failure] [GC in old space requested].
   81064 ms: Mark-sweep 877.6 (1148.6) -> 852.4 (1132.1) MB, 1431.0 / 0 ms [allocation failure] [GC in old space requested].
   82512 ms: Mark-sweep 852.4 (1132.1) -> 852.4 (1124.1) MB, 1448.0 / 0 ms [last resort gc].
   83997 ms: Mark-sweep 852.4 (1124.1) -> 852.3 (1117.1) MB, 1484.9 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000288098C9E51 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=000001FB5C5E0610] (this=0000028809804189 <undefined>,string=0000011DD428CE29 <Very long string[185622728]>,encoding=00000288098D6359 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=000001FB5C5CA556] (this=0000033C780ADC29 <JS Function Buffer (SharedFunctionInfo 00000288098E3899)>,value=0000011DD428CE29 <Verylong string[185622728]>,encod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by vsemozhetbyt** [comment] 2016-07-23 12:14
Is there a way to set `--max_old_space_size` for `node` in such calls?

**Comment by vsemozhetbyt** [comment] 2016-07-23 15:54
I've just edited the last line of `c:\Program Files\nodejs\npm.cmd` like this:
```
"%NODE_EXE%" "--max_old_space_size=4096" "%NPM_CLI_JS%" %*
```
And it runs OK. However, `npm search <name>` takes ~ 2.3 GB of memory.

**Comment by othiym23** [comment] 2016-07-28 00:42
Closing as duplicate of #12619. Please see that issue for broader context and discussion. The CLI team and npm is no more pleased about the state of search than anyone else, but there's a ways to go until the problem can be addressed systematically. Thanks to all for their time.

**Closed by othiym23** 2016-07-28 00:42 UTC
Labels: search
