### ISSUE TITLE
npm ERR! Linux 3.13.0-49-generic (npm init)

### ISSUE THREAD

**Issue by ketul87** [npm/npm#8022] opened 2015-04-21 09:46 UTC
```
ketul@ketul-Veriton-M200-A55:~/Desktop/workspace/Development/RestAPI$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (RestAPI) 
npm ERR! Linux 3.13.0-49-generic
npm ERR! argv "node" "/usr/local/bin/npm" "init"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.4

npm ERR! Cannot read property 'join' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ketul/Desktop/workspace/Development/RestAPI/npm-debug.log
```

**Comment by KenanY** [comment] 2015-04-21 12:40
> `name: (RestAPI) `

Package names cannot have capital letters. Duplicate of https://github.com/npm/npm/issues/7927, https://github.com/npm/init-package-json/issues/37.

**Comment by othiym23** [comment] 2015-07-08 17:48
Closing as a duplicate (and also as since resolved, by better error messaging and re-prompting).

**Closed by othiym23** 2015-07-08 17:48 UTC
Labels: support
