### ISSUE TITLE
shasum check failed for C:\Users\a639361\AppData\Local\Temp\npm-15932-f

### ISSUE THREAD

**Issue by sandercl** [npm/npm#14086] opened 2016-09-27 00:08 UTC
#### I'm opening this issue because:
- [ ] npm is crashing.
- [X] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I pulled node-v6.6.0-x64.msi from https://nodejs.org/en/download/ and installed with no issues.
then I ran 'npm install -g angular-cli' from command line and got:
npm ERR! shasum check failed for C:\Users\a639361\AppData\Local\Temp\npm-15932-f
 @e4f2e48\registry.npmjs.org\rxjs-\rxjs-5.0.0-beta.12.tgz
Windows 7 Enterprise SP1
[npm-debug.log.txt](https://github.com/npm/npm/files/494311/npm-debug.log.txt)
#### How can the CLI team reproduce the problem?

This was a standard install of nodejs.

### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2016-12-09 00:37
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:37 UTC
Labels: shasum, support
