### ISSUE TITLE
npm ERR! shasum check failed for /tmp/npm-1005-db72d058/registry.npmjs.org/ionic/-/ionic-2.1.1.tgz

### ISSUE THREAD

**Issue by sytlnrf** [npm/npm#14312] opened 2016-10-18 03:23 UTC
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for /tmp/npm-1005-db72d058/registry.npmjs.org/ionic/-/ionic-2.1.1.tgz
npm ERR! Expected: 7345b56915da2100a0efcd5257a4626848c4da80
npm ERR! Actual:   876c5875bb5428dac2905526a7ce66f0dcd90a4a
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.1.tgz
npm ERR!

**Comment by watilde** [comment] 2016-10-18 08:00
Hi! Could you please give us more detail, like `npm-debug.log` ? Potentially, `npm cache clear` can resolve this issue.

**Comment by zkat** [comment] 2016-12-02 09:24
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps. This might well have to do with the Great Firewall.

**Closed by zkat** 2016-12-02 09:24 UTC
Labels: network, proxy, shasum, support
