### ISSUE TITLE
User defined registry swaps to registry.npmjs.org part way through install 

### ISSUE THREAD

**Issue by busches** [npm/npm#12319] opened 2016-04-12 14:39 UTC
**Summary**: When running `npm install` with a user defined registry, I see the user defined registry being used and then it will swap back to to `registry.npmjs.org` which will fail to download due to the corporate proxy.

**Details**:
I'm using npm `3.8.6` with node `5.10.0` on Windows 7x64. I have the following config settings:
```
; cli configs
user-agent = "npm/3.8.6 node/v5.10.0 win32 x64"

; userconfig C:\Users\buschs1\.npmrc
registry = "http://nexusrepo/nexus/content/groups/npm/"

; globalconfig C:\Program Files\nodejs\etc\npmrc
prefix = "C:\\Users\\buschs1\\AppData\\Roaming\\npm"
```

Running with `-ddd` I see the correct registry being used multiple times and it's not until line 6818, that I see it swap to `registry.npmjs.org` with the following command: 
`npm sill fetchPackageMetaData amdefine@https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz`
Which eventually results in the following error: 
`npm info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443`
This is the first mention of `amdefine` in the log. 

You can find the entire log at this gist https://gist.github.com/busches/127f57d08da718a4f66b0f2f90d34809

**Comment by othiym23** [comment] 2016-04-12 17:59
```
npm sill addShrinkwrap Completed reading shrinkwrap in webdriverio
```

Due to npm shrinkwrap's intent, it is set up to pull down the exact tarballs, from the exact registry, that was used when the shrinkwrap file was created.  In this case, that's the primary registry. (This is part of the reason why we suggest that users not shrinkwrap libraries or frameworks.) This is by design. If you want to bypass that behavior, include `--ignore-shrinkwrap` on the command line when running `npm install`. You also might want to pull down `webdriverio` and republish it to your local Nexus registry without the shrinkwrap file so that using `--ignore-shrinkwrap` isn't required in the future.

As this is the intended behavior for shrinkwrap files, I'm going to close this issue. Thanks for your time!

**Closed by othiym23** 2016-04-12 17:59 UTC
Labels: registry, shrinkwrap, support

**Comment by busches** [comment] 2016-04-12 18:33
Thanks @othiym23, wasn't aware of that option!
