### ISSUE TITLE
npm install -g cordova error

### ISSUE THREAD

**Issue by kzpromo** [npm/npm#13169] opened 2016-06-24 12:47 UTC
error log
[npm-debug.log.txt](https://github.com/npm/npm/files/331749/npm-debug.log.txt)

**Comment by eliaslfox** [comment] 2016-06-25 21:38
Hey @kzpromo 
The error you got was, `EBUSY: resource busy or locked`. This is caused by npm trying to delete files which are open in another program. The solution as suggested [here](https://github.com/npm/npm/issues/12065) is to close all other programs which have the files(s) open. This includes other terminals and editor windows.

**Comment by othiym23** [comment] 2016-08-19 22:36
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 22:36 UTC
Labels: support
