### ISSUE TITLE
cordova isn't installing on windows 10. I need help urgently.

### ISSUE THREAD

**Issue by delastepz** [npm/npm#11662] opened 2016-02-24 16:03 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\Dela\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@3.7.3
3 info using node@v4.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchNamedPackageData cordova
9 silly mapToRegistry name cordova
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/cordova
13 verbose request uri https://registry.npmjs.org/cordova
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:56:05 PM
16 verbose request id c5d965d5dcebce84
17 verbose etag "D4LSYY2HK3ZTV0W0SXIQE1GRX"
18 http request GET https://registry.npmjs.org/cordova
19 http 304 https://registry.npmjs.org/cordova
20 verbose headers { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"D4LSYY2HK3ZTV0W0SXIQE1GRX"',
20 verbose headers   age: '266',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lcy1128-LCY',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1456329377.357110,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"D4LSYY2HK3ZTV0W0SXIQE1GRX"',
21 silly get     age: '266',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lcy1128-LCY',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1456329377.357110,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/cordova from cache
23 verbose get saving cordova to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\cordova.cache.json
24 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule cordova@6.0.0 checking installable status
38 silly cache add args [ 'cordova', null ]
39 verbose cache add spec cordova
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'cordova',
40 silly cache add   scope: null,
40 silly cache add   name: 'cordova',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: 'latest',
40 silly cache add   type: 'tag' }
41 silly addNamed cordova@latest
42 verbose addNamed "latest" is being treated as a dist-tag for cordova
43 info addNameTag [ 'cordova', 'latest' ]
44 silly mapToRegistry name cordova
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/cordova
48 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
49 verbose get https://registry.npmjs.org/cordova not expired, no request
50 silly addNameTag next cb for cordova with tag latest
51 silly addNamed cordova@6.0.0
52 verbose addNamed "6.0.0" is a plain semver version for cordova
53 silly cache afterAdd cordova@6.0.0
54 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\cordova\6.0.0\package\package.json not in flight; writing
55 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
56 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\cordova\6.0.0\package\package.json written
57 silly fetchNamedPackageData ansi
58 silly mapToRegistry name ansi
59 silly mapToRegistry using default registry
60 silly mapToRegistry registry https://registry.npmjs.org/
61 silly mapToRegistry uri https://registry.npmjs.org/ansi
62 silly fetchNamedPackageData cordova-lib
63 silly mapToRegistry name cordova-lib
64 silly mapToRegistry using default registry
65 silly mapToRegistry registry https://registry.npmjs.org/
66 silly mapToRegistry uri https://registry.npmjs.org/cordova-lib
67 silly fetchNamedPackageData q
68 silly mapToRegistry name q
69 silly mapToRegistry using default registry
70 silly mapToRegistry registry https://registry.npmjs.org/
71 silly mapToRegistry uri https://registry.npmjs.org/q
72 silly fetchNamedPackageData nopt
73 silly mapToRegistry name nopt
74 silly mapToRegistry using default registry
75 silly mapToRegistry registry https://registry.npmjs.org/
76 silly mapToRegistry uri https://registry.npmjs.org/nopt
77 silly fetchNamedPackageData underscore
78 silly mapToRegistry name underscore
79 silly mapToRegistry using default registry
80 silly mapToRegistry registry https://registry.npmjs.org/
81 silly mapToRegistry uri https://registry.npmjs.org/underscore
82 silly fetchNamedPackageData update-notifier
83 silly mapToRegistry name update-notifier
84 silly mapToRegistry using default registry
85 silly mapToRegistry registry https://registry.npmjs.org/
86 silly mapToRegistry uri https://registry.npmjs.org/update-notifier
87 verbose request uri https://registry.npmjs.org/ansi
88 verbose request no auth needed
89 info attempt registry request try #1 at 3:56:06 PM
90 verbose etag "1AT5UJ80MK2VK1QM4MWWIBZ43"
91 http request GET https://registry.npmjs.org/ansi
92 verbose request uri https://registry.npmjs.org/cordova-lib
93 verbose request no auth needed
94 info attempt registry request try #1 at 3:56:06 PM
95 verbose etag "9GKNWAQPV4K0X3R8NWG6KUZ6V"
96 http request GET https://registry.npmjs.org/cordova-lib
97 verbose request uri https://registry.npmjs.org/q
98 verbose request no auth needed
99 info attempt registry request try #1 at 3:56:06 PM
100 verbose etag "51R0MQHM5CBV9OGE6AARQI25"
101 http request GET https://registry.npmjs.org/q
102 verbose request uri https://registry.npmjs.org/nopt
103 verbose request no auth needed
104 info attempt registry request try #1 at 3:56:06 PM
105 verbose etag "EOZTX9OIF152XUTZOK5DSHSTH"
106 http request GET https://registry.npmjs.org/nopt
107 verbose request uri https://registry.npmjs.org/underscore
108 verbose request no auth needed
109 info attempt registry request try #1 at 3:56:06 PM
110 verbose etag "EFYS9G68FCSBB8P69WUIM6YME"
111 http request GET https://registry.npmjs.org/underscore
112 verbose request uri https://registry.npmjs.org/update-notifier
113 verbose request no auth needed
114 info attempt registry request try #1 at 3:56:06 PM
115 verbose etag "CWCZEVSXDDOKGZJJ4R86ZCYNL"
116 http request GET https://registry.npmjs.org/update-notifier
117 http 304 https://registry.npmjs.org/q
118 verbose headers { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
118 verbose headers   via: '1.1 varnish',
118 verbose headers   'cache-control': 'max-age=300',
118 verbose headers   etag: '"51R0MQHM5CBV9OGE6AARQI25"',
118 verbose headers   age: '130',
118 verbose headers   connection: 'keep-alive',
118 verbose headers   'x-served-by': 'cache-lcy1126-LCY',
118 verbose headers   'x-cache': 'HIT',
118 verbose headers   'x-cache-hits': '6',
118 verbose headers   'x-timer': 'S1456329377.967774,VS0,VE0',
118 verbose headers   vary: 'Accept' }
119 silly get cb [ 304,
119 silly get   { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
119 silly get     via: '1.1 varnish',
119 silly get     'cache-control': 'max-age=300',
119 silly get     etag: '"51R0MQHM5CBV9OGE6AARQI25"',
119 silly get     age: '130',
119 silly get     connection: 'keep-alive',
119 silly get     'x-served-by': 'cache-lcy1126-LCY',
119 silly get     'x-cache': 'HIT',
119 silly get     'x-cache-hits': '6',
119 silly get     'x-timer': 'S1456329377.967774,VS0,VE0',
119 silly get     vary: 'Accept' } ]
120 verbose etag https://registry.npmjs.org/q from cache
121 verbose get saving q to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\q.cache.json
122 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
123 http 304 https://registry.npmjs.org/update-notifier
124 verbose headers { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
124 verbose headers   via: '1.1 varnish',
124 verbose headers   'cache-control': 'max-age=300',
124 verbose headers   etag: '"CWCZEVSXDDOKGZJJ4R86ZCYNL"',
124 verbose headers   age: '293',
124 verbose headers   connection: 'keep-alive',
124 verbose headers   'x-served-by': 'cache-lcy1124-LCY',
124 verbose headers   'x-cache': 'HIT',
124 verbose headers   'x-cache-hits': '1',
124 verbose headers   'x-timer': 'S1456329377.987774,VS0,VE0',
124 verbose headers   vary: 'Accept' }
125 silly get cb [ 304,
125 silly get   { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
125 silly get     via: '1.1 varnish',
125 silly get     'cache-control': 'max-age=300',
125 silly get     etag: '"CWCZEVSXDDOKGZJJ4R86ZCYNL"',
125 silly get     age: '293',
125 silly get     connection: 'keep-alive',
125 silly get     'x-served-by': 'cache-lcy1124-LCY',
125 silly get     'x-cache': 'HIT',
125 silly get     'x-cache-hits': '1',
125 silly get     'x-timer': 'S1456329377.987774,VS0,VE0',
125 silly get     vary: 'Accept' } ]
126 verbose etag https://registry.npmjs.org/update-notifier from cache
127 verbose get saving update-notifier to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\update-notifier.cache.json
128 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
129 http 304 https://registry.npmjs.org/ansi
130 verbose headers { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
130 verbose headers   via: '1.1 varnish',
130 verbose headers   'cache-control': 'max-age=300',
130 verbose headers   etag: '"1AT5UJ80MK2VK1QM4MWWIBZ43"',
130 verbose headers   age: '216',
130 verbose headers   connection: 'keep-alive',
130 verbose headers   'x-served-by': 'cache-lcy1120-LCY',
130 verbose headers   'x-cache': 'HIT',
130 verbose headers   'x-cache-hits': '6',
130 verbose headers   'x-timer': 'S1456329377.991966,VS0,VE0',
130 verbose headers   vary: 'Accept' }
131 silly get cb [ 304,
131 silly get   { date: 'Wed, 24 Feb 2016 15:56:17 GMT',
131 silly get     via: '1.1 varnish',
131 silly get     'cache-control': 'max-age=300',
131 silly get     etag: '"1AT5UJ80MK2VK1QM4MWWIBZ43"',
131 silly get     age: '216',
131 silly get     connection: 'keep-alive',
131 silly get     'x-served-by': 'cache-lcy1120-LCY',
131 silly get     'x-cache': 'HIT',
131 silly get     'x-cache-hits': '6',
131 silly get     'x-timer': 'S1456329377.991966,VS0,VE0',
131 silly get     vary: 'Accept' } ]
132 verbose etag https://registry.npmjs.org/ansi from cache
133 verbose get saving ansi to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\ansi.cache.json
134 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
135 silly resolveWithNewModule q@1.0.1 checking installable status
136 silly cache add args [ 'q@1.0.1', null ]
137 verbose cache add spec q@1.0.1
138 silly cache add parsed spec Result {
138 silly cache add   raw: 'q@1.0.1',
138 silly cache add   scope: null,
138 silly cache add   name: 'q',
138 silly cache add   rawSpec: '1.0.1',
138 silly cache add   spec: '1.0.1',
138 silly cache add   type: 'version' }
139 silly addNamed q@1.0.1
140 verbose addNamed "1.0.1" is a plain semver version for q
141 silly mapToRegistry name q
142 silly mapToRegistry using default registry
143 silly mapToRegistry registry https://registry.npmjs.org/
144 silly mapToRegistry uri https://registry.npmjs.org/q
145 verbose addNameVersion registry:https://registry.npmjs.org/q not in flight; fetching
146 http 304 https://registry.npmjs.org/cordova-lib
147 verbose headers { date: 'Wed, 24 Feb 2016 15:56:19 GMT',
147 verbose headers   via: '1.1 varnish',
147 verbose headers   'cache-control': 'max-age=300',
147 verbose headers   etag: '"9GKNWAQPV4K0X3R8NWG6KUZ6V"',
147 verbose headers   age: '27',
147 verbose headers   connection: 'keep-alive',
147 verbose headers   'x-served-by': 'cache-lcy1130-LCY',
147 verbose headers   'x-cache': 'HIT',
147 verbose headers   'x-cache-hits': '1',
147 verbose headers   'x-timer': 'S1456329379.322151,VS0,VE0',
147 verbose headers   vary: 'Accept' }
148 silly get cb [ 304,
148 silly get   { date: 'Wed, 24 Feb 2016 15:56:19 GMT',
148 silly get     via: '1.1 varnish',
148 silly get     'cache-control': 'max-age=300',
148 silly get     etag: '"9GKNWAQPV4K0X3R8NWG6KUZ6V"',
148 silly get     age: '27',
148 silly get     connection: 'keep-alive',
148 silly get     'x-served-by': 'cache-lcy1130-LCY',
148 silly get     'x-cache': 'HIT',
148 silly get     'x-cache-hits': '1',
148 silly get     'x-timer': 'S1456329379.322151,VS0,VE0',
148 silly get     vary: 'Accept' } ]
149 verbose etag https://registry.npmjs.org/cordova-lib from cache
150 verbose get saving cordova-lib to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\cordova-lib.cache.json
151 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
152 verbose get https://registry.npmjs.org/q not expired, no request
153 silly resolveWithNewModule ansi@0.3.1 checking installable status
154 silly cache add args [ 'ansi@^0.3.0', null ]
155 verbose cache add spec ansi@^0.3.0
156 silly cache add parsed spec Result {
156 silly cache add   raw: 'ansi@^0.3.0',
156 silly cache add   scope: null,
156 silly cache add   name: 'ansi',
156 silly cache add   rawSpec: '^0.3.0',
156 silly cache add   spec: '>=0.3.0 <0.4.0',
156 silly cache add   type: 'range' }
157 silly addNamed ansi@>=0.3.0 <0.4.0
158 verbose addNamed ">=0.3.0 <0.4.0" is a valid semver range for ansi
159 silly addNameRange { name: 'ansi', range: '>=0.3.0 <0.4.0', hasData: false }
160 silly mapToRegistry name ansi
161 silly mapToRegistry using default registry
162 silly mapToRegistry registry https://registry.npmjs.org/
163 silly mapToRegistry uri https://registry.npmjs.org/ansi
164 verbose addNameRange registry:https://registry.npmjs.org/ansi not in flight; fetching
165 silly resolveWithNewModule update-notifier@0.5.0 checking installable status
166 silly cache add args [ 'update-notifier@^0.5.0', null ]
167 verbose cache add spec update-notifier@^0.5.0
168 silly cache add parsed spec Result {
168 silly cache add   raw: 'update-notifier@^0.5.0',
168 silly cache add   scope: null,
168 silly cache add   name: 'update-notifier',
168 silly cache add   rawSpec: '^0.5.0',
168 silly cache add   spec: '>=0.5.0 <0.6.0',
168 silly cache add   type: 'range' }
169 silly addNamed update-notifier@>=0.5.0 <0.6.0
170 verbose addNamed ">=0.5.0 <0.6.0" is a valid semver range for update-notifier
171 silly addNameRange { name: 'update-notifier',
171 silly addNameRange   range: '>=0.5.0 <0.6.0',
171 silly addNameRange   hasData: false }
172 silly mapToRegistry name update-notifier
173 silly mapToRegistry using default registry
174 silly mapToRegistry registry https://registry.npmjs.org/
175 silly mapToRegistry uri https://registry.npmjs.org/update-notifier
176 verbose addNameRange registry:https://registry.npmjs.org/update-notifier not in flight; fetching
177 silly cache afterAdd q@1.0.1
178 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\q\1.0.1\package\package.json not in flight; writing
179 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
180 silly resolveWithNewModule cordova-lib@6.0.0 checking installable status
181 silly cache add args [ 'cordova-lib@6.0.0', null ]
182 verbose cache add spec cordova-lib@6.0.0
183 silly cache add parsed spec Result {
183 silly cache add   raw: 'cordova-lib@6.0.0',
183 silly cache add   scope: null,
183 silly cache add   name: 'cordova-lib',
183 silly cache add   rawSpec: '6.0.0',
183 silly cache add   spec: '6.0.0',
183 silly cache add   type: 'version' }
184 silly addNamed cordova-lib@6.0.0
185 verbose addNamed "6.0.0" is a plain semver version for cordova-lib
186 silly mapToRegistry name cordova-lib
187 silly mapToRegistry using default registry
188 silly mapToRegistry registry https://registry.npmjs.org/
189 silly mapToRegistry uri https://registry.npmjs.org/cordova-lib
190 verbose addNameVersion registry:https://registry.npmjs.org/cordova-lib not in flight; fetching
191 verbose get https://registry.npmjs.org/ansi not expired, no request
192 silly addNameRange number 2 { name: 'ansi', range: '>=0.3.0 <0.4.0', hasData: true }
193 silly addNameRange versions [ 'ansi',
193 silly addNameRange   [ '0.0.1',
193 silly addNameRange     '0.0.2',
193 silly addNameRange     '0.0.3',
193 silly addNameRange     '0.0.4',
193 silly addNameRange     '0.1.0',
193 silly addNameRange     '0.1.1',
193 silly addNameRange     '0.1.2',
193 silly addNameRange     '0.2.0',
193 silly addNameRange     '0.2.1',
193 silly addNameRange     '0.3.0',
193 silly addNameRange     '0.3.1' ] ]
194 silly addNamed ansi@0.3.1
195 verbose addNamed "0.3.1" is a plain semver version for ansi
196 verbose get https://registry.npmjs.org/update-notifier not expired, no request
197 silly addNameRange number 2 { name: 'update-notifier',
197 silly addNameRange   range: '>=0.5.0 <0.6.0',
197 silly addNameRange   hasData: true }
198 silly addNameRange versions [ 'update-notifier',
198 silly addNameRange   [ '0.1.0',
198 silly addNameRange     '0.1.1',
198 silly addNameRange     '0.1.2',
198 silly addNameRange     '0.1.3',
198 silly addNameRange     '0.1.4',
198 silly addNameRange     '0.1.5',
198 silly addNameRange     '0.1.6',
198 silly addNameRange     '0.1.7',
198 silly addNameRange     '0.1.8',
198 silly addNameRange     '0.1.9',
198 silly addNameRange     '0.1.10',
198 silly addNameRange     '0.2.0',
198 silly addNameRange     '0.2.1',
198 silly addNameRange     '0.2.2',
198 silly addNameRange     '0.3.0',
198 silly addNameRange     '0.3.1',
198 silly addNameRange     '0.3.2',
198 silly addNameRange     '0.4.0',
198 silly addNameRange     '0.5.0',
198 silly addNameRange     '0.6.0' ] ]
199 silly addNamed update-notifier@0.5.0
200 verbose addNamed "0.5.0" is a plain semver version for update-notifier
201 verbose get https://registry.npmjs.org/cordova-lib not expired, no request
202 silly mapToRegistry name cordova-lib
203 silly mapToRegistry using default registry
204 silly mapToRegistry registry https://registry.npmjs.org/
205 silly mapToRegistry uri https://registry.npmjs.org/cordova-lib
206 verbose addRemoteTarball https://registry.npmjs.org/cordova-lib/-/cordova-lib-6.0.0.tgz not in flight; adding
207 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova-lib/-/cordova-lib-6.0.0.tgz',
207 verbose addRemoteTarball   '5bf498ae04fbcf2ff04f8cbfb594ee681f93c714' ]
208 silly cache afterAdd ansi@0.3.1
209 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\ansi\0.3.1\package\package.json not in flight; writing
210 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
211 silly cache afterAdd update-notifier@0.5.0
212 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\update-notifier\0.5.0\package\package.json not in flight; writing
213 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
214 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\q\1.0.1\package\package.json written
215 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\ansi\0.3.1\package\package.json written
216 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\update-notifier\0.5.0\package\package.json written
217 info retry fetch attempt 1 at 3:56:10 PM
218 info attempt registry request try #1 at 3:56:10 PM
219 http fetch GET https://registry.npmjs.org/cordova-lib/-/cordova-lib-6.0.0.tgz
220 http fetch 200 https://registry.npmjs.org/cordova-lib/-/cordova-lib-6.0.0.tgz
221 http 304 https://registry.npmjs.org/underscore
222 verbose headers { date: 'Wed, 24 Feb 2016 15:56:22 GMT',
222 verbose headers   via: '1.1 varnish',
222 verbose headers   'cache-control': 'max-age=300',
222 verbose headers   etag: '"EFYS9G68FCSBB8P69WUIM6YME"',
222 verbose headers   age: '196',
222 verbose headers   connection: 'keep-alive',
222 verbose headers   'x-served-by': 'cache-lcy1123-LCY',
222 verbose headers   'x-cache': 'HIT',
222 verbose headers   'x-cache-hits': '17',
222 verbose headers   'x-timer': 'S1456329382.179819,VS0,VE0',
222 verbose headers   vary: 'Accept' }
223 silly get cb [ 304,
223 silly get   { date: 'Wed, 24 Feb 2016 15:56:22 GMT',
223 silly get     via: '1.1 varnish',
223 silly get     'cache-control': 'max-age=300',
223 silly get     etag: '"EFYS9G68FCSBB8P69WUIM6YME"',
223 silly get     age: '196',
223 silly get     connection: 'keep-alive',
223 silly get     'x-served-by': 'cache-lcy1123-LCY',
223 silly get     'x-cache': 'HIT',
223 silly get     'x-cache-hits': '17',
223 silly get     'x-timer': 'S1456329382.179819,VS0,VE0',
223 silly get     vary: 'Accept' } ]
224 verbose etag https://registry.npmjs.org/underscore from cache
225 verbose get saving underscore to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\underscore\.cache.json
226 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
227 silly resolveWithNewModule underscore@1.7.0 checking installable status
228 silly cache add args [ 'underscore@1.7.0', null ]
229 verbose cache add spec underscore@1.7.0
230 silly cache add parsed spec Result {
230 silly cache add   raw: 'underscore@1.7.0',
230 silly cache add   scope: null,
230 silly cache add   name: 'underscore',
230 silly cache add   rawSpec: '1.7.0',
230 silly cache add   spec: '1.7.0',
230 silly cache add   type: 'version' }
231 silly addNamed underscore@1.7.0
232 verbose addNamed "1.7.0" is a plain semver version for underscore
233 silly mapToRegistry name underscore
234 silly mapToRegistry using default registry
235 silly mapToRegistry registry https://registry.npmjs.org/
236 silly mapToRegistry uri https://registry.npmjs.org/underscore
237 verbose addNameVersion registry:https://registry.npmjs.org/underscore not in flight; fetching
238 verbose get https://registry.npmjs.org/underscore not expired, no request
239 silly cache afterAdd underscore@1.7.0
240 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\underscore\1.7.0\package\package.json not in flight; writing
241 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
242 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\underscore\1.7.0\package\package.json written
243 http 304 https://registry.npmjs.org/nopt
244 verbose headers { date: 'Wed, 24 Feb 2016 15:56:28 GMT',
244 verbose headers   via: '1.1 varnish',
244 verbose headers   'cache-control': 'max-age=300',
244 verbose headers   etag: '"EOZTX9OIF152XUTZOK5DSHSTH"',
244 verbose headers   age: '74',
244 verbose headers   connection: 'keep-alive',
244 verbose headers   'x-served-by': 'cache-lcy1126-LCY',
244 verbose headers   'x-cache': 'HIT',
244 verbose headers   'x-cache-hits': '8',
244 verbose headers   'x-timer': 'S1456329388.121322,VS0,VE0',
244 verbose headers   vary: 'Accept' }
245 silly get cb [ 304,
245 silly get   { date: 'Wed, 24 Feb 2016 15:56:28 GMT',
245 silly get     via: '1.1 varnish',
245 silly get     'cache-control': 'max-age=300',
245 silly get     etag: '"EOZTX9OIF152XUTZOK5DSHSTH"',
245 silly get     age: '74',
245 silly get     connection: 'keep-alive',
245 silly get     'x-served-by': 'cache-lcy1126-LCY',
245 silly get     'x-cache': 'HIT',
245 silly get     'x-cache-hits': '8',
245 silly get     'x-timer': 'S1456329388.121322,VS0,VE0',
245 silly get     vary: 'Accept' } ]
246 verbose etag https://registry.npmjs.org/nopt from cache
247 verbose get saving nopt to C:\Users\Dela\AppData\Roaming\npm-cache\registry.npmjs.org\nopt\.cache.json
248 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
249 silly resolveWithNewModule nopt@3.0.1 checking installable status
250 silly cache add args [ 'nopt@3.0.1', null ]
251 verbose cache add spec nopt@3.0.1
252 silly cache add parsed spec Result {
252 silly cache add   raw: 'nopt@3.0.1',
252 silly cache add   scope: null,
252 silly cache add   name: 'nopt',
252 silly cache add   rawSpec: '3.0.1',
252 silly cache add   spec: '3.0.1',
252 silly cache add   type: 'version' }
253 silly addNamed nopt@3.0.1
254 verbose addNamed "3.0.1" is a plain semver version for nopt
255 silly mapToRegistry name nopt
256 silly mapToRegistry using default registry
257 silly mapToRegistry registry https://registry.npmjs.org/
258 silly mapToRegistry uri https://registry.npmjs.org/nopt
259 verbose addNameVersion registry:https://registry.npmjs.org/nopt not in flight; fetching
260 verbose get https://registry.npmjs.org/nopt not expired, no request
261 silly cache afterAdd nopt@3.0.1
262 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\nopt\3.0.1\package\package.json not in flight; writing
263 verbose correctMkdir C:\Users\Dela\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
264 verbose afterAdd C:\Users\Dela\AppData\Roaming\npm-cache\nopt\3.0.1\package\package.json written
265 silly fetchAndShaCheck shasum 5bf498ae04fbcf2ff04f8cbfb594ee681f93c714
266 silly rollbackFailedOptional Starting
267 silly rollbackFailedOptional Finishing
268 silly runTopLevelLifecycles Starting
269 silly runTopLevelLifecycles Finishing
270 silly install printInstalled
271 verbose stack Error: shasum check failed for C:\Users\Dela\AppData\Local\Temp\npm-3496-a9f22a30\registry.npmjs.org\cordova-lib\-\cordova-lib-6.0.0.tgz
271 verbose stack Expected: 5bf498ae04fbcf2ff04f8cbfb594ee681f93c714
271 verbose stack Actual:   35020cfbcd6a6e025686d9cf9d2ca371466ee983
271 verbose stack From:     https://registry.npmjs.org/cordova-lib/-/cordova-lib-6.0.0.tgz
271 verbose stack     at C:\Users\Dela\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:25:8
271 verbose stack     at ReadStream.<anonymous> (C:\Users\Dela\AppData\Roaming\npm\node_modules\npm\node_modules\sha\index.js:72:7)
271 verbose stack     at emitNone (events.js:72:20)
271 verbose stack     at ReadStream.emit (events.js:166:7)
271 verbose stack     at endReadableNT (_stream_readable.js:905:12)
271 verbose stack     at nextTickCallbackWith2Args (node.js:437:9)
271 verbose stack     at process._tickCallback (node.js:351:17)
272 verbose cwd C:\Users\Dela
273 error Windows_NT 10.0.10586
274 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Dela\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova"
275 error node v4.3.1
276 error npm  v3.7.3
277 error shasum check failed for C:\Users\Dela\AppData\Local\Temp\npm-3496-a9f22a30\registry.npmjs.org\cordova-lib-\cordova-lib-6.0.0.tgz
277 error Expected: 5bf498ae04fbcf2ff04f8cbfb594ee681f93c714
277 error Actual:   35020cfbcd6a6e025686d9cf9d2ca371466ee983
277 error From:     https://registry.npmjs.org/cordova-lib/-/cordova-lib-6.0.0.tgz
278 error If you need help, you may report this error at:
278 error     https://github.com/npm/npm/issues
279 verbose exit [ 1, true ]

**Comment by codebhendi** [comment] 2016-02-25 17:12
I have win 10 and i just installed it, so just try to install it again. May be it was an issue with the module itself.

**Comment by zkat** [comment] 2016-12-09 00:46
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:46 UTC
Labels: support
