### ISSUE TITLE
npm install is unbearably slow and uses TONS of CPU and RAM

### ISSUE THREAD

**Issue by kfirba** [npm/npm#9884] opened 2015-10-07 18:36 UTC
Hello.

I really don't know what else I can do at this point. I'm simply trying to use NPM to require some dependencies into my application. Even if I try to require something as simple as `npm install vue` it takes more than 50 minutes and I can see in my `Activity Monitor` that is uses around 3.6GB of RAM and 200% CPU! I'm pretty sure that something is bugged here...

I tries re-installing node and npm but that didn't help. I've also tried to install my npm dependencies through a vagrant box and I get the same issue..

Most of the times after watching it goes for more than an hour I get the error:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

I have 16GB of RAM.

P.S. It's running on a MAC. OS X Yosemite

Any idea what's going on here..?

**Comment by KenanY** [comment] 2015-10-07 18:59
@kfirba `node --version`? `npm --version`?

**Comment by kfirba** [comment] 2015-10-07 19:01
@KenanY node 4.1.2, npm 2.14.6

**Comment by KenanY** [comment] 2015-10-07 19:04
@kfirba Does `npm config get dev` return `false`? Personally I can run `npm install vue` just fine, so the first thing that comes to my mind is that you somehow have `dev` set to `true`.

**Comment by kfirba** [comment] 2015-10-07 19:07
@KenanY  when I run `npm config get dev` it returns `false`. I also tried something like `npm install laravel-elixir` but the same issue..

**Comment by kfirba** [comment] 2015-10-07 19:12
@KenanY Btw, I've also run `npm config set spin false` and `npm config loglevel http` to see the progression in real time. I've noticed that MANY times it's going to fetch some libraries and then stall for few minutes and then fetch another batch of libraries and stall again. Maybe it tries to do something with the downloaded libraries but something isn't working as expected?

**Comment by KenanY** [comment] 2015-10-07 19:21
@kfirba Hmm, maybe try raising the verbosity of the logging and piping the output to a file that you can upload as a [gist](https://gist.github.com/)?:

``` sh
npm cache clean && npm i vue --loglevel=silly 2> debug.log
```

Just let it run for like a minute or less I suppose.

**Comment by kfirba** [comment] 2015-10-07 19:26
@KenanY I'm actually already trying it, well, somewhat.. I removed my cache and ran `npm install laravel-elixir` and I can see it running. I think that it's getting into somewhat of endless loop with the dependencies? seems like it's getting 304 for any dependency request at this point even tho I've cleared the cache before running the command so I guess it has already cached those dependencies? It started with 350MB RAM consumption and after running for 8 minutes it's already at 2.5GB! I'm not sure if it matters but I've installed node and npm through `homebrew` - `brew install node`

P.S. as I was typing this post the RAM usage spiked to 3GB already.. maybe if I can somehow completely destroy NPM and NODE from my machine and re-install them in a good way with permissions will fix this?

**Comment by kfirba** [comment] 2015-10-07 20:07
@KenanY A one-time miracle has happened! I ran `npm i vue --loglevel=silly 2> debug.log` and it actually took few seconds and it has been installed. Unfortunately, It was a one time thing.. the issue still persists. However, looking at the log I could see: 

```
npm verb unlock done using /Users/kfir/.npm/_locks/vue-c483d891e42271f8.lock for /Users/kfir/code/Receipto/node_modules/vue
npm verb validateInstall loading /Users/kfir/code/Receipto/package.json for validation
npm verb exit [ 0, true ]
npm info ok
```

Maybe the issue is due to locking?

**Comment by kfirba** [comment] 2015-10-07 20:17
@KenanY Here is the result log of the command `npm i laravel-elixir --loglevel=silly 2>debug.log`:

https://mega.nz/#!TcVnAbRb!7iZIZ-hMIZCaGOpEYc03y7ik8IczFMdZeGNAMQCRaqE

Sorry it has to be a download since it's too big to use in pastebin or paste here.

**Comment by nmccready** [comment] 2015-10-22 18:19
#8826

**Comment by vishwanath-to** [comment] 2016-01-13 08:05
@nmccready This issue is for npm 2 with node 4 and that one is for npm 3.

**Comment by sysadmin1139** [comment] 2016-02-18 21:41
We're running into an issue like this as well. Previously, we were running with npm verison 2.7.6. After some modernization efforts, we're now on 2.14.12, and have noticed a pretty serious side-effect: 1.5GB of RAM is no longer sufficient to run our package.json file to completion, and the `npm` process is getting OOMKilled by the kernel. This RAM constraint is most evident on developer VMs; our production nodes aren't as constrained so don't experience it.

**Comment by ramsundhar20** [comment] 2016-03-09 00:34
I am also facing the issue, please let me know any smart patches to avoid this issue. I am using npm 2.14.12 and nodejs v4.3.1

**Comment by admiralobvious** [comment] 2016-03-21 21:37
Same issue. npm install randomly started using >1GB of memory in my docker build container today.

npm config get dev
npm info it worked if it ends with ok
npm info using npm@2.14.20
npm info using node@v4.4.0
false
npm info ok

**Comment by tchap** [comment] 2016-04-08 12:38
:+1:

**Comment by dvtoever** [comment] 2016-06-09 09:39
I experienced exactly the same symptoms when I executed `npm install typings --global`. I replaced my NodeJS installation with the 6.2.1 version and then the npm install command completed succesfully

**Comment by denodster** [comment] 2016-06-23 15:56
I'm running into similar issues, I have an app server with 2 gb of ram, but deployment fails because npm runs it out of ram.

**Comment by LRPalacios** [comment] 2016-06-27 15:24
i've face similar issues npm constantly get killed because the server runs out of memory.  nodejs v: v4.4.6 npm v: 2.15.5

**Comment by porioli** [comment] 2016-06-29 15:36
Same issue with a Centos VM running jenkins and Node.js v4.4.5 and nom 2.15.5, it consumes all the RAM then the swap until it gets killed, please tell me if I can provide more detailed infos. Thanks

**Comment by mufumbo** [comment] 2016-07-22 20:45
it seems that npm puts all the packages in memory and leak the context. If I go to the specific package that it's getting out of memory and "npm install" it, it won't crash.. there's any command that we can run that would clean the cache?

**Comment by carlcassar** [comment] 2016-08-01 09:04
Same issue here on AWS CentOS 2GB Ram. Tried Node.js v4.4.7 and v6.3.1. Has anyone been able to resolve this issue?

**Comment by liamuk** [comment] 2016-08-02 03:53
Facing this problem right now. Why does npm need to put all packages in memory at once? There should at the very least be a flag to install one at a time.

**Comment by yoshuawuyts** [comment] 2016-08-14 11:31
Yeah same, my containers go out of memory and then die without warning. My machines have 0.6GB of RAM and that should be more than sufficient to download and untar some deps

<img width="1273" alt="screen shot 2016-08-14 at 13 29 25" src="https://cloud.githubusercontent.com/assets/2467194/17648812/58258152-6223-11e6-835b-d9bf35a13cd8.png">

**Comment by 3rwww1** [comment] 2016-09-02 23:01
I'm facing the same issue:
```
cd path/to/my/code
rm -rf ./node_modules ~/.npm
npm install
```

ran the last `npm install` about 30 times with different flags (`-dddd --verbose`) and the process freezes, eating 100% of one my 4 logical cores (2x2HT), for no obvious reason, never at the same step (judging from the output).

my project has about 28 direct dependencies. Transitively, they add up to 552 required modules.

@yoshuawuyts workaround came in handy. The other working solution was to issue 28 `npm install <package>`  with a final `npm install` a final `npm install` to make sure all the voodoo spells were properly casted.

Spent some time trying to figure out the why and how, blaming my setup at first. I downgraded npm from 3.10.6 to 3.10.5 and 3.10.3 on node 6.5.0. My laptop runs an up-to-date arch linux and I tried both kernel 4.7.2-1 (stable) and 4.8rc4-1, to no avail.

Seems to me npm panicks when the dependency graph is too large with no modules readily available offline.

**Comment by liamuk** [comment] 2016-09-03 05:03
Another workaround: use the module npm-install-que. It runs separate npm install commands for each of your dependencies so only the currently installing package is loaded into memory.

**Comment by yoshuawuyts** [comment] 2016-09-03 07:31
I've found the following to work quite reliably:
```dockerfile
# Install app dependencies
COPY package.json /usr/src/app/
RUN /usr/bin/node \
  --max_semi_space_size=1 \
  --max_old_space_size=198 \
  --max_executable_size=148 \
  /usr/bin/npm install
```
It's slow, but it works quite reliably

**Comment by charlielondon** [comment] 2016-09-09 00:37
@JeffreyWay

**Comment by 3rwww1** [comment] 2016-09-09 23:58
Interesting development happening just now:
```
2016-09-10 01:55:04 ▶ ✔ ▶ npm install
(node:16154) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:16154) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
^C^C^C[1]    16154 killed     /usr/bin/node --max_semi_space_size=1 --max_old_space_size=198  /usr/bin/npm 
2016-09-10 01:55:40 ▶ ✘ 137 ▶ node -v
v6.5.0
2016-09-10 01:55:55 ▶ ✔ ▶ npm -v
3.10.7
```
I had to `killall -9 npm` as `^C` was apparently not enough

**Comment by charlielondon** [comment] 2016-09-10 00:02
Yeah this is a gnarly bug.  I had the same problem. For me, downgrading to
laravel-elixir ^3.0.0 seemed to fix the problem.

On Sep 9, 2016 4:59 PM, "Erwan Queffélec" <notifications@github.com> wrote:

Interesting development happening just now:

2016-09-10 01:55:04 ▶ ✔ ▶ npm install
(node:16154) Warning: Possible EventEmitter memory leak detected. 11
error listeners added. Use emitter.setMaxListeners() to increase limit
(node:16154) Warning: Possible EventEmitter memory leak detected. 11
error listeners added. Use emitter.setMaxListeners() to increase limit
^C^C^C[1]    16154 killed     /usr/bin/node --max_semi_space_size=1
--max_old_space_size=198  /usr/bin/npm
2016-09-10 01:55:40 ▶ ✘ 137 ▶ node -v
v6.5.0
2016-09-10 01:55:55 ▶ ✔ ▶ npm -v
3.10.7

I had to killall -9 npm as ^C was apparently not enough

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/9884#issuecomment-246071549>, or mute
the thread

**Comment by duzun** [comment] 2016-09-17 19:44
@3rwww1 I have exactly the same issue with exactly the same versions of node and npm under Manjaro Linux!

**Comment by KevinCreel** [comment] 2016-09-28 06:40
npm set registry https://registry.npmjs.org/

**Comment by tinybug** [comment] 2016-11-21 08:46
try https://yarnpkg.com/

**Comment by phpguru** [comment] 2016-11-30 20:28
Possible duplicate of [11028](https://github.com/npm/npm/issues/11028). Try debugging this issue on a Windows 10 machine behind a corporate proxy. It will make you want to stab yourself in the eye with an ice pick. Node v6.9.2, npm v3.10.9. I'm running with 

    npm set progress=false -g
    npm config set registry http://registry.npmjs.org/ -g
    npm config set loglevel=http -g
    npm --proxy http://myusername:mypassword@proxy.us.somecompany:8080 --without-ssl --insecure install

I see multiple copies of the same package being requested, 

    ....
    npm http request GET http://registry.npmjs.org/graceful-readlink
    npm http request GET http://registry.npmjs.org/graceful-readlink
    npm http request GET http://registry.npmjs.org/graceful-readlink
    npm http request GET http://registry.npmjs.org/amdefine
    npm http request GET http://registry.npmjs.org/amdefine
    npm http request GET http://registry.npmjs.org/amdefine
    npm http request GET http://registry.npmjs.org/colors
    npm http request GET http://registry.npmjs.org/colors
    ....

and npm times out for up to a half hour or more doing who knows what. All I see is:

    [    ..............] - fetchMetadata: http request GET http://registry.npmjs.org/somepackage

**Comment by legodude17** [comment] 2016-11-30 22:43
Does anyone have this issue without a proxy?

**Comment by hecmec** [comment] 2016-12-06 10:28
hello,

I'm on **windows server 2012** behind a **enterprise firewall**.
To enable npm:
1) I installed and configured cntlm (authentication proxy) on localhost:3128

2) then in the .npmrc (C:\Users\YourUser)

```
proxy=http://localhost:3128/
https-proxy=http://localhost:3128/
registry=https://registry.npmjs.org/
strict-ssl=false
```

I've just had some spaces before and after '=' and the new npm didn't get it and it became **very slow* :(
Now, removed spaces,  everything is **fast again** , :)

hector

**Comment by requiescate** [comment] 2017-02-16 09:32
same issue with a clean install nodejs  on windows 10

**Comment by albertnadal** [comment] 2017-02-21 11:13
I got the same experience when launching 'npm install' on a CI computer with only 1GB of RAM and Jenkins, Docker, etc. running in background. I realized that this operation consumes a lot of memory (when installing a large amount of dependencies) and just kills itself when the computer is out of memory. I added 1GB more and now works fine. I hope it can help you guys.

**Comment by redgeoff** [comment] 2017-02-23 14:50
I solved this by enabling swap: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by legodude17** [comment] 2017-02-23 17:06
Does anyone still have this issue?

**Comment by LRPalacios** [comment] 2017-02-23 17:18
@legodude17 on what npm version shall we test to make sure if the issue is gone?

**Comment by legodude17** [comment] 2017-02-23 18:10
The latest version (I think it is `npm@4.3.1`)

**Comment by kolbma** [comment] 2017-03-19 14:24
I'm using 

```
npm version
{ npm: '4.4.4',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.0',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.93',
  zlib: '1.2.8' }
```
and it uses complete available RAM and Swap until it gets killed by kernel.

**Comment by jonnnnyw** [comment] 2017-03-23 19:39
@yoshuawuyts Thank you. That worked a charm.

**Comment by legodude17** [comment] 2017-03-23 21:13
@kolbma does the solution from @yoshuawuyts work for you?

**Comment by kolbma** [comment] 2017-03-24 07:00
@legodude17 I've set now job = 1 and got it to install. Will try the call via node and memory settings and report back.

**Comment by knaos** [comment] 2017-04-06 08:23
I am having a common issue. Running this command starts a procces taking **~500MB** of RAM. Is this normal?

Issues is on Windows 10.
NPM version 3.10.10
Node version v6.9.4

**Comment by sofaking** [comment] 2017-04-20 13:23
For those, who still wondering how to fix slow install, I've changed registry from http to https and everything is flying now.

**Comment by zacacollier** [comment] 2017-05-01 22:05
I can confirm that resetting the registry fixes this issue for me. Before, I tried npm installation from both official (Arch) repositories and `nvm`, but the speed was so slow that sometimes it would timeout.

Anyone experiencing similar problems should try resetting the npm registry as @sofaking mentioned:
```bash
npm config set registry https://registry.npmjs.org/
```
This will update your `.npmrc` accordingly:
```bash
# ~/.npmrc
registry=https://registry.npmjs.org/
```

**Comment by FelikZ** [comment] 2017-05-02 15:18
@zacacollier does it solves cpu/ram usage?

**Comment by zacacollier** [comment] 2017-05-02 17:17
@FelikZ I honestly don't know - my issues were related to sluggish download speeds, not CPU/RAM usage. My best guess in your case would be to try updating Node. Also FWIW `yarn` is noticeably faster than plain `npm`.

I noticed yesterday that a lot of my students had issues with slow download speeds on Mac and Windows. This morning NPM [logged an issue](https://status.npmjs.org/incidents/154m9txf33zr) which may be tangentially related - just a hunch.

**Comment by kolbma** [comment] 2017-05-03 06:21
I've updated to npm 4.5.0 on windows and the memory footprint is quite nice, now. Between 30 and 90 MB during an update with updating 7 packages. Not any special setting.

**Comment by ghitapop** [comment] 2017-06-02 14:52
The ram/cpu usage didn't help, I have plenty of ram sitting and doing nothing. Behind the corporate proxy issue has nothing to do with ram/cpu. This issue happens even if you have very powerful pc as I do. Very frustrating and cannot do much about the corporate proxy.
I have tried every possible combination of registry setting for https://registry.npmjs.org/ ,cleaning the cache, reinstalling node, npm with latest stable version, setting proxy and as mentioned everything I could find that seemed worth trying out and nothing worked for me. Still looking for a miracle :).
Windows 10.
NPM version 4.6.1
Node version v6.9.4

**Comment by legodude17** [comment] 2017-06-02 20:54
Try `npm@5`

**Comment by ghitapop** [comment] 2017-06-08 14:35
Thanks, that really worked, so it turned our that it was not corporate proxy the issue or at least not entirely and not in my case. I thought it's the case since I was getting our admin going crazy with my complain :). He insisted that is not doing anything that would slow things so bad.

**Closed** 2017-06-18 22:48 UTC
Labels: bot-closed
