### ISSUE TITLE
Error in installing angular.io (Angular 2) shasum check failed

### ISSUE THREAD

**Issue by alphadeeto** [npm/npm#11020] opened 2016-01-04 10:10 UTC
Hello :)

I'm trying to follow the 5 min quick start from this page : https://angular.io/docs/js/latest/quickstart.html but can't seem to install the package. I already add the package.json and run the npm install. The installer takes long to finish, and I get errors afterward.

Here is what appears on my console :

> npm WARN package.json angular2-quickstart@1.0.0 No description
> npm WARN package.json angular2-quickstart@1.0.0 No repository field.
> npm WARN package.json angular2-quickstart@1.0.0 No README data
> npm ERR! Windows_NT 10.0.10240
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
> npm ERR! node v4.2.4
> npm ERR! npm  v2.14.12
> 
> npm ERR! shasum check failed for C:\Users\Alfa\AppData\Local\Temp\npm-1636-cdcdb4f1\registry.npmjs.org\angular2-\angular2-2.0.0-beta.0.tgz
> npm ERR! Expected: 97413fabc1eaf1547a081ba3ad4c61732db54837
> npm ERR! Actual:   899292ee094d8618928abf17cef5b4bae3b60345
> npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.0.tgz
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\xampp\htdocs\angular2-quickstart\npm-debug.log

I attached the debug log here if you need to look at it. Other dependencies seems to be installed fine if I'm reading the log right.
I've tried clearing the cache, and even reinstalling node js but the problem still persists.
I'm using node v4.2.4 and npm v2.14.12

I can download directly from the link provided though (https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.0.tgz). Should I install directly from that url?

I've searched for possible duplicates, but can't found any solutions. Pardon me if I missed any.
Thank you for your help. This is my first time using npm so I'm still a bit confused. :)

[npm-debug.txt](https://github.com/npm/npm/files/77034/npm-debug.txt)

**Comment by alphadeeto** [comment] 2016-01-04 11:28
Update : I've tried installing directly from the url, and I get this in my console :

> npm ERR! tar.unpack untar error C:\Users\Alfa\AppData\Local\Temp\npm-11356-9546b465\registry.npmjs.org\angular2\-\angular2-2.0.0-beta.0.tgz
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.0.tgz"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

> npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

> npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\angular2-quickstart\npm-debug.log

Seems like the download isn't finished. But when I tried opening the downloaded file (gzip) from the same url, I can extract from the downloaded gzip.

I will try installing this using other internet connection to check the problem.

**Comment by zkat** [comment] 2016-12-09 00:49
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:49 UTC
Labels: support, windows
