### ISSUE TITLE
Error: Missing required argument #1

### ISSUE THREAD

**Issue by theoden8** [npm/npm#10704] opened 2015-12-04 23:33 UTC
Hello. My `npm update` asked me to raise an issue:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'update' ]
2 info using npm@3.3.12
3 info using node@v5.1.1
4 verbose config Skipping project config: /Users/Admin/.npmrc. (matches userconfig)
5 verbose stack Error: Missing required argument #1
5 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
5 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
5 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
5 verbose stack     at fs.js:1657:23
6 verbose cwd /Users/Admin
7 error Darwin 13.4.0
8 error argv "/usr/local/Cellar/node/5.1.1/bin/node" "/usr/local/bin/npm" "update"
9 error node v5.1.1
10 error npm  v3.3.12
11 error code EMISSINGARG
12 error typeerror Error: Missing required argument #1
12 error typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
12 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
12 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
12 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
12 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
12 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
12 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
12 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
12 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
12 error typeerror     at fs.js:1657:23
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by fearphage** [comment] 2015-12-12 14:37
The same file (`mutate-into-logical-tree.js`) is throwing the same error from `npm outdated`.

```shell
✗ npm outdated     
npm ERR! Linux 3.19.0-37-generic
npm ERR! argv "/home/phred/.local/nvm/versions/node/v5.2.0/bin/node" "/home/phred/.local/nvm/versions/node/v5.2.0/bin/npm" "outdated"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at fs.js:1658:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by fearphage** [comment] 2015-12-12 15:46
This is a dupe of #9720.

**Closed** 2017-06-16 23:45 UTC
Labels: bot-closed, support
