### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Erwin1411** [npm/npm#13755] opened 2016-08-24 11:42 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x?] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

command npm install gives errors

#### How can the CLI team reproduce the problem?

no log file was created

cmd says:
C:\WINDOWS\system32>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

### supporting information:

 - `npm -v` prints: 3.10.3
 - `node -v` prints: 6.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Windows (10)
 - Network issues:
   - Geographic location where npm was run: Netherlands
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-08-24 12:32
@Erwin1411 There are no errors in the log that you have posted. Rather, there are only warnings. You are running `npm install` without passing any module names as arguments. Therefore, `npm` will then read a `package.json` file in your current directory to see what module you want installed. Since you do not have such a file in your directory, `npm` warns you about this, and ends up not installing anything. This is intended behavior so I'm gonna close this issue.

**Closed by KenanY** 2016-08-24 12:32 UTC
