### ISSUE TITLE
global install ignores optional nature of nested optionalDependencies

### ISSUE THREAD

**Issue by rmg** [npm/npm#9685] opened 2015-09-21 00:11 UTC
When installing a module with optional dependencies known to fail (on node-v4.1.0):
```
$ npm install -g ws@0.7

...snip...

9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rmg/.nvm/versions/node/v4.1.0/bin/node" "/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

...snip...

9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rmg/.nvm/versions/node/v4.1.0/bin/node" "/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
/Users/rmg/.nvm/versions/node/v4.1.0/lib
└─┬ ws@0.7.2
  ├── options@0.0.6
  └── ultron@1.0.2
```

When installing a module that depends on ws@0.7, the optionalDependencies get promoted to stop-everything-if-I-don't-get-installed dependencies:
```
$ npm install -g strong-control-channel@0.2.1

...snip...

9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rmg/.nvm/versions/node/v4.1.0/bin/node" "/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/strong-control-channel/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/rmg/.nvm/versions/node/v4.1.0/bin/node" "/Users/rmg/.nvm/versions/node/v4.1.0/bin/npm" "i" "-g" "strong-control-channel"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rmg/tmp/npm-debug.log
```

Then installing locally the package that fails to install globally:
```
$ npm install strong-control-channel@0.2.1
... snip ...
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rmg/.nvm/versions/node/v4.1.0/bin/node" "/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rmg/tmp/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.1.0 install /Users/rmg/tmp/node_modules/utf-8-validate
> node-gyp rebuild

... snip ...
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rmg/.nvm/versions/node/v4.1.0/bin/node" "/Users/rmg/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rmg/tmp/node_modules/utf-8-validate
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
/Users/rmg/tmp
└─┬ strong-control-channel@2.1.0
  ├─┬ debug@2.2.0
  │ └── ms@0.7.1
  ├─┬ newline-json@0.1.1
  │ └── stream2buffer@0.0.4
  └─┬ ws@0.7.2
    ├── options@0.0.6
    └── ultron@1.0.2

npm WARN ENOENT ENOENT: no such file or directory, open '/Users/rmg/tmp/package.json'
npm WARN EPACKAGEJSON /Users/rmg/tmp No description
npm WARN EPACKAGEJSON /Users/rmg/tmp No repository field.
npm WARN EPACKAGEJSON /Users/rmg/tmp No README data
npm WARN EPACKAGEJSON /Users/rmg/tmp No license field.
```

This might be a manifestation of #7175 or #9666.

Originally observed/reported in strongloop/strong-pm#278 and strongloop/strongloop#253.

**Comment by othiym23** [comment] 2015-09-21 18:21
Thanks for all the detail, Ryan! I'm closing this as a duplicate of #9643, and is something that's already on @iarna's radar, but now this will be cross-referenced there.

**Closed by othiym23** 2015-09-21 18:21 UTC
Labels: bug

**Comment by rmg** [comment] 2015-09-21 18:46
@othiym23 thanks, I figured it would already be logged somewhere.

If nothing else, hopefully the added detail will increase the google juice (and priority! :wink:) of the #9643.
