### ISSUE TITLE
 Refusing to install grunt-shopify as a dependency of itself

### ISSUE THREAD

**Issue by Jorybraun** [npm/npm#11500] opened 2016-02-11 01:19 UTC
first time grunt user - talk nerdy to me.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-shopify" "--save-dev"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.1
npm ERR! code ENOSELF

npm ERR! Refusing to install grunt-shopify as a dependency of itself

=================================================
=================================================

Here is the error log,

1. 0 info it worked if it ends with ok
2. 1 verbose cli [ '/usr/local/bin/node',
3. 1 verbose cli   '/usr/local/bin/npm',
4. 1 verbose cli   'install',
5. 1 verbose cli   'grunt-shopify',
6. 1 verbose cli   '--save-dev' ]
7. 2 info using npm@3.7.1
8. 3 info using node@v5.6.0
9. 4 silly loadCurrentTree Starting
10. 5 silly install loadCurrentTree
11. 6 silly install readLocalPackageData
12. 7 silly fetchPackageMetaData grunt-shopify
13. 8 silly fetchNamedPackageData grunt-shopify
14. 9 silly mapToRegistry name grunt-shopify
15. 10 silly mapToRegistry using default registry
16. 11 silly mapToRegistry registry https://registry.npmjs.org/
17. 12 silly mapToRegistry uri https://registry.npmjs.org/grunt-shopify
18. 13 verbose request uri https://registry.npmjs.org/grunt-shopify
19. 14 verbose request no auth needed
20. 15 info attempt registry request try #1 at 8:16:22 PM
21. 16 verbose request id 969cb461858698b5
22. 17 verbose etag "DMTCCBCMNWFYJPEHGNSLBODD"
23. 18 http request GET https://registry.npmjs.org/grunt-shopify
24. 19 http 304 https://registry.npmjs.org/grunt-shopify
25. 20 verbose headers { date: 'Thu, 11 Feb 2016 01:16:23 GMT',
26. 20 verbose headers   via: '1.1 varnish',
27. 20 verbose headers   'cache-control': 'max-age=300',
28. 20 verbose headers   etag: '"DMTCCBCMNWFYJPEHGNSLBODD"',
29. 20 verbose headers   age: '0',
30. 20 verbose headers   connection: 'keep-alive',
31. 20 verbose headers   'x-served-by': 'cache-iad2144-IAD',
32. 20 verbose headers   'x-cache': 'HIT',
33. 20 verbose headers   'x-cache-hits': '1',
34. 20 verbose headers   'x-timer': 'S1455153383.188206,VS0,VE15',
35. 20 verbose headers   vary: 'Accept' }
36. 21 silly get cb [ 304,
37. 21 silly get   { date: 'Thu, 11 Feb 2016 01:16:23 GMT',
38. 21 silly get     via: '1.1 varnish',
39. 21 silly get     'cache-control': 'max-age=300',
40. 21 silly get     etag: '"DMTCCBCMNWFYJPEHGNSLBODD"',
41. 21 silly get     age: '0',
42. 21 silly get     connection: 'keep-alive',
43. 21 silly get     'x-served-by': 'cache-iad2144-IAD',
44. 21 silly get     'x-cache': 'HIT',
45. 21 silly get     'x-cache-hits': '1',
46. 21 silly get     'x-timer': 'S1455153383.188206,VS0,VE15',
47. 21 silly get     vary: 'Accept' } ]
48. 22 verbose etag https://registry.npmjs.org/grunt-shopify from cache
49. 23 verbose get saving grunt-shopify to /Users/jorybraun/.npm/registry.npmjs.org/grunt-shopify/.cache.json
50. 24 verbose correctMkdir /Users/jorybraun/.npm correctMkdir not in flight; initializing
51. 25 silly install normalizeTree
52. 26 silly loadCurrentTree Finishing
53. 27 silly loadIdealTree Starting
54. 28 silly install loadIdealTree
55. 29 silly cloneCurrentTree Starting
56. 30 silly install cloneCurrentTreeToIdealTree
57. 31 silly cloneCurrentTree Finishing
58. 32 silly loadShrinkwrap Starting
59. 33 silly install loadShrinkwrap
60. 34 silly loadShrinkwrap Finishing
61. 35 silly loadAllDepsIntoIdealTree Starting
62. 36 silly install loadAllDepsIntoIdealTree
63. 37 silly rollbackFailedOptional Starting
64. 38 silly rollbackFailedOptional Finishing
65. 39 silly runTopLevelLifecycles Starting
66. 40 silly runTopLevelLifecycles Finishing
67. 41 silly install printInstalled
68. 42 verbose stack Error: Refusing to install grunt-shopify as a dependency of itself
69. 42 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
70. 42 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
71. 42 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
72. 42 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
73. 42 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
74. 42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
75. 42 verbose stack     at Array.forEach (native)
76. 42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
77. 42 verbose stack     at Array.forEach (native)
78. 42 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
79. 43 verbose cwd /Users/jorybraun/Websites/shopify/Peirotwist
80. 44 error Darwin 15.3.0
81. 45 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-shopify" "--save-dev"
82. 46 error node v5.6.0
83. 47 error npm  v3.7.1
84. 48 error code ENOSELF
85. 49 error Refusing to install grunt-shopify as a dependency of itself
86. 50 error If you need help, you may report this error at:
87. 50 error     <https://github.com/npm/npm/issues>
88. 51 verbose exit [ 1, true ]
89. `
90.

**Comment by KenanY** [comment] 2016-02-11 01:34
Duplicate of https://github.com/npm/npm/issues/11499

**Closed** 2016-02-11 12:48 UTC
