### ISSUE TITLE
NPM errors while attempting to install Atom 1.0 on 32 bit Ubuntu 15.04

### ISSUE THREAD

**Issue by fusion809** [npm/npm#8674] opened 2015-06-25 22:13 UTC
Hi, I've run `script/build` in my Atom repository to receive this error message at the install apm stage:

```
npm ERR! Linux 3.19.0-21-generic
npm ERR! argv "node" "/home/fusion809/atom/build/node_modules/.bin/npm" "--userconfig=/home/fusion809/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v0.12.4
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /tmp/npm-9778-c1622473/registry.npmjs.org/git-utils/-/git-utils-3.0.1.tgz
npm ERR! Expected: ebe544751e2469d0318407fe31caef146659508a
npm ERR! Actual:   9addb9ef72aac294aae0d117a2ac4b5e66d2c05b
npm ERR! From:     https://registry.npmjs.org/git-utils/-/git-utils-3.0.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fusion809/atom/apm/npm-debug.log
```

[here's](https://github.com/fusion809/Linux-atom-install/blob/master/npm-debug.log) my log file. This error did NOT occur when I was attempting to install Atom prior to the 1.0 release.

**Comment by zkat** [comment] 2016-12-09 00:56
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:56 UTC
Labels: shasum, support
