### ISSUE TITLE
npm v5.0.3 login hangs

### ISSUE THREAD

**Issue by pintux** [npm/npm#17119] opened 2017-06-09 15:55 UTC
#### I'm opening this issue because:

  - [ X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Installed node 8.1.0 and npm 5.0.3 on macOS Sierra through nvm,
doing npm login it hangs and freezes Terminal when asking for password.

#### How can the CLI team reproduce the problem?

try npm login.
Input for username works.
Terminal hangs when asking for password.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra v10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment] 2017-06-09 16:14
Try downgrading to node v7

**Comment by jessebye** [comment] 2017-06-09 18:23
Experiencing the same issue with npm 5.0.3 and node 8.1.0.

**Comment by ryanarmstrong** [comment] 2017-06-09 19:41
Can confirm having this issue with 5.0.3 but every works fine in 5.0.0.

**Comment by mdouglass** [comment] 2017-06-09 20:15
Possibly related: https://github.com/nodejs/node/issues/13557

**Comment by styfle** [comment] 2017-06-09 20:30
I cannot login with `npm login` using node 8.1.0 and npm 5.0.3 on Windows 10.

The same behavior for me, freezing after hitting Enter in the password field.

**Comment by legodude17** [comment] 2017-06-09 20:34
Does this work with node v7?

**Comment by styfle** [comment] 2017-06-09 20:59
@legodude17 I just tried `npm login` with node 7.9.0 and npm 5.0.3 on alpine linux and it works!

**Comment by legodude17** [comment] 2017-06-09 21:02
Then it is probably caused by nodejs/node#13557 and will be fixed by nodejs/node#13560

**Comment by bertolo1988** [comment] 2017-06-28 09:17
I had to share my screen to people in my office to prove that i couldn't get past the password prompt.
They still thought i was missing the CTRL+Shift+V thing.

Fun times.

**Comment by addaleax** [comment] 2017-06-28 12:35
I think this can be closed as a fixed bug/duplicate now.

**Closed as completed** 2017-06-28 22:19 UTC
Labels: node-bug, npm5

**Comment by mixflame** [comment] 2017-07-05 18:12
this is still an issue with node 8.10 and npm 5.0.4

**Comment by addaleax** [comment] 2017-07-05 18:18
@mixflame Yes, this is fixed in the latest Node version (https://nodejs.org/).

**Comment by mixflame** [comment] 2017-07-05 18:25
thanks @addaleax it was solved after upgrade to node latest

**Comment by nsisodiya** [comment] 2017-12-06 07:41
I have 

```$ npm -v
5.6.0
$ node -v
v8.1.0```
Unable to do `npm login`, it hands at password stage.
