### ISSUE TITLE
Troubles to download github private repo, can't work anymore

### ISSUE THREAD

**Issue by kud** [npm/npm#7807] opened 2015-03-31 13:29 UTC
I don't know what happened with the npm code but I cannot install private repo now with `2.7.4`.

### package.json

`"private": "git+ssh://git@github.com:org/private",`

### npm install

```console
$ npm install
npm ERR! git clone --template=/Users/kud/.npm/_git-remotes/_templates --mirror git://github.com/org/private.git /Users/kud/.npm/_git-remotes/git-github-com-org-private-git-a08d8794
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'charAt' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kud/Projects/_playmedia/desktop/npm-debug.log
```

I've tried this command manually `git clone --template=/Users/kud/.npm/_git-remotes/_templates --mirror git://github.com/org/private.git /Users/kud/.npm/_git-remotes/git-github-com-org-private-git-a08d8794` and this is what I've got: `fatal: remote error: Repository not found.`

I've read a bit more the line and I found an error. It shouldn't be `git://github.com/org/private.git` but `git@github.com:org/private.git`

which does:

```console
$ git clone --template=/Users/kud/.npm/_git-remotes/_templates --mirror git@github.com:org/private.git /Users/kud/.npm/_git-remotes/git-github-com-org-private-git-a08d8794
```

and it works.

**Comment by kud** [comment] 2015-03-31 13:33
It seems to be well written in package.json. http://debuggable.com/posts/private-npm-modules:4e68cc7d-1ac4-42d9-995a-343dcbdd56cb

**Comment by kud** [comment] 2015-03-31 13:51
It works with `npm install npm@2.7.1 -g`.

**Comment by KenanY** [comment] 2015-03-31 13:52
@kud 

```
npm ERR! Cannot read property 'charAt' of undefined
```

This was fixed in [`npm@2.7.5`](https://github.com/npm/npm/releases/tag/v2.7.5), can you try installing that version? (dupe of https://github.com/npm/npm/issues/7746 ?)

**Comment by kud** [comment] 2015-03-31 13:53
I've tried with 2.7.5, it did not work. :/

**Comment by kud** [comment] 2015-03-31 13:54
I retry once again. `npm install npm@2.7.5 -g` right?

**Comment by KenanY** [comment] 2015-03-31 13:56
@kud Yes, that's the command.

**Comment by kud** [comment] 2015-03-31 13:56
```console
$ npm install git+ssh://git@github.com:org/private
npm WARN package.json animate.css@3.1.1 No repository field.
npm WARN package.json browsernizr@1.0.2 No repository field.
npm WARN package.json EasyTabs@3.2.0 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json EasyTabs@3.2.0 bugs['web'] should probably be bugs['url'].
npm WARN package.json EasyTabs@3.2.0 Invalid dependency: jquery ["1.4.3","1.5","1.6","1.7"]
npm ERR! git clone --template=/Users/kud/.npm/_git-remotes/_templates --mirror git://github.com/org/private.git /Users/kud/.npm/_git-remotes/git-github-com-org-private-git-a08d8794
```

**Comment by kud** [comment] 2015-03-31 13:57
Contrary to `2.7.4`, it doesn't break the installation but it still doesn't install it. Which works perfectly with `2.7.1`.

**Comment by kud** [comment] 2015-03-31 13:59
Tried with `2.7.3`, it also works.

**Comment by jonathanong** [comment] 2015-03-31 16:41
bump. 

too bad npm is packaged with iojs now. also, is this not tested or what?

**Comment by othiym23** [comment] 2015-03-31 19:03
@kud I wasn't able to reproduce this, although I did notice that the error messaging isn't what it could be:

```
bauchelain% mkdir test-private-dependencies
bauchelain% cd test-private-dependencies
bauchelain% npm init -y
Wrote to /Users/ogd/Documents/projects/test-private-dependencies/package.json:

{
  "name": "test-private-dependencies",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Forrest L Norvell <ogd@aoaioxxysz.net>",
  "license": "MIT"
}

bauchelain% npm i -S org/private
npm WARN package.json test-private-dependencies@1.0.0 No description
npm WARN package.json test-private-dependencies@1.0.0 No repository field.
npm WARN package.json test-private-dependencies@1.0.0 No README data
npm ERR! git clone --template=/Users/ogd/.npm/_git-remotes/_templates --mirror git://github.com/org/private.git /Users/ogd/.npm/_git-remotes/git-github-com-org-private-git-3b4151c2
private@1.0.0 node_modules/private
bauchelain% npm ls
test-private-dependencies@1.0.0 /Users/ogd/Documents/projects/test-private-dependencies
└── private@1.0.0
```

**Comment by kud** [comment] 2015-03-31 19:19
In your code, npm does
```
npm ERR! git clone --template=/Users/ogd/.npm/_git-remotes/_templates --mirror git://github.com/org/private.git /Users/ogd/.npm/_git-remotes/git-github-com-org-private-git-3b4151c2
private@1.0.0 node_modules/private
```
but `git://github.com/org/private.git` does not exist. It was an example. You have to create your own private repo on github

**Comment by rmg** [comment] 2015-03-31 19:51
Upgrading from npm@2.7.4 to npm@2.7.5 worked for me. Still see a complaint about the `git clone --template...` but the installation appears to work.

**Comment by kud** [comment] 2015-03-31 19:59
Indeed, I didn't checked if it installed it well as I have the quite same error. Thank you @rmg. I'll have a try.

**Comment by iarna** [comment] 2015-03-31 20:19
kud: Yes, he edited his output in the same way you did. It obviously wouldn't work at all with `org/project`.

**Comment by kud** [comment] 2015-03-31 20:23
Oh my bad. ;)

As I said, I will try with 2.7.5 tomorrow. ^^

**Comment by kellyrmilligan** [comment] 2015-04-01 14:51
busted for me as well on 2.7.4 and 2.7.5, 

npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror git://github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/git-github-com-tastemade-tm-network-api-git-f3a4cc66
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b: Cloning into bare repository '/Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b'...
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b: Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b: Permission denied (publickey).
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b:
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b: and the repository exists.
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/kellymilligan/.nvm/versions/node/v0.12.2/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/kellymilligan/.npm/_git-remotes/_templates --mirror ssh://git@github.com/tastemade/tm-network-api.git /Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b
npm ERR! Cloning into bare repository '/Users/kellymilligan/.npm/_git-remotes/ssh-git-github-com-tastemade-tm-network-api-git-3ede272b'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kellymilligan/Documents/code/tm-web/npm-debug.log


was working with 0.12.1 and npm 2.5.1

**Comment by atrepca** [comment] 2015-04-01 16:40
Hit the bug too, with version `2.7.4`. Downgraded with `npm install -g npm@2.7.3` which works.

**Comment by int3h** [comment] 2015-04-01 23:19
:+1: I got this bug on `2.7.4` and `2.7.5` on both Ubuntu Linux (using the NodeSource PPA version of Node.js v0.10.38) and Mac OS X 10.9.5 (using Node.js 0.10.38 installed via `n`).

The command I run on my Mac is `npm install git+ssh://git@github.com:myorg/privaterepo.git`. The error output (sanitized of my username and exact GitHub private repo) is:

```
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo-git-XXXXXXX
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "git+ssh://git@github.com:myorg/privaterepo.git"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.4

npm ERR! Cannot call method 'charAt' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/gr/wxm50t9j3ms9_l_m4wyj8wfm0000gn/T/delme.KXIjw1F8/npm-debug.log
```

The stated `npm-debug.log` file does not exist.

Downgrading to `2.7.3` fixes the issue and the command works as expected.

**Comment by othiym23** [comment] 2015-04-01 23:23
@int3h are you seeing the same error under `npm@2.7.5`? a840a13bbf0330157536381ea8e58d0bd93b4c05 is specifically intended to address

```
npm ERR! Cannot call method 'charAt' of undefined
```

and if it's recurring, there's something happening that I don't yet understand.

**Comment by int3h** [comment] 2015-04-01 23:28
@othiym23 yup, it happens in `npm@2.7.5` as well as `npm@2.7.4` (installed via `npm install -g npm@2.7.5`).

Output (sanitized):
```
npm install git+ssh://git@github.com:myorg/privaterepo.gitls
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX: Cloning into bare repository '/Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX'...
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX: ERROR: Repository not found.
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX:
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror ssh://git@github.com/myorg/privaterepo.gitls.git /Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX: and the repository exists.
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "git+ssh://git@github.com:myorg/privaterepo.gitls"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.5
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/me/.npm/_git-remotes/ssh-git-github-com-myorg-privaterepo-gitls-git-XXXXXXXX'...
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!      /private/var/folders/gr/wxm50t9j3ms9_l_m4wyj8wfm0000gn/T/delme.tn2qwpWS/npm-debug.log
```

As before, the `npm-debug.log` file does not exist.

**Comment by othiym23** [comment] 2015-04-01 23:41
@int3h I get your results under `npm@2.7.4`, but not `npm@2.7.5`, so I'm very curious to know what's going wrong for you with `npm@2.7.5`, as I have no idea how cloning from an explicit `git+ssh:` URL could be failing (assuming the necessary ssh keys are in place) under `npm@2.7.5`.

**Comment by othiym23** [comment] 2015-04-01 23:43
Whoops... :ship:s passing in the night there. @int3h, let me know how it goes!

**Comment by int3h** [comment] 2015-04-01 23:53
@othiym23 On `npm@2.7.5`, the `charAt` bug is gone, but I get the following errors when installing:

```bash
$ npm install git+ssh://git@github.com:myorg/privaterepo.git
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo-git-XXXXXXXX
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo2.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo2-git-XXXXXXXX
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo3.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo3-git-XXXXXXXX
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo4.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo4-git-XXXXXXXX
npm ERR! git clone --template=/Users/me/.npm/_git-remotes/_templates --mirror git://github.com/myorg/privaterepo5.git /Users/me/.npm/_git-remotes/git-github-com-myorg-privaterepo5-git-XXXXXXXX
...
```

Where `privaterepo` is the repo of the module I'm explicitly installing, and `privaterepoN` is the private repo of a dependency of the module I'm installing (all under the same org). There is one error for each private repo installed as a dependency, plus the error for the private repo of the module I'm installing.

The module appears to still install, despite the errors. Those errors might be a different bug, though. And they're enough to mess up my server orchestration system :weary:.

**Comment by othiym23** [comment] 2015-04-01 23:59
@int3h Thank you! This is a full-blown constellation of clusterfluff, in that a useful debugging change made in another commit (44da66456b530c049ff50953f78368460df87461) ended up causing problems here due to a change that we made to make the CLI treat GitHub shortcuts consistently between the command line and CLI (I'll write up everything that's going on here when I figure out how to fix it). Those extraneous errors will be gone in the next version of npm.

**Comment by int3h** [comment] 2015-04-02 00:25
@othiym23 Awesome, thanks for looking into it! I'll stay on `npm@2.7.3` for now. Looking forward to that write up! :sunny:

**Comment by kud** [comment] 2015-04-02 08:08
Am I wrong by saying It shouldn't be `git://github.com/org/private.git` but `git@github.com:org/private.git` when `git+ssh` in `package.json`?

**Comment by othiym23** [comment] 2015-04-02 08:19
kud: I have a longer explanation to come, but the short version is that npm handles GitHub dependencies in a special way, and so it now always tries to clone via plain `git:` first before falling back to `git+ssh:`, regardless of how GitHub dependencies are specified on the command line or in `package.json`.

**Comment by kud** [comment] 2015-04-02 09:05
Okay thank you. ;)

I don't really like the error on `2.7.5` so I stay with `2.7.3` for the moment. ;) 

Thank you anyway for the support, it's really cool.

**Comment by othiym23** [comment] 2015-04-03 08:18
This is handled by the fixes to #7829 and #7630, which are included in the soon-to-be-published `npm@2.7.6`.

**Closed by othiym23** 2015-04-03 08:18 UTC
Labels: git, support

**Comment by kud** [comment] 2015-04-03 08:40
Okay thank you ;)

**Comment by DelvarWorld** [comment] 2015-04-09 18:34
will this land soon?:)

**Comment by DelvarWorld** [comment] 2015-04-09 18:50
When I install node with the official binary I then *cannot* install a specific version of NPM :( 

    $ npm install -g npm@2.7.3

        npm ERR! Darwin 14.3.0
        npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "npm@2.7.3"
        npm ERR! node v0.12.2
        npm ERR! npm  v2.7.4
        npm ERR! path /usr/local/lib/node_modules/npm/.eslintrc
        npm ERR! code EACCES
        npm ERR! errno -13

        npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/npm/.eslintrc'
        npm ERR!     at Error (native)

**Comment by KenanY** [comment] 2015-04-09 18:58
@DelvarWorld Have you tried using `sudo`? Looks like your user account does not have permission to modify `/usr/local`.

**Comment by DelvarWorld** [comment] 2015-04-09 19:29
I had a previous bad installation of nodejs which might have been done with sudo. I removed the node stuff from my machine and reinstalled using homebrew and that seemed to fix the sudo access error. @KenanY I personally wouldn't want to try any node / npm installs with sudo as that can mess up long term permissions.

**Comment by KenanY** [comment] 2015-04-09 22:21
@DelvarWorld I agree :) hopefully more and more users discover sudo-less node/npm installs with resources like https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by ptmccarthy** [comment] 2015-04-15 22:24
2.7.6 fixed this for me, thanks!

**Comment by base2build** [comment] 2015-04-16 05:52
Same here - thanks!

**Comment by mbrewster** [comment] 2015-04-16 05:52
Same here - working in 2.7.6. Thanks!

**Comment by inkub8** [comment] 2015-04-20 19:07
2.7.6 not working for me.  No error, but it didn't update the project either.  Have switched back to 2.7.1, which works fine.

**Comment by othiym23** [comment] 2015-04-20 20:28
@inkub8 I think you're probably having a separate issue. Can you try updating to `npm@2.8.3` (which is the newest stable version of npm) and seeing if this behavior continues, and if so, filing a new issue? Thanks!

**Comment by gdibble** [comment] 2015-04-30 22:31
:rotating_light: FYI affected windoze users: pay special attention to the PATH notes @ https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by jemymaRC** [comment] 2016-04-25 11:46
For those with x64 machines please try this:
http://blog.jimdhughes.com/2015/04/09/perils-with-node-gyp-and-windows-development/

It helped me.
