### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by theoneLee** [npm/npm#12072] opened 2016-03-25 22:14 UTC
I am trying to install hexo.But I encounter some error.

```
PS D:\win\software\Hexo> npm install -g hexo
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\win\\software\\NodeJs\\node.exe" "D:\\win\\software\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "hexo"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\win\\software\\NodeJs\\node.exe" "D:\\win\\software\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "hexo"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\win\\software\\NodeJs\\node.exe" "D:\\win\\software\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "hexo"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\win\\software\\NodeJs\\node.exe" "D:\\win\\software\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "hexo"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! registry error parsing json
```

**Comment by zkat** [comment] 2016-03-25 23:35
Hi! Thanks for reporting this. I'm marking this as a duplicate of #12072

If you have a reliable reproduction of this with a minimal package, and if the error persists after upgrading npm, please comment on that thread so we can keep collecting details on something relatively hard to track.

Since it's a duplicate, I'm also closing this.

**Closed by zkat** 2016-03-25 23:35 UTC
