### ISSUE TITLE
npm ERR! shasum check failed

### ISSUE THREAD

**Issue by rusamgr8** [npm/npm#12289] opened 2016-04-09 16:50 UTC
```
npm ERR! Expected: af493d5df4688d917d778b0934d1739b9be6efe6
npm ERR! Actual:   cd3c7b33c764895c632392ca4208c353801e8882
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
```

**Comment by busches** [comment] 2016-10-17 20:37
Are still seeing this issue when installing `ionic`? 

cc\ @KenanY

**Comment by zkat** [comment] 2016-12-09 00:43
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:43 UTC
Labels: shasum, support
