### ISSUE TITLE
Global uninstall crash

### ISSUE THREAD

**Issue by Timer** [npm/npm#16801] opened 2017-05-30 21:47 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
Joes-MacBook-Pro:Work joe$ npm uninstall -g yarn source-map-explorer flow-bin create-react-app
Unhandled rejection Error: Argument #2: Expected string but got null json-stable-stringify@^1.0.1 fetched in 132ms
    at addDependency (/Users/joe/n/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/joe/n/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/joe/n/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/joe/n/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/joe/n/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/joe/n/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/joe/n/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/joe/n/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/joe/n/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/joe/n/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/joe/n/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/joe/n/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/joe/n/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/joe/n/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joe/.npm/_logs/2017-05-30T21_43_08_481Z-debug.log
```

#### How can the CLI team reproduce the problem?

Try uninstalling a global package.

### supporting information:

 - `npm -v` prints: `5.0.0`
 - `node -v` prints: `v8.0.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/joe/n/bin/node',
1 verbose cli   '/Users/joe/n/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'yarn',
1 verbose cli   'source-map-explorer',
1 verbose cli   'flow-bin',
1 verbose cli   'create-react-app' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly install loadIdealTree
7 silly install cloneCurrentTreeToIdealTree
8 silly install loadShrinkwrap
9 silly uninstall loadAllDepsIntoIdealTree
10 silly install loadAllDepsIntoIdealTree
11 http fetch GET 200 https://registry.npmjs.org/yarn 669ms
12 silly pacote tag manifest for yarn@latest fetched in 698ms
13 http fetch GET 200 https://registry.npmjs.org/cmd-shim 141ms
14 silly pacote range manifest for cmd-shim@^2.0.1 fetched in 144ms
15 http fetch GET 304 https://registry.npmjs.org/ini 154ms (from cache)
16 silly pacote range manifest for ini@^1.3.4 fetched in 156ms
17 http fetch GET 200 https://registry.npmjs.org/babel-runtime 307ms
18 silly pacote range manifest for babel-runtime@^6.0.0 fetched in 313ms
19 http fetch GET 200 https://registry.npmjs.org/death 325ms
20 silly pacote range manifest for death@^1.0.0 fetched in 330ms
21 http fetch GET 200 https://registry.npmjs.org/bytes 357ms
22 http fetch GET 200 https://registry.npmjs.org/gunzip-maybe 352ms
23 http fetch GET 200 https://registry.npmjs.org/debug 356ms
24 http fetch GET 200 https://registry.npmjs.org/commander 360ms
25 silly pacote range manifest for debug@^2.2.0 fetched in 362ms
26 silly pacote range manifest for commander@^2.9.0 fetched in 366ms
27 http fetch GET 200 https://registry.npmjs.org/chalk 369ms
28 http fetch GET 304 https://registry.npmjs.org/detect-indent 366ms (from cache)
29 silly pacote range manifest for chalk@^1.1.1 fetched in 374ms
30 silly pacote range manifest for gunzip-maybe@^1.4.0 fetched in 380ms
31 silly pacote range manifest for bytes@^2.4.0 fetched in 386ms
32 silly pacote range manifest for detect-indent@^5.0.0 fetched in 388ms
33 http fetch GET 304 https://registry.npmjs.org/invariant 105ms (from cache)
34 silly pacote range manifest for invariant@^2.2.0 fetched in 107ms
35 http fetch GET 304 https://registry.npmjs.org/is-builtin-module 109ms (from cache)
36 silly pacote range manifest for is-builtin-module@^1.0.0 fetched in 110ms
37 http fetch GET 200 https://registry.npmjs.org/inquirer 149ms
38 silly pacote range manifest for inquirer@^3.0.1 fetched in 153ms
39 http fetch GET 200 https://registry.npmjs.org/mkdirp 108ms
40 http fetch GET 304 https://registry.npmjs.org/leven 128ms (from cache)
41 silly pacote range manifest for mkdirp@^0.5.1 fetched in 111ms
42 silly pacote range manifest for leven@^2.0.0 fetched in 132ms
43 http fetch GET 304 https://registry.npmjs.org/minimatch 120ms (from cache)
44 silly pacote range manifest for minimatch@^3.0.3 fetched in 123ms
45 http fetch GET 200 https://registry.npmjs.org/node-emoji 124ms
46 silly pacote range manifest for node-emoji@^1.0.4 fetched in 127ms
47 http fetch GET 200 https://registry.npmjs.org/object-path 112ms
48 silly pacote range manifest for object-path@^0.11.2 fetched in 115ms
49 http fetch GET 304 https://registry.npmjs.org/loud-rejection 160ms (from cache)
50 silly pacote range manifest for loud-rejection@^1.2.0 fetched in 162ms
51 http fetch GET 304 https://registry.npmjs.org/is-ci 214ms (from cache)
52 silly pacote range manifest for is-ci@^1.0.10 fetched in 216ms
53 http fetch GET 200 https://registry.npmjs.org/proper-lockfile 156ms
54 silly pacote range manifest for proper-lockfile@^2.0.0 fetched in 163ms
55 http fetch GET 200 https://registry.npmjs.org/read 149ms
56 http fetch GET 304 https://registry.npmjs.org/camelcase 614ms (from cache)
57 silly pacote range manifest for read@^1.0.7 fetched in 173ms
58 http fetch GET 200 https://registry.npmjs.org/rimraf 121ms
59 silly pacote range manifest for rimraf@^2.5.0 fetched in 125ms
60 silly pacote range manifest for camelcase@^4.0.0 fetched in 634ms
61 http fetch GET 200 https://registry.npmjs.org/tar-fs 106ms
62 http fetch GET 200 https://registry.npmjs.org/semver 122ms
63 silly pacote range manifest for semver@^5.1.0 fetched in 124ms
64 http fetch GET 304 https://registry.npmjs.org/strip-bom 114ms (from cache)
65 silly pacote range manifest for mkdirp@~0.5.0 fetched in 1ms
66 silly pacote range manifest for tar-fs@^1.15.1 fetched in 112ms
67 silly pacote range manifest for strip-bom@^3.0.0 fetched in 119ms
68 http fetch GET 200 https://registry.npmjs.org/request 163ms
69 http fetch GET 200 https://registry.npmjs.org/request-capture-har 162ms
70 silly pacote range manifest for request@^2.81.0 fetched in 166ms
71 silly pacote range manifest for request-capture-har@^1.2.2 fetched in 177ms
72 http fetch GET 200 https://registry.npmjs.org/tar-stream 110ms
73 silly pacote range manifest for tar-stream@^1.5.2 fetched in 112ms
74 http fetch GET 304 https://registry.npmjs.org/ansi-styles 119ms (from cache)
75 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 125ms
76 http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 160ms
77 silly pacote range manifest for regenerator-runtime@^0.10.0 fetched in 162ms
78 http fetch GET 200 https://registry.npmjs.org/v8-compile-cache 199ms
79 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 132ms (from cache)
80 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in 133ms
81 silly pacote range manifest for v8-compile-cache@^1.1.0 fetched in 204ms
82 http fetch GET 200 https://registry.npmjs.org/core-js 194ms
83 silly pacote range manifest for core-js@^2.4.0 fetched in 196ms
84 http fetch GET 200 https://registry.npmjs.org/graceful-fs 233ms
85 silly pacote range manifest for graceful-fs@^4.1.2 fetched in 235ms
86 http fetch GET 200 https://registry.npmjs.org/ms 242ms
87 silly pacote version manifest for ms@2.0.0 fetched in 247ms
88 http fetch GET 304 https://registry.npmjs.org/graceful-readlink 239ms (from cache)
89 http fetch GET 304 https://registry.npmjs.org/validate-npm-package-license 269ms (from cache)
90 silly pacote range manifest for validate-npm-package-license@^3.0.1 fetched in 270ms
91 silly pacote range manifest for graceful-readlink@>= 1.0.0 fetched in 243ms
92 http fetch GET 304 https://registry.npmjs.org/has-ansi 111ms (from cache)
93 silly pacote range manifest for has-ansi@^2.0.0 fetched in 112ms
94 http fetch GET 304 https://registry.npmjs.org/strip-ansi 118ms (from cache)
95 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 119ms
96 http fetch GET 200 https://registry.npmjs.org/uuid 335ms
97 silly pacote range manifest for uuid@^3.0.1 fetched in 337ms
98 http fetch GET 304 https://registry.npmjs.org/supports-color 110ms (from cache)
99 silly pacote range manifest for supports-color@^2.0.0 fetched in 113ms
100 silly pacote range manifest for chalk@^1.0.0 fetched in 1ms
101 http fetch GET 200 https://registry.npmjs.org/is-deflate 154ms
102 http fetch GET 200 https://registry.npmjs.org/is-gzip 128ms
103 http fetch GET 304 https://registry.npmjs.org/browserify-zlib 168ms (from cache)
104 silly pacote range manifest for browserify-zlib@^0.1.4 fetched in 169ms
105 silly pacote range manifest for is-deflate@^1.0.0 fetched in 160ms
106 silly pacote range manifest for is-gzip@^1.0.0 fetched in 134ms
107 http fetch GET 200 https://registry.npmjs.org/peek-stream 115ms
108 silly pacote range manifest for peek-stream@^1.1.0 fetched in 119ms
109 http fetch GET 200 https://registry.npmjs.org/pumpify 120ms
110 http fetch GET 200 https://registry.npmjs.org/through2 118ms
111 silly pacote range manifest for pumpify@^1.3.3 fetched in 122ms
112 silly pacote range manifest for through2@^2.0.3 fetched in 122ms
113 http fetch GET 200 https://registry.npmjs.org/loose-envify 124ms
114 silly pacote range manifest for loose-envify@^1.0.0 fetched in 133ms
115 http fetch GET 304 https://registry.npmjs.org/builtin-modules 124ms (from cache)
116 silly pacote range manifest for builtin-modules@^1.0.0 fetched in 125ms
117 http fetch GET 304 https://registry.npmjs.org/ansi-escapes 115ms (from cache)
118 silly pacote range manifest for ansi-escapes@^1.1.0 fetched in 118ms
119 http fetch GET 304 https://registry.npmjs.org/cli-width 135ms (from cache)
120 silly pacote range manifest for cli-width@^2.0.0 fetched in 136ms
121 http fetch GET 304 https://registry.npmjs.org/run-async 119ms (from cache)
122 silly pacote range manifest for run-async@^2.2.0 fetched in 120ms
123 http fetch GET 304 https://registry.npmjs.org/mute-stream 154ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/cli-cursor 237ms (from cache)
125 silly pacote version manifest for mute-stream@0.0.7 fetched in 157ms
126 http fetch GET 200 https://registry.npmjs.org/external-editor 183ms
127 http fetch GET 200 https://registry.npmjs.org/lodash 168ms
128 http fetch GET 304 https://registry.npmjs.org/rx 142ms (from cache)
129 silly pacote range manifest for cli-cursor@^2.1.0 fetched in 244ms
130 silly pacote range manifest for lodash@^4.3.0 fetched in 173ms
131 silly pacote range manifest for rx@^4.1.0 fetched in 146ms
132 silly pacote range manifest for external-editor@^2.0.1 fetched in 193ms
133 http fetch GET 304 https://registry.npmjs.org/through 147ms (from cache)
134 silly pacote range manifest for through@^2.3.6 fetched in 149ms
135 http fetch GET 304 https://registry.npmjs.org/string-width 157ms (from cache)
136 silly pacote range manifest for mute-stream@~0.0.4 fetched in 4ms
137 http fetch GET 304 https://registry.npmjs.org/figures 210ms (from cache)
138 silly pacote range manifest for string-width@^2.0.0 fetched in 159ms
139 silly pacote range manifest for figures@^2.0.0 fetched in 214ms
140 http fetch GET 304 https://registry.npmjs.org/brace-expansion 101ms (from cache)
141 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 102ms
142 silly pacote range manifest for tar-stream@^1.1.2 fetched in 1ms
143 http fetch GET 200 https://registry.npmjs.org/string.prototype.codepointat 99ms
144 silly pacote range manifest for string.prototype.codepointat@^0.2.0 fetched in 102ms
145 http fetch GET 200 https://registry.npmjs.org/signal-exit 119ms
146 silly pacote range manifest for signal-exit@^3.0.0 fetched in 120ms
147 http fetch GET 304 https://registry.npmjs.org/currently-unhandled 150ms (from cache)
148 silly pacote range manifest for currently-unhandled@^0.4.1 fetched in 151ms
149 http fetch GET 200 https://registry.npmjs.org/pump 126ms
150 http fetch GET 200 https://registry.npmjs.org/chownr 132ms
151 silly pacote range manifest for pump@^1.0.0 fetched in 132ms
152 http fetch GET 200 https://registry.npmjs.org/minimist 220ms
153 silly pacote range manifest for chownr@^1.0.1 fetched in 144ms
154 silly pacote version manifest for minimist@0.0.8 fetched in 223ms
155 http fetch GET 304 https://registry.npmjs.org/aws-sign2 110ms (from cache)
156 silly pacote range manifest for aws-sign2@~0.6.0 fetched in 112ms
157 http fetch GET 304 https://registry.npmjs.org/glob 153ms (from cache)
158 silly pacote range manifest for glob@^7.0.5 fetched in 171ms
159 http fetch GET 200 https://registry.npmjs.org/retry 191ms
160 http fetch GET 304 https://registry.npmjs.org/aws4 105ms (from cache)
161 silly pacote range manifest for retry@^0.10.0 fetched in 195ms
162 silly pacote range manifest for aws4@^1.2.1 fetched in 107ms
163 http fetch GET 304 https://registry.npmjs.org/ci-info 202ms (from cache)
164 silly pacote range manifest for ci-info@^1.0.0 fetched in 203ms
165 http fetch GET 304 https://registry.npmjs.org/caseless 157ms (from cache)
166 silly pacote range manifest for caseless@~0.12.0 fetched in 158ms
167 http fetch GET 304 https://registry.npmjs.org/form-data 121ms (from cache)
168 silly pacote range manifest for form-data@~2.1.1 fetched in 124ms
169 http fetch GET 304 https://registry.npmjs.org/forever-agent 138ms (from cache)
170 silly pacote range manifest for forever-agent@~0.6.1 fetched in 139ms
171 http fetch GET 304 https://registry.npmjs.org/extend 153ms (from cache)
172 silly pacote range manifest for extend@~3.0.0 fetched in 154ms
173 http fetch GET 304 https://registry.npmjs.org/is-typedarray 133ms (from cache)
174 silly pacote range manifest for is-typedarray@~1.0.0 fetched in 137ms
175 http fetch GET 304 https://registry.npmjs.org/isstream 141ms (from cache)
176 http fetch GET 304 https://registry.npmjs.org/hawk 152ms (from cache)
177 http fetch GET 304 https://registry.npmjs.org/http-signature 148ms (from cache)
178 silly pacote range manifest for hawk@~3.1.3 fetched in 157ms
179 silly pacote range manifest for isstream@~0.1.2 fetched in 146ms
180 silly pacote range manifest for http-signature@~1.1.0 fetched in 151ms
181 http fetch GET 200 https://registry.npmjs.org/json-stringify-safe 105ms
182 silly pacote range manifest for json-stringify-safe@~5.0.1 fetched in 106ms
183 http fetch GET 304 https://registry.npmjs.org/combined-stream 237ms (from cache)
184 silly pacote range manifest for combined-stream@~1.0.5 fetched in 240ms
185 silly pacote range manifest for uuid@^3.0.0 fetched in 2ms
186 http fetch GET 200 https://registry.npmjs.org/mime-types 103ms
187 silly pacote range manifest for mime-types@~2.1.7 fetched in 106ms
188 http fetch GET 304 https://registry.npmjs.org/oauth-sign 98ms (from cache)
189 http fetch GET 304 https://registry.npmjs.org/performance-now 92ms (from cache)
190 silly pacote range manifest for performance-now@^0.2.0 fetched in 93ms
191 silly pacote range manifest for oauth-sign@~0.8.1 fetched in 101ms
192 http fetch GET 304 https://registry.npmjs.org/tough-cookie 113ms (from cache)
193 silly pacote range manifest for tough-cookie@~2.3.0 fetched in 115ms
194 http fetch GET 304 https://registry.npmjs.org/safe-buffer 128ms (from cache)
195 silly pacote range manifest for safe-buffer@^5.0.1 fetched in 130ms
196 http fetch GET 304 https://registry.npmjs.org/stringstream 132ms (from cache)
197 silly pacote range manifest for stringstream@~0.0.4 fetched in 134ms
198 http fetch GET 200 https://registry.npmjs.org/qs 159ms
199 silly pacote range manifest for qs@~6.4.0 fetched in 170ms
200 http fetch GET 304 https://registry.npmjs.org/tunnel-agent 127ms (from cache)
201 http fetch GET 304 https://registry.npmjs.org/har-validator 341ms (from cache)
202 silly pacote range manifest for tunnel-agent@^0.6.0 fetched in 131ms
203 silly pacote range manifest for har-validator@~4.2.1 fetched in 345ms
204 http fetch GET 200 https://registry.npmjs.org/bl 134ms
205 silly pacote range manifest for bl@^1.0.0 fetched in 137ms
206 http fetch GET 304 https://registry.npmjs.org/xtend 140ms (from cache)
207 http fetch GET 200 https://registry.npmjs.org/end-of-stream 149ms
208 silly pacote range manifest for xtend@^4.0.0 fetched in 144ms
209 http fetch GET 304 https://registry.npmjs.org/readable-stream 148ms (from cache)
210 http fetch GET 200 https://registry.npmjs.org/readable-stream 5ms (from cache)
211 silly pacote range manifest for readable-stream@^2.0.0 fetched in 154ms
212 silly pacote range manifest for readable-stream@^2.1.5 fetched in 13ms
213 silly pacote range manifest for end-of-stream@^1.0.0 fetched in 167ms
214 silly pacote range manifest for xtend@~4.0.1 fetched in 6ms
215 http fetch GET 304 https://registry.npmjs.org/spdx-correct 140ms (from cache)
216 silly pacote range manifest for spdx-correct@~1.0.0 fetched in 148ms
217 http fetch GET 304 https://registry.npmjs.org/spdx-expression-parse 145ms (from cache)
218 http fetch GET 304 https://registry.npmjs.org/ansi-regex 147ms (from cache)
219 silly pacote range manifest for spdx-expression-parse@~1.0.0 fetched in 151ms
220 http fetch GET 200 https://registry.npmjs.org/duplexify 117ms
221 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 154ms
222 http fetch GET 304 https://registry.npmjs.org/pako 129ms (from cache)
223 http fetch GET 200 https://registry.npmjs.org/duplexify 122ms
224 silly pacote range manifest for pako@~0.2.0 fetched in 135ms
225 silly pacote range manifest for duplexify@^3.5.0 fetched in 130ms
226 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 3ms
227 http fetch GET 304 https://registry.npmjs.org/inherits 120ms (from cache)
228 silly pacote range manifest for duplexify@^3.1.2 fetched in 133ms
229 silly pacote range manifest for inherits@^2.0.1 fetched in 122ms
230 http fetch GET 304 https://registry.npmjs.org/js-tokens 141ms (from cache)
231 silly pacote range manifest for js-tokens@^3.0.0 fetched in 142ms
232 http fetch GET 304 https://registry.npmjs.org/is-promise 142ms (from cache)
233 silly pacote range manifest for end-of-stream@^1.1.0 fetched in 2ms
234 silly pacote range manifest for is-promise@^2.1.0 fetched in 143ms
235 http fetch GET 304 https://registry.npmjs.org/restore-cursor 152ms (from cache)
236 silly pacote range manifest for restore-cursor@^2.0.0 fetched in 154ms
237 http fetch GET 200 https://registry.npmjs.org/iconv-lite 122ms
238 silly pacote range manifest for iconv-lite@^0.4.17 fetched in 124ms
239 silly pacote range manifest for inherits@2 fetched in 3ms
240 http fetch GET 200 https://registry.npmjs.org/jschardet 111ms
241 silly pacote range manifest for minimatch@^3.0.4 fetched in 2ms
242 http fetch GET 304 https://registry.npmjs.org/tmp 113ms (from cache)
243 silly pacote range manifest for tmp@^0.0.31 fetched in 114ms
244 silly pacote range manifest for jschardet@^1.4.2 fetched in 119ms
245 http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 119ms (from cache)
246 http fetch GET 304 https://registry.npmjs.org/balanced-match 114ms (from cache)
247 silly pacote range manifest for is-fullwidth-code-point@^2.0.0 fetched in 120ms
248 silly pacote range manifest for balanced-match@^0.4.1 fetched in 116ms
249 silly pacote range manifest for combined-stream@^1.0.5 fetched in 2ms
250 silly pacote range manifest for mime-types@^2.1.12 fetched in 2ms
251 http fetch GET 304 https://registry.npmjs.org/array-find-index 117ms (from cache)
252 silly pacote range manifest for array-find-index@^1.0.1 fetched in 120ms
253 http fetch GET 304 https://registry.npmjs.org/concat-map 134ms (from cache)
254 silly pacote version manifest for concat-map@0.0.1 fetched in 135ms
255 http fetch GET 304 https://registry.npmjs.org/once 142ms (from cache)
256 silly pacote range manifest for once@^1.3.1 fetched in 143ms
257 http fetch GET 304 https://registry.npmjs.org/fs.realpath 151ms (from cache)
258 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 152ms
259 http fetch GET 304 https://registry.npmjs.org/asynckit 120ms (from cache)
260 silly pacote range manifest for asynckit@^0.4.0 fetched in 122ms
261 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 141ms (from cache)
262 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 143ms
263 http fetch GET 304 https://registry.npmjs.org/once 161ms (from cache)
264 silly pacote range manifest for once@^1.3.0 fetched in 163ms
265 http fetch GET 304 https://registry.npmjs.org/inflight 193ms (from cache)
266 silly pacote range manifest for inflight@^1.0.4 fetched in 193ms
267 http fetch GET 200 https://registry.npmjs.org/cryptiles 173ms
268 http fetch GET 200 https://registry.npmjs.org/boom 178ms
269 silly pacote range manifest for cryptiles@2.x.x fetched in 180ms
270 silly pacote range manifest for boom@2.x.x fetched in 184ms
271 http fetch GET 304 https://registry.npmjs.org/sntp 180ms (from cache)
272 silly pacote range manifest for sntp@1.x.x fetched in 183ms
273 http fetch GET 304 https://registry.npmjs.org/hoek 202ms (from cache)
274 silly pacote range manifest for readable-stream@^2.0.5 fetched in 4ms
275 silly pacote range manifest for hoek@2.x.x fetched in 206ms
276 http fetch GET 304 https://registry.npmjs.org/jsprim 182ms (from cache)
277 http fetch GET 304 https://registry.npmjs.org/assert-plus 192ms (from cache)
278 silly pacote range manifest for jsprim@^1.2.2 fetched in 185ms
279 silly pacote range manifest for assert-plus@^0.2.0 fetched in 194ms
280 http fetch GET 304 https://registry.npmjs.org/mime-db 139ms (from cache)
281 http fetch GET 304 https://registry.npmjs.org/delayed-stream 153ms (from cache)
282 silly pacote range manifest for inherits@~2.0.1 fetched in 3ms
283 http fetch GET 304 https://registry.npmjs.org/sshpk 174ms (from cache)
284 silly pacote range manifest for mime-db@~1.27.0 fetched in 145ms
285 silly pacote range manifest for delayed-stream@~1.0.0 fetched in 157ms
286 silly pacote range manifest for sshpk@^1.7.0 fetched in 178ms
287 silly pacote range manifest for once@^1.4.0 fetched in 2ms
288 http fetch GET 304 https://registry.npmjs.org/punycode 147ms (from cache)
289 silly pacote range manifest for punycode@^1.4.1 fetched in 155ms
290 silly pacote version manifest for end-of-stream@1.0.0 fetched in 2ms
291 http fetch GET 304 https://registry.npmjs.org/core-util-is 121ms (from cache)
292 silly pacote range manifest for core-util-is@~1.0.0 fetched in 123ms
293 http fetch GET 304 https://registry.npmjs.org/buffer-shims 125ms (from cache)
294 silly pacote range manifest for buffer-shims@~1.0.0 fetched in 126ms
295 silly pacote range manifest for signal-exit@^3.0.2 fetched in 1ms
296 http fetch GET 304 https://registry.npmjs.org/har-schema 161ms (from cache)
297 silly pacote range manifest for har-schema@^1.0.5 fetched in 162ms
298 http fetch GET 200 https://registry.npmjs.org/ajv 190ms
299 silly pacote range manifest for ajv@^4.9.1 fetched in 205ms
300 silly pacote version manifest for assert-plus@1.0.0 fetched in 2ms
301 http fetch GET 304 https://registry.npmjs.org/isarray 118ms (from cache)
302 silly pacote range manifest for isarray@~1.0.0 fetched in 119ms
303 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 117ms (from cache)
304 silly pacote range manifest for process-nextick-args@~1.0.6 fetched in 118ms
305 http fetch GET 304 https://registry.npmjs.org/spdx-license-ids 116ms (from cache)
306 silly pacote range manifest for spdx-license-ids@^1.0.2 fetched in 118ms
307 http fetch GET 304 https://registry.npmjs.org/string_decoder 143ms (from cache)
308 silly pacote range manifest for string_decoder@~1.0.0 fetched in 145ms
309 silly pacote range manifest for assert-plus@^1.0.0 fetched in 1ms
310 http fetch GET 304 https://registry.npmjs.org/util-deprecate 148ms (from cache)
311 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 150ms
312 http fetch GET 304 https://registry.npmjs.org/onetime 118ms (from cache)
313 http fetch GET 304 https://registry.npmjs.org/os-tmpdir 114ms (from cache)
314 silly pacote range manifest for onetime@^2.0.0 fetched in 120ms
315 silly pacote range manifest for os-tmpdir@~1.0.1 fetched in 120ms
316 http fetch GET 304 https://registry.npmjs.org/wrappy 112ms (from cache)
317 silly pacote range manifest for wrappy@1 fetched in 113ms
318 http fetch GET 304 https://registry.npmjs.org/extsprintf 105ms (from cache)
319 silly pacote version manifest for extsprintf@1.0.2 fetched in 106ms
320 http fetch GET 304 https://registry.npmjs.org/verror 101ms (from cache)
321 silly pacote version manifest for verror@1.3.6 fetched in 102ms
322 http fetch GET 304 https://registry.npmjs.org/json-schema 107ms (from cache)
323 silly pacote version manifest for json-schema@0.2.3 fetched in 109ms
324 silly pacote range manifest for once@~1.3.0 fetched in 3ms
325 http fetch GET 304 https://registry.npmjs.org/asn1 103ms (from cache)
326 silly pacote range manifest for asn1@~0.2.3 fetched in 104ms
327 http fetch GET 304 https://registry.npmjs.org/dashdash 95ms (from cache)
328 silly pacote range manifest for dashdash@^1.12.0 fetched in 96ms
329 http fetch GET 200 https://registry.npmjs.org/tweetnacl 96ms
330 silly pacote range manifest for tweetnacl@~0.14.0 fetched in 98ms
331 http fetch GET 304 https://registry.npmjs.org/jsbn 112ms (from cache)
332 silly pacote range manifest for jsbn@~0.1.0 fetched in 113ms
333 http fetch GET 304 https://registry.npmjs.org/jodid25519 111ms (from cache)
334 silly pacote range manifest for jodid25519@^1.0.0 fetched in 112ms
335 http fetch GET 304 https://registry.npmjs.org/ecc-jsbn 127ms (from cache)
336 silly pacote range manifest for ecc-jsbn@~0.1.1 fetched in 128ms
337 http fetch GET 200 https://registry.npmjs.org/co 129ms
338 http fetch GET 200 https://registry.npmjs.org/stream-shift 333ms
339 silly pacote range manifest for co@^4.6.0 fetched in 132ms
340 http fetch GET 304 https://registry.npmjs.org/getpass 204ms (from cache)
341 silly pacote range manifest for getpass@^0.1.1 fetched in 206ms
342 silly pacote range manifest for stream-shift@^1.0.0 fetched in 339ms
343 http fetch GET 304 https://registry.npmjs.org/mimic-fn 118ms (from cache)
344 silly pacote range manifest for mimic-fn@^1.0.0 fetched in 120ms
345 http fetch GET 304 https://registry.npmjs.org/bcrypt-pbkdf 147ms (from cache)
346 http fetch GET 304 https://registry.npmjs.org/json-stable-stringify 130ms (from cache)
347 silly pacote range manifest for bcrypt-pbkdf@^1.0.0 fetched in 148ms
348 silly pacote range manifest for tweetnacl@^0.14.3 fetched in 1ms
349 silly pacote range manifest for json-stable-stringify@^1.0.1 fetched in 132ms
350 http fetch GET 304 https://registry.npmjs.org/jsonify 172ms (from cache)
351 silly pacote range manifest for jsonify@~0.0.0 fetched in 173ms
352 error cb() never called!
353 error This is an error with npm itself. Please report this error at:
354 error <https://github.com/npm/npm/issues>
```

Related: #16779

**Comment by clk0115** [comment] 2017-05-31 07:45
Same error message!

**Comment by Timer** [comment] 2017-05-31 13:07
Figured out it's because of old installs. 

Switch to npm4, uninstall all global packages except npm5, switch to npm5 & it works again!

**Comment by teschste** [comment] 2017-05-31 14:24
Same error uninstalling yarn but shorter log file (attached).
[2017-05-31T14_23_17_724Z-debug.txt](https://github.com/npm/npm/files/1041828/2017-05-31T14_23_17_724Z-debug.txt)

**Comment by zkat** [comment] 2017-06-05 15:08
Closing as dupe of https://github.com/npm/npm/issues/16738

**Closed by zkat** 2017-06-05 15:08 UTC
Labels: npm5
