### ISSUE TITLE
Fallback to install <name> when install <tarball file> failed

### ISSUE THREAD

**Issue by XeCycle** [npm/npm#7703] opened 2015-03-22 02:41 UTC
npm install module-name-on-npmjs-registry will fail if a file with the same name exists in cwd, but is not a valid module tarball.  E.g.:
```
mkdir temp
cd temp
touch lodash
npm i lodash
```
--- fail.

**Comment by KenanY** [comment] 2015-03-22 14:52
@XeCycle So you think `npm` should first assume registry?

**Comment by XeCycle** [comment] 2015-03-22 23:26
@KenanY Yes, that covers more cases.  To force installing a local tarball one can say install ./tarball-file-name, if that name exists in the registry, but the reverse is difficult; using user/name may also fail if user/name exists in cwd.

**Comment by iarna** [comment] 2015-04-11 02:31
The current behavior was intended when this was implemented, as such I'm flagging this as a feature request.

**Comment by iarna** [comment] 2016-03-18 23:59
It’s my view that this adds additional complexity to story around package arguments as they’re passed to `npm install`. `npm` went through several variations on how it resolved local arguments when they were first added and the current behavior seemed to be the least confusing solution. The consensus of the CLI team is that this isn’t something we’re going to implement or accept as a pull request. As such, I’m going to close this issue, but thank you for bringing this up.

**Closed by iarna** 2016-03-18 23:59 UTC
Labels: feature-request
