### ISSUE TITLE
ENOENT error while installing node module with latest npm and node 

### ISSUE THREAD

**Issue by DavidBarishev** [npm/npm#10229] opened 2015-11-02 19:11 UTC
Hello!<br>
Im trying to install node - steam , and cant get it to work.
```
npm WARN EPACKAGEJSON loungeBot@ No repository field.
npm WARN EPACKAGEJSON loungeBot@ No license field.
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\steam\node_modules\protobufjs with new installed version
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "steam" "--save"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.11
npm ERR! path D:\test\node_modules\steam\node_modules\protobufjs\node_modules\yargs\node_modules\window-size\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\test\node_modules\steam\node_modules\protobufjs\node_modules\yargs\node_modules\window-size\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\npm-debug.log
npm ERR! code 1
```
As you can see , i have the latest npm and node js , and cant understand why doesn't it work.

**Comment by robertbaker** [comment] 2015-11-02 20:08
Actually you don't anymore :)

NodeJS 5.0 is out, which includes 3.3.6, you can update to 3.3.12 by using npm-windows-upgrade.

However, beware that npm-windows-upgrade does not generate the needed npmrc file, so your global packages would be installed in the wrong place.

**Comment by DavidBarishev** [comment] 2015-11-02 20:13
@robertbaker huh , nice to know , should it fix my problem ?

**Comment by robertbaker** [comment] 2015-11-02 20:15
I think this is related to the hotfix they just pushed, so I think so. Try it!

**Comment by DavidBarishev** [comment] 2015-11-02 20:18
Sure! Will try tomorrow

**Comment by DavidBarishev** [comment] 2015-11-03 13:36
Well this sulution didn't work , this is what i got : 
```
npm WARN EPACKAGEJSON Lounge@0.0.0 No repository field.
npm WARN EPACKAGEJSON Lounge@0.0.0 No license field.
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\steam\node_modules\proto
bufjs with new installed version
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! path F:\LetsSayThisDirIsYonys\node_modules\steam\node_modules\protobufj
s\node_modules\yargs\node_modules\window-size\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'F:\LetsSayThisDirIsYon
ys\node_modules\steam\node_modules\protobufjs\node_modules\yargs\node_modules\wi
ndow-size\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

```
If needed i can provide the npm-debug.log

**Comment by DavidBarishev** [comment] 2015-11-03 14:04
Also important note , on npm v 2 this works fine. It seems like the problem is quite popular  , as multiple people have it

**Comment by geraldvillorente** [comment] 2015-11-04 16:10
I am having the same problem.
```
gerald@von-viel:~/Repo/kalabox$ /home/gerald/.nvm/versions/node/v5.0.0/bin/npm install . -g
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/home/gerald/.nvm/versions/node/v5.0.0/bin/node" "/home/gerald/.nvm/versions/node/v5.0.0/bin/npm" "install" "." "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path /home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gerald/Repo/kalabox/npm-debug.log
```

Even `npm install kalabox -g` is throwing the same error.

**Comment by iarna** [comment] 2015-11-06 19:43
Closing this as a duplicate of #9633

**Closed by iarna** 2015-11-06 19:43 UTC
