### ISSUE TITLE
Unable to publish scoped module, despite public access

### ISSUE THREAD

**Issue by mstade** [npm/npm#12633] opened 2016-05-09 15:51 UTC
Hi, when trying to publish my module, I get the following error:

```bash
$ npm publish --access public
npm ERR! publish Failed PUT 402
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/mstade/.nvm/versions/node/v6.1.0/bin/node" "/Users/mstade/.nvm/versions/node/v6.1.0/bin/npm" "publish" "--access" "public"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code E402

npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @zambezi/prepare-release
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mstade/dev/zambezi/prepare-release/npm-debug.log
```

I've tried logging in again, as well as different npm versions, however nothing seems to do the trick. Any assistance you may be able to provide is much appreciated!

**Comment by andreypopp** [comment] 2016-05-23 11:44
Yes, seeing the same behaviour.

**Comment by mstade** [comment] 2016-05-24 09:34
Have you found any workaround @andreypopp? I haven't been able to publish my module at all.

**Comment by andreypopp** [comment] 2016-05-24 10:33
@mstade nope, I tried to see if `access: public` ends up in `PUT` request's body and it's there. So I guess the problem is on the registry side of things. I'd really like to see a response about that issue from npm as we already have modules published under the same scope.

**Comment by mstade** [comment] 2016-05-24 12:04
Ditto. @othiym23 any news?

**Comment by andreypopp** [comment] 2016-05-30 13:16
The issues is specific to `@prometheusresearch/react-ui` name, I can publish any other scoped packages but not that.

**Comment by othiym23** [comment] 2016-05-31 17:19
@mstade, @andreypopp: This is an issue for [`npm/registry`](https://github.com/npm/registry/issues), as that message is coming from the registry and not the CLI. As such, I'm going to close it, and you should take this over there (or contact <mailto:support@npmjs.com>) if you're still having trouble.

**Closed by othiym23** 2016-05-31 17:19 UTC
Labels: registry, support
