### ISSUE TITLE
shasum check failed for

### ISSUE THREAD

**Issue by MaxEnjoyProgramming** [npm/npm#12137] opened 2016-03-30 02:20 UTC
```
error Windows_NT 6.1.7601
 error argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g"
 error node v5.7.0
 error npm  v3.6.0
error shasum check failed for C:\Users\yuanyz\AppData\Local\Temp\npm-5912-da59decc\registry.npmjs.org\statique\-\statique-2.0.0.tgz
 error Expected: 11fdfc10a2086c8d00382ac35c0718a45063c4ad
 error Actual:   ed40f68a161f7e94d4c76ec731767f38f1d7f97b
 error From:     https://registry.npmjs.org/statique/-/statique-2.0.0.tgz
error If you need help, you may report this error at:
1934 error     <https://github.com/npm/npm/issues>
```

**Comment by zkat** [comment] 2016-12-09 00:45
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:45 UTC
Labels: shasum, support, windows
