### ISSUE TITLE
couldn't install johnny-five

### ISSUE THREAD

**Issue by mehamindran** [npm/npm#12425] opened 2016-04-21 11:52 UTC
This is the log file....

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'johnny-five' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose install initial load of /home/pi/Documents/NodeSamples/LDR_JohnnyFive_Rasp/package.json
5 verbose readDependencies loading dependencies from /home/pi/Documents/NodeSamples/LDR_JohnnyFive_Rasp/package.json
6 silly cache add args [ 'johnny-five', null ]
7 verbose cache add spec johnny-five
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'johnny-five',
8 silly cache add   scope: null,
8 silly cache add   name: 'johnny-five',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed johnny-five@*
10 verbose addNamed "*" is a valid semver range for johnny-five
11 silly addNameRange { name: 'johnny-five', range: '*', hasData: false }
12 silly mapToRegistry name johnny-five
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/johnny-five
16 verbose addNameRange registry:https://registry.npmjs.org/johnny-five not in flight; fetching
17 verbose request uri https://registry.npmjs.org/johnny-five
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:26:45 PM
20 verbose request id 36ceda6e25163435
21 http request GET https://registry.npmjs.org/johnny-five
22 info retry will retry, error on last attempt: Error: certificate is not yet valid
23 info attempt registry request try #2 at 4:26:56 PM
24 http request GET https://registry.npmjs.org/johnny-five
25 info retry will retry, error on last attempt: Error: certificate is not yet valid
26 info attempt registry request try #3 at 4:27:57 PM
27 http request GET https://registry.npmjs.org/johnny-five
28 verbose stack Error: certificate is not yet valid
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:567:8)
29 verbose cwd /home/pi/Documents/NodeSamples/LDR_JohnnyFive_Rasp
30 error Linux 4.1.13-v7+
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "johnny-five"
32 error node v4.0.0
33 error npm  v2.14.2
34 error code CERT_NOT_YET_VALID
35 error certificate is not yet valid
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2016-04-21 14:16
@mehamindran Is your system time correctly set?

**Comment by mehamindran** [comment] 2016-05-10 05:01
Yes, I check my system time. It was correct.

**Comment by KenanY** [comment] 2016-05-17 14:32
@mehamindran Hi, I'm just following up after a week of no activity here. Sorry I haven't provided any solutions yet. Every time this issue shows up on this tracker it has always been caused by incorrect system time. Are you still seeing this issue?

**Comment by KenanY** [comment] 2016-06-29 02:05
Closing as abandoned.

**Closed by KenanY** 2016-06-29 02:05 UTC
Labels: support
