### ISSUE TITLE
Error installing sailsjs  --  fetch failed with status code 502

### ISSUE THREAD

**Issue by AnasFullStack** [npm/npm#13286] opened 2016-07-06 07:49 UTC
#### I'm opening this issue because:

  - npm is returning this error :

> npm ERR! fetch failed with status code 502

#### What's going wrong?
Can not install sailsjs

#### How can the CLI team reproduce the problem?
`sudo npm -g install sails`

### supporting information:

 - `npm -v` prints: v3.9.5
 - `node -v` prints: v6.2.2
 - Windows, OS X, or Linux?: Linux

 - Container:
   - I Deploy using travis-cli

### Logs:

```
sudo npm -g install sails

npm ERR! fetch failed https://registry.npmjs.org/machinepack-urls/-/machinepack-urls-3.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/machinepack-urls/-/machinepack-urls-3.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/machinepack-urls/-/machinepack-urls-3.1.1.tgz
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "sails"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! fetch failed with status code 502
```

**Comment by dylclem** [comment] 2016-07-06 08:00
I'm getting this right now as well but with
`npm install lite-server --save-dev`
Running node v6.2.2 & npm v3.10.3
OS X

**Comment by hobofan** [comment] 2016-07-06 08:10
Duplicate of #13284

**Comment by dylclem** [comment] 2016-07-06 08:15
@hobofan my bad, good call

**Comment by miherlosev** [comment] 2016-07-06 08:41
Same for another package
```javascript
Updating nvm to v 0.31.0

$ nvm install stable

Downloading https://nodejs.org/dist/v6.2.2/node-v6.2.2-linux-x64.tar.xz...

######################################################################## 100.0%

Now using node v6.2.2 (npm v3.9.5)

$ node --version

v6.2.2

$ npm --version

3.9.5

$ nvm --version

0.31.0

852.02s $ npm install 

npm ERR! fetch failed https://registry.npmjs.org/multiline/-/multiline-1.0.2.tgz

npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

npm ERR! fetch failed https://registry.npmjs.org/multiline/-/multiline-1.0.2.tgz

npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

npm ERR! fetch failed https://registry.npmjs.org/multiline/-/multiline-1.0.2.tgz

npm ERR! Linux 3.13.0-40-generic

npm ERR! argv "/home/travis/.nvm/versions/node/v6.2.2/bin/node" "/home/travis/.nvm/versions/node/v6.2.2/bin/npm" "install"

npm ERR! node v6.2.2

npm ERR! npm  v3.9.5
```

**Comment by shane-tomlinson** [comment] 2016-07-06 08:56
I see a similar 502 when running tests on circle and travis:

https://circleci.com/gh/mozilla/fxa-content-server/3677
https://travis-ci.org/mozilla/fxa-content-server/jobs/142693938

```
npm WARN optional dep failed, continuing fsevents@1.0.12
npm ERR! fetch failed https://registry.npmjs.org/compare-func/-/compare-func-1.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/normalize-path/-/normalize-path-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/lodash._createpadding/-/lodash._createpadding-3.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/lolex/-/lolex-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/compare-func/-/compare-func-1.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/normalize-path/-/normalize-path-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/lodash._createpadding/-/lodash._createpadding-3.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/lolex/-/lolex-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/compare-func/-/compare-func-1.3.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/normalize-path/-/normalize-path-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash._createpadding/-/lodash._createpadding-3.6.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lolex/-/lolex-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.4.7/bin/node" "/home/travis/.nvm/versions/node/v4.4.7/bin/npm" "i" "mozilla/fxa-auth-server"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.9
npm ERR! fetch failed with status code 502
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
> husky@0.11.4 uninstall /home/travis/build/mozilla/fxa-content-server/deps/node_modules/fxa-auth-server/node_modules/husky
> node ./bin/uninstall.js
module.js:327
    throw err;
    ^
Error: Cannot find module 'normalize-path'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/deps/node_modules/fxa-auth-server/node_modules/husky/src/index.js:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm WARN continuing anyway husky@0.11.4 uninstall: `node ./bin/uninstall.js`
npm WARN continuing anyway Exit status 1

```

**Comment by davecozens** [comment] 2016-07-06 09:04
Looks like NPM are having CDN issues.

See https://github.com/npm/npm/issues/13284

**Comment by raisiqueira** [comment] 2016-07-06 14:03
I am having the same problem since this morning. NPM v3.9.5

**Comment by bioinfowistar** [comment] 2016-07-06 14:29
I have the same issue when trying to install cordova:

C:\Program Files\nodejs>npm install -g cordova
npm ERR! fetch failed https://registry.npmjs.org/cordova-app-hello-world/-/cordo
va-app-hello-world-3.10.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 502
npm ERR! fetch failed https://registry.npmjs.org/cordova-app-hello-world/-/cordo
va-app-hello-world-3.10.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 502
npm ERR! fetch failed https://registry.npmjs.org/cordova-app-hello-world/-/cordo
va-app-hello-world-3.10.0.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! fetch failed with status code 502
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by KenanY** [comment] 2016-07-06 15:08
I'm gonna close this as a duplicate of https://github.com/npm/npm/issues/13284.

**Closed by KenanY** 2016-07-06 15:08 UTC
Labels: registry, support
