### ISSUE TITLE
Windows 10  throws the following error any suggestion

### ISSUE THREAD

**Issue by pradeepkumart** [npm/npm#10581] opened 2015-11-27 12:25 UTC
```
npm install -g protractor
npm ERR! Error: DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR!     at SecurePair.<anonymous> (tls.js:1380:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:979:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:471:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:340:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:368:25)
npm ERR!     at doWrite (_stream_writable.js:225:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:215:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
npm ERR!     at write (_stream_readable.js:601:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! cwd C:\Users\kumartp.AUTH
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\kumartp.AUTH\npm-debug.log
npm ERR! not ok code 0
```

**Comment by onstottj** [comment] 2016-02-05 19:22
Maybe this is a duplicate of: https://github.com/npm/npm/issues/8048?

**Closed** 2017-06-16 23:47 UTC
Labels: bot-closed, proxy, support, windows
