### ISSUE TITLE
npm install --prefix / install local top-level dependencies only

### ISSUE THREAD

**Issue by arekkas** [npm/npm#4647] opened 2014-02-11 11:38 UTC
I'm using vagrant on a windows host and since npm sometimes creates a very deep directory tree (which fails on windows hosts), I thought it was a good idea, to install the local node_modules on the VM directly rather than in the shared folder and symlink them later. So I tried:

`npm --prefix ~/node_modules install ./`

That worked. However, it did only install the production dependencies, rather than the devDependencies. In contrast:

`npm install`

Installs the top-level devDependencies as well. So I thought, that adding `--dev` would solve my problem:

`npm --prefix ~/node_modules install ./ --dev`

But that installed **all** devDependencies rather than the top-level ones. That causes npm to work for over 30 minutes and some modules even fail the install due to `enoent 34` error (I have no idea why that happens).

Am I missing something or is prefix not supposed to work that way or is this indeed an issue?

**Comment by smikes** [comment] 2015-02-02 17:59
Is this still a problem for you?

The underlying problem of long paths and Windows has still not been fixed, so if this is still preventing you from getting your work done, please let us know and we will categorize this as a `bug` or `feature-request`.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since Feb 2014. Can you try updating your npm installation?  This will at least fix the `ENOENT` errors, which were caused by race conditions in older versions of `npm`.

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-02-20 21:03
Closing as abandoned. As a side node, the upcoming release of `npm@3` will bring with it a lot more deduplication by default, and therefore a much flatter dependency tree (although still not a single-level one, in many cases).

**Closed by othiym23** 2015-02-20 21:03 UTC
Labels: support
