### ISSUE TITLE
error while installing ionic beta-2

### ISSUE THREAD

**Issue by shadrackkip** [npm/npm#12172] opened 2016-04-02 10:49 UTC
i encountered this problem while i was downloading ionic -2 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic@2.0.0-beta.22' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic@2.0.0-beta.22
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/ionic
13 verbose request uri https://registry.npmjs.org/ionic
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:30:00 PM
16 verbose request id e2c5bac2ace92bf0
17 verbose etag "DLOOJDXPX5X5OC16CO6TJ2B0L"
18 http request GET https://registry.npmjs.org/ionic
19 http 304 https://registry.npmjs.org/ionic
20 verbose headers { date: 'Sat, 02 Apr 2016 10:30:06 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"DLOOJDXPX5X5OC16CO6TJ2B0L"',
20 verbose headers   age: '23',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1241-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1459593006.233786,VS0,VE1',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Sat, 02 Apr 2016 10:30:06 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"DLOOJDXPX5X5OC16CO6TJ2B0L"',
21 silly get     age: '23',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1241-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1459593006.233786,VS0,VE1',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/ionic from cache
23 verbose get saving ionic to C:\Users\SOI\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule ionic@2.0.0-beta.22 checking installable status
37 silly cache add args [ 'ionic@2.0.0-beta.22', null ]
38 verbose cache add spec ionic@2.0.0-beta.22
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'ionic@2.0.0-beta.22',
39 silly cache add   scope: null,
39 silly cache add   name: 'ionic',
39 silly cache add   rawSpec: '2.0.0-beta.22',
39 silly cache add   spec: '2.0.0-beta.22',
39 silly cache add   type: 'version' }
40 silly addNamed ionic@2.0.0-beta.22
41 verbose addNamed "2.0.0-beta.22" is a plain semver version for ionic
42 silly mapToRegistry name ionic
43 silly mapToRegistry using default registry
44 silly mapToRegistry registry https://registry.npmjs.org/
45 silly mapToRegistry uri https://registry.npmjs.org/ionic
46 verbose addNameVersion registry:https://registry.npmjs.org/ionic not in flight; fetching
47 verbose request uri https://registry.npmjs.org/ionic
48 verbose request no auth needed
49 info attempt registry request try #1 at 1:30:35 PM
50 verbose etag "DLOOJDXPX5X5OC16CO6TJ2B0L"
51 http request GET https://registry.npmjs.org/ionic
52 http 304 https://registry.npmjs.org/ionic
53 verbose headers { date: 'Sat, 02 Apr 2016 10:30:40 GMT',
53 verbose headers   via: '1.1 varnish',
53 verbose headers   'cache-control': 'max-age=300',
53 verbose headers   etag: '"DLOOJDXPX5X5OC16CO6TJ2B0L"',
53 verbose headers   age: '153',
53 verbose headers   connection: 'keep-alive',
53 verbose headers   'x-served-by': 'cache-lcy1132-LCY',
53 verbose headers   'x-cache': 'HIT',
53 verbose headers   'x-cache-hits': '1',
53 verbose headers   'x-timer': 'S1459593040.263928,VS0,VE1',
53 verbose headers   vary: 'Accept' }
54 silly get cb [ 304,
54 silly get   { date: 'Sat, 02 Apr 2016 10:30:40 GMT',
54 silly get     via: '1.1 varnish',
54 silly get     'cache-control': 'max-age=300',
54 silly get     etag: '"DLOOJDXPX5X5OC16CO6TJ2B0L"',
54 silly get     age: '153',
54 silly get     connection: 'keep-alive',
54 silly get     'x-served-by': 'cache-lcy1132-LCY',
54 silly get     'x-cache': 'HIT',
54 silly get     'x-cache-hits': '1',
54 silly get     'x-timer': 'S1459593040.263928,VS0,VE1',
54 silly get     vary: 'Accept' } ]
55 verbose etag https://registry.npmjs.org/ionic from cache
56 verbose get saving ionic to C:\Users\SOI\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
57 silly mapToRegistry name ionic
58 silly mapToRegistry using default registry
59 silly mapToRegistry registry https://registry.npmjs.org/
60 silly mapToRegistry uri https://registry.npmjs.org/ionic
61 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.22.tgz not in flight; adding
62 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.22.tgz',
62 verbose addRemoteTarball   'bac7213097354ec8272bf176840d241c0546c2f3' ]
63 info retry fetch attempt 1 at 1:30:37 PM
64 info attempt registry request try #1 at 1:30:37 PM
65 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.22.tgz
66 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.22.tgz
67 silly fetchAndShaCheck shasum bac7213097354ec8272bf176840d241c0546c2f3
68 silly rollbackFailedOptional Starting
69 silly rollbackFailedOptional Finishing
70 silly runTopLevelLifecycles Starting
71 silly runTopLevelLifecycles Finishing
72 silly install printInstalled
73 verbose stack Error: shasum check failed for C:\Users\SOI\AppData\Local\Temp\npm-8856-9c42ce53\registry.npmjs.org\ionic\-\ionic-2.0.0-beta.22.tgz
73 verbose stack Expected: bac7213097354ec8272bf176840d241c0546c2f3
73 verbose stack Actual:   8ef55644dcacd843442df8cae619a9282ce64fce
73 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.22.tgz
73 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
73 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
73 verbose stack     at emitNone (events.js:85:20)
73 verbose stack     at ReadStream.emit (events.js:179:7)
73 verbose stack     at endReadableNT (_stream_readable.js:906:12)
73 verbose stack     at nextTickCallbackWith2Args (node.js:474:9)
73 verbose stack     at process._tickCallback (node.js:388:17)
74 verbose cwd E:\
75 error Windows_NT 10.0.10586
76 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic@2.0.0-beta.22"
77 error node v5.5.0
78 error npm  v3.3.12
79 error shasum check failed for C:\Users\SOI\AppData\Local\Temp\npm-8856-9c42ce53\registry.npmjs.org\ionic\-\ionic-2.0.0-beta.22.tgz
79 error Expected: bac7213097354ec8272bf176840d241c0546c2f3
79 error Actual:   8ef55644dcacd843442df8cae619a9282ce64fce
79 error From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0-beta.22.tgz
80 error If you need help, you may report this error at:
80 error     <https://github.com/npm/npm/issues>
81 verbose exit [ 1, true ]
```

**Comment by zkat** [comment] 2016-12-09 00:44
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:44 UTC
Labels: network, support
