### ISSUE TITLE
--loglevel silent

### ISSUE THREAD

**Issue by Swaagie** [npm/npm#9355] opened 2015-08-20 13:18 UTC
Can it be silent for once? It continues to output build information and loaders in both v2 and v3.

**Comment by KenanY** [comment] 2015-08-21 02:27
@Swaagie 

> build information

You mean `node-gyp` output?

> loaders

What are these?

**Comment by Swaagie** [comment] 2015-08-21 06:07
npm itself
Op 21 aug. 2015 4:27 AM schreef "Kenan Yildirim" <notifications@github.com>:

**Comment by KenanY** [comment] 2015-08-21 13:50
@Swaagie I was hoping to get some clarification as to what "build information and loaders" specifically are, but I guess I need to be more explicit. Could you upload the output that `npm` is producing that you are _not_ expecting to see with `--loglevel silent` as a [gist](https://gist.github.com/)?

**Comment by Swaagie** [comment] 2015-08-24 20:00
I expect zero output to `stdout`, I've just noticed this https://github.com/npm/npm/issues/2040 was opened a few years ago. But since I'm using npm programmatically with `loglevel` in the config, piping to something like `dev/null` will not work.

**Comment by Swaagie** [comment] 2015-08-24 20:30
so since we are using child processes to run other code anyways I solved it with ```spawn(process.execPath, [ path.join(__dirname, 'workers', type + '.js') ], {
      stdio: ['ignore', 'ignore', 'ignore', 'ipc']
    });``` but I can see this still being a problem for anyone running `npm.install` programmatically from the main thread.

**Comment by othiym23** [comment] 2015-08-24 22:03
This is a duplicate of #4320, and you can see https://github.com/npm/npm/pull/4320#issuecomment-46325959 for a workaround. npm's internal APIs are unsupported, and as such the team makes no guarantees as to whether they will or won't do anything useful. Give that workaround a shot, and if that doesn't work for you, try running npm in a child process and snarfing the output. That's what the team suggests developers do.

**Closed by othiym23** 2015-08-24 22:03 UTC
Labels: feature-request
