### ISSUE TITLE
Getting EMISSINGARG when running npm outdated

### ISSUE THREAD

**Issue by gscott** [npm/npm#8678] opened 2015-06-26 02:17 UTC
npm@3.0.0

1.  `npm ls` looks normal
2.  `npm dedupe --save` works without error, flat `/node_modules`, app works fine
3.  `npm ls` post dedupe returns nothing back -- and no error.
4.  `npm outdated` returns an EMISSINGARG

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'outdated' ]
2 info using npm@3.0.0
3 info using node@v2.2.1
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/logical-tree.js:11:3)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:77:16
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:61:20
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:179:9
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:163:22)
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:149:20
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:118:22)
5 verbose cwd /Users/gs/dev/caa-template-webapp5
6 error Darwin 14.3.0
7 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "outdated"
8 error node v2.2.1
9 error npm  v3.0.0
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/logical-tree.js:11:3)
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:77:16
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:61:20
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:179:9
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:163:22)
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:149:20
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:118:22)
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
````

**Comment by iarna** [comment] 2015-07-01 01:23
I'm closing this as a duplicate of #8680 – while the command being run is different, the root cause is the same.

**Closed by iarna** 2015-07-01 01:23 UTC
Labels: bug

**Comment by ErikAbele** [comment] 2015-10-23 22:41
See also #9659 and #9720.

**Comment by JonDum** [comment] 2015-11-10 22:50
Getting this same error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/Users/JD/Dropbox/Applications/bin/npm', 'outdated' ]
2 info using npm@3.3.12
3 info using node@v0.12.7
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/Users/JD/Dropbox/Applications/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:166:22)
4 verbose stack     at f (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
5 verbose cwd /Users/JD/Dropbox/Creative/Projects/J2/alarms-dashboard
6 error Darwin 13.4.0
7 error argv "node" "/Users/JD/Dropbox/Applications/bin/npm" "outdated"
8 error node v0.12.7
9 error npm  v3.3.12
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/Users/JD/Dropbox/Applications/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:166:22)
11 error typeerror     at f (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/Users/JD/Dropbox/Applications/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
