### ISSUE TITLE
Ionic Cordova installation error

### ISSUE THREAD

**Issue by Logan219** [npm/npm#16158] opened 2017-03-26 16:43 UTC
#### I'm opening this issue because:

  npm install -g ionic cordova fails

#### What's going wrong?
shasu check failed for ionic-2.2.1tgz

### supporting information:

 - `npm -v` prints: v3.10.10
 - `node -v` prints: v6.10.1
 - `npm config get registry` prints: 
 - Windows, OS X/macOS, or Linux?: Windows

Issue:

npm ERR! Expected: 2b9d90b3ae109138084473282c18ea162a5f8248
npm ERR! Actual:   e1570d3e285465c0c867c37878cc333c5964dddd
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.2.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by legodude17** [comment] 2017-03-27 15:52
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-16 21:56 UTC
Labels: bot-closed, support
