### ISSUE TITLE
error on installing react

### ISSUE THREAD

**Issue by AravindRavichandran** [npm/npm#15742] opened 2017-02-11 19:00 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'react',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react
8 silly fetchNamedPackageData react
9 silly mapToRegistry name react
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'react',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'react',
12 silly mapToRegistry   name: 'react',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/react
14 verbose request uri https://registry.npmjs.org/react
15 verbose request no auth needed
16 info attempt registry request try #1 at 00:21:10
17 verbose request id d7dc7328ad0f7bcc
18 verbose etag W/"589c9684-22be6"
19 verbose lastModified Thu, 09 Feb 2017 16:19:16 GMT
20 http request GET https://registry.npmjs.org/react
21 http 304 https://registry.npmjs.org/react
22 verbose headers { date: 'Sat, 11 Feb 2017 18:51:11 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"589c9684-22be6"',
22 verbose headers   age: '58',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-sin6921-SIN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '2',
22 verbose headers   'x-timer': 'S1486839071.628156,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Sat, 11 Feb 2017 18:51:11 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"589c9684-22be6"',
23 silly get     age: '58',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin6921-SIN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '2',
23 silly get     'x-timer': 'S1486839071.628156,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/react from cache
25 verbose get saving react to C:\Users\Aravind\AppData\Roaming\npm-cache\registry.npmjs.org\react\.cache.json
26 verbose correctMkdir C:\Users\Aravind\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install react as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\Users\Aravind\Documents\react
45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react" "--save"
47 error node v6.9.5
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install react as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2017-02-11 23:31
@AravindRavichandran 

```
50 error Refusing to install react as a dependency of itself
```

Make sure the `"name"` property in your `package.json` is not the same as what you're trying to install. Closing since this `npm` working as intended.

**Closed by KenanY** 2017-02-11 23:31 UTC
