### ISSUE TITLE
`npm view` does not handle registry correctly

### ISSUE THREAD

**Issue by mearns** [npm/npm#11634] opened 2016-02-22 20:26 UTC
We are using a private module registry (JFrog's Artifactory) to host our internal modules. When I try to use the `npm view` command to view information about a module that _does not_ exist, the command blows up with exit code 1 and seems to be indicating that the URL for the registry is being used as the module name. This applies whether the registry is applied in my ~/.npmrc file, or on the command line with the `--registry` option. It works fine when the module does exist in the registry.

Example of failure:

```bash
$ npm config get registry
http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/
$ npm view this-module-does-not-exist
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "view" "this-module-does-not-exist"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 Not Found: artifactory
npm ERR! 404
npm ERR! 404  'artifactory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bmearns\npm-debug.log
```
Below are the contents of the npm-debug.log:

```
0 info it worked if it ends with ok                                                                                                                                                
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',                                                                                                                             
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',                                                                                                   
1 verbose cli   'view',                                                                                                                                                            
1 verbose cli   'this-module-does-not-exist' ]                                                                                                                                     
2 info using npm@3.6.0                                                                                                                                                             
3 info using node@v5.6.0                                                                                                                                                           
4 verbose config Skipping project config: C:\Users\bmearns/.npmrc. (matches userconfig)                                                                                            
5 silly mapToRegistry name this-module-does-not-exist                                                                                                                              
6 silly mapToRegistry using default registry                                                                                                                                       
7 silly mapToRegistry registry http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/                                                                           
8 silly mapToRegistry uri http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/this-module-does-not-exist                                                      
9 verbose request uri http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/this-module-does-not-exist                                                          
10 verbose request always-auth set; sending authorization                                                                                                                          
11 info attempt registry request try #1 at 3:18:55 PM                                                                                                                              
12 verbose request id 8b1bef2427bcdac3                                                                                                                                             
13 http request GET http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/this-module-does-not-exist                                                            
14 http 404 http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/this-module-does-not-exist                                                                    
15 verbose headers { server: 'Artifactory/3.5.3',                                                                                                                                  
15 verbose headers   'x-artifactory-id': 'REMOVED-FOR-SECURITY?',                                                                                           
15 verbose headers   'content-type': 'application/json',                                                                                                                           
15 verbose headers   'transfer-encoding': 'chunked',                                                                                                                               
15 verbose headers   date: 'Mon, 22 Feb 2016 20:18:55 GMT' }                                                                                                                       
16 silly get cb [ 404,                                                                                                                                                             
16 silly get   { server: 'Artifactory/3.5.3',                                                                                                                                      
16 silly get     'x-artifactory-id': 'REMOVED-FOR-SECURITY?',                                                                                               
16 silly get     'content-type': 'application/json',                                                                                                                               
16 silly get     'transfer-encoding': 'chunked',                                                                                                                                   
16 silly get     date: 'Mon, 22 Feb 2016 20:18:55 GMT' } ]                                                                                                                         
17 verbose stack Error: 404 Not Found: artifactory                                                                                                                                 
17 verbose stack     at makeError (C:\Users\bmearns\AppData\Roaming\nvm\v5.6.0\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)                            
17 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\bmearns\AppData\Roaming\nvm\v5.6.0\node_modules\npm\node_modules\npm-registry-client\lib\request.js:250:14)    
17 verbose stack     at Request._callback (C:\Users\bmearns\AppData\Roaming\nvm\v5.6.0\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)                    
17 verbose stack     at Request.self.callback (C:\Users\bmearns\AppData\Roaming\nvm\v5.6.0\node_modules\npm\node_modules\request\request.js:198:22)                                
17 verbose stack     at emitTwo (events.js:100:13)                                                                                                                                 
17 verbose stack     at Request.emit (events.js:185:7)                                                                                                                             
17 verbose stack     at Request.<anonymous> (C:\Users\bmearns\AppData\Roaming\nvm\v5.6.0\node_modules\npm\node_modules\request\request.js:1035:10)                                 
17 verbose stack     at emitOne (events.js:95:20)                                                                                                                                  
17 verbose stack     at Request.emit (events.js:182:7)                                                                                                                             
17 verbose stack     at IncomingMessage.<anonymous> (C:\Users\bmearns\AppData\Roaming\nvm\v5.6.0\node_modules\npm\node_modules\request\request.js:962:12)                          
18 verbose statusCode 404                                                                                                                                                          
19 verbose pkgid artifactory                                                                                                                                                       
20 verbose cwd C:\Users\bmearns                                                                                                                                                    
21 error Windows_NT 6.1.7601                                                                                                                                                       
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "view" "this-module-does-not-exist"                            
23 error node v5.6.0                                                                                                                                                               
24 error npm  v3.6.0                                                                                                                                                               
25 error code E404                                                                                                                                                                 
26 error 404 Not Found: artifactory                                                                                                                                                
27 error 404                                                                                                                                                                       
28 error 404 'artifactory' is not in the npm registry.                                                                                                                             
29 error 404 You should bug the author to publish it (or use the name yourself!)                                                                                                   
30 error 404 Note that you can also install from a                                                                                                                                 
31 error 404 tarball, folder, http url, or git url.                                                                                                                                
32 verbose exit [ 1, true ]                                                                                                                                                        
```

Reviewing the log, maybe it's just the error reporting that's wrong? It looks like it might have made the correct request, but instead of reporting the that 'this-module-does-not-exist' is not in npm, it reports that 'artifactory' is not in npm.

This is being done under cygwin on Windows 7, with node version 5.6.0 and npm version 3.6.0, as shown in the log.

**Comment by othiym23** [comment] 2016-02-22 20:41
The error message you're seeing is coming from the web service running Artifactory, not npm (hence the 404). If you look at the log output from `mapToRegistry`, you can see what URL is actually being requested, as well as the base registry the CLI is using to generate the URL. Check with your Artifactory admins to make sure that's the correct registry URL.

As this is a registry configuration issue and not a bug in npm, I'm going to close this issue. Thanks for your time, and good luck sorting this out!

**Closed by othiym23** 2016-02-22 20:41 UTC

**Comment by mearns** [comment] 2016-02-23 16:26
Sort of. My registry is responding differently than, for instance, the default registry at npmjs.org, but there's nothing in the response from my registry that says the package is named "artifactory". npm seems to be conflating part of the URL with the package name in the error message.

To be clear, my registry works fine for packages that do exist, so the URL is correct.

When I GET the URL shown in the output from `mapToRegistry` (http://artifactory.mydomain.example.com/artifactory/api/npm/npm-virtual/this-module-does-not-exist), the server responds with a 404, a content-type of `application/json` (as shown in the log above) and the following content:

```json
{"error": "not_found", "reason": "document not found"}
```
But the error message says:

> npm ERR! 404  'artifactory' is not in the npm registry.

Which doesn't really make sense. It should say something like:

> npm ERR! 404  'this-module-does-not-exist' is not in the npm registry.

This is what it says when I try to use the default registry (npmjs.org) to install the same package.

When I GET the URL for this missing package from the default regsitry (https://registry.npmjs.org/this-module-does-not-exist), and I also get a 404 and a content-type of `application/json`. The only different (other than some other response headers) is the response body:

```json
{}
```

So my registry definitely is responded differently, but it still seems that npm is incorrectly generating the error message.

**Comment by rmg** [comment] 2016-08-30 03:54
Isn't this is a manifestation of npm/npm-registry-client#80?
