### ISSUE TITLE
Add support for arrays of commands as an npm script

### ISSUE THREAD

**Issue by ryancole** [npm/npm#13582] opened 2016-08-04 22:27 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

Allow an npm script to specify an array of commands.

#### What problem is the feature intended to solve?

Can help remove clutter of chaining a bunch of commands via command-line `&&`, etc. Can also make use of npm's ability to kill the script chain on a fail exit code.

#### Is the absence of this feature blocking you or your team? If so, how?

No.

#### Is this feature similar to an existing feature in another tool?

Not sure. It'd be the equivalent of a single npm script that chains commands using `&&`, but would allow those scripts to be split out into cleaner looking strings within an array.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure. Perhaps a pointer where to start and I can take shot.

**Comment by KenanY** [comment] 2016-08-04 23:49
@ryancole Is this a duplicate of https://github.com/npm/npm/issues/6943?

**Comment by ryancole** [comment] 2016-08-04 23:52
Hmm, yea it does look like a duplicate. Although I don't like the idea of a literal string join. I want thinking more along the lines of actual different commands so that in one "script" (npm run build) you could benefit from the exit code checking and break.

**Closed** 2016-08-04 23:52 UTC
