### ISSUE TITLE
npm install - updates "integrity" in package-lock.json

### ISSUE THREAD

**Issue by the-noob** [npm/npm#17749] opened 2017-07-12 22:56 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm install` changes the hashing in `package-lock.json`

```
-      "integrity": "sha512-e+lJAJeNWuPCNyxZKOBdaJGyLGHugXVQtrAwtuAe2vhxTYxFTKE73p8JuTmdH0qdQZtDvI4dhJwjZc5zsfIsYw==",
+      "integrity": "sha1-hDGQ/WtzV6C54clW7d3V7IRitU0=",
```

#### How can the CLI team reproduce the problem?

I'm testing a few dashboard libraries in different branches of the same repo.  
Changing the branch to a new `package[-lock].json` and running `npm install` without deleting the `node_modules` folder ended up in a lot of changes to the `package-lock.json`
I would've expected this from `npm update` but not a simple `install` ?

### supporting information:

 - `npm -v` prints: **5.2.0** (also in 5.3)
 - `node -v` prints: **v7.10.0**
 - `npm config get registry` prints: **https://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?: **Linux**
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jessevdp** [comment] 2017-07-17 11:42
I had the exact same thing happen to me today. Indeed also when running `npm install` in a repository where the `node_modules` folder was still installed.

Alongside the integrity changes from `sha512` to `sha1` the git diff also showed added `requires` json objects. However I think those are unrelated.

#### supporting information:

 - `npm -v` prints: **5.3.0**
 - `node -v` prints: **v8.1.4**
 - `npm config get registry` prints: **https://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?: **macOS (v10.12.5)**
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by wd** [comment] 2017-07-28 04:53
I meet the same problem. 
```
$ npm -v
5.3.0
$ node -v
v8.2.1
```

**Comment by dzonatan** [comment] 2017-07-28 05:52
Same here. Seems like deleting the `node_modules` helps for some time. 

```
$ npm -v
5.3.0
$ node -v
v8.2.0
```

**Comment by sarkiroka** [comment] 2017-07-28 10:17
I have same problem too
npm: 5.3.0
node v6.7.0

**Comment by RaniSputnik** [comment] 2017-08-01 09:54
Same problem here;

* `npm -v` prints: **5.3.0**
* `node -v` prints: **v8.1.2**
* `npm config get registry` prints: **https://registry.npmjs.org/**
* Windows, OS X/macOS, or Linux?: **OS X**

**Comment by joakimcarlsten** [comment] 2017-08-02 13:05
Same problem - resolved by removing `node_modules` though

**Comment by teledemic** [comment] 2017-08-02 20:59
My mac machine always changes the integrity to sha512, while my windows machine always changes it to sha1 for the same repo

**Comment by sarkiroka** [comment] 2017-08-02 21:16
I have a linux machine and it always changes the integrity to sha512 too.

**Comment by ruchernchong** [comment] 2017-08-03 08:45
I would like to report a similar issue with macOS and Linux. The integrity is being switched from sha1 to sha512.

**Comment by Opalo** [comment] 2017-08-03 12:11
Same here for macos and linux workstations:
**macos**
```
> sw_vers -productVersion 
10.12.4
> node -v
v4.2.6
> npm -v
5.3.0
```
**linux**
```
> node -v
v4.2.6
> npm -v
5.3.0
> cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by toobulkeh** [comment] 2017-08-03 14:38
Same problem on Windows/Mac split here:

```
OSX
master % npm -v
5.2.0
master % node -v
v6.0.0
```


According to [the docs](https://docs.npmjs.com/files/package-lock.json#integrity), this comes from a few locations:
* For bundled dependencies this is not included, regardless of source.
* For registry sources, this is the integrity that the registry provided, or if one wasn't provided the SHA1 in shasum.
* For git sources this is the specific commit hash we cloned from.
* For remote tarball sources this is an integrity based on a SHA512 of the file.
* For local tarball sources: This is an integrity field based on the SHA512 of the file.

In my case, these are all `registry sources` without provided integrity, so `shasum` is the root difference between these two systems. I don't have that package anywhere on my system, so I can only assume it's a compiled difference.

**Comment by elmariachi111** [comment] 2017-08-14 12:14
same here.

Same problem here;

npm -v prints: 5.3.0
node -v prints: v8.2.1
npm config get registry prints: https://registry.npmjs.org/
Windows, OS X/macOS, or Linux?: OS X

**Comment by thom8** [comment] 2017-08-16 00:41
npm -v: `5.3.0`
node -v: `v8.4.0`

Ran into the same issue, fixed it by clearing the cache `npm cache clean --force`

manually deleting `node_modules` and then running `npm install` again.

From what I can see the issue was due to the initial install being done of an older version of npm.

**Comment by AJDurant** [comment] 2017-08-16 14:39
I have the same issue with Windows changing to sha1 and Linux changing to sha512
Windows 10:
npm -v `5.3.0`
node -v `v6.11.1`
Ubuntu 16.4.2:
npm -v `5.3.0`
node -v `v6.11.2`

npm complains that the integrity doesn't match up every time an install happens on switching platform.

**Comment by ruchernchong** [comment] 2017-08-16 14:46
Hi @zkat, any updates on this issue?

**Comment by Oliboy50** [comment] 2017-08-24 12:38
IMHO this issue is quite important because it's causing trouble even for "not javascript developers" (nodejs is everywhere in web development now, even in PHP stacks, etc.)...

so it should be a big concern for NPM to fix this issue as soon as possible, before everyone goes to `yarn` (e.g. the link above)

**Comment by ruchernchong** [comment] 2017-08-24 12:41
@Oliboy50 

> befor eeveryone goes to `yarn`

Well, it won't be everyone but there are people who will look to switch. In fact, as we speak, I am temporary using `yarn` until these issues with `npm` are fixed. I am not demanding, but I am holding on the faith that `npm` will solve this one day.

Another reason being why I do not want to stay on `yarn` for too long because of the affiliation with Facebook.

**Comment by retorquere** [comment] 2017-09-02 09:20
This negates what seems to be the main purpose of the lockfile -- I have taken to adding it to .gitignore because it adds spurious chatter to my git log.

**Comment by septemptus** [comment] 2017-09-06 10:02
Is this still an issue as of 5.4.0? One of my coworkers reported that he did not experience this issue anymore, but I cannot confirm because it didn't happen on my environment at all.

**Comment by zkat** [comment] 2017-09-06 10:33
just dropping a note that we're aware of this but I haven't really managed to track down why this sort of diff happens. My recommendation for those running into this is that you try doing an `rm -rf node_modules` _without the diff to `sha1-`_, and run a full npm install with the latest npm and see if it fixes it. We've had a number of miscellaneous fixes and random issues seem to just get fixed by other stuff. Once I have a concrete idea of how this hash dropping is happening, I hope to fix it quickly, but idk what's up with it right now -- a number of people have reported it to me directly and tried to get a good repro going.

**Comment by retorquere** [comment] 2017-09-06 10:46
My versions:

* Ubuntu: 17.04
* node: 8.2.1
* npm: 5.4.0

After:

1. npm cache clean --force
2. rm -rf node_modules
3. rm package-lock.json
4. npm install

I'm still seeing a mix of sha1 and sha512

**Comment by kevinburke** [comment] 2017-09-06 21:34
With 5.3.0, I could reproduce changes 100% of the time by running:

- rm -rf node_modules
- npm install

This would modify 5-7 of the `integrity` keys in packages in a 5,000 line package-lock.json - some changing from sha1 to sha512, some changing in the other direction.

After upgrading from 5.3.0 to 5.4.0, there's still a mix of sha1 and sha512 in the file, but I'm not seeing sha1 randomly change to sha512 as the result of running `npm install`.

**Comment by retorquere** [comment] 2017-09-06 22:20
@kevinburke can confirm -- no changes between my mac and linux system.

**Comment by billmei** [comment] 2017-09-21 23:41
Relates to https://github.com/npm/npm/issues/16938

**Comment by drewlustro** [comment] 2017-10-17 18:53
**I'm also having this issue.**

MacOS 10.11 produces a `sha1` integrity, whereas Ubuntu `17.10` produces a `sha512` integrity hash, thus busting the `package-lock.json` file and creating a ton of noise.

Both machines have:

**npm** version = `5.4.2`
**node** version = `7.10.1`

**Comment by elygre** [comment] 2017-10-25 21:48
Same issue.

This makes the idea of checking in to source control a bit messy, since the package-lock file keeps changing.

**Comment by mariotacke** [comment] 2017-10-30 22:21
Running into the same thing right now on Windows. Some of my devs run [cmder](http://cmder.net/), a bash/linux shell for Windows and some run regular cmd. It produces different hashes on `npm install`.

**Comment by jez9999** [comment] 2017-10-31 10:54
I have the same issue.  Looks like this REALLY needs to be fixed.

**Comment by ruchernchong** [comment] 2017-10-31 12:58
Lets ping @zkat to notify that this is still a problem since npm v5.

**Comment by ruchernchong** [comment] 2017-11-08 08:58
So there is still no update on this which existed 4 months ago?

**Comment by squidfunk** [comment] 2017-11-08 09:01
I'm also having issues running `npm install` within `make` as a dependency, because the `package.json` and `package-lock.json` are always touched, resulting in `npm install` on every command.

**Comment by paulirwin** [comment] 2017-11-10 14:09
This is driving me crazy. Can't this just always use SHA-512? SHA-1 should be deprecated anyways.

**Comment by AndrewJDR** [comment] 2017-11-11 01:58
I also want to voice my support for fixing this. Please settle on a hash function and stick to it :)

**Comment by micheleangioni** [comment] 2017-11-20 09:12
Same here with following versions:

node: v8.6.0
npm: 5.5.1

Running `npm install` changes the hash function from sha512 to sha1.

**Comment by AndyOGo** [comment] 2017-11-20 11:16
@zkat same here:

node: v8.8.1
npm: 5.4.2

On Mac OS X El Capitan 10.11.6

**Comment by Sonith** [comment] 2017-11-20 14:46
We have the same issue.

node: 8.9.0
npm: 5.5.1

running Mac Sierra

**Comment by jadenv** [comment] 2017-11-22 18:52
My team is also running into the same issue.

For now, we don't have a choice but to delete our package-lock files and gitignore them because it causes tons of merge conflicts :(

**Comment by AsaAyers** [comment] 2017-11-22 19:03
@jadenv I also added a `.npmrc` to each of my repos. If you don't prevent the files from generating, then each person on your team is going to end up with a unique lock file that they'll have to remember to delete when you really do want to upgrade anything.

https://codeburst.io/disabling-package-lock-json-6be662f5b97d

**Comment by jadenv** [comment] 2017-11-22 19:27
@AsaAyers thanks for the tip!
`echo 'package-lock=false' >> .npmrc` works great 👍🏼

**Comment by ruchernchong** [comment] 2017-11-23 00:51
@zkat this issue seemed to be ongoing.

**Comment by magnusjt** [comment] 2017-11-23 11:30
Still having this issue:

Node: 8.9.1
NPM: 5.5.1

**Comment by Tykzz** [comment] 2017-11-24 09:16
+1

**Comment by todofixthis** [comment] 2017-11-24 21:53
This appears to be a duplicate of #16938 

See https://github.com/npm/npm/issues/16938#issuecomment-339863980 for a workaround.

**Comment by cmloegcmluin** [comment] 2017-11-28 04:56
+1

**Comment by zkat** [comment] 2017-11-28 05:04
Y'all should try `npx npm@next install` and see if things work for you. I'd appreciate someone that has a consistent repro of this issue trying this out and letting me know if the situation's improved. I couldn't quite track down the root cause of this, but that version of npm (`npm@5.6.0`) has some fixes related to this that I _think_ might have fixed it!

**If you had a consistent repro** please try **and report here**.

**Comment by ruchernchong** [comment] 2017-11-28 05:54
The issue seemed to be fixed in `npm@5.6.0`. Fingers crossed that this is not just one project that worked.

**Comment by rpokorny** [comment] 2017-11-28 18:47
> The issue seemed to be fixed in npm@5.6.0. Fingers crossed that this is not just one project that worked.

I have a project where npm 5.6.0 has **not** fixed this issue.  Hashes are still changed when `npm install` is run on Linux vs Mac.

**Comment by drewlustro** [comment] 2017-11-28 19:00
⚠️  **This issue is not fixed with** `npm@5.6.0`

Depending on the system, npm chooses a different integrity hash algorithm. On macOS, it appears to choose `sha1`, on Linux it chooses `sha512`

**Comment by zkat** [comment] 2017-11-28 19:02
@rpokorny @drewlustro could either of you provide an isolated repro? I'm unable to repro this myself right now. I might also suggest making sure you `rm -rf node_modules/` and possibly clear your cache and _then_ try to repro: I'm not sure the changes will repair broken things, but they _might_ help prevent it from happening. A repro would definitely help track this down, though.

**Comment by eyelidlessness** [comment] 2017-11-29 21:48
I'm also experiencing this behavior, which is concerning enough. But what NPM does when this happens is of **much greater concern**. If there is already a hash, and NPM install produces a new hash, this is the current behavior:

1. Install the package with a different hash anyway.
2. Update package-lock.json with the new hash.

This seems to completely disregard the purpose of an integrity hash. I would expect a hash conflict to result in an error, and I would expect the offending hashed package not to be installed.

Not only are we potentially installing compromised software, we're being trained to ignore that fact because it's just noise.

**Comment by zkat** [comment] 2017-11-29 22:44
@eyelidlessness I'd say it's a bit less concerning than you think: both hashes come from the declared checksums for _the same package_. Yes, it's unfortunate to downgrade from sha512->sha1, but iiuc when it comes to this issue, this is just for some reason choosing the wrong algorithm (which might be a cache issue).

Now, I don't really know what the _root cause_ of this, and I'd encourage you to check if this is continuing to happen to you on `npm@5.6.0`, which seems to have resolved it for some people -- and otherwise, help find a resolution so we can get this fixed.

**Comment by eyelidlessness** [comment] 2017-11-29 23:55
@zkat if the hash does not match, there is no way of knowing whether it truly is from the same package. That's the entire point of the hash. The current behavior is allowing untrustworthy code to be installed and spread to others.

Unfortunately I am unable to upgrade NPM for this project, because it is built on Meteor which bundles its own Node/NPM versions (don't get me started on that...).

**Comment by ruchernchong** [comment] 2017-11-30 01:08
I will try it again today for a different project since I see people still having the issue.

**Comment by rpokorny** [comment] 2017-11-30 12:15
@zkat You're right, after removing `node_modules` and clearing the cache I believe 5.6.0 did fix it for us.

**Comment by chancancode** [comment] 2017-12-04 20:08
Hello. I think I have captured a problematic `node_modules` tree locally that reliably reproduces the problem. I don't see anything obviously wrong with it other than the packages having `sha1` checksums.

Deleting `node_modules` does "fix" the problem.

I think there is a more general problem with `npm install` which I documented in #19314.

**Comment by petrasonic** [comment] 2017-12-15 15:04
I fixed the issue by updating npm and reinstalling all the packages. 
`npm i -g npm`
`rm -rf node_modules/`
`npm i`

**Comment by jez9999** [comment] 2017-12-17 13:24
> @zkat You're right, after removing node_modules and clearing the cache I believe 5.6.0 did fix it for us.

So which SHA algorithm does NPM now use; SHA1 or SHA256?  And does it stay at that algorithm on Linux, Windows, and MacOS?

**Comment by zkat** [comment] 2017-12-18 01:59
@jez9999 npm defaults to sha512 for non-registry dependencies, and for new packages publishes. Beyond that, it will use the strongest algorithm available to verify a given dependency: so, if you're installing a registry package that was published with an older version of npm, we only have the sha1 available, and since it's a weaker algorithm, it's inappropriate to "upgrade" it to sha512, so... we leave it as sha1.

The issue with thrash was that there were some inconsistencies throughout npm about which the _default_ was when falling back, and that caused occasional issues with thrash. They're still possible, but I think it might have been fixed.

Since this issue seems to be fixed well enough, I'm going to close it, too.

**Closed as completed by zkat** 2017-12-18 01:59 UTC

**Comment by dsoudakov** [comment] 2018-01-04 15:11
Having the same issue installing a package from a 3rd party registry, defined through npmrc. Getting SHA-512 mismatch with package-lock.json. However, doing individual install with npm install <package url.tgz> works ok. Downgrading to npm3 fixes this. Is it an issue with 3rd party registry? How can it be compatible with both npm3 and npm5+?

npm -v = 5.6.0
node -v = 8.9.3

**Comment by pke** [comment] 2018-01-15 14:46
@zkat Why is it "inappropriate to "upgrade" it to sha512"? I thought the hashes are generated at `npm i` time and not extracted from the package.json generated by an older version if npm during publish.

**Comment by marekr** [comment] 2018-01-21 22:46
Node 8.9.4 and npm 5.6.0 both fresh on a Windows 10 and Windows Server 2016 machine.

Npm on Windows 10 is generating sha1 hashes in a brand new package-lock file.

Npm on the windows server is updating the package-lock file on npm install to sha512.

What the bloody duck?

Also, way to entirely defeat the point of a lock file by changing it in a process that isn't "npm update".

**Comment by IronSean** [comment] 2018-01-29 14:25
Happening to us as well, with one developer on Windows 10 with Node 8.9.7 and npm 5.6.0 and the other on MacOS and Node 9.3.0 and npm 5.6.0.

EDIT: Deleting the node_modules directory, clearing cache, and reinstalling did seem to switch it to SHA512 for me on Windows 10.

**Comment by gjgd** [comment] 2018-02-02 20:43
Same problem here. 
`npm -v`: 5.6.0
`node -v`: v9.4.0

Tried deleting node_modules and clearing the cache, but `npm install`still changes all the sha512 hashes to sha1 hashes.

**Comment by zkat** [comment] 2018-02-02 23:19
@pke the "correct" integrity hash is actually passed to the CLI as part of the registry metadata -- it is the integrity hash the _registry_ is telling us is the correct one. I say it's inappropriate because if the "guarantee" we have from the registry is a weaker algorithm, there's no point in upgrading.

Anyway: This bug should be fixed by now and included in the next npm release. The patch is included in the npm canary, so you can see if the fix works for you by doing `$ npx npmc install`. Note that if your package-lock has already been corrupted, it might still get confused, but I think this should fix the hash-bouncing issue, as well as the `EINTEGRITY` warnings people keep getting.

**Comment by nwshane** [comment] 2018-02-14 17:16
@zkat My company is dealing with this bug right now, so I'm glad to hear it should be fixed in the next npm release. Can you tell us when that will be?

Thanks for your hard work!

**Comment by mateomurphy** [comment] 2018-02-19 19:20
Just ran into this. Running the canary build did not fix the issue, however deleting `node_modules` and reinstalling did.

**Comment by Baiteman** [comment] 2018-02-21 11:37
We've recently upgraded all our projects to npm 5.6.0 as well and people across different machines with the same operating systems get different hashcodes.
For most circumstances removing the npm folder and cache has sufficed but I'm looking forward to the aforementioned fix being released.

**Comment by mateomurphy** [comment] 2018-02-21 14:41
I got the error when switching branches on the same machine...

**Comment by dj** [comment] 2018-03-23 14:01
`npx npm@next install`

This still causes the integrity has to change for me. Can't produce a repro right now because it's a client project, but it's a barely modified create-react-app so I can't imagine my case is all that uncommon. Will try to come up with a reproduction after work.

**Comment by Olgagr** [comment] 2018-03-26 09:49
I confirm that the problem still exists. We can reproduce the issue on 2 machines, both have node 8.10.0 and npm 5.6.0. Both machines have MacOS but one has El Capitan and other has High Sierra. On El Capitan npm prefers sha512, on High Sierra it falls back to sha1

**Comment by emilgoldsmith** [comment] 2018-03-28 12:43
Me too with both 5.6.0 and 5.8.0, node version 9.3.0

**Comment by mhama** [comment] 2018-03-29 02:40
This procedure fixed the issue on my MacBook (Mac OS X Sierra).
https://github.com/npm/npm/issues/16938#issuecomment-339863980
After that, my npm (v5.8.0) changed the generating integrity from sha1 to sha512.

**Comment by ogonkov** [comment] 2018-03-30 20:22
Fixed for me as of
$ npm -v
5.8.0
$ node -v
v8.9.4

with
$ rm package-lock.json
$ rm -rf node_modules/
$ npm cache verify // This one probably is not required
$ npm cache clear --force
$ npm i

This will generate changed `package-lock.json`, but after reverting it to the version from git, integrity changes disappear.

Seems like some caching issue for me.

**Comment by ozzyogkush** [comment] 2018-04-25 15:19
Is there an .npmrc config option we can set to force NPM to use SHA512 or SHA1?

**Comment by zkat** [comment] 2018-04-25 16:07
@ozzyogkush no. npm tries to always use the strongest available algorithm.

**Comment by clarete** [comment] 2018-04-26 21:58
@zkat thanks for the very important piece of info! I was wondering if it would be nice to warn (or even error out) if the strongest available algorithm is weaker than what was used to generate the `package-lock.json` file. If that's something you'd consider useful, I could create a new issue. Anyway, thank you for the great tool that is npm!

**Comment by jarrodconnolly** [comment] 2018-04-26 23:16
@zkat  Can this be re-opened? It is clearly an issue for many people including myself. The lock file is essentially useless noise with flip-flop going on all the time. No one pays attention to actual changes in the file anymore, or has just stopped tracking it in source control.

**Comment by zkat** [comment] 2018-04-27 22:56
@jarrodconnolly This thread is way past being useful to me to resolve anything.

There are two things you can do:
1. Create a new issue with a complete, self-contained reproduction of this issue
2. Send me a patch that actually fixes it for you, and I'll merge it.

These are the available options. I will lock this issue after this comment.

It is not very practical of me to try and suss out what people on 10 different versions of npm are experiencing exactly, what their environments were at the time of installation, and whether they even read other responses here. I've already done several patches fixing various situations where this thrash would've happened, and I'd like to see what the remaining gaps are, but since I have no repro for this myself, I can't help you.
