### ISSUE TITLE
Unable to install using install script

### ISSUE THREAD

**Issue by ibrechin** [npm/npm#16874] opened 2017-06-01 14:45 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Attempting to install npm both inside docker (ubuntu trusty) or on my machine (mint 18) using the following process:

```
curl -sL https://deb.nodesource.com/setup_7.x | bash -
apt-get install nodejs
curl -L https://npmjs.org/install.sh | bash
```

The output of the install script is:

```
tar=/bin/tar
version:
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.0.1.tgz
removed 254 packages in 12.493s
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
added 1 package in 2.138s
It worked
```

And after that point, `npm` is no longer available. 

```
➤ whereis npm
npm: /usr/bin/npm /usr/share/man/man1/npm.1

➤ ls -l /usr/bin/npm
lrwxrwxrwx 1 root root 38 Jun  1 14:46 /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js

➤ ls -l /usr/lib/node_modules/npm 
lrwxrwxrwx 1 root root 30 Jun  1 14:59 /usr/lib/node_modules/npm -> ../../../tmp/npm.49197/package

➤ ls -l /tmp/npm.49197/package
ls: cannot access '/tmp/npm.49197/package': No such file or directory
```
Cannot use ```npm install``` instead as I run into the same issue as in https://github.com/npm/npm/issues/16807

#### How can the CLI team reproduce the problem?

Use Dockerfile:

```
FROM ubuntu:trusty

RUN apt-get update
RUN apt-get install -y curl

# install node.js
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y nodejs
RUN curl -L https://npmjs.org/install.sh | bash
RUN npm --version  # this will fail
```

### supporting information:

 - `npm -v` prints: doesn't
 - `node -v` prints: v7.10.0
 - `npm config get registry` prints: doesn't
 - Windows, OS X/macOS, or Linux?: Linux (base and in docker)

**Comment by casoetan** [comment] 2017-06-02 09:14
Same issue. How do I go back.

**Comment by ibrechin** [comment] 2017-06-02 10:06
@casoetan if by "go back" you mean just install the latest pre-5 version you can do:

`curl -L https://npmjs.org/install.sh | npm_install=4.6.1 bash`

**Comment by casoetan** [comment] 2017-06-02 10:36
Thanks. From there I updated to 5.0.0. But holding out on 5.0.1

Best, \Charles
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.7.29&pv=10.12.5&source=email_footer_2]
On Fri, Jun 2, 2017 at 11:06, Ian Brechin <notifications@github.com> wrote:
@casoetan [https://github.com/casoetan] if by "go back" you mean just install the latest pre-5 version you can do:

curl -L https://npmjs.org/install.sh | npm_install=4.6.1 bash

**Comment by zkat** [comment] 2017-06-05 15:34
Closing as duplicate of https://github.com/npm/npm/issues/16807

**Closed as completed by zkat** 2017-06-05 15:34 UTC
Labels: docker, npm5
