### ISSUE TITLE
npm is doing something I don't understand.

### ISSUE THREAD

**Issue by sudhirrayini** [npm/npm#15958] opened 2017-03-06 09:35 UTC
C:\Users\sudhir.rayini\Desktop\masherytools-master\masherytools-master\api_definition_converter>npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\SUDHIR~1.RAY\AppData\Local\Temp\npm-36
88-083b2e8f\registry.npmjs.org\faker\-\faker-3.1.0.tgz
npm ERR! Expected: 0f908faf4e6ec02524e54a57e432c5c013e08c9f
npm ERR! Actual:   f9a08a26a7794720ca64a0f78c46b229389a2686
npm ERR! From:     https://registry.npmjs.org/faker/-/faker-3.1.0.tgz

**Comment by legodude17** [comment] 2017-03-06 17:21
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-17 03:56 UTC
Labels: bot-closed
