### ISSUE TITLE
problem with creating an app with command "yo angular webapp"

### ISSUE THREAD

**Issue by gaja33** [npm/npm#7498] opened 2015-02-28 07:48 UTC
My npm version is 1.4.3 and my node version is v.0.10.26 and below is my error in log file.

```
139550 verbose about to build C:\Demo\NewDemo\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modules\bin-build\node_modules\download\node_modules\vinyl-fs
139551 info build C:\Demo\NewDemo\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modules\bin-build\node_modules\download\node_modules\vinyl-fs
139552 error Error: ENOENT, lstat 'C:\Demo\NewDemo\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download\node_modules\request\node_modules\mime-types\node_modules\mime-db\HISTORY.md'
139553 error If you need help, you may report this *entire* log,
139553 error including the npm and node versions, at:
139553 error     <http://github.com/npm/npm/issues>
139554 error System Windows_NT 6.1.7600
139555 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
139556 error cwd C:\Demo\NewDemo
139557 error node -v v0.10.26
139558 error npm -v 1.4.3
139559 error path C:\Demo\NewDemo\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download\node_modules\request\node_modules\mime-types\node_modules\mime-db\HISTORY.md
139560 error fstream_path C:\Demo\NewDemo\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\download\node_modules\request\node_modules\mime-types\node_modules\mime-db\HISTORY.md
139561 error fstream_type File
139562 error fstream_class FileWriter
139563 error code ENOENT
139564 error errno 34
139565 error fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
139565 error fstream_stack Object.oncomplete (fs.js:107:15)
139566 verbose exit [ 34, true ]
```

**Comment by KenanY** [comment] 2015-02-28 15:12
@gaja33 `npm@1.4.3` is quite old. Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by smikes** [comment] 2015-04-29 17:57
Is this still a problem for you?

This looks like the kind of error that was caused by race conditions in older versions of `npm` -- particularly in 1.4. There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by gaja33** [comment] 2015-05-07 11:07
I think there was a problem with my antivirus software which was blocking
required files to get downloaded.. but during creating webapp i need to
disable antivirus and then enable it.. else its working fine for me now..

Thank You.

**Comment by othiym23** [comment] 2015-05-20 03:11
Closing as resolved.

**Closed by othiym23** 2015-05-20 03:11 UTC
Labels: support, windows
