### ISSUE TITLE
Not able to install Protractor

### ISSUE THREAD

**Issue by MugilRaja** [npm/npm#13874] opened 2016-09-06 06:30 UTC
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?
C:\>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\mrajagopal\AppData\Roaming\npm\node_modules\protractor\no
de_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall unlink

npm ERR! EBUSY: resource busy or locked, unlink 'C:\Users\mrajagopal\AppData\Roa
ming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\seleniu
m-server-standalone-2.53.1.jar'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, unlink 'C:\Us
ers\mrajagopal\AppData\Roaming\npm\node_modules\protractor\node_modules\webdrive
r-manager\selenium\selenium-server-standalone-2.53.1.jar'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, unlink 'C
:\Users\mrajagopal\AppData\Roaming\npm\node_modules\protractor\node_modules\webd
river-manager\selenium\selenium-server-standalone-2.53.1.jar']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: 'C:\\Users\\mrajagopal\\AppData\\Roaming\\np
m\\node_modules\\protractor\\node_modules\\webdriver-manager\\selenium\\selenium
-server-standalone-2.53.1.jar' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>
### supporting information:

 - `npm -v` prints:
2.15.8
 - `node -v` prints:
v.4.4.7
 - `npm config get registry` prints:
C:\>npm config get
; cli configs
user-agent = "npm/2.15.8 node/v4.4.7 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\mrajagopal\\AppData\\Roami

; node bin location = C:\Program Files\nodejs\n
; cwd = C:\
; HOME = C:\Users\mrajagopal
; 'npm config ls -l' to show all defaults.
 - Windows, OS X, or Linux?:
Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.

 - Container:
   - [ ] I develop using Vagrant on Windows.

**Comment by KenanY** [comment] 2016-09-06 13:38
@MugilRaja Does this still happen after rebooting?

**Comment by busches** [comment] 2016-09-10 10:53
Duplicate of https://github.com/npm/npm/issues/8564 @KenanY

**Comment by KenanY** [comment] 2016-09-10 14:38
Alright, closing.

**Closed by KenanY** 2016-09-10 14:38 UTC
