### ISSUE TITLE
npm v5 install crashes on git dependency

### ISSUE THREAD

**Issue by medikoo** [npm/npm#16907] opened 2017-06-02 08:34 UTC
Might be related to #16898 

#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

It crashes on install of dependency formulated as:

```json
 "serverless-meta-sync": "git://github.com/serverless/serverless-meta-sync.git#c5e34a59a8665df703534ee18464d035ef30edc6"
```

#### How can the CLI team reproduce the problem?

Create folder with package.json as:

```json
{
  "dependencies": {
    "serverless-meta-sync": "git://github.com/serverless/serverless-meta-sync.git#c5e34a59a8665df703534ee18464d035ef30edc6"
  }
}
```
Run:

    $  npm install

It crashes with:

```
$ npm install
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b 15/head git://github.com/serverless/serverless-meta-sync.git /Users/medikoo/.npm/_cacache/tmp/git-clone-aa8b2c4e
npm ERR! warning: templates not found /var/folders/rr/p8qlym295pv8b2b3bdhz1hwc0000gn/T/pacote-git-template-tmp/git-clone-e912360e
npm ERR! warning: Could not find remote branch 15/head to clone.
npm ERR! fatal: Remote branch 15/head not found in upstream origin
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/medikoo/.npm/_logs/2017-06-02T08_30_33_855Z-debug.log
```

Content of debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.0.1
3 info using node@v8.0.0
4 silly install runPreinstallTopLevelLifecycles
5 silly preinstall maas-tsp-reference-zip
6 info lifecycle @~preinstall: @
7 silly lifecycle @~preinstall: no script for preinstall, continuing
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly fetchPackageMetaData error for serverless-meta-sync@git://github.com/serverless/serverless-meta-sync.git#c5e34a59a8665df703534ee18464d035ef30edc6 Command failed: /usr/local/bin/git clone --depth=1 -q -b 15/head git://github.com/serverless/serverless-meta-sync.git /Users/medikoo/.npm/_cacache/tmp/git-clone-aa8b2c4e
14 silly fetchPackageMetaData warning: templates not found /var/folders/rr/p8qlym295pv8b2b3bdhz1hwc0000gn/T/pacote-git-template-tmp/git-clone-e912360e
14 silly fetchPackageMetaData warning: Could not find remote branch 15/head to clone.
14 silly fetchPackageMetaData fatal: Remote branch 15/head not found in upstream origin
15 verbose stack Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b 15/head git://github.com/serverless/serverless-meta-sync.git /Users/medikoo/.npm/_cacache/tmp/git-clone-aa8b2c4e
15 verbose stack warning: templates not found /var/folders/rr/p8qlym295pv8b2b3bdhz1hwc0000gn/T/pacote-git-template-tmp/git-clone-e912360e
15 verbose stack warning: Could not find remote branch 15/head to clone.
15 verbose stack fatal: Remote branch 15/head not found in upstream origin
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:252:12)
15 verbose stack     at emitTwo (events.js:125:13)
15 verbose stack     at ChildProcess.emit (events.js:213:7)
15 verbose stack     at maybeClose (internal/child_process.js:887:16)
15 verbose stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
15 verbose stack     at emitOne (events.js:115:13)
15 verbose stack     at Socket.emit (events.js:210:7)
15 verbose stack     at Pipe._handle.close [as _onclose] (net.js:546:12)
16 verbose cwd /Users/medikoo/Projects/maas/maas-tsp-reference-zip
17 verbose Darwin 16.6.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
19 verbose node v8.0.0
20 verbose npm  v5.0.1
21 error code 128
22 error Command failed: /usr/local/bin/git clone --depth=1 -q -b 15/head git://github.com/serverless/serverless-meta-sync.git /Users/medikoo/.npm/_cacache/tmp/git-clone-aa8b2c4e
22 error warning: templates not found /var/folders/rr/p8qlym295pv8b2b3bdhz1hwc0000gn/T/pacote-git-template-tmp/git-clone-e912360e
22 error warning: Could not find remote branch 15/head to clone.
22 error fatal: Remote branch 15/head not found in upstream origin
23 verbose exit [ 1, true ]

```

I also tried with fresh setup (removed `~/.npm`) same error occurs.

Package installs successfully when I downgrade to npm v4

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOs
 - Network issues:
   - Geographic location where npm was run: Warsaw, Poland
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mistydemeo** [comment] 2017-06-02 16:38
This looks like a dupe of #16898.

**Closed as completed** 2017-06-17 03:16 UTC
Labels: git, npm5

**Comment by laurisvan** [comment] 2017-07-03 16:04
I can confirm this error still repeated on with npm@5.0.4, so we should reopen it.

**Comment by medikoo** [comment] 2017-07-03 20:00
@iarna @zkat will you reopen, or should I report it again?

**Comment by medikoo** [comment] 2017-07-06 15:44
I can confirm it's still a bug with npm@5.1.0

**Comment by jehy** [comment] 2017-07-10 09:00
Yup, bug still exists in npm 5.1.0

**Comment by israel-maloney** [comment] 2017-07-10 23:05
I experienced this issue on version 5.0.3, then regressed to version 4.2.0 to get around the issue for now.

**Comment by medikoo** [comment] 2017-07-11 06:28
@zkat @iarna are you considering reopenning the issue? It's clearly a critical bug with npm@5

**Comment by Swailem95** [comment] 2017-07-30 12:24
Experiencing this on version 5.3.0.

**Comment by jcroll** [comment] 2017-09-15 15:33
Please reopen issue, it's a bug!

**Comment by ljharb** [comment] 2017-09-15 15:59
File a new one then :-)

**Comment by jcroll** [comment] 2017-09-15 16:05
:-) why

**Comment by ljharb** [comment] 2017-09-15 18:58
I would assume because you want it fixed?

**Comment by jcroll** [comment] 2017-09-15 19:20
To the same efficiency the opener of this thread experienced?

**Comment by medikoo** [comment] 2017-09-18 09:00
There were other issue attempts:

https://github.com/npm/npm/issues/16991#issuecomment-313436114
https://github.com/npm/npm/issues/18056

No success, it appears it's the way things are handled here

**Comment by swapy** [comment] 2017-10-03 07:15
Downgrading npm from 5 to 4 worked for me :)
`npm install -g npm@4`

**Comment by nikhildaga** [comment] 2017-10-31 20:26
npm 5 is such a time waster. It shouldn't be bundled with node
`npm i` works fine when using npm@3.10.8 and gives `Command failed: /usr/bin/git checkout ` with npm@5.5.1

**Comment by kontrollanten** [comment] 2018-03-03 14:00
I solved it by updating to version 5.7.1 by running
```
npm install npm -g
```

**Comment by mfpiccolo** [comment] 2018-04-05 17:40
This is still a bug on 5.8.0

**Comment by zkat** [comment] 2018-04-05 17:56
Alright so, I need a better repo: @medikoo's repro works now, but that's because `c5e34a59a8665df70` literally does not exist when you clone that repo. I see that https://github.com/serverless/serverless-meta-sync/commit/c5e34a59a8665df703534ee18464d035ef30edc6 exists on github, but if I clone that repo manually, that shasum is not there. So I'm not sure what's going on here.

This issue is closed because the _original_ issue, where a remote branch was being referenced, is no longer a problem and was fixed a while back. To y'all replying: it's way more helpful to have a full, self-contained reproduction for a bug, and hopefully after you've done your own debugging on the git repo with the commands stated. Otherwise, it's extraordinarily useless to keep posting in a closed issue thread like this.

**Comment by medikoo** [comment] 2018-04-06 15:39
@zkat see: https://github.com/serverless/serverless-meta-sync/pull/15

It looks it was a desired change that was proposed as PR, but not merged as it didn't apply to shortly coming SLS v1 version.

For those stuck at SLS v0.5 it was [recommended](https://github.com/serverless/serverless-meta-sync/pull/15#issuecomment-236894367) to rely on `serverless/serverless-meta-sync.git#c5e34a59a8665df703534ee18464d035ef30edc6` in package.json.

So technically this commit never landed in `serverless/serverless-meta-sync` repo, but referring to that commit (in context of `serverless/serverless-meta-sync`) works both on Github, and installs without issues with npm v4, and why is that, I'm also unable to explain.

**Comment by zkat** [comment] 2018-04-06 17:35
@medikoo I literally don't understand how it works on npm@4. I am -tremendously- confused about this because raw git itself can't clone this. If anyone figures out how the hell this is happening, I will happily fix it. I'm vexed.

**Comment by zkat** [comment] 2018-04-06 18:09
oh nevermind I figured it out. lol

**Comment by zkat** [comment] 2018-04-06 18:15
https://github.com/zkat/pacote/commit/fb186f93bb6d92b8e90347bdac3ef87060c55e0a

It'll work with this patch. Just gonna do some routine checks and it should go out with the next possible release.

**Comment by medikoo** [comment] 2018-04-09 07:26
> Just gonna do some routine checks and it should go out with the next possible release.

Thank you!
