### ISSUE TITLE
can't npm instsall express --save. Had this problem for a week.

### ISSUE THREAD

**Issue by keeseok1993** [npm/npm#18216] opened 2017-08-17 21:39 UTC
I'm having this problem where I can't instasll anything on npm.

![capture](https://user-images.githubusercontent.com/31081895/29434931-cb1475da-8359-11e7-9194-7fe8c3d034f2.PNG)
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:34:35 PM
17 verbose request id eb6f0b388887da7a
18 http request GET https://registry.npmjs.org/express
19 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
20 info attempt registry request try #2 at 2:34:45 PM
21 http request GET https://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #3 at 2:35:45 PM
24 http request GET https://registry.npmjs.org/express
25 silly fetchPackageMetaData Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
25 silly fetchPackageMetaData  error for express { Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate in certificate chain
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
31 verbose cwd C:\Users\hongk01\Desktop\front\project\asd
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
34 error node v6.11.2
35 error npm  v3.10.10
36 error code SELF_SIGNED_CERT_IN_CHAIN
37 error self signed certificate in certificate chain
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

I'll really appreciate for any help. Thank yoU!

**Comment by kenany** [comment] 2017-08-17 21:44
Duplicate of #18195

**Closed as completed by kenany** 2017-08-17 21:44 UTC
Labels: support

**Comment by keeseok1993** [comment] 2017-08-17 22:01
Could u solve it for me KenanY ?
