### ISSUE TITLE
npm install creating memory leak warning

### ISSUE THREAD

**Issue by rzeng95** [npm/npm#13760] opened 2016-08-24 16:52 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
![dbfca3ec7878d795752e064294aa0f2f](https://cloud.githubusercontent.com/assets/11772350/17939615/0a40c28c-69f1-11e6-8eaf-6e988365df91.png)

#### How can the CLI team reproduce the problem?
Clone from this repo: https://github.com/reactjs/react-router-tutorial
cd to lesson 1 and run npm install

### supporting information:

 - `npm -v` prints:   
3.10.7
 - `node -v` prints:   
v4.5.0
 - `npm config get registry` prints:  
https://registry.npmjs.org/
 - Windows, OS X, or Linux?:   
Windows 10 (using powershell)

**Comment by KenanY** [comment] 2016-08-24 18:20
Closing as a duplicate of https://github.com/npm/npm/issues/13656. If I am mistaken then I can easily reopen. Thanks for reporting this!

**Closed by KenanY** 2016-08-24 18:20 UTC
