### ISSUE TITLE
npm preinstall runs like postinstall

### ISSUE THREAD

**Issue by Luchillo** [npm/npm#12188] opened 2016-04-04 16:45 UTC
I have this as scripts: 
```js
"scripts": {
    "preinstall":"rm -rf node_modules",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  }
```
However this is the start of output of `npm i`, i think the postinstall is running after because the `node_module` folder isn't there, therefore it is installing then removing, but should be the other way around:
```sh
npm i
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN prefer global voc@0.5.0 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> node-sass@3.4.2 install /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest/node_modules/node-sass/vendor/darwin-x64-47/binding.node

> spawn-sync@1.0.15 postinstall /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest/node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest/node_modules/node-sass
> node scripts/build.js

` /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> rest@1.0.0 preinstall /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest
> rm -rf node_modules

rest@1.0.0 /Users/aplicacionesosgroup/Documents/OSGroup/tao_app/rest
├── adler-32@0.3.0 
├─┬ body-parser@1.15.0 
```

**Comment by othiym23** [comment] 2016-04-11 21:29
I believe this is a duplicate of #10379, and am closing it as such. Let us know if you think your issue is different, and I can reopen this. Thanks for your time!

**Closed by othiym23** 2016-04-11 21:29 UTC
Labels: bug, lifecycle

**Comment by Luchillo** [comment] 2016-04-12 15:34
@othiym23 It indeed seems like the same issue, though it seems the use case of the author of that issue is way complicated and is being tackled as a misunderstanding about the way npm reads the package.json scripts, however mine is just 2 commands that are executed in wrong order as stated in the docs of npm, it's a way simpler bug that should be easy to fix (i think).

Wether opening this again or just sticking with the other issue i leave that to you.
