### ISSUE TITLE
Unable to install appdynamics node module

### ISSUE THREAD

**Issue by beingshashi** [npm/npm#12522] opened 2016-04-29 07:16 UTC
Hi,

see below my error:

```
npm install appdynamics@4.1.2
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-protobuf.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-zmq.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-native.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-protobuf.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-zmq.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-native.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-native.tgz
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-zmq.tgz
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.1.2.0/appdynamics-protobuf.tgz
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "appdynamics@4.1.2"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
```

i have also trived different and latest versions of appdynamics upto 4.2.1 bu still same error

**Comment by Meldryn** [comment] 2016-04-29 16:05
Hi Beingsashi,

This is not a bug in npm itself. These 403 errors mean you're trying to install appdynamics 4.1.2 for a version of nodejs we don't support. Please file a support case at help.appdynamics.com and we'll resolve this swiftly.

Best,
AppDynamics Support

**Comment by othiym23** [comment] 2016-05-02 21:09
Closing as resolved; this is an oddity of working with AppDynamics's private registry, and isn't an issue with npm proper as far as I know. Thanks for your time!

**Closed by othiym23** 2016-05-02 21:09 UTC
Labels: support

**Comment by SabaaParaveen** [comment] 2016-05-30 13:04
Hi,

I am trying to install appdynamics in node version 5.0 but getting the same error. Does any one has clue what can be done?

**Comment by beingshashi** [comment] 2016-05-30 13:16
You have degrade the version of node...I have to do that to solve this issue

Regards,

Shashikant Sharma
