### ISSUE TITLE
npm outdated --global doesn't return any results, but there are outdated packages

### ISSUE THREAD

**Issue by eamodio** [npm/npm#17011] opened 2017-06-06 06:54 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running `npm outdated --global`, I am not always seeing any results, while I know there are outdated packages. For example, I first noticed this with npm itself -- I have `5.0.1`, but the registry had `5.0.3`, but `npm outdated -g` didn't provide any results.

#### How can the CLI team reproduce the problem?

Not exactly sure unfortunately :(

### supporting information:

 - `npm -v` prints: `5.0.3`
 - `node -v` prints: `v7.10.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Windows`
 - Network issues:
   - Geographic location where npm was run: `Northeastern US`
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2017-06-06 06:57
This is a duplicate of https://github.com/npm/npm/issues/16840

**Closed as completed by zkat** 2017-06-06 06:57 UTC
Labels: npm5

**Comment by eamodio** [comment] 2017-06-06 06:59
Doh -- sorry

**Comment by zkat** [comment] 2017-06-06 07:48
No worries. It's hard to dig through stuff 👍
