### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Budiman123** [npm/npm#12065] opened 2016-03-25 15:17 UTC
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\Heartnetz\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\Heartnetz\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Heartnetz\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Heartnetz\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'C:\\Users\\Heartnetz\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\node-sass' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Heartnetz\npm-debug.log
```

**Comment by zkat** [comment] 2016-03-25 23:43
Hi @Budiman123!

As it turns out, Windows is very particular about not allowing directories and files that are open, in some way, from being deleted.

In order to get around this error, please make sure any other terminals or IDEs or such don't have this file open, and let me know if that helps. If not, we'll try and figure out what else it could be. :)

**Comment by nitriques** [comment] 2016-08-16 21:02
I must have this error 80% of the time when I `npm i` on Windows. Weird thing is, no process should have any of the listed files opened... Maybe consider doing it a 2nd time before crashing?

**Comment by othiym23** [comment] 2016-08-19 21:57
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:57 UTC
Labels: support, windows
