### ISSUE TITLE
npm search returning errors

### ISSUE THREAD

**Issue by hylinlin** [npm/npm#13431] opened 2016-07-19 23:53 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `npm search hyperterm` I get this error `npm ERR! Cannot read property '_updated' of undefined` : 
![image](https://cloud.githubusercontent.com/assets/2435365/16970106/9bd3e1c8-4dce-11e6-8443-eb7983e553d7.png)

Then, I searched around to see how others handled this issue, and came across some posts saying I should run `npm cache clean` and I ran that command.

After running that, I tried running `npm search hyperterm` again and got this:
![image](https://cloud.githubusercontent.com/assets/2435365/16970166/05d3c2a0-4dcf-11e6-97df-b366f3ea407c.png)

my setup:
OSX 10.11.3
node version 6.3.0
npm version 3.10.5

I have uninstalled and reinstalled node and npm trying to correct this problem, but no luck.

#### How can the CLI team reproduce the problem?
To reproduce the problem, try to search using npm like `npm search hyperterm`, and you may get the same issue. 

Here's a link to the gist containing my npm-debug.log file: https://gist.github.com/hylinlin/6e68e1f0b54b1e1746de09cd86713a89

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints: 6.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: San Francisco
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by hylinlin** [comment] 2016-07-20 01:46
this issue has already been reported here https://github.com/npm/npm/issues/13310

**Comment by othiym23** [comment] 2016-07-28 00:41
Closing as duplicate of #12619.

**Closed by othiym23** 2016-07-28 00:41 UTC
Labels: big-bug, bug, search
