### ISSUE TITLE
Respect console's color settings (on Powershell on windows)

### ISSUE THREAD

**Issue by be5invis** [npm/npm#2381] opened 2012-04-18 02:28 UTC
I use `npm` on Powershell, but npm changed the console's background color.

**Comment by AncientSwordRage** [comment] 2015-02-19 14:38
:+1:

**Comment by stereokai** [comment] 2015-02-20 04:51
@iarna Any ideas (please see my previous comment)

**Comment by Ciwan1859** [comment] 2015-06-04 10:12
This was first reported in April 2012! Over three years and still no fix :( This buy is annoying.

**Comment by stereokai** [comment] 2015-06-04 10:49
@iarna @isaacs

Just because you guys use Macs doesn't take away from how annoying this bug is. And even if this issue doesn't seem to broadcast significance to you, doesn't mean you should let this one fall between the cracks. After all it's your product, and If this behavior would have occurred on OSX terminals, I am absolutely *confident* this bug would have been dealt with a long time ago. 

6 months ago I also said I am willing to invest my time into this and even posted a practical comment, which I quote here below:

> There only 2 calls to `color.bgBlack`: https://github.com/npm/npm/search?utf8=%E2%9C%93&q=color.bg
>
> I don't think these are the problem. Perhaps incorporating something like this could be a solution:
> https://github.com/adoxa/ansicon ?

Looking forward to your comment.

**Comment by domenic** [comment] 2015-06-04 14:51
Looking forward to pull requests from those complaining.

**Comment by DanTup** [comment] 2015-06-04 15:38
> Looking forward to pull requests from those complaining.

What a poor attitude. Since when was "fixing bugs you find" a condition of using OSS? Why no appreciation for those taking time to report bugs to you and even do some investigation into the issue?

**Comment by Ciwan1859** [comment] 2015-06-04 15:43
Surely domenic is joking! O.0

**Comment by domenic** [comment] 2015-06-04 15:45
Not at all. Complaining on an issue tracker is not very helpful in fixing the issue. This is a known issue, tagged with patch-welcome, and just complaining that the npm team has been working on other issues instead of the particular one you care about is very bad open source ettiquete, compared to actually contributing to the project.

**Comment by Ciwan1859** [comment] 2015-06-04 15:50
Thanks, with context, your previous post becomes understandable. My apologies, I was in a bad mood when I complained, I like my colours in PowerShell :) Will look and see if I can fix this damn thing.

**Comment by DanTup** [comment] 2015-06-04 15:56
> Complaining on an issue tracker is not very helpful in fixing the issue.

I think people are simply trying to express how frustrating this bug is, because it's clear it probably isn't affecting any of the contributors. Every time I use npm, I end up restarting PowerShell just to fix the colours. It makes npm seem unpolished and unloved.

> compared to actually contributing to the project

I don't know, but I interpreted this comment:

> There only 2 calls to color.bgBlack: https://github.com/npm/npm/search?utf8=%E2%9C%93&q=color.bg
> 
> I don't think these are the problem. 

as "I can't figure out where this could be coming from and need some pointers". Sometimes something that is trivial to debug to someone that's familiar with the code is not so for someone else.

I'd love to have a go at fixing this but with limited time, it would probably take me a long time just to get the thing up and running in a way that would allow me to debug and investigate.

Having the time, motivation or ability to fix something is not an advertised condition of using OSS but if that's how things are then maybe it should be made clear. Nothing worse than committing to a technology to find the author(s) will not fix any bugs you report and expect you to do it yourself. There is an assumption that an active OSS project will have bugs that affect large numbers of people fixed; it's not unreasonable for people to show their support for a case (especially in an issue tracker that has no good way to vote, like Google Issues had stars, to help prioritise cases).

**Comment by floyd-may** [comment] 2015-06-04 16:21
In the interest of keeping this positive and productive, I took a look at the code. After a brief perusal [here](https://github.com/npm/npm/blob/master/lib/npm.js#L332), I suspect that this bug may need to be moved to the [npmlog](https://github.com/npm/npmlog) project. My guess is that the npmlog object should capture the current foreground and background colors upon its first interaction with the output stream, and be responsible for restoring them.  Could one of the maintainers weigh in here, please?

**Comment by watilde** [comment] 2015-06-04 20:46
How about to make default value of `npm.color` `false` when running on  `process.platform === "win32"`...? https://github.com/npm/npm/blob/master/lib/npm.js#L347-L353

**Comment by floyd-may** [comment] 2015-06-04 20:53
:-1: `npm.color = true` is a good default if the terminal supports it. Turning them off by default will almost certainly ensure that this issue never gets fixed because fewer people would make noise about it.

Once upon a time I put [a powershell function](http://stackoverflow.com/questions/13805646/how-can-you-reset-the-colors-for-windows-powershell-if-they-become-corrupted-aft) into my `profile.ps1` that restores the FG and BG colors.

**Comment by floyd-may** [comment] 2015-06-05 02:37
And down the rabbit hole we go. I'm suspecting that the `ansi` package that npmlog uses may be the actual culprit. I'll take a crack at a boiled-down repro in the next few days.

**Comment by Ciwan1859** [comment] 2015-06-05 09:08
Thanks floyd, mcuh apprecaited.

**Comment by stereokai** [comment] 2015-06-05 09:12
@domenic 

> Not at all. Complaining on an issue tracker is not very helpful in fixing the issue. This is a known issue, tagged with patch-welcome, and just complaining that the npm team has been working on other issues instead of the particular one you care about is very bad open source ettiquete, compared to actually contributing to the project.

Excuse me? Have you actually paid attention to my... "rant"? I wasn't only complaining (though rightfully so, and in stark contrast to you), I actually had a go at this *6 months ago* and was looking for some pointers from people who *actually know the code*. Like you.

I don't want to turn this into a personal thing or whatever. But you could might as well direct your comment about my "complaining, non-contributing attitude" to yourself.

@floyd-may 
> Once upon a time I put a powershell function into my profile.ps1 that restores the FG and BG colors.
Although not a fix to the bug, it's a very clever idea - well done!

> And down the rabbit hole we go. I'm suspecting that the ansi package that npmlog uses may be the actual culprit. I'll take a crack at a boiled-down repro in the next few days.

That's what @iarna recommended me to look at last year. I have taken another thorough look at [ansi](https://github.com/TooTallNate/ansi.js/blob/master/lib/ansi.js), but I have a hunch that this is not where the problem is. I tend to lean towards Rebecca's idea:

> powershell doesn't properly support ansi. =( It almost certainly supports 0 to restore EVERYTHING to the defaults, you'll just have to **figure out how to issue that at the right time...**

**Comment by floyd-may** [comment] 2015-06-05 13:27
@stereokai  In reference to this:
> powershell doesn't properly support ansi. =( It almost certainly supports 0 to restore EVERYTHING to the defaults, you'll just have to **figure out how to issue that at the right time...**

[Here's an interesting tidbit from `npmlog`](https://github.com/npm/npmlog/blob/master/log.js#L217). It calls `.reset()` after every write, which leads me to thinking that the problem may lie with `ansi`'s `reset()` function.

**Comment by floyd-may** [comment] 2015-06-05 13:44
Actually, I just discovered something beautifully interesting. And frustrating as well. I put together a little sample app using `ansi`:

    var ansi = require('ansi');

    var ansiLogger = ansi(process.stderr);

    ansiLogger.fg.red();
    ansiLogger.bg.grey();

    ansiLogger.write('colored output\n').reset();

Now, in ConEmu (my terminal of choice on Windows), this works fine:

![image](https://cloud.githubusercontent.com/assets/1608756/8006976/15ed68da-0b5e-11e5-90ab-09dd535c65ae.png)

However, if I use powershell.exe by itself, I get the derpy behavior:
![image](https://cloud.githubusercontent.com/assets/1608756/8007014/4c7f9d00-0b5e-11e5-81f2-784e59442fa2.png)

So, IMHO, `ansi` (and, by extension, `npmlog` [and, by extension, `npm`]) is doing the Right Thing (tm) and resetting the colors. It just so happens that Powershell.exe's GUI on Windows doesn't properly interpret it.

You may consider switching to ConEmu (or something like it) rather than using powershell.exe as-is. Resizable window, tabs, etc. You will hate life less, and be less prone to internet trolling.

**Comment by mvas** [comment] 2015-10-23 16:10
Seems to be powershell issue, ansi's reset function does the right thing - it prints ANSI reset code (actually that's the single possible way, a terminal is not able to report its original colors in general). Powershell just treats the reset ANSI code as resetting to black and white - not the original powershell colors.

Workaround that I've used is to update prompt function in default powershell profile, add [Console]::ResetColor();
![image](https://cloud.githubusercontent.com/assets/1790471/10698360/ec9c919c-79b0-11e5-9719-c6ca7a32c478.png)

updated https://github.com/TooTallNate/ansi.js/issues/22 as well

**Comment by iarna** [comment] 2016-04-15 21:38
I can confirm that this does not happen in PowerShell for me any more with a current Node.js. I'm going to close this as resolved.

**Closed by iarna** 2016-04-15 21:38 UTC
Labels: feature-request, patch-welcome, windows

**Comment by stereokai** [comment] 2016-04-16 18:27
@iarna Thank you.

**Comment by jarruda** [comment] 2017-11-21 18:10
I'm running version 5.5.1 and seeing this behavior again when running inside of the VS Code integrated terminal with powershell.

I do *not* see it when running in a native Powershell terminal.

![2017-11-21 10_09_33-test js - nodesandbox - visual studio code](https://user-images.githubusercontent.com/714104/33088970-2425e088-cea4-11e7-9ff7-c78a95da1fed.png)

**Comment by floyd-may** [comment] 2017-11-21 18:15
@jarruda I'd recommend running the sample app above that uses the `ansi` package and see what behavior you get. If you get the same behavior as your screenshot, then this probably needs to be taken to the VS Code issue tracker.
