### ISSUE TITLE
Can't install bower because of error

### ISSUE THREAD

**Issue by SuprevoNL** [npm/npm#14162] opened 2016-10-03 10:00 UTC
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

Cant seem to install bower anymore already reinstalled node and npm. Anybody got a tip?

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: 6.7.0
 - `npm config get registry` prints: registry.npmjs.org
 - Windows, OS X, or Linux?: OS X

suprevo:~ marcobrok$ sudo npm install -g bower

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marcobrok/npm-debug.log

4332 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/package.json
4333 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/index.js
4334 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/license
4335 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/readme.md
4336 verbose stack TypeError: uid must be an unsigned int
4336 verbose stack     at TypeError (native)
4336 verbose stack     at Object.fs.chown (fs.js:1190:11)
4336 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
4336 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
4336 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
4336 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4336 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
4336 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
4337 verbose cwd /Users/marcobrok/WebstormProjects/Starter/app
4338 error Darwin 14.5.0
4339 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
4340 error node v6.7.0
4341 error npm  v3.10.8
4342 error uid must be an unsigned int
4343 error If you need help, you may report this error at:
4343 error     <https://github.com/npm/npm/issues>
4344 verbose exit [ 1, true ]

**Comment by KenanY** [comment] 2016-10-03 10:44
Duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-10-03 10:44 UTC
Labels: support
