### ISSUE TITLE
Show only first level of global dependencies using `list -g`

### ISSUE THREAD

**Issue by leo** [npm/npm#15176] opened 2016-12-08 17:57 UTC
By default, `list -g` should only output the first level of global dependencies, IMHO.

```bash
npm list -g --depth=0
```

...should be...

```bash
npm list -g
```

If someone wants to see more levels, he/she can set `--depth`.

**Comment by KenanY** [comment] 2016-12-08 18:13
Perhaps a duplicate of https://github.com/npm/npm/issues/10443.

**Comment by zkat** [comment] 2016-12-09 07:28
Closing as dupe

**Closed by zkat** 2016-12-09 07:28 UTC
