### ISSUE TITLE
error on exec 'npm unpublish --force gulp-fontspider-easyhi'

### ISSUE THREAD

**Issue by JounQin** [npm/npm#12396] opened 2016-04-18 12:04 UTC
This module is a clone of *gulp-font-spider* and I want to unpublish it because the author has fixed the previous bugs.

[npm-debug.log](https://gist.github.com/anonymous/3e8fe4c347084dabffa94abc36f35ff5)
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   '--force',
1 verbose cli   'gulp-fontspider-easyhi' ]
2 info using npm@3.8.6
3 info using node@v4.4.1
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] gulp-fontspider-easyhi
6 silly unpublish thing Result {
6 silly unpublish   raw: 'gulp-fontspider-easyhi',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'gulp-fontspider-easyhi',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized gulp-fontspider-easyhi
9 silly gentlyRm /Users/JounQin/.npm/gulp-fontspider-easyhi is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/JounQin/.npm/gulp-fontspider-easyhi
11 silly vacuum-fs purging /Users/JounQin/.npm/gulp-fontspider-easyhi
12 silly vacuum-fs quitting because other entries in /Users/JounQin/.npm
13 silly mapToRegistry name gulp-fontspider-easyhi
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry data Result {
16 silly mapToRegistry   raw: 'gulp-fontspider-easyhi',
16 silly mapToRegistry   scope: null,
16 silly mapToRegistry   name: 'gulp-fontspider-easyhi',
16 silly mapToRegistry   rawSpec: '',
16 silly mapToRegistry   spec: 'latest',
16 silly mapToRegistry   type: 'tag' }
17 silly mapToRegistry uri https://registry.npmjs.org/gulp-fontspider-easyhi
18 verbose get GET as part of write; not caching result
19 verbose request uri https://registry.npmjs.org/gulp-fontspider-easyhi?write=true
20 verbose request no auth needed
21 info attempt registry request try #1 at 8:08:59 PM
22 verbose request using bearer token for auth
23 verbose request id 3e54d30d0042f680
24 http request GET https://registry.npmjs.org/gulp-fontspider-easyhi?write=true
25 http 200 https://registry.npmjs.org/gulp-fontspider-easyhi?write=true
26 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 verbose headers   etag: '"2I3EQCF92RGVKZRIYM77U9HPV"',
26 verbose headers   'content-type': 'application/json',
26 verbose headers   'content-encoding': 'gzip',
26 verbose headers   'cache-control': 'max-age=0',
26 verbose headers   'transfer-encoding': 'chunked',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Mon, 18 Apr 2016 12:09:00 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-lhr6323-LHR',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1460981339.774593,VS0,VE328',
26 verbose headers   vary: 'Accept-Encoding' }
27 silly get cb [ 200,
27 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
27 silly get     etag: '"2I3EQCF92RGVKZRIYM77U9HPV"',
27 silly get     'content-type': 'application/json',
27 silly get     'content-encoding': 'gzip',
27 silly get     'cache-control': 'max-age=0',
27 silly get     'transfer-encoding': 'chunked',
27 silly get     'accept-ranges': 'bytes',
27 silly get     date: 'Mon, 18 Apr 2016 12:09:00 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-lhr6323-LHR',
27 silly get     'x-cache': 'MISS',
27 silly get     'x-cache-hits': '0',
27 silly get     'x-timer': 'S1460981339.774593,VS0,VE328',
27 silly get     vary: 'Accept-Encoding' } ]
28 verbose get saving gulp-fontspider-easyhi to /Users/JounQin/.npm/registry.npmjs.org/gulp-fontspider-easyhi_3Fwrite_3Dtrue/.cache.json
29 verbose correctMkdir /Users/JounQin/.npm correctMkdir not in flight; initializing
30 info unpublish No version specified, removing all
31 verbose request uri https://registry.npmjs.org/gulp-fontspider-easyhi/-rev/8-1c2fe473e940b8682b736c84537c31d3
32 verbose request sending authorization for write operation
33 info attempt registry request try #1 at 8:09:00 PM
34 verbose request using bearer token for auth
35 http request DELETE https://registry.npmjs.org/gulp-fontspider-easyhi/-rev/8-1c2fe473e940b8682b736c84537c31d3
36 http 400 https://registry.npmjs.org/gulp-fontspider-easyhi/-rev/8-1c2fe473e940b8682b736c84537c31d3
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '17',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Mon, 18 Apr 2016 12:09:01 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-lhr6327-LHR',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1460981340.739960,VS0,VE911',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating /Users/JounQin/.npm/registry.npmjs.org/gulp-fontspider-easyhi on DELETE
39 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/gulp-fontspider-easyhi/-rev/8-1c2fe473e940b8682b736c84537c31d3
39 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
39 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
39 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
39 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
39 verbose stack     at emitTwo (events.js:87:13)
39 verbose stack     at Request.emit (events.js:172:7)
39 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
39 verbose stack     at emitOne (events.js:82:20)
39 verbose stack     at Request.emit (events.js:169:7)
39 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
40 verbose statusCode 400
41 verbose pkgid gulp-fontspider-easyhi
42 verbose cwd /local/GitHub/gulp-font-spider
43 error Darwin 15.5.0
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "--force" "gulp-fontspider-easyhi"
45 error node v4.4.1
46 error npm  v3.8.6
47 error code E400
48 error Registry returned 400 for DELETE on https://registry.npmjs.org/gulp-fontspider-easyhi/-rev/8-1c2fe473e940b8682b736c84537c31d3
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment] 2016-04-18 13:18
@JounQin I think this is caused by [the recent change in unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy).

**Comment by othiym23** [comment] 2016-04-18 20:47
@KenanY is correct – due to the changes in the unpublish policy, you'll need to contact support@npmjs.com if you want to unpublish a package or version of a package. Closing as redirected to support.

**Closed by othiym23** 2016-04-18 20:47 UTC
Labels: registry, support
