### ISSUE TITLE
Getting issue during npm install

### ISSUE THREAD

**Issue by krishnakumarsingh** [npm/npm#16629] opened 2017-05-15 13:30 UTC
```
Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\528690\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0

npm ERR! shasum check failed for C:\Users\528690\AppData\Local\Temp\npm-11304-165c6618\registry.npmjs.org\node-notifier\-\node-notifier-4.6.1.tgz
npm ERR! Expected: 056d14244f3dcc1ceadfe68af9cff0c5473a33f3
npm ERR! Actual:   4dd3ef5afcf0046a900b55b56338e407f50fe9d2
npm ERR! From:     http://registry.npmjs.org/node-notifier/-/node-notifier-4.6.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\528690\AppData\Roaming\npm-cache\_logs\2017-05-15T13_28_15_181Z-debug.log
```

**Comment by legodude17** [comment] 2017-05-16 18:51
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Comment by krishnakumarsingh** [comment] 2017-05-17 06:00
Thanks legodude, I will check that and try again after reinstall npm.

**Closed** 2017-06-16 21:52 UTC
Labels: bot-closed, shasum, support
