### ISSUE TITLE
Atom package publication

### ISSUE THREAD

**Issue by ValentinLaTortue** [npm/npm#16317] opened 2017-04-12 02:19 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to publish my first atom package but when I execute the command it gives me an error message
#### How can the CLI team reproduce the problem?

Tell me what to install/change to make it work.

Here is the error message the console is giving me:

npm ERR! Linux 4.8.0-44-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "version" "minor" "-m" "Prepare %s release"
npm ERR! node v4.4.5
npm ERR! npm v3.10.5

npm ERR! Git working directory not clean.
npm ERR! M README.md
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /home/valentin/github/quick-comment/npm-debug.log

And here the log file: [npm-debug.txt](https://github.com/npm/npm/files/915238/npm-debug.txt)

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: 4.2.6
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2017-04-12 11:17
@ValentinLaTortue I'm gonna close this as a duplicate of https://github.com/npm/npm/issues/16208, which is also an issue by you. Opening duplicate tickets could be considered spam so I would advise against it.

**Closed by KenanY** 2017-04-12 11:17 UTC
Labels: git, support
