### ISSUE TITLE
Can't remove or update global packages

### ISSUE THREAD

**Issue by anthonybrown** [npm/npm#16941] opened 2017-06-03 09:11 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can't remove global packages or update global packages with:
`npm i -g outdated --depth=0` doesn't seem to work anymore.

Here is my debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.0.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '-g',
1 verbose cli   'remove',
1 verbose cli   'stylus' ]
2 info using npm@5.0.2
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly install loadIdealTree
7 silly install cloneCurrentTreeToIdealTree
8 silly install loadShrinkwrap
9 silly uninstall loadAllDepsIntoIdealTree
10 silly install loadAllDepsIntoIdealTree
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://github.com/npm/npm/issues>
```

#### How can the CLI team reproduce the problem?

npm -g remove <package>

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by fstock** [comment] 2017-06-03 17:06
Possible duplicate of [#16904](https://github.com/npm/npm/issues/16904)

**Comment by zkat** [comment] 2017-06-05 16:23
Closing as duplicate of https://github.com/npm/npm/issues/16738

**Closed as completed by zkat** 2017-06-05 16:23 UTC
Labels: npm5
