### ISSUE TITLE
You should probably upgrade to a newer version of node as we can't make any promises that npm will work with this version.

### ISSUE THREAD

**Issue by advanceddeveloper** [npm/npm#20477] opened 2018-05-01 20:53 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other

#### What's going wrong?

Every time I install some package, I get warning:

```console
> npm install <some_package>
npm WARN npm npm does not support Node.js v10.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
```

Package itself installs properly and no errors, and works fine, but the message is very disturbing. My node is latest and npm is latest version, but npm is telling me that I should update node...??? To what version? Node.js is v10.0.0 latest version, so I have no idea what npm wants from me.

Thanks.

#### How can the CLI team reproduce the problem?

Run npm install.

### supporting information:

 - `npm -v` prints: 5.8.0
 - `node -v` prints: v10.0.0
 - `npm config get registry` prints: `"npm WARN npm npm does not support Node.js v10.0.0\nnpm WARN npm You should probably upgrade to a newer version of node as we\nnpm WARN npm can't make any promises that npm will work with this version.\nnpm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.\nnpm WARN npm You can find the latest version at https://nodejs.org/\nhttps://registry.npmjs.org/"`
 - Windows, OS X/macOS, or Linux?: windows 8.1 64-bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment] 2018-05-01 20:54
Duplicate of https://github.com/npm/npm/issues/20433.

**Closed as completed by kenany** 2018-05-01 20:54 UTC
Labels: support

**Comment by advanceddeveloper** [comment] 2018-05-01 20:59
Oops, sorry for duplicate.
