### ISSUE TITLE
error with npm install -g adapt-cli command.Any solution on this?

### ISSUE THREAD

**Issue by AmitGolhar** [npm/npm#10921] opened 2015-12-22 09:27 UTC
C:\Users\amitg>npm install -g adapt-cli
npm ERR! git clone git://github.com/adaptlearning/download.git Cloning into bare
repository 'C:\Users\amitg\AppData\Roaming\npm-cache_git-remotes\git-github-co
m-adaptlearning-download-git-2681a17e'...
npm ERR! git clone git://github.com/adaptlearning/download.git fatal: unable to
connect to github.com:
npm ERR! git clone git://github.com/adaptlearning/download.git github.com[0: 192
.30.252.129]: errno=Invalid argument
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\amitg\App
Data\Roaming\npm-cache_git-remotes\git-github-com-adaptlearning-download-git-26
81a17e'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR! at ChildProcess.exithandler (child_process.js:648:15)
npm ERR! at ChildProcess.emit (events.js:98:17)
npm ERR! at maybeClose (child_process.js:756:16)
npm ERR! at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "adapt-cli"
npm ERR! cwd C:\Users\amitg
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

**Comment by KenanY** [comment] 2015-12-22 19:00
@AmitGolhar This looks like an issue with your internet connection, no?:

```
unable to connect to github.com
```

(also note that `npm@1` is very old at this point, so you may want to consider [updating](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows))

**Comment by annebione** [comment] 2015-12-23 08:30
If it's not your internet connection, it's an issue with git. Install git, sign in to your account and make sure you have no auth issues.

**Comment by KenanY** [comment] 2016-05-15 17:43
@AmitGolhar Are you still seeing this issue?

**Comment by mict-ss** [comment] 2016-05-20 09:32
I am getting a similar error on installation of this package. Checked for any firewall filtering, no traffic is blocked.
npm version is 1.3.6
system: CentOS 6.7

[root@localhost]# npm install -g adapt-cli
npm http GET https://registry.npmjs.org/adapt-cli
npm http 304 https://registry.npmjs.org/adapt-cli
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/q-io
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/speakingurl
npm http GET https://registry.npmjs.org/url-join/0.0.1
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/bower-endpoint-parser
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/prompt
npm http 304 https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/bower-endpoint-parser
npm http 304 https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/q-io
npm http 200 https://registry.npmjs.org/speakingurl
npm http 304 https://registry.npmjs.org/url-join/0.0.1
npm ERR! git clone git://github.com/adaptlearning/download.git Initialized empty Git repository in /root/.npm/_git-remotes/git-github-com-adaptlearning-download-git-2681a17e/
npm ERR! git clone git://github.com/adaptlearning/download.git
npm ERR! git clone git://github.com/adaptlearning/download.git github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! git clone git://github.com/adaptlearning/download.git fatal: unable to connect a socket (Connection timed out)
npm ERR! Error: Command failed: github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! fatal: unable to connect a socket (Connection timed out)
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "adapt-cli"
npm ERR! cwd /home/adapt_authoring
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/adapt_authoring/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment] 2016-06-02 15:01
@mict-ss Note that `npm@1.3` is years old and no longer supported. Also, as I said in my comment months ago, this is an issue with your internet connection and not with `npm`. Your connnection to `github.com` is timing out. Usually, this is caused by a proxy or firewall.

**Comment by KenanY** [comment] 2016-06-29 01:58
Closing as not an issue with `npm`. If you still believe `npm` to be at fault here, I can easily reopen.

**Closed by KenanY** 2016-06-29 01:58 UTC
Labels: support
