### ISSUE TITLE
Windshaft-cartodb npm faile to install

### ISSUE THREAD

**Issue by nicoali** [npm/npm#14390] opened 2016-10-23 17:56 UTC
- [x ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

carto@carto-desktop:~/Windshaft-cartodb$ npm install
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'aws-sign2' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'lodash._basetostring' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'lodash._basetostring' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'lodash._basetostring' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'lodash._basetostring' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'lodash._basetostring' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'lodash._basetostring' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints:v4.0.0
 - `node -v` prints: v0.10.26
 -  Linux?: Ubuntu 16.04 on RPI3

**Comment by watilde** [comment] 2016-10-25 22:16
I still need more time to find the actual bug, but this behavior comes from this breaking change https://github.com/npm/npm/pull/14327

**Comment by zkat** [comment] 2016-10-27 22:30
Closing at duplicate of #14427

**Closed by zkat** 2016-10-27 22:30 UTC
