### ISSUE TITLE
npm outdated reports "wrong" wanted version

### ISSUE THREAD

**Issue by doberkofler** [npm/npm#10687] opened 2015-12-04 09:09 UTC
I'm currently using npm 3.5.0 and over the last couple of weeks I've noticed that `npm outdated` on occasion reports some strange wanted versions. In the following example:
```
D:\MyDev\ljs_app\trunk\periscope\build>npm outdated
Package              Current  Wanted  Latest  Location
babel-preset-es2015   6.1.18   6.2.4  6.1.18  periscope
yargs                 3.30.0  3.31.0  3.30.0  periscope
```
It seems as if babel-preset-es2015@6.2.4 and yargs@3.31.0 would be wanted but actually those versions do not (yet) exist and the `package.json` file specifies them as follows:
```
{
  "name": "periscope",
  "license": "MIT",
  "version": "0.0.0",
  "repository": {},
  "dependencies": {
    "babel-preset-es2015": "^6.1.18",
    "yargs": "^3.30.0"
  }
}
```
Something seems wrong to me!

**Comment by othiym23** [comment] 2015-12-04 16:42
Babel has already released a new version since you filed this issue(!), so let's look at `yargs`, which I use on one of my projects as well:

```
bauchelain% npm outdated -l
Package              Current  Wanted  Latest  Location  Package Type
babel-cli              6.2.0  6.3.13  6.3.13  packard   devDependencies
babel-polyfill         6.2.0  6.3.13  6.3.13  packard   dependencies
babel-preset-es2015   6.1.18  6.3.13  6.3.13  packard   devDependencies
bluebird               3.0.5   3.0.6   3.0.6  packard   dependencies
yargs                 3.30.0  3.31.0  3.30.0  packard   dependencies
```
```
bauchelain% npm dist-tags ls yargs
latest: 3.30.0
next: 3.31.0
```

So "latest" is telling you a true story here, which is that the latest version of `yargs` is 3.30.0. What's probably not clear enough from context is that "latest" has a specific meaning here, which is _the version of yargs assigned to the `latest` [`dist-tag`](https://docs.npmjs.com/cli/dist-tag)_. You don't have to think about the fact that "latest" is a tag very often as an npm user, but an increasing number of developers are using release channels for their npm projects, which means that they're frequently publishing the newest versions of their packages to a dist-tag other than `latest` to let them get additional testing before becoming `latest`.

There are three ways of looking at packages that are interesting here:

1. What's marked as latest?
2. What's the most recently published version?
3. What's the maximum semver?

Depending on which of the three is your intuition, the `Wanted` column is going to make more or less sense to you, because it applies any applicable semver (e.g. from your `package.json`) to the full, sorted list of published versions and chooses the maximum version that satisfies that semver range. In the case of yargs, `Wanted` is saying that the maximum published version of yargs that satisfies the semver range in your `package.json` would be `yargs@3.31.0`, but `Latest` is telling you that `yargs@3.30.0` is what's tagged as `latest`, so that's what would be installed.

"Wanted" is not the best term for that column heading, but I haven't herd a term that's less confusing ("Newest"? "Max satisfying"?). I think maybe the order of the columns should be swapped, so that it becomes something like "Current Latest Wanted Location", but that still doesn't make very clear to people what the underlying machinery is. For now, people need to read [the help](https://docs.npmjs.com/cli/outdated) or read an explanation like this one before they get it. I think the docs probably need to include a more nuanced explanation of what the command is doing, but the feature is behaving as designed, so I'm going to close this (and make some tweaks to the docs).

**Closed by othiym23** 2015-12-04 16:42 UTC
Labels: support

**Comment by doberkofler** [comment] 2015-12-07 07:35
@othiym23 Thanks a lot for the extensive explanation.
