### ISSUE TITLE
npm ls -g takes a really long time

### ISSUE THREAD

**Issue by legodude17** [npm/npm#13727] opened 2016-08-22 17:11 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm ls -g` is taking about 11 - 12s on my machine.
#### How can the CLI team reproduce the problem?
Install some modules globally, run `time npm ls -g`.

### supporting information:

 - `npm -v` prints: 3.10.5
 - `node -v` prints:  6.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Italy
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-08-22 17:19
ref. https://github.com/npm/npm/issues/6507

**Comment by legodude17** [comment] 2016-08-22 17:20
Full result of `time npm ls -g`: [result.txt](https://gist.github.com/legodude17/fb8ec92d90e1ce502246a6d3a3bde663).

**Comment by othiym23** [comment] 2016-09-16 21:07
Closing as a duplicate of #6507. Thanks for your time!

**Closed by othiym23** 2016-09-16 21:07 UTC
Labels: bug, performance
