### ISSUE TITLE
npm@5.0.0 cannot uninstall -g npm5

### ISSUE THREAD

**Issue by dpogue** [npm/npm#16739] opened 2017-05-26 16:55 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

After updating `npm` to v5, I'm unable to uninstall the `npm5` package.

#### How can the CLI team reproduce the problem?

<details>
<summary>Background info/commands</summary>

```
dpogue@pripyat:~$ npm --version
4.6.1


dpogue@pripyat:~$ npm ls -g --depth 0
/usr/local/lib
├── cordova@7.0.1
├── ios-deploy@1.9.1
├── ios-sim@5.0.13
├── npm@4.6.1
└── npm5@5.0.0-beta.64


dpogue@pripyat:~$ npm install -g npm@next
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
- asap@2.0.5 node_modules/npm/node_modules/asap
- once@1.3.3 node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/node_modules/once
- os-homedir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-homedir
- os-tmpdir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-tmpdir
- osenv@0.1.4 node_modules/npm/node_modules/nopt/node_modules/osenv
- pseudomap@1.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap
- yallist@2.0.0 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist
- lru-cache@4.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache
- spdx-exceptions@1.0.4 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-exceptions
- spdx-license-ids@1.2.0 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-license-ids
- normalize-git-url@3.0.2 node_modules/npm/node_modules/normalize-git-url
- realize-package-specifier@3.0.3 node_modules/npm/node_modules/realize-package-specifier
/usr/local/lib
└─┬ npm@5.0.0 
  ├─┬ cacache@9.2.5 
  │ ├── glob@7.1.2  deduped
  │ ├── lru-cache@4.0.2  deduped
  │ ├── promise-inflight@1.0.1  deduped
  │ ├── ssri@4.1.3  deduped
  │ └── y18n@3.2.1 
  ├─┬ columnify@1.5.4
  │ └── wcwidth@1.0.1 
  ├── detect-indent@5.0.0 
  ├─┬ dezalgo@1.0.3
  │ └── asap@2.0.5 
  ├─┬ fstream-npm@1.2.1 
  │ └─┬ fstream-ignore@1.0.5
  │   └─┬ minimatch@3.0.4 
  │     └── brace-expansion@1.1.7 
  ├─┬ glob@7.1.2 
  │ └─┬ minimatch@3.0.4 
  │   └── brace-expansion@1.1.7 
  ├─┬ init-package-json@1.10.1
  │ ├── glob@7.1.2  deduped
  │ └── npm-package-arg@5.0.1  deduped
  ├─┬ lru-cache@4.0.2 
  │ ├── pseudomap@1.0.2 
  │ └── yallist@2.1.2 
  ├─┬ mississippi@1.3.0
  │ ├── end-of-stream@1.4.0 
  │ ├─┬ pump@1.0.2
  │ │ └── end-of-stream@1.4.0  deduped
  │ └─┬ stream-each@1.2.0
  │   └── end-of-stream@1.4.0  deduped
  ├─┬ node-gyp@3.6.1 
  │ ├── glob@7.1.2  deduped
  │ ├─┬ minimatch@3.0.4 
  │ │ └── brace-expansion@1.1.7 
  │ └── npmlog@4.1.0  deduped
  ├── npm-package-arg@5.0.1 
  ├─┬ npm-registry-client@8.3.0 
  │ ├── npm-package-arg@5.0.1  deduped
  │ ├── npmlog@4.1.0  deduped
  │ └── ssri@4.1.3  deduped
  ├── npmlog@4.1.0 
  ├─┬ pacote@2.7.21 
  │ ├── cacache@9.2.5  deduped
  │ ├── glob@7.1.2  deduped
  │ ├── lru-cache@4.0.2  deduped
  │ ├─┬ make-fetch-happen@2.4.9 
  │ │ ├─┬ agentkeepalive@3.1.0 
  │ │ │ └─┬ humanize-ms@1.2.1 
  │ │ │   └── ms@2.0.0 
  │ │ ├── cacache@9.2.5  deduped
  │ │ ├── http-cache-semantics@3.7.3 
  │ │ ├─┬ http-proxy-agent@1.0.0 
  │ │ │ ├─┬ agent-base@2.0.1 
  │ │ │ │ ├── extend@3.0.1  deduped
  │ │ │ │ └── semver@5.0.3 
  │ │ │ ├─┬ debug@2.6.8 
  │ │ │ │ └── ms@2.0.0 
  │ │ │ └── extend@3.0.1 
  │ │ ├─┬ https-proxy-agent@1.0.0 
  │ │ │ ├─┬ agent-base@2.0.1 
  │ │ │ │ ├── extend@3.0.1  deduped
  │ │ │ │ └── semver@5.0.3 
  │ │ │ ├─┬ debug@2.6.8 
  │ │ │ │ └── ms@2.0.0 
  │ │ │ └── extend@3.0.1 
  │ │ ├── lru-cache@4.0.2  deduped
  │ │ ├─┬ node-fetch-npm@2.0.1 
  │ │ │ ├─┬ encoding@0.1.12 
  │ │ │ │ └── iconv-lite@0.4.17 
  │ │ │ ├─┬ json-parse-helpfulerror@1.0.3 
  │ │ │ │ └── jju@1.3.0 
  │ │ │ └── safe-buffer@5.0.1  deduped
  │ │ ├── promise-retry@1.1.1  deduped
  │ │ ├─┬ socks-proxy-agent@2.1.0 
  │ │ │ ├─┬ agent-base@2.0.1 
  │ │ │ │ ├── extend@3.0.1  deduped
  │ │ │ │ └── semver@5.0.3 
  │ │ │ ├── extend@3.0.1 
  │ │ │ └─┬ socks@1.1.10 
  │ │ │   ├── ip@1.1.5 
  │ │ │   └── smart-buffer@1.1.15 
  │ │ └── ssri@4.1.3  deduped
  │ ├─┬ minimatch@3.0.4 
  │ │ └─┬ brace-expansion@1.1.7 
  │ │   ├── balanced-match@0.4.2 
  │ │   └── concat-map@0.0.1 
  │ ├── npm-package-arg@5.0.1  deduped
  │ ├─┬ npm-pick-manifest@1.0.3 
  │ │ └── npm-package-arg@5.0.1  deduped
  │ ├── promise-inflight@1.0.1  deduped
  │ ├─┬ promise-retry@1.1.1 
  │ │ └── err-code@1.1.2 
  │ ├─┬ protoduck@4.0.0 
  │ │ └── genfun@4.0.1 
  │ ├── safe-buffer@5.0.1  deduped
  │ ├── ssri@4.1.3  deduped
  │ ├─┬ tar-fs@1.15.2 
  │ │ ├─┬ pump@1.0.2 
  │ │ │ └── end-of-stream@1.4.0 
  │ │ └── tar-stream@1.5.4  deduped
  │ └─┬ tar-stream@1.5.4 
  │   ├── bl@1.2.1 
  │   ├── end-of-stream@1.4.0 
  │   └── xtend@4.0.1 
  ├── promise-inflight@1.0.1 
  ├─┬ read@1.0.7
  │ └── mute-stream@0.0.7 
  ├─┬ read-package-json@2.0.5
  │ └── glob@7.1.2  deduped
  ├─┬ request@2.81.0
  │ ├── extend@3.0.1 
  │ ├─┬ form-data@2.1.4 
  │ │ └── mime-types@2.1.15  deduped
  │ ├─┬ har-validator@4.2.1
  │ │ └── ajv@4.11.8 
  │ ├─┬ http-signature@1.1.1
  │ │ ├─┬ jsprim@1.4.0 
  │ │ │ └── assert-plus@1.0.0 
  │ │ └─┬ sshpk@1.13.0 
  │ │   └── getpass@0.1.7 
  │ └─┬ mime-types@2.1.15 
  │   └── mime-db@1.27.0 
  ├─┬ rimraf@2.6.1
  │ └── glob@7.1.2  deduped
  ├── safe-buffer@5.0.1 
  ├─┬ sorted-union-stream@2.1.3
  │ └─┬ stream-iterate@1.2.0 
  │   └── stream-shift@1.0.0 
  ├── ssri@4.1.3 
  ├─┬ tar@2.2.1
  │ └── block-stream@0.0.9 
  ├─┬ update-notifier@2.1.0
  │ ├─┬ boxen@1.0.0
  │ │ ├── camelcase@4.1.0 
  │ │ └─┬ term-size@0.1.1
  │ │   └─┬ execa@0.4.0
  │ │     └─┬ cross-spawn-async@2.2.5
  │ │       └── lru-cache@4.0.2  deduped
  │ ├─┬ configstore@3.0.0
  │ │ └── write-file-atomic@1.3.4 
  │ └─┬ latest-version@3.1.0 
  │   └─┬ package-json@4.0.1 
  │     ├─┬ registry-auth-token@3.3.0 
  │     │ ├── rc@1.2.1 
  │     │ └── safe-buffer@5.0.1 
  │     └─┬ registry-url@3.1.0
  │       └── rc@1.2.1 
  ├─┬ validate-npm-package-license@3.0.1
  │ ├─┬ spdx-correct@1.0.2
  │ │ └── spdx-license-ids@1.2.2 
  │ └── spdx-expression-parse@1.0.4 
  └── write-file-atomic@2.1.0 


dpogue@pripyat:~$ npm ls -g --depth 0
/usr/local/lib
├── cordova@7.0.1
├── ios-deploy@1.9.1
├── ios-sim@5.0.13
├── npm@5.0.0
└── npm5@5.0.0-beta.64


dpogue@pripyat:~$ npm --version
5.0.0
```
</details>

```
dpogue@pripyat:~$ npm uninstall -g npm5
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dpogue/.npm/_logs/2017-05-26T16_48_26_385Z-debug.log
```

#### Log File Contents
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'npm5' ]
2 info using npm@5.0.0
3 info using node@v7.10.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 silly install loadIdealTree
7 silly install cloneCurrentTreeToIdealTree
8 silly install loadShrinkwrap
9 silly uninstall loadAllDepsIntoIdealTree
10 silly install loadAllDepsIntoIdealTree
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://github.com/npm/npm/issues>
```

**Comment by zkat** [comment] 2017-05-26 17:09
Closing as a duplicate of #16738.

Thanks!

**Closed by zkat** 2017-05-26 17:09 UTC

**Comment by danthegoodman** [comment] 2017-05-26 21:04
@dpogue A temporary workaround is to install the package globally again and then it will be uninstallable.

**Comment by lednhatkhanh** [comment] 2017-05-29 04:04
Got the same issue when trying to uninstall yarn and after reinstall `yarn`, it can be uninstalled normally, thanks @danthegoodman

**Comment by hantsy** [comment] 2017-05-31 02:43
Got the same issue,  thanks @danthegoodman
