### ISSUE TITLE
npm uninstall -g produces error

### ISSUE THREAD

**Issue by akskos** [npm/npm#17358] opened 2017-06-21 05:15 UTC
I'm opening this issue because npm is producing an incorrect uninstall.

When I run `npm uninstall -g nodemon` I get the following error

```
Unhandled rejection Error: Argument #2: Expected string but got nullf78d40a338f9
    at addDependency (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:463:5
    at /home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/akseli/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/akseli/.npm/_logs/2017-06-20T18_44_55_224Z-debug.log
```

The debug log file contains following:
0 info it worked if it ends with ok
1 verbose cli [ '/home/akseli/.nvm/versions/node/v7.9.0/bin/node',
1 verbose cli   '/home/akseli/.nvm/versions/node/v7.9.0/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'nodemon' ]
2 info using npm@5.0.3
3 info using node@v7.9.0
4 verbose npm-session fe67f78d40a338f9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>

**Comment by kenany** [comment] 2017-06-21 15:09
Duplicate of https://github.com/npm/npm/issues/16738.

**Closed as completed by kenany** 2017-06-21 15:09 UTC
Labels: npm5
