### ISSUE TITLE
npm install -g ionic cordova error

### ISSUE THREAD

**Issue by silu44** [npm/npm#15122] opened 2016-12-02 18:43 UTC
#### I'm opening this issue because:

  -  npm is producing an incorrect install.
 

#### What's going wrong?
 C:\Users\Gtech>npm install -g ionic cordova
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/insight
npm http GET https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/cordova-common
npm http GET https://registry.npmjs.org/cordova-lib/6.4.0
npm http 304 https://registry.npmjs.org/insight
npm http 304 https://registry.npmjs.org/nopt/3.0.1
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/underscore/1.7.0
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http 304 https://registry.npmjs.org/cordova-lib/6.4.0
npm http 304 https://registry.npmjs.org/cordova-common
npm ERR! Error: No compatible version found: update-notifier@'^0.5.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8
","0.1.9","0.1.10","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.5.
0","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (C:\Users\Gtech\AppData\Roaming\npm\node_mod
ules\npm\lib\cache.js:719:10)
npm ERR!     at C:\Users\Gtech\AppData\Roaming\npm\node_modules\npm\lib\cache.js
:641:10
npm ERR!     at saved (C:\Users\Gtech\AppData\Roaming\npm\node_modules\npm\node_
modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:111:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gtech\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cor
dova"
npm ERR! cwd C:\Users\Gtech
npm ERR! node -v v7.2.0
npm ERR! npm -v 1.2.32

**Comment by helio-frota** [comment] 2016-12-02 18:49
looks like a problem with Mac ?
2 hours ago I get it installed on linux:
https://github.com/npm/npm/issues/13375#issuecomment-264496618

**Comment by Charlotteis** [comment] 2016-12-02 18:49
Hey @silu44!

You're using an outdated version of `npm`, which is no longer supported by npm!
Could you try upgrading (`npm install -g npm@latest`) and trying to install ionic and cordova after that? If it still doesn't work, then we can start working on a solution knowing the problem isn't an outdated tool.

**Comment by KenanY** [comment] 2016-12-02 18:59
Closing since this specific issue will surely be fixed by newer versions of `npm`, which support the `^` semver range. It's nevertheless interesting to see Node.js v7 (very new) and `npm@1.2` (very old) together in one place somehow :)

**Closed by KenanY** 2016-12-02 18:59 UTC

**Comment by silu44** [comment] 2016-12-03 10:46
Here is the same issue with 32bit version and node v6.9.1 LTS

C:\Users\Gtech>npm install -g ionic cordova
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http GET https://registry.npmjs.org/cordova-common
npm http GET https://registry.npmjs.org/insight
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/cordova-lib/6.4.0
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/cordova-common
npm http 304 https://registry.npmjs.org/insight
npm ERR! Error: No compatible version found: update-notifier@'^0.5.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8
","0.1.9","0.1.10","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.5.
0","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (C:\Users\Gtech\AppData\Roaming\npm\node_mod
ules\npm\lib\cache.js:719:10)
npm ERR!     at C:\Users\Gtech\AppData\Roaming\npm\node_modules\npm\lib\cache.js
:641:10
npm ERR!     at saved (C:\Users\Gtech\AppData\Roaming\npm\node_modules\npm\node_
modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Gtech\\
AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic
" "cordova"
npm ERR! cwd C:\Users\Gtech
npm ERR! node -v v6.9.1
npm ERR! npm -v 1.2.32
npm http 304 https://registry.npmjs.org/nopt/3.0.1
npm http 304 https://registry.npmjs.org/underscore/1.7.0
npm http 304 https://registry.npmjs.org/cordova-lib/6.4.0
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/ionic/app-generators/0.0.3
npm http 404 https://registry.npmjs.org/ionic/app-generators/0.0.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Gtech\npm-debug.log
npm ERR! not ok code 0

**Comment by helio-frota** [comment] 2016-12-03 11:38
npm http **404** https://registry.npmjs.org/ionic/app-generators/0.0.3
```
curl https://registry.npmjs.org/ionic/app-generators/0.0.3
{"error":"not_found","reason":"missing"}
```

**Comment by KenanY** [comment] 2016-12-03 16:06
@silu44 You are still using an extremely old version of `npm`.
