### ISSUE TITLE
Max call stack size exceeded on publish

### ISSUE THREAD

**Issue by llaughlin** [npm/npm#9658] opened 2015-09-18 16:22 UTC
Error on publish (has been working fine for days)

```
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.4

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/logan.laughlin/Repo/GitHub/serenity/npm-debug.log
```

Log file: https://gist.github.com/llaughlin/84fb5866b0735e63bdbc

**Comment by othiym23** [comment] 2015-09-18 16:36
Closing as a duplicate of #9224, which is the tracking issue for this problem, which we're having a tough time finding a reliable repro case for (whatever's going on, it's environment-specifi). Thanks for the gist! It's useful to know what npm was doing when it died.

**Closed by othiym23** 2015-09-18 16:36 UTC
