### ISSUE TITLE
NPM not updating on MAC OS X 

### ISSUE THREAD

**Issue by vikram1707** [npm/npm#14273] opened 2016-10-13 14:21 UTC
I am trying to update npm by issuing sudo npm install -g npm@3.10.7
OS X 10.10.5
node -v 4.6.0
node 2.X.X

here is gist for npm log https://gist.github.com/vikram1707/9e7bc1c265c018d79cbb0e2fa4d48742

**Comment by zkat** [comment] 2016-12-02 19:37
closing as duplicate of https://github.com/npm/npm/issues/12526 and possibly https://github.com/npm/npm/issues/14641

**Closed by zkat** 2016-12-02 19:37 UTC
