### ISSUE TITLE
Windows 10 Issue while installing Ionic

### ISSUE THREAD

**Issue by rkumar670** [npm/npm#9498] opened 2015-09-05 12:58 UTC
C:\Users\Ansh-PC>npm install -g ionic

npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bundled package wasn't found in unpacked tree

**Comment by Fenmingyu** [comment] 2015-09-05 16:20
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-6472-65648c9e\registry.npmjs.org\ionic\-\ionic-1.6.4.tgz
npm ERR! Expected: 2c0cd94c4316cab206796e44fe67565bf4b883a0
npm ERR! Actual:   dc6b364173983100ac531bc446fe32b7e95ac2f5
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.6.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\fenmingyu-github\ionic-starter-oauth\npm-debug.log

**Comment by tvsijin** [comment] 2015-09-06 03:34
npm ERR! tar.unpack untar error C:\Users\Sijin\AppData\Local\Temp\npm-4936-3228e0da\registry.npmjs.org\tough-cookie\-\tough-cookie-2.0.0.tgz
npm ERR! tar.unpack untar error C:\Users\Sijin\AppData\Local\Temp\npm-4936-3228e0da\registry.npmjs.org\request\-\request-2.9.203.tgz
npm ERR! tar.unpack untar error C:\Users\Sijin\AppData\Local\Temp\npm-4936-3228e0da\registry.npmjs.org\liftoff\-\liftoff-0.12.1.tgz
npm ERR! tar.unpack untar error C:\Users\Sijin\AppData\Local\Temp\npm-4936-3228e0da\registry.npmjs.org\plist\-\plist-1.1.0.tgz
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sijin\npm-debug.log

**Comment by bineeshmvarghese** [comment] 2015-09-26 17:20
Solution

Follow the steps
1. Install all necessary dependencies.
http://ionicframework.com/docs/guide/installation.html
2. Uninstall node.js from PC if already installed
3. Restart PC
4. Download and Install node.js (MSI Installer) from http://nodejs.org/dist/v0.10.38/ for x86 or http://nodejs.org/dist/v0.10.38/x64/ for x64
5. Right-click Command prompt, and then click Run as administrator.
6. Install Cordova using the command: npm install -g cordova
7. Finally install Ionic Framework using the command: npm install -g ionic
8. Reinstall nod.js http://nodejs.org/dist/v0.12.7/ for x86 or http://nodejs.org/dist/v0.12.7/x64/ for x64

Done!

**Comment by zkat** [comment] 2016-12-09 00:54
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:54 UTC
Labels: support

**Comment by taslimwaris** [comment] 2017-10-23 09:41
1.I had downloaded node js form https://nodejs.org/en/ 
  6.11.4 LTS
  and install =>Done
2. run npm install -g cordova =>done
3.run  npm install -g ionic => gives error::

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\ionic\node_modules\fsevents):   
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"win32","arch":"x64"})

**Comment by MadaraPremawardhana** [comment] 2017-11-04 04:14
C:\WINDOWS\system32>npm install -g ionic
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz.278925865' -> 'C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz'
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz.592620038' -> 'C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz'
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ionic\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz.416716698
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz.416716698' -> 'C:\Users\User\AppData\Local\Temp\npm-7048-0e484565\registry.npmjs.org\pseudomap\-\pseudomap-1.0.2.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by himanshurajputx** [comment] 2018-01-08 06:06
all error is coming.used latest node version.
please used node version 7.0 to 8.9. 

downloads msi file https://nodejs.org/download/release/v7.7.4/
