### ISSUE TITLE
3 issues / undocumented breaking changes we encountered while upgarding npm to v5.0.1 in homebrew 

### ISSUE THREAD

**Issue by chrmoritz** [npm/npm#16916] opened 2017-06-02 12:59 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues: no
 
 While upgrading npm from npm@4 to npm@5 in the `node` Homebrew formula over at https://github.com/Homebrew/homebrew-core/pull/14085 we encountered 3 undocumented breaking changes in npm@5 of which the last 2 are more or less in a grey area.
I decided to report them here anyway, so that you could make your own assessment if they are considered to be real bugs or just an unsupported usage of npm. I would completely understand if you label them as a wontfix.

### ~~1. installing a package with broken file system permission fails.~~ (fixed in npm@5.0.4)
 
 ~~This issue was already reported in https://github.com/npm/npm/issues/16896 and [I joined the discussion over there with more details](https://github.com/npm/npm/issues/16896#issuecomment-305662564).~~
 
~~(`npm install easy-table@0.0.1` will fail with EACCES because npm@5 doesn't normalize permissions anymore and the 0.0.1 tarball is lacking +x on its lib folder)~~

### 2. `make install` can't be used to install npm to a prefix anymore
 
 Refs: https://github.com/Homebrew/homebrew-core/pull/14085#discussion_r119396602
Also affects [`install.sh`](https://github.com/npm/npm/blob/latest/scripts/install.sh), refs: #17036, #17058 
 
Until now (for npm <=4) [we installed npm](https://github.com/Homebrew/homebrew-core/blob/3eab65760199bbda16a1b2175829c6c30f895d7b/Formula/node.rb#L68-L69) by the the hacky way of doing a `configure --prefix=libexec/npm` followed by a `make install`.
 Because `make install` is only an alias for `node bin/npm-cli.js install -g -f ${NPMOPTS}` and the breaking `npm install <folder>` change in npm@5, `make install` would now only create a symlink to our temporary build path (which gets removed by brew automatically after installation) instead of copying npm over to the specified prefix as npm@4 used to do.
This has broken the way we had installed npm until now, and yes we know what we did was never a recommended way of installing npm. Nonetheless, the npm@5 `make install` behaviour doesn't match what you would expect from a typical `make install` call in the unix world anymore (which could be problematic, because the make targets aren't documented and this could confuse someone trying to package npm). It would be nice to have the original make install behavior available in some form (as a different make target?).
 For now we have worked around this by using a temporary version of npm extracted from the [npm registry tarball](https://registry.npmjs.org/npm/-/npm-5.0.1.tgz) to install said registry tarball [to our prefix in libexec](https://github.com/DomT4/homebrew-core/blob/a5e39a5bccc183c7af35cd9a3c0085b09b0ceb35/Formula/node.rb#L63-L69).

 ### 3. npm@5 destroys node_modules folder installed by yarn
 
 Refs: https://github.com/Homebrew/homebrew-core/pull/14125
 
 By mistake the grafana formula previously executed after a complete installation of all its dependencies with `yarn install` also a `npm install grunt-cli` (grunt-cli was already installed by yarn, but the issue also reproduces if you install something new using npm). While using npm@4 the redundant `npm install grunt-cli` command just did nothing as expected, but when run with npm@5, npm@5 removes all other dependencies from node_modules except grunt-cli and its dependencies breaking the previously (with yarn) installed modules completly.
 
 **How to reproduce:**
 1. Install yarn: `npm install -g yarn`
 2. Download and extract grafana from https://github.com/grafana/grafana/archive/v4.3.0.tar.gz somewhere
 3. Install all dependencies with `yarn install`
 4. Install grunt-cli using npm@5: `npm install grunt-cli -ddd`
 
 Output of 4.: https://gist.github.com/chrmoritz/650993b1756c0ecbce76422809c5787f
 
 **Expected result** (actual for `npm@4`): all dependencies installed with yarn are still there inside node_modules
 
 **Actual result** (`npm@5`): all dependencies installed with yarn were removed and replaced by the grunt-cli only installation
 
 This was fixed in https://github.com/Homebrew/homebrew-core/pull/14125 by dropping the redundant `npm install grunt-cli` call.
 
 See also the following brew logs containing the full verbose npm log:
 * for npm@5 `removed 929 packages and updated 16 packages in 6.735s`: https://gist.github.com/ilovezfs/5e1280cc34b2dcc2f95c8f416da98a5c#file-gistfile1-txt-L70
 * for npm@4 (no yarn deps removed): https://gist.github.com/ilovezfs/c1f95d7e5d50dd4ed0cfc9acbfff2c18#file-gistfile1-txt-L91

**Comment by alaindeurveilher** [comment] 2017-06-02 13:52
It's not that "npm install" removes the node_modules "created by yarn"; it's just that the **second** execution of "npm install" removes the node_modules folder (See #16877)

**Comment by chrmoritz** [comment] 2017-06-02 14:06
@AlainD- Don't think that this is related to your issue because:
* we don't call `npm install` (without a package specified) to install all dependencies as listed in `package.json`, we call `npm install grunt-cli` to add a specific package to the already installed ones which is quite different
* in our case not the complete `node_module` folder gets removed, just every module inside the `node_module` folder not related to grunt-cli gets removed one after each other
* also this does not reproduce if the original package installation (step 3) is done by `npm install` instead of yarn

**Comment by alaindeurveilher** [comment] 2017-06-02 15:36
OK then.
There are so many issues on npm5 created in the past 24h/36h anyway. So one more, one less... no difference :-)
I wish good luck and feel supportive to the dev team which must be under pressure right now with all these issues!

**Comment by ilovezfs** [comment] 2017-06-24 06:20
@zkat any idea why this wasn't labeled before npm-robot closed it? @chrmoritz went out of his way to report these issues at my request on https://github.com/Homebrew/homebrew-core/pull/14085 and it seems to have not even been acknowledged.

**Comment by lilydjwg** [comment] 2017-07-04 13:14
@ilovezfs the bot has said that they didn't ever read. Now I'm trying my best to ignore the update notice every time I run npm install....

**Comment by zkat** [comment] 2017-07-04 18:15
@chrmoritz because the npm CLI team is putting its time into fixing bugs, instead of doing triage. There's a *lot* of issues. We honestly can't keep up with them all unless we take time away from fixing all the things we already know about, and issues are very often just support issues or duplicates. Triage, in the end, is about picking your battles, and spending a lot of time on the issue tracker is not better than actually making the CLI better.

**Comment by ilovezfs** [comment] 2017-07-04 18:21
@zkat is it in fact a duplicate of something you already know about that
```
./configure --prefix=/somewhere
make install
```
no longer works as expected?

**Comment by zkat** [comment] 2017-07-04 18:46
@ilovezfs The third issue in this thread is already fixed in the canary, and a patch will be available tomorrow in mainline npm.

Getting `make install` to work as it used to (which seems like a reasonable enough thing to do) is a matter of changing the `install` target to first run `npm pack` on the repo, and _then_ do an `npm install` on that tarball. I'll take a patch for that, but I'm not gonna do this today, and it's not gonna be my priority.

**Comment by ilovezfs** [comment] 2017-07-04 18:48
@zkat fair enough! As long as you're _aware_ of that one, I'm happy :)

**Comment by chrmoritz** [comment] 2017-07-04 22:10
@zkat Thanks for the reply. Looks like I'm still able to reproduce the 3rd issue with npmc 5.0.4-canary.14: https://gist.github.com/chrmoritz/c0634d0b2c4b65fce33a6ca08c32e7a4
Should this be fixed in this version?

Also note that the `make install` issue also affects your [`install.sh` script](http://npmjs.com/install.sh).

**Comment by zkat** [comment] 2017-07-04 22:34
Oh sorry I misread the repro. There was a separate bug where dependencies would be randomly missing after install that's been fixed.

This particular case seems to be working as expected and designed, but is probably surprising to people. I'm inclined to leave it as it is. Here's what's happening:

1. an install is created with a tree structure npm does not recognize and the packages have no metadata. As far as npm is concerned, all of the dependencies inside `node_modules` are completely invalid.

2. Since the trees that yarn generates are incompatible with npm, and npm needs to do tree manipulations in order to install a new package, it will remove all other packages when it needs to work with the tree

3. `npm i <pkg>` is designed such that it won't install anything but the things you requested -- so after removing all those packages, only `grunt-cli` and its dependencies will be present. Because you only asked for those.

So, this is an intentional design choice: the CLI team concluded that people would be _more_ unhappy if installing a single dependency forced installation of *all* of their dependencies (this is what yarn does, incidentally), and this is the result of it when combined with other behavior. Your `node_modules` should be completely back to normal if you just do an `npm i` after realizing you made this "slip-up", but neither npm nor yarn are designed to allow you to switch back and forth and expect "ideal" results.

I'll /cc @iarna cause tbh we can probably be convinced to change this behavior.

**Comment by chrmoritz** [comment] 2017-07-04 23:07
Thanks for the detailed explanation.

I assume the fact, that npm doesn't notice that `grunt-cli` is already installed is also related to npm not recognizing the tree structure created by yarn.

As I said in my first post, I'm totally fine with the repro from 3 being unsupported usage of npm (on a yarn created tree, which it can't recognize).

**Comment by iarna** [comment] 2017-07-04 23:11
We'll get a fix for the Makefile thing in the next release (it's an easy fix, it just needs to install from a pack file).

The "remove everything" I'm not keen on, it means that you end up with an empty package-lock and I'd prefer that we (as a rule) produced complete package locks regardless of your starting state. I'm not sure if would ideally mean installing just the requested package (and it's deps) but having a complete package lock, or if it means installing _everything_, plus the requested package.

I -am- a bit surprised that npm is throwing away all of the yarn installed packages, as the registry deps at least should be compatible, so I'd like to take another look at that.

_Edit: Ah, Yarn doesn't record what integrity hash was the source for an installed package, so there's now way to know if what's in node_modules is what we need to have. (In this case, Yarn like npm@<5, just assumes its ok.) npm@<5 records integrity but doesn't require it. npm@5 would have to disable integrity checks to consider yarn installed packages ok._

**Comment by chrmoritz** [comment] 2017-07-04 23:25
> We'll get a fix for the Makefile thing in the next release (it's an easy fix, it just needs to install from a pack file).

Thanks, but it looks like most people are hitting this issue through your install.sh script (#17036, #17058) and it's [line 260](https://github.com/npm/npm/blob/latest/scripts/install.sh#L259-L260) needs a `npm pack` step for a complete fix too.

>  it means that you end up with an empty package-lock

It's not completly empty, because npm installs `grunt-cli` (and it's deps) after removing the complete yarn tree from node_modules. But it's incomplete as it only contains `grunt-cli` (and it's deps).

**Comment by iarna** [comment] 2017-07-04 23:56
Yes, the `install.sh` too.

**Closed as completed** 2017-07-11 00:40 UTC
Labels: bot-closed

**Comment by ilovezfs** [comment] 2017-07-11 06:05
Thanks @iarna and @zkat! :bowing_man:
