### ISSUE TITLE
 You do not have permission to publish 'censorify'. Are you logged in as the correct user? : censorify

### ISSUE THREAD

**Issue by sharpscar** [npm/npm#8561] opened 2015-06-14 05:20 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.11.2
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/home/sharpscar/WebstormProjects/censorify',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /home/sharpscar/.npm/censorify/0.1.1/package.tgz not in flight; packing
10 verbose tar pack [ '/home/sharpscar/.npm/censorify/0.1.1/package.tgz',
10 verbose tar pack   '/home/sharpscar/WebstormProjects/censorify' ]
11 verbose tarball /home/sharpscar/.npm/censorify/0.1.1/package.tgz
12 verbose folder /home/sharpscar/WebstormProjects/censorify
13 info prepublish censorify@0.1.1
14 verbose addLocalTarball adding from inside cache /home/sharpscar/.npm/censorify/0.1.1/package.tgz
15 silly cache afterAdd censorify@0.1.1
16 verbose afterAdd /home/sharpscar/.npm/censorify/0.1.1/package/package.json not in flight; writing
17 verbose afterAdd /home/sharpscar/.npm/censorify/0.1.1/package/package.json written
18 silly publish { author: { name: 'Brad Dayley' },
18 silly publish   name: 'censorify',
18 silly publish   version: '0.1.1',
18 silly publish   description: 'Censors words out of text',
18 silly publish   main: 'censortext',
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'git+https://github.com/sharpscar/censorify.git' },
18 silly publish   keywords: [ 'censor', 'words' ],
18 silly publish   dependencies: {},
18 silly publish   engines: { node: '*' },
18 silly publish   readme: 'ERROR: No README data found!',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: '5ddc6709a9587c71ae0b54d666b757c7ebce3209',
18 silly publish   bugs: { url: 'https://github.com/sharpscar/censorify/issues' },
18 silly publish   homepage: 'https://github.com/sharpscar/censorify#readme',
18 silly publish   _id: 'censorify@0.1.1',
18 silly publish   scripts: {},
18 silly publish   _shasum: '56bc204c0d1607c86fd12178d8c5200533b1a4a3',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name censorify
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/censorify
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /home/sharpscar/.npm/censorify/0.1.1/package.tgz
26 verbose request uri https://registry.npmjs.org/censorify
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 14:08:04
29 verbose request using bearer token for auth
30 verbose request id 2cab1f70fedd5098
31 http request PUT https://registry.npmjs.org/censorify
32 http 403 https://registry.npmjs.org/censorify
33 verbose headers { 'content-type': 'application/json',
33 verbose headers   'cache-control': 'max-age=60',
33 verbose headers   'content-length': '101',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Sun, 14 Jun 2015 05:08:05 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-nrt6127-NRT',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1434258485.052771,VS0,VE334' }
34 verbose request invalidating /home/sharpscar/.npm/registry.npmjs.org/censorify on PUT
35 error publish Failed PUT 403
36 verbose stack Error: You do not have permission to publish 'censorify'. Are you logged in as the correct user? : censorify
36 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
36 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
36 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:354:22)
36 verbose stack     at Request.emit (events.js:98:17)
36 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1207:14)
36 verbose stack     at Request.emit (events.js:117:20)
36 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1153:12)
36 verbose stack     at IncomingMessage.emit (events.js:117:20)
36 verbose stack     at _stream_readable.js:944:16
36 verbose stack     at process._tickCallback (node.js:448:13)
37 verbose statusCode 403
38 verbose pkgid censorify
39 verbose cwd /home/sharpscar/WebstormProjects/censorify
40 error Linux 3.13.0-53-generic
41 error argv "node" "/usr/local/bin/npm" "publish"
42 error node v0.10.37
43 error npm  v2.11.2
44 error code E403
45 error You do not have permission to publish 'censorify'. Are you logged in as the correct user? : censorify
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]

I can't fix this error 

do not have permission ?  (censorify) is just application's name 

I want just publish  ->npm publish 

but terminal shown this error message 

You do not have permission to publish 'censorify'. Are you logged in as the correct user? :  censorify

how can I fix this error

**Comment by amovah** [comment] 2015-06-14 05:26
I have same problem too, please help us.

**Comment by zkat** [comment] 2015-06-14 06:16
Hi, @sharpscar! It looks like a module with that name was already [published by someone else](https://www.npmjs.com/package/censorify), so you'd need to use a different name, or [use a scope](https://docs.npmjs.com/getting-started/scoped-packages) if you really want to keep the same name.

@amovah -- could you check that the name is not already taken by someone else, as well?

**Comment by sharpscar** [comment] 2015-06-14 06:23
@zkat thank you I'll try other name

**Comment by zkat** [comment] 2015-06-14 06:38
Great! Let me know if that works out for you :)

**Comment by amovah** [comment] 2015-06-14 18:58
Thanks.
I don't have any mistake like this, until now.

**Comment by zkat** [comment] 2015-06-21 07:15
Heads up -- this looks like a duplicate of both #8625 and #8053 and #7662.

This is clearly a high-demand module if we've gotten at least 4 different people trying to publish the same name. Hah.

**Comment by KenanY** [comment] 2015-06-21 15:33
@zkat I believe they are all following a tutorial somewhere.

**Comment by sharpscar** [comment] 2015-06-24 23:34
sorry I'm late check my email

in my case is 'censorify'  is aready made by another user. so you can make
other name

ex)  'censorify_myown_8979887' like this ^^

2015-06-22 0:33 GMT+09:00 Kenan Yildirim <notifications@github.com>:

**Comment by ehsalazar** [comment] 2015-08-12 05:02
It sounds like you figured out the issue and got beyond it. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.

**Closed by ehsalazar** 2015-08-12 05:02 UTC
Labels: support

**Comment by James-dai** [comment] 2016-03-04 09:47
@zkat ,you are right..
i changed this "name" , it can be npm publish
thanks @zkat zkat
![issue2](https://cloud.githubusercontent.com/assets/4067081/13523533/05657782-e231-11e5-84a2-b08ce4953478.png)
![issue1](https://cloud.githubusercontent.com/assets/4067081/13523535/056f7732-e231-11e5-86a4-1bca1c5f3544.png)

**Comment by ashleydw** [comment] 2016-04-29 06:47
Ran into this too whilst trying to add a collaborator (owner). The correct error message should be returned as per @amovah comment!

**Comment by tibwiz** [comment] 2016-06-13 02:09
Yes, could we get this fixed? The error message does not give any clue and I had to google and find the issue. I believe many out there will be facing the same issue.

**Comment by boovius** [comment] 2017-01-25 16:54
@zkat's answer about the title of the package having already been taken was the answer - the error message output leads publishers to think it's an authentication issue with their account.  A simple message saying that "a package already exists with that name, make sure you are authorized to published to that package" would be far more informative and lead to far less confusion.

**Comment by zkat** [comment] 2017-01-25 17:44
@boovius you could create an issue over at https://github.com/npm/registry/issues asking for this change. I agree that we should have better messaging around this!

**Comment by garestrepop** [comment] 2017-06-29 02:36
If your repository is Public then

> npm publish --access=public

**Comment by Palochinmayee** [comment] 2017-11-28 11:12
I was also getting the same error. npm login helped me.

**Comment by daggerok** [comment] 2018-01-21 12:38
error message incorrect and should be fixed for something more helpful

**Comment by teamonn** [comment] 2018-04-11 07:30
@zkat Thank you. But why do I have to change another package name? What I used before was not used in fact.

**Comment by RatneshChauhan** [comment] 2018-04-11 16:27
@zkat Thank you!
