### ISSUE TITLE
JS Allocation failed - process out of memory (new)

### ISSUE THREAD

**Issue by examinedliving** [npm/npm#4868] opened 2014-03-12 20:54 UTC
This seems unrelated to the other issues regarding this error, so I am posting it newly.

It's possibly related to something with my network, though I have no evidence to support that other than speculation.

Result is identical in both Windows 7 with 64 bit install, and Vagrant running on the same box.

`npm search font` - generates the error after using enough memory to freeze my pc.
`npm search gulp` - works fine `//just chose this because the response set is small but not tiny`

`npm version` on windows, outputs: 

`{ http_parser: '1.0',
  node: '0.10.26',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.25',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.4.3' }`

on Vagrant (precise32 box):

`{ http_parser: '1.0',
  node: '0.10.25',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.23',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.3.24' }`

font is just too generic a search?

Even if this is true, the error is probably an undesirable response.

**Comment by smikes** [comment] 2015-01-06 12:47
@examinedliving , Is this still a problem for you?

As @othiym23 says above, `npm search` is currently broken on the command-line. The suggested workaround is to use the package search function at https://www.npmjs.com/

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-01-07 00:57
Actually, I'm just going to go ahead and close this as a duplicate of #6016 -- this is a known issue, and will probably be fixed by moving `npm search` to use online queries instead of an offline JSON cache. We may patch up the current solution so it's more robust, but it's living on borrowed time. Whatever work goes into fixing offline search will be tracked from #6016.

**Closed by othiym23** 2015-01-07 00:57 UTC
Labels: support, windows
