### ISSUE TITLE
Fail to uninstall global package

### ISSUE THREAD

**Issue by Diluka** [npm/npm#17850] opened 2017-07-19 06:36 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm crashed when uninstalling global package
#### How can the CLI team reproduce the problem?

command
```sh
[sudo] npm un react-native-cli -g
```

error stack
```
Unhandled rejection Error: Argument #2: Expected string but got null64c2e11b787
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Diluka/.npm/_logs/2017-07-19T06_28_23_847Z-debug.log
```

log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'un',
1 verbose cli   'react-native-cli',
1 verbose cli   '-g' ]
2 info using npm@5.0.3
3 info using node@v8.1.4
4 verbose npm-session a73a64c2e11b7879
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

### supporting information:

 - `npm -v` prints: `5.0.3`
 - `node -v` prints: `v8.1.4`
 - `npm config get registry` prints: `https://registry.npm.taobao.org/`
 - Windows, OS X/macOS, or Linux?: `macOS`
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

the `package.json` of `react-native-cli`
```json
{
  "_args": [
    [
      {
        "raw": "react-native-cli",
        "scope": null,
        "escapedName": "react-native-cli",
        "name": "react-native-cli",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "/Users/Diluka/Desktop"
    ]
  ],
  "_cnpm_publish_time": 1481898485895,
  "_from": "react-native-cli@latest",
  "_hasShrinkwrap": false,
  "_id": "react-native-cli@2.0.1",
  "_inCache": true,
  "_location": "/react-native-cli",
  "_nodeVersion": "6.9.1",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/react-native-cli-2.0.1.tgz_1481898483578_0.7135944531764835"
  },
  "_npmUser": {
    "name": "mkonicek",
    "email": "martin.konicek@gmail.com"
  },
  "_npmVersion": "3.10.8",
  "_phantomChildren": {},
  "_requested": {
    "raw": "react-native-cli",
    "scope": null,
    "escapedName": "react-native-cli",
    "name": "react-native-cli",
    "rawSpec": "",
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npm.taobao.org/react-native-cli/download/react-native-cli-2.0.1.tgz",
  "_shasum": "f2cd3c7aa1b83828cdfba630e2dfd817df766d54",
  "_shrinkwrap": null,
  "_spec": "react-native-cli",
  "_where": "/Users/Diluka/Desktop",
  "bin": {
    "react-native": "index.js"
  },
  "bugs": {
    "url": "https://github.com/facebook/react-native/issues"
  },
  "dependencies": {
    "chalk": "^1.1.1",
    "minimist": "^1.2.0",
    "prompt": "^0.2.14",
    "semver": "^5.0.3"
  },
  "description": "The React Native CLI tools",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "f2cd3c7aa1b83828cdfba630e2dfd817df766d54",
    "size": 5924,
    "noattachment": false,
    "tarball": "http://registry.npm.taobao.org/react-native-cli/download/react-native-cli-2.0.1.tgz"
  },
  "engines": {
    "node": ">=4"
  },
  "homepage": "https://github.com/facebook/react-native#readme",
  "license": "BSD-3-Clause",
  "main": "index.js",
  "maintainers": [
    {
      "name": "amasad",
      "email": "amjad.masad@gmail.com"
    },
    {
      "name": "bestander",
      "email": "bestander@gmail.com"
    },
    {
      "name": "fb",
      "email": "opensource+npm@fb.com"
    },
    {
      "name": "frantic",
      "email": "alex.frantic@gmail.com"
    },
    {
      "name": "mkonicek",
      "email": "martin.konicek@gmail.com"
    },
    {
      "name": "spicyj",
      "email": "ben@benalpert.com"
    },
    {
      "name": "vjeux",
      "email": "vjeuxx@gmail.com"
    }
  ],
  "name": "react-native-cli",
  "optionalDependencies": {},
  "publish_time": 1481898485895,
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/facebook/react-native.git"
  },
  "scripts": {
    "test": "mocha"
  },
  "version": "2.0.1"
}
```

**Comment by kenany** [comment] 2017-07-19 15:10
Duplicate of https://github.com/npm/npm/issues/16738

**Closed as completed by kenany** 2017-07-19 15:10 UTC
Labels: support
