### ISSUE TITLE
No such file or directory while install sql or express any other package  

### ISSUE THREAD

**Issue by dileep502** [npm/npm#11103] opened 2016-01-09 19:51 UTC
```
C:\Users\DELL>npm install mysql
C:\Users\DELL
└── mysql@2.10.0

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\DELL\package.json'
npm WARN EPACKAGEJSON DELL No description
npm WARN EPACKAGEJSON DELL No repository field.
npm WARN EPACKAGEJSON DELL No README data
npm WARN EPACKAGEJSON DELL No license field.
```

**Comment by ktrzeciaknubisa** [comment] 2016-01-20 13:18
Same here. 

I believe this is similar to https://github.com/npm/npm/issues/8871, however that one is about global install (`-g` or `--global` and it seems like they fixed it). But local install still suffers the issue.

**Comment by KenanY** [comment] 2016-01-20 13:45
I think this warning is simply trying to tell you that you do not have a `package.json` in your current directory. While it is not necessary to have a `package.json` in order to simply install modules as you are doing, in the long run it is usually best to specify these modules as dependencies or devDependencies of whatever project you are starting.

**Comment by KenanY** [comment] 2016-05-15 18:35
@dileep502 Since there are no errors in the output you have posted (only warnings), is it safe to say that this issue may be closed as not a bug in `npm`?

**Comment by KenanY** [comment] 2016-07-02 17:58
Closing as not an issue with `npm`.

**Closed by KenanY** 2016-07-02 17:58 UTC
Labels: support
