### ISSUE TITLE
npm install from a git remote url and it generates a file path pointing to the git temp folder

### ISSUE THREAD

**Issue by stevemao** [npm/npm#7374] opened 2015-02-17 06:17 UTC
running `npm install --save git+https://isaacs@github.com/npm/npm.git` and in my package.json i see 

```json
"dependencies": {
  "npm": "file:../../../../var/folders/g7/d108z_h16wxg9cxxdnb_sdcw0000gn/T/npm-145-0801115a/git-cache-a102253f0521/765c082bb89587c77c15494edfc402cc970adf98"
}
```

it used to be 

```json
"dependencies": {
  "npm": "git+https://isaacs@github.com/npm/npm.git"
}
```

So that other people can install the same package via `npm install`

I saw encountered this problem when I was using node version 0.10, npm version 2.4 and git 2.2 so I upgraded to node 0.12, npm 2.5 and git 2.3 but still have the same problem.

Please help! Thanks.

**Comment by stevemao** [comment] 2015-02-17 06:30
Tried with git 2.0.3 and it gives me the same result.

**Comment by smikes** [comment] 2015-02-18 05:13
Possibly a duplicate of #7121 , possibly fixed by #7296

**Comment by twhid** [comment] 2015-02-18 18:10
We've run into this bug as well. I don't think https://github.com/npm/npm/pull/7296 fixes it. I believe that only fixes the issue of prepending `git+` arbitrarily to the protocol if `git:` isn't found.

**Comment by smikes** [comment] 2015-02-18 19:00
Hm.. I agree that the cases look unrelated; I was basing my claim on this comment <https://github.com/npm/npm/issues/7121#issuecomment-73990831> but it's certainly possible that the comment landed on the wrong issue.

In any case, this is a known issue (`npm install --save` stores a path to the tmp directory when used with git dependencies), and we're hoping to fix it soon.  #7121 is marked as "patch-welcome" if anyone wants to take a crack at it...

**Comment by othiym23** [comment] 2015-02-19 08:11
Indeed, closing as a duplicate of #7121. It turns out there were some submarine dependencies between how git dependencies were being cached and how they got saved into `package.json`. I'd love to see this get fixed, but it's going to be a few weeks until I (or the other members of the CLI core team) have time to clear up some of these bugs.

**Closed by othiym23** 2015-02-19 08:11 UTC
