### ISSUE TITLE
npm 3.3.2, hangs after unsupported optional dependency. (Windows)

### ISSUE THREAD

**Issue by robertbaker** [npm/npm#9528] opened 2015-09-08 23:54 UTC
`npm WARN install Couldn't install optional dependency: Unsupported.`

It will just sit there blinking cursor for 3-5 minutes then spit out the dep tree.

**Comment by smikes** [comment] 2015-09-11 04:25
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

You may find that with the logging level increased, there is actually activity going on that's just not logged..

Thanks!

**Comment by robertbaker** [comment] 2015-09-16 23:28
```
npm info attempt registry request try #1 at 4:24:58 PM
npm http request GET https://registry.npmjs.org/tslint
npm http 304 https://registry.npmjs.org/tslint
npm info retry fetch attempt 1 at 4:24:58 PM
npm info attempt registry request try #1 at 4:24:58 PM
npm http fetch GET https://registry.npmjs.org/tslint/-/tslint-2.5.0-beta.tgz
npm http fetch 200 https://registry.npmjs.org/tslint/-/tslint-2.5.0-beta.tgz
npm info attempt registry request try #1 at 4:25:00 PM
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm WARN install Couldn't install optional dependency: Unsupported
npm info lifecycle espree@2.2.5~preinstall: espree@2.2.5
npm info lifecycle eslint@1.4.3~preinstall: eslint@1.4.3
npm info lifecycle ansi-regex@2.0.0~preinstall: ansi-regex@2.0.0
npm info lifecycle ansi-styles@2.1.0~preinstall: ansi-styles@2.1.0
npm info lifecycle has-ansi@2.0.0~preinstall: has-ansi@2.0.0
npm info lifecycle strip-ansi@3.0.0~preinstall: strip-ansi@3.0.0
npm info lifecycle supports-color@2.0.0~preinstall: supports-color@2.0.0
npm info lifecycle chalk@1.1.1~preinstall: chalk@1.1.1
npm info lifecycle fancy-log@1.1.0~preinstall: fancy-log@1.1.0
npm info lifecycle tslint@2.5.0-beta~preinstall: tslint@2.5.0-beta
npm info lifecycle sparkles@1.0.0~preinstall: sparkles@1.0.0
npm info lifecycle glogg@0.0.0~preinstall: glogg@0.0.0
npm info lifecycle gulplog@0.0.0~preinstall: gulplog@0.0.0
npm info lifecycle gulp-cli@0.4.0~preinstall: gulp-cli@0.4.0
npm info lifecycle gulp@4.0.0-alpha.1~preinstall: gulp@4.0.0-alpha.1
npm info lifecycle gulp-tslint@3.3.0-beta~preinstall: gulp-tslint@3.3.0-beta
npm info lifecycle tslint@2.4.5~preuninstall: tslint@2.4.5
npm info lifecycle tslint@2.4.5~uninstall: tslint@2.4.5
npm info lifecycle tslint@2.4.5~postuninstall: tslint@2.4.5
npm info lifecycle yargs@1.3.3~preuninstall: yargs@1.3.3
npm info lifecycle yargs@1.3.3~uninstall: yargs@1.3.3
npm info lifecycle yargs@1.3.3~postuninstall: yargs@1.3.3
npm info linkStuff espree@2.2.5
npm info linkStuff eslint@1.4.3
npm info build c:\git\pos\node_modules\eslint\node_modules\ansi-regex
npm info lifecycle ansi-regex@2.0.0~preinstall: ansi-regex@2.0.0
npm info linkStuff ansi-regex@2.0.0
npm info lifecycle ansi-regex@2.0.0~install: ansi-regex@2.0.0
npm info lifecycle ansi-regex@2.0.0~postinstall: ansi-regex@2.0.0
npm info build c:\git\pos\node_modules\eslint\node_modules\ansi-styles
npm info lifecycle ansi-styles@2.1.0~preinstall: ansi-styles@2.1.0
npm info linkStuff ansi-styles@2.1.0
npm info lifecycle ansi-styles@2.1.0~install: ansi-styles@2.1.0
npm info lifecycle ansi-styles@2.1.0~postinstall: ansi-styles@2.1.0
npm info build c:\git\pos\node_modules\eslint\node_modules\async
npm info lifecycle async@1.4.2~preinstall: async@1.4.2
npm info linkStuff async@1.4.2
npm info lifecycle async@1.4.2~install: async@1.4.2
npm info lifecycle async@1.4.2~postinstall: async@1.4.2
npm info build c:\git\pos\node_modules\eslint\node_modules\has-ansi
npm info lifecycle has-ansi@2.0.0~preinstall: has-ansi@2.0.0
npm info linkStuff has-ansi@2.0.0
npm info lifecycle has-ansi@2.0.0~install: has-ansi@2.0.0
npm info lifecycle has-ansi@2.0.0~postinstall: has-ansi@2.0.0
npm info build c:\git\pos\node_modules\eslint\node_modules\minimist
npm info lifecycle minimist@0.0.8~preinstall: minimist@0.0.8
npm info linkStuff minimist@0.0.8
npm info lifecycle minimist@0.0.8~install: minimist@0.0.8
npm info lifecycle minimist@0.0.8~postinstall: minimist@0.0.8
npm info build c:\git\pos\node_modules\eslint\node_modules\source-map
npm info lifecycle source-map@0.4.4~preinstall: source-map@0.4.4
npm info linkStuff source-map@0.4.4
npm info lifecycle source-map@0.4.4~install: source-map@0.4.4
npm info lifecycle source-map@0.4.4~postinstall: source-map@0.4.4
npm info build c:\git\pos\node_modules\eslint\node_modules\strip-ansi
npm info lifecycle strip-ansi@3.0.0~preinstall: strip-ansi@3.0.0
npm info linkStuff strip-ansi@3.0.0
npm info lifecycle strip-ansi@3.0.0~install: strip-ansi@3.0.0
npm info lifecycle strip-ansi@3.0.0~postinstall: strip-ansi@3.0.0
npm info build c:\git\pos\node_modules\eslint\node_modules\supports-color
npm info lifecycle supports-color@2.0.0~preinstall: supports-color@2.0.0
npm info linkStuff supports-color@2.0.0
npm info lifecycle supports-color@2.0.0~install: supports-color@2.0.0
npm info lifecycle supports-color@2.0.0~postinstall: supports-color@2.0.0
npm info build c:\git\pos\node_modules\eslint\node_modules\uglify-js
npm info lifecycle uglify-js@2.4.24~preinstall: uglify-js@2.4.24
npm info linkStuff uglify-js@2.4.24
npm info lifecycle uglify-js@2.4.24~install: uglify-js@2.4.24
npm info lifecycle uglify-js@2.4.24~postinstall: uglify-js@2.4.24
npm info build c:\git\pos\node_modules\eslint\node_modules\window-size
npm info lifecycle window-size@0.1.0~preinstall: window-size@0.1.0
npm info linkStuff window-size@0.1.0
npm info lifecycle window-size@0.1.0~install: window-size@0.1.0
npm info lifecycle window-size@0.1.0~postinstall: window-size@0.1.0
npm info build c:\git\pos\node_modules\eslint\node_modules\yargs
npm info lifecycle yargs@3.5.4~preinstall: yargs@3.5.4
npm info linkStuff yargs@3.5.4
npm info lifecycle yargs@3.5.4~install: yargs@3.5.4
npm info lifecycle yargs@3.5.4~postinstall: yargs@3.5.4
npm info linkStuff ansi-regex@2.0.0
npm info linkStuff ansi-styles@2.1.0
npm info linkStuff has-ansi@2.0.0
npm info linkStuff strip-ansi@3.0.0
npm info linkStuff supports-color@2.0.0
npm info linkStuff chalk@1.1.1
npm info linkStuff fancy-log@1.1.0
npm info build c:\git\pos\node_modules\fancy-log\node_modules\ansi-regex
npm info lifecycle ansi-regex@2.0.0~preinstall: ansi-regex@2.0.0
npm info linkStuff ansi-regex@2.0.0
npm info lifecycle ansi-regex@2.0.0~install: ansi-regex@2.0.0
npm info lifecycle ansi-regex@2.0.0~postinstall: ansi-regex@2.0.0
npm info build c:\git\pos\node_modules\fancy-log\node_modules\ansi-styles
npm info lifecycle ansi-styles@2.1.0~preinstall: ansi-styles@2.1.0
npm info linkStuff ansi-styles@2.1.0
npm info lifecycle ansi-styles@2.1.0~install: ansi-styles@2.1.0
npm info lifecycle ansi-styles@2.1.0~postinstall: ansi-styles@2.1.0
npm info build c:\git\pos\node_modules\fancy-log\node_modules\has-ansi
npm info lifecycle has-ansi@2.0.0~preinstall: has-ansi@2.0.0
npm info linkStuff has-ansi@2.0.0
npm info lifecycle has-ansi@2.0.0~install: has-ansi@2.0.0
npm info lifecycle has-ansi@2.0.0~postinstall: has-ansi@2.0.0
npm info build c:\git\pos\node_modules\fancy-log\node_modules\strip-ansi
npm info lifecycle strip-ansi@3.0.0~preinstall: strip-ansi@3.0.0
npm info linkStuff strip-ansi@3.0.0
npm info lifecycle strip-ansi@3.0.0~install: strip-ansi@3.0.0
npm info lifecycle strip-ansi@3.0.0~postinstall: strip-ansi@3.0.0
npm info build c:\git\pos\node_modules\fancy-log\node_modules\supports-color
npm info lifecycle supports-color@2.0.0~preinstall: supports-color@2.0.0
npm info linkStuff supports-color@2.0.0
npm info lifecycle supports-color@2.0.0~install: supports-color@2.0.0
npm info lifecycle supports-color@2.0.0~postinstall: supports-color@2.0.0
npm info linkStuff tslint@2.5.0-beta
npm info linkStuff sparkles@1.0.0
npm info linkStuff glogg@0.0.0
npm info linkStuff gulplog@0.0.0
npm info linkStuff gulp-cli@0.4.0
npm info linkStuff gulp@4.0.0-alpha.1
npm info build c:\git\pos\node_modules\gulp\node_modules\ansi-regex
npm info lifecycle ansi-regex@2.0.0~preinstall: ansi-regex@2.0.0
npm info linkStuff ansi-regex@2.0.0
npm info lifecycle ansi-regex@2.0.0~install: ansi-regex@2.0.0
npm info lifecycle ansi-regex@2.0.0~postinstall: ansi-regex@2.0.0
npm info build c:\git\pos\node_modules\gulp\node_modules\ansi-styles
npm info lifecycle ansi-styles@2.1.0~preinstall: ansi-styles@2.1.0
npm info linkStuff ansi-styles@2.1.0
npm info lifecycle ansi-styles@2.1.0~install: ansi-styles@2.1.0
npm info lifecycle ansi-styles@2.1.0~postinstall: ansi-styles@2.1.0
npm info build c:\git\pos\node_modules\gulp\node_modules\chalk
npm info lifecycle chalk@1.1.1~preinstall: chalk@1.1.1
npm info linkStuff chalk@1.1.1
npm info lifecycle chalk@1.1.1~install: chalk@1.1.1
npm info lifecycle chalk@1.1.1~postinstall: chalk@1.1.1
npm info build c:\git\pos\node_modules\gulp\node_modules\has-ansi
npm info lifecycle has-ansi@2.0.0~preinstall: has-ansi@2.0.0
npm info linkStuff has-ansi@2.0.0
npm info lifecycle has-ansi@2.0.0~install: has-ansi@2.0.0
npm info lifecycle has-ansi@2.0.0~postinstall: has-ansi@2.0.0
npm info build c:\git\pos\node_modules\gulp\node_modules\strip-ansi
npm info lifecycle strip-ansi@3.0.0~preinstall: strip-ansi@3.0.0
npm info linkStuff strip-ansi@3.0.0
npm info lifecycle strip-ansi@3.0.0~install: strip-ansi@3.0.0
npm info lifecycle strip-ansi@3.0.0~postinstall: strip-ansi@3.0.0
npm info build c:\git\pos\node_modules\gulp\node_modules\supports-color
npm info lifecycle supports-color@2.0.0~preinstall: supports-color@2.0.0
npm info linkStuff supports-color@2.0.0
npm info lifecycle supports-color@2.0.0~install: supports-color@2.0.0
npm info lifecycle supports-color@2.0.0~postinstall: supports-color@2.0.0
npm info linkStuff gulp-tslint@3.3.0-beta
npm info lifecycle espree@2.2.5~install: espree@2.2.5
npm info lifecycle eslint@1.4.3~install: eslint@1.4.3
npm info lifecycle ansi-regex@2.0.0~install: ansi-regex@2.0.0
npm info lifecycle ansi-styles@2.1.0~install: ansi-styles@2.1.0
npm info lifecycle has-ansi@2.0.0~install: has-ansi@2.0.0
npm info lifecycle strip-ansi@3.0.0~install: strip-ansi@3.0.0
npm info lifecycle supports-color@2.0.0~install: supports-color@2.0.0
npm info lifecycle chalk@1.1.1~install: chalk@1.1.1
npm info lifecycle fancy-log@1.1.0~install: fancy-log@1.1.0
npm info lifecycle tslint@2.5.0-beta~install: tslint@2.5.0-beta
npm info lifecycle sparkles@1.0.0~install: sparkles@1.0.0
npm info lifecycle glogg@0.0.0~install: glogg@0.0.0
npm info lifecycle gulplog@0.0.0~install: gulplog@0.0.0
npm info lifecycle gulp-cli@0.4.0~install: gulp-cli@0.4.0
npm info lifecycle gulp@4.0.0-alpha.1~install: gulp@4.0.0-alpha.1
npm info lifecycle gulp-tslint@3.3.0-beta~install: gulp-tslint@3.3.0-beta
npm info lifecycle espree@2.2.5~postinstall: espree@2.2.5
npm info lifecycle eslint@1.4.3~postinstall: eslint@1.4.3
npm info lifecycle ansi-regex@2.0.0~postinstall: ansi-regex@2.0.0
npm info lifecycle ansi-styles@2.1.0~postinstall: ansi-styles@2.1.0
npm info lifecycle has-ansi@2.0.0~postinstall: has-ansi@2.0.0
npm info lifecycle strip-ansi@3.0.0~postinstall: strip-ansi@3.0.0
npm info lifecycle supports-color@2.0.0~postinstall: supports-color@2.0.0
npm info lifecycle chalk@1.1.1~postinstall: chalk@1.1.1
npm info lifecycle fancy-log@1.1.0~postinstall: fancy-log@1.1.0
npm info lifecycle tslint@2.5.0-beta~postinstall: tslint@2.5.0-beta
npm info lifecycle sparkles@1.0.0~postinstall: sparkles@1.0.0
npm info lifecycle glogg@0.0.0~postinstall: glogg@0.0.0
npm info lifecycle gulplog@0.0.0~postinstall: gulplog@0.0.0
npm info lifecycle gulp-cli@0.4.0~postinstall: gulp-cli@0.4.0
npm info lifecycle gulp@4.0.0-alpha.1~postinstall: gulp@4.0.0-alpha.1
npm info lifecycle gulp-tslint@3.3.0-beta~postinstall: gulp-tslint@3.3.0-beta
- yargs@1.3.3 node_modules\gulp\node_modules\yargs
```

**Comment by lukeapage** [comment] 2015-10-02 11:19
duplicate of #9204

**Closed** 2017-06-18 22:56 UTC
Labels: bot-closed
