### ISSUE TITLE
npm install -g @angular/cli issue on windows 10

### ISSUE THREAD

**Issue by BapuKShinde** [npm/npm#16752] opened 2017-05-27 06:52 UTC
C:\Users\Bapusaheb>npm install -g @angular/cli
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\BAPUSA~1\AppData\Local\Temp\npm-5756-72bfe98a\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.17.tgz.3276165312' -> 'C:\Users\BAPUSA~1\AppData\Local\Temp\npm-5756-72bfe98a\registry.npmjs.org\iconv-lite\-\iconv-lite-0.4.17.tgz'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2017-05-27 07:38
closing as a duplicate of #16751

**Closed by zkat** 2017-05-27 07:38 UTC
Labels: support
