### ISSUE TITLE
npm ERR! Windows_NT 10.0.15063 and more

### ISSUE THREAD

**Issue by yolo-spolo** [npm/npm#17943] opened 2017-07-26 16:31 UTC
- [ ] npm is crashing.
  - npm is producing an incorrect install.
  - npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

```
C:\ya>npm install --save yambf
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "yambf"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/yambf
npm ERR! 404
npm ERR! 404  'yambf' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ya\npm-debug.log
```
C:\ya\npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'yambf' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData yambf
8 silly fetchNamedPackageData yambf
9 silly mapToRegistry name yambf
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'yambf',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'yambf',
12 silly mapToRegistry   name: 'yambf',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/yambf
14 verbose request uri https://registry.npmjs.org/yambf
15 verbose request no auth needed
16 info attempt registry request try #1 at 19:26:18
17 verbose request id a542511ec66d627f
18 http request GET https://registry.npmjs.org/yambf
19 http 404 https://registry.npmjs.org/yambf
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 26 Jul 2017 16:26:19 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1222-FRA',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1501086379.637297,VS0,VE481',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 26 Jul 2017 16:26:19 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1222-FRA',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1501086379.637297,VS0,VE481',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/yambf
22 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
22 silly fetchPackageMetaData  error for yambf { Error: Registry returned 404 for GET on https://registry.npmjs.org/yambf
22 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12) pkgid: 'yambf', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/yambf
27 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:188:7)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
28 verbose statusCode 404
29 verbose pkgid yambf
30 verbose cwd C:\ya
31 error Windows_NT 10.0.15063
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "yambf"
33 error node v6.11.1
34 error npm  v3.10.10
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/yambf
37 error 404
38 error 404 'yambf' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
```

**Comment by rodrigobacelli** [comment] 2017-07-27 18:17
Are you sure that 'yambf' is a valid NPM package? The error is a 404 error and I can't find it on NPM itself.

**Comment by shubhamsjmit** [comment] 2017-08-30 11:32
npm ERR! Windows_NT 10.0.15063
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Dev\\node-v6.11.2-win-x64\\node.exe" "C:\\Dev\\node-v6.11.2-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! file E:\Training\assignment1-ques2\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 13:3
npm ERR!   },
npm ERR!   ^
npm ERR! File: E:\Training\assignment1-ques2\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Training\assignment1-ques2\npm-debug.log


I am getting this error while using npm install while running someone else project

**Comment by agborne** [comment] 2017-09-01 05:33
same problem here

**Comment by zhipairen** [comment] 2017-09-21 06:10
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\gbl17\AppData\Local\Temp\npm-1028-e27c3232\registry.npmjs.org\caniuse-db\-\caniuse-db-1.0.30000733.tgz
npm ERR! Expected: 3a625bc41c7a9f99d59d64552857dd1af0edd9d4
npm ERR! Actual:   db6e92b01c0670fc705063c2ba314899a79735ff
npm ERR! From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000733.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gbl17\npm-debug.log

I executed the command 'npm install -g @angular/cli' to produce the error，why????????????

**Comment by kenany** [comment] 2017-09-21 14:53
I'm gonna assume that @yolo-spolo intended to install `yamdbf` and simply did a typo instead. Due to no reply to @rodrigobacelli I'm gonna close this as abandoned.

@shubhamsjmit Please open a new issue if you wish to pursue your specific issue further. Thanks!

**Closed as completed by kenany** 2017-09-21 14:53 UTC
Labels: support

**Comment by cesarAlvaradoDiaz** [comment] 2017-10-02 04:44
I had this problem because I wrongly selected the operating system for windows 10, when I chose the correct one and reinstalled mongodb, these errors disappeared. regards

**Comment by kwongiho** [comment] 2017-10-20 11:16
I write this comment although closed this issue. I had this problem too cause i write down wrong path with copy and paste. if you are using copy and paste, check it one more time.
