### ISSUE TITLE
npm login problems with 0.11.15, 404, user not found

### ISSUE THREAD

**Issue by sam-github** [npm/npm#7189] opened 2015-01-21 21:01 UTC
Underlying issue that #7188 was silent about.

What's happening here:

1. I'm being asked to login. When I switch to 0.10.35, I don't have to login, when I switch to 0.11.35 auth fails. This is reproduceable.
2. When I try to login with 0.11.15, it fails. This is probably underlying cause of (1)
3.  #7188, that with log level of warn, npm install silently fails

```
sam@samtu:~/w/sn/strongops/agent (fix-create-historgram-for-0.11.15 $) % npm install debug
npm info it worked if it ends with ok
npm info using npm@2.1.6
npm info using node@v0.11.15
npm info attempt registry request try #1 at 12:50:41
npm info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
npm info attempt registry request try #2 at 12:50:51
npm info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
^C
sam@samtu:~/w/sn/strongops/agent (fix-create-historgram-for-0.11.15 $) % node -v
v0.11.15
sam@samtu:~/w/sn/strongops/agent (fix-create-historgram-for-0.11.15 $) % npm login
Username: (octet) 
Password: (or leave unchanged) 
Email: (this IS public) (sam@strongloop.com) 
npm ERR! Linux 3.16.0-29-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code E404

npm ERR! 404 not_found missing: -/user/-/user/org.couchdb.user:octet

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sam/w/sn/strongops/agent/npm-debug.log
sam@samtu:~/w/sn/strongops/agent (fix-create-historgram-for-0.11.15 $) % npm login
Username: (octet) 
Password: (or leave unchanged) 
Email: (this IS public) (sam@strongloop.com) 
npm ERR! Linux 3.16.0-29-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code E404

npm ERR! 404 not_found missing: -/user/-/user/org.couchdb.user:octet

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sam/w/sn/strongops/agent/npm-debug.log
sam@samtu:~/w/sn/strongops/agent (fix-create-historgram-for-0.11.15 $) % npm -v
2.1.6
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'login' ]
2 info using npm@2.1.6
3 info using node@v0.11.15
4 verbose node symlink /usr/local/bin/node
5 verbose adduser before first PUT { name: 'octet',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'sam@strongloop.com',
5 verbose adduser   _id: 'org.couchdb.user:octet',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-01-21T20:54:54.117Z' }
6 verbose request on initialization, where is /-/user/org.couchdb.user:octet
7 verbose request after pass 1, where is /-/user/org.couchdb.user:octet
8 verbose request url raw /-/user/org.couchdb.user:octet
9 verbose request resolving registry [ 'https://registry.npmjs.org/-/user/org.couchdb.user:octet',
9 verbose request   './-/user/org.couchdb.user:octet' ]
10 verbose request after pass 2, where is https://registry.npmjs.org/-/user/-/user/org.couchdb.user:octet
11 verbose request new user, so can't send auth
12 info attempt registry request try #1 at 12:54:54
13 verbose request id f8755bf3bd490095
14 http request PUT https://registry.npmjs.org/-/user/-/user/org.couchdb.user:octet
15 http 404 https://registry.npmjs.org/-/user/-/user/org.couchdb.user:octet
16 verbose headers { date: 'Wed, 21 Jan 2015 20:54:54 GMT',
16 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '41',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   'x-served-by': 'cache-lax1427-LAX',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1421873694.449950,VS0,VE37',
16 verbose headers   connection: 'close' }
17 verbose adduser back [ { [Error: not_found missing: -/user/-/user/org.couchdb.user:octet] statusCode: 404, code: 'E404' },
17 verbose adduser   { error: 'not_found', reason: 'missing' },
17 verbose adduser   '{"error":"not_found","reason":"missing"}' ]
18 verbose stack Error: not_found missing: -/user/-/user/org.couchdb.user:octet
18 verbose stack     at RegClient.<anonymous> (/usr/local/stow/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:260:14)
18 verbose stack     at Request._callback (/usr/local/stow/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:65)
18 verbose stack     at Request.self.callback (/usr/local/stow/node/lib/node_modules/npm/node_modules/request/request.js:364:22)
18 verbose stack     at Request.emit (events.js:110:17)
18 verbose stack     at Request.<anonymous> (/usr/local/stow/node/lib/node_modules/npm/node_modules/request/request.js:1318:14)
18 verbose stack     at Request.emit (events.js:129:20)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/local/stow/node/lib/node_modules/npm/node_modules/request/request.js:1266:12)
18 verbose stack     at IncomingMessage.emit (events.js:129:20)
18 verbose stack     at _stream_readable.js:908:16
18 verbose stack     at process._tickCallback (node.js:355:11)
19 verbose statusCode 404
20 verbose cwd /home/sam/w/sn/strongops/agent
21 error Linux 3.16.0-29-generic
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
23 error node v0.11.15
24 error npm  v2.1.6
25 error code E404
26 error 404 not_found missing: -/user/-/user/org.couchdb.user:octet
27 verbose exit [ 1, true ]
```

**Comment by smikes** [comment] 2015-01-22 12:34
I am partially able to reproduce this, but it takes some config tweaks.

```
npm info attempt registry request try #1 at 05:29:22
npm info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
```

I can see this when I turn on `always-auth`, using `npm@2.3.0` on `iojs-v1.0.3`.

Sam, could you report the output of 

```
npm config ls -l | grep always
```
?

For the purposes of tracking down more context about this bug, please **don't** upgrade your `npm` from the version that ships with `node`.  But there's normally no reason you should want to run `2.1.6` or even `2.1.16` - you can always immediately run `npm install -g npm@latest`.

(Unless you are working around some bug later than 2.1.6, in which case, which bug?)

**Comment by designfrontier** [comment] 2015-01-22 17:27
I am seeing this as well

output:
```
always-auth = false
```

and the error itself:
```
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login" "--registry" "http://registry.npmjs.org"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code E404

npm ERR! 404 not_found missing: -/user/-/user/org.couchdb.user:daniel_sellers
```

**Comment by smikes** [comment] 2015-01-22 18:22
When I look again I see the doubled -/user/-/user in the login url. Looks like some sort of a problem with an old npm, an unstable node, and possibly an old version of request. 

Next suggestion is to get a new npm with npm install -g npm@latest ; and try to reproduce with the current code base.  /cc @othiym23 re doubled -/user in url

**Comment by othiym23** [comment] 2015-01-23 22:50
I'm pretty sure this is no longer an issue in newer versions of npm, but nobody at joyent/node asked me which version should be bundled with 0.11.15, so there's not a lot I can say except advise you to upgrade to `latest` and see if this problem persists.

**Comment by misterdjules** [comment] 2015-01-23 23:04
Not upgrading npm to a suitable version with node v0.11.15 was an oversight from me, I'll keep that in mind for future releases. Hopefully, [node v0.11.16 will ship with a more suitable version of npm](https://github.com/joyent/node/issues/9078).

Sorry for the inconvenience.

**Comment by designfrontier** [comment] 2015-01-23 23:30
sounds good @misterdjules

**Comment by misterdjules** [comment] 2015-01-28 19:16
Node.js will ship with npm 2.3.0 with the v0.11.16 release: https://github.com/joyent/node/commit/491ac6a84365e143255cd1b75717b05dadeec219.

**Comment by designfrontier** [comment] 2015-01-28 22:47
:+1:

**Comment by othiym23** [comment] 2015-01-29 02:12
Thank you again for your help with this, @misterdjules!

**Comment by othiym23** [comment] 2015-02-21 08:01
Closing as resolved.

**Closed by othiym23** 2015-02-21 08:01 UTC
Labels: node-bug, support
