### ISSUE TITLE
install bower, shasum check failed for uuid-2.0.1.tgz

### ISSUE THREAD

**Issue by xcompile** [npm/npm#9620] opened 2015-09-16 16:08 UTC
installation of bower failed during dependency resolution

    /usr/local/bin/npm install -g bower

    npm ERR! Linux 3.18.8-201.fc21.x86_64
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
    npm ERR! node v4.0.0
    npm ERR! npm  v2.14.2

    npm ERR! shasum check failed for /tmp/npm-31215-92d69860/registry.npmjs.org/uuid/-/uuid-2.0.1.tgz
    npm ERR! Expected: c2a30dedb3e535d72ccf82e343941a50ba8533ac
    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    npm ERR! From:     https://registry.npmjs.org/uuid/-/uuid-2.0.1.tgz
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/npm-debug.log

download debug log here:
http://www.filedropper.com/npm-debug

**Comment by amokan** [comment] 2015-09-16 16:09
Same issue here. Lots of flaky package installs (_and subsequent failures_) over the past 24 hours for me

**Comment by KenanY** [comment] 2015-09-16 16:17
@xcompile @amokan Please see http://status.npmjs.org/incidents/pyw00fmpjzrh

**Comment by amokan** [comment] 2015-09-16 16:19
@KenanY yep. just found that and things seem better now. Thanks!

**Comment by xcompile** [comment] 2015-09-16 16:20
@KenanY  thanks for the quick response, so I will just give it some time and check it later

**Comment by seldo** [comment] 2015-09-16 16:39
Duplicate of #9601

**Closed by seldo** 2015-09-16 16:39 UTC
