### ISSUE TITLE
Windows installs different version of package than Mac

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#7390] opened 2015-02-19 12:02 UTC
### Pretext
At a nodeschool class it happened that a member could't execute [learnyounode](https://github.com/rvagg/learnyounode). We installed on the windows system `npm i learnyounode -g` installed learnyounode in version 2.5.0. Also we did the same on a mac connected to the same network. Both systems use `node v0.12.0` and `npm v2.5.1`. 

### Current Output
[workshopper](https://github.com/rvagg/workshopper/tree/708e8d77538854751ed21d8d996d0ba6916c6f61) refers to [terminal-menu](https://github.com/rvagg/workshopper/blob/708e8d77538854751ed21d8d996d0ba6916c6f61/package.json#L20) with the version `^1.0.2`. On the mac machine `1.0.2` was installed but on the windows machine it installed `2.1.1`.

### Expected
It should be installing same version on mac and windows, shouldn't it?

### Details
At the time of writing following versions of `terminal-menu` were available:
```
{ modified: '2015-02-15T12:05:40.507Z',
     created: '2013-06-13T03:56:07.240Z',
     '0.0.0': '2013-06-13T03:56:08.277Z',
     '0.1.0': '2013-09-15T13:12:16.457Z',
     '0.2.0': '2013-09-30T13:40:42.666Z',
     '0.3.0': '2014-03-13T20:33:23.786Z',
     '0.3.1': '2014-03-13T20:37:52.770Z',
     '0.3.2': '2014-04-21T18:36:25.982Z',
```
The windows machine was a `Windows 8.1 64bit` machine. npm was running in Windows Powershell.

**Comment by smikes** [comment] 2015-02-19 13:10
I don't have the Windows side here, but I can confirm on OSX that `npm i -g learnyounode` at present depends on `terminal-menu@1.0.2` via `workshopper@2.3.1`

@martinheidegger is it safe to assume you no longer have access to the Windows machine where this happened?  If you do still have it, can you attach the result of `npm ls config` as a gist?

**Comment by martinheidegger** [comment] 2015-02-19 14:44
I don't have access anymore. It's been a fresh installation of node.js afaik.

**Comment by martinheidegger** [comment] 2015-02-19 15:38
Just checked on my home win 8.1 machine. Not reproducible there?!

**Comment by smikes** [comment] 2015-02-19 15:50
One possibility is that "npm update" got run at some point. Another one is that the .npmrc contained something other than "tag=latest". 

We can keep the issue open for a few weeks to see if it comes up again, but if we can't repro it reliably we won't be able to fix it-- but definitely ping if you see it again. And try to save the results of 

'npm config ls -l'

Thanks for the work you do with node school btw :-)

**Comment by othiym23** [comment] 2015-02-21 08:23
Closing as irreproducible! I suspect that either a bad `npm -g update` confused npm, or there was some kind of Windows path madness. Either way, if you do see this reproducibly, let us know and we'll file that as a bug, because yes, npm should always be installing the same versions of deps regardless of the OS it's running on.

**Closed by othiym23** 2015-02-21 08:23 UTC

**Comment by martinheidegger** [comment] 2015-04-03 19:46
Please reopen it. It has been reproducible by at least two other persons at nodeschool (reporting bugs). @MHolender reported it recently: https://github.com/nodeschool/discussions/issues/1024 seems like a bigger issue!

**Comment by othiym23** [comment] 2015-04-03 21:04
It's not reproducible until somebody puts together a case that yields the incorrect behavior consistently. I spent a good hour or so banging on this when this issue was first filed, and had no luck, using a stock npm and Node on stock Windows 8.1.

**Comment by martinheidegger** [comment] 2015-04-04 08:32
@othiym23 From the screenshots I get I figured that its a windows < 8 issue. Possibly vista? Also: @MHolender is atm. not available but I wanted to try to a live-chat to him. To make sure we gather more information on this. I wouldn't mind if you would have a chat/remote session with him instead :)
