### ISSUE TITLE
'Maximum call stack size exceeded' error

### ISSUE THREAD

**Issue by DmitryRomanenko** [npm/npm#10228] opened 2015-11-02 19:02 UTC
I created a virtual machine using vagrant and trying to install JS dependencies.
Since I'm using vagrant, I use `--no-bin-links` param:

```
$ npm install --no-bin-links
```

Here is my `package.json` file:

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "laravel-elixir": "^3.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}
```

But when I run `npm install --no-bin-links`, I get this error:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm install --no-bin-links
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.11

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.11
npm ERR! path npm-debug.log.b726c9784323e0605e9ff192379c7aad
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.b726c9784323e0605e9ff192379c7aad' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

And there is no `npm-debug.log.b726c9784323e0605e9ff192379c7aad` or `npm-debug.log` file.

How can I fix this problem?

**Comment by smikes** [comment] 2015-11-04 12:51
Thanks for opening this issue.

Can you tell me more about the underlying system, and how you are starting up vagrant?  I would like to try to reproduce the error.

In the meantime, you can capture the full debug log via stderr:

```
npm -ddd install --no-bin-links 2>&1 | tee node.log
```

the resulting file will be large, so please upload it as a gist https://gist.github.com and post a link as a comment in this issue.

Thanks!

**Comment by DmitryRomanenko** [comment] 2015-11-04 13:53
@smikes I created `ubuntu/trusty64` box with VirtualBox 5, installed Node 5.0

Here is the box (I removed other parts of the box and left only Node.js for you): https://github.com/DmitryRomanenko/Easy-Ansible-For-PHP/tree/npm_error
Just download it and run `vagrant up`.

After it I updated npm (`sudo npm install -g npm`), and run the command (`npm install --no-bin-links`) in `/vagrant` folder.
My host OS is Windows 10 64bit, NTFS.

> npm -ddd install --no-bin-links 2>&1 | tee node.log
I saved these logs to https://github.com/DmitryRomanenko/Easy-Ansible-For-PHP/blob/npm_error/node.log

Since node.js and npm are used for Laravel framework, and Laravel projects use vagrant, I think that it's a high priority bug.

**Comment by iamstarkov** [comment] 2015-11-06 14:24
not sure about high prio but definitily a bug

**Comment by fastest963** [comment] 2015-11-06 19:00
Related to https://github.com/npm/npm/issues/9224 https://github.com/npm/npm/issues/9953  https://github.com/npm/npm/issues/9875

**Comment by othiym23** [comment] 2016-02-24 21:10
Verified with `npm@latest` and the provided Vagrant box. Looks like this is a duplicate of #10776, because the stack trace is in `are-we-there-yet`:
```
112474 verbose stack RangeError: Maximum call stack size exceeded
112474 verbose stack     at Tracker.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:89:40)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
112474 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:28:55)
```

Having a self-contained repro case, and the use of Vagrant, makes this unique enough that it merits being left open, though.

**Comment by iarna** [comment] 2016-02-24 22:46
We have an update of `are-we-there-yet` that eliminates recursion from `completed()`, which would render this stack explosion impossible. However, cycles in the `are-we-there-yet` tree would make `emit` blow the stack instead, so we'll need to explicitly guard against them.

**Comment by iannem** [comment] 2016-03-14 11:14
Hi @iarna do we know when this fix to are-we-there-yet can make it into a release?

**Comment by zkat** [comment] 2016-08-12 23:05
@DmitryRomanenko The VM doesn't work anymore for me, so it's unclear if this is still happening.

@othiym23: you said the VM worked for you when you tried? You wanna give it a whirl, if so, and you still have it around?

**Comment by kadishmal** [comment] 2016-10-14 07:50
I've just run into this error again with Node `v6.8.0` and npm `v3.10.8`. I have `bin-link` turned OFF as well.

**Closed** 2017-06-19 10:31 UTC
Labels: big-bug, bot-closed, bug
