### ISSUE TITLE
npm view shows nothing for some packages after node 7.1.0

### ISSUE THREAD

**Issue by alanpurple** [npm/npm#14574] opened 2016-11-09 15:53 UTC
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.

#### What's going wrong?
npm view shows nothing for particular packages(e.g., webpack, npm, etc )

#### How can the CLI team reproduce the problem?

Windows 10 x64, nodeJS 7.1.0 x64, npm 3.10.9
powershell ->  npm view npm

**Comment by legodude17** [comment] 2016-11-09 18:22
Can anyone reproduce? @zkat or @KenanY?

**Comment by KenanY** [comment] 2016-11-09 18:51
Building Node.js v7.1.0 now.

**Comment by KenanY** [comment] 2016-11-09 19:12
Can't reproduce with Node.js v7.1.0, `npm@4.0.2`, on Linux. Might be worthwhile to see verbose output (i.e. `npm view -ddd npm`

**Comment by legodude17** [comment] 2016-11-09 19:34
Yes, also this might be a windows problem.

**Comment by alanpurple** [comment] 2016-11-10 01:02
@KenanY  npm view -ddd npm shows fine result

**Comment by KenanY** [comment] 2016-11-10 01:14
@alanpurple And `npm view npm` doesn't?

**Comment by alanpurple** [comment] 2016-11-10 01:16
@KenanY yes,   npm view npm......shows some "skipping blahblah" then disappears.

npm 3.10.9 with NodeJS 7.0.0 was fine

**Comment by legodude17** [comment] 2016-11-10 17:44
Can you show the output of both? Maybe in a gist?

**Comment by alanpurple** [comment] 2016-11-10 23:35
![image](https://cloud.githubusercontent.com/assets/4515120/20198778/d9b508f8-a7e9-11e6-9b43-a0392ef81706.png)

**Comment by alanpurple** [comment] 2016-11-10 23:39
I think only packages with massive versions has problem.

**Comment by legodude17** [comment] 2016-11-12 20:33
That is very odd. I think you might be right. What do you mean 'huge versions'?

**Comment by alanpurple** [comment] 2016-11-13 01:19
@legodude17 huge number of versions, huge thread of versions

**Comment by alanpurple** [comment] 2016-11-23 07:21
@legodude17 
resolved after node v7.2.0

**Comment by KenanY** [comment] 2016-11-23 16:12
Hmm, interesting. Closing as resolved then.

**Closed by KenanY** 2016-11-23 16:12 UTC
Labels: needs-repro, support
