### ISSUE TITLE
Windows 7 npm or proxy issue?

### ISSUE THREAD

**Issue by lbod** [npm/npm#3642] opened 2013-07-10 09:20 UTC
I've been trying to use msysgit on a Win 7 box at work. We have corporate firewalls and I use the CNTLM proxy to authenticate me to them,
I'm able to use git fine and npm however when I try and install this package : 
```
npm install intern
```
It fails apparently due to a network issue at the point when it tries to clone the package dependency git ref here:
```
"dojo": "git+https://github.com/csnover/dojo2-core.git#dfc5449"

    with the error:
650 error Error: Command failed: error: Couldn't resolve host 'github.com' while accessing https://github.com/csnover/dojo2-core.git/info/refs?service=git-upload-pack

```

However I can clone this repo successfully if I do it manually using:

```
git clone --verbose https://github.com/csnover/dojo2-core.git #dfc5449
```

I've attached the npm debug log http://jsfiddle.net/wfFPS/

**Comment by smikes** [comment] 2015-02-03 20:54
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 2013.  Specific to you issue, there have been changes to the way the `request` module works with proxies. Can you try updating your npm installation?

To update node and npm on Windows, first install the latest `node` package <https://nodejs.com/download> and then follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-02-12 02:16
Closing as abandoned.

**Closed by othiym23** 2015-02-12 02:16 UTC
Labels: support, windows

**Comment by dargoan** [comment] 2015-08-12 12:41
Yes, i think it's better to close it, as i changed my computer and i'm not able anymore to reproduce the issue i had.
But thanks anyway for answering and the help.
