### ISSUE TITLE
NPM 3.10.7 search out of memory

### ISSUE THREAD

**Issue by palmerj3** [npm/npm#13742] opened 2016-08-23 17:19 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I perform a search e.g. `npm search highcharts` I get a fatal error that JavaScript heap is out of memory.

#### How can the CLI team reproduce the problem?

`npm install -g npm@3.10.7`
`npm search highcharts`

Observe out of heap error.

### supporting information:

 - `npm -v` prints:
3.10.7
 - `node -v` prints:
v6.3.1

 - `npm config get registry` prints:
https://registry.npmjs.org/

 - Windows, OS X, or Linux?:
OS X

 - Network issues:
   - Geographic location where npm was run: NYC, USA.
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2016-08-23 21:32
Hey, there's some [work in progress](https://github.com/npm/npm/pull/10615) to fix these issues in general and have a fully-streamed search on the CLI. Stand by for news on that. There's dupes of this but I'll hunt them down and mark them as such later. I picked up the work from @aredridel and I'm finishing up and polishing some changes :)

**Comment by zkat** [comment] 2016-08-23 23:36
Closing as a duplicate of https://github.com/npm/npm/issues/12619

**Closed by zkat** 2016-08-23 23:36 UTC
Labels: big-bug, bug, search
