### ISSUE TITLE
npm link breaks npm install under some conditions on 3.X

### ISSUE THREAD

**Issue by clux** [npm/npm#10800] opened 2015-12-12 12:28 UTC
If you issue `npm install` in a module with multiple `npm link`d dependencies strange things can happen.

After a lot of bisecting, this is the smallest set of modules that I have managed to reproduce the install failures this with:

```sh
git clone https://github.com/clux/smell
git clone https://github.com/clux/ffa
git clone https://github.com/clux/tiebreaker
cd smell
npm install
npm link
cd ../ffa
npm link smell
npm install
npm link
cd ../tiebreaker
npm link smell ffa
npm install
```

The last instruction will fail with

```
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/clux/local/node-v5.2.0/bin/node" "/home/clux/local/node/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! path /home/clux/testrepos/tiebreaker/node_modules/escodegen/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/clux/testrepos/tiebreaker/node_modules/escodegen/node_modules/esprima/bin/esparse.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/clux/testrepos/tiebreaker/npm-debug.log
```

And what's worse, the first module's `node_modules` folder (`smell/node_modules`) disappears during the last failed install!

By doing `npm install` inside `tiebreaker` without first issuing `npm link smell ffa` (or by just blatting `./node_modules` after), it will succeed.

This kind of mechanic of making the least dependent modules link-availble first, then installing the rest all worked flawlessly on huge module sets with npm@2, but now I pretty much have to restrict `link` to the occasional manual hack. The more modules I put in, it may still work, but there will be loads more `skippingAction Module is inside a symlinked module` warnings, and more often than not, there will something that breaks it. This example does not have any warnings, it just breaks at the last state, leaving my folders broken in the process.

**Comment by KamranMackey** [comment] 2015-12-12 22:12
Once again, another issue where somebody is running an old version of npm. Update fricken npm version.

**Comment by clux** [comment] 2015-12-12 22:38
This is the version that is bundled with node 5.2.0 - and I can't upgrade npm inside docker so it's a pain to test.

Local test on the latest npm does also fail it seems though, but differently:

```sh
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/node-v5.2.0/bin/node" "/usr/local/node/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! path /home/clux/testrepos/tiebreaker/node_modules/smell/node_modules/escodegen/node_modules/.bin/esparse
npm ERR! code EEXIST

npm ERR! Refusing to delete /home/clux/testrepos/tiebreaker/node_modules/smell/node_modules/escodegen/node_modules/.bin/esparse: containing path /home/clux/testrepos/tiebreaker/node_modules/smell/node_modules/escodegen/node_modules/esprima isn't under npm's control
npm ERR! File exists: /home/clux/testrepos/tiebreaker/node_modules/smell/node_modules/escodegen/node_modules/.bin/esparse
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/clux/testrepos/tiebreaker/npm-debug.log
```

Doesn't seem to delete anything at least though.

**Comment by Reinmar** [comment] 2015-12-13 18:09
I had very similar (if not exactly the same) issues. First, running Node 5.2.0 with npm 3.3.12 I had what looked like problems described by @clux's in the first post. Then I upgraded npm and I encountered what @clux's described in https://github.com/npm/npm/issues/10800#issuecomment-164199517. 

I would post my `npm-debug.log` file but due to #10804/#10801 I can't install anything right now :(.

**Comment by Reinmar** [comment] 2015-12-13 22:23
After few more tries (and restarting the OS – maybe this was what helped with #10804/10801) I've reproduced this issue again.

npm-debug.log: https://gist.github.com/Reinmar/7eb57d557d252c689de0

To reproduce it seems that it's enough to `npm link ckeditor5-core` (https://github.com/ckeditor/ckeditor5-core) inside https://github.com/ckeditor/ckeditor5 and run `npm install` first in ckeditor5-core and then in ckeditor5.

**Comment by lancedikson** [comment] 2016-01-04 09:20
Seems like the same error for me. 
I have one main package, that has dependencies tree with several linked packages chain:
```
quch-api
— quch-api-v1
—— quch-models
—— quch-constants
—— quch-core
——— quch-constants
…
```

All these `quch`-packages on development stage now and they were linked as global by `npm link`.
Next, I made `npm i` for every package. Now, when I try to run `npm i` for main package (`quch-api`) it throws error.

Node 4.2.4, npm 3.5.2.
[npm-debug.log](https://gist.github.com/lancedikson/ff7e377217795064b0de)

Am I right about the similarity of the issue or not?

**Comment by rosskevin** [comment] 2016-02-08 16:00
I bumped into this same thing, my npm version was way! out of date.  `npm install -g npm` (not tat 3.7.1) solved the problem with npm link related projects.

It's easy to forget to update npm, I wish it had a reminder for me to keep it up to date when it falls behind.  Bower does this and I find it quite useful, albeit I'm now fully on npm for packages.

**Comment by othiym23** [comment] 2016-02-08 16:32
@rosskevin, see #11473 – that's a good idea. Thanks for suggesting it!

**Comment by NiXXeD** [comment] 2016-04-28 19:29
I'm running into this issue as well. Using latest npm from installing node v6.

We use many `npm link`'d modules for local development, and this almost entirely stops us from developing as a result. I'm just using latest 2.x for now.

**Comment by iarna** [comment] 2016-05-12 19:48
Status update: I have a fix for this that needs a little more shaking out before I'm totally confident with it. I think I'll be able to get it there for next week's release, so I'm going to just bump the milestone out to there.

**Comment by schmod** [comment] 2016-05-23 14:04
FYI: The symptoms of this look a lot like #10343.

**Comment by iarna** [comment] 2016-05-26 04:33
@schmod Yeah, I agree, I'll make sure tests for the fix to this encompass both scenarios.

**Closed** 2016-06-17 02:28 UTC
Labels: big-bug, bug, link
