### ISSUE TITLE
Bower won't install globally on OS X

### ISSUE THREAD

**Issue by kdbanman** [npm/npm#5732] opened 2014-07-19 16:34 UTC
I'm on OS X 10.8.5, running node 0.10.11 and npm 1.2.30.  Trying to globally install bower with this command:

    sudo npm install -g bower

But I'm consistently getting this in my `npm-debug.log`:

    2872 error Error: ENOENT, lstat 

    '/usr/local/share/npm/lib/node_modules/bower/node_modules/semver/semver.browser.js'
    2873 error If you need help, you may report this log at:
    2873 error     <http://github.com/isaacs/npm/issues>
    2873 error or email it to:
    2873 error     <npm-@googlegroups.com>
    2874 error System Darwin 12.5.0
    2875 error command "/usr/local/Cellar/node/0.10.11/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
    2876 error cwd /Users/kdbanman
    2877 error node -v v0.10.11
    2878 error npm -v 1.2.30
    2879 error path /usr/local/share/npm/lib/node_modules/bower/node_modules/semver/semver.browser.js
    2880 error fstream_path /usr/local/share/npm/lib/node_modules/bower/node_modules/semver/semver.browser.js
    2881 error fstream_type File
    2882 error fstream_class FileWriter
    2883 error code ENOENT
    2884 error errno 34
    2885 error fstream_stack /usr/local/Cellar/node/0.10.11/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
    2885 error fstream_stack Object.oncomplete (fs.js:107:15)

Any help would be appreciated :)

**Comment by smikes** [comment] 2015-01-28 18:46
Is this still a problem for you?

This looks like one of the problems caused by race conditions that were mostly eliminated in npm@2 -- the latest version is 2.3.0 and reports of these problems have dropped off substantially. 

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.5. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by tonyjessup** [comment] 2015-01-28 19:19
Installing bower globally on osx 10.10 using node 0.10.31 and npm 1.4.26
just worked fine for me now thanks for the followup!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Tony Jessup | tonyjessup.com | @tonypjessup
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by othiym23** [comment] 2015-02-20 22:06
Closing as resolved.

**Closed by othiym23** 2015-02-20 22:06 UTC
Labels: support
