### ISSUE TITLE
estraneous err with  jquery@3.0.0-beta1

### ISSUE THREAD

**Issue by catafest** [npm/npm#11187] opened 2016-01-17 13:31 UTC
I make one dir to test named test-npm and I install last version of jquery but I got this error.

test-npm@1.0.0 C:\Program Files (x86)\nodejs\test-npm
└── jquery@3.0.0-beta1 extraneous

npm ERR! extraneous: jquery@3.0.0-beta1 C:\Program Files (x86)\nodejs\test-npm\node_modules\jquery

**Comment by othiym23** [comment] 2016-01-18 03:46
This looks like the expected behavior to me, assuming you did something like the following:

```
C:\Program Files (x86)\nodejs> mkdir test-npm
C:\Program Files (x86)\nodejs> cd test-npm
C:\Program Files (x86)\nodejs\test-npm> npm install jquery
C:\Program Files (x86)\nodejs\test-npm> npm ls
```

Because you haven't saved the new dependency to `package.json` (perhaps by adding `--save` or `-S` to your install command), `npm ls` is telling you that the package is extraneous and going to be removed when you run `npm prune` or otherwise reset your `node_modules` folder.

Because this is npm doing what it's supposed to do, I'm going to close this, but let me know if you have further questions.

**Closed by othiym23** 2016-01-18 03:46 UTC
Labels: support
