### ISSUE TITLE
files attribute not respected? 

### ISSUE THREAD

**Issue by hemanth** [npm/npm#13024] opened 2016-06-11 14:34 UTC
This issue is wrt to [head-it](https://github.com/hemanth/head-it/issues/1#issuecomment-224832084).

```
$  tar -ztvf $(npm pack)
-rw-r--r--  1 120017702  120017702 602 May 31 19:54 package/package.json
-rw-r--r--  1 120017702  120017702 350 May 31 19:44 package/index.js
-rwxr-xr-x  1 120017702  120017702 432 May 31 19:42 package/cli.js
-rw-r--r--  1 120017702  120017702 12856 May 31 19:46 package/head.js
-rw-r--r--  1 120017702  120017702  1109 May 31 18:34 package/license
-rw-r--r--  1 120017702  120017702  1135 May 31 19:54 package/readme.md
```

`"node": ">=4"`

Seeking help //cc @isaacs

**Comment by othiym23** [comment] 2016-06-13 21:25
Closing as duplicate of #5082.

**Closed by othiym23** 2016-06-13 21:25 UTC
Labels: bug
