### ISSUE TITLE
npm installs incorrect dependencies for package A when optional dependency B is present

### ISSUE THREAD

**Issue by jwalton** [npm/npm#14262] opened 2016-10-12 17:02 UTC
#### I'm opening this issue because:
-  npm is producing an incorrect install.
#### What's going wrong?

npm installs incorrect version of a dependency when (somewhat) unrelated optionalDependency is present.
#### How can the CLI team reproduce the problem?

browserifyTest.js:

```
"use strict";
let browserify = require('browserify');
let b = browserify();
b.require('./foo');
b.bundle().pipe(process.stdout);
```

foo.js:

```
exports.foo = function() {console.log("Hello world");};
```

package.json:

```
{
  "name": "browserify-test",
  "version": "1.0.0",
  "devDependencies": {
    "browser-pack": "^2.0.0",
    "browserify": "^13.1.0"
  },
  "optionalDependencies": {
    "browserify-middleware": "*"
  }
}
```

Run:

```
rm -rf node_modules/ && npm install && node ./browserifyTest.js
```

This will produce output that starts with:

```
(function e(t,n,r){...
```

It _should_ produce output that starts with:

```
require=(function e(t,n,r){...
```

If you do any one of the following, the correct output is produced:
- Remove the dependency on browser-pack@^2.0.0.
- Remove the optional dependency on browserify-middleware.
- Change browserify-middleware from an optional dependency to a regular dependency.
- `npm install browserify@3.1.0` after `npm install`.

None of these changes _should_ affect the output, but all of them correct the problem.

The problem appears to be the browserify ends up running with browser-pack@2.0.1, despite the fact that browserify [requires browser-pack@^6.0.1](https://github.com/substack/node-browserify/blob/13.1.0/package.json#L25).  If you use the package.json as shown above, you'll see that node_modules/browse-pack is v2.0.1.  We would expect node_modules/browserify/node_modules/browser-pack to exist and be v6.0.1 (and this is exactly what happens if you do any of the fixes above, aside from the first), however instead node_modules/browserify/node_modules does not even exist.
### supporting information:
- `npm -v` prints: 3.10.9
- `node -v` prints: v4.2.3
- `npm config get registry` prints: https://registry.npmjs.org/
- os/x: 10.11.4

**Comment by zkat** [comment] 2016-12-02 19:49
This may have been fixed by https://github.com/npm/npm/pull/12811 and may be a duplicate of https://github.com/npm/npm/issues/10727. Could you try doing `npm install -g npm@4.0.5` and see if it fixes the problem for you? I'll leave it open until then.

**Comment by zkat** [comment] 2016-12-10 23:51
When running the repro steps myself with `npm@3.10.9`, I got the following:
```
$ npm ls browser-pack
test@1.0.0 /Users/zkat/Documents/code/test
├── browser-pack@2.0.1 
└─┬ browserify@13.1.1
  └── UNMET DEPENDENCY browser-pack@^6.0.1

npm ERR! missing: browser-pack@^6.0.1, required by browserify@13.1.1
```

After `npm@4.0.5`, I get the following after a fresh install:
```
$ npm ls browser-pack
test@1.0.0 /Users/zkat/Documents/code/test
├── browser-pack@2.0.1 
└─┬ browserify@13.1.1
  └── browser-pack@6.0.2 
```

Closing as fixed, since things should be using the correct versions now.

**Closed by zkat** 2016-12-10 23:51 UTC
Labels: big-bug
