### ISSUE TITLE
Cannot install core plugins

### ISSUE THREAD

**Issue by evanyeyeye** [npm/npm#12457] opened 2016-04-24 20:11 UTC
I have tried reinstalling heroku toolbelt, ruby, and nodejs. How do I fix this problem???

```
PS C:\Users\Evan\Documents\PakaBot> heroku
heroku-cli: Installing core plugins (retrying)... !
 !    Error installing package.
 !    npm ERR! Windows_NT 10.0.10586
 !    npm ERR! argv "C:\\Users\\Evan\\AppData\\Local\\heroku\\node-5.10.1-windows-386\\node.exe" "C:\\Users\\Evan\\AppDa
ta\\Local\\heroku\\npm-3.8.5\\cli.js" "install" "heroku-apps" "heroku-cli-addons" "heroku-fork" "heroku-git" "heroku-loc
al" "heroku-orgs" "heroku-pipelines" "heroku-run" "heroku-spaces" "heroku-status"
 !    npm ERR! node v5.10.1
 !    npm ERR! npm  v3.8.5
 !
 !    npm ERR! shasum check failed for C:\Users\Evan\AppData\Local\Temp\npm-416-10af59ed\cli-npm.heroku.com\heroku-apps\
-\heroku-apps-2.0.2\1a0f75f87427a574a552db12c877ed712a362f9e.tgz
 !    npm ERR! Expected: 1a0f75f87427a574a552db12c877ed712a362f9e
 !    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
 !    npm ERR! From:     https://cli-npm.heroku.com/heroku-apps/-/heroku-apps-2.0.2/1a0f75f87427a574a552db12c877ed712a36
2f9e.tgz
 !    npm ERR!
 !    npm ERR! If you need help, you may report this error at:
 !    npm ERR!     <https://github.com/npm/npm/issues>
 !
 !    npm ERR! Please include the following file with any support request:
 !    npm ERR!     C:\Users\Evan\AppData\Local\heroku\npm-debug.log
 !
 !    Try running again with GODE_DEBUG=info to see more output.
 !    error getting commands pid 5760 exit 1
```

**Comment by pazams** [comment] 2016-04-27 21:43
happens to me too

**Comment by zkat** [comment] 2016-12-09 00:41
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:41 UTC
Labels: network, support
