### ISSUE TITLE
npm self-update caching issues ?

### ISSUE THREAD

**Issue by DarkMukke** [npm/npm#16986] opened 2017-06-05 13:06 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I had to run the installer twice for it to realize it was updated,
maybe the new progressive caching is a bit too progressive.

#### How can the CLI team reproduce the problem?

Not sure how to reproduce but here is my log : 

```bash
[root@dev ~]# npm i -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
updated 255 packages in 24.936s
[root@dev ~]# npm -v
5.0.2


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.0.1 → 5.0.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

[root@dev ~]# npm i -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
+ npm@5.0.2
updated 1 package in 16.555s
[root@dev ~]# npm -v
5.0.2
[root@dev ~]#

```

**Comment by zkat** [comment] 2017-06-05 16:53
Closing as dupe of https://github.com/yeoman/update-notifier/issues/67

**Closed as completed by zkat** 2017-06-05 16:53 UTC
