### ISSUE TITLE
`npm publish` dies if node_modules exists

### ISSUE THREAD

**Issue by donabrams** [npm/npm#9435] opened 2015-08-28 21:44 UTC
If I have a node_modules directory (after an `npm install`) then npm publish crashes on me hard:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/don.abrams/.nvm/versions/io.js/v2.3.3/bin/iojs',
1 verbose cli   '/Users/don.abrams/.nvm/versions/io.js/v2.3.3/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@3.3.1
3 info using node@v2.3.3
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/don.abrams/workspace/test',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/don.abrams/.npm/npm-bug/1.0.1/package.tgz not in flight; packing
9 info lifecycle npm-bug@1.0.1~prepublish: npm-bug@1.0.1
10 silly lifecycle npm-bug@1.0.1~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/Users/don.abrams/.npm/npm-bug/1.0.1/package.tgz',
11 verbose tar pack   '/Users/don.abrams/workspace/test' ]
12 verbose tarball /Users/don.abrams/.npm/npm-bug/1.0.1/package.tgz
13 verbose folder /Users/don.abrams/workspace/test
14 verbose stack RangeError: Maximum call stack size exceeded
14 verbose stack     at byteLength (buffer.js:288:20)
14 verbose stack     at fromString (buffer.js:65:16)
14 verbose stack     at new Buffer (buffer.js:48:5)
14 verbose stack     at encodeField (/Users/don.abrams/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:186:16)
14 verbose stack     at /Users/don.abrams/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:145:29
14 verbose stack     at Array.forEach (native)
14 verbose stack     at encodeFields (/Users/don.abrams/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:99:23)
14 verbose stack     at /Users/don.abrams/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:139:7
14 verbose stack     at Array.forEach (native)
14 verbose stack     at encodeFields (/Users/don.abrams/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:99:23)
15 verbose cwd /Users/don.abrams/workspace/test
16 error Darwin 13.4.0
17 error argv "/Users/don.abrams/.nvm/versions/io.js/v2.3.3/bin/iojs" "/Users/don.abrams/.nvm/versions/io.js/v2.3.3/bin/npm" "publish"
18 error node v2.3.3
19 error npm  v3.3.1
20 error Maximum call stack size exceeded
21 error If you need help, you may report this error at:
21 error     <https://github.com/npm/npm/issues>
22 verbose exit [ 1, true ]
```
package.json:
```json
{
  "name": "npm-bug",
  "version": "1.0.1",
  "dependencies": {
    "body-parser": "^1.13.2"
  }
}
```

This is terribly annoying for publishing. Probably related: #9224

**Comment by othiym23** [comment] 2015-08-28 21:51
This is indeed a duplicate of #9239 and #9224, and so I'm going to close it as such. It's not the presence of `node_modules` that triggers the bug, but what's _in_ `node_modules`, and @iarna hasn't been able to isolate what exactly causes `npm@3` to go off to the moon yet (so thanks for the additional repro information). You're completely right that it's very annoying, which is why both #9224 and #9239 are marked as blockers to the wider `npm@3` release. Thanks for filing this!

**Closed by othiym23** 2015-08-28 21:51 UTC

**Comment by othiym23** [comment] 2015-08-28 21:54
As an example of why this has been so hard to fix:

```
bauchelain% mkdir test-publish-to-the-moon
bauchelain% cd test-publish-to-the-moon
bauchelain% cat > package.json
{
  "name": "npm-bug",
  "version": "1.0.1",
  "dependencies": {
    "body-parser": "^1.13.2"
  }
}
bauchelain% npm install
npm-bug@1.0.1 /Users/ogd/Documents/projects/test-publish-to-the-moon
└─┬ body-parser@1.13.3
  ├── bytes@2.1.0
  ├── content-type@1.0.1
  ├─┬ debug@2.2.0
  │ └── ms@0.7.1
  ├── depd@1.0.1
  ├─┬ http-errors@1.3.1
  │ ├── inherits@2.0.1
  │ └── statuses@1.2.1
  ├── iconv-lite@0.4.11
  ├─┬ on-finished@2.3.0
  │ └── ee-first@1.1.1
  ├── qs@4.0.0
  ├─┬ raw-body@2.1.2
  │ └── unpipe@1.0.0
  └─┬ type-is@1.6.7
    ├── media-typer@0.3.0
    └─┬ mime-types@2.1.5
      └── mime-db@1.17.0

npm WARN EPACKAGEJSON npm-bug@1.0.1 No description
npm WARN EPACKAGEJSON npm-bug@1.0.1 No repository field.
npm WARN EPACKAGEJSON npm-bug@1.0.1 No license field.
bauchelain% npm publish
+ npm-bug@1.0.1
bauchelain% npm unpublish -f npm-bug
npm WARN using --force I sure hope you know what you are doing.
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
bauchelain% npm -v
3.3.1
```

:grimacing: (also, if you want to try publishing this in the future, you'll probably need to bump the patch version ;)
