### ISSUE TITLE
Update package to the latest version compatible with the range listed in package.json

### ISSUE THREAD

**Issue by UltCombo** [npm/npm#6549] opened 2014-10-23 05:25 UTC
As the title suggests, I want to update an installed package to the latest version available which satisfies the version range listed in the `package.json`.

For instance, using Grunt.js as an example:

Assume I have Grunt 3.x installed, the `package.json` containing:

```
  "devDependencies": {
    "grunt": "^0.3.15"
  },
```

For a practical test case, the above `package.json` can be reproduced with:

```
npm i --save-dev grunt@0.3.15
```

Now, I want to install the given package's latest version which is still compatible with the range listed in `package.json` (in this case, the latest Grunt 0.3.x).

From testing and fiddling around, I've found that this does exactly what I want:

```
npm i grunt
```

The command above, when executed in a directory containing a `package.json` with a `"grunt": "^0.3.15"` dependency, will install Grunt 0.3.17 (the current latest version compatible with the ^0.3.15 range). To be clear, the behavior I seek is:

- Should update a package to the latest version which satisfies the version range determined in the `package.json`'s `dependencies`/`devDependencies`;
- Should check if there are new versions of the package and its dependencies even if the given package is already installed in the `node_modules` directory;
- Should be **recursive**: it should walk the given package's whole dependency tree, updating dependencies to the latest version which satisfies the given version range listed in its parent's `package.json`.

Looks like `npm install packageName` satisfies all my conditions above. However, I could not find this behavior documented anywhere. Is all this behavior actually expected? What I mean is, is this future-proof? Can I rely on this behavior for updating my dependencies to their latest compatible version? If so, it may be worth adding a note to the [npm-install docs](https://www.npmjs.org/doc/cli/npm-install.html).

Thanks for your time.

**Comment by smikes** [comment] 2015-02-22 00:23
It looks like you might actually want

```
npm update packagename
```

which does **try** to honor semver, and does **recursively** update all the dependencies of `packagename`.  Of course, it does them all recursively asynchronously at once.

If you can give up the need for updating deps-of-deps, then you can get pretty far with

```
npm --depth 0 update grunt
```

Which does update to 0.3.17 in the example given in your first post, above.

**Comment by UltCombo** [comment] 2015-02-22 00:47
@smikes Oh nice. Indeed, `npm update` seems to do exactly what I want. However, the [documentation](https://docs.npmjs.com/cli/update) seems outdated:

> This command will update all the packages listed to the latest version (specified by the `tag` config).

I believe "latest version" should read "latest **compatible** version", or similar.

**Comment by smikes** [comment] 2015-02-22 01:10
That's a good point. I think it would be best to have some concrete examples, actually. I will create a new issue for that.

**Comment by UltCombo** [comment] 2015-02-22 04:44
Examples would be really nice, indeed.

Back to the main topic, my actual use case does need to update deps-of-deps, and I just realized `npm update packagename` will not update `packagename`'s deps when `packagename` is already at the latest version. I've worked around this by passing the name of the deps-of-deps that I want to be updated to `npm update`.

The alternative solution `rm -rf node_modules && npm install` does not work for me as `npm install` without arguments invokes the `prepublish` script which breaks my use case, and `--ignore-scripts` is frowned upon as it can have undesired side-effects.

**Comment by othiym23** [comment] 2015-02-22 04:46
@UltCombo in your case, I think you probably want to wait for `npm@3`, then, which should handle this case better (right, @iarna?).

**Comment by UltCombo** [comment] 2015-02-22 04:54
For the time being, I guess it is probably best to just `npm install packagename@majorVersionNumber` when updating packages and their dependencies. This requires knowing the current major version of the package I'm updating, but it seems to accomplish what I'm looking for.

I've also considered `npm rm packagename && npm install packagename`, but it looks like `npm install` does not respect the version listed in `package.json`'s `devDependencies` (though it does respect the version for regular `dependencies`). This is a bit confusing IMO, perhaps it could do with some documentation improvements?

@othiym23 Oh nice, I'm curious as to what will change in npm v3 regarding this. `=]`

**Comment by othiym23** [comment] 2016-09-21 20:53
`npm@3` does fix this a bit, in that it makes the separation of responsibilities of `npm install` and `npm update` clearer. In the case of `npm install`, if there’s a version of the package that matches the semver range in the current tree’s `package.json`, the installer will consider that version sufficient and not do anything. In the case of `npm update`, it will update the dependencies to the maximum version of the package that satisfies the semver range.

There are a couple wrinkles, though!

`npm update`, by default, will only update the top-level dependencies. This is because update used to do… questionable things when run at all levels of the install tree, which is what used to cause `npm update -g` to scramble your global installs, including sometimes breaking npm itself. If you want to update the whole tree, you’ll need to include something like `--depth=12` as an argument.
`npm update --save` [is](https://github.com/npm/npm/issues/11622) [broken](https://github.com/npm/npm/issues/13555), in that it _will_ update all your `dependencies` and `devDependencies` (if you use `--dev`), and save the updated semver ranges for the dependencies it updates. Sounds good, except for the part where it puts them all in `dependencies` – including transitive dependencies (i.e. dependencies of dependencies) and `devDependencies`. This is a regression and should be fixed, but until then, you’ll need to update the ranges by hand, or continue to use `npm i -S`.

I believe the behavior of update is adequately described by the current documentation, although it doesn’t take into account the bugs mentioned above (and I’m not sure what it would say about the CLI team if incorporated bugs in the documentation?). As such, I think we’ve addressed the issue here, and so am going to close this feature request. Thanks for your time!

**Closed by othiym23** 2016-09-21 20:53 UTC
Labels: documentation, feature-request
