### ISSUE TITLE
`npm prune` removes dependencies it shouldn't

### ISSUE THREAD

**Issue by Moeriki** [npm/npm#15069] opened 2016-11-30 08:47 UTC
#### I'm opening this issue because:

  - npm is producing an incorrect install.
  - npm is doing something I don't understand.

#### What's going wrong?

`npm prune` removes dependencies (I think) it shouldn't.

#### How can the CLI team reproduce the problem?

```shell
git clone git@github.com:Moeriki/jest-test.git
cd jest-test
npm install
npm test # succeeds
npm prune
npm test # fails because missing dependencies
```

Why does npm removes packages it just deemed necessary to install?

### supporting information:

 - `npm -v` prints: `3.10.10` / `4.0.2`
 - `node -v` prints: `4.6.2` / `6.9.1` // reproducible across these node / npm versions
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.12.1
 - Geographic location where npm was run: Belgium
 - ~Network issues~
 - ~Container~

References:
* [4573](https://github.com/npm/npm/issues/4573) may be related
* [9889](https://github.com/npm/npm/issues/9889) may be related
* [jest/2181](https://github.com/facebook/jest/issues/2181) original report

**Comment by KenanY** [comment] 2016-11-30 14:08
I can't reproduce this with Node.js v7.1.0 and `npm@4.0.2`:

```
$ git clone https://github.com/Moeriki/jest-test.git
$ cd jest-test/
$ npm install
$ npm test

> jest-test@1.0.0 test /tmp/jest-test
> jest

No tests found
No files found in /tmp/jest-test.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html

$ npm prune
$ npm test

> jest-test@1.0.0 test /tmp/jest-test
> jest

No tests found
No files found in /tmp/jest-test.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
```

**Comment by Moeriki** [comment] 2016-11-30 14:39
I can reproduce this with node v7.2.0 and `npm@4.0.2`

```shell
~/Projects/jest-test master
λ node --version
v7.2.0
                                                                                
~/Projects/jest-test master
λ npm --version
4.0.2
                                                                                
~/Projects/jest-test master
λ npm install
npm WARN jest-test@1.0.0 No description
npm WARN jest-test@1.0.0 No repository field.
                                                                                
~/Projects/jest-test master
λ npm test

> jest-test@1.0.0 test /Users/moeriki/Projects/jest-test
> jest

 PASS  ./index.test.js
  ✓ should pass (2ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.636s, estimated 1s
Ran all test suites.
                                                                                
~/Projects/jest-test master
λ npm prune
npm WARN package.json jest-test@1.0.0 No description
npm WARN package.json jest-test@1.0.0 No repository field.
npm WARN package.json jest-test@1.0.0 No README data
unbuild abab@1.0.3
unbuild abbrev@1.0.9
unbuild acorn-globals@1.0.9
unbuild align-text@0.1.4
unbuild amdefine@1.0.1
unbuild ansi-escapes@1.4.0
unbuild ansi-regex@2.0.0
unbuild ansi-styles@2.2.1
unbuild ansicolors@0.2.1
unbuild append-transform@0.3.0
unbuild argparse@1.0.9
unbuild arr-diff@2.0.0
unbuild arr-flatten@1.0.1
unbuild array-differ@1.0.0
unbuild array-equal@1.0.0
unbuild array-union@1.0.2
unbuild array-uniq@1.0.3
unbuild array-unique@0.2.1
unbuild arrify@1.0.1
unbuild asn1@0.2.3
unbuild assert-plus@0.2.0
unbuild async@1.5.2
unbuild asynckit@0.4.0
unbuild aws-sign2@0.6.0
unbuild aws4@1.5.0
unbuild babel-code-frame@6.16.0
unbuild babel-generator@6.19.0
unbuild babel-core@6.18.2
unbuild babel-helpers@6.16.0
unbuild babel-jest@17.0.2
unbuild babel-plugin-istanbul@2.0.3
unbuild babel-messages@6.8.0
unbuild babel-plugin-jest-hoist@17.0.2
unbuild babel-preset-jest@17.0.2
unbuild babel-register@6.18.0
unbuild babel-runtime@6.18.0
unbuild babel-template@6.16.0
unbuild babel-traverse@6.19.0
unbuild babel-types@6.19.0
unbuild balanced-match@0.4.2
unbuild bcrypt-pbkdf@1.0.0
unbuild boom@2.10.1
unbuild brace-expansion@1.1.6
unbuild braces@1.8.5
unbuild browser-resolve@1.11.2
unbuild bser@1.0.2
unbuild builtin-modules@1.1.1
unbuild callsites@2.0.0
unbuild camelcase@1.2.1
unbuild caseless@0.11.0
unbuild center-align@0.1.3
unbuild chalk@1.1.3
unbuild ci-info@1.0.0
unbuild cli-table@0.3.1
unbuild cli-usage@0.1.4
unbuild cliui@2.1.0
unbuild clone@1.0.2
unbuild code-point-at@1.1.0
unbuild colors@1.0.3
unbuild combined-stream@1.0.5
unbuild commander@2.9.0
unbuild concat-map@0.0.1
unbuild content-type-parser@1.0.1
unbuild convert-source-map@1.3.0
unbuild core-js@2.4.1
unbuild cssom@0.3.1
unbuild cryptiles@2.0.5
unbuild cssstyle@0.2.37
unbuild dashdash@1.14.1
unbuild debug@2.3.3
unbuild decamelize@1.2.0
unbuild deep-is@0.1.3
unbuild delayed-stream@1.0.0
unbuild detect-indent@4.0.0
unbuild diff@3.1.0
unbuild ecc-jsbn@0.1.1
unbuild error-ex@1.3.0
unbuild escape-string-regexp@1.0.5
unbuild estraverse@1.9.3
unbuild esutils@2.0.2
unbuild exec-sh@0.2.0
unbuild expand-brackets@0.1.5
unbuild expand-range@1.8.2
unbuild extend@3.0.0
unbuild extglob@0.3.2
unbuild extsprintf@1.0.2
unbuild fast-levenshtein@2.0.5
unbuild fb-watchman@1.9.0
unbuild filename-regex@2.0.0
unbuild fileset@0.2.1
unbuild fill-range@2.2.3
unbuild find-up@1.1.2
unbuild for-in@0.1.6
unbuild for-own@0.1.4
unbuild forever-agent@0.6.1
unbuild form-data@2.1.2
unbuild fs.realpath@1.0.0
unbuild generate-function@2.0.0
unbuild generate-object-property@1.2.0
unbuild get-caller-file@1.0.2
unbuild getpass@0.1.6
unbuild glob@5.0.15
unbuild glob-base@0.3.0
unbuild glob-parent@2.0.0
unbuild globals@9.14.0
unbuild graceful-fs@4.1.11
unbuild graceful-readlink@1.0.1
unbuild growly@1.3.0
unbuild has-ansi@2.0.0
unbuild has-flag@1.0.0
unbuild hawk@3.1.3
unbuild hoek@2.16.3
unbuild home-or-tmp@2.0.0
unbuild hosted-git-info@2.1.5
unbuild html-encoding-sniffer@1.0.1
unbuild http-signature@1.1.1
unbuild iconv-lite@0.4.15
unbuild inflight@1.0.6
unbuild inherits@2.0.3
unbuild invariant@2.2.2
unbuild invert-kv@1.0.0
unbuild is-arrayish@0.2.1
unbuild is-builtin-module@1.0.0
unbuild is-buffer@1.1.4
unbuild is-ci@1.0.10
unbuild is-dotfile@1.0.2
unbuild is-equal-shallow@0.1.3
unbuild is-extendable@0.1.1
unbuild is-extglob@1.0.0
unbuild is-finite@1.0.2
unbuild is-fullwidth-code-point@1.0.0
unbuild is-glob@2.0.1
unbuild is-my-json-valid@2.15.0
unbuild is-number@2.1.0
unbuild is-posix-bracket@0.1.1
unbuild is-primitive@2.0.0
unbuild is-property@1.0.2
unbuild is-typedarray@1.0.0
unbuild is-utf8@0.2.1
unbuild isarray@1.0.0
unbuild isexe@1.1.2
unbuild isobject@2.1.0
unbuild isstream@0.1.2
unbuild istanbul-api@1.0.0-aplha.10
unbuild istanbul-lib-coverage@1.0.0
unbuild istanbul-lib-hook@1.0.0-alpha.4
unbuild istanbul-lib-instrument@1.3.0
unbuild istanbul-lib-report@1.0.0-alpha.3
unbuild istanbul-lib-source-maps@1.1.0
unbuild istanbul-reports@1.0.0
unbuild jest-changed-files@17.0.2
unbuild jest-config@17.0.3
unbuild jest-environment-jsdom@17.0.2
unbuild jest-diff@17.0.3
unbuild jest-environment-node@17.0.2
unbuild jest-file-exists@17.0.0
unbuild jest-haste-map@17.0.3
unbuild jest-jasmine2@17.0.3
unbuild jest-matcher-utils@17.0.3
unbuild jest-matchers@17.0.3
unbuild jest-mock@17.0.2
unbuild jest-resolve@17.0.3
unbuild jest-resolve-dependencies@17.0.3
unbuild jest-snapshot@17.0.3
unbuild jest-util@17.0.2
unbuild jodid25519@1.0.2
unbuild js-tokens@2.0.0
unbuild jsbn@0.1.0
unbuild jsdom@9.8.3
unbuild json-schema@0.2.3
unbuild json-stable-stringify@1.0.1
unbuild json-stringify-safe@5.0.1
unbuild jsonify@0.0.0
unbuild jsonpointer@4.0.0
unbuild jsprim@1.3.1
unbuild kind-of@3.0.4
unbuild lazy-cache@1.0.4
unbuild lcid@1.0.0
unbuild levn@0.3.0
unbuild load-json-file@1.1.0
unbuild lodash._arraycopy@3.0.0
unbuild lodash@4.17.2
unbuild lodash._arrayeach@3.0.0
unbuild lodash._baseassign@3.2.0
unbuild lodash._baseclone@3.3.0
unbuild lodash._basecopy@3.0.1
unbuild lodash._basefor@3.0.3
unbuild lodash._bindcallback@3.0.1
unbuild lodash._getnative@3.9.1
unbuild lodash.assign@4.2.0
unbuild lodash.clonedeep@3.0.2
unbuild lodash.isarguments@3.1.0
unbuild lodash.isarray@3.0.4
unbuild longest@1.0.1
unbuild lodash.keys@3.1.2
unbuild makeerror@1.0.11
unbuild marked-terminal@1.7.0
unbuild merge@1.2.0
unbuild micromatch@2.3.11
unbuild mime-db@1.25.0
unbuild mime-types@2.1.13
unbuild minimatch@2.0.10
unbuild minimist@0.0.8
unbuild ms@0.7.2
unbuild multimatch@2.1.0
unbuild natural-compare@1.4.0
unbuild node-emoji@1.4.1
unbuild node-int64@0.4.0
unbuild normalize-package-data@2.3.5
unbuild normalize-path@2.0.1
unbuild number-is-nan@1.0.1
unbuild nwmatcher@1.3.9
unbuild oauth-sign@0.8.2
unbuild object-assign@4.1.0
unbuild object.omit@2.0.1
unbuild once@1.4.0
unbuild optimist@0.6.1
unbuild optionator@0.8.2
unbuild os-homedir@1.0.2
unbuild os-locale@1.4.0
unbuild os-tmpdir@1.0.2
unbuild parse-glob@3.0.4
unbuild parse-json@2.2.0
unbuild parse5@1.5.1
unbuild path-exists@2.1.0
unbuild path-is-absolute@1.0.1
unbuild path-parse@1.0.5
unbuild path-type@1.1.0
unbuild pify@2.3.0
unbuild pinkie@2.0.4
unbuild pinkie-promise@2.0.1
unbuild prelude-ls@1.1.2
unbuild preserve@0.2.0
unbuild pretty-format@4.2.3
unbuild private@0.1.6
unbuild prr@0.0.0
unbuild punycode@1.4.1
unbuild qs@6.3.0
unbuild randomatic@1.1.6
unbuild read-pkg@1.1.0
unbuild read-pkg-up@1.0.1
unbuild redeyed@1.0.1
unbuild regenerator-runtime@0.9.6
unbuild regex-cache@0.4.3
unbuild repeat-element@1.1.2
unbuild repeat-string@1.6.1
unbuild repeating@2.0.1
unbuild request@2.79.0
unbuild require-directory@2.1.1
unbuild require-main-filename@1.0.1
unbuild resolve@1.1.7
unbuild right-align@0.1.3
unbuild sax@1.2.1
unbuild set-blocking@2.0.0
unbuild shellwords@0.1.0
unbuild slash@1.0.0
unbuild sntp@1.0.9
unbuild source-map@0.5.6
unbuild source-map-support@0.4.6
unbuild spdx-correct@1.0.2
unbuild spdx-expression-parse@1.0.4
unbuild spdx-license-ids@1.2.2
unbuild sprintf-js@1.0.3
unbuild string-width@1.0.2
unbuild string.prototype.codepointat@0.2.0
unbuild stringstream@0.0.5
unbuild strip-ansi@3.0.1
unbuild strip-bom@2.0.0
unbuild supports-color@2.0.0
unbuild symbol-tree@3.1.4
unbuild test-exclude@2.1.3
unbuild throat@3.0.0
unbuild tmpl@1.0.4
unbuild to-fast-properties@1.0.2
unbuild tough-cookie@2.3.2
unbuild tr46@0.0.3
unbuild tunnel-agent@0.4.3
unbuild tweetnacl@0.14.3
unbuild type-check@0.3.2
unbuild uglify-to-browserify@1.0.2
unbuild validate-npm-package-license@3.0.1
unbuild verror@1.3.6
unbuild walker@1.0.7
unbuild watch@0.10.0
unbuild webidl-conversions@3.0.1
unbuild whatwg-encoding@1.0.1
unbuild whatwg-url@3.1.0
unbuild which-module@1.0.0
unbuild window-size@0.1.0
unbuild wordwrap@0.0.3
unbuild worker-farm@1.3.1
unbuild wrap-ansi@2.1.0
unbuild wrappy@1.0.2
unbuild xml-name-validator@2.0.1
unbuild xtend@4.0.1
unbuild y18n@3.2.1
unbuild yargs@6.4.0
unbuild yargs-parser@4.1.0
unbuild acorn@2.7.0
unbuild babylon@6.14.1
unbuild cardinal@1.0.0
unbuild errno@0.1.4
unbuild escodegen@1.8.1
unbuild esprima@2.7.3
unbuild handlebars@4.0.6
unbuild har-validator@2.0.6
unbuild istanbul@0.4.5
unbuild jest-runtime@17.0.3
unbuild js-yaml@3.7.0
unbuild jsesc@1.3.0
unbuild json5@0.5.1
unbuild loose-envify@1.3.0
unbuild marked@0.3.6
unbuild mkdirp@0.5.1
unbuild node-notifier@4.6.1
unbuild nopt@3.0.6
unbuild rimraf@2.5.4
unbuild sane@1.4.1
unbuild semver@5.3.0
unbuild sshpk@1.10.1
unbuild uglify-js@2.7.5
unbuild uuid@3.0.1
unbuild which@1.2.12
                                                                                
~/Projects/jest-test master
λ npm test

> jest-test@1.0.0 test /Users/moeriki/Projects/jest-test
> jest

module.js:472
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moeriki/Projects/jest-test/node_modules/jest/node_modules/jest-cli/build/cli/getJest.js:15:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by Moeriki** [comment] 2016-11-30 14:42
Your test output is `No tests found`. That is not correct, there is one test.

Don't know why Jest doesn't see the file at your end @KenanY.

**Comment by KenanY** [comment] 2016-11-30 14:49
¯\_(ツ)_/¯

**Comment by KenanY** [comment] 2016-11-30 14:56
<http://facebook.github.io/jest/docs/configuration.html> leads me to believe that tests should be, by default, in a `__tests__/` directory, which is not the case here? I'm not familiar with Jest but maybe you have some sort of config that I don't, somehow?

**Comment by KenanY** [comment] 2016-11-30 15:05
Regardless, `npm prune` does not appear to delete any module for me. I can only imagine that somehow you have set `NODE_ENV=production` or `npm config get production` set to `true`? Might be a stretch :/

**Comment by Moeriki** [comment] 2016-11-30 16:14
Removing `depth=1` from my `.npmrc` fixes this issue.

This would make this a duplicate of 12558.

Now the question is: Is this a bug, or an expected, though unfortunate, side-effect of setting depth in `.npmrc`? :)

**Comment by KenanY** [comment] 2016-11-30 16:16
Closing as a duplicate of https://github.com/npm/npm/issues/12558 then. I'm inclined to say it's a bug (or, perhaps, an undocumented feature ;)).

**Closed by KenanY** 2016-11-30 16:16 UTC
