### ISSUE TITLE
`mkdir -p` doesn't work properly in package.json on Windows

### ISSUE THREAD

**Issue by cageygee3** [npm/npm#12774] opened 2016-05-20 00:15 UTC
Try adding this to your package.json:

`"foo": "mkdir -p foo"`

When you `npm run foo`, the `-p` parameter is not passed correctly, and mkdir ends up making two directories: one named `-p` and one named `foo`. If you `npm run foo` again, you'll get this error:

```
> mkdir -p foo

A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file foo already exists.
Error occurred while processing: foo.
```

**Comment by KenanY** [comment] 2016-05-20 00:19
@cageygee3 When I run `mkdir -p foo` on the Windows `cmd.exe` I get two directories: `-p/` and `foo/` so I do not this is the fault of `npm`.

**Comment by KenanY** [comment] 2016-05-20 00:21
I cannot find any documentation online that suggests that `-p` is a valid flag in the Windows implementation of `mkdir`.

**Comment by cageygee3** [comment] 2016-05-20 00:28
Ah, good point. I'm using the git bash shell for Windows though, which does support it:

```
$ ls foo/
ls: cannot access foo/: No such file or directory

$ mkdir -p foo/bar/baz

$ ls -R foo/
foo/:
bar/

foo/bar:
baz/

foo/bar/baz:
```

**Comment by KenanY** [comment] 2016-05-20 00:33
@cageygee3 And the `-p/` directory is not created? Windows `mkdir` from `cmd.exe` already creates intermediate directories without any flags.

```
C:\>mkdir /?
Creates a directory.

MKDIR [drive:]path
MD [drive:]path

If Command Extensions are enabled MKDIR changes as follows:

MKDIR creates any intermediate directories in the path, if needed.
For example, assume \a does not exist then:

    mkdir \a\b\c\d

is the same as:

    mkdir \a
    chdir \a
    mkdir b
    chdir b
    mkdir c
    chdir c
    mkdir d

which is what you would have to type if extensions were disabled.
```

**Comment by cageygee3** [comment] 2016-05-20 00:35
Correct, the `-p` directory is not created when I run `mkdir -p` from the git bash shell. My team is cross-platform and we've noticed that our package.json (with the `mkdir -p` inside) works fine on MacOS and Linux, but not Windows.

**Comment by KenanY** [comment] 2016-05-20 00:41
Hmm, maybe the [`shell`](https://docs.npmjs.com/misc/config#shell) config is what you would need to edit if you would like `npm` to use git bash instead of `cmd.exe`.

**Comment by othiym23** [comment] 2016-05-20 00:42
I'd switch to adding a `devDependency` on `mkdirp` and using it to create the path from the package script instead; part of the reason `mkdirp` exists is to simplify directory creation across Unix and Windows. On Windows, npm runs package scripts using `cmd.exe` instead of the user shell (by design / originally by Microsoft's preference). This means that, absent some major `PATH` shenanigans, package scripts run on Windows will end up getting the Windows version of `mkdir`.

The CLI team may or may not change this in the future, but even so, that's how most versions of npm work right now, so in order to minimize confusion, I strongly suggest switching to `mkdirp`. This is all the behavior as intended, so I'm going to close this issue. Thanks for your time, and good luck getting this sorted out for your team!

**Closed by othiym23** 2016-05-20 00:42 UTC
Labels: platform-integration, support, windows

**Comment by cageygee3** [comment] 2016-05-20 00:44
Thanks a ton for all the info everyone. Appreciate it!

**Comment by sanewell92** [comment] 2017-05-29 23:52
Just ran into this and found `mkdirp` and this issue. Thanks @othiym23 <3<3 Helped me set up a quick cross-platform npm script build set up.
