### ISSUE TITLE
npmlog depends on npmlog

### ISSUE THREAD

**Issue by joaumg** [npm/npm#11242] opened 2016-01-22 02:06 UTC
The beginning of everything:

I was trying to install `cordova-plugin-inappbrowser.git`. No problem with that...

    cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git

Which screamed (:scream:) with me:

    module.js:341
    throw err;
    ^

    Error: Cannot find module 'semver'
        // ...

Then googling, I found a "try sudo npm update -g".
( I might screwed ( :boom: ) really hard just running the command, but no bad feelings :broken_heart: ... )

So, `sudo npm update -g`:

    npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
    npm WARN install:number-is-nan@1.0.0 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/is-integer/node_modules/is-finite/node_modules/number-is-nan' -> '/usr/local/lib/node_modules/bigrig/node_modules/number-is-nan'
    npm WARN install:asn1@0.1.11 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/asn1' -> '/usr/local/lib/node_modules/cordova/node_modules/asn1'
    npm WARN install:ctype@0.5.3 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype' -> '/usr/local/lib/node_modules/cordova/node_modules/ctype'
    npm WARN install:delayed-stream@0.0.5 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream' -> '/usr/local/lib/node_modules/cordova/node_modules/delayed-stream'
    npm WARN install:isarray@0.0.1 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/htmlparser2/node_modules/readable-stream/node_modules/isarray' -> '/usr/local/lib/node_modules/cordova/node_modules/isarray'
    npm WARN install:is-finite@1.0.1 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/is-integer/node_modules/is-finite' -> '/usr/local/lib/node_modules/cordova/node_modules/is-finite'
    npm WARN install:string_decoder@0.10.31 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/htmlparser2/node_modules/readable-stream/node_modules/string_decoder' -> '/usr/local/lib/node_modules/cordova/node_modules/string_decoder'
    npm WARN install:end-of-stream@1.0.0 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/bigrig/node_modules/snyk/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/duplexify/node_modules/end-of-stream' -> '/usr/local/lib/node_modules/cordova/node_modules/end-of-stream'
    npm ERR! gentlyRm containing path /usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn isn't under npm's control
    npm WARN install:acorn@1.2.2 Refusing to delete: /usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/.bin/acorn not in /usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/acorn
    npm WARN install:amdefine@1.0.0 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/source-map-support/node_modules/source-map/node_modules/amdefine' -> '/usr/local/lib/node_modules/jscs/node_modules/amdefine'
    npm WARN install:concat-map@0.0.1 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/bower/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' -> '/usr/local/lib/node_modules/jscs/node_modules/concat-map'
    npm WARN install:core-util-is@1.0.2 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/htmlparser2/node_modules/readable-stream/node_modules/core-util-is' -> '/usr/local/lib/node_modules/jscs/node_modules/core-util-is'
    npm WARN install:defined@1.0.0 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jscs/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/detective/node_modules/defined' -> '/usr/local/lib/node_modules/jscs/node_modules/defined'
    npm ERR! Linux 3.16.0-59-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
    npm ERR! node v5.4.1
    npm ERR! npm  v3.3.12

    npm ERR! Maximum call stack size exceeded
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /media/joaumg/B3CD-BAA8/friendly/npm-debug.log

Maximum call stack size exceeded... I think I broke everything. But ok...
Lets retry ? Why not?! :joy: :joy:

    cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git

    module.js:341
    throw err;
    ^

    Error: Cannot find module 'umask'
        // ...

Whoa! New Error... :open_mouth:
Let's do an ugly fix...

    sudo npm install -g umask

    module.js:327
    throw err;
    ^

    Error: Cannot find module 'npmlog'
        // ...

Maybe installing the npmlog... :joy:

    sudo npm install -g npmlog
    module.js:327
    throw err;
    ^

    Error: Cannot find module 'npmlog'
        // ...

So, is there any easy fix? :heart_eyes:

Or just prune + full reinstall ? :cry:

Oh, almost forgot [npm-debug.log](http://paste.ubuntu.com/14594453/): ( 9700 lines of logging... )

**Comment by joaumg** [comment] 2016-01-22 02:43
# Update:

After running `curl -L https://www.npmjs.org/install.sh | sh` and a `sudo npm update -g` I got the `npmlog` working... !

Which raises my final question, `npmlog` depends on `npmlog`... is there a way to avoid this ? ( there's no docs on `npm install --help` ;\ )

**Comment by othiym23** [comment] 2016-02-24 19:37
>  `npmlog` depends on `npmlog`... is there a way to avoid this ?

What do you mean when you say `npmlog` depends on itself?

```
bauchelain% npm view npmlog dependencies --json
```
```json
{
  "ansi": "~0.3.1",
  "are-we-there-yet": "~1.0.6",
  "gauge": "~1.2.5"
}
```

> Maybe installing the npmlog... :joy:

That's not going to work, or, rather, if it works, it's only going to work by coincidence. The version of `npmlog` that was missing was npm's own local install, so globally installing another copy won't fix a broken npm install. Using `install.sh` to reinstall npm is indeed the best way to fix this.

I think somewhere along the line you got one of the less-good versions of npm that had a regression around how `bundledDependencies` are handled / replaced when they're out of date with respect to semver. The good news is, once you're on `npm@3.6.0` or greater, that should be more consistent. The bad news is that there's a bug under there somewhere that caused all those `ENOENT` failures, which may or may not have been addressed.

Either way, since your original problem has been solved, I'm going to close this issue. If you run into further issues with either call stacks exceeded or `ENOENT` errors, please open a new issue, and we'll take another look. Thanks for your time and the thorough report!

**Closed by othiym23** 2016-02-24 19:37 UTC
Labels: support
