### ISSUE TITLE
There is an error upon trying to install the 'formidable' module.

### ISSUE THREAD

**Issue by dbdavis** [npm/npm#16212] opened 2017-03-31 18:10 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dbdavis** [comment] 2017-03-31 18:28
I am learning node. After some travail, I had started over by deleting node.js and everything else, then reinstalling all the latest. Things were going OK until now. Would appreciate knowing how to install formidable (or to know what replaces it.) Node things are moving so fast that its hard for a newcomer to keep up because what is available goes out-of-date so very quickly, and what remains posted is often not amended.

Attached files:
- extract of console log.
- log file requested by the console log.
Please notify at dbd400@gmail.com
Many Thanks

**Console log:**
MacBook-Air:app dbd$ npm install -g formidible --save
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/dbd/.nvm/versions/node/v7.8.0/bin/node" "/Users/dbd/.nvm/versions/node/v7.8.0/bin/npm" "install" "-g" "formidible" "--save"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dbd/.npm/_logs/2017-03-31T17_49_59_366Z-debug.log
MacBook-Air:app dbd$ 

**/Users/dbd/.npm/_logs/2017-03-31T17_49_59_366Z-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dbd/.nvm/versions/node/v7.8.0/bin/node',
1 verbose cli   '/Users/dbd/.nvm/versions/node/v7.8.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'formidible',
1 verbose cli   '--save' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData formidible
8 silly fetchNamedPackageData formidible
9 silly mapToRegistry name formidible
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'formidible',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'formidible',
12 silly mapToRegistry   name: 'formidible',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/formidible
14 verbose request uri https://registry.npmjs.org/formidible
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:49:58 PM
17 verbose request id 5a62ef59c6c30115
18 http request GET https://registry.npmjs.org/formidible
19 http 404 https://registry.npmjs.org/formidible
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Fri, 31 Mar 2017 17:49:59 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-iad2625-IAD',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1490982598.895565,VS0,VE393',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Fri, 31 Mar 2017 17:49:59 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-iad2625-IAD',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1490982598.895565,VS0,VE393',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/formidible
22 silly fetchPackageMetaData     at makeError (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/request/request.js:1001:12)
22 silly fetchPackageMetaData  error for formidible { Error: Registry returned 404 for GET on https://registry.npmjs.org/formidible
22 silly fetchPackageMetaData     at makeError (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/request/request.js:1001:12) pkgid: 'formidible', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 verbose stack TypeError: Cannot read property 'path' of null
24 verbose stack     at Installer.rollbackFailedOptional (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install.js:511:29)
24 verbose stack     at Array.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
24 verbose stack     at LOOP (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
24 verbose stack     at /Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
24 verbose stack     at /Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install.js:337:5
24 verbose stack     at Array.<anonymous> (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
24 verbose stack     at LOOP (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
24 verbose stack     at chain (/Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
24 verbose stack     at /Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install.js:294:5
24 verbose stack     at /Users/dbd/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
25 verbose cwd /Users/dbd/Documents/workspace/SudokuN/app
26 error Darwin 16.4.0
27 error argv "/Users/dbd/.nvm/versions/node/v7.8.0/bin/node" "/Users/dbd/.nvm/versions/node/v7.8.0/bin/npm" "install" "-g" "formidible" "--save"
28 error node v7.8.0
29 error npm  v4.2.0
30 error Cannot read property 'path' of null
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]

**Comment by legodude17** [comment] 2017-03-31 20:23
Duplicate of #10686. Try checking your internet connection.

**Comment by KenanY** [comment] 2017-03-31 20:43
@dbdavis There is a typo in your command: you are trying to install `formidible`, instead of `formidable`.

**Closed by KenanY** 2017-03-31 20:43 UTC
