### ISSUE TITLE
got an error when i was trying to install cordova with npm

### ISSUE THREAD

**Issue by franklee0817** [npm/npm#8369] opened 2015-05-27 09:07 UTC
```
1537 error Windows_NT 6.1.7600
1538 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
1539 error node v0.12.4
1540 error npm  v2.10.1
1541 error Cannot read property 'emit' of null
1542 error If you need help, you may report this error at:
1542 error     <https://github.com/npm/npm/issues>
1543 verbose exit [ 1, true ]
```

could any body help with it? I'm a fresh learner,thanks a lot.

**Comment by KenanY** [comment] 2015-05-28 04:29
@franklee0817 Hmm, could you upload the _entire_ `npm-debug.log` as a [gist](https://gist.github.com/)? Last few lines isn't sufficient to track down a bug here.

**Comment by franklee0817** [comment] 2015-05-29 02:06
c:\pro\hello>cordova platform add android
npm http GET https://registry.npmjs.org/cordova-android/4.0.0
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (C:\Users\Administrator\AppData\Roaming\npm\n
ode_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\reque
st\node_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Users\Administrat
or\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_module
s\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request
\node_modules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (C:\Users\Administrator\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:59
4:30)
    at Request.end (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cord
ova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:1186
:28)

I made it. But now I got this. Can you please help me?

**Comment by franklee0817** [comment] 2015-05-29 02:22
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.frank.hello" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloWorld</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" version="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>

this is the context of config.xml.

**Comment by franklee0817** [comment] 2015-05-29 02:30
Sorry. It looks like I cannot upload the snapshot of my config.xml file. And I also cannot paste the context here. It will went wrong. But as far as I know the xml file is fine.

**Comment by franklee0817** [comment] 2015-05-31 14:40
@KenanY  Please help me.

**Comment by KenanY** [comment] 2015-05-31 18:12
@franklee0817 I see that `npm` is throwing an error, but if you believe your `config.xml` is the cause of your issue then you need to ask the cordova people about this, since that's not a `npm` thing.

**Comment by KenanY** [comment] 2016-05-15 17:57
@franklee0817 Are you still seeing this issue?

**Comment by KenanY** [comment] 2016-06-28 21:01
Closing as abandoned.

**Closed by KenanY** 2016-06-28 21:01 UTC
Labels: support, windows
