### ISSUE TITLE
fetch failed with status code 502; The command '/bin/sh -c sudo npm install -g yo bower grunt-cli gulp' returned a non-zero code: 1

### ISSUE THREAD

**Issue by rogersachan** [npm/npm#13298] opened 2016-07-06 15:51 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
Try installing "RUN sudo npm install -g yo bower grunt-cli gulp"
```docker
Building in Docker Cloud's infrastructure...
Starting to clone
Cloning into '.'...
Cloning done
Starting Build
KernelVersion: 4.4.0-21-generic
Os: linux
BuildTime: 2016-04-26T23:43:49.174056600+00:00
ApiVersion: 1.23
Version: 1.11.1
GitCommit: 5604cbe
Arch: amd64
GoVersion: go1.5.4
Starting build of index.docker.io/codenvy/dotnet_core:latest...
Step 1 : FROM codenvy/ubuntu_jre
 ---> 2d6a79c69c3a
Step 2 : MAINTAINER mercuriete@gmail.com
 ---> Running in 75b98e45fe12
 ---> b3127a6c4135
Removing intermediate container 75b98e45fe12
Step 3 : RUN echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" | sudo tee --append /etc/apt/sources.list.d/dotnetdev.list &&     sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 &&    sudo apt-get update &&     sudo apt-get install dotnet-dev-1.0.0-preview2-003121 -y &&     sudo apt-get clean &&     sudo apt-get -y autoremove &&     sudo apt-get -y clean &&     sudo rm -rf /var/lib/apt/lists/*
 ---> Running in 4236bdd93f71
deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.rv30CgjnOg --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/git-core-ppa.gpg --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
[91mgpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
[0m[91mgpg: key 417A0893: public key "MS Open Tech <interop@microsoft.com>" imported
[0m[91mgpg: Total number processed: 1
[0m[91mgpg:               imported: 1[0m[91m  (RSA: 1)
[0mGet:1 http://apt-mo.trafficmanager.net trusty InRelease [2819 B]
Ign http://archive.ubuntu.com trusty InRelease
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:4 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Get:5 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:6 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:7 http://apt-mo.trafficmanager.net trusty/main amd64 Packages [115 kB]
Get:8 http://archive.ubuntu.com trusty-updates/main Sources [350 kB]
Get:9 http://archive.ubuntu.com trusty-updates/restricted Sources [5217 B]
Get:10 http://archive.ubuntu.com trusty-updates/universe Sources [198 kB]
Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [991 kB]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [23.5 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [469 kB]
Get:14 http://archive.ubuntu.com trusty-security/main Sources [149 kB]
Get:15 http://archive.ubuntu.com trusty-security/restricted Sources [3920 B]
Get:16 http://archive.ubuntu.com trusty-security/universe Sources [44.1 kB]
Get:17 http://archive.ubuntu.com trusty-security/main amd64 Packages [629 kB]
Get:18 http://ppa.launchpad.net trusty/main amd64 Packages [3389 B]
Get:19 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [20.2 kB]
Get:20 http://archive.ubuntu.com trusty-security/universe amd64 Packages [170 kB]
Get:21 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:22 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:23 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:24 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:25 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:26 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 22.0 MB in 8s (2617 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  dotnet-host dotnet-hostfxr-1.0.1
  dotnet-sharedframework-microsoft.netcore.app-1.0.0 libicu52 liblldb-3.6
  libllvm3.6 liblttng-ust-ctl2 liblttng-ust0 libpython2.7 libunwind8 liburcu1
The following NEW packages will be installed:
  dotnet-dev-1.0.0-preview2-003121 dotnet-host dotnet-hostfxr-1.0.1
  dotnet-sharedframework-microsoft.netcore.app-1.0.0 libicu52 liblldb-3.6
  libllvm3.6 liblttng-ust-ctl2 liblttng-ust0 libpython2.7 libunwind8 liburcu1
0 upgraded, 12 newly installed, 0 to remove and 21 not upgraded.
Need to get 62.7 MB of archives.
After this operation, 201 MB of additional disk space will be used.
Get:1 http://apt-mo.trafficmanager.net/repos/dotnet/ trusty/main dotnet-host amd64 1.0.2-beta-000555-00-1 [34.5 kB]
Get:2 http://apt-mo.trafficmanager.net/repos/dotnet/ trusty/main dotnet-hostfxr-1.0.1 amd64 1.0.1-1 [130 kB]
Get:3 http://apt-mo.trafficmanager.net/repos/dotnet/ trusty/main dotnet-sharedframework-microsoft.netcore.app-1.0.0 amd64 1.0.0-1 [22.6 MB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libicu52 amd64 52.1-3ubuntu0.4 [6752 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libllvm3.6 amd64 1:3.6-2ubuntu1~trusty1 [7858 kB]
Get:6 http://apt-mo.trafficmanager.net/repos/dotnet/ trusty/main dotnet-dev-1.0.0-preview2-003121 amd64 1.0.0-preview2-003121-1 [17.0 MB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpython2.7 amd64 2.7.6-8ubuntu0.2 [1039 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/main liblldb-3.6 amd64 1:3.6-2ubuntu1~trusty1 [7055 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main libunwind8 amd64 1.1-2.2ubuntu3 [48.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty/main liburcu1 amd64 0.7.12-0ubuntu2 [34.9 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ trusty/main liblttng-ust-ctl2 amd64 2.4.0-4ubuntu1 [61.7 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty/main liblttng-ust0 amd64 2.4.0-4ubuntu1 [106 kB]
[91mdebconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
[0m[91mdebconf: falling back to frontend: Readline
[0m[91mdebconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
[0m[91mdebconf: falling back to frontend: Teletype
[0m[91mdpkg-preconfigure: unable to re-open stdin: 
[0mFetched 62.7 MB in 4s (15.3 MB/s)
Selecting previously unselected package libicu52:amd64.
(Reading database ... 18384 files and directories currently installed.)
Preparing to unpack .../libicu52_52.1-3ubuntu0.4_amd64.deb ...
Unpacking libicu52:amd64 (52.1-3ubuntu0.4) ...
Selecting previously unselected package libllvm3.6:amd64.
Preparing to unpack .../libllvm3.6_1%3a3.6-2ubuntu1~trusty1_amd64.deb ...
Unpacking libllvm3.6:amd64 (1:3.6-2ubuntu1~trusty1) ...
Selecting previously unselected package libpython2.7:amd64.
Preparing to unpack .../libpython2.7_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking libpython2.7:amd64 (2.7.6-8ubuntu0.2) ...
Selecting previously unselected package liblldb-3.6.
Preparing to unpack .../liblldb-3.6_1%3a3.6-2ubuntu1~trusty1_amd64.deb ...
Unpacking liblldb-3.6 (1:3.6-2ubuntu1~trusty1) ...
Selecting previously unselected package libunwind8.
Preparing to unpack .../libunwind8_1.1-2.2ubuntu3_amd64.deb ...
Unpacking libunwind8 (1.1-2.2ubuntu3) ...
Selecting previously unselected package liburcu1.
Preparing to unpack .../liburcu1_0.7.12-0ubuntu2_amd64.deb ...
Unpacking liburcu1 (0.7.12-0ubuntu2) ...
Selecting previously unselected package liblttng-ust-ctl2:amd64.
Preparing to unpack .../liblttng-ust-ctl2_2.4.0-4ubuntu1_amd64.deb ...
Unpacking liblttng-ust-ctl2:amd64 (2.4.0-4ubuntu1) ...
Selecting previously unselected package liblttng-ust0:amd64.
Preparing to unpack .../liblttng-ust0_2.4.0-4ubuntu1_amd64.deb ...
Unpacking liblttng-ust0:amd64 (2.4.0-4ubuntu1) ...
Selecting previously unselected package dotnet-host.
Preparing to unpack .../dotnet-host_1.0.2-beta-000555-00-1_amd64.deb ...
Unpacking dotnet-host (1.0.2-beta-000555-00-1) ...
Selecting previously unselected package dotnet-hostfxr-1.0.1.
Preparing to unpack .../dotnet-hostfxr-1.0.1_1.0.1-1_amd64.deb ...
Unpacking dotnet-hostfxr-1.0.1 (1.0.1-1) ...
Selecting previously unselected package dotnet-sharedframework-microsoft.netcore.app-1.0.0.
Preparing to unpack .../dotnet-sharedframework-microsoft.netcore.app-1.0.0_1.0.0-1_amd64.deb ...
Unpacking dotnet-sharedframework-microsoft.netcore.app-1.0.0 (1.0.0-1) ...
Selecting previously unselected package dotnet-dev-1.0.0-preview2-003121.
Preparing to unpack .../dotnet-dev-1.0.0-preview2-003121_1.0.0-preview2-003121-1_amd64.deb ...
Unpacking dotnet-dev-1.0.0-preview2-003121 (1.0.0-preview2-003121-1) ...
Setting up libicu52:amd64 (52.1-3ubuntu0.4) ...
Setting up libllvm3.6:amd64 (1:3.6-2ubuntu1~trusty1) ...
Setting up libpython2.7:amd64 (2.7.6-8ubuntu0.2) ...
Setting up liblldb-3.6 (1:3.6-2ubuntu1~trusty1) ...
Setting up libunwind8 (1.1-2.2ubuntu3) ...
Setting up liburcu1 (0.7.12-0ubuntu2) ...
Setting up liblttng-ust-ctl2:amd64 (2.4.0-4ubuntu1) ...
Setting up liblttng-ust0:amd64 (2.4.0-4ubuntu1) ...
Setting up dotnet-host (1.0.2-beta-000555-00-1) ...
Setting up dotnet-hostfxr-1.0.1 (1.0.1-1) ...
Setting up dotnet-sharedframework-microsoft.netcore.app-1.0.0 (1.0.0-1) ...
Setting up dotnet-dev-1.0.0-preview2-003121 (1.0.0-preview2-003121-1) ...
This software may collect information about you and your use of the software, and send that to Microsoft.
Please visit http://aka.ms/dotnet-cli-eula for more information.
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
 ---> 3560cbcf255d
Removing intermediate container 4236bdd93f71
Step 4 : RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
 ---> Running in e322f2f552a5

## Installing the NodeSource Node.js v6.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://apt-mo.trafficmanager.net trusty InRelease [2819 B]
Ign http://archive.ubuntu.com trusty InRelease
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:4 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Get:5 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:6 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:7 http://apt-mo.trafficmanager.net trusty/main amd64 Packages [115 kB]
Get:8 http://archive.ubuntu.com trusty-updates/main Sources [350 kB]
Get:9 http://archive.ubuntu.com trusty-updates/restricted Sources [5217 B]
Get:10 http://archive.ubuntu.com trusty-updates/universe Sources [198 kB]
Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [991 kB]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [23.5 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [469 kB]
Get:14 http://archive.ubuntu.com trusty-security/main Sources [149 kB]
Get:15 http://archive.ubuntu.com trusty-security/restricted Sources [3920 B]
Get:16 http://archive.ubuntu.com trusty-security/universe Sources [44.1 kB]
Get:17 http://ppa.launchpad.net trusty/main amd64 Packages [3389 B]
Get:18 http://archive.ubuntu.com trusty-security/main amd64 Packages [629 kB]
Get:19 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [20.2 kB]
Get:20 http://archive.ubuntu.com trusty-security/universe amd64 Packages [170 kB]
Get:21 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:22 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:23 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:24 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:25 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:26 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 22.0 MB in 8s (2612 kB/s)
Reading package lists...

## Installing packages required for setup: apt-transport-https...

+ apt-get install -y apt-transport-https > /dev/null 2>&1

## Confirming "trusty" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/trusty/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource ${NODENAME} repo...

+ echo 'deb https://deb.nodesource.com/node_6.x trusty main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_6.x trusty main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit http://apt-mo.trafficmanager.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.ubuntu.com trusty-security InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Get:1 https://deb.nodesource.com trusty InRelease
Hit http://archive.ubuntu.com trusty Release
Hit http://apt-mo.trafficmanager.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty-security/restricted Sources
Hit http://archive.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:2 https://deb.nodesource.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/main Sources
Get:3 https://deb.nodesource.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Fetched 5643 B in 8s (673 B/s)
Reading package lists...

## Run `apt-get install ${NODEPKG}` (as root) to install ${NODENAME} and npm

 ---> f5ea7a06e82a
Removing intermediate container e322f2f552a5
Step 5 : RUN sudo apt-get install nodejs -y
 ---> Running in c925176217ae
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  rlwrap
The following NEW packages will be installed:
  nodejs rlwrap
0 upgraded, 2 newly installed, 0 to remove and 21 not upgraded.
Need to get 9475 kB of archives.
After this operation, 47.2 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe rlwrap amd64 0.37-5 [73.4 kB]
Get:2 https://deb.nodesource.com/node_6.x/ trusty/main nodejs amd64 6.2.2-1nodesource1~trusty1 [9402 kB]
[91mdebconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
[0m[91mdebconf: falling back to frontend: Readline
[0m[91mdebconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
[0m[91mdebconf: falling back to frontend: Teletype
[0m[91mdpkg-preconfigure: unable to re-open stdin: 
[0mFetched 9475 kB in 2s (4125 kB/s)
Selecting previously unselected package rlwrap.
(Reading database ... 18716 files and directories currently installed.)
Preparing to unpack .../rlwrap_0.37-5_amd64.deb ...
Unpacking rlwrap (0.37-5) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_6.2.2-1nodesource1~trusty1_amd64.deb ...
Unpacking nodejs (6.2.2-1nodesource1~trusty1) ...
Setting up rlwrap (0.37-5) ...
update-alternatives: using /usr/bin/rlwrap to provide /usr/bin/readline-editor (readline-editor) in auto mode
Setting up nodejs (6.2.2-1nodesource1~trusty1) ...
 ---> 81b8f7afedc3
Removing intermediate container c925176217ae
Step 6 : RUN sudo npm install -g yo bower grunt-cli gulp
 ---> Running in d7e6490d4fd0
[91mnpm[0m[91m WARN[0m[91m deprecated[0m[91m graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[0m[91mnpm [0m[91mWARN [0m[91mdeprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[0m[91mnpm [0m[91mWARN [0m[91mdeprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[0m[91mnpm [0m[91mWARN [0m[91mdeprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
[0m[91mnpm [0m[91mWARN [0m[91mdeprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[0m[91mnpm [0m[91mWARN [0m[91mdeprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
[0m[91mnpm [0m[91mERR! [0m[91mfetch failed https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz
[0m[91mnpm [0m[91mWARN [0m[91mretry will retry, error on last attempt: Error: fetch failed with status code 502
[0m[91mnpm [0m[91mERR! [0m[91mfetch failed https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz
[0m[91mnpm [0m[91mWARN [0m[91mretry will retry, error on last attempt: Error: fetch failed with status code 502
[0m[91mnpm[0m[91m ERR![0m[91m fetch failed[0m[91m https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz
[0m[91mnpm [0m[91mERR! Linux 4.4.0-21-generic
[0m[91mnpm [0m[91mERR! [0m[91margv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "gulp"
[0m[91mnpm [0m[91mERR! [0m[91mnode v6.2.2
[0m[91mnpm [0m[91mERR! [0m[91mnpm  v3.9.5
[0m[91m
[0m[91mnpm [0m[91mERR! fetch failed with status code 502
[0m[91mnpm [0m[91mERR! 
[0m[91mnpm [0m[91mERR! If you need help, you may report this error at:
[0m[91mnpm [0m[91mERR!     <https://github.com/npm/npm/issues>
[0m[91m
[0m[91mnpm [0m[91mERR! Please include the following file with any support request:
[0m[91mnpm [0m[91mERR!     /projects/npm-debug.log
[0mRemoving intermediate container d7e6490d4fd0
The command '/bin/sh -c sudo npm install -g yo bower grunt-cli gulp' returned a non-zero code: 1
```

### supporting information:

 - `npm -v` prints: Dockerscript build, cant check that
 - `node -v` prints: Dockerscript
 - `npm config get registry` prints: Dockerscript
 - Windows, OS X, or Linux?: Ubuntu 14
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

<!--
    Thank you for contributing to npm! Please review this checklist
    before submitting your issue.

    - Please check if there's a solution in the troubleshooting wiki:
      https://github.com/npm/npm/wiki/Troubleshooting

    - Also ensure that your new issue conforms to npm's contribution guidelines:
      https://github.com/npm/npm/wiki/Contributing-Guidelines

    - Participation in this open source project is subject to the npm Code of Conduct:
      https://www.npmjs.com/policies/conduct

**Comment by rogersachan** [comment] 2016-07-06 15:52
https://hub.docker.com/r/codenvy/dotnet_core/builds/bqkibnfjj6yihkz9yvl7jkd/
https://github.com/codenvy/dockerfiles/blob/master/dotnet_core/Dockerfile

**Comment by othiym23** [comment] 2016-07-06 15:59
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 15:59 UTC
