### ISSUE TITLE
npm install -g phonegap error ! can any one fix this ? 

### ISSUE THREAD

**Issue by laleeth** [npm/npm#8578] opened 2015-06-16 06:30 UTC
```
569 error Failed to parse json
569 error Unexpected token }
570 error File: /home/seba/.npm/commander/2.1.0/package/package.json
571 error Failed to parse package.json data.
571 error package.json must be actual JSON, not just JavaScript.
571 error
571 error This is not a bug in npm.
571 error Tell the package author to fix their package.json file. JSON.parse
572 error System Linux 3.13.0-36-generic
573 error command "/home/seba/.nvm/v0.11.13/bin/node" "/home/seba/.nvm/v0.11.13/bin/npm" "install"
574 error cwd /home/seba/repos/angularApps/todo
575 error node -v v0.11.13
576 error npm -v 1.4.9
577 error file /home/seba/.npm/commander/2.1.0/package/package.json
578 error code EJSONPARSE
579 verbose exit [ 1, true ]
```

**Comment by AoJ** [comment] 2015-06-16 12:27
Do you read error message?

"571 error This is not a bug in npm."
"571 error Tell the package author to fix their package.json file. JSON.parse"

Now it's works for me.

**Comment by laleeth** [comment] 2015-06-17 05:00
hey pal thanks :)
 its working now

**Comment by othiym23** [comment] 2015-06-17 23:13
Closing as resolved.

**Closed by othiym23** 2015-06-17 23:13 UTC
Labels: support
