### ISSUE TITLE
npm install --no-bin-links => Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tarikihm** [npm/npm#9953] opened 2015-10-12 22:28 UTC
Hi,

I am running into an issue with npm, this is on the last current version of Node (4.2.0) and npm (3.3.6).
I have to use `--no-bin-links` as this is a build server that pre-builds the `node_modules` folder for generating an AMI image.

Error messages (verbose mode):

```
npm verb stack RangeError: Maximum call stack size exceeded
npm verb stack     at Array.forEach (native)
npm verb stack     at TrackerGroup.completed (/usr/local/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
npm verb stack     at Array.forEach (native)
npm verb stack     at TrackerGroup.completed (/usr/local/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
npm verb stack     at Array.forEach (native)
npm verb stack     at TrackerGroup.completed (/usr/local/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
npm verb stack     at Array.forEach (native)
npm verb cwd /tmp

npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.6

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

**Comment by fastest963** [comment] 2015-10-15 22:02
I had the same problem running Node 4.2.1 and npm 3.3.6. npm-debug.log can be found here: https://gobin.io/VGQZ

**Comment by JnMik** [comment] 2015-11-09 17:13
Same issue with Node 5.0

39050 silly build tar-stream
39051 silly build decompress-targz
39052 verbose stack RangeError: Maximum call stack size exceeded
39052 verbose stack     at Array.forEach (native)
39052 verbose stack     at TrackerGroup.completed (/root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
39052 verbose stack     at /root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
39052 verbose stack     at Array.forEach (native)
39052 verbose stack     at TrackerGroup.completed (/root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
39052 verbose stack     at /root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
39052 verbose stack     at Array.forEach (native)
39052 verbose stack     at TrackerGroup.completed (/root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
39052 verbose stack     at /root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
39052 verbose stack     at Array.forEach (native)
39053 verbose cwd /www/somepath
39054 error Linux 2.6.32-431.3.1.el6.x86_64
39055 error argv "/root/.nvm/versions/node/v5.0.0/bin/node" "/root/.nvm/versions/node/v5.0.0/bin/npm" "install" "--no-bin-links"
39056 error node v5.0.0
39057 error npm  v3.3.6
39058 error Maximum call stack size exceeded
39059 error If you need help, you may report this error at:
39059 error     <https://github.com/npm/npm/issues>
39060 verbose exit [ 1, true ]


I always have tons of issues with NPM trying to resolve the dependencies, god I hate that.
The logs doesn't say much, errors happens 80% when trying to build

**Comment by fresheneesz** [comment] 2015-11-19 03:03
+1 node v5.1.0 npm v3.3.12

**Comment by joaokmz** [comment] 2015-11-19 17:47
+1 Node 5.1.0 and 5.0.0 with npm v3.3.12

**Comment by joshbalfour** [comment] 2015-11-19 23:01
+1 
Linux 4.0.9-boot2docker 
node v5.1.0 
npm  v3.3.12

**Comment by DmitryRomanenko** [comment] 2015-11-24 11:45
+1,
Windows host, Ubuntu guest (vagrant)
node 0.12, 4.0, 5.0
npm  v3.3.11

**Comment by Johnnycus** [comment] 2015-11-28 19:59
+1,
Windows 8.1 host, Ubuntu guest (vagrant)
node 4.2.2
npm 3.5.0

**Comment by inggo** [comment] 2015-11-29 16:04
+1
Windows 10 host, Ubuntu guest (vagrant)
node 4.2.2
npm 3.3.6

npm -ddd install log: https://gist.github.com/inggo/969902d495f3e4143f27

**Comment by FelikZ** [comment] 2015-12-01 13:40
Using latest docker image with:
```
node 0.12.8
npm 3.4.*
```

Also broken.

But if I use node 0.12.7 docker image with old npm, everything is fine.

**Comment by collapsarzhang** [comment] 2015-12-15 19:58
any work around at this time?

**Comment by FelikZ** [comment] 2015-12-16 16:27
@collapsarzhang see comment above yours^

Solution is to use older npm version.

**Comment by DmitryRomanenko** [comment] 2015-12-16 16:34
@FelikZ what npm version should I use?  
I had this problem 6 months ago with an older npm version.

**Comment by Perni1984** [comment] 2015-12-17 07:43
same problem here:

Windows 10 host, Ubuntu guest (vagrant)
node 5.2.0
npm 3.3.12

**Comment by Perni1984** [comment] 2015-12-18 19:55
ok, finally figured this out, after nearly a week of digging into this problem. Now my node environment works fast and as a breeze inside my vagrant boxes (without any --no-bin-links workarounds).

Host: Windows 10
Vagrant: 1.7.4 (manually patched to use UNC-paths for mounting on windows, and thus support longer pathnames then 260 chars, should be in Vagrant 1.8, see mitchellh/vagrant#6493)
VirtualBox: 5.0.10

Guest OS: ubuntu/vivid64 (**any linux distro works, important is kernel >= 3.18 for mfsymlinks support**)
VirtualBoxGuestAdditions: 5.0.10

I use smb to mount my synced folders with smb3 and mfsymlinks mount options. With this I have a fast performance on windows on synced folders aswell as full compatability to unix symlinks in my guest OS. Moreover the use of UNC paths lifts the 260 chars limit of the file path.

```
config.vm.synced_folder "projectfolder", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]
```

Finally the node environment is working fast and as expected on my windows host OS inside my vagrant ubuntu box. Before, web development on windows was a real pain, now everything is working as expected.

**Comment by spescina** [comment] 2016-01-25 12:14
Host Windows 10
Vagrant 1.8.1
VirtualBox 5.0.10
Guest Os: ubuntu/trusty with vivid kernel (3.19)
VirtualBoxGuestAdditions: 5.0.10
node 5.0.0
npm 3.3.6

I've tried @Perni1984 solution but I've encountered a lot of issues with smb (no file deletion from guest, slow performance, --no-bin-links maximum stack exceed error and npm errors on missing files).

Then I reverted to virtualbox shared folders with this customize parameter `VBoxInternal2/SharedFoldersEnableSymlinksCreate`.
Now everything works fine inside the vm.

this is my vagrantfile
```
config.vm.provider "virtualbox" do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//var/www", "1"]
end

config.vm.synced_folder "./app", "/var/www", owner: "vagrant", group: "www-data", :mount_options=> ['dmode=777', 'fmode=666']
```

**Comment by web-jenezis** [comment] 2016-02-16 16:28
Hi guys,
I got the same error with node v5.0.0 and npm v3.3.6

Any updates on the issue???

I run the command `npm install --no-bin-links`

```
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/project_name/npm-debug.log
```

**Comment by irond13** [comment] 2016-02-17 15:45
We have the same issue with node v5.6.0 and npm v3.7.2. Interestingly, when we rerun the command it succeeds - evidently the issue only occurs when many modules need to be installed. So this is a workaround of sorts, but very far from ideal - especially if a build server is involved.

**Comment by othiym23** [comment] 2016-02-24 19:23
Closing as a duplicate of #10776, due to the identical stack trace showing a crash in `are-we-there-yet`. Thanks for the environment info, everybody!

**Closed by othiym23** 2016-02-24 19:23 UTC
Labels: big-bug, bug

**Comment by dempfi** [comment] 2016-08-09 08:24
@othiym23 OLD issue is duplicate of a NEW one? even new one is not providing enough info compared to old

**Comment by jhourlad** [comment] 2016-08-16 09:49
First of all, you don't need the old npm version and stuff.  
The problem is caused by too much recursive call inside the script. To solve this problem:

```
$ npm install --no-bin-links // Allow this one to fail
$ npm install --no-bin-links // Repeat the command. It should go through this time
```

It will most probably cause an error if you use a certain package. This is because a certain part of the package failed to complete in favor of the previous error. To fix that, you need to rebuild the defective package:


```
$ npm rebuild <package_name>`
```

For example:
```
$ npm rebuild node-sass
```

I hope it helps somebody out there.

**Comment by OElabed** [comment] 2016-08-26 19:20
I found a solution how override npm install errors when we use vagrant with sync floder. 

The trick is to use a symbolic link for nodes_module/ folder before runing npm install.

`
$ mkdir /home/vagrant/node_modules 
$ cd [root project folder]
$ ln -s /home/vagrant/node_modules/ node_modules
`

Host: Windows 10
Vagrant: 1.8.5
VirtualBox: 5.5.1

Guest OS: ubuntu/trusty64 
node 6.4.0
npm 3.10.6


I hope it helps somebody out there.

**Comment by jonnywilliamson** [comment] 2016-08-29 13:28
@OElabed 

Oh wow! Thank you so much! This is so much easier.

No need to use `--no-bin-links` and everything worked first time! This is so much easier. 

I was also using windows 10 with Vagrant 1.8.4 to run laravel homestead. Really appreciate that tip.

**Comment by nicdex** [comment] 2016-08-30 04:22
@OElabed @jonnywilliamson I don't see how this would work.
Npm can't create a symbolic link in the sync folder, so how are you suppose to be able to create one using ln? I get protocol error. 
Did you also use the VBoxInternal2/SharedFoldersEnableSymlinksCreate in your Vagrantfile?

Thanks

**Comment by OElabed** [comment] 2016-08-31 15:56
@nicdex Yes i know this problem!! I forget to indicate that in my last comment. You need to have a Permission to make symbolic links in Windows. 

You have 2 solutions :  
1. open your prompt with administrator rights to lunch `vagrant up` and `vagrant ssh`
2. Change your Local Policies on windows settings to add the right  to create symbolic links for your windows user

I hope it helps you.
Thanks

**Comment by jonnywilliamson** [comment] 2016-08-31 20:21
@nicdex @OElabed 

Hi, this is still working great. @nicdex Yes, if you need to do this, you must launch Vagrant as an admin, that gives it the ability to create any symlink.

However the good news is that you only have to do this once (when you make the symlink) and then if you need to restart the vagrant box again, it does NOT need to be run under admin again.

Until you need to make another symlink. However, I only had a couple of projects and so this wasn't something I need to do often.

**Comment by AntoniPierres** [comment] 2016-10-05 04:22
I have the same issue. 
Windows 10 , and I don't work under Homestead. Just work on my OS windows 10. 
Glade for a tip.

**Comment by AntoniPierres** [comment] 2016-10-05 04:25
I have this issue after 'npm install' command 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules                    \chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fseven                    ts@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch"                    :"x64"})

**Comment by icamys** [comment] 2016-10-05 11:04
@michaelsanford has offered a working solution [here](https://github.com/npm/npm/issues/10776#issuecomment-208791872).

Works for me.

Host: Ubuntu 14.04
Vagrant: 1.8.5
node 6.7.0
npm 3.10.3

**Comment by michaelsanford** [comment] 2016-10-05 20:54
@AntoniPierres : fsevents provides ["Native Access to **Mac OS-X** FSEvents"](https://www.npmjs.com/package/fsevents)

1. `fsevents` [requires](https://github.com/strongloop/fsevents/blob/master/package.json#L11) `os: "darwin"` (i.e., MacOS) but you're trying to install it on Windows. It just won't work.
2. It's an _npm WARN_, you can probably ignore it.
3. Also, doesn't seem related to this issue.

**Comment by CoolGoose** [comment] 2016-11-29 09:58
@jhourlad solution works
Here's my current homestead version / packages
```
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update" "--no-bin-links"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
```

**Comment by dsinghr** [comment] 2016-12-07 16:44
Symlinks are only supported in POSIX filesystem i.e. ext3 or ext4, not on Windows filesytems i.e. NTFS, FAT. This is a serious bug while using docker. Just switch to ext4 filesystem and everything will run as expected.

**Comment by jmcollin78** [comment] 2017-01-02 15:18
Same pb here with:
- host windows10,
- vagrant 1.9.1,
- virtualbox 5.1.12,
- vm centos7,
- node 7.3.0 with nvm 

@spescina can't make your solution works. I added those lines in Vagrantfile:
```
config.vm.synced_folder ".", "/vagrant", type:"virtualbox", owner: "vagrant", group: "vagrant", :mount_options=> ['dmode=777', 'fmode=666']
  config.vm.synced_folder "..", "/datas/cld-apps", type:"virtualbox", owner: "vagrant", group: "vagrant", :mount_options=> ['dmode=777', 'fmode=666']
  ...
  config.vm.provider "virtualbox" do |vb|
  vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//datas/cld-apps", "1"]
  vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//vagrant", "1"]
end
```
and `npm install` always give me:
```
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v7.3.0/bin/node" "/home/vagrant/.nvm/versions/node/v7.3.0/bin/npm" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! path ../semver/bin/semver
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../semver/bin/semver' -> '/datas/cld-apps/node_modules/agent-base/node_modules/.bin/semver'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /datas/cld-apps/npm-debug.log
```
May be I'm missing something.

@OElabed I have diffculty to undestand your solution. Are you in the VM ? What dirs are shared with the host (/home/vagrant or [root project folder]) ? Where is the root of your node project ?

Thx in advance for any precision. I'm struggling with this issue for a while now ...

**Comment by bmartus** [comment] 2017-01-09 15:15
I did two things .. not sure which fixed this, but ..

1. Enabled symlinks for my specific user in Local Group Policy (It already was for Administrators, which my account is, so I don't know that this helped at all).  I'm on Windows 10.

2. Ran command prompt as an administrator, and `vagrant up` from there.

Once I did those two things, I could create symlinks on my ubuntu machine.  So I could run `npm install` (`yarn install`, in my case) and it worked without having to use `--no-bin-links` or getting any maximum call stack size exceeded errors.

**Comment by valterbarros** [comment] 2017-02-02 15:35
#9953

**Comment by valterbarros** [comment] 2017-02-02 16:23
@OElabed Don't work here `ln: failed to create symbolic link ‘node_modules’: Resource temporarily unavailable`

**Comment by dilvane** [comment] 2017-03-09 17:33
config.vm.synced_folder "./", "/home/vagrant/app", type: "rsync", rsync__exclude: "./node_modules"
This worked fine for me.

**Comment by bashet** [comment] 2017-03-13 01:40
What I did is: Ran command (npm install) prompt as an administrator, and vagrant up from there
Works fine with no error!

**Comment by raoulduke** [comment] 2017-04-13 04:18
Still experiencing this issue on the latest npm. Running a Windows 7 machine with Homestead on VirtualBox.

```
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v7.9.0/bin/node" "/home/vagrant/.nvm/versions/node/v7.9.0/bin/npm" "install" "--no-bin-links"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Maximum call stack size exceeded
```

I only have a couple dependencies so if I install them all individually it works.

**Comment by vbullinger** [comment] 2018-03-14 14:11
I just needed to run npm rb and then tried npm i again and it worked. So try that first, as it's the least invasive. And npm rb was very fast.
