### ISSUE TITLE
 validation for npm install in node modules

### ISSUE THREAD

**Issue by js08** [npm/npm#10045] opened 2015-10-20 19:52 UTC
I have a react app, in which folder name is sports, inside the sports folder I have node modules, inside the node modules folder I have football folder.
If go to football folder and do npm install react its installing react, which makes my application fail, how to prevent this command npm install from being successful in football folder. Or when I do npm install in football folder it should not install react.
Is it anyway we can right a script to prevent this process to happen, but it should work when we do npm install in sports folder. Is there any already npm packages which we use it make automatically validated our npm commands.

**Comment by KenanY** [comment] 2015-10-21 04:44
Duplicate of https://github.com/npm/npm/issues/10035 by same author.

**Comment by othiym23** [comment] 2015-10-21 04:52
Closing as duplicate of #10035. Good catch, @KenanY.

**Closed by othiym23** 2015-10-21 04:52 UTC
Labels: support

**Comment by js08** [comment] 2015-10-21 05:03
@kenany can you tell how to fix it

**Comment by KenanY** [comment] 2015-10-21 14:52
@js08 I have not looked into this enough yet to produce a response.
