### ISSUE TITLE
Maximum call stack exceeded error while npm install

### ISSUE THREAD

**Issue by sweetest** [npm/npm#11657] opened 2016-02-24 02:46 UTC
seems like there's an infinite loop in are-we-there-yet.

```
59069 silly build preserve@0.2.0
59070 silly build private@0.1.6
59071 silly build process@0.5.2
59072 silly build global@4.3.0
59073 verbose stack RangeError: Maximum call stack size exceeded
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59073 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:9:18)
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59073 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:9:18)
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59073 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:9:18)
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59074 verbose cwd /Users/naver/dev/AwesomeProject
59075 error Darwin 15.0.0
59076 error argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native"
59077 error node v5.7.0
59078 error npm  v3.7.3
59079 error Maximum call stack size exceeded
59080 error If you need help, you may report this error at:
59080 error     <https://github.com/npm/npm/issues>
59081 verbose exit [ 1, true ]
```

**Comment by mcartoixa** [comment] 2016-02-24 07:37
May be a duplicate of #10776. @iarna?

**Comment by othiym23** [comment] 2016-02-24 18:48
This does indeed appear to be the same issue, so closing as duplicate of #10776. Thanks for the assist, @mcartoixa!

**Closed by othiym23** 2016-02-24 18:48 UTC
Labels: big-bug, bug
