### ISSUE TITLE
Npm install WARN package.json

### ISSUE THREAD

**Issue by crisandretta** [npm/npm#12217] opened 2016-04-05 20:36 UTC
I'm getting the following error when trying to build. Can anyone assist, please? It's driving me crazy!

npm WARN package.json unifiedportalweb@0.0.0 No description
npm WARN package.json unifiedportalweb@0.0.0 No repository field.
npm WARN package.json unifiedportalweb@0.0.0 No README data
npm http GET https://registry.npmjs.org/grunt-autoprefixer
npm http GET https://registry.npmjs.org/karma-ie-launcher
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm http 200 https://registry.npmjs.org/karma-ie-launcher
npm ERR! registry error parsing json
npm http 200 https://registry.npmjs.org/grunt-autoprefixer
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
npm ERR! �     ��_o�6�����>E
npm ERR! )Q�lH�X��i[_�!�ȓMG�RJ��gߑR\�]2{�� ���D����������̿�z�A͇F,@�g���k|�#����XNA�Q,�eFY�rI������=�Ъ�U�����[;����\5���4�W��{������7]�j�!����A��Ɵ}�kރ�Q	������k�U��$$!��0g�T��8�#
\qeW�	7�Ҡ�q�Τ�\��{��ֺ�3�i=+�LBU
npm ERR! �{�{��{�.JC�շzmWӯ;��sգ�A�����9JC�vu>zPMz����о�z�`���-�e���Ի�y��g>�E��v�]�����j8\�5��
npm ERR! �%
npm ERR! /�Vd��3I� 7�
npm ERR! �>����ܕ�6���IXطZg��đ5�Vc��Û�pR	׻��d��9o:AP��6 lx�¦[M��NvO�_�Q4�]�Yp3�7���$	Yp�4�!J��1�%�HZ��Q��=�%��-��3�+
sd�ъ�	[=��M��������ߜ͕����61.Qӻ1�QB1!(��?L��y��d}����q6�{��b��M*���&���;��3
���E��̴�����瑙�^�����W�P�bڒ0CWog�F!��
4��
npm ERR! ��T�mz�J|�b��cb��m����sè�B���a
npm ERR! ML�;pHH�9�S��2Oc�T �(iRE2��GtH\�Q�����8�j��$�pȩMO����~Jlx�i}Ll����H��V+#[]a��<�ڈ/jի�V}(�����ĕ��4!�S)e�`,�)Mɥ�I�E<�2#q�����iB�M��*
�S���.�h����������Fë��do;�d{��5���p���4��oSGEѢ]A���Rup}��>T�D�%�$��d��*ϣ��9`��+)R	YB+.,��L�hO�Y ?��(>e��yB�	e���Q��\&첈�Q�򸬲��h\�9/�b@	ɒ��$*JY�E�~,�O�E� �^ԉE'mXt���j�`i�j�:�}�kO�M��&�?!ĕmb��]�꿯(3��;�����1�now�܉ɝ����q|����W����Q
npm ERR! ����oD��8�ha���,�Bf�`<f�d��!������_>��yr}�&��{�w�z���   ���[ao�F�+s6�s!EQ�D���ޥ.�h���\kI.%��rI�j���7��$Kql8F{.H�����������"q���W��2�ݞ��Ro�'����a�'<'NBO��1|���}�ٗ�O��d��g_�;`���H� +b�f�+�ԳGv���>�6X�f>��"����vϬ���B����'۸��摅�j�N-U�<%cl���M
npm ERR! s���M�&�==��������[P�����S7x<�m� ڝ�RT�6��_/d���a�-��̊)O�`�
����>fe�޾��E!gfҚ�ت�C�'�]!Y!b�p���ހм�p�@[����\� �X?a���!V��J��i�!>?� E@��8��������oӛ��oq��7�b[�Җ�4�ꦬr[�0ݺ*z�5���%���ĉ��#�$F�0J<o8x]�GN�8Ѩ%�a/wc�9ۇ���O�o��^��d�w���p��Dr���u�Q2����BgJG�a������'�΋Xn�<�e���_��w�<��4���aϑ�E�9
6h�ga���|<\~���2�\�7_�Q�H[;�3���]HM�3��!����n����?]�W�/ �����q{��Χ6@d+;-:�����	��:�t32,�鬚�R��ZL��_�&�BZ��Z��d���X��qN�Ƥx�a�#h:�}dڣ�,�����[���i��I+G\,s�&�OJ�`�-s��(ͺ��N���U���*�"U�>!/;s� j}T@�̊�-d�C<���@��cr�3~D�G��L�x�T񶡚O�C~G)�<)N��ZA1���(���<��.Cbŏ.f��4���bE����)oi�� &L����W�)\/z�O��d2	������m?Րe)��X�!�to��.����睎a���' +��yי���mQV�N)�U:f�tzB�"S��a+Y��DaY,3U]��]1Շ�������X��5E"�[�e�H�H���|wN���s�Da�"��[[�`岂���t~�7���0�ym����d�B�
npm ERR! �
npm ERR! �stg����-�f��
npm ERR! �L7��=��������g��P8ĀX�׬3�3�oOϴ$C��m4����|F�a7x'%]��(���ɩ�V��'�@]Q�����~k�8���5�-Hı�6���	�����W�@��y$�ի
npm ERR! �y�
npm ERR! Λ�:�(�3���.yu
N���C���d����-��;�NQ
�S⡒sk�b���5�Kǵ��N���D�(JZ�ŖE�t�> ~s����	J�e������ Zb���\ƴ��&����$����M	�i�!0,�exT������$�&xk3�ύ0���6-��:,��:�hwض���-���j��t�[�l՚�jQ�'�K��w�ɮ�&�g�a^c�!��Ss� :����
���c�OC�1�xy#x>���{9l��4�I�3�4i6�}m�AC&���X�Rk�L�B���8��s`�f��>GW:��\��oHױ׆�v�Q�Z�
&�!�� ^gvH7o�9�-��\�~Љd'�,�a��N8�%���_8�rX~��a��e[�\i��r�  �8���|I��@�s[G� �G���p��=O���pGޝ�ܪU'K�R��N*;����Q�;^�.��{'�P�w��!�
wnux��l��������TT)�<�z�$�+|����,g`9��	�n���p4�/3���1�zL�zN/����v�.�s����lh�3$\0�$>]8������-	 ��D���]8��N����(I&�[��_8���8���$@�I�� ����۞��������A�s��o�Q�7W���}'p���-�?'����C��y�H@;�	�6�aiMS��v�º(�c���Q
npm ERR! o���é�;g�=46� ߤ�l�<���ߟ�sn�h�7ܻ-�79�^.o~l��C)|���E���X����٬�&�RܠM�<�N��.����U%���y���/t��9  
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:203:23)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Builds\4\CloudServices\UnifiedPortal-Dev\src
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Builds\4\CloudServices\UnifiedPortal-Dev\src\npm-debug.log
npm ERR! not ok code 0

**Comment by jameshalsall** [comment] 2016-04-05 20:38
Upgrade your npm to latest version:

`npm install -g npm`

**Comment by crisandretta** [comment] 2016-04-05 20:42
I tried that before but when I run npm -v again to check the version it's still showing the old version. For some reason it's not being updated

**Comment by othiym23** [comment] 2016-04-05 20:45
Closing as duplicate of #12196. See there for more details, and check the [Troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting) for details on how to get your npm updated. Thanks for your time!

**Closed by othiym23** 2016-04-05 20:46 UTC
Labels: bug, registry
