### ISSUE TITLE
using --no-optional, but optionalDep still affect the version of packages

### ISSUE THREAD

**Issue by mapleeit** [npm/npm#20769] opened 2018-05-26 05:44 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
using `npm i --no-optional`, but the optionalDependencies still affect the version of other dependencies.

#### How can the CLI team reproduce the problem?

1. `git clone https://github.com/mapleeit/how-to-reproduce-npm-bug.git`
2. `npm i --no-optional`
3. `npm ls | grep request`
```
// it prints 
│ ├─┬ request@2.81.0
│ │ │ │   ├─┬ request@2.87.0
│ │ │ │   ├─┬ request-promise-native@1.0.5
│ │ │ │   │ ├─┬ request-promise-core@1.1.1
    ├── request@2.81.0 deduped
```
__the version of `request` is 2.81.0__

4. `open package.json`
5. delete the `optionalDependencies`
6. `rm -R node_modules && rm package-lock.json`
7. `npm i --no-optional` or `npm i`
8. `npm ls | grep request`
```
// it prints 
│ ├─┬ request@2.87.0
  │ │ │   ├── request@2.87.0 deduped
  │ │ │   ├─┬ request-promise-native@1.0.5
  │ │ │   │ ├─┬ request-promise-core@1.1.1
```
__the version of `request` is 2.87.0__

### supporting information:

 - `npm -v` prints: 6.1.0 
 - `node -v` prints: v8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/ 
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by webpepper** [comment] 2018-05-29 15:19
Seems to be related to https://github.com/npm/npm/issues/17633, which is getting no love :*(

**Comment by roccomuso** [comment] 2018-06-01 14:06
Same issue. npm is getting worse and worse.

**Comment by zkat** [comment] 2018-07-10 19:26
dupe of https://github.com/npm/npm/issues/17633

**Closed as completed by zkat** 2018-07-10 19:26 UTC
