### ISSUE TITLE
JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by cliffano** [npm/npm#3340] opened 2013-04-12 07:17 UTC
I got "JS Allocation failed - process out of memory" error when trying to npm publish a large module (80Mb) with npm v1.2.18 .

The problem did not occur with npm v1.2.11 .

**Comment by jhurliman** [comment] 2015-02-04 23:25
Seeing the same issue as @ronaldpetty

**Comment by kumavis** [comment] 2015-02-20 00:46
```
╭─{👘 } kumavis in ~/Development/Node/vapor on (master✱) 
╰─± npm i "git+https://github.com/ethereum/tests.git#develop"
npm WARN package.json vapor@0.0.0 No repository field.
FATAL ERROR: JS Allocation failed - process out of memory
[1]    40566 abort      npm i "git+https://github.com/ethereum/tests.git#develop"
╭─{👘 } kumavis in ~/Development/Node/vapor on (master✱) 
╰─± node -v
v0.10.35
╭─{👘 } kumavis in ~/Development/Node/vapor on (master✱) 
╰─± npm -v
1.3.7
```

**Comment by othiym23** [comment] 2015-02-20 00:49
@kumavis `npm@1.3.7` is a year and a half old at this point, so it probably needs and upgrade, but beyond that, if you're getting a V8 error like that on a plain install, something else is going wrong. What kind of system are you running on, and how much memory does it have?

**Comment by kumavis** [comment] 2015-02-20 01:02
Yeah I just realized that it was super old! Installs fine now:
```
╭─{👘 } kumavis in ~/Development/Node/vapor on (master✱) 
╰─± npm -v
2.5.1
```

**Comment by B2F** [comment] 2015-02-20 18:22
I faced the problem compressing a package with about 500MB of data. In my case it wasn't intentional but I guess the problem is still there for people genuinely compressing a package this large (it may be questionable for a npm package though).

Either a solution such as [dstovell's](https://github.com/npm/npm/issues/3340#issuecomment-33409540) or setting a size cap would resolve the issue.

**Comment by EmmaRamirez** [comment] 2016-06-30 02:03
npm 1.x is deprecated, so I'm going to close this issue presuming that this problem hasn't arisen since. Thanks for your time everyone!

**Closed by EmmaRamirez** 2016-06-30 02:03 UTC
Labels: bug

**Comment by topaxi** [comment] 2016-06-30 06:16
This is still a problem:
```bash
$ npm --version
3.9.5
$ npm search anything

<--- Last few GCs --->

   13159 ms: Scavenge 986.8 (1434.3) -> 986.8 (1434.3) MB, 6.7 / 0 ms [allocation failure].
   13165 ms: Scavenge 986.8 (1434.3) -> 986.8 (1434.3) MB, 6.4 / 0 ms [allocation failure].
   14052 ms: Mark-sweep 986.8 (1434.3) -> 986.2 (1434.3) MB, 886.9 / 0 ms (+ 597.2 ms in 3750 steps since start of marking, biggest step 5.6 ms) [last resort gc].
   14892 ms: Mark-sweep 986.2 (1434.3) -> 986.2 (1434.3) MB, 840.5 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1c990ac9e59 <JS Object>
    1: stringify [native json.js:164] [pc=0x71d0d872117] (this=0x1c990ac36a9 <a JSON with map 0x126556c095e9>,z=0x6784f962329 <an Object with map 0xaacfdfdb61>,A=0x1c990a04189 <undefined>,N=0x1c990a04189 <undefined>)
    2: arguments adaptor frame: 1->3
    3: /* anonymous */ [/home/dsenn/.nvm/versions/node/v6.2.1/lib/node_modules/npm/lib/cache/update-index.js:96] [pc=0x71d0d85e2e1] (this=0x1c99...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
zsh: abort (core dumped)  npm search anything
```

I can reproduce this on several machines...

**Comment by othiym23** [comment] 2016-06-30 06:34
@topaxi you should take a look at #12619, which is the tracking issue for the generic case of `npm search` blowing up because the search index is too large for the current search implementation to handle. There's a whole set of related issues around memory exhaustion, though, and Emma is right that we no longer support `npm@1`.

**Comment by topaxi** [comment] 2016-06-30 06:34
@othiym23 alright, thanks :)
