### ISSUE TITLE
cannot unpublish readme-utils

### ISSUE THREAD

**Issue by balupton** [npm/npm#12546] opened 2016-05-02 15:32 UTC
https://www.npmjs.com/package/readme-utils

```
$ npm unpublish readme-utils --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "readme-utils" "--force"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/Projects/npm-debug.log
```

```
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/balupton/.nvm/versions/node/v6.0.0/bin/node',
1 verbose cli   '/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'readme-utils',
1 verbose cli   '--force' ]
2 info using npm@3.8.7
3 info using node@v6.0.0
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] readme-utils
6 silly unpublish thing Result {
6 silly unpublish   raw: 'readme-utils',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'readme-utils',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized readme-utils
9 silly gentlyRm /Users/balupton/.npm/readme-utils is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/balupton/.npm/readme-utils
11 silly mapToRegistry name readme-utils
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'readme-utils',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   name: 'readme-utils',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/readme-utils
16 verbose get GET as part of write; not caching result
17 verbose request uri https://registry.npmjs.org/readme-utils?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:31:02 PM
20 verbose request using bearer token for auth
21 verbose request id 0bcc64ad5e5459a3
22 http request GET https://registry.npmjs.org/readme-utils?write=true
23 http 200 https://registry.npmjs.org/readme-utils?write=true
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"DDAYWNCWDU0XVJWFKU68QMKQ9"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'content-encoding': 'gzip',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Mon, 02 May 2016 15:31:02 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-per7621-PER',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1462203061.695597,VS0,VE979',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"DDAYWNCWDU0XVJWFKU68QMKQ9"',
25 silly get     'content-type': 'application/json',
25 silly get     'content-encoding': 'gzip',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Mon, 02 May 2016 15:31:02 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-per7621-PER',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1462203061.695597,VS0,VE979',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving readme-utils to /Users/balupton/.npm/registry.npmjs.org/readme-utils_3Fwrite_3Dtrue/.cache.json
27 verbose correctMkdir /Users/balupton/.npm correctMkdir not in flight; initializing
28 info unpublish No version specified, removing all
29 verbose request uri https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 11:31:03 PM
32 verbose request using bearer token for auth
33 http request DELETE https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
34 http 400 https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
35 verbose headers { 'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   'content-length': '17',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   date: 'Mon, 02 May 2016 15:31:02 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-per7621-PER',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1462203062.710446,VS0,VE267',
35 verbose headers   vary: 'Accept-Encoding' }
36 verbose request invalidating /Users/balupton/.npm/registry.npmjs.org/readme-utils on DELETE
37 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
37 verbose stack     at makeError (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
37 verbose stack     at Request._callback (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
37 verbose stack     at Request.self.callback (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:200:22)
37 verbose stack     at emitTwo (events.js:106:13)
37 verbose stack     at Request.emit (events.js:191:7)
37 verbose stack     at Request.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:1041:10)
37 verbose stack     at emitOne (events.js:101:20)
37 verbose stack     at Request.emit (events.js:188:7)
37 verbose stack     at IncomingMessage.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:968:12)
38 verbose statusCode 400
39 verbose pkgid readme-utils
40 verbose cwd /Users/balupton/Projects
41 error Darwin 15.4.0
42 error argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "readme-utils" "--force"
43 error node v6.0.0
44 error npm  v3.8.7
45 error code E400
46 error Registry returned 400 for DELETE on https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

**Comment by balupton** [comment] 2016-05-02 15:36
Same deal for `mdv`

```
$ npm unpublish mdv --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "mdv" "--force"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/mdv/-rev/2-79b48fd3c9b240e5302ca2b09e3cebbc
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/Projects/npm-debug.log
```

**Comment by balupton** [comment] 2016-05-02 15:37
And `mailer-bal`

```
$ npm unpublish mailer-bal --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "mailer-bal" "--force"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/mailer-bal/-rev/3-fc8265b1905ea37638309d7c10852050
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/Projects/npm-debug.log
```

```
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/balupton/.nvm/versions/node/v6.0.0/bin/node',
1 verbose cli   '/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'mailer-bal',
1 verbose cli   '--force' ]
2 info using npm@3.8.7
3 info using node@v6.0.0
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] mailer-bal
6 silly unpublish thing Result {
6 silly unpublish   raw: 'mailer-bal',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'mailer-bal',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized mailer-bal
9 silly gentlyRm /Users/balupton/.npm/mailer-bal is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/balupton/.npm/mailer-bal
11 silly mapToRegistry name mailer-bal
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'mailer-bal',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   name: 'mailer-bal',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/mailer-bal
16 verbose get GET as part of write; not caching result
17 verbose request uri https://registry.npmjs.org/mailer-bal?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:37:13 PM
20 verbose request using bearer token for auth
21 verbose request id fc875bab6d3a0635
22 http request GET https://registry.npmjs.org/mailer-bal?write=true
23 http 200 https://registry.npmjs.org/mailer-bal?write=true
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"27FGSOBT9J3YVD1UA6JQII4O5"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'content-length': '1640',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Mon, 02 May 2016 15:37:14 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-per7621-PER',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1462203433.078340,VS0,VE940',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"27FGSOBT9J3YVD1UA6JQII4O5"',
25 silly get     'content-type': 'application/json',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'content-length': '1640',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Mon, 02 May 2016 15:37:14 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-per7621-PER',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1462203433.078340,VS0,VE940',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving mailer-bal to /Users/balupton/.npm/registry.npmjs.org/mailer-bal_3Fwrite_3Dtrue/.cache.json
27 verbose correctMkdir /Users/balupton/.npm correctMkdir not in flight; initializing
28 info unpublish No version specified, removing all
29 verbose request uri https://registry.npmjs.org/mailer-bal/-rev/3-fc8265b1905ea37638309d7c10852050
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 11:37:14 PM
32 verbose request using bearer token for auth
33 http request DELETE https://registry.npmjs.org/mailer-bal/-rev/3-fc8265b1905ea37638309d7c10852050
34 http 400 https://registry.npmjs.org/mailer-bal/-rev/3-fc8265b1905ea37638309d7c10852050
35 verbose headers { 'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   'content-length': '17',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   date: 'Mon, 02 May 2016 15:37:14 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-per7621-PER',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1462203434.037159,VS0,VE301',
35 verbose headers   vary: 'Accept-Encoding' }
36 verbose request invalidating /Users/balupton/.npm/registry.npmjs.org/mailer-bal on DELETE
37 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/mailer-bal/-rev/3-fc8265b1905ea37638309d7c10852050
37 verbose stack     at makeError (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
37 verbose stack     at Request._callback (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
37 verbose stack     at Request.self.callback (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:200:22)
37 verbose stack     at emitTwo (events.js:106:13)
37 verbose stack     at Request.emit (events.js:191:7)
37 verbose stack     at Request.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:1041:10)
37 verbose stack     at emitOne (events.js:101:20)
37 verbose stack     at Request.emit (events.js:188:7)
37 verbose stack     at IncomingMessage.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:968:12)
38 verbose statusCode 400
39 verbose pkgid mailer-bal
40 verbose cwd /Users/balupton/Projects
41 error Darwin 15.4.0
42 error argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "mailer-bal" "--force"
43 error node v6.0.0
44 error npm  v3.8.7
45 error code E400
46 error Registry returned 400 for DELETE on https://registry.npmjs.org/mailer-bal/-rev/3-fc8265b1905ea37638309d7c10852050
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

**Comment by balupton** [comment] 2016-05-02 15:39
Another:

```
$ npm unpublish html2coffeekup-bal --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "html2coffeekup-bal" "--force"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/html2coffeekup-bal/-rev/5-0663ac1339d72932004130b668c949f0
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/Projects/npm-debug.log
```

```
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/balupton/.nvm/versions/node/v6.0.0/bin/node',
1 verbose cli   '/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'html2coffeekup-bal',
1 verbose cli   '--force' ]
2 info using npm@3.8.7
3 info using node@v6.0.0
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] html2coffeekup-bal
6 silly unpublish thing Result {
6 silly unpublish   raw: 'html2coffeekup-bal',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'html2coffeekup-bal',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized html2coffeekup-bal
9 silly gentlyRm /Users/balupton/.npm/html2coffeekup-bal is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/balupton/.npm/html2coffeekup-bal
11 silly mapToRegistry name html2coffeekup-bal
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'html2coffeekup-bal',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   name: 'html2coffeekup-bal',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/html2coffeekup-bal
16 verbose get GET as part of write; not caching result
17 verbose request uri https://registry.npmjs.org/html2coffeekup-bal?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:39:06 PM
20 verbose request using bearer token for auth
21 verbose request id 2a56914c03db42fe
22 http request GET https://registry.npmjs.org/html2coffeekup-bal?write=true
23 http 200 https://registry.npmjs.org/html2coffeekup-bal?write=true
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"31T2FQHGVDBZORM022MLT9A42"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'content-length': '2627',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Mon, 02 May 2016 15:39:07 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-per7622-PER',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1462203546.226948,VS0,VE973',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     etag: '"31T2FQHGVDBZORM022MLT9A42"',
25 silly get     'content-type': 'application/json',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'content-length': '2627',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Mon, 02 May 2016 15:39:07 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-per7622-PER',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1462203546.226948,VS0,VE973',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving html2coffeekup-bal to /Users/balupton/.npm/registry.npmjs.org/html2coffeekup-bal_3Fwrite_3Dtrue/.cache.json
27 verbose correctMkdir /Users/balupton/.npm correctMkdir not in flight; initializing
28 info unpublish No version specified, removing all
29 verbose request uri https://registry.npmjs.org/html2coffeekup-bal/-rev/5-0663ac1339d72932004130b668c949f0
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 11:39:07 PM
32 verbose request using bearer token for auth
33 http request DELETE https://registry.npmjs.org/html2coffeekup-bal/-rev/5-0663ac1339d72932004130b668c949f0
34 http 400 https://registry.npmjs.org/html2coffeekup-bal/-rev/5-0663ac1339d72932004130b668c949f0
35 verbose headers { 'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   'content-length': '17',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   date: 'Mon, 02 May 2016 15:39:08 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-per7622-PER',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1462203547.217888,VS0,VE1032',
35 verbose headers   vary: 'Accept-Encoding' }
36 verbose request invalidating /Users/balupton/.npm/registry.npmjs.org/html2coffeekup-bal on DELETE
37 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/html2coffeekup-bal/-rev/5-0663ac1339d72932004130b668c949f0
37 verbose stack     at makeError (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
37 verbose stack     at Request._callback (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
37 verbose stack     at Request.self.callback (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:200:22)
37 verbose stack     at emitTwo (events.js:106:13)
37 verbose stack     at Request.emit (events.js:191:7)
37 verbose stack     at Request.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:1041:10)
37 verbose stack     at emitOne (events.js:101:20)
37 verbose stack     at Request.emit (events.js:188:7)
37 verbose stack     at IncomingMessage.<anonymous> (/Users/balupton/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/request/request.js:968:12)
38 verbose statusCode 400
39 verbose pkgid html2coffeekup-bal
40 verbose cwd /Users/balupton/Projects
41 error Darwin 15.4.0
42 error argv "/Users/balupton/.nvm/versions/node/v6.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.0.0/bin/npm" "unpublish" "html2coffeekup-bal" "--force"
43 error node v6.0.0
44 error npm  v3.8.7
45 error code E400
46 error Registry returned 400 for DELETE on https://registry.npmjs.org/html2coffeekup-bal/-rev/5-0663ac1339d72932004130b668c949f0
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

**Comment by balupton** [comment] 2016-05-02 15:50
Also:

- https://www.npmjs.com/package/generator-chainy-plugin
- https://www.npmjs.com/package/generator-chainy-bundle
- https://www.npmjs.com/package/generator-chainy
- https://www.npmjs.com/package/es6templatetest
- https://www.npmjs.com/package/es6guardian
- https://www.npmjs.com/package/bootstrap.docpad
- https://www.npmjs.com/package/chainy-bundle-official

**Comment by KenanY** [comment] 2016-05-02 15:52
@balupton Probably because of the [recent change in unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy).

**Comment by balupton** [comment] 2016-05-02 15:55
@KenanY that makes it even stranger, as one of them worked fine, which was a very old package:

```
23:28:47:balupton@balmac-2.local:/Users/balupton/Projects:master
$ npm unpublish pulverizer-bal --force
npm WARN using --force I sure hope you know what you are doing.
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
```

**Comment by busches** [comment] 2016-08-10 22:55
Is this issue still occurring?

**Comment by balupton** [comment] 2016-08-19 11:00
```
$ npm unpublish pulverizer-bal --force
npm WARN using --force I sure hope you know what you are doing.
- pulverizer-bal
```

now works thanks!

**Comment by busches** [comment] 2016-08-19 12:51
@balupton can you close the issue too? :)

**Comment by balupton** [comment] 2016-08-19 12:54
Still some failures, will try the rest later:

```
$ npm unpublish readme-utils --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.3.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.3.0/bin/npm" "unpublish" "readme-utils" "--force"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/readme-utils/-rev/3-d44826a6bff392e062d3be5624d5ecf4
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/npm-debug.log
```

**Comment by othiym23** [comment] 2016-08-19 15:37
You can unpublish packages from the primary registry only within 24 hours of first publishing it, as per npm's updated [unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy). If an unpublish attempt succeeds outside that window, it's a fluke or bug that should be reported to the [registry team](https://github.com/npm/registry/issues).

Ordinarily, unpublishing outside that window requires the assistance of support@npmjs.com. As such, I'm going to close this issue and redirect you there, because this is the system working as designed. Thanks for your time, and our support team will be happy to get you sorted out!

**Closed by othiym23** 2016-08-19 15:37 UTC
Labels: registry, support

**Comment by balupton** [comment] 2016-08-19 21:00
@othiym23 then shouldn't https://github.com/npm/npm/issues/12546#issuecomment-240989716 have failed?

**Comment by othiym23** [comment] 2016-08-19 22:10
@balupton, see this piece of my reply:
> If an unpublish attempt succeeds outside that window, it's a fluke or bug that should be reported to the [registry team](https://github.com/npm/registry/issues).

**Comment by balupton** [comment] 2016-08-19 22:25
Okay. Figured that was for future use. Will do.

Also emailed support and all packages listed a above are now gone. Yay!
