### ISSUE TITLE
npm Error : EBUSY resource busy or locked

### ISSUE THREAD

**Issue by scagulanna** [npm/npm#13461] opened 2016-07-22 22:42 UTC
I am new to angulr and each time i try to run the npm install to install packages in package.json, i get the following error

```
C:\Users\Chinedu>cd plans
The system cannot find the path specified.

C:\Users\Chinedu>cd desktop

C:\Users\Chinedu\Desktop>
C:\Users\Chinedu\Desktop>cd plans

C:\Users\Chinedu\Desktop\Plans>cd angular2

C:\Users\Chinedu\Desktop\Plans\Angular2>cd angular2-quickstart

C:\Users\Chinedu\Desktop\Plans\Angular2\angular2-quickstart>npm install
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.
npmjs.org\_40angular\upgrade\-\upgrade-2.0.0-rc.4.tgz.3208765519' -> 'C:\Users\C
hinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.npmjs.org\_40angular\upgrad
e\-\upgrade-2.0.0-rc.4.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chinedu\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.
npmjs.org\_40angular\http\-\http-2.0.0-rc.4.tgz.3495958710' -> 'C:\Users\Chinedu
\AppData\Local\Temp\npm-7276-2a3723d9\registry.npmjs.org\_40angular\http\-\http-
2.0.0-rc.4.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chinedu\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.
npmjs.org\_40angular\upgrade\-\upgrade-2.0.0-rc.4.tgz.3192006008' -> 'C:\Users\C
hinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.npmjs.org\_40angular\upgrad
e\-\upgrade-2.0.0-rc.4.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chinedu\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.
npmjs.org\_40angular\http\-\http-2.0.0-rc.4.tgz.3801615371' -> 'C:\Users\Chinedu
\AppData\Local\Temp\npm-7276-2a3723d9\registry.npmjs.org\_40angular\http\-\http-
2.0.0-rc.4.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chinedu\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Please any idea how to resolve this. It always happens each time i use the npm install tool, i always get the resource locked or busy error message

**Comment by ernanirst** [comment] 2016-08-08 19:19
Hello @scagulanna I found myself with the same issue on windows 10. At first I tried to delete the directory indicated, for you that would be `C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\`. But when I ran npm again, it would throw the same error on another similar path.

So what worked for me was deleting all directories on `C:\Users\Chinedu\AppData\Local\Temp\` that start with `npm-`.

Hope this works for you too.

**Comment by othiym23** [comment] 2016-08-19 22:38
```
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.npmjs.org\_40angular\upgrade\-\upgrade-2.0.0-rc.4.tgz.3208765519' -> 'C:\Users\Chinedu\AppData\Local\Temp\npm-7276-2a3723d9\registry.npmjs.org\_40angular\upgrade\-\upgrade-2.0.0-rc.4.tgz'
```

Closing as a duplicate of #8564. The issue with `tarball.destroy` not being set has also been addressed in recent versions of `npm@3`, at least, so do give upgrading npm a try if you run into this problem.

**Closed by othiym23** 2016-08-19 22:38 UTC
Labels: support, windows

**Comment by joel61** [comment] 2016-10-29 18:51
The problem was got solved by running the same command with "Run as Administrator" in command prompt.

**Comment by yashpalpuri** [comment] 2017-01-31 05:00
I resolved with `npm cache clean `

**Comment by shahidkarimi** [comment] 2017-02-21 19:41
This issue is still unresolved.

**Comment by karthiksundar** [comment] 2017-02-26 13:34
In Windows 10, I have resolved this issue by uninstalling Anti-Malware software.

**Comment by sana4591** [comment] 2017-03-06 13:40
@karthiksundar  , uninstalling Anti-Malware  solved the issue on my behalf, million thanks.

**Comment by kennyedward** [comment] 2017-04-21 12:34
Running the command prompt as an admin solved this issue for me

**Comment by mahrizal** [comment] 2017-05-10 06:19
@karthiksundar  it works for me 
Thanks a lot

**Comment by chaitanyachekuri** [comment] 2017-05-25 15:29
@karthiksundar Thanks, A Lot. Stupid Malware. Good for nothing

**Comment by Jimit09** [comment] 2017-06-16 13:46
Thanks a lot!! Uninstalling the Malware worked for me too.

**Comment by ElTimuro** [comment] 2017-07-10 17:31
Solved by deactivating Antivir :)

**Comment by shingenko** [comment] 2017-07-13 20:17
Wanted to add a comment. I was running into this issue. I didn't have any antivirus running. What I did have though was saving the file into a Dropbox folder. Dropbox sync service appears to have been locking up the file. I killed dropbox, then `npm install` worked just fine. Restarted Dropbox again once my npm config was how I wanted it.

**Comment by vinaypdgr8** [comment] 2017-07-14 19:34
Node Latest Current Version: v8.1.4 (includes npm 5.0.3) from www.nodejs.org worked for me

**Comment by mrshyi** [comment] 2017-07-28 07:17
The problem was got solved by running the same command again.
But I want to look for a better way.

**Comment by randre70** [comment] 2017-08-02 15:23
npm is failing on me for one and the same package.json (attached, log file attached) for the last 3 hours. 
I'm on:


Windows 10 Professional 64 Bit
node -v: 7.10.0
npm -v : 4.6.1

I tried "npm cache clean", run as administrator, deleting node_modules, ... but it keeps failing with:
 
npm ERR! path D:\GIT\cms-global\cms.global\src\cms.global.wpl.web.home\assets\node_modules\.staging\has-flag-1c1a2c46\package.json.1212840727
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename
npm ERR! EBUSY: resource busy or locked, rename 'D:\GIT\cms-global\cms.global\src\cms.global.wpl.web.home\assets\node_modules\.staging\has-flag-1c1a2c46\package.json.1212840727' -> 'D:\GIT\cms-global\cms.global\src\cms.global.wpl.web.home\assets\node_modules\.staging\has-flag-1c1a2c46\package.json'

Afterwards the node_modules folder is always empty.
Please advise ... or where can I try to implement a "try, catch, wait and retry three times kind of behavior "?


[package.json.txt](https://github.com/npm/npm/files/1194421/package.json.txt)
[2017-08-02T15_15_35_001Z-debug.log.txt](https://github.com/npm/npm/files/1194420/2017-08-02T15_15_35_001Z-debug.log.txt)

Same applies to LTS version (v6.11.2 with npm 3.10.10) (fresh install, deleted all directories, ...).
See second log file: [npm-debug.log.txt](https://github.com/npm/npm/files/1194539/npm-debug.log.txt)
Latest console output: [console-output.txt](https://github.com/npm/npm/files/1194560/console-output.txt)

**Comment by wufeng87** [comment] 2017-08-08 02:37
Solved by unchecking some read only of derectory properties.

**Comment by pkitatta** [comment] 2017-08-16 17:22
Thanks a lot @karthiksundar. The most annoying thing is that the bloody anti-malware installed its self!

**Comment by mihirkadam** [comment] 2017-08-19 12:02
It is caused by the anti-malware software. disabled the anti-malware software and try again.
https://stackoverflow.com/questions/36835882/npm-err-tarball-destroy-is-not-a-function#

**Comment by cyber2024** [comment] 2017-11-15 05:55
I find that this happens when gulp fails to transpile, leaving a nodejs process running in the background. 
End this task and you can start the bastard back up.

**Comment by Darren80** [comment] 2017-11-22 16:05
Disable your Dropbox.

**Comment by Skura23** [comment] 2018-01-20 14:27
Thanks @karthiksundar. I stopped the anti-malware and the problem is solved.

**Comment by Nikhilkapoor20** [comment] 2018-02-02 13:07
Tried with disabling byte fence anti malware in my system and it worked
steps : go to task manager 
look for byte fence anti malware and click on end process 

Here you go!

**Comment by KamranSadiq1** [comment] 2018-02-02 19:49
In my case close all terminals and again run the command solve the problem.

**Comment by saber13812002** [comment] 2018-02-24 10:50
after disabling the antivirus also worked for me !!!!

**Comment by Phanindra34** [comment] 2018-03-02 02:52
Im my case I build the project where the dist folder didn't build properly.
just deleted all the local temp files and Dist folder reopened my IDE (VC) the then build my code. its worked perfectly

**Comment by ngmartinezs** [comment] 2018-03-21 02:58
Hi in my case, the issue was resolved by inactivating the antivirus

**Comment by RyanQuey** [comment] 2018-03-24 17:53
In my case restarting my computer was what solved it for me :)

I'm not sure what in particular it did, but maybe there was some process going that needed to get killed. Either way, even after deleting the `dist` folder and trying again, nothing solved it for me except restarting

**Comment by venkat0289** [comment] 2018-04-08 07:45
I did quit the byte fence in my windows 10 machine. Now it is working fine.

**Comment by shabith** [comment] 2018-04-24 03:49
disabling real-time protection in windows defender fixed this issue.

**Comment by Brendan-Bormann** [comment] 2018-05-08 02:41
I ran into this same issue, however, I seemed to solve mine with an `npm update` and that seemed to allow me to install it.

**Comment by jmaicaaan** [comment] 2018-05-09 15:07
I solved mine by doing these things
- disable windows defender (optional)
- `npm update` 
- running this command in Administration `npm --add-python-to-path='true' --debug install --global windows-build-tools` 

Btw, i'm using a windows 10 machine. I'm not sure if disabling windows defender really helps but yeah I now can't reproduce the issue. Hope this helps everyone!

**Comment by bodduuec** [comment] 2018-05-28 06:50
@karthiksundar, Thanks a lot...it worked after uninstalling anti malware software.

**Comment by venkatprabu5** [comment] 2018-06-07 06:43
Resolved after uninstall anti malware also do npm cache clean

**Comment by GaoQianhui1991** [comment] 2018-06-19 02:52
I closed the Visual Studio 2017 and the Visual Studio Code，then open cmd to run command，the problem got solved
