### ISSUE TITLE
"npm install git+ssh://… --save" saves file: dependency pointing to tmp

### ISSUE THREAD

**Issue by timoxley** [npm/npm#7191] opened 2015-01-22 09:00 UTC
Trying to install and save a git dependency from the command line. Installs fine, but saves it as `file:` dependency pointing into `$TMPDIR`. This doesn't seem correct.

From command line:
```
npm install git+ssh://git@github.com/isaacs/inherits --save
```

package.json:

```json
{
  "name": "npm-gitssh",
  "version": "1.0.0",
  "dependencies": {
    "inherits": "file:../../../../../var/folders/8n/ndny7fjs1vd60sj48ht4mkjr0000gn/T/npm-14078-8f2e7129/1421917088600-0.82927759247832/3af5a10c6b51f9e99d9f90394645d7ea630d5eaa"
  }
}
```

**Comment by smikes** [comment] 2015-01-22 12:41
Thanks for the bug report /cc @othiym23 ; can reproduce this behavior in `npm@2.3.0`

**Comment by KenanY** [comment] 2015-01-22 15:11
Dupe of https://github.com/npm/npm/issues/7121

**Comment by othiym23** [comment] 2015-01-24 05:30
Closing as a dupe of #7121, which is already tagged with both `next-patch` and `patch-welcome`, so once my product engineering pile is beaten down a little (i.e. once `registry-2` is up and moderately stable and `npm@3` is into beta), this will be at the top of the list.

**Closed by othiym23** 2015-01-24 05:30 UTC
Labels: bug
