### ISSUE TITLE
Propagate signals to child processes with `npm start`

### ISSUE THREAD

**Issue by Wilfred** [npm/npm#8162] opened 2015-05-02 16:05 UTC
```
$ npm start &
$ pkill npm
```
To my surprise, this leaves the child subprocess running. There is [a separate npm-start package](https://github.com/mafintosh/npm-start) to work around this, but it would be nice if npm did this itself.

This makes it hard to use `npm start` with process runners like `supervisord`. I'm forced to write `node path/to/script.js` instead which ideally would be abstracted by `npm start`.

Possibly related: #7919.

**Comment by jvivs** [comment] 2015-11-24 16:47
I can replicate and am experiencing this issue with deployed node applications.

Is `npm` supposed to be capable of being used in concert with keep-alive tools like `supervisor`? If `npm` intends the script interface to be used in production, it seems like this might be more of a bug than a feature request.

**Comment by jasonkarns** [comment] 2015-11-24 16:53
> more of a bug than a feature request.

:+1: 

We use npm-scripts for everything *except* running our app in production for precisely this reason. Our npm scripts cover various build configurations, test configurations, etc. And our team uses npm-start locally for development. But in production, we rely on supervisord, and hence can't use npm-start. We have to fall back to `node path/to/app.js`.

**Comment by lo1tuma** [comment] 2015-11-27 11:53
Looks like a duplicate of #4603.

**Comment by othiym23** [comment] 2016-03-03 22:16
This is indeed a duplicate of #4603, and is also handled, in part, by the pending PR #10868. Thanks for your time!

**Closed by othiym23** 2016-03-03 22:16 UTC
Labels: feature-request

**Comment by Wilfred** [comment] 2016-03-03 23:32
Great news! Thanks.
