### ISSUE TITLE
error building index for first time

### ISSUE THREAD

**Issue by CoAxLab** [npm/npm#13543] opened 2016-08-01 17:06 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Building index for first time produces the error:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

#### How can the CLI team reproduce the problem?
$ npm search hyperterm
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "search" "hyperterm"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

  100253 ms: Mark-sweep 899.4 (1185.6) -> 898.9 (1193.6) MB, 479.9 / 0 ms (+ 121.4 ms in 624 steps since start of marking, biggest step 8.3 ms) [allocation failure] [GC in old space requested].
  101168 ms: Mark-sweep 898.9 (1193.6) -> 873.8 (1171.1) MB, 915.0 / 0 ms [allocation failure] [GC in old space requested].
  102133 ms: Mark-sweep 873.8 (1171.1) -> 873.8 (1165.1) MB, 965.4 / 0 ms [last resort gc].
  103060 ms: Mark-sweep 873.8 (1165.1) -> 873.8 (1158.1) MB, 926.6 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2df9112c9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x282c780c2bd0] (this=0x2df911204189 <undefined>,string=0x329e5366c9e1 <Very long string[187904824]>,encoding=0x2df9112d7a21 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x282c780982f6] (this=0x1bbf4a8e4c71 <JS Function Buffer (SharedFunctionInfo 0x2df9112e3831)>,value=0x329e5366c9e1 <Very long string[187904824]>,encodingOrOffset=0x2df9...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x282c77b0961b
Abort trap: 6

### supporting information:

 - `npm -v` prints:
3.10.3
 - `node -v` prints:
v6.3.1
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X, or Linux?:
  System Version:	OS X 10.11.6 (15G31)
  Kernel Version:	Darwin 15.6.0
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by BurtHarris** [comment] 2016-08-10 01:04
I've been getting this too on Windows 10.   
npm -v prints 3.10.5
node-v prints v6.3.1
npm config get registry prints https://registry.npmjs.org/
ver prints Microsoft Windows [Version 10.0.14393]

C:\my\shebang-win>npm search win32
npm WARN Building the local index for the first time, please be patient
[..................] / : WARN Building the local index for the first time, please be patient
<--- Last few GCs --->

   29858 ms: Mark-sweep 910.4 (1196.7) -> 908.8 (1202.7) MB, 416.9 / 0 ms (+ 128.5 ms in 823 steps since start of marking, biggest step 6.9 ms) [allocation failure] [GC in old space requested].
   30630 ms: Mark-sweep 908.8 (1202.7) -> 883.4 (1185.1) MB, 772.1 / 0 ms [allocation failure] [GC in old space requested].
   31426 ms: Mark-sweep 883.4 (1185.1) -> 883.4 (1179.1) MB, 795.9 / 0 ms [last resort gc].
   32176 ms: Mark-sweep 883.4 (1179.1) -> 883.3 (1172.1) MB, 750.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000012F864C9E51 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=00000105356FE050] (this=0000012F86404189 <undefined>,string=000001B730BB4771 <Very long string[190072575]>,encoding=0000012F864D6359 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=00000105356BB916] (this=00000026E49A7B11 <JS Function Buffer (SharedFunctionInfo 0000012F864E38D9)>,value=000001B730BB4771 <Very long string[190072575]>,encod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by CoAxLab** [comment] 2016-08-10 12:14
Upgraded to node from 3.10.3 to 3.10.6 and npm is still crashing:

$ npm search hyperterm
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "search" "hyperterm"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

  436664 ms: Mark-sweep 909.0 (1323.7) -> 883.7 (1303.1) MB, 799.0 / 0 ms [allocation failure] [GC in old space requested].
  437513 ms: Mark-sweep 883.7 (1303.1) -> 883.7 (1301.1) MB, 849.3 / 0 ms [allocation failure] [GC in old space requested].
  438424 ms: Mark-sweep 883.7 (1301.1) -> 883.7 (1295.1) MB, 911.1 / 0 ms [last resort gc].
  439332 ms: Mark-sweep 883.7 (1295.1) -> 883.7 (1289.1) MB, 908.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x378b463c9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x238bff8d38d0] (this=0x378b46304189 <undefined>,string=0x3828dbc250b1 <Very long string[190187140]>,encoding=0x378b463d7a21 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x238bff8b44b6] (this=0x3ba5a6ce1e41 <JS Function Buffer (SharedFunctionInfo 0x378b463e3831)>,value=0x3828dbc250b1 <Very long string[190187140]>,encodingOrOffset=0x378b...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x238bfef0961b
Abort trap: 6

**Comment by boeserwolf** [comment] 2016-08-11 08:55
Same over here on OS X 10.11.6 with npm 3.10.5:

npm search pug
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "search" "pug"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5

npm ERR! Cannot read property '_updated' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

   47340 ms: Mark-sweep 910.6 (1326.7) -> 910.0 (1334.7) MB, 116.9 / 0 ms (+ 550.2 ms in 2322 steps since start of marking, biggest step 5.9 ms) [allocation failure] [GC in old space requested].
   48045 ms: Mark-sweep 910.0 (1334.7) -> 884.7 (1312.1) MB, 704.8 / 0 ms [allocation failure] [GC in old space requested].
   48771 ms: Mark-sweep 884.7 (1312.1) -> 884.7 (1306.1) MB, 726.3 / 0 ms [last resort gc].
   49480 ms: Mark-sweep 884.7 (1306.1) -> 884.7 (1300.1) MB, 708.9 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1fdb1cdc9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x3c769face3b0] (this=0x1fdb1cd04189 <undefined>,string=0x1634915d9a29 <Very long string[190429130]>,encoding=0x1fdb1cdd7a21 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x3c769faa8296] (this=0x22950cae51a9 <JS Function Buffer (SharedFunctionInfo 0x1fdb1cde3831)>,value=0x1634915d9a29 <Very long string[190429130]>,encodingOrOffset=0x1fdb...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
12: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x3c769f60961b
[1]    59030 abort      npm search pug

**Comment by icedoe** [comment] 2016-08-14 23:11
And linux...

npm search hyperterm
npm ERR! Linux 4.7.0-0-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "search" "hyperterm"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

   24383 ms: Mark-sweep 913.3 (1332.7) -> 888.0 (1309.1) MB, 746.5 / 0 ms [allocation failure] [GC in old space requested].
   25189 ms: Mark-sweep 888.0 (1309.1) -> 888.0 (1307.1) MB, 806.8 / 0 ms [allocation failure] [GC in old space requested].
   25998 ms: Mark-sweep 888.0 (1307.1) -> 888.0 (1301.1) MB, 808.6 / 0 ms [last resort gc].
   26794 ms: Mark-sweep 888.0 (1301.1) -> 888.0 (1294.1) MB, 795.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3661e3bc9e31 <JS Object>
    1: fromString(aka fromString) [buffer.js:194] [pc=0x3bbc93f3e070] (this=0x3661e3b04189 <undefined>,string=0x13c6d5dd4709 <Very long string[191199451]>,encoding=0x3661e3bd7a21 <String[4]: utf8>)
    2: from [buffer.js:94] [pc=0x3bbc94591ef6] (this=0x1cae626e3361 <JS Function Buffer (SharedFunctionInfo 0x3661e3be3259)>,value=0x13c6d5dd4709 <Very long string[191199451]>,encodingOrOffset=0x3661...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [npm]
 2: 0xc8a7dc [npm]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [npm]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
13: 0x72dd6a [npm]
14: 0x72e26c [npm]
15: 0x3bbc93f0961b
Aborted (core dumped)

**Comment by zkat** [comment] 2016-08-23 23:37
closing as a duplicate of https://github.com/npm/npm/issues/12619

**Closed by zkat** 2016-08-23 23:37 UTC
