### ISSUE TITLE
Yeoman issue when I install with command "npm install -g yo"

### ISSUE THREAD

**Issue by AlexCao2016** [npm/npm#11694] opened 2016-02-26 07:49 UTC
npm ERR! Error: No compatible version found: fullname@'^2.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.2.0","1.0.0","1.1.0","1.1.1","2.0.0","2.0.1","2.1.0","3.0.0"]
npm ERR!     at installTargetsError (C:\nodejs\node_modules\npm\lib\cache.js:719:10)
npm ERR!     at C:\nodejs\node_modules\npm\lib\cache.js:641:10
npm ERR!     at saved (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" npm ERR! cwd C:\gds\drug-management
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32

**Comment by KenanY** [comment] 2016-02-26 12:37
@AlexCao2016 Try the [latest stable release of `npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first. Your `npm` version is years old and is no longer supported.

The issue is that it does not support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: fullname@'^2.0.0'
```

Hence it fails to find a version that matches the range.

**Comment by KenanY** [comment] 2016-06-07 20:37
@AlexCao2016 It has been a few months with no reply from you... are you still seeing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment] 2016-06-28 19:52
Closing as abandoned (just as `npm@1.2` has been for a looong time).

**Closed by KenanY** 2016-06-28 19:52 UTC
Labels: support, windows
