### ISSUE TITLE
NPM UPdate not working

### ISSUE THREAD

**Issue by zeusbangayan** [npm/npm#16278] opened 2017-04-07 08:38 UTC
npm update --save not working

**Comment by KenanY** [comment] 2017-04-07 11:17
@zeusbangayan At the very least, could you please provide your `npm-debug.log` file as a [gist](https://gist.github.com/) along with a small set of steps I can follow to reproduce your issue?

**Comment by KenanY** [comment] 2017-05-30 17:20
Closing due to no reply after a month.

**Closed by KenanY** 2017-05-30 17:20 UTC
