### ISSUE TITLE
npm install problem on Travis CI sever

### ISSUE THREAD

**Issue by Janpot** [npm/npm#4491] opened 2014-01-15 12:11 UTC
npm fails to install a certain dependency on the Travis CI Linux VM's

    npm i git://github.com/ElbertF/Wappalyzer.git#c1f9ca14ae7abbaec9cd5dd2c8520b4e03579e38

On my mac I have no problem whatsoever installing this dependency.

Here's the debug log I received from Travis CI support team: https://gist.github.com/joshk/6d0f485b5c2f5b6bf70c

**Comment by smikes** [comment] 2015-01-06 13:01
@janpot Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest` ; you can include this command in your travis scripts.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-01-15 17:45
Closing as abandoned. I'm going to guess this was probably tied to the registry instability of a year or so ago that somehow bit Travis harder than other users, but this isn't reproducible now either way.

**Closed by othiym23** 2015-01-15 17:45 UTC
Labels: support
