### ISSUE TITLE
Missing top level dependencies after npm install

### ISSUE THREAD

**Issue by naholyr** [npm/npm#10257] opened 2015-11-04 14:49 UTC
I've tried many combinations of my dependencies but really can't find the logic or if there is a single guilty module in my dependencies :( whatever, here is a ``package.json`` to reproduce:

```json
{
  "dependencies": {
    "angular": "^1.4.7",
    "angular-animate": "^1.4.7",
    "angular-bootstrap-colorpicker": "^3.0.19",
    "angular-masonry": "github:delapouite/angular-masonry#nojquery",
    "angular-off-click": "github:lmtm/angular-off-click#npm",
    "angular-sanitize": "^1.4.7",
    "angular-socket-io": "^0.7.0",
    "angular-ui-bootstrap": "^0.14.3",
    "angular-ui-router": "^0.2.15",
    "async": "^1.5.0",
    "babel-eslint": "^4.1.3",
    "bluebird": "^3.0.5",
    "body-parser": "^1.14.1",
    "bootstrap": "^3.3.5",
    "bootstrap-styl": "^4.0.5",
    "busboy": "^0.2.11",
    "chalk": "^1.1.1",
    "commander": "^2.9.0",
    "connect-assets": "^5.0.1",
    "connect-flash": "~0.1.1",
    "connect-mongo": "~0.8.2",
    "connect-redis": "^3.0.1",
    "cors": "^2.7.1",
    "debug": "^2.2.0",
    "deepmerge": "~0.2.10",
    "ect": "~0.5.9",
    "eslint": "^1.8.0",
    "express": "^4.13.3",
    "express-session": "^1.12.1",
    "file-loader": "^0.8.4",
    "gm": "^1.21.1",
    "hiredis": "~0.4.1",
    "html-loader": "^0.3.0",
    "imap": "^0.8.16",
    "imports-loader": "^0.6.5",
    "jquery": "^2.1.4",
    "less": "^2.5.3",
    "lodash": "~3.10.1",
    "mailparser": "0.5.3",
    "masonry-layout": "^3.3.2",
    "method-override": "^2.3.5",
    "mime": "^1.3.4",
    "minimatch": "^3.0.0",
    "moment": "^2.10.6",
    "mongoose": "~4.2.4",
    "mongoose-schema-extend": "^0.1.7",
    "mongoose-timestamp": "^0.4.0",
    "nconf": "~0.8.2",
    "ng-annotate-loader": "0.0.10",
    "ng-file-upload": "^9.1.2",
    "ngtemplate-loader": "^1.3.1",
    "node-transloadit": "0.0.4",
    "node-uuid": "~1.4.3",
    "nodemailer": "^1.8.0",
    "passport": "^0.3.0",
    "passport-local": "^1.0.0",
    "random-string": "~0.1.2",
    "raw-loader": "^0.5.1",
    "redis": "^2.3.0",
    "request": "^2.65.0",
    "serve-favicon": "^2.3.0",
    "serve-static": "^1.10.0",
    "slugify2": "0.0.2",
    "socket.io": "^1.3.7",
    "socket.io-client": "^1.3.7",
    "striptags": "^2.0.4",
    "stylus-loader": "^1.4.2",
    "talon": "^2.3.2",
    "temporary": "0.0.8",
    "transloadit-api": "^1.0.0",
    "wb-angular-slugify": "^1.2.0",
    "winston": "^2.1.0"
  },
  "devDependencies": {
    "aggregate-commands": "^2.1.0",
    "awsbox": "^0.7.0",
    "babel-core": "^6.0.20",
    "babel-loader": "^6.0.1",
    "chai": "^3.4.0",
    "chai-as-promised": "^5.1.0",
    "compression-webpack-plugin": "^0.2.0",
    "css-loader": "^0.21.0",
    "env-test": "^1.0.0",
    "http-server": "^0.8.5",
    "mocha": "^2.3.3",
    "nodemon": "^1.8.1",
    "rewire": "^2.3.4",
    "style-loader": "^0.13.0",
    "protractor": "^2.2.0",
    "stylus": "^0.52.4",
    "supertest": "^1.1.0",
    "watch-exec": "^1.2.0",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1",
    "xhr2": "^0.1.3"
  }
}
```

After first ``npm install`` (which claims it ran **successfully**), there still are missing dependencies (``chalk``, ``debug``, ``lodash``, identified thanks to ``npm ls --depth=0`` and folders are effectively missing). Second ``npm install`` fixes this weird state, but my ``postinstall`` script (supposed to be automatically run on server during first-install...)

During my experiments, some weird things made install work :

* Merging ``devDependencies`` into ``dependencies``
* Removing blocks of dependencies (for example, if I remove all ``a-*`` dependencies)
* Moving ``babel-eslint`` from ``dependencies`` from ``devDependencies`` (which is actually a logical move here)

I'm not really able to explain **why** any of thoses changes actually fix the behavior, nor I am any more able to explain **why** npm considers its install successful with 3 missing top-dependencies :(

**Comment by othiym23** [comment] 2015-11-06 19:54
Closing as duplicate of #10277, which is marked as a big bug, so we'll probably fix it soon. Thanks for the report!

**Closed by othiym23** 2015-11-06 19:54 UTC
