### ISSUE TITLE
problem installing ionic on windows?

### ISSUE THREAD

**Issue by ved54321** [npm/npm#11257] opened 2016-01-23 11:02 UTC
i have install node version 5.4.0 and npm version 3.3.12.While running npm install -g cordova ionic i am getting the following issue,

C:\Windows\system32>npm install -g cordova ionic
'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\b
in\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_m
odules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for C:\Users\admin\AppData\Local\Temp\npm-5768-1aee47db\r
egistry.npmjs.org\ionic-\ionic-1.7.13.tgz
npm ERR! Expected: 0a16c0aea3280acd406938d31165fc0f2d258e06
npm ERR! Actual:   99b3c58da5b825305001e56ce41506fdc1be1c20
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

Any idea why i am getting this error ?

**Comment by ashleygwilliams** [comment] 2016-02-06 18:12
hi! this error is seen often with windows users. can you try npm set registry https://registry.npmjs.org/, then try to install ionic again?

**Comment by ved54321** [comment] 2016-02-07 12:00
Still i am getting another issue,

'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\b
in\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
|
> node-sass@3.4.2 install D:\vedapp\node_modules\ionic\node_modules\node-sass
> node scripts/install.js

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_m
odules\\npm\\bin\\npm-cli.js" "install" "ionic"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! file C:\Program Files\Java\jdk1.7.0_06\lib
npm ERR! path C:\Program Files\Java\jdk1.7.0_06\lib
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Java\jdk1.7.0_06\lib

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn C:\Program Files\Java\jdk1.7.0_06\lib ENOENT
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vedapp\npm-debug.log

**Comment by Sacho** [comment] 2016-03-13 12:05
Hello @ved54321 , I recently had a very similar issue with the exact same warning you had:

'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\b
in\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.

But I was getting a different error:
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe; ENOENT

For me, it turned out that my ComSpec environment variable was set to C:\WINDOWS\system32\cmd.exe; <-- note the semicolon

Looking at your error, perhaps you have a problem with your environment variables as well.You could try pasting them here(you could get them by say running node -p process.env in your terminal). It seems odd that you have "syscall spawn C:\Program Files\Java\jdk1.7.0_06\lib", since that's a directory, not an executable.

**Comment by zkat** [comment] 2016-12-09 00:47
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:47 UTC
Labels: support
