### ISSUE TITLE
error Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by granaderos** [npm/npm#7955] opened 2015-04-15 02:37 UTC
When I was installing ember, this is one of the errors returned.

**Comment by KenanY** [comment] 2015-04-15 02:47
@granaderos Should this be closed in favor of https://github.com/npm/npm/issues/7957?

**Comment by iarna** [comment] 2015-04-15 18:30
Closing as dupe of #7957 & #7956

**Closed by iarna** 2015-04-15 18:30 UTC
