### ISSUE TITLE
install failing to get all deps on Windows Appveyor

### ISSUE THREAD

**Issue by isaacs** [npm/npm#16948] opened 2017-06-03 16:48 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

On appveyor using npm v5.0.0 with node-pre-gyp, it's running `npm install`, but immediately after, some deps are missing.  This log shows the issue:

https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/1.0.561/job/i3i0p734ww1obftb

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Unknown
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment] 2017-06-05 16:25
Closing as duplicate of https://github.com/npm/npm/issues/16902

**Closed as completed by zkat** 2017-06-05 16:25 UTC
Labels: npm5
