### ISSUE TITLE
Improve the error reporting when npm fails to install a package due to missing platform support

### ISSUE THREAD

**Issue by Pomax** [npm/npm#10843] opened 2015-12-15 21:10 UTC
Right now, when NPM installs a package that is unsupported on the target platform, this happens:
```
> npm install
npm WARN install Couldn't install optional dependency: Unsupported
...
```
Which is not particularly useful if you're trying to figure out what just happened, and if that's bad or not. A `--verbose` shows what happened:

```
> npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@3.3.12
npm info using node@v5.1.0
npm verb request uri https://registry.npmjs.org/fsevents
npm verb request no auth needed
npm info attempt registry request try #1 at 1:07:04 PM
npm verb request id 6c4da2707669be2e
npm verb etag "43VWEZO0NHQR9W0RRC4SYHILN"
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm verb headers { date: 'Tue, 15 Dec 2015 21:07:05 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"43VWEZO0NHQR9W0RRC4SYHILN"',
npm verb headers   age: '99',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sjc3120-SJC',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1450213625.032221,VS0,VE0',
npm verb headers   vary: 'Accept' }
npm verb etag https://registry.npmjs.org/fsevents from cache
npm verb get saving fsevents to C:\Users\Mike\AppData\Roaming\npm-cache\registry.npmjs.org\fsevents\.cache.json
npm WARN install Couldn't install optional dependency: Unsupported
npm verb install Error: Unsupported
npm verb install     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:46:14)
npm verb install     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm verb install     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm verb install     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
npm verb install     at checkEngine (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:25:10)
npm verb install     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm verb install     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm verb install     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
npm verb install     at module.exports.isInstallable (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:26:3)
npm verb install     at resolveWithNewModule (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:452:12)
```
but this is something that can probably be reported without verbosity; the following error message would be very useful:

```
npm WARN install Couldn't install optional dependency: Platform win32 not supported by fsevents.
```

**Comment by smikes** [comment] 2015-12-18 03:49
Thanks for pointing this out.  This is a place where a clearer message would help a lot.

**Comment by Pomax** [comment] 2015-12-19 00:26
The "Unsupported" is actually the error generated by fsevents, passed through to npm, but it's probably doable to have npm report the name of the module in question, so that it becomes something like `npm WARN install Couldn't install optional dependency: module_name (reason: thrown_error)` so that in this case it'd become:
```
npm WARN install Couldn't install optional dependency: fsevents (reason: Unsupported)
```

**Comment by Martinspire** [comment] 2016-01-05 23:32
@Pomax +1 for that suggestion!

**Comment by Download** [comment] 2016-01-08 18:35
Actually I just upgraded to latest NPM (3.3.12, that came bundled with Node JS 5 download) and this issue is new. On older versions, NPM did report the name of the module. I was getting used to seeing reports about `fsevents` being unsupported. Now, we don't know which module caused the message so can only guess that is is indeed `fsevents`. It is regression, not really a new feature request.

It is related to `npm@3.5.0 should not be trying to install modules that arch/os say are incompatible` #10768 because why is NPM trying to install `fsevents` in the first place? It is doing this on my Windows machine as well as on Linux (as reported in the issue).

**Comment by zkat** [comment] 2016-01-13 23:07
This is definitely a regression from before. This has been fixed as of `npm@3.5.0`.

**Closed by zkat** 2016-01-13 23:07 UTC
Labels: bug, error-handling, ux

**Comment by Download** [comment] 2016-01-14 00:02
Great to know! Thank you guys! :+1:

**Comment by Pomax** [comment] 2016-01-14 03:54
nice!
