### ISSUE TITLE
Make --save option default in npm install

### ISSUE THREAD

**Issue by aug-riedinger** [npm/npm#12031] opened 2016-03-23 17:16 UTC
As noticed in this [could-have-been-closed-but-fortunately-hasn't SO question](http://stackoverflow.com/questions/27821909/npm-install-save-what-is-the-use-of-not-saving) I hardly find a use case when doing `npm install xxxx` **without** the `--save` option.

Instead, shouldn't there be a `npm install xxxx --nosave`. Indeed, when I forget to add the `--save`, I need to reset all my `node_modules` content, run `npm install xxx --save` again and then `npm install` to make sure my state is the same as someone else doing `npm install` in the first place.
On the other hand, if I set `npm install xxxx --save` while I did not want to save, I simply need to remove a line in my `package.json` file.

My personal guess is that this is historical, as npm was created before the whole `package.json` standardization.

Regarding the SO accepted answer, it appears to be incorrect/imcomplete to me, as the `--save-dev` option hasn't been mentioned. Also my practice is that even for globally installable modules like [Nodemon](http://nodemon.io/) it is a better practice to set them in the `package.json` like so, to make scripts work simply by running `npm install`:

```
{
  "name": "MyApp",
  "version": "1.0.0",
  "description": "",
  "license": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "node app.js",
    "reload": "$(npm bin)/nodemon app.js",
    "dev": "npm run reload"
  },
  "dependencies": {
  },
  "devDependencies": {
    "nodemon": "^1.3.6"
  },
  "engines": {
    "node": "0.12.x"
  }
}

```

Please comment or correct if I'm wrong!

**Comment by weisk** [comment] 2016-03-23 17:27
> Indeed, when I forget to add the --save, I need to reset all my node_modules content, run npm install xxx --save again and then npm install to make sure my state is the same as someone else doing npm install in the first place.

I dont really understand this. By 'reset' you mean deleting them? Why would you need to do that? You can just run the same command again with the --save flag and it will just add the line to your package.json. Am I missing something?

**Comment by KenanY** [comment] 2016-03-23 17:28
Is this a duplicate of https://github.com/npm/npm/issues/5108?

**Comment by zkat** [comment] 2016-03-23 20:52
Closing as a duplicate of #5108

Thanks for the time submitting this. It's a reasonable thing to ask for, and a worthwhile discussion to have, but please refer to the other thread for it. :)

**Closed by zkat** 2016-03-23 20:52 UTC

**Comment by aug-riedinger** [comment] 2016-03-29 09:02
Sure @zkat I was guessing there would already be a discussion about it, but did not find it at first.

Replying to @weisk here: I guess I did not know about this. Glad to read this. I know I have had cases when I needed to delete the whole `node_modules` folder because of module version mismatch between `package.json` and the `node_modules` content. Unfortunately I can't make up a full example yet.

**Comment by weisk** [comment] 2016-03-29 10:08
yeah semantic versioning can lead to version mismatches, depending how you set it up, but in any case you should always be able to run `npm install package@version` to override your current package and get a specific version. It will override the current one.
