### ISSUE TITLE
Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by salihsagdilek** [npm/npm#10449] opened 2015-11-18 10:52 UTC
i upgraded node version 5x and started getting this error.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose stack Error: Cannot find module 'minimatch'
4 verbose stack     at Function.Module._resolveFilename (module.js:338:15)
4 verbose stack     at Function.Module._load (module.js:289:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\glob\glob.js:44:17)
4 verbose stack     at Module._compile (module.js:425:26)
4 verbose stack     at Object.Module._extensions..js (module.js:432:10)
4 verbose stack     at Module.load (module.js:356:32)
4 verbose stack     at Function.Module._load (module.js:313:12)
4 verbose stack     at Module.require (module.js:366:17)
5 verbose cwd X:\cafeV2
6 error Windows_NT 6.2.9200
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "yo"
8 error node v5.1.0
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'minimatch'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by cedx** [comment] 2015-11-18 12:03
Same error than issue #10434.

**Comment by othiym23** [comment] 2015-11-18 17:22
Closing as a duplicate of #10434 – there appears to be an issue with the OS X installer of Node that causes it to improperly clean up the existing npm installation before unpacking the version included in the installer. #10434 has the workaround and my suggested next steps.

**Closed by othiym23** 2015-11-18 17:22 UTC
