### ISSUE TITLE
Not able to install npm in windows 10

### ISSUE THREAD

**Issue by suragar** [npm/npm#11875] opened 2016-03-12 07:03 UTC
Am not able to install npm in windows 10. Please see the attached logs for the same.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData imagesloaded
20 silly mapToRegistry name imagesloaded
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/imagesloaded
24 silly fetchNamedPackageData lodash
25 silly mapToRegistry name lodash
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/lodash
29 silly fetchNamedPackageData promise
30 silly mapToRegistry name promise
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/promise
34 verbose request uri https://registry.npmjs.org/imagesloaded
35 verbose request no auth needed
36 info attempt registry request try #1 at 12:24:39 PM
37 verbose request id 35f2e1657a114c56
38 http request GET https://registry.npmjs.org/imagesloaded
39 verbose request uri https://registry.npmjs.org/lodash
40 verbose request no auth needed
41 info attempt registry request try #1 at 12:24:39 PM
42 http request GET https://registry.npmjs.org/lodash
43 verbose request uri https://registry.npmjs.org/promise
44 verbose request no auth needed
45 info attempt registry request try #1 at 12:24:39 PM
46 http request GET https://registry.npmjs.org/promise
47 http 200 https://registry.npmjs.org/promise
48 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
48 verbose headers   etag: '"1GZ94JI2I0WSVUWQ3CE8P3BIH"',
48 verbose headers   'content-type': 'application/json',
48 verbose headers   'cache-control': 'max-age=300',
48 verbose headers   'content-length': '34761',
48 verbose headers   'accept-ranges': 'bytes',
48 verbose headers   date: 'Sat, 12 Mar 2016 06:54:50 GMT',
48 verbose headers   via: '1.1 varnish',
48 verbose headers   age: '154',
48 verbose headers   connection: 'keep-alive',
48 verbose headers   'x-served-by': 'cache-sin6921-SIN',
48 verbose headers   'x-cache': 'HIT',
48 verbose headers   'x-cache-hits': '2',
48 verbose headers   'x-timer': 'S1457765690.670532,VS0,VE0',
48 verbose headers   vary: 'Accept' }
49 silly get cb [ 200,
49 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
49 silly get     etag: '"1GZ94JI2I0WSVUWQ3CE8P3BIH"',
49 silly get     'content-type': 'application/json',
49 silly get     'cache-control': 'max-age=300',
49 silly get     'content-length': '34761',
49 silly get     'accept-ranges': 'bytes',
49 silly get     date: 'Sat, 12 Mar 2016 06:54:50 GMT',
49 silly get     via: '1.1 varnish',
49 silly get     age: '154',
49 silly get     connection: 'keep-alive',
49 silly get     'x-served-by': 'cache-sin6921-SIN',
49 silly get     'x-cache': 'HIT',
49 silly get     'x-cache-hits': '2',
49 silly get     'x-timer': 'S1457765690.670532,VS0,VE0',
49 silly get     vary: 'Accept' } ]
50 verbose get saving promise to C:\Users\Cherry\AppData\Roaming\npm-cache\registry.npmjs.org\promise\.cache.json
51 verbose correctMkdir C:\Users\Cherry\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
52 verbose makeDirectory C:\Users\Cherry\AppData\Roaming\npm-cache creation not in flight; initializing
53 verbose makeCacheDir UID & GID are irrelevant on win32
54 silly resolveWithNewModule promise@6.1.0 checking installable status
55 silly cache add args [ 'promise@^6.0.1', null ]
56 verbose cache add spec promise@^6.0.1
57 silly cache add parsed spec Result {
57 silly cache add   raw: 'promise@^6.0.1',
57 silly cache add   scope: null,
57 silly cache add   name: 'promise',
57 silly cache add   rawSpec: '^6.0.1',
57 silly cache add   spec: '>=6.0.1 <7.0.0',
57 silly cache add   type: 'range' }
58 silly addNamed promise@>=6.0.1 <7.0.0
59 verbose addNamed ">=6.0.1 <7.0.0" is a valid semver range for promise
60 silly addNameRange { name: 'promise', range: '>=6.0.1 <7.0.0', hasData: false }
61 silly mapToRegistry name promise
62 silly mapToRegistry using default registry
63 silly mapToRegistry registry https://registry.npmjs.org/
64 silly mapToRegistry uri https://registry.npmjs.org/promise
65 verbose addNameRange registry:https://registry.npmjs.org/promise not in flight; fetching
66 verbose get https://registry.npmjs.org/promise not expired, no request
67 silly addNameRange number 2 { name: 'promise', range: '>=6.0.1 <7.0.0', hasData: true }
68 silly addNameRange versions [ 'promise',
68 silly addNameRange   [ '1.2.1',
68 silly addNameRange     '1.2.2',
68 silly addNameRange     '1.3.0',
68 silly addNameRange     '2.0.0',
68 silly addNameRange     '3.0.0',
68 silly addNameRange     '3.0.1',
68 silly addNameRange     '3.1.0',
68 silly addNameRange     '3.2.0',
68 silly addNameRange     '4.0.0',
68 silly addNameRange     '5.0.0',
68 silly addNameRange     '6.0.0',
68 silly addNameRange     '6.0.1',
68 silly addNameRange     '6.1.0',
68 silly addNameRange     '7.0.0',
68 silly addNameRange     '7.0.1',
68 silly addNameRange     '7.0.2',
68 silly addNameRange     '7.0.3',
68 silly addNameRange     '7.0.4',
68 silly addNameRange     '7.1.0',
68 silly addNameRange     '7.1.1' ] ]
69 silly addNamed promise@6.1.0
70 verbose addNamed "6.1.0" is a plain semver version for promise
71 silly mapToRegistry name promise
72 silly mapToRegistry using default registry
73 silly mapToRegistry registry https://registry.npmjs.org/
74 silly mapToRegistry uri https://registry.npmjs.org/promise
75 verbose addRemoteTarball https://registry.npmjs.org/promise/-/promise-6.1.0.tgz not in flight; adding
76 verbose addRemoteTarball [ 'https://registry.npmjs.org/promise/-/promise-6.1.0.tgz',
76 verbose addRemoteTarball   '2ce729f6b94b45c26891ad0602c5c90e04c6eef6' ]
77 info retry fetch attempt 1 at 12:24:41 PM
78 info attempt registry request try #1 at 12:24:41 PM
79 http fetch GET https://registry.npmjs.org/promise/-/promise-6.1.0.tgz
80 http 200 https://registry.npmjs.org/imagesloaded
81 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
81 verbose headers   etag: '"9TOHC3XV1QGVRHJ0CAD9LLUMJ"',
81 verbose headers   'content-type': 'application/json',
81 verbose headers   'cache-control': 'max-age=300',
81 verbose headers   'content-length': '15482',
81 verbose headers   'accept-ranges': 'bytes',
81 verbose headers   date: 'Sat, 12 Mar 2016 06:54:50 GMT',
81 verbose headers   via: '1.1 varnish',
81 verbose headers   age: '0',
81 verbose headers   connection: 'keep-alive',
81 verbose headers   'x-served-by': 'cache-sin6927-SIN',
81 verbose headers   'x-cache': 'HIT',
81 verbose headers   'x-cache-hits': '1',
81 verbose headers   'x-timer': 'S1457765690.712520,VS0,VE206',
81 verbose headers   vary: 'Accept' }
82 silly get cb [ 200,
82 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
82 silly get     etag: '"9TOHC3XV1QGVRHJ0CAD9LLUMJ"',
82 silly get     'content-type': 'application/json',
82 silly get     'cache-control': 'max-age=300',
82 silly get     'content-length': '15482',
82 silly get     'accept-ranges': 'bytes',
82 silly get     date: 'Sat, 12 Mar 2016 06:54:50 GMT',
82 silly get     via: '1.1 varnish',
82 silly get     age: '0',
82 silly get     connection: 'keep-alive',
82 silly get     'x-served-by': 'cache-sin6927-SIN',
82 silly get     'x-cache': 'HIT',
82 silly get     'x-cache-hits': '1',
82 silly get     'x-timer': 'S1457765690.712520,VS0,VE206',
82 silly get     vary: 'Accept' } ]
83 verbose get saving imagesloaded to C:\Users\Cherry\AppData\Roaming\npm-cache\registry.npmjs.org\imagesloaded\.cache.json
84 verbose correctMkdir C:\Users\Cherry\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
85 silly resolveWithNewModule imagesloaded@3.2.0 checking installable status
86 silly cache add args [ 'imagesloaded@^3.1.8', null ]
87 verbose cache add spec imagesloaded@^3.1.8
88 silly cache add parsed spec Result {
88 silly cache add   raw: 'imagesloaded@^3.1.8',
88 silly cache add   scope: null,
88 silly cache add   name: 'imagesloaded',
88 silly cache add   rawSpec: '^3.1.8',
88 silly cache add   spec: '>=3.1.8 <4.0.0',
88 silly cache add   type: 'range' }
89 silly addNamed imagesloaded@>=3.1.8 <4.0.0
90 verbose addNamed ">=3.1.8 <4.0.0" is a valid semver range for imagesloaded
91 silly addNameRange { name: 'imagesloaded', range: '>=3.1.8 <4.0.0', hasData: false }
92 silly mapToRegistry name imagesloaded
93 silly mapToRegistry using default registry
94 silly mapToRegistry registry https://registry.npmjs.org/
95 silly mapToRegistry uri https://registry.npmjs.org/imagesloaded
96 verbose addNameRange registry:https://registry.npmjs.org/imagesloaded not in flight; fetching
97 verbose get https://registry.npmjs.org/imagesloaded not expired, no request
98 silly addNameRange number 2 { name: 'imagesloaded', range: '>=3.1.8 <4.0.0', hasData: true }
99 silly addNameRange versions [ 'imagesloaded', [ '3.1.8', '3.2.0', '4.0.0', '4.1.0' ] ]
100 silly addNamed imagesloaded@3.2.0
101 verbose addNamed "3.2.0" is a plain semver version for imagesloaded
102 silly mapToRegistry name imagesloaded
103 silly mapToRegistry using default registry
104 silly mapToRegistry registry https://registry.npmjs.org/
105 silly mapToRegistry uri https://registry.npmjs.org/imagesloaded
106 verbose addRemoteTarball https://registry.npmjs.org/imagesloaded/-/imagesloaded-3.2.0.tgz not in flight; adding
107 verbose addRemoteTarball [ 'https://registry.npmjs.org/imagesloaded/-/imagesloaded-3.2.0.tgz',
107 verbose addRemoteTarball   '31f7c0840dee77184ce6ff9e81ae51936f4e5384' ]
108 info retry fetch attempt 1 at 12:24:41 PM
109 info attempt registry request try #1 at 12:24:41 PM
110 http fetch GET https://registry.npmjs.org/imagesloaded/-/imagesloaded-3.2.0.tgz
111 http 200 https://registry.npmjs.org/lodash
112 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
112 verbose headers   etag: '"18NG3GUDQV4LOJ4ZCYULVEE5J"',
112 verbose headers   'content-type': 'application/json',
112 verbose headers   'cache-control': 'max-age=300',
112 verbose headers   'content-length': '123965',
112 verbose headers   'accept-ranges': 'bytes',
112 verbose headers   date: 'Sat, 12 Mar 2016 06:54:50 GMT',
112 verbose headers   via: '1.1 varnish',
112 verbose headers   age: '5',
112 verbose headers   connection: 'keep-alive',
112 verbose headers   'x-served-by': 'cache-sin6927-SIN',
112 verbose headers   'x-cache': 'HIT',
112 verbose headers   'x-cache-hits': '1',
112 verbose headers   'x-timer': 'S1457765690.659508,VS0,VE0',
112 verbose headers   vary: 'Accept' }
113 silly get cb [ 200,
113 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
113 silly get     etag: '"18NG3GUDQV4LOJ4ZCYULVEE5J"',
113 silly get     'content-type': 'application/json',
113 silly get     'cache-control': 'max-age=300',
113 silly get     'content-length': '123965',
113 silly get     'accept-ranges': 'bytes',
113 silly get     date: 'Sat, 12 Mar 2016 06:54:50 GMT',
113 silly get     via: '1.1 varnish',
113 silly get     age: '5',
113 silly get     connection: 'keep-alive',
113 silly get     'x-served-by': 'cache-sin6927-SIN',
113 silly get     'x-cache': 'HIT',
113 silly get     'x-cache-hits': '1',
113 silly get     'x-timer': 'S1457765690.659508,VS0,VE0',
113 silly get     vary: 'Accept' } ]
114 verbose get saving lodash to C:\Users\Cherry\AppData\Roaming\npm-cache\registry.npmjs.org\lodash\.cache.json
115 verbose correctMkdir C:\Users\Cherry\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
116 silly resolveWithNewModule lodash@2.4.2 checking installable status
117 silly cache add args [ 'lodash@^2.4.1', null ]
118 verbose cache add spec lodash@^2.4.1
119 silly cache add parsed spec Result {
119 silly cache add   raw: 'lodash@^2.4.1',
119 silly cache add   scope: null,
119 silly cache add   name: 'lodash',
119 silly cache add   rawSpec: '^2.4.1',
119 silly cache add   spec: '>=2.4.1 <3.0.0',
119 silly cache add   type: 'range' }
120 silly addNamed lodash@>=2.4.1 <3.0.0
121 verbose addNamed ">=2.4.1 <3.0.0" is a valid semver range for lodash
122 silly addNameRange { name: 'lodash', range: '>=2.4.1 <3.0.0', hasData: false }
123 silly mapToRegistry name lodash
124 silly mapToRegistry using default registry
125 silly mapToRegistry registry https://registry.npmjs.org/
126 silly mapToRegistry uri https://registry.npmjs.org/lodash
127 verbose addNameRange registry:https://registry.npmjs.org/lodash not in flight; fetching
128 verbose get https://registry.npmjs.org/lodash not expired, no request
129 silly addNameRange number 2 { name: 'lodash', range: '>=2.4.1 <3.0.0', hasData: true }
130 silly addNameRange versions [ 'lodash',
130 silly addNameRange   [ '0.1.0',
130 silly addNameRange     '0.2.0',
130 silly addNameRange     '0.2.1',
130 silly addNameRange     '0.2.2',
130 silly addNameRange     '0.3.0',
130 silly addNameRange     '0.3.1',
130 silly addNameRange     '0.3.2',
130 silly addNameRange     '0.4.0',
130 silly addNameRange     '0.4.1',
130 silly addNameRange     '0.4.2',
130 silly addNameRange     '0.5.0-rc.1',
130 silly addNameRange     '0.5.0',
130 silly addNameRange     '0.5.1',
130 silly addNameRange     '0.5.2',
130 silly addNameRange     '0.6.0',
130 silly addNameRange     '0.6.1',
130 silly addNameRange     '0.7.0',
130 silly addNameRange     '0.8.0',
130 silly addNameRange     '0.8.1',
130 silly addNameRange     '0.8.2',
130 silly addNameRange     '0.9.0',
130 silly addNameRange     '0.9.1',
130 silly addNameRange     '0.9.2',
130 silly addNameRange     '0.10.0',
130 silly addNameRange     '1.0.0-rc.1',
130 silly addNameRange     '1.0.0-rc.2',
130 silly addNameRange     '1.0.0-rc.3',
130 silly addNameRange     '1.0.0',
130 silly addNameRange     '1.0.1',
130 silly addNameRange     '1.1.0',
130 silly addNameRange     '1.1.1',
130 silly addNameRange     '1.2.0',
130 silly addNameRange     '1.2.1',
130 silly addNameRange     '1.3.0',
130 silly addNameRange     '1.3.1',
130 silly addNameRange     '2.0.0',
130 silly addNameRange     '2.1.0',
130 silly addNameRange     '2.2.0',
130 silly addNameRange     '2.2.1',
130 silly addNameRange     '2.3.0',
130 silly addNameRange     '2.4.0',
130 silly addNameRange     '2.4.1',
130 silly addNameRange     '3.0.0',
130 silly addNameRange     '3.0.1',
130 silly addNameRange     '3.1.0',
130 silly addNameRange     '3.2.0',
130 silly addNameRange     '3.3.0',
130 silly addNameRange     '3.3.1',
130 silly addNameRange     '3.4.0',
130 silly addNameRange     '3.5.0',
130 silly addNameRange     '3.6.0',
130 silly addNameRange     '1.0.2',
130 silly addNameRange     '3.7.0',
130 silly addNameRange     '2.4.2',
130 silly addNameRange     '3.8.0',
130 silly addNameRange     '3.9.0',
130 silly addNameRange     '3.9.1',
130 silly addNameRange     '3.9.2',
130 silly addNameRange     '3.9.3',
130 silly addNameRange     '3.10.0',
130 silly addNameRange     '3.10.1',
130 silly addNameRange     '4.0.0',
130 silly addNameRange     '4.0.1',
130 silly addNameRange     '4.1.0',
130 silly addNameRange     '4.2.0',
130 silly addNameRange     '4.2.1',
130 silly addNameRange     '4.3.0',
130 silly addNameRange     '4.4.0',
130 silly addNameRange     '4.5.0',
130 silly addNameRange     '4.5.1',
130 silly addNameRange     '4.6.0',
130 silly addNameRange     '4.6.1' ] ]
131 silly addNamed lodash@2.4.2
132 verbose addNamed "2.4.2" is a plain semver version for lodash
133 silly mapToRegistry name lodash
134 silly mapToRegistry using default registry
135 silly mapToRegistry registry https://registry.npmjs.org/
136 silly mapToRegistry uri https://registry.npmjs.org/lodash
137 verbose addRemoteTarball https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz not in flight; adding
138 verbose addRemoteTarball [ 'https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz',
138 verbose addRemoteTarball   'fadd834b9683073da179b3eae6d9c0d15053f73e' ]
139 info retry fetch attempt 1 at 12:24:41 PM
140 info attempt registry request try #1 at 12:24:41 PM
141 http fetch GET https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
142 http fetch 200 https://registry.npmjs.org/promise/-/promise-6.1.0.tgz
143 silly fetchAndShaCheck shasum 2ce729f6b94b45c26891ad0602c5c90e04c6eef6
144 verbose addTmpTarball C:\Users\Cherry\AppData\Local\Temp\npm-7180-42484863\registry.npmjs.org\promise\-\promise-6.1.0.tgz not in flight; adding
145 verbose addTmpTarball already have metadata; skipping unpack for promise@6.1.0
146 verbose correctMkdir C:\Users\Cherry\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
147 silly cache afterAdd promise@6.1.0
148 verbose afterAdd C:\Users\Cherry\AppData\Roaming\npm-cache\promise\6.1.0\package\package.json not in flight; writing
149 verbose correctMkdir C:\Users\Cherry\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
150 verbose afterAdd C:\Users\Cherry\AppData\Roaming\npm-cache\promise\6.1.0\package\package.json written
151 http fetch 200 https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
152 http fetch 200 https://registry.npmjs.org/imagesloaded/-/imagesloaded-3.2.0.tgz
153 warn retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\Cherry\AppData\Local\Temp\npm-7180-42484863\registry.npmjs.org\lodash\-\lodash-2.4.2.tgz.2207628695' -> 'C:\Users\Cherry\AppData\Local\Temp\npm-7180-42484863\registry.npmjs.org\lodash\-\lodash-2.4.2.tgz'
154 verbose stack TypeError: tarball.destroy is not a function
154 verbose stack     at WriteStreamAtomic.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-tarball.js:97:15)
154 verbose stack     at emitOne (events.js:95:20)
154 verbose stack     at WriteStreamAtomic.emit (events.js:182:7)
154 verbose stack     at WriteStreamAtomic.emit (C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:60:34)
154 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\index.js:89:19
154 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
155 verbose cwd F:\Office\Realm2-Code
156 error Windows_NT 10.0.10240
157 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
158 error node v5.8.0
159 error npm  v3.7.3
160 error tarball.destroy is not a function
161 error If you need help, you may report this error at:
161 error     <https://github.com/npm/npm/issues>
162 verbose exit [ 1, true ]
```

**Comment by FrankFang** [comment] 2016-03-14 03:15
+1 in Linux.

**Comment by bemeurer** [comment] 2016-03-21 21:39
+1 on Arch Linux

**Comment by tslater** [comment] 2016-04-09 04:48
I got this on windows 10 too. Any thoughts on where to look?

**Comment by tslater** [comment] 2016-04-09 04:50
I think I fixed it by calling `npm install tarball` first.

**Comment by ronaldoats** [comment] 2016-08-04 19:34
hey, solution is:
`sudo rm /tmp/* -R -f`
all problem with `npm -g install `

> Error: tarball.destory

**Comment by othiym23** [comment] 2016-08-19 21:57
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:57 UTC
Labels: bug, needs-repro

**Comment by sanraje** [comment] 2017-07-26 06:50
It worked for me as suggested by tslater 
npm install tarball
