### ISSUE TITLE
npm error ebusy

### ISSUE THREAD

**Issue by jain15506** [npm/npm#10596] opened 2015-11-29 07:35 UTC
getting npm error EBUSY while adding through npm the gulp dependency

**Comment by othiym23** [comment] 2015-12-04 23:14
Probably a reboot will fix this problem, but if it doesn't, can you update `npm-debug.log`, as well as telling us which versions of Node and npm you're using?

**Comment by othiym23** [comment] 2016-08-19 21:54
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:54 UTC
Labels: support, windows
