### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by geraldvillorente** [npm/npm#10259] opened 2015-11-04 15:46 UTC
Node newbie here.

```
gerald@von-viel:~/Repo/kalabox$ npm install . -g
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/home/gerald/.nvm/versions/node/v5.0.0/bin/node" "/home/gerald/.nvm/versions/node/v5.0.0/bin/npm" "install" "." "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path /home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gerald/Repo/kalabox/npm-debug.log
```

From npm-debug.log

```
29217 silly install printInstalled
29218 verbose stack Error: ENOENT: no such file or directory, chmod '/home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js'
29218 verbose stack     at Error (native)
29219 verbose cwd /home/gerald/Repo/kalabox
29220 error Linux 3.13.0-66-generic
29221 error argv "/home/gerald/.nvm/versions/node/v5.0.0/bin/node" "/home/gerald/.nvm/versions/node/v5.0.0/bin/npm" "install" "." "-g"
29222 error node v5.0.0
29223 error npm  v3.3.6
29224 error path /home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js
29225 error code ENOENT
29226 error errno -2
29227 error syscall chmod
29228 error enoent ENOENT: no such file or directory, chmod '/home/gerald/.nvm/versions/node/v5.0.0/lib/node_modules/kalabox/bin/kbox.js'
29228 error enoent This is most likely not a problem with npm itself
29228 error enoent and is related to npm not being able to find a file.
29229 verbose exit [ -2, true ]
````

**Comment by lencioni** [comment] 2015-11-04 16:48
Do you still see this problem if you upgrade npm@latest (currently 3.3.10) or npm@next (currently 3.3.12)? You should be able to do that by running `npm install -g npm@latest` or `npm install -g npm@next`.

**Comment by smartmouse** [comment] 2015-11-05 01:07
@geraldvillorente, are you using  nvm to manage the different node versions?  and you are doing npm install . -g , what are you trying to install globally?

**Comment by iarna** [comment] 2015-11-06 19:45
Closing this as a duplicate of #9633

**Closed by iarna** 2015-11-06 19:45 UTC
