### ISSUE TITLE
Checksum failed for c:\.....\registery.npmjs.org\wcf.js\-\wcf.js=0.0.6.tgz

### ISSUE THREAD

**Issue by canyon2015** [npm/npm#8437] opened 2015-06-02 16:50 UTC
I'm trying to install wcf.js and get following issue: I've tried all solutions at following link but none worked.
https://github.com/npm/npm/issues/2701

Please help me with this issue:

```
29 verbose etag https://registry.npmjs.org/wcf.js from cache
30 verbose get saving wcf.js to C:\Users\tdavoodian-\AppData\Roaming\npm-cache\registry.npmjs.org\wcf.js\.cache.json
31 silly addNameRange number 2 { name: 'wcf.js', range: '*', hasData: true }
32 silly addNameRange versions [ 'wcf.js', [ '0.0.1', '0.0.2', '0.0.4', '0.0.5', '0.0.6' ] ]
33 silly addNamed wcf.js@0.0.6
34 verbose addNamed "0.0.6" is a plain semver version for wcf.js
35 silly mapToRegistry name wcf.js
36 silly mapToRegistry using default registry
37 silly mapToRegistry registry https://registry.npmjs.org/
38 silly mapToRegistry uri https://registry.npmjs.org/wcf.js
39 verbose addRemoteTarball https://registry.npmjs.org/wcf.js/-/wcf.js-0.0.6.tgz not in flight; adding
40 verbose addRemoteTarball [ 'https://registry.npmjs.org/wcf.js/-/wcf.js-0.0.6.tgz',
40 verbose addRemoteTarball   '08236613cf50f2867212be83af19ff0758342586' ]
41 info retry fetch attempt 1 at 9:35:47 AM
42 info attempt registry request try #1 at 9:35:47 AM
43 http fetch GET https://registry.npmjs.org/wcf.js/-/wcf.js-0.0.6.tgz
44 http fetch 200 https://registry.npmjs.org/wcf.js/-/wcf.js-0.0.6.tgz
45 silly fetchAndShaCheck shasum 08236613cf50f2867212be83af19ff0758342586
46 verbose stack Error: shasum check failed for C:\Users\TDAVOO~2\AppData\Local\Temp\npm-17516-c86729db\registry.npmjs.org\wcf.js\-\wcf.js-0.0.6.tgz
46 verbose stack Expected: 08236613cf50f2867212be83af19ff0758342586
46 verbose stack Actual:   a7e53cec0f42eb7fe1cb7e55aeec5a6b12fe452a
46 verbose stack From:     https://registry.npmjs.org/wcf.js/-/wcf.js-0.0.6.tgz
46 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
46 verbose stack     at ReadStream.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
46 verbose stack     at ReadStream.emit (events.js:129:20)
46 verbose stack     at _stream_readable.js:908:16
46 verbose stack     at process._tickCallback (node.js:355:11)
47 verbose cwd C:\Windows\System32
48 error Windows_NT 6.1.7601
49 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "wcf.js"
50 error node v0.12.4
51 error npm  v2.10.1
52 error shasum check failed for C:\Users\TD~2\AppData\Local\Temp\npm-17516-c86729db\registry.npmjs.org\wcf.js\-\wcf.js-0.0.6.tgz
52 error Expected: 08236613cf50f2867212be83af19ff0758342586
52 error Actual:   a7e53cec0f42eb7fe1cb7e55aeec5a6b12fe452a
52 error From:     https://registry.npmjs.org/wcf.js/-/wcf.js-0.0.6.tgz
53 error If you need help, you may report this error at:
53 error     <https://github.com/npm/npm/issues>
54 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment] 2015-06-02 17:46
@canyon2015 Maybe try cleaning your cache?: `npm cache clean`

**Comment by canyon2015** [comment] 2015-06-02 18:01
Thanks but getting the same error.

**Comment by othiym23** [comment] 2015-06-02 18:14
@canyon2015 did you mean to close this issue? Aside from having crud in your cache, the second-most common cause of checksum failures is there being a proxy in between npm and the registry. Is your browser configured to use a proxy to connect to the web?

**Comment by canyon2015** [comment] 2015-06-02 18:42
I didn't mean to close. It was a mistake

**Comment by canyon2015** [comment] 2015-06-02 21:01
No, My browser doesn't use proxy.

**Comment by ericbarch** [comment] 2015-06-03 16:01
Also wanted to chime in that I'm seeing this with bower currently. Cleaning my cache before the install doesn't seem to help either.

```
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /tmp/npm-5-b8488a21/registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! Expected: 21adc7d80f02002af50dae97fd9dbf248755f566
npm ERR! Actual:   90a592379a2d104c91cc98bcefd5d37c678ac2d7
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by ThomWright** [comment] 2015-06-23 13:03
I'm getting a similar problem with my `flyd-cacheuntil` package. I just reinstalled node/npm and it still doesn't work.

**OS**: Ubuntu 12.04
**Node**: 0.12.5
**NPM**: 2.11.2

[Error output](https://gist.github.com/ThomWright/5c3fa302275d5f2d3e0a)

I'm assuming this isn't a problem with a proxy, all my other packages seem to work. I'll try with a different connection later and update if it works.

**Comment by busches** [comment] 2015-06-28 03:24
#8511, #8547, #8674, #8675, and #8727 all appear to be duplicates of the same issue.

**Comment by travellers** [comment] 2015-07-25 03:51
It's a network issue:
npm --registry http://registry.cnpmjs.org (npm config set registry )

**Comment by pixelrebel** [comment] 2015-08-10 16:48
@travellers Care to elaborate on the network issue?  What is happening?  Is it my network?

**Comment by zkat** [comment] 2016-12-09 00:56
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:56 UTC
Labels: support
