### ISSUE TITLE
npm5: Crash when publishing tarballs directly (formerly: Cannot read property 'algorithm' of undefined)

### ISSUE THREAD

**Issue by simonua** [npm/npm#16723] opened 2017-05-25 20:49 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am running into an error when publishing a packed package.

#### How can the CLI team reproduce the problem?
1. md npm5-test && cd npm5-test
1. npm5 init -y 
**I then edited the package name to contain our scope but am unsure whether that would have any bearing here.**
1. npm5 pack - I like to pack, so that I can inspect the tgz before I publish.
1. npm5 publish < scope >-npm5-test-1.0.0.tgz

### supporting information:

 - `npm5 -v` prints: 5.0.0-beta.64
 - `node -v` prints: v7.10.0
 - `npm5 config get registry` prints: https://connectionseducation.pkgs.visualstudio.com/_packaging/ConnectionsEducationNpm/npm/registry/
 - Windows, OS X/macOS, or Linux?: Windows 7 64-bit
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Gist [2017-05-25T20_45_04_549Z-debug.log](https://gist.github.com/simonua/17b6dd71a779484e007fe1cfc1b87f8f)

Linking to npm@5 beta tracking: #16510

**Comment by simonua** [comment] 2017-05-25 20:50
@zkat, I'm so sorry, link to 16510 is probably good enough but in light of npm5's tight timeline, I wanted to ping you separately.

**Comment by rmg** [comment] 2017-05-26 00:44
FYI, I reproduced this against registry.npmjs.org (macOS/npm@5.0.0-beta.64/node@v6.10.3) so it's not related to the use of a non-official registry, in case that helps narrow the field.

**Comment by simonua** [comment] 2017-05-26 00:50
@rmg, awesome! I meant to do that earlier, too, but I was half way out the door when I reported what I initially saw. Thanks for validating/reproducing!

**Comment by rmg** [comment] 2017-05-26 00:56
Actually, after reviewing the very short log, I **am** going to paste the most relevant section of it here to save @zkat the clicking just to see the stacktrace:
```
9 silly prefetch no integrity hash provided for file:rmg-npm-16723-1.0.0.tgz - fetching by manifest
10 silly prefetch file:rmg-npm-16723-1.0.0.tgz done in 10ms
11 verbose stack TypeError: Cannot read property 'algorithm' of undefined
11 verbose stack     at Object.parse (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/ssri/index.js:113:17)
11 verbose stack     at pickContentSri (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/cacache/lib/content/read.js:74:20)
11 verbose stack     at Function.readStream (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/cacache/lib/content/read.js:37:3)
11 verbose stack     at Function.getStreamDigest [as byDigest] (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/cacache/get.js:120:23)
11 verbose stack     at Function.x.get.stream.byDigest (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/cacache/locales/en.js:22:59)
11 verbose stack     at cache.add.then (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/lib/publish.js:103:30)
11 verbose stack     at tryCatcher (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Promise._fulfill (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:638:18)
11 verbose stack     at Promise._resolveCallback (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:432:57)
11 verbose stack     at Promise._settlePromiseFromHandler (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:524:17)
11 verbose stack     at Promise._settlePromise (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/Users/ryan/.nvs/node/6.10.3/x64/lib/node_modules/npm5/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by rmg** [comment] 2017-05-26 16:16
Sadly, `npm@5.0.0` did not magically fix this.

**Comment by simonua** [comment] 2017-05-26 16:17
Haha, if only. =P

**Comment by zkat** [comment] 2017-05-26 16:28
Yeah. I'll be tackling this one soon -- it sounds like publishing works fine if it's off a regular `npm publish`?

**Comment by simonua** [comment] 2017-05-26 16:33
@zkat, you are correct. If I simply follow these adjusted steps, the publish occurs, and I can see the package in our 3rd party registry. And as @rmg alluded to and you know anyway, it's irrelevant that it's a 3rd party. That's just how my setup is. =P

1. md npm5-test && cd npm5-test
1. npm5 init -y - I then edited the package name to contain our scope
1. npm5 publish

**Comment by zkat** [comment] 2017-05-26 16:37
awesome. I'm just making sure you have an escape hatch. People publishing directly from tarballs is relatively rare -- though it's a very good idea to do what you're doing (and I often recommend it), since we didn't rewrite the pack code for this release, and that code has known awful races. I have a general idea of why/where this is happening. I'll let you know once I poke at it :)

**Comment by garoyeri** [comment] 2017-05-31 13:17
I just upgraded to npm@5.0.0 and I see the same issue when publishing tarballs directly.  What I am doing is mirroring my cache to an internally hosted NPM repository (ProGet).  We are mirroring packages that are in use so that our internal build servers don't need Internet access.

I clear my cache, then install a set of packages, then run:
find . -name package.tgz | xargs -n1 npm publish --registry=https://myurl/npm/npm

And this worked with the previous version just fine.

**Comment by blyork** [comment] 2017-05-31 14:41
I am having the same issue publishing a tarball:
...
```
2 info using npm@5.0.0
3 info using node@v7.9.0
```
...
```
10 verbose stack TypeError: Cannot read property 'algorithm' of undefined
10 verbose stack     at Object.parse (/usr/lib/node_modules/npm/node_modules/ssri/index.js:113:17)
10 verbose stack     at pickContentSri (/usr/lib/node_modules/npm/node_modules/cacache/lib/content/read.js:74:20)
10 verbose stack     at Function.readStream (/usr/lib/node_modules/npm/node_modules/cacache/lib/content/read.js:37:3)
10 verbose stack     at Function.getStreamDigest [as byDigest] (/usr/lib/node_modules/npm/node_modules/cacache/get.js:120:23)
10 verbose stack     at Function.x.get.stream.byDigest (/usr/lib/node_modules/npm/node_modules/cacache/locales/en.js:22:59)
10 verbose stack     at cache.add.then (/usr/lib/node_modules/npm/lib/publish.js:111:30)
10 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
10 verbose stack     at Promise._resolveCallback (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
10 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by simonua** [comment] 2017-06-06 16:15
@zkat, I started to look under the hood a bit here, but I don't quite know whether I'm on the right track. I used `5.0.3-canary.4`. Hopefully, this helps things a little nevertheless:

Based on the stack trace in my linked gist above, I started tracking from this line on:

`11 verbose stack     at cache.add.then (C:\Program Files\nodejs\node_modules\npm5\lib\publish.js:103:30)`

If I log `arg` out of what gets passed to `cache.add`, I see the name of the tgz file I want to publish (good):

`return cache.add(arg).then((info) => {`

Tracing the addition gets me to `function add (args, where)` in _cache.js_. The first parameter is the expected filename, but `where` is `undefined` since never passed in. That `undefined` then propagates to 
`pacoteOpts({where})` which returns an object passed as the second parameter into `pacote.prefetch` which has signature `prefetch (spec, opts)`. I don't see the `undefined` here having any impact as `where` in the returned object has `undefined` assigned, and that's as far as that goes, I think (red herring). 
However, `opts` never appears to add an `integrity` property (see log of the object below), so `undefined` then propagates all the way to where it bombs in _ssri_:

```
11 verbose stack TypeError: Cannot read property 'algorithm' of undefined
11 verbose stack     at Object.parse (C:\Program Files\nodejs\node_modules\npm5\node_modules\ssri\index.js:113:17)
11 verbose stack     at pickContentSri (C:\Program Files\nodejs\node_modules\npm5\node_modules\cacache\lib\content\read.js:74:20)
11 verbose stack     at Function.readStream (C:\Program Files\nodejs\node_modules\npm5\node_modules\cacache\lib\content\read.js:37:3)
11 verbose stack     at Function.getStreamDigest [as byDigest] (C:\Program Files\nodejs\node_modules\npm5\node_modules\cacache\get.js:120:23)
11 verbose stack     at Function.x.get.stream.byDigest (C:\Program Files\nodejs\node_modules\npm5\node_modules\cacache\locales\en.js:22:59)
11 verbose stack     at cache.add.then (C:\Program Files\nodejs\node_modules\npm5\lib\publish.js:103:30)
```

Logging `opts` from `prefetch (spec, opts)` gives me this (`auth` was removed but the rest is accurate):
```
{ cache: 'C:\\Users\\skurtz\\AppData\\Roaming\\npm-cache\\_cacache',
  ca: null,
  cert: null,
  defaultTag: 'latest',
  dirPacker: [Function: packGitDep],
  hashAlgorithm: 'sha1',
  key: null,
  localAddress: undefined,
  log:
   EventEmitter {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     useColor: [Function],
     enableColor: [Function],
     disableColor: [Function],
     level: 'notice',
     gauge:
      { _status: [Object],
        _paused: false,
        _disabled: false,
        _showing: true,
        _onScreen: true,
        _needsRedraw: true,
        _hideCursor: true,
        _fixedFramerate: true,
        _lastUpdateAt: null,
        _updateInterval: 50,
        _themes: [Object],
        _theme: [Object],
        _writeTo: [Object],
        _tty: [Object],
        _gauge: [Object],
        '_$$doRedraw': [Function],
        '_$$handleSizeChange': [Function],
        _cleanupOnExit: true,
        _removeOnExit: [Function: remove],
        redrawTracker: [Object] },
     tracker:
      EventEmitter {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        id: 1,
        name: undefined,
        parentGroup: null,
        trackers: [],
        completion: {},
        weight: {},
        totalWeight: 0,
        finished: false,
        bubbleChange: [Function] },
     progressEnabled: true,
     enableUnicode: [Function],
     disableUnicode: [Function],
     setGaugeThemeset: [Function],
     setGaugeTemplate: [Function],
     enableProgress: [Function],
     disableProgress: [Function],
     newGroup: [Function],
     newItem: [Function],
     newStream: [Function],
     clearProgress: [Function],
     showProgress: [Function: bound ],
     pause: [Function],
     resume: [Function],
     _buffer: [],
     record:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     maxRecordSize: 10000,
     log: [Function: bound ],
     emitLog: [Function],
     _format: [Function],
     write: [Function],
     addLevel: [Function],
     prefixStyle: { fg: 'magenta' },
     headingStyle: { fg: 'white', bg: 'black' },
     style:
      { silly: [Object],
        verbose: [Object],
        info: [Object],
        timing: [Object],
        http: [Object],
        notice: [Object],
        warn: [Object],
        error: [Object],
        silent: undefined },
     levels:
      { silly: -Infinity,
        verbose: 1000,
        info: 2000,
        timing: 2500,
        http: 3000,
        notice: 3500,
        warn: 4000,
        error: 5000,
        silent: Infinity },
     disp:
      { silly: 'sill',
        verbose: 'verb',
        info: 'info',
        timing: 'timing',
        http: 'http',
        notice: 'notice',
        warn: 'WARN',
        error: 'ERR!',
        silent: 'silent' },
     silly: [Function: bound ],
     verbose: [Function: bound ],
     info: [Function: bound ],
     timing: [Function: bound ],
     http: [Function: bound ],
     notice: [Function: bound ],
     warn: [Function: bound ],
     error: [Function: bound ],
     silent: [Function: bound ],
     _paused: false,
     heading: 'npm' },
  maxAge: 10,
  maxSockets: 50,
  npmSession: 'be12944dc72f345e',
  offline: false,
  preferOffline: false,
  preferOnline: false,
  projectScope: '@connections-education',
  proxy: null,
  refer: 'publish connections-education-constants-4.10.0.tgz',
  registry: 'https://connectionseducation.pkgs.visualstudio.com/_packaging/ConnectionsEducationNpm/npm/registry/',
  retry: { retries: 2, factor: 10, minTimeout: 10000, maxTimeout: 60000 },
  scope: '',
  strictSSL: true,
  userAgent: 'npm/5.0.3-canary.4 node/v8.0.0 win32 x64',
  auth: [REMOVED],   
  where: undefined }
```

**Comment by simonua** [comment] 2017-06-06 16:36
`prefetchByManifest` ends up executing in _prefetch.js_. but both `integrity` and `manifest` are `undefined ` on the assignment in the return:

```
    return {
      manifest,
      spec,
      integrity: integrity || (manifest && manifest._integrity),
      byDigest: false
    }
```

**Comment by zkat** [comment] 2017-06-06 18:38
@simonua I think what's going on is that some things aren't picking up or emitting `integrity` events, so prefetch is never picking it up. I've fixed a couple of those cases before.

**Comment by simonua** [comment] 2017-06-06 18:45
@zkat, sounds ugly. The "escape hatch" works, and I'm mostly comfortable that way. Could you refresh my memory as to precisely what lifecycle event I want to hook into if I want to run a script just prior to publishing and not on npm install, please? We call our own `gulp publish-package` to generate the package output prior to packing/publishing it, and having that in would solidify this process greatly.

**Comment by zkat** [comment] 2017-06-06 18:47
@simonua For the use case you're describing, I'd recommend you use the new `prepack` lifecycle event, which will run before `pack` and before `publish`, but no on `npm install`. `prepublishOnly` will _only_ run on `npm publish`, and not on `npm pack`.

**Comment by zkat** [comment] 2017-06-06 18:47
(note that `prepack` and `postpack` are both new in `npm@5`)

**Comment by simonua** [comment] 2017-06-06 18:48
Ok, perfect! That makes it safe for both cases if/when pack gets fixed. I was worried about missing one. Thank you, @zkat!

**Comment by mscdex** [comment] 2017-06-12 09:02
FWIW I just ran into this with npm v5 (5.0.3 too) as I always publish from github tarballs (so I know more exactly what will be published).

Downgrading to npm v4 (4.6.1) allows me to publish from github tarballs again.

**Comment by MichalCz** [comment] 2017-06-15 15:09
+1 in 5.0.3 too - cannot publish anything directly from github tarballs. 3.x on another machine works well.

**Comment by BorisMoore** [comment] 2017-06-18 04:02
+1 me too in 5.03 - same error log. Can't publish from tarball directly.

**Comment by sijeesh-02** [comment] 2017-06-22 16:57
I tried publishing tarball to a **private repo** with npm 5.0.3 it fails with same error

**Comment by chgibb** [comment] 2017-06-23 02:58
I seem a little late to the party here. Cannot ```npm publish``` a tarball created using ```npm pack``` to the public registry with npm ```5.0.0```.

**Comment by jwarkentin** [comment] 2017-06-23 03:13
Yeah, just ran into this myself. Also on 5.0.3. Not sure what it's gonna take to get a fix but this seems like a pretty critical issue.

**Comment by kemmis** [comment] 2017-07-12 20:55
bump bump ^^

I too am running into this issue when trying to publish using 5.0.3.

**Comment by felipeconti** [comment] 2017-07-13 18:18
+1 in 5.0.3 too, cannot publish anything directly from github tarballs

**Comment by kcowgill** [comment] 2017-07-28 20:41
+1 still in 5.3.0. Trying to migrate from one internal repo to another - I've got a directory full of tarballs but am seeing `Cannot read property 'algorithm' of undefined`

**Comment by zkat** [comment] 2017-07-28 22:04
Quick update: I haven't touched this one yet, and it involves a bit of painful refactor on the pacote side of things that I need to sit and brain through. Hang in there, y'all. 👍

**Comment by zkat** [comment] 2017-07-28 22:05
in the meantime: I recommend considering doing an `npm pack` and doing an inspection on that tarball, and then maybe assuming `npm publish` will run the same process, if you're willing to do that sort of thing. That might mitigate this for some of y'all.

**Comment by simonua** [comment] 2017-07-31 17:00
If it helps, here's what I ended up doing: After Kat confirmed the proper lifecycle events in [this earlier post](https://github.com/npm/npm/issues/16723#issuecomment-306580944), I implemented `prepack` tasks in all scenarios I needed, and I have those tasks intentionally bail on publish for cases such as failing tests, etc. I went from reluctantly typing `npm publish` and pressing _Enter_ with an outstretched arm while turning away from the perceived bomb to fully embracing it now and having issued corresponding guidance to our teams. I now prefer `npm publish`. I understand this may not be everyone's scenario, policy, or preference, so take this as just another developer's 2 cents. Good luck!

**Comment by kcowgill** [comment] 2017-07-31 17:37
I'm getting by with (some form of) the workaround. I wrote a little shell script to iterate through all the .tgz's, unpack them, replace the package.json's `publishConfig: { registry }` if it exists, and upload it to my new artifact repository. (Sadly specifying `--registry` on the command line didn't override what was hardcoded into some of these packages' package.json.

**Comment by haraldF** [comment] 2017-08-01 12:36
Another workaround is to locally install npm4 via `npm install npm@4` and then call `node_modules/.bin/npm publish` instead of `npm publish`

**Comment by chadly** [comment] 2017-08-01 12:57
The workaround I have been using is just not upgrading to npm 5.

**Comment by andvgal** [comment] 2017-09-04 22:21
The problem still exists with npm 5.4.0.

**Comment by yvele** [comment] 2017-09-25 13:00
Can we rename this issue to something more explicit like:

> Crash when publishing tarballs directly

BYTW is this issue supposed to be fixed soon..? This keep me from moving to npm 5 on some scenarios 😞

**Comment by simonua** [comment] 2017-09-25 14:40
@yvele, good call! I should have done that a long time ago. Thank you.

**Comment by zkat** [comment] 2017-10-05 21:25
https://github.com/npm/npm/pull/18726 should fix this. Finally got around to it. Lol <3

**Comment by simonua** [comment] 2017-10-05 22:19
Awesome, @zkat! If it's in canary, I can take a look tomorrow morning.

**Comment by simonua** [comment] 2017-10-06 11:27
@zkat, let me know when it's good to test with a new canary, please. 5.4.2-canary.7 does not yet appear to have it. Thank you!!

![npmc 5 4 2-canary 7 publish result](https://user-images.githubusercontent.com/8005145/31276015-c1967a82-aa67-11e7-9336-39f44dc45393.png)

**Comment by berardo** [comment] 2017-10-10 08:13
![image](https://user-images.githubusercontent.com/2008164/31375575-c0606aea-aded-11e7-88ba-6b12edcb03a4.png)
It's also reproducible on my end. Looks like #18726 isn't merged yet.
Any eta?
Thanks

**Comment by zkat** [comment] 2017-10-14 05:47
This should be fixed in the canary. It'll go out next time we do an npm release. See https://github.com/npm/npm/commit/34c762d3dd19bddbfce5c0441eaeb1cd4d442e86, which has landed in `release-next`.

**Comment by simonua** [comment] 2017-10-16 13:16
Hi @zkat, I get a [different error](https://gist.github.com/simonua/f29946ba28c5f21fc36f24d20cc6595f) now.

STRs:

- `md npm5-test2 && cd npm5-test2`
- `npmc init -y`
- Edit _package.json_ to add scope for our org.
- `npmc pack`
- `npmc publish <package-name>.tgz`

For additional detail: I don't suppose this matters, but this goes into our own registry hosted as part of Microsoft's VSTS.

**Comment by okv** [comment] 2017-11-02 09:17
Hi there.
Any plans about releasing it?
Really blocks moving to npm 5.

**Comment by kmashint** [comment] 2017-11-15 01:08
The ( npm pack ; npm publish *.tgz ) is broken for me too in npm 5.0.4 that we use for compatibility with dependencies that don't like 5.1+.  Hoping for a fix soon... even to a later 5.x version ...

**Comment by zkat** [comment] 2017-11-15 07:11
(just dropping the note that I've got the fix for this now, and I'm just getting some library releases done. Look forward to it soon!)

**Comment by zkat** [comment] 2017-11-15 07:57
I believe https://github.com/npm/npm/pull/19163 includes a fix for this. I've published it on the npm canary. Would any of you be willing to do `npx npmc i` in your repos and tell me if you can still reproduce it with the latest `npmc@5.5.1-canary.6`?

**Comment by okv** [comment] 2017-11-15 09:09
@zkat I've tried to publish tarball using `npmc@5.5.1-canary.6`, it's completed without errors but produces to the output:
```
npm notice CANARY npmc is experimental software. If you find an issue, please file it in the main npm repository, and call out that you were using npmc.
+ undefined
```

**Comment by zkat** [comment] 2017-11-15 09:28
@okv but the published version is correct and everything? This output issue is minor enough in that case, but I'll take a look.

**Comment by okv** [comment] 2017-11-15 09:32
@zkat published version seems to be ok :+1:

**Comment by zkat** [comment] 2017-11-15 09:35
@okv and I just pushed a quick fix for the `+ undefined` thing (not published on the canary). Things should be all set! Thanks for checking!

**Comment by okv** [comment] 2017-11-15 09:43
@zkat great, thanks for fixing it :smiley: 
Do you know when canary can be released?

**Comment by zkat** [comment] 2017-11-15 10:01
You can safely ignore that output error! It was just a final output issue. I don't know when exactly the next Canary will be out but there's an actual release coming pretty soon.

**Comment by simonua** [comment] 2017-11-20 20:42
@zkat, I'm sorry it's taken me a while to check this out. I have success with **npmc@5.5.1-canary.8**.

![image](https://user-images.githubusercontent.com/8005145/33040485-3a5c2b46-ce09-11e7-809d-f15d50fbf781.png)

I was subsequently able to pull that package into another project as well and verify its contents, so I think **this all looks good**. I'll defer to you when you want to close this out.

**Comment by zkat** [comment] 2017-11-20 22:49
@simonua thanks, Simon! Sorry this took a while to fix. It required a bit of a multi-layer minor rearchitect but it turned out to have been easier than I expected it to be.

This hasn't been merged directly into `release-next` yet, so I'm gonna hold off on closing it until that's done. Cheers!

**Closed** 2017-11-28 03:39 UTC
Labels: bug, npm5

**Comment by EightArmCode** [comment] 2018-04-13 13:17
Has this been published? I'm having an error publishing from a tarball.

node -v 8.9.4
npm -v 5.6.0

**Comment by kmashint** [comment] 2018-04-13 14:32
node 8.9.4 and more particularly npm 5.6.0 did solve the problem of publishing from a tgz for me.  Just double check with npm --version that it was updated.  Sometimes even with a new node install you need to `npm install npm@5.6.0` or similar.

**Comment by simonua** [comment] 2018-04-13 14:38
[node 8.9.4 installed npm 5.6.0](https://nodejs.org/en/blog/release/v8.9.4/), so I would suspect you do indeed have the right npm version where this was fixed. Having said that, tangentially, it's a good idea to have most recent versions for [npm](https://github.com/npm/npm/releases) and [node](https://nodejs.org/en/) installed, if you can.

@EightArmCode, do you have an error log you could update as part of a [gist](gist.github.com) to help assess the root cause?
