### ISSUE TITLE
Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by TomiCat** [npm/npm#19374] opened 2017-12-12 02:59 UTC
E:\vue2>vue init webpack he

? Project name he
? Project description A Vue.js project
? Author
? Vue build runtime
? Install vue-router? Yes
? Use ESLint to lint your code? No
? Set up unit tests No
? Setup e2e tests with Nightwatch? No
? Should we run `npm install` for you after the project has been created? (recommended) npm

   vue-cli · Generated "he".

# Installing project dependencies ...
# ========================

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by juan-carlos-correa** [comment] 2017-12-13 16:36
+1 

I reinstall vue-cli but i get the same issue

Windows 10
vue 2.9.2

Error:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by wikett** [comment] 2017-12-13 20:18
+1

Same problem

Windows 10
npm 5.6.0
vue 2.9.2

Any idea?

**Comment by SnekInDisguise** [comment] 2017-12-13 22:58
Same problem here.

Windows 10
node 8.9.3
npm 5.5.1
vue 2.9.2

What is more strange is that I set a node env in my android smartphone (with Termux) with Vue and it actually worked with out any errors in the installing process nor the 'vue init webpack ...' command. It got to run without any problems.

So, it might have to do something with Windows.

**Comment by wikett** [comment] 2017-12-13 23:04
I have solved the problem if you skip the last step.
Instead of choose 

> Should we run npm install for you after the project has been created? (recommended)

,choose the last option, and after that you can do
`cd my-project

npm install

npm run dev`

That worked for me.

Regards

**Comment by TomiCat** [comment] 2017-12-14 00:03
I didn't do anything. When i execute npm install and npm run dev,It worked

**Comment by lambdakris** [comment] 2017-12-14 03:32
Yes, I think the issue is if you tell vue-cli to restore packages after scaffolding AND you are providing a name to create a directory instead of using the existing directory. This issue really belongs in the vue-cli repo. In fact, there is already an issue about this there: https://github.com/vuejs/vue-cli/issues/681.

**Comment by gu-fan** [comment] 2017-12-14 04:34
same here...

**Comment by LinusBorg** [comment] 2017-12-14 07:11
Hey guys,

I'm maintaining the template with which this error happens. It is more than likely that the problem is on our side, so I suggest to to close this issue, and we will come back if do find indication to the opposite. 

We'll try and solve this on our side. Thanks!

**Closed as completed** 2017-12-14 10:08 UTC
Labels: support
