### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wfgenius** [npm/npm#8727] opened 2015-06-27 13:40 UTC
Get errors during npm install. Please help.

```
C:\Fan\GitHub\play\ng-demos\modular>npm install
npm WARN optional dep failed, continuing fsevents@0.3.6
-


> phantomjs@1.9.17 install C:\Fan\GitHub\play\ng-demos\modular\node_modules\phan
tomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\Fan\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...
| [====================================----] 90% 0.0s/
Received 7292K total.
Extracting zip contents
Removing C:\Fan\GitHub\play\ng-demos\modular\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Fan\AppData\Local\Temp\phantomjs\phantomjs-1.9
.8-windows.zip-extract-1435411118735\phantomjs-1.9.8-windows -> C:\Fan\GitHub\pl
ay\ng-demos\modular\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Fan\GitHub\play\ng-demos\modular\node_mod
ules\phantomjs\lib\phantom\phantomjs.exe
-


> jpegtran-bin@3.0.2 postinstall C:\Fan\GitHub\play\ng-demos\modular\node_module
s\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_module
s\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully

> gifsicle@3.0.1 postinstall C:\Fan\GitHub\play\ng-demos\modular\node_modules\gu
lp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gi
fsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> pngquant-bin@3.0.0 postinstall C:\Fan\GitHub\play\ng-demos\modular\node_module
s\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_module
s\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully
\


> optipng-bin@3.0.2 postinstall C:\Fan\GitHub\play\ng-demos\modular\node_modules
\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\
optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully
\


> ws@0.4.32 install C:\Fan\GitHub\play\ng-demos\modular\node_modules\karma\node_
modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Fan\GitHub\play\ng-demos\modular\node_modules\karma\node_modules\socket.io\no
de_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (
node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for C:\Users\Fan\AppData\Local\Temp\npm-13712-28982
742\registry.npmjs.org\node-notifier\-\node-notifier-3.4.1.tgz
npm ERR! Expected: ec0ba696bd6097aaf7c6c3e58b23c849f334bda1
npm ERR! Actual:   80a2486d7f6c3488be2cd2ec3d4774f1fc0d8c40
npm ERR! From:     https://registry.npmjs.org/node-notifier/-/node-notifier-3.4.
1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Fan\GitHub\play\ng-demos\modular\npm-debug.log

```

**Comment by zkat** [comment] 2016-12-09 00:55
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:55 UTC
Labels: shasum, support, windows
