### ISSUE TITLE
Error: ELOOP when installing via git+https://

### ISSUE THREAD

**Issue by 75lb** [npm/npm#3888] opened 2013-09-12 12:53 UTC
i am using **npm v1.3.8, node v0.10.18**

running this command (copied from the man page for `npm install`):

    $ npm install git+https://isaacs@github.com/isaacs/npm.git

raises this error: 

    npm ERR! Error: ELOOP, readdir '/Users/Lloyd/.npm/_git-remotes/https-isaacs-github-com-isaacs-npm-git-efd08813/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template'
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>

    npm ERR! System Darwin 12.4.1
    npm ERR! command "/usr/local/Cellar/node/0.10.18/bin/node" "/usr/local/bin/npm" "install" "git+https://isaacs@github.com/isaacs/npm.git"
    npm ERR! cwd /Users/Lloyd/Documents/tmp
    npm ERR! node -v v0.10.18
    npm ERR! npm -v 1.3.8
    npm ERR! path /Users/Lloyd/.npm/_git-remotes/https-isaacs-github-com-isaacs-npm-git-efd08813/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template/git_template
    npm ERR! code ELOOP
    npm ERR! errno 51
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /Users/Lloyd/Documents/tmp/npm-debug.log
    npm ERR! not ok code 0

**Comment by smikes** [comment] 2015-01-06 13:34
That's a really cool error!

But it seems to have been fixed in recent versions of `npm`.  I am unable to reproduce it with OSX Yosemite, node 0.10.35, npm 2.1.17

Is this issue now resolved?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment] 2015-01-15 17:33
Closing as abandoned.

**Closed by othiym23** 2015-01-15 17:33 UTC
Labels: bug
