### ISSUE TITLE
shasum error installing  package

### ISSUE THREAD

**Issue by jcollado** [npm/npm#11218] opened 2016-01-20 11:33 UTC
Lately I'm having problems trying to install packages that I published myself. The specific error that I get is that the shasum check fails similar to other errors already reported here like #1751, #2701, #7991, #9559. I believe that the problem cannot be reproduced consitently and, in fact, my workaround until now has been to publish a new release of the package to skip the one with the shasum problems. However, I've just had the same problem in two consecutive releases of the same package, so I thought it was worth reporting the problem.

As you'll see in the `npm-debug.log` content below I'm using node 5.4.0, npm 3.5.3 (I upgraded from the version included in node by default) and the package name is `promisify-function`. Anyway, note that the package was published using node 5.4.1 and npm 3.3.12 in a [travis job](https://travis-ci.org/jcollado/promisify-function/jobs/103570879) as part of the `semantic-release` npm script that includes a call to `npm publish`.

I've tried to follow the advice found in other issues. In particular `npm cache clean`, but doesn't fix the problem for me. Another check I've done is trying to get the package `.tgz` and check the shasum in the command line with:

``` bash
wget -q -O - https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz | shasum
```

Weirdly enough for `1.2.0` I get what `npm install` says is the expected value rather than the actual value. However, if I try with `1.1.3`, what I get is the actual value according to `npm install` instead of the expected one.

If you need further information, please let me know. Thanks.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/javi/.nvm/versions/node/v5.4.0/bin/node',
1 verbose cli   '/home/javi/.nvm/versions/node/v5.4.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--verbose',
1 verbose cli   'promisify-function@1.2.0' ]
2 info using npm@3.5.3
3 info using node@v5.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData promisify-function@1.2.0
8 silly fetchNamedPackageData promisify-function
9 silly mapToRegistry name promisify-function
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/promisify-function
13 verbose get https://registry.npmjs.org/promisify-function not expired, no request
14 silly install normalizeTree
15 silly loadCurrentTree Finishing
16 silly loadIdealTree Starting
17 silly install loadIdealTree
18 silly cloneCurrentTree Starting
19 silly install cloneCurrentTreeToIdealTree
20 silly cloneCurrentTree Finishing
21 silly loadShrinkwrap Starting
22 silly install loadShrinkwrap
23 silly loadShrinkwrap Finishing
24 silly loadAllDepsIntoIdealTree Starting
25 silly install loadAllDepsIntoIdealTree
26 silly resolveWithNewModule promisify-function@1.2.0 checking installable status
27 silly cache add args [ 'promisify-function@1.2.0', null ]
28 verbose cache add spec promisify-function@1.2.0
29 silly cache add parsed spec Result {
29 silly cache add   raw: 'promisify-function@1.2.0',
29 silly cache add   scope: null,
29 silly cache add   name: 'promisify-function',
29 silly cache add   rawSpec: '1.2.0',
29 silly cache add   spec: '1.2.0',
29 silly cache add   type: 'version' }
30 silly addNamed promisify-function@1.2.0
31 verbose addNamed "1.2.0" is a plain semver version for promisify-function
32 silly mapToRegistry name promisify-function
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/promisify-function
36 verbose addNameVersion registry:https://registry.npmjs.org/promisify-function not in flight; fetching
37 verbose get https://registry.npmjs.org/promisify-function not expired, no request
38 silly mapToRegistry name promisify-function
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry https://registry.npmjs.org/
41 silly mapToRegistry uri https://registry.npmjs.org/promisify-function
42 verbose addRemoteTarball https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz not in flight; adding
43 verbose addRemoteTarball [ 'https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz',
43 verbose addRemoteTarball   'c7bbf79b9cce6b8b2ba17fa9a44bab25a5b776e3' ]
44 info retry fetch attempt 1 at 12:05:06 PM
45 info attempt registry request try #1 at 12:05:06 PM
46 http fetch GET https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz
47 verbose request using bearer token for auth
48 verbose request id 0424206aa98eb395
49 http fetch 200 https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz
50 silly fetchAndShaCheck shasum c7bbf79b9cce6b8b2ba17fa9a44bab25a5b776e3
51 silly rollbackFailedOptional Starting
52 silly rollbackFailedOptional Finishing
53 silly runTopLevelLifecycles Starting
54 silly runTopLevelLifecycles Finishing
55 silly install printInstalled
56 verbose stack Error: shasum check failed for /tmp/npm-5831-dcd935bc/registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz
56 verbose stack Expected: c7bbf79b9cce6b8b2ba17fa9a44bab25a5b776e3
56 verbose stack Actual:   6e42d108b81f4cd1fbd99af7dba369addb9a90f0
56 verbose stack From:     https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz
56 verbose stack     at /home/javi/.nvm/versions/node/v5.4.0/lib/node_modules/npm/node_modules/sha/index.js:25:8
56 verbose stack     at ReadStream.<anonymous> (/home/javi/.nvm/versions/node/v5.4.0/lib/node_modules/npm/node_modules/sha/index.js:72:7)
56 verbose stack     at emitNone (events.js:72:20)
56 verbose stack     at ReadStream.emit (events.js:166:7)
56 verbose stack     at endReadableNT (_stream_readable.js:905:12)
56 verbose stack     at nextTickCallbackWith2Args (node.js:478:9)
56 verbose stack     at process._tickCallback (node.js:392:17)
57 verbose cwd /home/javi/code/git/personal/github/multitest
58 error Linux 4.2.0-25-generic
59 error argv "/home/javi/.nvm/versions/node/v5.4.0/bin/node" "/home/javi/.nvm/versions/node/v5.4.0/bin/npm" "install" "--verbose" "promisify-function@1.2.0"
60 error node v5.4.0
61 error npm  v3.5.3
62 error shasum check failed for /tmp/npm-5831-dcd935bc/registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz
62 error Expected: c7bbf79b9cce6b8b2ba17fa9a44bab25a5b776e3
62 error Actual:   6e42d108b81f4cd1fbd99af7dba369addb9a90f0
62 error From:     https://registry.npmjs.org/promisify-function/-/promisify-function-1.2.0.tgz
63 error If you need help, you may report this error at:
63 error     <https://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]
```

**Comment by theherk** [comment] 2016-01-26 19:55
I am experiencing a similar issue, pulling from Artifactory. The sha1 matches what it should be, but the expected value as reported by npm is something totally different.

**Comment by theherk** [comment] 2016-01-26 22:17
I cannot sort out from where the expected sum is coming. I have checked the tmp packages and it is correct with what is in the registry. Nevertheless, the problem in my case was renaming the package. It had a name that also existed in the main npmjs.org registry. Maybe we were somehow getting sums for the package with a matching name even though it was coming from our private repository.

I am wondering how the expected sum is calculated.

**Comment by jcollado** [comment] 2016-01-28 13:50
According to travisci/travisci#5423 there's some kind of race condition when running test cases for multiple node versions and then deploying on multiple jobs. The suggested fix for this is to use conditional deployment as in:

```yaml
deploy:
  on:
    node: <version>
```

**Comment by jansselt** [comment] 2016-05-05 16:37
We are experiencing the same issue using artifactory.  The sha1 is as expected and what is stored in artifactory.  It seems like npm is pulling the expected sha1 from npmjs.org despite that we are set up to not use it.

**Comment by rmg** [comment] 2016-08-31 16:59
@jansselt @theherk did you happen to publish a package of the same version to artifactory _before_ it was published to npmjs.org? I've seen a problem where it uses the metadata from npmjs.org (eg. the shasum) but the tarball from its local storage.

**Comment by theherk** [comment] 2016-08-31 17:04
@rmg I don't believe so, but that is possible. It has been a little while, so I cannot be certain.

**Comment by Suzal3579** [comment] 2016-09-18 08:29
I'm having the same problem. Did you fix it? If yes, how?

**Comment by zkat** [comment] 2016-12-09 00:48
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:48 UTC
