### ISSUE TITLE
Assets Problem

### ISSUE THREAD

**Issue by hosein-xz** [npm/npm#15883] opened 2017-02-27 11:16 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by hosein-xz** [comment] 2017-02-27 11:20
when I use -npm run dev- these errors happens:
[npm-debug.log.zip](https://github.com/npm/npm/files/803440/npm-debug.log.zip)
how can i fix it?

**Comment by KenanY** [comment] 2017-02-27 12:21
@hosein-xz In the future, do note that you can upload text files like the debug log file to <https://gist.github.com/> instead of `zip`ping them up.

From the error message, it seems like one of your scripts is trying to run a `"watch-poll"` script, but you do not have one defined in your `package.json`. See <https://docs.npmjs.com/misc/scripts> for documentation on writing your own scripts.

I'm gonna close this one since this is `npm` working as intended.

**Closed by KenanY** 2017-02-27 12:21 UTC
