### ISSUE TITLE
`index.js` file being removed

### ISSUE THREAD

**Issue by whitneyit** [npm/npm#9272] opened 2015-08-14 01:07 UTC
Running `npm publish` is removing the `index.js` file. This is occuring with the following package `@whitneyit/log` and `@whitneyit/clean`.

Republishing the package has fixed it for `log@1.1.1` but not for `clean@1.0.3`.

https://github.com/whitneyit/log
https://github.com/whitneyit/clean

It also seems to be including `.npmignore` even though that file is in my `.npmignore`.

**Update**
Just republished `clean` a second time and it worked then as `clean@1.0.3`

I've unpublished the offending packages due to my builds breaking. Not sure if that was a bad thing to do :confused:

**Comment by othiym23** [comment] 2015-08-14 01:15
This is a duplicate of #5082, so I'm closing it as such. However, we're still looking for a reliable reproduction case for this issue, so if you have one, that would be excellent. Also, a few questions that might help us reproduce and fix this:

* is there a `main` entry in the affected packages? (`@whitneyit/log`: yes, points explicitly to `index.js`, `@whitneyit/clean`: same)
* what version of npm were you using?
* what version of Node / io.js were you using?
* Does the machine you're publishing from have an SSD or a rotating-disk hard drive? Is it a VM / cloud instance?

We suspect there's a race condition in one of npm's components that causes it to drop a stitch when packing the package tarball, and my current hypothesis is that it's sensitive to read latency at packaging time, but as I said, we haven't been able to come up with a way to make this bug reproduce itself consistently. Sorry this bit you, and thanks in advance for answering those questions!

**Closed by othiym23** 2015-08-14 01:15 UTC
Labels: bug

**Comment by whitneyit** [comment] 2015-08-14 01:18
When clean first stuffed up I was using `2..10.*`, I then updated to `2.13.4` and had it happen again
