### ISSUE TITLE
`npm uninstall` throws

### ISSUE THREAD

**Issue by DoctypeRosenthal** [npm/npm#12314] opened 2016-04-12 09:12 UTC
I should report this error.

Unfortunately and strangely this rich text field doesn't support .log-file attachments (strange!). So I attach my npm-debug.log as npm-debug.txt.

Hope it helps!

Cheers!

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /opt/lampp/htdocs/ToDo/redux
6 error Linux 3.13.0-71-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v5.4.0
9 error npm  v3.3.12
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment] 2016-04-12 14:44
@DoctypeRosenthal The log says you are running `npm start`, not `npm uninstall`....

**Comment by othiym23** [comment] 2016-04-12 17:41
I took the liberty of replacing the attached file with its contents; hope you don't mind. As @KenanY says, this isn't a crash due to uninstall, but from running `npm start` when there's no `"start"` script in the `"scripts"` section of `package.json`, which is expected behavior. You might want to read up on [npm scripts](https://docs.npmjs.com/misc/scripts). For now, I'm going to close this issue as it's not a problem in npm. Thanks for your time!

**Closed by othiym23** 2016-04-12 17:41 UTC
Labels: support
