### ISSUE TITLE
ERR! Cannot read property path of null

### ISSUE THREAD

**Issue by daintypearl** [npm/npm#15854] opened 2017-02-24 05:50 UTC
#### I'm opening this issue because:
I m getting the following error 

D:\Power BI\Creating Custom Visual s for power bi\node js>npm install -g  powerb
i-visuals-tools
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Power BI\\Creating Custom Visual s for power bi\\node js\\nod
e.exe" "D:\\Power BI\\Creating Custom Visual s for power bi\\node js\\node_modul
es\\npm\\bin\\npm-cli.js" "install" "-g" "powerbi-visuals-tools"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Power BI\Creating Custom Visual s for power bi\node js\npm-debug
.log

**Comment by legodude17** [comment] 2017-02-24 22:30
Duplicate of #15849.

**Closed** 2017-06-17 04:04 UTC
Labels: bot-closed
