### ISSUE TITLE
Unable to use the example to covert video file

### ISSUE THREAD

**Issue by Nikmike** [npm/npm#15688] opened 2017-02-06 13:54 UTC
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Can not convert video using Given example JS...

#### How can the CLI team reproduce the problem?
1> Create JS name "Full.js"
2>Add below code in it
3> 

var ffmpeg = require("fluent-ffmpeg");

// make sure you set the correct path to your video file
var proc = ffmpeg('C:\Users\GORDEN\Videos\Test-desktop.mp4')
  // set video bitrate
  .videoBitrate(1024)
  // set target codec
  .videoCodec('divx')
  // set aspect ratio
  .aspect('16:9')
  // set size in percent
  .size('50%')
  // set fps
  .fps(24)
  // set audio bitrate
  .audioBitrate('128k')
  // set audio codec
  .audioCodec('libmp3lame')
  // set number of audio channels
  .audioChannels(2)
  // set custom option
  .addOption('-vtag', 'DIVX')
  // set output format to force
  .format('avi')
  // setup event handlers
  .on('end', function() {
    console.log('file has been converted succesfully');
  })
  .on('error', function(err) {
    console.log('an error happened: ' + err.message);
  })
  // save to file
  .save('C:\Users\GORDEN\Videos\EncodedFIles\your_target.avi');

4>save it on desktop.
5> open NodeJs command prompt with Admin Privileges
6> Type cd "C:\Users\GORDEN\Desktop>node full.js" / Navigate to your desktop file" full.js  "
7> Then it gives below error

module.js:471
    throw err;
    ^

Error: Cannot find module 'fluent-ffmpeg'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\GORDEN\Desktop\full.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

### supporting information:

 - Windows, : windows 10 ( 64bit)

**Comment by KenanY** [comment] 2017-02-06 14:41
@Nikmike Make sure to install any dependencies you need, like `npm install fluent-ffmpeg`. Closing since this is not a bug in `npm` and this issue tracker is for bugs and feature requests.

**Closed by KenanY** 2017-02-06 14:41 UTC

**Comment by Nikmike** [comment] 2017-02-07 06:08
Fluent- FFmpeg is installed on My System. please find below version.

C:\Windows\System32>npm fluent-ffmpeg -v
3.10.10

**Comment by KenanY** [comment] 2017-02-07 16:19
@Nikmike That command is displaying the version of `npm` you have installed.
