### ISSUE TITLE
npm-update documentation doesn't match behaviour, and behaviour is odd.

### ISSUE THREAD

**Issue by latentflip** [npm/npm#5024] opened 2014-04-07 13:07 UTC
I'm running into a number of issues understanding exactly how npm-update works. (I'm on 1.4.6)
1. The [documentation](https://www.npmjs.org/doc/cli/npm-update.html#DESCRIPTION) says: "This command will update all the packages listed to the latest version (specified by the tag config)." However, if I have an old dependency listed exactly, like `"underscore": "1.3.3"`, running `npm update --save --save-exact` doesn't update it at all. Which would imply it's actually installing "the latest version which specifies the semver spec". Similar same happens if I specify it like "1.3.x", 
2. Assuming no new versions have been installed, it would seem that npm-update should be idempotent, however, again with a dependency of `"underscore": "1.3.3"`, running `npm install --save` once doesn't install a new version but changes the package to `"underscore": "^1.3.3"`, and now when if I run `npm update --save` again it installs 1.6.0 and upgrades package.json again to `"underscore": "^1.6.0"`. Again, a similar thing happens if the package is specified as "1.3.x", it upgrades to "^1.3.3" the first time, then "^1.6.0"

Are these just expected behaviours, and I'm hitting an edge case in what npm-update is trying to achieve? What I _want_ is to pin versions exactly, but be able to easily update them to the latest version, pinned exactly, with `npm update <my-packages> --save --save-exact`

**Comment by smikes** [comment] 2015-01-06 01:24
> Are these just expected behaviours, and I'm hitting an edge case in what npm-update is trying to achieve?

These are expected behaviors, and I think you are one of the few who is actually using `npm update` appropriately.

Rather than using `--save --save-exact` to pin the versions, though, I think you can get what you're aiming for by using `npm shrinkwrap`.  The update workflow would be something like this:

```
npm update 
npm test && npm shrinkwrap
git commit npm-shrinkwrap.json -m 'updated dependencies on $(date)'
```

Then you could leave your dependencies specified as `"foo": "*"` in the package.json and not have to muck with the contents of that file, and the installed package versions would be pinned exactly by npm-shrinkwrap.

Please let me know if I have misunderstood what you're trying to do.  Also /cc @othiym23  for comments

**Comment by othiym23** [comment] 2015-01-07 01:28
> Are these just expected behaviours, and I'm hitting an edge case in what npm-update is trying to achieve?

The behavior of `npm update` is ill-defined (or, more accurately, undefined). I think your interpretation of the documentation is substantially correct: it's sensible to expect `npm update --save --save-exact` to _first_ update the dependencies to the `latest` version of each dependency, and _then_ save that exact version to `package.json`. I believe what's happening instead is also sensible: _first_ read the semver ranges for all of the dependencies from `package.json`, and _then_ update to the latest version matching the semver range specified by `package.json`, finally saving the exact version back to `package.json`.

As @smikes mentioned, people mostly just use `npm -g update`, which does something that is almost - but not quite - entirely unlike what they expect. This creates an opportunity for us to tweak the behavior. I'd be happy to take patches to make `npm update --save --save-exact` work the way you want, but be aware that

1. the behavior of npm update is [going to change](https://github.com/npm/npm/issues/6247)
2. the way it works requires some digging to understand

**Comment by othiym23** [comment] 2016-05-09 21:05
This is feature-ish work; there are a raft of inconsistencies around the behavior of `npm update` that cause it to be much less useful than it should be (and consequently experienced npm users tend to ignore or overlook it), but since this doesn't cause outright crashes, nor does it cause inconsistent installs on disk, it's slightly less priority than the other things with the `big-bug` label on it. Consequently, I've marked it as a feature request with the understanding that this is something the CLI team intends to get to within the next 6-12 months (unless our fine community beats us do it!), and am removing the `big-bug` label.

**Closed** 2017-06-19 11:16 UTC
Labels: already-looked-at, bot-closed, bug, feature-request, needs-discussion, ux
