### ISSUE TITLE
`npm uninstall -g yo` fails

### ISSUE THREAD

**Issue by bradj** [npm/npm#16921] opened 2017-06-02 14:33 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm uninstall -g yo` fails

#### How can the CLI team reproduce the problem?

I am not sure how to reproduce this. I type `npm uninstall -g yo` and it does this:

exception
https://gist.github.com/bradj/a4c649a6a20d851d2d8edfbe524bf215

debug-log
https://gist.github.com/bradj/29e049f8934a403de8dda294f538f256

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by maxdeviant** [comment] 2017-06-02 15:31
Getting this same error when trying to uninstall any globally-installed package.

- [Error](https://gist.github.com/maxdeviant/3984783299b973005b4a1fb064f910a7#file-error-txt)
- [Debug Log](https://gist.github.com/maxdeviant/3984783299b973005b4a1fb064f910a7#file-2017-06-02t15_26_16_194z-debug-log)

**Comment by tilda** [comment] 2017-06-02 15:46
Possible duplicate of #16904

**Comment by maxdeviant** [comment] 2017-06-02 16:59
@xshotD Yea, it looks like they're the same issue.

**Comment by zkat** [comment] 2017-06-06 04:59
Closing as dupe of https://github.com/npm/npm/issues/16904. Cheers 👋

**Closed as completed by zkat** 2017-06-06 04:59 UTC
