### ISSUE TITLE
Windows support for non-cmd.exe shells for npm-run scripts

### ISSUE THREAD

**Issue by jsdnxx** [npm/npm#7209] opened 2015-01-25 10:52 UTC
[cmd.exe is broken](http://substack.net/task_automation_with_npm_run#windows), which makes it impossible to write cross-platform npm-run scripts.

I want to override `cmd.exe` as the command processor for npm run scripts on windows, since it's not compatible with basic shell-isms, like `&`, making it hard to write portable scripts even for basic tasks (like, say, running watchified sass and browserify at the same time).

I'm wanting to override `cmd.exe` with the msys `sh.exe` which ships with Git on Windows and works well - however I'd also need to override `shFlag` to be `-c` instead of `/c`.

Proposal: add a config setting which ignores the Windows-specific code block in https://github.com/npm/npm/blob/5fce278a688a1cb79183e012bde40b089c2e97a4/lib/utils/lifecycle.js#L201-205 which specifically calls out to `cmd.exe` to run npm-run scripts on Windows. In systems like msys, the default shell-style script execution runs just fine and is more compatible.

Of course, I don't want to break existing Windows installations. The default should remain cmd.exe - but I want to be able to turn that off and have npm try to execute npm-run scripts the same way that it does on other platforms.

**Comment by smikes** [comment] 2015-01-27 23:46
/cc @othiym23 as feature request

I believe there's a feature request or similar floating around that would use the value of %COMPSEC%  as the shell on Windows.

**Comment by othiym23** [comment] 2015-01-27 23:56
This is different. The `%COMSPEC%` change was [already included](https://github.com/npm/npm/commit/5fce278a688a1cb79183e012bde40b089c2e97a4) in `npm@2.3.0`; this is a more invasive request that would have an impact that extends out into how `cmd-shim` is used and `run-script` is configured, because `sh.exe` and `cmd.exe` are very different at a semantic level.

I think @jden's suggestion needs some more bikeshedding and refinement. It's not as simple, I think, as a simple conditional switch that can be set via configuration; there's a bunch of stuff going on in the `mingw` world, and npm's approach to Windows is equally crenelated and gingerbreaded in some horrifi punctuated-equilibrium evolutionary way. Also, I am all in favor of improving the Git Bash experience of npm, but not at the cost of breaking *anything* for generic Windows users, because there are a lot of them and a breaking change for even a small number of them ends up being a significant increase in the number of open npm issues.

**Comment by othiym23** [comment] 2016-09-20 21:55
We discovered that this is a duplicate of existing feature request #6543, so I'm going to close it in favor of that. The current consensus is that allowing users to choose their own shell for running scripts is probably more of a boon than a footgun, so this is something we'd like to see land. Thanks to @jsdnxx for filing this in the first place!

**Closed by othiym23** 2016-09-20 21:55 UTC
Labels: feature-request, needs-discussion, patch-welcome
