### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by Q15010417** [npm/npm#13405] opened 2016-07-17 14:38 UTC
#### I'm opening this issue because:
  - [ ] npm is doing something I don't understand.
 
### supporting information:
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Lenovo\\node.js\\node.exe" "C:\\Users\\Lenovo\\node.js
\\node_modules\\npm\\bin\\npm-cli.js" "install" "puer" "-g"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! shasum check failed for C:\Users\Lenovo\AppData\Local\Temp\npm-6980-f75
35a2b\registry.npmjs.org\socket.io-client\-\socket.io-client-0.9.16.tgz
npm ERR! Expected: 4da7515c5e773041d1b423970415bcc430f35fc6
npm ERR! Actual:   08c6365d59543afc18032f877b934104a6e767f0
npm ERR! From:     https://registry.npmjs.org/socket.io-client/-/socket.io-clien
t-0.9.16.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Lenovo\npm-debug.log

**Comment by KenanY** [comment] 2016-07-17 14:39
@Q15010417 Have you tried running `npm cache clean`?

**Comment by Q15010417** [comment] 2016-07-17 15:15
yes.but it didn't work.

**Comment by Q15010417** [comment] 2016-07-17 15:16
@KenanY yes,but it didn't work

**Comment by Q15010417** [comment] 2016-07-17 15:46
at last I found the way to solve this problem.
first ,copy this to the cmd and enter:
npm` config set registry http://registry.cnpmjs.org 

and then copy this:
npm info underscore 
(I am not really good at English.Please forgive me)

**Comment by othiym23** [comment] 2016-07-18 21:17
Closing as resolved – @Q15010417, it sounds like you're behind the Chinese firewall, so switching to the cnpmjs registry is indeed the most likely way to get past these errors, which are caused by incomplete or corrupt downloads of package tarballs. Thanks for your time!

**Closed by othiym23** 2016-07-18 21:17 UTC
Labels: network, shasum, support

**Comment by chenyijie-bit** [comment] 2017-06-06 05:25
could you help me ? thank you

![02](https://cloud.githubusercontent.com/assets/23470635/26814923/9c187a50-4abb-11e7-9f6f-b55253ac957b.png)
