### ISSUE TITLE
npm@3.x shrinkwrap of git dependencies fails hard on subsequent `npm shrinkwrap` or `npm ls`

### ISSUE THREAD

**Issue by evocateur** [npm/npm#10502] opened 2015-11-20 20:22 UTC
Starting with at least `npm@3.3.12` (shipped in `node@5.1.0`), and continuing with the latest preview release (`npm@3.5.0`), any subsequent `npm shrinkwrap` or `npm ls` after shrinkwrapping a git dependency will fail.

``` sh
npm cache clean async
npm i -S async
rm -rf node_modules && npm i
npm shrinkwrap # 0: no error
rm -rf node_modules && npm i
npm shrinkwrap # 1: idempotent, no error
npm i -S sindresorhus/get-stream#v1.0.0
npm shrinkwrap # 2: no error
rm -rf node_modules && npm i
npm shrinkwrap # 3: error
npm ls # error
```

I've created a repo that illustrates the [repro steps](https://github.com/evocateur/testing-shrinkwrap) with full diffs. The full debug log  after `npm shrinkwrap` at step 3 above is in the repo, but here's the relevant chunk:

``` txt
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack invalid: have get-stream@1.0.0 (expected: github:sindresorhus/get-stream#v1.0.0) ${PACKAGE_DIR}/node_modules/get-stream
4 verbose stack extraneous: get-stream@1.0.0 ${PACKAGE_DIR}/node_modules/get-stream
4 verbose stack     at shrinkwrap_ (${NPM_DIR}/lib/shrinkwrap.js:101:15)
4 verbose stack     at ${NPM_DIR}/lib/shrinkwrap.js:36:5
4 verbose stack     at ${NPM_DIR}/node_modules/iferr/index.js:13:50
4 verbose stack     at ${NPM_DIR}/lib/install/deps.js:123:5
4 verbose stack     at LOOP (${NPM_DIR}/node_modules/slide/lib/chain.js:7:26)
```

Here's the output of the `npm ls`:

``` txt
testing-shrinkwrap@ ${PACKAGE_DIR}
├── async@1.5.0
└── get-stream@1.0.0 invalid (git://github.com/sindresorhus/get-stream.git#56bf66ad5a924be824a6603d000c68ca394f71f5)

npm ERR! invalid: get-stream@1.0.0 ${PACKAGE_DIR}/node_modules/get-stream
```

Notably, the hash indicated in the `npm ls` output is identical to the `"resolved"` attribute in the shrinkwrap.

`npm@2` [does not exhibit](https://github.com/evocateur/testing-shrinkwrap/tree/npm2) this problem.

**Comment by markstos** [comment] 2016-01-06 16:46
To add to this conversation, I ran into this bug with `npm 3.5.2` with a package.json value specified like this:

```
git://github.com/team/project.git#ebb45f03a32cef85aaf745cf976ed668d5645e84
```

Trying `npm shrinkwrap` produced a failure like this:

```
npm ERR! invalid: have project@0.0.4 (expected: github:team/project#branch) 
```

I was able to successfully work around the issue, by running `npm rm name_of_module` and then running `npm install git://github.com/team/project.git#ebb45f03a32cef85aaf745cf976ed668d5645e84`

After that, `npm shrinkwrap` worked. So it appears that  the issue *might* be fixed in `npm 3.5.2` but only if the original `npm install` was also made with the same version.  It would have been interesting to compare the `package.json` files generated in `node_modules` for the affected package for the new and old `npm` versions, but unfortunately I didn't think to save those files for diffing.

If this is indeed the issue, it would be nice if future versions of `npm` could detect the issue and if not workaround it, then at least update the diagnostic message to suggest that re-installing the related modules might help.

**Comment by ifuyivara** [comment] 2016-03-31 18:44
I ran into the same issue today. I tried @markstos workaround with no luck. Also this issue is with a dependency of one of my dependencies (both of which are a github repo).

**Comment by runn1ng** [comment] 2016-04-01 14:30
I can reproduce it also

**Comment by FredyC** [comment] 2016-04-07 19:13
Same issue here for npm 3.7.3 on Windows 10 x64. It does generate correct shrinkwrap file for the first time, but any subsequent run complains with same errors as above. Doesn't work either for `github:` urls nor private ones like `git+ssh://git@....`.

**Comment by ryan-sandy** [comment] 2016-04-14 18:54
I too am experiencing this issue. I was able to work around it by deleting the `npm-shrinkwrap.json` file then running `npm shrinkwrap`.

**Comment by tonybaroneee** [comment] 2016-06-10 21:22
+1. We implemented the same workaround as @ryan-sandy.

**Comment by FredyC** [comment] 2016-06-11 05:26
@tonybaroneee Is that actually good workaround? In case your `package.json` is using either `~` or `^`, you can get different versions in shrinkwrap too and that kinda ruins all that effort.

**Comment by tonybaroneee** [comment] 2016-06-11 11:20
Good point, it does kind of negate the purpose of the shrinkwrap now that I think about it.

**Comment by FredyC** [comment] 2016-06-12 06:51
I have personally decided to not use shrinkwrap for now and rather have fixed versions of modules in package.json. I aware that doesn't work deeply and some package dependency could break stuff, but I guess that's something I have to trust till this is fixed somehow.

**Comment by runn1ng** [comment] 2016-06-13 10:34
I worked around it by always removing whole `node_modules` and doing whole `npm install` again. It takes a while, but I am sure that it's installing what I want.

**Comment by finneganh** [comment] 2016-06-13 19:58
I work with @tonybaroneee. Turns out removing npm-shrinkwrap.json before re-shrinkwrapping does not help. If the GitHub packages were installed with npm-shrinkwrap.json present (which we want in order to have predictable production builds; fixed versions only works for first-level dependencies, not for transitive ones) then you can't re-run shrinkwrap without the "extraneous" errors.

I'd be interested in diving in to fix this, if there were any pointers to where these checks are happening.

**Comment by finneganh** [comment] 2016-06-14 18:19
Dug into this a bit. An immediate workaround is to specify your GitHub dependencies in your package.json like so:

`git://github.com/ORGNAME/REPO.git#123456sha`

This will cause the "rawSpec" format for the dependency to match with what the shrinkwrap-installed package will have in its "_requested" value.

(What we're trying to do is make deps.js#doesChildVersionMatch return true.)

Part of the tension here is that most of the shrinkwrap-installed stuff has coverted tags / branches to particular SHAs, which is presumably a good thing for repeatability.

There is a line in doesChildVersionMatch that seems like it would work given the sha / tag mismatch, which is:

`if (!registryTypes[requested.type]) return requested.rawSpec === child.package._from`

However, I'm consistently seeing `requested.rawSpec` have values like `github:ORG/REPO#tag` while `child.package._from` has values like `ORG/REPO#tag`. the lack of “github:” at the beginning is keeping this check from succeeding for us.

The NPM devs would have to say for certain, but may be a bug that `child.package._from` *never* is prefixed with “github:”, while `requested.rawSpec` *always* has it. This behavior is consistent regardless of whether the “github:” prefix appears in the package.json. There's some normalization going on, but it's inconsistent between those two values.

**Comment by jmonster** [comment] 2016-10-13 20:22
This issue has been biting me hard all week. In summation, to access private github repos by branch, I have to use the following format (and ONLY the following format) .. otherwise `npm ls` complains and `npm shrinkwrap` fails:

```
git+https://github.com/{{account}}/{{repo}}#dd2a43e7adc000980f6fa18ff83db2c545e34a51
```

`git+ssh` may also work, but not in my case as I use https auth on CI/Heroku, so I didn't try it.
other shorthands do not work -- `account/repo#branch`, `github://...`, etc.

Another important note -- I found that `account/repo#dd2a43e7adc000980f6fa18ff83db2c545e34a51` -- call it module X -- worked when required in module Y. But when I then required module Y in another module, Z, `npm ls` and `shrinkwrap` complained that module X was invalid again

**Comment by tonybaroneee** [comment] 2016-10-13 21:38
Switched to yarn :)

**Comment by jmonster** [comment] 2016-10-13 22:01
unfortunately private modules don't work there yet, either.

**Comment by tonybaroneee** [comment] 2016-10-13 23:22
Ah, gotcha. That's not a req for us anymore.

**Comment by karelbilek** [comment] 2016-10-14 08:14
yarn has issues with git dependencies too.

edit: not anymore :D

**Closed** 2017-06-19 10:27 UTC
Labels: bot-closed, bug, shrinkwrap
