### ISSUE TITLE
npm install -g protractor: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by MarkAvreliy** [npm/npm#16599] opened 2017-05-11 14:14 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
>npm install -g protractor
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\blablabla\AppData\Roaming\npm-cache\_logs\2017-05-11T13_53_44_104Z-debug.log
```

#### How can the CLI team reproduce the problem?
1) download nodejs from main site.
2) install it
3) run CMD and execute _npm install -g protractor_

### supporting information:

 - `npm -v` prints:
v7.10.0
 - `node -v` prints:
4.2.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Win10 Pro
 - Network issues:
   - Geographic location where npm was run:
RUS
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thanks an advance!

**Comment by legodude17** [comment] 2017-05-11 16:18
Duplicate of #10686.

**Comment by legodude17** [comment] 2017-05-11 16:18
This is most likely a problem with your internet. Please check your internet connection.

**Comment by MarkAvreliy** [comment] 2017-05-12 12:28
Hello all.
Internet worked and works good, but reason was in npmrc file. It contained just _prefix=${APPDATA}\npm_ 

Now it contains:
registry=http://registry.npmjs.org/
proxy=http://
https-proxy=http://

Thanks for all and I close this issue.

**Closed** 2017-05-12 12:28 UTC
Labels: network, support
