### ISSUE TITLE
npm install --save <local-folder> works; npm install <local-module> does not

### ISSUE THREAD

**Issue by FuzzicalLogic** [npm/npm#12046] opened 2016-03-24 12:06 UTC
**NPM version: 3.7.3**
**Node Version: 5.9.1**
**Platform: Windows 10**

For local repositories, I often install local modules until each feature is ready to upstream. After performing an upgrade to node.js (4.4.1 -> 5.9.1), npm was updated to 3.7.3 and nearly all of my local modules stopped working. 

`npm install --save <local-path>` will install the package properly, but `npm ls` will then mark the package as invalid. `npm cache clean` does not resolve the issue. Further, after testing, `npm uninstall <module-name>` _(resolved by the package.json)_ will uninstall the package, but `npm install <module-name>` results in the following output:

    npm ERR! addLocal Could not install C:\C:\local_folder
    npm ERR! Windows_NT 10.0.10586
    npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "module-name"
    npm ERR! node v5.9.1
    npm ERR! npm  v3.7.3
    npm ERR! path C:\C:\local_folder
    npm ERR! code ENOENT
    npm ERR! errno -4058
    npm ERR! syscall open
    
    npm ERR! enoent ENOENT: no such file or directory, open 'C:\C:\local_folder'
    npm ERR! enoent ENOENT: no such file or directory, open 'C:\C:\local_folder'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\path\npm-debug.log

This caused me to look at the package.json of the offending module. 

    "dependencies": {
        "module-name": "file:///C:\\path\\to\\module"
     },

While the above ended up being a properly formed file URI, the output above caused me to tinker with URI. As there was a duplicate `C:\` at each of the `ENOENT`s, I removed the `C:` from the dependency's URI. **Voila!** This solved the problem. However, this is simply a workaround. 
[npm-debug.txt](https://github.com/npm/npm/files/187785/npm-debug.txt)

**Comment by zkat** [comment] 2016-03-24 18:47
Closing this as a duplicate of #12027 -- thanks for filing this, and feel free to continue discussion in that other issue <3

**Closed by zkat** 2016-03-24 18:47 UTC

**Comment by cesarve77** [comment] 2017-03-01 07:49
https://guide.meteor.com/writing-npm-packages.html#overriding-npm-packages
