### ISSUE TITLE
ENOENT with 3.3.12

### ISSUE THREAD

**Issue by aredridel** [npm/npm#10236] opened 2015-11-03 01:54 UTC
```
npm WARN EPACKAGEJSON t@1.0.0 No description
npm WARN EPACKAGEJSON t@1.0.0 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "https://github.com/cjdelisle/cjdns.git"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.12
npm ERR! path /Users/aredridel/Projects/t/node_modules/johnny-five/node_modules/array-includes/node_modules/es-abstract/node_modules/function-bind
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, rename '/Users/aredridel/Projects/t/node_modules/johnny-five/node_modules/array-includes/node_modules/es-abstract/node_modules/function-bind'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aredridel/Projects/t/npm-debug.log
```

https://gist.github.com/97ea8376fcf4d7718908 for debug log

**Comment by iarna** [comment] 2015-11-06 19:44
Closing this as a duplicate of #9633

**Closed by iarna** 2015-11-06 19:44 UTC
