### ISSUE TITLE
npm ERR! Error: EBUSY (npm -install -g strongloop)

### ISSUE THREAD

**Issue by katperezz** [npm/npm#11501] opened 2016-02-11 09:45 UTC
browser bundle successfully generated
**npm ERR! Error: EBUSY,** open 'C:\Users\Katrine\AppData\Roaming\npm\node_modules\s
trongloop\node_modules\strong-registry\node_modules\inquirer\node_modules\lodash
\package.json'

**Comment by HardieBoeve** [comment] 2016-02-11 10:26
Can you try to update npm?

**Comment by othiym23** [comment] 2016-08-19 21:56
Closing as a duplicate of #8564.

**Closed by othiym23** 2016-08-19 21:56 UTC
Labels: support, windows
