### ISSUE TITLE
Error: Invalid array buffer length.

### ISSUE THREAD

**Issue by Anabar** [npm/npm#13053] opened 2016-06-14 15:51 UTC
Several times I used simple "npm s 'string'".  
OS: OpenBSD 5.9/amd64, npm 2.14.12,  node v4.3.0   

Please, see log
[npm-debug.log.txt](https://github.com/npm/npm/files/314342/npm-debug.log.txt)

**Comment by KenanY** [comment] 2016-06-14 16:04
@Anabar I cannot reproduce this with node 6.2.1 and npm 3.9.5. Does this also occur with newer versions of `npm`?

**Comment by Anabar** [comment] 2016-06-14 16:23
Those versions are from binary packages in last release OS (5.9/amd64, March 29). It is production server.
To get newer version I ought to use other machine with such OS (and ports from snapshot); it will take time.

**Comment by KenanY** [comment] 2017-03-24 14:32
Closing since my own testing showed that this is probably resolved in newer versions of `npm`. If not, I will happily reopen.

**Closed by KenanY** 2017-03-24 14:32 UTC
Labels: support
