### ISSUE TITLE
npm update --save --dev puts dev deps in dependencies

### ISSUE THREAD

**Issue by SimenB** [npm/npm#12384] opened 2016-04-17 14:04 UTC
When persisting updated dependencies including dev deps, the "updated" dev dependency is written to the `dependencies` hash in package.json, not `devDependencies`?.

**Comment by othiym23** [comment] 2016-04-18 21:01
`--save --dev` does something entirely different (and generally undesirable) than using what I think you were aiming for, which is `--save-dev` / `-D`. Closing as resolved. Let us know if `--save-dev` doesn't work for you.

**Closed by othiym23** 2016-04-18 21:01 UTC
Labels: support

**Comment by SimenB** [comment] 2016-04-19 06:03
Ah, so it matches `install`, that makes sense. And it does work!
I still think it's a bug that you put dev deps in normal deps after running it though. Maybe warn if both options are used in conjunction?

**Comment by SimenB** [comment] 2016-04-19 13:18
@othiym23 Actully, this is buggy, `npm update -S` puts updated dev deps in `dependencies` without me specifying `--dev` or `--save-dev`

**Comment by othiym23** [comment] 2016-04-19 16:19
@SimenB That's by design – `--save` / `-S` is intended to save to `dependencies`, `--save-dev` / `-D` is intended to save to `devDependencies`, and `--dev` is mostly intended as an argument for `npm prune` (the fact that it applies to `npm install` is a historical wart the CLI team would like to remove, because its behavior is confusing and unhelpful, as it causes `devDependencies` to be recursively installed all the way across the dependency graph, which is rarely what you want).

npm will print a warning if dependencies are in both `dependencies` and `devDependencies`, because that's at best an inconsistency. A patch to disallow `--save` and / or `--save-dev` from doing that, or just updating the semver in the relevant section, or causing it to switch which section the dependencies are in (with a warning, because using the wrong command is a frequent mistake) would be reviewed and probably landed without too much difficulty. The current behavior is more or less by design, though.

**Comment by SimenB** [comment] 2016-04-19 16:35
So with a package.json like

```json
{
  ...
  "devDependencies": {
    "lodash": "^4.0.1"
  }
}
```

Running `npm update -S` is designed to output

```json
{
  ...
  "devDependencies": {
    "lodash": "^4.0.1"
  },
  "dependencies": {
    "lodash": "^4.11.1"
  }
}
```

???

That makes no sense at all.

**Comment by othiym23** [comment] 2016-04-19 16:51
It _is_ unexpected behavior by users, which is why npm itself will warn you on install when a dependency is in both `dependencies` and `devDependencies`. Like I said above, a patch to prevent that would probably land (I hedge a little because there are some intricacies to the design around the user experience of such a change that it would be important to get right, like making sure that npm doesn't silently switch the section a dependency is in, or make it impossible to switch sections). As things stand right now, though, it's the way npm has always behaved, so it's squarely on the "unexpected behavior" side of the fence, rather than bug.

**Comment by SimenB** [comment] 2016-04-19 18:40
Hmm, a change npm itself makes to package.json is supposed to warn on the next invocation of npm install? What's the use of the save function then if it messes up the file?

So I suppose the real question is: why is devDependencies upgraded when not specifying `--dev`, and as that's the case, what is the point of the `--dev` flag?
