### ISSUE TITLE
Something wrong with node-6.9.0 (fresh install)

### ISSUE THREAD

**Issue by linuxenko** [npm/npm#14333] opened 2016-10-19 07:19 UTC
#### I'm opening this issue because:

  -  [x ] npm is crashing.

#### What's going wrong?

```
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

npm ERR! Cannot read property '_updated' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN Building the local index for the first time, please be patient

<--- Last few GCs --->

   33623 ms: Mark-sweep 1027.4 (1320.2) -> 1000.6 (1301.1) MB, 543.0 / 0.0 ms [allocation failure] [GC in old space requested].
   34215 ms: Mark-sweep 1000.6 (1301.1) -> 1000.4 (1307.1) MB, 591.4 / 0.0 ms [allocation failure] [GC in old space requested].
   34856 ms: Mark-sweep 1000.4 (1307.1) -> 1000.3 (1268.1) MB, 641.4 / 0.0 ms [last resort gc].
   35479 ms: Mark-sweep 1000.3 (1268.1) -> 1000.3 (1262.1) MB, 623.3 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xd3ee25cfb51 <JS Object>
    1: fromString(aka fromString) [buffer.js:199] [pc=0x3018e12ae8b0] (this=0xd3ee2504381 <undefined>,string=0x25fffac846c9 <Very long string[208695661]>,encoding=0xd3ee25dd361 <String[4]: utf8>)
    2: from [buffer.js:99] [pc=0x3018e1256c42] (this=0x143321ca3891 <JS Function Buffer (SharedFunctionInfo 0x2a917dff71c9)>,value=0x25fffac846c9 <Very long string[208695661]>,encodingOrOffset=0xd3ee25d...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [npm]
 2: 0x1098b2c [npm]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [npm]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
13: 0x9e6f22 [npm]
14: 0x9e759e [npm]
15: 0x3018e0d092a7
[1]    12405 abort (core dumped)  npm search express
```

#### How can the CLI team reproduce the problem?

`npm search express`

or something else

**Comment by KenanY** [comment] 2016-10-19 14:42
Duplicate of https://github.com/npm/npm/issues/12439, among other search-related issues. Should be fixed by https://github.com/npm/npm/pull/13746 though :)

**Closed by KenanY** 2016-10-19 14:42 UTC
