### ISSUE TITLE
requests@2.69.1

### ISSUE THREAD

**Issue by Gogfather** [npm/npm#13126] opened 2016-06-21 01:02 UTC
At around 2;30pm PDT today all of a sudden we keep getting this error:
npm WARN package.json origin-grunt-component-packager@0.0.0 No repository field.
      npm WARN package.json origin-grunt-component-packager@0.0.0 license should be a valid SPDX license expression
      npm ERR! Linux 3.5.0-23-generic
      npm ERR! argv "/home/originautomation/.nvm/versions/node/v0.12.7/bin/node" "/home/originautomation/.nvm/versions/node/v0.12.7/bin/npm" "install"
      npm ERR! node v0.12.7
      npm ERR! npm  v2.11.3
      
      npm ERR! version not found: request@2.69.1
      npm ERR! 
      npm ERR! If you need help, you may report this error at:
      npm ERR!     <https://github.com/npm/npm/issues>

Can some versions go offline?

**Comment by othiym23** [comment] 2016-06-21 01:23
Closing as duplicate of #13123. Check out that issue for details and resolution. The problem wasn't a disappearing dependency – `request@2.69.1` never existed in the first place.

**Comment by Gogfather** [comment] 2016-06-21 01:24
Sorry. I reopened this by accident.This is fixed for me.

**Closed by othiym23** 2016-06-21 01:23 UTC
