### ISSUE TITLE
Unable to remove npm update notification message

### ISSUE THREAD

**Issue by hackergrrl** [npm/npm#17476] opened 2017-06-27 21:29 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm@4` periodically shows me a curses-style box urging me to update to `npm@5`. I am not interested in updating at this time and would like to stop seeing this message.

#### How can the CLI team reproduce the problem?

Run an `npm` command several times until the notification appears in the output.

**Comment by kenany** [comment] 2017-06-28 22:06
Duplicate of https://github.com/npm/npm/issues/17453, I believe.

**Closed as completed by kenany** 2017-06-28 22:06 UTC
