### ISSUE TITLE
phonegap installation problem

### ISSUE THREAD

**Issue by kalyaniyaganti** [npm/npm#9424] opened 2015-08-27 07:49 UTC
These are the errors which are constantly occuring while i try to install phonegap... My wifi is connectin is alright...

```
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
```

**Comment by mdrozdo** [comment] 2015-08-29 22:00
Seems like a dupe of #9418

**Closed** 2017-06-16 23:57 UTC
Labels: bot-closed, support, windows
