### ISSUE TITLE
install @ionic/cloud-angular --save Failed 

### ISSUE THREAD

**Issue by kcsiva** [npm/npm#15813] opened 2017-02-21 10:10 UTC
#### I'm opening this issue because:

  
  - [ ] npm is producing an incorrect install.
  
#### What's going wrong?
"shasum check failed for C:\Users\User\AppData\Local\Temp\npm-15244-1533dd7c\registry.npmjs.org\_40ionic\cloud\-\cloud-0.16.0.tgz" - The error I am getting on executing the baove command...Please note that I am pretty much new to this filed and I was following the https://docs.ionic.io/services/push/ artcile

Please help me out as I am really really STUCK
[npm-debug.txt](https://github.com/npm/npm/files/789750/npm-debug.txt)

**Comment by legodude17** [comment] 2017-02-21 17:54
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.

**Closed** 2017-06-17 04:07 UTC
Labels: bot-closed
