### ISSUE TITLE
Unable to install Appium

### ISSUE THREAD

**Issue by c-hendo** [npm/npm#11909] opened 2016-03-15 10:57 UTC
Hi,
with the command "npm install -g appium" I receive:

npm ERR! node v5.8.0
npm ERR! npm  v3.8.1
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file

**Comment by karthik-uppoor** [comment] 2016-03-15 11:25
I get this when I run "npm install -g appium" : 


ubuntu@ubuntu-HP-Pavilion-g6-Notebook-PC:~$ npm install -g appium
npm ERR! tar.unpack unzip error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-atoms/-/appium-atoms-0.1.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-atoms/-/appium-atoms-0.1.0.tgz
npm ERR! tar.unpack unzip error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-adb/-/appium-adb-2.4.3.tgz
npm ERR! tar.unpack unzip error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-android-driver/-/appium-android-driver-1.6.12.tgz
npm ERR! tar.unpack untar error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-android-driver/-/appium-android-driver-1.6.12.tgz
npm ERR! tar.unpack unzip error /tmp/npm-7143-bebfed1a/registry.npmjs.org/babel-core/-/babel-core-5.8.24.tgz
npm ERR! tar.unpack unzip error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-instruments/-/appium-instruments-3.6.0.tgz
npm ERR! tar.unpack untar error /tmp/npm-7143-bebfed1a/registry.npmjs.org/babel-core/-/babel-core-5.8.24.tgz
npm ERR! tar.unpack unzip error /tmp/npm-7143-bebfed1a/registry.npmjs.org/appium-android-bootstrap/-/appium-android-bootstrap-2.5.1.tgz
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v5.8.0/bin/node" "/home/ubuntu/.nvm/versions/node/v5.8.0/bin/npm" "install" "-g" "appium"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

**Comment by zkat** [comment] 2016-03-15 23:19
Hi -- this is most likely caused by some kind of cache corruptions. We occasionally see something like this, so I'm marking it as a bug so we'll investigate it further.

For now, though, you will almost certainly be able to get back to work if you do `npm cache clean` and try installing again.

**Comment by c-hendo** [comment] 2016-04-14 15:49
Hi,
I try to clean the cache but It doesn't work 

114140 silly install printInstalled
114141 warn optional Skipping failed optional dependency /appium/fsevents:
114142 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.11
114143 verbose stack Error: appium-selendroid-driver@1.3.1 install: `node ./bin/install.js`
114143 verbose stack Exit status 1
114143 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
114143 verbose stack     at emitTwo (events.js:100:13)
114143 verbose stack     at EventEmitter.emit (events.js:185:7)
114143 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
114143 verbose stack     at emitTwo (events.js:100:13)
114143 verbose stack     at ChildProcess.emit (events.js:185:7)
114143 verbose stack     at maybeClose (internal/child_process.js:850:16)
114143 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
114144 verbose pkgid appium-selendroid-driver@1.3.1
114145 verbose cwd D:\
114146 error Windows_NT 6.1.7601
114147 error argv "D:\\dev\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
114148 error node v5.8.0
114149 error npm  v3.8.1
114150 error code ELIFECYCLE
114151 error appium-selendroid-driver@1.3.1 install: `node ./bin/install.js`
114151 error Exit status 1
114152 error Failed at the appium-selendroid-driver@1.3.1 install script 'node ./bin/install.js'.
114152 error Make sure you have the latest version of node.js and npm installed.
114152 error If you do, this is most likely a problem with the appium-selendroid-driver package,
114152 error not with npm itself.
114152 error Tell the author that this fails on your system:
114152 error     node ./bin/install.js
114152 error You can get information on how to open an issue for this project with:
114152 error     npm bugs appium-selendroid-driver
114152 error Or if that isn't available, you can get their info via:
114152 error     npm owner ls appium-selendroid-driver
114152 error There is likely additional logging output above.
114153 verbose exit [ 1, true ]

**Comment by zkat** [comment] 2016-04-14 16:30
You are seeing a different error now: Appium's installation script is failing. You'll need to contact Appium folks for support on that one, since this most likely doesn't have anything to do with npm itself.

See the relevant section:
```
114150 error code ELIFECYCLE
114151 error appium-selendroid-driver@1.3.1 install: node ./bin/install.js
114151 error Exit status 1
```

Since the npm side of this was fixed and this is no longer an npm issue, I'm going to close this. If you think there's still npm specific stuff, please feel free to comment here again or create a new issue. :)

**Closed by zkat** 2016-04-14 16:30 UTC
Labels: bug, cache

**Comment by c-hendo** [comment] 2016-04-15 14:17
thanks, I'll contact the Appium support.
best,
