### ISSUE TITLE
Error: Missing required argument #1 for npm update -g

### ISSUE THREAD

**Issue by siutsin** [npm/npm#9720] opened 2015-09-23 02:05 UTC
Hi, I am not able to run `npm update -g`, following is the error log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.1.0/bin/node',
1 verbose cli   '/Users/simonli/.node/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g' ]
2 info using npm@3.3.3
3 info using node@v4.1.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/Users/simonli/.node/lib/node_modules/npm/lib/install/logical-tree.js:12:3)
4 verbose stack     at /Users/simonli/.node/lib/node_modules/npm/lib/outdated.js:77:16
4 verbose stack     at /Users/simonli/.node/lib/node_modules/npm/lib/outdated.js:61:20
4 verbose stack     at /Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:188:9
4 verbose stack     at f (/Users/simonli/.node/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:154:20
4 verbose stack     at f (/Users/simonli/.node/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:123:22)
4 verbose stack     at /Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:83:20
4 verbose stack     at fs.js:1579:23
5 verbose cwd /Users/simonli/Desktop
6 error Darwin 14.5.0
7 error argv "/usr/local/Cellar/node/4.1.0/bin/node" "/Users/simonli/.node/bin/npm" "update" "-g"
8 error node v4.1.0
9 error npm  v3.3.3
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/Users/simonli/.node/lib/node_modules/npm/lib/install/logical-tree.js:12:3)
11 error typeerror     at /Users/simonli/.node/lib/node_modules/npm/lib/outdated.js:77:16
11 error typeerror     at /Users/simonli/.node/lib/node_modules/npm/lib/outdated.js:61:20
11 error typeerror     at /Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:188:9
11 error typeerror     at f (/Users/simonli/.node/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:154:20
11 error typeerror     at f (/Users/simonli/.node/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:123:22)
11 error typeerror     at /Users/simonli/.node/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:83:20
11 error typeerror     at fs.js:1579:23
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by joshuakleveter** [comment] 2015-09-23 11:27
I'm getting the same error on `npm outdated -g`. It only throws the error if I run the command with a `-g` flag though. Here's my debug log:
```

**Comment by thasmo** [comment] 2015-09-26 01:02
Same problem here.

**Comment by ingro** [comment] 2015-09-26 12:28
Here too, npm@3.3.4 on Windows 7, problem was not present in 3.3.3.

**Comment by thasmo** [comment] 2015-09-26 13:41
I got the problem using 3.3.3.

**Comment by ingro** [comment] 2015-09-27 12:54
Confirmed, I tried to force install of 3.3.3 and the problem is still present.

**Comment by joshuakleveter** [comment] 2015-10-01 11:29
I ended up doing a complete uninstall and reinstall of Node and NPM and that fixed the problem on my machine. Could be due to upgrading from NPM 2 to NPM 3.

**Comment by siutsin** [comment] 2015-10-02 02:48
@joshuakleveter I installed node and npm recently so I believe it should not related to npm 2 -> 3

**Comment by niallobrien** [comment] 2015-10-08 23:04
Same issue.

**Comment by dhritzkiv** [comment] 2015-10-09 16:29
Same here. On `v3.3.7`

**Comment by Olical** [comment] 2015-10-16 08:35
And on `v3.3.8`, Arch Linux with node `v0.12.7`. Tried a reinstall, did nothing.

**Comment by Olical** [comment] 2015-10-16 08:37
Here's my log...

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', '-g', 'outdated' ]
2 info using npm@3.3.8
3 info using node@v0.12.7
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /usr/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /usr/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at fs.js:1518:23
5 verbose cwd /home/ollie/repos/profiles/profile-estimates
6 error Linux 4.2.3-1-ARCH
7 error argv "node" "/usr/bin/npm" "-g" "outdated"
8 error node v0.12.7
9 error npm  v3.3.8
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /usr/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /usr/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /usr/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at fs.js:1518:23
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by goa-andersol** [comment] 2015-10-20 15:04
Same problem for me `v. 3.3.8`, `mac os el capitan`

**Comment by dhritzkiv** [comment] 2015-10-20 16:00
I found that upgrading to `v3.3.9` fixes this error for me.

**Comment by eonlepapillon** [comment] 2015-10-20 20:46
I updated to `v3.3.9`. That didn't help for me.
`npm update -g bower` results into:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/peter/.local/bin/node',
1 verbose cli   '/home/peter/.local/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.3.9
3 info using node@v4.2.1
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/home/peter/.local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /home/peter/.local/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /home/peter/.local/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/home/peter/.local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/home/peter/.local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at fs.js:1583:23
5 verbose cwd /home/peter
6 error Linux 3.13.0-65-generic
7 error argv "/home/peter/.local/bin/node" "/home/peter/.local/bin/npm" "update" "-g" "bower"
8 error node v4.2.1
9 error npm  v3.3.9
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/home/peter/.local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /home/peter/.local/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /home/peter/.local/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/home/peter/.local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/home/peter/.local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /home/peter/.local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at fs.js:1583:23
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by avdv** [comment] 2015-10-21 08:02
The problem for me was that there was a dangling symlink in my $PREFIX/lib/node_modules directory pointing to a linked module which I already had removed.

After removing the symlink, the "outdated -g" command worked (v3.3.8).

**Comment by Olical** [comment] 2015-10-21 08:12
@avdv Good catch! That was my issue too!

**Comment by michaelkrone** [comment] 2015-10-21 17:03
This is a duplicate of #9659.
I was facing the same Issue. I can confirm that removing missing linked modules solved ```npm update -g``` for me.

**Comment by ErikAbele** [comment] 2015-10-23 22:42
See also #9659.

**Comment by iamstarkov** [comment] 2015-11-03 16:38
@michaelkrone @ErikAbele not sure if its #9659 dup.

anyway its reproducable in 3.3.12
![screen shot 2015-11-03 at 17 36 22](https://cloud.githubusercontent.com/assets/559321/10914202/a45ca4fe-8251-11e5-8621-61165ecec130.png)

**Comment by iarna** [comment] 2015-11-06 19:32
The original issue here was a dup of #9659. The unrelated bug around mutate-into-logical-tree is not, and is currently an outstanding bug.

**Comment by WesTyler** [comment] 2015-11-16 21:06
I'm also getting the mutate-into-logical-tree missing arg issue, using Node 4.2.2 and npm 3.4.1 .
Any clues as to what's causing this bug / any workarounds?

**Comment by othiym23** [comment] 2015-12-04 17:33
This is a crasher, so I'm bumping it in importance to `big-bug`.

**Comment by fearphage** [comment] 2015-12-12 15:45
I can reproduce this error without the global flag or doing `npm update`. It still pertains to all the same files though (`lib/outdated` and `lib/install/mutate-into-logical-tree`).

node: 5.2
npm 3.3.12

```shell
✗ npm outdated     
npm ERR! Linux 3.19.0-37-generic
npm ERR! argv "/home/phred/.local/nvm/versions/node/v5.2.0/bin/node" "/home/phred/.local/nvm/versions/node/v5.2.0/bin/npm" "outdated"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /home/phred/.local/nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at fs.js:1658:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

It seems like npm 3.x is the culprit here. npm v2.9.1 seems to be the last version where this worked.

```shell
➜  webui git:(master) ✗ nvm use v5.2.0
Now using node v5.2.0 (npm v3.3.12)
➜  webui git:(master) ✗ for version in $(npm info --json npm | jq -r '.versions[]' | sort -r); do
        echo "installing $version";
        npm install -g npm@$version > /dev/null 2>&1;
        npm outdated > /dev/null 2>&1 && echo "version $version works" && break;
done;
installing 3.5.3
installing 3.5.2
installing 3.5.1
installing 3.5.0
installing 3.4.1
installing 3.4.0
installing 3.3.9
installing 3.3.8
installing 3.3.7
installing 3.3.6
installing 3.3.5
installing 3.3.4
installing 3.3.3
installing 3.3.2
installing 3.3.12
installing 3.3.11
installing 3.3.10
installing 3.3.1
installing 3.3.0
installing 3.2.2
installing 3.2.1
installing 3.2.0
installing 3.1.3
installing 3.1.2
installing 3.1.1
installing 3.1.0
installing 3.0.0
installing 2.9.1
version 2.9.1 works
```

**Comment by igor-galchevsky** [comment] 2016-01-12 00:54
Same with node@v4.2.2, npm@3.5.3 

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/igor/.nvm/versions/node/v4.2.2/bin/node',
1 verbose cli   '/Users/igor/.nvm/versions/node/v4.2.2/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g' ]
2 info using npm@3.5.3
3 info using node@v4.2.2
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at fs.js:1578:23
5 verbose cwd /private/tmp
6 error Darwin 13.4.0
7 error argv "/Users/igor/.nvm/versions/node/v4.2.2/bin/node" "/Users/igor/.nvm/versions/node/v4.2.2/bin/npm" "update" "-g"
8 error node v4.2.2
9 error npm  v3.5.3
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /Users/igor/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at fs.js:1578:23
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by semiromid** [comment] 2016-01-22 03:39
I trining - npm -g outdated   but give errors.

**Comment by oshliaer** [comment] 2016-01-27 04:54
```
> npm outdated -g --depth=0
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "outdated" "-g" "--depth=0"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\install\mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\outdated.js:78:5
npm ERR! typeerror     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\lib\outdated.js:62:20
npm ERR! typeerror     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:186:9
npm ERR! typeerror     at f (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:17:25)
npm ERR! typeerror     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:152:20
npm ERR! typeerror     at f (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:17:25)
npm ERR! typeerror     at then (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:121:22)
npm ERR! typeerror     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-tree\rpt.js:81:20
npm ERR! typeerror     at fs.js:1657:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```
Unlike **Node v5.4.1** works fine.

**Comment by alistairjcbrown** [comment] 2016-05-08 19:47
I had this same issue with a project using the latest node (`v6.1.0`) and npm (`v3.9.0`), running `npm install` from a clean slate (no `node_modules` directory, cache cleaned).
I'm not able to replicate with an empty "test" project with just lodash as dependency in the `package.json` file. This issue also doesn't occur for me using npm `v3.8.9`.

Let me know if you need any other details, such as the `npm-debug.log` output.

```
> $ npm install
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/alistairbrown/.nvm/versions/node/v6.1.0/bin/node" "/Users/alistairbrown/.nvm/versions/node/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at markDeps (/Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/install/deps.js:106:5)
npm ERR! typeerror     at /Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at recalculateMetadata (/Users/alistairbrown/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/install/deps.js:147:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

**Comment by jiajiawang** [comment] 2016-05-09 01:23
Got the save issue here after upgrading npm to `v3.9.0`.

```
 ❯❯❯ npm i 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/JJ/.nvm/versions/node/v5.9.1/bin/node" "/Users/JJ/.nvm/versions/node/v5.9.1/bin/npm" "i"
npm ERR! node v5.9.1
npm ERR! npm  v3.9.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at markDeps (/Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/lib/install/deps.js:106:5)
npm ERR! typeerror     at /Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at recalculateMetadata (/Users/JJ/.nvm/versions/node/v5.9.1/lib/node_modules/npm/lib/install/deps.js:147:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/JJ/workspace/range-me/client/npm-debug.log
```

**Comment by pmadruga** [comment] 2016-05-16 14:54
Having the same issue with v3.9.0 (with node v5.6.0).
Solution is to rollback to 3.8.9.

**Comment by cglantschnig** [comment] 2016-05-17 10:03
I had the same issue with v3.9.0 (node 4.4.4), 
Solution was to delete the node_modules directory and reinstall the dependencies.

**Comment by iamrudra** [comment] 2016-05-18 05:57
@cglantschnig - Tried that - does not seem to work for me.

**Comment by ilyaigpetrov** [comment] 2016-05-20 06:58
Updating npm from 4.4.4/3.9.0 to 4.4.4/3.9.3 with `npm update -g npm` helped.
@iamrudra You have deleted some global `node_modules` with npm in it, but should have deleted `node_modules` of the project under issue, I believe.

**Comment by iamrudra** [comment] 2016-05-21 02:56
@ilyaigpetrov - I just cloned a project and was trying to install the modules for the first time. And I guessed that the sentiment was to update the npm and since it would not do so by itself, you delete the global node_modules to reinstall.  :/

**Comment by iamrudra** [comment] 2016-05-21 02:57
@ilyaigpetrov - I tried the same thing as you did `npm update -g npm` - But that does not seem to work (as expected) for me - It updates to `3.9.2` in stead of `3.9.3`

**Closed** 2017-06-19 10:34 UTC
Labels: big-bug, bot-closed, bug
