### ISSUE TITLE
issue with installing stuff with grunt

### ISSUE THREAD

**Issue by M7amadSa3ed** [npm/npm#14349] opened 2016-10-20 12:56 UTC
- `npm -v` prints: 2.15.9
- `node -v` prints: v4.6.1
- `npm config get registry` prints:  /usr/local/lib/node_modules/npm
  - [x] I develop using Vagrant on OS X .

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for /var/folders/c5/pcpx83cn179cvr8mhdmw1w500000gn/T/npm-1653-7fce845f/registry.npmjs.org/grunt-html/-/grunt-html-8.0.2.tgz
npm ERR! Expected: 886d9c170a85f90f529f320697d1847d89e3bfa0
npm ERR! Actual:   138b52ea13ccffde95aaccb48d178da9aaabff58
npm ERR! From:     https://registry.npmjs.org/grunt-html/-/grunt-html-8.0.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
clear

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mohamedsaed/node_modules/bootstrap/npm-debug.log

**Comment by KenanY** [comment] 2016-10-20 19:08
@M7amadSa3ed Have you tried running `npm cache clean`?

**Comment by KenanY** [comment] 2016-10-27 18:18
Closing as abandoned.

**Comment by M7amadSa3ed** [comment] 2016-10-27 18:22
hi mate , yeah i have tried to go with cache clean , and the same problem are remains

**Comment by zkat** [comment] 2016-12-02 04:39
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps.

**Closed by zkat** 2016-12-02 04:39 UTC
Labels: network, shasum
