### ISSUE TITLE
Bad JSON when performing NPM install

### ISSUE THREAD

**Issue by sribiere** [npm/npm#12250] opened 2016-04-07 09:29 UTC
Hello

#https://github.com/npm/npm/issues/12196

This morning, I tried again with a 1.4.3 NPM and I still have gzipped JSON

> npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
npm ERR! �UMs1
                  �+_
�V��h��ܔڋ&b�!(�.\    &��NL�K�ɩi/M���bWdwMm/�f���X>LJf�za@�Oғx���@�e�����%���&�[տP}2��El����Y��0
                  ��#E��0���p���G�m�;�d�
npm ERR! ˜�J̠
            r���~W�#���<���+�m��orK��-���$�w�nb��?�+�芺{��hŭ.#q�H �����S�}�ɾI�fΐ�c�7դ�r��L�%@lK�t$=�&:���ˣ�Gn���
npm ERR! kq�Ӣ,T��<�R
                     O���s�Ec���t��%u�Mch�?�^��cBs���Z�Z�T�>���Q�ו�hI*�	�$&���W8i�
                                                                                            �	���� n�5)(��Z����%&�`�7�<
npm ERR!  Tҏ��
              H�\���z��$�J���^˻��[����	$�v�H�!d��3�؃DO
                                                            �
                                                             ���)N7+Q̜��u.,D�gP��M�o�����^#��ZJ��%.-���LC�CS�ghf�!�`pm��?�����.�F�vf�Cc��
                                                                                                                                             se�QS�3O�2�|
npm ERR! ����z�/��O�[3�����Υ�¿H�uޮ!9�dE��Ԓ�^M��oq�߉"!�RFɮ,
�+������.zgv$	OU�$���m�D��$��~�r-���L1jo���w��CNp~�h���*���h�Ս��O��E�
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:203:23)
npm ERR!     at Request.self.callback (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

> npm ERR! System Linux 3.2.0-101-generic
npm ERR! command "/home/sribiere/.nvm/v0.10.26/bin/node" "/home/sribiere/.nvm/v0.10.26/bin/npm" "i"
npm ERR! cwd /home/sribiere/src/AFCHELSINK/GTO/gto_api_card_access/trunk
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type unexpected_token

For some reasons it is impossible for us to upgrade to the lastest version of NPM
Is there any other workaround?

Regards

**Comment by beloha** [comment] 2016-04-07 11:30
small tip: upgrade to 1.4.5 if you can. That did it for me ;-)

**Comment by sribiere** [comment] 2016-04-07 11:32
Let's hope this kind of regression won't happen again....

**Comment by othiym23** [comment] 2016-04-07 16:05
Closing as duplicate of #12196. It's my hope as well that npm can put into place processes to keep edentate like this from recurring. Thanks for your patience!

**Closed by othiym23** 2016-04-07 16:05 UTC
