### ISSUE TITLE
Git-based npm modules not installing correct versions

### ISSUE THREAD

**Issue by BryanDonovan** [npm/npm#7202] opened 2015-01-23 22:28 UTC
I've found that since commit 1a90ec2f2cfbefc8becc6ef0c480e5edacc8a4cb, when npm dependencies are specified by using their git URLs, then child modules don't install the correct versions.

I've created a repo here that demonstrates this:https://github.com/BryanDonovan/npm-git-test

If you clone that repo and run `npm install` with a commit prior to 1a90ec2f2cfbefc8becc6ef0c480e5edacc8a4cb, (e.g. npm@2.0.0 works) the child dependencies are installed correctly.  E.g.,:

```
 $ npm list
npm-git-test@1.0.0 /Users/bdonovan/code/node/npm-git-test
├─┬ dummy-npm-bar@4.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-bar.git#575b86626745cda65c05da620ae1c64e8a34dee7)
│ ├── dummy-npm-buzz@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#fc6c1ebffccd5ef8755c833072c41be51448f2d6)
│ └── dummy-npm-foo@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-foo.git#8524863b7db0ab64eedf7a38c8af670d04865839)
├── dummy-npm-buzz@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#fc6c1ebffccd5ef8755c833072c41be51448f2d6)
└─┬ dummy-npm-foo@4.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-foo.git#295739950f3366d9ce668082748e80674670d605)
  └── dummy-npm-buzz@2.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#21673508ffed3584acb800421be7c4a337f4fe78)
```

But if we run npm install with a newer version of npm, the `dummy-npm-bar` dependency has the wrong version of `dummy-npm-buzz` installed (it should be 3.0.0, but it's 2.0.0 instead):

```
$ npm list
npm-git-test@1.0.0 /Users/bdonovan/code/node/npm-git-test
├─┬ dummy-npm-bar@4.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-bar.git#575b86626745cda65c05da620ae1c64e8a34dee7)
│ ├── dummy-npm-buzz@2.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#21673508ffed3584acb800421be7c4a337f4fe78)
│ └── dummy-npm-foo@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-foo.git#8524863b7db0ab64eedf7a38c8af670d04865839)
├── dummy-npm-buzz@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#fc6c1ebffccd5ef8755c833072c41be51448f2d6)
└─┬ dummy-npm-foo@4.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-foo.git#295739950f3366d9ce668082748e80674670d605)
  └── dummy-npm-buzz@2.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#21673508ffed3584acb800421be7c4a337f4fe78)
```

That is, `dummy-npm-bar@4.0.0` lists `dummy-npm-buzz@3.0.0` as a dependency, but `dummy-npm-buzz@2.0.0` is installed.  

The `dummy-npm-foo` npm lists `dummy-npm-buzz@2.0.0` as a dependency, so somehow this is getting mixed up with the `dummy-npm-bar` dependency of `dummy-npm-buzz@3.0.0`.

**Comment by smikes** [comment] 2015-01-27 23:17
Thanks for the bug report and repro case.

**Comment by tommymessbauer** [comment] 2015-04-08 22:04
@BryanDonovan  Great repro case!  

I have this exact same issue in my environments.  Going to rollback to npm 2.0.0 to see if this resolves it for now.

**Comment by tommymessbauer** [comment] 2015-04-08 23:54
Confirmation:  Rolling back to npm@2.0.0 works for now.

**Comment by smikes** [comment] 2015-04-17 12:16
I just checked this with the latest npm (2.8.3) and the bleeding-edge npm (2.8.4) and the problem is still present.

@BryanDonovan , for your actual use case, can you work around this with the new scoped module support in the npm registry?

**Comment by BryanDonovan** [comment] 2015-04-17 16:06
@smikes - Not sure, but I'll look into it.

**Comment by BryanDonovan** [comment] 2015-04-17 16:44
I think we'll get around this by publishing our modules to an internal registry.

**Comment by tommymessbauer** [comment] 2015-04-17 21:45
We lost a lot of time this week when we updated a internal module repo with breaking changes.  We have higher level deps that rely on different versions of the lib (like everything).  

We do not have it solved, but for the near term, uber's npm-shrinkwrap tool is making things possible.  The uber shrinkwrap.json file allows npm@2.8.1 to install properly about ~90% percent of the time, but it is not perfect.  We still have to manually double check the build logs to make sure the correct versions were installed.

**Comment by othiym23** [comment] 2015-04-21 00:40
I can't reproduce this with npm `HEAD`:

```
bauchelain% hub clone BryanDonovan/npm-git-test test-git-install-git-dependencies
Cloning into 'test-git-install-git-dependencies'...
remote: Counting objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Receiving objects: 100% (13/13), done.
Resolving deltas: 100% (3/3), done.
Checking connectivity... done.
bauchelain% cd test-git-install-git-dependencies
bauchelain% git status -sb
## master...origin/master
bauchelain% npm --version
2.8.4
bauchelain% npm install
dummy-npm-buzz@3.0.0 node_modules/dummy-npm-buzz

dummy-npm-foo@4.0.0 node_modules/dummy-npm-foo

dummy-npm-bar@4.0.0 node_modules/dummy-npm-bar
└── dummy-npm-foo@3.0.0
bauchelain% npm ls
npm-git-test@1.0.0 /Users/ogd/Documents/projects/test-git-install-git-dependencies
├─┬ dummy-npm-bar@4.0.0
│ └── dummy-npm-foo@3.0.0
├── dummy-npm-buzz@3.0.0
└── dummy-npm-foo@4.0.0
```

Am I missing something?

**Comment by othiym23** [comment] 2015-04-21 00:46
Apparently I was!

```
bauchelain% rm -r node_modules
bauchelain% npm i
dummy-npm-buzz@3.0.0 node_modules/dummy-npm-buzz

dummy-npm-foo@4.0.0 node_modules/dummy-npm-foo
└── dummy-npm-buzz@2.0.0

dummy-npm-bar@4.0.0 node_modules/dummy-npm-bar
├── dummy-npm-buzz@2.0.0
└── dummy-npm-foo@3.0.0
bauchelain% npm ls
npm-git-test@1.0.0 /Users/ogd/Documents/projects/test-git-install-git-dependencies
├─┬ dummy-npm-bar@4.0.0
│ ├── dummy-npm-buzz@2.0.0
│ └── dummy-npm-foo@3.0.0
├── dummy-npm-buzz@3.0.0
└─┬ dummy-npm-foo@4.0.0
  └── dummy-npm-buzz@2.0.0
```

There appears to be a race between the top-level git dependencies finishing the installation process before deciding what to install next. It exists somewhere in between the caching and installation code (and may involve `read-installed` and `read-package-json`), and is probably going to be a little tricky to track down. Unfortunately, I'm not going to have time to dive deep on this soon, but if somebody wants to take a look at it, that would be most welcome. This is definitely a bug I want fixed in `npm@2`.

**Comment by BryanDonovan** [comment] 2015-04-21 01:02
Yes, the `rm -r node_modules` step is a key step that I forgot to mention.  If you do that, the bug is repeatable every time.

**Comment by othiym23** [comment] 2015-04-21 01:03
The initial caching process probably changes the timings enough to keep the problem from manifesting at least part of the time. :/ I really strongly dislike race conditions. :imp:

**Comment by iarna** [comment] 2015-04-27 21:51
Yeah, I've seen the race condition result in different outcomes both with `rm -rf node_modules` at the start. 😕

**Closed** 2015-04-30 23:49 UTC
Labels: bug, git, in progress, next-patch

**Comment by BryanDonovan** [comment] 2015-05-01 00:58
Awesome, thanks!

**Comment by BryanDonovan** [comment] 2015-05-01 01:29
@iarna,

I think this might have introduced a new bug (or maybe the bug was already there).  Using my original example of what should show up in `npm list` using npm 2.0.0:

```
npm-git-test@1.0.0 /Users/bdonovan/code/node/npm-git-test
├─┬ dummy-npm-bar@4.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-bar.git#575b86626745cda65c05da620ae1c64e8a34dee7)
│ ├── dummy-npm-buzz@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#fc6c1ebffccd5ef8755c833072c41be51448f2d6)
│ └── dummy-npm-foo@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-foo.git#8524863b7db0ab64eedf7a38c8af670d04865839)
├── dummy-npm-buzz@3.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#fc6c1ebffccd5ef8755c833072c41be51448f2d6)
└─┬ dummy-npm-foo@4.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-foo.git#295739950f3366d9ce668082748e80674670d605)
  └── dummy-npm-buzz@2.0.0 (git+ssh://git@github.com:BryanDonovan/dummy-npm-buzz.git#21673508ffed3584acb800421be7c4a337f4fe78)
```

And now, with 2.9.0, it's:

```
npm-git-test@1.0.0 /Users/bdonovan/code/node/npm-git-test
├─┬ dummy-npm-bar@4.0.0
│ └── dummy-npm-foo@3.0.0
├── dummy-npm-buzz@3.0.0
└── dummy-npm-foo@4.0.0
```
Note that `dummy-npm-buzz@2.0.0` is no longer listed.

**Comment by othiym23** [comment] 2015-05-01 01:43
@BryanDonovan If you look at d975aa08da5f0b473be008a298436e33625d2ac8, you'll see that a subsequent patch that I landed (63b79ccde092a9cb3b1f34abe43e1d2ba69c0dbf) tweaked the results to produce a tree exactly identical to your ideal tree, along with my reasoning about how all three of those result trees are equally valid (and one gets chosen over another due to the exigencies of the installer). Is my reasoning there incorrect? I think the current state (after 63b79ccde092a9cb3b1f34abe43e1d2ba69c0dbf) will always produce your first tree, but if it's incorrect for one or both of the other two trees to result, I can lock down that test.

More importantly, does npm HEAD fix the original problem you were seeing? I'm in the process of cutting this week's release, but there's still a little time for me to tweak things if there's a problem.

**Comment by iarna** [comment] 2015-05-01 02:17
@BryanDonovan The version published as 2.9.0 does not have this fixed. But if you install from `npm/npm` (which will install from github instead of the registry) then you'll get the fixes for this. Confusingly, this is also labeled as 2.9.0 but it's what's actually going to be the next version number.

**Comment by BryanDonovan** [comment] 2015-05-01 02:25
Oh, ok.  I thought it was strange that this was in 2.9.0 ... I didn't check carefully enough.  I'll try HEAD.

**Comment by BryanDonovan** [comment] 2015-05-01 02:37
Confirmed, HEAD looks good.  @othiym23 - yeah, I definitely agree with your reasoning.
