### ISSUE TITLE
git dependencies error with '-' in the revision name

### ISSUE THREAD

**Issue by luisrudge** [npm/npm#8359] opened 2015-05-26 00:41 UTC
Following this comment by @smikes: https://github.com/npm/npm/issues/6914#issuecomment-105342526

I'm having an issue while downloading a project with a dependency pointing to a github repo with `-` in the name.

Here are the logs:

```
λ npm install gulp-aspnet-k
npm ERR! git rev-list -n1 options-env: fatal: ambiguous argument 'options-env': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 options-env: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 options-env: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 options-env:
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-aspnet-k"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 options-env
npm ERR! fatal: ambiguous argument 'options-env': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\a\npm-debug.log
```

Here's the log file

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp-aspnet-k' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of c:\a\package.json
5 verbose readDependencies loading dependencies from c:\a\package.json
6 silly cache add args [ 'gulp-aspnet-k', null ]
7 verbose cache add spec gulp-aspnet-k
8 silly cache add parsed spec { raw: 'gulp-aspnet-k',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp-aspnet-k',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed gulp-aspnet-k@*
10 verbose addNamed "*" is a valid semver range for gulp-aspnet-k
11 silly addNameRange { name: 'gulp-aspnet-k', range: '*', hasData: false }
12 silly mapToRegistry name gulp-aspnet-k
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp-aspnet-k
16 verbose addNameRange registry:https://registry.npmjs.org/gulp-aspnet-k not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp-aspnet-k
18 verbose request no auth needed
19 info attempt registry request try #1 at 21:24:19
20 verbose request id 40f0153cb70c39e1
21 verbose etag "5JILA6EYY5EFMSCZASTWRADDD"
22 http request GET https://registry.npmjs.org/gulp-aspnet-k
23 http 304 https://registry.npmjs.org/gulp-aspnet-k
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 26 May 2015 00:24:22 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"5JILA6EYY5EFMSCZASTWRADDD"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-iad2120-IAD',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1432599862.478641,VS0,VE55',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/gulp-aspnet-k from cache
26 verbose get saving gulp-aspnet-k to C:\Users\luis\AppData\Roaming\npm-cache\registry.npmjs.org\gulp-aspnet-k\.cache.json
27 silly addNameRange number 2 { name: 'gulp-aspnet-k', range: '*', hasData: true }
28 silly addNameRange versions [ 'gulp-aspnet-k',
28 silly addNameRange   [ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '0.0.5' ] ]
29 silly addNamed gulp-aspnet-k@0.0.5
30 verbose addNamed "0.0.5" is a plain semver version for gulp-aspnet-k
31 silly cache afterAdd gulp-aspnet-k@0.0.5
32 verbose afterAdd C:\Users\luis\AppData\Roaming\npm-cache\gulp-aspnet-k\0.0.5\package\package.json not in flight; writing
33 verbose afterAdd C:\Users\luis\AppData\Roaming\npm-cache\gulp-aspnet-k\0.0.5\package\package.json written
34 silly install resolved [ { name: 'gulp-aspnet-k',
34 silly install resolved     version: '0.0.5',
34 silly install resolved     description: 'Gulp plugin for ASP.NET vNext',
34 silly install resolved     main: 'index.js',
34 silly install resolved     scripts: { test: 'mocha' },
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git://github.com/tugberkugurlu/gulp-aspnet-k.git' },
34 silly install resolved     keywords: [ 'aspnet', 'aspnetvnext', 'dotnet', 'gulp' ],
34 silly install resolved     author: { name: 'Tugberk Ugurlu' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     bugs: { url: 'https://github.com/tugberkugurlu/gulp-aspnet-k/issues' },
34 silly install resolved     homepage: 'https://github.com/tugberkugurlu/gulp-aspnet-k',
34 silly install resolved     dependencies:
34 silly install resolved      { 'gulp-shell': 'git://github.com/tugberkugurlu/gulp-shell.git#options-env',
34 silly install resolved        'gulp-util': '^3.0.1',
34 silly install resolved        lodash: '^2.4.1' },
34 silly install resolved     gitHead: '54a0ad37b268a54e150de7b00d5d1f5a03e8890d',
34 silly install resolved     _id: 'gulp-aspnet-k@0.0.5',
34 silly install resolved     _shasum: '75865fc4f5ea26e7211ea92d846a262e1d539383',
34 silly install resolved     _from: 'gulp-aspnet-k@*',
34 silly install resolved     _npmVersion: '2.5.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'tugberk', email: 'tugberkugurlu@gmail.com' },
34 silly install resolved     dist:
34 silly install resolved      { shasum: '75865fc4f5ea26e7211ea92d846a262e1d539383',
34 silly install resolved        tarball: 'http://registry.npmjs.org/gulp-aspnet-k/-/gulp-aspnet-k-0.0.5.tgz' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/gulp-aspnet-k/-/gulp-aspnet-k-0.0.5.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install gulp-aspnet-k@0.0.5 into c:\a
36 info installOne gulp-aspnet-k@0.0.5
37 verbose installOne of gulp-aspnet-k to c:\a not in flight; installing
38 verbose lock using C:\Users\luis\AppData\Roaming\npm-cache\_locks\gulp-aspnet-k-b5881b842609c10f.lock for c:\a\node_modules\gulp-aspnet-k
39 silly install write writing gulp-aspnet-k 0.0.5 to c:\a\node_modules\gulp-aspnet-k
40 verbose unbuild node_modules\gulp-aspnet-k
41 silly gentlyRm c:\a\node_modules\gulp-aspnet-k is being purged from base c:\a
42 verbose gentlyRm don't care about contents; nuking c:\a\node_modules\gulp-aspnet-k
43 verbose tar unpack C:\Users\luis\AppData\Roaming\npm-cache\gulp-aspnet-k\0.0.5\package.tgz
44 verbose tar unpacking to c:\a\node_modules\gulp-aspnet-k
45 silly gentlyRm c:\a\node_modules\gulp-aspnet-k is being purged
46 verbose gentlyRm don't care about contents; nuking c:\a\node_modules\gulp-aspnet-k
47 silly gunzTarPerm modes [ '777', '666' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm extractEntry .npmignore
50 silly gunzTarPerm extractEntry README.md
51 silly gunzTarPerm extractEntry LICENSE
52 silly gunzTarPerm extractEntry index.js
53 verbose write writing to c:\a\node_modules\gulp-aspnet-k\package.json
54 info preinstall gulp-aspnet-k@0.0.5
55 verbose readDependencies loading dependencies from c:\a\node_modules\gulp-aspnet-k\package.json
56 silly prepareForInstallMany adding gulp-shell@git://github.com/tugberkugurlu/gulp-shell.git#options-env from gulp-aspnet-k dependencies
57 silly prepareForInstallMany adding gulp-util@^3.0.1 from gulp-aspnet-k dependencies
58 silly prepareForInstallMany adding lodash@^2.4.1 from gulp-aspnet-k dependencies
59 verbose readDependencies loading dependencies from c:\a\node_modules\gulp-aspnet-k\package.json
60 silly cache add args [ 'gulp-shell@git://github.com/tugberkugurlu/gulp-shell.git#options-env',
60 silly cache add   null ]
61 verbose cache add spec gulp-shell@git://github.com/tugberkugurlu/gulp-shell.git#options-env
62 silly cache add args [ 'gulp-util@^3.0.1', null ]
63 verbose cache add spec gulp-util@^3.0.1
64 silly cache add parsed spec { raw: 'gulp-util@^3.0.1',
64 silly cache add   scope: null,
64 silly cache add   name: 'gulp-util',
64 silly cache add   rawSpec: '^3.0.1',
64 silly cache add   spec: '>=3.0.1 <4.0.0',
64 silly cache add   type: 'range' }
65 silly addNamed gulp-util@>=3.0.1 <4.0.0
66 verbose addNamed ">=3.0.1 <4.0.0" is a valid semver range for gulp-util
67 silly addNameRange { name: 'gulp-util', range: '>=3.0.1 <4.0.0', hasData: false }
68 silly mapToRegistry name gulp-util
69 silly mapToRegistry using default registry
70 silly mapToRegistry registry https://registry.npmjs.org/
71 silly mapToRegistry uri https://registry.npmjs.org/gulp-util
72 verbose addNameRange registry:https://registry.npmjs.org/gulp-util not in flight; fetching
73 silly cache add args [ 'lodash@^2.4.1', null ]
74 verbose cache add spec lodash@^2.4.1
75 silly cache add parsed spec { raw: 'lodash@^2.4.1',
75 silly cache add   scope: null,
75 silly cache add   name: 'lodash',
75 silly cache add   rawSpec: '^2.4.1',
75 silly cache add   spec: '>=2.4.1 <3.0.0',
75 silly cache add   type: 'range' }
76 silly addNamed lodash@>=2.4.1 <3.0.0
77 verbose addNamed ">=2.4.1 <3.0.0" is a valid semver range for lodash
78 silly addNameRange { name: 'lodash', range: '>=2.4.1 <3.0.0', hasData: false }
79 silly mapToRegistry name lodash
80 silly mapToRegistry using default registry
81 silly mapToRegistry registry https://registry.npmjs.org/
82 silly mapToRegistry uri https://registry.npmjs.org/lodash
83 verbose addNameRange registry:https://registry.npmjs.org/lodash not in flight; fetching
84 silly cache add parsed spec { raw: 'gulp-shell@git://github.com/tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add   scope: null,
84 silly cache add   name: 'gulp-shell',
84 silly cache add   rawSpec: 'git://github.com/tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add   spec: 'git://github.com/tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add   type: 'hosted',
84 silly cache add   hosted:
84 silly cache add    { type: 'github',
84 silly cache add      ssh: 'git@github.com:tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add      sshUrl: 'git+ssh://git@github.com/tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add      httpsUrl: 'git+https://github.com/tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add      gitUrl: 'git://github.com/tugberkugurlu/gulp-shell.git#options-env',
84 silly cache add      shortcut: 'github:tugberkugurlu/gulp-shell#options-env',
84 silly cache add      directUrl: 'https://raw.githubusercontent.com/tugberkugurlu/gulp-shell/options-env/package.json' } }
85 verbose addRemoteGit caching git://github.com/tugberkugurlu/gulp-shell.git#options-env
86 verbose addRemoteGit git://github.com/tugberkugurlu/gulp-shell.git#options-env is a repository hosted by github
87 silly tryClone cloning git://github.com/tugberkugurlu/gulp-shell.git#options-env via git://github.com/tugberkugurlu/gulp-shell.git#options-env
88 verbose tryClone git-github-com-tugberkugurlu-gulp-shell-git-bda5d09b not in flight; caching
89 verbose request uri https://registry.npmjs.org/gulp-util
90 verbose request no auth needed
91 info attempt registry request try #1 at 21:24:23
92 verbose etag "9G4Q5TFO4NIPNGW1V8I0JS9FD"
93 http request GET https://registry.npmjs.org/gulp-util
94 verbose request uri https://registry.npmjs.org/lodash
95 verbose request no auth needed
96 info attempt registry request try #1 at 21:24:23
97 verbose etag "DHD1FQ6IG489XALHD4W379C24"
98 http request GET https://registry.npmjs.org/lodash
99 info git [ 'config', '--get', 'remote.origin.url' ]
100 silly validateExistingRemote git://github.com/tugberkugurlu/gulp-shell.git#options-env remote.origin.url: git://github.com/tugberkugurlu/gulp-shell.git
101 verbose validateExistingRemote git://github.com/tugberkugurlu/gulp-shell.git#options-env is updating existing cached remote C:\Users\luis\AppData\Roaming\npm-cache\_git-remotes\git-github-com-tugberkugurlu-gulp-shell-git-bda5d09b
102 info git [ 'fetch', '-a', 'origin' ]
103 verbose updateRemote git fetch -a origin (git://github.com/tugberkugurlu/gulp-shell.git)
104 verbose setPermissions git://github.com/tugberkugurlu/gulp-shell.git#options-env skipping chownr on Windows
105 verbose resolveHead git://github.com/tugberkugurlu/gulp-shell.git#options-env original treeish: options-env
106 info git [ 'rev-list', '-n1', 'options-env' ]
107 error git rev-list -n1 options-env: fatal: ambiguous argument 'options-env': unknown revision or path not in the working tree.
107 error git rev-list -n1 options-env: Use '--' to separate paths from revisions, like this:
107 error git rev-list -n1 options-env: 'git <command> [<revision>...] -- [<file>...]'
108 http 304 https://registry.npmjs.org/gulp-util
109 silly get cb [ 304,
109 silly get   { date: 'Tue, 26 May 2015 00:24:23 GMT',
109 silly get     via: '1.1 varnish',
109 silly get     'cache-control': 'max-age=60',
109 silly get     etag: '"9G4Q5TFO4NIPNGW1V8I0JS9FD"',
109 silly get     age: '59',
109 silly get     connection: 'keep-alive',
109 silly get     'x-served-by': 'cache-iad2133-IAD',
109 silly get     'x-cache': 'HIT',
109 silly get     'x-cache-hits': '1',
109 silly get     'x-timer': 'S1432599863.607058,VS0,VE0',
109 silly get     vary: 'Accept' } ]
110 verbose etag https://registry.npmjs.org/gulp-util from cache
111 verbose get saving gulp-util to C:\Users\luis\AppData\Roaming\npm-cache\registry.npmjs.org\gulp-util\.cache.json
112 silly addNameRange number 2 { name: 'gulp-util', range: '>=3.0.1 <4.0.0', hasData: true }
113 silly addNameRange versions [ 'gulp-util',
113 silly addNameRange   [ '0.0.1',
113 silly addNameRange     '1.0.0',
113 silly addNameRange     '1.1.0',
113 silly addNameRange     '1.1.1',
113 silly addNameRange     '1.2.0',
113 silly addNameRange     '1.3.0',
113 silly addNameRange     '2.0.0',
113 silly addNameRange     '2.1.1',
113 silly addNameRange     '2.1.2',
113 silly addNameRange     '2.1.3',
113 silly addNameRange     '2.1.4',
113 silly addNameRange     '2.2.0',
113 silly addNameRange     '2.2.1',
113 silly addNameRange     '2.2.2',
113 silly addNameRange     '2.2.3',
113 silly addNameRange     '2.2.5',
113 silly addNameRange     '2.2.6',
113 silly addNameRange     '2.2.7',
113 silly addNameRange     '2.2.8',
113 silly addNameRange     '2.2.9',
113 silly addNameRange     '2.2.10',
113 silly addNameRange     '2.2.11',
113 silly addNameRange     '2.2.12',
113 silly addNameRange     '2.2.13',
113 silly addNameRange     '2.2.14',
113 silly addNameRange     '2.2.15',
113 silly addNameRange     '2.2.16',
113 silly addNameRange     '2.2.17',
113 silly addNameRange     '2.2.18',
113 silly addNameRange     '2.2.19',
113 silly addNameRange     '2.2.20',
113 silly addNameRange     '3.0.0',
113 silly addNameRange     '3.0.1',
113 silly addNameRange     '3.0.2',
113 silly addNameRange     '3.0.3',
113 silly addNameRange     '3.0.4' ] ]
114 silly addNamed gulp-util@3.0.4
115 verbose addNamed "3.0.4" is a plain semver version for gulp-util
116 http 304 https://registry.npmjs.org/lodash
117 silly get cb [ 304,
117 silly get   { date: 'Tue, 26 May 2015 00:24:23 GMT',
117 silly get     via: '1.1 varnish',
117 silly get     'cache-control': 'max-age=60',
117 silly get     etag: '"DHD1FQ6IG489XALHD4W379C24"',
117 silly get     age: '47',
117 silly get     connection: 'keep-alive',
117 silly get     'x-served-by': 'cache-iad2141-IAD',
117 silly get     'x-cache': 'HIT',
117 silly get     'x-cache-hits': '2',
117 silly get     'x-timer': 'S1432599863.626929,VS0,VE0',
117 silly get     vary: 'Accept' } ]
118 verbose etag https://registry.npmjs.org/lodash from cache
119 verbose get saving lodash to C:\Users\luis\AppData\Roaming\npm-cache\registry.npmjs.org\lodash\.cache.json
120 silly cache afterAdd gulp-util@3.0.4
121 verbose afterAdd C:\Users\luis\AppData\Roaming\npm-cache\gulp-util\3.0.4\package\package.json not in flight; writing
122 verbose afterAdd C:\Users\luis\AppData\Roaming\npm-cache\gulp-util\3.0.4\package\package.json written
123 silly addNameRange number 2 { name: 'lodash', range: '>=2.4.1 <3.0.0', hasData: true }
124 silly addNameRange versions [ 'lodash',
124 silly addNameRange   [ '0.1.0',
124 silly addNameRange     '0.2.0',
124 silly addNameRange     '0.2.1',
124 silly addNameRange     '0.2.2',
124 silly addNameRange     '0.3.0',
124 silly addNameRange     '0.3.1',
124 silly addNameRange     '0.3.2',
124 silly addNameRange     '0.4.0',
124 silly addNameRange     '0.4.1',
124 silly addNameRange     '0.4.2',
124 silly addNameRange     '0.5.0-rc.1',
124 silly addNameRange     '0.5.0',
124 silly addNameRange     '0.5.1',
124 silly addNameRange     '0.5.2',
124 silly addNameRange     '0.6.0',
124 silly addNameRange     '0.6.1',
124 silly addNameRange     '0.7.0',
124 silly addNameRange     '0.8.0',
124 silly addNameRange     '0.8.1',
124 silly addNameRange     '0.8.2',
124 silly addNameRange     '0.9.0',
124 silly addNameRange     '0.9.1',
124 silly addNameRange     '0.9.2',
124 silly addNameRange     '0.10.0',
124 silly addNameRange     '1.0.0-rc.1',
124 silly addNameRange     '1.0.0-rc.2',
124 silly addNameRange     '1.0.0-rc.3',
124 silly addNameRange     '1.0.0',
124 silly addNameRange     '1.0.1',
124 silly addNameRange     '1.1.0',
124 silly addNameRange     '1.1.1',
124 silly addNameRange     '1.2.0',
124 silly addNameRange     '1.2.1',
124 silly addNameRange     '1.3.0',
124 silly addNameRange     '1.3.1',
124 silly addNameRange     '2.0.0',
124 silly addNameRange     '2.1.0',
124 silly addNameRange     '2.2.0',
124 silly addNameRange     '2.2.1',
124 silly addNameRange     '2.3.0',
124 silly addNameRange     '2.4.0',
124 silly addNameRange     '2.4.1',
124 silly addNameRange     '3.0.0',
124 silly addNameRange     '3.0.1',
124 silly addNameRange     '3.1.0',
124 silly addNameRange     '3.2.0',
124 silly addNameRange     '3.3.0',
124 silly addNameRange     '3.3.1',
124 silly addNameRange     '3.4.0',
124 silly addNameRange     '3.5.0',
124 silly addNameRange     '3.6.0',
124 silly addNameRange     '1.0.2',
124 silly addNameRange     '3.7.0',
124 silly addNameRange     '2.4.2',
124 silly addNameRange     '3.8.0',
124 silly addNameRange     '3.9.0',
124 silly addNameRange     '3.9.1',
124 silly addNameRange     '3.9.2' ] ]
125 silly addNamed lodash@2.4.2
126 verbose addNamed "2.4.2" is a plain semver version for lodash
127 silly cache afterAdd lodash@2.4.2
128 verbose afterAdd C:\Users\luis\AppData\Roaming\npm-cache\lodash\2.4.2\package\package.json not in flight; writing
129 verbose afterAdd C:\Users\luis\AppData\Roaming\npm-cache\lodash\2.4.2\package\package.json written
130 verbose about to build c:\a\node_modules\gulp-aspnet-k
131 verbose unlock done using C:\Users\luis\AppData\Roaming\npm-cache\_locks\gulp-aspnet-k-b5881b842609c10f.lock for c:\a\node_modules\gulp-aspnet-k
132 verbose stack Error: Command failed: git -c core.longpaths=true rev-list -n1 options-env
132 verbose stack fatal: ambiguous argument 'options-env': unknown revision or path not in the working tree.
132 verbose stack Use '--' to separate paths from revisions, like this:
132 verbose stack 'git <command> [<revision>...] -- [<file>...]'
132 verbose stack
132 verbose stack     at ChildProcess.exithandler (child_process.js:751:12)
132 verbose stack     at ChildProcess.emit (events.js:110:17)
132 verbose stack     at maybeClose (child_process.js:1015:16)
132 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
133 verbose cwd c:\a
134 error Windows_NT 6.3.9600
135 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-aspnet-k"
136 error node v0.12.4
137 error npm  v2.10.1
138 error code 128
139 error Command failed: git -c core.longpaths=true rev-list -n1 options-env
139 error fatal: ambiguous argument 'options-env': unknown revision or path not in the working tree.
139 error Use '--' to separate paths from revisions, like this:
139 error 'git <command> [<revision>...] -- [<file>...]'
140 error If you need help, you may report this error at:
140 error     <https://github.com/npm/npm/issues>
141 verbose exit [ 1, true ]
142 verbose unbuild node_modules\gulp-aspnet-k
143 info preuninstall gulp-aspnet-k@0.0.5
144 info uninstall gulp-aspnet-k@0.0.5
145 verbose unbuild rmStuff gulp-aspnet-k@0.0.5 from c:\a\node_modules
146 info postuninstall gulp-aspnet-k@0.0.5
147 silly gentlyRm c:\a\node_modules\gulp-aspnet-k is being purged from base c:\a
148 verbose gentlyRm don't care about contents; nuking c:\a\node_modules\gulp-aspnet-k
149 silly vacuum-fs purging c:\a\node_modules\gulp-aspnet-k
150 silly vacuum-fs removing c:\a\node_modules
151 silly vacuum-fs finished vacuuming up to c:\a
```

Here are my versions:

```
λ npm -v
2.10.1
λ node -v
v0.12.4
λ git --version
git version 1.9.4.msysgit.0
```

**Comment by smikes** [comment] 2015-05-26 00:45
Could you please post the excerpt of your `package.json` file that defines the dependency on tugberkugurlu/gulp-shell ?

**Comment by smikes** [comment] 2015-05-26 00:46
I can reproduce this on windows with

```
$ npm i https://github.com/tugberkugurlu/gulp-shell#option-env
npm ERR! git rev-list -n1 option-env: fatal: ambiguous argument 'option-env': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 option-env: Use '--' to separate paths from revisions
npm ERR! git rev-list -n1 option-env:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "https://github.com/tugberkugurlu/gulp-shell#option-env"
npm ERR! node v0.10.36
npm ERR! npm  v2.10.1
npm ERR! code 128

```

**Comment by luisrudge** [comment] 2015-05-26 00:51
@smikes actually, my project depends on `gulp-aspnet-k`, not on `gulp-shell`.

**Comment by smikes** [comment] 2015-05-26 00:54
Okay, but somewhere someone is asking for a dependency on `gulp-shell#option-env` which is confusing to git.  I will have to look into this tomorrow, my time window just ended.

**Comment by luisrudge** [comment] 2015-05-26 00:57
Yeah. Ok, man. Thanks!

**Comment by luisrudge** [comment] 2015-05-28 17:22
Any news on this? This is really affecting me :(

**Comment by smikes** [comment] 2015-05-28 18:06
Will be able to look at it again tonight; sorry, most of the npm crew are at jsconf this week

**Comment by luisrudge** [comment] 2015-05-28 18:13
Ahhh, no problem. Thanks!

**Comment by othiym23** [comment] 2015-05-28 19:27
@luisrudge Sorry it took me a couple days to get to you, as @smikes said, the CLI team's been doing a lot of traveling over the last week and are a little distracted as a result. I pulled down `gulp-shell`, and it appears that the problem is that it has no branch or tag named `option-env`. I think this is either a bug in `gulp-aspnet-k`, or possibly the maintainer of `gulp-shell` has some branches in their local tree that they haven't pushed to GitHub. The error message could stand to be easier to decipher, but this looks like a problem with `gulp-aspnet-k`, not npm.

**Comment by luisrudge** [comment] 2015-05-28 19:51
Oh, ok. thanks!

**Comment by othiym23** [comment] 2015-06-18 00:02
I'm pretty sure we nailed this one down, so I'm closing this as resolved. Let me know if I got that wrong, @luisrudge.

**Closed by othiym23** 2015-06-18 00:02 UTC
Labels: git, support, windows
