### ISSUE TITLE
npm install bower error

### ISSUE THREAD

**Issue by renshaoping** [npm/npm#14448] opened 2016-10-28 03:11 UTC
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by renshaoping** [comment] 2016-10-28 03:17
I install bower  but something goes wrong after I have installed node.js in wondows 7
C:\Users\kim>npm install -g yo grunt-cli bower
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "grunt-cli" "bow
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\kim\AppData\Local\Temp\npm-550
bc\registry.npmjs.org\bower\-\bower-1.7.9.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   1ab43c2aee482bd8fef45149c7a82d444bf58f7f
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kim\npm-debug.log

**Comment by megamit** [comment] 2016-10-28 14:26
I have this problem aswell. I am encountering this with several popular packages namely this bowser and connect. I can work around npm failing by directly grabbing the release i need from the packages github repo but its a time consuming workaround

**Comment by legodude17** [comment] 2016-10-28 14:32
Try running `npm cache clean` and retrying.

**Comment by zkat** [comment] 2016-12-09 00:34
Closing as a duplicate of https://github.com/npm/npm/issues/14626

**Closed by zkat** 2016-12-09 00:34 UTC
Labels: network, shasum, support
