### ISSUE TITLE
npm@3.5.0 should not be trying to install modules that arch/os say are incompatible

### ISSUE THREAD

**Issue by rstoenescu** [npm/npm#10768] opened 2015-12-09 20:39 UTC
A reference to https://github.com/npm/npm/issues/8921.
Was fixed with npm 3.3.12, now it doesn't works again, with npm 3.5.0

**Comment by othiym23** [comment] 2015-12-09 22:27
Do you have an example of how to reproduce it? We have a [few](https://github.com/npm/npm/blob/master/test/tap/check-cpu-reqs.js) [test](https://github.com/npm/npm/blob/master/test/tap/check-engine-reqs.js) [cases](https://github.com/npm/npm/blob/master/test/tap/check-os-reqs.js) around this functionality that are still passing, so it seems we've overlooked something.

**Comment by rstoenescu** [comment] 2015-12-09 22:55
Test case: install quasar-framework package on a Linux machine.

Seems like fsevents is not supported on Linux (and it shouldn't, since it's MacOS specific):
``` bash
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.5
```

**Comment by Plummat** [comment] 2015-12-10 16:47
getting this with fsevents@1.0.5, which is also unfortunately busting our CI builds.

**Comment by rstoenescu** [comment] 2015-12-15 14:50
Any progress on this one? For reproduction, use a VM with Linux (most likely Windows too) and try to install [quasar-framework](https://www.npmjs.com/package/quasar-framework).

Thanks!

**Comment by yonatanmn** [comment] 2015-12-16 09:38
same happens to me : 
windows,
npm@3.5.2, node@4.2.2
git clone https://github.com/facebook/react-native.git
npm install

````
 fsevents@1.0.5 install C:\projects\react-native\node_modules\fsevents
> node-pre-gyp install --fallback-to-build

Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\projects\\react-native\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-x64\\fse.node" "--module_name=fse" "--module_path=C:\\projects\\react-native\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-x64"
gyp ERR! cwd C:\projects\react-native\node_modules\fsevents
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\projects\react-native\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64\fse.node --module_name=fse --module_path=C:\projects\react-native\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\react-native\node_modules\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\react-native\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects\react-native\node_modules\fsevents
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.15
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\projects\react-native\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64\fse.node --module_name=fse --module_path=C:\projects\react-native\node_modules\fsevents\lib\binding\Release\node-v46-win32-x64' (1)
npm WARN install:fsevents@1.0.5 fsevents@1.0.5 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fsevents@1.0.5 Exit status 1
````

**Comment by gemina** [comment] 2015-12-21 10:20
same here on Ubuntu 14.04...

**Comment by joerideg** [comment] 2015-12-28 10:05
Same here on Linux Mint
node: v5.3.0
npm: 3.5.2

**Comment by Luukuton** [comment] 2016-01-04 13:33
Same with Debian 8.2.

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "fsevents"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

**Comment by AkessonHenrik** [comment] 2016-01-04 13:43
Same problem for me with some packages like mysql, sqlite, sequelize, etc.

```
Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by gnomesoftuk** [comment] 2016-01-04 16:04
Exact same issue here on Ubuntu 14.04.3 LTS

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

**Comment by codingquark** [comment] 2016-01-18 05:30
@gnomesoftuk I'm unable to fix it by rolling back 3.3.12

Node versions tried: 4.2.4, 5.4.1
npm versions tried: 3.3.12, 3.5.2
OS: Ubuntu 14.04 LTS

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by diegoarcega** [comment] 2016-01-18 19:26
Same

45 error Linux 4.2.0-23-generic
46 error argv "node" "/usr/local/bin/npm" "install" "fsevents"
47 error node v0.10.25
48 error npm  v3.5.3
49 error code EBADPLATFORM
50 error notsup Not compatible with your operating system or architecture: fsevents@1.0.6
51 error notsup Valid OS:    darwin
51 error notsup Valid Arch:  any
51 error notsup Actual OS:   linux
51 error notsup Actual Arch: x64
52 verbose exit [ 1, true ]

**Comment by aush** [comment] 2016-01-19 02:31
windows 10
npm: 3.5.2

    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

**Comment by anaibol** [comment] 2016-01-20 14:21
:+1: same on Linux, npm 3.5.3

**Comment by bmulcahy** [comment] 2016-01-20 17:04
same 
windows 7   
node: 5.3.0  
npm: 3.5.4  

rolling back to 3.3.12 fixes it

**Comment by shercoder** [comment] 2016-01-20 18:26
Same:
OS: Linux
Arch: x64
node: 5.1.1
npm: 3.3.12

```
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by bmulcahy** [comment] 2016-01-20 18:29
For a test case try to install ampersand-app (where I got my error)

**Comment by roman-io** [comment] 2016-01-24 16:11
If I delete the `node_modules` folder and install tested package again, the error doesn't show up.
Tested package is `semantic-ui`

**Comment by SergeyKhval** [comment] 2016-01-25 08:59
same here. fails to install `gulp-sass`
OS: Windows 7
node: 4.2.6
npm: 3.5.3

**Comment by anonimusprogramus** [comment] 2016-01-26 05:39
Same here.
OS: Arch Linux 64bit
node: 5.5.0
npm: 3.5.3

step #1 git clone https://github.com/vuejs/vue-hackernews.git
step #2 npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

**Comment by obust** [comment] 2016-01-26 13:00
same here
ubuntu: 15.10
node: 5.5.0
npm: 3.5.3

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by javierav** [comment] 2016-01-27 20:25
Same trying to install `pm2`:

* OS: Ubuntu 14.04.3 LTS
* node: v0.10.41
* npm: 3.5.3

```
npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by jdiez17** [comment] 2016-01-29 19:14
Same problem here.

```
npm ERR! Linux 4.3.3-3-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "fsevents"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

```

**Comment by Nicolab** [comment] 2016-01-31 11:47
Same problem here: 

```
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

NPM 3.5.3
Node v5.1.1

**Comment by treeder** [comment] 2016-02-01 18:42
@othiym23 you can reproduce with Docker easily:

```sh
git clone https://github.com/vuejs/vue-hackernews.git
cd vue-hackernews
docker run --rm -it -v "$PWD":/app -w /app iron/node:dev npm install
```

You'll get the error.

**Comment by palutz** [comment] 2016-02-08 13:53
Same here:

Ubuntu 15.10
npm 2.14.12
node 4.2.6 then updated to 5.4.1 but nothing changed

**Comment by danyim** [comment] 2016-02-10 02:43
Rolled back to node 5.2.0 on nvm comes with npm 3.3.12, which fixes the problem

**Comment by atesgoral** [comment] 2016-02-12 16:34
I confirm that rolling back to 5.2.0 helps. (Use nvm and `nvm install 5.2.0`)

**Comment by Wildhoney** [comment] 2016-02-12 17:50
Can also confirm it works on `v5.2.0`. Any roadmap for fixing this in `v5.6.x`?

**Comment by jan-zajic** [comment] 2016-02-15 21:00
same on windows 8:
npm WARN optional Skipping failed optional dependency /brunch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
node v5.6.0
npm 3.6.0

**Comment by maximilianschmitt** [comment] 2016-02-16 10:19
I have the same issue: node v5.6.0, npm 3.6.0

**Comment by benjoox** [comment] 2016-02-16 23:44
Same issue for me when installing any package.
windows 8.1 
node v5.6.0
npm 3.6.0

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
` npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7`

**Comment by idbentley** [comment] 2016-02-16 23:47
@othiym23 we haven't heard from you or anyone at npm in 2 months.  This is pretty clearly reproducable, since myself and the dozens of other people here have all run into it.  The resolution of rolling back is not super satisfactory, though it has allowed me to proceed.

**Comment by joshmanders** [comment] 2016-02-17 00:05
Getting same issue on debian in a docker container.

**Comment by sqram** [comment] 2016-02-17 05:03
Same issue here. On Arch.

node 5.6.0
npm 3.7.2

**Comment by bhanuV** [comment] 2016-02-18 09:21
Having a similar issue. 

node 4.2.1
npm 3.6.0
Ubuntu 14.04

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN npm@1.0.0 No repository field.

**Comment by lukaszbaranski** [comment] 2016-02-19 08:10
Same issue for me when installing any package.

Windows 10 v.1511, OS-version: 10586.104 (64)
npm version:
{ 'angularjs-testing-quick-start': '1.0.0',
  npm: '3.7.3',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.3.1',
  openssl: '1.0.2f',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7

**Comment by bokideckonja** [comment] 2016-02-19 12:06
I have the same issue trying to install angular2-quickstart example from angular2.io

node v5.6.0
npm v3.6.0
```

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
...
npm ERR! Windows_NT 10.0.10586
```

**Comment by sfbaltaci** [comment] 2016-02-19 21:03
Same problem on Debian when installing pm2 via npm, fsevents fails

node v5.6.0
npm 3.6.0

`$ sudo npm i -g pm2
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/lib
└─┬ pm2@1.0.1 
  └── ikt@0.0.0  (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)

npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7`

**Comment by thohoh** [comment] 2016-02-20 13:27
ubuntu 14.04
node v5.6.0
npm 3.6.0

` npm install karma-ng-html2js-preprocessor --save-dev
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN noterious@0.0.0 No license field.
`

**Comment by ifeedmonsters** [comment] 2016-02-20 14:25
Any word on a fix? Same thing happens to me on Windows 10.

**Comment by defyjoy** [comment] 2016-02-20 15:09
Same here --
Windows 7 


npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm ERR! code 1

**Comment by franz-josef-kaiser** [comment] 2016-02-21 13:30
Same on Docker-Machine on OS X

Node: 5.6
OS: Alpine Linux 3.3

```shell
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
```

**Comment by mikemaccana** [comment] 2016-02-21 14:07
Hey I think this got fixed in 3.7!!! 😃

     npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
     npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7

As @franz-josef-kaiser mentioned, **this is a warning now: it won't error out** and you can happily install. 

     $ npm --version
     3.7.3

Yaaay 🎉

**Comment by franz-josef-kaiser** [comment] 2016-02-21 16:54
> is this better as an 'INFO' rather than a 'WARN'?

@mikemaccana If it is (a) not needed and (b) just an information that the package was skipped, `INFO` is the way to go.

**Comment by dikiaap** [comment] 2016-02-22 04:55
@mikemaccana I think will perfect for mark as warn and bug.

**Comment by mikemaccana** [comment] 2016-02-22 08:38
@dikiaap Weird, it's fine for me: I'm getting WARN (not ERR) on node 4.3.1.

**Comment by dikiaap** [comment] 2016-02-22 10:24
@mikemaccana Im using npm 3.7.3.

**Comment by mikemaccana** [comment] 2016-02-22 11:32
@dikiaap Weird. I'm using the same versions of both npm and node. Can I confirm you're getting ERR, not WARN?

**Comment by dikiaap** [comment] 2016-02-22 12:07
@mikemaccana I get warn, how do you fix that?

**Comment by mikemaccana** [comment] 2016-02-22 12:08
@dikiaap OK then you don't have the problem. Scroll up to 

# If you get a WARN and are worried this bug affects you

and read it.

**Comment by cagils** [comment] 2016-02-22 12:11
I too think it would be better as an INFO, not a WARN.

**Comment by mikemaccana** [comment] 2016-02-22 12:14
Yep. Just filed a separate bug bug for it. 

Since the 'ERR' reported in this issue (and subsequent npm exiting) seems to be resolved, discussions on whether to make the somewhat scary 'WARN' into an 'ERR' are in #11632

**Comment by dikiaap** [comment] 2016-02-22 12:18
Ok, hope fixed for next update
https://github.com/npm/npm/milestones

**Comment by hansiemithun** [comment] 2016-02-26 07:43
Same error, i have posted my question in stackoverflow as well. http://stackoverflow.com/questions/35644708/karma-unmet-dependencies
Please help, what need to be done for this quick fix

**Comment by dikiaap** [comment] 2016-02-26 08:01
Try Node 4.3.1, many commit there.
https://github.com/nodejs/node/commit/ef37a465c536ec3e7d9d4d86f98003a156abf3bb

**Comment by bokideckonja** [comment] 2016-02-26 08:29
Following steps solved the problem for me:
1. update npm to 3.7.3. 
2. disable antivirus (even the default Windows defender)

**Comment by hansiemithun** [comment] 2016-02-26 09:06
@bokideckonja , i cant disable antivirus as i am working in corporate office. It cant be done, that would not be the solution for me unfortunately

**Comment by rstoenescu** [comment] 2016-02-26 10:58
@hansiemithun Install npm 3.3.12 and it will work.

**Comment by mikemaccana** [comment] 2016-02-26 12:02
@hansiemithun you don't have any errors. See http://stackoverflow.com/questions/35644708/karma-unmet-dependencies/35651191

**Comment by mikemaccana** [comment] 2016-02-26 12:03
Quick reminder to all: if you haven't seen it yet, scroll up and read:

# If you get a WARN and are worried this bug affects you

above.

**Comment by franz-josef-kaiser** [comment] 2016-02-26 12:38
@mikemaccana you should really stop sticking bold headlines into peoples faces. That never works out.

![tb;cr – Too bold; Can't read](https://cloud.githubusercontent.com/assets/387666/13352537/2a5f6d3e-dc8e-11e5-808a-ac2df76c099f.gif)

**Comment by mikemaccana** [comment] 2016-02-26 14:31
@franz-josef-kaiser It'd h1 because I'm helping people and I want them to see it. DBAA.

**Comment by Wildhoney** [comment] 2016-02-26 14:34
`h2`s are less <h2>controversial</h2>.

**Comment by dikiaap** [comment] 2016-02-26 23:01
<h1>Calm down. I sell orange, offer 50% discount !!</h1>

**Comment by kangarooo** [comment] 2016-03-09 15:53
Had Chrome repo with chrome installation and with that i got nore 0.10.25. Also maybe old npm cause 
student@student-Web-Frontend:~/proangular/angular$ npm install webpack
npm WARN prefer global node-deb@0.1.10 should be installed with -g
myfacebook@1.0.0 /home/student/proangular/angular
├── angular@1.5.0 
├── angular-aria@1.5.0 
├── angular-material@1.0.6 
├── angular-messages@1.5.0  extraneous
├── bootstrap@3.3.6 
├── node-deb@0.1.10  extraneous
└── webpack-dev-server@1.14.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN myfacebook@1.0.0 No description

student@student-Web-Frontend:~/proangular/angular$ npm install fsevents
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/home/student/.npm-global/bin/npm" "install" "fsevents"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.0
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/student/proangular/angular/npm-debug.log


I have UBUNTU 15.10

**Comment by freddy24** [comment] 2016-03-10 06:32
@yonatanmn have you solved this problem?I got the same problem as you

**Comment by thilinamgit** [comment] 2016-03-11 08:19
Same kind of issues occurring on,
Node: v0.10.42
NPM: 3.7.3
-----------------------------------------------------------------------------
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
Updating Angular UI Bootstrap Components
npm WARN angular-ui-bootstrap@0.12.0 No repository field.

**Comment by MichelBakker** [comment] 2016-03-11 08:41
Same here:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.8.2
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/~/node_modules/.bin/acorn'

**Comment by WhatFreshHellIsThis** [comment] 2016-03-11 18:52
Why does it show *any* message at all on a non OSX OS if it's completely irrelevant to a non OSX user?  This just seems like something that should go away.

**Comment by kimtn-bitmark** [comment] 2016-03-14 23:46
@kangarooo did you resolve your problem. The same here

```
npm ERR! argv "/home/vagrant/.nvm/versions/node/v5.8.0/bin/node" "/home/vagrant/.nvm/versions/node/v5.8.0/bin/npm" "install" "fsevents"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

ubuntu 15.10

**Comment by aaron9527** [comment] 2016-03-15 07:14
Same:
```
vagrant@debian-8:~$ npm -v
3.7.3
vagrant@debian-8:~$ node -v
v5.8.0
npm WARN optional Skipping failed optional dependency /reapp/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8

```

**Comment by aquartier** [comment] 2016-03-15 07:50
Same problem here : (

```
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "fsevents"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Comment by mikemaccana** [comment] 2016-03-15 10:07
@franz-josef-kaiser See why now? 50% of folk here haven't read the thread. Anyway I'm out *unsubscribes*.

**Comment by franz-josef-kaiser** [comment] 2016-03-15 11:58
@mikemaccana well, that one we agree. _unsubscribe_

**Comment by WhatFreshHellIsThis** [comment] 2016-03-15 15:20
@mikemaccana  are you criticizing people for reporting this error that really should not be shown to the user in the first place?  What difference does it make if it's not a real problem and just cosmetic?  It's still an issue and it's still not resolved and that's a bit mystifying but reports will continue until it is.

**Comment by WhatFreshHellIsThis** [comment] 2016-03-15 15:21
Surely the "needs repro" label can be removed now?

**Comment by joshmanders** [comment] 2016-03-15 15:27
@mikemaccana That doesn't fix it for everyone. npm uses the `npmlog` module for logging warnings and errors, the module by DEFAULT logs to `stderr` which in MY case, causes things that check for messages on `stderr` and errors out, such as Docker is a problem. Your "cosmetic" solution isn't a one size fits all. So stop saying the problem is fixed when it clearly isn't.

**Comment by GitMiester** [comment] 2016-03-16 09:31
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE

**Comment by mikemaccana** [comment] 2016-03-16 12:52
@WhatFreshHellIsThis 

> are you criticizing people for reporting this error that really should not be shown to the user in the first place? 

No. There is no reason anyone would think that. 

> What difference does it make if it's not a real problem and just cosmetic? 

Because they're separate behaviours - one stops installation the other doesn't - and the WARN is (and should be) a separate bug.

**Comment by WhatFreshHellIsThis** [comment] 2016-03-16 15:15
@mikemaccana I think you need to re-read the initial reported case in this bug here and you need to consider retracting bug #11632 because it makes no sense to report anything to anyone when it doesn't apply to their operating system.  This case already has a proper request and will fix the problem in a correct manner.  Reporting completely irrelevant information is still reporting completely irrelevant information, it's better that install doesn't fail yes, but any seasoned developer knows you don't show irrelevant confusing information to users, it's a recipe for more bug reports and more hassle all around.

**Comment by burzum** [comment] 2016-03-17 08:34
This happens as well for me with NodeJS 5.8.0, Npm 3.7.3 on 14.04.1-Ubuntu.

**Comment by Cardoso222** [comment] 2016-03-17 11:51
Same here, NodeJS 5.8.0, NPM 3.7.3 on 14.04 ubuntu.

**Comment by kfrost89** [comment] 2016-03-17 18:08
Same issue on Arch Linux. NodeJS 5.9.0 and NPM 3.8.1

**Comment by mikemaccana** [comment] 2016-03-17 18:15
@WhatFreshHellIsThis you just said 'it makes no sense to report anything to anyone when it doesn't apply to their operating system' - that's what https://github.com/npm/npm/issues/11632 is there to fix.

**Comment by WhatFreshHellIsThis** [comment] 2016-03-17 19:05
@mikemaccana I stand by what I said, if you don't want to hear it or think about it that's your call.

**Comment by othiym23** [comment] 2016-03-17 21:08
There are 83 comments on this issue now, and I think it long ago passed the point of diminishing returns. The actionable piece of this is preserved in #11632, and if there are other pieces of this that users would like to see addressed, please file new issues. Thanks to all for their time!

**Closed by othiym23** 2016-03-17 21:08 UTC
Labels: bug, needs-repro
