### ISSUE TITLE
npm update --save creates unwanted entry in package.json

### ISSUE THREAD

**Issue by devrafalko** [npm/npm#16554] opened 2017-05-07 03:49 UTC
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm update --save` does not recognize whether the packages from `package.json` are stored as `dependency` or `devDependency`. Let's consider, that I have outdated **Lodash** package as `devDependency` and outdated **jquery** package as `dependency`. 

```javascript
  "devDependencies": {
    "lodash": "^4.8.0"
  },
  "dependencies": {
    "jquery": "^3.0.0"
  }
```

When I run `npm update --save` I expect (comparing how `npm install` behaves) that it will:
* update **Lodash**
* update **jquery**
* update the version entry of **jquery** `dependency` in `package.json` file.

```javascript
  "devDependencies": {
    "lodash": "^4.8.0"
  },
  "dependencies": {
    "jquery": "^3.2.1"
  }
```

What it really does:
* updates **Lodash**
* updates **jquery**
* updates the version entry of **jquery** `dependency` in `package.json` file.
* creates new entry of **Lodash** as `dependency` in `package.json` file.

```javascript
  "devDependencies": {
    "lodash": "^4.8.0"
  },
  "dependencies": {
    "jquery": "^3.2.1",
    "lodash": "^4.17.4" //?????
  }
```

#### How can the CLI team reproduce the problem?

Due to how `npm install`'s arguments work:

Implement `--production` argument to update only `dependencies` packages
Implement `--only={prod|dev}` argument to update either `dependencies` or `devDependencies` packages
Implement `--save` argument to update `dependencies` entry in `package.json` file
Implement `--save-dev` argument to update `devDependencies` entry in `package.json` file

### supporting information:

 - `npm -v` prints: 4.5.0
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 Pro x64
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2017-05-07 14:49
Duplicate of https://github.com/npm/npm/issues/10531?

**Comment by zkat** [comment] 2017-05-17 08:04
Indeed a duplicate. Also something that's slated to be fixed with `npm5` (in fact, it's the next thing on my docket so it'll probably be fixed by the end of this week). Closing!

**Closed by zkat** 2017-05-17 08:04 UTC
