### ISSUE TITLE
Can't install express-generator

### ISSUE THREAD

**Issue by spencerjsimpson** [npm/npm#14392] opened 2016-10-23 20:36 UTC
#### I'm opening this issue because:

  - I am trying to install the express-generator, but I keep getting errors

#### What's going wrong?

- I get some error that says "uid must be an unassigned int"

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment] 2016-10-23 20:37
Sounds like a duplicate of https://github.com/npm/npm/issues/13918.

**Closed by KenanY** 2016-10-23 20:37 UTC
