### ISSUE TITLE
Allow "Private" license in npm init

### ISSUE THREAD

**Issue by tracker1** [npm/npm#8542] opened 2015-06-11 22:08 UTC
It would be nice, if one could enter "private", "internal" or something similar during npm init for private/internal package.json initialization... probably also setting `private:true` in the `package.json` file.

**Comment by jandrieu** [comment] 2015-06-13 17:33
@tracker1 tracker1 This is a continuation of issue https://github.com/npm/npm/issues/8291 .

I have the same issue. In most of my development, my modules simply don't have a license. The LicenseRef-LICENSE mechanism as documented in https://github.com/npm/npm/blob/d27d647ee0685b3ca3dd0cd344a267017113a9a9/doc/files/package.json.md#license is a viable work around, except that it forces me to fabricate a license where none is ever intended.

"Private" or "NONE" or "NOASSERTION" or false should be a valid option. FWIW, I used to directly put in a (c) notice in the license field and I was ok with that 

Related to https://github.com/npm/npm/issues/8557

**Comment by othiym23** [comment] 2015-06-17 23:41
Closing as a duplicate of #8291 / #8557 – being able to say `NONE` or something similar (spelling as yet undecided) will handle this use case for many people, but as documented on those other issues, this does not free you up from dealing with the consequences of publishing privately-licensed code to a registry.

**Closed by othiym23** 2015-06-17 23:41 UTC
Labels: feature-request
