### ISSUE TITLE
Installing Atom package 'mavenmmate-atom' crashing

### ISSUE THREAD

**Issue by Teddy22** [npm/npm#18213] opened 2017-08-17 19:51 UTC
#### I'm opening this issue because:

  - npm crashes behind the scenes as I try to install package 'MavensMate-Atom@1.0.10'
  -  Getting the error string 'Installing “MavensMate-Atom@1.0.10” failed.' with a stacktrace log after

OS: Windows 7 Professional

#### How can the CLI team reproduce the problem?
search for the mavensmate-atom package in Atom and click install

**Comment by kenany** [comment] 2017-08-17 20:01
This sounds like a duplicate of https://github.com/npm/npm/issues/17925 to me. You haven't provided much information so I'm just gonna close this `¯\_(ツ)_/¯`

**Closed as completed by kenany** 2017-08-17 20:01 UTC
Labels: support
