### ISSUE TITLE
Openning solution "PartsUnlimited, but error: ENOENT errono 34.

### ISSUE THREAD

**Issue by GuilhermeMorais** [npm/npm#10291] opened 2015-11-06 12:21 UTC
Hi guys, maybe can anyone help me with this error, log below:

```
PATH=C:\Projects\PartsUnlimited-master\src\PartsUnlimitedWebsite\.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\Bower.cmd" install --force-latest
bower jquery-validation-unobtrusive#3.2.2       not-cached git://github.com/aspnet/jquery-validation-unobtrusive.git#3.2.2
bower jquery-validation-unobtrusive#3.2.2          resolve git://github.com/aspnet/jquery-validation-unobtrusive.git#3.2.2
bower bootstrap#3.3.1                           not-cached git://github.com/twbs/bootstrap.git#3.3.1
bower bootstrap#3.3.1                              resolve git://github.com/twbs/bootstrap.git#3.3.1
bower jquery#2.1.1                              not-cached git://github.com/jquery/jquery.git#2.1.1
bower jquery#2.1.1                                 resolve git://github.com/jquery/jquery.git#2.1.1
bower jquery-ui-smoothness#1.11.1               not-cached git://github.com/CrankyDragon/jquery-ui-smoothness.git#1.11.1
bower jquery-ui-smoothness#1.11.1                  resolve git://github.com/CrankyDragon/jquery-ui-smoothness.git#1.11.1
bower jquery-ui#1.11.2                          not-cached git://github.com/components/jqueryui.git#1.11.2
bower jquery-ui#1.11.2                             resolve git://github.com/components/jqueryui.git#1.11.2
bower jquery-validation#1.13.1                  not-cached git://github.com/jzaefferer/jquery-validation.git#1.13.1
bower jquery-validation#1.13.1                     resolve git://github.com/jzaefferer/jquery-validation.git#1.13.1
bower jquery-zoom#1.7.14                        not-cached git://github.com/jackmoore/zoom.git#1.7.14
bower jquery-zoom#1.7.14                           resolve git://github.com/jackmoore/zoom.git#1.7.14
bower signalr#2.1.2                             not-cached git://github.com/SignalR/bower-signalr.git#2.1.2
bower signalr#2.1.2                                resolve git://github.com/SignalR/bower-signalr.git#2.1.2
bower respond#1.2.0                             not-cached git://github.com/scottjehl/Respond.git#1.2.0
bower respond#1.2.0                                resolve git://github.com/scottjehl/Respond.git#1.2.0
bower modernizr#2.7.2                           not-cached git://github.com/Modernizr/Modernizr.git#2.7.2
bower modernizr#2.7.2                              resolve git://github.com/Modernizr/Modernizr.git#2.7.2
bower signalr#2.1.2                               download https://github.com/SignalR/bower-signalr/archive/v2.1.2.tar.gz
bower jquery-ui-smoothness#1.11.1                 download https://github.com/CrankyDragon/jquery-ui-smoothness/archive/v1.11.1.tar.gz
bower jquery-ui#1.11.2                            download https://github.com/components/jqueryui/archive/1.11.2.tar.gz
bower jquery-zoom#1.7.14                          download https://github.com/jackmoore/zoom/archive/1.7.14.tar.gz
bower jquery-validation-unobtrusive#3.2.2         download https://github.com/aspnet/jquery-validation-unobtrusive/archive/v3.2.2.tar.gz
bower respond#1.2.0                               download https://github.com/scottjehl/Respond/archive/1.2.0.tar.gz
bower modernizr#2.7.2                             download https://github.com/Modernizr/Modernizr/archive/v2.7.2.tar.gz
bower jquery-validation#1.13.1                    download https://github.com/jzaefferer/jquery-validation/archive/1.13.1.tar.gz
bower jquery#2.1.1                                download https://github.com/jquery/jquery/archive/2.1.1.tar.gz
bower bootstrap#3.3.1                             download https://github.com/twbs/bootstrap/archive/v3.3.1.tar.gz
bower jquery-validation-unobtrusive#3.2.2          extract archive.tar.gz
bower jquery-ui-smoothness#1.11.1                  extract archive.tar.gz
bower signalr#2.1.2                                extract archive.tar.gz
bower jquery-ui-smoothness#1.11.1             invalid-meta jquery-ui-smoothness is missing "main" entry in bower.json
bower jquery-ui-smoothness#1.11.1             invalid-meta jquery-ui-smoothness is missing "ignore" entry in bower.json
bower respond#1.2.0                                extract archive.tar.gz
bower jquery-validation-unobtrusive#3.2.2     invalid-meta jquery-validation-unobtrusive is missing "ignore" entry in bower.json
bower jquery-zoom#1.7.14                           extract archive.tar.gz
bower jquery-ui-smoothness#1.11.1                 resolved git://github.com/CrankyDragon/jquery-ui-smoothness.git#1.11.1
bower signalr#2.1.2                           invalid-meta signalr is missing "ignore" entry in bower.json
bower jquery-validation-unobtrusive#3.2.2         resolved git://github.com/aspnet/jquery-validation-unobtrusive.git#3.2.2
bower signalr#2.1.2                               resolved git://github.com/SignalR/bower-signalr.git#2.1.2
bower jquery-zoom#1.7.14                      invalid-meta jquery-zoom is missing "ignore" entry in bower.json
bower respond#1.2.0                           invalid-meta respond is missing "main" entry in bower.json
bower respond#1.2.0                           invalid-meta respond is missing "ignore" entry in bower.json
bower jquery-zoom#1.7.14                          resolved git://github.com/jackmoore/zoom.git#1.7.14
bower respond#1.2.0                               resolved git://github.com/scottjehl/Respond.git#1.2.0
bower jquery-validation#1.13.1                     extract archive.tar.gz
bower modernizr#2.7.2                              extract archive.tar.gz
bower jquery#2.1.1                                 extract archive.tar.gz
bower bootstrap#3.3.1                              extract archive.tar.gz
bower jquery-validation#1.13.1                    resolved git://github.com/jzaefferer/jquery-validation.git#1.13.1
bower jquery-ui#1.11.2                             extract archive.tar.gz
bower modernizr#2.7.2                         invalid-meta modernizr is missing "main" entry in bower.json
bower modernizr#2.7.2                         invalid-meta modernizr is missing "ignore" entry in bower.json
bower modernizr#2.7.2                             resolved git://github.com/Modernizr/Modernizr.git#2.7.2
bower jquery#2.1.1                                resolved git://github.com/jquery/jquery.git#2.1.1
bower bootstrap#3.3.1                             resolved git://github.com/twbs/bootstrap.git#3.3.1
bower jquery-ui#1.11.2                            resolved git://github.com/components/jqueryui.git#1.11.2
bower jquery-ui-smoothness#1.11.1                  install jquery-ui-smoothness#1.11.1
bower jquery-validation-unobtrusive#3.2.2          install jquery-validation-unobtrusive#3.2.2
bower signalr#2.1.2                                install signalr#2.1.2
bower jquery-zoom#1.7.14                           install jquery-zoom#1.7.14
bower respond#1.2.0                                install respond#1.2.0
bower jquery-validation#1.13.1                     install jquery-validation#1.13.1
bower modernizr#2.7.2                              install modernizr#2.7.2
bower jquery#2.1.1                                 install jquery#2.1.1
bower bootstrap#3.3.1                              install bootstrap#3.3.1
bower jquery-ui#1.11.2                             install jquery-ui#1.11.2
jquery-ui-smoothness#1.11.1 bower_components\jquery-ui-smoothness
jquery-validation-unobtrusive#3.2.2 bower_components\jquery-validation-unobtrusive
├── jquery#2.1.1
└── jquery-validation#1.13.1
signalr#2.1.2 bower_components\signalr
└── jquery#2.1.1
jquery-zoom#1.7.14 bower_components\jquery-zoom
└── jquery#2.1.1
respond#1.2.0 bower_components\respond
jquery-validation#1.13.1 bower_components\jquery-validation
└── jquery#2.1.1
modernizr#2.7.2 bower_components\modernizr
jquery#2.1.1 bower_components\jquery
bootstrap#3.3.1 bower_components\bootstrap
└── jquery#2.1.1
jquery-ui#1.11.2 bower_components\jquery-ui
└── jquery#2.1.1
====Executing command 'npm install'====


npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/bower-registry-client
npm http GET https://registry.npmjs.org/gzip-size
npm http GET https://registry.npmjs.org/es6-weak-map
npm http GET https://registry.npmjs.org/grunt-bower-task
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/end-of-stream
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/grunt-sass
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/latest-version
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/pretty-bytes
npm http GET https://registry.npmjs.org/npmconf
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/update-notifier
npm http 200 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/argparse/-/argparse-1.0.1.tgz
npm http 200 https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/combined-stream/-/combined-stream-0.0.7.tgz
npm http 200 https://registry.npmjs.org/bower-registry-client
npm http 200 https://registry.npmjs.org/gzip-size
npm http 200 https://registry.npmjs.org/grunt-contrib-copy
npm http 200 https://registry.npmjs.org/es6-weak-map
npm http 200 https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/end-of-stream
npm http GET https://registry.npmjs.org/bower-registry-client/-/bower-registry-client-0.2.4.tgz
npm http GET https://registry.npmjs.org/grunt-contrib-copy/-/grunt-contrib-copy-0.7.0.tgz
npm http 200 https://registry.npmjs.org/grunt-bower-task
npm http 200 https://registry.npmjs.org/form-data
npm http 200 https://registry.npmjs.org/grunt-sass
npm http 200 https://registry.npmjs.org/cli-color
npm http 200 https://registry.npmjs.org/latest-version
npm http GET https://registry.npmjs.org/gzip-size/-/gzip-size-1.0.0.tgz
npm http GET https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-0.1.4.tgz
npm http 200 https://registry.npmjs.org/readable-stream
npm http 200 https://registry.npmjs.org/pretty-bytes
npm http 200 https://registry.npmjs.org/grunt-contrib-uglify
npm http 200 https://registry.npmjs.org/combined-stream/-/combined-stream-0.0.7.tgz
npm http 200 https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt-contrib-concat
npm http 200 https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-0.1.4.tgz
npm http 200 https://registry.npmjs.org/npmconf
npm http 200 https://registry.npmjs.org/argparse/-/argparse-1.0.1.tgz
npm http GET https://registry.npmjs.org/grunt-bower-task/-/grunt-bower-task-0.4.0.tgz
npm http GET https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.0.0.tgz
npm http GET https://registry.npmjs.org/cli-color/-/cli-color-0.3.2.tgz
npm http GET https://registry.npmjs.org/grunt-sass/-/grunt-sass-1.1.0.tgz
npm http GET https://registry.npmjs.org/bower/-/bower-1.6.5.tgz
npm http GET https://registry.npmjs.org/form-data/-/form-data-0.2.0.tgz
npm http GET https://registry.npmjs.org/latest-version/-/latest-version-1.0.1.tgz
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.13.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-copy/-/grunt-contrib-copy-0.7.0.tgz
npm http 200 https://registry.npmjs.org/bower-registry-client/-/bower-registry-client-0.2.4.tgz
npm http 200 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/cli-color/-/cli-color-0.3.2.tgz
npm http 200 https://registry.npmjs.org/gzip-size/-/gzip-size-1.0.0.tgz
npm http 200 https://registry.npmjs.org/grunt-sass/-/grunt-sass-1.1.0.tgz
npm http GET https://registry.npmjs.org/grunt-contrib-concat/-/grunt-contrib-concat-0.5.0.tgz
npm http GET https://registry.npmjs.org/grunt-contrib-uglify/-/grunt-contrib-uglify-0.7.0.tgz
npm http GET https://registry.npmjs.org/npmconf/-/npmconf-2.1.1.tgz
npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm http GET https://registry.npmjs.org/pretty-bytes/-/pretty-bytes-1.0.4.tgz
npm http GET https://registry.npmjs.org/request/-/request-2.27.0.tgz
npm http 200 https://registry.npmjs.org/form-data/-/form-data-0.2.0.tgz
npm http 200 https://registry.npmjs.org/latest-version/-/latest-version-1.0.1.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.6.5.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-concat/-/grunt-contrib-concat-0.5.0.tgz
npm http 200 https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/update-notifier/-/update-notifier-0.3.2.tgz
npm http 200 https://registry.npmjs.org/grunt-bower-task/-/grunt-bower-task-0.4.0.tgz
npm http 200 https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.0.0.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-uglify/-/grunt-contrib-uglify-0.7.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.13.tgz
npm http 200 https://registry.npmjs.org/npmconf/-/npmconf-2.1.1.tgz
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm http 200 https://registry.npmjs.org/update-notifier/-/update-notifier-0.3.2.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.27.0.tgz
npm http 200 https://registry.npmjs.org/pretty-bytes/-/pretty-bytes-1.0.4.tgz
npm ERR! Error: ENOENT, lstat 'C:\Users\glopes\AppData\Roaming\npm-cache\bower\1.6.5\package\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Projects\PartsUnlimited-master\src\PartsUnlimitedWebsite
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! path C:\Users\glopes\AppData\Roaming\npm-cache\bower\1.6.5\package\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\index.js
npm ERR! fstream_path C:\Users\glopes\AppData\Roaming\npm-cache\bower\1.6.5\package\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm
```
====npm command completed with exit code 34====

**Comment by KenanY** [comment] 2015-11-06 18:49
@GuilhermeMorais Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`?

**Comment by iarna** [comment] 2015-11-06 19:46
Closing this as a duplicate of #9633

**Comment by iarna** [comment] 2015-11-06 19:46
oh, 1.4.9, not a duplicate =D

**Comment by GuilhermeMorais** [comment] 2015-11-12 12:53
@KenanY This was in the lasted version of npm. any help, just say...

**Comment by KenanY** [comment] 2016-05-15 17:34
@GuilhermeMorais Are you still seeing this issue with `npm@2` or `npm@3`?

**Comment by GuilhermeMorais** [comment] 2016-05-16 12:00
Hi @KenanY , I don't know because I just uninstalled my VS2015 a few months ago.

**Closed** 2016-06-28 20:44 UTC
