### ISSUE TITLE
Cannot download a NPM package due to 502 Bad Gateway error

### ISSUE THREAD

**Issue by bmamouri** [npm/npm#13295] opened 2016-07-06 13:46 UTC
When I am trying to install `gulp` on my server, I get the following error:

    ubuntu@bigboy:/var/www/$ npm install
    npm ERR! fetch failed http://registry.npmjs.org/caching-transform/-/caching-transform-1.0.1.tgz

The problem is that the path of the package cannot be resolved:

    ubuntu@bigboy:/var/www/$ curl --head http://registry.npmjs.org/caching-transform/-/caching-transform-1.0.1.tgz
    HTTP/1.1 502 Bad Gateway
    Content-Type: text/html
    Cache-Control: max-age=21600
    Transfer-Encoding: chunked
    Accept-Ranges: bytes
    Date: Wed, 06 Jul 2016 13:26:28 GMT
    Via: 1.1 varnish
    Connection: keep-alive
    X-Served-By: cache-jfk1034-JFK
    X-Cache: MISS
    X-Cache-Hits: 0
    X-Timer: S1467811588.853116,VS0,VE65

It is actually funny that the directory of the package can successfully downloaded:

    ubuntu@bigboy:/var/www/$ curl --head http://registry.npmjs.org/caching-transform/
    HTTP/1.1 200 OK
    server: CouchDB/1.6.1 (Erlang OTP/R16B03)
    etag: "47H1AE8C58DZJSN6RH2C5BGZF"
    Content-Type: application/json
    Cache-Control: max-age=300
    Content-Length: 14713
    Accept-Ranges: bytes
    Date: Wed, 06 Jul 2016 13:27:39 GMT
    Via: 1.1 varnish
    Age: 0
    Connection: keep-alive
    X-Served-By: cache-jfk1042-JFK
    X-Cache: MISS
    X-Cache-Hits: 0
    X-Timer: S1467811659.501650,VS0,VE192
    Vary: Accept-Encoding

This is the result of my `traceroute` to `registry.npmjs.org`:

    traceroute to registry.npmjs.org (151.101.116.162), 30 hops max, 60 byte packets
     1  216.182.225.98 (216.182.225.98)  49.944 ms  49.938 ms 216.182.225.94 (216.182.225.94)  18.780 ms
     2  100.66.12.254 (100.66.12.254)  19.344 ms 100.66.8.64 (100.66.8.64)  14.231 ms 100.66.12.76 (100.66.12.76)  15.227 ms
     3  100.66.15.206 (100.66.15.206)  12.567 ms 100.66.10.230 (100.66.10.230)  21.903 ms 100.66.14.200 (100.66.14.200)  17.681 ms
     4  100.66.6.175 (100.66.6.175)  21.732 ms 100.66.7.143 (100.66.7.143)  23.479 ms 100.66.6.71 (100.66.6.71)  32.338 ms
     5  100.66.4.97 (100.66.4.97)  19.657 ms 100.66.4.239 (100.66.4.239)  153.106 ms 100.66.4.77 (100.66.4.77)  22.246 ms
     6  100.65.10.225 (100.65.10.225)  1.984 ms 100.65.9.1 (100.65.9.1)  0.423 ms 100.65.10.1 (100.65.10.1)  1.859 ms
     7  205.251.245.251 (205.251.245.251)  0.880 ms  0.885 ms 205.251.245.46 (205.251.245.46)  0.888 ms
     8  54.239.111.36 (54.239.111.36)  1.124 ms 54.239.108.234 (54.239.108.234)  8.591 ms 54.239.108.98 (54.239.108.98)  24.467 ms
     9  54.239.109.35 (54.239.109.35)  0.975 ms 54.239.108.185 (54.239.108.185)  1.013 ms 54.239.108.187 (54.239.108.187)  1.162 ms
    10  54.239.41.219 (54.239.41.219)  6.762 ms 54.239.41.221 (54.239.41.221)  6.792 ms 54.239.42.185 (54.239.42.185)  6.844 ms
    11  52.93.4.13 (52.93.4.13)  11.969 ms 52.93.4.3 (52.93.4.3)  7.715 ms 52.93.4.25 (52.93.4.25)  9.139 ms
    12  52.93.4.82 (52.93.4.82)  6.775 ms 52.93.4.106 (52.93.4.106)  6.754 ms 52.93.4.92 (52.93.4.92)  6.807 ms
    13  be-104-pe03.111eighthave.ny.ibone.comcast.net (50.242.148.117)  7.638 ms be-110-pe02.111eighthave.ny.ibone.comcast.net (50.242.148.113)  7.259 ms be-120-pe03.111eighthave.ny.ibone.comcast.net (50.242.148.121)  7.209 ms
    14  hu-0-3-0-0-cr02.newyork.ny.ibone.comcast.net (68.86.86.249)  9.270 ms hu-1-3-0-8-cr02.newyork.ny.ibone.comcast.net (68.86.84.241)  8.257 ms hu-1-3-0-3-cr02.newyork.ny.ibone.comcast.net (68.86.83.101)  7.448 ms
    15  be-10373-pe02.onesummer.ma.ibone.comcast.net (68.86.86.158)  12.125 ms  12.114 ms  12.138 ms

I can almost install any other package. It is only this package that I have the problem with. I even tried to turn off SSL with the following command, with no success:

    npm config set registry http://registry.npmjs.org/

How can I solve this problem? Is there even anything that I can do to find the real cause of this error?

**Comment by erickrawczyk** [comment] 2016-07-06 13:50
shit's broken right now yo, #13284

**Comment by avengerine** [comment] 2016-07-06 14:01
having the same problem

**Comment by othiym23** [comment] 2016-07-06 14:54
Closing as duplicate of #13284.

**Closed by othiym23** 2016-07-06 14:54 UTC
Labels: big-bug, bug, registry
