### ISSUE TITLE
Can't install modules with npm 3.1.1

### ISSUE THREAD

**Issue by timdp** [npm/npm#8929] opened 2015-07-13 16:27 UTC
I had npm 3.1.0 and ran `npm i -g npm@3.1.1`. After that, I couldn't install any npm module into a vanilla module (the result of `npm init`) anymore:

```
>npm install --save-dev grunt-aws-lambda
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Tim\\.nvmw\\latest\\\\node.exe" "C:\\Users\\Tim\\.nvmw\\latest\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "grunt-aws-lambda"
npm ERR! node v0.12.6
npm ERR! npm  v3.1.1
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected object but got string
npm ERR! typeerror     at resolveWithNewModule (C:\Users\Tim\.nvmw\latest\node_modules\npm\lib\install\deps.js:375:3)
npm ERR! typeerror     at C:\Users\Tim\.nvmw\latest\node_modules\npm\lib\install\deps.js:163:5
npm ERR! typeerror     at C:\Users\Tim\.nvmw\latest\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at C:\Users\Tim\.nvmw\latest\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (C:\Users\Tim\.nvmw\latest\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (C:\Users\Tim\.nvmw\latest\node_modules\npm\lib\install\deps.js:158:3)
npm ERR! typeerror     at Array.<anonymous> (C:\Users\Tim\.nvmw\latest\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (C:\Users\Tim\.nvmw\latest\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

This is on Windows 8.1 with node 0.12.6 (through nvmw).

**Comment by cchamberlain** [comment] 2015-07-13 16:39
Duplicate of https://github.com/npm/npm/issues/8893

I tried digging around in the code and fixing it but in the end its easier to just install npm@3.1.0 which doesn't have the issue.

**Comment by iarna** [comment] 2015-07-13 16:49
I'll be releasing a fixed version later today.

**Comment by iarna** [comment] 2015-07-13 16:51
Closing as duplicate.

**Closed by iarna** 2015-07-13 16:51 UTC
Labels: bug
