### ISSUE TITLE
'npm install bower' error

### ISSUE THREAD

**Issue by mustafavzg** [npm/npm#9617] opened 2015-09-16 15:42 UTC
Hi, 

I am getting following error while installing bower (both global and local versions):

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for /tmp/npm-16939-f2025f4c/registry.npmjs.org/glob/-/glob-5.0.14.tgz
npm ERR! Expected: a811d507acb605441edd6cd2622a3c6f06cc00e1
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     http://registry.npmjs.org/glob/-/glob-5.0.14.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mustafa/npm-debug.log

Here are the errors form the npm-debug.log:

17904 silly gunzTarPerm extractEntry src/core/linq/observable/mergedelayerror.js
17905 silly gunzTarPerm modified mode [ 'src/core/linq/observable/mergedelayerror.js', 438, 436 ]
17938 silly gunzTarPerm extractEntry src/core/linq/observable/onerrorresumenext.js
17939 silly gunzTarPerm modified mode [ 'src/core/linq/observable/onerrorresumenext.js', 438, 436 ]
17942 silly gunzTarPerm extractEntry src/core/linq/observable/onerrorresumenextproto.js
17943 silly gunzTarPerm modified mode [ 'src/core/linq/observable/onerrorresumenextproto.js',
18717 silly gunzTarPerm extractEntry src/core/internal/errors.js
18718 silly gunzTarPerm modified mode [ 'src/core/internal/errors.js', 438, 436 ]
19540 silly gunzTarPerm extractEntry error/custom.js
19541 silly gunzTarPerm modified mode [ 'error/custom.js', 420, 436 ]
19542 silly gunzTarPerm extractEntry error/index.js
19543 silly gunzTarPerm modified mode [ 'error/index.js', 420, 436 ]
19544 silly gunzTarPerm extractEntry error/is-error.js
19545 silly gunzTarPerm modified mode [ 'error/is-error.js', 420, 436 ]
19546 silly gunzTarPerm extractEntry error/valid-error.js
19547 silly gunzTarPerm modified mode [ 'error/valid-error.js', 420, 436 ]
19548 silly gunzTarPerm extractEntry error/#/index.js
19549 silly gunzTarPerm modified mode [ 'error/#/index.js', 420, 436 ]
19550 silly gunzTarPerm extractEntry error/#/throw.js
19551 silly gunzTarPerm modified mode [ 'error/#/throw.js', 420, 436 ]
20092 silly gunzTarPerm extractEntry test/error/custom.js
20093 silly gunzTarPerm modified mode [ 'test/error/custom.js', 420, 436 ]
20094 silly gunzTarPerm extractEntry test/error/is-error.js
20095 silly gunzTarPerm modified mode [ 'test/error/is-error.js', 420, 436 ]
20096 silly gunzTarPerm extractEntry test/error/valid-error.js
20097 silly gunzTarPerm modified mode [ 'test/error/valid-error.js', 420, 436 ]
20098 silly gunzTarPerm extractEntry test/error/#/throw.js
20099 silly gunzTarPerm modified mode [ 'test/error/#/throw.js', 420, 436 ]
21377 error Linux 3.13.0-55-generic
21378 error argv "/usr/bin/node" "/usr/local/bin/npm" "install" "bower"
21379 error node v0.12.7
21380 error npm  v2.11.3
21381 error shasum check failed for /tmp/npm-16939-f2025f4c/registry.npmjs.org/glob/-/glob-5.0.14.tgz
21381 error Expected: a811d507acb605441edd6cd2622a3c6f06cc00e1
21381 error Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
21381 error From:     http://registry.npmjs.org/glob/-/glob-5.0.14.tgz
21382 error If you need help, you may report this error at:
21382 error     <https://github.com/npm/npm/issues>

Please look into it.

**Comment by KenanY** [comment] 2015-09-16 15:46
@mustafavzg http://status.npmjs.org/incidents/pyw00fmpjzrh

**Comment by seldo** [comment] 2015-09-16 15:52
Closing as dupe of https://github.com/npm/npm/issues/9601

**Closed by seldo** 2015-09-16 15:52 UTC

**Comment by Ishman12Khera** [comment] 2016-01-24 10:37
i am still facing the same problem
Any Suggestion?

**Comment by windrian** [comment] 2017-03-06 02:51
me too,
