### ISSUE TITLE
Error: EPERM: operation not permitted on npm 5.4 on windows

### ISSUE THREAD

**Issue by egoroof** [npm/npm#18380] opened 2017-09-02 09:44 UTC
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

I've updated to npm5.4 (from 5.3) and fresh npm i (without node_modules, package-lock.json and cleared cache) throws this error:

```
npm ERR! path C:\Data\Dropbox\repo\blowfish\node_modules\fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Data\Dropbox\repo\blowfish\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Data\Dropbox\repo\blowfish\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Data\\Dropbox\\repo\\blowfish\\node_modules\\fsevents\\node_modules\\abbrev\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Data\\Dropbox\\repo\\blowfish\\node_modules\\fsevents\\node_modules\\abbrev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

#### How can the CLI team reproduce the problem?

Here's my dependencies:

```json
{
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.0"
  }
}
```

Run `npm i` on Windows.

### supporting information:

 - `npm -v` prints: 5.4.0
 - `node -v` prints: 8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues: no

**Comment by pvdlg** [comment] 2017-09-02 16:57
Same issue here:
https://ci.appveyor.com/project/vanduynslagerp/karma-rollup-preprocessor/build/138
https://ci.appveyor.com/project/vanduynslagerp/karma-jasmine-jquery/build/87
https://ci.appveyor.com/project/vanduynslagerp/karma-postcss-preprocessor/build/40

**Comment by hasancanozkan** [comment] 2017-09-02 18:19
same here

**Comment by juansev** [comment] 2017-09-02 18:38
i am having the same problem on Windows 10, Node 6.3.1 NPM 5.4 . I have rollbacked to 5.3 and it works

**Comment by DominikLevitsky** [comment] 2017-09-02 19:55
same

**Comment by Tsury** [comment] 2017-09-02 21:58
same

**Comment by Zbyl** [comment] 2017-09-03 06:15
I had the same issue when trying "npm install --save hammerjs" (and some other packages too!).

In my case package.json file mentioned in the error (for me it was \node_modules\\fsevents\\node_modules\\ansi-regex\\package.json) was not present in the system.
I have added an empty file with this name and it got further - to next similar error.

It turned out that all directories under fsevents\\node_modules (few dozens of them) are empty!
Definitely some bug in npm.

I didn't know what to do with that, so I removed node_modules folder in project directory and run npm install again. This went well.

So I tried "npm install --save hammerjs" again, but I got the same errors all over.

npm -v
5.4.0
node -v
v8.4.0

I was running in command prompt as Administrator. Previously I was running that in non-admin cmd and had the same error.
Error message and debug logs in attachments,
[logs.zip](https://github.com/npm/npm/files/1272734/logs.zip)

I have uninstalled node (and npm).
I have also deleted C:\Users\Skowron\AppData\Roaming\npm and C:\Users\Skowron\AppData\Roaming\npm-cache.
I deleted node_modules folder in project directory.
I have reinstalled node 8.4.0 (which comes with npm 5.3.0).

After that "npm install --save hammerjs" worked.
Instead of errors with non-existing files in fsevents folder it simply printed this warning:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents)

**Comment by valakhosravi** [comment] 2017-09-03 09:08
same

**Comment by shravan2x** [comment] 2017-09-03 10:13
This issue appears to only occur with specific packages, `babel-loader` is one of them.

**Comment by jschumme** [comment] 2017-09-03 10:39
confirm Windows 10

**Comment by inestyne** [comment] 2017-09-03 15:41
same

**Comment by inestyne** [comment] 2017-09-03 15:58
temporary fix, downgrade npm to 5.3

npm install npm@5.3 -g

**Comment by kyleryanaz** [comment] 2017-09-03 17:14
Got this error when trying to create a react app. Downgrading to npm 5.3 worked for me as well.

**Comment by jhoutromundo** [comment] 2017-09-03 17:47
Same thing here!

**Comment by LMS007** [comment] 2017-09-03 18:52
I have the issue on my Heroku  Dyno, so it's an issue in Linux too

**Comment by oleonardo** [comment] 2017-09-03 21:00
+1

**Comment by starman-vlad** [comment] 2017-09-03 21:45
I had nothing but problems since `npm v5` came out. I am not able to install `electron`, `create-react-app`, `create-react-native-app` using `npm v5`, just because of the permission issue even though I tried to install those modules through `root`/`Administrator`.

However, if I were to install `npm v4.6.1` everything works flawlessly.

**Comment by MiLL10N** [comment] 2017-09-04 06:52
same

**Comment by marcovdb** [comment] 2017-09-04 08:56
I have the same issue. Windows 10 Enterprise x64, Node.js 6.11.2, NPM 5.4. For me, it kept doing it with a module called "nan".

Rolled back to 5.3 and it fixed the problem for me.

```
11330 error path c:\xampp\htdocs\XXX\node_modules\nan\package.json
11331 error code EPERM
11332 error errno -4048
11333 error syscall unlink
11334 error Error: EPERM: operation not permitted, unlink 'c:\xampp\htdocs\XXX\node_modules\nan\package.json'
11334 error     at Error (native)
11334 error  { Error: EPERM: operation not permitted, unlink 'c:\xampp\htdocs\XXX\node_modules\nan\package.json'
11334 error     at Error (native)
11334 error   stack: 'Error: EPERM: operation not permitted, unlink \'c:\\xampp\\htdocs\\XXX\\node_modules\\nan\\package.json\'\n    at Error (native)',
11334 error   errno: -4048,
11334 error   code: 'EPERM',
11334 error   syscall: 'unlink',
11334 error   path: 'c:\\xampp\\htdocs\\XXX\\node_modules\\nan\\package.json' }
11335 error Please try running this command again as root/Administrator.
11336 verbose exit [ -4048, true ]
```

**Comment by Mardoxx** [comment] 2017-09-04 12:33
Same! npm@5.3 works fine.

Thanks for breaking all my builds 😉 

```
2017-09-04T12:10:43.0834553Z 24393 verbose unlock done using C:\NPM\Cache\_locks\staging-7a8d0a4441b61671.lock for d:\a\1\s\node_modules\.staging
2017-09-04T12:10:43.0834553Z 24394 verbose stack Error: EPERM: operation not permitted, unlink 'd:\a\1\s\node_modules\nan\package.json'
2017-09-04T12:10:43.0834553Z 24395 verbose cwd d:\a\1\s
2017-09-04T12:10:43.0834553Z 24396 verbose Windows_NT 6.3.9600
2017-09-04T12:10:43.0834553Z 24397 verbose argv "d:\\a\\_tool\\node\\8.4.0\\x64\\node.exe" "C:\\NPM\\Modules\\node_modules\\npm\\bin\\npm-cli.js" "install"
2017-09-04T12:10:43.0834553Z 24398 verbose node v8.4.0
2017-09-04T12:10:43.0834553Z 24399 verbose npm  v5.4.0
2017-09-04T12:10:43.0834553Z 24400 error path d:\a\1\s\node_modules\nan\package.json
2017-09-04T12:10:43.0834553Z 24401 error code EPERM
2017-09-04T12:10:43.0834553Z 24402 error errno -4048
2017-09-04T12:10:43.0834553Z 24403 error syscall unlink
2017-09-04T12:10:43.0834553Z 24404 error Error: EPERM: operation not permitted, unlink 'd:\a\1\s\node_modules\nan\package.json'
2017-09-04T12:10:43.0834553Z 24404 error  { Error: EPERM: operation not permitted, unlink 'd:\a\1\s\node_modules\nan\package.json'
2017-09-04T12:10:43.0834553Z 24404 error   stack: 'Error: EPERM: operation not permitted, unlink \'d:\\a\\1\\s\\node_modules\\nan\\package.json\'',
2017-09-04T12:10:43.0834553Z 24404 error   errno: -4048,
2017-09-04T12:10:43.0834553Z 24404 error   code: 'EPERM',
2017-09-04T12:10:43.0834553Z 24404 error   syscall: 'unlink',
2017-09-04T12:10:43.0834553Z 24404 error   path: 'd:\\a\\1\\s\\node_modules\\nan\\package.json' }
2017-09-04T12:10:43.0834553Z 24405 error Please try running this command again as root/Administrator.
2017-09-04T12:10:43.0834553Z 24406 verbose exit [ -4048, true ]
```

**Comment by n3dst4** [comment] 2017-09-04 12:46
I've done some `git bisect`ing on on the npm repo and the bug is introduced in this commit: https://github.com/npm/npm/commit/f4650b5d4b2be2c04c229cc53aa930e260af9b4e

This updates `write-file-atomic` to 2.3.0. I've confirmed this by taking the 5.4.0 code and manualy installing `write-file-atomic` at the previous version (2.1.0) and it fixes the issue.

**Comment by Mardoxx** [comment] 2017-09-04 13:26
@n3dst4 Good job. "Cleanup tempfiles when process is interrupted or killed." Sounds like a probable cause....

**Comment by Jimmy02020** [comment] 2017-09-04 16:10
same here.

>   windows 10, 
>   npm: '5.4.0',

**Comment by mikkotikkanen** [comment] 2017-09-04 17:24
same. W10, npm 5.4.0 -> `Error: EPERM: operation not permitted, unlink` with `fsevents`

Works correctly with 5.3.0 though 👍, which just saved my evening.

**Comment by jonbarrow** [comment] 2017-09-04 17:38
Getting the exact same issue with the exact same error, and downgrading to npm 5.3 is not an option in my case :/

**Comment by ConsoleTVs** [comment] 2017-09-04 18:42
Same

**Comment by kokijorge1** [comment] 2017-09-04 19:04
same

**Comment by xiaofuyesnew** [comment] 2017-09-05 03:02
I have the same situation on Windows 10， trying make npm version back to 5.3.0 and it works.

**Comment by egoroof** [comment] 2017-09-05 03:10
@iarna, @KenanY or @zkat plz lock this issue.

**Comment by kulshekhar** [comment] 2017-09-05 03:43
We're facing the same issue. For reference:

The builds fail with v5.4 with this error (https://ci.appveyor.com/project/kulshekhar/ts-jest/build/698/job/i4r9vjkd29wed9th)

After configuring the build to use npm v5.3, the build passes (https://ci.appveyor.com/project/kulshekhar/ts-jest/build/699/job/juxeee5u1wea7r7o)

In this case, the trigger appears to be an `unlink` operation on file(s) from the `nan` package

*Edit: adding a reference to track this from another issue https://github.com/kulshekhar/ts-jest/issues/321*

**Comment by cyberocw** [comment] 2017-09-05 05:17
@inestyne thank you. it fixed by downgrade npm

**Comment by calbertts** [comment] 2017-09-05 09:45
I was using v5.3 and had an issue with Electron Packager which was fixed in v5.4, now v5.4 have this issue installing all the packages.

**Comment by panmanphil** [comment] 2017-09-05 21:28
Both npm 5.4 and 5.3 failed for me. I downgraded to version 4.6.1 and then got a more appropriate message back, and a successful run:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by darioquintana** [comment] 2017-09-06 00:34
Downgraded from 5.4 to version 5.3. Worked for me.
` npm i -g npm@5.3`

Hope this helps

**Comment by chjuruena** [comment] 2017-09-06 02:14
Ionic requires npm v6 and higher so downgrading is not an option for me.

**Comment by StarpTech** [comment] 2017-09-06 08:13
Same here

**Comment by penggy** [comment] 2017-09-06 09:36
same here, downgraded from 5.4 to 5.3 worked for me too.

`npm i -g npm@5.3`

**Comment by bertyhell** [comment] 2017-09-06 10:24
5.4 and 5.3 didn't work for me
5.0.3 did work
`npm i -g npm@5.0.3`

**Comment by benshabatnoam** [comment] 2017-09-06 11:17
Thank you @inestyne you've saved me hours of work. already spent 3 hours for finding a solution. God bless you

**Comment by apascualm** [comment] 2017-09-06 13:07
Same here, i also downgraded.
it is work for me.

**Comment by egoroof** [comment] 2017-09-06 13:21
Вот сука каждому надо написать, что у него тоже не работает. Как будто тут перепись идиотов.

**Comment by KMayne** [comment] 2017-09-06 18:23
This has also affected me on Linux.

**Comment by StarpTech** [comment] 2017-09-06 18:41
> Вот сука каждому надо написать, что у него тоже не работает. Как будто тут перепись идиотов.

"That bitch everyone should write that he does not work either. It's like a census of idiots."
_Google Translate_

**Comment by Mardoxx** [comment] 2017-09-06 19:15
Still no response from maintainers. Disgraceful.

**Comment by Salakar** [comment] 2017-09-07 01:07
Couldn't get any version of npm 5 to publish here, had to downgrade to v4: `npm i npm@4.6.1 -g`

Windows 10, Node 8.4.0

**Comment by irotaev** [comment] 2017-09-07 02:49
Windows 10, Node 7.5.0 npm 5.4.1 still not worked

Rollback to version 5.3.0 helped me? thx for comments!

**Comment by SalahEddineMadih** [comment] 2017-09-07 09:58
same. W10, npm 5.4.0
Works correctly with 5.3.0

**Comment by ldk18501** [comment] 2017-09-07 10:09
same on win10 5.4.0      
however   5.3.0 also have another bug that i cannot use electron package command
so    
use yarn instead

**Comment by apascualm** [comment] 2017-09-07 12:35
I thought that this been corrected with the downgrade of npm, but it continuous with the problem. I updated all, and i performed the next steps:

`rm -rf node_modules`
`rm package-lock.json yarn.lock ` 
`npm cache clear --force`
`npm install`

For now everything works correctly.

**Comment by fural** [comment] 2017-09-07 14:02
Downgrading is the solution, I spent like 3 hours today in this! feels bad man

**Comment by akattelman** [comment] 2017-09-07 15:00
Same here downgrading to 5.3 worked.

**Comment by panmanphil** [comment] 2017-09-07 15:30
I upgraded back to npm 5.4.1 and then added, based on the better message that 4.6 output about skipping optional dependencies, --no-optional like 
`npm install --no-optional`
and this worked

**Comment by hinell** [comment] 2017-09-07 15:53
@StarpTech What the user have left that comment, lol?

**Comment by Mardoxx** [comment] 2017-09-07 18:47
Same on v5.4.1.

Might just migrate to yarn.

**Comment by Jaxolotl** [comment] 2017-09-07 18:55
v5.4.1 solved the pristine installation, but still having issues with current installations.

Win 10
node v.6.9.2
npm 5.4.1

steps
- remove completely the node_modules dir on an existing project
- `>npm install`
- install completed without issues
- `>npm install`
- perms error raised again


```
[MY PATH TO PROJECT]>npm install
npm ERR! path [MY PATH TO PROJECT]\node_modules\fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink '[MY PATH TO PROJECT]\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink '[MY PATH TO PROJECT]\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'[MY PATH TO PROJECT]\\node_modules\\fsevents\\node_modules\\abbrev\\package.json\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '[MY PATH TO PROJECT]\\node_modules\\fsevents\\node_modules\\abbrev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     [MY ME MINE]\AppData\Roaming\npm-cache\_logs\2017-09-07T18_44_32_293Z-debug.log
```

I had to rollback to npm 5.3.x again

Hope this is useful

**Comment by satsuya0114** [comment] 2017-09-08 03:29
same. 
5.3.0 not work 
downgrade to 5.0.3 did work... 
maybe change to use yarn... :(

**Comment by louposk** [comment] 2017-09-08 06:20
Probably there will be a fix soon. We should wait.

**Comment by Mds92** [comment] 2017-09-08 09:49
If you downgrade to 5.3 and still get the same error in Windows like me.
After hours working with npm versions I found the following solution:

https://stackoverflow.com/a/46113451/191647

**Comment by mekwall** [comment] 2017-09-08 11:55
It works the first time after running `npm cache clean --force` so I gather this has to do with the cache being b0rked on Windows. Horrible bug that should have been caught before release...

**Comment by Mardoxx** [comment] 2017-09-08 11:59
@mekwall absolutely.

@zkat found the time to moderate responses, but not to comment on your colleague's major breaking change. How do you sleep at night?

**Comment by mekwall** [comment] 2017-09-08 12:07
After some more digging, this seems related to `node` installed by `nvm`. When installing with `nvm` it will symlink the installation from `C:\Users\<user>\AppData\Roaming\nvm\vX.X.X` to `C:\Program Files\nodejs`.

My guess is that npm5 is trying to manipulate files within `C:\Program Files\nodejs\node_modules` in some way which it is not allowed to do, causing `EPERM: operation not allowed` since the process doesn't have access to `C:\Program Files`.

Running npm 5.3 with `--preserve-symlinks` flag seems to work without having to force clean the cache, but the issue persists with npm 5.4. Can someone else confirm these findings?

**Comment by ratheeshkannan** [comment] 2017-09-08 12:55
I've always thought that updating anything to latest might fix some unknown issue, but this time updating randomly in the middle of development actually resulted in wasting hours. Even tried restarting my system.

Downgraded to 5.3.0 and things fall back to normal.

**Comment by marcins** [comment] 2017-09-08 13:14
Duplicate of #17671 - I have a lot of notes on my investigation of the issue there, and a potential fix in PR.

**Comment by KMayne** [comment] 2017-09-08 13:25
@marcins Actually this is not a duplicate of the issue you linked. 
This error is an EPERM on unlinking of files in a directory due to npm still having that file opened. It is also an issue on Linux, manifesting as an EBUSY.

**Comment by marcins** [comment] 2017-09-08 13:31
@KMayne is there a particular package that causes this for you on Linux? 

I tracked down the EPERM on Windows as occurring because writes to `package.json` were occurring in modules that were getting deleted by rollback, which was causing what was effectively a race condition. It pretty much is almost always reported as an fsevent issue because that is a common dependency that is 'optional' on Windows and therefore gets rolled back after an install attempt.

Does that sound like what you're seeing on Linux?

**Comment by panmanphil** [comment] 2017-09-08 13:31
Maybe you all are are seeing a different problem than I am but the underlying issue is that these recent versions attempt to install fsevents, an optional package that doesn't work on windows, and then we see these EPERM errors as node trys to do operations on folders that don't exist because the installation of fsevents failed. Some earlier versions appropriately skipped the installation of fsevents so did not have this issue. 

You can solve this, assuming you can live without any of the other automatically installed optional dependencies, and you can because you just put them in your packages.json, add --no-optional and it will work. so

`npm install --no-optional`

**Comment by KMayne** [comment] 2017-09-08 13:47
@marcins Ah I see. This sounds like it could be a manifestation of the same bug and perhaps the EPERM on scandir might only occur on Windows.

**Comment by KMayne** [comment] 2017-09-08 14:15
I can confirm that enabling fsync in `install-package-json.js` as in https://github.com/npm/npm/pull/18458 solves this problem on Linux. I suspect that the actual bug lies elsewhere though since the comment does say that it should be unnecessary.

**Comment by eman1986** [comment] 2017-09-08 14:34
going back to 5.3 solved my problem, hopefully they'll fix this soon, seems like someone should have caught this pretty easily before releasing

**Comment by arackaf** [comment] 2017-09-08 18:39
5.3 worked for me as well, but `npm i npm@5.3 -g` error'd on me.  What did work, however, was just grabbing the zipped up npm deploy from 

registry.npmjs.com/npm/-/npm-5.3.0.tgz

and un-zipping it into node's root node_modules into the npm folder (after clearing it out first, obviously).

Hopefully that'll help someone out there.

**Comment by paulmelero** [comment] 2017-09-09 06:05
As @Apascualm and @panmanphil pointed: This worked for me:

`rm` (-rf) ` node_modules`
`rm package-lock.json yarn.lock`
`npm cache clear --force`
`npm i -g npm ` # 5.4.1, as for now
`npm install --no-optional`

**Comment by radosvet93** [comment] 2017-09-09 08:19
I try everything, definitely there is a problem with the new version of npm, when i downgrade the npm to version 5.3 the problem was fixed

`npm install npm@5.3 -g`

**Comment by bellib** [comment] 2017-09-09 11:02
5.4 didn't work for me
5.3 did work
`npm i -g npm@5.3`

**Comment by KevinSimple** [comment] 2017-09-09 12:04
dont know when bugs like this will be gone, so sad :(

**Comment by vscodeguru** [comment] 2017-09-09 12:10
![image](https://user-images.githubusercontent.com/18045792/30239989-50dc9a98-9585-11e7-8262-a87b1225873a.png)

Npm  : 5.3.0
Node : v7.9.0

While try **npm install** i get 

![image](https://user-images.githubusercontent.com/18045792/30240019-beae52dc-9585-11e7-857f-cc6e9560bf8a.png)

i also tried **npm cache clean** with **-force**  nothing happen. any on help me on this issue

**Comment by badrday** [comment] 2017-09-09 12:11
I was trying to install express-jwt-permissions:
5.4 didn't work for me
5.3 didn't work for me
**5.2 did work**
npm i -g npm@5.2

**Comment by wzard** [comment] 2017-09-09 12:16
I was try install `npm install --saveDev babel-plugin-transform-decorators-legacy` 5.4 didn't work. 5.3 is a lifesaver

**Comment by vscodeguru** [comment] 2017-09-09 12:21
i tried in npm 5.4, 5.3 and 5.2 nothing helpes me. still get sam error

![image](https://user-images.githubusercontent.com/18045792/30240094-76e76202-9587-11e7-82d0-16dbc93f6da6.png)

**Comment by Bubelbub** [comment] 2017-09-09 16:17
Yay 5.3 is working really fine <3

**Comment by fregante** [comment] 2017-09-09 16:21
@egoroof please don't ~~delete~~ your posts. Others have the same issue. Click on `Unsubscribe` if you don't want to be notified.

**Comment by ForsakenHarmony** [comment] 2017-09-09 16:47
I think he did because of the new release

**Comment by egoroof** [comment] 2017-09-09 17:10
@bfred-it sure, I'm sorry

**Comment by fregante** [comment] 2017-09-09 17:14
Thanks! :)

**Comment by ForsakenHarmony** [comment] 2017-09-09 20:53
has anyone tried `5.4.1`?

**Comment by Mardoxx** [comment] 2017-09-09 20:56
Yes, still broken.

On 9 Sep 2017 9:53 pm, "Ashley" <notifications@github.com> wrote:

has anyone tried 5.4.1?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/18380#issuecomment-328302834>, or mute
the thread

**Comment by spences10** [comment] 2017-09-10 07:07
`npm cache clean --force` worked for me 👍 

I did, first of all downgrade to npm@5.3 then I saw @mekwall's comment so tried that after deleting my `node_modules` folder then installing `npm@latest` then cleaned the cache and `npm install`'ed again.

All seems ok now:

Wondows10 Pro
`npm@5.4.1`
`node@8.4.0`

**Comment by TylerR909** [comment] 2017-09-10 08:12
I upgraded from 5.3 to 5.4.1 mid-project and literally the next command I ran to install nodemon failed. Rolled back to 5.3 and nodemon installed in a jiffy. I think babel-preset-es2016 displayed similar issues, however apparently I already had that one installed & saved.

**Comment by shapir** [comment] 2017-09-10 11:35
# downgrade npm from 5.4.1 to 5.3 has instantly solved the issue!
Indeed as previously suggested this bypassed the problem. In fact I've experienced this issue just after upgrading npm to the recent version _(btw following a notification/suggestion  from npm to do that)_

`> npm install npm@5.3 -g`

**Comment by liviuu** [comment] 2017-09-10 20:57
Had the same problem. downgrading npm solved the issue.

**Comment by ForsakenHarmony** [comment] 2017-09-10 22:25
## Please don't post new comments if you don't have anything to add
### Use 👍 on comments that helped

**Comment by gsutcliffe** [comment] 2017-09-11 17:48
Downgrading to 5.3 worked for me as well.

**Comment by durgeshrkumari** [comment] 2017-09-11 19:05
npm install -g npm@5.3

**Comment by Mardoxx** [comment] 2017-09-11 19:13
`npm install -g yarn`

**Comment by ForsakenHarmony** [comment] 2017-09-11 19:47
# Please don't post new comments if you don't have anything to add

you're not helping anyone

**Comment by Mardoxx** [comment] 2017-09-12 11:03
@ForsakenHarmony likewise!

**Comment by sydinh** [comment] 2017-09-13 02:32
@gangsthub Worked for me. Thanks 👍

**Closed as completed** 2017-11-28 03:39 UTC
