### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by johnzhu12** [npm/npm#14315] opened 2016-10-18 05:14 UTC
when I run ' npm install -g weex-toolkit ',the following error occurred.

npm ERR! shasum check failed for /var/folders/dm/bzjdbz_s1z1bby3p087g0jr00000gn/T/npm-22914-c2c23791/registry.npmjs.org/pkginfo/-/pkginfo-0.4.0.tgz
npm ERR! Expected: 349dbb7ffd38081fcadc0853df687f0c7744cd65
npm ERR! Actual:   b2465e4a4280841c3e20ea6ed2c796f4091a787f
npm ERR! From:     https://registry.npmjs.org/pkginfo/-/pkginfo-0.4.0.tgz

attached is the npm-debug.log file.
I'm going to update npm and try again. 

[npm-debug.txt](https://github.com/npm/npm/files/535316/npm-debug.txt)

**Comment by watilde** [comment] 2016-10-18 08:01
Hi! Thanks for reporting this. I think `npm cache clear` potentially can resolve this issue since it seems to be catching a wrong file in the cache.

**Comment by json1986** [comment] 2016-10-18 08:34
the same to you

**Comment by json1986** [comment] 2016-10-18 11:22
@johnzhu12 My problem has been solved.That might help you.If you are in "strong" China or other equally powerful country, you need to change npm source. example:   npm config set registry="http://registry.cnpmjs.org”

**Comment by johnzhu12** [comment] 2016-10-21 02:43
@json1986  yeah,thanks,I have downloaded it with 'cnpm' command. before  It's not working even I use VPN.so all these issues are because of the great wall's exist?

**Comment by zkat** [comment] 2016-12-02 09:23
Closing as duplicate of https://github.com/npm/npm/issues/14626. See https://github.com/npm/npm/issues/14626#issuecomment-264371634 for some helpful steps. Although it seems you figured out the firewall thing.

I can't say it's *all* the issues, but I think a good chunk of them are due to the Great Firewall, yes. I think there's other proxies, and the occasional registry hiccup, causing the others.

**Closed by zkat** 2016-12-02 09:23 UTC
Labels: network, proxy, support
