### ISSUE TITLE
getting following error while installing cordova from node js

### ISSUE THREAD

**Issue by harshadoswal** [npm/npm#9619] opened 2015-09-16 16:01 UTC
Hi Team,

I am installing cordova by following video tutorial: https://www.youtube.com/watch?v=nqFpfrUrMM4
I have successfully installed node js, while installing cordova using node js command prompt it is giving following error

![cordovaerror](https://cloud.githubusercontent.com/assets/12110162/9910314/2af72fba-5cba-11e5-8192-547fedefd81b.jpg)

**Comment by seldo** [comment] 2015-09-16 16:01
This is a duplicate of #9601; resolution in ~10 minutes.

**Closed by seldo** 2015-09-16 16:01 UTC

**Comment by harshadoswal** [comment] 2015-09-16 16:10
Hi Seldo,

After reading the #9601 ticket, I could not figure out what should be the next step. The conclusion that i can make after reading is to wait, tentatively how much time will it take ?

**Comment by seldo** [comment] 2015-09-16 16:40
It should be ready to go now :-)

**Comment by harshadoswal** [comment] 2015-09-19 16:04
Hi Seldo,

I tried installing it again and it gave following error:

![image](https://cloud.githubusercontent.com/assets/12110162/9977005/c72e79bc-5f15-11e5-8714-83adb9edb65b.png)
