### ISSUE TITLE
Serve registry via http/2?

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10767] opened 2015-12-09 20:19 UTC
Not sure if this is in place or not. 

npmjs.com and NPMO (both registry and UI) could benefit as well.

**Comment by KenanY** [comment] 2015-12-09 21:43
With regards to the registry—at least—this is not trivial. Larger discussion: https://github.com/npm/npm/issues/10380.

**Comment by kevinSuttle** [comment] 2015-12-09 21:46
WOW. I had no idea. Thanks for the heads up @KenanY. 

How about the front-ends?

**Comment by othiym23** [comment] 2015-12-16 22:53
This is indeed a duplicate of #10380, and also is something best discussed in the context of the registry, as that's where the bulk of the changes (that aren't tied to finding an HTTP/2.0 client that's pure JS and works back to Node 0.8) will need to happen. This discussion belongs either on #10380 or on `npm/public-api`, which is where we talk about cross-team API / registry issues, so I'm going to close this issue. This is definitely something I'd like to see happen, but getting there is going to be a journey of many steps, some of them quite large!

**Closed by othiym23** 2015-12-16 22:53 UTC
Labels: feature-request

**Comment by kevinSuttle** [comment] 2015-12-17 00:02
Good to know. That's helpful. Thanks again!
