### ISSUE TITLE
[NPM@5.0.2] Cannot install local dependency: error cb() never called!

### ISSUE THREAD

**Issue by Domiii** [npm/npm#16962] opened 2017-06-04 09:13 UTC
These are the relevant lines from the `debug.log`:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/6.6.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'update' ]
> 2 info using npm@5.0.2
> 3 info using node@v6.6.0
> [...]
> 795 info lifecycle react-redux-firebase@1.4.0~postpack: react-redux-firebase@1.4.0
> 796 silly lifecycle react-redux-firebase@1.4.0~postpack: no script for postpack, continuing
> 797 silly prefetch react-redux-firebase@file:local_modules/react-redux-firebase done in 612ms
> 798 error cb() never called!
> 799 error This is an error with npm itself. Please report this error at:
> 800 error <https://github.com/npm/npm/issues>

NOTE: I am on **MacOS**.

This is the line in my `package.json` (under `dependencies`):

> "react-redux-firebase": "file:local_modules/react-redux-firebase"

NOTE: `react-redux-firebase` is indeed at `1.4.0` (as defined in it's own `package.json`).

I had all kinds of issues with local NPM packages in the past, but this is definitely worse. :/

PS: Good luck with the flood of new issues guys! I'm gonna revert to a previous NPM version for now, looking forward to see NPM in all it's glory, later this year! :)

**Comment by RillingDev** [comment] 2017-06-04 10:14
Duplicate of #16904

**Comment by zkat** [comment] 2017-06-05 16:30
Closing as duplicate of https://github.com/npm/npm/issues/16904

**Closed as completed by zkat** 2017-06-05 16:30 UTC
Labels: npm5
