### ISSUE TITLE
npm@3 breaks on an optional dep breakage

### ISSUE THREAD

**Issue by mzgol** [npm/npm#9772] opened 2015-09-27 17:30 UTC
With the following `package.json`:
```json
{
  "name": "polona-gui",
  "version": "0.0.0",
  "dependencies": {
    "angular": "1.4.6",
    "angular-animate": "1.4.6",
    "angular-aria": "1.4.6",
    "angular-mocks": "1.4.6",
    "angular-resource": "1.4.6",
    "angular-sanitize": "1.4.6",
    "angulartics": "0.20.1",
    "bootstrap": "3.3.5",
    "ee-bind-attr": "0.1.3",
    "ee-l20n": "1.2.0",
    "jquery": "2.1.4",
    "jquery-wheel": "0.1.1",
    "jquery.tabbable": "1.0.1",
    "lodash": "3.10.1",
    "malakh": "0.10.0-beta.3",
    "ng-l20n": "0.2.2",
    "ng-tags-input": "3.0.0",
    "pdfjs-dist": "1.1.474",
    "typeahead.js": "0.11.1"
  },
  "devDependencies": {
    "babel-core": "5.8.25",
    "bluebird": "2.10.1",
    "browserstacktunnel-wrapper": "1.4.0",
    "check-dependencies": "0.10.3",
    "connect-modrewrite": "0.8.2",
    "ee-grunt-svgstore": "0.4.1-fork.2",
    "findup-sync": "0.3.0",
    "gitignore-to-glob": "0.1.2",
    "grunt": "0.4.5",
    "grunt-angular-templates": "0.5.7",
    "grunt-autoprefixer": "3.0.3",
    "grunt-babel": "5.0.3",
    "grunt-cli": "0.1.13",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-concat": "0.5.1",
    "grunt-contrib-connect": "0.11.2",
    "grunt-contrib-copy": "0.8.1",
    "grunt-contrib-cssmin": "0.14.0",
    "grunt-contrib-htmlmin": "0.5.0",
    "grunt-contrib-sass": "0.9.2",
    "grunt-contrib-uglify": "0.9.2",
    "grunt-contrib-watch": "0.6.1",
    "grunt-ddescribe-iit": "0.0.6",
    "grunt-eslint": "17.2.0",
    "grunt-file-exists": "0.1.3",
    "grunt-filerev": "2.3.1",
    "grunt-fontello": "0.1.3",
    "grunt-githooks": "0.3.1",
    "grunt-include-source": "0.7.0",
    "grunt-jsonlint": "1.0.4",
    "grunt-karma": "0.12.1",
    "grunt-merge-conflict": "0.0.2",
    "grunt-newer": "1.1.1",
    "grunt-ng-annotate": "1.0.1",
    "grunt-npmcopy": "0.1.0",
    "grunt-shell": "1.1.2",
    "grunt-usemin": "3.1.1",
    "image-size": "0.3.5",
    "isbinaryfile": "3.0.0",
    "jasmine-core": "2.3.4",
    "jit-grunt": "0.9.1",
    "json5": "0.4.0",
    "karma": "0.13.10",
    "karma-browserstack-launcher": "0.1.5",
    "karma-jasmine": "0.3.6",
    "karma-junit-reporter": "0.3.4",
    "karma-ng-json2js-preprocessor": "1.1.1",
    "l20n": "1.0.2",
    "mime": "1.3.4",
    "protractor": "2.2.0",
    "semver": "5.0.3",
    "serve-static": "1.10.0",
    "time-grunt": "1.2.1"
  },
  "optionalDependencies": {
    "grunt-contrib-imagemin": "0.9.4",
    "grunt-inline-images": "0.2.3",
    "grunt-notify": "0.4.1",
    "karma-chrome-launcher": "0.2.0",
    "karma-coverage": "0.5.2",
    "karma-firefox-launcher": "0.1.6",
    "karma-safari-launcher": "0.1.1",
    "karma-sauce-launcher": "0.2.14"
  }
}
```
in Node 4.1.1 `bufferutil@1.1.0` installation fails making the whole install fail. This works fine in npm@2 since `bufferutil` is an optional dependency.

1. `npm install` output: https://gist.github.com/mzgol/dbbdd1adb30a369a2e29
2. `npm-debug.log`: https://gist.github.com/mzgol/fe3ec1294694cec26975

**Comment by iarna** [comment] 2015-10-08 23:13
Closing as a duplicate of #9643 (which has a fix landing later today)

**Closed by iarna** 2015-10-08 23:13 UTC
